Cantera: VPStandardStateTP Class Reference
VPStandardStateTP Class Reference
Models of Phases of Matter » Thermodynamic Properties
This is a filter class for ThermoPhase that implements some preparatory steps for efficiently handling a variable pressure standard state for species.
#include <VPStandardStateTP.h>
Public Member Functions
Constructors and Duplicators for VPStandardStateTP
VPStandardStateTP ()
Constructor.
virtual bool isCompressible () const
Return whether phase represents a compressible substance.
Utilities (VPStandardStateTP)
virtual int standardStateConvention () const
This method returns the convention used in specification of the standard state, of which there are currently two, temperature based, and variable pressure based.
virtual void getdlnActCoeffdlnN_diag (doublereal *dlnActCoeffdlnN_diag) const
Get the array of log species mole number derivatives of the log activity coefficients.
Partial Molar Properties of the Solution (VPStandardStateTP)
virtual void getChemPotentials_RT (doublereal *mu) const
Get the array of non-dimensional species chemical potentials.
Public Member Functions inherited from ThermoPhase
ThermoPhase ()
Constructor.
virtual std::string type () const
String indicating the thermodynamic model implemented.
virtual std::string phaseOfMatter () const
String indicating the mechanical phase of the matter in this Phase.
virtual doublereal refPressure () const
Returns the reference pressure in Pa.
doublereal Hf298SS (const size_t k) const
Report the 298 K Heat of Formation of the standard state of one species (J kmol-1)
virtual void modifyOneHf298SS (const size_t k, const doublereal Hf298New)
Modify the value of the 298 K Heat of Formation of one species in the phase (J kmol-1)
virtual void resetHf298 (const size_t k=npos)
Restore the original heat of formation of one or more species.
bool chargeNeutralityNecessary () const
Returns the chargeNeutralityNecessity boolean.
virtual doublereal enthalpy_mole () const
Molar enthalpy. Units: J/kmol.
virtual doublereal intEnergy_mole () const
Molar internal energy. Units: J/kmol.
virtual doublereal entropy_mole () const
Molar entropy. Units: J/kmol/K.
virtual doublereal gibbs_mole () const
Molar Gibbs function. Units: J/kmol.
virtual doublereal cp_mole () const
Molar heat capacity at constant pressure. Units: J/kmol/K.
virtual doublereal cv_mole () const
Molar heat capacity at constant volume. Units: J/kmol/K.
virtual doublereal isothermalCompressibility () const
Returns the isothermal compressibility. Units: 1/Pa.
virtual doublereal thermalExpansionCoeff () const
Return the volumetric thermal expansion coefficient. Units: 1/K.
void setElectricPotential (doublereal v)
Set the electric potential of this phase (V).
doublereal electricPotential () const
Returns the electric potential of this phase (V).
virtual int activityConvention () const
This method returns the convention used in specification of the activities, of which there are currently two, molar- and molality-based conventions.
virtual Units standardConcentrationUnits () const
Returns the units of the "standard concentration" for this phase.
virtual void getActivityConcentrations (doublereal *c) const
This method returns an array of generalized concentrations.
virtual doublereal standardConcentration (size_t k=0) const
Return the standard concentration for the kth species.
virtual doublereal logStandardConc (size_t k=0) const
Natural logarithm of the standard concentration of the kth species.
virtual void getActivities (doublereal *a) const
Get the array of non-dimensional activities at the current solution temperature, pressure, and solution concentration.
virtual void getActivityCoefficients (doublereal *ac) const
Get the array of non-dimensional molar-based activity coefficients at the current solution temperature, pressure, and solution concentration.
virtual void getLnActivityCoefficients (doublereal *lnac) const
Get the array of non-dimensional molar-based ln activity coefficients at the current solution temperature, pressure, and solution concentration.
virtual void getChemPotentials (doublereal *mu) const
Get the species chemical potentials. Units: J/kmol.
void getElectrochemPotentials (doublereal *mu) const
Get the species electrochemical potentials.
virtual void getPartialMolarEnthalpies (doublereal *hbar) const
Returns an array of partial molar enthalpies for the species in the mixture.
virtual void getPartialMolarEntropies (doublereal *sbar) const
Returns an array of partial molar entropies of the species in the solution.
virtual void getPartialMolarIntEnergies (doublereal *ubar) const
Return an array of partial molar internal energies for the species in the mixture.
virtual void getPartialMolarCp (doublereal *cpbar) const
Return an array of partial molar heat capacities for the species in the mixture.
virtual void getPartialMolarVolumes (doublereal *vbar) const
Return an array of partial molar volumes for the species in the mixture.
virtual void getIntEnergy_RT_ref (doublereal *urt) const
Returns the vector of nondimensional internal Energies of the reference state at the current temperature of the solution and the reference pressure for each species.
doublereal enthalpy_mass () const
Specific enthalpy. Units: J/kg.
doublereal intEnergy_mass () const
Specific internal energy. Units: J/kg.
doublereal entropy_mass () const
Specific entropy. Units: J/kg/K.
doublereal gibbs_mass () const
Specific Gibbs function. Units: J/kg.
doublereal cp_mass () const
Specific heat at constant pressure. Units: J/kg/K.
doublereal cv_mass () const
Specific heat at constant volume. Units: J/kg/K.
doublereal RT () const
Return the Gas Constant multiplied by the current temperature.
virtual void setState_TPX (doublereal t, doublereal p, const doublereal *x)
Set the temperature (K), pressure (Pa), and mole fractions.
virtual void setState_TPX (doublereal t, doublereal p, const compositionMap &x)
Set the temperature (K), pressure (Pa), and mole fractions.
virtual void setState_TPX (doublereal t, doublereal p, const std::string &x)
Set the temperature (K), pressure (Pa), and mole fractions.
virtual void setState_TPY (doublereal t, doublereal p, const doublereal *y)
Set the internally stored temperature (K), pressure (Pa), and mass fractions of the phase.
virtual void setState_TPY (doublereal t, doublereal p, const compositionMap &y)
Set the internally stored temperature (K), pressure (Pa), and mass fractions of the phase.
virtual void setState_TPY (doublereal t, doublereal p, const std::string &y)
Set the internally stored temperature (K), pressure (Pa), and mass fractions of the phase.
virtual void setState_PX (doublereal p, doublereal *x)
Set the pressure (Pa) and mole fractions.
virtual void setState_PY (doublereal p, doublereal *y)
Set the internally stored pressure (Pa) and mass fractions.
virtual void setState_HP (double h, double p, double tol=1e-9)
Set the internally stored specific enthalpy (J/kg) and pressure (Pa) of the phase.
virtual void setState_UV (double u, double v, double tol=1e-9)
Set the specific internal energy (J/kg) and specific volume (m^3/kg).
virtual void setState_SP (double s, double p, double tol=1e-9)
Set the specific entropy (J/kg/K) and pressure (Pa).
virtual void setState_SV (double s, double v, double tol=1e-9)
Set the specific entropy (J/kg/K) and specific volume (m^3/kg).
virtual void setState_ST (double s, double t, double tol=1e-9)
Set the specific entropy (J/kg/K) and temperature (K).
virtual void setState_TV (double t, double v, double tol=1e-9)
Set the temperature (K) and specific volume (m^3/kg).
virtual void setState_PV (double p, double v, double tol=1e-9)
Set the pressure (Pa) and specific volume (m^3/kg).
virtual void setState_UP (double u, double p, double tol=1e-9)
Set the specific internal energy (J/kg) and pressure (Pa).
virtual void setState_VH (double v, double h, double tol=1e-9)
Set the specific volume (m^3/kg) and the specific enthalpy (J/kg)
virtual void setState_TH (double t, double h, double tol=1e-9)
Set the temperature (K) and the specific enthalpy (J/kg)
virtual void setState_SH (double s, double h, double tol=1e-9)
Set the specific entropy (J/kg/K) and the specific enthalpy (J/kg)
virtual void setState_RP (doublereal rho, doublereal p)
Set the density (kg/m**3) and pressure (Pa) at constant composition.
virtual void setState_RPX (doublereal rho, doublereal p, const doublereal *x)
Set the density (kg/m**3), pressure (Pa) and mole fractions.
virtual void setState_RPX (doublereal rho, doublereal p, const compositionMap &x)
Set the density (kg/m**3), pressure (Pa) and mole fractions.
virtual void setState_RPX (doublereal rho, doublereal p, const std::string &x)
Set the density (kg/m**3), pressure (Pa) and mole fractions.
virtual void setState_RPY (doublereal rho, doublereal p, const doublereal *y)
Set the density (kg/m**3), pressure (Pa) and mass fractions.
virtual void setState_RPY (doublereal rho, doublereal p, const compositionMap &y)
Set the density (kg/m**3), pressure (Pa) and mass fractions.
virtual void setState_RPY (doublereal rho, doublereal p, const std::string &y)
Set the density (kg/m**3), pressure (Pa) and mass fractions.
virtual void setState (const AnyMap &state)
Set the state using an AnyMap containing any combination of properties supported by the thermodynamic model.
void setMixtureFraction (double mixFrac, const double *fuelComp, const double *oxComp, ThermoBasis basis=ThermoBasis::molar)
Set the mixture composition according to the mixture fraction = kg fuel / (kg oxidizer + kg fuel)
void setMixtureFraction (double mixFrac, const std::string &fuelComp, const std::string &oxComp, ThermoBasis basis=ThermoBasis::molar)
Set the mixture composition according to the mixture fraction = kg fuel / (kg oxidizer + kg fuel)
void setMixtureFraction (double mixFrac, const compositionMap &fuelComp, const compositionMap &oxComp, ThermoBasis basis=ThermoBasis::molar)
Set the mixture composition according to the mixture fraction = kg fuel / (kg oxidizer + kg fuel)
double mixtureFraction (const double *fuelComp, const double *oxComp, ThermoBasis basis=ThermoBasis::molar, const std::string &element="Bilger") const
Compute the mixture fraction = kg fuel / (kg oxidizer + kg fuel) for the current mixture given fuel and oxidizer compositions.
double mixtureFraction (const std::string &fuelComp, const std::string &oxComp, ThermoBasis basis=ThermoBasis::molar, const std::string &element="Bilger") const
Compute the mixture fraction = kg fuel / (kg oxidizer + kg fuel) for the current mixture given fuel and oxidizer compositions.
double mixtureFraction (const compositionMap &fuelComp, const compositionMap &oxComp, ThermoBasis basis=ThermoBasis::molar, const std::string &element="Bilger") const
Compute the mixture fraction = kg fuel / (kg oxidizer + kg fuel) for the current mixture given fuel and oxidizer compositions.
void setEquivalenceRatio (double phi, const double *fuelComp, const double *oxComp, ThermoBasis basis=ThermoBasis::molar)
Set the mixture composition according to the equivalence ratio.
void setEquivalenceRatio (double phi, const std::string &fuelComp, const std::string &oxComp, ThermoBasis basis=ThermoBasis::molar)
Set the mixture composition according to the equivalence ratio.
void setEquivalenceRatio (double phi, const compositionMap &fuelComp, const compositionMap &oxComp, ThermoBasis basis=ThermoBasis::molar)
Set the mixture composition according to the equivalence ratio.
double equivalenceRatio (const double *fuelComp, const double *oxComp, ThermoBasis basis=ThermoBasis::molar) const
Compute the equivalence ratio for the current mixture given the compositions of fuel and oxidizer.
double equivalenceRatio (const std::string &fuelComp, const std::string &oxComp, ThermoBasis basis=ThermoBasis::molar) const
Compute the equivalence ratio for the current mixture given the compositions of fuel and oxidizer.
double equivalenceRatio (const compositionMap &fuelComp, const compositionMap &oxComp, ThermoBasis basis=ThermoBasis::molar) const
Compute the equivalence ratio for the current mixture given the compositions of fuel and oxidizer.
double equivalenceRatio () const
Compute the equivalence ratio for the current mixture from available oxygen and required oxygen.
void equilibrate (const std::string &XY, const std::string &solver="auto", double rtol=1e-9, int max_steps=50000, int max_iter=100, int estimate_equil=0, int log_level=0)
Equilibrate a ThermoPhase object.
virtual void setToEquilState (const doublereal *mu_RT)
This method is used by the ChemEquil equilibrium solver.
virtual bool compatibleWithMultiPhase () const
Indicates whether this phase type can be used with class MultiPhase for equilibrium calculations.
virtual doublereal critTemperature () const
Critical temperature (K).
virtual doublereal critPressure () const
Critical pressure (Pa).
virtual doublereal critVolume () const
Critical volume (m3/kmol).
virtual doublereal critCompressibility () const
Critical compressibility (unitless).
virtual doublereal critDensity () const
Critical density (kg/m3).
virtual doublereal satTemperature (doublereal p) const
Return the saturation temperature given the pressure.
virtual doublereal satPressure (doublereal t)
Return the saturation pressure given the temperature.
virtual doublereal vaporFraction () const
Return the fraction of vapor at the current conditions.
virtual void setState_Tsat (doublereal t, doublereal x)
Set the state to a saturated system at a particular temperature.
virtual void setState_Psat (doublereal p, doublereal x)
Set the state to a saturated system at a particular pressure.
void setState_TPQ (double T, double P, double Q)
Set the temperature, pressure, and vapor fraction (quality).
virtual void modifySpecies (size_t k, shared_ptr< Species > spec)
Modify the thermodynamic data associated with a species.
void saveSpeciesData (const size_t k, const XML_Node *const data)
Store a reference pointer to the XML tree containing the species data for this phase.
const std::vector< const XML_Node * > & speciesData () const
Return a pointer to the vector of XML nodes containing the species data for this phase.
virtual MultiSpeciesThermo & speciesThermo (int k=-1)
Return a changeable reference to the calculation manager for species reference-state thermodynamic properties.
virtual const MultiSpeciesThermo & speciesThermo (int k=-1) const
virtual void initThermoFile (const std::string &inputFile, const std::string &id)
virtual void initThermoXML (XML_Node &phaseNode, const std::string &id)
Import and initialize a ThermoPhase object using an XML tree.
virtual void setParameters (int n, doublereal *const c)
Set the equation of state parameters.
virtual void getParameters (int &n, doublereal *const c) const
Get the equation of state parameters in a vector.
virtual void setParameters (const AnyMap &phaseNode, const AnyMap &rootNode=AnyMap())
Set equation of state parameters from an AnyMap phase description.
const AnyMap & input () const
Access input data associated with the phase description.
AnyMap & input ()
virtual void setParametersFromXML (const XML_Node &eosdata)
Set equation of state parameter values from XML entries.
virtual void setStateFromXML (const XML_Node &state)
Set the initial state of the phase to the conditions specified in the state XML element.
virtual void getdlnActCoeffds (const doublereal dTds, const doublereal *const dXds, doublereal *dlnActCoeffds) const
Get the change in activity coefficients wrt changes in state (temp, mole fraction, etc) along a line in parameter space or along a line in physical space.
virtual void getdlnActCoeffdlnX_diag (doublereal *dlnActCoeffdlnX_diag) const
Get the array of ln mole fraction derivatives of the log activity coefficients - diagonal component only.
virtual void getdlnActCoeffdlnN (const size_t ld, doublereal *const dlnActCoeffdlnN)
Get the array of derivatives of the log activity coefficients with respect to the log of the species mole numbers.
virtual void getdlnActCoeffdlnN_numderiv (const size_t ld, doublereal *const dlnActCoeffdlnN)
virtual std::string report (bool show_thermo=true, doublereal threshold=-1e-14) const
returns a summary of the state of the phase as a string
virtual void reportCSV (std::ofstream &csvFile) const
returns a summary of the state of the phase to a comma separated file.
double stoichAirFuelRatio (const double *fuelComp, const double *oxComp, ThermoBasis basis=ThermoBasis::molar) const
Compute the stoichiometric air to fuel ratio (kg oxidizer / kg fuel) given fuel and oxidizer compositions.
double stoichAirFuelRatio (const std::string &fuelComp, const std::string &oxComp, ThermoBasis basis=ThermoBasis::molar) const
Compute the stoichiometric air to fuel ratio (kg oxidizer / kg fuel) given fuel and oxidizer compositions.
double stoichAirFuelRatio (const compositionMap &fuelComp, const compositionMap &oxComp, ThermoBasis basis=ThermoBasis::molar) const
Compute the stoichiometric air to fuel ratio (kg oxidizer / kg fuel) given fuel and oxidizer compositions.
Public Member Functions inherited from Phase
Phase ()
Default constructor.
Phase (const Phase &)=delete
Phase & operator= (const Phase &)=delete
XML_Node & xml () const
Returns a const reference to the XML_Node that describes the phase.
void setXMLdata (XML_Node &xmlPhase)
Stores the XML tree information for the current phase.
virtual bool isPure () const
Return whether phase represents a pure (single species) substance.
virtual bool hasPhaseTransition () const
Return whether phase represents a substance with phase transitions.
virtual std::map< std::string, size_t > nativeState () const
Return a map of properties defining the native state of a substance.
virtual std::vector< std::string > fullStates () const
Return a vector containing full states defining a phase.
virtual std::vector< std::string > partialStates () const
Return a vector of settable partial property sets within a phase.
virtual size_t stateSize () const
Return size of vector defining internal state of the phase.
void saveState (vector_fp &state) const
Save the current internal state of the phase.
virtual void saveState (size_t lenstate, doublereal *state) const
Write to array 'state' the current internal state.
void restoreState (const vector_fp &state)
Restore a state saved on a previous call to saveState.
virtual void restoreState (size_t lenstate, const doublereal *state)
Restore the state of the phase from a previously saved state vector.
doublereal molecularWeight (size_t k) const
Molecular weight of species k.
void getMolecularWeights (vector_fp &weights) const
Copy the vector of molecular weights into vector weights.
void getMolecularWeights (doublereal *weights) const
Copy the vector of molecular weights into array weights.
const vector_fp & molecularWeights () const
Return a const reference to the internal vector of molecular weights.
void getCharges (double *charges) const
Copy the vector of species charges into array charges.
virtual bool ready () const
Returns a bool indicating whether the object is ready for use.
int stateMFNumber () const
Return the State Mole Fraction Number.
bool caseSensitiveSpecies () const
Returns true if case sensitive species names are enforced.
void setCaseSensitiveSpecies (bool cflag=true)
Set flag that determines whether case sensitive species are enforced in look-up operations, e.g.
virtual void setRoot (std::shared_ptr< Solution > root)
Set root Solution holding all phase information.
vector_fp getCompositionFromMap (const compositionMap &comp) const
Converts a compositionMap to a vector with entries for each species Species that are not specified are set to zero in the vector.
void massFractionsToMoleFractions (const double *Y, double *X) const
Converts a mixture composition from mole fractions to mass fractions.
void moleFractionsToMassFractions (const double *X, double *Y) const
Converts a mixture composition from mass fractions to mole fractions.
std::string id () const
Return the string id for the phase.
void setID (const std::string &id)
Set the string id for the phase.
std::string name () const
Return the name of the phase.
void setName (const std::string &nm)
Sets the string name for the phase.
std::string elementName (size_t m) const
Name of the element with index m.
size_t elementIndex (const std::string &name) const
Return the index of element named 'name'.
const std::vector< std::string > & elementNames () const
Return a read-only reference to the vector of element names.
doublereal atomicWeight (size_t m) const
Atomic weight of element m.
doublereal entropyElement298 (size_t m) const
Entropy of the element in its standard state at 298 K and 1 bar.
int atomicNumber (size_t m) const
Atomic number of element m.
int elementType (size_t m) const
Return the element constraint type Possible types include:
int changeElementType (int m, int elem_type)
Change the element type of the mth constraint Reassigns an element type.
const vector_fp & atomicWeights () const
Return a read-only reference to the vector of atomic weights.
size_t nElements () const
Number of elements.
void checkElementIndex (size_t m) const
Check that the specified element index is in range.
void checkElementArraySize (size_t mm) const
Check that an array size is at least nElements().
doublereal nAtoms (size_t k, size_t m) const
Number of atoms of element m in species k.
void getAtoms (size_t k, double *atomArray) const
Get a vector containing the atomic composition of species k.
size_t speciesIndex (const std::string &name) const
Returns the index of a species named 'name' within the Phase object.
std::string speciesName (size_t k) const
Name of the species with index k.
std::string speciesSPName (int k) const
Returns the expanded species name of a species, including the phase name This is guaranteed to be unique within a Cantera problem.
const std::vector< std::string > & speciesNames () const
Return a const reference to the vector of species names.
size_t nSpecies () const
Returns the number of species in the phase.
void checkSpeciesIndex (size_t k) const
Check that the specified species index is in range.
void checkSpeciesArraySize (size_t kk) const
Check that an array size is at least nSpecies().
void setMoleFractionsByName (const compositionMap &xMap)
Set the species mole fractions by name.
void setMoleFractionsByName (const std::string &x)
Set the mole fractions of a group of species by name.
void setMassFractionsByName (const compositionMap &yMap)
Set the species mass fractions by name.
void setMassFractionsByName (const std::string &x)
Set the species mass fractions by name.
void setState_TRX (doublereal t, doublereal dens, const doublereal *x)
Set the internally stored temperature (K), density, and mole fractions.
void setState_TRX (doublereal t, doublereal dens, const compositionMap &x)
Set the internally stored temperature (K), density, and mole fractions.
void setState_TRY (doublereal t, doublereal dens, const doublereal *y)
Set the internally stored temperature (K), density, and mass fractions.
void setState_TRY (doublereal t, doublereal dens, const compositionMap &y)
Set the internally stored temperature (K), density, and mass fractions.
void setState_TNX (doublereal t, doublereal n, const doublereal *x)
Set the internally stored temperature (K), molar density (kmol/m^3), and mole fractions.
void setState_TR (doublereal t, doublereal rho)
Set the internally stored temperature (K) and density (kg/m^3)
void setState_TX (doublereal t, doublereal *x)
Set the internally stored temperature (K) and mole fractions.
void setState_TY (doublereal t, doublereal *y)
Set the internally stored temperature (K) and mass fractions.
void setState_RX (doublereal rho, doublereal *x)
Set the density (kg/m^3) and mole fractions.
void setState_RY (doublereal rho, doublereal *y)
Set the density (kg/m^3) and mass fractions.
compositionMap getMoleFractionsByName (double threshold=0.0) const
Get the mole fractions by name.
double moleFraction (size_t k) const
Return the mole fraction of a single species.
double moleFraction (const std::string &name) const
Return the mole fraction of a single species.
compositionMap getMassFractionsByName (double threshold=0.0) const
Get the mass fractions by name.
double massFraction (size_t k) const
Return the mass fraction of a single species.
double massFraction (const std::string &name) const
Return the mass fraction of a single species.
void getMoleFractions (double *const x) const
Get the species mole fraction vector.
virtual void setMoleFractions (const double *const x)
Set the mole fractions to the specified values.
virtual void setMoleFractions_NoNorm (const double *const x)
Set the mole fractions to the specified values without normalizing.
void getMassFractions (double *const y) const
Get the species mass fractions.
const double * massFractions () const
Return a const pointer to the mass fraction array.
virtual void setMassFractions (const double *const y)
Set the mass fractions to the specified values and normalize them.
virtual void setMassFractions_NoNorm (const double *const y)
Set the mass fractions to the specified values without normalizing.
void getConcentrations (double *const c) const
Get the species concentrations (kmol/m^3).
double concentration (const size_t k) const
Concentration of species k.
virtual void setConcentrations (const double *const conc)
Set the concentrations to the specified values within the phase.
virtual void setConcentrationsNoNorm (const double *const conc)
Set the concentrations without ignoring negative concentrations.
doublereal elementalMassFraction (const size_t m) const
Elemental mass fraction of element m.
doublereal elementalMoleFraction (const size_t m) const
Elemental mole fraction of element m.
const double * moleFractdivMMW () const
Returns a const pointer to the start of the moleFraction/MW array.
doublereal charge (size_t k) const
Dimensionless electrical charge of a single molecule of species k The charge is normalized by the the magnitude of the electron charge.
doublereal chargeDensity () const
Charge density [C/m^3].
size_t nDim () const
Returns the number of spatial dimensions (1, 2, or 3)
void setNDim (size_t ndim)
Set the number of spatial dimensions (1, 2, or 3).
doublereal temperature () const
Temperature (K).
virtual double density () const
Density (kg/m^3).
double molarDensity () const
Molar density (kmol/m^3).
double molarVolume () const
Molar volume (m^3/kmol).
virtual void setDensity (const double density_)
Set the internally stored density (kg/m^3) of the phase.
virtual void setMolarDensity (const double molarDensity)
Set the internally stored molar density (kmol/m^3) of the phase.
doublereal mean_X (const doublereal *const Q) const
Evaluate the mole-fraction-weighted mean of an array Q.
doublereal mean_X (const vector_fp &Q) const
Evaluate the mole-fraction-weighted mean of an array Q.
doublereal meanMolecularWeight () const
The mean molecular weight. Units: (kg/kmol)
doublereal sum_xlogx () const
Evaluate \(\sum_k X_k \log X_k \).
size_t addElement (const std::string &symbol, doublereal weight=-12345.0, int atomicNumber=0, doublereal entropy298=ENTROPY298_UNKNOWN, int elem_type=CT_ELEM_TYPE_ABSPOS)
Add an element.
void addSpeciesAlias (const std::string &name, const std::string &alias)
Add a species alias (i.e.
virtual std::vector< std::string > findIsomers (const compositionMap &compMap) const
Return a vector with isomers names matching a given composition map.
virtual std::vector< std::string > findIsomers (const std::string &comp) const
Return a vector with isomers names matching a given composition string.
shared_ptr< Species > species (const std::string &name) const
Return the Species object for the named species.
shared_ptr< Species > species (size_t k) const
Return the Species object for species whose index is k.
void ignoreUndefinedElements ()
Set behavior when adding a species containing undefined elements to just skip the species.
void addUndefinedElements ()
Set behavior when adding a species containing undefined elements to add those elements to the phase.
void throwUndefinedElements ()
Set the behavior when adding a species containing undefined elements to throw an exception.
Initialization Methods - For Internal use
doublereal m_Pcurrent
Current value of the pressure - state variable.
double m_minTemp
The minimum temperature at which data for all species is valid.
double m_maxTemp
The maximum temperature at which data for all species is valid.
doublereal m_Tlast_ss
The last temperature at which the standard state thermodynamic properties were calculated at.
doublereal m_Plast_ss
The last pressure at which the Standard State thermodynamic properties were calculated at.
std::vector< std::unique_ptr< PDSS > > m_PDSS_storage
Storage for the PDSS objects for the species.
vector_fp m_h0_RT
Vector containing the species reference enthalpies at T = m_tlast and P = p_ref.
vector_fp m_cp0_R
Vector containing the species reference constant pressure heat capacities at T = m_tlast and P = p_ref.
vector_fp m_g0_RT
Vector containing the species reference Gibbs functions at T = m_tlast and P = p_ref.
vector_fp m_s0_R
Vector containing the species reference entropies at T = m_tlast and P = p_ref.
vector_fp m_V0
Vector containing the species reference molar volumes.
vector_fp m_hss_RT
Vector containing the species Standard State enthalpies at T = m_tlast and P = m_plast.
vector_fp m_cpss_R
Vector containing the species Standard State constant pressure heat capacities at T = m_tlast and P = m_plast.
vector_fp m_gss_RT
Vector containing the species Standard State Gibbs functions at T = m_tlast and P = m_plast.
vector_fp m_sss_R
Vector containing the species Standard State entropies at T = m_tlast and P = m_plast.
vector_fp m_Vss
Vector containing the species standard state volumes at T = m_tlast and P = m_plast.
virtual void initThermo ()
virtual bool addSpecies (shared_ptr< Species > spec)
void installPDSS (size_t k, std::unique_ptr< PDSS > &&pdss)
Install a PDSS object for species k
PDSS * providePDSS (size_t k)
const PDSS * providePDSS (size_t k) const
virtual bool addSpecies (shared_ptr< Species > spec)
Add a Species to this Phase.
virtual void invalidateCache ()
Invalidate any cached values which are normally updated only when a change in state is detected.
Properties of the Standard State of the Species in the Solution
Within VPStandardStateTP, these properties are calculated via a common routine, _updateStandardStateThermo(), which must be overloaded in inherited objects. The values are cached within this object, and are not recalculated unless the temperature or pressure changes.
virtual void getStandardChemPotentials (doublereal *mu) const
Get the array of chemical potentials at unit activity for the species at their standard states at the current T and P of the solution.
virtual void getEnthalpy_RT (doublereal *hrt) const
Get the nondimensional Enthalpy functions for the species at their standard states at the current T and P of the solution.
virtual void getEntropy_R (doublereal *sr) const
Get the array of nondimensional Entropy functions for the standard state species at the current T and P of the solution.
virtual void getGibbs_RT (doublereal *grt) const
Get the nondimensional Gibbs functions for the species in their standard states at the current T and P of the solution.
virtual void getPureGibbs (doublereal *gpure) const
Get the Gibbs functions for the standard state of the species at the current T and P of the solution.
virtual void getIntEnergy_RT (doublereal *urt) const
Returns the vector of nondimensional Internal Energies of the standard state species at the current T and P of the solution.
virtual void getCp_R (doublereal *cpr) const
Get the nondimensional Heat Capacities at constant pressure for the species standard states at the current T and P of the solution.
virtual void getStandardVolumes (doublereal *vol) const
Get the molar volumes of the species standard states at the current T and P of the solution.
virtual const vector_fp & getStandardVolumes () const
virtual void setTemperature (const doublereal temp)
Set the temperature of the phase.
virtual void setPressure (doublereal p)
Set the internally stored pressure (Pa) at constant temperature and composition.
virtual void setState_TP (doublereal T, doublereal pres)
Set the temperature and pressure at the same time.
virtual doublereal pressure () const
Returns the current pressure of the phase.
virtual void updateStandardStateThermo () const
Updates the standard state thermodynamic functions at the current T and P of the solution.
virtual double minTemp (size_t k=npos) const
Minimum temperature for which the thermodynamic data for the species or phase are valid.
virtual double maxTemp (size_t k=npos) const
Maximum temperature for which the thermodynamic data for the species are valid.
virtual void calcDensity ()
Calculate the density of the mixture using the partial molar volumes and mole fractions as input.
virtual void _updateStandardStateThermo () const
Updates the standard state thermodynamic functions at the current T and P of the solution.
Thermodynamic Values for the Species Reference States
virtual void getEnthalpy_RT_ref (doublereal *hrt) const
virtual void getGibbs_RT_ref (doublereal *grt) const
Returns the vector of nondimensional Gibbs Free Energies of the reference state at the current temperature of the solution and the reference pressure for the species.
virtual void getGibbs_ref (doublereal *g) const
Returns the vector of the Gibbs function of the reference state at the current temperature of the solution and the reference pressure for the species.
virtual void getEntropy_R_ref (doublereal *er) const
Returns the vector of nondimensional entropies of the reference state at the current temperature of the solution and the reference pressure for each species.
virtual void getCp_R_ref (doublereal *cprt) const
Returns the vector of nondimensional constant pressure heat capacities of the reference state at the current temperature of the solution and reference pressure for each species.
virtual void getStandardVolumes_ref (doublereal *vol) const
Get the molar volumes of the species reference states at the current T and P_ref of the solution.
const vector_fp & Gibbs_RT_ref () const
Additional Inherited Members
Protected Member Functions inherited from ThermoPhase
virtual void getCsvReportData (std::vector< std::string > &names, std::vector< vector_fp > &data) const
Fills names and data with the column names and species thermo properties to be included in the output of the reportCSV method.
Protected Member Functions inherited from Phase
void assertCompressible (const std::string &setter) const
Ensure that phase is compressible.
void assignDensity (const double density_)
Set the internally stored constant density (kg/m^3) of the phase.
void setMolecularWeight (const int k, const double mw)
Set the molecular weight of a single species to a given value.
virtual void compositionChanged ()
Apply changes to the state which are needed after the composition changes.
Protected Attributes inherited from ThermoPhase
MultiSpeciesThermo m_spthermo
Pointer to the calculation manager for species reference-state thermodynamic properties.
AnyMap m_input
Data supplied via setParameters.
std::vector< const XML_Node * > m_speciesData
Vector of pointers to the species databases.
doublereal m_phi
Stored value of the electric potential for this phase. Units are Volts.
bool m_chargeNeutralityNecessary
Boolean indicating whether a charge neutrality condition is a necessity.
int m_ssConvention
Contains the standard state convention.
doublereal m_tlast
last value of the temperature processed by reference state
Protected Attributes inherited from Phase
ValueCache m_cache
Cached for saved calculations within each ThermoPhase.
size_t m_kk
Number of species in the phase.
size_t m_ndim
Dimensionality of the phase.
vector_fp m_speciesComp
Atomic composition of the species.
vector_fp m_speciesCharge
Vector of species charges. length m_kk.
std::map< std::string, shared_ptr< Species > > m_species
UndefElement::behavior m_undefinedElementBehavior
Flag determining behavior when adding species with an undefined element.
bool m_caseSensitiveSpecies
Flag determining whether case sensitive species names are enforced.
Detailed Description
This is a filter class for ThermoPhase that implements some preparatory steps for efficiently handling a variable pressure standard state for species.
Several concepts are introduced. The first concept is there are temporary variables for holding the species standard state values of Cp, H, S, G, and V at the last temperature and pressure called. These functions are not recalculated if a new call is made using the previous temperature and pressure.
To support the above functionality, pressure and temperature variables, m_Plast_ss and m_Tlast_ss, are kept which store the last pressure and temperature used in the evaluation of standard state properties.
This class is usually used for nearly incompressible phases. For those phases, it makes sense to change the equation of state independent variable from density to pressure. The variable m_Pcurrent contains the current value of the pressure within the phase.
Definition at line 41 of file VPStandardStateTP.h.
Constructor & Destructor Documentation
VPStandardStateTP()
VPStandardStateTP ()
Constructor.
Definition at line 26 of file VPStandardStateTP.cpp.
Member Function Documentation
isCompressible()
virtual bool isCompressible () const inline virtual
Return whether phase represents a compressible substance.
Reimplemented from Phase.
Definition at line 51 of file VPStandardStateTP.h.
standardStateConvention()
int standardStateConvention () const virtual
This method returns the convention used in specification of the standard state, of which there are currently two, temperature based, and variable pressure based.
Currently, there are two standard state conventions:
Temperature-based activities cSS_CONVENTION_TEMPERATURE 0
default
Variable Pressure and Temperature -based activities cSS_CONVENTION_VPSS 1
Thermodynamics is set via slave ThermoPhase objects with nothing being carried out at this ThermoPhase object level cSS_CONVENTION_SLAVE 2
Reimplemented from ThermoPhase.
Definition at line 35 of file VPStandardStateTP.cpp.
References Cantera::cSS_CONVENTION_VPSS.
getdlnActCoeffdlnN_diag()
virtual void getdlnActCoeffdlnN_diag (doublereal * dlnActCoeffdlnN_diag) const inline virtual
Get the array of log species mole number derivatives of the log activity coefficients.
For ideal mixtures (unity activity coefficients), this can return zero. Implementations should take the derivative of the logarithm of the activity coefficient with respect to the logarithm of the concentration- like variable (i.e. moles) that represents the standard state. This quantity is to be used in conjunction with derivatives of that species mole number variable when the derivative of the chemical potential is taken.
units = dimensionless
Parameters
dlnActCoeffdlnN_diag Output vector of derivatives of the log Activity Coefficients. length = m_kk
Reimplemented from ThermoPhase.
Reimplemented in RedlichKisterVPSSTP, MargulesVPSSTP, and IonsFromNeutralVPSSTP.
Definition at line 60 of file VPStandardStateTP.h.
Referenced by IonsFromNeutralVPSSTP::s_update_dlnActCoeff_dlnN_diag().
getChemPotentials_RT()
void getChemPotentials_RT (doublereal * mu) const virtual
Get the array of non-dimensional species chemical potentials.
These are partial molar Gibbs free energies, \(\mu_k / \hat R T \).
We close the loop on this function, here, calling getChemPotentials() and then dividing by RT. No need for child classes to handle.
Parameters
mu Output vector of non-dimensional species chemical potentials Length: m_kk.
Reimplemented from ThermoPhase.
Reimplemented in MaskellSolidSolnPhase.
Definition at line 40 of file VPStandardStateTP.cpp.
References ThermoPhase::getChemPotentials(), Phase::m_kk, and ThermoPhase::RT().
getStandardChemPotentials()
void getStandardChemPotentials (doublereal * mu) const virtual
Get the array of chemical potentials at unit activity for the species at their standard states at the current T and P of the solution.
These are the standard state chemical potentials \(\mu^0_k(T,P) \). The values are evaluated at the current temperature and pressure of the solution
Parameters
mu Output vector of chemical potentials. Length: m_kk.
Reimplemented from ThermoPhase.
Reimplemented in MaskellSolidSolnPhase.
Definition at line 50 of file VPStandardStateTP.cpp.
References VPStandardStateTP::getGibbs_RT(), Phase::m_kk, and ThermoPhase::RT().
Referenced by DebyeHuckel::getChemPotentials(), HMWSoln::getChemPotentials(), IdealMolalSoln::getChemPotentials(), IdealSolnGasVPSS::getChemPotentials(), MargulesVPSSTP::getChemPotentials(), RedlichKisterVPSSTP::getChemPotentials(), and MolalityVPSSTP::getCsvReportData().
getEnthalpy_RT()
void getEnthalpy_RT (doublereal * hrt) const virtual
Get the nondimensional Enthalpy functions for the species at their standard states at the current T and P of the solution.
Parameters
hrt Output vector of nondimensional standard state enthalpies. Length: m_kk.
Reimplemented from ThermoPhase.
Definition at line 58 of file VPStandardStateTP.cpp.
References VPStandardStateTP::m_hss_RT, and VPStandardStateTP::updateStandardStateThermo().
Referenced by DebyeHuckel::getPartialMolarEnthalpies(), HMWSoln::getPartialMolarEnthalpies(), IdealMolalSoln::getPartialMolarEnthalpies(), IdealSolnGasVPSS::getPartialMolarEnthalpies(), IonsFromNeutralVPSSTP::getPartialMolarEnthalpies(), MargulesVPSSTP::getPartialMolarEnthalpies(), RedlichKisterVPSSTP::getPartialMolarEnthalpies(), and HMWSoln::relative_enthalpy().
getEntropy_R()
void getEntropy_R (doublereal * sr) const virtual
Get the array of nondimensional Entropy functions for the standard state species at the current T and P of the solution.
Parameters
sr Output vector of nondimensional standard state entropies. Length: m_kk.
Reimplemented from ThermoPhase.
Definition at line 64 of file VPStandardStateTP.cpp.
References VPStandardStateTP::m_sss_R, and VPStandardStateTP::updateStandardStateThermo().
Referenced by DebyeHuckel::getPartialMolarEntropies(), HMWSoln::getPartialMolarEntropies(), IdealMolalSoln::getPartialMolarEntropies(), IdealSolnGasVPSS::getPartialMolarEntropies(), IonsFromNeutralVPSSTP::getPartialMolarEntropies(), MargulesVPSSTP::getPartialMolarEntropies(), and RedlichKisterVPSSTP::getPartialMolarEntropies().
getGibbs_RT()
void getGibbs_RT (doublereal * grt) const virtual
Get the nondimensional Gibbs functions for the species in their standard states at the current T and P of the solution.
Parameters
grt Output vector of nondimensional standard state Gibbs free energies. Length: m_kk.
Reimplemented from ThermoPhase.
Definition at line 70 of file VPStandardStateTP.cpp.
References VPStandardStateTP::m_gss_RT, and VPStandardStateTP::updateStandardStateThermo().
Referenced by VPStandardStateTP::getStandardChemPotentials().
getPureGibbs()
void getPureGibbs (doublereal * gpure) const virtual
Get the Gibbs functions for the standard state of the species at the current T and P of the solution.
Units are Joules/kmol
Parameters
gpure Output vector of standard state Gibbs free energies. Length: m_kk.
Reimplemented from ThermoPhase.
Reimplemented in MaskellSolidSolnPhase.
Definition at line 76 of file VPStandardStateTP.cpp.
References VPStandardStateTP::m_gss_RT, Phase::m_kk, ThermoPhase::RT(), Cantera::scale(), and VPStandardStateTP::updateStandardStateThermo().
getIntEnergy_RT()
void getIntEnergy_RT (doublereal * urt) const virtual
Returns the vector of nondimensional Internal Energies of the standard state species at the current T and P of the solution.
Parameters
urt output vector of nondimensional standard state internal energies of the species. Length: m_kk.
Reimplemented from ThermoPhase.
Definition at line 83 of file VPStandardStateTP.cpp.
References VPStandardStateTP::m_hss_RT, Phase::m_kk, VPStandardStateTP::m_Plast_ss, VPStandardStateTP::m_Vss, ThermoPhase::RT(), and VPStandardStateTP::updateStandardStateThermo().
Referenced by IdealSolnGasVPSS::getPartialMolarIntEnergies().
getCp_R()
void getCp_R (doublereal * cpr) const virtual
Get the nondimensional Heat Capacities at constant pressure for the species standard states at the current T and P of the solution.
Parameters
cpr Output vector of nondimensional standard state heat capacities. Length: m_kk.
Reimplemented from ThermoPhase.
Definition at line 92 of file VPStandardStateTP.cpp.
References VPStandardStateTP::m_cpss_R, and VPStandardStateTP::updateStandardStateThermo().
Referenced by DebyeHuckel::getPartialMolarCp(), HMWSoln::getPartialMolarCp(), IdealMolalSoln::getPartialMolarCp(), IdealSolnGasVPSS::getPartialMolarCp(), MargulesVPSSTP::getPartialMolarCp(), and RedlichKisterVPSSTP::getPartialMolarCp().
getStandardVolumes()
void getStandardVolumes (doublereal * vol) const virtual
Get the molar volumes of the species standard states at the current T and P of the solution.
units = m^3 / kmol
Parameters
vol Output vector containing the standard state volumes. Length: m_kk.
Reimplemented from ThermoPhase.
Definition at line 98 of file VPStandardStateTP.cpp.
References VPStandardStateTP::m_Vss, and VPStandardStateTP::updateStandardStateThermo().
Referenced by IdealSolnGasVPSS::calcDensity(), IdealSolnGasVPSS::getActivityConcentrations(), DebyeHuckel::getPartialMolarVolumes(), HMWSoln::getPartialMolarVolumes(), IdealMolalSoln::getPartialMolarVolumes(), IdealSolnGasVPSS::getPartialMolarVolumes(), RedlichKisterVPSSTP::getPartialMolarVolumes(), HMWSoln::standardConcentration(), and IdealSolnGasVPSS::standardConcentration().
setTemperature()
void setTemperature (const doublereal temp) virtual
Set the temperature of the phase.
Currently this passes down to setState_TP(). It does not make sense to calculate the standard state without first setting T and P.
Parameters
temp Temperature (kelvin)
Reimplemented from Phase.
Definition at line 191 of file VPStandardStateTP.cpp.
References VPStandardStateTP::m_Pcurrent, VPStandardStateTP::setState_TP(), and VPStandardStateTP::updateStandardStateThermo().
setPressure()
void setPressure (doublereal p) virtual
Set the internally stored pressure (Pa) at constant temperature and composition.
Currently this passes down to setState_TP(). It does not make sense to calculate the standard state without first setting T and P.
Parameters
p input Pressure (Pa)
Reimplemented from Phase.
Reimplemented in MaskellSolidSolnPhase, and IdealSolnGasVPSS.
Definition at line 197 of file VPStandardStateTP.cpp.
References VPStandardStateTP::setState_TP(), Phase::temperature(), and VPStandardStateTP::updateStandardStateThermo().
Referenced by MolalityVPSSTP::setStateFromXML().
setState_TP()
void setState_TP (doublereal T, doublereal pres) virtual
Set the temperature and pressure at the same time.
Note this function triggers a reevaluation of the standard state quantities.
Parameters
T temperature (kelvin)
pres pressure (pascal)
Reimplemented from ThermoPhase.
Definition at line 208 of file VPStandardStateTP.cpp.
References VPStandardStateTP::calcDensity(), VPStandardStateTP::m_Pcurrent, Phase::setTemperature(), and VPStandardStateTP::updateStandardStateThermo().
Referenced by VPStandardStateTP::setPressure(), MolalityVPSSTP::setState_TPM(), and VPStandardStateTP::setTemperature().
pressure()
virtual doublereal pressure () const inline virtual
Returns the current pressure of the phase.
The pressure is an independent variable in this phase. Its current value is stored in the object VPStandardStateTP.
Returns
the pressure in pascals.
Reimplemented from Phase.
Reimplemented in MaskellSolidSolnPhase.
Definition at line 138 of file VPStandardStateTP.h.
References VPStandardStateTP::m_Pcurrent.
Referenced by HMWSoln::calcDensity(), IonsFromNeutralVPSSTP::calcDensity(), HMWSoln::s_update_d2lnMolalityActCoeff_dT2(), HMWSoln::s_update_dlnMolalityActCoeff_dP(), HMWSoln::s_update_dlnMolalityActCoeff_dT(), HMWSoln::s_updatePitzer_dlnMolalityActCoeff_dP(), HMWSoln::satPressure(), and IdealSolnGasVPSS::standardConcentration().
updateStandardStateThermo()
void updateStandardStateThermo () const virtual
Updates the standard state thermodynamic functions at the current T and P of the solution.
If m_useTmpStandardStateStorage is true, this function must be called for every call to functions in this class. It checks to see whether the temperature or pressure has changed and thus the ss thermodynamics functions for all of the species must be recalculated.
This function is responsible for updating the following internal members, when m_useTmpStandardStateStorage is true.
m_hss_RT;
m_cpss_R;
m_gss_RT;
m_sss_R;
m_Vss
If m_useTmpStandardStateStorage is not true, this function may be required to be called by child classes to update internal member data.
Definition at line 288 of file VPStandardStateTP.cpp.
References VPStandardStateTP::_updateStandardStateThermo(), VPStandardStateTP::m_Pcurrent, VPStandardStateTP::m_Plast_ss, ThermoPhase::m_tlast, VPStandardStateTP::m_Tlast_ss, and Phase::temperature().
Referenced by IdealSolnGasVPSS::cp_mole(), IdealSolnGasVPSS::enthalpy_mole(), IdealSolnGasVPSS::entropy_mole(), HMWSoln::getActivities(), VPStandardStateTP::getCp_R(), VPStandardStateTP::getCp_R_ref(), VPStandardStateTP::getEnthalpy_RT(), VPStandardStateTP::getEnthalpy_RT_ref(), VPStandardStateTP::getEntropy_R(), VPStandardStateTP::getEntropy_R_ref(), VPStandardStateTP::getGibbs_ref(), VPStandardStateTP::getGibbs_RT(), VPStandardStateTP::getGibbs_RT_ref(), VPStandardStateTP::getIntEnergy_RT(), VPStandardStateTP::getPureGibbs(), VPStandardStateTP::getStandardVolumes(), VPStandardStateTP::getStandardVolumes_ref(), HMWSoln::getUnscaledMolalityActivityCoefficients(), IdealSolnGasVPSS::setPressure(), VPStandardStateTP::setPressure(), VPStandardStateTP::setState_TP(), VPStandardStateTP::setTemperature(), and IdealSolnGasVPSS::setToEquilState().
minTemp()
double minTemp (size_t k = npos) const virtual
Minimum temperature for which the thermodynamic data for the species or phase are valid.
If no argument is supplied, the value returned will be the lowest temperature at which the data for all species are valid. Otherwise, the value will be only for species k. This function is a wrapper that calls the species thermo minTemp function.
Parameters
k index of the species. Default is -1, which will return the max of the min value over all species.
Reimplemented from ThermoPhase.
Definition at line 296 of file VPStandardStateTP.cpp.
References VPStandardStateTP::m_minTemp, VPStandardStateTP::m_PDSS_storage, and Cantera::npos.
maxTemp()
double maxTemp (size_t k = npos) const virtual
Maximum temperature for which the thermodynamic data for the species are valid.
If no argument is supplied, the value returned will be the highest temperature at which the data for all species are valid. Otherwise, the value will be only for species k. This function is a wrapper that calls the species thermo maxTemp function.
Parameters
k index of the species. Default is -1, which will return the min of the max value over all species.
Reimplemented from ThermoPhase.
Definition at line 305 of file VPStandardStateTP.cpp.
References VPStandardStateTP::m_maxTemp, VPStandardStateTP::m_PDSS_storage, and Cantera::npos.
calcDensity()
void calcDensity () protected virtual
Calculate the density of the mixture using the partial molar volumes and mole fractions as input.
The formula for this is
\[ \rho = \frac{\sum_k{X_k W_k}}{\sum_k{X_k V_k}} \]
where \(X_k\) are the mole fractions, \(W_k\) are the molecular weights, and \(V_k\) are the pure species molar volumes.
Note, the basis behind this formula is that in an ideal solution the partial molar volumes are equal to the pure species molar volumes. We have additionally specified in this class that the pure species molar volumes are independent of temperature and pressure.
NOTE: This function is not a member of the ThermoPhase base class.
Reimplemented in MaskellSolidSolnPhase, IonsFromNeutralVPSSTP, IdealSolnGasVPSS, IdealMolalSoln, HMWSoln, GibbsExcessVPSSTP, and DebyeHuckel.
Definition at line 203 of file VPStandardStateTP.cpp.
Referenced by VPStandardStateTP::setState_TP().
_updateStandardStateThermo()
void _updateStandardStateThermo () const protected virtual
Updates the standard state thermodynamic functions at the current T and P of the solution.
If m_useTmpStandardStateStorage is true, this function must be called for every call to functions in this class.
This function is responsible for updating the following internal members, when m_useTmpStandardStateStorage is true.
m_hss_RT;
m_cpss_R;
m_gss_RT;
m_sss_R;
m_Vss
This function doesn't check to see if the temperature or pressure has changed. It automatically assumes that it has changed. If m_useTmpStandardStateStorage is not true, this function may be required to be called by child classes to update internal member data..
Definition at line 262 of file VPStandardStateTP.cpp.
References PDSS::cp_R(), PDSS::cp_R_ref(), PDSS::enthalpy_RT(), PDSS::enthalpy_RT_ref(), PDSS::entropy_R(), PDSS::entropy_R_ref(), VPStandardStateTP::m_cp0_R, VPStandardStateTP::m_cpss_R, VPStandardStateTP::m_g0_RT, VPStandardStateTP::m_gss_RT, VPStandardStateTP::m_h0_RT, VPStandardStateTP::m_hss_RT, Phase::m_kk, VPStandardStateTP::m_Pcurrent, VPStandardStateTP::m_PDSS_storage, VPStandardStateTP::m_Plast_ss, VPStandardStateTP::m_s0_R, VPStandardStateTP::m_sss_R, ThermoPhase::m_tlast, VPStandardStateTP::m_Tlast_ss, VPStandardStateTP::m_V0, VPStandardStateTP::m_Vss, PDSS::molarVolume(), PDSS::molarVolume_ref(), PDSS::setState_TP(), and Phase::temperature().
Referenced by DebyeHuckel::getActivities(), IdealMolalSoln::getActivities(), DebyeHuckel::getMolalityActivityCoefficients(), and VPStandardStateTP::updateStandardStateThermo().
getEnthalpy_RT_ref()
void getEnthalpy_RT_ref (doublereal * hrt) const virtual
There are also temporary variables for holding the species reference- state values of Cp, H, S, and V at the last temperature and reference pressure called. These functions are not recalculated if a new call is made using the previous temperature. All calculations are done within the routine _updateRefStateThermo().
Reimplemented from ThermoPhase.
Definition at line 111 of file VPStandardStateTP.cpp.
References VPStandardStateTP::m_h0_RT, and VPStandardStateTP::updateStandardStateThermo().
getGibbs_RT_ref()
void getGibbs_RT_ref (doublereal * grt) const virtual
Returns the vector of nondimensional Gibbs Free Energies of the reference state at the current temperature of the solution and the reference pressure for the species.
Parameters
grt Output vector containing the nondimensional reference state Gibbs Free energies. Length: m_kk.
Reimplemented from ThermoPhase.
Definition at line 117 of file VPStandardStateTP.cpp.
References VPStandardStateTP::m_g0_RT, and VPStandardStateTP::updateStandardStateThermo().
getGibbs_ref()
void getGibbs_ref (doublereal * g) const virtual
Returns the vector of the Gibbs function of the reference state at the current temperature of the solution and the reference pressure for the species.
Parameters
g Output vector containing the reference state Gibbs Free energies. Length: m_kk. Units: J/kmol.
Reimplemented from ThermoPhase.
Definition at line 123 of file VPStandardStateTP.cpp.
References VPStandardStateTP::m_g0_RT, Phase::m_kk, ThermoPhase::RT(), Cantera::scale(), and VPStandardStateTP::updateStandardStateThermo().
getEntropy_R_ref()
void getEntropy_R_ref (doublereal * er) const virtual
Returns the vector of nondimensional entropies of the reference state at the current temperature of the solution and the reference pressure for each species.
Parameters
er Output vector containing the nondimensional reference state entropies. Length: m_kk.
Reimplemented from ThermoPhase.
Definition at line 136 of file VPStandardStateTP.cpp.
References VPStandardStateTP::m_s0_R, and VPStandardStateTP::updateStandardStateThermo().
getCp_R_ref()
void getCp_R_ref (doublereal * cprt) const virtual
Returns the vector of nondimensional constant pressure heat capacities of the reference state at the current temperature of the solution and reference pressure for each species.
Parameters
cprt Output vector of nondimensional reference state heat capacities at constant pressure for the species. Length: m_kk
Reimplemented from ThermoPhase.
Definition at line 142 of file VPStandardStateTP.cpp.
References VPStandardStateTP::m_cp0_R, and VPStandardStateTP::updateStandardStateThermo().
getStandardVolumes_ref()
void getStandardVolumes_ref (doublereal * vol) const virtual
Get the molar volumes of the species reference states at the current T and P_ref of the solution.
units = m^3 / kmol
Parameters
vol Output vector containing the standard state volumes. Length: m_kk.
Reimplemented from ThermoPhase.
Definition at line 148 of file VPStandardStateTP.cpp.
References VPStandardStateTP::m_Vss, and VPStandardStateTP::updateStandardStateThermo().
initThermo()
void initThermo () virtual
The following methods are used in the process of constructing the phase and setting its parameters from a specification in an input file. They are not normally used in application programs. To see how they are used, see importPhase().
Reimplemented from ThermoPhase.
Reimplemented in RedlichKisterVPSSTP, MolalityVPSSTP, MaskellSolidSolnPhase, MargulesVPSSTP, IonsFromNeutralVPSSTP, IdealSolnGasVPSS, IdealMolalSoln, HMWSoln, and DebyeHuckel.
Definition at line 154 of file VPStandardStateTP.cpp.
References PDSS::initThermo(), ThermoPhase::initThermo(), Phase::m_kk, and VPStandardStateTP::m_PDSS_storage.
Referenced by IdealSolnGasVPSS::initThermo(), IonsFromNeutralVPSSTP::initThermo(), MargulesVPSSTP::initThermo(), MolalityVPSSTP::initThermo(), and RedlichKisterVPSSTP::initThermo().
addSpecies() [1/2]
bool addSpecies (shared_ptr< Species > spec) virtual
The following methods are used in the process of constructing the phase and setting its parameters from a specification in an input file. They are not normally used in application programs. To see how they are used, see importPhase().
Reimplemented from ThermoPhase.
Reimplemented in MolalityVPSSTP, IonsFromNeutralVPSSTP, IdealSolnGasVPSS, IdealMolalSoln, GibbsExcessVPSSTP, and DebyeHuckel.
Definition at line 167 of file VPStandardStateTP.cpp.
References Phase::addSpecies(), MultiSpeciesThermo::install_STIT(), VPStandardStateTP::m_cp0_R, VPStandardStateTP::m_cpss_R, VPStandardStateTP::m_g0_RT, VPStandardStateTP::m_gss_RT, VPStandardStateTP::m_h0_RT, VPStandardStateTP::m_hss_RT, Phase::m_kk, VPStandardStateTP::m_s0_R, ThermoPhase::m_spthermo, VPStandardStateTP::m_sss_R, VPStandardStateTP::m_V0, and VPStandardStateTP::m_Vss.
installPDSS()
void installPDSS (size_t k, std::unique_ptr< PDSS > && pdss)
Install a PDSS object for species k
Definition at line 228 of file VPStandardStateTP.cpp.
References VPStandardStateTP::m_maxTemp, VPStandardStateTP::m_minTemp, VPStandardStateTP::m_PDSS_storage, Phase::molecularWeight(), Species::name, Phase::species(), and Species::thermo.
invalidateCache()
void invalidateCache () protected virtual
Invalidate any cached values which are normally updated only when a change in state is detected.
Reimplemented from ThermoPhase.
Definition at line 256 of file VPStandardStateTP.cpp.
References ThermoPhase::invalidateCache(), and VPStandardStateTP::m_Tlast_ss.
addSpecies() [2/2]
bool addSpecies
Add a Species to this Phase.
Returns true if the species was successfully added, or false if the species was ignored.
Derived classes which need to size arrays according to the number of species should overload this method. The derived class implementation should call the base class method, and, if this returns true (indicating that the species has been added), adjust their array sizes accordingly.
See also
ignoreUndefinedElements addUndefinedElements throwUndefinedElements
Definition at line 792 of file Phase.cpp.
Referenced by DebyeHuckel::addSpecies(), IdealMolalSoln::addSpecies(), IdealSolnGasVPSS::addSpecies(), IonsFromNeutralVPSSTP::addSpecies(), and MolalityVPSSTP::addSpecies().
Member Data Documentation
m_Pcurrent
doublereal m_Pcurrent protected
Current value of the pressure - state variable.
Because we are now using the pressure as a state variable, we need to carry it along within this object
units = Pascals
Definition at line 269 of file VPStandardStateTP.h.
Referenced by VPStandardStateTP::_updateStandardStateThermo(), IdealSolnGasVPSS::calcDensity(), IdealSolnGasVPSS::isothermalCompressibility(), VPStandardStateTP::pressure(), IdealSolnGasVPSS::setPressure(), VPStandardStateTP::setState_TP(), VPStandardStateTP::setTemperature(), and VPStandardStateTP::updateStandardStateThermo().
m_minTemp
double m_minTemp protected
The minimum temperature at which data for all species is valid.
Definition at line 272 of file VPStandardStateTP.h.
Referenced by VPStandardStateTP::installPDSS(), and VPStandardStateTP::minTemp().
m_maxTemp
double m_maxTemp protected
The maximum temperature at which data for all species is valid.
Definition at line 275 of file VPStandardStateTP.h.
Referenced by VPStandardStateTP::installPDSS(), and VPStandardStateTP::maxTemp().
m_Tlast_ss
doublereal m_Tlast_ss mutable protected
The last temperature at which the standard state thermodynamic properties were calculated at.
Definition at line 279 of file VPStandardStateTP.h.
Referenced by VPStandardStateTP::_updateStandardStateThermo(), VPStandardStateTP::invalidateCache(), and VPStandardStateTP::updateStandardStateThermo().
m_Plast_ss
doublereal m_Plast_ss mutable protected
The last pressure at which the Standard State thermodynamic properties were calculated at.
Definition at line 283 of file VPStandardStateTP.h.
Referenced by VPStandardStateTP::_updateStandardStateThermo(), VPStandardStateTP::getIntEnergy_RT(), and VPStandardStateTP::updateStandardStateThermo().
m_PDSS_storage
std::vector<std::unique_ptr<PDSS> > m_PDSS_storage protected
Storage for the PDSS objects for the species.
Storage is in species index order. VPStandardStateTp owns each of the objects. Copy operations are deep.
Definition at line 290 of file VPStandardStateTP.h.
Referenced by VPStandardStateTP::_updateStandardStateThermo(), VPStandardStateTP::initThermo(), VPStandardStateTP::installPDSS(), VPStandardStateTP::maxTemp(), and VPStandardStateTP::minTemp().
m_h0_RT
vector_fp m_h0_RT mutable protected
Vector containing the species reference enthalpies at T = m_tlast and P = p_ref.
Definition at line 294 of file VPStandardStateTP.h.
Referenced by VPStandardStateTP::_updateStandardStateThermo(), VPStandardStateTP::addSpecies(), and VPStandardStateTP::getEnthalpy_RT_ref().
m_cp0_R
vector_fp m_cp0_R mutable protected
Vector containing the species reference constant pressure heat capacities at T = m_tlast and P = p_ref.
Definition at line 298 of file VPStandardStateTP.h.
Referenced by VPStandardStateTP::_updateStandardStateThermo(), VPStandardStateTP::addSpecies(), and VPStandardStateTP::getCp_R_ref().
m_g0_RT
vector_fp m_g0_RT mutable protected
Vector containing the species reference Gibbs functions at T = m_tlast and P = p_ref.
Definition at line 302 of file VPStandardStateTP.h.
Referenced by VPStandardStateTP::_updateStandardStateThermo(), VPStandardStateTP::addSpecies(), VPStandardStateTP::getGibbs_ref(), VPStandardStateTP::getGibbs_RT_ref(), and IdealSolnGasVPSS::setToEquilState().
m_s0_R
vector_fp m_s0_R mutable protected
Vector containing the species reference entropies at T = m_tlast and P = p_ref.
Definition at line 306 of file VPStandardStateTP.h.
Referenced by VPStandardStateTP::_updateStandardStateThermo(), VPStandardStateTP::addSpecies(), and VPStandardStateTP::getEntropy_R_ref().
m_V0
vector_fp m_V0 mutable protected
Vector containing the species reference molar volumes.
Definition at line 309 of file VPStandardStateTP.h.
Referenced by VPStandardStateTP::_updateStandardStateThermo(), and VPStandardStateTP::addSpecies().
m_hss_RT
vector_fp m_hss_RT mutable protected
Vector containing the species Standard State enthalpies at T = m_tlast and P = m_plast.
Definition at line 313 of file VPStandardStateTP.h.
Referenced by VPStandardStateTP::_updateStandardStateThermo(), VPStandardStateTP::addSpecies(), IdealSolnGasVPSS::enthalpy_mole(), VPStandardStateTP::getEnthalpy_RT(), and VPStandardStateTP::getIntEnergy_RT().
m_cpss_R
vector_fp m_cpss_R mutable protected
Vector containing the species Standard State constant pressure heat capacities at T = m_tlast and P = m_plast.
Definition at line 317 of file VPStandardStateTP.h.
Referenced by VPStandardStateTP::_updateStandardStateThermo(), VPStandardStateTP::addSpecies(), IdealSolnGasVPSS::cp_mole(), and VPStandardStateTP::getCp_R().
m_gss_RT
vector_fp m_gss_RT mutable protected
Vector containing the species Standard State Gibbs functions at T = m_tlast and P = m_plast.
Definition at line 321 of file VPStandardStateTP.h.
Referenced by VPStandardStateTP::_updateStandardStateThermo(), VPStandardStateTP::addSpecies(), VPStandardStateTP::getGibbs_RT(), and VPStandardStateTP::getPureGibbs().
m_sss_R
vector_fp m_sss_R mutable protected
Vector containing the species Standard State entropies at T = m_tlast and P = m_plast.
Definition at line 325 of file VPStandardStateTP.h.
Referenced by VPStandardStateTP::_updateStandardStateThermo(), VPStandardStateTP::addSpecies(), IdealSolnGasVPSS::entropy_mole(), and VPStandardStateTP::getEntropy_R().
m_Vss
vector_fp m_Vss mutable protected
Vector containing the species standard state volumes at T = m_tlast and P = m_plast.
Definition at line 329 of file VPStandardStateTP.h.
Referenced by VPStandardStateTP::_updateStandardStateThermo(), VPStandardStateTP::addSpecies(), VPStandardStateTP::getIntEnergy_RT(), VPStandardStateTP::getStandardVolumes(), and VPStandardStateTP::getStandardVolumes_ref().
The documentation for this class was generated from the following files:
VPStandardStateTP.h
VPStandardStateTP.cpp