Cantera: LTPspecies Class Reference
LTPspecies Class Reference
Class LTPspecies holds transport parameterizations for a specific liquid- phase species.
#include <LTPspecies.h>
Public Member Functions
virtual LTPspecies * duplMyselfAsLTPspecies () const
Duplication routine.
void setThermo (thermo_t *thermo)
Set the ThermoPhase object, which is used to find the temperature.
void setName (const std::string &name)
Set the species name.
void setTransportPropertyType (TransportPropertyType tp_ind)
TransportPropertyType containing the property id that this object is creating a parameterization for (e.g., viscosity)
virtual void setupFromXML (const XML_Node &propNode)
Set up the species transport property from the XML node, <propNode> that is a child of the <transport> node in the species block and specifies a type of transport property (like viscosity)
virtual doublereal getSpeciesTransProp ()
Returns the vector of standard state species transport property.
virtual bool checkPositive () const
Check to see if the property evaluation will be positive.
doublereal getMixWeight () const
Return the weight mixture.
Protected Attributes
std::string m_speciesName
Species Name for the property that is being described.
LTPTemperatureDependenceType m_model
Model type for the temperature dependence.
TransportPropertyType m_property
enum indicating which property this is (i.e viscosity)
vector_fp m_coeffs
Model temperature-dependence ceofficients.
const thermo_t * m_thermo
Pointer to a const thermo object to get current temperature.
doublereal m_mixWeight
Weighting used for mixing.
Private Member Functions
virtual void adjustCoeffsForComposition ()
Internal model to adjust species-specific properties for the composition.
Detailed Description
Class LTPspecies holds transport parameterizations for a specific liquid- phase species.
Deprecated:
To be removed after Cantera 2.4
Subclasses handle different means of specifying transport properties like constant, Arrhenius or polynomial temperature fits. In its current state, it is primarily suitable for specifying temperature dependence, but the adjustCoeffsForComposition() method can be implemented to adjust for the composition dependence.
Mixing rules for computing mixture transport properties are handled separately in the LiquidTranInteraction subclasses.
Definition at line 78 of file LTPspecies.h.
Member Function Documentation
duplMyselfAsLTPspecies()
LTPspecies * duplMyselfAsLTPspecies () const virtual
Duplication routine.
(virtual from LTPspecies)
Returns
a copy of this routine as a pointer to LTPspecies
Reimplemented in LTPspecies_ExpT, LTPspecies_Poly, LTPspecies_Arrhenius, and LTPspecies_Const.
Definition at line 62 of file LTPspecies.cpp.
setThermo()
void setThermo (thermo_t * thermo) inline
Set the ThermoPhase object, which is used to find the temperature.
Definition at line 93 of file LTPspecies.h.
References LTPspecies::m_thermo.
setName()
void setName (const std::string & name) inline
Set the species name.
Definition at line 98 of file LTPspecies.h.
References LTPspecies::m_speciesName.
setTransportPropertyType()
void setTransportPropertyType (TransportPropertyType tp_ind) inline
TransportPropertyType containing the property id that this object is creating a parameterization for (e.g., viscosity)
Definition at line 104 of file LTPspecies.h.
References LTPspecies::m_property.
setupFromXML()
virtual void setupFromXML (const XML_Node & propNode) inline virtual
Set up the species transport property from the XML node, <propNode> that is a child of the <transport> node in the species block and specifies a type of transport property (like viscosity)
Reimplemented in LTPspecies_ExpT, LTPspecies_Poly, LTPspecies_Arrhenius, and LTPspecies_Const.
Definition at line 111 of file LTPspecies.h.
getSpeciesTransProp()
doublereal getSpeciesTransProp () virtual
Returns the vector of standard state species transport property.
The standard state species transport property is returned. Any temperature and composition dependence will be adjusted internally according to the information provided by the subclass object.
Returns
a single double containing the property evaluation at the current ThermoPhase temperature.
Reimplemented in LTPspecies_ExpT, LTPspecies_Poly, LTPspecies_Arrhenius, and LTPspecies_Const.
Definition at line 67 of file LTPspecies.cpp.
Referenced by SolidTransport::defectActivity(), SolidTransport::defectDiffusivity(), SolidTransport::electricalConductivity(), SolidTransport::ionConductivity(), and SolidTransport::thermalConductivity().
checkPositive()
bool checkPositive () const virtual
Check to see if the property evaluation will be positive.
Definition at line 72 of file LTPspecies.cpp.
getMixWeight()
doublereal getMixWeight () const
Return the weight mixture.
Definition at line 77 of file LTPspecies.cpp.
adjustCoeffsForComposition()
void adjustCoeffsForComposition () private virtual
Internal model to adjust species-specific properties for the composition.
Currently just a place holder, but this method could take the composition from the thermo object and adjust coefficients according to some yet unspecified model.
Definition at line 82 of file LTPspecies.cpp.
Member Data Documentation
m_speciesName
std::string m_speciesName protected
Species Name for the property that is being described.
Definition at line 143 of file LTPspecies.h.
Referenced by LTPspecies::setName().
m_model
LTPTemperatureDependenceType m_model protected
Model type for the temperature dependence.
Definition at line 146 of file LTPspecies.h.
m_property
TransportPropertyType m_property protected
enum indicating which property this is (i.e viscosity)
Definition at line 149 of file LTPspecies.h.
Referenced by LTPspecies::setTransportPropertyType().
m_coeffs
vector_fp m_coeffs protected
Model temperature-dependence ceofficients.
Definition at line 152 of file LTPspecies.h.
Referenced by LTPspecies_Poly::getSpeciesTransProp(), and LTPspecies_ExpT::getSpeciesTransProp().
m_thermo
const thermo_t* m_thermo protected
Pointer to a const thermo object to get current temperature.
Definition at line 155 of file LTPspecies.h.
Referenced by LTPspecies_Poly::getSpeciesTransProp(), LTPspecies_ExpT::getSpeciesTransProp(), and LTPspecies::setThermo().
m_mixWeight
doublereal m_mixWeight protected
Weighting used for mixing.
This weighting can be employed to allow salt transport properties to be represented by specific ions. For example, to have Li+ and Ca+ represent the mixing transport properties of LiCl and CaCl2, the weightings for Li+ would be 2.0, for K+ would be 3.0 and for Cl- would be 0.0. The transport properties for Li+ would be those for LiCl and the transport properties for Ca+ would be those for CaCl2. The transport properties for Cl- should be something innoccuous like 1.0–note that 0.0 is not innocuous if there are logarithms involved.
Definition at line 168 of file LTPspecies.h.
The documentation for this class was generated from the following files:
LTPspecies.h
LTPspecies.cpp