Cantera: MaskellSolidSolnPhase Class Reference
MaskellSolidSolnPhase Class Reference
Models of Phases of Matter » Thermodynamic Properties
Class MaskellSolidSolnPhase represents a condensed phase non-ideal solution with 2 species following the thermodynamic model described in Maskell, Shaw, and Tye, Manganese Dioxide Electrode – IX, Electrochimica Acta 28(2) pp 231-235, 1983.
#include <MaskellSolidSolnPhase.h>
Public Member Functions
virtual std::string type () const
String indicating the thermodynamic model implemented.
virtual void getActivityConcentrations (doublereal *c) const
This method returns an array of generalized concentrations.
virtual doublereal standardConcentration (size_t k=0) const
Return the standard concentration for the kth species.
virtual doublereal logStandardConc (size_t k=0) const
Natural logarithm of the standard concentration of the kth species.
Molar Thermodynamic Properties of the Solution
virtual doublereal enthalpy_mole () const
Molar enthalpy. Units: J/kmol.
virtual doublereal entropy_mole () const
Molar entropy. Units: J/kmol/K.
Mechanical Equation of State Properties
In this equation of state implementation, the density is a function only of the mole fractions.
Therefore, it can't be an independent variable. Instead, the pressure is used as the independent variable. Functions which try to set the thermodynamic state by calling setDensity() may cause an exception to be thrown.
virtual doublereal pressure () const
Pressure.
virtual void setPressure (doublereal p)
Set the pressure at constant temperature.
virtual void setDensity (const doublereal rho)
Overridden setDensity() function is necessary because the density is not an independent variable.
virtual void calcDensity ()
Calculate the density of the mixture using the partial molar volumes and mole fractions as input.
virtual void setMolarDensity (const doublereal rho)
Overridden setMolarDensity() function is necessary because the density is not an independent variable.
Chemical Potentials and Activities
virtual void getActivityCoefficients (doublereal *ac) const
Get the array of non-dimensional molar-based activity coefficients at the current solution temperature, pressure, and solution concentration.
virtual void getChemPotentials (doublereal *mu) const
Get the species chemical potentials. Units: J/kmol.
virtual void getChemPotentials_RT (doublereal *mu) const
Get the array of non-dimensional species chemical potentials.
Partial Molar Properties of the Solution
virtual void getPartialMolarEnthalpies (doublereal *hbar) const
Returns an array of partial molar enthalpies for the species in the mixture.
virtual void getPartialMolarEntropies (doublereal *sbar) const
Returns an array of partial molar entropies of the species in the solution.
virtual void getPartialMolarCp (doublereal *cpbar) const
Return an array of partial molar heat capacities for the species in the mixture.
virtual void getPartialMolarVolumes (doublereal *vbar) const
Return an array of partial molar volumes for the species in the mixture.
virtual void getPureGibbs (doublereal *gpure) const
Get the Gibbs functions for the standard state of the species at the current T and P of the solution.
virtual void getStandardChemPotentials (doublereal *mu) const
Get the array of chemical potentials at unit activity for the species at their standard states at the current T and P of the solution.
Utility Functions
virtual void initThermoXML (XML_Node &phaseNode, const std::string &id)
Import and initialize a ThermoPhase object using an XML tree.
void set_h_mix (const doublereal hmix)
void setProductSpecies (const std::string &name)
Set the product Species. Must be called after species have been added.
Public Member Functions inherited from VPStandardStateTP
VPStandardStateTP ()
Constructor.
virtual int standardStateConvention () const
This method returns the convention used in specification of the standard state, of which there are currently two, temperature based, and variable pressure based.
virtual void getdlnActCoeffdlnN_diag (doublereal *dlnActCoeffdlnN_diag) const
Get the array of log species mole number derivatives of the log activity coefficients.
virtual void getEnthalpy_RT (doublereal *hrt) const
Get the nondimensional Enthalpy functions for the species at their standard states at the current T and P of the solution.
virtual void getEntropy_R (doublereal *sr) const
Get the array of nondimensional Entropy functions for the standard state species at the current T and P of the solution.
virtual void getGibbs_RT (doublereal *grt) const
Get the nondimensional Gibbs functions for the species in their standard states at the current T and P of the solution.
virtual void getIntEnergy_RT (doublereal *urt) const
Returns the vector of nondimensional Internal Energies of the standard state species at the current T and P of the solution.
virtual void getCp_R (doublereal *cpr) const
Get the nondimensional Heat Capacities at constant pressure for the species standard states at the current T and P of the solution.
virtual void getStandardVolumes (doublereal *vol) const
Get the molar volumes of the species standard states at the current T and P of the solution.
virtual const vector_fp & getStandardVolumes () const
virtual void setTemperature (const doublereal temp)
Set the temperature of the phase.
virtual void setState_TP (doublereal T, doublereal pres)
Set the temperature and pressure at the same time.
virtual void updateStandardStateThermo () const
Updates the standard state thermodynamic functions at the current T and P of the solution.
virtual void initThermo ()
virtual bool addSpecies (shared_ptr< Species > spec)
void installPDSS (size_t k, std::unique_ptr< PDSS > &&pdss)
Install a PDSS object for species k
PDSS * providePDSS (size_t k)
const PDSS * providePDSS (size_t k) const
virtual bool addSpecies (shared_ptr< Species > spec)
Add a Species to this Phase.
virtual void getEnthalpy_RT_ref (doublereal *hrt) const
virtual void getGibbs_RT_ref (doublereal *grt) const
Returns the vector of nondimensional Gibbs Free Energies of the reference state at the current temperature of the solution and the reference pressure for the species.
virtual void getGibbs_ref (doublereal *g) const
Returns the vector of the Gibbs function of the reference state at the current temperature of the solution and the reference pressure for the species.
virtual void getEntropy_R_ref (doublereal *er) const
Returns the vector of nondimensional entropies of the reference state at the current temperature of the solution and the reference pressure for each species.
virtual void getCp_R_ref (doublereal *cprt) const
Returns the vector of nondimensional constant pressure heat capacities of the reference state at the current temperature of the solution and reference pressure for each species.
virtual void getStandardVolumes_ref (doublereal *vol) const
Get the molar volumes of the species reference states at the current T and P_ref of the solution.
Public Member Functions inherited from ThermoPhase
ThermoPhase ()
Constructor.
doublereal RT () const
Return the Gas Constant multiplied by the current temperature.
virtual doublereal refPressure () const
Returns the reference pressure in Pa.
virtual doublereal minTemp (size_t k=npos) const
Minimum temperature for which the thermodynamic data for the species or phase are valid.
doublereal Hf298SS (const size_t k) const
Report the 298 K Heat of Formation of the standard state of one species (J kmol-1)
virtual void modifyOneHf298SS (const size_t k, const doublereal Hf298New)
Modify the value of the 298 K Heat of Formation of one species in the phase (J kmol-1)
virtual void resetHf298 (const size_t k=npos)
Restore the original heat of formation of one or more species.
virtual doublereal maxTemp (size_t k=npos) const
Maximum temperature for which the thermodynamic data for the species are valid.
bool chargeNeutralityNecessary () const
Returns the chargeNeutralityNecessity boolean.
virtual doublereal intEnergy_mole () const
Molar internal energy. Units: J/kmol.
virtual doublereal gibbs_mole () const
Molar Gibbs function. Units: J/kmol.
virtual doublereal cp_mole () const
Molar heat capacity at constant pressure. Units: J/kmol/K.
virtual doublereal cv_mole () const
Molar heat capacity at constant volume. Units: J/kmol/K.
virtual doublereal isothermalCompressibility () const
Returns the isothermal compressibility. Units: 1/Pa.
virtual doublereal thermalExpansionCoeff () const
Return the volumetric thermal expansion coefficient. Units: 1/K.
void setElectricPotential (doublereal v)
Set the electric potential of this phase (V).
doublereal electricPotential () const
Returns the electric potential of this phase (V).
virtual int activityConvention () const
This method returns the convention used in specification of the activities, of which there are currently two, molar- and molality-based conventions.
virtual void getActivities (doublereal *a) const
Get the array of non-dimensional activities at the current solution temperature, pressure, and solution concentration.
virtual void getLnActivityCoefficients (doublereal *lnac) const
Get the array of non-dimensional molar-based ln activity coefficients at the current solution temperature, pressure, and solution concentration.
void getElectrochemPotentials (doublereal *mu) const
Get the species electrochemical potentials.
virtual void getPartialMolarIntEnergies (doublereal *ubar) const
Return an array of partial molar internal energies for the species in the mixture.
virtual void getIntEnergy_RT_ref (doublereal *urt) const
Returns the vector of nondimensional internal Energies of the reference state at the current temperature of the solution and the reference pressure for each species.
doublereal enthalpy_mass () const
Specific enthalpy. Units: J/kg.
doublereal intEnergy_mass () const
Specific internal energy. Units: J/kg.
doublereal entropy_mass () const
Specific entropy. Units: J/kg/K.
doublereal gibbs_mass () const
Specific Gibbs function. Units: J/kg.
doublereal cp_mass () const
Specific heat at constant pressure. Units: J/kg/K.
doublereal cv_mass () const
Specific heat at constant volume. Units: J/kg/K.
virtual void setState_TPX (doublereal t, doublereal p, const doublereal *x)
Set the temperature (K), pressure (Pa), and mole fractions.
virtual void setState_TPX (doublereal t, doublereal p, const compositionMap &x)
Set the temperature (K), pressure (Pa), and mole fractions.
virtual void setState_TPX (doublereal t, doublereal p, const std::string &x)
Set the temperature (K), pressure (Pa), and mole fractions.
virtual void setState_TPY (doublereal t, doublereal p, const doublereal *y)
Set the internally stored temperature (K), pressure (Pa), and mass fractions of the phase.
virtual void setState_TPY (doublereal t, doublereal p, const compositionMap &y)
Set the internally stored temperature (K), pressure (Pa), and mass fractions of the phase.
virtual void setState_TPY (doublereal t, doublereal p, const std::string &y)
Set the internally stored temperature (K), pressure (Pa), and mass fractions of the phase.
virtual void setState_PX (doublereal p, doublereal *x)
Set the pressure (Pa) and mole fractions.
virtual void setState_PY (doublereal p, doublereal *y)
Set the internally stored pressure (Pa) and mass fractions.
virtual void setState_HP (double h, double p, double tol=1e-9)
Set the internally stored specific enthalpy (J/kg) and pressure (Pa) of the phase.
virtual void setState_UV (double u, double v, double tol=1e-9)
Set the specific internal energy (J/kg) and specific volume (m^3/kg).
virtual void setState_SP (double s, double p, double tol=1e-9)
Set the specific entropy (J/kg/K) and pressure (Pa).
virtual void setState_SV (double s, double v, double tol=1e-9)
Set the specific entropy (J/kg/K) and specific volume (m^3/kg).
virtual void setState_ST (double s, double t, double tol=1e-9)
Set the specific entropy (J/kg/K) and temperature (K).
virtual void setState_TV (double t, double v, double tol=1e-9)
Set the temperature (K) and specific volume (m^3/kg).
virtual void setState_PV (double p, double v, double tol=1e-9)
Set the pressure (Pa) and specific volume (m^3/kg).
virtual void setState_UP (double u, double p, double tol=1e-9)
Set the specific internal energy (J/kg) and pressure (Pa).
virtual void setState_VH (double v, double h, double tol=1e-9)
Set the specific volume (m^3/kg) and the specific enthalpy (J/kg)
virtual void setState_TH (double t, double h, double tol=1e-9)
Set the temperature (K) and the specific enthalpy (J/kg)
virtual void setState_SH (double s, double h, double tol=1e-9)
Set the specific entropy (J/kg/K) and the specific enthalpy (J/kg)
virtual void setState_RP (doublereal rho, doublereal p)
Set the density (kg/m**3) and pressure (Pa) at constant composition.
virtual void setState_RPX (doublereal rho, doublereal p, const doublereal *x)
Set the density (kg/m**3), pressure (Pa) and mole fractions.
virtual void setState_RPX (doublereal rho, doublereal p, const compositionMap &x)
Set the density (kg/m**3), pressure (Pa) and mole fractions.
virtual void setState_RPX (doublereal rho, doublereal p, const std::string &x)
Set the density (kg/m**3), pressure (Pa) and mole fractions.
virtual void setState_RPY (doublereal rho, doublereal p, const doublereal *y)
Set the density (kg/m**3), pressure (Pa) and mass fractions.
virtual void setState_RPY (doublereal rho, doublereal p, const compositionMap &y)
Set the density (kg/m**3), pressure (Pa) and mass fractions.
virtual void setState_RPY (doublereal rho, doublereal p, const std::string &y)
Set the density (kg/m**3), pressure (Pa) and mass fractions.
void equilibrate (const std::string &XY, const std::string &solver="auto", double rtol=1e-9, int max_steps=50000, int max_iter=100, int estimate_equil=0, int log_level=0)
Equilibrate a ThermoPhase object.
virtual void setToEquilState (const doublereal *lambda_RT)
This method is used by the ChemEquil equilibrium solver.
void setElementPotentials (const vector_fp &lambda)
Stores the element potentials in the ThermoPhase object.
bool getElementPotentials (doublereal *lambda) const
Returns the element potentials stored in the ThermoPhase object.
virtual bool compatibleWithMultiPhase () const
Indicates whether this phase type can be used with class MultiPhase for equilibrium calculations.
virtual doublereal critTemperature () const
Critical temperature (K).
virtual doublereal critPressure () const
Critical pressure (Pa).
virtual doublereal critVolume () const
Critical volume (m3/kmol).
virtual doublereal critCompressibility () const
Critical compressibility (unitless).
virtual doublereal critDensity () const
Critical density (kg/m3).
virtual doublereal satTemperature (doublereal p) const
Return the saturation temperature given the pressure.
virtual doublereal satPressure (doublereal t)
Return the saturation pressure given the temperature.
virtual doublereal vaporFraction () const
Return the fraction of vapor at the current conditions.
virtual void setState_Tsat (doublereal t, doublereal x)
Set the state to a saturated system at a particular temperature.
virtual void setState_Psat (doublereal p, doublereal x)
Set the state to a saturated system at a particular pressure.
virtual void modifySpecies (size_t k, shared_ptr< Species > spec)
Modify the thermodynamic data associated with a species.
void saveSpeciesData (const size_t k, const XML_Node *const data)
Store a reference pointer to the XML tree containing the species data for this phase.
const std::vector< const XML_Node * > & speciesData () const
Return a pointer to the vector of XML nodes containing the species data for this phase.
virtual MultiSpeciesThermo & speciesThermo (int k=-1)
Return a changeable reference to the calculation manager for species reference-state thermodynamic properties.
virtual void initThermoFile (const std::string &inputFile, const std::string &id)
virtual void setParameters (int n, doublereal *const c)
Set the equation of state parameters.
virtual void getParameters (int &n, doublereal *const c) const
Get the equation of state parameters in a vector.
virtual void setParametersFromXML (const XML_Node &eosdata)
Set equation of state parameter values from XML entries.
virtual void setStateFromXML (const XML_Node &state)
Set the initial state of the phase to the conditions specified in the state XML element.
virtual void getdlnActCoeffds (const doublereal dTds, const doublereal *const dXds, doublereal *dlnActCoeffds) const
Get the change in activity coefficients wrt changes in state (temp, mole fraction, etc) along a line in parameter space or along a line in physical space.
virtual void getdlnActCoeffdlnX_diag (doublereal *dlnActCoeffdlnX_diag) const
Get the array of ln mole fraction derivatives of the log activity coefficients - diagonal component only.
virtual void getdlnActCoeffdlnN (const size_t ld, doublereal *const dlnActCoeffdlnN)
Get the array of derivatives of the log activity coefficients with respect to the log of the species mole numbers.
virtual void getdlnActCoeffdlnN_numderiv (const size_t ld, doublereal *const dlnActCoeffdlnN)
virtual std::string report (bool show_thermo=true, doublereal threshold=-1e-14) const
returns a summary of the state of the phase as a string
virtual void reportCSV (std::ofstream &csvFile) const
returns a summary of the state of the phase to a comma separated file.
Public Member Functions inherited from Phase
Phase ()
Default constructor.
Phase (const Phase &)=delete
Phase & operator= (const Phase &)=delete
XML_Node & xml () const
Returns a const reference to the XML_Node that describes the phase.
void setXMLdata (XML_Node &xmlPhase)
Stores the XML tree information for the current phase.
void saveState (vector_fp &state) const
Save the current internal state of the phase.
void saveState (size_t lenstate, doublereal *state) const
Write to array 'state' the current internal state.
void restoreState (const vector_fp &state)
Restore a state saved on a previous call to saveState.
void restoreState (size_t lenstate, const doublereal *state)
Restore the state of the phase from a previously saved state vector.
doublereal molecularWeight (size_t k) const
Molecular weight of species k.
void getMolecularWeights (vector_fp &weights) const
Copy the vector of molecular weights into vector weights.
void getMolecularWeights (doublereal *weights) const
Copy the vector of molecular weights into array weights.
const vector_fp & molecularWeights () const
Return a const reference to the internal vector of molecular weights.
virtual double size (size_t k) const
doublereal charge (size_t k) const
Dimensionless electrical charge of a single molecule of species k The charge is normalized by the the magnitude of the electron charge.
doublereal chargeDensity () const
Charge density [C/m^3].
size_t nDim () const
Returns the number of spatial dimensions (1, 2, or 3)
void setNDim (size_t ndim)
Set the number of spatial dimensions (1, 2, or 3).
virtual bool ready () const
Returns a bool indicating whether the object is ready for use.
int stateMFNumber () const
Return the State Mole Fraction Number.
std::string id () const
Return the string id for the phase.
void setID (const std::string &id)
Set the string id for the phase.
std::string name () const
Return the name of the phase.
void setName (const std::string &nm)
Sets the string name for the phase.
std::string elementName (size_t m) const
Name of the element with index m.
size_t elementIndex (const std::string &name) const
Return the index of element named 'name'.
const std::vector< std::string > & elementNames () const
Return a read-only reference to the vector of element names.
doublereal atomicWeight (size_t m) const
Atomic weight of element m.
doublereal entropyElement298 (size_t m) const
Entropy of the element in its standard state at 298 K and 1 bar.
int atomicNumber (size_t m) const
Atomic number of element m.
int elementType (size_t m) const
Return the element constraint type Possible types include:
int changeElementType (int m, int elem_type)
Change the element type of the mth constraint Reassigns an element type.
const vector_fp & atomicWeights () const
Return a read-only reference to the vector of atomic weights.
size_t nElements () const
Number of elements.
void checkElementIndex (size_t m) const
Check that the specified element index is in range.
void checkElementArraySize (size_t mm) const
Check that an array size is at least nElements().
doublereal nAtoms (size_t k, size_t m) const
Number of atoms of element m in species k.
void getAtoms (size_t k, double *atomArray) const
Get a vector containing the atomic composition of species k.
size_t speciesIndex (const std::string &name) const
Returns the index of a species named 'name' within the Phase object.
std::string speciesName (size_t k) const
Name of the species with index k.
std::string speciesSPName (int k) const
Returns the expanded species name of a species, including the phase name This is guaranteed to be unique within a Cantera problem.
const std::vector< std::string > & speciesNames () const
Return a const reference to the vector of species names.
size_t nSpecies () const
Returns the number of species in the phase.
void checkSpeciesIndex (size_t k) const
Check that the specified species index is in range.
void checkSpeciesArraySize (size_t kk) const
Check that an array size is at least nSpecies().
void setMoleFractionsByName (const compositionMap &xMap)
Set the species mole fractions by name.
void setMoleFractionsByName (const std::string &x)
Set the mole fractions of a group of species by name.
void setMassFractionsByName (const compositionMap &yMap)
Set the species mass fractions by name.
void setMassFractionsByName (const std::string &x)
Set the species mass fractions by name.
void setState_TRX (doublereal t, doublereal dens, const doublereal *x)
Set the internally stored temperature (K), density, and mole fractions.
void setState_TRX (doublereal t, doublereal dens, const compositionMap &x)
Set the internally stored temperature (K), density, and mole fractions.
void setState_TRY (doublereal t, doublereal dens, const doublereal *y)
Set the internally stored temperature (K), density, and mass fractions.
void setState_TRY (doublereal t, doublereal dens, const compositionMap &y)
Set the internally stored temperature (K), density, and mass fractions.
void setState_TNX (doublereal t, doublereal n, const doublereal *x)
Set the internally stored temperature (K), molar density (kmol/m^3), and mole fractions.
void setState_TR (doublereal t, doublereal rho)
Set the internally stored temperature (K) and density (kg/m^3)
void setState_TX (doublereal t, doublereal *x)
Set the internally stored temperature (K) and mole fractions.
void setState_TY (doublereal t, doublereal *y)
Set the internally stored temperature (K) and mass fractions.
void setState_RX (doublereal rho, doublereal *x)
Set the density (kg/m^3) and mole fractions.
void setState_RY (doublereal rho, doublereal *y)
Set the density (kg/m^3) and mass fractions.
compositionMap getMoleFractionsByName (double threshold=0.0) const
Get the mole fractions by name.
doublereal moleFraction (size_t k) const
Return the mole fraction of a single species.
doublereal moleFraction (const std::string &name) const
Return the mole fraction of a single species.
compositionMap getMassFractionsByName (double threshold=0.0) const
Get the mass fractions by name.
doublereal massFraction (size_t k) const
Return the mass fraction of a single species.
doublereal massFraction (const std::string &name) const
Return the mass fraction of a single species.
void getMoleFractions (doublereal *const x) const
Get the species mole fraction vector.
virtual void setMoleFractions (const doublereal *const x)
Set the mole fractions to the specified values.
virtual void setMoleFractions_NoNorm (const doublereal *const x)
Set the mole fractions to the specified values without normalizing.
void getMassFractions (doublereal *const y) const
Get the species mass fractions.
const doublereal * massFractions () const
Return a const pointer to the mass fraction array.
virtual void setMassFractions (const doublereal *const y)
Set the mass fractions to the specified values and normalize them.
virtual void setMassFractions_NoNorm (const doublereal *const y)
Set the mass fractions to the specified values without normalizing.
void getConcentrations (doublereal *const c) const
Get the species concentrations (kmol/m^3).
doublereal concentration (const size_t k) const
Concentration of species k.
virtual void setConcentrations (const doublereal *const conc)
Set the concentrations to the specified values within the phase.
virtual void setConcentrationsNoNorm (const double *const conc)
Set the concentrations without ignoring negative concentrations.
doublereal elementalMassFraction (const size_t m) const
Elemental mass fraction of element m.
doublereal elementalMoleFraction (const size_t m) const
Elemental mole fraction of element m.
const doublereal * moleFractdivMMW () const
Returns a const pointer to the start of the moleFraction/MW array.
doublereal temperature () const
Temperature (K).
virtual doublereal density () const
Density (kg/m^3).
doublereal molarDensity () const
Molar density (kmol/m^3).
doublereal molarVolume () const
Molar volume (m^3/kmol).
doublereal mean_X (const doublereal *const Q) const
Evaluate the mole-fraction-weighted mean of an array Q.
doublereal mean_X (const vector_fp &Q) const
Evaluate the mole-fraction-weighted mean of an array Q.
doublereal meanMolecularWeight () const
The mean molecular weight. Units: (kg/kmol)
doublereal sum_xlogx () const
Evaluate \(\sum_k X_k \log X_k \).
size_t addElement (const std::string &symbol, doublereal weight=-12345.0, int atomicNumber=0, doublereal entropy298=ENTROPY298_UNKNOWN, int elem_type=CT_ELEM_TYPE_ABSPOS)
Add an element.
shared_ptr< Species > species (const std::string &name) const
Return the Species object for the named species.
shared_ptr< Species > species (size_t k) const
Return the Species object for species whose index is k.
void ignoreUndefinedElements ()
Set behavior when adding a species containing undefined elements to just skip the species.
void addUndefinedElements ()
Set behavior when adding a species containing undefined elements to add those elements to the phase.
void throwUndefinedElements ()
Set the behavior when adding a species containing undefined elements to throw an exception.
Private Member Functions
void _updateThermo () const
Function to call through to m_spthermo->update and fill m_h0_RT, m_cp0_R, m_g0_RT, m_s0_R.
doublereal s () const
doublereal fm (const doublereal r) const
doublereal p (const doublereal r) const
Private Attributes
doublereal m_Pcurrent
m_Pcurrent = The current pressure.
vector_fp m_h0_RT
Vector containing the species reference enthalpies at T = m_tlast.
vector_fp m_cp0_R
Vector containing the species reference constant pressure heat capacities at T = m_tlast.
vector_fp m_g0_RT
Vector containing the species reference Gibbs functions at T = m_tlast.
vector_fp m_s0_R
Vector containing the species reference entropies at T = m_tlast.
doublereal h_mixing
Value of the enthalpy change on mixing due to protons changing from type B to type A configurations.
int product_species_index
Index of the species whose mole fraction defines the extent of reduction r.
int reactant_species_index
Additional Inherited Members
Protected Member Functions inherited from VPStandardStateTP
virtual void _updateStandardStateThermo () const
Updates the standard state thermodynamic functions at the current T and P of the solution.
virtual void invalidateCache ()
Invalidate any cached values which are normally updated only when a change in state is detected.
const vector_fp & Gibbs_RT_ref () const
Protected Member Functions inherited from ThermoPhase
virtual void getCsvReportData (std::vector< std::string > &names, std::vector< vector_fp > &data) const
Fills names and data with the column names and species thermo properties to be included in the output of the reportCSV method.
Protected Member Functions inherited from Phase
void setMolecularWeight (const int k, const double mw)
Set the molecular weight of a single species to a given value.
virtual void compositionChanged ()
Apply changes to the state which are needed after the composition changes.
Protected Attributes inherited from VPStandardStateTP
doublereal m_Pcurrent
Current value of the pressure - state variable.
doublereal m_Tlast_ss
The last temperature at which the standard statethermodynamic properties were calculated at.
doublereal m_Plast_ss
The last pressure at which the Standard State thermodynamic properties were calculated at.
std::vector< std::unique_ptr< PDSS > > m_PDSS_storage
Storage for the PDSS objects for the species.
vector_fp m_h0_RT
Vector containing the species reference enthalpies at T = m_tlast and P = p_ref.
vector_fp m_cp0_R
Vector containing the species reference constant pressure heat capacities at T = m_tlast and P = p_ref.
vector_fp m_g0_RT
Vector containing the species reference Gibbs functions at T = m_tlast and P = p_ref.
vector_fp m_s0_R
Vector containing the species reference entropies at T = m_tlast and P = p_ref.
vector_fp m_V0
Vector containing the species reference molar volumes.
vector_fp m_hss_RT
Vector containing the species Standard State enthalpies at T = m_tlast and P = m_plast.
vector_fp m_cpss_R
Vector containing the species Standard State constant pressure heat capacities at T = m_tlast and P = m_plast.
vector_fp m_gss_RT
Vector containing the species Standard State Gibbs functions at T = m_tlast and P = m_plast.
vector_fp m_sss_R
Vector containing the species Standard State entropies at T = m_tlast and P = m_plast.
vector_fp m_Vss
Vector containing the species standard state volumes at T = m_tlast and P = m_plast.
Protected Attributes inherited from ThermoPhase
MultiSpeciesThermo m_spthermo
Pointer to the calculation manager for species reference-state thermodynamic properties.
std::vector< const XML_Node * > m_speciesData
Vector of pointers to the species databases.
doublereal m_phi
Stored value of the electric potential for this phase. Units are Volts.
vector_fp m_lambdaRRT
Vector of element potentials.
bool m_hasElementPotentials
Boolean indicating whether there is a valid set of saved element potentials for this phase.
bool m_chargeNeutralityNecessary
Boolean indicating whether a charge neutrality condition is a necessity.
int m_ssConvention
Contains the standard state convention.
doublereal m_tlast
last value of the temperature processed by reference state
Protected Attributes inherited from Phase
ValueCache m_cache
Cached for saved calculations within each ThermoPhase.
size_t m_kk
Number of species in the phase.
size_t m_ndim
Dimensionality of the phase.
vector_fp m_speciesComp
Atomic composition of the species.
vector_fp m_speciesCharge
Vector of species charges. length m_kk.
std::map< std::string, shared_ptr< Species > > m_species
UndefElement::behavior m_undefinedElementBehavior
Flag determining behavior when adding species with an undefined element.
Detailed Description
Class MaskellSolidSolnPhase represents a condensed phase non-ideal solution with 2 species following the thermodynamic model described in Maskell, Shaw, and Tye, Manganese Dioxide Electrode – IX, Electrochimica Acta 28(2) pp 231-235, 1983.
Definition at line 27 of file MaskellSolidSolnPhase.h.
Member Function Documentation
type()
virtual std::string type () const inline virtual
String indicating the thermodynamic model implemented.
Usually corresponds to the name of the derived class, less any suffixes such as "Phase", TP", "VPSS", etc.
Reimplemented from ThermoPhase.
Definition at line 32 of file MaskellSolidSolnPhase.h.
getActivityConcentrations()
void getActivityConcentrations (doublereal * c) const virtual
This method returns an array of generalized concentrations.
\(C^a_k\) are defined such that \(a_k = C^a_k / C^0_k, \) where \(C^0_k \) is a standard concentration defined below and \(a_k \) are activities used in the thermodynamic functions. These activity (or generalized) concentrations are used by kinetics manager classes to compute the forward and reverse rates of elementary reactions. Note that they may or may not have units of concentration — they might be partial pressures, mole fractions, or surface coverages, for example.
Parameters
c Output array of generalized concentrations. The units depend upon the implementation of the reaction rate expressions within the phase.
Reimplemented from ThermoPhase.
Definition at line 32 of file MaskellSolidSolnPhase.cpp.
References MaskellSolidSolnPhase::getActivityCoefficients(), Phase::m_kk, and Phase::moleFraction().
standardConcentration()
virtual doublereal standardConcentration (size_t k = 0) const inline virtual
Return the standard concentration for the kth species.
The standard concentration \(C^0_k \) used to normalize the activity (i.e., generalized) concentration. In many cases, this quantity will be the same for all species in a phase - for example, for an ideal gas \(C^0_k = P/\hat R T \). For this reason, this method returns a single value, instead of an array. However, for phases in which the standard concentration is species-specific (e.g. surface species of different sizes), this method may be called with an optional parameter indicating the species.
Parameters
k Optional parameter indicating the species. The default is to assume this refers to species 0.
Returns
Returns the standard concentration. The units are by definition dependent on the ThermoPhase and kinetics manager representation.
Reimplemented from ThermoPhase.
Definition at line 37 of file MaskellSolidSolnPhase.h.
logStandardConc()
virtual doublereal logStandardConc (size_t k = 0) const inline virtual
Natural logarithm of the standard concentration of the kth species.
Parameters
k index of the species (defaults to zero)
Reimplemented from ThermoPhase.
Definition at line 38 of file MaskellSolidSolnPhase.h.
enthalpy_mole()
doublereal enthalpy_mole () const virtual
Molar enthalpy. Units: J/kmol.
Reimplemented from ThermoPhase.
Definition at line 42 of file MaskellSolidSolnPhase.cpp.
References MaskellSolidSolnPhase::_updateThermo(), MaskellSolidSolnPhase::h_mixing, MaskellSolidSolnPhase::m_h0_RT, Phase::mean_X(), Phase::moleFraction(), MaskellSolidSolnPhase::product_species_index, and ThermoPhase::RT().
entropy_mole()
doublereal entropy_mole () const virtual
Molar entropy. Units: J/kmol/K.
Reimplemented from ThermoPhase.
Definition at line 56 of file MaskellSolidSolnPhase.cpp.
References MaskellSolidSolnPhase::_updateThermo().
pressure()
virtual doublereal pressure () const inline virtual
Pressure.
Units: Pa. For this incompressible system, we return the internally stored independent value of the pressure.
Reimplemented from VPStandardStateTP.
Definition at line 62 of file MaskellSolidSolnPhase.h.
References MaskellSolidSolnPhase::m_Pcurrent.
Referenced by MaskellSolidSolnPhase::getActivityCoefficients().
setPressure()
void setPressure (doublereal p) virtual
Set the pressure at constant temperature.
Units: Pa. This method sets a constant within the object. The mass density is not a function of pressure.
Parameters
p Input Pressure (Pa)
Reimplemented from VPStandardStateTP.
Definition at line 93 of file MaskellSolidSolnPhase.cpp.
References MaskellSolidSolnPhase::m_Pcurrent.
setDensity()
void setDensity (const doublereal rho) virtual
Overridden setDensity() function is necessary because the density is not an independent variable.
This function will now throw an error condition
Parameters
rho Input density
Reimplemented from Phase.
Definition at line 68 of file MaskellSolidSolnPhase.cpp.
References Phase::density().
calcDensity()
void calcDensity () virtual
Calculate the density of the mixture using the partial molar volumes and mole fractions as input.
The formula for this is
\[ \rho = \frac{\sum_k{X_k W_k}}{\sum_k{X_k V_k}} \]
where \(X_k\) are the mole fractions, \(W_k\) are the molecular weights, and \(V_k\) are the pure species molar volumes.
Note, the basis behind this formula is that in an ideal solution the partial molar volumes are equal to the pure species molar volumes. We have additionally specified in this class that the pure species molar volumes are independent of temperature and pressure.
NOTE: This function is not a member of the ThermoPhase base class.
Reimplemented from VPStandardStateTP.
Definition at line 80 of file MaskellSolidSolnPhase.cpp.
References Phase::getMoleFractions(), VPStandardStateTP::getStandardVolumes(), Phase::m_kk, Phase::meanMolecularWeight(), and Phase::setDensity().
setMolarDensity()
void setMolarDensity (const doublereal rho) virtual
Overridden setMolarDensity() function is necessary because the density is not an independent variable.
This function will now throw an error condition.
Parameters
rho Input Density
Reimplemented from Phase.
Definition at line 98 of file MaskellSolidSolnPhase.cpp.
getActivityCoefficients()
void getActivityCoefficients (doublereal * ac) const virtual
Get the array of non-dimensional molar-based activity coefficients at the current solution temperature, pressure, and solution concentration.
Parameters
ac Output vector of activity coefficients. Length: m_kk.
Reimplemented from ThermoPhase.
Definition at line 106 of file MaskellSolidSolnPhase.cpp.
References MaskellSolidSolnPhase::_updateThermo(), ValueCache::getArray(), ValueCache::getId(), Phase::m_cache, Phase::moleFraction(), MaskellSolidSolnPhase::pressure(), MaskellSolidSolnPhase::product_species_index, Phase::stateMFNumber(), Phase::temperature(), CachedValue< T >::validate(), and CachedValue< T >::value.
Referenced by MaskellSolidSolnPhase::getActivityConcentrations().
getChemPotentials()
void getChemPotentials (doublereal * mu) const virtual
Get the species chemical potentials. Units: J/kmol.
This function returns a vector of chemical potentials of the species in solution at the current temperature, pressure and mole fraction of the solution.
Parameters
mu Output vector of species chemical potentials. Length: m_kk. Units: J/kmol
Reimplemented from ThermoPhase.
Definition at line 126 of file MaskellSolidSolnPhase.cpp.
References MaskellSolidSolnPhase::_updateThermo(), MaskellSolidSolnPhase::h_mixing, MaskellSolidSolnPhase::m_g0_RT, Phase::moleFraction(), MaskellSolidSolnPhase::product_species_index, and ThermoPhase::RT().
Referenced by MaskellSolidSolnPhase::getChemPotentials_RT().
getChemPotentials_RT()
void getChemPotentials_RT (doublereal * mu) const virtual
Get the array of non-dimensional species chemical potentials.
These are partial molar Gibbs free energies, \(\mu_k / \hat R T \).
We close the loop on this function, here, calling getChemPotentials() and then dividing by RT. No need for child classes to handle.
Parameters
mu Output vector of non-dimensional species chemical potentials Length: m_kk.
Reimplemented from VPStandardStateTP.
Definition at line 140 of file MaskellSolidSolnPhase.cpp.
References MaskellSolidSolnPhase::getChemPotentials(), Phase::m_kk, and ThermoPhase::RT().
getPartialMolarEnthalpies()
void getPartialMolarEnthalpies (doublereal * hbar) const virtual
Returns an array of partial molar enthalpies for the species in the mixture.
Units (J/kmol)
Parameters
hbar Output vector of species partial molar enthalpies. Length: m_kk. units are J/kmol.
Reimplemented from ThermoPhase.
Definition at line 150 of file MaskellSolidSolnPhase.cpp.
getPartialMolarEntropies()
void getPartialMolarEntropies (doublereal * sbar) const virtual
Returns an array of partial molar entropies of the species in the solution.
Units: J/kmol/K.
Parameters
sbar Output vector of species partial molar entropies. Length = m_kk. units are J/kmol/K.
Reimplemented from ThermoPhase.
Definition at line 155 of file MaskellSolidSolnPhase.cpp.
getPartialMolarCp()
void getPartialMolarCp (doublereal * cpbar) const virtual
Return an array of partial molar heat capacities for the species in the mixture.
Units: J/kmol/K
Parameters
cpbar Output vector of species partial molar heat capacities at constant pressure. Length = m_kk. units are J/kmol/K.
Reimplemented from ThermoPhase.
Definition at line 160 of file MaskellSolidSolnPhase.cpp.
getPartialMolarVolumes()
void getPartialMolarVolumes (doublereal * vbar) const virtual
Return an array of partial molar volumes for the species in the mixture.
Units: m^3/kmol.
Parameters
vbar Output vector of species partial molar volumes. Length = m_kk. units are m^3/kmol.
Reimplemented from ThermoPhase.
Definition at line 165 of file MaskellSolidSolnPhase.cpp.
References VPStandardStateTP::getStandardVolumes().
getPureGibbs()
void getPureGibbs (doublereal * gpure) const virtual
Get the Gibbs functions for the standard state of the species at the current T and P of the solution.
Units are Joules/kmol
Parameters
gpure Output vector of standard state Gibbs free energies. Length: m_kk.
Reimplemented from VPStandardStateTP.
Definition at line 170 of file MaskellSolidSolnPhase.cpp.
References MaskellSolidSolnPhase::_updateThermo(), MaskellSolidSolnPhase::m_g0_RT, Phase::m_kk, and ThermoPhase::RT().
Referenced by MaskellSolidSolnPhase::getStandardChemPotentials().
getStandardChemPotentials()
void getStandardChemPotentials (doublereal * mu) const virtual
Get the array of chemical potentials at unit activity for the species at their standard states at the current T and P of the solution.
These are the standard state chemical potentials \(\mu^0_k(T,P) \). The values are evaluated at the current temperature and pressure of the solution
Parameters
mu Output vector of chemical potentials. Length: m_kk.
Reimplemented from VPStandardStateTP.
Definition at line 178 of file MaskellSolidSolnPhase.cpp.
References MaskellSolidSolnPhase::getPureGibbs().
initThermoXML()
void initThermoXML (XML_Node & phaseNode, const std::string & id) virtual
Import and initialize a ThermoPhase object using an XML tree.
Here we read extra information about the XML description of a phase. Regular information about elements and species and their reference state thermodynamic information have already been read at this point. For example, we do not need to call this function for ideal gas equations of state. This function is called from importPhase() after the elements and the species are initialized with default ideal solution level data.
The default implementation in ThermoPhase calls the virtual function initThermo() and then sets the "state" of the phase by looking for an XML element named "state", and then interpreting its contents by calling the virtual function setStateFromXML().
Parameters
phaseNode This object must be the phase node of a complete XML tree description of the phase, including all of the species data. In other words while "phase" must point to an XML phase object, it must have sibling nodes "speciesData" that describe the species in the phase.
id ID of the phase. If nonnull, a check is done to see if phaseNode is pointing to the phase with the correct id.
Reimplemented from ThermoPhase.
Definition at line 187 of file MaskellSolidSolnPhase.cpp.
References Cantera::caseInsensitiveEquals(), XML_Node::child(), Cantera::fpValue(), XML_Node::hasChild(), XML_Node::id(), ThermoPhase::initThermoXML(), Phase::m_kk, MaskellSolidSolnPhase::setProductSpecies(), Phase::speciesName(), and XML_Node::value().
setProductSpecies()
void setProductSpecies (const std::string & name)
Set the product Species. Must be called after species have been added.
Definition at line 231 of file MaskellSolidSolnPhase.cpp.
References Phase::name(), MaskellSolidSolnPhase::product_species_index, and Phase::speciesIndex().
Referenced by MaskellSolidSolnPhase::initThermoXML().
_updateThermo()
void _updateThermo () const private
Function to call through to m_spthermo->update and fill m_h0_RT, m_cp0_R, m_g0_RT, m_s0_R.
Definition at line 241 of file MaskellSolidSolnPhase.cpp.
References ValueCache::getId(), ValueCache::getScalar(), Phase::m_cache, MaskellSolidSolnPhase::m_cp0_R, MaskellSolidSolnPhase::m_g0_RT, MaskellSolidSolnPhase::m_h0_RT, Phase::m_kk, MaskellSolidSolnPhase::m_s0_R, ThermoPhase::m_spthermo, Phase::temperature(), MultiSpeciesThermo::update(), and CachedValue< T >::validate().
Referenced by MaskellSolidSolnPhase::enthalpy_mole(), MaskellSolidSolnPhase::entropy_mole(), MaskellSolidSolnPhase::getActivityCoefficients(), MaskellSolidSolnPhase::getChemPotentials(), and MaskellSolidSolnPhase::getPureGibbs().
Member Data Documentation
m_Pcurrent
doublereal m_Pcurrent private
m_Pcurrent = The current pressure.
Since the density isn't a function of pressure, but only of the mole fractions, we need to independently specify the pressure.
Definition at line 137 of file MaskellSolidSolnPhase.h.
Referenced by MaskellSolidSolnPhase::pressure(), and MaskellSolidSolnPhase::setPressure().
m_h0_RT
vector_fp m_h0_RT mutable private
Vector containing the species reference enthalpies at T = m_tlast.
Definition at line 146 of file MaskellSolidSolnPhase.h.
Referenced by MaskellSolidSolnPhase::_updateThermo(), and MaskellSolidSolnPhase::enthalpy_mole().
m_cp0_R
vector_fp m_cp0_R mutable private
Vector containing the species reference constant pressure heat capacities at T = m_tlast.
Definition at line 150 of file MaskellSolidSolnPhase.h.
Referenced by MaskellSolidSolnPhase::_updateThermo().
m_g0_RT
vector_fp m_g0_RT mutable private
Vector containing the species reference Gibbs functions at T = m_tlast.
Definition at line 153 of file MaskellSolidSolnPhase.h.
Referenced by MaskellSolidSolnPhase::_updateThermo(), MaskellSolidSolnPhase::getChemPotentials(), and MaskellSolidSolnPhase::getPureGibbs().
m_s0_R
vector_fp m_s0_R mutable private
Vector containing the species reference entropies at T = m_tlast.
Definition at line 156 of file MaskellSolidSolnPhase.h.
Referenced by MaskellSolidSolnPhase::_updateThermo().
h_mixing
doublereal h_mixing private
Value of the enthalpy change on mixing due to protons changing from type B to type A configurations.
Definition at line 160 of file MaskellSolidSolnPhase.h.
Referenced by MaskellSolidSolnPhase::enthalpy_mole(), and MaskellSolidSolnPhase::getChemPotentials().
product_species_index
int product_species_index private
Index of the species whose mole fraction defines the extent of reduction r.
Definition at line 163 of file MaskellSolidSolnPhase.h.
Referenced by MaskellSolidSolnPhase::enthalpy_mole(), MaskellSolidSolnPhase::getActivityCoefficients(), MaskellSolidSolnPhase::getChemPotentials(), and MaskellSolidSolnPhase::setProductSpecies().
The documentation for this class was generated from the following files:
MaskellSolidSolnPhase.h
MaskellSolidSolnPhase.cpp