Cantera: ReactorBase Class Reference
ReactorBase Class Reference
Base class for stirred reactors.
#include <ReactorBase.h>
Public Member Functions
ReactorBase (const std::string &name="(none)")
ReactorBase (const ReactorBase &)=delete
ReactorBase & operator= (const ReactorBase &)=delete
virtual int type () const
Return a constant indicating the type of this Reactor.
std::string name () const
Return the name of this reactor.
void setName (const std::string &name)
Set the name of this reactor.
void restoreState ()
Set the state of the Phase object associated with this reactor to the reactor's current state.
virtual void syncState ()
Set the state of the reactor to correspond to the state of the associated ThermoPhase object.
thermo_t & contents ()
return a reference to the contents.
const thermo_t & contents () const
doublereal residenceTime ()
Return the residence time (s) of the contents of this reactor, based on the outlet mass flow rates and the mass of the reactor contents.
ReactorNet & network ()
The ReactorNet that this reactor belongs to.
void setNetwork (ReactorNet *net)
Set the ReactorNet that this reactor belongs to.
Methods to set up a simulation.
void setInitialVolume (doublereal vol)
Set the initial reactor volume. By default, the volume is 1.0 m^3.
virtual void setThermoMgr (thermo_t &thermo)
Specify the mixture contained in the reactor.
void addInlet (FlowDevice &inlet)
Connect an inlet FlowDevice to this reactor.
void addOutlet (FlowDevice &outlet)
Connect an outlet FlowDevice to this reactor.
FlowDevice & inlet (size_t n=0)
Return a reference to the n-th inlet FlowDevice connected to this reactor.
FlowDevice & outlet (size_t n=0)
Return a reference to the n-th outlet FlowDevice connected to this reactor.
size_t nInlets ()
Return the number of inlet FlowDevice objects connected to this reactor.
size_t nOutlets ()
Return the number of outlet FlowDevice objects connected to this reactor.
size_t nWalls ()
Return the number of Wall objects connected to this reactor.
void addWall (Wall &w, int lr)
Insert a Wall between this reactor and another reactor.
Wall & wall (size_t n)
Return a reference to the n-th Wall connected to this reactor.
void addSurface (ReactorSurface *surf)
ReactorSurface * surface (size_t n)
Return a reference to the n-th ReactorSurface connected to this reactor.
virtual void initialize (doublereal t0=0.0)
Initialize the reactor.
Solution components.
The values returned are those after the last call to ReactorNet::advance or ReactorNet::step.
doublereal volume () const
Returns the current volume (m^3) of the reactor.
doublereal density () const
Returns the current density (kg/m^3) of the reactor's contents.
doublereal temperature () const
Returns the current temperature (K) of the reactor's contents.
doublereal enthalpy_mass () const
Returns the current enthalpy (J/kg) of the reactor's contents.
doublereal intEnergy_mass () const
Returns the current internal energy (J/kg) of the reactor's contents.
doublereal pressure () const
Returns the current pressure (Pa) of the reactor.
doublereal mass () const
Returns the mass (kg) of the reactor's contents.
const doublereal * massFractions () const
Return the vector of species mass fractions.
doublereal massFraction (size_t k) const
Return the mass fraction of the k-th species.
Protected Attributes
size_t m_nsp
Number of homogeneous species in the mixture.
thermo_t * m_thermo
doublereal m_vol
doublereal m_enthalpy
doublereal m_intEnergy
doublereal m_pressure
vector_fp m_state
std::vector< FlowDevice * > m_inlet
std::vector< FlowDevice * > m_outlet
std::vector< Wall * > m_wall
std::vector< ReactorSurface * > m_surfaces
vector_int m_lr
std::string m_name
ReactorNet * m_net
The ReactorNet that this reactor is part of.
Detailed Description
Base class for stirred reactors.
Allows using any substance model, with arbitrary inflow, outflow, heat loss/gain, surface chemistry, and volume change.
Definition at line 44 of file ReactorBase.h.
Member Function Documentation
type()
virtual int type () const inline virtual
Return a constant indicating the type of this Reactor.
Reimplemented in Reactor, ConstPressureReactor, IdealGasConstPressureReactor, IdealGasReactor, and FlowReactor.
Definition at line 53 of file ReactorBase.h.
name()
std::string name () const inline
Return the name of this reactor.
Definition at line 58 of file ReactorBase.h.
Referenced by Reactor::addSensitivityReaction(), Reactor::addSensitivitySpeciesEnthalpy(), and ReactorBase::setName().
setName()
void setName (const std::string & name) inline
Set the name of this reactor.
Definition at line 63 of file ReactorBase.h.
References ReactorBase::name().
setInitialVolume()
void setInitialVolume (doublereal vol) inline
Set the initial reactor volume. By default, the volume is 1.0 m^3.
Definition at line 71 of file ReactorBase.h.
setThermoMgr()
void setThermoMgr (thermo_t & thermo) virtual
Specify the mixture contained in the reactor.
Note that a pointer to this substance is stored, and as the integration proceeds, the state of the substance is modified.
Reimplemented in IdealGasConstPressureReactor, and IdealGasReactor.
Definition at line 26 of file ReactorBase.cpp.
References ThermoPhase::enthalpy_mass(), ThermoPhase::intEnergy_mass(), ReactorBase::m_nsp, Phase::nSpecies(), ThermoPhase::pressure(), and Phase::saveState().
addInlet()
void addInlet (FlowDevice & inlet)
Connect an inlet FlowDevice to this reactor.
Definition at line 47 of file ReactorBase.cpp.
References ReactorBase::inlet().
Referenced by FlowDevice::install().
addOutlet()
void addOutlet (FlowDevice & outlet)
Connect an outlet FlowDevice to this reactor.
Definition at line 52 of file ReactorBase.cpp.
References ReactorBase::outlet().
Referenced by FlowDevice::install().
inlet()
FlowDevice & inlet (size_t n = 0)
Return a reference to the n-th inlet FlowDevice connected to this reactor.
Definition at line 109 of file ReactorBase.cpp.
Referenced by ReactorBase::addInlet().
outlet()
FlowDevice & outlet (size_t n = 0)
Return a reference to the n-th outlet FlowDevice connected to this reactor.
Definition at line 113 of file ReactorBase.cpp.
Referenced by ReactorBase::addOutlet().
nInlets()
size_t nInlets () inline
Return the number of inlet FlowDevice objects connected to this reactor.
Definition at line 95 of file ReactorBase.h.
nOutlets()
size_t nOutlets () inline
Return the number of outlet FlowDevice objects connected to this reactor.
Definition at line 101 of file ReactorBase.h.
nWalls()
size_t nWalls () inline
Return the number of Wall objects connected to this reactor.
Definition at line 106 of file ReactorBase.h.
addWall()
void addWall (Wall & w, int lr)
Insert a Wall between this reactor and another reactor.
lr = 0 if this reactor is to the left of the wall and lr = 1 if this reactor is to the right of the wall. This method is called automatically for both the left and right reactors by Wall::install.
Definition at line 57 of file ReactorBase.cpp.
Referenced by Wall::install().
wall()
Wall & wall (size_t n)
Return a reference to the n-th Wall connected to this reactor.
Definition at line 67 of file ReactorBase.cpp.
surface()
ReactorSurface * surface (size_t n)
Return a reference to the n-th ReactorSurface connected to this reactor.
Definition at line 80 of file ReactorBase.cpp.
initialize()
virtual void initialize (doublereal t0 = 0.0) inline virtual
Initialize the reactor.
Called automatically by ReactorNet::initialize.
Reimplemented in Reactor, IdealGasConstPressureReactor, ConstPressureReactor, IdealGasReactor, and FlowReactor.
Definition at line 130 of file ReactorBase.h.
restoreState()
void restoreState () inline
Set the state of the Phase object associated with this reactor to the reactor's current state.
Definition at line 138 of file ReactorBase.h.
References Phase::restoreState().
syncState()
void syncState () virtual
Set the state of the reactor to correspond to the state of the associated ThermoPhase object.
This is the inverse of restoreState(). Calling this will trigger integrator reinitialization.
Reimplemented in Reactor.
Definition at line 36 of file ReactorBase.cpp.
References ThermoPhase::enthalpy_mass(), ThermoPhase::intEnergy_mass(), ReactorBase::m_net, ThermoPhase::pressure(), Phase::saveState(), and ReactorNet::setNeedsReinit().
Referenced by Reactor::syncState().
contents()
thermo_t& contents () inline
return a reference to the contents.
Definition at line 151 of file ReactorBase.h.
Referenced by FlowDevice::install().
residenceTime()
doublereal residenceTime ()
Return the residence time (s) of the contents of this reactor, based on the outlet mass flow rates and the mass of the reactor contents.
Definition at line 100 of file ReactorBase.cpp.
References ReactorBase::mass().
volume()
doublereal volume () const inline
Returns the current volume (m^3) of the reactor.
Definition at line 179 of file ReactorBase.h.
density()
doublereal density () const inline
Returns the current density (kg/m^3) of the reactor's contents.
Definition at line 184 of file ReactorBase.h.
Referenced by ReactorBase::mass().
temperature()
doublereal temperature () const inline
Returns the current temperature (K) of the reactor's contents.
Definition at line 189 of file ReactorBase.h.
Referenced by Wall::Q().
enthalpy_mass()
doublereal enthalpy_mass () const inline
Returns the current enthalpy (J/kg) of the reactor's contents.
Definition at line 194 of file ReactorBase.h.
Referenced by FlowDevice::enthalpy_mass().
intEnergy_mass()
doublereal intEnergy_mass () const inline
Returns the current internal energy (J/kg) of the reactor's contents.
Definition at line 199 of file ReactorBase.h.
pressure()
doublereal pressure () const inline
Returns the current pressure (Pa) of the reactor.
Definition at line 204 of file ReactorBase.h.
Referenced by PressureController::updateMassFlowRate(), Valve::updateMassFlowRate(), and Wall::vdot().
mass()
doublereal mass () const inline
Returns the mass (kg) of the reactor's contents.
Definition at line 209 of file ReactorBase.h.
References ReactorBase::density().
Referenced by ReactorBase::residenceTime().
massFractions()
const doublereal* massFractions () const inline
Return the vector of species mass fractions.
Definition at line 214 of file ReactorBase.h.
massFraction()
doublereal massFraction (size_t k) const inline
Return the mass fraction of the k-th species.
Definition at line 219 of file ReactorBase.h.
Referenced by FlowDevice::outletSpeciesMassFlowRate().
network()
ReactorNet & network ()
The ReactorNet that this reactor belongs to.
Definition at line 85 of file ReactorBase.cpp.
References ReactorBase::m_net.
Referenced by Reactor::addSensitivityReaction(), and Reactor::addSensitivitySpeciesEnthalpy().
setNetwork()
void setNetwork (ReactorNet * net)
Set the ReactorNet that this reactor belongs to.
Definition at line 95 of file ReactorBase.cpp.
References ReactorBase::m_net.
Referenced by ReactorNet::addReactor().
Member Data Documentation
m_nsp
size_t m_nsp protected
Number of homogeneous species in the mixture.
Definition at line 233 of file ReactorBase.h.
Referenced by FlowReactor::evalEqs(), Reactor::evalEqs(), Reactor::getState(), FlowReactor::initialize(), Reactor::initialize(), ReactorBase::setThermoMgr(), and Reactor::speciesIndex().
m_net
ReactorNet* m_net protected
The ReactorNet that this reactor is part of.
Definition at line 248 of file ReactorBase.h.
Referenced by ReactorBase::network(), ReactorBase::setNetwork(), and ReactorBase::syncState().
The documentation for this class was generated from the following files:
ReactorBase.h
ReactorBase.cpp