Cantera: Arrhenius Class Reference
Arrhenius Class Reference
Arrhenius reaction rate type depends only on temperature.
#include <RxnRates.h>
Public Member Functions
Arrhenius ()
Default constructor.
Arrhenius (doublereal A, doublereal b, doublereal E)
Constructor.
void update_C (const doublereal *c)
Update concentration-dependent parts of the rate coefficient.
doublereal updateLog (doublereal logT, doublereal recipT) const
Update the value of the natural logarithm of the rate constant.
doublereal updateRC (doublereal logT, doublereal recipT) const
Update the value the rate constant.
double preExponentialFactor () const
Return the pre-exponential factor A (in m, kmol, s to powers depending on the reaction order)
double temperatureExponent () const
Return the temperature exponent b
doublereal activationEnergy_R () const
Return the activation energy divided by the gas constant (i.e.
Static Public Member Functions
static int type ()
return the rate coefficient type.
Protected Attributes
doublereal m_logA
doublereal m_b
doublereal m_E
doublereal m_A
Detailed Description
Arrhenius reaction rate type depends only on temperature.
A reaction rate coefficient of the following form.
\[ k_f = A T^b \exp (-E/RT) \]
Definition at line 30 of file RxnRates.h.
Constructor & Destructor Documentation
Arrhenius() [1/2]
Arrhenius ()
Default constructor.
Definition at line 11 of file RxnRates.cpp.
Arrhenius() [2/2]
Arrhenius (doublereal A, doublereal b, doublereal E)
Constructor.
Parameters
A pre-exponential. The unit system is (kmol, m, s). The actual units depend on the reaction order and the dimensionality (surface or bulk).
b Temperature exponent. Non-dimensional.
E Activation energy in temperature units. Kelvin.
Definition at line 19 of file RxnRates.cpp.
Member Function Documentation
type()
static int type () inline static
return the rate coefficient type.
Definition at line 34 of file RxnRates.h.
update_C()
void update_C (const doublereal * c) inline
Update concentration-dependent parts of the rate coefficient.
For this class, there are no concentration-dependent parts, so this method does nothing.
Definition at line 54 of file RxnRates.h.
updateLog()
doublereal updateLog (doublereal logT, doublereal recipT) const inline
Update the value of the natural logarithm of the rate constant.
Definition at line 60 of file RxnRates.h.
updateRC()
doublereal updateRC (doublereal logT, doublereal recipT) const inline
Update the value the rate constant.
This function returns the actual value of the rate constant. It can be safely called for negative values of the pre-exponential factor.
Definition at line 70 of file RxnRates.h.
preExponentialFactor()
double preExponentialFactor () const inline
Return the pre-exponential factor A (in m, kmol, s to powers depending on the reaction order)
Definition at line 76 of file RxnRates.h.
Referenced by InterfaceKinetics::buildSurfaceArrhenius(), ElementaryReaction::validate(), and FalloffReaction::validate().
temperatureExponent()
double temperatureExponent () const inline
Return the temperature exponent b
Definition at line 81 of file RxnRates.h.
Referenced by InterfaceKinetics::buildSurfaceArrhenius().
activationEnergy_R()
doublereal activationEnergy_R () const inline
Return the activation energy divided by the gas constant (i.e.
the activation temperature) [K]
Definition at line 87 of file RxnRates.h.
Referenced by InterfaceKinetics::buildSurfaceArrhenius().
The documentation for this class was generated from the following files:
RxnRates.h
RxnRates.cpp