Cantera: MetalSHEelectrons Class Reference
MetalSHEelectrons Class Reference
Models of Phases of Matter » Thermodynamic Properties
Class MetalSHEelectrons represents electrons within a metal, adjacent to an aqueous electrolyte, that are consistent with the SHE reference electrode.
#include <MetalSHEelectrons.h>
Public Member Functions
MetalSHEelectrons ()
Default constructor for the MetalSHEelectrons class.
MetalSHEelectrons (const std::string &infile, const std::string &id="")
Construct and initialize a MetalSHEelectrons ThermoPhase object directly from an ASCII input file.
MetalSHEelectrons (XML_Node &phaseRef, const std::string &id="")
Construct and initialize a MetalSHEelectrons ThermoPhase object directly from an XML database.
virtual void initThermoXML (XML_Node &phaseNode, const std::string &id)
Import and initialize a ThermoPhase object using an XML tree.
virtual void setParameters (int n, doublereal *const c)
Set the equation of state parameters.
virtual void getParameters (int &n, doublereal *const c) const
Get the equation of state parameters in a vector.
virtual void setParametersFromXML (const XML_Node &eosdata)
Set equation of state parameter values from XML entries.
Mechanical Equation of State
virtual doublereal pressure () const
Report the Pressure. Units: Pa.
virtual void setPressure (doublereal p)
Set the pressure at constant temperature. Units: Pa.
virtual doublereal isothermalCompressibility () const
Returns the isothermal compressibility. Units: 1/Pa.
virtual doublereal thermalExpansionCoeff () const
Return the volumetric thermal expansion coefficient. Units: 1/K.
Activities, Standard States, and Activity Concentrations
This section is largely handled by parent classes, since there is only one species.
Therefore, the activity is equal to one.
virtual void getActivityConcentrations (doublereal *c) const
This method returns an array of generalized concentrations.
virtual doublereal standardConcentration (size_t k=0) const
Return the standard concentration for the kth species.
virtual doublereal logStandardConc (size_t k=0) const
Natural logarithm of the standard concentration of the kth species.
virtual void getStandardChemPotentials (doublereal *mu0) const
Get the array of chemical potentials at unit activity for the species at their standard states at the current T and P of the solution.
Properties of the Standard State of the Species in the Solution
virtual void getEnthalpy_RT (doublereal *hrt) const
Get the nondimensional Enthalpy functions for the species at their standard states at the current T and P of the solution.
virtual void getEntropy_R (doublereal *sr) const
Get the array of nondimensional Entropy functions for the standard state species at the current T and P of the solution.
virtual void getGibbs_RT (doublereal *grt) const
Get the nondimensional Gibbs functions for the species in their standard states at the current T and P of the solution.
virtual void getCp_R (doublereal *cpr) const
Get the nondimensional Heat Capacities at constant pressure for the species standard states at the current T and P of the solution.
virtual void getIntEnergy_RT (doublereal *urt) const
Returns the vector of nondimensional Internal Energies of the standard state species at the current T and P of the solution.
Thermodynamic Values for the Species Reference States
virtual void getIntEnergy_RT_ref (doublereal *urt) const
Returns the vector of nondimensional internal Energies of the reference state at the current temperature of the solution and the reference pressure for each species.
Public Member Functions inherited from SingleSpeciesTP
SingleSpeciesTP ()
Base empty constructor.
virtual std::string type () const
String indicating the thermodynamic model implemented.
virtual bool addSpecies (shared_ptr< Species > spec)
virtual doublereal enthalpy_mole () const
Molar enthalpy. Units: J/kmol.
virtual doublereal intEnergy_mole () const
Molar internal energy. Units: J/kmol.
virtual doublereal entropy_mole () const
Molar entropy. Units: J/kmol/K.
virtual doublereal gibbs_mole () const
Molar Gibbs function. Units: J/kmol.
virtual doublereal cp_mole () const
Molar heat capacity at constant pressure. Units: J/kmol/K.
virtual doublereal cv_mole () const
Molar heat capacity at constant volume. Units: J/kmol/K.
virtual void getActivities (doublereal *a) const
Get the array of non-dimensional activities at the current solution temperature, pressure, and solution concentration.
virtual void getActivityCoefficients (doublereal *ac) const
Get the array of non-dimensional molar-based activity coefficients at the current solution temperature, pressure, and solution concentration.
virtual void getChemPotentials_RT (doublereal *murt) const
Get the array of non-dimensional species chemical potentials.
virtual void getChemPotentials (doublereal *mu) const
Get the array of chemical potentials.
virtual void getPartialMolarEnthalpies (doublereal *hbar) const
Get the species partial molar enthalpies. Units: J/kmol.
virtual void getPartialMolarIntEnergies (doublereal *ubar) const
Get the species partial molar internal energies. Units: J/kmol.
virtual void getPartialMolarEntropies (doublereal *sbar) const
Get the species partial molar entropy. Units: J/kmol K.
virtual void getPartialMolarCp (doublereal *cpbar) const
Get the species partial molar Heat Capacities. Units: J/ kmol /K.
virtual void getPartialMolarVolumes (doublereal *vbar) const
Get the species partial molar volumes. Units: m^3/kmol.
virtual void getPureGibbs (doublereal *gpure) const
Get the Gibbs functions for the standard state of the species at the current T and P of the solution.
virtual void getStandardVolumes (doublereal *vbar) const
Get the molar volumes of each species in their standard states at the current T and P of the solution.
virtual void getEnthalpy_RT_ref (doublereal *hrt) const
Returns the vector of nondimensional enthalpies of the reference state at the current temperature of the solution and the reference pressure for the species.
virtual void getGibbs_RT_ref (doublereal *grt) const
Returns the vector of nondimensional Gibbs Free Energies of the reference state at the current temperature of the solution and the reference pressure for the species.
virtual void getGibbs_ref (doublereal *g) const
Returns the vector of the Gibbs function of the reference state at the current temperature of the solution and the reference pressure for the species.
virtual void getEntropy_R_ref (doublereal *er) const
Returns the vector of nondimensional entropies of the reference state at the current temperature of the solution and the reference pressure for each species.
virtual void getCp_R_ref (doublereal *cprt) const
Returns the vector of nondimensional constant pressure heat capacities of the reference state at the current temperature of the solution and reference pressure for each species.
virtual void setMassFractions (const doublereal *const y)
Mass fractions are fixed, with Y[0] = 1.0.
virtual void setMoleFractions (const doublereal *const x)
Mole fractions are fixed, with x[0] = 1.0.
virtual void setState_HP (double h, double p, double tol=1e-9)
Set the internally stored specific enthalpy (J/kg) and pressure (Pa) of the phase.
virtual void setState_UV (double u, double v, double tol=1e-9)
Set the specific internal energy (J/kg) and specific volume (m^3/kg).
virtual void setState_SP (double s, double p, double tol=1e-9)
Set the specific entropy (J/kg/K) and pressure (Pa).
virtual void setState_SV (double s, double v, double tol=1e-9)
Set the specific entropy (J/kg/K) and specific volume (m^3/kg).
Public Member Functions inherited from ThermoPhase
ThermoPhase ()
Constructor.
doublereal RT () const
Return the Gas Constant multiplied by the current temperature.
virtual doublereal refPressure () const
Returns the reference pressure in Pa.
virtual doublereal minTemp (size_t k=npos) const
Minimum temperature for which the thermodynamic data for the species or phase are valid.
doublereal Hf298SS (const size_t k) const
Report the 298 K Heat of Formation of the standard state of one species (J kmol-1)
virtual void modifyOneHf298SS (const size_t k, const doublereal Hf298New)
Modify the value of the 298 K Heat of Formation of one species in the phase (J kmol-1)
virtual void resetHf298 (const size_t k=npos)
Restore the original heat of formation of one or more species.
virtual doublereal maxTemp (size_t k=npos) const
Maximum temperature for which the thermodynamic data for the species are valid.
bool chargeNeutralityNecessary () const
Returns the chargeNeutralityNecessity boolean.
void setElectricPotential (doublereal v)
Set the electric potential of this phase (V).
doublereal electricPotential () const
Returns the electric potential of this phase (V).
virtual int activityConvention () const
This method returns the convention used in specification of the activities, of which there are currently two, molar- and molality-based conventions.
virtual int standardStateConvention () const
This method returns the convention used in specification of the standard state, of which there are currently two, temperature based, and variable pressure based.
virtual void getLnActivityCoefficients (doublereal *lnac) const
Get the array of non-dimensional molar-based ln activity coefficients at the current solution temperature, pressure, and solution concentration.
void getElectrochemPotentials (doublereal *mu) const
Get the species electrochemical potentials.
virtual void getStandardVolumes_ref (doublereal *vol) const
Get the molar volumes of the species reference states at the current T and P_ref of the solution.
doublereal enthalpy_mass () const
Specific enthalpy. Units: J/kg.
doublereal intEnergy_mass () const
Specific internal energy. Units: J/kg.
doublereal entropy_mass () const
Specific entropy. Units: J/kg/K.
doublereal gibbs_mass () const
Specific Gibbs function. Units: J/kg.
doublereal cp_mass () const
Specific heat at constant pressure. Units: J/kg/K.
doublereal cv_mass () const
Specific heat at constant volume. Units: J/kg/K.
virtual void setState_TPX (doublereal t, doublereal p, const doublereal *x)
Set the temperature (K), pressure (Pa), and mole fractions.
virtual void setState_TPX (doublereal t, doublereal p, const compositionMap &x)
Set the temperature (K), pressure (Pa), and mole fractions.
virtual void setState_TPX (doublereal t, doublereal p, const std::string &x)
Set the temperature (K), pressure (Pa), and mole fractions.
virtual void setState_TPY (doublereal t, doublereal p, const doublereal *y)
Set the internally stored temperature (K), pressure (Pa), and mass fractions of the phase.
virtual void setState_TPY (doublereal t, doublereal p, const compositionMap &y)
Set the internally stored temperature (K), pressure (Pa), and mass fractions of the phase.
virtual void setState_TPY (doublereal t, doublereal p, const std::string &y)
Set the internally stored temperature (K), pressure (Pa), and mass fractions of the phase.
virtual void setState_TP (doublereal t, doublereal p)
Set the temperature (K) and pressure (Pa)
virtual void setState_PX (doublereal p, doublereal *x)
Set the pressure (Pa) and mole fractions.
virtual void setState_PY (doublereal p, doublereal *y)
Set the internally stored pressure (Pa) and mass fractions.
virtual void setState_ST (double s, double t, double tol=1e-9)
Set the specific entropy (J/kg/K) and temperature (K).
virtual void setState_TV (double t, double v, double tol=1e-9)
Set the temperature (K) and specific volume (m^3/kg).
virtual void setState_PV (double p, double v, double tol=1e-9)
Set the pressure (Pa) and specific volume (m^3/kg).
virtual void setState_UP (double u, double p, double tol=1e-9)
Set the specific internal energy (J/kg) and pressure (Pa).
virtual void setState_VH (double v, double h, double tol=1e-9)
Set the specific volume (m^3/kg) and the specific enthalpy (J/kg)
virtual void setState_TH (double t, double h, double tol=1e-9)
Set the temperature (K) and the specific enthalpy (J/kg)
virtual void setState_SH (double s, double h, double tol=1e-9)
Set the specific entropy (J/kg/K) and the specific enthalpy (J/kg)
virtual void setState_RP (doublereal rho, doublereal p)
Set the density (kg/m**3) and pressure (Pa) at constant composition.
virtual void setState_RPX (doublereal rho, doublereal p, const doublereal *x)
Set the density (kg/m**3), pressure (Pa) and mole fractions.
virtual void setState_RPX (doublereal rho, doublereal p, const compositionMap &x)
Set the density (kg/m**3), pressure (Pa) and mole fractions.
virtual void setState_RPX (doublereal rho, doublereal p, const std::string &x)
Set the density (kg/m**3), pressure (Pa) and mole fractions.
virtual void setState_RPY (doublereal rho, doublereal p, const doublereal *y)
Set the density (kg/m**3), pressure (Pa) and mass fractions.
virtual void setState_RPY (doublereal rho, doublereal p, const compositionMap &y)
Set the density (kg/m**3), pressure (Pa) and mass fractions.
virtual void setState_RPY (doublereal rho, doublereal p, const std::string &y)
Set the density (kg/m**3), pressure (Pa) and mass fractions.
void equilibrate (const std::string &XY, const std::string &solver="auto", double rtol=1e-9, int max_steps=50000, int max_iter=100, int estimate_equil=0, int log_level=0)
Equilibrate a ThermoPhase object.
virtual void setToEquilState (const doublereal *lambda_RT)
This method is used by the ChemEquil equilibrium solver.
void setElementPotentials (const vector_fp &lambda)
Stores the element potentials in the ThermoPhase object.
bool getElementPotentials (doublereal *lambda) const
Returns the element potentials stored in the ThermoPhase object.
virtual bool compatibleWithMultiPhase () const
Indicates whether this phase type can be used with class MultiPhase for equilibrium calculations.
virtual doublereal critTemperature () const
Critical temperature (K).
virtual doublereal critPressure () const
Critical pressure (Pa).
virtual doublereal critVolume () const
Critical volume (m3/kmol).
virtual doublereal critCompressibility () const
Critical compressibility (unitless).
virtual doublereal critDensity () const
Critical density (kg/m3).
virtual doublereal satTemperature (doublereal p) const
Return the saturation temperature given the pressure.
virtual doublereal satPressure (doublereal t)
Return the saturation pressure given the temperature.
virtual doublereal vaporFraction () const
Return the fraction of vapor at the current conditions.
virtual void setState_Tsat (doublereal t, doublereal x)
Set the state to a saturated system at a particular temperature.
virtual void setState_Psat (doublereal p, doublereal x)
Set the state to a saturated system at a particular pressure.
virtual void modifySpecies (size_t k, shared_ptr< Species > spec)
Modify the thermodynamic data associated with a species.
void saveSpeciesData (const size_t k, const XML_Node *const data)
Store a reference pointer to the XML tree containing the species data for this phase.
const std::vector< const XML_Node * > & speciesData () const
Return a pointer to the vector of XML nodes containing the species data for this phase.
virtual MultiSpeciesThermo & speciesThermo (int k=-1)
Return a changeable reference to the calculation manager for species reference-state thermodynamic properties.
virtual void initThermoFile (const std::string &inputFile, const std::string &id)
virtual void initThermo ()
Initialize the ThermoPhase object after all species have been set up.
virtual void setStateFromXML (const XML_Node &state)
Set the initial state of the phase to the conditions specified in the state XML element.
virtual void invalidateCache ()
Invalidate any cached values which are normally updated only when a change in state is detected.
virtual void getdlnActCoeffds (const doublereal dTds, const doublereal *const dXds, doublereal *dlnActCoeffds) const
Get the change in activity coefficients wrt changes in state (temp, mole fraction, etc) along a line in parameter space or along a line in physical space.
virtual void getdlnActCoeffdlnX_diag (doublereal *dlnActCoeffdlnX_diag) const
Get the array of ln mole fraction derivatives of the log activity coefficients - diagonal component only.
virtual void getdlnActCoeffdlnN_diag (doublereal *dlnActCoeffdlnN_diag) const
Get the array of log species mole number derivatives of the log activity coefficients.
virtual void getdlnActCoeffdlnN (const size_t ld, doublereal *const dlnActCoeffdlnN)
Get the array of derivatives of the log activity coefficients with respect to the log of the species mole numbers.
virtual void getdlnActCoeffdlnN_numderiv (const size_t ld, doublereal *const dlnActCoeffdlnN)
virtual std::string report (bool show_thermo=true, doublereal threshold=-1e-14) const
returns a summary of the state of the phase as a string
virtual void reportCSV (std::ofstream &csvFile) const
returns a summary of the state of the phase to a comma separated file.
Public Member Functions inherited from Phase
Phase ()
Default constructor.
Phase (const Phase &)=delete
Phase & operator= (const Phase &)=delete
XML_Node & xml () const
Returns a const reference to the XML_Node that describes the phase.
void setXMLdata (XML_Node &xmlPhase)
Stores the XML tree information for the current phase.
void saveState (vector_fp &state) const
Save the current internal state of the phase.
void saveState (size_t lenstate, doublereal *state) const
Write to array 'state' the current internal state.
void restoreState (const vector_fp &state)
Restore a state saved on a previous call to saveState.
void restoreState (size_t lenstate, const doublereal *state)
Restore the state of the phase from a previously saved state vector.
doublereal molecularWeight (size_t k) const
Molecular weight of species k.
void getMolecularWeights (vector_fp &weights) const
Copy the vector of molecular weights into vector weights.
void getMolecularWeights (doublereal *weights) const
Copy the vector of molecular weights into array weights.
const vector_fp & molecularWeights () const
Return a const reference to the internal vector of molecular weights.
virtual double size (size_t k) const
doublereal charge (size_t k) const
Dimensionless electrical charge of a single molecule of species k The charge is normalized by the the magnitude of the electron charge.
doublereal chargeDensity () const
Charge density [C/m^3].
size_t nDim () const
Returns the number of spatial dimensions (1, 2, or 3)
void setNDim (size_t ndim)
Set the number of spatial dimensions (1, 2, or 3).
virtual bool ready () const
Returns a bool indicating whether the object is ready for use.
int stateMFNumber () const
Return the State Mole Fraction Number.
std::string id () const
Return the string id for the phase.
void setID (const std::string &id)
Set the string id for the phase.
std::string name () const
Return the name of the phase.
void setName (const std::string &nm)
Sets the string name for the phase.
std::string elementName (size_t m) const
Name of the element with index m.
size_t elementIndex (const std::string &name) const
Return the index of element named 'name'.
const std::vector< std::string > & elementNames () const
Return a read-only reference to the vector of element names.
doublereal atomicWeight (size_t m) const
Atomic weight of element m.
doublereal entropyElement298 (size_t m) const
Entropy of the element in its standard state at 298 K and 1 bar.
int atomicNumber (size_t m) const
Atomic number of element m.
int elementType (size_t m) const
Return the element constraint type Possible types include:
int changeElementType (int m, int elem_type)
Change the element type of the mth constraint Reassigns an element type.
const vector_fp & atomicWeights () const
Return a read-only reference to the vector of atomic weights.
size_t nElements () const
Number of elements.
void checkElementIndex (size_t m) const
Check that the specified element index is in range.
void checkElementArraySize (size_t mm) const
Check that an array size is at least nElements().
doublereal nAtoms (size_t k, size_t m) const
Number of atoms of element m in species k.
void getAtoms (size_t k, double *atomArray) const
Get a vector containing the atomic composition of species k.
size_t speciesIndex (const std::string &name) const
Returns the index of a species named 'name' within the Phase object.
std::string speciesName (size_t k) const
Name of the species with index k.
std::string speciesSPName (int k) const
Returns the expanded species name of a species, including the phase name This is guaranteed to be unique within a Cantera problem.
const std::vector< std::string > & speciesNames () const
Return a const reference to the vector of species names.
size_t nSpecies () const
Returns the number of species in the phase.
void checkSpeciesIndex (size_t k) const
Check that the specified species index is in range.
void checkSpeciesArraySize (size_t kk) const
Check that an array size is at least nSpecies().
void setMoleFractionsByName (const compositionMap &xMap)
Set the species mole fractions by name.
void setMoleFractionsByName (const std::string &x)
Set the mole fractions of a group of species by name.
void setMassFractionsByName (const compositionMap &yMap)
Set the species mass fractions by name.
void setMassFractionsByName (const std::string &x)
Set the species mass fractions by name.
void setState_TRX (doublereal t, doublereal dens, const doublereal *x)
Set the internally stored temperature (K), density, and mole fractions.
void setState_TRX (doublereal t, doublereal dens, const compositionMap &x)
Set the internally stored temperature (K), density, and mole fractions.
void setState_TRY (doublereal t, doublereal dens, const doublereal *y)
Set the internally stored temperature (K), density, and mass fractions.
void setState_TRY (doublereal t, doublereal dens, const compositionMap &y)
Set the internally stored temperature (K), density, and mass fractions.
void setState_TNX (doublereal t, doublereal n, const doublereal *x)
Set the internally stored temperature (K), molar density (kmol/m^3), and mole fractions.
void setState_TR (doublereal t, doublereal rho)
Set the internally stored temperature (K) and density (kg/m^3)
void setState_TX (doublereal t, doublereal *x)
Set the internally stored temperature (K) and mole fractions.
void setState_TY (doublereal t, doublereal *y)
Set the internally stored temperature (K) and mass fractions.
void setState_RX (doublereal rho, doublereal *x)
Set the density (kg/m^3) and mole fractions.
void setState_RY (doublereal rho, doublereal *y)
Set the density (kg/m^3) and mass fractions.
compositionMap getMoleFractionsByName (double threshold=0.0) const
Get the mole fractions by name.
doublereal moleFraction (size_t k) const
Return the mole fraction of a single species.
doublereal moleFraction (const std::string &name) const
Return the mole fraction of a single species.
compositionMap getMassFractionsByName (double threshold=0.0) const
Get the mass fractions by name.
doublereal massFraction (size_t k) const
Return the mass fraction of a single species.
doublereal massFraction (const std::string &name) const
Return the mass fraction of a single species.
void getMoleFractions (doublereal *const x) const
Get the species mole fraction vector.
virtual void setMoleFractions_NoNorm (const doublereal *const x)
Set the mole fractions to the specified values without normalizing.
void getMassFractions (doublereal *const y) const
Get the species mass fractions.
const doublereal * massFractions () const
Return a const pointer to the mass fraction array.
virtual void setMassFractions_NoNorm (const doublereal *const y)
Set the mass fractions to the specified values without normalizing.
void getConcentrations (doublereal *const c) const
Get the species concentrations (kmol/m^3).
doublereal concentration (const size_t k) const
Concentration of species k.
virtual void setConcentrations (const doublereal *const conc)
Set the concentrations to the specified values within the phase.
virtual void setConcentrationsNoNorm (const double *const conc)
Set the concentrations without ignoring negative concentrations.
doublereal elementalMassFraction (const size_t m) const
Elemental mass fraction of element m.
doublereal elementalMoleFraction (const size_t m) const
Elemental mole fraction of element m.
const doublereal * moleFractdivMMW () const
Returns a const pointer to the start of the moleFraction/MW array.
doublereal temperature () const
Temperature (K).
virtual doublereal density () const
Density (kg/m^3).
doublereal molarDensity () const
Molar density (kmol/m^3).
doublereal molarVolume () const
Molar volume (m^3/kmol).
virtual void setDensity (const doublereal density_)
Set the internally stored density (kg/m^3) of the phase.
virtual void setMolarDensity (const doublereal molarDensity)
Set the internally stored molar density (kmol/m^3) of the phase.
virtual void setTemperature (const doublereal temp)
Set the internally stored temperature of the phase (K).
doublereal mean_X (const doublereal *const Q) const
Evaluate the mole-fraction-weighted mean of an array Q.
doublereal mean_X (const vector_fp &Q) const
Evaluate the mole-fraction-weighted mean of an array Q.
doublereal meanMolecularWeight () const
The mean molecular weight. Units: (kg/kmol)
doublereal sum_xlogx () const
Evaluate \(\sum_k X_k \log X_k \).
size_t addElement (const std::string &symbol, doublereal weight=-12345.0, int atomicNumber=0, doublereal entropy298=ENTROPY298_UNKNOWN, int elem_type=CT_ELEM_TYPE_ABSPOS)
Add an element.
shared_ptr< Species > species (const std::string &name) const
Return the Species object for the named species.
shared_ptr< Species > species (size_t k) const
Return the Species object for species whose index is k.
void ignoreUndefinedElements ()
Set behavior when adding a species containing undefined elements to just skip the species.
void addUndefinedElements ()
Set behavior when adding a species containing undefined elements to add those elements to the phase.
void throwUndefinedElements ()
Set the behavior when adding a species containing undefined elements to throw an exception.
Static Public Member Functions
static XML_Node * makeDefaultXMLTree ()
Make the default XML tree.
Additional Inherited Members
Protected Member Functions inherited from SingleSpeciesTP
void _updateThermo () const
Protected Member Functions inherited from ThermoPhase
virtual void getCsvReportData (std::vector< std::string > &names, std::vector< vector_fp > &data) const
Fills names and data with the column names and species thermo properties to be included in the output of the reportCSV method.
Protected Member Functions inherited from Phase
void setMolecularWeight (const int k, const double mw)
Set the molecular weight of a single species to a given value.
virtual void compositionChanged ()
Apply changes to the state which are needed after the composition changes.
Protected Attributes inherited from SingleSpeciesTP
doublereal m_press
The current pressure of the solution (Pa). It gets initialized to 1 atm.
doublereal m_p0
double m_h0_RT
Dimensionless enthalpy at the (mtlast, m_p0)
double m_cp0_R
Dimensionless heat capacity at the (mtlast, m_p0)
double m_s0_R
Dimensionless entropy at the (mtlast, m_p0)
Protected Attributes inherited from ThermoPhase
MultiSpeciesThermo m_spthermo
Pointer to the calculation manager for species reference-state thermodynamic properties.
std::vector< const XML_Node * > m_speciesData
Vector of pointers to the species databases.
doublereal m_phi
Stored value of the electric potential for this phase. Units are Volts.
vector_fp m_lambdaRRT
Vector of element potentials.
bool m_hasElementPotentials
Boolean indicating whether there is a valid set of saved element potentials for this phase.
bool m_chargeNeutralityNecessary
Boolean indicating whether a charge neutrality condition is a necessity.
int m_ssConvention
Contains the standard state convention.
doublereal m_tlast
last value of the temperature processed by reference state
Protected Attributes inherited from Phase
ValueCache m_cache
Cached for saved calculations within each ThermoPhase.
size_t m_kk
Number of species in the phase.
size_t m_ndim
Dimensionality of the phase.
vector_fp m_speciesComp
Atomic composition of the species.
vector_fp m_speciesCharge
Vector of species charges. length m_kk.
std::map< std::string, shared_ptr< Species > > m_species
UndefElement::behavior m_undefinedElementBehavior
Flag determining behavior when adding species with an undefined element.
Detailed Description
Class MetalSHEelectrons represents electrons within a metal, adjacent to an aqueous electrolyte, that are consistent with the SHE reference electrode.
Attention
This class currently does not have any test cases or examples. Its implementation may be incomplete, and future changes to Cantera may unexpectedly cause this class to stop working. If you use this class, please consider contributing examples or test cases. In the absence of new tests or examples, this class may be deprecated and removed in a future version of Cantera. See https://github.com/Cantera/cantera/issues/267 for additional information.
Deprecated:
To be removed after Cantera 2.4
The class is based on the electron having a chemical potential equal to one- half of the entropy of the H2 gas at the system pressure
Specification of Species Standard State Properties
This class inherits from SingleSpeciesTP. It is assumed that the reference state thermodynamics may be obtained by a pointer to a populated species thermodynamic property manager class (see ThermoPhase::m_spthermo). How to relate pressure changes to the reference state thermodynamics is resolved at this level.
The enthalpy function is given by the following relation.
\[ h^o_k(T,P) = h^{ref}_k(T) \]
The standard state constant-pressure heat capacity is independent of pressure:
\[ Cp^o_k(T,P) = Cp^{ref}_k(T) \]
The standard state entropy depends in the following fashion on pressure:
\[ S^o_k(T,P) = S^{ref}_k(T) - R \ln(\frac{P}{P_{ref}}) \]
The standard state Gibbs free energy is obtained from the enthalpy and entropy functions:
\[ \mu^o_k(T,P) = h^o_k(T,P) - S^o_k(T,P) T \]
\[ \mu^o_k(T,P) = \mu^{ref}_k(T) + R T \ln(\frac{P}{P_{ref}}) \]
where
\[ \mu^{ref}_k(T) = h^{ref}_k(T) - T S^{ref}_k(T) \]
The standard state internal energy is obtained from the enthalpy function also
\[ u^o_k(T,P) = h^o_k(T) - R T \]
Specification of Solution Thermodynamic Properties
All solution properties are obtained from the standard state species functions, since there is only one species in the phase.
Application within Kinetics Managers
The standard concentration is equal to 1.0. This means that the kinetics operator works on an activities basis. Since this is a stoichiometric substance, this means that the concentration of this phase drops out of kinetics expressions since the activity is always equal to one.
This is what is expected of electrons. The only effect that this class will have on reactions is in terms of the standard state chemical potential, which is equal to 1/2 of the H2 gas chemical potential, and the voltage assigned to the electron, which is the voltage of the metal.
Instantiation of the Class
The constructor for this phase is located in the default ThermoFactory for Cantera. A new MetalSHEelectrons object may be created by the following code snippets, where the file metalSHEelectrons.xml exists in a local directory:
MetalSHEelectrons *eMetal = new MetalSHEelectrons("metalSHEelectrons.xml", "");
or by the following call to importPhase():
XML_Node *xm = get_XML_NameID("phase", iFile + "#MetalSHEelectrons", 0);
MetalSHEelectrons eMetal;
importPhase(*xm, &eMetal);
ThermoPhase *eMetal = newPhase("MetalSHEelectrons.xml", "MetalSHEelectrons");
Additionally, this phase may be created without including an XML file with the special command, where the default file is embedded into this object.
MetalSHEelectrons *eMetal = new MetalSHEelectrons("MetalSHEelectrons_default.xml", "");
XML Example
The phase model name for this is called MetalSHEelectrons. It must be supplied as the model attribute of the thermo XML element entry. Within the phase XML block, the density of the phase must be specified though it's not used. An example of an XML file this phase is given below.
<?xml version="1.0"?>
<ctml>
  <validate reactions="yes" species="yes"/>
  <phase dim="3" id="MetalSHEelectrons">
    <elementArray datasrc="elements.xml">
        E
    </elementArray>
    <speciesArray datasrc="#species_Metal_SHEelectrons"> she_electron </speciesArray>
    <thermo model="metalSHEelectrons">
      <density units="g/cm3">2.165</density>
    </thermo>
    <transport model="None"/>
    <kinetics model="none"/>
  </phase>
  <!-- species definitions     -->
  <speciesData id="species_Metal_SHEelectrons">
    <species name="she_electron">
      <atomArray> E:1  </atomArray>
      <charge> -1 </charge>
      <thermo>
        <NASA Tmax="1000.0" Tmin="200.0" P0="100000.0">
         <floatArray name="coeffs" size="7">
          1.172165560E+00,   3.990260375E-03,  -9.739075500E-06,  1.007860470E-08,
         -3.688058805E-12, -4.589675865E+02,  3.415051190E-01
         </floatArray>
        </NASA>
        <NASA Tmax="6000.0" Tmin="1000.0" P0="100000.0">
           <floatArray name="coeffs" size="7">
             1.466432895E+00,  4.133039835E-04, -7.320116750E-08, 7.705017950E-12,
            -3.444022160E-16, -4.065327985E+02, -5.121644350E-01
          </floatArray>
        </NASA>
      </thermo>
      <density units="g/cm3">2.165</density>
    </species>
  </speciesData>
</ctml>
The model attribute, "MetalSHEelectrons", on the thermo element identifies the phase as being a MetalSHEelectrons object.
Definition at line 185 of file MetalSHEelectrons.h.
Constructor & Destructor Documentation
MetalSHEelectrons() [1/3]
MetalSHEelectrons ()
Default constructor for the MetalSHEelectrons class.
Definition at line 21 of file MetalSHEelectrons.cpp.
References Cantera::warn_deprecated().
MetalSHEelectrons() [2/3]
MetalSHEelectrons (const std::string & infile, const std::string & id = "")
Construct and initialize a MetalSHEelectrons ThermoPhase object directly from an ASCII input file.
Parameters
infile name of the input file
id name of the phase id in the file. If this is blank, the first phase in the file is used.
Definition at line 26 of file MetalSHEelectrons.cpp.
References ThermoPhase::initThermoFile(), and Cantera::warn_deprecated().
MetalSHEelectrons() [3/3]
MetalSHEelectrons (XML_Node & phaseRef, const std::string & id = "")
Construct and initialize a MetalSHEelectrons ThermoPhase object directly from an XML database.
Parameters
phaseRef XML node pointing to a MetalSHEelectrons description
id Id of the phase.
Definition at line 32 of file MetalSHEelectrons.cpp.
References Cantera::importPhase(), and Cantera::warn_deprecated().
Member Function Documentation
pressure()
doublereal pressure () const virtual
Report the Pressure. Units: Pa.
For an incompressible substance, the density is independent of pressure. This method simply returns the stored pressure value.
Reimplemented from ThermoPhase.
Definition at line 40 of file MetalSHEelectrons.cpp.
References SingleSpeciesTP::m_press.
Referenced by MetalSHEelectrons::getEntropy_R(), MetalSHEelectrons::getGibbs_RT(), and MetalSHEelectrons::isothermalCompressibility().
setPressure()
void setPressure (doublereal p) virtual
Set the pressure at constant temperature. Units: Pa.
For an incompressible substance, the density is independent of pressure. Therefore, this method only stores the specified pressure value. It does not modify the density.
Parameters
p Pressure (units - Pa)
Reimplemented from ThermoPhase.
Definition at line 45 of file MetalSHEelectrons.cpp.
References SingleSpeciesTP::m_press.
isothermalCompressibility()
doublereal isothermalCompressibility () const virtual
Returns the isothermal compressibility. Units: 1/Pa.
The isothermal compressibility is defined as
\[ \kappa_T = -\frac{1}{v}\left(\frac{\partial v}{\partial P}\right)_T \]
or
\[ \kappa_T = \frac{1}{\rho}\left(\frac{\partial \rho}{\partial P}\right)_T \]
Reimplemented from ThermoPhase.
Definition at line 50 of file MetalSHEelectrons.cpp.
References MetalSHEelectrons::pressure().
thermalExpansionCoeff()
doublereal thermalExpansionCoeff () const virtual
Return the volumetric thermal expansion coefficient. Units: 1/K.
The thermal expansion coefficient is defined as
\[ \beta = \frac{1}{v}\left(\frac{\partial v}{\partial T}\right)_P \]
Reimplemented from ThermoPhase.
Definition at line 55 of file MetalSHEelectrons.cpp.
References Phase::temperature().
getActivityConcentrations()
void getActivityConcentrations (doublereal * c) const virtual
This method returns an array of generalized concentrations.
\(C^a_k\) are defined such that \(a_k = C^a_k / C^0_k, \) where \(C^0_k \) is a standard concentration defined below and \(a_k \) are activities used in the thermodynamic functions. These activity (or generalized) concentrations are used by kinetics manager classes to compute the forward and reverse rates of elementary reactions.
For a stoichiometric substance, there is only one species, and the generalized concentration is 1.0.
Parameters
c Output array of generalized concentrations. The units depend upon the implementation of the reaction rate expressions within the phase.
Reimplemented from ThermoPhase.
Definition at line 62 of file MetalSHEelectrons.cpp.
standardConcentration()
doublereal standardConcentration (size_t k = 0) const virtual
Return the standard concentration for the kth species.
The standard concentration \(C^0_k \) used to normalize the activity (i.e., generalized) concentration. This phase assumes that the kinetics operator works on an dimensionless basis. Thus, the standard concentration is equal to 1.0.
Parameters
k Optional parameter indicating the species. The default is to assume this refers to species 0.
Returns
Returns The standard Concentration as 1.0
Reimplemented from ThermoPhase.
Definition at line 67 of file MetalSHEelectrons.cpp.
logStandardConc()
doublereal logStandardConc (size_t k = 0) const virtual
Natural logarithm of the standard concentration of the kth species.
Parameters
k index of the species (defaults to zero)
Reimplemented from ThermoPhase.
Definition at line 72 of file MetalSHEelectrons.cpp.
getStandardChemPotentials()
void getStandardChemPotentials (doublereal * mu0) const virtual
Get the array of chemical potentials at unit activity for the species at their standard states at the current T and P of the solution.
For a stoichiometric substance, there is no activity term in the chemical potential expression, and therefore the standard chemical potential and the chemical potential are both equal to the molar Gibbs function.
These are the standard state chemical potentials \(\mu^0_k(T,P) \). The values are evaluated at the current temperature and pressure of the solution
Parameters
mu0 Output vector of chemical potentials. Length: m_kk.
Reimplemented from ThermoPhase.
Definition at line 79 of file MetalSHEelectrons.cpp.
References MetalSHEelectrons::getGibbs_RT(), and ThermoPhase::RT().
getEnthalpy_RT()
void getEnthalpy_RT (doublereal * hrt) const virtual
Get the nondimensional Enthalpy functions for the species at their standard states at the current T and P of the solution.
Parameters
hrt Output vector of nondimensional standard state enthalpies. Length: m_kk.
Reimplemented from ThermoPhase.
Definition at line 85 of file MetalSHEelectrons.cpp.
References SingleSpeciesTP::getEnthalpy_RT_ref().
Referenced by MetalSHEelectrons::getIntEnergy_RT().
getEntropy_R()
void getEntropy_R (doublereal * sr) const virtual
Get the array of nondimensional Entropy functions for the standard state species at the current T and P of the solution.
Parameters
sr Output vector of nondimensional standard state entropies. Length: m_kk.
Reimplemented from ThermoPhase.
Definition at line 90 of file MetalSHEelectrons.cpp.
References SingleSpeciesTP::getEntropy_R_ref(), and MetalSHEelectrons::pressure().
getGibbs_RT()
void getGibbs_RT (doublereal * grt) const virtual
Get the nondimensional Gibbs functions for the species in their standard states at the current T and P of the solution.
Parameters
grt Output vector of nondimensional standard state Gibbs free energies. Length: m_kk.
Reimplemented from ThermoPhase.
Definition at line 97 of file MetalSHEelectrons.cpp.
References SingleSpeciesTP::getGibbs_RT_ref(), and MetalSHEelectrons::pressure().
Referenced by MetalSHEelectrons::getStandardChemPotentials().
getCp_R()
void getCp_R (doublereal * cpr) const virtual
Get the nondimensional Heat Capacities at constant pressure for the species standard states at the current T and P of the solution.
Parameters
cpr Output vector of nondimensional standard state heat capacities. Length: m_kk.
Reimplemented from ThermoPhase.
Definition at line 104 of file MetalSHEelectrons.cpp.
References SingleSpeciesTP::_updateThermo(), and SingleSpeciesTP::m_cp0_R.
getIntEnergy_RT()
void getIntEnergy_RT (doublereal * urt) const virtual
Returns the vector of nondimensional Internal Energies of the standard state species at the current T and P of the solution.
For an incompressible, stoichiometric substance, the molar internal energy is independent of pressure. Since the thermodynamic properties are specified by giving the standard-state enthalpy, the term \(P_{ref} \hat v\) is subtracted from the specified reference molar enthalpy to compute the standard state molar internal energy.
Parameters
urt output vector of nondimensional standard state internal energies of the species. Length: m_kk.
Reimplemented from ThermoPhase.
Definition at line 109 of file MetalSHEelectrons.cpp.
References MetalSHEelectrons::getEnthalpy_RT().
getIntEnergy_RT_ref()
void getIntEnergy_RT_ref (doublereal * urt) const virtual
Returns the vector of nondimensional internal Energies of the reference state at the current temperature of the solution and the reference pressure for each species.
Parameters
urt Output vector of nondimensional reference state internal energies of the species. Length: m_kk
Reimplemented from ThermoPhase.
Definition at line 115 of file MetalSHEelectrons.cpp.
References SingleSpeciesTP::_updateThermo(), SingleSpeciesTP::m_h0_RT, Phase::molarDensity(), and ThermoPhase::RT().
initThermoXML()
void initThermoXML (XML_Node & phaseNode, const std::string & id) virtual
Import and initialize a ThermoPhase object using an XML tree.
Here we read extra information about the XML description of a phase. Regular information about elements and species and their reference state thermodynamic information have already been read at this point. For example, we do not need to call this function for ideal gas equations of state. This function is called from importPhase() after the elements and the species are initialized with default ideal solution level data.
The default implementation in ThermoPhase calls the virtual function initThermo() and then sets the "state" of the phase by looking for an XML element named "state", and then interpreting its contents by calling the virtual function setStateFromXML().
Parameters
phaseNode This object must be the phase node of a complete XML tree description of the phase, including all of the species data. In other words while "phase" must point to an XML phase object, it must have sibling nodes "speciesData" that describe the species in the phase.
id ID of the phase. If nonnull, a check is done to see if phaseNode is pointing to the phase with the correct id.
Reimplemented from ThermoPhase.
Definition at line 123 of file MetalSHEelectrons.cpp.
References XML_Node::child(), Cantera::getFloat(), XML_Node::hasChild(), ThermoPhase::initThermoXML(), and Phase::setDensity().
makeDefaultXMLTree()
XML_Node * makeDefaultXMLTree () static
Make the default XML tree.
Returns
a new XML tree containing the default info.
Definition at line 139 of file MetalSHEelectrons.cpp.
References XML_Node::addAttribute().
setParameters()
void setParameters (int n, doublereal *const c) virtual
Set the equation of state parameters.
Parameters
n number of parameters
c array of n coefficients c[0] = density of phase [ kg/m3 ]
Reimplemented from ThermoPhase.
Definition at line 192 of file MetalSHEelectrons.cpp.
References Phase::setDensity().
getParameters()
void getParameters (int & n, doublereal *const c) const virtual
Get the equation of state parameters in a vector.
Parameters
n number of parameters
c array of n coefficients
For this phase:
n = 1
c[0] = density of phase [ kg/m3 ]
Reimplemented from ThermoPhase.
Definition at line 197 of file MetalSHEelectrons.cpp.
References Phase::density().
setParametersFromXML()
void setParametersFromXML (const XML_Node & eosdata) virtual
Set equation of state parameter values from XML entries.
For this phase, the density of the phase is specified in this block.
Parameters
eosdata An XML_Node object corresponding to the "thermo" entry for this phase in the input file.
eosdata points to the thermo block, and looks like this:
<phase id="stoichsolid" >
  <thermo model="StoichSubstance">
    <density units="g/cm3">3.52</density>
  </thermo>
</phase>
Reimplemented from ThermoPhase.
Definition at line 203 of file MetalSHEelectrons.cpp.
References Cantera::getFloat(), XML_Node::hasChild(), and Phase::setDensity().
The documentation for this class was generated from the following files:
MetalSHEelectrons.h
MetalSHEelectrons.cpp