Cantera: PlusConstant1 Class Reference
PlusConstant1 Class Reference
A function plus a constant.
#include <Func1.h>
Public Member Functions
PlusConstant1 (Func1 &f1, doublereal A)
PlusConstant1 (const PlusConstant1 &b)
PlusConstant1 & operator= (const PlusConstant1 &right)
virtual int ID () const
virtual Func1 & duplicate () const
Duplicate the current function.
virtual doublereal eval (doublereal t) const
Evaluate the function.
virtual Func1 & derivative () const
Creates a derivative to the current function.
virtual std::string write (const std::string &arg) const
virtual int order () const
Return the order of the function, if it makes sense.
Public Member Functions inherited from Func1
Func1 (const Func1 &right)
Func1 & operator= (const Func1 &right)
doublereal operator() (doublereal t) const
Calls method eval to evaluate the function.
bool isIdentical (Func1 &other) const
Routine to determine if two functions are the same.
virtual doublereal isProportional (TimesConstant1 &other)
virtual doublereal isProportional (Func1 &other)
doublereal c () const
accessor function for the stored constant
void setC (doublereal c)
Function to set the stored constant.
Func1 & func1 () const
accessor function for m_f1
Func1 & func2 () const
accessor function for m_f2
Func1 & func1_dup () const
Func1 & func2_dup () const
Func1 * parent () const
void setParent (Func1 *p)
Additional Inherited Members
Protected Attributes inherited from Func1
doublereal m_c
Func1 * m_f1
Func1 * m_f2
Func1 * m_parent
Detailed Description
A function plus a constant.
Definition at line 574 of file Func1.h.
Member Function Documentation
duplicate()
virtual Func1& duplicate () const inline virtual
Duplicate the current function.
This duplicates the current function, returning a reference to the newly created function.
Reimplemented from Func1.
Definition at line 608 of file Func1.h.
References Func1::duplicate().
eval()
virtual doublereal eval (doublereal t) const inline virtual
Evaluate the function.
Reimplemented from Func1.
Definition at line 614 of file Func1.h.
References Func1::eval().
derivative()
virtual Func1& derivative () const inline virtual
Creates a derivative to the current function.
This will create a new derivative function and return a reference to the function.
Reimplemented from Func1.
Definition at line 617 of file Func1.h.
References Func1::derivative().
order()
virtual int order () const inline virtual
Return the order of the function, if it makes sense.
Reimplemented from Func1.
Definition at line 622 of file Func1.h.
The documentation for this class was generated from the following files:
Func1.h
Func1.cpp