Cantera: utils.h File Reference
utils.h File Reference
#include "cantera/tpx/Sub.h"
Functions
Substance * GetSub (int isub)
Substance * newSubstance (const std::string &name)
Create a new Substance object corresponding to the specified name.
Function Documentation
newSubstance()
Substance * newSubstance (const std::string & name)
Create a new Substance object corresponding to the specified name.
Definition at line 20 of file utils.cpp.
References tpx::newSubstance(), and Cantera::toLowerCopy().
Referenced by tpx::newSubstance().