default_language_version:
  python: python3.10
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.2.0
  hooks:
  - id: end-of-file-fixer
- repo: https://github.com/pycqa/isort
  rev: 5.10.1
  hooks:
  - id: isort
    language_version: python3
- repo: https://github.com/psf/black
  rev: 22.3.0
  hooks:
  - id: black
    language_version: python3
- repo: https://gitlab.com/pycqa/flake8
  rev: 3.9.2
  hooks:
  - id: flake8
    language_version: python3
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.960
  hooks:
  - id: mypy
    # Override default --ignore-missing-imports
    args: []
    additional_dependencies:
    - sphinx
