Cantera: IdealGasPhase Class Reference
IdealGasPhase Class Reference
Thermodynamic Properties
Class IdealGasPhase represents low-density gases that obey the ideal gas equation of state.
#include <IdealGasPhase.h>
Public Member Functions
IdealGasPhase ()
Default empty Constructor.
IdealGasPhase (const IdealGasPhase &right)
Copy Constructor.
IdealGasPhase & operator= (const IdealGasPhase &right)
Assignment operator.
virtual ~IdealGasPhase ()
Destructor.
ThermoPhase * duplMyselfAsThermoPhase () const
Duplicator from the ThermoPhase parent class.
virtual int eosType () const
Equation of state flag.
virtual void initThermo ()
Initialize the ThermoPhase object after all species have been set up.
doublereal _RT () const
Return the Gas Constant multiplied by the current temperature.
XML_Node & xml ()
Returns a reference to the XML_Node stored for the phase.
void saveState (vector_fp &state) const
Save the current internal state of the phase Write to vector 'state' the current internal state.
void saveState (size_t lenstate, doublereal *state) const
Write to array 'state' the current internal state.
void restoreState (const vector_fp &state)
Restore a state saved on a previous call to saveState.
void restoreState (size_t lenstate, const doublereal *state)
Restore the state of the phase from a previously saved state vector.
doublereal molecularWeight (size_t k) const
Molecular weight of species k.
doublereal molarMass (size_t k) const
Return the Molar mass of species k Alternate name for molecular weight.
void getMolecularWeights (vector_fp &weights) const
Copy the vector of molecular weights into vector weights.
void getMolecularWeights (int iwt, doublereal *weights) const
Copy the vector of molecular weights into array weights.
void getMolecularWeights (doublereal *weights) const
Copy the vector of molecular weights into array weights.
const vector_fp & molecularWeights () const
Return a const reference to the internal vector of molecular weights.
doublereal size (size_t k) const
This routine returns the size of species k.
doublereal charge (size_t k) const
Dimensionless electrical charge of a single molecule of species k The charge is normalized by the the magnitude of the electron charge.
doublereal chargeDensity () const
Charge density [C/m^3].
size_t nDim () const
Returns the number of spatial dimensions (1, 2, or 3)
void setNDim (size_t ndim)
Set the number of spatial dimensions (1, 2, or 3).
virtual void freezeSpecies ()
Call when finished adding species.
bool speciesFrozen ()
True if freezeSpecies has been called.
virtual bool ready () const
int stateMFNumber () const
Return the State Mole Fraction Number.
void stateMFChangeCalc (bool forceChange=false)
Every time the mole fractions have changed, this routine will increment the stateMFNumber.
Molar Thermodynamic Properties of the Solution ------------------------------
virtual doublereal enthalpy_mole () const
Return the Molar enthalpy. Units: J/kmol.
virtual doublereal intEnergy_mole () const
Molar internal energy.
virtual doublereal entropy_mole () const
Molar entropy.
virtual doublereal gibbs_mole () const
Molar Gibbs free Energy for an ideal gas.
virtual doublereal cp_mole () const
Molar heat capacity at constant pressure.
virtual doublereal cv_mole () const
Molar heat capacity at constant volume.
Mechanical Equation of State ------------------------------------------------
virtual doublereal pressure () const
Pressure.
virtual void setPressure (doublereal p)
Set the pressure at constant temperature and composition.
virtual doublereal isothermalCompressibility () const
Returns the isothermal compressibility. Units: 1/Pa.
virtual doublereal thermalExpansionCoeff () const
Return the volumetric thermal expansion coefficient. Units: 1/K.
Chemical Potentials and Activities ------------------------------------------
The activity \(a_k\) of a species in solution is related to the chemical potential by
\[ \mu_k(T,P,X_k) = \mu_k^0(T,P) + \hat R T \log a_k. \]
The quantity \(\mu_k^0(T,P)\) is the standard state chemical potential at unit activity.
It may depend on the pressure and the temperature. However, it may not depend on the mole fractions of the species in the solution.
The activities are related to the generalized concentrations, \(\tilde C_k\), and standard concentrations, \(C^0_k\), by the following formula:
\[ a_k = \frac{\tilde C_k}{C^0_k} \]
The generalized concentrations are used in the kinetics classes to describe the rates of progress of reactions involving the species. Their formulation depends upon the specification of the rate constants for reaction, especially the units used in specifying the rate constants. The bridge between the thermodynamic equilibrium expressions that use a_k and the kinetics expressions which use the generalized concentrations is provided by the multiplicative factor of the standard concentrations.
virtual void getActivityConcentrations (doublereal *c) const
This method returns the array of generalized concentrations.
virtual doublereal standardConcentration (size_t k=0) const
Returns the standard concentration \(C^0_k \), which is used to normalize the generalized concentration.
virtual doublereal logStandardConc (size_t k=0) const
Returns the natural logarithm of the standard concentration of the kth species.
virtual void getActivityCoefficients (doublereal *ac) const
Get the array of non-dimensional activity coefficients at the current solution temperature, pressure, and solution concentration.
Partial Molar Properties of the Solution ----------------------------------
virtual void getChemPotentials (doublereal *mu) const
Get the species chemical potentials. Units: J/kmol.
virtual void getPartialMolarEnthalpies (doublereal *hbar) const
Get the species partial molar enthalpies. Units: J/kmol.
virtual void getPartialMolarEntropies (doublereal *sbar) const
Get the species partial molar entropies. Units: J/kmol/K.
virtual void getPartialMolarIntEnergies (doublereal *ubar) const
Get the species partial molar enthalpies. Units: J/kmol.
virtual void getPartialMolarCp (doublereal *cpbar) const
Get the partial molar heat capacities Units: J/kmol/K.
virtual void getPartialMolarVolumes (doublereal *vbar) const
Get the species partial molar volumes. Units: m^3/kmol.
Properties of the Standard State of the Species in the Solution ----------
virtual void getStandardChemPotentials (doublereal *mu) const
Get the array of chemical potentials at unit activity for the species standard states at the current T and P of the solution.
virtual void getEnthalpy_RT (doublereal *hrt) const
Get the nondimensional Enthalpy functions for the species standard states at their standard states at the current T and P of the solution.
virtual void getEntropy_R (doublereal *sr) const
Get the array of nondimensional Entropy functions for the species standard states at the current T and P of the solution.
virtual void getGibbs_RT (doublereal *grt) const
Get the nondimensional Gibbs functions for the species standard states at the current T and P of the solution.
virtual void getPureGibbs (doublereal *gpure) const
Get the Gibbs functions for the standard state of the species at the current T and P of the solution.
virtual void getIntEnergy_RT (doublereal *urt) const
Returns the vector of nondimensional Internal Energies of the standard state species at the current T and P of the solution.
virtual void getCp_R (doublereal *cpr) const
Get the nondimensional Heat Capacities at constant pressure for the species standard states at the current T and P of the solution.
virtual void getStandardVolumes (doublereal *vol) const
Get the molar volumes of the species standard states at the current T and P of the solution.
Thermodynamic Values for the Species Reference States ---------------------
virtual void getEnthalpy_RT_ref (doublereal *hrt) const
Returns the vector of nondimensional enthalpies of the reference state at the current temperature of the solution and the reference pressure for the species.
virtual void getGibbs_RT_ref (doublereal *grt) const
Returns the vector of nondimensional Gibbs Free Energies of the reference state at the current temperature of the solution and the reference pressure for the species.
virtual void getGibbs_ref (doublereal *g) const
Returns the vector of the gibbs function of the reference state at the current temperature of the solution and the reference pressure for the species.
virtual void getEntropy_R_ref (doublereal *er) const
Returns the vector of nondimensional entropies of the reference state at the current temperature of the solution and the reference pressure for each species.
virtual void getIntEnergy_RT_ref (doublereal *urt) const
Returns the vector of nondimensional internal Energies of the reference state at the current temperature of the solution and the reference pressure for each species.
virtual void getCp_R_ref (doublereal *cprt) const
Returns the vector of nondimensional constant pressure heat capacities of the reference state at the current temperature of the solution and reference pressure for each species.
virtual void getStandardVolumes_ref (doublereal *vol) const
Get the molar volumes of the species standard states at the current T and P_ref of the solution.
NonVirtual Internal methods to Return References to Reference State Thermo
const vector_fp & enthalpy_RT_ref () const
Returns a reference to the dimensionless reference state enthalpy vector.
const vector_fp & gibbs_RT_ref () const
Returns a reference to the dimensionless reference state Gibbs free energy vector.
const vector_fp & expGibbs_RT_ref () const
Returns a reference to the exponent of the dimensionless reference state Gibbs Free energy vector.
const vector_fp & entropy_R_ref () const
Returns a reference to the dimensionless reference state Entropy vector.
const vector_fp & cp_R_ref () const
Returns a reference to the dimensionless reference state Heat Capacity vector.
Chemical Equilibrium
This method is used by the ChemEquil equilibrium solver.
Set mixture to an equilibrium state consistent with specified element potentials and temperature. It sets the state such that the chemical potentials satisfy
\[ \frac{\mu_k}{\hat R T} = \sum_m A_{k,m} \left(\frac{\lambda_m} {\hat R T}\right) \]
where \(\lambda_m \) is the element potential of element m. The temperature is unchanged. Any phase (ideal or not) that implements this method can be equilibrated by ChemEquil.
Parameters
lambda_RT vector of non-dimensional element potentials
\[ \lambda_m/RT \]
.
virtual void setToEquilState (const doublereal *lambda_RT)
This method is used by the ChemEquil equilibrium solver.
Information Methods
virtual doublereal refPressure () const
Returns the reference pressure in Pa.
virtual doublereal minTemp (size_t k=npos) const
Minimum temperature for which the thermodynamic data for the species or phase are valid.
doublereal Hf298SS (const int k) const
Report the 298 K Heat of Formation of the standard state of one species (J kmol-1)
virtual void modifyOneHf298SS (const int k, const doublereal Hf298New)
Modify the value of the 298 K Heat of Formation of one species in the phase (J kmol-1)
virtual doublereal maxTemp (size_t k=npos) const
Maximum temperature for which the thermodynamic data for the species are valid.
bool chargeNeutralityNecessary () const
Returns the chargeNeutralityNecessity boolean.
Mechanical Properties
virtual void updateDensity ()
Electric Potential
The phase may be at some non-zero electrical potential.
These methods set or get the value of the electric potential.
void setElectricPotential (doublereal v)
Set the electric potential of this phase (V).
doublereal electricPotential () const
Returns the electric potential of this phase (V).
Activities, Standard States, and Activity Concentrations
The activity \(a_k\) of a species in solution is related to the chemical potential by
\[ \mu_k = \mu_k^0(T,P) + \hat R T \log a_k. \]
The quantity \(\mu_k^0(T,P)\) is the standard chemical potential at unit activity, which depends on temperature and pressure, but not on composition.
The activity is dimensionless.
virtual int activityConvention () const
This method returns the convention used in specification of the activities, of which there are currently two, molar- and molality-based conventions.
virtual int standardStateConvention () const
This method returns the convention used in specification of the standard state, of which there are currently two, temperature based, and variable pressure based.
virtual void getUnitsStandardConc (double *uA, int k=0, int sizeUA=6) const
Returns the units of the standard and generalized concentrations.
virtual void getActivities (doublereal *a) const
Get the array of non-dimensional activities at the current solution temperature, pressure, and solution concentration.
virtual void getLnActivityCoefficients (doublereal *lnac) const
Get the array of non-dimensional molar-based ln activity coefficients at the current solution temperature, pressure, and solution concentration.
Partial Molar Properties of the Solution
virtual void getChemPotentials_RT (doublereal *mu) const
Get the array of non-dimensional species chemical potentials These are partial molar Gibbs free energies.
void getElectrochemPotentials (doublereal *mu) const
Get the species electrochemical potentials.
virtual void getdPartialMolarVolumes_dT (doublereal *d_vbar_dT) const
Return an array of derivatives of partial molar volumes wrt temperature for the species in the mixture.
virtual void getdPartialMolarVolumes_dP (doublereal *d_vbar_dP) const
Return an array of derivatives of partial molar volumes wrt pressure for the species in the mixture.
Properties of the Standard State of the Species in the Solution
virtual void getdStandardVolumes_dT (doublereal *d_vol_dT) const
Get the derivative of the molar volumes of the species standard states wrt temperature at the current T and P of the solution.
virtual void getdStandardVolumes_dP (doublereal *d_vol_dP) const
Get the derivative molar volumes of the species standard states wrt pressure at the current T and P of the solution.
Thermodynamic Values for the Species Reference States
virtual void setReferenceComposition (const doublereal *const x)
Sets the reference composition.
virtual void getReferenceComposition (doublereal *const x) const
Gets the reference composition.
Specific Properties
doublereal enthalpy_mass () const
Specific enthalpy.
doublereal intEnergy_mass () const
Specific internal energy.
doublereal entropy_mass () const
Specific entropy.
doublereal gibbs_mass () const
Specific Gibbs function.
doublereal cp_mass () const
Specific heat at constant pressure.
doublereal cv_mass () const
Specific heat at constant volume.
Setting the State
These methods set all or part of the thermodynamic state.
virtual void setState_TPX (doublereal t, doublereal p, const doublereal *x)
Set the temperature (K), pressure (Pa), and mole fractions.
void setState_TPX (doublereal t, doublereal p, compositionMap &x)
Set the temperature (K), pressure (Pa), and mole fractions.
void setState_TPX (doublereal t, doublereal p, const std::string &x)
Set the temperature (K), pressure (Pa), and mole fractions.
void setState_TPY (doublereal t, doublereal p, const doublereal *y)
Set the internally stored temperature (K), pressure (Pa), and mass fractions of the phase.
void setState_TPY (doublereal t, doublereal p, compositionMap &y)
Set the internally stored temperature (K), pressure (Pa), and mass fractions of the phase.
void setState_TPY (doublereal t, doublereal p, const std::string &y)
Set the internally stored temperature (K), pressure (Pa), and mass fractions of the phase.
void setState_TP (doublereal t, doublereal p)
Set the temperature (K) and pressure (Pa)
void setState_PX (doublereal p, doublereal *x)
Set the pressure (Pa) and mole fractions.
void setState_PY (doublereal p, doublereal *y)
Set the internally stored pressure (Pa) and mass fractions.
virtual void setState_HP (doublereal h, doublereal p, doublereal tol=1.e-4)
Set the internally stored specific enthalpy (J/kg) and pressure (Pa) of the phase.
virtual void setState_UV (doublereal u, doublereal v, doublereal tol=1.e-4)
Set the specific internal energy (J/kg) and specific volume (m^3/kg).
virtual void setState_SP (doublereal s, doublereal p, doublereal tol=1.e-4)
Set the specific entropy (J/kg/K) and pressure (Pa).
virtual void setState_SV (doublereal s, doublereal v, doublereal tol=1.e-4)
Set the specific entropy (J/kg/K) and specific volume (m^3/kg).
Chemical Equilibrium
Chemical equilibrium.
void setElementPotentials (const vector_fp &lambda)
Stores the element potentials in the ThermoPhase object.
bool getElementPotentials (doublereal *lambda) const
Returns the element potentials stored in the ThermoPhase object.
Critical State Properties.
These methods are only implemented by some subclasses, and may be moved out of ThermoPhase at a later date.
virtual doublereal critTemperature () const
Critical temperature (K).
virtual doublereal critPressure () const
Critical pressure (Pa).
virtual doublereal critDensity () const
Critical density (kg/m3).
Saturation Properties.
These methods are only implemented by subclasses that implement full liquid-vapor equations of state.
They may be moved out of ThermoPhase at a later date.
virtual doublereal satTemperature (doublereal p) const
Return the saturation temperature given the pressure.
virtual doublereal satPressure (doublereal t) const
Return the saturation pressure given the temperature.
virtual doublereal vaporFraction () const
Return the fraction of vapor at the current conditions.
virtual void setState_Tsat (doublereal t, doublereal x)
Set the state to a saturated system at a particular temperature.
virtual void setState_Psat (doublereal p, doublereal x)
Set the state to a saturated system at a particular pressure.
Initialization Methods - For Internal Use (ThermoPhase)
void saveSpeciesData (const size_t k, const XML_Node *const data)
Store a reference pointer to the XML tree containing the species data for this phase.
const std::vector< const
XML_Node * > & speciesData () const
Return a pointer to the vector of XML nodes containing the species data for this phase.
void setSpeciesThermo (SpeciesThermo *spthermo)
Install a species thermodynamic property manager.
virtual SpeciesThermo & speciesThermo (int k=-1)
Return a changeable reference to the calculation manager for species reference-state thermodynamic properties.
virtual void initThermoFile (std::string inputFile, std::string id)
virtual void initThermoXML (XML_Node &phaseNode, std::string id)
Import and initialize a ThermoPhase object using an XML tree.
virtual void installSlavePhases (Cantera::XML_Node *phaseNode)
Add in species from Slave phases.
virtual void setParameters (int n, doublereal *const c)
Set the equation of state parameters.
virtual void getParameters (int &n, doublereal *const c) const
Get the equation of state parameters in a vector.
virtual void setParametersFromXML (const XML_Node &eosdata)
Set equation of state parameter values from XML entries.
virtual void setStateFromXML (const XML_Node &state)
Set the initial state of the phase to the conditions specified in the state XML element.
Derivatives of Thermodynamic Variables needed for Applications
virtual void getdlnActCoeffds (const doublereal dTds, const doublereal *const dXds, doublereal *dlnActCoeffds) const
Get the change in activity coefficients wrt changes in state (temp, mole fraction, etc) along a line in parameter space or along a line in physical space.
virtual void getdlnActCoeffdlnX_diag (doublereal *dlnActCoeffdlnX_diag) const
Get the array of ln mole fraction derivatives of the log activity coefficients - diagonal component only.
virtual void getdlnActCoeffdlnN_diag (doublereal *dlnActCoeffdlnN_diag) const
Get the array of log species mole number derivatives of the log activity coefficients.
virtual void getdlnActCoeffdlnN (const size_t ld, doublereal *const dlnActCoeffdlnN)
Get the array of derivatives of the log activity coefficients with respect to the log of the species mole numbers.
virtual void getdlnActCoeffdlnN_numderiv (const size_t ld, doublereal *const dlnActCoeffdlnN)
Printing
virtual std::string report (bool show_thermo=true) const
returns a summary of the state of the phase as a string
virtual void reportCSV (std::ofstream &csvFile) const
returns a summary of the state of the phase to a comma separated file
Name and ID
Class Phase contains two strings that identify a phase. The ID is the value of the ID attribute of the XML phase node that is used to initialize a phase when it is read. The name field is also initialized to the value of the ID attribute of the XML phase node.
However, the name field may be changed to another value during the course of a calculation. For example, if a phase is located in two places, but has the same constitutive input, the ids of the two phases will be the same, but the names of the two phases may be different.
It is an error to have two phases in a single problem with the same name or the same id (or the name from one phase being the same as the id of another phase). Thus, it is expected that there is a 1-1 correspondence between names and unique phases within a Cantera problem.
std::string id () const
Return the string id for the phase.
void setID (std::string id)
Set the string id for the phase.
std::string name () const
Return the name of the phase.
void setName (std::string nm)
Sets the string name for the phase.
Element and Species Information
std::string elementName (size_t m) const
Name of the element with index m.
size_t elementIndex (std::string name) const
Return the index of element named 'name'.
const std::vector< std::string > & elementNames () const
Return a read-only reference to the vector of element names.
doublereal atomicWeight (size_t m) const
Atomic weight of element m.
doublereal entropyElement298 (size_t m) const
Entropy of the element in its standard state at 298 K and 1 bar.
int atomicNumber (size_t m) const
Atomic number of element m.
int elementType (size_t m) const
Return the element constraint type Possible types include:
int changeElementType (int m, int elem_type)
Change the element type of the mth constraint Reassigns an element type.
const vector_fp & atomicWeights () const
Return a read-only reference to the vector of atomic weights.
size_t nElements () const
Number of elements.
void checkElementIndex (size_t m) const
Check that the specified element index is in range Throws an exception if m is greater than nElements()-1.
void checkElementArraySize (size_t mm) const
Check that an array size is at least nElements() Throws an exception if mm is less than nElements().
doublereal nAtoms (size_t k, size_t m) const
Number of atoms of element m in species k.
void getAtoms (size_t k, double *atomArray) const
Get a vector containing the atomic composition of species k.
size_t speciesIndex (std::string name) const
Returns the index of a species named 'name' within the Phase object.
std::string speciesName (size_t k) const
Name of the species with index k.
std::string speciesSPName (int k) const
Returns the expanded species name of a species, including the phase name This is guaranteed to be unique within a Cantera problem.
const std::vector< std::string > & speciesNames () const
Return a const reference to the vector of species names.
size_t nSpecies () const
Returns the number of species in the phase.
void checkSpeciesIndex (size_t k) const
Check that the specified species index is in range Throws an exception if k is greater than nSpecies()-1.
void checkSpeciesArraySize (size_t kk) const
Check that an array size is at least nSpecies() Throws an exception if kk is less than nSpecies().
Set thermodynamic state
Set the internal thermodynamic state by setting the internally stored temperature, density and species composition. Note that the composition is always set first.
Temperature and density are held constant if not explicitly set.
void setMoleFractionsByName (compositionMap &xMap)
Set the species mole fractions by name.
void setMoleFractionsByName (const std::string &x)
Set the mole fractions of a group of species by name.
void setMassFractionsByName (compositionMap &yMap)
Set the species mass fractions by name.
void setMassFractionsByName (const std::string &x)
Set the species mass fractions by name.
void setState_TRX (doublereal t, doublereal dens, const doublereal *x)
Set the internally stored temperature (K), density, and mole fractions.
void setState_TRX (doublereal t, doublereal dens, compositionMap &x)
Set the internally stored temperature (K), density, and mole fractions.
void setState_TRY (doublereal t, doublereal dens, const doublereal *y)
Set the internally stored temperature (K), density, and mass fractions.
void setState_TRY (doublereal t, doublereal dens, compositionMap &y)
Set the internally stored temperature (K), density, and mass fractions.
void setState_TNX (doublereal t, doublereal n, const doublereal *x)
Set the internally stored temperature (K), molar density (kmol/m^3), and mole fractions.
void setState_TR (doublereal t, doublereal rho)
Set the internally stored temperature (K) and density (kg/m^3)
void setState_TX (doublereal t, doublereal *x)
Set the internally stored temperature (K) and mole fractions.
void setState_TY (doublereal t, doublereal *y)
Set the internally stored temperature (K) and mass fractions.
void setState_RX (doublereal rho, doublereal *x)
Set the density (kg/m^3) and mole fractions.
void setState_RY (doublereal rho, doublereal *y)
Set the density (kg/m^3) and mass fractions.
Composition
void getMoleFractionsByName (compositionMap &x) const
Get the mole fractions by name.
doublereal moleFraction (size_t k) const
Return the mole fraction of a single species.
doublereal moleFraction (std::string name) const
Return the mole fraction of a single species.
doublereal massFraction (size_t k) const
Return the mass fraction of a single species.
doublereal massFraction (std::string name) const
Return the mass fraction of a single species.
void getMoleFractions (doublereal *const x) const
Get the species mole fraction vector.
virtual void setMoleFractions (const doublereal *const x)
Set the mole fractions to the specified values There is no restriction on the sum of the mole fraction vector.
virtual void setMoleFractions_NoNorm (const doublereal *const x)
Set the mole fractions to the specified values without normalizing.
void getMassFractions (doublereal *const y) const
Get the species mass fractions.
const doublereal * massFractions () const
Return a const pointer to the mass fraction array.
virtual void setMassFractions (const doublereal *const y)
Set the mass fractions to the specified values and normalize them.
virtual void setMassFractions_NoNorm (const doublereal *const y)
Set the mass fractions to the specified values without normalizing.
void getConcentrations (doublereal *const c) const
Get the species concentrations (kmol/m^3).
doublereal concentration (const size_t k) const
Concentration of species k.
virtual void setConcentrations (const doublereal *const conc)
Set the concentrations to the specified values within the phase.
const doublereal * moleFractdivMMW () const
Returns a const pointer to the start of the moleFraction/MW array.
Thermodynamic Properties
doublereal temperature () const
Temperature (K).
virtual doublereal density () const
Density (kg/m^3).
doublereal molarDensity () const
Molar density (kmol/m^3).
doublereal molarVolume () const
Molar volume (m^3/kmol).
virtual void setDensity (const doublereal density)
Set the internally stored density (kg/m^3) of the phase Note the density of a phase is an independent variable.
virtual void setMolarDensity (const doublereal molarDensity)
Set the internally stored molar density (kmol/m^3) of the phase.
virtual void setTemperature (const doublereal temp)
Set the internally stored temperature of the phase (K).
Mean Properties
doublereal mean_X (const doublereal *const Q) const
Evaluate the mole-fraction-weighted mean of an array Q.
doublereal mean_Y (const doublereal *const Q) const
Evaluate the mass-fraction-weighted mean of an array Q.
doublereal meanMolecularWeight () const
The mean molecular weight. Units: (kg/kmol)
doublereal sum_xlogx () const
Evaluate \(\sum_k X_k \log X_k \).
doublereal sum_xlogQ (doublereal *const Q) const
Evaluate \(\sum_k X_k \log Q_k \).
Adding Elements and Species
These methods are used to add new elements or species.
These are not usually called by user programs.
Since species are checked to insure that they are only composed of declared elements, it is necessary to first add all elements before adding any species.
void addElement (const std::string &symbol, doublereal weight=-12345.0)
Add an element.
void addElement (const XML_Node &e)
Add an element from an XML specification.
void addUniqueElement (const std::string &symbol, doublereal weight=-12345.0, int atomicNumber=0, doublereal entropy298=ENTROPY298_UNKNOWN, int elem_type=CT_ELEM_TYPE_ABSPOS)
Add an element, checking for uniqueness The uniqueness is checked by comparing the string symbol.
void addUniqueElement (const XML_Node &e)
Add an element, checking for uniqueness The uniqueness is checked by comparing the string symbol.
void addElementsFromXML (const XML_Node &phase)
Add all elements referenced in an XML_Node tree.
void freezeElements ()
Prohibit addition of more elements, and prepare to add species.
bool elementsFrozen ()
True if freezeElements has been called.
size_t addUniqueElementAfterFreeze (const std::string &symbol, doublereal weight, int atomicNumber, doublereal entropy298=ENTROPY298_UNKNOWN, int elem_type=CT_ELEM_TYPE_ABSPOS)
Add an element after elements have been frozen, checking for uniqueness The uniqueness is checked by comparing the string symbol.
void addSpecies (const std::string &name, const doublereal *comp, doublereal charge=0.0, doublereal size=1.0)
void addUniqueSpecies (const std::string &name, const doublereal *comp, doublereal charge=0.0, doublereal size=1.0)
Add a species to the phase, checking for uniqueness of the name This routine checks for uniqueness of the string name.
Protected Member Functions
void init (const vector_fp &mw)
void setMolecularWeight (const int k, const double mw)
Set the molecular weight of a single species to a given value.
Protected Attributes
size_t m_mm
Number of Elements in the phase.
doublereal m_tmin
Minimum temperature for valid species standard state thermo props.
doublereal m_tmax
Maximum temperature for valid species standard state thermo props.
doublereal m_p0
Reference state pressure.
doublereal m_tlast
last value of the temperature processed by reference state
doublereal m_logc0
Temporary storage for log of p/rt.
vector_fp m_h0_RT
Temporary storage for dimensionless reference state enthalpies.
vector_fp m_cp0_R
Temporary storage for dimensionless reference state heat capacities.
vector_fp m_g0_RT
Temporary storage for dimensionless reference state gibbs energies.
vector_fp m_s0_R
Temporary storage for dimensionless reference state entropies.
vector_fp m_expg0_RT
currently unsed
vector_fp m_pe
Currently unused.
vector_fp m_pp
Temporary array containing internally calculated partial pressures.
SpeciesThermo * m_spthermo
Pointer to the calculation manager for species reference-state thermodynamic properties.
std::vector< const XML_Node * > m_speciesData
Vector of pointers to the species databases.
doublereal m_phi
Stored value of the electric potential for this phase.
vector_fp m_lambdaRRT
Vector of element potentials.
bool m_hasElementPotentials
Boolean indicating whether there is a valid set of saved element potentials for this phase.
bool m_chargeNeutralityNecessary
Boolean indicating whether a charge neutrality condition is a necessity.
int m_ssConvention
Contains the standard state convention.
std::vector< doublereal > xMol_Ref
Reference Mole Fraction Composition.
size_t m_kk
Number of species in the phase.
size_t m_ndim
Dimensionality of the phase.
vector_fp m_speciesComp
Atomic composition of the species.
vector_fp m_speciesSize
Vector of species sizes.
vector_fp m_speciesCharge
Vector of species charges. length m_kk.
Private Member Functions
void _updateThermo () const
Update the species reference state thermodynamic functions.
Detailed Description
Class IdealGasPhase represents low-density gases that obey the ideal gas equation of state.
IdealGasPhase derives from class ThermoPhase, and overloads the virtual methods defined there with ones that use expressions appropriate for ideal gas mixtures.
The independent unknowns are density, mass fraction, and temperature. the setPressure() function will calculate the density consistent with the current mass fraction vector and temperature and the desired pressure, and then set the density.
Specification of Species Standard State Properties
It is assumed that the reference state thermodynamics may be obtained by a pointer to a populated species thermodynamic property manager class in the base class, ThermoPhase::m_spthermo (see the base class SpeciesThermo for a description of the specification of reference state species thermodynamics functions). The reference state, where the pressure is fixed at a single pressure, is a key species property calculation for the Ideal Gas Equation of state.
This class is optimized for speed of execution. All calls to thermodynamic functions first call internal routines (aka enthalpy_RT_ref()) which return references the reference state thermodynamics functions. Within these internal reference state functions, the function _updateThermo() is called, that first checks to see whether the temperature has changed. If it has, it updates the internal reference state thermo functions by calling the SpeciesThermo object.
Functions for the calculation of standard state properties for species at arbitrary pressure are provided in IdealGasPhase. However, they are all derived from their reference state counterparts.
The standard state enthalpy is independent of pressure:
\[ h^o_k(T,P) = h^{ref}_k(T) \]
The standard state constant-pressure heat capacity is independent of pressure:
\[ Cp^o_k(T,P) = Cp^{ref}_k(T) \]
The standard state entropy depends in the following fashion on pressure:
\[ S^o_k(T,P) = S^{ref}_k(T) - R \ln(\frac{P}{P_{ref}}) \]
The standard state gibbs free energy is obtained from the enthalpy and entropy functions:
\[ \mu^o_k(T,P) = h^o_k(T,P) - S^o_k(T,P) T \]
\[ \mu^o_k(T,P) = \mu^{ref}_k(T) + R T \ln(\frac{P}{P_{ref}}) \]
where
\[ \mu^{ref}_k(T) = h^{ref}_k(T) - T S^{ref}_k(T) \]
The standard state internal energy is obtained from the enthalpy function also
\[ u^o_k(T,P) = h^o_k(T) - R T \]
The molar volume of a species is given by the ideal gas law
\[ V^o_k(T,P) = \frac{R T}{P} \mbox{\quad where} \]
R is the molar gas constant. For a complete list of physical constants used within Cantera, see Physical Constants .
Specification of Solution Thermodynamic Properties
The activity of a species defined in the phase is given by the ideal gas law:
\[ a_k = X_k \]
where \(X_k \) is the mole fraction of species k. The chemical potential for species k is equal to
\[ \mu_k(T,P) = \mu^o_k(T, P) + R T \log(X_k) \]
In terms of the reference state, the above can be rewritten
\[ \mu_k(T,P) = \mu^{ref}_k(T, P) + R T \log(\frac{P X_k}{P_{ref}}) \]
The partial molar entropy for species k is given by the following relation,
\[ \tilde{s}_k(T,P) = s^o_k(T,P) - R \log(X_k) = s^{ref}_k(T) - R \log(\frac{P X_k}{P_{ref}}) \]
The partial molar enthalpy for species k is
\[ \tilde{h}_k(T,P) = h^o_k(T,P) = h^{ref}_k(T) \]
The partial molar Internal Energy for species k is
\[ \tilde{u}_k(T,P) = u^o_k(T,P) = u^{ref}_k(T) \]
The partial molar Heat Capacity for species k is
\[ \tilde{Cp}_k(T,P) = Cp^o_k(T,P) = Cp^{ref}_k(T) \]
Application within Kinetics Managers
\(C^a_k\) are defined such that \(a_k = C^a_k / C^s_k, \) where \(C^s_k \) is a standard concentration defined below and \(a_k \) are activities used in the thermodynamic functions. These activity (or generalized) concentrations are used by kinetics manager classes to compute the forward and reverse rates of elementary reactions. The activity concentration, \(C^a_k \),is given by the following expression.
\[ C^a_k = C^s_k X_k = \frac{P}{R T} X_k \]
The standard concentration for species k is independent of k and equal to
\[ C^s_k = C^s = \frac{P}{R T} \]
For example, a bulk-phase binary gas reaction between species j and k, producing a new gas species l would have the following equation for its rate of progress variable, \(R^1 \), which has units of kmol m-3 s-1.
\[ R^1 = k^1 C_j^a C_k^a = k^1 (C^s a_j) (C^s a_k) \]
where
\[ C_j^a = C^s a_j \mbox{\quad and \quad} C_k^a = C^s a_k \]
\(C_j^a \) is the activity concentration of species j, and \(C_k^a \) is the activity concentration of species k. \(C^s \) is the standard concentration. \(a_j \) is the activity of species j which is equal to the mole fraction of j.
The reverse rate constant can then be obtained from the law of microscopic reversibility and the equilibrium expression for the system.
\[ \frac{a_j a_k}{ a_l} = K_a^{o,1} = \exp(\frac{\mu^o_l - \mu^o_j - \mu^o_k}{R T}) \]
\(K_a^{o,1} \) is the dimensionless form of the equilibrium constant, associated with the pressure dependent standard states \(\mu^o_l(T,P) \) and their associated activities, \(a_l \), repeated here:
\[ \mu_l(T,P) = \mu^o_l(T, P) + R T \log(a_l) \]
We can switch over to expressing the equilibrium constant in terms of the reference state chemical potentials
\[ K_a^{o,1} = \exp(\frac{\mu^{ref}_l - \mu^{ref}_j - \mu^{ref}_k}{R T}) * \frac{P_{ref}}{P} \]
The concentration equilibrium constant, \(K_c \), may be obtained by changing over to activity concentrations. When this is done:
\[ \frac{C^a_j C^a_k}{ C^a_l} = C^o K_a^{o,1} = K_c^1 = \exp(\frac{\mu^{ref}_l - \mu^{ref}_j - \mu^{ref}_k}{R T}) * \frac{P_{ref}}{RT} \]
Kinetics managers will calculate the concentration equilibrium constant, \(K_c \), using the second and third part of the above expression as a definition for the concentration equilibrium constant.
For completeness, the pressure equilibrium constant may be obtained as well
\[ \frac{P_j P_k}{ P_l P_{ref}} = K_p^1 = \exp(\frac{\mu^{ref}_l - \mu^{ref}_j - \mu^{ref}_k}{R T}) \]
\(K_p \) is the simplest form of the equilibrium constant for ideal gases. However, it isn't necessarily the simplest form of the equilibrium constant for other types of phases; \(K_c \) is used instead because it is completely general.
The reverse rate of progress may be written down as
\[ R^{-1} = k^{-1} C_l^a = k^{-1} (C^o a_l) \]
where we can use the concept of microscopic reversibility to write the reverse rate constant in terms of the forward rate constant and the concentration equilibrium constant, \(K_c \).
\[ k^{-1} = k^1 K^1_c \]
\(k^{-1} \) has units of s-1.
Instantiation of the Class
The constructor for this phase is located in the default ThermoFactory for Cantera. A new IdealGasPhase may be created by the following code snippet:
XML_Node *xc = get_XML_File("silane.xml");
XML_Node * const xs = xc->findNameID("phase", "silane");
ThermoPhase *silane_tp = newPhase(*xs);
IdealGasPhase *silaneGas = dynamic_cast <IdealGasPhase *>(silane_tp);
or by the following constructor:
XML_Node *xc = get_XML_File("silane.xml");
XML_Node * const xs = xc->findNameID("phase", "silane");
IdealGasPhase *silaneGas = new IdealGasPhase(*xs);
XML Example
An example of an XML Element named phase setting up a IdealGasPhase object named silane is given below.
<!--     phase silane      -->
<phase dim="3" id="silane">
   <elementArray datasrc="elements.xml"> Si  H  He </elementArray>
   <speciesArray datasrc="#species_data">
           H2  H  HE  SIH4  SI  SIH  SIH2  SIH3  H3SISIH  SI2H6
                  H2SISIH2  SI3H8  SI2  SI3
   </speciesArray>
   <reactionArray datasrc="#reaction_data"/>
   <thermo model="IdealGas"/>
   <kinetics model="GasKinetics"/>
   <transport model="None"/>
 </phase>
The model attribute "IdealGas" of the thermo XML element identifies the phase as being of the type handled by the IdealGasPhase object.
Definition at line 308 of file IdealGasPhase.h.
Constructor & Destructor Documentation
IdealGasPhase ()
Default empty Constructor.
Definition at line 18 of file IdealGasPhase.cpp.
Referenced by IdealGasPhase::duplMyselfAsThermoPhase().
IdealGasPhase (const IdealGasPhase & right)
Copy Constructor.
Copy constructor for the object. Constructed object will be a clone of this object, but will also own all of its data. This is a wrapper around the assignment operator
Parameters
right Object to be copied.
Definition at line 29 of file IdealGasPhase.cpp.
virtual ~IdealGasPhase () inline virtual
Destructor.
Definition at line 339 of file IdealGasPhase.h.
Member Function Documentation
IdealGasPhase & operator= (const IdealGasPhase & right)
Assignment operator.
Assignment operator for the object. Constructed object will be a clone of this object, but will also own all of its data.
Parameters
right Object to be copied.
Definition at line 53 of file IdealGasPhase.cpp.
References IdealGasPhase::m_cp0_R, IdealGasPhase::m_expg0_RT, IdealGasPhase::m_g0_RT, IdealGasPhase::m_h0_RT, IdealGasPhase::m_logc0, IdealGasPhase::m_mm, IdealGasPhase::m_p0, IdealGasPhase::m_pe, IdealGasPhase::m_pp, IdealGasPhase::m_s0_R, IdealGasPhase::m_tlast, IdealGasPhase::m_tmax, IdealGasPhase::m_tmin, and ThermoPhase::operator=().
ThermoPhase * duplMyselfAsThermoPhase () const virtual
Duplicator from the ThermoPhase parent class.
Given a pointer to a ThermoPhase object, this function will duplicate the ThermoPhase object and all underlying structures. This is basically a wrapper around the inherited copy constructor.
Returns
returns a pointer to a ThermoPhase object, containing a copy of the current object
Reimplemented from ThermoPhase.
Definition at line 82 of file IdealGasPhase.cpp.
References IdealGasPhase::IdealGasPhase().
virtual int eosType () const inline virtual
Equation of state flag.
Returns the value cIdealGas, defined in mix_defs.h.
Reimplemented from ThermoPhase.
Definition at line 356 of file IdealGasPhase.h.
References Cantera::cIdealGas.
virtual doublereal enthalpy_mole () const inline virtual
Return the Molar enthalpy. Units: J/kmol.
For an ideal gas mixture,
\[ \hat h(T) = \sum_k X_k \hat h^0_k(T), \]
and is a function only of temperature. The standard-state pure-species enthalpies \(\hat h^0_k(T) \) are computed by the species thermodynamic property manager.
See Also
SpeciesThermo
Reimplemented from ThermoPhase.
Definition at line 379 of file IdealGasPhase.h.
References IdealGasPhase::enthalpy_RT_ref(), Cantera::GasConstant, Phase::mean_X(), and Phase::temperature().
Referenced by IdealGasPhase::gibbs_mole().
doublereal intEnergy_mole () const virtual
Molar internal energy.
J/kmol. For an ideal gas mixture,
\[ \hat u(T) = \sum_k X_k \hat h^0_k(T) - \hat R T, \]
and is a function only of temperature. The reference-state pure-species enthalpies \(\hat h^0_k(T) \) are computed by the species thermodynamic property manager.
See Also
SpeciesThermo
Reimplemented from ThermoPhase.
Definition at line 101 of file IdealGasPhase.cpp.
References IdealGasPhase::enthalpy_RT_ref(), Cantera::GasConstant, Phase::mean_X(), and Phase::temperature().
doublereal entropy_mole () const virtual
Molar entropy.
Units: J/kmol/K. For an ideal gas mixture,
\[ \hat s(T, P) = \sum_k X_k \hat s^0_k(T) - \hat R \log (P/P^0). \]
The reference-state pure-species entropies \(\hat s^0_k(T) \) are computed by the species thermodynamic property manager.
See Also
SpeciesThermo
Reimplemented from ThermoPhase.
Definition at line 118 of file IdealGasPhase.cpp.
References IdealGasPhase::entropy_R_ref(), Cantera::GasConstant, ThermoPhase::m_spthermo, Phase::mean_X(), IdealGasPhase::pressure(), SpeciesThermo::refPressure(), and Phase::sum_xlogx().
Referenced by IdealGasPhase::gibbs_mole().
doublereal gibbs_mole () const virtual
Molar Gibbs free Energy for an ideal gas.
Units = J/kmol.
Reimplemented from ThermoPhase.
Definition at line 128 of file IdealGasPhase.cpp.
References IdealGasPhase::enthalpy_mole(), IdealGasPhase::entropy_mole(), and Phase::temperature().
doublereal cp_mole () const virtual
Molar heat capacity at constant pressure.
Units: J/kmol/K. For an ideal gas mixture,
\[ \hat c_p(t) = \sum_k \hat c^0_{p,k}(T). \]
The reference-state pure-species heat capacities \(\hat c^0_{p,k}(T) \) are computed by the species thermodynamic property manager.
See Also
SpeciesThermo
Reimplemented from ThermoPhase.
Definition at line 144 of file IdealGasPhase.cpp.
References IdealGasPhase::cp_R_ref(), Cantera::GasConstant, and Phase::mean_X().
Referenced by IdealGasPhase::cv_mole().
doublereal cv_mole () const virtual
Molar heat capacity at constant volume.
Units: J/kmol/K. For an ideal gas mixture,
\[ \hat c_v = \hat c_p - \hat R. \]
Reimplemented from ThermoPhase.
Definition at line 154 of file IdealGasPhase.cpp.
References IdealGasPhase::cp_mole(), and Cantera::GasConstant.
virtual doublereal pressure () const inline virtual
Pressure.
Units: Pa. For an ideal gas mixture,
\[ P = n \hat R T. \]
Reimplemented from ThermoPhase.
Definition at line 448 of file IdealGasPhase.h.
References Cantera::GasConstant, Phase::molarDensity(), and Phase::temperature().
Referenced by IdealGasPhase::entropy_mole(), IdealGasPhase::getEntropy_R(), IdealGasPhase::getGibbs_RT(), IdealGasPhase::getPartialMolarEntropies(), IdealGasPhase::getPureGibbs(), IdealGasPhase::getStandardChemPotentials(), IdealGasPhase::isothermalCompressibility(), IdealGasPhase::logStandardConc(), and IdealGasPhase::standardConcentration().
virtual void setPressure (doublereal p) inline virtual
Set the pressure at constant temperature and composition.
Units: Pa. This method is implemented by setting the mass density to
\[ \rho = \frac{P \overline W}{\hat R T }. \]
Parameters
p Pressure (Pa)
Reimplemented from ThermoPhase.
Definition at line 463 of file IdealGasPhase.h.
References Cantera::GasConstant, Phase::meanMolecularWeight(), Phase::setDensity(), and Phase::temperature().
Referenced by StFlow::setGas(), and StFlow::setGasAtMidpoint().
virtual doublereal isothermalCompressibility () const inline virtual
Returns the isothermal compressibility. Units: 1/Pa.
The isothermal compressibility is defined as
\[ \kappa_T = -\frac{1}{v}\left(\frac{\partial v}{\partial P}\right)_T \]
For ideal gases it's equal to the inverse of the pressure
Reimplemented from ThermoPhase.
Definition at line 476 of file IdealGasPhase.h.
References IdealGasPhase::pressure().
virtual doublereal thermalExpansionCoeff () const inline virtual
Return the volumetric thermal expansion coefficient. Units: 1/K.
The thermal expansion coefficient is defined as
\[ \beta = \frac{1}{v}\left(\frac{\partial v}{\partial T}\right)_P \]
For ideal gases, it's equal to the inverse of the temperature.
Reimplemented from ThermoPhase.
Definition at line 488 of file IdealGasPhase.h.
References Phase::temperature().
virtual void getActivityConcentrations (doublereal * c) const inline virtual
This method returns the array of generalized concentrations.
For an ideal gas mixture, these are simply the actual concentrations.
Parameters
c Output array of generalized concentrations. The units depend upon the implementation of the reaction rate expressions within the phase.
Reimplemented from ThermoPhase.
Definition at line 537 of file IdealGasPhase.h.
References Phase::getConcentrations().
doublereal standardConcentration (size_t k = 0) const virtual
Returns the standard concentration \(C^0_k \), which is used to normalize the generalized concentration.
This is defined as the concentration by which the generalized concentration is normalized to produce the activity. In many cases, this quantity will be the same for all species in a phase. Since the activity for an ideal gas mixture is simply the mole fraction, for an ideal gas \(C^0_k = P/\hat R T \).
Parameters
k Optional parameter indicating the species. The default is to assume this refers to species 0.
Returns
Returns the standard Concentration in units of m3 kmol-1.
Reimplemented from ThermoPhase.
Definition at line 166 of file IdealGasPhase.cpp.
References Cantera::GasConstant, IdealGasPhase::pressure(), and Phase::temperature().
doublereal logStandardConc (size_t k = 0) const virtual
Returns the natural logarithm of the standard concentration of the kth species.
Parameters
k index of the species. (defaults to zero)
Reimplemented from ThermoPhase.
Definition at line 176 of file IdealGasPhase.cpp.
References IdealGasPhase::_updateThermo(), Cantera::GasConstant, IdealGasPhase::pressure(), and Phase::temperature().
void getActivityCoefficients (doublereal * ac) const virtual
Get the array of non-dimensional activity coefficients at the current solution temperature, pressure, and solution concentration.
For ideal gases, the activity coefficients are all equal to one.
Parameters
ac Output vector of activity coefficients. Length: m_kk.
Reimplemented from ThermoPhase.
Definition at line 187 of file IdealGasPhase.cpp.
References Phase::m_kk.
void getChemPotentials (doublereal * mu) const virtual
Get the species chemical potentials. Units: J/kmol.
This function returns a vector of chemical potentials of the species in solution at the current temperature, pressure and mole fraction of the solution.
Parameters
mu Output vector of species chemical potentials. Length: m_kk. Units: J/kmol
Reimplemented from ThermoPhase.
Definition at line 211 of file IdealGasPhase.cpp.
References Cantera::GasConstant, IdealGasPhase::getStandardChemPotentials(), Phase::m_kk, ckr::max(), Phase::moleFraction(), Cantera::SmallNumber, and Phase::temperature().
void getPartialMolarEnthalpies (doublereal * hbar) const virtual
Get the species partial molar enthalpies. Units: J/kmol.
Parameters
hbar Output vector of species partial molar enthalpies. Length: m_kk. units are J/kmol.
Reimplemented from ThermoPhase.
Definition at line 228 of file IdealGasPhase.cpp.
References IdealGasPhase::enthalpy_RT_ref(), Cantera::GasConstant, Cantera::scale(), and Phase::temperature().
void getPartialMolarEntropies (doublereal * sbar) const virtual
Get the species partial molar entropies. Units: J/kmol/K.
Parameters
sbar Output vector of species partial molar entropies. Length = m_kk. units are J/kmol/K.
Reimplemented from ThermoPhase.
Definition at line 239 of file IdealGasPhase.cpp.
References IdealGasPhase::entropy_R_ref(), Cantera::GasConstant, Phase::m_kk, ThermoPhase::m_spthermo, ckr::max(), Phase::moleFraction(), IdealGasPhase::pressure(), SpeciesThermo::refPressure(), Cantera::scale(), and Cantera::SmallNumber.
void getPartialMolarIntEnergies (doublereal * ubar) const virtual
Get the species partial molar enthalpies. Units: J/kmol.
Parameters
ubar Output vector of species partial molar internal energies. Length = m_kk. units are J/kmol.
Reimplemented from ThermoPhase.
Definition at line 255 of file IdealGasPhase.cpp.
References IdealGasPhase::enthalpy_RT_ref(), Cantera::GasConstant, Phase::m_kk, and Phase::temperature().
void getPartialMolarCp (doublereal * cpbar) const virtual
Get the partial molar heat capacities Units: J/kmol/K.
Parameters
cpbar Output vector of species partial molar heat capacities at constant pressure. Length = m_kk. units are J/kmol/K.
Reimplemented from ThermoPhase.
Definition at line 267 of file IdealGasPhase.cpp.
References IdealGasPhase::cp_R_ref(), Cantera::GasConstant, and Cantera::scale().
void getPartialMolarVolumes (doublereal * vbar) const virtual
Get the species partial molar volumes. Units: m^3/kmol.
Parameters
vbar Output vector of species partial molar volumes. Length = m_kk. units are m^3/kmol.
Reimplemented from ThermoPhase.
Definition at line 277 of file IdealGasPhase.cpp.
References Phase::m_kk, and Phase::molarDensity().
void getStandardChemPotentials (doublereal * mu) const virtual
Get the array of chemical potentials at unit activity for the species standard states at the current T and P of the solution.
These are the standard state chemical potentials \(\mu^0_k(T,P) \). The values are evaluated at the current temperature and pressure of the solution
Parameters
mu Output vector of chemical potentials. Length: m_kk.
Reimplemented from ThermoPhase.
Definition at line 198 of file IdealGasPhase.cpp.
References ThermoPhase::_RT(), Cantera::GasConstant, IdealGasPhase::gibbs_RT_ref(), Phase::m_kk, ThermoPhase::m_spthermo, IdealGasPhase::pressure(), SpeciesThermo::refPressure(), Cantera::scale(), and Phase::temperature().
Referenced by IdealGasPhase::getChemPotentials().
void getEnthalpy_RT (doublereal * hrt) const virtual
Get the nondimensional Enthalpy functions for the species standard states at their standard states at the current T and P of the solution.
Parameters
hrt Output vector of nondimensional standard state enthalpies. Length: m_kk.
Reimplemented from ThermoPhase.
Definition at line 292 of file IdealGasPhase.cpp.
References IdealGasPhase::enthalpy_RT_ref().
void getEntropy_R (doublereal * sr) const virtual
Get the array of nondimensional Entropy functions for the species standard states at the current T and P of the solution.
Parameters
sr Output vector of nondimensional standard state entropies. Length: m_kk.
Reimplemented from ThermoPhase.
Definition at line 303 of file IdealGasPhase.cpp.
References IdealGasPhase::entropy_R_ref(), Phase::m_kk, ThermoPhase::m_spthermo, IdealGasPhase::pressure(), and SpeciesThermo::refPressure().
void getGibbs_RT (doublereal * grt) const virtual
Get the nondimensional Gibbs functions for the species standard states at the current T and P of the solution.
Parameters
grt Output vector of nondimensional standard state gibbs free energies Length: m_kk.
Reimplemented from ThermoPhase.
Definition at line 317 of file IdealGasPhase.cpp.
References IdealGasPhase::gibbs_RT_ref(), Phase::m_kk, ThermoPhase::m_spthermo, IdealGasPhase::pressure(), and SpeciesThermo::refPressure().
void getPureGibbs (doublereal * gpure) const virtual
Get the Gibbs functions for the standard state of the species at the current T and P of the solution.
Units are Joules/kmol
Parameters
gpure Output vector of standard state gibbs free energies Length: m_kk.
Reimplemented from ThermoPhase.
Definition at line 332 of file IdealGasPhase.cpp.
References ThermoPhase::_RT(), IdealGasPhase::gibbs_RT_ref(), Phase::m_kk, ThermoPhase::m_spthermo, IdealGasPhase::pressure(), SpeciesThermo::refPressure(), and Cantera::scale().
void getIntEnergy_RT (doublereal * urt) const virtual
Returns the vector of nondimensional Internal Energies of the standard state species at the current T and P of the solution.
Parameters
urt output vector of nondimensional standard state internal energies of the species. Length: m_kk.
Reimplemented from ThermoPhase.
Definition at line 348 of file IdealGasPhase.cpp.
References IdealGasPhase::enthalpy_RT_ref(), and Phase::m_kk.
void getCp_R (doublereal * cpr) const virtual
Get the nondimensional Heat Capacities at constant pressure for the species standard states at the current T and P of the solution.
Parameters
cpr Output vector of nondimensional standard state heat capacities Length: m_kk.
Reimplemented from ThermoPhase.
Definition at line 361 of file IdealGasPhase.cpp.
References IdealGasPhase::cp_R_ref().
void getStandardVolumes (doublereal * vol) const virtual
Get the molar volumes of the species standard states at the current T and P of the solution.
units = m^3 / kmol
Parameters
vol Output vector containing the standard state volumes. Length: m_kk.
Reimplemented from ThermoPhase.
Definition at line 375 of file IdealGasPhase.cpp.
References Phase::m_kk, and Phase::molarDensity().
void getEnthalpy_RT_ref (doublereal * hrt) const virtual
Returns the vector of nondimensional enthalpies of the reference state at the current temperature of the solution and the reference pressure for the species.
Parameters
hrt Output vector containing the nondimensional reference state enthalpies. Length: m_kk.
Reimplemented from ThermoPhase.
Definition at line 390 of file IdealGasPhase.cpp.
References IdealGasPhase::enthalpy_RT_ref().
void getGibbs_RT_ref (doublereal * grt) const virtual
Returns the vector of nondimensional Gibbs Free Energies of the reference state at the current temperature of the solution and the reference pressure for the species.
Parameters
grt Output vector containing the nondimensional reference state Gibbs Free energies. Length: m_kk.
Reimplemented from ThermoPhase.
Definition at line 401 of file IdealGasPhase.cpp.
References IdealGasPhase::gibbs_RT_ref().
void getGibbs_ref (doublereal * g) const virtual
Returns the vector of the gibbs function of the reference state at the current temperature of the solution and the reference pressure for the species.
units = J/kmol
Parameters
g Output vector containing the reference state Gibbs Free energies. Length: m_kk. Units: J/kmol.
Reimplemented from ThermoPhase.
Definition at line 413 of file IdealGasPhase.cpp.
References ThermoPhase::_RT(), IdealGasPhase::gibbs_RT_ref(), and Cantera::scale().
void getEntropy_R_ref (doublereal * er) const virtual
Returns the vector of nondimensional entropies of the reference state at the current temperature of the solution and the reference pressure for each species.
Parameters
er Output vector containing the nondimensional reference state entropies. Length: m_kk.
Reimplemented from ThermoPhase.
Definition at line 424 of file IdealGasPhase.cpp.
References IdealGasPhase::entropy_R_ref().
void getIntEnergy_RT_ref (doublereal * urt) const virtual
Returns the vector of nondimensional internal Energies of the reference state at the current temperature of the solution and the reference pressure for each species.
Parameters
urt Output vector of nondimensional reference state internal energies of the species. Length: m_kk
Reimplemented from ThermoPhase.
Definition at line 435 of file IdealGasPhase.cpp.
References IdealGasPhase::enthalpy_RT_ref(), and Phase::m_kk.
void getCp_R_ref (doublereal * cprt) const virtual
Returns the vector of nondimensional constant pressure heat capacities of the reference state at the current temperature of the solution and reference pressure for each species.
Parameters
cprt Output vector of nondimensional reference state heat capacities at constant pressure for the species. Length: m_kk
Reimplemented from ThermoPhase.
Definition at line 448 of file IdealGasPhase.cpp.
References IdealGasPhase::cp_R_ref().
void getStandardVolumes_ref (doublereal * vol) const virtual
Get the molar volumes of the species standard states at the current T and P_ref of the solution.
units = m^3 / kmol
Parameters
vol Output vector containing the standard state volumes. Length: m_kk.
Reimplemented from ThermoPhase.
Definition at line 454 of file IdealGasPhase.cpp.
References ThermoPhase::_RT(), Phase::m_kk, and IdealGasPhase::m_p0.
const vector_fp& enthalpy_RT_ref () const inline
Returns a reference to the dimensionless reference state enthalpy vector.
This function is part of the layer that checks/recalculates the reference state thermo functions.
Definition at line 791 of file IdealGasPhase.h.
References IdealGasPhase::_updateThermo(), and IdealGasPhase::m_h0_RT.
Referenced by IdealGasPhase::enthalpy_mole(), AxiStagnFlow::eval(), FreeFlame::eval(), IdealGasPhase::getEnthalpy_RT(), IdealGasPhase::getEnthalpy_RT_ref(), IdealGasPhase::getIntEnergy_RT(), IdealGasPhase::getIntEnergy_RT_ref(), IdealGasPhase::getPartialMolarEnthalpies(), IdealGasPhase::getPartialMolarIntEnergies(), and IdealGasPhase::intEnergy_mole().
const vector_fp& gibbs_RT_ref () const inline
Returns a reference to the dimensionless reference state Gibbs free energy vector.
This function is part of the layer that checks/recalculates the reference state thermo functions.
Definition at line 801 of file IdealGasPhase.h.
References IdealGasPhase::_updateThermo(), and IdealGasPhase::m_g0_RT.
Referenced by IdealGasPhase::getGibbs_ref(), IdealGasPhase::getGibbs_RT(), IdealGasPhase::getGibbs_RT_ref(), IdealGasPhase::getPureGibbs(), IdealGasPhase::getStandardChemPotentials(), and IdealGasPhase::setToEquilState().
const vector_fp& expGibbs_RT_ref () const inline
Returns a reference to the exponent of the dimensionless reference state Gibbs Free energy vector.
This function is part of the layer that checks/recalculates the reference state thermo functions.
Definition at line 811 of file IdealGasPhase.h.
References IdealGasPhase::_updateThermo(), IdealGasPhase::m_expg0_RT, IdealGasPhase::m_g0_RT, and Phase::m_kk.
const vector_fp& entropy_R_ref () const inline
Returns a reference to the dimensionless reference state Entropy vector.
This function is part of the layer that checks/recalculates the reference state thermo functions.
Definition at line 824 of file IdealGasPhase.h.
References IdealGasPhase::_updateThermo(), and IdealGasPhase::m_s0_R.
Referenced by IdealGasPhase::entropy_mole(), IdealGasPhase::getEntropy_R(), IdealGasPhase::getEntropy_R_ref(), and IdealGasPhase::getPartialMolarEntropies().
const vector_fp& cp_R_ref () const inline
Returns a reference to the dimensionless reference state Heat Capacity vector.
This function is part of the layer that checks/recalculates the reference state thermo functions.
Definition at line 834 of file IdealGasPhase.h.
References IdealGasPhase::_updateThermo(), and IdealGasPhase::m_cp0_R.
Referenced by IdealGasPhase::cp_mole(), AxiStagnFlow::eval(), FreeFlame::eval(), IdealGasPhase::getCp_R(), IdealGasPhase::getCp_R_ref(), and IdealGasPhase::getPartialMolarCp().
void initThermo () virtual
Initialize the ThermoPhase object after all species have been set up.
Initialize.
This method performs any initialization required after all species have been added. For example, it is used to resize internal work arrays that must have an entry for each species. This method is called from ThermoPhase::initThermoXML(), which is called from importPhase(), just prior to returning from the function, importPhase().
See Also
importCTML.cpp
Reimplemented from ThermoPhase.
Definition at line 466 of file IdealGasPhase.cpp.
References IdealGasPhase::m_cp0_R, IdealGasPhase::m_expg0_RT, IdealGasPhase::m_g0_RT, IdealGasPhase::m_h0_RT, Phase::m_kk, IdealGasPhase::m_mm, IdealGasPhase::m_p0, IdealGasPhase::m_pe, IdealGasPhase::m_pp, IdealGasPhase::m_s0_R, ThermoPhase::m_spthermo, IdealGasPhase::m_tmax, IdealGasPhase::m_tmin, SpeciesThermo::maxTemp(), SpeciesThermo::minTemp(), Phase::nElements(), and ThermoPhase::refPressure().
void setToEquilState (const doublereal * lambda_RT) virtual
This method is used by the ChemEquil equilibrium solver.
It sets the state such that the chemical potentials satisfy
\[ \frac{\mu_k}{\hat R T} = \sum_m A_{k,m} \left(\frac{\lambda_m} {\hat R T}\right) \]
where \(\lambda_m \) is the element potential of element m. The temperature is unchanged. Any phase (ideal or not) that implements this method can be equilibrated by ChemEquil.
Parameters
lambda_RT Input vector of dimensionless element potentials The length is equal to nElements().
Reimplemented from ThermoPhase.
Definition at line 494 of file IdealGasPhase.cpp.
References IdealGasPhase::gibbs_RT_ref(), Phase::m_kk, IdealGasPhase::m_p0, IdealGasPhase::m_pp, and ThermoPhase::setState_PX().
void _updateThermo () const private
Update the species reference state thermodynamic functions.
This method is called each time a thermodynamic property is requested, to check whether the internal species properties within the object need to be updated.
The polynomials for the standard state functions are only reevaluated if the temperature has changed.
Currently, this updates the species thermo polynomial values for the current value of the temperature. A check is made to see if the temperature has changed since the last evaluation. This object does not contain any persistent data that depends on the concentration, that needs to be updated. The state object modifies its concentration dependent information at the time the setMoleFractions() (or equivalent) call is made.
Definition at line 537 of file IdealGasPhase.cpp.
References Cantera::GasConstant, IdealGasPhase::m_cp0_R, IdealGasPhase::m_g0_RT, IdealGasPhase::m_h0_RT, Phase::m_kk, IdealGasPhase::m_logc0, IdealGasPhase::m_p0, IdealGasPhase::m_s0_R, ThermoPhase::m_spthermo, IdealGasPhase::m_tlast, Phase::temperature(), and SpeciesThermo::update().
Referenced by IdealGasPhase::cp_R_ref(), IdealGasPhase::enthalpy_RT_ref(), IdealGasPhase::entropy_R_ref(), IdealGasPhase::expGibbs_RT_ref(), IdealGasPhase::gibbs_RT_ref(), and IdealGasPhase::logStandardConc().
virtual doublereal refPressure () const inline virtual inherited
Returns the reference pressure in Pa.
This function is a wrapper that calls the species thermo refPressure function.
Reimplemented in LatticeSolidPhase.
Definition at line 164 of file ThermoPhase.h.
References ThermoPhase::m_spthermo, and SpeciesThermo::refPressure().
Referenced by MixtureFugacityTP::_updateReferenceStateThermo(), RedlichKwongMFTP::getChemPotentials(), RedlichKwongMFTP::getPartialMolarEntropies(), MixtureFugacityTP::getStandardVolumes_ref(), ChemEquil::initialize(), IdealSolidSolnPhase::initLengths(), ConstDensityThermo::initThermo(), StoichSubstance::initThermo(), StoichSubstanceSSTP::initThermo(), PureFluidPhase::initThermo(), SingleSpeciesTP::initThermo(), IdealGasPhase::initThermo(), LatticePhase::initThermo(), and RedlichKwongMFTP::setToEquilState().
virtual doublereal minTemp (size_t k = npos) const inline virtual inherited
Minimum temperature for which the thermodynamic data for the species or phase are valid.
If no argument is supplied, the value returned will be the lowest temperature at which the data for all species are valid. Otherwise, the value will be only for species k. This function is a wrapper that calls the species thermo minTemp function.
Parameters
k index of the species. Default is -1, which will return the max of the min value over all species.
Reimplemented in LatticeSolidPhase.
Definition at line 181 of file ThermoPhase.h.
References ThermoPhase::m_spthermo, and SpeciesThermo::minTemp().
Referenced by MultiPhase::addPhase(), ChemEquil::equilibrate(), LiquidTransport::initLiquid(), SimpleTransport::initLiquid(), AqueousTransport::initLiquid(), ThermoPhase::setState_HPorUV(), ThermoPhase::setState_SPorSV(), TransportFactory::setupLiquidTransport(), and TransportFactory::setupMM().
doublereal Hf298SS (const int k) const inline inherited
Report the 298 K Heat of Formation of the standard state of one species (J kmol-1)
The 298K Heat of Formation is defined as the enthalpy change to create the standard state of the species from its constituent elements in their standard states at 298 K and 1 bar.
Parameters
k species index
Returns
Returns the current value of the Heat of Formation at 298K and 1 bar
Definition at line 221 of file ThermoPhase.h.
References ThermoPhase::err().
virtual void modifyOneHf298SS (const int k, const doublereal Hf298New) inline virtual inherited
Modify the value of the 298 K Heat of Formation of one species in the phase (J kmol-1)
The 298K heat of formation is defined as the enthalpy change to create the standard state of the species from its constituent elements in their standard states at 298 K and 1 bar.
Parameters
k Species k
Hf298New Specify the new value of the Heat of Formation at 298K and 1 bar
Definition at line 233 of file ThermoPhase.h.
References ThermoPhase::err().
virtual doublereal maxTemp (size_t k = npos) const inline virtual inherited
Maximum temperature for which the thermodynamic data for the species are valid.
If no argument is supplied, the value returned will be the highest temperature at which the data for all species are valid. Otherwise, the value will be only for species k. This function is a wrapper that calls the species thermo maxTemp function.
Parameters
k index of the species. Default is -1, which will return the min of the max value over all species.
Reimplemented in LatticeSolidPhase.
Definition at line 250 of file ThermoPhase.h.
References ThermoPhase::m_spthermo, and SpeciesThermo::maxTemp().
Referenced by MultiPhase::addPhase(), ChemEquil::equilibrate(), LiquidTransport::initLiquid(), SimpleTransport::initLiquid(), AqueousTransport::initLiquid(), ThermoPhase::setState_HPorUV(), ThermoPhase::setState_SPorSV(), TransportFactory::setupLiquidTransport(), and TransportFactory::setupMM().
bool chargeNeutralityNecessary () const inline inherited
Returns the chargeNeutralityNecessity boolean.
Some phases must have zero net charge in order for their thermodynamics functions to be valid. If this is so, then the value returned from this function is true. If this is not the case, then this is false. Now, ideal gases have this parameter set to false, while solution with molality-based activity coefficients have this parameter set to true.
Definition at line 261 of file ThermoPhase.h.
References ThermoPhase::m_chargeNeutralityNecessary.
virtual void updateDensity () inline virtual inherited
Deprecated:
Definition at line 366 of file ThermoPhase.h.
References Cantera::deprecatedMethod().
void setElectricPotential (doublereal v) inline inherited
Set the electric potential of this phase (V).
This is used by classes InterfaceKinetics and EdgeKinetics to compute the rates of charge-transfer reactions, and in computing the electrochemical potentials of the species.
Each phase may have its own electric potential.
Parameters
v Input value of the electric potential in Volts
Definition at line 390 of file ThermoPhase.h.
References ThermoPhase::m_phi.
Referenced by InterfaceKinetics::setElectricPotential(), vcs_VolPhase::setElectricPotential(), and vcs_VolPhase::setState_TP().
doublereal electricPotential () const inline inherited
Returns the electric potential of this phase (V).
Units are Volts (which are Joules/coulomb)
Definition at line 398 of file ThermoPhase.h.
References ThermoPhase::m_phi.
Referenced by InterfaceKinetics::_update_rates_phi(), PureFluidPhase::getElectrochemPotentials(), PseudoBinaryVPSSTP::getElectrochemPotentials(), MolarityIonicVPSSTP::getElectrochemPotentials(), GibbsExcessVPSSTP::getElectrochemPotentials(), RedlichKisterVPSSTP::getElectrochemPotentials(), MargulesVPSSTP::getElectrochemPotentials(), MixedSolventElectrolyte::getElectrochemPotentials(), ThermoPhase::getElectrochemPotentials(), MolalityVPSSTP::getElectrochemPotentials(), PhaseCombo_Interaction::getElectrochemPotentials(), PseudoBinaryVPSSTP::report(), MolarityIonicVPSSTP::report(), PureFluidPhase::report(), MolalityVPSSTP::report(), ThermoPhase::report(), PureFluidPhase::reportCSV(), MolalityVPSSTP::reportCSV(), ThermoPhase::reportCSV(), and vcs_VolPhase::setPtrThermoPhase().
int activityConvention () const virtual inherited
This method returns the convention used in specification of the activities, of which there are currently two, molar- and molality-based conventions.
Currently, there are two activity conventions:
Molar-based activities Unit activity of species at either a hypothetical pure solution of the species or at a hypothetical pure ideal solution at infinite dilution cAC_CONVENTION_MOLAR 0
default
Molality-based activities (unit activity of solutes at a hypothetical 1 molal solution referenced to infinite dilution at all pressures and temperatures). cAC_CONVENTION_MOLALITY 1
Reimplemented in MolalityVPSSTP.
Definition at line 143 of file ThermoPhase.cpp.
References Cantera::cAC_CONVENTION_MOLAR.
Referenced by vcs_MultiPhaseEquil::reportCSV(), and LiquidTransport::stefan_maxwell_solve().
int standardStateConvention () const virtual inherited
This method returns the convention used in specification of the standard state, of which there are currently two, temperature based, and variable pressure based.
Currently, there are two standard state conventions:
Temperature-based activities cSS_CONVENTION_TEMPERATURE 0
default
Variable Pressure and Temperature -based activities cSS_CONVENTION_VPSS 1
Thermodynamics is set via slave ThermoPhase objects with nothing being carried out at this ThermoPhase object level cSS_CONVENTION_SLAVE 2
Reimplemented in PureFluidPhase, LatticeSolidPhase, MixtureFugacityTP, and VPStandardStateTP.
Definition at line 148 of file ThermoPhase.cpp.
References ThermoPhase::m_ssConvention.
Referenced by Cantera::importPhase().
void getUnitsStandardConc (double * uA, int k = 0, int sizeUA = 6) const virtual inherited
Returns the units of the standard and generalized concentrations.
Note they have the same units, as their ratio is defined to be equal to the activity of the kth species in the solution, which is unitless.
This routine is used in print out applications where the units are needed. Usually, MKS units are assumed throughout the program and in the XML input files.
The base ThermoPhase class assigns the default quantities of (kmol/m3) for all species. Inherited classes are responsible for overriding the default values if necessary.
Parameters
uA Output vector containing the units uA[0] = kmol units - default = 1 uA[1] = m units - default = -nDim(), the number of spatial dimensions in the Phase class. uA[2] = kg units - default = 0; uA[3] = Pa(pressure) units - default = 0; uA[4] = Temperature units - default = 0; uA[5] = time units - default = 0
k species index. Defaults to 0.
sizeUA output int containing the size of the vector. Currently, this is equal to 6.
Reimplemented in HMWSoln, DebyeHuckel, IdealSolidSolnPhase, MolalityVPSSTP, IdealMolalSoln, MetalSHEelectrons, FixedChemPotSSTP, MineralEQ3, StoichSubstanceSSTP, RedlichKwongMFTP, GibbsExcessVPSSTP, IdealSolnGasVPSS, and StoichSubstance.
Definition at line 848 of file ThermoPhase.cpp.
References Phase::nDim().
void getActivities (doublereal * a) const virtual inherited
Get the array of non-dimensional activities at the current solution temperature, pressure, and solution concentration.
Note, for molality based formulations, this returns the molality based activities.
We resolve this function at this level by calling on the activityConcentration function. However, derived classes may want to override this default implementation.
Parameters
a Output vector of activities. Length: m_kk.
Reimplemented in HMWSoln, DebyeHuckel, MolalityVPSSTP, IdealMolalSoln, GibbsExcessVPSSTP, PureFluidPhase, and SingleSpeciesTP.
Definition at line 158 of file ThermoPhase.cpp.
References ThermoPhase::getActivityConcentrations(), Phase::nSpecies(), and ThermoPhase::standardConcentration().
Referenced by vcs_MultiPhaseEquil::reportCSV(), and ThermoPhase::reportCSV().
void getLnActivityCoefficients (doublereal * lnac) const virtual inherited
Get the array of non-dimensional molar-based ln activity coefficients at the current solution temperature, pressure, and solution concentration.
Parameters
lnac Output vector of ln activity coefficients. Length: m_kk.
Reimplemented in MargulesVPSSTP, RedlichKisterVPSSTP, and MolarityIonicVPSSTP.
Definition at line 166 of file ThermoPhase.cpp.
References ThermoPhase::getActivityCoefficients(), and Phase::m_kk.
Referenced by GibbsExcessVPSSTP::getActivityCoefficients(), IonsFromNeutralVPSSTP::getChemPotentials(), and IonsFromNeutralVPSSTP::s_update_lnActCoeff().
virtual void getChemPotentials_RT (doublereal * mu) const inline virtual inherited
Get the array of non-dimensional species chemical potentials These are partial molar Gibbs free energies.
\(\mu_k / \hat R T \). Units: unitless
Parameters
mu Output vector of dimensionless chemical potentials. Length: m_kk.
Reimplemented in IdealSolidSolnPhase, RedlichKwongMFTP, SingleSpeciesTP, IdealSolnGasVPSS, StoichSubstance, MixtureFugacityTP, and VPStandardStateTP.
Definition at line 583 of file ThermoPhase.h.
References ThermoPhase::err().
void getElectrochemPotentials (doublereal * mu) const inline inherited
Get the species electrochemical potentials.
These are partial molar quantities. This method adds a term \(F z_k \phi_p \) to each chemical potential. The electrochemical potential of species k in a phase p, \(\zeta_k \), is related to the chemical potential via the following equation,
\[ \zeta_{k}(T,P) = \mu_{k}(T,P) + F z_k \phi_p \]
Parameters
mu Output vector of species electrochemical potentials. Length: m_kk. Units: J/kmol
Definition at line 616 of file ThermoPhase.h.
References Phase::charge(), ThermoPhase::electricPotential(), ThermoPhase::getChemPotentials(), and Phase::m_kk.
Referenced by InterfaceKinetics::getDeltaElectrochemPotentials().
virtual void getdPartialMolarVolumes_dT (doublereal * d_vbar_dT) const inline virtual inherited
Return an array of derivatives of partial molar volumes wrt temperature for the species in the mixture.
Units: m^3/kmol.
The derivative is at constant pressure
Parameters
d_vbar_dT Output vector of derivatives of species partial molar volumes wrt T. Length = m_kk. units are m^3/kmol/K.
Definition at line 683 of file ThermoPhase.h.
References ThermoPhase::err().
virtual void getdPartialMolarVolumes_dP (doublereal * d_vbar_dP) const inline virtual inherited
Return an array of derivatives of partial molar volumes wrt pressure for the species in the mixture.
Units: m^3/kmol.
The derivative is at constant temperature
Parameters
d_vbar_dP Output vector of derivatives of species partial molar volumes wrt P. Length = m_kk. units are m^3/kmol/Pa.
Definition at line 695 of file ThermoPhase.h.
References ThermoPhase::err().
virtual void getdStandardVolumes_dT (doublereal * d_vol_dT) const inline virtual inherited
Get the derivative of the molar volumes of the species standard states wrt temperature at the current T and P of the solution.
The derivative is at constant pressure units = m^3 / kmol / K
Parameters
d_vol_dT Output vector containing derivatives of standard state volumes wrt T Length: m_kk.
Definition at line 800 of file ThermoPhase.h.
References ThermoPhase::err().
virtual void getdStandardVolumes_dP (doublereal * d_vol_dP) const inline virtual inherited
Get the derivative molar volumes of the species standard states wrt pressure at the current T and P of the solution.
The derivative is at constant temperature. units = m^3 / kmol / Pa
Parameters
d_vol_dP Output vector containing the derivative of standard state volumes wrt P. Length: m_kk.
Definition at line 813 of file ThermoPhase.h.
References ThermoPhase::err().
void setReferenceComposition (const doublereal *const x) virtual inherited
Sets the reference composition.
Parameters
x Mole fraction vector to set the reference composition to. If this is zero, then the reference mole fraction is set to the current mole fraction vector.
Definition at line 992 of file ThermoPhase.cpp.
References DATA_PTR, Phase::getMoleFractions(), Phase::m_kk, and ThermoPhase::xMol_Ref.
Referenced by ThermoPhase::initThermoXML().
void getReferenceComposition (doublereal *const x) const virtual inherited
Gets the reference composition.
The reference mole fraction is a safe mole fraction.
Parameters
x Mole fraction vector containing the reference composition.
Definition at line 1013 of file ThermoPhase.cpp.
References Phase::m_kk, and ThermoPhase::xMol_Ref.
doublereal enthalpy_mass () const inline inherited
Specific enthalpy.
Units: J/kg.
Definition at line 937 of file ThermoPhase.h.
References ThermoPhase::enthalpy_mole(), and Phase::meanMolecularWeight().
Referenced by ConstPressureReactor::initialize(), Reactor::initialize(), PseudoBinaryVPSSTP::report(), MolarityIonicVPSSTP::report(), PureFluidPhase::report(), MolalityVPSSTP::report(), ThermoPhase::report(), PureFluidPhase::reportCSV(), MolalityVPSSTP::reportCSV(), ThermoPhase::reportCSV(), SingleSpeciesTP::setState_HP(), ThermoPhase::setState_HPorUV(), ThermoPhase::setState_SPorSV(), ReactorBase::setThermoMgr(), ConstPressureReactor::updateState(), and Reactor::updateState().
doublereal intEnergy_mass () const inline inherited
Specific internal energy.
Units: J/kg.
Definition at line 944 of file ThermoPhase.h.
References ThermoPhase::intEnergy_mole(), and Phase::meanMolecularWeight().
Referenced by ConstPressureReactor::initialize(), Reactor::initialize(), PseudoBinaryVPSSTP::report(), MolarityIonicVPSSTP::report(), PureFluidPhase::report(), MolalityVPSSTP::report(), ThermoPhase::report(), PureFluidPhase::reportCSV(), MolalityVPSSTP::reportCSV(), ThermoPhase::reportCSV(), ThermoPhase::setState_HPorUV(), SingleSpeciesTP::setState_UV(), ReactorBase::setThermoMgr(), ConstPressureReactor::updateState(), and Reactor::updateState().
doublereal entropy_mass () const inline inherited
Specific entropy.
Units: J/kg/K.
Definition at line 951 of file ThermoPhase.h.
References ThermoPhase::entropy_mole(), and Phase::meanMolecularWeight().
Referenced by PseudoBinaryVPSSTP::report(), MolarityIonicVPSSTP::report(), PureFluidPhase::report(), MolalityVPSSTP::report(), ThermoPhase::report(), PureFluidPhase::reportCSV(), MolalityVPSSTP::reportCSV(), ThermoPhase::reportCSV(), SingleSpeciesTP::setState_SP(), ThermoPhase::setState_SPorSV(), and SingleSpeciesTP::setState_SV().
doublereal gibbs_mass () const inline inherited
Specific Gibbs function.
Units: J/kg.
Definition at line 958 of file ThermoPhase.h.
References ThermoPhase::gibbs_mole(), and Phase::meanMolecularWeight().
Referenced by PseudoBinaryVPSSTP::report(), MolarityIonicVPSSTP::report(), PureFluidPhase::report(), MolalityVPSSTP::report(), ThermoPhase::report(), PureFluidPhase::reportCSV(), MolalityVPSSTP::reportCSV(), and ThermoPhase::reportCSV().
doublereal cp_mass () const inline inherited
Specific heat at constant pressure.
Units: J/kg/K.
Definition at line 965 of file ThermoPhase.h.
References ThermoPhase::cp_mole(), and Phase::meanMolecularWeight().
Referenced by PseudoBinaryVPSSTP::report(), MolarityIonicVPSSTP::report(), PureFluidPhase::report(), MolalityVPSSTP::report(), ThermoPhase::report(), PureFluidPhase::reportCSV(), MolalityVPSSTP::reportCSV(), ThermoPhase::reportCSV(), SingleSpeciesTP::setState_HP(), ThermoPhase::setState_HPorUV(), SingleSpeciesTP::setState_SP(), ThermoPhase::setState_SPorSV(), and StFlow::updateThermo().
doublereal cv_mass () const inline inherited
Specific heat at constant volume.
Units: J/kg/K.
Definition at line 972 of file ThermoPhase.h.
References ThermoPhase::cv_mole(), and Phase::meanMolecularWeight().
Referenced by PseudoBinaryVPSSTP::report(), MolarityIonicVPSSTP::report(), PureFluidPhase::report(), MolalityVPSSTP::report(), ThermoPhase::report(), PureFluidPhase::reportCSV(), MolalityVPSSTP::reportCSV(), ThermoPhase::reportCSV(), ThermoPhase::setState_HPorUV(), ThermoPhase::setState_SPorSV(), SingleSpeciesTP::setState_SV(), and SingleSpeciesTP::setState_UV().
doublereal _RT () const inline inherited
Return the Gas Constant multiplied by the current temperature.
The units are Joules kmol-1
Definition at line 981 of file ThermoPhase.h.
References Cantera::GasConstant, and Phase::temperature().
Referenced by MixtureFugacityTP::corr0(), RedlichKwongMFTP::enthalpy_mole(), VPStandardStateTP::getChemPotentials_RT(), MixtureFugacityTP::getChemPotentials_RT(), IdealSolnGasVPSS::getChemPotentials_RT(), RedlichKwongMFTP::getChemPotentials_RT(), PureFluidPhase::getEnthalpy_RT(), FixedChemPotSSTP::getEnthalpy_RT(), FixedChemPotSSTP::getEnthalpy_RT_ref(), WaterSSTP::getGibbs_ref(), MixtureFugacityTP::getGibbs_ref(), IdealGasPhase::getGibbs_ref(), PureFluidPhase::getGibbs_RT(), FixedChemPotSSTP::getGibbs_RT(), IdealSolidSolnPhase::getGibbs_RT(), LatticePhase::getGibbs_RT(), FixedChemPotSSTP::getGibbs_RT_ref(), MixtureFugacityTP::getIntEnergy_RT(), IdealMolalSoln::getPartialMolarEnthalpies(), ConstDensityThermo::getPureGibbs(), MixtureFugacityTP::getPureGibbs(), IdealGasPhase::getPureGibbs(), IdealSolidSolnPhase::getPureGibbs(), VPStandardStateTP::getStandardChemPotentials(), MixtureFugacityTP::getStandardChemPotentials(), IdealGasPhase::getStandardChemPotentials(), LatticePhase::getStandardChemPotentials(), MixtureFugacityTP::getStandardVolumes(), MixtureFugacityTP::getStandardVolumes_ref(), IdealGasPhase::getStandardVolumes_ref(), and MixtureFugacityTP::z().
void setState_TPX (doublereal t, doublereal p, const doublereal * x) virtual inherited
Set the temperature (K), pressure (Pa), and mole fractions.
Note, the mole fractions are set first before the pressure is set. Setting the pressure may involve the solution of a nonlinear equation.
Parameters
t Temperature (K)
p Pressure (Pa)
x Vector of mole fractions. Length is equal to m_kk.
Reimplemented in SingleSpeciesTP, and MixtureFugacityTP.
Definition at line 174 of file ThermoPhase.cpp.
References Phase::setMoleFractions(), ThermoPhase::setPressure(), and Phase::setTemperature().
Referenced by MultiTransport::getMassFluxes(), DustyGasTransport::getMolarFluxes(), MultiPhase::setMoles(), and MultiPhase::setPhaseMoleFractions().
void setState_TPX (doublereal t, doublereal p, compositionMap & x) inherited
Set the temperature (K), pressure (Pa), and mole fractions.
Note, the mole fractions are set first before the pressure is set. Setting the pressure may involve the solution of a nonlinear equation.
Parameters
t Temperature (K)
p Pressure (Pa)
x Composition map of mole fractions. Species not in the composition map are assumed to have zero mole fraction
Definition at line 181 of file ThermoPhase.cpp.
References Phase::setMoleFractionsByName(), ThermoPhase::setPressure(), and Phase::setTemperature().
void setState_TPX (doublereal t, doublereal p, const std::string & x) inherited
Set the temperature (K), pressure (Pa), and mole fractions.
Note, the mole fractions are set first before the pressure is set. Setting the pressure may involve the solution of a nonlinear equation.
Parameters
t Temperature (K)
p Pressure (Pa)
x String containing a composition map of the mole fractions. Species not in the composition map are assumed to have zero mole fraction
Definition at line 188 of file ThermoPhase.cpp.
References ThermoPhase::err(), Phase::nSpecies(), Cantera::parseCompString(), CanteraError::save(), Phase::setMoleFractionsByName(), ThermoPhase::setPressure(), Phase::setTemperature(), and Phase::speciesName().
void setState_TPY (doublereal t, doublereal p, const doublereal * y) inherited
Set the internally stored temperature (K), pressure (Pa), and mass fractions of the phase.
Note, the mass fractions are set first before the pressure is set. Setting the pressure may involve the solution of a nonlinear equation.
Parameters
t Temperature (K)
p Pressure (Pa)
y Vector of mass fractions. Length is equal to m_kk.
Definition at line 206 of file ThermoPhase.cpp.
References Phase::setMassFractions(), ThermoPhase::setPressure(), and Phase::setTemperature().
void setState_TPY (doublereal t, doublereal p, compositionMap & y) inherited
Set the internally stored temperature (K), pressure (Pa), and mass fractions of the phase.
Note, the mass fractions are set first before the pressure is set. Setting the pressure may involve the solution of a nonlinear equation.
Parameters
t Temperature (K)
p Pressure (Pa)
y Composition map of mass fractions. Species not in the composition map are assumed to have zero mass fraction
Definition at line 214 of file ThermoPhase.cpp.
References Phase::setMassFractionsByName(), ThermoPhase::setPressure(), and Phase::setTemperature().
void setState_TPY (doublereal t, doublereal p, const std::string & y) inherited
Set the internally stored temperature (K), pressure (Pa), and mass fractions of the phase.
Note, the mass fractions are set first before the pressure is set. Setting the pressure may involve the solution of a nonlinear equation.
Parameters
t Temperature (K)
p Pressure (Pa)
y String containing a composition map of the mass fractions. Species not in the composition map are assumed to have zero mass fraction
Definition at line 222 of file ThermoPhase.cpp.
References ThermoPhase::err(), Phase::nSpecies(), Cantera::parseCompString(), CanteraError::save(), Phase::setMassFractionsByName(), ThermoPhase::setPressure(), Phase::setTemperature(), and Phase::speciesName().
void setState_TP (doublereal t, doublereal p) inherited
Set the temperature (K) and pressure (Pa)
Setting the pressure may involve the solution of a nonlinear equation.
Parameters
t Temperature (K)
p Pressure (Pa)
Definition at line 242 of file ThermoPhase.cpp.
References ThermoPhase::setPressure(), and Phase::setTemperature().
Referenced by StoichSubstance::initThermo(), ImplicitSurfChem::setCommonState_TP(), SingleSpeciesTP::setState_HP(), ThermoPhase::setState_HPorUV(), SingleSpeciesTP::setState_SP(), ThermoPhase::setState_SPorSV(), vcs_VolPhase::setState_TP(), PDSS_IonsFromNeutral::setState_TP(), IonsFromNeutralVPSSTP::setState_TP(), and FlowReactor::updateState().
void setState_PX (doublereal p, doublereal * x) inherited
Set the pressure (Pa) and mole fractions.
Note, the mole fractions are set first before the pressure is set. Setting the pressure may involve the solution of a nonlinear equation.
Parameters
p Pressure (Pa)
x Vector of mole fractions. Length is equal to m_kk.
Definition at line 249 of file ThermoPhase.cpp.
References Phase::setMoleFractions(), and ThermoPhase::setPressure().
Referenced by vcs_VolPhase::_updateMoleFractionDependencies(), IdealSolnGasVPSS::setToEquilState(), RedlichKwongMFTP::setToEquilState(), IdealGasPhase::setToEquilState(), and IdealSolidSolnPhase::setToEquilState().
void setState_PY (doublereal p, doublereal * y) inherited
Set the internally stored pressure (Pa) and mass fractions.
Note, the temperature is held constant during this operation. Note, the mass fractions are set first before the pressure is set. Setting the pressure may involve the solution of a nonlinear equation.
Parameters
p Pressure (Pa)
y Vector of mass fractions. Length is equal to m_kk.
Definition at line 256 of file ThermoPhase.cpp.
References Phase::setMassFractions(), and ThermoPhase::setPressure().
void setState_HP (doublereal h, doublereal p, doublereal tol = 1.e-4) virtual inherited
Set the internally stored specific enthalpy (J/kg) and pressure (Pa) of the phase.
Parameters
h Specific enthalpy (J/kg)
p Pressure (Pa)
tol Optional parameter setting the tolerance of the calculation. Defaults to 1.0E-4
Reimplemented in SingleSpeciesTP, and PureFluidPhase.
Definition at line 263 of file ThermoPhase.cpp.
References ThermoPhase::setState_HPorUV().
Referenced by FlowReactor::updateState(), and ConstPressureReactor::updateState().
void setState_UV (doublereal u, doublereal v, doublereal tol = 1.e-4) virtual inherited
Set the specific internal energy (J/kg) and specific volume (m^3/kg).
This function fixes the internal state of the phase so that the specific internal energy and specific volume have the value of the input parameters.
Parameters
u specific internal energy (J/kg)
v specific volume (m^3/kg).
tol Optional parameter setting the tolerance of the calculation. Defaults to 1.0E-4
Reimplemented in SingleSpeciesTP, and PureFluidPhase.
Definition at line 270 of file ThermoPhase.cpp.
References ThermoPhase::setState_HPorUV().
Referenced by Reactor::updateState().
void setState_SP (doublereal s, doublereal p, doublereal tol = 1.e-4) virtual inherited
Set the specific entropy (J/kg/K) and pressure (Pa).
This function fixes the internal state of the phase so that the specific entropy and the pressure have the value of the input parameters.
Parameters
s specific entropy (J/kg/K)
p specific pressure (Pa).
tol Optional parameter setting the tolerance of the calculation. Defaults to 1.0E-4
Reimplemented in SingleSpeciesTP, and PureFluidPhase.
Definition at line 546 of file ThermoPhase.cpp.
References ThermoPhase::setState_SPorSV().
void setState_SV (doublereal s, doublereal v, doublereal tol = 1.e-4) virtual inherited
Set the specific entropy (J/kg/K) and specific volume (m^3/kg).
This function fixes the internal state of the phase so that the specific entropy and specific volume have the value of the input parameters.
Parameters
s specific entropy (J/kg/K)
v specific volume (m^3/kg).
tol Optional parameter setting the tolerance of the calculation. Defaults to 1.0E-4
Reimplemented in SingleSpeciesTP, and PureFluidPhase.
Definition at line 553 of file ThermoPhase.cpp.
References ThermoPhase::setState_SPorSV().
void setElementPotentials (const vector_fp & lambda) inherited
Stores the element potentials in the ThermoPhase object.
Called by function 'equilibrate' in ChemEquil.h to transfer the element potentials to this object after every successful equilibration routine. The element potentials are stored in their dimensionless forms, calculated by dividing by RT.
Parameters
lambda Input vector containing the element potentials. Length = nElements. Units are Joules/kmol.
Definition at line 1106 of file ThermoPhase.cpp.
References Cantera::GasConstant, ThermoPhase::m_hasElementPotentials, ThermoPhase::m_lambdaRRT, Phase::nElements(), and Phase::temperature().
Referenced by Cantera::equilibrate(), ChemEquil::equilibrate(), and Cantera::vcs_equilibrate().
bool getElementPotentials (doublereal * lambda) const inherited
Returns the element potentials stored in the ThermoPhase object.
Returns the stored element potentials. The element potentials are retrieved from their stored dimensionless forms by multiplying by RT.
Parameters
lambda Output vector containing the element potentials. Length = nElements. Units are Joules/kmol.
Returns
bool indicating whether there are any valid stored element potentials. The calling routine should check this bool. In the case that there aren't any, lambda is not touched.
Definition at line 1129 of file ThermoPhase.cpp.
References Cantera::GasConstant, ThermoPhase::m_hasElementPotentials, ThermoPhase::m_lambdaRRT, Phase::nElements(), and Phase::temperature().
Referenced by ChemEquil::equilibrate().
virtual doublereal critTemperature () const inline virtual inherited
Critical temperature (K).
Reimplemented in HMWSoln, IdealMolalSoln, RedlichKwongMFTP, PureFluidPhase, and WaterSSTP.
Definition at line 1236 of file ThermoPhase.h.
References ThermoPhase::err().
Referenced by MixtureFugacityTP::calculatePsat(), MixtureFugacityTP::densityCalc(), MixtureFugacityTP::phaseState(), and MixtureFugacityTP::psatEst().
virtual doublereal critPressure () const inline virtual inherited
Critical pressure (Pa).
Reimplemented in HMWSoln, IdealMolalSoln, RedlichKwongMFTP, PureFluidPhase, and WaterSSTP.
Definition at line 1242 of file ThermoPhase.h.
References ThermoPhase::err().
Referenced by MixtureFugacityTP::calculatePsat(), and MixtureFugacityTP::psatEst().
virtual doublereal critDensity () const inline virtual inherited
Critical density (kg/m3).
Reimplemented in HMWSoln, IdealMolalSoln, RedlichKwongMFTP, PureFluidPhase, and WaterSSTP.
Definition at line 1248 of file ThermoPhase.h.
References ThermoPhase::err().
Referenced by MixtureFugacityTP::densityCalc(), and MixtureFugacityTP::phaseState().
virtual doublereal satTemperature (doublereal p) const inline virtual inherited
Return the saturation temperature given the pressure.
Parameters
p Pressure (Pa)
Reimplemented in HMWSoln, DebyeHuckel, SingleSpeciesTP, and PureFluidPhase.
Definition at line 1267 of file ThermoPhase.h.
References ThermoPhase::err().
virtual doublereal satPressure (doublereal t) const inline virtual inherited
Return the saturation pressure given the temperature.
Parameters
t Temperature (Kelvin)
Reimplemented in HMWSoln, DebyeHuckel, SingleSpeciesTP, PureFluidPhase, and WaterSSTP.
Definition at line 1276 of file ThermoPhase.h.
References ThermoPhase::err().
virtual doublereal vaporFraction () const inline virtual inherited
Return the fraction of vapor at the current conditions.
Reimplemented in HMWSoln, DebyeHuckel, SingleSpeciesTP, PureFluidPhase, and WaterSSTP.
Definition at line 1282 of file ThermoPhase.h.
References ThermoPhase::err().
virtual void setState_Tsat (doublereal t, doublereal x) inline virtual inherited
Set the state to a saturated system at a particular temperature.
Parameters
t Temperature (kelvin)
x Fraction of vapor
Reimplemented in HMWSoln, DebyeHuckel, SingleSpeciesTP, and PureFluidPhase.
Definition at line 1292 of file ThermoPhase.h.
References ThermoPhase::err().
virtual void setState_Psat (doublereal p, doublereal x) inline virtual inherited
Set the state to a saturated system at a particular pressure.
Parameters
p Pressure (Pa)
x Fraction of vapor
Reimplemented in HMWSoln, DebyeHuckel, SingleSpeciesTP, and PureFluidPhase.
Definition at line 1301 of file ThermoPhase.h.
References ThermoPhase::err().
void saveSpeciesData (const size_t k, const XML_Node *const data) inherited
Store a reference pointer to the XML tree containing the species data for this phase.
The following methods are used in the process of constructing the phase and setting its parameters from a specification in an input file. They are not normally used in application programs. To see how they are used, see files importCTML.cpp and ThermoFactory.cpp.
This is used to access data needed to construct transport manager later.
Parameters
k Species index
data Pointer to the XML_Node data containing information about the species in the phase.
Definition at line 1050 of file ThermoPhase.cpp.
References ThermoPhase::m_speciesData.
Referenced by FixedChemPotSSTP::FixedChemPotSSTP(), and Cantera::importPhase().
const std::vector< const XML_Node * > & speciesData () const inherited
Return a pointer to the vector of XML nodes containing the species data for this phase.
Definition at line 1060 of file ThermoPhase.cpp.
References Phase::m_kk, and ThermoPhase::m_speciesData.
Referenced by MineralEQ3::initThermoXML(), DebyeHuckel::initThermoXML(), TransportFactory::initTransport(), LatticeSolidPhase::installSlavePhases(), and TransportFactory::setupLiquidTransport().
void setSpeciesThermo (SpeciesThermo * spthermo) inherited
Install a species thermodynamic property manager.
The species thermodynamic property manager computes properties of the pure species for use in constructing solution properties. It is meant for internal use, and some classes derived from ThermoPhase may not use any species thermodynamic property manager. This method is called by function importPhase() in importCTML.cpp.
Parameters
spthermo input pointer to the species thermodynamic property manager.
Definition at line 886 of file ThermoPhase.cpp.
References ThermoPhase::m_spthermo.
Referenced by FixedChemPotSSTP::FixedChemPotSSTP(), Cantera::importPhase(), LatticeSolidPhase::installSlavePhases(), and VPSSMgrFactory::newVPSSMgr().
SpeciesThermo & speciesThermo (int k = -1) virtual inherited
Return a changeable reference to the calculation manager for species reference-state thermodynamic properties.
Parameters
k Speices id. The default is -1, meaning return the default
Reimplemented in LatticeSolidPhase.
Definition at line 904 of file ThermoPhase.cpp.
References ThermoPhase::m_spthermo.
Referenced by PDSS_ConstVol::constructPDSSXML(), PDSS_SSVol::constructPDSSXML(), PDSS_ConstVol::initThermo(), PDSS_IdealGas::initThermo(), PDSS_IonsFromNeutral::initThermo(), PDSS_SSVol::initThermo(), VPSSMgrFactory::newVPSSMgr(), and PDSS::PDSS().
void initThermoFile (std::string inputFile, std::string id) virtual inherited
Initialization of a ThermoPhase object using an ctml file.
This routine is a precursor to initThermoXML(XML_Node*) routine, which does most of the work. Here we read extra information about the XML description of a phase. Regular information about elements and species and their reference state thermodynamic information have already been read at this point. For example, we do not need to call this function for ideal gas equations of state.
Parameters
inputFile XML file containing the description of the phase
id Optional parameter identifying the name of the phase. If none is given, the first XML phase element encountered will be used.
Definition at line 928 of file ThermoPhase.cpp.
References XML_Node::build(), XML_Node::copy(), Cantera::findInputFile(), Cantera::findXMLPhase(), ThermoPhase::initThermoXML(), and Phase::xml().
void initThermoXML (XML_Node & phaseNode, std::string id) virtual inherited
Import and initialize a ThermoPhase object using an XML tree.
Here we read extra information about the XML description of a phase. Regular information about elements and species and their reference state thermodynamic information have already been read at this point. For example, we do not need to call this function for ideal gas equations of state. This function is called from importPhase() after the elements and the species are initialized with default ideal solution level data.
The default implementation in ThermoPhase calls the virtual function initThermo() and then sets the "state" of the phase by looking for an XML element named "state", and then interpreting its contents by calling the virtual function setStateFromXML().
Parameters
phaseNode This object must be the phase node of a complete XML tree description of the phase, including all of the species data. In other words while "phase" must point to an XML phase object, it must have sibling nodes "speciesData" that describe the species in the phase.
id ID of the phase. If nonnull, a check is done to see if phaseNode is pointing to the phase with the correct id.
Reimplemented in HMWSoln, DebyeHuckel, IdealSolidSolnPhase, LatticePhase, IdealMolalSoln, MolalityVPSSTP, MixedSolventElectrolyte, MargulesVPSSTP, RedlichKisterVPSSTP, PhaseCombo_Interaction, MixtureFugacityTP, IonsFromNeutralVPSSTP, FixedChemPotSSTP, electrodeElectron, VPStandardStateTP, RedlichKwongMFTP, MineralEQ3, MetalSHEelectrons, WaterSSTP, StoichSubstanceSSTP, MolarityIonicVPSSTP, IdealSolnGasVPSS, and PseudoBinaryVPSSTP.
Definition at line 979 of file ThermoPhase.cpp.
References XML_Node::child(), XML_Node::hasChild(), ThermoPhase::setReferenceComposition(), and ThermoPhase::setStateFromXML().
Referenced by Cantera::importPhase(), ThermoPhase::initThermoFile(), StoichSubstanceSSTP::initThermoXML(), MetalSHEelectrons::initThermoXML(), VPStandardStateTP::initThermoXML(), electrodeElectron::initThermoXML(), FixedChemPotSSTP::initThermoXML(), MixtureFugacityTP::initThermoXML(), LatticePhase::initThermoXML(), and IdealSolidSolnPhase::initThermoXML().
void installSlavePhases (Cantera::XML_Node * phaseNode) virtual inherited
Add in species from Slave phases.
This hook is used for cSS_CONVENTION_SLAVE phases
Parameters
phaseNode XML Element for the phase
Reimplemented in LatticeSolidPhase.
Definition at line 1045 of file ThermoPhase.cpp.
Referenced by Cantera::importPhase().
virtual void setParameters (int n, doublereal *const c) inline virtual inherited
Set the equation of state parameters.
The number and meaning of these depends on the subclass.
Parameters
n number of parameters
c array of n coefficients
Reimplemented in HMWSoln, DebyeHuckel, LatticePhase, IdealMolalSoln, SingleSpeciesTP, FixedChemPotSSTP, electrodeElectron, MineralEQ3, MetalSHEelectrons, StoichSubstanceSSTP, StoichSubstance, ConstDensityThermo, and SurfPhase.
Definition at line 1451 of file ThermoPhase.h.
virtual void getParameters (int & n, doublereal *const c) const inline virtual inherited
Get the equation of state parameters in a vector.
The number and meaning of these depends on the subclass.
Parameters
n number of parameters
c array of n coefficients
Reimplemented in HMWSoln, DebyeHuckel, LatticePhase, IdealMolalSoln, SingleSpeciesTP, FixedChemPotSSTP, MineralEQ3, MetalSHEelectrons, StoichSubstanceSSTP, StoichSubstance, and ConstDensityThermo.
Definition at line 1462 of file ThermoPhase.h.
virtual void setParametersFromXML (const XML_Node & eosdata) inline virtual inherited
Set equation of state parameter values from XML entries.
This method is called by function importPhase() in file importCTML.cpp when processing a phase definition in an input file. It should be overloaded in subclasses to set any parameters that are specific to that particular phase model. Note, this method is called before the phase is initialized with elements and/or species.
Parameters
eosdata An XML_Node object corresponding to the "thermo" entry for this phase in the input file.
Reimplemented in HMWSoln, DebyeHuckel, LatticePhase, IdealMolalSoln, SingleSpeciesTP, LatticeSolidPhase, FixedChemPotSSTP, MineralEQ3, electrodeElectron, MetalSHEelectrons, PureFluidPhase, VPStandardStateTP, StoichSubstanceSSTP, WaterSSTP, RedlichKwongMFTP, ConstDensityThermo, StoichSubstance, SurfPhase, IdealSolnGasVPSS, MetalPhase, EdgePhase, and SemiconductorPhase.
Definition at line 1478 of file ThermoPhase.h.
Referenced by Cantera::importPhase(), and RedlichKwongMFTP::setParametersFromXML().
void setStateFromXML (const XML_Node & state) virtual inherited
Set the initial state of the phase to the conditions specified in the state XML element.
This method sets the temperature, pressure, and mole fraction vector to a set default value.
Parameters
state AN XML_Node object corresponding to the "state" entry for this phase in the input file.
Reimplemented in MolalityVPSSTP, MixtureFugacityTP, and SurfPhase.
Definition at line 1072 of file ThermoPhase.cpp.
References ctml::getChildValue(), ctml::getFloat(), XML_Node::hasChild(), Phase::setDensity(), Phase::setMassFractionsByName(), Phase::setMoleFractionsByName(), ThermoPhase::setPressure(), and Phase::setTemperature().
Referenced by ThermoPhase::initThermoXML(), and MolalityVPSSTP::setStateFromXML().
virtual void getdlnActCoeffds (const doublereal dTds, const doublereal *const dXds, doublereal * dlnActCoeffds) const inline virtual inherited
Get the change in activity coefficients wrt changes in state (temp, mole fraction, etc) along a line in parameter space or along a line in physical space.
Parameters
dTds Input of temperature change along the path
dXds Input vector of changes in mole fraction along the path. length = m_kk Along the path length it must be the case that the mole fractions sum to one.
dlnActCoeffds Output vector of the directional derivatives of the log Activity Coefficients along the path. length = m_kk units are 1/units(s). if s is a physical coordinate then the units are 1/m.
Reimplemented in MixedSolventElectrolyte, MargulesVPSSTP, RedlichKisterVPSSTP, PhaseCombo_Interaction, and IonsFromNeutralVPSSTP.
Definition at line 1511 of file ThermoPhase.h.
References ThermoPhase::err().
Referenced by IonsFromNeutralVPSSTP::getdlnActCoeffds(), and LiquidTransport::update_Grad_lnAC().
virtual void getdlnActCoeffdlnX_diag (doublereal * dlnActCoeffdlnX_diag) const inline virtual inherited
Get the array of ln mole fraction derivatives of the log activity coefficients - diagonal component only.
This function is a virtual method. For ideal mixtures (unity activity coefficients), this can return zero. Implementations should take the derivative of the logarithm of the activity coefficient with respect to the logarithm of the mole fraction variable that represents the standard state. This quantity is to be used in conjunction with derivatives of that mole fraction variable when the derivative of the chemical potential is taken.
units = dimensionless
Parameters
dlnActCoeffdlnX_diag Output vector of derivatives of the log Activity Coefficients wrt the mole fractions. length = m_kk
Reimplemented in MixedSolventElectrolyte, MargulesVPSSTP, RedlichKisterVPSSTP, PhaseCombo_Interaction, and IonsFromNeutralVPSSTP.
Definition at line 1533 of file ThermoPhase.h.
References ThermoPhase::err().
Referenced by IonsFromNeutralVPSSTP::s_update_dlnActCoeff_dlnX_diag().
virtual void getdlnActCoeffdlnN_diag (doublereal * dlnActCoeffdlnN_diag) const inline virtual inherited
Get the array of log species mole number derivatives of the log activity coefficients.
This function is a virtual method. For ideal mixtures (unity activity coefficients), this can return zero. Implementations should take the derivative of the logarithm of the activity coefficient with respect to the logarithm of the concentration-like variable (i.e. moles) that represents the standard state. This quantity is to be used in conjunction with derivatives of that species mole number variable when the derivative of the chemical potential is taken.
units = dimensionless
Parameters
dlnActCoeffdlnN_diag Output vector of derivatives of the log Activity Coefficients. length = m_kk
Reimplemented in MixedSolventElectrolyte, MargulesVPSSTP, RedlichKisterVPSSTP, PhaseCombo_Interaction, IonsFromNeutralVPSSTP, MixtureFugacityTP, and VPStandardStateTP.
Definition at line 1554 of file ThermoPhase.h.
References ThermoPhase::err().
void getdlnActCoeffdlnN (const size_t ld, doublereal *const dlnActCoeffdlnN) virtual inherited
Get the array of derivatives of the log activity coefficients with respect to the log of the species mole numbers.
Implementations should take the derivative of the logarithm of the activity coefficient with respect to a species log mole number (with all other species mole numbers held constant). The default treatment in the ThermoPhase object is to set this vector to zero.
units = 1 / kmol
dlnActCoeffdlnN[ ld * k + m] will contain the derivative of log act_coeff for the mth species with respect to the number of moles of the kth species.
\[ \frac{d \ln(\gamma_m) }{d \ln(n_k) }\Bigg|_{n_i} \]
Parameters
ld Number of rows in the matrix
dlnActCoeffdlnN Output vector of derivatives of the log Activity Coefficients. length = m_kk * m_kk
Reimplemented in MolalityVPSSTP, MixedSolventElectrolyte, MargulesVPSSTP, RedlichKisterVPSSTP, PhaseCombo_Interaction, IonsFromNeutralVPSSTP, and GibbsExcessVPSSTP.
Definition at line 1158 of file ThermoPhase.cpp.
References Phase::m_kk.
Referenced by vcs_VolPhase::_updateLnActCoeffJac().
std::string report (bool show_thermo = true) const virtual inherited
returns a summary of the state of the phase as a string
Parameters
show_thermo If true, extra information is printed out about the thermodynamic state of the system.
Reimplemented in MolalityVPSSTP, PureFluidPhase, MolarityIonicVPSSTP, and PseudoBinaryVPSSTP.
Definition at line 1243 of file ThermoPhase.cpp.
References ThermoPhase::cp_mass(), ThermoPhase::cp_mole(), ThermoPhase::cv_mass(), ThermoPhase::cv_mole(), Phase::density(), ThermoPhase::electricPotential(), ThermoPhase::enthalpy_mass(), ThermoPhase::enthalpy_mole(), ThermoPhase::entropy_mass(), ThermoPhase::entropy_mole(), ThermoPhase::err(), Cantera::GasConstant, ThermoPhase::getChemPotentials(), Phase::getMassFractions(), Phase::getMoleFractions(), ThermoPhase::gibbs_mass(), ThermoPhase::gibbs_mole(), ThermoPhase::intEnergy_mass(), ThermoPhase::intEnergy_mole(), Phase::meanMolecularWeight(), Phase::name(), Phase::nSpecies(), ThermoPhase::pressure(), CanteraError::save(), Cantera::SmallNumber, Phase::speciesName(), and Phase::temperature().
Referenced by Cantera::operator<<(), and Cantera::report().
void reportCSV (std::ofstream & csvFile) const virtual inherited
returns a summary of the state of the phase to a comma separated file
Parameters
csvFile ofstream file to print comma separated data for the phase
Reimplemented in MolalityVPSSTP, and PureFluidPhase.
Definition at line 1350 of file ThermoPhase.cpp.
References ThermoPhase::cp_mass(), ThermoPhase::cp_mole(), ThermoPhase::cv_mass(), ThermoPhase::cv_mole(), Phase::density(), ThermoPhase::electricPotential(), ThermoPhase::enthalpy_mass(), ThermoPhase::enthalpy_mole(), ThermoPhase::entropy_mass(), ThermoPhase::entropy_mole(), ThermoPhase::err(), ThermoPhase::getActivities(), ThermoPhase::getActivityCoefficients(), ThermoPhase::getChemPotentials(), Phase::getMassFractions(), Phase::getMoleFractions(), ThermoPhase::getPartialMolarCp(), ThermoPhase::getPartialMolarEnthalpies(), ThermoPhase::getPartialMolarEntropies(), ThermoPhase::getPartialMolarIntEnergies(), ThermoPhase::getPartialMolarVolumes(), ThermoPhase::gibbs_mass(), ThermoPhase::gibbs_mole(), ThermoPhase::intEnergy_mass(), ThermoPhase::intEnergy_mole(), Phase::meanMolecularWeight(), Phase::name(), Phase::nSpecies(), ThermoPhase::pressure(), CanteraError::save(), Cantera::SmallNumber, Phase::speciesName(), and Phase::temperature().
XML_Node & xml () inherited
Returns a reference to the XML_Node stored for the phase.
The XML_Node for the phase contains all of the input data used to set up the model for the phase, during its initialization.
Definition at line 125 of file Phase.cpp.
References Phase::m_xml.
Referenced by MolarityIonicVPSSTP::constructPhaseFile(), LatticePhase::constructPhaseFile(), RedlichKisterVPSSTP::constructPhaseFile(), MargulesVPSSTP::constructPhaseFile(), MixedSolventElectrolyte::constructPhaseFile(), WaterSSTP::constructPhaseFile(), PhaseCombo_Interaction::constructPhaseFile(), IonsFromNeutralVPSSTP::constructPhaseFile(), IdealMolalSoln::constructPhaseFile(), IdealSolidSolnPhase::constructPhaseFile(), DebyeHuckel::constructPhaseFile(), Cantera::importPhase(), SimpleTransport::initLiquid(), ThermoPhase::initThermoFile(), TransportFactory::newTransport(), and TransportFactory::setupLiquidTransport().
std::string id () const inherited
Return the string id for the phase.
Definition at line 130 of file Phase.cpp.
References Phase::m_id.
Referenced by Kinetics::assignShallowPointers(), Cantera::equilibrate(), Cantera::getEfficiencies(), Cantera::importPhase(), LatticeSolidPhase::installSlavePhases(), Kinetics::kineticsSpeciesIndex(), MultiPhase::phaseIndex(), MultiPhase::phaseName(), solveProb::print_header(), RedlichKwongMFTP::RedlichKwongMFTP(), Phase::setID(), LatticeSolidPhase::setParametersFromXML(), vcs_VolPhase::transferElementsFM(), and Cantera::vcs_equilibrate().
void setID (std::string id) inherited
Set the string id for the phase.
Parameters
id String id of the phase
Definition at line 135 of file Phase.cpp.
References Phase::id(), and Phase::m_id.
Referenced by FixedChemPotSSTP::FixedChemPotSSTP(), and Cantera::importPhase().
std::string name () const inherited
Return the name of the phase.
Definition at line 140 of file Phase.cpp.
References Phase::m_name.
Referenced by Cantera::operator<<(), PseudoBinaryVPSSTP::report(), MolarityIonicVPSSTP::report(), PureFluidPhase::report(), MolalityVPSSTP::report(), ThermoPhase::report(), PureFluidPhase::reportCSV(), vcs_MultiPhaseEquil::reportCSV(), MolalityVPSSTP::reportCSV(), and ThermoPhase::reportCSV().
void setName (std::string nm) inherited
Sets the string name for the phase.
Parameters
nm String name of the phase
Definition at line 145 of file Phase.cpp.
References Phase::m_name.
Referenced by FixedChemPotSSTP::FixedChemPotSSTP(), and Cantera::importPhase().
string elementName (size_t m) const inherited
Name of the element with index m.
Parameters
m Element index.
Definition at line 169 of file Phase.cpp.
References Phase::checkElementIndex(), and Phase::m_elementNames.
Referenced by MultiPhase::addPhase(), Cantera::checkRxnElementBalance(), Cantera::convertDGFormation(), PDSS_HKFT::convertDGFormation(), ChemEquil::equilibrate(), ChemEquil::equilResidual(), ChemEquil::estimateElementPotentials(), ChemEquil::estimateEP_Brinkley(), MolalityVPSSTP::findCLMIndex(), ChemEquil::initialize(), LatticeSolidPhase::installSlavePhases(), Cantera::installSpecies(), ChemEquil::setInitialMoles(), and vcs_VolPhase::transferElementsFM().
size_t elementIndex (std::string name) const inherited
Return the index of element named 'name'.
The index is an integer assigned to each element in the order it was added. Returns npos if the specified element is not found.
Parameters
name Name of the element
Definition at line 175 of file Phase.cpp.
References Phase::m_elementNames, Phase::m_mm, and Cantera::npos.
Referenced by Phase::addUniqueElementAfterFreeze(), MultiPhase::init(), WaterSSTP::initThermoXML(), LatticeSolidPhase::installSlavePhases(), Cantera::installSpecies(), Cantera::LookupGe(), and PDSS_HKFT::LookupGe().
const vector< string > & elementNames () const inherited
Return a read-only reference to the vector of element names.
Definition at line 185 of file Phase.cpp.
References Phase::m_elementNames.
Referenced by ChemEquil::equilibrate(), ChemEquil::estimateEP_Brinkley(), and IonsFromNeutralVPSSTP::initThermoXML().
doublereal atomicWeight (size_t m) const inherited
Atomic weight of element m.
Parameters
m Element index
Definition at line 190 of file Phase.cpp.
References Phase::m_atomicWeights.
Referenced by ChemEquil::initialize(), and WaterSSTP::initThermoXML().
doublereal entropyElement298 (size_t m) const inherited
Entropy of the element in its standard state at 298 K and 1 bar.
Parameters
m Element index
Definition at line 195 of file Phase.cpp.
References AssertThrowMsg, AssertTrace, ENTROPY298_UNKNOWN, Phase::m_entropy298, and Phase::m_mm.
Referenced by LatticeSolidPhase::installSlavePhases(), Cantera::LookupGe(), and PDSS_HKFT::LookupGe().
int atomicNumber (size_t m) const inherited
Atomic number of element m.
Parameters
m Element index
Definition at line 209 of file Phase.cpp.
References Phase::m_atomicNumbers.
Referenced by MultiPhase::addPhase(), and LatticeSolidPhase::installSlavePhases().
int elementType (size_t m) const inherited
Return the element constraint type Possible types include:
CT_ELEM_TYPE_TURNEDOFF -1 CT_ELEM_TYPE_ABSPOS 0 CT_ELEM_TYPE_ELECTRONCHARGE 1 CT_ELEM_TYPE_CHARGENEUTRALITY 2 CT_ELEM_TYPE_LATTICERATIO 3 CT_ELEM_TYPE_KINETICFROZEN 4 CT_ELEM_TYPE_SURFACECONSTRAINT 5 CT_ELEM_TYPE_OTHERCONSTRAINT 6
The default is CT_ELEM_TYPE_ABSPOS.
Parameters
m Element index
Returns
Returns the element type
Definition at line 214 of file Phase.cpp.
References Phase::m_elem_type.
Referenced by LatticeSolidPhase::installSlavePhases(), and vcs_VolPhase::transferElementsFM().
int changeElementType (int m, int elem_type) inherited
Change the element type of the mth constraint Reassigns an element type.
Parameters
m Element index
elem_type New elem type to be assigned
Returns
Returns the old element type
Definition at line 219 of file Phase.cpp.
References Phase::m_elem_type.
const vector_fp & atomicWeights () const inherited
Return a read-only reference to the vector of atomic weights.
Definition at line 204 of file Phase.cpp.
References Phase::m_atomicWeights.
Referenced by LatticeSolidPhase::installSlavePhases().
size_t nElements () const inherited
Number of elements.
Definition at line 150 of file Phase.cpp.
References Phase::m_mm.
Referenced by MultiPhase::addPhase(), Cantera::checkRxnElementBalance(), Cantera::convertDGFormation(), PDSS_HKFT::convertDGFormation(), ChemEquil::equilibrate(), MolalityVPSSTP::findCLMIndex(), FixedChemPotSSTP::FixedChemPotSSTP(), ThermoPhase::getElementPotentials(), ChemEquil::initialize(), IdealSolidSolnPhase::initLengths(), ConstDensityThermo::initThermo(), LatticeSolidPhase::initThermo(), IdealGasPhase::initThermo(), LatticePhase::initThermo(), IonsFromNeutralVPSSTP::initThermoXML(), LatticeSolidPhase::installSlavePhases(), Cantera::installSpecies(), ThermoPhase::setElementPotentials(), vcs_VolPhase::setPtrThermoPhase(), and vcs_VolPhase::transferElementsFM().
void checkElementIndex (size_t m) const inherited
Check that the specified element index is in range Throws an exception if m is greater than nElements()-1.
Definition at line 155 of file Phase.cpp.
References Phase::m_mm.
Referenced by Phase::elementName(), and Phase::nAtoms().
void checkElementArraySize (size_t mm) const inherited
Check that an array size is at least nElements() Throws an exception if mm is less than nElements().
Used before calls which take an array pointer.
Definition at line 162 of file Phase.cpp.
References Phase::m_mm.
doublereal nAtoms (size_t k, size_t m) const inherited
Number of atoms of element m in species k.
Parameters
k species index
m element index
Definition at line 226 of file Phase.cpp.
References Phase::checkElementIndex(), Phase::checkSpeciesIndex(), Phase::m_mm, and Phase::m_speciesComp.
Referenced by Cantera::checkRxnElementBalance(), Cantera::convertDGFormation(), PDSS_HKFT::convertDGFormation(), MolalityVPSSTP::findCLMIndex(), MultiPhase::init(), ChemEquil::initialize(), IonsFromNeutralVPSSTP::initThermoXML(), IdealSolidSolnPhase::setToEquilState(), and vcs_VolPhase::transferElementsFM().
void getAtoms (size_t k, double * atomArray) const inherited
Get a vector containing the atomic composition of species k.
Parameters
k species index
atomArray vector containing the atomic number in the species. Length: m_mm
Definition at line 233 of file Phase.cpp.
References Phase::m_mm, and Phase::m_speciesComp.
Referenced by LatticeSolidPhase::installSlavePhases().
size_t speciesIndex (std::string name) const inherited
Returns the index of a species named 'name' within the Phase object.
The first species in the phase will have an index 0, and the last one will have an index of nSpecies() - 1.
Parameters
name String name of the species. It may also be in the form phaseName:speciesName
Returns
The index of the species. If the name is not found, the value npos is returned.
Definition at line 240 of file Phase.cpp.
References Phase::m_id, Phase::m_kk, Phase::m_name, Phase::m_speciesNames, Cantera::npos, and Cantera::parseSpeciesName().
Referenced by PDSS_IonsFromNeutral::constructPDSSXML(), TransportFactory::getLiquidInteractionsTransportData(), TransportFactory::getLiquidSpeciesTransportData(), Cantera::getStick(), HMWSoln::HMWSoln(), Cantera::importSolution(), LiquidTranInteraction::init(), DebyeHuckel::initThermoXML(), FlowDevice::install(), Kinetics::kineticsSpeciesIndex(), MargulesVPSSTP::MargulesVPSSTP(), Phase::massFraction(), MixedSolventElectrolyte::MixedSolventElectrolyte(), Phase::moleFraction(), PhaseCombo_Interaction::PhaseCombo_Interaction(), PhaseCombo_Interaction::readXMLBinarySpecies(), RedlichKisterVPSSTP::readXMLBinarySpecies(), MargulesVPSSTP::readXMLBinarySpecies(), MixedSolventElectrolyte::readXMLBinarySpecies(), RedlichKwongMFTP::readXMLCrossFluid(), RedlichKwongMFTP::readXMLPureFluid(), RedlichKisterVPSSTP::RedlichKisterVPSSTP(), MolalityVPSSTP::report(), MolalityVPSSTP::reportCSV(), and Kinetics::speciesPhase().
string speciesName (size_t k) const inherited
Name of the species with index k.
Parameters
k index of the species
Definition at line 257 of file Phase.cpp.
References Phase::checkSpeciesIndex(), and Phase::m_speciesNames.
Referenced by StFlow::componentName(), ReactingSurf1D::componentName(), ChemEquil::estimateElementPotentials(), ChemEquil::estimateEP_Brinkley(), MolalityVPSSTP::findCLMIndex(), TransportFactory::fitProperties(), AqueousTransport::getLiquidTransportData(), Phase::getMoleFractionsByName(), Cantera::importSolution(), MultiPhase::init(), ChemEquil::initialize(), LiquidTransport::initLiquid(), SimpleTransport::initLiquid(), IdealMolalSoln::initThermoXML(), DebyeHuckel::initThermoXML(), FlowDevice::install(), LatticeSolidPhase::installSlavePhases(), Kinetics::kineticsSpeciesName(), solveProb::print_header(), HMWSoln::printCoeffs(), PhaseCombo_Interaction::readXMLBinarySpecies(), RedlichKisterVPSSTP::readXMLBinarySpecies(), MargulesVPSSTP::readXMLBinarySpecies(), MixedSolventElectrolyte::readXMLBinarySpecies(), PureFluidPhase::report(), MolalityVPSSTP::report(), ThermoPhase::report(), PureFluidPhase::reportCSV(), vcs_MultiPhaseEquil::reportCSV(), MolalityVPSSTP::reportCSV(), ThermoPhase::reportCSV(), HMWSoln::s_updatePitzer_d2lnMolalityActCoeff_dT2(), HMWSoln::s_updatePitzer_dlnMolalityActCoeff_dP(), HMWSoln::s_updatePitzer_dlnMolalityActCoeff_dT(), HMWSoln::s_updatePitzer_lnMolalityActCoeff(), StFlow::save(), SurfPhase::setCoveragesByName(), ChemEquil::setInitialMoles(), Phase::setMassFractionsByName(), MolalityVPSSTP::setMolalitiesByName(), Phase::setMoleFractionsByName(), ThermoPhase::setState_TPX(), ThermoPhase::setState_TPY(), Inlet1D::showSolution(), ReactingSurf1D::showSolution(), Phase::speciesSPName(), and ChemEquil::update().
std::string speciesSPName (int k) const inherited
Returns the expanded species name of a species, including the phase name This is guaranteed to be unique within a Cantera problem.
Parameters
k Species index within the phase
Returns
The "phaseName:speciesName" string
Definition at line 282 of file Phase.cpp.
References Phase::m_name, and Phase::speciesName().
const vector< string > & speciesNames () const inherited
Return a const reference to the vector of species names.
Definition at line 263 of file Phase.cpp.
References Phase::m_speciesNames.
Referenced by PDSS_ConstVol::constructPDSSFile(), PDSS_HKFT::constructPDSSFile(), PDSS_IonsFromNeutral::constructPDSSFile(), PDSS_SSVol::constructPDSSFile(), VPSSMgr_ConstVol::initThermoXML(), VPSSMgr_Water_ConstVol::initThermoXML(), VPSSMgr_Water_HKFT::initThermoXML(), IdealMolalSoln::initThermoXML(), LatticePhase::initThermoXML(), IdealSolidSolnPhase::initThermoXML(), DebyeHuckel::initThermoXML(), TransportFactory::setupLiquidTransport(), and TransportFactory::setupMM().
size_t nSpecies () const inline inherited
Returns the number of species in the phase.
Definition at line 252 of file Phase.h.
References Phase::m_kk.
Referenced by MultiPhase::addPhase(), InterfaceKinetics::applyButlerVolmerCorrection(), Kinetics::assignShallowPointers(), MultiPhase::calcElemAbundances(), Phase::chargeDensity(), MultiPhaseEquil::computeReactionSteps(), PDSS_IonsFromNeutral::constructPDSSXML(), RedlichKisterVPSSTP::cp_mole(), MargulesVPSSTP::cp_mole(), MixedSolventElectrolyte::cp_mole(), PhaseCombo_Interaction::cp_mole(), SolidTransport::electricalConductivity(), RedlichKisterVPSSTP::enthalpy_mole(), MargulesVPSSTP::enthalpy_mole(), MixedSolventElectrolyte::enthalpy_mole(), PhaseCombo_Interaction::enthalpy_mole(), RedlichKisterVPSSTP::entropy_mole(), MargulesVPSSTP::entropy_mole(), MixedSolventElectrolyte::entropy_mole(), PhaseCombo_Interaction::entropy_mole(), ChemEquil::equilibrate(), vcs_MultiPhaseEquil::equilibrate_TP(), ChemEquil::estimateElementPotentials(), ThermoPhase::getActivities(), MetalPhase::getActivityConcentrations(), MetalPhase::getChemPotentials(), IonsFromNeutralVPSSTP::getdlnActCoeffds(), MetalPhase::getEnthalpy_RT(), MetalPhase::getEntropy_R(), AqueousKinetics::getEquilibriumConstants(), InterfaceKinetics::getEquilibriumConstants(), MultiTransport::getMassFluxes(), LTI_Pairwise_Interaction::getMatrixTransProp(), LTI_StefanMaxwell_PPN::getMatrixTransProp(), SolidTransport::getMixDiffCoeffs(), LTI_MoleFracs::getMixTransProp(), LTI_MassFracs::getMixTransProp(), LTI_Log_MoleFracs::getMixTransProp(), LTI_Pairwise_Interaction::getMixTransProp(), LTI_StefanMaxwell_PPN::getMixTransProp(), LTI_MoleFracs_ExpT::getMixTransProp(), SolidTransport::getMobilities(), MultiTransport::getMolarFluxes(), Phase::getMoleFractionsByName(), MultiPhase::getMoles(), MetalPhase::getStandardChemPotentials(), ImplicitSurfChem::ImplicitSurfChem(), Cantera::importSolution(), LiquidTranInteraction::init(), MultiPhase::init(), AqueousKinetics::init(), GasKinetics::init(), InterfaceKinetics::init(), GasTransport::initGas(), ChemEquil::initialize(), DustyGasTransport::initialize(), PseudoBinaryVPSSTP::initLengths(), IdealSolnGasVPSS::initLengths(), MolarityIonicVPSSTP::initLengths(), GibbsExcessVPSSTP::initLengths(), VPStandardStateTP::initLengths(), IonsFromNeutralVPSSTP::initLengths(), MixtureFugacityTP::initLengths(), VPSSMgr::initLengths(), PhaseCombo_Interaction::initLengths(), RedlichKisterVPSSTP::initLengths(), MargulesVPSSTP::initLengths(), MixedSolventElectrolyte::initLengths(), MolalityVPSSTP::initLengths(), IdealMolalSoln::initLengths(), IdealSolidSolnPhase::initLengths(), DebyeHuckel::initLengths(), HMWSoln::initLengths(), LiquidTransport::initLiquid(), SimpleTransport::initLiquid(), AqueousTransport::initLiquid(), ConstDensityThermo::initThermo(), StoichSubstance::initThermo(), StoichSubstanceSSTP::initThermo(), LatticeSolidPhase::initThermo(), SingleSpeciesTP::initThermo(), LatticePhase::initThermo(), FlowDevice::install(), rxninfo::installReaction(), LatticeSolidPhase::installSlavePhases(), Kinetics::nTotalSpecies(), solveProb::print_header(), PseudoBinaryVPSSTP::report(), MolarityIonicVPSSTP::report(), PureFluidPhase::report(), MolalityVPSSTP::report(), ThermoPhase::report(), PureFluidPhase::reportCSV(), vcs_MultiPhaseEquil::reportCSV(), MolalityVPSSTP::reportCSV(), ThermoPhase::reportCSV(), Phase::restoreState(), IonsFromNeutralVPSSTP::s_update_dlnActCoeff_dlnN(), Phase::saveState(), Kinetics::selectPhase(), ImplicitSurfChem::setConcSpecies(), SurfPhase::setCoveragesByName(), Phase::setMassFractionsByName(), MolalityVPSSTP::setMolalitiesByName(), Phase::setMoleFractionsByName(), MultiPhase::setMoles(), SolidTransport::setParameters(), MultiPhase::setPhaseMoleFractions(), vcs_VolPhase::setPtrThermoPhase(), ThermoPhase::setState_TPX(), ThermoPhase::setState_TPY(), Transport::setThermo(), ReactorBase::setThermoMgr(), TransportFactory::setupLiquidTransport(), TransportFactory::setupMM(), Inlet1D::showSolution(), solveSP::solveSP(), StFlow::StFlow(), vcs_VolPhase::transferElementsFM(), AqueousKinetics::updateKc(), InterfaceKinetics::updateKc(), ConstPressureReactor::updateState(), Reactor::updateState(), and MultiPhase::uploadMoleFractionsFromPhases().
void checkSpeciesIndex (size_t k) const inherited
Check that the specified species index is in range Throws an exception if k is greater than nSpecies()-1.
Definition at line 268 of file Phase.cpp.
References Phase::m_kk.
Referenced by Phase::concentration(), Phase::massFraction(), Phase::molecularWeight(), Phase::moleFraction(), Phase::nAtoms(), and Phase::speciesName().
void checkSpeciesArraySize (size_t kk) const inherited
Check that an array size is at least nSpecies() Throws an exception if kk is less than nSpecies().
Used before calls which take an array pointer.
Definition at line 275 of file Phase.cpp.
References Phase::m_kk.
void saveState (vector_fp & state) const inherited
Save the current internal state of the phase Write to vector 'state' the current internal state.
Parameters
state output vector. Will be resized to nSpecies() + 2.
Definition at line 288 of file Phase.cpp.
References Phase::nSpecies().
Referenced by ChemEquil::equilibrate(), ChemEquil::estimateEP_Brinkley(), TransportFactory::newTransport(), ReactorBase::setThermoMgr(), FlowReactor::updateState(), ConstPressureReactor::updateState(), and Reactor::updateState().
void saveState (size_t lenstate, doublereal * state) const inherited
Write to array 'state' the current internal state.
Parameters
lenstate length of the state array. Must be >= nSpecies()+2
state output vector. Must be of length nSpecies() + 2 or greater.
Definition at line 293 of file Phase.cpp.
References Phase::density(), Phase::getMassFractions(), and Phase::temperature().
void restoreState (const vector_fp & state) inherited
Restore a state saved on a previous call to saveState.
Parameters
state State vector containing the previously saved state.
Definition at line 300 of file Phase.cpp.
Referenced by ChemEquil::equilibrate(), ChemEquil::estimateEP_Brinkley(), MultiTransport::getMassFluxes(), FlowReactor::initialize(), ConstPressureReactor::initialize(), Reactor::initialize(), and TransportFactory::newTransport().
void restoreState (size_t lenstate, const doublereal * state) inherited
Restore the state of the phase from a previously saved state vector.
Parameters
lenstate Length of the state vector
state Vector of state conditions.
Definition at line 305 of file Phase.cpp.
References Phase::nSpecies(), Phase::setDensity(), Phase::setMassFractions_NoNorm(), and Phase::setTemperature().
void setMoleFractionsByName (compositionMap & xMap) inherited
Set the species mole fractions by name.
@param xMap map from species names to mole fraction values.
Species not listed by name in xMap are set to zero.
Definition at line 362 of file Phase.cpp.
References Phase::nSpecies(), Phase::setMoleFractions(), and Phase::speciesName().
Referenced by Inlet1D::setMoleFractions(), OutletRes1D::setMoleFractions(), Phase::setMoleFractionsByName(), ThermoPhase::setState_TPX(), Phase::setState_TRX(), MixtureFugacityTP::setStateFromXML(), and ThermoPhase::setStateFromXML().
void setMoleFractionsByName (const std::string & x) inherited
Set the mole fractions of a group of species by name.
Species which are not listed by name in the composition map are set to zero.
Parameters
x string x in the form of a composition map
Definition at line 376 of file Phase.cpp.
References Phase::nSpecies(), Cantera::parseCompString(), Phase::setMoleFractionsByName(), and Phase::speciesName().
void setMassFractionsByName (compositionMap & yMap) inherited
Set the species mass fractions by name.
@param yMap map from species names to mass fraction values.
Species not listed by name in yMap are set to zero.
Definition at line 416 of file Phase.cpp.
References Phase::nSpecies(), Phase::setMassFractions(), and Phase::speciesName().
Referenced by Phase::setMassFractionsByName(), ThermoPhase::setState_TPY(), Phase::setState_TRY(), MixtureFugacityTP::setStateFromXML(), and ThermoPhase::setStateFromXML().
void setMassFractionsByName (const std::string & x) inherited
Set the species mass fractions by name.
Species not listed by name in x are set to zero.
Parameters
x String containing a composition map
Definition at line 430 of file Phase.cpp.
References Phase::nSpecies(), Cantera::parseCompString(), Phase::setMassFractionsByName(), and Phase::speciesName().
void setState_TRX (doublereal t, doublereal dens, const doublereal * x) inherited
Set the internally stored temperature (K), density, and mole fractions.
Parameters
t Temperature in kelvin
dens Density (kg/m^3)
x vector of species mole fractions, length m_kk
Definition at line 441 of file Phase.cpp.
References Phase::setDensity(), Phase::setMoleFractions(), and Phase::setTemperature().
void setState_TRX (doublereal t, doublereal dens, compositionMap & x) inherited
Set the internally stored temperature (K), density, and mole fractions.
Parameters
t Temperature in kelvin
dens Density (kg/m^3)
x Composition Map containing the mole fractions. Species not included in the map are assumed to have a zero mole fraction.
Definition at line 455 of file Phase.cpp.
References Phase::setDensity(), Phase::setMoleFractionsByName(), and Phase::setTemperature().
void setState_TRY (doublereal t, doublereal dens, const doublereal * y) inherited
Set the internally stored temperature (K), density, and mass fractions.
Parameters
t Temperature in kelvin
dens Density (kg/m^3)
y vector of species mass fractions, length m_kk
Definition at line 462 of file Phase.cpp.
References Phase::setDensity(), Phase::setMassFractions(), and Phase::setTemperature().
void setState_TRY (doublereal t, doublereal dens, compositionMap & y) inherited
Set the internally stored temperature (K), density, and mass fractions.
Parameters
t Temperature in kelvin
dens Density (kg/m^3)
y Composition Map containing the mass fractions. Species not included in the map are assumed to have a zero mass fraction.
Definition at line 469 of file Phase.cpp.
References Phase::setDensity(), Phase::setMassFractionsByName(), and Phase::setTemperature().
void setState_TNX (doublereal t, doublereal n, const doublereal * x) inherited
Set the internally stored temperature (K), molar density (kmol/m^3), and mole fractions.
Parameters
t Temperature in kelvin
n molar density (kmol/m^3)
x vector of species mole fractions, length m_kk
Definition at line 448 of file Phase.cpp.
References Phase::setMolarDensity(), Phase::setMoleFractions(), and Phase::setTemperature().
void setState_TR (doublereal t, doublereal rho) inherited
Set the internally stored temperature (K) and density (kg/m^3)
Parameters
t Temperature in kelvin
rho Density (kg/m^3)
Definition at line 476 of file Phase.cpp.
References Phase::setDensity(), and Phase::setTemperature().
Referenced by PureFluidPhase::setState_HP(), PureFluidPhase::setState_SP(), PureFluidPhase::setState_SV(), PDSS_IonsFromNeutral::setState_TR(), and PureFluidPhase::setState_UV().
void setState_TX (doublereal t, doublereal * x) inherited
Set the internally stored temperature (K) and mole fractions.
Parameters
t Temperature in kelvin
x vector of species mole fractions, length m_kk
Definition at line 482 of file Phase.cpp.
References Phase::setMoleFractions(), and Phase::setTemperature().
void setState_TY (doublereal t, doublereal * y) inherited
Set the internally stored temperature (K) and mass fractions.
Parameters
t Temperature in kelvin
y vector of species mass fractions, length m_kk
Definition at line 488 of file Phase.cpp.
References Phase::setMassFractions(), and Phase::setTemperature().
void setState_RX (doublereal rho, doublereal * x) inherited
Set the density (kg/m^3) and mole fractions.
Parameters
rho Density (kg/m^3)
x vector of species mole fractions, length m_kk
Definition at line 494 of file Phase.cpp.
References Phase::setDensity(), and Phase::setMoleFractions().
void setState_RY (doublereal rho, doublereal * y) inherited
Set the density (kg/m^3) and mass fractions.
Parameters
rho Density (kg/m^3)
y vector of species mass fractions, length m_kk
Definition at line 500 of file Phase.cpp.
References Phase::setDensity(), and Phase::setMassFractions().
doublereal molecularWeight (size_t k) const inherited
Molecular weight of species k.
Parameters
k index of species k
Returns
Returns the molecular weight of species k.
Definition at line 506 of file Phase.cpp.
References Phase::checkSpeciesIndex(), and Phase::m_molwts.
Referenced by VPSSMgr_Water_ConstVol::_updateRefStateThermo(), VPSSMgr_Water_HKFT::_updateRefStateThermo(), VPSSMgr_Water_ConstVol::_updateStandardStateThermo(), VPSSMgr_Water_HKFT::_updateStandardStateThermo(), SingleSpeciesTP::cv_mole(), SingleSpeciesTP::getPartialMolarVolumes(), SingleSpeciesTP::getStandardVolumes(), VPSSMgr_Water_ConstVol::getStandardVolumes_ref(), PDSS::initThermo(), VPSSMgr_Water_ConstVol::initThermoXML(), VPSSMgr_Water_HKFT::initThermoXML(), PDSS_ConstVol::initThermoXML(), MineralEQ3::initThermoXML(), PDSS_SSVol::initThermoXML(), Phase::molarMass(), MolalityVPSSTP::setSolvent(), HMWSoln::speciesMolarVolume(), and LiquidTransport::stefan_maxwell_solve().
doublereal molarMass (size_t k) const inline inherited
Return the Molar mass of species k Alternate name for molecular weight.
@param k  index for species
@return   Return the molar mass of species k kg/kmol.
Deprecated:
use molecularWeight instead
Definition at line 388 of file Phase.h.
References Phase::molecularWeight().
void getMolecularWeights (vector_fp & weights) const inherited
Copy the vector of molecular weights into vector weights.
Parameters
weights Output vector of molecular weights (kg/kmol)
Definition at line 512 of file Phase.cpp.
References Phase::molecularWeights().
void getMolecularWeights (int iwt, doublereal * weights) const inherited
Copy the vector of molecular weights into array weights.
@param iwt      Unused.
@param weights  Output array of molecular weights (kg/kmol)
Deprecated:
Definition at line 521 of file Phase.cpp.
References Phase::molecularWeights().
void getMolecularWeights (doublereal * weights) const inherited
Copy the vector of molecular weights into array weights.
Parameters
weights Output array of molecular weights (kg/kmol)
Definition at line 527 of file Phase.cpp.
References Phase::molecularWeights().
const vector_fp & molecularWeights () const inherited
Return a const reference to the internal vector of molecular weights.
units = kg / kmol
Definition at line 533 of file Phase.cpp.
References Phase::m_molwts.
Referenced by ReactingSurf1D::eval(), Phase::freezeSpecies(), Phase::getMolecularWeights(), MixTransport::getSpeciesFluxes(), AqueousTransport::getSpeciesFluxesExt(), SimpleTransport::getSpeciesFluxesExt(), Cantera::getStick(), GasTransport::initGas(), DustyGasTransport::initialize(), LiquidTransport::initLiquid(), SimpleTransport::initLiquid(), AqueousTransport::initLiquid(), TransportFactory::setupLiquidTransport(), TransportFactory::setupMM(), AqueousTransport::stefan_maxwell_solve(), LiquidTransport::stefan_maxwell_solve(), and StFlow::StFlow().
doublereal size (size_t k) const inline inherited
This routine returns the size of species k.
Parameters
k index of the species
Returns
The size of the species. Units are meters.
Definition at line 413 of file Phase.h.
References Phase::m_speciesSize.
Referenced by MolarityIonicVPSSTP::constructPhaseXML(), RedlichKisterVPSSTP::constructPhaseXML(), MargulesVPSSTP::constructPhaseXML(), MixedSolventElectrolyte::constructPhaseXML(), PhaseCombo_Interaction::constructPhaseXML(), IonsFromNeutralVPSSTP::constructPhaseXML(), IdealMolalSoln::constructPhaseXML(), IdealSolidSolnPhase::constructPhaseXML(), DebyeHuckel::constructPhaseXML(), ReactingSurf1D::eval(), SurfPhase::getCoverages(), SurfPhase::initThermo(), IdealMolalSoln::initThermoXML(), LatticeSolidPhase::installSlavePhases(), SurfPhase::setCoverages(), SurfPhase::setCoveragesNoNorm(), and SurfPhase::standardConcentration().
void getMoleFractionsByName (compositionMap & x) const inherited
Get the mole fractions by name.
Parameters
[out] x composition map containing the species mole fractions.
Definition at line 538 of file Phase.cpp.
References Phase::moleFraction(), Phase::nSpecies(), and Phase::speciesName().
doublereal moleFraction (size_t k) const inherited
Return the mole fraction of a single species.
Parameters
k species index
Returns
Mole fraction of the species
Definition at line 552 of file Phase.cpp.
References Phase::checkSpeciesIndex(), Phase::m_mmw, and Phase::m_ym.
Referenced by Phase::chargeDensity(), SolidTransport::electricalConductivity(), ChemEquil::equilibrate(), IdealMolalSoln::getActivities(), DebyeHuckel::getActivities(), HMWSoln::getActivities(), MolalityVPSSTP::getActivityCoefficients(), IdealSolnGasVPSS::getActivityConcentrations(), RedlichKwongMFTP::getActivityConcentrations(), ConstDensityThermo::getChemPotentials(), IdealSolnGasVPSS::getChemPotentials(), RedlichKwongMFTP::getChemPotentials(), IdealSolidSolnPhase::getChemPotentials(), IdealMolalSoln::getChemPotentials(), IdealGasPhase::getChemPotentials(), LatticePhase::getChemPotentials(), DebyeHuckel::getChemPotentials(), HMWSoln::getChemPotentials(), IdealSolidSolnPhase::getChemPotentials_RT(), IdealMolalSoln::getMolalityActivityCoefficients(), Phase::getMoleFractionsByName(), IdealSolnGasVPSS::getPartialMolarEntropies(), RedlichKwongMFTP::getPartialMolarEntropies(), IdealGasPhase::getPartialMolarEntropies(), IdealMolalSoln::getPartialMolarEntropies(), IdealSolidSolnPhase::getPartialMolarEntropies(), LatticePhase::getPartialMolarEntropies(), DebyeHuckel::getPartialMolarEntropies(), HMWSoln::getPartialMolarEntropies(), Phase::moleFraction(), DebyeHuckel::s_update_d2lnMolalityActCoeff_dT2(), DebyeHuckel::s_update_dlnMolalityActCoeff_dP(), DebyeHuckel::s_update_dlnMolalityActCoeff_dT(), DebyeHuckel::s_update_lnMolalityActCoeff(), HMWSoln::s_update_lnMolalityActCoeff(), IdealMolalSoln::s_updateIMS_lnMolalityActCoeff(), HMWSoln::s_updateIMS_lnMolalityActCoeff(), HMWSoln::s_updatePitzer_lnMolalityActCoeff(), and ChemEquil::setInitialMoles().
doublereal moleFraction (std::string name) const inherited
Return the mole fraction of a single species.
Parameters
name String name of the species
Returns
Mole fraction of the species
Definition at line 558 of file Phase.cpp.
References Phase::moleFraction(), Cantera::npos, and Phase::speciesIndex().
doublereal massFraction (size_t k) const inherited
Return the mass fraction of a single species.
Parameters
k species index
Returns
Mass fraction of the species
Definition at line 573 of file Phase.cpp.
References Phase::checkSpeciesIndex(), and Phase::m_y.
doublereal massFraction (std::string name) const inherited
Return the mass fraction of a single species.
Parameters
name String name of the species
Returns
Mass Fraction of the species
Definition at line 579 of file Phase.cpp.
References Phase::massFractions(), Cantera::npos, and Phase::speciesIndex().
void getMoleFractions (doublereal *const x) const inherited
Get the species mole fraction vector.
Parameters
x On return, x contains the mole fractions. Must have a length greater than or equal to the number of species.
Definition at line 547 of file Phase.cpp.
References Phase::m_mmw, Phase::m_ym, and Cantera::scale().
Referenced by IdealMolalSoln::calcDensity(), DebyeHuckel::calcDensity(), HMWSoln::calcDensity(), IonsFromNeutralVPSSTP::calcIonMoleFractions(), MolalityVPSSTP::calcMolalities(), HMWSoln::calcMolalitiesCropped(), IdealMolalSoln::enthalpy_mole(), HMWSoln::enthalpy_mole(), ChemEquil::estimateElementPotentials(), ChemEquil::estimateEP_Brinkley(), GibbsExcessVPSSTP::getActivities(), LatticePhase::getActivityConcentrations(), MultiTransport::getMassFluxes(), LTI_Pairwise_Interaction::getMatrixTransProp(), LTI_StefanMaxwell_PPN::getMatrixTransProp(), LTI_MoleFracs::getMixTransProp(), LTI_Log_MoleFracs::getMixTransProp(), LTI_Pairwise_Interaction::getMixTransProp(), LTI_StefanMaxwell_PPN::getMixTransProp(), LTI_MoleFracs_ExpT::getMixTransProp(), LatticeSolidPhase::getMoleFractions(), DustyGasTransport::initialize(), GibbsExcessVPSSTP::initThermo(), HMWSoln::printCoeffs(), HMWSoln::relative_molal_enthalpy(), PseudoBinaryVPSSTP::report(), MolarityIonicVPSSTP::report(), PureFluidPhase::report(), MolalityVPSSTP::report(), ThermoPhase::report(), PureFluidPhase::reportCSV(), MolalityVPSSTP::reportCSV(), ThermoPhase::reportCSV(), MixtureFugacityTP::setConcentrations(), GibbsExcessVPSSTP::setConcentrations(), MixtureFugacityTP::setMassFractions(), GibbsExcessVPSSTP::setMassFractions(), MixtureFugacityTP::setMassFractions_NoNorm(), GibbsExcessVPSSTP::setMassFractions_NoNorm(), MolalityVPSSTP::setMolalitiesByName(), MixtureFugacityTP::setMoleFractions(), GibbsExcessVPSSTP::setMoleFractions(), MixtureFugacityTP::setMoleFractions_NoNorm(), GibbsExcessVPSSTP::setMoleFractions_NoNorm(), MultiPhase::setMoles(), vcs_VolPhase::setPtrThermoPhase(), ThermoPhase::setReferenceComposition(), MixtureFugacityTP::setState_TP(), MixtureFugacityTP::setState_TR(), AqueousTransport::stefan_maxwell_solve(), ChemEquil::update(), MixTransport::update_C(), MultiTransport::update_C(), AqueousTransport::update_C(), SimpleTransport::update_C(), LiquidTransport::update_C(), solveSP::updateMFKinSpecies(), DustyGasTransport::updateTransport_C(), and MultiPhase::uploadMoleFractionsFromPhases().
void setMoleFractions (const doublereal *const x) virtual inherited
Set the mole fractions to the specified values There is no restriction on the sum of the mole fraction vector.
Internally, the Phase object will normalize this vector before storing its contents.
Parameters
x Array of unnormalized mole fraction values (input). Must have a length greater than or equal to the number of species, m_kk.
Reimplemented in IonsFromNeutralVPSSTP, GibbsExcessVPSSTP, LatticePhase, MixtureFugacityTP, IdealSolidSolnPhase, LatticeSolidPhase, and RedlichKwongMFTP.
Definition at line 317 of file Phase.cpp.
References Phase::m_kk, Phase::m_mmw, Phase::m_molwts, Phase::m_y, Phase::m_ym, ckr::max(), and Phase::stateMFChangeCalc().
Referenced by ChemEquil::calcEmoles(), ChemEquil::equilibrate(), ChemEquil::estimateElementPotentials(), ChemEquil::estimateEP_Brinkley(), PureFluidPhase::initThermo(), SingleSpeciesTP::initThermo(), WaterSSTP::initThermoXML(), IonsFromNeutralVPSSTP::setConcentrations(), IonsFromNeutralVPSSTP::setMassFractions(), IonsFromNeutralVPSSTP::setMassFractions_NoNorm(), MolalityVPSSTP::setMolalities(), MolalityVPSSTP::setMolalitiesByName(), Inlet1D::setMoleFractions(), OutletRes1D::setMoleFractions(), LatticeSolidPhase::setMoleFractions(), IdealSolidSolnPhase::setMoleFractions(), MixtureFugacityTP::setMoleFractions(), LatticePhase::setMoleFractions(), GibbsExcessVPSSTP::setMoleFractions(), IonsFromNeutralVPSSTP::setMoleFractions(), IdealSolidSolnPhase::setMoleFractions_NoNorm(), LatticePhase::setMoleFractions_NoNorm(), Phase::setMoleFractionsByName(), ThermoPhase::setState_PX(), Phase::setState_RX(), Phase::setState_TNX(), ThermoPhase::setState_TPX(), Phase::setState_TRX(), and Phase::setState_TX().
void setMoleFractions_NoNorm (const doublereal *const x) virtual inherited
Set the mole fractions to the specified values without normalizing.
This is useful when the normalization condition is being handled by some other means, for example by a constraint equation as part of a larger set of equations.
Parameters
x Input vector of mole fractions. Length is m_kk.
Reimplemented in IonsFromNeutralVPSSTP, GibbsExcessVPSSTP, LatticePhase, MixtureFugacityTP, IdealSolidSolnPhase, and RedlichKwongMFTP.
Definition at line 350 of file Phase.cpp.
References Cantera::dot(), Phase::m_kk, Phase::m_mmw, Phase::m_molwts, Phase::m_y, Phase::m_ym, and Phase::stateMFChangeCalc().
Referenced by MixtureFugacityTP::setMoleFractions_NoNorm(), GibbsExcessVPSSTP::setMoleFractions_NoNorm(), and IonsFromNeutralVPSSTP::setMoleFractions_NoNorm().
void getMassFractions (doublereal *const y) const inherited
Get the species mass fractions.
Parameters
[out] y Array of mass fractions, length nSpecies()
Definition at line 589 of file Phase.cpp.
References Phase::m_y.
Referenced by LTI_MassFracs::getMixTransProp(), Cantera::importSolution(), PureFluidPhase::report(), ThermoPhase::report(), PureFluidPhase::reportCSV(), ThermoPhase::reportCSV(), Phase::saveState(), Inlet1D::setMoleFractions(), OutletRes1D::setMoleFractions(), and LiquidTransport::update_C().
const doublereal* massFractions () const inline inherited
Return a const pointer to the mass fraction array.
Definition at line 469 of file Phase.h.
References Phase::m_y.
Referenced by MultiTransport::getMassFluxes(), MultiTransport::getSpeciesFluxes(), MixTransport::getSpeciesFluxes(), AqueousTransport::getSpeciesFluxesExt(), SimpleTransport::getSpeciesFluxesExt(), SimpleTransport::getSpeciesVdiff(), SimpleTransport::getSpeciesVdiffES(), and Phase::massFraction().
void setMassFractions (const doublereal *const y) virtual inherited
Set the mass fractions to the specified values and normalize them.
@param[in] y Array of unnormalized mass fraction values. Length
must be greater than or equal to the number of species. The Ptate object will normalize this vector before storing its contents.
Reimplemented in IonsFromNeutralVPSSTP, LatticePhase, GibbsExcessVPSSTP, MixtureFugacityTP, LatticeSolidPhase, IdealSolidSolnPhase, and RedlichKwongMFTP.
Definition at line 387 of file Phase.cpp.
References Phase::m_kk, Phase::m_mmw, Phase::m_rmolwts, Phase::m_y, Phase::m_ym, ckr::max(), Cantera::scale(), and Phase::stateMFChangeCalc().
Referenced by Cantera::importSolution(), IdealSolidSolnPhase::setMassFractions(), MixtureFugacityTP::setMassFractions(), GibbsExcessVPSSTP::setMassFractions(), LatticePhase::setMassFractions(), Phase::setMassFractionsByName(), ThermoPhase::setState_PY(), Phase::setState_RY(), ThermoPhase::setState_TPY(), Phase::setState_TRY(), Phase::setState_TY(), FlowReactor::updateState(), ConstPressureReactor::updateState(), and Reactor::updateState().
void setMassFractions_NoNorm (const doublereal *const y) virtual inherited
Set the mass fractions to the specified values without normalizing.
This is useful when the normalization condition is being handled by some other means, for example by a constraint equation as part of a larger set of equations.
Parameters
y Input vector of mass fractions. Length is m_kk.
Reimplemented in IonsFromNeutralVPSSTP, LatticePhase, GibbsExcessVPSSTP, MixtureFugacityTP, LatticeSolidPhase, IdealSolidSolnPhase, and RedlichKwongMFTP.
Definition at line 403 of file Phase.cpp.
References Phase::m_kk, Phase::m_mmw, Phase::m_rmolwts, Phase::m_y, Phase::m_ym, and Phase::stateMFChangeCalc().
Referenced by Phase::restoreState(), StFlow::setGas(), StFlow::setGasAtMidpoint(), IdealSolidSolnPhase::setMassFractions_NoNorm(), MixtureFugacityTP::setMassFractions_NoNorm(), GibbsExcessVPSSTP::setMassFractions_NoNorm(), and LatticePhase::setMassFractions_NoNorm().
void getConcentrations (doublereal *const c) const inherited
Get the species concentrations (kmol/m^3).
@param[out] c Array of species concentrations Length must be
greater than or equal to the number of species.
Definition at line 600 of file Phase.cpp.
References Phase::m_dens, Phase::m_ym, and Cantera::scale().
Referenced by ConstDensityThermo::getActivityConcentrations(), IdealSolnGasVPSS::getActivityConcentrations(), SurfPhase::getActivityConcentrations(), IdealGasPhase::getActivityConcentrations(), SurfPhase::getCoverages(), solveSP::solveSurfProb(), SimpleTransport::update_C(), and LiquidTransport::update_C().
doublereal concentration (const size_t k) const inherited
Concentration of species k.
If k is outside the valid range, an exception will be thrown.
Parameters
k Index of species
Definition at line 594 of file Phase.cpp.
References Phase::checkSpeciesIndex(), Phase::m_dens, Phase::m_rmolwts, and Phase::m_y.
void setConcentrations (const doublereal *const conc) virtual inherited
Set the concentrations to the specified values within the phase.
We set the concentrations here and therefore we set the overall density of the phase. We hold the temperature constant during this operation. Therefore, we have possibly changed the pressure of the phase by calling this routine.
Parameters
[in] conc Array of concentrations in dimensional units. For bulk phases c[k] is the concentration of the kth species in kmol/m3. For surface phases, c[k] is the concentration in kmol/m2. The length of the vector is the numberof species in the phase.
Reimplemented in IonsFromNeutralVPSSTP, GibbsExcessVPSSTP, LatticePhase, MixtureFugacityTP, LatticeSolidPhase, IdealSolidSolnPhase, and RedlichKwongMFTP.
Definition at line 605 of file Phase.cpp.
References Phase::m_kk, Phase::m_mmw, Phase::m_molwts, Phase::m_y, Phase::m_ym, ckr::max(), Phase::setDensity(), and Phase::stateMFChangeCalc().
Referenced by IdealSolidSolnPhase::setConcentrations(), MixtureFugacityTP::setConcentrations(), LatticePhase::setConcentrations(), GibbsExcessVPSSTP::setConcentrations(), ImplicitSurfChem::setConcSpecies(), SurfPhase::setCoverages(), and SurfPhase::setCoveragesNoNorm().
const doublereal * moleFractdivMMW () const inherited
Returns a const pointer to the start of the moleFraction/MW array.
This array is the array of mole fractions, each divided by the mean molecular weight.
Definition at line 568 of file Phase.cpp.
References Phase::m_ym.
Referenced by IdealSolnGasVPSS::calcDensity(), RedlichKwongMFTP::calcDensity(), IdealSolidSolnPhase::calcDensity(), and IdealSolidSolnPhase::getActivityConcentrations().
doublereal charge (size_t k) const inherited
Dimensionless electrical charge of a single molecule of species k The charge is normalized by the the magnitude of the electron charge.
Parameters
k species index
Definition at line 642 of file Phase.cpp.
References Phase::m_speciesCharge.
Referenced by InterfaceKinetics::applyButlerVolmerCorrection(), HMWSoln::calcMolalitiesCropped(), Phase::chargeDensity(), PDSS_HKFT::constructPDSSXML(), SolidTransport::electricalConductivity(), PureFluidPhase::getElectrochemPotentials(), PseudoBinaryVPSSTP::getElectrochemPotentials(), MolarityIonicVPSSTP::getElectrochemPotentials(), GibbsExcessVPSSTP::getElectrochemPotentials(), RedlichKisterVPSSTP::getElectrochemPotentials(), MargulesVPSSTP::getElectrochemPotentials(), ThermoPhase::getElectrochemPotentials(), MixedSolventElectrolyte::getElectrochemPotentials(), MolalityVPSSTP::getElectrochemPotentials(), PhaseCombo_Interaction::getElectrochemPotentials(), InterfaceKinetics::getEquilibriumConstants(), LiquidTransport::initLiquid(), SimpleTransport::initLiquid(), PDSS_HKFT::initThermo(), IonsFromNeutralVPSSTP::initThermoXML(), DebyeHuckel::initThermoXML(), LatticeSolidPhase::installSlavePhases(), HMWSoln::printCoeffs(), PhaseCombo_Interaction::readXMLBinarySpecies(), RedlichKisterVPSSTP::readXMLBinarySpecies(), MargulesVPSSTP::readXMLBinarySpecies(), MixedSolventElectrolyte::readXMLBinarySpecies(), HMWSoln::relative_molal_enthalpy(), HMWSoln::s_updatePitzer_d2lnMolalityActCoeff_dT2(), HMWSoln::s_updatePitzer_dlnMolalityActCoeff_dP(), HMWSoln::s_updatePitzer_dlnMolalityActCoeff_dT(), HMWSoln::s_updatePitzer_lnMolalityActCoeff(), MolalityVPSSTP::setMolalitiesByName(), vcs_VolPhase::transferElementsFM(), and InterfaceKinetics::updateKc().
doublereal chargeDensity () const inherited
Charge density [C/m^3].
Definition at line 647 of file Phase.cpp.
References Phase::charge(), Phase::moleFraction(), and Phase::nSpecies().
size_t nDim () const inline inherited
Returns the number of spatial dimensions (1, 2, or 3)
Definition at line 523 of file Phase.h.
References Phase::m_ndim.
Referenced by Kinetics::addPhase(), EdgeKinetics::finalize(), InterfaceKinetics::finalize(), IdealSolnGasVPSS::getUnitsStandardConc(), RedlichKwongMFTP::getUnitsStandardConc(), IdealMolalSoln::getUnitsStandardConc(), MolalityVPSSTP::getUnitsStandardConc(), IdealSolidSolnPhase::getUnitsStandardConc(), ThermoPhase::getUnitsStandardConc(), DebyeHuckel::getUnitsStandardConc(), and HMWSoln::getUnitsStandardConc().
void setNDim (size_t ndim) inline inherited
Set the number of spatial dimensions (1, 2, or 3).
The number of spatial dimensions is used for vector involving directions.
Parameters
ndim Input number of dimensions.
Definition at line 530 of file Phase.h.
References Phase::m_ndim.
Referenced by EdgePhase::EdgePhase(), FixedChemPotSSTP::FixedChemPotSSTP(), Cantera::importPhase(), EdgePhase::operator=(), and SurfPhase::SurfPhase().
doublereal temperature () const inline inherited
Temperature (K).
Returns
The temperature of the phase
Definition at line 539 of file Phase.h.
References Phase::m_temp.
Referenced by ThermoPhase::_RT(), InterfaceKinetics::_update_rates_T(), MixtureFugacityTP::_updateReferenceStateThermo(), VPStandardStateTP::_updateStandardStateThermo(), ConstDensityThermo::_updateThermo(), SurfPhase::_updateThermo(), LatticeSolidPhase::_updateThermo(), SingleSpeciesTP::_updateThermo(), IdealGasPhase::_updateThermo(), LatticePhase::_updateThermo(), IdealSolidSolnPhase::_updateThermo(), DebyeHuckel::A_Debye_TP(), HMWSoln::A_Debye_TP(), MultiPhase::addPhase(), HMWSoln::ADebye_J(), HMWSoln::ADebye_L(), HMWSoln::ADebye_V(), InterfaceKinetics::applyButlerVolmerCorrection(), InterfaceKinetics::applyExchangeCurrentDensityFormulation(), IdealSolnGasVPSS::calcDensity(), MixtureFugacityTP::calculatePsat(), RedlichKwongMFTP::cp_mole(), SingleSpeciesTP::cv_mole(), HMWSoln::cv_mole(), DebyeHuckel::d2A_DebyedT2_TP(), HMWSoln::d2A_DebyedT2_TP(), DebyeHuckel::dA_DebyedP_TP(), HMWSoln::dA_DebyedP_TP(), DebyeHuckel::dA_DebyedT_TP(), HMWSoln::dA_DebyedT_TP(), WaterSSTP::dthermalExpansionCoeffdT(), IdealSolnGasVPSS::enthalpy_mole(), ConstDensityThermo::enthalpy_mole(), IdealSolidSolnPhase::enthalpy_mole(), LatticePhase::enthalpy_mole(), IdealGasPhase::enthalpy_mole(), ChemEquil::equilibrate(), ChemEquil::estimateElementPotentials(), ChemEquil::estimateEP_Brinkley(), FixedChemPotSSTP::FixedChemPotSSTP(), RedlichKwongMFTP::getActivityCoefficients(), ConstDensityThermo::getChemPotentials(), SurfPhase::getChemPotentials(), MolarityIonicVPSSTP::getChemPotentials(), IdealSolnGasVPSS::getChemPotentials(), IonsFromNeutralVPSSTP::getChemPotentials(), RedlichKwongMFTP::getChemPotentials(), RedlichKisterVPSSTP::getChemPotentials(), MargulesVPSSTP::getChemPotentials(), MixedSolventElectrolyte::getChemPotentials(), PhaseCombo_Interaction::getChemPotentials(), IdealSolidSolnPhase::getChemPotentials(), IdealMolalSoln::getChemPotentials(), IdealGasPhase::getChemPotentials(), LatticePhase::getChemPotentials(), DebyeHuckel::getChemPotentials(), HMWSoln::getChemPotentials(), StoichSubstance::getChemPotentials_RT(), SingleSpeciesTP::getChemPotentials_RT(), IdealSolidSolnPhase::getChemPotentials_RT(), WaterSSTP::getCp_R_ref(), AqueousKinetics::getDeltaSSEnthalpy(), GasKinetics::getDeltaSSEnthalpy(), InterfaceKinetics::getDeltaSSEnthalpy(), PhaseCombo_Interaction::getdlnActCoeffds(), MargulesVPSSTP::getdlnActCoeffds(), MixedSolventElectrolyte::getdlnActCoeffds(), ThermoPhase::getElementPotentials(), WaterSSTP::getEnthalpy_RT(), StoichSubstance::getEnthalpy_RT(), StoichSubstanceSSTP::getEnthalpy_RT(), MineralEQ3::getEnthalpy_RT(), SurfPhase::getEnthalpy_RT(), IdealSolidSolnPhase::getEnthalpy_RT(), LatticePhase::getEnthalpy_RT(), WaterSSTP::getEnthalpy_RT_ref(), PureFluidPhase::getEnthalpy_RT_ref(), WaterSSTP::getEntropy_R_ref(), PureFluidPhase::getEntropy_R_ref(), AqueousKinetics::getEquilibriumConstants(), GasKinetics::getEquilibriumConstants(), InterfaceKinetics::getEquilibriumConstants(), StoichSubstance::getGibbs_ref(), PureFluidPhase::getGibbs_ref(), SingleSpeciesTP::getGibbs_ref(), LatticeSolidPhase::getGibbs_ref(), IdealSolidSolnPhase::getGibbs_ref(), LatticePhase::getGibbs_ref(), WaterSSTP::getGibbs_RT(), StoichSubstance::getGibbs_RT(), SurfPhase::getGibbs_RT(), WaterSSTP::getGibbs_RT_ref(), PureFluidPhase::getGibbs_RT_ref(), StoichSubstanceSSTP::getIntEnergy_RT(), MineralEQ3::getIntEnergy_RT(), IdealSolidSolnPhase::getIntEnergy_RT(), StoichSubstanceSSTP::getIntEnergy_RT_ref(), MineralEQ3::getIntEnergy_RT_ref(), MetalSHEelectrons::getIntEnergy_RT_ref(), IdealSolidSolnPhase::getIntEnergy_RT_ref(), LTI_Pairwise_Interaction::getMatrixTransProp(), LTI_StefanMaxwell_PPN::getMatrixTransProp(), SolidTransport::getMixDiffCoeffs(), LTI_MoleFracs::getMixTransProp(), LTI_MassFracs::getMixTransProp(), LTI_Log_MoleFracs::getMixTransProp(), LTI_MoleFracs_ExpT::getMixTransProp(), SolidTransport::getMobilities(), MolarityIonicVPSSTP::getPartialMolarCp(), RedlichKisterVPSSTP::getPartialMolarCp(), MargulesVPSSTP::getPartialMolarCp(), MixedSolventElectrolyte::getPartialMolarCp(), PhaseCombo_Interaction::getPartialMolarCp(), DebyeHuckel::getPartialMolarCp(), HMWSoln::getPartialMolarCp(), SurfPhase::getPartialMolarEnthalpies(), IdealSolnGasVPSS::getPartialMolarEnthalpies(), MolarityIonicVPSSTP::getPartialMolarEnthalpies(), SingleSpeciesTP::getPartialMolarEnthalpies(), IonsFromNeutralVPSSTP::getPartialMolarEnthalpies(), RedlichKwongMFTP::getPartialMolarEnthalpies(), RedlichKisterVPSSTP::getPartialMolarEnthalpies(), MargulesVPSSTP::getPartialMolarEnthalpies(), MixedSolventElectrolyte::getPartialMolarEnthalpies(), PhaseCombo_Interaction::getPartialMolarEnthalpies(), IdealGasPhase::getPartialMolarEnthalpies(), IdealSolidSolnPhase::getPartialMolarEnthalpies(), LatticePhase::getPartialMolarEnthalpies(), DebyeHuckel::getPartialMolarEnthalpies(), HMWSoln::getPartialMolarEnthalpies(), MolarityIonicVPSSTP::getPartialMolarEntropies(), IonsFromNeutralVPSSTP::getPartialMolarEntropies(), RedlichKwongMFTP::getPartialMolarEntropies(), RedlichKisterVPSSTP::getPartialMolarEntropies(), MargulesVPSSTP::getPartialMolarEntropies(), MixedSolventElectrolyte::getPartialMolarEntropies(), PhaseCombo_Interaction::getPartialMolarEntropies(), DebyeHuckel::getPartialMolarEntropies(), HMWSoln::getPartialMolarEntropies(), IdealSolnGasVPSS::getPartialMolarIntEnergies(), SingleSpeciesTP::getPartialMolarIntEnergies(), RedlichKwongMFTP::getPartialMolarIntEnergies(), IdealGasPhase::getPartialMolarIntEnergies(), RedlichKwongMFTP::getPartialMolarVolumes(), MargulesVPSSTP::getPartialMolarVolumes(), MixedSolventElectrolyte::getPartialMolarVolumes(), PhaseCombo_Interaction::getPartialMolarVolumes(), DebyeHuckel::getPartialMolarVolumes(), HMWSoln::getPartialMolarVolumes(), SingleSpeciesTP::getPureGibbs(), LatticePhase::getPureGibbs(), LTPspecies_Arrhenius::getSpeciesTransProp(), LTPspecies_Poly::getSpeciesTransProp(), LTPspecies_ExpT::getSpeciesTransProp(), WaterSSTP::getStandardChemPotentials(), StoichSubstanceSSTP::getStandardChemPotentials(), MineralEQ3::getStandardChemPotentials(), MetalSHEelectrons::getStandardChemPotentials(), IdealGasPhase::getStandardChemPotentials(), WaterSSTP::getStandardVolumes_ref(), IdealSolnGasVPSS::gibbs_mole(), ConstDensityThermo::gibbs_mole(), StoichSubstance::gibbs_mole(), RedlichKwongMFTP::gibbs_mole(), IdealSolidSolnPhase::gibbs_mole(), ThermoPhase::gibbs_mole(), LatticePhase::gibbs_mole(), IdealGasPhase::gibbs_mole(), RedlichKwongMFTP::hresid(), ConstDensityThermo::intEnergy_mole(), StoichSubstance::intEnergy_mole(), IdealSolidSolnPhase::intEnergy_mole(), LatticePhase::intEnergy_mole(), IdealGasPhase::intEnergy_mole(), IdealGasPhase::logStandardConc(), MixtureFugacityTP::phaseState(), RedlichKwongMFTP::pressure(), IdealGasPhase::pressure(), MixTransport::pressure_ig(), RedlichKwongMFTP::pressureDerivatives(), HMWSoln::relative_enthalpy(), PseudoBinaryVPSSTP::report(), MolarityIonicVPSSTP::report(), PureFluidPhase::report(), MolalityVPSSTP::report(), ThermoPhase::report(), PureFluidPhase::reportCSV(), MolalityVPSSTP::reportCSV(), ThermoPhase::reportCSV(), PhaseCombo_Interaction::s_update_dlnActCoeff_dlnN(), MargulesVPSSTP::s_update_dlnActCoeff_dlnN(), MixedSolventElectrolyte::s_update_dlnActCoeff_dlnN(), PhaseCombo_Interaction::s_update_dlnActCoeff_dlnN_diag(), MargulesVPSSTP::s_update_dlnActCoeff_dlnN_diag(), MixedSolventElectrolyte::s_update_dlnActCoeff_dlnN_diag(), PhaseCombo_Interaction::s_update_dlnActCoeff_dlnX_diag(), MargulesVPSSTP::s_update_dlnActCoeff_dlnX_diag(), MixedSolventElectrolyte::s_update_dlnActCoeff_dlnX_diag(), PhaseCombo_Interaction::s_update_dlnActCoeff_dT(), MargulesVPSSTP::s_update_dlnActCoeff_dT(), MixedSolventElectrolyte::s_update_dlnActCoeff_dT(), RedlichKisterVPSSTP::s_update_dlnActCoeff_dX_(), PhaseCombo_Interaction::s_update_lnActCoeff(), RedlichKisterVPSSTP::s_update_lnActCoeff(), MargulesVPSSTP::s_update_lnActCoeff(), MixedSolventElectrolyte::s_update_lnActCoeff(), HMWSoln::s_updatePitzer_CoeffWRTemp(), HMWSoln::s_updatePitzer_dlnMolalityActCoeff_dP(), HMWSoln::s_updatePitzer_lnMolalityActCoeff(), WaterSSTP::satPressure(), HMWSoln::satPressure(), Phase::saveState(), WaterSSTP::setDensity(), ThermoPhase::setElementPotentials(), ChemEquil::setInitialMoles(), PureFluidPhase::setPressure(), WaterSSTP::setPressure(), GibbsExcessVPSSTP::setPressure(), IdealMolalSoln::setPressure(), VPStandardStateTP::setPressure(), MixtureFugacityTP::setPressure(), IdealGasPhase::setPressure(), IonsFromNeutralVPSSTP::setPressure(), DebyeHuckel::setPressure(), HMWSoln::setPressure(), vcs_VolPhase::setPtrThermoPhase(), SingleSpeciesTP::setState_HP(), ThermoPhase::setState_HPorUV(), SingleSpeciesTP::setState_SP(), ThermoPhase::setState_SPorSV(), SingleSpeciesTP::setState_SV(), SingleSpeciesTP::setState_UV(), MixtureFugacityTP::setStateFromXML(), MixtureFugacityTP::setTemperature(), PureFluidPhase::setTPXState(), ImplicitSurfChem::solvePseudoSteadyStateProblem(), RedlichKwongMFTP::sresid(), IdealSolnGasVPSS::standardConcentration(), IdealGasPhase::standardConcentration(), AqueousTransport::stefan_maxwell_solve(), LiquidTransport::stefan_maxwell_solve(), SolidTransport::thermalConductivity(), MetalSHEelectrons::thermalExpansionCoeff(), IdealGasPhase::thermalExpansionCoeff(), ChemEquil::update(), MixTransport::update_T(), MultiTransport::update_T(), AqueousTransport::update_T(), SimpleTransport::update_T(), LiquidTransport::update_T(), RedlichKwongMFTP::updateAB(), AqueousKinetics::updateKc(), GasKinetics::updateKc(), InterfaceKinetics::updateKc(), VPStandardStateTP::updateStandardStateThermo(), Reactor::updateState(), MultiTransport::updateThermal_T(), DustyGasTransport::updateTransport_T(), and WaterSSTP::vaporFraction().
virtual doublereal density () const inline virtual inherited
Density (kg/m^3).
Returns
The density of the phase
Reimplemented in HMWSoln.
Definition at line 545 of file Phase.h.
References Phase::m_dens.
Referenced by MixtureFugacityTP::calculatePsat(), SingleSpeciesTP::cv_mole(), HMWSoln::density(), WaterSSTP::dthermalExpansionCoeffdT(), WaterSSTP::getCp_R_ref(), WaterSSTP::getEnthalpy_RT_ref(), WaterSSTP::getEntropy_R_ref(), WaterSSTP::getGibbs_RT_ref(), MultiTransport::getMassFluxes(), ConstDensityThermo::getParameters(), StoichSubstance::getParameters(), StoichSubstanceSSTP::getParameters(), MetalSHEelectrons::getParameters(), MineralEQ3::getParameters(), SingleSpeciesTP::getPartialMolarVolumes(), MultiTransport::getSpeciesFluxes(), SimpleTransport::getSpeciesVdiff(), SimpleTransport::getSpeciesVdiffES(), SingleSpeciesTP::getStandardVolumes(), WaterSSTP::getStandardVolumes_ref(), RedlichKwongMFTP::hresid(), Phase::molarDensity(), MixtureFugacityTP::phaseState(), RedlichKwongMFTP::pressure(), PseudoBinaryVPSSTP::report(), MolarityIonicVPSSTP::report(), PureFluidPhase::report(), MolalityVPSSTP::report(), ThermoPhase::report(), PureFluidPhase::reportCSV(), MolalityVPSSTP::reportCSV(), ThermoPhase::reportCSV(), WaterSSTP::satPressure(), Phase::saveState(), IdealMolalSoln::setDensity(), IdealSolidSolnPhase::setDensity(), Phase::setDensity(), DebyeHuckel::setDensity(), WaterSSTP::setPressure(), MixtureFugacityTP::setState_TP(), IonsFromNeutralVPSSTP::setState_TP(), MixtureFugacityTP::setStateFromXML(), MixtureFugacityTP::setTemperature(), WaterSSTP::setTemperature(), PureFluidPhase::setTPXState(), RedlichKwongMFTP::sresid(), ChemEquil::update(), SimpleTransport::update_C(), LiquidTransport::update_C(), ConstPressureReactor::updateState(), StFlow::updateThermo(), WaterSSTP::vaporFraction(), and MixtureFugacityTP::z().
doublereal molarDensity () const inherited
Molar density (kmol/m^3).
Returns
The molar density of the phase
Definition at line 627 of file Phase.cpp.
References Phase::density(), and Phase::meanMolecularWeight().
Referenced by solveSP::calc_t(), SolidTransport::electricalConductivity(), ConstDensityThermo::enthalpy_mole(), StoichSubstance::enthalpy_mole(), IdealSolidSolnPhase::enthalpy_mole(), LatticePhase::enthalpy_mole(), ConstDensityThermo::getChemPotentials(), StoichSubstanceSSTP::getEnthalpy_RT(), MineralEQ3::getEnthalpy_RT(), StoichSubstanceSSTP::getIntEnergy_RT(), MineralEQ3::getIntEnergy_RT(), StoichSubstanceSSTP::getIntEnergy_RT_ref(), MineralEQ3::getIntEnergy_RT_ref(), MetalSHEelectrons::getIntEnergy_RT_ref(), LatticePhase::getParameters(), PureFluidPhase::getPartialMolarVolumes(), StoichSubstance::getPartialMolarVolumes(), IdealGasPhase::getPartialMolarVolumes(), MixTransport::getSpeciesFluxes(), AqueousTransport::getSpeciesFluxesExt(), SimpleTransport::getSpeciesFluxesExt(), StoichSubstance::getStandardVolumes(), IdealGasPhase::getStandardVolumes(), IdealSolnGasVPSS::intEnergy_mole(), ConstDensityThermo::intEnergy_mole(), StoichSubstance::intEnergy_mole(), RedlichKwongMFTP::intEnergy_mole(), IonsFromNeutralVPSSTP::intEnergy_mole(), IdealSolidSolnPhase::intEnergy_mole(), LatticePhase::intEnergy_mole(), DebyeHuckel::intEnergy_mole(), HMWSoln::intEnergy_mole(), ConstDensityThermo::logStandardConc(), Phase::molarVolume(), IdealGasPhase::pressure(), MixTransport::pressure_ig(), IdealMolalSoln::setMolarDensity(), DebyeHuckel::setMolarDensity(), and ConstDensityThermo::standardConcentration().
doublereal molarVolume () const inherited
Molar volume (m^3/kmol).
Returns
The molar volume of the phase
Definition at line 637 of file Phase.cpp.
References Phase::molarDensity().
Referenced by RedlichKwongMFTP::cp_mole(), HMWSoln::cv_mole(), RedlichKwongMFTP::getActivityCoefficients(), RedlichKwongMFTP::getChemPotentials(), LTI_StefanMaxwell_PPN::getMatrixTransProp(), RedlichKwongMFTP::getPartialMolarEnthalpies(), RedlichKwongMFTP::getPartialMolarEntropies(), RedlichKwongMFTP::getPartialMolarVolumes(), ThermoPhase::intEnergy_mole(), RedlichKwongMFTP::pressureDerivatives(), MixtureFugacityTP::setState_TR(), and LiquidTransport::stefan_maxwell_solve().
virtual void setDensity (const doublereal density) inline virtual inherited
Set the internally stored density (kg/m^3) of the phase Note the density of a phase is an independent variable.
Parameters
[in] density density (kg/m^3).
Reimplemented in HMWSoln, DebyeHuckel, WaterSSTP, IdealSolidSolnPhase, and IdealMolalSoln.
Definition at line 560 of file Phase.h.
References Phase::density(), and Phase::m_dens.
Referenced by IdealSolnGasVPSS::calcDensity(), RedlichKwongMFTP::calcDensity(), GibbsExcessVPSSTP::calcDensity(), IdealMolalSoln::calcDensity(), IdealSolidSolnPhase::calcDensity(), LatticeSolidPhase::calcDensity(), DebyeHuckel::calcDensity(), HMWSoln::calcDensity(), StoichSubstanceSSTP::initThermoXML(), WaterSSTP::initThermoXML(), MetalSHEelectrons::initThermoXML(), MineralEQ3::initThermoXML(), electrodeElectron::initThermoXML(), Phase::restoreState(), Phase::setConcentrations(), WaterSSTP::setDensity(), ConstDensityThermo::setParameters(), StoichSubstance::setParameters(), StoichSubstanceSSTP::setParameters(), MetalSHEelectrons::setParameters(), MineralEQ3::setParameters(), electrodeElectron::setParameters(), SemiconductorPhase::setParametersFromXML(), MetalPhase::setParametersFromXML(), StoichSubstance::setParametersFromXML(), ConstDensityThermo::setParametersFromXML(), StoichSubstanceSSTP::setParametersFromXML(), MetalSHEelectrons::setParametersFromXML(), PureFluidPhase::setPressure(), IdealGasPhase::setPressure(), ThermoPhase::setState_HPorUV(), PureFluidPhase::setState_Psat(), Phase::setState_RX(), Phase::setState_RY(), ThermoPhase::setState_SPorSV(), SingleSpeciesTP::setState_SV(), MixtureFugacityTP::setState_TP(), IonsFromNeutralVPSSTP::setState_TP(), Phase::setState_TR(), MixtureFugacityTP::setState_TR(), Phase::setState_TRX(), Phase::setState_TRY(), PureFluidPhase::setState_Tsat(), SingleSpeciesTP::setState_UV(), ThermoPhase::setStateFromXML(), and Reactor::updateState().
void setMolarDensity (const doublereal molarDensity) virtual inherited
Set the internally stored molar density (kmol/m^3) of the phase.
Parameters
[in] molarDensity Input molar density (kmol/m^3).
Reimplemented in HMWSoln, DebyeHuckel, IdealSolidSolnPhase, and IdealMolalSoln.
Definition at line 632 of file Phase.cpp.
References Phase::m_dens, and Phase::meanMolecularWeight().
Referenced by LatticePhase::calcDensity(), LatticePhase::setParameters(), and Phase::setState_TNX().
virtual void setTemperature (const doublereal temp) inline virtual inherited
Set the internally stored temperature of the phase (K).
Parameters
temp Temperature in Kelvin
Reimplemented in HMWSoln, DebyeHuckel, IonsFromNeutralVPSSTP, WaterSSTP, MixtureFugacityTP, VPStandardStateTP, and RedlichKwongMFTP.
Definition at line 570 of file Phase.h.
References Phase::m_temp.
Referenced by ChemEquil::equilibrate(), ReactingSurf1D::eval(), TransportFactory::fitProperties(), WaterSSTP::initThermoXML(), Phase::restoreState(), StFlow::setGas(), StFlow::setGasAtMidpoint(), ThermoPhase::setState_HPorUV(), PureFluidPhase::setState_Psat(), ThermoPhase::setState_SPorSV(), SingleSpeciesTP::setState_SV(), Phase::setState_TNX(), VPStandardStateTP::setState_TP(), IdealMolalSoln::setState_TP(), MixtureFugacityTP::setState_TP(), GibbsExcessVPSSTP::setState_TP(), DebyeHuckel::setState_TP(), ThermoPhase::setState_TP(), HMWSoln::setState_TP(), SingleSpeciesTP::setState_TPX(), ThermoPhase::setState_TPX(), SingleSpeciesTP::setState_TPY(), ThermoPhase::setState_TPY(), Phase::setState_TR(), MixtureFugacityTP::setState_TR(), Phase::setState_TRX(), Phase::setState_TRY(), PureFluidPhase::setState_Tsat(), Phase::setState_TX(), Phase::setState_TY(), SingleSpeciesTP::setState_UV(), SurfPhase::setStateFromXML(), ThermoPhase::setStateFromXML(), RedlichKwongMFTP::setTemperature(), PDSS_IonsFromNeutral::setTemperature(), WaterSSTP::setTemperature(), ChemEquil::setToEquilState(), and Reactor::updateState().
doublereal mean_X (const doublereal *const Q) const inherited
Evaluate the mole-fraction-weighted mean of an array Q.
\[ \sum_k X_k Q_k. \]
Q should contain pure-species molar property values.
Parameters
[in] Q Array of length m_kk that is to be averaged.
Returns
mole-fraction-weighted mean of Q
Definition at line 658 of file Phase.cpp.
References Phase::m_mmw, and Phase::m_ym.
Referenced by IdealSolnGasVPSS::cp_mole(), ConstDensityThermo::cp_mole(), RedlichKwongMFTP::cp_mole(), IonsFromNeutralVPSSTP::cp_mole(), IdealSolidSolnPhase::cp_mole(), IdealMolalSoln::cp_mole(), LatticePhase::cp_mole(), IdealGasPhase::cp_mole(), DebyeHuckel::cp_mole(), HMWSoln::cp_mole(), IonsFromNeutralVPSSTP::cv_mole(), IdealSolnGasVPSS::enthalpy_mole(), ConstDensityThermo::enthalpy_mole(), RedlichKwongMFTP::enthalpy_mole(), IdealSolidSolnPhase::enthalpy_mole(), IonsFromNeutralVPSSTP::enthalpy_mole(), IdealMolalSoln::enthalpy_mole(), SurfPhase::enthalpy_mole(), LatticePhase::enthalpy_mole(), IdealGasPhase::enthalpy_mole(), DebyeHuckel::enthalpy_mole(), HMWSoln::enthalpy_mole(), IdealSolnGasVPSS::entropy_mole(), ConstDensityThermo::entropy_mole(), RedlichKwongMFTP::entropy_mole(), IonsFromNeutralVPSSTP::entropy_mole(), IdealSolidSolnPhase::entropy_mole(), IdealMolalSoln::entropy_mole(), LatticePhase::entropy_mole(), IdealGasPhase::entropy_mole(), DebyeHuckel::entropy_mole(), HMWSoln::entropy_mole(), IonsFromNeutralVPSSTP::gibbs_mole(), IdealSolidSolnPhase::gibbs_mole(), IdealMolalSoln::gibbs_mole(), DebyeHuckel::gibbs_mole(), HMWSoln::gibbs_mole(), ConstDensityThermo::intEnergy_mole(), IdealSolidSolnPhase::intEnergy_mole(), IdealMolalSoln::intEnergy_mole(), LatticePhase::intEnergy_mole(), IdealGasPhase::intEnergy_mole(), and HMWSoln::relative_enthalpy().
doublereal mean_Y (const doublereal *const Q) const inherited
Evaluate the mass-fraction-weighted mean of an array Q.
\[ \sum_k Y_k Q_k \]
Parameters
[in] Q Array of species property values in mass units.
Returns
The mass-fraction-weighted mean of Q.
Definition at line 663 of file Phase.cpp.
References Cantera::dot(), and Phase::m_y.
doublereal meanMolecularWeight () const inline inherited
The mean molecular weight. Units: (kg/kmol)
Definition at line 592 of file Phase.h.
References Phase::m_mmw.
Referenced by IdealSolnGasVPSS::calcDensity(), GibbsExcessVPSSTP::calcDensity(), IdealMolalSoln::calcDensity(), LatticePhase::calcDensity(), DebyeHuckel::calcDensity(), HMWSoln::calcDensity(), MixtureFugacityTP::calculatePsat(), ThermoPhase::cp_mass(), RedlichKwongMFTP::critDensity(), ThermoPhase::cv_mass(), RedlichKwongMFTP::densityCalc(), MixtureFugacityTP::densityCalc(), RedlichKwongMFTP::densSpinodalGas(), RedlichKwongMFTP::densSpinodalLiquid(), ThermoPhase::enthalpy_mass(), ThermoPhase::entropy_mass(), IdealSolidSolnPhase::getActivityConcentrations(), GasTransport::getMixDiffCoeffs(), AqueousTransport::getMixDiffCoeffs(), GasTransport::getMixDiffCoeffsMass(), MultiTransport::getMultiDiffCoeffs(), WaterSSTP::getStandardVolumes_ref(), ThermoPhase::gibbs_mass(), RedlichKwongMFTP::hresid(), ThermoPhase::intEnergy_mass(), Phase::molarDensity(), MixtureFugacityTP::phaseState(), RedlichKwongMFTP::pressure(), PseudoBinaryVPSSTP::report(), MolarityIonicVPSSTP::report(), PureFluidPhase::report(), MolalityVPSSTP::report(), ThermoPhase::report(), PureFluidPhase::reportCSV(), MolalityVPSSTP::reportCSV(), ThermoPhase::reportCSV(), Phase::setMolarDensity(), IdealGasPhase::setPressure(), RedlichKwongMFTP::sresid(), SimpleTransport::update_C(), LiquidTransport::update_C(), StFlow::updateThermo(), StFlow::updateTransport(), and MixtureFugacityTP::z().
doublereal sum_xlogx () const inherited
Evaluate \(\sum_k X_k \log X_k \).
Returns
The indicated sum. Dimensionless.
Definition at line 668 of file Phase.cpp.
References Phase::m_mmw, Phase::m_ym, and Cantera::sum_xlogx().
Referenced by IdealSolnGasVPSS::entropy_mole(), ConstDensityThermo::entropy_mole(), RedlichKwongMFTP::entropy_mole(), IdealSolidSolnPhase::entropy_mole(), LatticePhase::entropy_mole(), IdealGasPhase::entropy_mole(), and IdealSolidSolnPhase::gibbs_mole().
doublereal sum_xlogQ (doublereal *const Q) const inherited
Evaluate \(\sum_k X_k \log Q_k \).
Parameters
Q Vector of length m_kk to take the log average of
Returns
The indicated sum.
Definition at line 673 of file Phase.cpp.
References Phase::m_mmw, Phase::m_ym, and Cantera::sum_xlogQ().
void addElement (const std::string & symbol, doublereal weight = -12345.0) inherited
Add an element.
Parameters
symbol Atomic symbol std::string.
weight Atomic mass in amu.
Definition at line 678 of file Phase.cpp.
References CT_ELEM_TYPE_ABSPOS, CT_ELEM_TYPE_ELECTRONCHARGE, Cantera::LookupWtElements(), Phase::m_atomicWeights, Phase::m_elem_type, Phase::m_elementNames, Phase::m_elementsFrozen, and Phase::m_mm.
Referenced by Phase::addElement().
void addElement (const XML_Node & e) inherited
Add an element from an XML specification.
Parameters
e Reference to the XML_Node where the element is described.
Definition at line 701 of file Phase.cpp.
References Phase::addElement().
void addUniqueElement (const std::string & symbol, doublereal weight = -12345.0, int atomicNumber = 0, doublereal entropy298 = ENTROPY298_UNKNOWN, int elem_type = CT_ELEM_TYPE_ABSPOS) inherited
Add an element, checking for uniqueness The uniqueness is checked by comparing the string symbol.
If not unique, nothing is done.
Parameters
symbol String symbol of the element
weight Atomic weight of the element (kg kmol-1).
atomicNumber Atomic number of the element (unitless)
entropy298 Entropy of the element at 298 K and 1 bar in its most stable form. The default is the value ENTROPY298_UNKNOWN, which is interpreted as an unknown, and if used will cause Cantera to throw an error.
elem_type Specifies the type of the element constraint equation. This defaults to CT_ELEM_TYPE_ABSPOS, i.e., an element.
Definition at line 708 of file Phase.cpp.
References CT_ELEM_TYPE_ELECTRONCHARGE, Cantera::LookupWtElements(), Phase::m_atomicNumbers, Phase::m_atomicWeights, Phase::m_elem_type, Phase::m_elementNames, Phase::m_elementsFrozen, Phase::m_entropy298, and Phase::m_mm.
Referenced by Phase::addElementsFromXML(), Phase::addUniqueElement(), Phase::addUniqueElementAfterFreeze(), and FixedChemPotSSTP::FixedChemPotSSTP().
void addUniqueElement (const XML_Node & e) inherited
Add an element, checking for uniqueness The uniqueness is checked by comparing the string symbol.
If not unique, nothing is done.
Parameters
e Reference to the XML_Node where the element is described.
Definition at line 755 of file Phase.cpp.
References Phase::addUniqueElement(), Cantera::atofCheck(), XML_Node::child(), ENTROPY298_UNKNOWN, XML_Node::hasAttrib(), XML_Node::hasChild(), and Cantera::stripws().
void addElementsFromXML (const XML_Node & phase) inherited
Add all elements referenced in an XML_Node tree.
Parameters
phase Reference to the root XML_Node of a phase
Definition at line 780 of file Phase.cpp.
References Phase::addUniqueElement(), XML_Node::child(), XML_Node::findByAttr(), Cantera::get_XML_File(), ctml::getStringArray(), XML_Node::hasAttrib(), XML_Node::hasChild(), and XML_Node::root().
Referenced by Cantera::importPhase().
void freezeElements () inherited
Prohibit addition of more elements, and prepare to add species.
Definition at line 831 of file Phase.cpp.
References Phase::m_elementsFrozen.
Referenced by FixedChemPotSSTP::FixedChemPotSSTP().
bool elementsFrozen () inherited
True if freezeElements has been called.
Definition at line 836 of file Phase.cpp.
References Phase::m_elementsFrozen.
size_t addUniqueElementAfterFreeze (const std::string & symbol, doublereal weight, int atomicNumber, doublereal entropy298 = ENTROPY298_UNKNOWN, int elem_type = CT_ELEM_TYPE_ABSPOS) inherited
Add an element after elements have been frozen, checking for uniqueness The uniqueness is checked by comparing the string symbol.
If not unique, nothing is done.
Parameters
symbol String symbol of the element
weight Atomic weight of the element (kg kmol-1).
atomicNumber Atomic number of the element (unitless)
entropy298 Entropy of the element at 298 K and 1 bar in its most stable form. The default is the value ENTROPY298_UNKNOWN, which if used will cause Cantera to throw an error.
elem_type Specifies the type of the element constraint equation. This defaults to CT_ELEM_TYPE_ABSPOS, i.e., an element.
Definition at line 841 of file Phase.cpp.
References Phase::addUniqueElement(), Phase::elementIndex(), Phase::m_elementsFrozen, Phase::m_kk, Phase::m_mm, Phase::m_speciesComp, and Cantera::npos.
Referenced by LatticeSolidPhase::installSlavePhases().
void addUniqueSpecies (const std::string & name, const doublereal * comp, doublereal charge = 0.0, doublereal size = 1.0) inherited
Add a species to the phase, checking for uniqueness of the name This routine checks for uniqueness of the string name.
It only adds the species if it is unique.
Parameters
name String name of the species
comp Array containing the elemental composition of the species.
charge Charge of the species. Defaults to zero.
size Size of the species (meters). Defaults to 1 meter.
Definition at line 919 of file Phase.cpp.
References Phase::m_kk, Phase::m_mm, Phase::m_speciesCharge, Phase::m_speciesComp, Phase::m_speciesNames, and Phase::m_speciesSize.
Referenced by FixedChemPotSSTP::FixedChemPotSSTP(), LatticeSolidPhase::installSlavePhases(), and Cantera::installSpecies().
void freezeSpecies () virtual inherited
Call when finished adding species.
Prepare to use them for calculation of mixture properties.
Definition at line 952 of file Phase.cpp.
References Phase::init(), Phase::m_speciesFrozen, and Phase::molecularWeights().
Referenced by FixedChemPotSSTP::FixedChemPotSSTP(), and Cantera::importPhase().
bool speciesFrozen () inline inherited
True if freezeSpecies has been called.
Definition at line 694 of file Phase.h.
References Phase::m_speciesFrozen.
int stateMFNumber () const inline inherited
Return the State Mole Fraction Number.
Definition at line 701 of file Phase.h.
References Phase::m_stateNum.
Referenced by SimpleTransport::update_C(), and LiquidTransport::update_C().
void stateMFChangeCalc (bool forceChange = false) inline inherited
Every time the mole fractions have changed, this routine will increment the stateMFNumber.
@param forceChange If this is true then the stateMFNumber always
changes. This defaults to false.
Deprecated:
Definition at line 115 of file Phase.cpp.
References Phase::m_stateNum.
Referenced by Phase::setConcentrations(), Phase::setMassFractions(), Phase::setMassFractions_NoNorm(), Phase::setMoleFractions(), and Phase::setMoleFractions_NoNorm().
void init (const vector_fp & mw) protected inherited
Initialize. Make a local copy of the vector of molecular weights, and resize the composition arrays to the appropriate size.
Parameters
mw Vector of molecular weights of the species.
Definition at line 958 of file Phase.cpp.
References Cantera::int2str(), Phase::m_kk, Phase::m_mmw, Phase::m_molwts, Phase::m_rmolwts, Phase::m_y, Phase::m_ym, and Cantera::Tiny.
Referenced by Phase::freezeSpecies().
void setMolecularWeight (const int k, const double mw) inline protected inherited
Set the molecular weight of a single species to a given value.
Parameters
k id of the species
mw Molecular Weight (kg kmol-1)
Definition at line 722 of file Phase.h.
References Phase::m_molwts, and Phase::m_rmolwts.
Referenced by PureFluidPhase::initThermo(), and WaterSSTP::initThermoXML().
Member Data Documentation
size_t m_mm protected
Number of Elements in the phase.
This member is defined here, from a call to the Elements ojbect, for speed.
Definition at line 885 of file IdealGasPhase.h.
Referenced by IdealGasPhase::initThermo(), and IdealGasPhase::operator=().
doublereal m_tmin protected
Minimum temperature for valid species standard state thermo props.
This is the minimum temperature at which all species have valid standard state thermo props defined.
Definition at line 892 of file IdealGasPhase.h.
Referenced by IdealGasPhase::initThermo(), and IdealGasPhase::operator=().
doublereal m_tmax protected
Maximum temperature for valid species standard state thermo props.
This is the maximum temperature at which all species have valid standard state thermo props defined.
Definition at line 899 of file IdealGasPhase.h.
Referenced by IdealGasPhase::initThermo(), and IdealGasPhase::operator=().
doublereal m_p0 protected
Reference state pressure.
Value of the reference state pressure in Pascals. All species must have the same reference state pressure.
Definition at line 906 of file IdealGasPhase.h.
Referenced by IdealGasPhase::_updateThermo(), IdealGasPhase::getStandardVolumes_ref(), IdealGasPhase::initThermo(), IdealGasPhase::operator=(), and IdealGasPhase::setToEquilState().
doublereal m_tlast mutable protected
last value of the temperature processed by reference state
Definition at line 909 of file IdealGasPhase.h.
Referenced by IdealGasPhase::_updateThermo(), and IdealGasPhase::operator=().
doublereal m_logc0 mutable protected
Temporary storage for log of p/rt.
Definition at line 912 of file IdealGasPhase.h.
Referenced by IdealGasPhase::_updateThermo(), and IdealGasPhase::operator=().
vector_fp m_h0_RT mutable protected
Temporary storage for dimensionless reference state enthalpies.
Definition at line 915 of file IdealGasPhase.h.
Referenced by IdealGasPhase::_updateThermo(), IdealGasPhase::enthalpy_RT_ref(), IdealGasPhase::initThermo(), and IdealGasPhase::operator=().
vector_fp m_cp0_R mutable protected
Temporary storage for dimensionless reference state heat capacities.
Definition at line 918 of file IdealGasPhase.h.
Referenced by IdealGasPhase::_updateThermo(), IdealGasPhase::cp_R_ref(), IdealGasPhase::initThermo(), and IdealGasPhase::operator=().
vector_fp m_g0_RT mutable protected
Temporary storage for dimensionless reference state gibbs energies.
Definition at line 921 of file IdealGasPhase.h.
Referenced by IdealGasPhase::_updateThermo(), IdealGasPhase::expGibbs_RT_ref(), IdealGasPhase::gibbs_RT_ref(), IdealGasPhase::initThermo(), and IdealGasPhase::operator=().
vector_fp m_s0_R mutable protected
Temporary storage for dimensionless reference state entropies.
Definition at line 924 of file IdealGasPhase.h.
Referenced by IdealGasPhase::_updateThermo(), IdealGasPhase::entropy_R_ref(), IdealGasPhase::initThermo(), and IdealGasPhase::operator=().
vector_fp m_expg0_RT mutable protected
currently unsed
Deprecated:
Definition at line 930 of file IdealGasPhase.h.
Referenced by IdealGasPhase::expGibbs_RT_ref(), IdealGasPhase::initThermo(), and IdealGasPhase::operator=().
vector_fp m_pe mutable protected
Currently unused.
Definition at line 936 of file IdealGasPhase.h.
Referenced by IdealGasPhase::initThermo(), and IdealGasPhase::operator=().
vector_fp m_pp mutable protected
Temporary array containing internally calculated partial pressures.
Definition at line 939 of file IdealGasPhase.h.
Referenced by IdealGasPhase::initThermo(), IdealGasPhase::operator=(), and IdealGasPhase::setToEquilState().
SpeciesThermo* m_spthermo protected inherited
Pointer to the calculation manager for species reference-state thermodynamic properties.
This class is called when the reference-state thermodynamic properties of all the species in the phase needs to be evaluated.
Definition at line 1611 of file ThermoPhase.h.
Referenced by MixtureFugacityTP::_updateReferenceStateThermo(), ConstDensityThermo::_updateThermo(), SurfPhase::_updateThermo(), SingleSpeciesTP::_updateThermo(), IdealGasPhase::_updateThermo(), LatticePhase::_updateThermo(), IdealSolidSolnPhase::_updateThermo(), ConstDensityThermo::enthalpy_mole(), LatticePhase::enthalpy_mole(), RedlichKwongMFTP::entropy_mole(), IdealGasPhase::entropy_mole(), FixedChemPotSSTP::FixedChemPotSSTP(), ConstDensityThermo::getChemPotentials(), MixtureFugacityTP::getEntropy_R(), IdealGasPhase::getEntropy_R(), PureFluidPhase::getEntropy_R_ref(), MixtureFugacityTP::getGibbs_RT(), IdealGasPhase::getGibbs_RT(), PureFluidPhase::getGibbs_RT_ref(), IdealGasPhase::getPartialMolarEntropies(), MixtureFugacityTP::getPureGibbs(), IdealGasPhase::getPureGibbs(), MixtureFugacityTP::getStandardChemPotentials(), IdealGasPhase::getStandardChemPotentials(), IdealSolidSolnPhase::initLengths(), ConstDensityThermo::initThermo(), StoichSubstance::initThermo(), StoichSubstanceSSTP::initThermo(), PureFluidPhase::initThermo(), SingleSpeciesTP::initThermo(), IdealGasPhase::initThermo(), LatticePhase::initThermo(), WaterSSTP::initThermoXML(), LatticeSolidPhase::installSlavePhases(), ConstDensityThermo::intEnergy_mole(), LatticePhase::intEnergy_mole(), ThermoPhase::maxTemp(), ThermoPhase::minTemp(), VPStandardStateTP::operator=(), ThermoPhase::operator=(), ThermoPhase::refPressure(), ThermoPhase::setSpeciesThermo(), LatticeSolidPhase::speciesThermo(), ThermoPhase::speciesThermo(), and ThermoPhase::~ThermoPhase().
std::vector<const XML_Node*> m_speciesData protected inherited
Vector of pointers to the species databases.
This is used to access data needed to construct the transport manager and other properties later in the initialization process. We create a copy of the XML_Node data read in here. Therefore, we own this data.
Definition at line 1621 of file ThermoPhase.h.
Referenced by LatticeSolidPhase::installSlavePhases(), ThermoPhase::operator=(), ThermoPhase::saveSpeciesData(), ThermoPhase::speciesData(), and ThermoPhase::~ThermoPhase().
doublereal m_phi protected inherited
Stored value of the electric potential for this phase.
Units are Volts
Definition at line 1627 of file ThermoPhase.h.
Referenced by ThermoPhase::electricPotential(), IdealMolalSoln::electricPotential(), ThermoPhase::operator=(), and ThermoPhase::setElectricPotential().
vector_fp m_lambdaRRT protected inherited
Vector of element potentials.
-> length equal to number of elements
Definition at line 1631 of file ThermoPhase.h.
Referenced by ThermoPhase::getElementPotentials(), ThermoPhase::operator=(), and ThermoPhase::setElementPotentials().
bool m_hasElementPotentials protected inherited
Boolean indicating whether there is a valid set of saved element potentials for this phase.
Definition at line 1635 of file ThermoPhase.h.
Referenced by ThermoPhase::getElementPotentials(), ThermoPhase::operator=(), and ThermoPhase::setElementPotentials().
bool m_chargeNeutralityNecessary protected inherited
Boolean indicating whether a charge neutrality condition is a necessity.
Note, the charge neutrality condition is not a necessity for ideal gas phases. There may be a net charge in those phases, because the NASA polynomials for ionized species in Ideal gases take this condition into account. However, liquid phases usually require charge neutrality in order for their derived thermodynamics to be valid.
Definition at line 1645 of file ThermoPhase.h.
Referenced by ThermoPhase::chargeNeutralityNecessary(), MolalityVPSSTP::MolalityVPSSTP(), and ThermoPhase::operator=().
int m_ssConvention protected inherited
Contains the standard state convention.
Definition at line 1648 of file ThermoPhase.h.
Referenced by ThermoPhase::operator=(), and ThermoPhase::standardStateConvention().
std::vector<doublereal> xMol_Ref protected inherited
Reference Mole Fraction Composition.
Occasionally, the need arises to find a safe mole fraction vector to initialize the object to. This contains such a vector. The algorithm will pick up the mole fraction vector that is applied from the state xml file in the input file
Definition at line 1657 of file ThermoPhase.h.
Referenced by ThermoPhase::getReferenceComposition(), ThermoPhase::initThermo(), and ThermoPhase::setReferenceComposition().
size_t m_kk protected inherited
Number of species in the phase.
Definition at line 727 of file Phase.h.
Referenced by DebyeHuckel::_lnactivityWaterHelgesonFixedForm(), MixtureFugacityTP::_updateReferenceStateThermo(), ConstDensityThermo::_updateThermo(), SurfPhase::_updateThermo(), IdealGasPhase::_updateThermo(), LatticePhase::_updateThermo(), IdealSolidSolnPhase::_updateThermo(), Phase::addUniqueElementAfterFreeze(), Phase::addUniqueSpecies(), HMWSoln::applyphScale(), RedlichKwongMFTP::applyStandardMixingRules(), GibbsExcessVPSSTP::calcDensity(), IdealMolalSoln::calcDensity(), DebyeHuckel::calcDensity(), HMWSoln::calcDensity(), IonsFromNeutralVPSSTP::calcIonMoleFractions(), MolalityVPSSTP::calcMolalities(), HMWSoln::calcMolalitiesCropped(), IonsFromNeutralVPSSTP::calcNeutralMoleculeMoleFractions(), PseudoBinaryVPSSTP::calcPseudoBinaryMoleFractions(), MolarityIonicVPSSTP::calcPseudoBinaryMoleFractions(), RedlichKwongMFTP::calculateAB(), GibbsExcessVPSSTP::checkMFSum(), Phase::checkSpeciesArraySize(), Phase::checkSpeciesIndex(), HMWSoln::counterIJ_setup(), RedlichKwongMFTP::critDensity(), RedlichKwongMFTP::critPressure(), RedlichKwongMFTP::critTemperature(), ConstDensityThermo::expGibbs_RT(), IdealGasPhase::expGibbs_RT_ref(), IdealSolidSolnPhase::expGibbs_RT_ref(), MolalityVPSSTP::findCLMIndex(), GibbsExcessVPSSTP::getActivities(), IdealMolalSoln::getActivities(), DebyeHuckel::getActivities(), HMWSoln::getActivities(), ConstDensityThermo::getActivityCoefficients(), SingleSpeciesTP::getActivityCoefficients(), IdealSolnGasVPSS::getActivityCoefficients(), IonsFromNeutralVPSSTP::getActivityCoefficients(), GibbsExcessVPSSTP::getActivityCoefficients(), RedlichKwongMFTP::getActivityCoefficients(), LatticeSolidPhase::getActivityCoefficients(), MixedSolventElectrolyte::getActivityCoefficients(), PhaseCombo_Interaction::getActivityCoefficients(), IdealSolidSolnPhase::getActivityCoefficients(), ThermoPhase::getActivityCoefficients(), MolalityVPSSTP::getActivityCoefficients(), IdealGasPhase::getActivityCoefficients(), LatticePhase::getActivityCoefficients(), IdealSolnGasVPSS::getActivityConcentrations(), RedlichKwongMFTP::getActivityConcentrations(), IdealMolalSoln::getActivityConcentrations(), IdealSolidSolnPhase::getActivityConcentrations(), DebyeHuckel::getActivityConcentrations(), HMWSoln::getActivityConcentrations(), ConstDensityThermo::getChemPotentials(), SurfPhase::getChemPotentials(), MolarityIonicVPSSTP::getChemPotentials(), IdealSolnGasVPSS::getChemPotentials(), RedlichKwongMFTP::getChemPotentials(), RedlichKisterVPSSTP::getChemPotentials(), MargulesVPSSTP::getChemPotentials(), MixedSolventElectrolyte::getChemPotentials(), PhaseCombo_Interaction::getChemPotentials(), IdealSolidSolnPhase::getChemPotentials(), IdealMolalSoln::getChemPotentials(), IdealGasPhase::getChemPotentials(), LatticePhase::getChemPotentials(), DebyeHuckel::getChemPotentials(), HMWSoln::getChemPotentials(), VPStandardStateTP::getChemPotentials_RT(), MixtureFugacityTP::getChemPotentials_RT(), IdealSolnGasVPSS::getChemPotentials_RT(), RedlichKwongMFTP::getChemPotentials_RT(), IdealSolidSolnPhase::getChemPotentials_RT(), SurfPhase::getCoverages(), IdealSolidSolnPhase::getCp_R_ref(), RedlichKisterVPSSTP::getd2lnActCoeffdT2(), MargulesVPSSTP::getd2lnActCoeffdT2(), MixedSolventElectrolyte::getd2lnActCoeffdT2(), PhaseCombo_Interaction::getd2lnActCoeffdT2(), IonsFromNeutralVPSSTP::getdlnActCoeffdlnN(), PhaseCombo_Interaction::getdlnActCoeffdlnN(), RedlichKisterVPSSTP::getdlnActCoeffdlnN(), MargulesVPSSTP::getdlnActCoeffdlnN(), MixedSolventElectrolyte::getdlnActCoeffdlnN(), ThermoPhase::getdlnActCoeffdlnN(), IonsFromNeutralVPSSTP::getdlnActCoeffdlnN_diag(), PhaseCombo_Interaction::getdlnActCoeffdlnN_diag(), RedlichKisterVPSSTP::getdlnActCoeffdlnN_diag(), MargulesVPSSTP::getdlnActCoeffdlnN_diag(), MixedSolventElectrolyte::getdlnActCoeffdlnN_diag(), IonsFromNeutralVPSSTP::getdlnActCoeffdlnX_diag(), PhaseCombo_Interaction::getdlnActCoeffdlnX_diag(), RedlichKisterVPSSTP::getdlnActCoeffdlnX_diag(), MargulesVPSSTP::getdlnActCoeffdlnX_diag(), MixedSolventElectrolyte::getdlnActCoeffdlnX_diag(), IonsFromNeutralVPSSTP::getdlnActCoeffds(), PhaseCombo_Interaction::getdlnActCoeffds(), RedlichKisterVPSSTP::getdlnActCoeffds(), MargulesVPSSTP::getdlnActCoeffds(), MixedSolventElectrolyte::getdlnActCoeffds(), RedlichKisterVPSSTP::getdlnActCoeffdT(), MargulesVPSSTP::getdlnActCoeffdT(), MixedSolventElectrolyte::getdlnActCoeffdT(), PhaseCombo_Interaction::getdlnActCoeffdT(), PureFluidPhase::getElectrochemPotentials(), PseudoBinaryVPSSTP::getElectrochemPotentials(), MolarityIonicVPSSTP::getElectrochemPotentials(), GibbsExcessVPSSTP::getElectrochemPotentials(), RedlichKisterVPSSTP::getElectrochemPotentials(), MargulesVPSSTP::getElectrochemPotentials(), ThermoPhase::getElectrochemPotentials(), MixedSolventElectrolyte::getElectrochemPotentials(), MolalityVPSSTP::getElectrochemPotentials(), PhaseCombo_Interaction::getElectrochemPotentials(), IdealSolidSolnPhase::getEnthalpy_RT(), LatticePhase::getEnthalpy_RT(), IdealSolidSolnPhase::getEnthalpy_RT_ref(), MixtureFugacityTP::getEntropy_R(), IdealGasPhase::getEntropy_R(), IdealSolidSolnPhase::getEntropy_R_ref(), WaterSSTP::getGibbs_ref(), LatticeSolidPhase::getGibbs_ref(), IdealSolidSolnPhase::getGibbs_ref(), LatticePhase::getGibbs_ref(), MixtureFugacityTP::getGibbs_RT(), IdealGasPhase::getGibbs_RT(), IdealSolidSolnPhase::getGibbs_RT(), LatticePhase::getGibbs_RT(), IdealSolidSolnPhase::getGibbs_RT_ref(), LatticePhase::getGibbs_RT_ref(), MixtureFugacityTP::getIntEnergy_RT(), IdealGasPhase::getIntEnergy_RT(), IdealSolidSolnPhase::getIntEnergy_RT(), IdealGasPhase::getIntEnergy_RT_ref(), IdealSolidSolnPhase::getIntEnergy_RT_ref(), MolarityIonicVPSSTP::getLnActivityCoefficients(), RedlichKisterVPSSTP::getLnActivityCoefficients(), MargulesVPSSTP::getLnActivityCoefficients(), ThermoPhase::getLnActivityCoefficients(), MolalityVPSSTP::getMolalities(), IdealMolalSoln::getMolalityActivityCoefficients(), DebyeHuckel::getMolalityActivityCoefficients(), IonsFromNeutralVPSSTP::getNeutralMoleculeMoleGrads(), SurfPhase::getPartialMolarCp(), IdealSolnGasVPSS::getPartialMolarCp(), MolarityIonicVPSSTP::getPartialMolarCp(), RedlichKwongMFTP::getPartialMolarCp(), RedlichKisterVPSSTP::getPartialMolarCp(), MargulesVPSSTP::getPartialMolarCp(), MixedSolventElectrolyte::getPartialMolarCp(), PhaseCombo_Interaction::getPartialMolarCp(), IdealSolidSolnPhase::getPartialMolarCp(), IdealMolalSoln::getPartialMolarCp(), LatticePhase::getPartialMolarCp(), DebyeHuckel::getPartialMolarCp(), HMWSoln::getPartialMolarCp(), SurfPhase::getPartialMolarEnthalpies(), IdealSolnGasVPSS::getPartialMolarEnthalpies(), MolarityIonicVPSSTP::getPartialMolarEnthalpies(), IonsFromNeutralVPSSTP::getPartialMolarEnthalpies(), RedlichKwongMFTP::getPartialMolarEnthalpies(), RedlichKisterVPSSTP::getPartialMolarEnthalpies(), MargulesVPSSTP::getPartialMolarEnthalpies(), MixedSolventElectrolyte::getPartialMolarEnthalpies(), PhaseCombo_Interaction::getPartialMolarEnthalpies(), IdealMolalSoln::getPartialMolarEnthalpies(), DebyeHuckel::getPartialMolarEnthalpies(), HMWSoln::getPartialMolarEnthalpies(), SurfPhase::getPartialMolarEntropies(), IdealSolnGasVPSS::getPartialMolarEntropies(), MolarityIonicVPSSTP::getPartialMolarEntropies(), IonsFromNeutralVPSSTP::getPartialMolarEntropies(), RedlichKwongMFTP::getPartialMolarEntropies(), RedlichKisterVPSSTP::getPartialMolarEntropies(), MargulesVPSSTP::getPartialMolarEntropies(), MixedSolventElectrolyte::getPartialMolarEntropies(), PhaseCombo_Interaction::getPartialMolarEntropies(), IdealGasPhase::getPartialMolarEntropies(), IdealMolalSoln::getPartialMolarEntropies(), IdealSolidSolnPhase::getPartialMolarEntropies(), LatticePhase::getPartialMolarEntropies(), DebyeHuckel::getPartialMolarEntropies(), HMWSoln::getPartialMolarEntropies(), IdealSolnGasVPSS::getPartialMolarIntEnergies(), RedlichKwongMFTP::getPartialMolarIntEnergies(), IdealGasPhase::getPartialMolarIntEnergies(), MolarityIonicVPSSTP::getPartialMolarVolumes(), RedlichKwongMFTP::getPartialMolarVolumes(), RedlichKisterVPSSTP::getPartialMolarVolumes(), MargulesVPSSTP::getPartialMolarVolumes(), MixedSolventElectrolyte::getPartialMolarVolumes(), IdealGasPhase::getPartialMolarVolumes(), PhaseCombo_Interaction::getPartialMolarVolumes(), DebyeHuckel::getPartialMolarVolumes(), HMWSoln::getPartialMolarVolumes(), MixtureFugacityTP::getPureGibbs(), IdealGasPhase::getPureGibbs(), LatticePhase::getPureGibbs(), IdealSolidSolnPhase::getPureGibbs(), ThermoPhase::getReferenceComposition(), VPStandardStateTP::getStandardChemPotentials(), MixtureFugacityTP::getStandardChemPotentials(), IdealGasPhase::getStandardChemPotentials(), MixtureFugacityTP::getStandardVolumes(), SurfPhase::getStandardVolumes(), IdealGasPhase::getStandardVolumes(), MixtureFugacityTP::getStandardVolumes_ref(), IdealGasPhase::getStandardVolumes_ref(), HMWSoln::getUnscaledMolalityActivityCoefficients(), HMWSoln::HMWSoln(), Phase::init(), PseudoBinaryVPSSTP::initLengths(), IdealSolnGasVPSS::initLengths(), MolarityIonicVPSSTP::initLengths(), GibbsExcessVPSSTP::initLengths(), RedlichKwongMFTP::initLengths(), VPStandardStateTP::initLengths(), LatticeSolidPhase::initLengths(), IonsFromNeutralVPSSTP::initLengths(), MixtureFugacityTP::initLengths(), PhaseCombo_Interaction::initLengths(), RedlichKisterVPSSTP::initLengths(), MargulesVPSSTP::initLengths(), MixedSolventElectrolyte::initLengths(), MolalityVPSSTP::initLengths(), IdealMolalSoln::initLengths(), IdealSolidSolnPhase::initLengths(), DebyeHuckel::initLengths(), HMWSoln::initLengths(), ConstDensityThermo::initThermo(), SurfPhase::initThermo(), MolarityIonicVPSSTP::initThermo(), StoichSubstanceSSTP::initThermo(), VPStandardStateTP::initThermo(), LatticeSolidPhase::initThermo(), SingleSpeciesTP::initThermo(), IdealGasPhase::initThermo(), LatticePhase::initThermo(), ThermoPhase::initThermo(), RedlichKwongMFTP::initThermoXML(), VPStandardStateTP::initThermoXML(), IonsFromNeutralVPSSTP::initThermoXML(), IdealMolalSoln::initThermoXML(), LatticePhase::initThermoXML(), IdealSolidSolnPhase::initThermoXML(), DebyeHuckel::initThermoXML(), IdealSolidSolnPhase::logStandardConc(), Phase::nSpecies(), VPStandardStateTP::operator=(), Phase::operator=(), ThermoPhase::operator=(), MolalityVPSSTP::osmoticCoefficient(), HMWSoln::printCoeffs(), RedlichKwongMFTP::readXMLCrossFluid(), RedlichKwongMFTP::readXMLPureFluid(), IdealSolidSolnPhase::referenceConcentration(), HMWSoln::relative_enthalpy(), HMWSoln::relative_molal_enthalpy(), DebyeHuckel::s_update_d2lnMolalityActCoeff_dT2(), HMWSoln::s_update_d2lnMolalityActCoeff_dT2(), IonsFromNeutralVPSSTP::s_update_dlnActCoeff_dlnN(), PhaseCombo_Interaction::s_update_dlnActCoeff_dlnN(), MargulesVPSSTP::s_update_dlnActCoeff_dlnN(), MixedSolventElectrolyte::s_update_dlnActCoeff_dlnN(), IonsFromNeutralVPSSTP::s_update_dlnActCoeff_dlnN_diag(), PhaseCombo_Interaction::s_update_dlnActCoeff_dlnN_diag(), MargulesVPSSTP::s_update_dlnActCoeff_dlnN_diag(), MixedSolventElectrolyte::s_update_dlnActCoeff_dlnN_diag(), IonsFromNeutralVPSSTP::s_update_dlnActCoeff_dlnX_diag(), PhaseCombo_Interaction::s_update_dlnActCoeff_dlnX_diag(), MargulesVPSSTP::s_update_dlnActCoeff_dlnX_diag(), MixedSolventElectrolyte::s_update_dlnActCoeff_dlnX_diag(), PhaseCombo_Interaction::s_update_dlnActCoeff_dT(), RedlichKisterVPSSTP::s_update_dlnActCoeff_dT(), MargulesVPSSTP::s_update_dlnActCoeff_dT(), MixedSolventElectrolyte::s_update_dlnActCoeff_dT(), RedlichKisterVPSSTP::s_update_dlnActCoeff_dX_(), IonsFromNeutralVPSSTP::s_update_dlnActCoeffdT(), DebyeHuckel::s_update_dlnMolalityActCoeff_dP(), HMWSoln::s_update_dlnMolalityActCoeff_dP(), DebyeHuckel::s_update_dlnMolalityActCoeff_dT(), HMWSoln::s_update_dlnMolalityActCoeff_dT(), MolarityIonicVPSSTP::s_update_lnActCoeff(), IonsFromNeutralVPSSTP::s_update_lnActCoeff(), PhaseCombo_Interaction::s_update_lnActCoeff(), RedlichKisterVPSSTP::s_update_lnActCoeff(), MargulesVPSSTP::s_update_lnActCoeff(), MixedSolventElectrolyte::s_update_lnActCoeff(), DebyeHuckel::s_update_lnMolalityActCoeff(), HMWSoln::s_update_lnMolalityActCoeff(), IdealMolalSoln::s_updateIMS_lnMolalityActCoeff(), HMWSoln::s_updateIMS_lnMolalityActCoeff(), HMWSoln::s_updatePitzer_CoeffWRTemp(), HMWSoln::s_updatePitzer_d2lnMolalityActCoeff_dT2(), HMWSoln::s_updatePitzer_dlnMolalityActCoeff_dP(), HMWSoln::s_updatePitzer_dlnMolalityActCoeff_dT(), HMWSoln::s_updatePitzer_lnMolalityActCoeff(), HMWSoln::s_updateScaling_pHScaling(), HMWSoln::s_updateScaling_pHScaling_dP(), HMWSoln::s_updateScaling_pHScaling_dT(), HMWSoln::s_updateScaling_pHScaling_dT2(), Phase::setConcentrations(), SurfPhase::setCoverages(), SurfPhase::setCoveragesNoNorm(), Phase::setMassFractions(), Phase::setMassFractions_NoNorm(), MolalityVPSSTP::setMolalities(), Phase::setMoleFractions(), Phase::setMoleFractions_NoNorm(), ThermoPhase::setReferenceComposition(), MolalityVPSSTP::setSolvent(), IdealSolnGasVPSS::setToEquilState(), RedlichKwongMFTP::setToEquilState(), IdealGasPhase::setToEquilState(), IdealSolidSolnPhase::setToEquilState(), ThermoPhase::speciesData(), Phase::speciesIndex(), IdealSolidSolnPhase::standardConcentration(), RedlichKwongMFTP::updateAB(), and ThermoPhase::~ThermoPhase().
size_t m_ndim protected inherited
Dimensionality of the phase.
Volumetric phases have dimensionality 3 and surface phases have dimensionality 2.
Definition at line 731 of file Phase.h.
Referenced by Phase::nDim(), Phase::operator=(), and Phase::setNDim().
vector_fp m_speciesComp protected inherited
Atomic composition of the species.
The number of atoms of element i in species k is equal to m_speciesComp[k * m_mm + i] The length of this vector is equal to m_kk * m_mm
Definition at line 736 of file Phase.h.
Referenced by Phase::addUniqueElementAfterFreeze(), Phase::addUniqueSpecies(), Phase::getAtoms(), LatticeSolidPhase::installSlavePhases(), Phase::nAtoms(), and Phase::operator=().
vector_fp m_speciesSize protected inherited
Vector of species sizes.
length m_kk. Used in some equations of state which employ the constant partial molar volume approximation.
Definition at line 740 of file Phase.h.
Referenced by Phase::addUniqueSpecies(), DebyeHuckel::initLengths(), HMWSoln::initLengths(), MineralEQ3::initThermoXML(), DebyeHuckel::initThermoXML(), Phase::operator=(), Phase::size(), HMWSoln::speciesMolarVolume(), and DebyeHuckel::standardConcentration().
vector_fp m_speciesCharge protected inherited
Vector of species charges. length m_kk.
Definition at line 742 of file Phase.h.
Referenced by Phase::addUniqueSpecies(), HMWSoln::applyphScale(), HMWSoln::calcMolalitiesCropped(), MolarityIonicVPSSTP::calcPseudoBinaryMoleFractions(), Phase::charge(), IonsFromNeutralVPSSTP::getDissociationCoeffs(), MolarityIonicVPSSTP::initThermo(), DebyeHuckel::initThermoXML(), Phase::operator=(), HMWSoln::printCoeffs(), PhaseCombo_Interaction::readXMLBinarySpecies(), RedlichKisterVPSSTP::readXMLBinarySpecies(), MargulesVPSSTP::readXMLBinarySpecies(), MixedSolventElectrolyte::readXMLBinarySpecies(), HMWSoln::relative_molal_enthalpy(), DebyeHuckel::s_update_d2lnMolalityActCoeff_dT2(), DebyeHuckel::s_update_dlnMolalityActCoeff_dP(), DebyeHuckel::s_update_dlnMolalityActCoeff_dT(), DebyeHuckel::s_update_lnMolalityActCoeff(), HMWSoln::s_update_lnMolalityActCoeff(), HMWSoln::s_updatePitzer_CoeffWRTemp(), HMWSoln::s_updatePitzer_d2lnMolalityActCoeff_dT2(), HMWSoln::s_updatePitzer_dlnMolalityActCoeff_dP(), HMWSoln::s_updatePitzer_dlnMolalityActCoeff_dT(), HMWSoln::s_updatePitzer_lnMolalityActCoeff(), HMWSoln::s_updateScaling_pHScaling(), HMWSoln::s_updateScaling_pHScaling_dP(), HMWSoln::s_updateScaling_pHScaling_dT(), and HMWSoln::s_updateScaling_pHScaling_dT2().
The documentation for this class was generated from the following files:
IdealGasPhase.h
IdealGasPhase.cpp