Cantera: TortuosityMaxwell Class Reference
TortuosityMaxwell Class Reference
Maxwell model for tortuosity.
#include <TortuosityMaxwell.h>
Public Member Functions
TortuosityMaxwell (double relativeConductivites=0.0)
Default constructor uses Maxwelln exponent of 1.5.
TortuosityMaxwell (const TortuosityMaxwell &right)
Copy Constructor.
virtual ~TortuosityMaxwell ()
Default destructor for TortuosityMaxwell.
TortuosityMaxwell & operator= (const TortuosityMaxwell &right)
Assignment operator.
virtual TortuosityBase * duplMyselfAsTortuosityBase () const
Duplication operator.
virtual doublereal tortuosityFactor (doublereal porosity)
The tortuosity factor models the effective increase in the diffusive transport length.
virtual doublereal McMillanFactor (doublereal porosity)
The McMillan number is the ratio of the flux-like variable to the value it would have without porous flow.
Protected Attributes
doublereal relativeConductivities_
Relative conductivities of the dispersed and continuous phases,.
Detailed Description
Maxwell model for tortuosity.
This class implements transport coefficient corrections appropriate for porous media with a dispersed phase. This model goes back to Maxwell. The formula for the conductivity is expressed in terms of the volume fraction of the continuous phase, \(\phi \), and the relative conductivities of the dispersed and continuous phases, \(r = \kappa_d / \kappa_0 \). For dilute particle suspensions the effective conductivity is
\[ \kappa / \kappa_0 = 1 + 3 (1 - \phi) (r - 1) / (r + 2) + O(\phi^2) \]
The class is derived from the TortuosityBase class.
Definition at line 41 of file TortuosityMaxwell.h.
Constructor & Destructor Documentation
TortuosityMaxwell (double relativeConductivites = 0.0)
Default constructor uses Maxwelln exponent of 1.5.
Parameters
setPower Exponent in the Maxwell factor. The default is 1.5
Definition at line 23 of file TortuosityMaxwell.cpp.
Referenced by TortuosityMaxwell::duplMyselfAsTortuosityBase().
TortuosityMaxwell (const TortuosityMaxwell & right)
Copy Constructor.
Parameters
right Object to be copied
Definition at line 33 of file TortuosityMaxwell.cpp.
~TortuosityMaxwell () virtual
Default destructor for TortuosityMaxwell.
Definition at line 41 of file TortuosityMaxwell.cpp.
Member Function Documentation
TortuosityMaxwell & operator= (const TortuosityMaxwell & right)
Assignment operator.
Parameters
right Object to be copied
Definition at line 50 of file TortuosityMaxwell.cpp.
References TortuosityBase::operator=(), and TortuosityMaxwell::relativeConductivities_.
TortuosityBase * duplMyselfAsTortuosityBase () const virtual
Duplication operator.
Returns
Returns a pointer to a duplicate of the current object given a base class pointer
Reimplemented from TortuosityBase.
Definition at line 67 of file TortuosityMaxwell.cpp.
References TortuosityMaxwell::TortuosityMaxwell().
doublereal tortuosityFactor (doublereal porosity) virtual
The tortuosity factor models the effective increase in the diffusive transport length.
This method returns \(1/\tau^2 \) in the description of the flux
\(C_T D_i \nabla X_i / \tau^2 \).
Reimplemented from TortuosityBase.
Definition at line 80 of file TortuosityMaxwell.cpp.
References TortuosityMaxwell::McMillanFactor().
doublereal McMillanFactor (doublereal porosity) virtual
The McMillan number is the ratio of the flux-like variable to the value it would have without porous flow.
The McMillan number combines the effect of tortuosity and volume fraction of the transported phase. The net flux observed is then the product of the McMillan number and the non-porous transport rate. For a conductivity in a non-porous media, \(\kappa_0 \), the conductivity in the porous media would be \(\kappa = (\rm McMillan) \kappa_0 \).
Reimplemented from TortuosityBase.
Definition at line 94 of file TortuosityMaxwell.cpp.
References TortuosityMaxwell::relativeConductivities_.
Referenced by TortuosityMaxwell::tortuosityFactor().
Member Data Documentation
doublereal relativeConductivities_ protected
Relative conductivities of the dispersed and continuous phases,.
\[ \code{relativeConductivites_} = \kappa_d / \kappa_0 \]
Definition at line 106 of file TortuosityMaxwell.h.
Referenced by TortuosityMaxwell::McMillanFactor(), and TortuosityMaxwell::operator=().
The documentation for this class was generated from the following files:
TortuosityMaxwell.h
TortuosityMaxwell.cpp