Cantera: SpeciesThermoDuo< T1, T2 > Class Template Reference
SpeciesThermoDuo< T1, T2 > Class Template Reference
Managers for Calculating Reference-State Thermodynamics
This species thermo manager requires that all species have one of two parameterizations.
#include <SpeciesThermoMgr.h>
Public Member Functions
SpeciesThermoDuo ()
Constructor.
virtual ~SpeciesThermoDuo ()
Destructor.
SpeciesThermoDuo (const SpeciesThermoDuo &right)
copy constructor
SpeciesThermoDuo & operator= (const SpeciesThermoDuo &right)
Assignment operator.
virtual SpeciesThermo * duplMyselfAsSpeciesThermo () const
Duplication routine for objects which inherit from SpeciesThermo.
virtual void install (std::string name, size_t sp, int type, const doublereal *c, doublereal minTemp, doublereal maxTemp, doublereal refPressure)
install a new species thermodynamic property parameterization for one species.
virtual void install_STIT (SpeciesThermoInterpType *stit_ptr)
Install a new species thermodynamic property parameterization for one species.
virtual void update (doublereal t, doublereal *cp_R, doublereal *h_RT, doublereal *s_R) const
Compute the reference-state properties for all species.
virtual doublereal minTemp (size_t k=npos) const
Minimum temperature.
virtual doublereal maxTemp (size_t k=npos) const
Maximum temperature.
virtual doublereal refPressure (size_t k=npos) const
The reference-state pressure for species k.
virtual int reportType (size_t k) const
This utility function reports the type of parameterization used for the species with index number index.
virtual void reportParams (size_t index, int &type, doublereal *const c, doublereal &minTemp, doublereal &maxTemp, doublereal &refPressure) const
virtual void modifyParams (size_t index, doublereal *c)
Modify parameters for the standard state.
virtual void update_one (size_t k, doublereal T, doublereal *cp_R, doublereal *h_RT, doublereal *s_R) const
Like update(), but only updates the single species k.
Private Attributes
T1 m_thermo1
Thermo Type 1.
T2 m_thermo2
Thermo Type 2.
doublereal m_p0
Reference pressure.
std::map< size_t, int > speciesToType
map from species to type
Detailed Description
template<class T1, class T2>
class Cantera::SpeciesThermoDuo< T1, T2 >
This species thermo manager requires that all species have one of two parameterizations.
Note this seems to be a slow way to do things, and it may be on its way out.
Definition at line 166 of file SpeciesThermoMgr.h.
Constructor & Destructor Documentation
SpeciesThermoDuo () inline
Constructor.
Definition at line 171 of file SpeciesThermoMgr.h.
virtual ~SpeciesThermoDuo () inline virtual
Destructor.
Definition at line 174 of file SpeciesThermoMgr.h.
SpeciesThermoDuo (const SpeciesThermoDuo< T1, T2 > & right) inline
copy constructor
Parameters
right Object to be copied
Definition at line 180 of file SpeciesThermoMgr.h.
References SpeciesThermoDuo< T1, T2 >::operator=().
Member Function Documentation
SpeciesThermoDuo< T1, T2 > & operator= (const SpeciesThermoDuo< T1, T2 > & right)
Assignment operator.
Parameters
right Object to be copied
Definition at line 373 of file SpeciesThermoMgr.h.
References SpeciesThermoDuo< T1, T2 >::m_p0, SpeciesThermoDuo< T1, T2 >::m_thermo1, SpeciesThermoDuo< T1, T2 >::m_thermo2, and SpeciesThermoDuo< T1, T2 >::speciesToType.
Referenced by SpeciesThermoDuo< T1, T2 >::SpeciesThermoDuo().
SpeciesThermo * duplMyselfAsSpeciesThermo () const virtual
Duplication routine for objects which inherit from SpeciesThermo.
This virtual routine can be used to duplicate SpeciesThermo objects inherited from SpeciesThermo even if the application only has a pointer to SpeciesThermo to work with. ->commented out because we first need to add copy constructors and assignment operators to all of the derived classes.
Implements SpeciesThermo.
Definition at line 389 of file SpeciesThermoMgr.h.
void install (std::string name, size_t sp, int type, const doublereal * c, doublereal minTemp, doublereal maxTemp, doublereal refPressure) virtual
install a new species thermodynamic property parameterization for one species.
Parameters
name Name of the species
sp The 'update' method will update the property values for this species at position i index in the property arrays.
type int flag specifying the type of parameterization to be installed.
c vector of coefficients for the parameterization. This vector is simply passed through to the parameterization constructor.
minTemp minimum temperature for which this parameterization is valid.
maxTemp maximum temperature for which this parameterization is valid.
refPressure standard-state pressure for this parameterization.
See Also
speciesThermoTypes.h
Implements SpeciesThermo.
Definition at line 397 of file SpeciesThermoMgr.h.
virtual void install_STIT (SpeciesThermoInterpType * stit_ptr) inline virtual
Install a new species thermodynamic property parameterization for one species.
Parameters
stit_ptr Pointer to the SpeciesThermoInterpType object This will set up the thermo for one species
Implements SpeciesThermo.
Definition at line 234 of file SpeciesThermoMgr.h.
void update (doublereal t, doublereal * cp_R, doublereal * h_RT, doublereal * s_R) const virtual
Compute the reference-state properties for all species.
Given temperature T in K, this method updates the values of the non-dimensional heat capacity at constant pressure, enthalpy, and entropy, at the reference pressure, Pref of each of the standard states.
Parameters
t Temperature (Kelvin)
cp_R Vector of Dimensionless heat capacities. (length m_kk).
h_RT Vector of Dimensionless enthalpies. (length m_kk).
s_R Vector of Dimensionless entropies. (length m_kk).
Implements SpeciesThermo.
Definition at line 419 of file SpeciesThermoMgr.h.
virtual doublereal minTemp (size_t k = npos) const inline virtual
Minimum temperature.
If no argument is supplied, this method returns the minimum temperature for which all parameterizations are valid. If an integer index k is supplied, then the value returned is the minimum temperature for species k in the phase.
Parameters
k Species index
Implements SpeciesThermo.
Definition at line 267 of file SpeciesThermoMgr.h.
References SpeciesThermoDuo< T1, T2 >::m_thermo1, SpeciesThermoDuo< T1, T2 >::m_thermo2, and ckr::max().
virtual doublereal maxTemp (size_t k = npos) const inline virtual
Maximum temperature.
If no argument is supplied, this method returns the maximum temperature for which all parameterizations are valid. If an integer index k is supplied, then the value returned is the maximum temperature for parameterization k.
Parameters
k index for parameterization k
Implements SpeciesThermo.
Definition at line 282 of file SpeciesThermoMgr.h.
References SpeciesThermoDuo< T1, T2 >::m_thermo1, SpeciesThermoDuo< T1, T2 >::m_thermo2, and ckr::min().
virtual doublereal refPressure (size_t k = npos) const inline virtual
The reference-state pressure for species k.
returns the reference state pressure in Pascals for species k. If k is left out of the argument list, it returns the reference state pressure for the first species. Note that some SpeciesThermo implementations, such as those for ideal gases, require that all species in the same phase have the same reference state pressures.
Parameters
k index for parameterization k
Implements SpeciesThermo.
Definition at line 300 of file SpeciesThermoMgr.h.
References SpeciesThermoDuo< T1, T2 >::m_p0.
int reportType (size_t k) const virtual
This utility function reports the type of parameterization used for the species with index number index.
Parameters
k Species index
Implements SpeciesThermo.
Definition at line 428 of file SpeciesThermoMgr.h.
void reportParams (size_t index, int & type, doublereal *const c, doublereal & minTemp, doublereal & maxTemp, doublereal & refPressure) const virtual
This utility function reports back the type of parameterization and all of the parameters for the species, index.
Parameters
index Species index
type Integer type of the standard type
c Vector of coefficients used to set the parameters for the standard state.
minTemp output - Minimum temperature
maxTemp output - Maximum temperature
refPressure output - reference pressure (Pa).
Implements SpeciesThermo.
Definition at line 439 of file SpeciesThermoMgr.h.
void modifyParams (size_t index, doublereal * c) virtual
Modify parameters for the standard state.
Parameters
index Species index
c Vector of coefficients used to set the parameters for the standard state.
Deprecated:
Implements SpeciesThermo.
Definition at line 459 of file SpeciesThermoMgr.h.
virtual void update_one (size_t k, doublereal T, doublereal * cp_R, doublereal * h_RT, doublereal * s_R) const inline virtual inherited
Like update(), but only updates the single species k.
The default treatment is to just call update() which means that potentially the operation takes a m_kk*m_kk hit.
Parameters
k species index
T Temperature (Kelvin)
cp_R Vector of Dimensionless heat capacities. (length m_kk).
h_RT Vector of Dimensionless enthalpies. (length m_kk).
s_R Vector of Dimensionless entropies. (length m_kk).
Reimplemented in NasaThermo, SimpleThermo, ShomateThermo, and GeneralSpeciesThermo.
Definition at line 285 of file SpeciesThermo.h.
References SpeciesThermo::update().
Referenced by PureFluidPhase::initThermo(), PDSS_ConstVol::setTemperature(), PDSS_IdealGas::setTemperature(), and PDSS_SSVol::setTemperature().
Member Data Documentation
T1 m_thermo1 private
Thermo Type 1.
Definition at line 357 of file SpeciesThermoMgr.h.
Referenced by SpeciesThermoDuo< T1, T2 >::maxTemp(), SpeciesThermoDuo< T1, T2 >::minTemp(), and SpeciesThermoDuo< T1, T2 >::operator=().
T2 m_thermo2 private
Thermo Type 2.
Definition at line 359 of file SpeciesThermoMgr.h.
Referenced by SpeciesThermoDuo< T1, T2 >::maxTemp(), SpeciesThermoDuo< T1, T2 >::minTemp(), and SpeciesThermoDuo< T1, T2 >::operator=().
doublereal m_p0 private
Reference pressure.
Definition at line 361 of file SpeciesThermoMgr.h.
Referenced by SpeciesThermoDuo< T1, T2 >::operator=(), and SpeciesThermoDuo< T1, T2 >::refPressure().
std::map<size_t, int> speciesToType private
map from species to type
Definition at line 363 of file SpeciesThermoMgr.h.
Referenced by SpeciesThermoDuo< T1, T2 >::operator=().
The documentation for this class was generated from the following file:
SpeciesThermoMgr.h