Cantera: MMCollisionInt Class Reference
MMCollisionInt Class Reference
Calculation of Collision integrals.
#include <MMCollisionInt.h>
Public Member Functions
MMCollisionInt ()
Default Constructor.
virtual ~MMCollisionInt ()
Destructor.
void init (XML_Writer *xml, doublereal tsmin, doublereal tsmax, int loglevel=0)
Initialize the object for calculation.
doublereal omega22 (double ts, double deltastar)
omega22
doublereal astar (double ts, double deltastar)
astar
doublereal bstar (double ts, double deltastar)
bstar
doublereal cstar (double ts, double deltastar)
cstar
void fit (std::ostream &logfile, int degree, doublereal deltastar, doublereal *astar, doublereal *bstar, doublereal *cstar)
fit
void fit_omega22 (std::ostream &logfile, int degree, doublereal deltastar, doublereal *om22)
fit_omega22
doublereal omega11 (double ts, double deltastar)
omega11
Private Member Functions
doublereal fitDelta (int table, int ntstar, int degree, doublereal *c)
Fit delta.
Private Attributes
std::vector< vector_fp > m_o22poly
m_o22poly
std::vector< vector_fp > m_apoly
m_apoly
std::vector< vector_fp > m_bpoly
m_bpoly
std::vector< vector_fp > m_cpoly
m_cpoly
vector_fp m_logTemp
Log temp.
int m_nmin
nmin
int m_nmax
nmax
XML_Writer * m_xml
XML_Writer pointer.
int m_loglevel
loglevel
Static Private Attributes
static doublereal delta [8]
delta
static doublereal tstar22 [37]
tstar22
static doublereal omega22_table [37 *8]
Table of omega22 values from MM.
static doublereal tstar [39]
tstar
static doublereal astar_table [39 *8]
astar table from MM
static doublereal bstar_table [39 *8]
bstar table from MM
static doublereal cstar_table [39 *8]
cstar table from MM
Detailed Description
Calculation of Collision integrals.
This class provides functions that interpolate the tabulated collision integrals in Monchick and Mason, "Transport Properties of Polar Gases," J. Chem. Phys. (1961)
Definition at line 53 of file MMCollisionInt.h.
Constructor & Destructor Documentation
MMCollisionInt ()
Default Constructor.
Definition at line 230 of file MMCollisionInt.cpp.
~MMCollisionInt () virtual
Destructor.
Definition at line 234 of file MMCollisionInt.cpp.
Member Function Documentation
void init (XML_Writer * xml, doublereal tsmin, doublereal tsmax, int loglevel = 0)
Initialize the object for calculation.
Parameters
xml Pointer to the log file that will receive the debug output messages
tsmin Minimum value of Tstar to carry out the fitting
tsmax Maximum value of Tstar to carry out the fitting
loglevel Set the loglevel for the object. The default loglevel is zero, indicating no output.
Definition at line 248 of file MMCollisionInt.cpp.
References DATA_PTR.
Referenced by TransportFactory::setupMM().
doublereal omega22 (double ts, double deltastar)
omega22
Parameters
ts
deltastar
Definition at line 406 of file MMCollisionInt.cpp.
References DATA_PTR, and Cantera::poly5().
Referenced by TransportFactory::fitProperties(), TransportFactory::getBinDiffCorrection(), and MMCollisionInt::omega11().
doublereal astar (double ts, double deltastar)
astar
Parameters
ts
deltastar
Definition at line 435 of file MMCollisionInt.cpp.
References DATA_PTR, and Cantera::poly5().
Referenced by TransportFactory::getBinDiffCorrection(), and MMCollisionInt::omega11().
doublereal bstar (double ts, double deltastar)
bstar
Parameters
ts
deltastar
Definition at line 465 of file MMCollisionInt.cpp.
References DATA_PTR, and Cantera::poly5().
Referenced by TransportFactory::getBinDiffCorrection().
doublereal cstar (double ts, double deltastar)
cstar
Parameters
ts
deltastar
Definition at line 494 of file MMCollisionInt.cpp.
References DATA_PTR, and Cantera::poly5().
Referenced by TransportFactory::getBinDiffCorrection().
void fit (std::ostream & logfile, int degree, doublereal deltastar, doublereal * astar, doublereal * bstar, doublereal * cstar)
fit
Parameters
logfile
degree
deltastar
astar
bstar
cstar
Definition at line 554 of file MMCollisionInt.cpp.
References DATA_PTR, Cantera::poly5(), and Cantera::polyfit().
Referenced by TransportFactory::fitCollisionIntegrals().
void fit_omega22 (std::ostream & logfile, int degree, doublereal deltastar, doublereal * om22)
fit_omega22
Parameters
logfile
degree
deltastar
om22
Definition at line 524 of file MMCollisionInt.cpp.
References DATA_PTR, Cantera::poly5(), and Cantera::polyfit().
Referenced by TransportFactory::fitCollisionIntegrals().
doublereal omega11 (double ts, double deltastar) inline
omega11
Parameters
ts
deltastar
Definition at line 131 of file MMCollisionInt.h.
References MMCollisionInt::astar(), and MMCollisionInt::omega22().
Referenced by TransportFactory::fitProperties(), and TransportFactory::getBinDiffCorrection().
doublereal fitDelta (int table, int ntstar, int degree, doublereal * c) private
Fit delta.
Parameters
table
ntstar
degree
c C is probable the output vector
Returns
Definition at line 380 of file MMCollisionInt.cpp.
References DATA_PTR, and Cantera::polyfit().
Member Data Documentation
std::vector<vector_fp> m_o22poly private
m_o22poly
Definition at line 149 of file MMCollisionInt.h.
std::vector<vector_fp> m_apoly private
m_apoly
Definition at line 152 of file MMCollisionInt.h.
std::vector<vector_fp> m_bpoly private
m_bpoly
Definition at line 154 of file MMCollisionInt.h.
std::vector<vector_fp> m_cpoly private
m_cpoly
Definition at line 157 of file MMCollisionInt.h.
doublereal delta[8] static private
delta
Definition at line 160 of file MMCollisionInt.h.
doublereal tstar22[37] static private
tstar22
Definition at line 163 of file MMCollisionInt.h.
doublereal omega22_table[37 *8] static private
Table of omega22 values from MM.
Definition at line 166 of file MMCollisionInt.h.
doublereal tstar[39] static private
tstar
table of tstar values
Definition at line 172 of file MMCollisionInt.h.
doublereal astar_table[39 *8] static private
astar table from MM
Definition at line 175 of file MMCollisionInt.h.
doublereal bstar_table[39 *8] static private
bstar table from MM
Definition at line 178 of file MMCollisionInt.h.
doublereal cstar_table[39 *8] static private
cstar table from MM
Definition at line 181 of file MMCollisionInt.h.
vector_fp m_logTemp private
Log temp.
Definition at line 184 of file MMCollisionInt.h.
int m_nmin private
nmin
Definition at line 187 of file MMCollisionInt.h.
int m_nmax private
nmax
Definition at line 190 of file MMCollisionInt.h.
XML_Writer* m_xml private
XML_Writer pointer.
Definition at line 193 of file MMCollisionInt.h.
int m_loglevel private
loglevel
Definition at line 196 of file MMCollisionInt.h.
The documentation for this class was generated from the following files:
MMCollisionInt.h
MMCollisionInt.cpp