Cantera: TortuosityBruggeman Class Reference
TortuosityBruggeman Class Reference
Base case to handle tortuosity corrections for diffusive transport in porous media using the Bruggeman exponential approximation.
#include <TortuosityBruggeman.h>
Public Member Functions
TortuosityBruggeman (doublereal setPower=1.5)
Default constructor uses Bruggeman exponent of 1.5.
TortuosityBruggeman (const TortuosityBruggeman &right)
Copy Constructor.
virtual ~TortuosityBruggeman ()
Default destructor for TortuosityBruggeman.
TortuosityBruggeman & operator= (const TortuosityBruggeman &right)
Assignment operator.
virtual TortuosityBase * duplMyselfAsTortuosityBase () const
Duplication operator.
virtual doublereal tortuosityFactor (doublereal porosity)
The tortuosity factor models the effective increase in the diffusive transport length.
virtual doublereal McMillanFactor (doublereal porosity)
The McMillan number is the ratio of the flux-like variable to the value it would have without porous flow.
Protected Attributes
doublereal expBrug_
Bruggeman exponent: power to which the tortuosity depends on the volume fraction.
Detailed Description
Base case to handle tortuosity corrections for diffusive transport in porous media using the Bruggeman exponential approximation.
Class to compute the increase in diffusive path length associated with tortuous path diffusion through, for example, porous media. This base class implementation relates tortuosity to volume fraction through a power-law relationship that goes back to Bruggeman. The exponent is referred to as the Bruggeman exponent.
Note that the total diffusional flux is generally written as
\[ \frac{ \phi C_T D_i \nabla X_i }{ \tau^2 } \]
where \(\phi \) is the volume fraction of the transported phase, \(\tau \) is referred to as the tortuosity. (Other variables are \(C_T \), the total concentration, \(D_i \), the diffusion coefficient, and \(X_i \), the mole fraction with Fickian transport assumed.)
The tortuosity comes into play in conjunction the the
Definition at line 44 of file TortuosityBruggeman.h.
Constructor & Destructor Documentation
TortuosityBruggeman (doublereal setPower = 1.5)
Default constructor uses Bruggeman exponent of 1.5.
Parameters
setPower Exponent in the Bruggeman factor. The default is 1.5
Definition at line 23 of file TortuosityBruggeman.cpp.
Referenced by TortuosityBruggeman::duplMyselfAsTortuosityBase().
TortuosityBruggeman (const TortuosityBruggeman & right)
Copy Constructor.
Parameters
right Object to be copied
Definition at line 33 of file TortuosityBruggeman.cpp.
~TortuosityBruggeman () virtual
Default destructor for TortuosityBruggeman.
Definition at line 41 of file TortuosityBruggeman.cpp.
Member Function Documentation
TortuosityBruggeman & operator= (const TortuosityBruggeman & right)
Assignment operator.
Parameters
right Object to be copied
Definition at line 50 of file TortuosityBruggeman.cpp.
References TortuosityBruggeman::expBrug_, and TortuosityBase::operator=().
TortuosityBase * duplMyselfAsTortuosityBase () const virtual
Duplication operator.
Returns
Returns a pointer to a duplicate of the current object given a base class pointer
Reimplemented from TortuosityBase.
Definition at line 67 of file TortuosityBruggeman.cpp.
References TortuosityBruggeman::TortuosityBruggeman().
doublereal tortuosityFactor (doublereal porosity) virtual
The tortuosity factor models the effective increase in the diffusive transport length.
This method returns \(1/\tau^2 \) in the description of the flux
\(C_T D_i \nabla X_i / \tau^2 \).
Reimplemented from TortuosityBase.
Definition at line 81 of file TortuosityBruggeman.cpp.
References TortuosityBruggeman::expBrug_.
doublereal McMillanFactor (doublereal porosity) virtual
The McMillan number is the ratio of the flux-like variable to the value it would have without porous flow.
The McMillan number combines the effect of tortuosity and volume fraction of the transported phase. The net flux observed is then the product of the McMillan number and the non-porous transport rate. For a conductivity in a non-porous media, \(\kappa_0 \), the conductivity in the porous media would be \(\kappa = (\rm McMillan) \kappa_0 \).
Reimplemented from TortuosityBase.
Definition at line 95 of file TortuosityBruggeman.cpp.
References TortuosityBruggeman::expBrug_.
Member Data Documentation
doublereal expBrug_ protected
Bruggeman exponent: power to which the tortuosity depends on the volume fraction.
Definition at line 102 of file TortuosityBruggeman.h.
Referenced by TortuosityBruggeman::McMillanFactor(), TortuosityBruggeman::operator=(), and TortuosityBruggeman::tortuosityFactor().
The documentation for this class was generated from the following files:
TortuosityBruggeman.h
TortuosityBruggeman.cpp