Cantera: PhaseCombo_Interaction Class Reference
PhaseCombo_Interaction Class Reference
Thermodynamic Properties
PhaseCombo_Interaction is a derived class of GibbsExcessVPSSTP that employs the Margules approximation for the excess gibbs free energy while eliminating the entropy of mixing term.
#include <PhaseCombo_Interaction.h>
Public Member Functions
PhaseCombo_Interaction ()
Constructor.
PhaseCombo_Interaction (std::string inputFile, std::string id="")
Construct and initialize a PhaseCombo_Interaction ThermoPhase object directly from an xml input file.
PhaseCombo_Interaction (XML_Node &phaseRef, std::string id="")
Construct and initialize a PhaseCombo_Interaction ThermoPhase object directly from an XML database.
PhaseCombo_Interaction (int testProb)
Special constructor for a hard-coded problem.
PhaseCombo_Interaction (const PhaseCombo_Interaction &b)
Copy constructor.
PhaseCombo_Interaction & operator= (const PhaseCombo_Interaction &b)
Assignment operator.
virtual ~PhaseCombo_Interaction ()
Destructor.
virtual ThermoPhase * duplMyselfAsThermoPhase () const
Duplication routine for objects which inherit from ThermoPhase.
doublereal _RT () const
Return the Gas Constant multiplied by the current temperature.
XML_Node & xml ()
Returns a reference to the XML_Node stored for the phase.
void saveState (vector_fp &state) const
Save the current internal state of the phase Write to vector 'state' the current internal state.
void saveState (size_t lenstate, doublereal *state) const
Write to array 'state' the current internal state.
void restoreState (const vector_fp &state)
Restore a state saved on a previous call to saveState.
void restoreState (size_t lenstate, const doublereal *state)
Restore the state of the phase from a previously saved state vector.
doublereal molecularWeight (size_t k) const
Molecular weight of species k.
doublereal molarMass (size_t k) const
Return the Molar mass of species k Alternate name for molecular weight.
void getMolecularWeights (vector_fp &weights) const
Copy the vector of molecular weights into vector weights.
void getMolecularWeights (int iwt, doublereal *weights) const
Copy the vector of molecular weights into array weights.
void getMolecularWeights (doublereal *weights) const
Copy the vector of molecular weights into array weights.
const vector_fp & molecularWeights () const
Return a const reference to the internal vector of molecular weights.
doublereal size (size_t k) const
This routine returns the size of species k.
doublereal charge (size_t k) const
Dimensionless electrical charge of a single molecule of species k The charge is normalized by the the magnitude of the electron charge.
doublereal chargeDensity () const
Charge density [C/m^3].
size_t nDim () const
Returns the number of spatial dimensions (1, 2, or 3)
void setNDim (size_t ndim)
Set the number of spatial dimensions (1, 2, or 3).
virtual void freezeSpecies ()
Call when finished adding species.
bool speciesFrozen ()
True if freezeSpecies has been called.
virtual bool ready () const
int stateMFNumber () const
Return the State Mole Fraction Number.
void stateMFChangeCalc (bool forceChange=false)
Every time the mole fractions have changed, this routine will increment the stateMFNumber.
Utilities
virtual int eosType () const
Equation of state type flag.
void constructPhaseFile (std::string inputFile, std::string id)
Initialization of a phase using an xml file.
void constructPhaseXML (XML_Node &phaseNode, std::string id)
Import and initialize a phase specification in an XML tree into the current object.
Activities, Standard States, and Activity Concentrations
The activity \(a_k\) of a species in solution is related to the chemical potential by
\[ \mu_k = \mu_k^0(T) + \hat R T \log a_k. \]
The quantity \(\mu_k^0(T,P)\) is the chemical potential at unit activity, which depends only on temperature and pressure.
virtual void getActivityCoefficients (doublereal *ac) const
Get the array of non-dimensional molar-based activity coefficients at the current solution temperature, pressure, and solution concentration.
Partial Molar Properties of the Solution
virtual void getChemPotentials (doublereal *mu) const
Get the species chemical potentials. Units: J/kmol.
virtual doublereal enthalpy_mole () const
Molar enthalpy. Units: J/kmol.
virtual doublereal entropy_mole () const
Molar entropy. Units: J/kmol.
virtual doublereal cp_mole () const
Molar heat capacity at constant pressure. Units: J/kmol/K.
virtual doublereal cv_mole () const
Molar heat capacity at constant volume. Units: J/kmol/K.
virtual void getPartialMolarEnthalpies (doublereal *hbar) const
Returns an array of partial molar enthalpies for the species in the mixture.
virtual void getPartialMolarEntropies (doublereal *sbar) const
Returns an array of partial molar entropies for the species in the mixture.
virtual void getPartialMolarCp (doublereal *cpbar) const
Returns an array of partial molar entropies for the species in the mixture.
virtual void getPartialMolarVolumes (doublereal *vbar) const
Return an array of partial molar volumes for the species in the mixture.
void getElectrochemPotentials (doublereal *mu) const
Get the species electrochemical potentials.
virtual void getd2lnActCoeffdT2 (doublereal *d2lnActCoeffdT2) const
Get the array of temperature second derivatives of the log activity coefficients.
virtual void getdlnActCoeffdT (doublereal *dlnActCoeffdT) const
Get the array of temperature derivatives of the log activity coefficients.
Thermodynamic Values for the Species Reference States
virtual void initThermo ()
The following methods are used in the process of constructing the phase and setting its parameters from a specification in an input file.
void initThermoXML (XML_Node &phaseNode, std::string id)
Import and initialize a ThermoPhase object.
Derivatives of Thermodynamic Variables needed for Applications
virtual void getdlnActCoeffds (const doublereal dTds, const doublereal *const dXds, doublereal *dlnActCoeffds) const
Get the change in activity coefficients w.r.t.
virtual void getdlnActCoeffdlnX_diag (doublereal *dlnActCoeffdlnX_diag) const
Get the array of log concentration-like derivatives of the log activity coefficients - diagonal component.
virtual void getdlnActCoeffdlnN_diag (doublereal *dlnActCoeffdlnN_diag) const
Get the array of derivatives of the log activity coefficients wrt mole numbers - diagonal only.
virtual void getdlnActCoeffdlnN (const size_t ld, doublereal *const dlnActCoeffdlnN)
Get the array of derivatives of the log activity coefficients with respect to the ln species mole numbers.
Activities, Standard States, and Activity Concentrations
The activity \(a_k\) of a species in solution is related to the chemical potential by
\[ \mu_k = \mu_k^0(T) + \hat R T \log a_k. \]
The quantity \(\mu_k^0(T,P)\) is the chemical potential at unit activity, which depends only on temperature and pressure.
virtual void getActivityConcentrations (doublereal *c) const
This method returns an array of generalized concentrations.
virtual doublereal standardConcentration (size_t k=0) const
The standard concentration \(C^0_k \) used to normalize the generalized concentration.
virtual doublereal logStandardConc (size_t k=0) const
Returns the natural logarithm of the standard concentration of the kth species.
virtual void getUnitsStandardConc (double *uA, int k=0, int sizeUA=6) const
Returns the units of the standard and generalized concentrations Note they have the same units, as their ratio is defined to be equal to the activity of the kth species in the solution, which is unitless.
virtual void getActivities (doublereal *ac) const
Get the array of non-dimensional activities (molality based for this class and classes that derive from it) at the current solution temperature, pressure, and solution concentration.
virtual void getdlnActCoeffdlnX (doublereal *dlnActCoeffdlnX) const
Get the array of log concentration-like derivatives of the log activity coefficients.
Setting the State
These methods set all or part of the thermodynamic state.
virtual void setState_TP (doublereal t, doublereal p)
Set the temperature (K) and pressure (Pa)
Chemical Equilibrium
Routines that implement the Chemical equilibrium capability for a single phase, based on the element-potential method.
virtual void setMassFractions (const doublereal *const y)
Set the mass fractions to the specified values, and then normalize them so that they sum to 1.0.
virtual void setMassFractions_NoNorm (const doublereal *const y)
Set the mass fractions to the specified values without normalizing.
virtual void setMoleFractions (const doublereal *const x)
Set the mole fractions to the specified values, and then normalize them so that they sum to 1.0.
virtual void setMoleFractions_NoNorm (const doublereal *const x)
Set the mole fractions to the specified values without normalizing.
virtual void setConcentrations (const doublereal *const c)
Set the concentrations to the specified values within the phase.
Utilities (VPStandardStateTP)
virtual int standardStateConvention () const
This method returns the convention used in specification of the standard state, of which there are currently two, temperature based, and variable pressure based.
Partial Molar Properties of the Solution (VPStandardStateTP)
void getChemPotentials_RT (doublereal *mu) const
Get the array of non-dimensional species chemical potentials These are partial molar Gibbs free energies.
Initialization Methods - For Internal use (VPStandardState)
virtual void setParametersFromXML (const XML_Node &eosdata)
Set equation of state parameter values from XML entries.
void setVPSSMgr (VPSSMgr *vp_ptr)
set the VPSS Mgr
VPSSMgr * provideVPSSMgr ()
Return a pointer to the VPSSMgr for this phase.
void createInstallPDSS (size_t k, const XML_Node &s, const XML_Node *phaseNode_ptr)
PDSS * providePDSS (size_t k)
const PDSS * providePDSS (size_t k) const
Information Methods
virtual doublereal refPressure () const
Returns the reference pressure in Pa.
virtual doublereal minTemp (size_t k=npos) const
Minimum temperature for which the thermodynamic data for the species or phase are valid.
doublereal Hf298SS (const int k) const
Report the 298 K Heat of Formation of the standard state of one species (J kmol-1)
virtual void modifyOneHf298SS (const int k, const doublereal Hf298New)
Modify the value of the 298 K Heat of Formation of one species in the phase (J kmol-1)
virtual doublereal maxTemp (size_t k=npos) const
Maximum temperature for which the thermodynamic data for the species are valid.
bool chargeNeutralityNecessary () const
Returns the chargeNeutralityNecessity boolean.
Molar Thermodynamic Properties of the Solution
virtual doublereal intEnergy_mole () const
Molar internal energy. Units: J/kmol.
virtual doublereal gibbs_mole () const
Molar Gibbs function. Units: J/kmol.
Mechanical Properties
virtual doublereal isothermalCompressibility () const
Returns the isothermal compressibility. Units: 1/Pa.
virtual doublereal thermalExpansionCoeff () const
Return the volumetric thermal expansion coefficient. Units: 1/K.
virtual void updateDensity ()
Electric Potential
The phase may be at some non-zero electrical potential.
These methods set or get the value of the electric potential.
void setElectricPotential (doublereal v)
Set the electric potential of this phase (V).
doublereal electricPotential () const
Returns the electric potential of this phase (V).
Activities, Standard States, and Activity Concentrations
The activity \(a_k\) of a species in solution is related to the chemical potential by
\[ \mu_k = \mu_k^0(T,P) + \hat R T \log a_k. \]
The quantity \(\mu_k^0(T,P)\) is the standard chemical potential at unit activity, which depends on temperature and pressure, but not on composition.
The activity is dimensionless.
virtual int activityConvention () const
This method returns the convention used in specification of the activities, of which there are currently two, molar- and molality-based conventions.
virtual void getLnActivityCoefficients (doublereal *lnac) const
Get the array of non-dimensional molar-based ln activity coefficients at the current solution temperature, pressure, and solution concentration.
Partial Molar Properties of the Solution
virtual void getPartialMolarIntEnergies (doublereal *ubar) const
Return an array of partial molar internal energies for the species in the mixture.
virtual void getdPartialMolarVolumes_dT (doublereal *d_vbar_dT) const
Return an array of derivatives of partial molar volumes wrt temperature for the species in the mixture.
virtual void getdPartialMolarVolumes_dP (doublereal *d_vbar_dP) const
Return an array of derivatives of partial molar volumes wrt pressure for the species in the mixture.
Properties of the Standard State of the Species in the Solution
virtual void getdStandardVolumes_dT (doublereal *d_vol_dT) const
Get the derivative of the molar volumes of the species standard states wrt temperature at the current T and P of the solution.
virtual void getdStandardVolumes_dP (doublereal *d_vol_dP) const
Get the derivative molar volumes of the species standard states wrt pressure at the current T and P of the solution.
Thermodynamic Values for the Species Reference States
virtual void getIntEnergy_RT_ref (doublereal *urt) const
Returns the vector of nondimensional internal Energies of the reference state at the current temperature of the solution and the reference pressure for each species.
virtual void setReferenceComposition (const doublereal *const x)
Sets the reference composition.
virtual void getReferenceComposition (doublereal *const x) const
Gets the reference composition.
Specific Properties
doublereal enthalpy_mass () const
Specific enthalpy.
doublereal intEnergy_mass () const
Specific internal energy.
doublereal entropy_mass () const
Specific entropy.
doublereal gibbs_mass () const
Specific Gibbs function.
doublereal cp_mass () const
Specific heat at constant pressure.
doublereal cv_mass () const
Specific heat at constant volume.
Setting the State
These methods set all or part of the thermodynamic state.
virtual void setState_TPX (doublereal t, doublereal p, const doublereal *x)
Set the temperature (K), pressure (Pa), and mole fractions.
void setState_TPX (doublereal t, doublereal p, compositionMap &x)
Set the temperature (K), pressure (Pa), and mole fractions.
void setState_TPX (doublereal t, doublereal p, const std::string &x)
Set the temperature (K), pressure (Pa), and mole fractions.
void setState_TPY (doublereal t, doublereal p, const doublereal *y)
Set the internally stored temperature (K), pressure (Pa), and mass fractions of the phase.
void setState_TPY (doublereal t, doublereal p, compositionMap &y)
Set the internally stored temperature (K), pressure (Pa), and mass fractions of the phase.
void setState_TPY (doublereal t, doublereal p, const std::string &y)
Set the internally stored temperature (K), pressure (Pa), and mass fractions of the phase.
void setState_PX (doublereal p, doublereal *x)
Set the pressure (Pa) and mole fractions.
void setState_PY (doublereal p, doublereal *y)
Set the internally stored pressure (Pa) and mass fractions.
virtual void setState_HP (doublereal h, doublereal p, doublereal tol=1.e-4)
Set the internally stored specific enthalpy (J/kg) and pressure (Pa) of the phase.
virtual void setState_UV (doublereal u, doublereal v, doublereal tol=1.e-4)
Set the specific internal energy (J/kg) and specific volume (m^3/kg).
virtual void setState_SP (doublereal s, doublereal p, doublereal tol=1.e-4)
Set the specific entropy (J/kg/K) and pressure (Pa).
virtual void setState_SV (doublereal s, doublereal v, doublereal tol=1.e-4)
Set the specific entropy (J/kg/K) and specific volume (m^3/kg).
Chemical Equilibrium
Chemical equilibrium.
virtual void setToEquilState (const doublereal *lambda_RT)
This method is used by the ChemEquil equilibrium solver.
void setElementPotentials (const vector_fp &lambda)
Stores the element potentials in the ThermoPhase object.
bool getElementPotentials (doublereal *lambda) const
Returns the element potentials stored in the ThermoPhase object.
Critical State Properties.
These methods are only implemented by some subclasses, and may be moved out of ThermoPhase at a later date.
virtual doublereal critTemperature () const
Critical temperature (K).
virtual doublereal critPressure () const
Critical pressure (Pa).
virtual doublereal critDensity () const
Critical density (kg/m3).
Saturation Properties.
These methods are only implemented by subclasses that implement full liquid-vapor equations of state.
They may be moved out of ThermoPhase at a later date.
virtual doublereal satTemperature (doublereal p) const
Return the saturation temperature given the pressure.
virtual doublereal satPressure (doublereal t) const
Return the saturation pressure given the temperature.
virtual doublereal vaporFraction () const
Return the fraction of vapor at the current conditions.
virtual void setState_Tsat (doublereal t, doublereal x)
Set the state to a saturated system at a particular temperature.
virtual void setState_Psat (doublereal p, doublereal x)
Set the state to a saturated system at a particular pressure.
Initialization Methods - For Internal Use (ThermoPhase)
void saveSpeciesData (const size_t k, const XML_Node *const data)
Store a reference pointer to the XML tree containing the species data for this phase.
const std::vector< const
XML_Node * > & speciesData () const
Return a pointer to the vector of XML nodes containing the species data for this phase.
void setSpeciesThermo (SpeciesThermo *spthermo)
Install a species thermodynamic property manager.
virtual SpeciesThermo & speciesThermo (int k=-1)
Return a changeable reference to the calculation manager for species reference-state thermodynamic properties.
virtual void initThermoFile (std::string inputFile, std::string id)
virtual void installSlavePhases (Cantera::XML_Node *phaseNode)
Add in species from Slave phases.
virtual void setParameters (int n, doublereal *const c)
Set the equation of state parameters.
virtual void getParameters (int &n, doublereal *const c) const
Get the equation of state parameters in a vector.
virtual void setStateFromXML (const XML_Node &state)
Set the initial state of the phase to the conditions specified in the state XML element.
Derivatives of Thermodynamic Variables needed for Applications
virtual void getdlnActCoeffdlnN_numderiv (const size_t ld, doublereal *const dlnActCoeffdlnN)
Printing
virtual std::string report (bool show_thermo=true) const
returns a summary of the state of the phase as a string
virtual void reportCSV (std::ofstream &csvFile) const
returns a summary of the state of the phase to a comma separated file
Name and ID
Class Phase contains two strings that identify a phase. The ID is the value of the ID attribute of the XML phase node that is used to initialize a phase when it is read. The name field is also initialized to the value of the ID attribute of the XML phase node.
However, the name field may be changed to another value during the course of a calculation. For example, if a phase is located in two places, but has the same constitutive input, the ids of the two phases will be the same, but the names of the two phases may be different.
It is an error to have two phases in a single problem with the same name or the same id (or the name from one phase being the same as the id of another phase). Thus, it is expected that there is a 1-1 correspondence between names and unique phases within a Cantera problem.
std::string id () const
Return the string id for the phase.
void setID (std::string id)
Set the string id for the phase.
std::string name () const
Return the name of the phase.
void setName (std::string nm)
Sets the string name for the phase.
Element and Species Information
std::string elementName (size_t m) const
Name of the element with index m.
size_t elementIndex (std::string name) const
Return the index of element named 'name'.
const std::vector< std::string > & elementNames () const
Return a read-only reference to the vector of element names.
doublereal atomicWeight (size_t m) const
Atomic weight of element m.
doublereal entropyElement298 (size_t m) const
Entropy of the element in its standard state at 298 K and 1 bar.
int atomicNumber (size_t m) const
Atomic number of element m.
int elementType (size_t m) const
Return the element constraint type Possible types include:
int changeElementType (int m, int elem_type)
Change the element type of the mth constraint Reassigns an element type.
const vector_fp & atomicWeights () const
Return a read-only reference to the vector of atomic weights.
size_t nElements () const
Number of elements.
void checkElementIndex (size_t m) const
Check that the specified element index is in range Throws an exception if m is greater than nElements()-1.
void checkElementArraySize (size_t mm) const
Check that an array size is at least nElements() Throws an exception if mm is less than nElements().
doublereal nAtoms (size_t k, size_t m) const
Number of atoms of element m in species k.
void getAtoms (size_t k, double *atomArray) const
Get a vector containing the atomic composition of species k.
size_t speciesIndex (std::string name) const
Returns the index of a species named 'name' within the Phase object.
std::string speciesName (size_t k) const
Name of the species with index k.
std::string speciesSPName (int k) const
Returns the expanded species name of a species, including the phase name This is guaranteed to be unique within a Cantera problem.
const std::vector< std::string > & speciesNames () const
Return a const reference to the vector of species names.
size_t nSpecies () const
Returns the number of species in the phase.
void checkSpeciesIndex (size_t k) const
Check that the specified species index is in range Throws an exception if k is greater than nSpecies()-1.
void checkSpeciesArraySize (size_t kk) const
Check that an array size is at least nSpecies() Throws an exception if kk is less than nSpecies().
Set thermodynamic state
Set the internal thermodynamic state by setting the internally stored temperature, density and species composition. Note that the composition is always set first.
Temperature and density are held constant if not explicitly set.
void setMoleFractionsByName (compositionMap &xMap)
Set the species mole fractions by name.
void setMoleFractionsByName (const std::string &x)
Set the mole fractions of a group of species by name.
void setMassFractionsByName (compositionMap &yMap)
Set the species mass fractions by name.
void setMassFractionsByName (const std::string &x)
Set the species mass fractions by name.
void setState_TRX (doublereal t, doublereal dens, const doublereal *x)
Set the internally stored temperature (K), density, and mole fractions.
void setState_TRX (doublereal t, doublereal dens, compositionMap &x)
Set the internally stored temperature (K), density, and mole fractions.
void setState_TRY (doublereal t, doublereal dens, const doublereal *y)
Set the internally stored temperature (K), density, and mass fractions.
void setState_TRY (doublereal t, doublereal dens, compositionMap &y)
Set the internally stored temperature (K), density, and mass fractions.
void setState_TNX (doublereal t, doublereal n, const doublereal *x)
Set the internally stored temperature (K), molar density (kmol/m^3), and mole fractions.
void setState_TR (doublereal t, doublereal rho)
Set the internally stored temperature (K) and density (kg/m^3)
void setState_TX (doublereal t, doublereal *x)
Set the internally stored temperature (K) and mole fractions.
void setState_TY (doublereal t, doublereal *y)
Set the internally stored temperature (K) and mass fractions.
void setState_RX (doublereal rho, doublereal *x)
Set the density (kg/m^3) and mole fractions.
void setState_RY (doublereal rho, doublereal *y)
Set the density (kg/m^3) and mass fractions.
Composition
void getMoleFractionsByName (compositionMap &x) const
Get the mole fractions by name.
doublereal moleFraction (size_t k) const
Return the mole fraction of a single species.
doublereal moleFraction (std::string name) const
Return the mole fraction of a single species.
doublereal massFraction (size_t k) const
Return the mass fraction of a single species.
doublereal massFraction (std::string name) const
Return the mass fraction of a single species.
void getMoleFractions (doublereal *const x) const
Get the species mole fraction vector.
void getMassFractions (doublereal *const y) const
Get the species mass fractions.
const doublereal * massFractions () const
Return a const pointer to the mass fraction array.
void getConcentrations (doublereal *const c) const
Get the species concentrations (kmol/m^3).
doublereal concentration (const size_t k) const
Concentration of species k.
const doublereal * moleFractdivMMW () const
Returns a const pointer to the start of the moleFraction/MW array.
Thermodynamic Properties
doublereal temperature () const
Temperature (K).
virtual doublereal density () const
Density (kg/m^3).
doublereal molarDensity () const
Molar density (kmol/m^3).
doublereal molarVolume () const
Molar volume (m^3/kmol).
virtual void setDensity (const doublereal density)
Set the internally stored density (kg/m^3) of the phase Note the density of a phase is an independent variable.
virtual void setMolarDensity (const doublereal molarDensity)
Set the internally stored molar density (kmol/m^3) of the phase.
Mean Properties
doublereal mean_X (const doublereal *const Q) const
Evaluate the mole-fraction-weighted mean of an array Q.
doublereal mean_Y (const doublereal *const Q) const
Evaluate the mass-fraction-weighted mean of an array Q.
doublereal meanMolecularWeight () const
The mean molecular weight. Units: (kg/kmol)
doublereal sum_xlogx () const
Evaluate \(\sum_k X_k \log X_k \).
doublereal sum_xlogQ (doublereal *const Q) const
Evaluate \(\sum_k X_k \log Q_k \).
Adding Elements and Species
These methods are used to add new elements or species.
These are not usually called by user programs.
Since species are checked to insure that they are only composed of declared elements, it is necessary to first add all elements before adding any species.
void addElement (const std::string &symbol, doublereal weight=-12345.0)
Add an element.
void addElement (const XML_Node &e)
Add an element from an XML specification.
void addUniqueElement (const std::string &symbol, doublereal weight=-12345.0, int atomicNumber=0, doublereal entropy298=ENTROPY298_UNKNOWN, int elem_type=CT_ELEM_TYPE_ABSPOS)
Add an element, checking for uniqueness The uniqueness is checked by comparing the string symbol.
void addUniqueElement (const XML_Node &e)
Add an element, checking for uniqueness The uniqueness is checked by comparing the string symbol.
void addElementsFromXML (const XML_Node &phase)
Add all elements referenced in an XML_Node tree.
void freezeElements ()
Prohibit addition of more elements, and prepare to add species.
bool elementsFrozen ()
True if freezeElements has been called.
size_t addUniqueElementAfterFreeze (const std::string &symbol, doublereal weight, int atomicNumber, doublereal entropy298=ENTROPY298_UNKNOWN, int elem_type=CT_ELEM_TYPE_ABSPOS)
Add an element after elements have been frozen, checking for uniqueness The uniqueness is checked by comparing the string symbol.
void addSpecies (const std::string &name, const doublereal *comp, doublereal charge=0.0, doublereal size=1.0)
void addUniqueSpecies (const std::string &name, const doublereal *comp, doublereal charge=0.0, doublereal size=1.0)
Add a species to the phase, checking for uniqueness of the name This routine checks for uniqueness of the string name.
Protected Member Functions
double checkMFSum (const doublereal *const x) const
utility routine to check mole fraction sum
void init (const vector_fp &mw)
void setMolecularWeight (const int k, const double mw)
Set the molecular weight of a single species to a given value.
Protected Attributes
size_t numBinaryInteractions_
number of binary interaction expressions
vector_fp m_HE_b_ij
Enthalpy term for the binary mole fraction interaction of the excess gibbs free energy expression.
vector_fp m_HE_c_ij
Enthalpy term for the ternary mole fraction interaction of the excess gibbs free energy expression.
vector_fp m_HE_d_ij
Enthalpy term for the quaternary mole fraction interaction of the excess gibbs free energy expression.
vector_fp m_SE_b_ij
Entropy term for the binary mole fraction interaction of the excess gibbs free energy expression.
vector_fp m_SE_c_ij
Entropy term for the ternary mole fraction interaction of the excess gibbs free energy expression.
vector_fp m_SE_d_ij
Entropy term for the quaternary mole fraction interaction of the excess gibbs free energy expression.
vector_fp m_VHE_b_ij
Enthalpy term for the binary mole fraction interaction of the excess gibbs free energy expression.
vector_fp m_VHE_c_ij
Enthalpy term for the ternary mole fraction interaction of the excess gibbs free energy expression.
vector_fp m_VHE_d_ij
Enthalpy term for the quaternary mole fraction interaction of the excess gibbs free energy expression.
vector_fp m_VSE_b_ij
Entropy term for the binary mole fraction interaction of the excess gibbs free energy expression.
vector_fp m_VSE_c_ij
Entropy term for the ternary mole fraction interaction of the excess gibbs free energy expression.
vector_fp m_VSE_d_ij
Entropy term for the quaternary mole fraction interaction of the excess gibbs free energy expression.
std::vector< size_t > m_pSpecies_A_ij
vector of species indices representing species A in the interaction
std::vector< size_t > m_pSpecies_B_ij
vector of species indices representing species B in the interaction
int formMargules_
form of the Margules interaction expression
int formTempModel_
form of the temperature dependence of the Margules interaction expression
std::vector< doublereal > moleFractions_
Storage for the current values of the mole fractions of the species.
std::vector< doublereal > lnActCoeff_Scaled_
Storage for the current values of the activity coefficients of the species.
std::vector< doublereal > dlnActCoeffdT_Scaled_
Storage for the current derivative values of the gradients with respect to temperature of the log of the activity coefficients of the species.
std::vector< doublereal > d2lnActCoeffdT2_Scaled_
Storage for the current derivative values of the gradients with respect to temperature of the log of the activity coefficients of the species.
std::vector< doublereal > dlnActCoeffdlnN_diag_
Storage for the current derivative values of the gradients with respect to logarithm of the mole fraction of the log of the activity coefficients of the species.
std::vector< doublereal > dlnActCoeffdlnX_diag_
Storage for the current derivative values of the gradients with respect to logarithm of the mole fraction of the log of the activity coefficients of the species.
Array2D dlnActCoeffdlnN_
Storage for the current derivative values of the gradients with respect to logarithm of the species mole number of the log of the activity coefficients of the species.
std::vector< doublereal > m_pp
Temporary storage space that is fair game.
doublereal m_Pcurrent
Current value of the pressure - state variable.
doublereal m_Tlast_ss
The last temperature at which the standard statethermodynamic properties were calculated at.
doublereal m_Plast_ss
The last pressure at which the Standard State thermodynamic properties were calculated at.
doublereal m_P0
VPSSMgr * m_VPSS_ptr
Pointer to the VPSS manager that calculates all of the standard state info efficiently.
std::vector< PDSS * > m_PDSS_storage
Storage for the PDSS objects for the species.
SpeciesThermo * m_spthermo
Pointer to the calculation manager for species reference-state thermodynamic properties.
std::vector< const XML_Node * > m_speciesData
Vector of pointers to the species databases.
doublereal m_phi
Stored value of the electric potential for this phase.
vector_fp m_lambdaRRT
Vector of element potentials.
bool m_hasElementPotentials
Boolean indicating whether there is a valid set of saved element potentials for this phase.
bool m_chargeNeutralityNecessary
Boolean indicating whether a charge neutrality condition is a necessity.
int m_ssConvention
Contains the standard state convention.
std::vector< doublereal > xMol_Ref
Reference Mole Fraction Composition.
size_t m_kk
Number of species in the phase.
size_t m_ndim
Dimensionality of the phase.
vector_fp m_speciesComp
Atomic composition of the species.
vector_fp m_speciesSize
Vector of species sizes.
vector_fp m_speciesCharge
Vector of species charges. length m_kk.
Private Member Functions
void readXMLBinarySpecies (XML_Node &xmlBinarySpecies)
Process an XML node called "binaryNeutralSpeciesParameters".
void resizeNumInteractions (const size_t num)
Resize internal arrays within the object that depend upon the number of binary Margules interaction terms.
void initLengths ()
Initialize lengths of local variables after all species have been identified.
void s_update_lnActCoeff () const
Update the activity coefficients.
void s_update_dlnActCoeff_dT () const
Update the derivative of the log of the activity coefficients wrt T.
void s_update_dlnActCoeff_dlnX_diag () const
Update the derivative of the log of the activity coefficients wrt log(mole fraction)
void s_update_dlnActCoeff_dlnN_diag () const
Update the derivative of the log of the activity coefficients wrt log(moles) - diagonal only.
void s_update_dlnActCoeff_dlnN () const
Update the derivative of the log of the activity coefficients wrt log(moles_m)
doublereal err (std::string msg) const
Error function.
Mechanical Properties
virtual void setPressure (doublereal p)
Set the internally stored pressure (Pa) at constant temperature and composition.
void calcDensity ()
Calculate the density of the mixture using the partial molar volumes and mole fractions as input.
Properties of the Standard State of the Species in the Solution
          (VPStandardStateTP)
Within VPStandardStateTP, these properties are calculated via a common routine, _updateStandardStateThermo(), which must be overloaded in inherited objects. The values are cached within this object, and are not recalculated unless the temperature or pressure changes.
virtual void getStandardChemPotentials (doublereal *mu) const
Get the array of chemical potentials at unit activity.
virtual void getEnthalpy_RT (doublereal *hrt) const
Get the nondimensional Enthalpy functions for the species at their standard states at the current T and P of the solution.
virtual void getEntropy_R (doublereal *sr) const
Get the array of nondimensional Enthalpy functions for the standard state species at the current T and P of the solution.
virtual void getGibbs_RT (doublereal *grt) const
Get the nondimensional Gibbs functions for the species at their standard states of solution at the current T and P of the solution.
void getPureGibbs (doublereal *gpure) const
Get the standard state Gibbs functions for each species at the current T and P.
virtual void getIntEnergy_RT (doublereal *urt) const
Returns the vector of nondimensional internal Energies of the standard state at the current temperature and pressure of the solution for each species.
virtual void getCp_R (doublereal *cpr) const
Get the nondimensional Heat Capacities at constant pressure for the standard state of the species at the current T and P.
virtual void getStandardVolumes (doublereal *vol) const
Get the molar volumes of each species in their standard states at the current T and P of the solution.
virtual void setTemperature (const doublereal temp)
Set the temperature of the phase.
doublereal pressure () const
Returns the current pressure of the phase.
virtual void updateStandardStateThermo () const
Updates the standard state thermodynamic functions at the current T and P of the solution.
virtual void _updateStandardStateThermo () const
Updates the standard state thermodynamic functions at the current T and P of the solution.
Thermodynamic Values for the Species Reference States (VPStandardStateTP)
virtual void getEnthalpy_RT_ref (doublereal *hrt) const
Returns the vector of nondimensional enthalpies of the reference state at the current temperature of the solution and the reference pressure for the species.
virtual void getGibbs_RT_ref (doublereal *grt) const
Returns the vector of nondimensional Gibbs free energies of the reference state at the current temperature of the solution and the reference pressure for the species.
virtual void getGibbs_ref (doublereal *g) const
virtual void getEntropy_R_ref (doublereal *er) const
virtual void getCp_R_ref (doublereal *cprt) const
virtual void getStandardVolumes_ref (doublereal *vol) const
Get the molar volumes of the species reference states at the current T and P_ref of the solution.
const vector_fp & Gibbs_RT_ref () const
Detailed Description
PhaseCombo_Interaction is a derived class of GibbsExcessVPSSTP that employs the Margules approximation for the excess gibbs free energy while eliminating the entropy of mixing term.
PhaseCombo_Interaction derives from class GibbsExcessVPSSTP which is derived from VPStandardStateTP, and overloads the virtual methods defined there with ones that use expressions appropriate for the Margules Excess gibbs free energy approximation. The reader should refer to the MargulesVPSSTP class for information on that class. This class in addition adds a term to the activity coefficient that eliminates the ideal solution mixing term within the chemical potential. This is a very radical thing to do, but it is supported by experimental evidence under some conditions.
The independent unknowns are pressure, temperature, and mass fraction.
Several concepts are introduced. The first concept is that there are temporary variables for holding the species standard state values of Cp, H, S, G, and V at the last temperature and pressure called. These functions are not recalculated if a new call is made using the previous temperature and pressure. Currently, these variables and the calculation method are handled by the VPSSMgr class, for which VPStandardStateTP owns a pointer to.
To support the above functionality, pressure and temperature variables, m_plast_ss and m_tlast_ss, are kept which store the last pressure and temperature used in the evaluation of standard state properties.
This class is introduced to represent specific conditions observed in thermal batteries. HOwever, it may be physically motivated to represent conditions where there may be a mixture of compounds that are not "mixed" at the molecular level. Therefore, there is no mixing term.
The lack of a mixing term has profound effects. First, the mole fraction of a species can now be identically zero due to thermodynamic considerations. The phase behaves more like a series of phases. That's why we named it PhaseCombo.
Specification of Species Standard State Properties
All species are defined to have standard states that depend upon both the temperature and the pressure. The Margules approximation assumes symmetric standard states, where all of the standard state assume that the species are in pure component states at the temperature and pressure of the solution. I don't think it prevents, however, some species from being dilute in the solution.
Specification of Solution Thermodynamic Properties
The molar excess Gibbs free energy is given by the following formula which is a sum over interactions i. Each of the interactions are binary interactions involving two of the species in the phase, denoted, Ai and Bi. This is the generalization of the Margules formulation for a phase that has more than 2 species. The second term in the excess gibbs free energy is a negation of the ideal solution's mixing term.
\[ G^E = \sum_i \left(H_{Ei} - T S_{Ei} \right) - \sum_i \left(n_i R T \ln{X_i} \right) \]
\[ H^E_i = n X_{Ai} X_{Bi} \left(h_{o,i} + h_{1,i} X_{Bi} \right) \]
\[ S^E_i = n X_{Ai} X_{Bi} \left(s_{o,i} + s_{1,i} X_{Bi} \right) \]
where n is the total moles in the solution.
The activity of a species defined in the phase is given by an excess Gibbs free energy formulation.
\[ a_k = \gamma_k X_k \]
  where
\[ R T \ln(\gamma_k)= \frac{d(n G^E)}{d(n_k)}\Bigg|_{n_i} \]
Taking the derivatives results in the following expression
\[ R T \ln(\gamma_k)= \sum_i \left(\left(\delta_{Ai,k} X_{Bi} + \delta_{Bi,k} X_{Ai} - X_{Ai} X_{Bi} \right) \left(g^E_{o,i} + g^E_{1,i} X_{Bi} \right) + \left(\delta_{Bi,k} - X_{Bi} \right) X_{Ai} X_{Bi} g^E_{1,i} \right) - RT \ln{X_k} \]
where \(g^E_{o,i} = h_{o,i} - T s_{o,i} \) and \(g^E_{1,i} = h_{1,i} - T s_{1,i} \) and where \(X_k \) is the mole fraction of species k.
This object inherits from the class VPStandardStateTP. Therefore, the specification and calculation of all standard state and reference state values are handled at that level. Various functional forms for the standard state are permissible. The chemical potential for species k is equal to
\[ \mu_k(T,P) = \mu^o_k(T, P) + R T \ln(\gamma_k X_k) \]
The partial molar entropy for species k is given by the following relation,
\[ \tilde{s}_k(T,P) = s^o_k(T,P) - R \ln(\gamma_k X_k) - R T \frac{d \ln(\gamma_k) }{dT} \]
The partial molar enthalpy for species k is given by
\[ \tilde{h}_k(T,P) = h^o_k(T,P) - R T^2 \frac{d \ln(\gamma_k)}{dT} \]
The partial molar volume for species k is
\[ \tilde V_k(T,P) = V^o_k(T,P) + R T \frac{d \ln(\gamma_k) }{dP} \]
The partial molar Heat Capacity for species k is
\[ \tilde{C}_{p,k}(T,P) = C^o_{p,k}(T,P) - 2 R T \frac{d \ln(\gamma_k)}{dT} - R T^2 \frac{d^2 \ln(\gamma_k) }{{dT}^2} \]
Application within Kinetics Managers
\(C^a_k\) are defined such that \(a_k = C^a_k / C^s_k, \) where \(C^s_k \) is a standard concentration defined below and \(a_k \) are activities used in the thermodynamic functions. These activity (or generalized) concentrations are used by kinetics manager classes to compute the forward and reverse rates of elementary reactions. The activity concentration, \(C^a_k \),is given by the following expression.
\[ C^a_k = C^s_k X_k = \frac{P}{R T} X_k \]
The standard concentration for species k is independent of k and equal to
\[ C^s_k = C^s = \frac{P}{R T} \]
For example, a bulk-phase binary gas reaction between species j and k, producing a new gas species l would have the following equation for its rate of progress variable, \(R^1 \), which has units of kmol m-3 s-1.
\[ R^1 = k^1 C_j^a C_k^a = k^1 (C^s a_j) (C^s a_k) \]
where
\[ C_j^a = C^s a_j \mbox{\quad and \quad} C_k^a = C^s a_k \]
\(C_j^a \) is the activity concentration of species j, and \(C_k^a \) is the activity concentration of species k. \(C^s \) is the standard concentration. \(a_j \) is the activity of species j which is equal to the mole fraction of j.
The reverse rate constant can then be obtained from the law of microscopic reversibility and the equilibrium expression for the system.
\[ \frac{a_j a_k}{ a_l} = K_a^{o,1} = \exp(\frac{\mu^o_l - \mu^o_j - \mu^o_k}{R T}) \]
\(K_a^{o,1} \) is the dimensionless form of the equilibrium constant, associated with the pressure dependent standard states \(\mu^o_l(T,P) \) and their associated activities, \(a_l \), repeated here:
\[ \mu_l(T,P) = \mu^o_l(T, P) + R T \log(a_l) \]
We can switch over to expressing the equilibrium constant in terms of the reference state chemical potentials
\[ K_a^{o,1} = \exp(\frac{\mu^{ref}_l - \mu^{ref}_j - \mu^{ref}_k}{R T}) * \frac{P_{ref}}{P} \]
The concentration equilibrium constant, \(K_c \), may be obtained by changing over to activity concentrations. When this is done:
\[ \frac{C^a_j C^a_k}{ C^a_l} = C^o K_a^{o,1} = K_c^1 = \exp(\frac{\mu^{ref}_l - \mu^{ref}_j - \mu^{ref}_k}{R T}) * \frac{P_{ref}}{RT} \]
%Kinetics managers will calculate the concentration equilibrium constant, \form#423,
using the second and third part of the above expression as a definition for the concentration
equilibrium constant.
For completeness, the pressure equilibrium constant may be obtained as well
\[ \frac{P_j P_k}{ P_l P_{ref}} = K_p^1 = \exp(\frac{\mu^{ref}_l - \mu^{ref}_j - \mu^{ref}_k}{R T}) \]
\(K_p \) is the simplest form of the equilibrium constant for ideal gases. However, it isn't necessarily the simplest form of the equilibrium constant for other types of phases; \(K_c \) is used instead because it is completely general.
The reverse rate of progress may be written down as
\[ R^{-1} = k^{-1} C_l^a = k^{-1} (C^o a_l) \]
where we can use the concept of microscopic reversibility to write the reverse rate constant in terms of the forward reate constant and the concentration equilibrium constant, \(K_c \).
\[ k^{-1} = k^1 K^1_c \]
\(k^{-1} \) has units of s-1.
Instantiation of the Class
The constructor for this phase is located in the default ThermoFactory for Cantera. A new PhaseCombo_Interaction object may be created by the following code snippet:
XML_Node *xc = get_XML_File("LiFeS_X_combo.xml");
XML_Node * const xs = xc->findNameID("phase", "LiFeS_X");
ThermoPhase *l_tp = newPhase(*xs);
PhaseCombo_Interaction *LiFeS_X_solid = dynamic_cast <PhaseCombo_Interaction *>(l_tp);
or by the following code
std::string  id = "LiFeS_X";
Cantera::ThermoPhase *LiFeS_X_Phase = Cantera::newPhase("LiFeS_X_combo.xml", id);
PhaseCombo_Interaction *LiFeS_X_solid = dynamic_cast <PhaseCombo_Interaction *>(l_tp);
or by the following constructor:
XML_Node *xc = get_XML_File("LiFeS_X_combo.xml");
XML_Node * const xs = xc->findNameID("phase", "LiFeS_X");
PhaseCombo_Interaction *LiFeS_X_solid = new PhaseCombo_Interaction(*xs);
XML Example
An example of an XML Element named phase setting up a PhaseCombo_Interaction object named LiFeS_X is given below.
 <phase dim="3" id="LiFeS_X">
   <elementArray datasrc="elements.xml">
      Li Fe S
   </elementArray>
   <speciesArray datasrc="#species_LiFeS">
    LiTFe1S2(S)  Li2Fe1S2(S)
   </speciesArray>
   <thermo model="PhaseCombo_Interaction">
   <activityCoefficients model="Margules" TempModel="constant">
      <binaryNeutralSpeciesParameters speciesA="LiTFe1S2(S)" speciesB="Li2Fe1S2(S)">
         <excessEnthalpy model="poly_Xb" terms="2" units="kJ/mol">
             84.67069219, -269.1959421
         </excessEnthalpy>
         <excessEntropy  model="poly_Xb" terms="2" units="J/mol/K">
             100.7511565, -361.4222659
         </excessEntropy>
         <excessVolume_Enthalpy model="poly_Xb" terms="2" units="ml/mol">
              0, 0
         </excessVolume_Enthalpy>
         <excessVolume_Entropy  model="poly_Xb" terms="2" units="ml/mol/K">
              0, 0
         </excessVolume_Entropy>
       </binaryNeutralSpeciesParameters>
    </activityCoefficients>
  </thermo>
  <transport model="none"/>
  <kinetics model="none"/>
</phase>
The model attribute "PhaseCombo_Interaction" of the thermo XML element identifies the phase as
being of the type handled by the PhaseCombo_Interaction object.
Definition at line 341 of file PhaseCombo_Interaction.h.
Constructor & Destructor Documentation
PhaseCombo_Interaction ()
Constructor.
This doesn't do much more than initialize constants with default values for water at 25C. Water molecular weight comes from the default elements.xml file. It actually differs slightly from the IAPWS95 value of 18.015268. However, density conservation and therefore element conservation is the more important principle to follow.
Definition at line 30 of file PhaseCombo_Interaction.cpp.
Referenced by PhaseCombo_Interaction::duplMyselfAsThermoPhase().
PhaseCombo_Interaction (std::string inputFile, std::string id = "")
Construct and initialize a PhaseCombo_Interaction ThermoPhase object directly from an xml input file.
Working constructors
The two constructors below are the normal way the phase initializes itself. They are shells that call the routine initThermo(), with a reference to the XML database to get the info for the phase.
Parameters
inputFile Name of the input file containing the phase XML data to set up the object
id ID of the phase in the input file. Defaults to the empty string.
Definition at line 48 of file PhaseCombo_Interaction.cpp.
References PhaseCombo_Interaction::constructPhaseFile().
PhaseCombo_Interaction (XML_Node & phaseRef, std::string id = "")
Construct and initialize a PhaseCombo_Interaction ThermoPhase object directly from an XML database.
Parameters
phaseRef XML phase node containing the description of the phase
id id attribute containing the name of the phase. (default is the empty string)
Definition at line 62 of file PhaseCombo_Interaction.cpp.
References PhaseCombo_Interaction::constructPhaseXML().
PhaseCombo_Interaction (int testProb)
Special constructor for a hard-coded problem.
Parameters
testProb Hard-coded value. Only the value of 1 is used. It's for a LiKCl system -> test to predict the eutectic and liquidus correctly.
Definition at line 155 of file PhaseCombo_Interaction.cpp.
References PhaseCombo_Interaction::constructPhaseFile(), PhaseCombo_Interaction::m_HE_b_ij, PhaseCombo_Interaction::m_HE_c_ij, PhaseCombo_Interaction::m_HE_d_ij, PhaseCombo_Interaction::m_pSpecies_A_ij, PhaseCombo_Interaction::m_pSpecies_B_ij, PhaseCombo_Interaction::m_SE_b_ij, PhaseCombo_Interaction::m_SE_c_ij, PhaseCombo_Interaction::m_SE_d_ij, PhaseCombo_Interaction::m_VHE_b_ij, PhaseCombo_Interaction::m_VHE_c_ij, PhaseCombo_Interaction::m_VHE_d_ij, PhaseCombo_Interaction::m_VSE_b_ij, PhaseCombo_Interaction::m_VSE_c_ij, PhaseCombo_Interaction::m_VSE_d_ij, Cantera::npos, PhaseCombo_Interaction::numBinaryInteractions_, and Phase::speciesIndex().
PhaseCombo_Interaction (const PhaseCombo_Interaction & b)
Copy constructor.
Note this stuff will not work until the underlying phase has a working copy constructor
Parameters
b class to be copied
Definition at line 80 of file PhaseCombo_Interaction.cpp.
References PhaseCombo_Interaction::operator=().
~PhaseCombo_Interaction () virtual
Destructor.
~PhaseCombo_Interaction(): (virtual)
Destructor: does nothing:
HKM - Checked for Transition
Definition at line 132 of file PhaseCombo_Interaction.cpp.
Member Function Documentation
PhaseCombo_Interaction & operator= (const PhaseCombo_Interaction & b)
Assignment operator.
Parameters
b class to be copied.
Definition at line 95 of file PhaseCombo_Interaction.cpp.
References PhaseCombo_Interaction::formMargules_, PhaseCombo_Interaction::formTempModel_, PhaseCombo_Interaction::m_HE_b_ij, PhaseCombo_Interaction::m_HE_c_ij, PhaseCombo_Interaction::m_HE_d_ij, PhaseCombo_Interaction::m_pSpecies_A_ij, PhaseCombo_Interaction::m_pSpecies_B_ij, PhaseCombo_Interaction::m_SE_b_ij, PhaseCombo_Interaction::m_SE_c_ij, PhaseCombo_Interaction::m_SE_d_ij, PhaseCombo_Interaction::m_VHE_b_ij, PhaseCombo_Interaction::m_VHE_c_ij, PhaseCombo_Interaction::m_VHE_d_ij, PhaseCombo_Interaction::m_VSE_b_ij, PhaseCombo_Interaction::m_VSE_c_ij, PhaseCombo_Interaction::m_VSE_d_ij, PhaseCombo_Interaction::numBinaryInteractions_, and GibbsExcessVPSSTP::operator=().
Referenced by PhaseCombo_Interaction::PhaseCombo_Interaction().
ThermoPhase * duplMyselfAsThermoPhase () const virtual
Duplication routine for objects which inherit from ThermoPhase.
This virtual routine can be used to duplicate thermophase objects inherited from ThermoPhase even if the application only has a pointer to ThermoPhase to work with.
Reimplemented from GibbsExcessVPSSTP.
Definition at line 142 of file PhaseCombo_Interaction.cpp.
References PhaseCombo_Interaction::PhaseCombo_Interaction().
int eosType () const virtual
Equation of state type flag.
The ThermoPhase base class returns zero. Subclasses should define this to return a unique non-zero value. Known constants defined for this purpose are listed in mix_defs.h. The MolalityVPSSTP class also returns zero, as it is a non-complete class.
Reimplemented from GibbsExcessVPSSTP.
Definition at line 229 of file PhaseCombo_Interaction.cpp.
Referenced by PhaseCombo_Interaction::err().
void constructPhaseFile (std::string inputFile, std::string id)
Initialization of a phase using an xml file.
This routine is a precursor to routine, which does most of the work.
Parameters
inputFile XML file containing the description of the phase
id Optional parameter identifying the name of the phase. If none is given, the first XML phase element will be used.
Definition at line 250 of file PhaseCombo_Interaction.cpp.
References XML_Node::build(), PhaseCombo_Interaction::constructPhaseXML(), XML_Node::copy(), Cantera::findInputFile(), Cantera::findXMLPhase(), and Phase::xml().
Referenced by PhaseCombo_Interaction::PhaseCombo_Interaction().
void constructPhaseXML (XML_Node & phaseNode, std::string id)
Import and initialize a phase specification in an XML tree into the current object.
Here we read an XML description of the phase. We import descriptions of the elements that make up the species in a phase. We import information about the species, including their reference state thermodynamic polynomials. We then freeze the state of the species.
Then, we read the species molar volumes from the xml tree to finish the initialization.
Parameters
phaseNode This object must be the phase node of a complete XML tree description of the phase, including all of the species data. In other words while "phase" must point to an XML phase object, it must have sibling nodes "speciesData" that describe the species in the phase.
id ID of the phase. If nonnull, a check is done to see if phaseNode is pointing to the phase with the correct id.
Definition at line 309 of file PhaseCombo_Interaction.cpp.
References XML_Node::attrib(), XML_Node::child(), XML_Node::hasChild(), XML_Node::id(), Cantera::importPhase(), Cantera::lowercase(), and Phase::size().
Referenced by PhaseCombo_Interaction::constructPhaseFile(), and PhaseCombo_Interaction::PhaseCombo_Interaction().
void getActivityCoefficients (doublereal * ac) const virtual
Get the array of non-dimensional molar-based activity coefficients at the current solution temperature, pressure, and solution concentration.
Parameters
ac Output vector of activity coefficients. Length: m_kk.
Reimplemented from GibbsExcessVPSSTP.
Definition at line 363 of file PhaseCombo_Interaction.cpp.
References GibbsExcessVPSSTP::lnActCoeff_Scaled_, Phase::m_kk, and PhaseCombo_Interaction::s_update_lnActCoeff().
void getChemPotentials (doublereal * mu) const virtual
Get the species chemical potentials. Units: J/kmol.
This function returns a vector of chemical potentials of the species in solution at the current temperature, pressure and mole fraction of the solution.
Parameters
mu Output vector of species chemical potentials. Length: m_kk. Units: J/kmol
Reimplemented from ThermoPhase.
Definition at line 394 of file PhaseCombo_Interaction.cpp.
References Cantera::GasConstant, VPStandardStateTP::getStandardChemPotentials(), GibbsExcessVPSSTP::lnActCoeff_Scaled_, Phase::m_kk, ckr::max(), GibbsExcessVPSSTP::moleFractions_, PhaseCombo_Interaction::s_update_lnActCoeff(), Phase::temperature(), and Cantera::xxSmall.
Referenced by PhaseCombo_Interaction::getElectrochemPotentials().
doublereal enthalpy_mole () const virtual
Molar enthalpy. Units: J/kmol.
Reimplemented from ThermoPhase.
Definition at line 419 of file PhaseCombo_Interaction.cpp.
References PhaseCombo_Interaction::getPartialMolarEnthalpies(), GibbsExcessVPSSTP::moleFractions_, and Phase::nSpecies().
doublereal entropy_mole () const virtual
Molar entropy. Units: J/kmol.
Reimplemented from ThermoPhase.
Definition at line 432 of file PhaseCombo_Interaction.cpp.
References PhaseCombo_Interaction::getPartialMolarEntropies(), GibbsExcessVPSSTP::moleFractions_, and Phase::nSpecies().
doublereal cp_mole () const virtual
Molar heat capacity at constant pressure. Units: J/kmol/K.
Reimplemented from ThermoPhase.
Definition at line 445 of file PhaseCombo_Interaction.cpp.
References ckr::cp(), PhaseCombo_Interaction::getPartialMolarCp(), GibbsExcessVPSSTP::moleFractions_, and Phase::nSpecies().
Referenced by PhaseCombo_Interaction::cv_mole().
doublereal cv_mole () const virtual
Molar heat capacity at constant volume. Units: J/kmol/K.
Reimplemented from ThermoPhase.
Definition at line 458 of file PhaseCombo_Interaction.cpp.
References PhaseCombo_Interaction::cp_mole(), and Cantera::GasConstant.
void getPartialMolarEnthalpies (doublereal * hbar) const virtual
Returns an array of partial molar enthalpies for the species in the mixture.
Units (J/kmol)
For this phase, the partial molar enthalpies are equal to the standard state enthalpies modified by the derivative of the molality-based activity coefficient wrt temperature
\[ \bar h_k(T,P) = h^o_k(T,P) - R T^2 \frac{d \ln(\gamma_k)}{dT} \]
Parameters
hbar Vector of returned partial molar enthalpies (length m_kk, units = J/kmol)
Reimplemented from ThermoPhase.
Definition at line 477 of file PhaseCombo_Interaction.cpp.
References GibbsExcessVPSSTP::dlnActCoeffdT_Scaled_, Cantera::GasConstant, VPStandardStateTP::getEnthalpy_RT(), Phase::m_kk, PhaseCombo_Interaction::s_update_dlnActCoeff_dT(), PhaseCombo_Interaction::s_update_lnActCoeff(), and Phase::temperature().
Referenced by PhaseCombo_Interaction::enthalpy_mole().
void getPartialMolarEntropies (doublereal * sbar) const virtual
Returns an array of partial molar entropies for the species in the mixture.
Units (J/kmol)
For this phase, the partial molar enthalpies are equal to the standard state enthalpies modified by the derivative of the activity coefficient wrt temperature
\[ \bar s_k(T,P) = s^o_k(T,P) - R T^2 \frac{d \ln(\gamma_k)}{dT} - R \ln(\gamma_k X_k) - R T \frac{d \ln(\gamma_k) }{dT} \]
Parameters
sbar Vector of returned partial molar entropies (length m_kk, units = J/kmol/K)
Reimplemented from ThermoPhase.
Definition at line 555 of file PhaseCombo_Interaction.cpp.
References GibbsExcessVPSSTP::dlnActCoeffdT_Scaled_, Cantera::GasConstant, VPStandardStateTP::getEntropy_R(), GibbsExcessVPSSTP::lnActCoeff_Scaled_, Phase::m_kk, ckr::max(), GibbsExcessVPSSTP::moleFractions_, PhaseCombo_Interaction::s_update_dlnActCoeff_dT(), PhaseCombo_Interaction::s_update_lnActCoeff(), Phase::temperature(), and Cantera::xxSmall.
Referenced by PhaseCombo_Interaction::entropy_mole().
void getPartialMolarCp (doublereal * cpbar) const virtual
Returns an array of partial molar entropies for the species in the mixture.
Units (J/kmol)
For this phase, the partial molar enthalpies are equal to the standard state enthalpies modified by the derivative of the activity coefficient wrt temperature
\[ ??????????????? \bar s_k(T,P) = s^o_k(T,P) - R T^2 \frac{d \ln(\gamma_k)}{dT} - R \ln(\gamma_k X_k) - R T \frac{d \ln(\gamma_k) }{dT} ??????????????? \]
Parameters
cpbar Vector of returned partial molar heat capacities (length m_kk, units = J/kmol/K)
Reimplemented from ThermoPhase.
Definition at line 516 of file PhaseCombo_Interaction.cpp.
References GibbsExcessVPSSTP::d2lnActCoeffdT2_Scaled_, GibbsExcessVPSSTP::dlnActCoeffdT_Scaled_, Cantera::GasConstant, VPStandardStateTP::getCp_R(), Phase::m_kk, PhaseCombo_Interaction::s_update_dlnActCoeff_dT(), PhaseCombo_Interaction::s_update_lnActCoeff(), and Phase::temperature().
Referenced by PhaseCombo_Interaction::cp_mole().
void getPartialMolarVolumes (doublereal * vbar) const virtual
Return an array of partial molar volumes for the species in the mixture.
Units: m^3/kmol.
Frequently, for this class of thermodynamics representations, the excess Volume due to mixing is zero. Here, we set it as a default. It may be overridden in derived classes.
Parameters
vbar Output vector of species partial molar volumes. Length = m_kk. units are m^3/kmol.
Reimplemented from GibbsExcessVPSSTP.
Definition at line 595 of file PhaseCombo_Interaction.cpp.
References VPStandardStateTP::getStandardVolumes(), Phase::m_kk, PhaseCombo_Interaction::m_pSpecies_A_ij, PhaseCombo_Interaction::m_pSpecies_B_ij, PhaseCombo_Interaction::m_VHE_b_ij, PhaseCombo_Interaction::m_VHE_c_ij, PhaseCombo_Interaction::m_VSE_b_ij, PhaseCombo_Interaction::m_VSE_c_ij, GibbsExcessVPSSTP::moleFractions_, PhaseCombo_Interaction::numBinaryInteractions_, and Phase::temperature().
void getElectrochemPotentials (doublereal * mu) const
Get the species electrochemical potentials.
These are partial molar quantities. This method adds a term \(Fz_k \phi_k \) to the to each chemical potential.
Units: J/kmol
Parameters
mu output vector containing the species electrochemical potentials. Length: m_kk., units = J/kmol
Definition at line 384 of file PhaseCombo_Interaction.cpp.
References Phase::charge(), ThermoPhase::electricPotential(), PhaseCombo_Interaction::getChemPotentials(), and Phase::m_kk.
void getd2lnActCoeffdT2 (doublereal * d2lnActCoeffdT2) const virtual
Get the array of temperature second derivatives of the log activity coefficients.
This function is a virtual class, but it first appears in GibbsExcessVPSSTP class and derived classes from GibbsExcessVPSSTP.
units = 1/Kelvin
Parameters
d2lnActCoeffdT2 Output vector of temperature 2nd derivatives of the log Activity Coefficients. length = m_kk
Definition at line 848 of file PhaseCombo_Interaction.cpp.
References GibbsExcessVPSSTP::d2lnActCoeffdT2_Scaled_, Phase::m_kk, and PhaseCombo_Interaction::s_update_dlnActCoeff_dT().
void getdlnActCoeffdT (doublereal * dlnActCoeffdT) const virtual
Get the array of temperature derivatives of the log activity coefficients.
This function is a virtual class, but it first appears in GibbsExcessVPSSTP class and derived classes from GibbsExcessVPSSTP.
units = 1/Kelvin
Parameters
dlnActCoeffdT Output vector of temperature derivatives of the log Activity Coefficients. length = m_kk
Reimplemented from GibbsExcessVPSSTP.
Definition at line 836 of file PhaseCombo_Interaction.cpp.
References GibbsExcessVPSSTP::dlnActCoeffdT_Scaled_, Phase::m_kk, and PhaseCombo_Interaction::s_update_dlnActCoeff_dT().
void initThermo () virtual
The following methods are used in the process of constructing the phase and setting its parameters from a specification in an input file.
They are not normally used in application programs. To see how they are used, see files importCTML.cpp and ThermoFactory.cpp.
Initialize. This method is provided to allow subclasses to perform any initialization required after all species have been added. For example, it might be used to resize internal work arrays that must have an entry for each species. The base class implementation does nothing, and subclasses that do not require initialization do not need to overload this method. When importing a CTML phase description, this method is called just prior to returning from function importPhase.
See Also
importCTML.cpp
Reimplemented from GibbsExcessVPSSTP.
Definition at line 652 of file PhaseCombo_Interaction.cpp.
References PhaseCombo_Interaction::initLengths(), and GibbsExcessVPSSTP::initThermo().
void initThermoXML (XML_Node & phaseNode, std::string id) virtual
Import and initialize a ThermoPhase object.
Parameters
phaseNode This object must be the phase node of a complete XML tree description of the phase, including all of the species data. In other words while "phase" must point to an XML phase object, it must have sibling nodes "speciesData" that describe the species in the phase.
id ID of the phase. If nonnull, a check is done to see if phaseNode is pointing to the phase with the correct id.
Reimplemented from VPStandardStateTP.
Definition at line 682 of file PhaseCombo_Interaction.cpp.
References XML_Node::attrib(), XML_Node::child(), XML_Node::hasChild(), VPStandardStateTP::initThermoXML(), Cantera::lowercase(), XML_Node::name(), XML_Node::nChildren(), and PhaseCombo_Interaction::readXMLBinarySpecies().
void getdlnActCoeffds (const doublereal dTds, const doublereal *const dXds, doublereal * dlnActCoeffds) const virtual
Get the change in activity coefficients w.r.t.
change in state (temp, mole fraction, etc.) along a line in parameter space or along a line in physical space
Parameters
dTds Input of temperature change along the path
dXds Input vector of changes in mole fraction along the path. length = m_kk Along the path length it must be the case that the mole fractions sum to one.
dlnActCoeffds Output vector of the directional derivatives of the log Activity Coefficients along the path. length = m_kk units are 1/units(s). if s is a physical coordinate then the units are 1/m.
Reimplemented from ThermoPhase.
Definition at line 870 of file PhaseCombo_Interaction.cpp.
References GibbsExcessVPSSTP::dlnActCoeffdT_Scaled_, Cantera::GasConstant, PhaseCombo_Interaction::m_HE_b_ij, PhaseCombo_Interaction::m_HE_c_ij, Phase::m_kk, PhaseCombo_Interaction::m_pSpecies_A_ij, PhaseCombo_Interaction::m_pSpecies_B_ij, PhaseCombo_Interaction::m_SE_b_ij, PhaseCombo_Interaction::m_SE_c_ij, ckr::max(), GibbsExcessVPSSTP::moleFractions_, PhaseCombo_Interaction::numBinaryInteractions_, PhaseCombo_Interaction::s_update_dlnActCoeff_dT(), Phase::temperature(), and Cantera::xxSmall.
void getdlnActCoeffdlnX_diag (doublereal * dlnActCoeffdlnX_diag) const virtual
Get the array of log concentration-like derivatives of the log activity coefficients - diagonal component.
This function is a virtual method. For ideal mixtures (unity activity coefficients), this can return zero. Implementations should take the derivative of the logarithm of the activity coefficient with respect to the logarithm of the mole fraction.
units = dimensionless
Parameters
dlnActCoeffdlnX_diag Output vector of the diagonal component of the log(mole fraction) derivatives of the log Activity Coefficients. length = m_kk
Reimplemented from ThermoPhase.
Definition at line 1101 of file PhaseCombo_Interaction.cpp.
References GibbsExcessVPSSTP::dlnActCoeffdlnX_diag_, Phase::m_kk, and PhaseCombo_Interaction::s_update_dlnActCoeff_dlnX_diag().
void getdlnActCoeffdlnN_diag (doublereal * dlnActCoeffdlnN_diag) const virtual
Get the array of derivatives of the log activity coefficients wrt mole numbers - diagonal only.
This function is a virtual method. For ideal mixtures (unity activity coefficients), this can return zero. Implementations should take the derivative of the logarithm of the activity coefficient with respect to the logarithm of the concentration-like variable (i.e. mole fraction, molality, etc.) that represents the standard state.
units = dimensionless
Parameters
dlnActCoeffdlnN_diag Output vector of the diagonal entries for the log(mole fraction) derivatives of the log Activity Coefficients. length = m_kk
Reimplemented from VPStandardStateTP.
Definition at line 1089 of file PhaseCombo_Interaction.cpp.
References GibbsExcessVPSSTP::dlnActCoeffdlnN_diag_, Phase::m_kk, and PhaseCombo_Interaction::s_update_dlnActCoeff_dlnN_diag().
void getdlnActCoeffdlnN (const size_t ld, doublereal *const dlnActCoeffdlnN) virtual
Get the array of derivatives of the log activity coefficients with respect to the ln species mole numbers.
Implementations should take the derivative of the logarithm of the activity coefficient with respect to a log of a species mole number (with all other species mole numbers held constant)
units = 1 / kmol
dlnActCoeffdlnN[ ld * k + m] will contain the derivative of log act_coeff for the mth species with respect to the number of moles of the kth species.
\[ \frac{d \ln(\gamma_m) }{d \ln(n_k) }\Bigg|_{n_i} \]
Parameters
ld Number of rows in the matrix
dlnActCoeffdlnN Output vector of derivatives of the log Activity Coefficients. length = m_kk * m_kk
Reimplemented from GibbsExcessVPSSTP.
Definition at line 1113 of file PhaseCombo_Interaction.cpp.
References GibbsExcessVPSSTP::dlnActCoeffdlnN_, Phase::m_kk, and PhaseCombo_Interaction::s_update_dlnActCoeff_dlnN().
void readXMLBinarySpecies (XML_Node & xmlBinarySpecies) private
Process an XML node called "binaryNeutralSpeciesParameters".
This node contains all of the parameters necessary to describe the Margules model for a particular binary interaction. This function reads the XML file and writes the coefficients it finds to an internal data structures.
Parameters
xmlBinarySpecies Reference to the XML_Node named "binaryNeutralSpeciesParameters" containing the binary interaction
Definition at line 1156 of file PhaseCombo_Interaction.cpp.
References XML_Node::attrib(), Phase::charge(), XML_Node::child(), DATA_PTR, ctml::getFloatArray(), Cantera::lowercase(), PhaseCombo_Interaction::m_HE_b_ij, PhaseCombo_Interaction::m_HE_c_ij, PhaseCombo_Interaction::m_pSpecies_A_ij, PhaseCombo_Interaction::m_pSpecies_B_ij, PhaseCombo_Interaction::m_SE_b_ij, PhaseCombo_Interaction::m_SE_c_ij, Phase::m_speciesCharge, PhaseCombo_Interaction::m_VHE_b_ij, PhaseCombo_Interaction::m_VHE_c_ij, PhaseCombo_Interaction::m_VSE_b_ij, PhaseCombo_Interaction::m_VSE_c_ij, XML_Node::name(), XML_Node::nChildren(), Cantera::npos, PhaseCombo_Interaction::numBinaryInteractions_, PhaseCombo_Interaction::resizeNumInteractions(), Phase::speciesIndex(), and Phase::speciesName().
Referenced by PhaseCombo_Interaction::initThermoXML().
void resizeNumInteractions (const size_t num) private
Resize internal arrays within the object that depend upon the number of binary Margules interaction terms.
Parameters
num Number of binary Margules interaction terms
Definition at line 1128 of file PhaseCombo_Interaction.cpp.
References PhaseCombo_Interaction::m_HE_b_ij, PhaseCombo_Interaction::m_HE_c_ij, PhaseCombo_Interaction::m_HE_d_ij, PhaseCombo_Interaction::m_pSpecies_A_ij, PhaseCombo_Interaction::m_pSpecies_B_ij, PhaseCombo_Interaction::m_SE_b_ij, PhaseCombo_Interaction::m_SE_c_ij, PhaseCombo_Interaction::m_SE_d_ij, PhaseCombo_Interaction::m_VHE_b_ij, PhaseCombo_Interaction::m_VHE_c_ij, PhaseCombo_Interaction::m_VHE_d_ij, PhaseCombo_Interaction::m_VSE_b_ij, PhaseCombo_Interaction::m_VSE_c_ij, PhaseCombo_Interaction::m_VSE_d_ij, Cantera::npos, and PhaseCombo_Interaction::numBinaryInteractions_.
Referenced by PhaseCombo_Interaction::readXMLBinarySpecies().
void initLengths () private
Initialize lengths of local variables after all species have been identified.
Definition at line 661 of file PhaseCombo_Interaction.cpp.
References GibbsExcessVPSSTP::dlnActCoeffdlnN_, Phase::m_kk, Phase::nSpecies(), and Array2D::resize().
Referenced by PhaseCombo_Interaction::initThermo().
void s_update_lnActCoeff () const private
Update the activity coefficients.
This function will be called to update the internally stored natural logarithm of the activity coefficients
Definition at line 752 of file PhaseCombo_Interaction.cpp.
References Cantera::GasConstant, GibbsExcessVPSSTP::lnActCoeff_Scaled_, PhaseCombo_Interaction::m_HE_b_ij, PhaseCombo_Interaction::m_HE_c_ij, Phase::m_kk, PhaseCombo_Interaction::m_pSpecies_A_ij, PhaseCombo_Interaction::m_pSpecies_B_ij, PhaseCombo_Interaction::m_SE_b_ij, PhaseCombo_Interaction::m_SE_c_ij, ckr::max(), GibbsExcessVPSSTP::moleFractions_, PhaseCombo_Interaction::numBinaryInteractions_, Phase::temperature(), and Cantera::xxSmall.
Referenced by PhaseCombo_Interaction::getActivityCoefficients(), PhaseCombo_Interaction::getChemPotentials(), PhaseCombo_Interaction::getPartialMolarCp(), PhaseCombo_Interaction::getPartialMolarEnthalpies(), and PhaseCombo_Interaction::getPartialMolarEntropies().
void s_update_dlnActCoeff_dT () const private
Update the derivative of the log of the activity coefficients wrt T.
This function will be called to update the internally stored derivative of the natural logarithm of the activity coefficients wrt temperature.
Definition at line 802 of file PhaseCombo_Interaction.cpp.
References GibbsExcessVPSSTP::d2lnActCoeffdT2_Scaled_, GibbsExcessVPSSTP::dlnActCoeffdT_Scaled_, Cantera::GasConstant, PhaseCombo_Interaction::m_HE_b_ij, PhaseCombo_Interaction::m_HE_c_ij, Phase::m_kk, PhaseCombo_Interaction::m_pSpecies_A_ij, PhaseCombo_Interaction::m_pSpecies_B_ij, GibbsExcessVPSSTP::moleFractions_, PhaseCombo_Interaction::numBinaryInteractions_, and Phase::temperature().
Referenced by PhaseCombo_Interaction::getd2lnActCoeffdT2(), PhaseCombo_Interaction::getdlnActCoeffds(), PhaseCombo_Interaction::getdlnActCoeffdT(), PhaseCombo_Interaction::getPartialMolarCp(), PhaseCombo_Interaction::getPartialMolarEnthalpies(), and PhaseCombo_Interaction::getPartialMolarEntropies().
void s_update_dlnActCoeff_dlnX_diag () const private
Update the derivative of the log of the activity coefficients wrt log(mole fraction)
This function will be called to update the internally stored derivative of the natural logarithm of the activity coefficients wrt logarithm of the mole fractions.
Definition at line 1060 of file PhaseCombo_Interaction.cpp.
References GibbsExcessVPSSTP::dlnActCoeffdlnX_diag_, Cantera::GasConstant, PhaseCombo_Interaction::m_HE_b_ij, PhaseCombo_Interaction::m_HE_c_ij, Phase::m_kk, PhaseCombo_Interaction::m_pSpecies_A_ij, PhaseCombo_Interaction::m_pSpecies_B_ij, PhaseCombo_Interaction::m_SE_b_ij, PhaseCombo_Interaction::m_SE_c_ij, GibbsExcessVPSSTP::moleFractions_, PhaseCombo_Interaction::numBinaryInteractions_, and Phase::temperature().
Referenced by PhaseCombo_Interaction::getdlnActCoeffdlnX_diag().
void s_update_dlnActCoeff_dlnN_diag () const private
Update the derivative of the log of the activity coefficients wrt log(moles) - diagonal only.
This function will be called to update the internally stored diagonal entries for the derivative of the natural logarithm of the activity coefficients wrt logarithm of the moles.
Definition at line 934 of file PhaseCombo_Interaction.cpp.
References GibbsExcessVPSSTP::dlnActCoeffdlnN_diag_, Cantera::GasConstant, PhaseCombo_Interaction::m_HE_b_ij, PhaseCombo_Interaction::m_HE_c_ij, Phase::m_kk, PhaseCombo_Interaction::m_pSpecies_A_ij, PhaseCombo_Interaction::m_pSpecies_B_ij, PhaseCombo_Interaction::m_SE_b_ij, PhaseCombo_Interaction::m_SE_c_ij, ckr::max(), GibbsExcessVPSSTP::moleFractions_, PhaseCombo_Interaction::numBinaryInteractions_, Phase::temperature(), and Cantera::xxSmall.
Referenced by PhaseCombo_Interaction::getdlnActCoeffdlnN_diag().
void s_update_dlnActCoeff_dlnN () const private
Update the derivative of the log of the activity coefficients wrt log(moles_m)
This function will be called to update the internally stored derivative of the natural logarithm of the activity coefficients wrt logarithm of the mole number of species
Definition at line 993 of file PhaseCombo_Interaction.cpp.
References GibbsExcessVPSSTP::dlnActCoeffdlnN_, Cantera::GasConstant, PhaseCombo_Interaction::m_HE_b_ij, PhaseCombo_Interaction::m_HE_c_ij, Phase::m_kk, PhaseCombo_Interaction::m_pSpecies_A_ij, PhaseCombo_Interaction::m_pSpecies_B_ij, PhaseCombo_Interaction::m_SE_b_ij, PhaseCombo_Interaction::m_SE_c_ij, ckr::max(), GibbsExcessVPSSTP::moleFractions_, PhaseCombo_Interaction::numBinaryInteractions_, Phase::temperature(), Cantera::xxSmall, and Array2D::zero().
Referenced by PhaseCombo_Interaction::getdlnActCoeffdlnN().
doublereal err (std::string msg) const private
Error function.
Print an error string and exit
Parameters
msg Message to be printed
Definition at line 631 of file PhaseCombo_Interaction.cpp.
References PhaseCombo_Interaction::eosType(), and Cantera::int2str().
void setPressure (doublereal p) virtual inherited
Set the internally stored pressure (Pa) at constant temperature and composition.
This method sets the pressure within the object. The water model is a completely compressible model. Also, the dielectric constant is pressure dependent.
Parameters
p input Pressure (Pa)
Todo:
Implement a variable pressure capability
Reimplemented from VPStandardStateTP.
Reimplemented in IonsFromNeutralVPSSTP.
Definition at line 181 of file GibbsExcessVPSSTP.cpp.
References GibbsExcessVPSSTP::setState_TP(), and Phase::temperature().
void calcDensity () protected virtual inherited
Calculate the density of the mixture using the partial molar volumes and mole fractions as input.
The formula for this is
\[ \rho = \frac{\sum_k{X_k W_k}}{\sum_k{X_k V_k}} \]
where \(X_k\) are the mole fractions, \(W_k\) are the molecular weights, and \(V_k\) are the pure species molar volumes.
Note, the basis behind this formula is that in an ideal solution the partial molar volumes are equal to the pure species molar volumes. We have additionally specified in this class that the pure species molar volumes are independent of temperature and pressure.
NOTE: This is a non-virtual function, which is not a member of the ThermoPhase base class.
Reimplemented from VPStandardStateTP.
Definition at line 186 of file GibbsExcessVPSSTP.cpp.
References GibbsExcessVPSSTP::getPartialMolarVolumes(), Phase::m_kk, Phase::meanMolecularWeight(), GibbsExcessVPSSTP::moleFractions_, and Phase::setDensity().
Referenced by GibbsExcessVPSSTP::setState_TP().
void getActivityConcentrations (doublereal * c) const virtual inherited
This method returns an array of generalized concentrations.
\(C^a_k\) are defined such that \(a_k = C^a_k / C^0_k, \) where \(C^0_k \) is a standard concentration defined below and \(a_k \) are activities used in the thermodynamic functions. These activity (or generalized) concentrations are used by kinetics manager classes to compute the forward and reverse rates of elementary reactions. Note that they may or may not have units of concentration — they might be partial pressures, mole fractions, or surface coverages, for example.
Parameters
c Output array of generalized concentrations. The units depend upon the implementation of the reaction rate expressions within the phase.
Reimplemented from ThermoPhase.
Definition at line 226 of file GibbsExcessVPSSTP.cpp.
References GibbsExcessVPSSTP::getActivities().
doublereal standardConcentration (size_t k = 0) const virtual inherited
The standard concentration \(C^0_k \) used to normalize the generalized concentration.
In many cases, this quantity will be the same for all species in a phase - for example, for an ideal gas \(C^0_k = P/\hat R T \). For this reason, this method returns a single value, instead of an array. However, for phases in which the standard concentration is species-specific (e.g. surface species of different sizes), this method may be called with an optional parameter indicating the species.
The standard concentration for defaulted to 1. In other words the activity concentration is assumed to be 1.
Parameters
k species index. Defaults to zero.
Reimplemented from ThermoPhase.
Reimplemented in PseudoBinaryVPSSTP.
Definition at line 232 of file GibbsExcessVPSSTP.cpp.
doublereal logStandardConc (size_t k = 0) const virtual inherited
Returns the natural logarithm of the standard concentration of the kth species.
Parameters
k species index
Reimplemented from ThermoPhase.
Reimplemented in PseudoBinaryVPSSTP.
Definition at line 237 of file GibbsExcessVPSSTP.cpp.
void getUnitsStandardConc (double * uA, int k = 0, int sizeUA = 6) const virtual inherited
Returns the units of the standard and generalized concentrations Note they have the same units, as their ratio is defined to be equal to the activity of the kth species in the solution, which is unitless.
This routine is used in print out applications where the units are needed. Usually, MKS units are assumed throughout the program and in the XML input files.
Parameters
uA Output vector containing the units uA[0] = kmol units - default = 1 uA[1] = m units - default = -nDim(), the number of spatial dimensions in the Phase class. uA[2] = kg units - default = 0; uA[3] = Pa(pressure) units - default = 0; uA[4] = Temperature units - default = 0; uA[5] = time units - default = 0
k species index. Defaults to 0.
sizeUA output int containing the size of the vector. Currently, this is equal to 6.
Reimplemented from ThermoPhase.
Definition at line 343 of file GibbsExcessVPSSTP.cpp.
void getActivities (doublereal * ac) const virtual inherited
Get the array of non-dimensional activities (molality based for this class and classes that derive from it) at the current solution temperature, pressure, and solution concentration.
\[ a_i^\triangle = \gamma_k^{\triangle} \frac{m_k}{m^\triangle} \]
This function must be implemented in derived classes.
Parameters
ac Output vector of molality-based activities. Length: m_kk.
Reimplemented from ThermoPhase.
Definition at line 242 of file GibbsExcessVPSSTP.cpp.
References DATA_PTR, GibbsExcessVPSSTP::getActivityCoefficients(), Phase::getMoleFractions(), Phase::m_kk, and GibbsExcessVPSSTP::moleFractions_.
Referenced by GibbsExcessVPSSTP::getActivityConcentrations(), PseudoBinaryVPSSTP::report(), and MolarityIonicVPSSTP::report().
virtual void getdlnActCoeffdlnX (doublereal * dlnActCoeffdlnX) const inline virtual inherited
Get the array of log concentration-like derivatives of the log activity coefficients.
This function is a virtual method. For ideal mixtures (unity activity coefficients), this can return zero. Implementations should take the derivative of the logarithm of the activity coefficient with respect to the logarithm of the concentration-like variable (i.e. number of moles in in a unit volume.) that represents the standard state. This quantity is to be used in conjunction with derivatives of that concentration-like variable when the derivative of the chemical potential is taken.
units = dimensionless
Parameters
dlnActCoeffdlnX Output vector of derivatives of the log Activity Coefficients. length = m_kk
Definition at line 392 of file GibbsExcessVPSSTP.h.
References GibbsExcessVPSSTP::err().
void setState_TP (doublereal t, doublereal p) virtual inherited
Set the temperature (K) and pressure (Pa)
Set the temperature and pressure.
Parameters
t Temperature (K)
p Pressure (Pa)
Reimplemented from VPStandardStateTP.
Reimplemented in IonsFromNeutralVPSSTP.
Definition at line 202 of file GibbsExcessVPSSTP.cpp.
References GibbsExcessVPSSTP::calcDensity(), VPStandardStateTP::m_Pcurrent, Phase::setTemperature(), and VPStandardStateTP::updateStandardStateThermo().
Referenced by GibbsExcessVPSSTP::setPressure().
void setMassFractions (const doublereal *const y) virtual inherited
Set the mass fractions to the specified values, and then normalize them so that they sum to 1.0.
Parameters
y Array of unnormalized mass fraction values (input). Must have a length greater than or equal to the number of species.
y Input vector of mass fractions. Length is m_kk.
Reimplemented from Phase.
Reimplemented in IonsFromNeutralVPSSTP.
Definition at line 119 of file GibbsExcessVPSSTP.cpp.
References DATA_PTR, Phase::getMoleFractions(), GibbsExcessVPSSTP::moleFractions_, and Phase::setMassFractions().
Referenced by IonsFromNeutralVPSSTP::setMassFractions().
void setMassFractions_NoNorm (const doublereal *const y) virtual inherited
Set the mass fractions to the specified values without normalizing.
This is useful when the normalization condition is being handled by some other means, for example by a constraint equation as part of a larger set of equations.
Parameters
y Input vector of mass fractions. Length is m_kk.
Reimplemented from Phase.
Reimplemented in IonsFromNeutralVPSSTP.
Definition at line 125 of file GibbsExcessVPSSTP.cpp.
References DATA_PTR, Phase::getMoleFractions(), GibbsExcessVPSSTP::moleFractions_, and Phase::setMassFractions_NoNorm().
Referenced by IonsFromNeutralVPSSTP::setMassFractions_NoNorm().
void setMoleFractions (const doublereal *const x) virtual inherited
Set the mole fractions to the specified values, and then normalize them so that they sum to 1.0.
Parameters
x Array of unnormalized mole fraction values (input). Must have a length greater than or equal to the number of species.
x Input vector of mole fractions. Length is m_kk.
Reimplemented from Phase.
Reimplemented in IonsFromNeutralVPSSTP.
Definition at line 131 of file GibbsExcessVPSSTP.cpp.
References DATA_PTR, Phase::getMoleFractions(), GibbsExcessVPSSTP::moleFractions_, and Phase::setMoleFractions().
Referenced by IonsFromNeutralVPSSTP::setMoleFractions().
void setMoleFractions_NoNorm (const doublereal *const x) virtual inherited
Set the mole fractions to the specified values without normalizing.
This is useful when the normalization condition is being handled by some other means, for example by a constraint equation as part of a larger set of equations.
Parameters
x Input vector of mole fractions. Length is m_kk.
Reimplemented from Phase.
Reimplemented in IonsFromNeutralVPSSTP.
Definition at line 137 of file GibbsExcessVPSSTP.cpp.
References DATA_PTR, Phase::getMoleFractions(), GibbsExcessVPSSTP::moleFractions_, and Phase::setMoleFractions_NoNorm().
Referenced by IonsFromNeutralVPSSTP::setMoleFractions_NoNorm().
void setConcentrations (const doublereal *const c) virtual inherited
Set the concentrations to the specified values within the phase.
Parameters
c The input vector to this routine is in dimensional units. For volumetric phases c[k] is the concentration of the kth species in kmol/m3. For surface phases, c[k] is the concentration in kmol/m2. The length of the vector is the number of species in the phase.
Reimplemented from Phase.
Reimplemented in IonsFromNeutralVPSSTP.
Definition at line 144 of file GibbsExcessVPSSTP.cpp.
References DATA_PTR, Phase::getMoleFractions(), GibbsExcessVPSSTP::moleFractions_, and Phase::setConcentrations().
Referenced by IonsFromNeutralVPSSTP::setConcentrations().
double checkMFSum (const doublereal *const x) const protected inherited
utility routine to check mole fraction sum
Parameters
x vector of mole fractions.
Definition at line 311 of file GibbsExcessVPSSTP.cpp.
References Cantera::fp2str(), and Phase::m_kk.
int standardStateConvention () const virtual inherited
This method returns the convention used in specification of the standard state, of which there are currently two, temperature based, and variable pressure based.
Currently, there are two standard state conventions:
Temperature-based activities cSS_CONVENTION_TEMPERATURE 0
default
Variable Pressure and Temperature -based activities cSS_CONVENTION_VPSS 1
Reimplemented from ThermoPhase.
Definition at line 163 of file VPStandardStateTP.cpp.
References Cantera::cSS_CONVENTION_VPSS.
void getChemPotentials_RT (doublereal * mu) const virtual inherited
Get the array of non-dimensional species chemical potentials These are partial molar Gibbs free energies.
\(\mu_k / \hat R T \). Units: unitless
We close the loop on this function, here, calling getChemPotentials() and then dividing by RT. No need for child classes to handle.
Parameters
mu Output vector of non-dimensional species chemical potentials Length: m_kk.
Reimplemented from ThermoPhase.
Definition at line 194 of file VPStandardStateTP.cpp.
References ThermoPhase::_RT(), ThermoPhase::getChemPotentials(), and Phase::m_kk.
void getStandardChemPotentials (doublereal * mu) const virtual inherited
Get the array of chemical potentials at unit activity.
These are the standard state chemical potentials \(\mu^0_k(T,P) \). The values are evaluated at the current temperature and pressure.
Parameters
mu Output vector of standard state chemical potentials. length = m_kk. units are J / kmol.
Reimplemented from ThermoPhase.
Definition at line 206 of file VPStandardStateTP.cpp.
References ThermoPhase::_RT(), VPStandardStateTP::getGibbs_RT(), and Phase::m_kk.
Referenced by MolarityIonicVPSSTP::getChemPotentials(), IdealSolnGasVPSS::getChemPotentials(), RedlichKisterVPSSTP::getChemPotentials(), MargulesVPSSTP::getChemPotentials(), MixedSolventElectrolyte::getChemPotentials(), PhaseCombo_Interaction::getChemPotentials(), IdealMolalSoln::getChemPotentials(), DebyeHuckel::getChemPotentials(), HMWSoln::getChemPotentials(), PseudoBinaryVPSSTP::report(), MolarityIonicVPSSTP::report(), MolalityVPSSTP::report(), and MolalityVPSSTP::reportCSV().
void getEnthalpy_RT (doublereal * hrt) const inline virtual inherited
Get the nondimensional Enthalpy functions for the species at their standard states at the current T and P of the solution.
Parameters
hrt Output vector of standard state enthalpies. length = m_kk. units are unitless.
Reimplemented from ThermoPhase.
Definition at line 216 of file VPStandardStateTP.cpp.
References VPSSMgr::getEnthalpy_RT(), VPStandardStateTP::m_VPSS_ptr, and VPStandardStateTP::updateStandardStateThermo().
Referenced by IdealSolnGasVPSS::getPartialMolarEnthalpies(), MolarityIonicVPSSTP::getPartialMolarEnthalpies(), IonsFromNeutralVPSSTP::getPartialMolarEnthalpies(), RedlichKisterVPSSTP::getPartialMolarEnthalpies(), MargulesVPSSTP::getPartialMolarEnthalpies(), MixedSolventElectrolyte::getPartialMolarEnthalpies(), PhaseCombo_Interaction::getPartialMolarEnthalpies(), IdealMolalSoln::getPartialMolarEnthalpies(), DebyeHuckel::getPartialMolarEnthalpies(), HMWSoln::getPartialMolarEnthalpies(), and HMWSoln::relative_enthalpy().
void getEntropy_R (doublereal * sr) const virtual inherited
Get the array of nondimensional Enthalpy functions for the standard state species at the current T and P of the solution.
Parameters
sr Output vector of nondimensional standard state entropies. length = m_kk.
Reimplemented from ThermoPhase.
Definition at line 239 of file VPStandardStateTP.cpp.
References VPSSMgr::getEntropy_R(), VPStandardStateTP::m_VPSS_ptr, and VPStandardStateTP::updateStandardStateThermo().
Referenced by IdealSolnGasVPSS::getPartialMolarEntropies(), MolarityIonicVPSSTP::getPartialMolarEntropies(), IonsFromNeutralVPSSTP::getPartialMolarEntropies(), RedlichKisterVPSSTP::getPartialMolarEntropies(), MargulesVPSSTP::getPartialMolarEntropies(), MixedSolventElectrolyte::getPartialMolarEntropies(), PhaseCombo_Interaction::getPartialMolarEntropies(), IdealMolalSoln::getPartialMolarEntropies(), DebyeHuckel::getPartialMolarEntropies(), and HMWSoln::getPartialMolarEntropies().
void getGibbs_RT (doublereal * grt) const inline virtual inherited
Get the nondimensional Gibbs functions for the species at their standard states of solution at the current T and P of the solution.
Parameters
grt Output vector of nondimensional standard state Gibbs free energies. length = m_kk.
Reimplemented from ThermoPhase.
Definition at line 246 of file VPStandardStateTP.cpp.
References VPSSMgr::getGibbs_RT(), VPStandardStateTP::m_VPSS_ptr, and VPStandardStateTP::updateStandardStateThermo().
Referenced by VPStandardStateTP::getStandardChemPotentials().
void getPureGibbs (doublereal * gpure) const inline virtual inherited
Get the standard state Gibbs functions for each species at the current T and P.
(Note resolved at this level)
Parameters
gpure Output vector of standard state Gibbs free energies. length = m_kk. units are J/kmol.
Reimplemented from ThermoPhase.
Definition at line 253 of file VPStandardStateTP.cpp.
References VPSSMgr::getStandardChemPotentials(), VPStandardStateTP::m_VPSS_ptr, and VPStandardStateTP::updateStandardStateThermo().
void getIntEnergy_RT (doublereal * urt) const virtual inherited
Returns the vector of nondimensional internal Energies of the standard state at the current temperature and pressure of the solution for each species.
\[ u^{ss}_k(T,P) = h^{ss}_k(T) - P * V^{ss}_k \]
Parameters
urt Output vector of nondimensional standard state internal energies. length = m_kk.
Reimplemented from ThermoPhase.
Definition at line 259 of file VPStandardStateTP.cpp.
References VPSSMgr::getIntEnergy_RT(), VPStandardStateTP::m_VPSS_ptr, and VPStandardStateTP::updateStandardStateThermo().
Referenced by IdealSolnGasVPSS::getPartialMolarIntEnergies().
void getCp_R (doublereal * cpr) const virtual inherited
Get the nondimensional Heat Capacities at constant pressure for the standard state of the species at the current T and P.
This is redefined here to call the internal function, _updateStandardStateThermo(), which calculates all standard state properties at the same time.
Parameters
cpr Output vector containing the the nondimensional Heat Capacities at constant pressure for the standard state of the species. Length: m_kk.
Reimplemented from ThermoPhase.
Definition at line 265 of file VPStandardStateTP.cpp.
References VPSSMgr::getCp_R(), VPStandardStateTP::m_VPSS_ptr, and VPStandardStateTP::updateStandardStateThermo().
Referenced by IdealSolnGasVPSS::getPartialMolarCp(), MolarityIonicVPSSTP::getPartialMolarCp(), RedlichKisterVPSSTP::getPartialMolarCp(), MargulesVPSSTP::getPartialMolarCp(), MixedSolventElectrolyte::getPartialMolarCp(), PhaseCombo_Interaction::getPartialMolarCp(), IdealMolalSoln::getPartialMolarCp(), DebyeHuckel::getPartialMolarCp(), and HMWSoln::getPartialMolarCp().
void getStandardVolumes (doublereal * vol) const virtual inherited
Get the molar volumes of each species in their standard states at the current T and P of the solution.
units = m^3 / kmol
This is redefined here to call the internal function, _updateStandardStateThermo(), which calculates all standard state properties at the same time.
Parameters
vol Output vector of species volumes. length = m_kk. units = m^3 / kmol
Reimplemented from ThermoPhase.
Definition at line 271 of file VPStandardStateTP.cpp.
References VPSSMgr::getStandardVolumes(), VPStandardStateTP::m_VPSS_ptr, and VPStandardStateTP::updateStandardStateThermo().
Referenced by IdealSolnGasVPSS::getPartialMolarVolumes(), MolarityIonicVPSSTP::getPartialMolarVolumes(), GibbsExcessVPSSTP::getPartialMolarVolumes(), RedlichKisterVPSSTP::getPartialMolarVolumes(), MargulesVPSSTP::getPartialMolarVolumes(), MixedSolventElectrolyte::getPartialMolarVolumes(), IdealMolalSoln::getPartialMolarVolumes(), PhaseCombo_Interaction::getPartialMolarVolumes(), DebyeHuckel::getPartialMolarVolumes(), HMWSoln::getPartialMolarVolumes(), and HMWSoln::standardConcentration().
void setTemperature (const doublereal temp) virtual inherited
Set the temperature of the phase.
Currently this passes down to setState_TP(). It does not make sense to calculate the standard state without first setting T and P.
Parameters
temp Temperature (kelvin)
Reimplemented from Phase.
Reimplemented in HMWSoln, DebyeHuckel, and IonsFromNeutralVPSSTP.
Definition at line 392 of file VPStandardStateTP.cpp.
References VPStandardStateTP::m_Pcurrent, VPStandardStateTP::setState_TP(), and VPStandardStateTP::updateStandardStateThermo().
doublereal pressure () const inline virtual inherited
Returns the current pressure of the phase.
The pressure is an independent variable in this phase. Its current value is stored in the object VPStandardStateTP.
Returns
return the pressure in pascals.
Reimplemented from ThermoPhase.
Definition at line 340 of file VPStandardStateTP.h.
References VPStandardStateTP::m_Pcurrent.
Referenced by IdealSolnGasVPSS::intEnergy_mole(), IonsFromNeutralVPSSTP::intEnergy_mole(), PseudoBinaryVPSSTP::report(), MolarityIonicVPSSTP::report(), MolalityVPSSTP::report(), MolalityVPSSTP::reportCSV(), IonsFromNeutralVPSSTP::setTemperature(), and IdealSolnGasVPSS::standardConcentration().
void _updateStandardStateThermo () const protected virtual inherited
Updates the standard state thermodynamic functions at the current T and P of the solution.
If m_useTmpStandardStateStorage is true, this function must be called for every call to functions in this class.
This function is responsible for updating the following internal members, when m_useTmpStandardStateStorage is true.
m_hss_RT;
m_cpss_R;
m_gss_RT;
m_sss_R;
m_Vss
This function doesn't check to see if the temperature or pressure has changed. It automatically assumes that it has changed. If m_useTmpStandardStateStorage is not true, this function may be required to be called by child classes to update internal member data..
Definition at line 517 of file VPStandardStateTP.cpp.
References AssertThrowMsg, VPStandardStateTP::m_Pcurrent, VPStandardStateTP::m_Plast_ss, VPStandardStateTP::m_Tlast_ss, VPStandardStateTP::m_VPSS_ptr, VPSSMgr::setState_TP(), and Phase::temperature().
Referenced by IdealMolalSoln::getActivities(), DebyeHuckel::getActivities(), DebyeHuckel::getMolalityActivityCoefficients(), DebyeHuckel::setState_TP(), and VPStandardStateTP::updateStandardStateThermo().
void updateStandardStateThermo () const virtual inherited
Updates the standard state thermodynamic functions at the current T and P of the solution.
If m_useTmpStandardStateStorage is true, this function must be called for every call to functions in this class. It checks to see whether the temperature or pressure has changed and thus the ss thermodynamics functions for all of the species must be recalculated.
This function is responsible for updating the following internal members, when m_useTmpStandardStateStorage is true.
m_hss_RT;
m_cpss_R;
m_gss_RT;
m_sss_R;
m_Vss
If m_useTmpStandardStateStorage is not true, this function may be required to be called by child classes to update internal member data.
Definition at line 527 of file VPStandardStateTP.cpp.
References VPStandardStateTP::_updateStandardStateThermo(), VPStandardStateTP::m_Pcurrent, VPStandardStateTP::m_Plast_ss, VPStandardStateTP::m_Tlast_ss, and Phase::temperature().
Referenced by IdealSolnGasVPSS::cp_mole(), IdealSolnGasVPSS::enthalpy_mole(), IdealSolnGasVPSS::entropy_mole(), HMWSoln::getActivities(), VPStandardStateTP::getCp_R(), VPStandardStateTP::getCp_R_ref(), VPStandardStateTP::getEnthalpy_RT(), VPStandardStateTP::getEnthalpy_RT_ref(), VPStandardStateTP::getEntropy_R(), VPStandardStateTP::getEntropy_R_ref(), VPStandardStateTP::getGibbs_ref(), VPStandardStateTP::getGibbs_RT(), VPStandardStateTP::getGibbs_RT_ref(), VPStandardStateTP::getIntEnergy_RT(), VPStandardStateTP::getPureGibbs(), VPStandardStateTP::getStandardVolumes(), VPStandardStateTP::getStandardVolumes_ref(), HMWSoln::getUnscaledMolalityActivityCoefficients(), IdealSolnGasVPSS::setPressure(), VPStandardStateTP::setPressure(), VPStandardStateTP::setState_TP(), IdealMolalSoln::setState_TP(), GibbsExcessVPSSTP::setState_TP(), HMWSoln::setState_TP(), VPStandardStateTP::setTemperature(), IdealSolnGasVPSS::setToEquilState(), MolalityVPSSTP::setToEquilState(), and HMWSoln::setToEquilState().
void getEnthalpy_RT_ref (doublereal * hrt) const virtual inherited
Returns the vector of nondimensional enthalpies of the reference state at the current temperature of the solution and the reference pressure for the species.
There are also temporary variables for holding the species reference-state values of Cp, H, S, and V at the last temperature and reference pressure called. These functions are not recalculated if a new call is made using the previous temperature. All calculations are done within the routine _updateRefStateThermo().
Parameters
hrt Output vector contains the nondimensional enthalpies of the reference state of the species length = m_kk, units = dimensionless.
Reimplemented from ThermoPhase.
Definition at line 286 of file VPStandardStateTP.cpp.
References VPSSMgr::getEnthalpy_RT_ref(), VPStandardStateTP::m_VPSS_ptr, and VPStandardStateTP::updateStandardStateThermo().
void getGibbs_RT_ref (doublereal * grt) const virtual inherited
Returns the vector of nondimensional Gibbs free energies of the reference state at the current temperature of the solution and the reference pressure for the species.
Parameters
grt Output vector contains the nondimensional Gibbs free energies of the reference state of the species length = m_kk, units = dimensionless.
Reimplemented from ThermoPhase.
Definition at line 297 of file VPStandardStateTP.cpp.
References VPSSMgr::getGibbs_RT_ref(), VPStandardStateTP::m_VPSS_ptr, and VPStandardStateTP::updateStandardStateThermo().
void getGibbs_ref (doublereal * g) const virtual inherited
Returns the vector of the gibbs function of the reference state at the current temperature of the solution and the reference pressure for the species. units = J/kmol
Parameters
g Output vector contain the Gibbs free energies of the reference state of the species length = m_kk, units = J/kmol.
Reimplemented from ThermoPhase.
Definition at line 312 of file VPStandardStateTP.cpp.
References VPSSMgr::getGibbs_ref(), VPStandardStateTP::m_VPSS_ptr, and VPStandardStateTP::updateStandardStateThermo().
void getEntropy_R_ref (doublereal * er) const virtual inherited
Returns the vector of nondimensional entropies of the reference state at the current temperature of the solution and the reference pressure for the species.
Parameters
er Output vector contain the nondimensional entropies of the species in their reference states length: m_kk, units: dimensionless.
Reimplemented from ThermoPhase.
Definition at line 329 of file VPStandardStateTP.cpp.
References VPSSMgr::getEntropy_R_ref(), VPStandardStateTP::m_VPSS_ptr, and VPStandardStateTP::updateStandardStateThermo().
void getCp_R_ref (doublereal * cprt) const virtual inherited
Returns the vector of nondimensional constant pressure heat capacities of the reference state at the current temperature of the solution and reference pressure for the species.
Parameters
cprt Output vector contains the nondimensional heat capacities of the species in their reference states length: m_kk, units: dimensionless.
Reimplemented from ThermoPhase.
Definition at line 341 of file VPStandardStateTP.cpp.
References VPSSMgr::getCp_R_ref(), VPStandardStateTP::m_VPSS_ptr, and VPStandardStateTP::updateStandardStateThermo().
void getStandardVolumes_ref (doublereal * vol) const virtual inherited
Get the molar volumes of the species reference states at the current T and P_ref of the solution.
units = m^3 / kmol
Parameters
vol Output vector containing the standard state volumes. Length: m_kk.
Reimplemented from ThermoPhase.
Definition at line 353 of file VPStandardStateTP.cpp.
References VPSSMgr::getStandardVolumes_ref(), VPStandardStateTP::m_VPSS_ptr, and VPStandardStateTP::updateStandardStateThermo().
virtual void setParametersFromXML (const XML_Node & eosdata) inline virtual inherited
Set equation of state parameter values from XML entries.
The following methods are used in the process of constructing the phase and setting its parameters from a specification in an input file. They are not normally used in application programs. To see how they are used, see files importCTML.cpp and ThermoFactory.cpp. This method is called by function importPhase in file importCTML.cpp when processing a phase definition in an input file. It should be overloaded in subclasses to set any parameters that are specific to that particular phase model.
Parameters
eosdata An XML_Node object corresponding to the "thermo" entry for this phase in the input file.
Reimplemented from ThermoPhase.
Reimplemented in HMWSoln, DebyeHuckel, IdealMolalSoln, and IdealSolnGasVPSS.
Definition at line 521 of file VPStandardStateTP.h.
Referenced by IdealSolnGasVPSS::setParametersFromXML().
void setVPSSMgr (VPSSMgr * vp_ptr) inherited
set the VPSS Mgr
Parameters
vp_ptr Pointer to the manager
Definition at line 376 of file VPStandardStateTP.cpp.
References VPStandardStateTP::m_VPSS_ptr.
Referenced by Cantera::importPhase().
VPSSMgr * provideVPSSMgr () inherited
Return a pointer to the VPSSMgr for this phase.
Returns
Returns a pointer to the VPSSMgr for this phase
Definition at line 498 of file VPStandardStateTP.cpp.
References VPStandardStateTP::m_VPSS_ptr.
Referenced by PDSS::initThermo(), and PDSS::PDSS().
virtual doublereal refPressure () const inline virtual inherited
Returns the reference pressure in Pa.
This function is a wrapper that calls the species thermo refPressure function.
Reimplemented in LatticeSolidPhase.
Definition at line 164 of file ThermoPhase.h.
References ThermoPhase::m_spthermo, and SpeciesThermo::refPressure().
Referenced by MixtureFugacityTP::_updateReferenceStateThermo(), RedlichKwongMFTP::getChemPotentials(), RedlichKwongMFTP::getPartialMolarEntropies(), MixtureFugacityTP::getStandardVolumes_ref(), ChemEquil::initialize(), IdealSolidSolnPhase::initLengths(), ConstDensityThermo::initThermo(), StoichSubstance::initThermo(), StoichSubstanceSSTP::initThermo(), PureFluidPhase::initThermo(), SingleSpeciesTP::initThermo(), IdealGasPhase::initThermo(), LatticePhase::initThermo(), and RedlichKwongMFTP::setToEquilState().
virtual doublereal minTemp (size_t k = npos) const inline virtual inherited
Minimum temperature for which the thermodynamic data for the species or phase are valid.
If no argument is supplied, the value returned will be the lowest temperature at which the data for all species are valid. Otherwise, the value will be only for species k. This function is a wrapper that calls the species thermo minTemp function.
Parameters
k index of the species. Default is -1, which will return the max of the min value over all species.
Reimplemented in LatticeSolidPhase.
Definition at line 181 of file ThermoPhase.h.
References ThermoPhase::m_spthermo, and SpeciesThermo::minTemp().
Referenced by MultiPhase::addPhase(), ChemEquil::equilibrate(), LiquidTransport::initLiquid(), SimpleTransport::initLiquid(), AqueousTransport::initLiquid(), ThermoPhase::setState_HPorUV(), ThermoPhase::setState_SPorSV(), TransportFactory::setupLiquidTransport(), and TransportFactory::setupMM().
doublereal Hf298SS (const int k) const inline inherited
Report the 298 K Heat of Formation of the standard state of one species (J kmol-1)
The 298K Heat of Formation is defined as the enthalpy change to create the standard state of the species from its constituent elements in their standard states at 298 K and 1 bar.
Parameters
k species index
Returns
Returns the current value of the Heat of Formation at 298K and 1 bar
Definition at line 221 of file ThermoPhase.h.
References ThermoPhase::err().
virtual void modifyOneHf298SS (const int k, const doublereal Hf298New) inline virtual inherited
Modify the value of the 298 K Heat of Formation of one species in the phase (J kmol-1)
The 298K heat of formation is defined as the enthalpy change to create the standard state of the species from its constituent elements in their standard states at 298 K and 1 bar.
Parameters
k Species k
Hf298New Specify the new value of the Heat of Formation at 298K and 1 bar
Definition at line 233 of file ThermoPhase.h.
References ThermoPhase::err().
virtual doublereal maxTemp (size_t k = npos) const inline virtual inherited
Maximum temperature for which the thermodynamic data for the species are valid.
If no argument is supplied, the value returned will be the highest temperature at which the data for all species are valid. Otherwise, the value will be only for species k. This function is a wrapper that calls the species thermo maxTemp function.
Parameters
k index of the species. Default is -1, which will return the min of the max value over all species.
Reimplemented in LatticeSolidPhase.
Definition at line 250 of file ThermoPhase.h.
References ThermoPhase::m_spthermo, and SpeciesThermo::maxTemp().
Referenced by MultiPhase::addPhase(), ChemEquil::equilibrate(), LiquidTransport::initLiquid(), SimpleTransport::initLiquid(), AqueousTransport::initLiquid(), ThermoPhase::setState_HPorUV(), ThermoPhase::setState_SPorSV(), TransportFactory::setupLiquidTransport(), and TransportFactory::setupMM().
bool chargeNeutralityNecessary () const inline inherited
Returns the chargeNeutralityNecessity boolean.
Some phases must have zero net charge in order for their thermodynamics functions to be valid. If this is so, then the value returned from this function is true. If this is not the case, then this is false. Now, ideal gases have this parameter set to false, while solution with molality-based activity coefficients have this parameter set to true.
Definition at line 261 of file ThermoPhase.h.
References ThermoPhase::m_chargeNeutralityNecessary.
virtual doublereal intEnergy_mole () const inline virtual inherited
Molar internal energy. Units: J/kmol.
Reimplemented in HMWSoln, DebyeHuckel, IdealGasPhase, LatticePhase, SurfPhase, LatticeSolidPhase, IdealMolalSoln, IdealSolidSolnPhase, IonsFromNeutralVPSSTP, RedlichKwongMFTP, SingleSpeciesTP, StoichSubstance, ConstDensityThermo, IdealSolnGasVPSS, PureFluidPhase, and MetalPhase.
Definition at line 277 of file ThermoPhase.h.
References ThermoPhase::enthalpy_mole(), Phase::molarVolume(), and ThermoPhase::pressure().
Referenced by ThermoPhase::intEnergy_mass(), PseudoBinaryVPSSTP::report(), MolarityIonicVPSSTP::report(), MolalityVPSSTP::report(), ThermoPhase::report(), MolalityVPSSTP::reportCSV(), and ThermoPhase::reportCSV().
virtual doublereal gibbs_mole () const inline virtual inherited
Molar Gibbs function. Units: J/kmol.
Reimplemented in HMWSoln, DebyeHuckel, IdealGasPhase, LatticePhase, LatticeSolidPhase, IdealMolalSoln, IdealSolidSolnPhase, IonsFromNeutralVPSSTP, SingleSpeciesTP, RedlichKwongMFTP, StoichSubstance, ConstDensityThermo, IdealSolnGasVPSS, PureFluidPhase, and MetalPhase.
Definition at line 287 of file ThermoPhase.h.
References ThermoPhase::enthalpy_mole(), ThermoPhase::entropy_mole(), and Phase::temperature().
Referenced by MixtureFugacityTP::corr0(), ThermoPhase::gibbs_mass(), PseudoBinaryVPSSTP::report(), MolarityIonicVPSSTP::report(), MolalityVPSSTP::report(), ThermoPhase::report(), MolalityVPSSTP::reportCSV(), and ThermoPhase::reportCSV().
virtual doublereal isothermalCompressibility () const inline virtual inherited
Returns the isothermal compressibility. Units: 1/Pa.
The isothermal compressibility is defined as
\[ \kappa_T = -\frac{1}{v}\left(\frac{\partial v}{\partial P}\right)_T \]
or
\[ \kappa_T = \frac{1}{\rho}\left(\frac{\partial \rho}{\partial P}\right)_T \]
Reimplemented in HMWSoln, DebyeHuckel, IdealGasPhase, IdealMolalSoln, MetalSHEelectrons, PureFluidPhase, FixedChemPotSSTP, MineralEQ3, StoichSubstanceSSTP, WaterSSTP, RedlichKwongMFTP, and IdealSolnGasVPSS.
Definition at line 348 of file ThermoPhase.h.
References ThermoPhase::err().
Referenced by SingleSpeciesTP::cv_mole().
virtual doublereal thermalExpansionCoeff () const inline virtual inherited
Return the volumetric thermal expansion coefficient. Units: 1/K.
The thermal expansion coefficient is defined as
\[ \beta = \frac{1}{v}\left(\frac{\partial v}{\partial T}\right)_P \]
Reimplemented in HMWSoln, DebyeHuckel, IdealGasPhase, IdealMolalSoln, MetalSHEelectrons, PureFluidPhase, FixedChemPotSSTP, MineralEQ3, StoichSubstanceSSTP, and WaterSSTP.
Definition at line 360 of file ThermoPhase.h.
References ThermoPhase::err().
Referenced by SingleSpeciesTP::cv_mole().
virtual void updateDensity () inline virtual inherited
Deprecated:
Definition at line 366 of file ThermoPhase.h.
References Cantera::deprecatedMethod().
void setElectricPotential (doublereal v) inline inherited
Set the electric potential of this phase (V).
This is used by classes InterfaceKinetics and EdgeKinetics to compute the rates of charge-transfer reactions, and in computing the electrochemical potentials of the species.
Each phase may have its own electric potential.
Parameters
v Input value of the electric potential in Volts
Definition at line 390 of file ThermoPhase.h.
References ThermoPhase::m_phi.
Referenced by InterfaceKinetics::setElectricPotential(), vcs_VolPhase::setElectricPotential(), and vcs_VolPhase::setState_TP().
doublereal electricPotential () const inline inherited
Returns the electric potential of this phase (V).
Units are Volts (which are Joules/coulomb)
Definition at line 398 of file ThermoPhase.h.
References ThermoPhase::m_phi.
Referenced by InterfaceKinetics::_update_rates_phi(), PureFluidPhase::getElectrochemPotentials(), PseudoBinaryVPSSTP::getElectrochemPotentials(), MolarityIonicVPSSTP::getElectrochemPotentials(), GibbsExcessVPSSTP::getElectrochemPotentials(), RedlichKisterVPSSTP::getElectrochemPotentials(), MargulesVPSSTP::getElectrochemPotentials(), MixedSolventElectrolyte::getElectrochemPotentials(), ThermoPhase::getElectrochemPotentials(), MolalityVPSSTP::getElectrochemPotentials(), PhaseCombo_Interaction::getElectrochemPotentials(), PseudoBinaryVPSSTP::report(), MolarityIonicVPSSTP::report(), PureFluidPhase::report(), MolalityVPSSTP::report(), ThermoPhase::report(), PureFluidPhase::reportCSV(), MolalityVPSSTP::reportCSV(), ThermoPhase::reportCSV(), and vcs_VolPhase::setPtrThermoPhase().
int activityConvention () const virtual inherited
This method returns the convention used in specification of the activities, of which there are currently two, molar- and molality-based conventions.
Currently, there are two activity conventions:
Molar-based activities Unit activity of species at either a hypothetical pure solution of the species or at a hypothetical pure ideal solution at infinite dilution cAC_CONVENTION_MOLAR 0
default
Molality-based activities (unit activity of solutes at a hypothetical 1 molal solution referenced to infinite dilution at all pressures and temperatures). cAC_CONVENTION_MOLALITY 1
Reimplemented in MolalityVPSSTP.
Definition at line 143 of file ThermoPhase.cpp.
References Cantera::cAC_CONVENTION_MOLAR.
Referenced by vcs_MultiPhaseEquil::reportCSV(), and LiquidTransport::stefan_maxwell_solve().
void getLnActivityCoefficients (doublereal * lnac) const virtual inherited
Get the array of non-dimensional molar-based ln activity coefficients at the current solution temperature, pressure, and solution concentration.
Parameters
lnac Output vector of ln activity coefficients. Length: m_kk.
Reimplemented in MargulesVPSSTP, RedlichKisterVPSSTP, and MolarityIonicVPSSTP.
Definition at line 166 of file ThermoPhase.cpp.
References ThermoPhase::getActivityCoefficients(), and Phase::m_kk.
Referenced by GibbsExcessVPSSTP::getActivityCoefficients(), IonsFromNeutralVPSSTP::getChemPotentials(), and IonsFromNeutralVPSSTP::s_update_lnActCoeff().
virtual void getPartialMolarIntEnergies (doublereal * ubar) const inline virtual inherited
Return an array of partial molar internal energies for the species in the mixture.
Units: J/kmol.
Parameters
ubar Output vector of species partial molar internal energies. Length = m_kk. units are J/kmol.
Reimplemented in IdealGasPhase, RedlichKwongMFTP, SingleSpeciesTP, IdealSolnGasVPSS, and PureFluidPhase.
Definition at line 650 of file ThermoPhase.h.
References ThermoPhase::err().
Referenced by MolalityVPSSTP::reportCSV(), and ThermoPhase::reportCSV().
virtual void getdPartialMolarVolumes_dT (doublereal * d_vbar_dT) const inline virtual inherited
Return an array of derivatives of partial molar volumes wrt temperature for the species in the mixture.
Units: m^3/kmol.
The derivative is at constant pressure
Parameters
d_vbar_dT Output vector of derivatives of species partial molar volumes wrt T. Length = m_kk. units are m^3/kmol/K.
Definition at line 683 of file ThermoPhase.h.
References ThermoPhase::err().
virtual void getdPartialMolarVolumes_dP (doublereal * d_vbar_dP) const inline virtual inherited
Return an array of derivatives of partial molar volumes wrt pressure for the species in the mixture.
Units: m^3/kmol.
The derivative is at constant temperature
Parameters
d_vbar_dP Output vector of derivatives of species partial molar volumes wrt P. Length = m_kk. units are m^3/kmol/Pa.
Definition at line 695 of file ThermoPhase.h.
References ThermoPhase::err().
virtual void getdStandardVolumes_dT (doublereal * d_vol_dT) const inline virtual inherited
Get the derivative of the molar volumes of the species standard states wrt temperature at the current T and P of the solution.
The derivative is at constant pressure units = m^3 / kmol / K
Parameters
d_vol_dT Output vector containing derivatives of standard state volumes wrt T Length: m_kk.
Definition at line 800 of file ThermoPhase.h.
References ThermoPhase::err().
virtual void getdStandardVolumes_dP (doublereal * d_vol_dP) const inline virtual inherited
Get the derivative molar volumes of the species standard states wrt pressure at the current T and P of the solution.
The derivative is at constant temperature. units = m^3 / kmol / Pa
Parameters
d_vol_dP Output vector containing the derivative of standard state volumes wrt P. Length: m_kk.
Definition at line 813 of file ThermoPhase.h.
References ThermoPhase::err().
virtual void getIntEnergy_RT_ref (doublereal * urt) const inline virtual inherited
Returns the vector of nondimensional internal Energies of the reference state at the current temperature of the solution and the reference pressure for each species.
Parameters
urt Output vector of nondimensional reference state internal energies of the species. Length: m_kk
Reimplemented in IdealSolidSolnPhase, IdealGasPhase, FixedChemPotSSTP, MetalSHEelectrons, MineralEQ3, and StoichSubstanceSSTP.
Definition at line 879 of file ThermoPhase.h.
References ThermoPhase::err().
void setReferenceComposition (const doublereal *const x) virtual inherited
Sets the reference composition.
Parameters
x Mole fraction vector to set the reference composition to. If this is zero, then the reference mole fraction is set to the current mole fraction vector.
Definition at line 992 of file ThermoPhase.cpp.
References DATA_PTR, Phase::getMoleFractions(), Phase::m_kk, and ThermoPhase::xMol_Ref.
Referenced by ThermoPhase::initThermoXML().
void getReferenceComposition (doublereal *const x) const virtual inherited
Gets the reference composition.
The reference mole fraction is a safe mole fraction.
Parameters
x Mole fraction vector containing the reference composition.
Definition at line 1013 of file ThermoPhase.cpp.
References Phase::m_kk, and ThermoPhase::xMol_Ref.
doublereal enthalpy_mass () const inline inherited
Specific enthalpy.
Units: J/kg.
Definition at line 937 of file ThermoPhase.h.
References ThermoPhase::enthalpy_mole(), and Phase::meanMolecularWeight().
Referenced by ConstPressureReactor::initialize(), Reactor::initialize(), PseudoBinaryVPSSTP::report(), MolarityIonicVPSSTP::report(), PureFluidPhase::report(), MolalityVPSSTP::report(), ThermoPhase::report(), PureFluidPhase::reportCSV(), MolalityVPSSTP::reportCSV(), ThermoPhase::reportCSV(), SingleSpeciesTP::setState_HP(), ThermoPhase::setState_HPorUV(), ThermoPhase::setState_SPorSV(), ReactorBase::setThermoMgr(), ConstPressureReactor::updateState(), and Reactor::updateState().
doublereal intEnergy_mass () const inline inherited
Specific internal energy.
Units: J/kg.
Definition at line 944 of file ThermoPhase.h.
References ThermoPhase::intEnergy_mole(), and Phase::meanMolecularWeight().
Referenced by ConstPressureReactor::initialize(), Reactor::initialize(), PseudoBinaryVPSSTP::report(), MolarityIonicVPSSTP::report(), PureFluidPhase::report(), MolalityVPSSTP::report(), ThermoPhase::report(), PureFluidPhase::reportCSV(), MolalityVPSSTP::reportCSV(), ThermoPhase::reportCSV(), ThermoPhase::setState_HPorUV(), SingleSpeciesTP::setState_UV(), ReactorBase::setThermoMgr(), ConstPressureReactor::updateState(), and Reactor::updateState().
doublereal entropy_mass () const inline inherited
Specific entropy.
Units: J/kg/K.
Definition at line 951 of file ThermoPhase.h.
References ThermoPhase::entropy_mole(), and Phase::meanMolecularWeight().
Referenced by PseudoBinaryVPSSTP::report(), MolarityIonicVPSSTP::report(), PureFluidPhase::report(), MolalityVPSSTP::report(), ThermoPhase::report(), PureFluidPhase::reportCSV(), MolalityVPSSTP::reportCSV(), ThermoPhase::reportCSV(), SingleSpeciesTP::setState_SP(), ThermoPhase::setState_SPorSV(), and SingleSpeciesTP::setState_SV().
doublereal gibbs_mass () const inline inherited
Specific Gibbs function.
Units: J/kg.
Definition at line 958 of file ThermoPhase.h.
References ThermoPhase::gibbs_mole(), and Phase::meanMolecularWeight().
Referenced by PseudoBinaryVPSSTP::report(), MolarityIonicVPSSTP::report(), PureFluidPhase::report(), MolalityVPSSTP::report(), ThermoPhase::report(), PureFluidPhase::reportCSV(), MolalityVPSSTP::reportCSV(), and ThermoPhase::reportCSV().
doublereal cp_mass () const inline inherited
Specific heat at constant pressure.
Units: J/kg/K.
Definition at line 965 of file ThermoPhase.h.
References ThermoPhase::cp_mole(), and Phase::meanMolecularWeight().
Referenced by PseudoBinaryVPSSTP::report(), MolarityIonicVPSSTP::report(), PureFluidPhase::report(), MolalityVPSSTP::report(), ThermoPhase::report(), PureFluidPhase::reportCSV(), MolalityVPSSTP::reportCSV(), ThermoPhase::reportCSV(), SingleSpeciesTP::setState_HP(), ThermoPhase::setState_HPorUV(), SingleSpeciesTP::setState_SP(), ThermoPhase::setState_SPorSV(), and StFlow::updateThermo().
doublereal cv_mass () const inline inherited
Specific heat at constant volume.
Units: J/kg/K.
Definition at line 972 of file ThermoPhase.h.
References ThermoPhase::cv_mole(), and Phase::meanMolecularWeight().
Referenced by PseudoBinaryVPSSTP::report(), MolarityIonicVPSSTP::report(), PureFluidPhase::report(), MolalityVPSSTP::report(), ThermoPhase::report(), PureFluidPhase::reportCSV(), MolalityVPSSTP::reportCSV(), ThermoPhase::reportCSV(), ThermoPhase::setState_HPorUV(), ThermoPhase::setState_SPorSV(), SingleSpeciesTP::setState_SV(), and SingleSpeciesTP::setState_UV().
doublereal _RT () const inline inherited
Return the Gas Constant multiplied by the current temperature.
The units are Joules kmol-1
Definition at line 981 of file ThermoPhase.h.
References Cantera::GasConstant, and Phase::temperature().
Referenced by MixtureFugacityTP::corr0(), RedlichKwongMFTP::enthalpy_mole(), VPStandardStateTP::getChemPotentials_RT(), MixtureFugacityTP::getChemPotentials_RT(), IdealSolnGasVPSS::getChemPotentials_RT(), RedlichKwongMFTP::getChemPotentials_RT(), PureFluidPhase::getEnthalpy_RT(), FixedChemPotSSTP::getEnthalpy_RT(), FixedChemPotSSTP::getEnthalpy_RT_ref(), WaterSSTP::getGibbs_ref(), MixtureFugacityTP::getGibbs_ref(), IdealGasPhase::getGibbs_ref(), PureFluidPhase::getGibbs_RT(), FixedChemPotSSTP::getGibbs_RT(), IdealSolidSolnPhase::getGibbs_RT(), LatticePhase::getGibbs_RT(), FixedChemPotSSTP::getGibbs_RT_ref(), MixtureFugacityTP::getIntEnergy_RT(), IdealMolalSoln::getPartialMolarEnthalpies(), ConstDensityThermo::getPureGibbs(), MixtureFugacityTP::getPureGibbs(), IdealGasPhase::getPureGibbs(), IdealSolidSolnPhase::getPureGibbs(), VPStandardStateTP::getStandardChemPotentials(), MixtureFugacityTP::getStandardChemPotentials(), IdealGasPhase::getStandardChemPotentials(), LatticePhase::getStandardChemPotentials(), MixtureFugacityTP::getStandardVolumes(), MixtureFugacityTP::getStandardVolumes_ref(), IdealGasPhase::getStandardVolumes_ref(), and MixtureFugacityTP::z().
void setState_TPX (doublereal t, doublereal p, const doublereal * x) virtual inherited
Set the temperature (K), pressure (Pa), and mole fractions.
Note, the mole fractions are set first before the pressure is set. Setting the pressure may involve the solution of a nonlinear equation.
Parameters
t Temperature (K)
p Pressure (Pa)
x Vector of mole fractions. Length is equal to m_kk.
Reimplemented in SingleSpeciesTP, and MixtureFugacityTP.
Definition at line 174 of file ThermoPhase.cpp.
References Phase::setMoleFractions(), ThermoPhase::setPressure(), and Phase::setTemperature().
Referenced by MultiTransport::getMassFluxes(), DustyGasTransport::getMolarFluxes(), MultiPhase::setMoles(), and MultiPhase::setPhaseMoleFractions().
void setState_TPX (doublereal t, doublereal p, compositionMap & x) inherited
Set the temperature (K), pressure (Pa), and mole fractions.
Note, the mole fractions are set first before the pressure is set. Setting the pressure may involve the solution of a nonlinear equation.
Parameters
t Temperature (K)
p Pressure (Pa)
x Composition map of mole fractions. Species not in the composition map are assumed to have zero mole fraction
Definition at line 181 of file ThermoPhase.cpp.
References Phase::setMoleFractionsByName(), ThermoPhase::setPressure(), and Phase::setTemperature().
void setState_TPX (doublereal t, doublereal p, const std::string & x) inherited
Set the temperature (K), pressure (Pa), and mole fractions.
Note, the mole fractions are set first before the pressure is set. Setting the pressure may involve the solution of a nonlinear equation.
Parameters
t Temperature (K)
p Pressure (Pa)
x String containing a composition map of the mole fractions. Species not in the composition map are assumed to have zero mole fraction
Definition at line 188 of file ThermoPhase.cpp.
References ThermoPhase::err(), Phase::nSpecies(), Cantera::parseCompString(), CanteraError::save(), Phase::setMoleFractionsByName(), ThermoPhase::setPressure(), Phase::setTemperature(), and Phase::speciesName().
void setState_TPY (doublereal t, doublereal p, const doublereal * y) inherited
Set the internally stored temperature (K), pressure (Pa), and mass fractions of the phase.
Note, the mass fractions are set first before the pressure is set. Setting the pressure may involve the solution of a nonlinear equation.
Parameters
t Temperature (K)
p Pressure (Pa)
y Vector of mass fractions. Length is equal to m_kk.
Definition at line 206 of file ThermoPhase.cpp.
References Phase::setMassFractions(), ThermoPhase::setPressure(), and Phase::setTemperature().
void setState_TPY (doublereal t, doublereal p, compositionMap & y) inherited
Set the internally stored temperature (K), pressure (Pa), and mass fractions of the phase.
Note, the mass fractions are set first before the pressure is set. Setting the pressure may involve the solution of a nonlinear equation.
Parameters
t Temperature (K)
p Pressure (Pa)
y Composition map of mass fractions. Species not in the composition map are assumed to have zero mass fraction
Definition at line 214 of file ThermoPhase.cpp.
References Phase::setMassFractionsByName(), ThermoPhase::setPressure(), and Phase::setTemperature().
void setState_TPY (doublereal t, doublereal p, const std::string & y) inherited
Set the internally stored temperature (K), pressure (Pa), and mass fractions of the phase.
Note, the mass fractions are set first before the pressure is set. Setting the pressure may involve the solution of a nonlinear equation.
Parameters
t Temperature (K)
p Pressure (Pa)
y String containing a composition map of the mass fractions. Species not in the composition map are assumed to have zero mass fraction
Definition at line 222 of file ThermoPhase.cpp.
References ThermoPhase::err(), Phase::nSpecies(), Cantera::parseCompString(), CanteraError::save(), Phase::setMassFractionsByName(), ThermoPhase::setPressure(), Phase::setTemperature(), and Phase::speciesName().
void setState_PX (doublereal p, doublereal * x) inherited
Set the pressure (Pa) and mole fractions.
Note, the mole fractions are set first before the pressure is set. Setting the pressure may involve the solution of a nonlinear equation.
Parameters
p Pressure (Pa)
x Vector of mole fractions. Length is equal to m_kk.
Definition at line 249 of file ThermoPhase.cpp.
References Phase::setMoleFractions(), and ThermoPhase::setPressure().
Referenced by vcs_VolPhase::_updateMoleFractionDependencies(), IdealSolnGasVPSS::setToEquilState(), RedlichKwongMFTP::setToEquilState(), IdealGasPhase::setToEquilState(), and IdealSolidSolnPhase::setToEquilState().
void setState_PY (doublereal p, doublereal * y) inherited
Set the internally stored pressure (Pa) and mass fractions.
Note, the temperature is held constant during this operation. Note, the mass fractions are set first before the pressure is set. Setting the pressure may involve the solution of a nonlinear equation.
Parameters
p Pressure (Pa)
y Vector of mass fractions. Length is equal to m_kk.
Definition at line 256 of file ThermoPhase.cpp.
References Phase::setMassFractions(), and ThermoPhase::setPressure().
void setState_HP (doublereal h, doublereal p, doublereal tol = 1.e-4) virtual inherited
Set the internally stored specific enthalpy (J/kg) and pressure (Pa) of the phase.
Parameters
h Specific enthalpy (J/kg)
p Pressure (Pa)
tol Optional parameter setting the tolerance of the calculation. Defaults to 1.0E-4
Reimplemented in SingleSpeciesTP, and PureFluidPhase.
Definition at line 263 of file ThermoPhase.cpp.
References ThermoPhase::setState_HPorUV().
Referenced by FlowReactor::updateState(), and ConstPressureReactor::updateState().
void setState_UV (doublereal u, doublereal v, doublereal tol = 1.e-4) virtual inherited
Set the specific internal energy (J/kg) and specific volume (m^3/kg).
This function fixes the internal state of the phase so that the specific internal energy and specific volume have the value of the input parameters.
Parameters
u specific internal energy (J/kg)
v specific volume (m^3/kg).
tol Optional parameter setting the tolerance of the calculation. Defaults to 1.0E-4
Reimplemented in SingleSpeciesTP, and PureFluidPhase.
Definition at line 270 of file ThermoPhase.cpp.
References ThermoPhase::setState_HPorUV().
Referenced by Reactor::updateState().
void setState_SP (doublereal s, doublereal p, doublereal tol = 1.e-4) virtual inherited
Set the specific entropy (J/kg/K) and pressure (Pa).
This function fixes the internal state of the phase so that the specific entropy and the pressure have the value of the input parameters.
Parameters
s specific entropy (J/kg/K)
p specific pressure (Pa).
tol Optional parameter setting the tolerance of the calculation. Defaults to 1.0E-4
Reimplemented in SingleSpeciesTP, and PureFluidPhase.
Definition at line 546 of file ThermoPhase.cpp.
References ThermoPhase::setState_SPorSV().
void setState_SV (doublereal s, doublereal v, doublereal tol = 1.e-4) virtual inherited
Set the specific entropy (J/kg/K) and specific volume (m^3/kg).
This function fixes the internal state of the phase so that the specific entropy and specific volume have the value of the input parameters.
Parameters
s specific entropy (J/kg/K)
v specific volume (m^3/kg).
tol Optional parameter setting the tolerance of the calculation. Defaults to 1.0E-4
Reimplemented in SingleSpeciesTP, and PureFluidPhase.
Definition at line 553 of file ThermoPhase.cpp.
References ThermoPhase::setState_SPorSV().
virtual void setToEquilState (const doublereal * lambda_RT) inline virtual inherited
This method is used by the ChemEquil equilibrium solver.
It sets the state such that the chemical potentials satisfy
\[ \frac{\mu_k}{\hat R T} = \sum_m A_{k,m} \left(\frac{\lambda_m} {\hat R T}\right) \]
where \(\lambda_m \) is the element potential of element m. The temperature is unchanged. Any phase (ideal or not) that implements this method can be equilibrated by ChemEquil.
Parameters
lambda_RT Input vector of dimensionless element potentials The length is equal to nElements().
Reimplemented in HMWSoln, DebyeHuckel, IdealSolidSolnPhase, IdealGasPhase, IdealMolalSoln, MolalityVPSSTP, RedlichKwongMFTP, IdealSolnGasVPSS, and ConstDensityThermo.
Definition at line 1193 of file ThermoPhase.h.
References ThermoPhase::err().
Referenced by ChemEquil::setToEquilState().
void setElementPotentials (const vector_fp & lambda) inherited
Stores the element potentials in the ThermoPhase object.
Called by function 'equilibrate' in ChemEquil.h to transfer the element potentials to this object after every successful equilibration routine. The element potentials are stored in their dimensionless forms, calculated by dividing by RT.
Parameters
lambda Input vector containing the element potentials. Length = nElements. Units are Joules/kmol.
Definition at line 1106 of file ThermoPhase.cpp.
References Cantera::GasConstant, ThermoPhase::m_hasElementPotentials, ThermoPhase::m_lambdaRRT, Phase::nElements(), and Phase::temperature().
Referenced by Cantera::equilibrate(), ChemEquil::equilibrate(), and Cantera::vcs_equilibrate().
bool getElementPotentials (doublereal * lambda) const inherited
Returns the element potentials stored in the ThermoPhase object.
Returns the stored element potentials. The element potentials are retrieved from their stored dimensionless forms by multiplying by RT.
Parameters
lambda Output vector containing the element potentials. Length = nElements. Units are Joules/kmol.
Returns
bool indicating whether there are any valid stored element potentials. The calling routine should check this bool. In the case that there aren't any, lambda is not touched.
Definition at line 1129 of file ThermoPhase.cpp.
References Cantera::GasConstant, ThermoPhase::m_hasElementPotentials, ThermoPhase::m_lambdaRRT, Phase::nElements(), and Phase::temperature().
Referenced by ChemEquil::equilibrate().
virtual doublereal critTemperature () const inline virtual inherited
Critical temperature (K).
Reimplemented in HMWSoln, IdealMolalSoln, RedlichKwongMFTP, PureFluidPhase, and WaterSSTP.
Definition at line 1236 of file ThermoPhase.h.
References ThermoPhase::err().
Referenced by MixtureFugacityTP::calculatePsat(), MixtureFugacityTP::densityCalc(), MixtureFugacityTP::phaseState(), and MixtureFugacityTP::psatEst().
virtual doublereal critPressure () const inline virtual inherited
Critical pressure (Pa).
Reimplemented in HMWSoln, IdealMolalSoln, RedlichKwongMFTP, PureFluidPhase, and WaterSSTP.
Definition at line 1242 of file ThermoPhase.h.
References ThermoPhase::err().
Referenced by MixtureFugacityTP::calculatePsat(), and MixtureFugacityTP::psatEst().
virtual doublereal critDensity () const inline virtual inherited
Critical density (kg/m3).
Reimplemented in HMWSoln, IdealMolalSoln, RedlichKwongMFTP, PureFluidPhase, and WaterSSTP.
Definition at line 1248 of file ThermoPhase.h.
References ThermoPhase::err().
Referenced by MixtureFugacityTP::densityCalc(), and MixtureFugacityTP::phaseState().
virtual doublereal satTemperature (doublereal p) const inline virtual inherited
Return the saturation temperature given the pressure.
Parameters
p Pressure (Pa)
Reimplemented in HMWSoln, DebyeHuckel, SingleSpeciesTP, and PureFluidPhase.
Definition at line 1267 of file ThermoPhase.h.
References ThermoPhase::err().
virtual doublereal satPressure (doublereal t) const inline virtual inherited
Return the saturation pressure given the temperature.
Parameters
t Temperature (Kelvin)
Reimplemented in HMWSoln, DebyeHuckel, SingleSpeciesTP, PureFluidPhase, and WaterSSTP.
Definition at line 1276 of file ThermoPhase.h.
References ThermoPhase::err().
virtual doublereal vaporFraction () const inline virtual inherited
Return the fraction of vapor at the current conditions.
Reimplemented in HMWSoln, DebyeHuckel, SingleSpeciesTP, PureFluidPhase, and WaterSSTP.
Definition at line 1282 of file ThermoPhase.h.
References ThermoPhase::err().
virtual void setState_Tsat (doublereal t, doublereal x) inline virtual inherited
Set the state to a saturated system at a particular temperature.
Parameters
t Temperature (kelvin)
x Fraction of vapor
Reimplemented in HMWSoln, DebyeHuckel, SingleSpeciesTP, and PureFluidPhase.
Definition at line 1292 of file ThermoPhase.h.
References ThermoPhase::err().
virtual void setState_Psat (doublereal p, doublereal x) inline virtual inherited
Set the state to a saturated system at a particular pressure.
Parameters
p Pressure (Pa)
x Fraction of vapor
Reimplemented in HMWSoln, DebyeHuckel, SingleSpeciesTP, and PureFluidPhase.
Definition at line 1301 of file ThermoPhase.h.
References ThermoPhase::err().
void saveSpeciesData (const size_t k, const XML_Node *const data) inherited
Store a reference pointer to the XML tree containing the species data for this phase.
The following methods are used in the process of constructing the phase and setting its parameters from a specification in an input file. They are not normally used in application programs. To see how they are used, see files importCTML.cpp and ThermoFactory.cpp.
This is used to access data needed to construct transport manager later.
Parameters
k Species index
data Pointer to the XML_Node data containing information about the species in the phase.
Definition at line 1050 of file ThermoPhase.cpp.
References ThermoPhase::m_speciesData.
Referenced by FixedChemPotSSTP::FixedChemPotSSTP(), and Cantera::importPhase().
const std::vector< const XML_Node * > & speciesData () const inherited
Return a pointer to the vector of XML nodes containing the species data for this phase.
Definition at line 1060 of file ThermoPhase.cpp.
References Phase::m_kk, and ThermoPhase::m_speciesData.
Referenced by MineralEQ3::initThermoXML(), DebyeHuckel::initThermoXML(), TransportFactory::initTransport(), LatticeSolidPhase::installSlavePhases(), and TransportFactory::setupLiquidTransport().
void setSpeciesThermo (SpeciesThermo * spthermo) inherited
Install a species thermodynamic property manager.
The species thermodynamic property manager computes properties of the pure species for use in constructing solution properties. It is meant for internal use, and some classes derived from ThermoPhase may not use any species thermodynamic property manager. This method is called by function importPhase() in importCTML.cpp.
Parameters
spthermo input pointer to the species thermodynamic property manager.
Definition at line 886 of file ThermoPhase.cpp.
References ThermoPhase::m_spthermo.
Referenced by FixedChemPotSSTP::FixedChemPotSSTP(), Cantera::importPhase(), LatticeSolidPhase::installSlavePhases(), and VPSSMgrFactory::newVPSSMgr().
SpeciesThermo & speciesThermo (int k = -1) virtual inherited
Return a changeable reference to the calculation manager for species reference-state thermodynamic properties.
Parameters
k Speices id. The default is -1, meaning return the default
Reimplemented in LatticeSolidPhase.
Definition at line 904 of file ThermoPhase.cpp.
References ThermoPhase::m_spthermo.
Referenced by PDSS_ConstVol::constructPDSSXML(), PDSS_SSVol::constructPDSSXML(), PDSS_ConstVol::initThermo(), PDSS_IdealGas::initThermo(), PDSS_IonsFromNeutral::initThermo(), PDSS_SSVol::initThermo(), VPSSMgrFactory::newVPSSMgr(), and PDSS::PDSS().
void initThermoFile (std::string inputFile, std::string id) virtual inherited
Initialization of a ThermoPhase object using an ctml file.
This routine is a precursor to initThermoXML(XML_Node*) routine, which does most of the work. Here we read extra information about the XML description of a phase. Regular information about elements and species and their reference state thermodynamic information have already been read at this point. For example, we do not need to call this function for ideal gas equations of state.
Parameters
inputFile XML file containing the description of the phase
id Optional parameter identifying the name of the phase. If none is given, the first XML phase element encountered will be used.
Definition at line 928 of file ThermoPhase.cpp.
References XML_Node::build(), XML_Node::copy(), Cantera::findInputFile(), Cantera::findXMLPhase(), ThermoPhase::initThermoXML(), and Phase::xml().
void installSlavePhases (Cantera::XML_Node * phaseNode) virtual inherited
Add in species from Slave phases.
This hook is used for cSS_CONVENTION_SLAVE phases
Parameters
phaseNode XML Element for the phase
Reimplemented in LatticeSolidPhase.
Definition at line 1045 of file ThermoPhase.cpp.
Referenced by Cantera::importPhase().
virtual void setParameters (int n, doublereal *const c) inline virtual inherited
Set the equation of state parameters.
The number and meaning of these depends on the subclass.
Parameters
n number of parameters
c array of n coefficients
Reimplemented in HMWSoln, DebyeHuckel, LatticePhase, IdealMolalSoln, SingleSpeciesTP, FixedChemPotSSTP, electrodeElectron, MineralEQ3, MetalSHEelectrons, StoichSubstanceSSTP, StoichSubstance, ConstDensityThermo, and SurfPhase.
Definition at line 1451 of file ThermoPhase.h.
virtual void getParameters (int & n, doublereal *const c) const inline virtual inherited
Get the equation of state parameters in a vector.
The number and meaning of these depends on the subclass.
Parameters
n number of parameters
c array of n coefficients
Reimplemented in HMWSoln, DebyeHuckel, LatticePhase, IdealMolalSoln, SingleSpeciesTP, FixedChemPotSSTP, MineralEQ3, MetalSHEelectrons, StoichSubstanceSSTP, StoichSubstance, and ConstDensityThermo.
Definition at line 1462 of file ThermoPhase.h.
void setStateFromXML (const XML_Node & state) virtual inherited
Set the initial state of the phase to the conditions specified in the state XML element.
This method sets the temperature, pressure, and mole fraction vector to a set default value.
Parameters
state AN XML_Node object corresponding to the "state" entry for this phase in the input file.
Reimplemented in MolalityVPSSTP, MixtureFugacityTP, and SurfPhase.
Definition at line 1072 of file ThermoPhase.cpp.
References ctml::getChildValue(), ctml::getFloat(), XML_Node::hasChild(), Phase::setDensity(), Phase::setMassFractionsByName(), Phase::setMoleFractionsByName(), ThermoPhase::setPressure(), and Phase::setTemperature().
Referenced by ThermoPhase::initThermoXML(), and MolalityVPSSTP::setStateFromXML().
std::string report (bool show_thermo = true) const virtual inherited
returns a summary of the state of the phase as a string
Parameters
show_thermo If true, extra information is printed out about the thermodynamic state of the system.
Reimplemented in MolalityVPSSTP, PureFluidPhase, MolarityIonicVPSSTP, and PseudoBinaryVPSSTP.
Definition at line 1243 of file ThermoPhase.cpp.
References ThermoPhase::cp_mass(), ThermoPhase::cp_mole(), ThermoPhase::cv_mass(), ThermoPhase::cv_mole(), Phase::density(), ThermoPhase::electricPotential(), ThermoPhase::enthalpy_mass(), ThermoPhase::enthalpy_mole(), ThermoPhase::entropy_mass(), ThermoPhase::entropy_mole(), ThermoPhase::err(), Cantera::GasConstant, ThermoPhase::getChemPotentials(), Phase::getMassFractions(), Phase::getMoleFractions(), ThermoPhase::gibbs_mass(), ThermoPhase::gibbs_mole(), ThermoPhase::intEnergy_mass(), ThermoPhase::intEnergy_mole(), Phase::meanMolecularWeight(), Phase::name(), Phase::nSpecies(), ThermoPhase::pressure(), CanteraError::save(), Cantera::SmallNumber, Phase::speciesName(), and Phase::temperature().
Referenced by Cantera::operator<<(), and Cantera::report().
void reportCSV (std::ofstream & csvFile) const virtual inherited
returns a summary of the state of the phase to a comma separated file
Parameters
csvFile ofstream file to print comma separated data for the phase
Reimplemented in MolalityVPSSTP, and PureFluidPhase.
Definition at line 1350 of file ThermoPhase.cpp.
References ThermoPhase::cp_mass(), ThermoPhase::cp_mole(), ThermoPhase::cv_mass(), ThermoPhase::cv_mole(), Phase::density(), ThermoPhase::electricPotential(), ThermoPhase::enthalpy_mass(), ThermoPhase::enthalpy_mole(), ThermoPhase::entropy_mass(), ThermoPhase::entropy_mole(), ThermoPhase::err(), ThermoPhase::getActivities(), ThermoPhase::getActivityCoefficients(), ThermoPhase::getChemPotentials(), Phase::getMassFractions(), Phase::getMoleFractions(), ThermoPhase::getPartialMolarCp(), ThermoPhase::getPartialMolarEnthalpies(), ThermoPhase::getPartialMolarEntropies(), ThermoPhase::getPartialMolarIntEnergies(), ThermoPhase::getPartialMolarVolumes(), ThermoPhase::gibbs_mass(), ThermoPhase::gibbs_mole(), ThermoPhase::intEnergy_mass(), ThermoPhase::intEnergy_mole(), Phase::meanMolecularWeight(), Phase::name(), Phase::nSpecies(), ThermoPhase::pressure(), CanteraError::save(), Cantera::SmallNumber, Phase::speciesName(), and Phase::temperature().
XML_Node & xml () inherited
Returns a reference to the XML_Node stored for the phase.
The XML_Node for the phase contains all of the input data used to set up the model for the phase, during its initialization.
Definition at line 125 of file Phase.cpp.
References Phase::m_xml.
Referenced by MolarityIonicVPSSTP::constructPhaseFile(), LatticePhase::constructPhaseFile(), RedlichKisterVPSSTP::constructPhaseFile(), MargulesVPSSTP::constructPhaseFile(), MixedSolventElectrolyte::constructPhaseFile(), WaterSSTP::constructPhaseFile(), PhaseCombo_Interaction::constructPhaseFile(), IonsFromNeutralVPSSTP::constructPhaseFile(), IdealMolalSoln::constructPhaseFile(), IdealSolidSolnPhase::constructPhaseFile(), DebyeHuckel::constructPhaseFile(), Cantera::importPhase(), SimpleTransport::initLiquid(), ThermoPhase::initThermoFile(), TransportFactory::newTransport(), and TransportFactory::setupLiquidTransport().
std::string id () const inherited
Return the string id for the phase.
Definition at line 130 of file Phase.cpp.
References Phase::m_id.
Referenced by Kinetics::assignShallowPointers(), Cantera::equilibrate(), Cantera::getEfficiencies(), Cantera::importPhase(), LatticeSolidPhase::installSlavePhases(), Kinetics::kineticsSpeciesIndex(), MultiPhase::phaseIndex(), MultiPhase::phaseName(), solveProb::print_header(), RedlichKwongMFTP::RedlichKwongMFTP(), Phase::setID(), LatticeSolidPhase::setParametersFromXML(), vcs_VolPhase::transferElementsFM(), and Cantera::vcs_equilibrate().
void setID (std::string id) inherited
Set the string id for the phase.
Parameters
id String id of the phase
Definition at line 135 of file Phase.cpp.
References Phase::id(), and Phase::m_id.
Referenced by FixedChemPotSSTP::FixedChemPotSSTP(), and Cantera::importPhase().
std::string name () const inherited
Return the name of the phase.
Definition at line 140 of file Phase.cpp.
References Phase::m_name.
Referenced by Cantera::operator<<(), PseudoBinaryVPSSTP::report(), MolarityIonicVPSSTP::report(), PureFluidPhase::report(), MolalityVPSSTP::report(), ThermoPhase::report(), PureFluidPhase::reportCSV(), vcs_MultiPhaseEquil::reportCSV(), MolalityVPSSTP::reportCSV(), and ThermoPhase::reportCSV().
void setName (std::string nm) inherited
Sets the string name for the phase.
Parameters
nm String name of the phase
Definition at line 145 of file Phase.cpp.
References Phase::m_name.
Referenced by FixedChemPotSSTP::FixedChemPotSSTP(), and Cantera::importPhase().
string elementName (size_t m) const inherited
Name of the element with index m.
Parameters
m Element index.
Definition at line 169 of file Phase.cpp.
References Phase::checkElementIndex(), and Phase::m_elementNames.
Referenced by MultiPhase::addPhase(), Cantera::checkRxnElementBalance(), Cantera::convertDGFormation(), PDSS_HKFT::convertDGFormation(), ChemEquil::equilibrate(), ChemEquil::equilResidual(), ChemEquil::estimateElementPotentials(), ChemEquil::estimateEP_Brinkley(), MolalityVPSSTP::findCLMIndex(), ChemEquil::initialize(), LatticeSolidPhase::installSlavePhases(), Cantera::installSpecies(), ChemEquil::setInitialMoles(), and vcs_VolPhase::transferElementsFM().
size_t elementIndex (std::string name) const inherited
Return the index of element named 'name'.
The index is an integer assigned to each element in the order it was added. Returns npos if the specified element is not found.
Parameters
name Name of the element
Definition at line 175 of file Phase.cpp.
References Phase::m_elementNames, Phase::m_mm, and Cantera::npos.
Referenced by Phase::addUniqueElementAfterFreeze(), MultiPhase::init(), WaterSSTP::initThermoXML(), LatticeSolidPhase::installSlavePhases(), Cantera::installSpecies(), Cantera::LookupGe(), and PDSS_HKFT::LookupGe().
const vector< string > & elementNames () const inherited
Return a read-only reference to the vector of element names.
Definition at line 185 of file Phase.cpp.
References Phase::m_elementNames.
Referenced by ChemEquil::equilibrate(), ChemEquil::estimateEP_Brinkley(), and IonsFromNeutralVPSSTP::initThermoXML().
doublereal atomicWeight (size_t m) const inherited
Atomic weight of element m.
Parameters
m Element index
Definition at line 190 of file Phase.cpp.
References Phase::m_atomicWeights.
Referenced by ChemEquil::initialize(), and WaterSSTP::initThermoXML().
doublereal entropyElement298 (size_t m) const inherited
Entropy of the element in its standard state at 298 K and 1 bar.
Parameters
m Element index
Definition at line 195 of file Phase.cpp.
References AssertThrowMsg, AssertTrace, ENTROPY298_UNKNOWN, Phase::m_entropy298, and Phase::m_mm.
Referenced by LatticeSolidPhase::installSlavePhases(), Cantera::LookupGe(), and PDSS_HKFT::LookupGe().
int atomicNumber (size_t m) const inherited
Atomic number of element m.
Parameters
m Element index
Definition at line 209 of file Phase.cpp.
References Phase::m_atomicNumbers.
Referenced by MultiPhase::addPhase(), and LatticeSolidPhase::installSlavePhases().
int elementType (size_t m) const inherited
Return the element constraint type Possible types include:
CT_ELEM_TYPE_TURNEDOFF -1 CT_ELEM_TYPE_ABSPOS 0 CT_ELEM_TYPE_ELECTRONCHARGE 1 CT_ELEM_TYPE_CHARGENEUTRALITY 2 CT_ELEM_TYPE_LATTICERATIO 3 CT_ELEM_TYPE_KINETICFROZEN 4 CT_ELEM_TYPE_SURFACECONSTRAINT 5 CT_ELEM_TYPE_OTHERCONSTRAINT 6
The default is CT_ELEM_TYPE_ABSPOS.
Parameters
m Element index
Returns
Returns the element type
Definition at line 214 of file Phase.cpp.
References Phase::m_elem_type.
Referenced by LatticeSolidPhase::installSlavePhases(), and vcs_VolPhase::transferElementsFM().
int changeElementType (int m, int elem_type) inherited
Change the element type of the mth constraint Reassigns an element type.
Parameters
m Element index
elem_type New elem type to be assigned
Returns
Returns the old element type
Definition at line 219 of file Phase.cpp.
References Phase::m_elem_type.
const vector_fp & atomicWeights () const inherited
Return a read-only reference to the vector of atomic weights.
Definition at line 204 of file Phase.cpp.
References Phase::m_atomicWeights.
Referenced by LatticeSolidPhase::installSlavePhases().
size_t nElements () const inherited
Number of elements.
Definition at line 150 of file Phase.cpp.
References Phase::m_mm.
Referenced by MultiPhase::addPhase(), Cantera::checkRxnElementBalance(), Cantera::convertDGFormation(), PDSS_HKFT::convertDGFormation(), ChemEquil::equilibrate(), MolalityVPSSTP::findCLMIndex(), FixedChemPotSSTP::FixedChemPotSSTP(), ThermoPhase::getElementPotentials(), ChemEquil::initialize(), IdealSolidSolnPhase::initLengths(), ConstDensityThermo::initThermo(), LatticeSolidPhase::initThermo(), IdealGasPhase::initThermo(), LatticePhase::initThermo(), IonsFromNeutralVPSSTP::initThermoXML(), LatticeSolidPhase::installSlavePhases(), Cantera::installSpecies(), ThermoPhase::setElementPotentials(), vcs_VolPhase::setPtrThermoPhase(), and vcs_VolPhase::transferElementsFM().
void checkElementIndex (size_t m) const inherited
Check that the specified element index is in range Throws an exception if m is greater than nElements()-1.
Definition at line 155 of file Phase.cpp.
References Phase::m_mm.
Referenced by Phase::elementName(), and Phase::nAtoms().
void checkElementArraySize (size_t mm) const inherited
Check that an array size is at least nElements() Throws an exception if mm is less than nElements().
Used before calls which take an array pointer.
Definition at line 162 of file Phase.cpp.
References Phase::m_mm.
doublereal nAtoms (size_t k, size_t m) const inherited
Number of atoms of element m in species k.
Parameters
k species index
m element index
Definition at line 226 of file Phase.cpp.
References Phase::checkElementIndex(), Phase::checkSpeciesIndex(), Phase::m_mm, and Phase::m_speciesComp.
Referenced by Cantera::checkRxnElementBalance(), Cantera::convertDGFormation(), PDSS_HKFT::convertDGFormation(), MolalityVPSSTP::findCLMIndex(), MultiPhase::init(), ChemEquil::initialize(), IonsFromNeutralVPSSTP::initThermoXML(), IdealSolidSolnPhase::setToEquilState(), and vcs_VolPhase::transferElementsFM().
void getAtoms (size_t k, double * atomArray) const inherited
Get a vector containing the atomic composition of species k.
Parameters
k species index
atomArray vector containing the atomic number in the species. Length: m_mm
Definition at line 233 of file Phase.cpp.
References Phase::m_mm, and Phase::m_speciesComp.
Referenced by LatticeSolidPhase::installSlavePhases().
size_t speciesIndex (std::string name) const inherited
Returns the index of a species named 'name' within the Phase object.
The first species in the phase will have an index 0, and the last one will have an index of nSpecies() - 1.
Parameters
name String name of the species. It may also be in the form phaseName:speciesName
Returns
The index of the species. If the name is not found, the value npos is returned.
Definition at line 240 of file Phase.cpp.
References Phase::m_id, Phase::m_kk, Phase::m_name, Phase::m_speciesNames, Cantera::npos, and Cantera::parseSpeciesName().
Referenced by PDSS_IonsFromNeutral::constructPDSSXML(), TransportFactory::getLiquidInteractionsTransportData(), TransportFactory::getLiquidSpeciesTransportData(), Cantera::getStick(), HMWSoln::HMWSoln(), Cantera::importSolution(), LiquidTranInteraction::init(), DebyeHuckel::initThermoXML(), FlowDevice::install(), Kinetics::kineticsSpeciesIndex(), MargulesVPSSTP::MargulesVPSSTP(), Phase::massFraction(), MixedSolventElectrolyte::MixedSolventElectrolyte(), Phase::moleFraction(), PhaseCombo_Interaction::PhaseCombo_Interaction(), PhaseCombo_Interaction::readXMLBinarySpecies(), RedlichKisterVPSSTP::readXMLBinarySpecies(), MargulesVPSSTP::readXMLBinarySpecies(), MixedSolventElectrolyte::readXMLBinarySpecies(), RedlichKwongMFTP::readXMLCrossFluid(), RedlichKwongMFTP::readXMLPureFluid(), RedlichKisterVPSSTP::RedlichKisterVPSSTP(), MolalityVPSSTP::report(), MolalityVPSSTP::reportCSV(), and Kinetics::speciesPhase().
string speciesName (size_t k) const inherited
Name of the species with index k.
Parameters
k index of the species
Definition at line 257 of file Phase.cpp.
References Phase::checkSpeciesIndex(), and Phase::m_speciesNames.
Referenced by StFlow::componentName(), ReactingSurf1D::componentName(), ChemEquil::estimateElementPotentials(), ChemEquil::estimateEP_Brinkley(), MolalityVPSSTP::findCLMIndex(), TransportFactory::fitProperties(), AqueousTransport::getLiquidTransportData(), Phase::getMoleFractionsByName(), Cantera::importSolution(), MultiPhase::init(), ChemEquil::initialize(), LiquidTransport::initLiquid(), SimpleTransport::initLiquid(), IdealMolalSoln::initThermoXML(), DebyeHuckel::initThermoXML(), FlowDevice::install(), LatticeSolidPhase::installSlavePhases(), Kinetics::kineticsSpeciesName(), solveProb::print_header(), HMWSoln::printCoeffs(), PhaseCombo_Interaction::readXMLBinarySpecies(), RedlichKisterVPSSTP::readXMLBinarySpecies(), MargulesVPSSTP::readXMLBinarySpecies(), MixedSolventElectrolyte::readXMLBinarySpecies(), PureFluidPhase::report(), MolalityVPSSTP::report(), ThermoPhase::report(), PureFluidPhase::reportCSV(), vcs_MultiPhaseEquil::reportCSV(), MolalityVPSSTP::reportCSV(), ThermoPhase::reportCSV(), HMWSoln::s_updatePitzer_d2lnMolalityActCoeff_dT2(), HMWSoln::s_updatePitzer_dlnMolalityActCoeff_dP(), HMWSoln::s_updatePitzer_dlnMolalityActCoeff_dT(), HMWSoln::s_updatePitzer_lnMolalityActCoeff(), StFlow::save(), SurfPhase::setCoveragesByName(), ChemEquil::setInitialMoles(), Phase::setMassFractionsByName(), MolalityVPSSTP::setMolalitiesByName(), Phase::setMoleFractionsByName(), ThermoPhase::setState_TPX(), ThermoPhase::setState_TPY(), Inlet1D::showSolution(), ReactingSurf1D::showSolution(), Phase::speciesSPName(), and ChemEquil::update().
std::string speciesSPName (int k) const inherited
Returns the expanded species name of a species, including the phase name This is guaranteed to be unique within a Cantera problem.
Parameters
k Species index within the phase
Returns
The "phaseName:speciesName" string
Definition at line 282 of file Phase.cpp.
References Phase::m_name, and Phase::speciesName().
const vector< string > & speciesNames () const inherited
Return a const reference to the vector of species names.
Definition at line 263 of file Phase.cpp.
References Phase::m_speciesNames.
Referenced by PDSS_ConstVol::constructPDSSFile(), PDSS_HKFT::constructPDSSFile(), PDSS_IonsFromNeutral::constructPDSSFile(), PDSS_SSVol::constructPDSSFile(), VPSSMgr_ConstVol::initThermoXML(), VPSSMgr_Water_ConstVol::initThermoXML(), VPSSMgr_Water_HKFT::initThermoXML(), IdealMolalSoln::initThermoXML(), LatticePhase::initThermoXML(), IdealSolidSolnPhase::initThermoXML(), DebyeHuckel::initThermoXML(), TransportFactory::setupLiquidTransport(), and TransportFactory::setupMM().
size_t nSpecies () const inline inherited
Returns the number of species in the phase.
Definition at line 252 of file Phase.h.
References Phase::m_kk.
Referenced by MultiPhase::addPhase(), InterfaceKinetics::applyButlerVolmerCorrection(), Kinetics::assignShallowPointers(), MultiPhase::calcElemAbundances(), Phase::chargeDensity(), MultiPhaseEquil::computeReactionSteps(), PDSS_IonsFromNeutral::constructPDSSXML(), RedlichKisterVPSSTP::cp_mole(), MargulesVPSSTP::cp_mole(), MixedSolventElectrolyte::cp_mole(), PhaseCombo_Interaction::cp_mole(), SolidTransport::electricalConductivity(), RedlichKisterVPSSTP::enthalpy_mole(), MargulesVPSSTP::enthalpy_mole(), MixedSolventElectrolyte::enthalpy_mole(), PhaseCombo_Interaction::enthalpy_mole(), RedlichKisterVPSSTP::entropy_mole(), MargulesVPSSTP::entropy_mole(), MixedSolventElectrolyte::entropy_mole(), PhaseCombo_Interaction::entropy_mole(), ChemEquil::equilibrate(), vcs_MultiPhaseEquil::equilibrate_TP(), ChemEquil::estimateElementPotentials(), ThermoPhase::getActivities(), MetalPhase::getActivityConcentrations(), MetalPhase::getChemPotentials(), IonsFromNeutralVPSSTP::getdlnActCoeffds(), MetalPhase::getEnthalpy_RT(), MetalPhase::getEntropy_R(), AqueousKinetics::getEquilibriumConstants(), InterfaceKinetics::getEquilibriumConstants(), MultiTransport::getMassFluxes(), LTI_Pairwise_Interaction::getMatrixTransProp(), LTI_StefanMaxwell_PPN::getMatrixTransProp(), SolidTransport::getMixDiffCoeffs(), LTI_MoleFracs::getMixTransProp(), LTI_MassFracs::getMixTransProp(), LTI_Log_MoleFracs::getMixTransProp(), LTI_Pairwise_Interaction::getMixTransProp(), LTI_StefanMaxwell_PPN::getMixTransProp(), LTI_MoleFracs_ExpT::getMixTransProp(), SolidTransport::getMobilities(), MultiTransport::getMolarFluxes(), Phase::getMoleFractionsByName(), MultiPhase::getMoles(), MetalPhase::getStandardChemPotentials(), ImplicitSurfChem::ImplicitSurfChem(), Cantera::importSolution(), LiquidTranInteraction::init(), MultiPhase::init(), AqueousKinetics::init(), GasKinetics::init(), InterfaceKinetics::init(), GasTransport::initGas(), ChemEquil::initialize(), DustyGasTransport::initialize(), PseudoBinaryVPSSTP::initLengths(), IdealSolnGasVPSS::initLengths(), MolarityIonicVPSSTP::initLengths(), GibbsExcessVPSSTP::initLengths(), VPStandardStateTP::initLengths(), IonsFromNeutralVPSSTP::initLengths(), MixtureFugacityTP::initLengths(), VPSSMgr::initLengths(), PhaseCombo_Interaction::initLengths(), RedlichKisterVPSSTP::initLengths(), MargulesVPSSTP::initLengths(), MixedSolventElectrolyte::initLengths(), MolalityVPSSTP::initLengths(), IdealMolalSoln::initLengths(), IdealSolidSolnPhase::initLengths(), DebyeHuckel::initLengths(), HMWSoln::initLengths(), LiquidTransport::initLiquid(), SimpleTransport::initLiquid(), AqueousTransport::initLiquid(), ConstDensityThermo::initThermo(), StoichSubstance::initThermo(), StoichSubstanceSSTP::initThermo(), LatticeSolidPhase::initThermo(), SingleSpeciesTP::initThermo(), LatticePhase::initThermo(), FlowDevice::install(), rxninfo::installReaction(), LatticeSolidPhase::installSlavePhases(), Kinetics::nTotalSpecies(), solveProb::print_header(), PseudoBinaryVPSSTP::report(), MolarityIonicVPSSTP::report(), PureFluidPhase::report(), MolalityVPSSTP::report(), ThermoPhase::report(), PureFluidPhase::reportCSV(), vcs_MultiPhaseEquil::reportCSV(), MolalityVPSSTP::reportCSV(), ThermoPhase::reportCSV(), Phase::restoreState(), IonsFromNeutralVPSSTP::s_update_dlnActCoeff_dlnN(), Phase::saveState(), Kinetics::selectPhase(), ImplicitSurfChem::setConcSpecies(), SurfPhase::setCoveragesByName(), Phase::setMassFractionsByName(), MolalityVPSSTP::setMolalitiesByName(), Phase::setMoleFractionsByName(), MultiPhase::setMoles(), SolidTransport::setParameters(), MultiPhase::setPhaseMoleFractions(), vcs_VolPhase::setPtrThermoPhase(), ThermoPhase::setState_TPX(), ThermoPhase::setState_TPY(), Transport::setThermo(), ReactorBase::setThermoMgr(), TransportFactory::setupLiquidTransport(), TransportFactory::setupMM(), Inlet1D::showSolution(), solveSP::solveSP(), StFlow::StFlow(), vcs_VolPhase::transferElementsFM(), AqueousKinetics::updateKc(), InterfaceKinetics::updateKc(), ConstPressureReactor::updateState(), Reactor::updateState(), and MultiPhase::uploadMoleFractionsFromPhases().
void checkSpeciesIndex (size_t k) const inherited
Check that the specified species index is in range Throws an exception if k is greater than nSpecies()-1.
Definition at line 268 of file Phase.cpp.
References Phase::m_kk.
Referenced by Phase::concentration(), Phase::massFraction(), Phase::molecularWeight(), Phase::moleFraction(), Phase::nAtoms(), and Phase::speciesName().
void checkSpeciesArraySize (size_t kk) const inherited
Check that an array size is at least nSpecies() Throws an exception if kk is less than nSpecies().
Used before calls which take an array pointer.
Definition at line 275 of file Phase.cpp.
References Phase::m_kk.
void saveState (vector_fp & state) const inherited
Save the current internal state of the phase Write to vector 'state' the current internal state.
Parameters
state output vector. Will be resized to nSpecies() + 2.
Definition at line 288 of file Phase.cpp.
References Phase::nSpecies().
Referenced by ChemEquil::equilibrate(), ChemEquil::estimateEP_Brinkley(), TransportFactory::newTransport(), ReactorBase::setThermoMgr(), FlowReactor::updateState(), ConstPressureReactor::updateState(), and Reactor::updateState().
void saveState (size_t lenstate, doublereal * state) const inherited
Write to array 'state' the current internal state.
Parameters
lenstate length of the state array. Must be >= nSpecies()+2
state output vector. Must be of length nSpecies() + 2 or greater.
Definition at line 293 of file Phase.cpp.
References Phase::density(), Phase::getMassFractions(), and Phase::temperature().
void restoreState (const vector_fp & state) inherited
Restore a state saved on a previous call to saveState.
Parameters
state State vector containing the previously saved state.
Definition at line 300 of file Phase.cpp.
Referenced by ChemEquil::equilibrate(), ChemEquil::estimateEP_Brinkley(), MultiTransport::getMassFluxes(), FlowReactor::initialize(), ConstPressureReactor::initialize(), Reactor::initialize(), and TransportFactory::newTransport().
void restoreState (size_t lenstate, const doublereal * state) inherited
Restore the state of the phase from a previously saved state vector.
Parameters
lenstate Length of the state vector
state Vector of state conditions.
Definition at line 305 of file Phase.cpp.
References Phase::nSpecies(), Phase::setDensity(), Phase::setMassFractions_NoNorm(), and Phase::setTemperature().
void setMoleFractionsByName (compositionMap & xMap) inherited
Set the species mole fractions by name.
@param xMap map from species names to mole fraction values.
Species not listed by name in xMap are set to zero.
Definition at line 362 of file Phase.cpp.
References Phase::nSpecies(), Phase::setMoleFractions(), and Phase::speciesName().
Referenced by Inlet1D::setMoleFractions(), OutletRes1D::setMoleFractions(), Phase::setMoleFractionsByName(), ThermoPhase::setState_TPX(), Phase::setState_TRX(), MixtureFugacityTP::setStateFromXML(), and ThermoPhase::setStateFromXML().
void setMoleFractionsByName (const std::string & x) inherited
Set the mole fractions of a group of species by name.
Species which are not listed by name in the composition map are set to zero.
Parameters
x string x in the form of a composition map
Definition at line 376 of file Phase.cpp.
References Phase::nSpecies(), Cantera::parseCompString(), Phase::setMoleFractionsByName(), and Phase::speciesName().
void setMassFractionsByName (compositionMap & yMap) inherited
Set the species mass fractions by name.
@param yMap map from species names to mass fraction values.
Species not listed by name in yMap are set to zero.
Definition at line 416 of file Phase.cpp.
References Phase::nSpecies(), Phase::setMassFractions(), and Phase::speciesName().
Referenced by Phase::setMassFractionsByName(), ThermoPhase::setState_TPY(), Phase::setState_TRY(), MixtureFugacityTP::setStateFromXML(), and ThermoPhase::setStateFromXML().
void setMassFractionsByName (const std::string & x) inherited
Set the species mass fractions by name.
Species not listed by name in x are set to zero.
Parameters
x String containing a composition map
Definition at line 430 of file Phase.cpp.
References Phase::nSpecies(), Cantera::parseCompString(), Phase::setMassFractionsByName(), and Phase::speciesName().
void setState_TRX (doublereal t, doublereal dens, const doublereal * x) inherited
Set the internally stored temperature (K), density, and mole fractions.
Parameters
t Temperature in kelvin
dens Density (kg/m^3)
x vector of species mole fractions, length m_kk
Definition at line 441 of file Phase.cpp.
References Phase::setDensity(), Phase::setMoleFractions(), and Phase::setTemperature().
void setState_TRX (doublereal t, doublereal dens, compositionMap & x) inherited
Set the internally stored temperature (K), density, and mole fractions.
Parameters
t Temperature in kelvin
dens Density (kg/m^3)
x Composition Map containing the mole fractions. Species not included in the map are assumed to have a zero mole fraction.
Definition at line 455 of file Phase.cpp.
References Phase::setDensity(), Phase::setMoleFractionsByName(), and Phase::setTemperature().
void setState_TRY (doublereal t, doublereal dens, const doublereal * y) inherited
Set the internally stored temperature (K), density, and mass fractions.
Parameters
t Temperature in kelvin
dens Density (kg/m^3)
y vector of species mass fractions, length m_kk
Definition at line 462 of file Phase.cpp.
References Phase::setDensity(), Phase::setMassFractions(), and Phase::setTemperature().
void setState_TRY (doublereal t, doublereal dens, compositionMap & y) inherited
Set the internally stored temperature (K), density, and mass fractions.
Parameters
t Temperature in kelvin
dens Density (kg/m^3)
y Composition Map containing the mass fractions. Species not included in the map are assumed to have a zero mass fraction.
Definition at line 469 of file Phase.cpp.
References Phase::setDensity(), Phase::setMassFractionsByName(), and Phase::setTemperature().
void setState_TNX (doublereal t, doublereal n, const doublereal * x) inherited
Set the internally stored temperature (K), molar density (kmol/m^3), and mole fractions.
Parameters
t Temperature in kelvin
n molar density (kmol/m^3)
x vector of species mole fractions, length m_kk
Definition at line 448 of file Phase.cpp.
References Phase::setMolarDensity(), Phase::setMoleFractions(), and Phase::setTemperature().
void setState_TR (doublereal t, doublereal rho) inherited
Set the internally stored temperature (K) and density (kg/m^3)
Parameters
t Temperature in kelvin
rho Density (kg/m^3)
Definition at line 476 of file Phase.cpp.
References Phase::setDensity(), and Phase::setTemperature().
Referenced by PureFluidPhase::setState_HP(), PureFluidPhase::setState_SP(), PureFluidPhase::setState_SV(), PDSS_IonsFromNeutral::setState_TR(), and PureFluidPhase::setState_UV().
void setState_TX (doublereal t, doublereal * x) inherited
Set the internally stored temperature (K) and mole fractions.
Parameters
t Temperature in kelvin
x vector of species mole fractions, length m_kk
Definition at line 482 of file Phase.cpp.
References Phase::setMoleFractions(), and Phase::setTemperature().
void setState_TY (doublereal t, doublereal * y) inherited
Set the internally stored temperature (K) and mass fractions.
Parameters
t Temperature in kelvin
y vector of species mass fractions, length m_kk
Definition at line 488 of file Phase.cpp.
References Phase::setMassFractions(), and Phase::setTemperature().
void setState_RX (doublereal rho, doublereal * x) inherited
Set the density (kg/m^3) and mole fractions.
Parameters
rho Density (kg/m^3)
x vector of species mole fractions, length m_kk
Definition at line 494 of file Phase.cpp.
References Phase::setDensity(), and Phase::setMoleFractions().
void setState_RY (doublereal rho, doublereal * y) inherited
Set the density (kg/m^3) and mass fractions.
Parameters
rho Density (kg/m^3)
y vector of species mass fractions, length m_kk
Definition at line 500 of file Phase.cpp.
References Phase::setDensity(), and Phase::setMassFractions().
doublereal molecularWeight (size_t k) const inherited
Molecular weight of species k.
Parameters
k index of species k
Returns
Returns the molecular weight of species k.
Definition at line 506 of file Phase.cpp.
References Phase::checkSpeciesIndex(), and Phase::m_molwts.
Referenced by VPSSMgr_Water_ConstVol::_updateRefStateThermo(), VPSSMgr_Water_HKFT::_updateRefStateThermo(), VPSSMgr_Water_ConstVol::_updateStandardStateThermo(), VPSSMgr_Water_HKFT::_updateStandardStateThermo(), SingleSpeciesTP::cv_mole(), SingleSpeciesTP::getPartialMolarVolumes(), SingleSpeciesTP::getStandardVolumes(), VPSSMgr_Water_ConstVol::getStandardVolumes_ref(), PDSS::initThermo(), VPSSMgr_Water_ConstVol::initThermoXML(), VPSSMgr_Water_HKFT::initThermoXML(), PDSS_ConstVol::initThermoXML(), MineralEQ3::initThermoXML(), PDSS_SSVol::initThermoXML(), Phase::molarMass(), MolalityVPSSTP::setSolvent(), HMWSoln::speciesMolarVolume(), and LiquidTransport::stefan_maxwell_solve().
doublereal molarMass (size_t k) const inline inherited
Return the Molar mass of species k Alternate name for molecular weight.
@param k  index for species
@return   Return the molar mass of species k kg/kmol.
Deprecated:
use molecularWeight instead
Definition at line 388 of file Phase.h.
References Phase::molecularWeight().
void getMolecularWeights (vector_fp & weights) const inherited
Copy the vector of molecular weights into vector weights.
Parameters
weights Output vector of molecular weights (kg/kmol)
Definition at line 512 of file Phase.cpp.
References Phase::molecularWeights().
void getMolecularWeights (int iwt, doublereal * weights) const inherited
Copy the vector of molecular weights into array weights.
@param iwt      Unused.
@param weights  Output array of molecular weights (kg/kmol)
Deprecated:
Definition at line 521 of file Phase.cpp.
References Phase::molecularWeights().
void getMolecularWeights (doublereal * weights) const inherited
Copy the vector of molecular weights into array weights.
Parameters
weights Output array of molecular weights (kg/kmol)
Definition at line 527 of file Phase.cpp.
References Phase::molecularWeights().
const vector_fp & molecularWeights () const inherited
Return a const reference to the internal vector of molecular weights.
units = kg / kmol
Definition at line 533 of file Phase.cpp.
References Phase::m_molwts.
Referenced by ReactingSurf1D::eval(), Phase::freezeSpecies(), Phase::getMolecularWeights(), MixTransport::getSpeciesFluxes(), AqueousTransport::getSpeciesFluxesExt(), SimpleTransport::getSpeciesFluxesExt(), Cantera::getStick(), GasTransport::initGas(), DustyGasTransport::initialize(), LiquidTransport::initLiquid(), SimpleTransport::initLiquid(), AqueousTransport::initLiquid(), TransportFactory::setupLiquidTransport(), TransportFactory::setupMM(), AqueousTransport::stefan_maxwell_solve(), LiquidTransport::stefan_maxwell_solve(), and StFlow::StFlow().
doublereal size (size_t k) const inline inherited
This routine returns the size of species k.
Parameters
k index of the species
Returns
The size of the species. Units are meters.
Definition at line 413 of file Phase.h.
References Phase::m_speciesSize.
Referenced by MolarityIonicVPSSTP::constructPhaseXML(), RedlichKisterVPSSTP::constructPhaseXML(), MargulesVPSSTP::constructPhaseXML(), MixedSolventElectrolyte::constructPhaseXML(), PhaseCombo_Interaction::constructPhaseXML(), IonsFromNeutralVPSSTP::constructPhaseXML(), IdealMolalSoln::constructPhaseXML(), IdealSolidSolnPhase::constructPhaseXML(), DebyeHuckel::constructPhaseXML(), ReactingSurf1D::eval(), SurfPhase::getCoverages(), SurfPhase::initThermo(), IdealMolalSoln::initThermoXML(), LatticeSolidPhase::installSlavePhases(), SurfPhase::setCoverages(), SurfPhase::setCoveragesNoNorm(), and SurfPhase::standardConcentration().
void getMoleFractionsByName (compositionMap & x) const inherited
Get the mole fractions by name.
Parameters
[out] x composition map containing the species mole fractions.
Definition at line 538 of file Phase.cpp.
References Phase::moleFraction(), Phase::nSpecies(), and Phase::speciesName().
doublereal moleFraction (size_t k) const inherited
Return the mole fraction of a single species.
Parameters
k species index
Returns
Mole fraction of the species
Definition at line 552 of file Phase.cpp.
References Phase::checkSpeciesIndex(), Phase::m_mmw, and Phase::m_ym.
Referenced by Phase::chargeDensity(), SolidTransport::electricalConductivity(), ChemEquil::equilibrate(), IdealMolalSoln::getActivities(), DebyeHuckel::getActivities(), HMWSoln::getActivities(), MolalityVPSSTP::getActivityCoefficients(), IdealSolnGasVPSS::getActivityConcentrations(), RedlichKwongMFTP::getActivityConcentrations(), ConstDensityThermo::getChemPotentials(), IdealSolnGasVPSS::getChemPotentials(), RedlichKwongMFTP::getChemPotentials(), IdealSolidSolnPhase::getChemPotentials(), IdealMolalSoln::getChemPotentials(), IdealGasPhase::getChemPotentials(), LatticePhase::getChemPotentials(), DebyeHuckel::getChemPotentials(), HMWSoln::getChemPotentials(), IdealSolidSolnPhase::getChemPotentials_RT(), IdealMolalSoln::getMolalityActivityCoefficients(), Phase::getMoleFractionsByName(), IdealSolnGasVPSS::getPartialMolarEntropies(), RedlichKwongMFTP::getPartialMolarEntropies(), IdealGasPhase::getPartialMolarEntropies(), IdealMolalSoln::getPartialMolarEntropies(), IdealSolidSolnPhase::getPartialMolarEntropies(), LatticePhase::getPartialMolarEntropies(), DebyeHuckel::getPartialMolarEntropies(), HMWSoln::getPartialMolarEntropies(), Phase::moleFraction(), DebyeHuckel::s_update_d2lnMolalityActCoeff_dT2(), DebyeHuckel::s_update_dlnMolalityActCoeff_dP(), DebyeHuckel::s_update_dlnMolalityActCoeff_dT(), DebyeHuckel::s_update_lnMolalityActCoeff(), HMWSoln::s_update_lnMolalityActCoeff(), IdealMolalSoln::s_updateIMS_lnMolalityActCoeff(), HMWSoln::s_updateIMS_lnMolalityActCoeff(), HMWSoln::s_updatePitzer_lnMolalityActCoeff(), and ChemEquil::setInitialMoles().
doublereal moleFraction (std::string name) const inherited
Return the mole fraction of a single species.
Parameters
name String name of the species
Returns
Mole fraction of the species
Definition at line 558 of file Phase.cpp.
References Phase::moleFraction(), Cantera::npos, and Phase::speciesIndex().
doublereal massFraction (size_t k) const inherited
Return the mass fraction of a single species.
Parameters
k species index
Returns
Mass fraction of the species
Definition at line 573 of file Phase.cpp.
References Phase::checkSpeciesIndex(), and Phase::m_y.
doublereal massFraction (std::string name) const inherited
Return the mass fraction of a single species.
Parameters
name String name of the species
Returns
Mass Fraction of the species
Definition at line 579 of file Phase.cpp.
References Phase::massFractions(), Cantera::npos, and Phase::speciesIndex().
void getMoleFractions (doublereal *const x) const inherited
Get the species mole fraction vector.
Parameters
x On return, x contains the mole fractions. Must have a length greater than or equal to the number of species.
Definition at line 547 of file Phase.cpp.
References Phase::m_mmw, Phase::m_ym, and Cantera::scale().
Referenced by IdealMolalSoln::calcDensity(), DebyeHuckel::calcDensity(), HMWSoln::calcDensity(), IonsFromNeutralVPSSTP::calcIonMoleFractions(), MolalityVPSSTP::calcMolalities(), HMWSoln::calcMolalitiesCropped(), IdealMolalSoln::enthalpy_mole(), HMWSoln::enthalpy_mole(), ChemEquil::estimateElementPotentials(), ChemEquil::estimateEP_Brinkley(), GibbsExcessVPSSTP::getActivities(), LatticePhase::getActivityConcentrations(), MultiTransport::getMassFluxes(), LTI_Pairwise_Interaction::getMatrixTransProp(), LTI_StefanMaxwell_PPN::getMatrixTransProp(), LTI_MoleFracs::getMixTransProp(), LTI_Log_MoleFracs::getMixTransProp(), LTI_Pairwise_Interaction::getMixTransProp(), LTI_StefanMaxwell_PPN::getMixTransProp(), LTI_MoleFracs_ExpT::getMixTransProp(), LatticeSolidPhase::getMoleFractions(), DustyGasTransport::initialize(), GibbsExcessVPSSTP::initThermo(), HMWSoln::printCoeffs(), HMWSoln::relative_molal_enthalpy(), PseudoBinaryVPSSTP::report(), MolarityIonicVPSSTP::report(), PureFluidPhase::report(), MolalityVPSSTP::report(), ThermoPhase::report(), PureFluidPhase::reportCSV(), MolalityVPSSTP::reportCSV(), ThermoPhase::reportCSV(), MixtureFugacityTP::setConcentrations(), GibbsExcessVPSSTP::setConcentrations(), MixtureFugacityTP::setMassFractions(), GibbsExcessVPSSTP::setMassFractions(), MixtureFugacityTP::setMassFractions_NoNorm(), GibbsExcessVPSSTP::setMassFractions_NoNorm(), MolalityVPSSTP::setMolalitiesByName(), MixtureFugacityTP::setMoleFractions(), GibbsExcessVPSSTP::setMoleFractions(), MixtureFugacityTP::setMoleFractions_NoNorm(), GibbsExcessVPSSTP::setMoleFractions_NoNorm(), MultiPhase::setMoles(), vcs_VolPhase::setPtrThermoPhase(), ThermoPhase::setReferenceComposition(), MixtureFugacityTP::setState_TP(), MixtureFugacityTP::setState_TR(), AqueousTransport::stefan_maxwell_solve(), ChemEquil::update(), MixTransport::update_C(), MultiTransport::update_C(), AqueousTransport::update_C(), SimpleTransport::update_C(), LiquidTransport::update_C(), solveSP::updateMFKinSpecies(), DustyGasTransport::updateTransport_C(), and MultiPhase::uploadMoleFractionsFromPhases().
void getMassFractions (doublereal *const y) const inherited
Get the species mass fractions.
Parameters
[out] y Array of mass fractions, length nSpecies()
Definition at line 589 of file Phase.cpp.
References Phase::m_y.
Referenced by LTI_MassFracs::getMixTransProp(), Cantera::importSolution(), PureFluidPhase::report(), ThermoPhase::report(), PureFluidPhase::reportCSV(), ThermoPhase::reportCSV(), Phase::saveState(), Inlet1D::setMoleFractions(), OutletRes1D::setMoleFractions(), and LiquidTransport::update_C().
const doublereal* massFractions () const inline inherited
Return a const pointer to the mass fraction array.
Definition at line 469 of file Phase.h.
References Phase::m_y.
Referenced by MultiTransport::getMassFluxes(), MultiTransport::getSpeciesFluxes(), MixTransport::getSpeciesFluxes(), AqueousTransport::getSpeciesFluxesExt(), SimpleTransport::getSpeciesFluxesExt(), SimpleTransport::getSpeciesVdiff(), SimpleTransport::getSpeciesVdiffES(), and Phase::massFraction().
void getConcentrations (doublereal *const c) const inherited
Get the species concentrations (kmol/m^3).
@param[out] c Array of species concentrations Length must be
greater than or equal to the number of species.
Definition at line 600 of file Phase.cpp.
References Phase::m_dens, Phase::m_ym, and Cantera::scale().
Referenced by ConstDensityThermo::getActivityConcentrations(), IdealSolnGasVPSS::getActivityConcentrations(), SurfPhase::getActivityConcentrations(), IdealGasPhase::getActivityConcentrations(), SurfPhase::getCoverages(), solveSP::solveSurfProb(), SimpleTransport::update_C(), and LiquidTransport::update_C().
doublereal concentration (const size_t k) const inherited
Concentration of species k.
If k is outside the valid range, an exception will be thrown.
Parameters
k Index of species
Definition at line 594 of file Phase.cpp.
References Phase::checkSpeciesIndex(), Phase::m_dens, Phase::m_rmolwts, and Phase::m_y.
const doublereal * moleFractdivMMW () const inherited
Returns a const pointer to the start of the moleFraction/MW array.
This array is the array of mole fractions, each divided by the mean molecular weight.
Definition at line 568 of file Phase.cpp.
References Phase::m_ym.
Referenced by IdealSolnGasVPSS::calcDensity(), RedlichKwongMFTP::calcDensity(), IdealSolidSolnPhase::calcDensity(), and IdealSolidSolnPhase::getActivityConcentrations().
doublereal charge (size_t k) const inherited
Dimensionless electrical charge of a single molecule of species k The charge is normalized by the the magnitude of the electron charge.
Parameters
k species index
Definition at line 642 of file Phase.cpp.
References Phase::m_speciesCharge.
Referenced by InterfaceKinetics::applyButlerVolmerCorrection(), HMWSoln::calcMolalitiesCropped(), Phase::chargeDensity(), PDSS_HKFT::constructPDSSXML(), SolidTransport::electricalConductivity(), PureFluidPhase::getElectrochemPotentials(), PseudoBinaryVPSSTP::getElectrochemPotentials(), MolarityIonicVPSSTP::getElectrochemPotentials(), GibbsExcessVPSSTP::getElectrochemPotentials(), RedlichKisterVPSSTP::getElectrochemPotentials(), MargulesVPSSTP::getElectrochemPotentials(), ThermoPhase::getElectrochemPotentials(), MixedSolventElectrolyte::getElectrochemPotentials(), MolalityVPSSTP::getElectrochemPotentials(), PhaseCombo_Interaction::getElectrochemPotentials(), InterfaceKinetics::getEquilibriumConstants(), LiquidTransport::initLiquid(), SimpleTransport::initLiquid(), PDSS_HKFT::initThermo(), IonsFromNeutralVPSSTP::initThermoXML(), DebyeHuckel::initThermoXML(), LatticeSolidPhase::installSlavePhases(), HMWSoln::printCoeffs(), PhaseCombo_Interaction::readXMLBinarySpecies(), RedlichKisterVPSSTP::readXMLBinarySpecies(), MargulesVPSSTP::readXMLBinarySpecies(), MixedSolventElectrolyte::readXMLBinarySpecies(), HMWSoln::relative_molal_enthalpy(), HMWSoln::s_updatePitzer_d2lnMolalityActCoeff_dT2(), HMWSoln::s_updatePitzer_dlnMolalityActCoeff_dP(), HMWSoln::s_updatePitzer_dlnMolalityActCoeff_dT(), HMWSoln::s_updatePitzer_lnMolalityActCoeff(), MolalityVPSSTP::setMolalitiesByName(), vcs_VolPhase::transferElementsFM(), and InterfaceKinetics::updateKc().
doublereal chargeDensity () const inherited
Charge density [C/m^3].
Definition at line 647 of file Phase.cpp.
References Phase::charge(), Phase::moleFraction(), and Phase::nSpecies().
size_t nDim () const inline inherited
Returns the number of spatial dimensions (1, 2, or 3)
Definition at line 523 of file Phase.h.
References Phase::m_ndim.
Referenced by Kinetics::addPhase(), EdgeKinetics::finalize(), InterfaceKinetics::finalize(), IdealSolnGasVPSS::getUnitsStandardConc(), RedlichKwongMFTP::getUnitsStandardConc(), IdealMolalSoln::getUnitsStandardConc(), MolalityVPSSTP::getUnitsStandardConc(), IdealSolidSolnPhase::getUnitsStandardConc(), ThermoPhase::getUnitsStandardConc(), DebyeHuckel::getUnitsStandardConc(), and HMWSoln::getUnitsStandardConc().
void setNDim (size_t ndim) inline inherited
Set the number of spatial dimensions (1, 2, or 3).
The number of spatial dimensions is used for vector involving directions.
Parameters
ndim Input number of dimensions.
Definition at line 530 of file Phase.h.
References Phase::m_ndim.
Referenced by EdgePhase::EdgePhase(), FixedChemPotSSTP::FixedChemPotSSTP(), Cantera::importPhase(), EdgePhase::operator=(), and SurfPhase::SurfPhase().
doublereal temperature () const inline inherited
Temperature (K).
Returns
The temperature of the phase
Definition at line 539 of file Phase.h.
References Phase::m_temp.
Referenced by ThermoPhase::_RT(), InterfaceKinetics::_update_rates_T(), MixtureFugacityTP::_updateReferenceStateThermo(), VPStandardStateTP::_updateStandardStateThermo(), ConstDensityThermo::_updateThermo(), SurfPhase::_updateThermo(), LatticeSolidPhase::_updateThermo(), SingleSpeciesTP::_updateThermo(), IdealGasPhase::_updateThermo(), LatticePhase::_updateThermo(), IdealSolidSolnPhase::_updateThermo(), DebyeHuckel::A_Debye_TP(), HMWSoln::A_Debye_TP(), MultiPhase::addPhase(), HMWSoln::ADebye_J(), HMWSoln::ADebye_L(), HMWSoln::ADebye_V(), InterfaceKinetics::applyButlerVolmerCorrection(), InterfaceKinetics::applyExchangeCurrentDensityFormulation(), IdealSolnGasVPSS::calcDensity(), MixtureFugacityTP::calculatePsat(), RedlichKwongMFTP::cp_mole(), SingleSpeciesTP::cv_mole(), HMWSoln::cv_mole(), DebyeHuckel::d2A_DebyedT2_TP(), HMWSoln::d2A_DebyedT2_TP(), DebyeHuckel::dA_DebyedP_TP(), HMWSoln::dA_DebyedP_TP(), DebyeHuckel::dA_DebyedT_TP(), HMWSoln::dA_DebyedT_TP(), WaterSSTP::dthermalExpansionCoeffdT(), IdealSolnGasVPSS::enthalpy_mole(), ConstDensityThermo::enthalpy_mole(), IdealSolidSolnPhase::enthalpy_mole(), LatticePhase::enthalpy_mole(), IdealGasPhase::enthalpy_mole(), ChemEquil::equilibrate(), ChemEquil::estimateElementPotentials(), ChemEquil::estimateEP_Brinkley(), FixedChemPotSSTP::FixedChemPotSSTP(), RedlichKwongMFTP::getActivityCoefficients(), ConstDensityThermo::getChemPotentials(), SurfPhase::getChemPotentials(), MolarityIonicVPSSTP::getChemPotentials(), IdealSolnGasVPSS::getChemPotentials(), IonsFromNeutralVPSSTP::getChemPotentials(), RedlichKwongMFTP::getChemPotentials(), RedlichKisterVPSSTP::getChemPotentials(), MargulesVPSSTP::getChemPotentials(), MixedSolventElectrolyte::getChemPotentials(), PhaseCombo_Interaction::getChemPotentials(), IdealSolidSolnPhase::getChemPotentials(), IdealMolalSoln::getChemPotentials(), IdealGasPhase::getChemPotentials(), LatticePhase::getChemPotentials(), DebyeHuckel::getChemPotentials(), HMWSoln::getChemPotentials(), StoichSubstance::getChemPotentials_RT(), SingleSpeciesTP::getChemPotentials_RT(), IdealSolidSolnPhase::getChemPotentials_RT(), WaterSSTP::getCp_R_ref(), AqueousKinetics::getDeltaSSEnthalpy(), GasKinetics::getDeltaSSEnthalpy(), InterfaceKinetics::getDeltaSSEnthalpy(), PhaseCombo_Interaction::getdlnActCoeffds(), MargulesVPSSTP::getdlnActCoeffds(), MixedSolventElectrolyte::getdlnActCoeffds(), ThermoPhase::getElementPotentials(), WaterSSTP::getEnthalpy_RT(), StoichSubstance::getEnthalpy_RT(), StoichSubstanceSSTP::getEnthalpy_RT(), MineralEQ3::getEnthalpy_RT(), SurfPhase::getEnthalpy_RT(), IdealSolidSolnPhase::getEnthalpy_RT(), LatticePhase::getEnthalpy_RT(), WaterSSTP::getEnthalpy_RT_ref(), PureFluidPhase::getEnthalpy_RT_ref(), WaterSSTP::getEntropy_R_ref(), PureFluidPhase::getEntropy_R_ref(), AqueousKinetics::getEquilibriumConstants(), GasKinetics::getEquilibriumConstants(), InterfaceKinetics::getEquilibriumConstants(), StoichSubstance::getGibbs_ref(), PureFluidPhase::getGibbs_ref(), SingleSpeciesTP::getGibbs_ref(), LatticeSolidPhase::getGibbs_ref(), IdealSolidSolnPhase::getGibbs_ref(), LatticePhase::getGibbs_ref(), WaterSSTP::getGibbs_RT(), StoichSubstance::getGibbs_RT(), SurfPhase::getGibbs_RT(), WaterSSTP::getGibbs_RT_ref(), PureFluidPhase::getGibbs_RT_ref(), StoichSubstanceSSTP::getIntEnergy_RT(), MineralEQ3::getIntEnergy_RT(), IdealSolidSolnPhase::getIntEnergy_RT(), StoichSubstanceSSTP::getIntEnergy_RT_ref(), MineralEQ3::getIntEnergy_RT_ref(), MetalSHEelectrons::getIntEnergy_RT_ref(), IdealSolidSolnPhase::getIntEnergy_RT_ref(), LTI_Pairwise_Interaction::getMatrixTransProp(), LTI_StefanMaxwell_PPN::getMatrixTransProp(), SolidTransport::getMixDiffCoeffs(), LTI_MoleFracs::getMixTransProp(), LTI_MassFracs::getMixTransProp(), LTI_Log_MoleFracs::getMixTransProp(), LTI_MoleFracs_ExpT::getMixTransProp(), SolidTransport::getMobilities(), MolarityIonicVPSSTP::getPartialMolarCp(), RedlichKisterVPSSTP::getPartialMolarCp(), MargulesVPSSTP::getPartialMolarCp(), MixedSolventElectrolyte::getPartialMolarCp(), PhaseCombo_Interaction::getPartialMolarCp(), DebyeHuckel::getPartialMolarCp(), HMWSoln::getPartialMolarCp(), SurfPhase::getPartialMolarEnthalpies(), IdealSolnGasVPSS::getPartialMolarEnthalpies(), MolarityIonicVPSSTP::getPartialMolarEnthalpies(), SingleSpeciesTP::getPartialMolarEnthalpies(), IonsFromNeutralVPSSTP::getPartialMolarEnthalpies(), RedlichKwongMFTP::getPartialMolarEnthalpies(), RedlichKisterVPSSTP::getPartialMolarEnthalpies(), MargulesVPSSTP::getPartialMolarEnthalpies(), MixedSolventElectrolyte::getPartialMolarEnthalpies(), PhaseCombo_Interaction::getPartialMolarEnthalpies(), IdealGasPhase::getPartialMolarEnthalpies(), IdealSolidSolnPhase::getPartialMolarEnthalpies(), LatticePhase::getPartialMolarEnthalpies(), DebyeHuckel::getPartialMolarEnthalpies(), HMWSoln::getPartialMolarEnthalpies(), MolarityIonicVPSSTP::getPartialMolarEntropies(), IonsFromNeutralVPSSTP::getPartialMolarEntropies(), RedlichKwongMFTP::getPartialMolarEntropies(), RedlichKisterVPSSTP::getPartialMolarEntropies(), MargulesVPSSTP::getPartialMolarEntropies(), MixedSolventElectrolyte::getPartialMolarEntropies(), PhaseCombo_Interaction::getPartialMolarEntropies(), DebyeHuckel::getPartialMolarEntropies(), HMWSoln::getPartialMolarEntropies(), IdealSolnGasVPSS::getPartialMolarIntEnergies(), SingleSpeciesTP::getPartialMolarIntEnergies(), RedlichKwongMFTP::getPartialMolarIntEnergies(), IdealGasPhase::getPartialMolarIntEnergies(), RedlichKwongMFTP::getPartialMolarVolumes(), MargulesVPSSTP::getPartialMolarVolumes(), MixedSolventElectrolyte::getPartialMolarVolumes(), PhaseCombo_Interaction::getPartialMolarVolumes(), DebyeHuckel::getPartialMolarVolumes(), HMWSoln::getPartialMolarVolumes(), SingleSpeciesTP::getPureGibbs(), LatticePhase::getPureGibbs(), LTPspecies_Arrhenius::getSpeciesTransProp(), LTPspecies_Poly::getSpeciesTransProp(), LTPspecies_ExpT::getSpeciesTransProp(), WaterSSTP::getStandardChemPotentials(), StoichSubstanceSSTP::getStandardChemPotentials(), MineralEQ3::getStandardChemPotentials(), MetalSHEelectrons::getStandardChemPotentials(), IdealGasPhase::getStandardChemPotentials(), WaterSSTP::getStandardVolumes_ref(), IdealSolnGasVPSS::gibbs_mole(), ConstDensityThermo::gibbs_mole(), StoichSubstance::gibbs_mole(), RedlichKwongMFTP::gibbs_mole(), IdealSolidSolnPhase::gibbs_mole(), ThermoPhase::gibbs_mole(), LatticePhase::gibbs_mole(), IdealGasPhase::gibbs_mole(), RedlichKwongMFTP::hresid(), ConstDensityThermo::intEnergy_mole(), StoichSubstance::intEnergy_mole(), IdealSolidSolnPhase::intEnergy_mole(), LatticePhase::intEnergy_mole(), IdealGasPhase::intEnergy_mole(), IdealGasPhase::logStandardConc(), MixtureFugacityTP::phaseState(), RedlichKwongMFTP::pressure(), IdealGasPhase::pressure(), MixTransport::pressure_ig(), RedlichKwongMFTP::pressureDerivatives(), HMWSoln::relative_enthalpy(), PseudoBinaryVPSSTP::report(), MolarityIonicVPSSTP::report(), PureFluidPhase::report(), MolalityVPSSTP::report(), ThermoPhase::report(), PureFluidPhase::reportCSV(), MolalityVPSSTP::reportCSV(), ThermoPhase::reportCSV(), PhaseCombo_Interaction::s_update_dlnActCoeff_dlnN(), MargulesVPSSTP::s_update_dlnActCoeff_dlnN(), MixedSolventElectrolyte::s_update_dlnActCoeff_dlnN(), PhaseCombo_Interaction::s_update_dlnActCoeff_dlnN_diag(), MargulesVPSSTP::s_update_dlnActCoeff_dlnN_diag(), MixedSolventElectrolyte::s_update_dlnActCoeff_dlnN_diag(), PhaseCombo_Interaction::s_update_dlnActCoeff_dlnX_diag(), MargulesVPSSTP::s_update_dlnActCoeff_dlnX_diag(), MixedSolventElectrolyte::s_update_dlnActCoeff_dlnX_diag(), PhaseCombo_Interaction::s_update_dlnActCoeff_dT(), MargulesVPSSTP::s_update_dlnActCoeff_dT(), MixedSolventElectrolyte::s_update_dlnActCoeff_dT(), RedlichKisterVPSSTP::s_update_dlnActCoeff_dX_(), PhaseCombo_Interaction::s_update_lnActCoeff(), RedlichKisterVPSSTP::s_update_lnActCoeff(), MargulesVPSSTP::s_update_lnActCoeff(), MixedSolventElectrolyte::s_update_lnActCoeff(), HMWSoln::s_updatePitzer_CoeffWRTemp(), HMWSoln::s_updatePitzer_dlnMolalityActCoeff_dP(), HMWSoln::s_updatePitzer_lnMolalityActCoeff(), WaterSSTP::satPressure(), HMWSoln::satPressure(), Phase::saveState(), WaterSSTP::setDensity(), ThermoPhase::setElementPotentials(), ChemEquil::setInitialMoles(), PureFluidPhase::setPressure(), WaterSSTP::setPressure(), GibbsExcessVPSSTP::setPressure(), IdealMolalSoln::setPressure(), VPStandardStateTP::setPressure(), MixtureFugacityTP::setPressure(), IdealGasPhase::setPressure(), IonsFromNeutralVPSSTP::setPressure(), DebyeHuckel::setPressure(), HMWSoln::setPressure(), vcs_VolPhase::setPtrThermoPhase(), SingleSpeciesTP::setState_HP(), ThermoPhase::setState_HPorUV(), SingleSpeciesTP::setState_SP(), ThermoPhase::setState_SPorSV(), SingleSpeciesTP::setState_SV(), SingleSpeciesTP::setState_UV(), MixtureFugacityTP::setStateFromXML(), MixtureFugacityTP::setTemperature(), PureFluidPhase::setTPXState(), ImplicitSurfChem::solvePseudoSteadyStateProblem(), RedlichKwongMFTP::sresid(), IdealSolnGasVPSS::standardConcentration(), IdealGasPhase::standardConcentration(), AqueousTransport::stefan_maxwell_solve(), LiquidTransport::stefan_maxwell_solve(), SolidTransport::thermalConductivity(), MetalSHEelectrons::thermalExpansionCoeff(), IdealGasPhase::thermalExpansionCoeff(), ChemEquil::update(), MixTransport::update_T(), MultiTransport::update_T(), AqueousTransport::update_T(), SimpleTransport::update_T(), LiquidTransport::update_T(), RedlichKwongMFTP::updateAB(), AqueousKinetics::updateKc(), GasKinetics::updateKc(), InterfaceKinetics::updateKc(), VPStandardStateTP::updateStandardStateThermo(), Reactor::updateState(), MultiTransport::updateThermal_T(), DustyGasTransport::updateTransport_T(), and WaterSSTP::vaporFraction().
virtual doublereal density () const inline virtual inherited
Density (kg/m^3).
Returns
The density of the phase
Reimplemented in HMWSoln.
Definition at line 545 of file Phase.h.
References Phase::m_dens.
Referenced by MixtureFugacityTP::calculatePsat(), SingleSpeciesTP::cv_mole(), HMWSoln::density(), WaterSSTP::dthermalExpansionCoeffdT(), WaterSSTP::getCp_R_ref(), WaterSSTP::getEnthalpy_RT_ref(), WaterSSTP::getEntropy_R_ref(), WaterSSTP::getGibbs_RT_ref(), MultiTransport::getMassFluxes(), ConstDensityThermo::getParameters(), StoichSubstance::getParameters(), StoichSubstanceSSTP::getParameters(), MetalSHEelectrons::getParameters(), MineralEQ3::getParameters(), SingleSpeciesTP::getPartialMolarVolumes(), MultiTransport::getSpeciesFluxes(), SimpleTransport::getSpeciesVdiff(), SimpleTransport::getSpeciesVdiffES(), SingleSpeciesTP::getStandardVolumes(), WaterSSTP::getStandardVolumes_ref(), RedlichKwongMFTP::hresid(), Phase::molarDensity(), MixtureFugacityTP::phaseState(), RedlichKwongMFTP::pressure(), PseudoBinaryVPSSTP::report(), MolarityIonicVPSSTP::report(), PureFluidPhase::report(), MolalityVPSSTP::report(), ThermoPhase::report(), PureFluidPhase::reportCSV(), MolalityVPSSTP::reportCSV(), ThermoPhase::reportCSV(), WaterSSTP::satPressure(), Phase::saveState(), IdealMolalSoln::setDensity(), IdealSolidSolnPhase::setDensity(), Phase::setDensity(), DebyeHuckel::setDensity(), WaterSSTP::setPressure(), MixtureFugacityTP::setState_TP(), IonsFromNeutralVPSSTP::setState_TP(), MixtureFugacityTP::setStateFromXML(), MixtureFugacityTP::setTemperature(), WaterSSTP::setTemperature(), PureFluidPhase::setTPXState(), RedlichKwongMFTP::sresid(), ChemEquil::update(), SimpleTransport::update_C(), LiquidTransport::update_C(), ConstPressureReactor::updateState(), StFlow::updateThermo(), WaterSSTP::vaporFraction(), and MixtureFugacityTP::z().
doublereal molarDensity () const inherited
Molar density (kmol/m^3).
Returns
The molar density of the phase
Definition at line 627 of file Phase.cpp.
References Phase::density(), and Phase::meanMolecularWeight().
Referenced by solveSP::calc_t(), SolidTransport::electricalConductivity(), ConstDensityThermo::enthalpy_mole(), StoichSubstance::enthalpy_mole(), IdealSolidSolnPhase::enthalpy_mole(), LatticePhase::enthalpy_mole(), ConstDensityThermo::getChemPotentials(), StoichSubstanceSSTP::getEnthalpy_RT(), MineralEQ3::getEnthalpy_RT(), StoichSubstanceSSTP::getIntEnergy_RT(), MineralEQ3::getIntEnergy_RT(), StoichSubstanceSSTP::getIntEnergy_RT_ref(), MineralEQ3::getIntEnergy_RT_ref(), MetalSHEelectrons::getIntEnergy_RT_ref(), LatticePhase::getParameters(), PureFluidPhase::getPartialMolarVolumes(), StoichSubstance::getPartialMolarVolumes(), IdealGasPhase::getPartialMolarVolumes(), MixTransport::getSpeciesFluxes(), AqueousTransport::getSpeciesFluxesExt(), SimpleTransport::getSpeciesFluxesExt(), StoichSubstance::getStandardVolumes(), IdealGasPhase::getStandardVolumes(), IdealSolnGasVPSS::intEnergy_mole(), ConstDensityThermo::intEnergy_mole(), StoichSubstance::intEnergy_mole(), RedlichKwongMFTP::intEnergy_mole(), IonsFromNeutralVPSSTP::intEnergy_mole(), IdealSolidSolnPhase::intEnergy_mole(), LatticePhase::intEnergy_mole(), DebyeHuckel::intEnergy_mole(), HMWSoln::intEnergy_mole(), ConstDensityThermo::logStandardConc(), Phase::molarVolume(), IdealGasPhase::pressure(), MixTransport::pressure_ig(), IdealMolalSoln::setMolarDensity(), DebyeHuckel::setMolarDensity(), and ConstDensityThermo::standardConcentration().
doublereal molarVolume () const inherited
Molar volume (m^3/kmol).
Returns
The molar volume of the phase
Definition at line 637 of file Phase.cpp.
References Phase::molarDensity().
Referenced by RedlichKwongMFTP::cp_mole(), HMWSoln::cv_mole(), RedlichKwongMFTP::getActivityCoefficients(), RedlichKwongMFTP::getChemPotentials(), LTI_StefanMaxwell_PPN::getMatrixTransProp(), RedlichKwongMFTP::getPartialMolarEnthalpies(), RedlichKwongMFTP::getPartialMolarEntropies(), RedlichKwongMFTP::getPartialMolarVolumes(), ThermoPhase::intEnergy_mole(), RedlichKwongMFTP::pressureDerivatives(), MixtureFugacityTP::setState_TR(), and LiquidTransport::stefan_maxwell_solve().
virtual void setDensity (const doublereal density) inline virtual inherited
Set the internally stored density (kg/m^3) of the phase Note the density of a phase is an independent variable.
Parameters
[in] density density (kg/m^3).
Reimplemented in HMWSoln, DebyeHuckel, WaterSSTP, IdealSolidSolnPhase, and IdealMolalSoln.
Definition at line 560 of file Phase.h.
References Phase::density(), and Phase::m_dens.
Referenced by IdealSolnGasVPSS::calcDensity(), RedlichKwongMFTP::calcDensity(), GibbsExcessVPSSTP::calcDensity(), IdealMolalSoln::calcDensity(), IdealSolidSolnPhase::calcDensity(), LatticeSolidPhase::calcDensity(), DebyeHuckel::calcDensity(), HMWSoln::calcDensity(), StoichSubstanceSSTP::initThermoXML(), WaterSSTP::initThermoXML(), MetalSHEelectrons::initThermoXML(), MineralEQ3::initThermoXML(), electrodeElectron::initThermoXML(), Phase::restoreState(), Phase::setConcentrations(), WaterSSTP::setDensity(), ConstDensityThermo::setParameters(), StoichSubstance::setParameters(), StoichSubstanceSSTP::setParameters(), MetalSHEelectrons::setParameters(), MineralEQ3::setParameters(), electrodeElectron::setParameters(), SemiconductorPhase::setParametersFromXML(), MetalPhase::setParametersFromXML(), StoichSubstance::setParametersFromXML(), ConstDensityThermo::setParametersFromXML(), StoichSubstanceSSTP::setParametersFromXML(), MetalSHEelectrons::setParametersFromXML(), PureFluidPhase::setPressure(), IdealGasPhase::setPressure(), ThermoPhase::setState_HPorUV(), PureFluidPhase::setState_Psat(), Phase::setState_RX(), Phase::setState_RY(), ThermoPhase::setState_SPorSV(), SingleSpeciesTP::setState_SV(), MixtureFugacityTP::setState_TP(), IonsFromNeutralVPSSTP::setState_TP(), Phase::setState_TR(), MixtureFugacityTP::setState_TR(), Phase::setState_TRX(), Phase::setState_TRY(), PureFluidPhase::setState_Tsat(), SingleSpeciesTP::setState_UV(), ThermoPhase::setStateFromXML(), and Reactor::updateState().
void setMolarDensity (const doublereal molarDensity) virtual inherited
Set the internally stored molar density (kmol/m^3) of the phase.
Parameters
[in] molarDensity Input molar density (kmol/m^3).
Reimplemented in HMWSoln, DebyeHuckel, IdealSolidSolnPhase, and IdealMolalSoln.
Definition at line 632 of file Phase.cpp.
References Phase::m_dens, and Phase::meanMolecularWeight().
Referenced by LatticePhase::calcDensity(), LatticePhase::setParameters(), and Phase::setState_TNX().
doublereal mean_X (const doublereal *const Q) const inherited
Evaluate the mole-fraction-weighted mean of an array Q.
\[ \sum_k X_k Q_k. \]
Q should contain pure-species molar property values.
Parameters
[in] Q Array of length m_kk that is to be averaged.
Returns
mole-fraction-weighted mean of Q
Definition at line 658 of file Phase.cpp.
References Phase::m_mmw, and Phase::m_ym.
Referenced by IdealSolnGasVPSS::cp_mole(), ConstDensityThermo::cp_mole(), RedlichKwongMFTP::cp_mole(), IonsFromNeutralVPSSTP::cp_mole(), IdealSolidSolnPhase::cp_mole(), IdealMolalSoln::cp_mole(), LatticePhase::cp_mole(), IdealGasPhase::cp_mole(), DebyeHuckel::cp_mole(), HMWSoln::cp_mole(), IonsFromNeutralVPSSTP::cv_mole(), IdealSolnGasVPSS::enthalpy_mole(), ConstDensityThermo::enthalpy_mole(), RedlichKwongMFTP::enthalpy_mole(), IdealSolidSolnPhase::enthalpy_mole(), IonsFromNeutralVPSSTP::enthalpy_mole(), IdealMolalSoln::enthalpy_mole(), SurfPhase::enthalpy_mole(), LatticePhase::enthalpy_mole(), IdealGasPhase::enthalpy_mole(), DebyeHuckel::enthalpy_mole(), HMWSoln::enthalpy_mole(), IdealSolnGasVPSS::entropy_mole(), ConstDensityThermo::entropy_mole(), RedlichKwongMFTP::entropy_mole(), IonsFromNeutralVPSSTP::entropy_mole(), IdealSolidSolnPhase::entropy_mole(), IdealMolalSoln::entropy_mole(), LatticePhase::entropy_mole(), IdealGasPhase::entropy_mole(), DebyeHuckel::entropy_mole(), HMWSoln::entropy_mole(), IonsFromNeutralVPSSTP::gibbs_mole(), IdealSolidSolnPhase::gibbs_mole(), IdealMolalSoln::gibbs_mole(), DebyeHuckel::gibbs_mole(), HMWSoln::gibbs_mole(), ConstDensityThermo::intEnergy_mole(), IdealSolidSolnPhase::intEnergy_mole(), IdealMolalSoln::intEnergy_mole(), LatticePhase::intEnergy_mole(), IdealGasPhase::intEnergy_mole(), and HMWSoln::relative_enthalpy().
doublereal mean_Y (const doublereal *const Q) const inherited
Evaluate the mass-fraction-weighted mean of an array Q.
\[ \sum_k Y_k Q_k \]
Parameters
[in] Q Array of species property values in mass units.
Returns
The mass-fraction-weighted mean of Q.
Definition at line 663 of file Phase.cpp.
References Cantera::dot(), and Phase::m_y.
doublereal meanMolecularWeight () const inline inherited
The mean molecular weight. Units: (kg/kmol)
Definition at line 592 of file Phase.h.
References Phase::m_mmw.
Referenced by IdealSolnGasVPSS::calcDensity(), GibbsExcessVPSSTP::calcDensity(), IdealMolalSoln::calcDensity(), LatticePhase::calcDensity(), DebyeHuckel::calcDensity(), HMWSoln::calcDensity(), MixtureFugacityTP::calculatePsat(), ThermoPhase::cp_mass(), RedlichKwongMFTP::critDensity(), ThermoPhase::cv_mass(), RedlichKwongMFTP::densityCalc(), MixtureFugacityTP::densityCalc(), RedlichKwongMFTP::densSpinodalGas(), RedlichKwongMFTP::densSpinodalLiquid(), ThermoPhase::enthalpy_mass(), ThermoPhase::entropy_mass(), IdealSolidSolnPhase::getActivityConcentrations(), GasTransport::getMixDiffCoeffs(), AqueousTransport::getMixDiffCoeffs(), GasTransport::getMixDiffCoeffsMass(), MultiTransport::getMultiDiffCoeffs(), WaterSSTP::getStandardVolumes_ref(), ThermoPhase::gibbs_mass(), RedlichKwongMFTP::hresid(), ThermoPhase::intEnergy_mass(), Phase::molarDensity(), MixtureFugacityTP::phaseState(), RedlichKwongMFTP::pressure(), PseudoBinaryVPSSTP::report(), MolarityIonicVPSSTP::report(), PureFluidPhase::report(), MolalityVPSSTP::report(), ThermoPhase::report(), PureFluidPhase::reportCSV(), MolalityVPSSTP::reportCSV(), ThermoPhase::reportCSV(), Phase::setMolarDensity(), IdealGasPhase::setPressure(), RedlichKwongMFTP::sresid(), SimpleTransport::update_C(), LiquidTransport::update_C(), StFlow::updateThermo(), StFlow::updateTransport(), and MixtureFugacityTP::z().
doublereal sum_xlogx () const inherited
Evaluate \(\sum_k X_k \log X_k \).
Returns
The indicated sum. Dimensionless.
Definition at line 668 of file Phase.cpp.
References Phase::m_mmw, Phase::m_ym, and Cantera::sum_xlogx().
Referenced by IdealSolnGasVPSS::entropy_mole(), ConstDensityThermo::entropy_mole(), RedlichKwongMFTP::entropy_mole(), IdealSolidSolnPhase::entropy_mole(), LatticePhase::entropy_mole(), IdealGasPhase::entropy_mole(), and IdealSolidSolnPhase::gibbs_mole().
doublereal sum_xlogQ (doublereal *const Q) const inherited
Evaluate \(\sum_k X_k \log Q_k \).
Parameters
Q Vector of length m_kk to take the log average of
Returns
The indicated sum.
Definition at line 673 of file Phase.cpp.
References Phase::m_mmw, Phase::m_ym, and Cantera::sum_xlogQ().
void addElement (const std::string & symbol, doublereal weight = -12345.0) inherited
Add an element.
Parameters
symbol Atomic symbol std::string.
weight Atomic mass in amu.
Definition at line 678 of file Phase.cpp.
References CT_ELEM_TYPE_ABSPOS, CT_ELEM_TYPE_ELECTRONCHARGE, Cantera::LookupWtElements(), Phase::m_atomicWeights, Phase::m_elem_type, Phase::m_elementNames, Phase::m_elementsFrozen, and Phase::m_mm.
Referenced by Phase::addElement().
void addElement (const XML_Node & e) inherited
Add an element from an XML specification.
Parameters
e Reference to the XML_Node where the element is described.
Definition at line 701 of file Phase.cpp.
References Phase::addElement().
void addUniqueElement (const std::string & symbol, doublereal weight = -12345.0, int atomicNumber = 0, doublereal entropy298 = ENTROPY298_UNKNOWN, int elem_type = CT_ELEM_TYPE_ABSPOS) inherited
Add an element, checking for uniqueness The uniqueness is checked by comparing the string symbol.
If not unique, nothing is done.
Parameters
symbol String symbol of the element
weight Atomic weight of the element (kg kmol-1).
atomicNumber Atomic number of the element (unitless)
entropy298 Entropy of the element at 298 K and 1 bar in its most stable form. The default is the value ENTROPY298_UNKNOWN, which is interpreted as an unknown, and if used will cause Cantera to throw an error.
elem_type Specifies the type of the element constraint equation. This defaults to CT_ELEM_TYPE_ABSPOS, i.e., an element.
Definition at line 708 of file Phase.cpp.
References CT_ELEM_TYPE_ELECTRONCHARGE, Cantera::LookupWtElements(), Phase::m_atomicNumbers, Phase::m_atomicWeights, Phase::m_elem_type, Phase::m_elementNames, Phase::m_elementsFrozen, Phase::m_entropy298, and Phase::m_mm.
Referenced by Phase::addElementsFromXML(), Phase::addUniqueElement(), Phase::addUniqueElementAfterFreeze(), and FixedChemPotSSTP::FixedChemPotSSTP().
void addUniqueElement (const XML_Node & e) inherited
Add an element, checking for uniqueness The uniqueness is checked by comparing the string symbol.
If not unique, nothing is done.
Parameters
e Reference to the XML_Node where the element is described.
Definition at line 755 of file Phase.cpp.
References Phase::addUniqueElement(), Cantera::atofCheck(), XML_Node::child(), ENTROPY298_UNKNOWN, XML_Node::hasAttrib(), XML_Node::hasChild(), and Cantera::stripws().
void addElementsFromXML (const XML_Node & phase) inherited
Add all elements referenced in an XML_Node tree.
Parameters
phase Reference to the root XML_Node of a phase
Definition at line 780 of file Phase.cpp.
References Phase::addUniqueElement(), XML_Node::child(), XML_Node::findByAttr(), Cantera::get_XML_File(), ctml::getStringArray(), XML_Node::hasAttrib(), XML_Node::hasChild(), and XML_Node::root().
Referenced by Cantera::importPhase().
void freezeElements () inherited
Prohibit addition of more elements, and prepare to add species.
Definition at line 831 of file Phase.cpp.
References Phase::m_elementsFrozen.
Referenced by FixedChemPotSSTP::FixedChemPotSSTP().
bool elementsFrozen () inherited
True if freezeElements has been called.
Definition at line 836 of file Phase.cpp.
References Phase::m_elementsFrozen.
size_t addUniqueElementAfterFreeze (const std::string & symbol, doublereal weight, int atomicNumber, doublereal entropy298 = ENTROPY298_UNKNOWN, int elem_type = CT_ELEM_TYPE_ABSPOS) inherited
Add an element after elements have been frozen, checking for uniqueness The uniqueness is checked by comparing the string symbol.
If not unique, nothing is done.
Parameters
symbol String symbol of the element
weight Atomic weight of the element (kg kmol-1).
atomicNumber Atomic number of the element (unitless)
entropy298 Entropy of the element at 298 K and 1 bar in its most stable form. The default is the value ENTROPY298_UNKNOWN, which if used will cause Cantera to throw an error.
elem_type Specifies the type of the element constraint equation. This defaults to CT_ELEM_TYPE_ABSPOS, i.e., an element.
Definition at line 841 of file Phase.cpp.
References Phase::addUniqueElement(), Phase::elementIndex(), Phase::m_elementsFrozen, Phase::m_kk, Phase::m_mm, Phase::m_speciesComp, and Cantera::npos.
Referenced by LatticeSolidPhase::installSlavePhases().
void addUniqueSpecies (const std::string & name, const doublereal * comp, doublereal charge = 0.0, doublereal size = 1.0) inherited
Add a species to the phase, checking for uniqueness of the name This routine checks for uniqueness of the string name.
It only adds the species if it is unique.
Parameters
name String name of the species
comp Array containing the elemental composition of the species.
charge Charge of the species. Defaults to zero.
size Size of the species (meters). Defaults to 1 meter.
Definition at line 919 of file Phase.cpp.
References Phase::m_kk, Phase::m_mm, Phase::m_speciesCharge, Phase::m_speciesComp, Phase::m_speciesNames, and Phase::m_speciesSize.
Referenced by FixedChemPotSSTP::FixedChemPotSSTP(), LatticeSolidPhase::installSlavePhases(), and Cantera::installSpecies().
void freezeSpecies () virtual inherited
Call when finished adding species.
Prepare to use them for calculation of mixture properties.
Definition at line 952 of file Phase.cpp.
References Phase::init(), Phase::m_speciesFrozen, and Phase::molecularWeights().
Referenced by FixedChemPotSSTP::FixedChemPotSSTP(), and Cantera::importPhase().
bool speciesFrozen () inline inherited
True if freezeSpecies has been called.
Definition at line 694 of file Phase.h.
References Phase::m_speciesFrozen.
int stateMFNumber () const inline inherited
Return the State Mole Fraction Number.
Definition at line 701 of file Phase.h.
References Phase::m_stateNum.
Referenced by SimpleTransport::update_C(), and LiquidTransport::update_C().
void stateMFChangeCalc (bool forceChange = false) inline inherited
Every time the mole fractions have changed, this routine will increment the stateMFNumber.
@param forceChange If this is true then the stateMFNumber always
changes. This defaults to false.
Deprecated:
Definition at line 115 of file Phase.cpp.
References Phase::m_stateNum.
Referenced by Phase::setConcentrations(), Phase::setMassFractions(), Phase::setMassFractions_NoNorm(), Phase::setMoleFractions(), and Phase::setMoleFractions_NoNorm().
void init (const vector_fp & mw) protected inherited
Initialize. Make a local copy of the vector of molecular weights, and resize the composition arrays to the appropriate size.
Parameters
mw Vector of molecular weights of the species.
Definition at line 958 of file Phase.cpp.
References Cantera::int2str(), Phase::m_kk, Phase::m_mmw, Phase::m_molwts, Phase::m_rmolwts, Phase::m_y, Phase::m_ym, and Cantera::Tiny.
Referenced by Phase::freezeSpecies().
void setMolecularWeight (const int k, const double mw) inline protected inherited
Set the molecular weight of a single species to a given value.
Parameters
k id of the species
mw Molecular Weight (kg kmol-1)
Definition at line 722 of file Phase.h.
References Phase::m_molwts, and Phase::m_rmolwts.
Referenced by PureFluidPhase::initThermo(), and WaterSSTP::initThermoXML().
Member Data Documentation
size_t numBinaryInteractions_ protected
number of binary interaction expressions
Definition at line 882 of file PhaseCombo_Interaction.h.
Referenced by PhaseCombo_Interaction::getdlnActCoeffds(), PhaseCombo_Interaction::getPartialMolarVolumes(), PhaseCombo_Interaction::operator=(), PhaseCombo_Interaction::PhaseCombo_Interaction(), PhaseCombo_Interaction::readXMLBinarySpecies(), PhaseCombo_Interaction::resizeNumInteractions(), PhaseCombo_Interaction::s_update_dlnActCoeff_dlnN(), PhaseCombo_Interaction::s_update_dlnActCoeff_dlnN_diag(), PhaseCombo_Interaction::s_update_dlnActCoeff_dlnX_diag(), PhaseCombo_Interaction::s_update_dlnActCoeff_dT(), and PhaseCombo_Interaction::s_update_lnActCoeff().
vector_fp m_HE_b_ij mutable protected
Enthalpy term for the binary mole fraction interaction of the excess gibbs free energy expression.
Definition at line 886 of file PhaseCombo_Interaction.h.
Referenced by PhaseCombo_Interaction::getdlnActCoeffds(), PhaseCombo_Interaction::operator=(), PhaseCombo_Interaction::PhaseCombo_Interaction(), PhaseCombo_Interaction::readXMLBinarySpecies(), PhaseCombo_Interaction::resizeNumInteractions(), PhaseCombo_Interaction::s_update_dlnActCoeff_dlnN(), PhaseCombo_Interaction::s_update_dlnActCoeff_dlnN_diag(), PhaseCombo_Interaction::s_update_dlnActCoeff_dlnX_diag(), PhaseCombo_Interaction::s_update_dlnActCoeff_dT(), and PhaseCombo_Interaction::s_update_lnActCoeff().
vector_fp m_HE_c_ij mutable protected
Enthalpy term for the ternary mole fraction interaction of the excess gibbs free energy expression.
Definition at line 890 of file PhaseCombo_Interaction.h.
Referenced by PhaseCombo_Interaction::getdlnActCoeffds(), PhaseCombo_Interaction::operator=(), PhaseCombo_Interaction::PhaseCombo_Interaction(), PhaseCombo_Interaction::readXMLBinarySpecies(), PhaseCombo_Interaction::resizeNumInteractions(), PhaseCombo_Interaction::s_update_dlnActCoeff_dlnN(), PhaseCombo_Interaction::s_update_dlnActCoeff_dlnN_diag(), PhaseCombo_Interaction::s_update_dlnActCoeff_dlnX_diag(), PhaseCombo_Interaction::s_update_dlnActCoeff_dT(), and PhaseCombo_Interaction::s_update_lnActCoeff().
vector_fp m_HE_d_ij mutable protected
Enthalpy term for the quaternary mole fraction interaction of the excess gibbs free energy expression.
Definition at line 894 of file PhaseCombo_Interaction.h.
Referenced by PhaseCombo_Interaction::operator=(), PhaseCombo_Interaction::PhaseCombo_Interaction(), and PhaseCombo_Interaction::resizeNumInteractions().
vector_fp m_SE_b_ij mutable protected
Entropy term for the binary mole fraction interaction of the excess gibbs free energy expression.
Definition at line 898 of file PhaseCombo_Interaction.h.
Referenced by PhaseCombo_Interaction::getdlnActCoeffds(), PhaseCombo_Interaction::operator=(), PhaseCombo_Interaction::PhaseCombo_Interaction(), PhaseCombo_Interaction::readXMLBinarySpecies(), PhaseCombo_Interaction::resizeNumInteractions(), PhaseCombo_Interaction::s_update_dlnActCoeff_dlnN(), PhaseCombo_Interaction::s_update_dlnActCoeff_dlnN_diag(), PhaseCombo_Interaction::s_update_dlnActCoeff_dlnX_diag(), and PhaseCombo_Interaction::s_update_lnActCoeff().
vector_fp m_SE_c_ij mutable protected
Entropy term for the ternary mole fraction interaction of the excess gibbs free energy expression.
Definition at line 902 of file PhaseCombo_Interaction.h.
Referenced by PhaseCombo_Interaction::getdlnActCoeffds(), PhaseCombo_Interaction::operator=(), PhaseCombo_Interaction::PhaseCombo_Interaction(), PhaseCombo_Interaction::readXMLBinarySpecies(), PhaseCombo_Interaction::resizeNumInteractions(), PhaseCombo_Interaction::s_update_dlnActCoeff_dlnN(), PhaseCombo_Interaction::s_update_dlnActCoeff_dlnN_diag(), PhaseCombo_Interaction::s_update_dlnActCoeff_dlnX_diag(), and PhaseCombo_Interaction::s_update_lnActCoeff().
vector_fp m_SE_d_ij mutable protected
Entropy term for the quaternary mole fraction interaction of the excess gibbs free energy expression.
Definition at line 906 of file PhaseCombo_Interaction.h.
Referenced by PhaseCombo_Interaction::operator=(), PhaseCombo_Interaction::PhaseCombo_Interaction(), and PhaseCombo_Interaction::resizeNumInteractions().
vector_fp m_VHE_b_ij mutable protected
Enthalpy term for the binary mole fraction interaction of the excess gibbs free energy expression.
Definition at line 910 of file PhaseCombo_Interaction.h.
Referenced by PhaseCombo_Interaction::getPartialMolarVolumes(), PhaseCombo_Interaction::operator=(), PhaseCombo_Interaction::PhaseCombo_Interaction(), PhaseCombo_Interaction::readXMLBinarySpecies(), and PhaseCombo_Interaction::resizeNumInteractions().
vector_fp m_VHE_c_ij mutable protected
Enthalpy term for the ternary mole fraction interaction of the excess gibbs free energy expression.
Definition at line 914 of file PhaseCombo_Interaction.h.
Referenced by PhaseCombo_Interaction::getPartialMolarVolumes(), PhaseCombo_Interaction::operator=(), PhaseCombo_Interaction::PhaseCombo_Interaction(), PhaseCombo_Interaction::readXMLBinarySpecies(), and PhaseCombo_Interaction::resizeNumInteractions().
vector_fp m_VHE_d_ij mutable protected
Enthalpy term for the quaternary mole fraction interaction of the excess gibbs free energy expression.
Definition at line 918 of file PhaseCombo_Interaction.h.
Referenced by PhaseCombo_Interaction::operator=(), PhaseCombo_Interaction::PhaseCombo_Interaction(), and PhaseCombo_Interaction::resizeNumInteractions().
vector_fp m_VSE_b_ij mutable protected
Entropy term for the binary mole fraction interaction of the excess gibbs free energy expression.
Definition at line 922 of file PhaseCombo_Interaction.h.
Referenced by PhaseCombo_Interaction::getPartialMolarVolumes(), PhaseCombo_Interaction::operator=(), PhaseCombo_Interaction::PhaseCombo_Interaction(), PhaseCombo_Interaction::readXMLBinarySpecies(), and PhaseCombo_Interaction::resizeNumInteractions().
vector_fp m_VSE_c_ij mutable protected
Entropy term for the ternary mole fraction interaction of the excess gibbs free energy expression.
Definition at line 926 of file PhaseCombo_Interaction.h.
Referenced by PhaseCombo_Interaction::getPartialMolarVolumes(), PhaseCombo_Interaction::operator=(), PhaseCombo_Interaction::PhaseCombo_Interaction(), PhaseCombo_Interaction::readXMLBinarySpecies(), and PhaseCombo_Interaction::resizeNumInteractions().
vector_fp m_VSE_d_ij mutable protected
Entropy term for the quaternary mole fraction interaction of the excess gibbs free energy expression.
Definition at line 930 of file PhaseCombo_Interaction.h.
Referenced by PhaseCombo_Interaction::operator=(), PhaseCombo_Interaction::PhaseCombo_Interaction(), and PhaseCombo_Interaction::resizeNumInteractions().
std::vector<size_t> m_pSpecies_A_ij protected
vector of species indices representing species A in the interaction
Each Margules excess Gibbs free energy term involves two species, A and B. This vector identifies species A.
Definition at line 939 of file PhaseCombo_Interaction.h.
Referenced by PhaseCombo_Interaction::getdlnActCoeffds(), PhaseCombo_Interaction::getPartialMolarVolumes(), PhaseCombo_Interaction::operator=(), PhaseCombo_Interaction::PhaseCombo_Interaction(), PhaseCombo_Interaction::readXMLBinarySpecies(), PhaseCombo_Interaction::resizeNumInteractions(), PhaseCombo_Interaction::s_update_dlnActCoeff_dlnN(), PhaseCombo_Interaction::s_update_dlnActCoeff_dlnN_diag(), PhaseCombo_Interaction::s_update_dlnActCoeff_dlnX_diag(), PhaseCombo_Interaction::s_update_dlnActCoeff_dT(), and PhaseCombo_Interaction::s_update_lnActCoeff().
std::vector<size_t> m_pSpecies_B_ij protected
vector of species indices representing species B in the interaction
Each Margules excess Gibbs free energy term involves two species, A and B. This vector identifies species B.
Definition at line 946 of file PhaseCombo_Interaction.h.
Referenced by PhaseCombo_Interaction::getdlnActCoeffds(), PhaseCombo_Interaction::getPartialMolarVolumes(), PhaseCombo_Interaction::operator=(), PhaseCombo_Interaction::PhaseCombo_Interaction(), PhaseCombo_Interaction::readXMLBinarySpecies(), PhaseCombo_Interaction::resizeNumInteractions(), PhaseCombo_Interaction::s_update_dlnActCoeff_dlnN(), PhaseCombo_Interaction::s_update_dlnActCoeff_dlnN_diag(), PhaseCombo_Interaction::s_update_dlnActCoeff_dlnX_diag(), PhaseCombo_Interaction::s_update_dlnActCoeff_dT(), and PhaseCombo_Interaction::s_update_lnActCoeff().
int formMargules_ protected
form of the Margules interaction expression
Currently there is only one form.
Definition at line 952 of file PhaseCombo_Interaction.h.
Referenced by PhaseCombo_Interaction::operator=().
int formTempModel_ protected
form of the temperature dependence of the Margules interaction expression
Currently there is only one form -> constant wrt temperature.
Definition at line 958 of file PhaseCombo_Interaction.h.
Referenced by PhaseCombo_Interaction::operator=().
std::vector<doublereal> moleFractions_ mutable protected inherited
Storage for the current values of the mole fractions of the species.
This vector is kept up-to-date when the setState functions are called. Therefore, it may be considered to be an independent variable.
Note in order to do this, the setState functions are redefined to always keep this vector current.
Definition at line 601 of file GibbsExcessVPSSTP.h.
Referenced by GibbsExcessVPSSTP::calcDensity(), IonsFromNeutralVPSSTP::calcNeutralMoleculeMoleFractions(), PseudoBinaryVPSSTP::calcPseudoBinaryMoleFractions(), MolarityIonicVPSSTP::calcPseudoBinaryMoleFractions(), RedlichKisterVPSSTP::cp_mole(), MargulesVPSSTP::cp_mole(), MixedSolventElectrolyte::cp_mole(), PhaseCombo_Interaction::cp_mole(), RedlichKisterVPSSTP::enthalpy_mole(), MargulesVPSSTP::enthalpy_mole(), MixedSolventElectrolyte::enthalpy_mole(), PhaseCombo_Interaction::enthalpy_mole(), RedlichKisterVPSSTP::entropy_mole(), MargulesVPSSTP::entropy_mole(), MixedSolventElectrolyte::entropy_mole(), PhaseCombo_Interaction::entropy_mole(), GibbsExcessVPSSTP::getActivities(), MolarityIonicVPSSTP::getChemPotentials(), IonsFromNeutralVPSSTP::getChemPotentials(), RedlichKisterVPSSTP::getChemPotentials(), MargulesVPSSTP::getChemPotentials(), MixedSolventElectrolyte::getChemPotentials(), PhaseCombo_Interaction::getChemPotentials(), RedlichKisterVPSSTP::getdlnActCoeffdlnN_diag(), IonsFromNeutralVPSSTP::getdlnActCoeffds(), PhaseCombo_Interaction::getdlnActCoeffds(), MargulesVPSSTP::getdlnActCoeffds(), MixedSolventElectrolyte::getdlnActCoeffds(), IonsFromNeutralVPSSTP::getNeutralMoleculeMoleGrads(), MolarityIonicVPSSTP::getPartialMolarEntropies(), IonsFromNeutralVPSSTP::getPartialMolarEntropies(), RedlichKisterVPSSTP::getPartialMolarEntropies(), MargulesVPSSTP::getPartialMolarEntropies(), MixedSolventElectrolyte::getPartialMolarEntropies(), PhaseCombo_Interaction::getPartialMolarEntropies(), MargulesVPSSTP::getPartialMolarVolumes(), MixedSolventElectrolyte::getPartialMolarVolumes(), PhaseCombo_Interaction::getPartialMolarVolumes(), PseudoBinaryVPSSTP::initLengths(), GibbsExcessVPSSTP::initLengths(), IonsFromNeutralVPSSTP::initLengths(), GibbsExcessVPSSTP::initThermo(), GibbsExcessVPSSTP::operator=(), PhaseCombo_Interaction::s_update_dlnActCoeff_dlnN(), MargulesVPSSTP::s_update_dlnActCoeff_dlnN(), MixedSolventElectrolyte::s_update_dlnActCoeff_dlnN(), PhaseCombo_Interaction::s_update_dlnActCoeff_dlnN_diag(), MargulesVPSSTP::s_update_dlnActCoeff_dlnN_diag(), MixedSolventElectrolyte::s_update_dlnActCoeff_dlnN_diag(), PhaseCombo_Interaction::s_update_dlnActCoeff_dlnX_diag(), MargulesVPSSTP::s_update_dlnActCoeff_dlnX_diag(), MixedSolventElectrolyte::s_update_dlnActCoeff_dlnX_diag(), PhaseCombo_Interaction::s_update_dlnActCoeff_dT(), RedlichKisterVPSSTP::s_update_dlnActCoeff_dT(), MargulesVPSSTP::s_update_dlnActCoeff_dT(), MixedSolventElectrolyte::s_update_dlnActCoeff_dT(), RedlichKisterVPSSTP::s_update_dlnActCoeff_dX_(), PhaseCombo_Interaction::s_update_lnActCoeff(), RedlichKisterVPSSTP::s_update_lnActCoeff(), MargulesVPSSTP::s_update_lnActCoeff(), MixedSolventElectrolyte::s_update_lnActCoeff(), GibbsExcessVPSSTP::setConcentrations(), GibbsExcessVPSSTP::setMassFractions(), GibbsExcessVPSSTP::setMassFractions_NoNorm(), GibbsExcessVPSSTP::setMoleFractions(), and GibbsExcessVPSSTP::setMoleFractions_NoNorm().
std::vector<doublereal> lnActCoeff_Scaled_ mutable protected inherited
Storage for the current values of the activity coefficients of the species.
Definition at line 605 of file GibbsExcessVPSSTP.h.
Referenced by IonsFromNeutralVPSSTP::getActivityCoefficients(), MixedSolventElectrolyte::getActivityCoefficients(), PhaseCombo_Interaction::getActivityCoefficients(), MolarityIonicVPSSTP::getChemPotentials(), RedlichKisterVPSSTP::getChemPotentials(), MargulesVPSSTP::getChemPotentials(), MixedSolventElectrolyte::getChemPotentials(), PhaseCombo_Interaction::getChemPotentials(), MolarityIonicVPSSTP::getLnActivityCoefficients(), RedlichKisterVPSSTP::getLnActivityCoefficients(), MargulesVPSSTP::getLnActivityCoefficients(), MolarityIonicVPSSTP::getPartialMolarEntropies(), IonsFromNeutralVPSSTP::getPartialMolarEntropies(), RedlichKisterVPSSTP::getPartialMolarEntropies(), MargulesVPSSTP::getPartialMolarEntropies(), MixedSolventElectrolyte::getPartialMolarEntropies(), PhaseCombo_Interaction::getPartialMolarEntropies(), GibbsExcessVPSSTP::initLengths(), GibbsExcessVPSSTP::operator=(), MolarityIonicVPSSTP::s_update_lnActCoeff(), IonsFromNeutralVPSSTP::s_update_lnActCoeff(), PhaseCombo_Interaction::s_update_lnActCoeff(), RedlichKisterVPSSTP::s_update_lnActCoeff(), MargulesVPSSTP::s_update_lnActCoeff(), and MixedSolventElectrolyte::s_update_lnActCoeff().
std::vector<doublereal> dlnActCoeffdT_Scaled_ mutable protected inherited
Storage for the current derivative values of the gradients with respect to temperature of the log of the activity coefficients of the species.
Definition at line 610 of file GibbsExcessVPSSTP.h.
Referenced by PhaseCombo_Interaction::getdlnActCoeffds(), RedlichKisterVPSSTP::getdlnActCoeffds(), MargulesVPSSTP::getdlnActCoeffds(), MixedSolventElectrolyte::getdlnActCoeffds(), RedlichKisterVPSSTP::getdlnActCoeffdT(), MargulesVPSSTP::getdlnActCoeffdT(), MixedSolventElectrolyte::getdlnActCoeffdT(), PhaseCombo_Interaction::getdlnActCoeffdT(), MolarityIonicVPSSTP::getPartialMolarCp(), RedlichKisterVPSSTP::getPartialMolarCp(), MargulesVPSSTP::getPartialMolarCp(), MixedSolventElectrolyte::getPartialMolarCp(), PhaseCombo_Interaction::getPartialMolarCp(), MolarityIonicVPSSTP::getPartialMolarEnthalpies(), IonsFromNeutralVPSSTP::getPartialMolarEnthalpies(), RedlichKisterVPSSTP::getPartialMolarEnthalpies(), MargulesVPSSTP::getPartialMolarEnthalpies(), MixedSolventElectrolyte::getPartialMolarEnthalpies(), PhaseCombo_Interaction::getPartialMolarEnthalpies(), MolarityIonicVPSSTP::getPartialMolarEntropies(), IonsFromNeutralVPSSTP::getPartialMolarEntropies(), RedlichKisterVPSSTP::getPartialMolarEntropies(), MargulesVPSSTP::getPartialMolarEntropies(), MixedSolventElectrolyte::getPartialMolarEntropies(), PhaseCombo_Interaction::getPartialMolarEntropies(), GibbsExcessVPSSTP::initLengths(), GibbsExcessVPSSTP::operator=(), PhaseCombo_Interaction::s_update_dlnActCoeff_dT(), RedlichKisterVPSSTP::s_update_dlnActCoeff_dT(), MargulesVPSSTP::s_update_dlnActCoeff_dT(), MixedSolventElectrolyte::s_update_dlnActCoeff_dT(), and IonsFromNeutralVPSSTP::s_update_dlnActCoeffdT().
std::vector<doublereal> d2lnActCoeffdT2_Scaled_ mutable protected inherited
Storage for the current derivative values of the gradients with respect to temperature of the log of the activity coefficients of the species.
Definition at line 615 of file GibbsExcessVPSSTP.h.
Referenced by RedlichKisterVPSSTP::getd2lnActCoeffdT2(), MargulesVPSSTP::getd2lnActCoeffdT2(), MixedSolventElectrolyte::getd2lnActCoeffdT2(), PhaseCombo_Interaction::getd2lnActCoeffdT2(), MolarityIonicVPSSTP::getPartialMolarCp(), RedlichKisterVPSSTP::getPartialMolarCp(), MargulesVPSSTP::getPartialMolarCp(), MixedSolventElectrolyte::getPartialMolarCp(), PhaseCombo_Interaction::getPartialMolarCp(), GibbsExcessVPSSTP::initLengths(), GibbsExcessVPSSTP::operator=(), PhaseCombo_Interaction::s_update_dlnActCoeff_dT(), RedlichKisterVPSSTP::s_update_dlnActCoeff_dT(), MargulesVPSSTP::s_update_dlnActCoeff_dT(), and MixedSolventElectrolyte::s_update_dlnActCoeff_dT().
std::vector<doublereal> dlnActCoeffdlnN_diag_ mutable protected inherited
Storage for the current derivative values of the gradients with respect to logarithm of the mole fraction of the log of the activity coefficients of the species.
Deprecated:
Definition at line 620 of file GibbsExcessVPSSTP.h.
Referenced by IonsFromNeutralVPSSTP::getdlnActCoeffdlnN_diag(), PhaseCombo_Interaction::getdlnActCoeffdlnN_diag(), MargulesVPSSTP::getdlnActCoeffdlnN_diag(), MixedSolventElectrolyte::getdlnActCoeffdlnN_diag(), GibbsExcessVPSSTP::initLengths(), GibbsExcessVPSSTP::operator=(), IonsFromNeutralVPSSTP::s_update_dlnActCoeff_dlnN(), IonsFromNeutralVPSSTP::s_update_dlnActCoeff_dlnN_diag(), PhaseCombo_Interaction::s_update_dlnActCoeff_dlnN_diag(), MargulesVPSSTP::s_update_dlnActCoeff_dlnN_diag(), and MixedSolventElectrolyte::s_update_dlnActCoeff_dlnN_diag().
std::vector<doublereal> dlnActCoeffdlnX_diag_ mutable protected inherited
Storage for the current derivative values of the gradients with respect to logarithm of the mole fraction of the log of the activity coefficients of the species.
Deprecated:
Definition at line 625 of file GibbsExcessVPSSTP.h.
Referenced by IonsFromNeutralVPSSTP::getdlnActCoeffdlnX_diag(), PhaseCombo_Interaction::getdlnActCoeffdlnX_diag(), RedlichKisterVPSSTP::getdlnActCoeffdlnX_diag(), MargulesVPSSTP::getdlnActCoeffdlnX_diag(), MixedSolventElectrolyte::getdlnActCoeffdlnX_diag(), GibbsExcessVPSSTP::initLengths(), GibbsExcessVPSSTP::operator=(), IonsFromNeutralVPSSTP::s_update_dlnActCoeff_dlnX_diag(), PhaseCombo_Interaction::s_update_dlnActCoeff_dlnX_diag(), MargulesVPSSTP::s_update_dlnActCoeff_dlnX_diag(), and MixedSolventElectrolyte::s_update_dlnActCoeff_dlnX_diag().
Array2D dlnActCoeffdlnN_ mutable protected inherited
Storage for the current derivative values of the gradients with respect to logarithm of the species mole number of the log of the activity coefficients of the species.
dlnActCoeffdlnN_(k, m) is the derivative of ln(gamma_k) wrt ln mole number of species m
Definition at line 632 of file GibbsExcessVPSSTP.h.
Referenced by IonsFromNeutralVPSSTP::getdlnActCoeffdlnN(), PhaseCombo_Interaction::getdlnActCoeffdlnN(), RedlichKisterVPSSTP::getdlnActCoeffdlnN(), MargulesVPSSTP::getdlnActCoeffdlnN(), MixedSolventElectrolyte::getdlnActCoeffdlnN(), GibbsExcessVPSSTP::initLengths(), PhaseCombo_Interaction::initLengths(), RedlichKisterVPSSTP::initLengths(), MargulesVPSSTP::initLengths(), MixedSolventElectrolyte::initLengths(), GibbsExcessVPSSTP::operator=(), IonsFromNeutralVPSSTP::s_update_dlnActCoeff_dlnN(), PhaseCombo_Interaction::s_update_dlnActCoeff_dlnN(), MargulesVPSSTP::s_update_dlnActCoeff_dlnN(), and MixedSolventElectrolyte::s_update_dlnActCoeff_dlnN().
std::vector<doublereal> m_pp mutable protected inherited
Temporary storage space that is fair game.
Definition at line 635 of file GibbsExcessVPSSTP.h.
Referenced by IonsFromNeutralVPSSTP::cp_mole(), IonsFromNeutralVPSSTP::cv_mole(), IonsFromNeutralVPSSTP::enthalpy_mole(), IonsFromNeutralVPSSTP::entropy_mole(), IonsFromNeutralVPSSTP::gibbs_mole(), GibbsExcessVPSSTP::initLengths(), and GibbsExcessVPSSTP::operator=().
doublereal m_Pcurrent protected inherited
Current value of the pressure - state variable.
Because we are now using the pressure as a state variable, we need to carry it along within this object
units = Pascals
Definition at line 606 of file VPStandardStateTP.h.
Referenced by VPStandardStateTP::_updateStandardStateThermo(), IdealSolnGasVPSS::calcDensity(), IdealSolnGasVPSS::isothermalCompressibility(), VPStandardStateTP::operator=(), VPStandardStateTP::pressure(), DebyeHuckel::pressure(), HMWSoln::pressure(), IdealSolnGasVPSS::setPressure(), VPStandardStateTP::setState_TP(), IdealMolalSoln::setState_TP(), GibbsExcessVPSSTP::setState_TP(), DebyeHuckel::setState_TP(), HMWSoln::setState_TP(), VPStandardStateTP::setTemperature(), DebyeHuckel::setTemperature(), HMWSoln::setTemperature(), and VPStandardStateTP::updateStandardStateThermo().
doublereal m_Tlast_ss mutable protected inherited
The last temperature at which the standard statethermodynamic properties were calculated at.
Definition at line 609 of file VPStandardStateTP.h.
Referenced by VPStandardStateTP::_updateStandardStateThermo(), VPStandardStateTP::operator=(), and VPStandardStateTP::updateStandardStateThermo().
doublereal m_Plast_ss mutable protected inherited
The last pressure at which the Standard State thermodynamic properties were calculated at.
Definition at line 613 of file VPStandardStateTP.h.
Referenced by VPStandardStateTP::_updateStandardStateThermo(), VPStandardStateTP::operator=(), and VPStandardStateTP::updateStandardStateThermo().
doublereal m_P0 protected inherited
Reference pressure (Pa) must be the same for all species
defaults to OneAtm
Definition at line 619 of file VPStandardStateTP.h.
Referenced by VPStandardStateTP::operator=().
VPSSMgr* m_VPSS_ptr mutable protected inherited
Pointer to the VPSS manager that calculates all of the standard state info efficiently.
Definition at line 626 of file VPStandardStateTP.h.
Referenced by VPStandardStateTP::_updateStandardStateThermo(), IdealSolnGasVPSS::calcDensity(), IdealSolnGasVPSS::cp_mole(), IdealSolnGasVPSS::enthalpy_mole(), IdealSolnGasVPSS::entropy_mole(), IdealSolnGasVPSS::getActivityConcentrations(), VPStandardStateTP::getCp_R(), VPStandardStateTP::getCp_R_ref(), VPStandardStateTP::getEnthalpy_RT(), VPStandardStateTP::getEnthalpy_RT_ref(), VPStandardStateTP::getEntropy_R(), VPStandardStateTP::getEntropy_R_ref(), VPStandardStateTP::getGibbs_ref(), VPStandardStateTP::getGibbs_RT(), VPStandardStateTP::getGibbs_RT_ref(), VPStandardStateTP::getIntEnergy_RT(), VPStandardStateTP::getPureGibbs(), VPStandardStateTP::getStandardVolumes(), VPStandardStateTP::getStandardVolumes_ref(), VPStandardStateTP::initThermo(), VPStandardStateTP::initThermoXML(), VPStandardStateTP::operator=(), VPStandardStateTP::provideVPSSMgr(), IdealSolnGasVPSS::setToEquilState(), VPStandardStateTP::setVPSSMgr(), IdealSolnGasVPSS::standardConcentration(), and VPStandardStateTP::~VPStandardStateTP().
std::vector<PDSS*> m_PDSS_storage protected inherited
Storage for the PDSS objects for the species.
Storage is in species index order. VPStandardStateTp owns each of the objects. Copy operations are deep.
Definition at line 634 of file VPStandardStateTP.h.
Referenced by VPStandardStateTP::initThermo(), VPStandardStateTP::initThermoXML(), VPStandardStateTP::operator=(), and VPStandardStateTP::~VPStandardStateTP().
SpeciesThermo* m_spthermo protected inherited
Pointer to the calculation manager for species reference-state thermodynamic properties.
This class is called when the reference-state thermodynamic properties of all the species in the phase needs to be evaluated.
Definition at line 1611 of file ThermoPhase.h.
Referenced by MixtureFugacityTP::_updateReferenceStateThermo(), ConstDensityThermo::_updateThermo(), SurfPhase::_updateThermo(), SingleSpeciesTP::_updateThermo(), IdealGasPhase::_updateThermo(), LatticePhase::_updateThermo(), IdealSolidSolnPhase::_updateThermo(), ConstDensityThermo::enthalpy_mole(), LatticePhase::enthalpy_mole(), RedlichKwongMFTP::entropy_mole(), IdealGasPhase::entropy_mole(), FixedChemPotSSTP::FixedChemPotSSTP(), ConstDensityThermo::getChemPotentials(), MixtureFugacityTP::getEntropy_R(), IdealGasPhase::getEntropy_R(), PureFluidPhase::getEntropy_R_ref(), MixtureFugacityTP::getGibbs_RT(), IdealGasPhase::getGibbs_RT(), PureFluidPhase::getGibbs_RT_ref(), IdealGasPhase::getPartialMolarEntropies(), MixtureFugacityTP::getPureGibbs(), IdealGasPhase::getPureGibbs(), MixtureFugacityTP::getStandardChemPotentials(), IdealGasPhase::getStandardChemPotentials(), IdealSolidSolnPhase::initLengths(), ConstDensityThermo::initThermo(), StoichSubstance::initThermo(), StoichSubstanceSSTP::initThermo(), PureFluidPhase::initThermo(), SingleSpeciesTP::initThermo(), IdealGasPhase::initThermo(), LatticePhase::initThermo(), WaterSSTP::initThermoXML(), LatticeSolidPhase::installSlavePhases(), ConstDensityThermo::intEnergy_mole(), LatticePhase::intEnergy_mole(), ThermoPhase::maxTemp(), ThermoPhase::minTemp(), VPStandardStateTP::operator=(), ThermoPhase::operator=(), ThermoPhase::refPressure(), ThermoPhase::setSpeciesThermo(), LatticeSolidPhase::speciesThermo(), ThermoPhase::speciesThermo(), and ThermoPhase::~ThermoPhase().
std::vector<const XML_Node*> m_speciesData protected inherited
Vector of pointers to the species databases.
This is used to access data needed to construct the transport manager and other properties later in the initialization process. We create a copy of the XML_Node data read in here. Therefore, we own this data.
Definition at line 1621 of file ThermoPhase.h.
Referenced by LatticeSolidPhase::installSlavePhases(), ThermoPhase::operator=(), ThermoPhase::saveSpeciesData(), ThermoPhase::speciesData(), and ThermoPhase::~ThermoPhase().
doublereal m_phi protected inherited
Stored value of the electric potential for this phase.
Units are Volts
Definition at line 1627 of file ThermoPhase.h.
Referenced by ThermoPhase::electricPotential(), IdealMolalSoln::electricPotential(), ThermoPhase::operator=(), and ThermoPhase::setElectricPotential().
vector_fp m_lambdaRRT protected inherited
Vector of element potentials.
-> length equal to number of elements
Definition at line 1631 of file ThermoPhase.h.
Referenced by ThermoPhase::getElementPotentials(), ThermoPhase::operator=(), and ThermoPhase::setElementPotentials().
bool m_hasElementPotentials protected inherited
Boolean indicating whether there is a valid set of saved element potentials for this phase.
Definition at line 1635 of file ThermoPhase.h.
Referenced by ThermoPhase::getElementPotentials(), ThermoPhase::operator=(), and ThermoPhase::setElementPotentials().
bool m_chargeNeutralityNecessary protected inherited
Boolean indicating whether a charge neutrality condition is a necessity.
Note, the charge neutrality condition is not a necessity for ideal gas phases. There may be a net charge in those phases, because the NASA polynomials for ionized species in Ideal gases take this condition into account. However, liquid phases usually require charge neutrality in order for their derived thermodynamics to be valid.
Definition at line 1645 of file ThermoPhase.h.
Referenced by ThermoPhase::chargeNeutralityNecessary(), MolalityVPSSTP::MolalityVPSSTP(), and ThermoPhase::operator=().
int m_ssConvention protected inherited
Contains the standard state convention.
Definition at line 1648 of file ThermoPhase.h.
Referenced by ThermoPhase::operator=(), and ThermoPhase::standardStateConvention().
std::vector<doublereal> xMol_Ref protected inherited
Reference Mole Fraction Composition.
Occasionally, the need arises to find a safe mole fraction vector to initialize the object to. This contains such a vector. The algorithm will pick up the mole fraction vector that is applied from the state xml file in the input file
Definition at line 1657 of file ThermoPhase.h.
Referenced by ThermoPhase::getReferenceComposition(), ThermoPhase::initThermo(), and ThermoPhase::setReferenceComposition().
size_t m_kk protected inherited
Number of species in the phase.
Definition at line 727 of file Phase.h.
Referenced by DebyeHuckel::_lnactivityWaterHelgesonFixedForm(), MixtureFugacityTP::_updateReferenceStateThermo(), ConstDensityThermo::_updateThermo(), SurfPhase::_updateThermo(), IdealGasPhase::_updateThermo(), LatticePhase::_updateThermo(), IdealSolidSolnPhase::_updateThermo(), Phase::addUniqueElementAfterFreeze(), Phase::addUniqueSpecies(), HMWSoln::applyphScale(), RedlichKwongMFTP::applyStandardMixingRules(), GibbsExcessVPSSTP::calcDensity(), IdealMolalSoln::calcDensity(), DebyeHuckel::calcDensity(), HMWSoln::calcDensity(), IonsFromNeutralVPSSTP::calcIonMoleFractions(), MolalityVPSSTP::calcMolalities(), HMWSoln::calcMolalitiesCropped(), IonsFromNeutralVPSSTP::calcNeutralMoleculeMoleFractions(), PseudoBinaryVPSSTP::calcPseudoBinaryMoleFractions(), MolarityIonicVPSSTP::calcPseudoBinaryMoleFractions(), RedlichKwongMFTP::calculateAB(), GibbsExcessVPSSTP::checkMFSum(), Phase::checkSpeciesArraySize(), Phase::checkSpeciesIndex(), HMWSoln::counterIJ_setup(), RedlichKwongMFTP::critDensity(), RedlichKwongMFTP::critPressure(), RedlichKwongMFTP::critTemperature(), ConstDensityThermo::expGibbs_RT(), IdealGasPhase::expGibbs_RT_ref(), IdealSolidSolnPhase::expGibbs_RT_ref(), MolalityVPSSTP::findCLMIndex(), GibbsExcessVPSSTP::getActivities(), IdealMolalSoln::getActivities(), DebyeHuckel::getActivities(), HMWSoln::getActivities(), ConstDensityThermo::getActivityCoefficients(), SingleSpeciesTP::getActivityCoefficients(), IdealSolnGasVPSS::getActivityCoefficients(), IonsFromNeutralVPSSTP::getActivityCoefficients(), GibbsExcessVPSSTP::getActivityCoefficients(), RedlichKwongMFTP::getActivityCoefficients(), LatticeSolidPhase::getActivityCoefficients(), MixedSolventElectrolyte::getActivityCoefficients(), PhaseCombo_Interaction::getActivityCoefficients(), IdealSolidSolnPhase::getActivityCoefficients(), ThermoPhase::getActivityCoefficients(), MolalityVPSSTP::getActivityCoefficients(), IdealGasPhase::getActivityCoefficients(), LatticePhase::getActivityCoefficients(), IdealSolnGasVPSS::getActivityConcentrations(), RedlichKwongMFTP::getActivityConcentrations(), IdealMolalSoln::getActivityConcentrations(), IdealSolidSolnPhase::getActivityConcentrations(), DebyeHuckel::getActivityConcentrations(), HMWSoln::getActivityConcentrations(), ConstDensityThermo::getChemPotentials(), SurfPhase::getChemPotentials(), MolarityIonicVPSSTP::getChemPotentials(), IdealSolnGasVPSS::getChemPotentials(), RedlichKwongMFTP::getChemPotentials(), RedlichKisterVPSSTP::getChemPotentials(), MargulesVPSSTP::getChemPotentials(), MixedSolventElectrolyte::getChemPotentials(), PhaseCombo_Interaction::getChemPotentials(), IdealSolidSolnPhase::getChemPotentials(), IdealMolalSoln::getChemPotentials(), IdealGasPhase::getChemPotentials(), LatticePhase::getChemPotentials(), DebyeHuckel::getChemPotentials(), HMWSoln::getChemPotentials(), VPStandardStateTP::getChemPotentials_RT(), MixtureFugacityTP::getChemPotentials_RT(), IdealSolnGasVPSS::getChemPotentials_RT(), RedlichKwongMFTP::getChemPotentials_RT(), IdealSolidSolnPhase::getChemPotentials_RT(), SurfPhase::getCoverages(), IdealSolidSolnPhase::getCp_R_ref(), RedlichKisterVPSSTP::getd2lnActCoeffdT2(), MargulesVPSSTP::getd2lnActCoeffdT2(), MixedSolventElectrolyte::getd2lnActCoeffdT2(), PhaseCombo_Interaction::getd2lnActCoeffdT2(), IonsFromNeutralVPSSTP::getdlnActCoeffdlnN(), PhaseCombo_Interaction::getdlnActCoeffdlnN(), RedlichKisterVPSSTP::getdlnActCoeffdlnN(), MargulesVPSSTP::getdlnActCoeffdlnN(), MixedSolventElectrolyte::getdlnActCoeffdlnN(), ThermoPhase::getdlnActCoeffdlnN(), IonsFromNeutralVPSSTP::getdlnActCoeffdlnN_diag(), PhaseCombo_Interaction::getdlnActCoeffdlnN_diag(), RedlichKisterVPSSTP::getdlnActCoeffdlnN_diag(), MargulesVPSSTP::getdlnActCoeffdlnN_diag(), MixedSolventElectrolyte::getdlnActCoeffdlnN_diag(), IonsFromNeutralVPSSTP::getdlnActCoeffdlnX_diag(), PhaseCombo_Interaction::getdlnActCoeffdlnX_diag(), RedlichKisterVPSSTP::getdlnActCoeffdlnX_diag(), MargulesVPSSTP::getdlnActCoeffdlnX_diag(), MixedSolventElectrolyte::getdlnActCoeffdlnX_diag(), IonsFromNeutralVPSSTP::getdlnActCoeffds(), PhaseCombo_Interaction::getdlnActCoeffds(), RedlichKisterVPSSTP::getdlnActCoeffds(), MargulesVPSSTP::getdlnActCoeffds(), MixedSolventElectrolyte::getdlnActCoeffds(), RedlichKisterVPSSTP::getdlnActCoeffdT(), MargulesVPSSTP::getdlnActCoeffdT(), MixedSolventElectrolyte::getdlnActCoeffdT(), PhaseCombo_Interaction::getdlnActCoeffdT(), PureFluidPhase::getElectrochemPotentials(), PseudoBinaryVPSSTP::getElectrochemPotentials(), MolarityIonicVPSSTP::getElectrochemPotentials(), GibbsExcessVPSSTP::getElectrochemPotentials(), RedlichKisterVPSSTP::getElectrochemPotentials(), MargulesVPSSTP::getElectrochemPotentials(), ThermoPhase::getElectrochemPotentials(), MixedSolventElectrolyte::getElectrochemPotentials(), MolalityVPSSTP::getElectrochemPotentials(), PhaseCombo_Interaction::getElectrochemPotentials(), IdealSolidSolnPhase::getEnthalpy_RT(), LatticePhase::getEnthalpy_RT(), IdealSolidSolnPhase::getEnthalpy_RT_ref(), MixtureFugacityTP::getEntropy_R(), IdealGasPhase::getEntropy_R(), IdealSolidSolnPhase::getEntropy_R_ref(), WaterSSTP::getGibbs_ref(), LatticeSolidPhase::getGibbs_ref(), IdealSolidSolnPhase::getGibbs_ref(), LatticePhase::getGibbs_ref(), MixtureFugacityTP::getGibbs_RT(), IdealGasPhase::getGibbs_RT(), IdealSolidSolnPhase::getGibbs_RT(), LatticePhase::getGibbs_RT(), IdealSolidSolnPhase::getGibbs_RT_ref(), LatticePhase::getGibbs_RT_ref(), MixtureFugacityTP::getIntEnergy_RT(), IdealGasPhase::getIntEnergy_RT(), IdealSolidSolnPhase::getIntEnergy_RT(), IdealGasPhase::getIntEnergy_RT_ref(), IdealSolidSolnPhase::getIntEnergy_RT_ref(), MolarityIonicVPSSTP::getLnActivityCoefficients(), RedlichKisterVPSSTP::getLnActivityCoefficients(), MargulesVPSSTP::getLnActivityCoefficients(), ThermoPhase::getLnActivityCoefficients(), MolalityVPSSTP::getMolalities(), IdealMolalSoln::getMolalityActivityCoefficients(), DebyeHuckel::getMolalityActivityCoefficients(), IonsFromNeutralVPSSTP::getNeutralMoleculeMoleGrads(), SurfPhase::getPartialMolarCp(), IdealSolnGasVPSS::getPartialMolarCp(), MolarityIonicVPSSTP::getPartialMolarCp(), RedlichKwongMFTP::getPartialMolarCp(), RedlichKisterVPSSTP::getPartialMolarCp(), MargulesVPSSTP::getPartialMolarCp(), MixedSolventElectrolyte::getPartialMolarCp(), PhaseCombo_Interaction::getPartialMolarCp(), IdealSolidSolnPhase::getPartialMolarCp(), IdealMolalSoln::getPartialMolarCp(), LatticePhase::getPartialMolarCp(), DebyeHuckel::getPartialMolarCp(), HMWSoln::getPartialMolarCp(), SurfPhase::getPartialMolarEnthalpies(), IdealSolnGasVPSS::getPartialMolarEnthalpies(), MolarityIonicVPSSTP::getPartialMolarEnthalpies(), IonsFromNeutralVPSSTP::getPartialMolarEnthalpies(), RedlichKwongMFTP::getPartialMolarEnthalpies(), RedlichKisterVPSSTP::getPartialMolarEnthalpies(), MargulesVPSSTP::getPartialMolarEnthalpies(), MixedSolventElectrolyte::getPartialMolarEnthalpies(), PhaseCombo_Interaction::getPartialMolarEnthalpies(), IdealMolalSoln::getPartialMolarEnthalpies(), DebyeHuckel::getPartialMolarEnthalpies(), HMWSoln::getPartialMolarEnthalpies(), SurfPhase::getPartialMolarEntropies(), IdealSolnGasVPSS::getPartialMolarEntropies(), MolarityIonicVPSSTP::getPartialMolarEntropies(), IonsFromNeutralVPSSTP::getPartialMolarEntropies(), RedlichKwongMFTP::getPartialMolarEntropies(), RedlichKisterVPSSTP::getPartialMolarEntropies(), MargulesVPSSTP::getPartialMolarEntropies(), MixedSolventElectrolyte::getPartialMolarEntropies(), PhaseCombo_Interaction::getPartialMolarEntropies(), IdealGasPhase::getPartialMolarEntropies(), IdealMolalSoln::getPartialMolarEntropies(), IdealSolidSolnPhase::getPartialMolarEntropies(), LatticePhase::getPartialMolarEntropies(), DebyeHuckel::getPartialMolarEntropies(), HMWSoln::getPartialMolarEntropies(), IdealSolnGasVPSS::getPartialMolarIntEnergies(), RedlichKwongMFTP::getPartialMolarIntEnergies(), IdealGasPhase::getPartialMolarIntEnergies(), MolarityIonicVPSSTP::getPartialMolarVolumes(), RedlichKwongMFTP::getPartialMolarVolumes(), RedlichKisterVPSSTP::getPartialMolarVolumes(), MargulesVPSSTP::getPartialMolarVolumes(), MixedSolventElectrolyte::getPartialMolarVolumes(), IdealGasPhase::getPartialMolarVolumes(), PhaseCombo_Interaction::getPartialMolarVolumes(), DebyeHuckel::getPartialMolarVolumes(), HMWSoln::getPartialMolarVolumes(), MixtureFugacityTP::getPureGibbs(), IdealGasPhase::getPureGibbs(), LatticePhase::getPureGibbs(), IdealSolidSolnPhase::getPureGibbs(), ThermoPhase::getReferenceComposition(), VPStandardStateTP::getStandardChemPotentials(), MixtureFugacityTP::getStandardChemPotentials(), IdealGasPhase::getStandardChemPotentials(), MixtureFugacityTP::getStandardVolumes(), SurfPhase::getStandardVolumes(), IdealGasPhase::getStandardVolumes(), MixtureFugacityTP::getStandardVolumes_ref(), IdealGasPhase::getStandardVolumes_ref(), HMWSoln::getUnscaledMolalityActivityCoefficients(), HMWSoln::HMWSoln(), Phase::init(), PseudoBinaryVPSSTP::initLengths(), IdealSolnGasVPSS::initLengths(), MolarityIonicVPSSTP::initLengths(), GibbsExcessVPSSTP::initLengths(), RedlichKwongMFTP::initLengths(), VPStandardStateTP::initLengths(), LatticeSolidPhase::initLengths(), IonsFromNeutralVPSSTP::initLengths(), MixtureFugacityTP::initLengths(), PhaseCombo_Interaction::initLengths(), RedlichKisterVPSSTP::initLengths(), MargulesVPSSTP::initLengths(), MixedSolventElectrolyte::initLengths(), MolalityVPSSTP::initLengths(), IdealMolalSoln::initLengths(), IdealSolidSolnPhase::initLengths(), DebyeHuckel::initLengths(), HMWSoln::initLengths(), ConstDensityThermo::initThermo(), SurfPhase::initThermo(), MolarityIonicVPSSTP::initThermo(), StoichSubstanceSSTP::initThermo(), VPStandardStateTP::initThermo(), LatticeSolidPhase::initThermo(), SingleSpeciesTP::initThermo(), IdealGasPhase::initThermo(), LatticePhase::initThermo(), ThermoPhase::initThermo(), RedlichKwongMFTP::initThermoXML(), VPStandardStateTP::initThermoXML(), IonsFromNeutralVPSSTP::initThermoXML(), IdealMolalSoln::initThermoXML(), LatticePhase::initThermoXML(), IdealSolidSolnPhase::initThermoXML(), DebyeHuckel::initThermoXML(), IdealSolidSolnPhase::logStandardConc(), Phase::nSpecies(), VPStandardStateTP::operator=(), Phase::operator=(), ThermoPhase::operator=(), MolalityVPSSTP::osmoticCoefficient(), HMWSoln::printCoeffs(), RedlichKwongMFTP::readXMLCrossFluid(), RedlichKwongMFTP::readXMLPureFluid(), IdealSolidSolnPhase::referenceConcentration(), HMWSoln::relative_enthalpy(), HMWSoln::relative_molal_enthalpy(), DebyeHuckel::s_update_d2lnMolalityActCoeff_dT2(), HMWSoln::s_update_d2lnMolalityActCoeff_dT2(), IonsFromNeutralVPSSTP::s_update_dlnActCoeff_dlnN(), PhaseCombo_Interaction::s_update_dlnActCoeff_dlnN(), MargulesVPSSTP::s_update_dlnActCoeff_dlnN(), MixedSolventElectrolyte::s_update_dlnActCoeff_dlnN(), IonsFromNeutralVPSSTP::s_update_dlnActCoeff_dlnN_diag(), PhaseCombo_Interaction::s_update_dlnActCoeff_dlnN_diag(), MargulesVPSSTP::s_update_dlnActCoeff_dlnN_diag(), MixedSolventElectrolyte::s_update_dlnActCoeff_dlnN_diag(), IonsFromNeutralVPSSTP::s_update_dlnActCoeff_dlnX_diag(), PhaseCombo_Interaction::s_update_dlnActCoeff_dlnX_diag(), MargulesVPSSTP::s_update_dlnActCoeff_dlnX_diag(), MixedSolventElectrolyte::s_update_dlnActCoeff_dlnX_diag(), PhaseCombo_Interaction::s_update_dlnActCoeff_dT(), RedlichKisterVPSSTP::s_update_dlnActCoeff_dT(), MargulesVPSSTP::s_update_dlnActCoeff_dT(), MixedSolventElectrolyte::s_update_dlnActCoeff_dT(), RedlichKisterVPSSTP::s_update_dlnActCoeff_dX_(), IonsFromNeutralVPSSTP::s_update_dlnActCoeffdT(), DebyeHuckel::s_update_dlnMolalityActCoeff_dP(), HMWSoln::s_update_dlnMolalityActCoeff_dP(), DebyeHuckel::s_update_dlnMolalityActCoeff_dT(), HMWSoln::s_update_dlnMolalityActCoeff_dT(), MolarityIonicVPSSTP::s_update_lnActCoeff(), IonsFromNeutralVPSSTP::s_update_lnActCoeff(), PhaseCombo_Interaction::s_update_lnActCoeff(), RedlichKisterVPSSTP::s_update_lnActCoeff(), MargulesVPSSTP::s_update_lnActCoeff(), MixedSolventElectrolyte::s_update_lnActCoeff(), DebyeHuckel::s_update_lnMolalityActCoeff(), HMWSoln::s_update_lnMolalityActCoeff(), IdealMolalSoln::s_updateIMS_lnMolalityActCoeff(), HMWSoln::s_updateIMS_lnMolalityActCoeff(), HMWSoln::s_updatePitzer_CoeffWRTemp(), HMWSoln::s_updatePitzer_d2lnMolalityActCoeff_dT2(), HMWSoln::s_updatePitzer_dlnMolalityActCoeff_dP(), HMWSoln::s_updatePitzer_dlnMolalityActCoeff_dT(), HMWSoln::s_updatePitzer_lnMolalityActCoeff(), HMWSoln::s_updateScaling_pHScaling(), HMWSoln::s_updateScaling_pHScaling_dP(), HMWSoln::s_updateScaling_pHScaling_dT(), HMWSoln::s_updateScaling_pHScaling_dT2(), Phase::setConcentrations(), SurfPhase::setCoverages(), SurfPhase::setCoveragesNoNorm(), Phase::setMassFractions(), Phase::setMassFractions_NoNorm(), MolalityVPSSTP::setMolalities(), Phase::setMoleFractions(), Phase::setMoleFractions_NoNorm(), ThermoPhase::setReferenceComposition(), MolalityVPSSTP::setSolvent(), IdealSolnGasVPSS::setToEquilState(), RedlichKwongMFTP::setToEquilState(), IdealGasPhase::setToEquilState(), IdealSolidSolnPhase::setToEquilState(), ThermoPhase::speciesData(), Phase::speciesIndex(), IdealSolidSolnPhase::standardConcentration(), RedlichKwongMFTP::updateAB(), and ThermoPhase::~ThermoPhase().
size_t m_ndim protected inherited
Dimensionality of the phase.
Volumetric phases have dimensionality 3 and surface phases have dimensionality 2.
Definition at line 731 of file Phase.h.
Referenced by Phase::nDim(), Phase::operator=(), and Phase::setNDim().
vector_fp m_speciesComp protected inherited
Atomic composition of the species.
The number of atoms of element i in species k is equal to m_speciesComp[k * m_mm + i] The length of this vector is equal to m_kk * m_mm
Definition at line 736 of file Phase.h.
Referenced by Phase::addUniqueElementAfterFreeze(), Phase::addUniqueSpecies(), Phase::getAtoms(), LatticeSolidPhase::installSlavePhases(), Phase::nAtoms(), and Phase::operator=().
vector_fp m_speciesSize protected inherited
Vector of species sizes.
length m_kk. Used in some equations of state which employ the constant partial molar volume approximation.
Definition at line 740 of file Phase.h.
Referenced by Phase::addUniqueSpecies(), DebyeHuckel::initLengths(), HMWSoln::initLengths(), MineralEQ3::initThermoXML(), DebyeHuckel::initThermoXML(), Phase::operator=(), Phase::size(), HMWSoln::speciesMolarVolume(), and DebyeHuckel::standardConcentration().
vector_fp m_speciesCharge protected inherited
Vector of species charges. length m_kk.
Definition at line 742 of file Phase.h.
Referenced by Phase::addUniqueSpecies(), HMWSoln::applyphScale(), HMWSoln::calcMolalitiesCropped(), MolarityIonicVPSSTP::calcPseudoBinaryMoleFractions(), Phase::charge(), IonsFromNeutralVPSSTP::getDissociationCoeffs(), MolarityIonicVPSSTP::initThermo(), DebyeHuckel::initThermoXML(), Phase::operator=(), HMWSoln::printCoeffs(), PhaseCombo_Interaction::readXMLBinarySpecies(), RedlichKisterVPSSTP::readXMLBinarySpecies(), MargulesVPSSTP::readXMLBinarySpecies(), MixedSolventElectrolyte::readXMLBinarySpecies(), HMWSoln::relative_molal_enthalpy(), DebyeHuckel::s_update_d2lnMolalityActCoeff_dT2(), DebyeHuckel::s_update_dlnMolalityActCoeff_dP(), DebyeHuckel::s_update_dlnMolalityActCoeff_dT(), DebyeHuckel::s_update_lnMolalityActCoeff(), HMWSoln::s_update_lnMolalityActCoeff(), HMWSoln::s_updatePitzer_CoeffWRTemp(), HMWSoln::s_updatePitzer_d2lnMolalityActCoeff_dT2(), HMWSoln::s_updatePitzer_dlnMolalityActCoeff_dP(), HMWSoln::s_updatePitzer_dlnMolalityActCoeff_dT(), HMWSoln::s_updatePitzer_lnMolalityActCoeff(), HMWSoln::s_updateScaling_pHScaling(), HMWSoln::s_updateScaling_pHScaling_dP(), HMWSoln::s_updateScaling_pHScaling_dT(), and HMWSoln::s_updateScaling_pHScaling_dT2().
The documentation for this class was generated from the following files:
PhaseCombo_Interaction.h
PhaseCombo_Interaction.cpp