Cantera: EdgeKinetics Class Reference
EdgeKinetics Class Reference
Heterogeneous reactions at one-dimensional interfaces between multiple adjacent two-dimensional surfaces.
#include <EdgeKinetics.h>
Public Member Functions
EdgeKinetics ()
Constructor.
virtual ~EdgeKinetics ()
Destructor.
EdgeKinetics (const EdgeKinetics &right)
EdgeKinetics & operator= (const EdgeKinetics &right)
virtual Kinetics * duplMyselfAsKinetics (const std::vector< thermo_t * > &tpVector) const
Duplication routine for objects which inherit from Kinetics.
virtual int ID () const
Identifies the subclass of the Kinetics manager type.
virtual int type () const
Identifies the subclass of the Kinetics manager type.
virtual void finalize ()
Finish adding reactions and prepare for use.
void setElectricPotential (int n, doublereal V)
Set the electric potential in the nth phase.
void incrementRxnCount ()
Increment the number of reactions in the mechanism by one.
void selectPhase (const doublereal *data, const thermo_t *phase, doublereal *phase_data)
Extract from array data the portion pertaining to phase phase.
Reaction Rates Of Progress
virtual void getFwdRatesOfProgress (doublereal *fwdROP)
Return the forward rates of progress for each reaction.
virtual void getRevRatesOfProgress (doublereal *revROP)
Return the reverse rates of progress for each reaction.
virtual void getNetRatesOfProgress (doublereal *netROP)
Return the net rates of progress for each reaction.
virtual void getEquilibriumConstants (doublereal *kc)
Get the equilibrium constants of all reactions, whether the reaction is reversible or not.
void getExchangeCurrentQuantities ()
virtual void getDeltaGibbs (doublereal *deltaG)
Return the vector of values for the reaction gibbs free energy change.
virtual void getDeltaElectrochemPotentials (doublereal *deltaM)
Return the vector of values for the reaction electrochemical free energy change.
virtual void getDeltaEnthalpy (doublereal *deltaH)
Return the vector of values for the reactions change in enthalpy.
virtual void getDeltaEntropy (doublereal *deltaS)
Return the vector of values for the change in entropy due to each reaction.
virtual void getDeltaSSGibbs (doublereal *deltaG)
Return the vector of values for the reaction standard state gibbs free energy change.
virtual void getDeltaSSEnthalpy (doublereal *deltaH)
Return the vector of values for the change in the standard state enthalpies of reaction.
virtual void getDeltaSSEntropy (doublereal *deltaS)
Return the vector of values for the change in the standard state entropies for each reaction.
Species Production Rates
virtual void getCreationRates (doublereal *cdot)
Returns the Species creation rates [kmol/m^2/s].
virtual void getDestructionRates (doublereal *ddot)
Return the Species destruction rates [kmol/m^2/s].
virtual void getNetProductionRates (doublereal *net)
Return the species net production rates [kmol/m^2/s].
Reaction Mechanism Informational Query Routines
virtual doublereal reactantStoichCoeff (size_t k, size_t i) const
Stoichiometric coefficient of species k as a reactant in reaction i.
virtual doublereal productStoichCoeff (size_t k, size_t i) const
Stoichiometric coefficient of species k as a product in reaction i.
virtual int reactionType (size_t i) const
Flag specifying the type of reaction.
virtual void getActivityConcentrations (doublereal *const conc)
Get the vector of activity concentrations used in the kinetics object.
doublereal electrochem_beta (size_t irxn) const
Return the charge transfer rxn Beta parameter for the ith reaction.
virtual bool isReversible (size_t i)
True if reaction i has been declared to be reversible.
virtual std::string reactionString (size_t i) const
Return a string representing the reaction.
virtual void getFwdRateConstants (doublereal *kfwd)
Update the rates of progress of the reactions in the reaction mechanism.
virtual void getRevRateConstants (doublereal *krev, bool doIrreversible=false)
Update the rates of progress of the reactions in the reaction mechanism.
virtual void getActivationEnergies (doublereal *E)
Return the activation energies in Kelvin.
Constructors and General Information about Mechanism
virtual void assignShallowPointers (const std::vector< thermo_t * > &tpVector)
Reassign the shallow pointers within the FKinetics object.
size_t nReactions () const
Number of reactions in the reaction mechanism.
void checkReactionIndex (size_t m) const
Check that the specified reaction index is in range Throws an exception if i is greater than nReactions()
void checkReactionArraySize (size_t ii) const
Check that an array size is at least nReactions() Throws an exception if ii is less than nReactions().
void checkSpeciesIndex (size_t k) const
Check that the specified species index is in range Throws an exception if k is greater than nSpecies()-1.
void checkSpeciesArraySize (size_t mm) const
Check that an array size is at least nSpecies() Throws an exception if kk is less than nSpecies().
Information/Lookup Functions about Phases and Species
size_t nPhases () const
The number of phases participating in the reaction mechanism.
void checkPhaseIndex (size_t m) const
Check that the specified phase index is in range Throws an exception if m is greater than nPhases()
void checkPhaseArraySize (size_t mm) const
Check that an array size is at least nPhases() Throws an exception if mm is less than nPhases().
size_t phaseIndex (std::string ph)
Return the phase index of a phase in the list of phases defined within the object.
size_t surfacePhaseIndex ()
This returns the integer index of the phase which has ThermoPhase type cSurf.
size_t reactionPhaseIndex ()
Phase where the reactions occur.
thermo_t & thermo (size_t n=0)
This method returns a reference to the nth ThermoPhase object defined in this kinetics mechanism.
const thermo_t & thermo (size_t n=0) const
thermo_t & phase (size_t n=0)
This method returns a reference to the nth ThermoPhase defined in this kinetics mechanism.
const thermo_t & phase (size_t n=0) const
This method returns a reference to the nth ThermoPhase defined in this kinetics mechanism.
size_t nTotalSpecies () const
The total number of species in all phases participating in the kinetics mechanism.
size_t start (size_t n)
Returns the starting index of the species in the nth phase associated with the reaction mechanism.
size_t kineticsSpeciesIndex (size_t k, size_t n) const
The location of species k of phase n in species arrays.
size_t kineticsSpeciesIndex (const std::string &nm) const
This routine will look up a species number based on the input std::string nm.
size_t kineticsSpeciesIndex (const std::string &nm, const std::string &ph) const
This routine will look up a species number based on the input std::string nm.
std::string kineticsSpeciesName (size_t k) const
Return the std::string name of the kth species in the kinetics manager.
thermo_t & speciesPhase (std::string nm)
This function looks up the std::string name of a species and returns a reference to the ThermoPhase object of the phase where the species resides.
thermo_t & speciesPhase (size_t k)
This function takes as an argument the kineticsSpecies index (i.e., the list index in the list of species in the kinetics manager) and returns the species' owning ThermoPhase object.
size_t speciesPhaseIndex (size_t k)
This function takes as an argument the kineticsSpecies index (i.e., the list index in the list of species in the kinetics manager) and returns the index of the phase owning the species.
Reaction Rates Of Progress
virtual void getReactionDelta (const doublereal *property, doublereal *deltaProperty)
Change in species properties.
Reaction Mechanism Informational Query Routines
virtual doublereal reactantOrder (size_t k, size_t i) const
Reactant order of species k in reaction i.
virtual doublereal productOrder (int k, int i) const
product Order of species k in reaction i.
virtual const std::vector
< size_t > & reactants (size_t i) const
Returns a read-only reference to the vector of reactant index numbers for reaction i.
virtual const std::vector
< size_t > & products (size_t i) const
Returns a read-only reference to the vector of product index numbers for reaction i.
Reaction Mechanism Construction
virtual const std::vector
< grouplist_t > & reactantGroups (size_t i)
virtual const std::vector
< grouplist_t > & productGroups (size_t i)
Altering Reaction Rates
These methods alter reaction rates.
They are designed primarily for carrying out sensitivity analysis, but may be used for any purpose requiring dynamic alteration of rate constants. For each reaction, a real-valued multiplier may be defined that multiplies the reaction rate coefficient. The multiplier may be set to zero to completely remove a reaction from the mechanism.
doublereal multiplier (size_t i) const
The current value of the multiplier for reaction i.
void setMultiplier (size_t i, doublereal f)
Set the multiplier for reaction i to f.
Protected Attributes
size_t m_ii
Number of reactions in the mechanism.
size_t m_kk
The number of species in all of the phases that participate in this kinetics mechanism.
vector_fp m_perturb
Vector of perturbation factors for each reaction's rate of progress vector.
std::vector< std::vector
< size_t > > m_reactants
This is a vector of vectors containing the reactants for each reaction.
std::vector< std::vector
< size_t > > m_products
This is a vector of vectors containing the products for each reaction.
std::vector< thermo_t * > m_thermo
m_thermo is a vector of pointers to ThermoPhase objects that are involved with this kinetics operator
std::vector< size_t > m_start
m_start is a vector of integers specifying the beginning position for the species vector for the n'th phase in the kinetics class.
std::map< std::string, size_t > m_phaseindex
Mapping of the phase id, i.e., the id attribute in the xml phase element to the position of the phase within the kinetics object.
size_t m_surfphase
Index in the list of phases of the one surface phase.
size_t m_rxnphase
Phase Index where reactions are assumed to be taking place.
size_t m_mindim
number of spatial dimensions of lowest-dimensional phase.
Reaction Mechanism Construction
virtual void addPhase (thermo_t &thermo)
Add a phase to the kinetics manager object.
virtual void init ()
Prepare the class for the addition of reactions.
virtual void addReaction (ReactionData &r)
Add a single reaction to the mechanism.
virtual bool ready () const
Returns true if the kinetics manager has been properly initialized and finalized.
void updateROP ()
Internal routine that updates the Rates of Progress of the reactions.
void _update_rates_T ()
Update properties that depend on temperature.
void _update_rates_phi ()
Update properties that depend on the electric potential.
void _update_rates_C ()
Update properties that depend on the species mole fractions and/or concentration.
void advanceCoverages (doublereal tstep)
Advance the surface coverages in time.
void solvePseudoSteadyStateProblem (int ifuncOverride=-1, doublereal timeScaleOverride=1.0)
Solve for the pseudo steady-state of the surface problem.
void setIOFlag (int ioFlag)
void checkPartialEquil ()
size_t reactionNumber () const
void addElementaryReaction (ReactionData &r)
void addGlobalReaction (const ReactionData &r)
void installReagents (const ReactionData &r)
void updateKc ()
Update the equilibrium constants in molar units for all reversible reactions.
void registerReaction (size_t rxnNumber, int type, size_t loc)
Write values into m_index.
void applyButlerVolmerCorrection (doublereal *const kf)
Apply corrections for interfacial charge transfer reactions.
void applyExchangeCurrentDensityFormulation (doublereal *const kfwd)
When an electrode reaction rate is optionally specified in terms of its exchange current density, extra vectors need to be precalculated.
void setPhaseExistence (const size_t iphase, const bool exists)
Set the existence of a phase in the reaction object.
void setPhaseStability (const int iphase, const int isStable)
Set the stability of a phase in the reaction object.
int phaseExistence (const int iphase) const
Gets the phase existence int for the ith phase.
int phaseStability (const int iphase) const
Gets the phase stability int for the ith phase.
vector_fp m_grt
Temporary work vector of length m_kk.
std::vector< size_t > m_revindex
List of reactions numbers which are reversible reactions.
Rate1< SurfaceArrhenius > m_rates
Templated class containing the vector of reactions for this interface.
bool m_redo_rates
std::map< size_t, std::pair
< int, size_t > > m_index
Vector of information about reactions in the mechanism.
std::vector< size_t > m_irrev
Vector of irreversible reaction numbers.
ReactionStoichMgr m_rxnstoich
Stoichiometric manager for the reaction mechanism.
size_t m_nirrev
Number of irreversible reactions in the mechanism.
size_t m_nrev
Number of reversible reactions in the mechanism.
std::vector< std::map< size_t,
doublereal > > m_rrxn
m_rrxn is a vector of maps, containing the reactant stoichiometric coefficient information
std::vector< std::map< size_t,
doublereal > > m_prxn
m_prxn is a vector of maps, containing the reactant stoichiometric coefficient information
std::vector< std::string > m_rxneqn
String expression for each rxn.
InterfaceKineticsData * m_kdata
Temporary data storage used in calculating the rates of of reactions.
vector_fp m_conc
an array of generalized concentrations for each species
vector_fp m_mu0
Vector of standard state chemical potentials.
vector_fp m_phi
Vector of phase electric potentials.
vector_fp m_pot
Vector of potential energies due to Voltages.
vector_fp m_rwork
Vector temporary.
vector_fp m_E
Vector of raw activation energies for the reactions.
SurfPhase * m_surf
Pointer to the single surface phase.
ImplicitSurfChem * m_integrator
Pointer to the Implicit surface chemistry object.
vector_fp m_beta
std::vector< size_t > m_ctrxn
Vector of reaction indexes specifying the id of the current transfer reactions in the mechanism.
vector_int m_ctrxn_ecdf
Vector of booleans indicating whether the charge transfer reaction may be described by an exchange current density expression.
vector_fp m_StandardConc
vector_fp m_deltaG0
vector_fp m_ProdStanConcReac
bool m_finalized
boolean indicating whether mechanism has been finalized
bool m_has_coverage_dependence
Boolean flag indicating whether any reaction in the mechanism has a coverage dependent forward reaction rate.
bool m_has_electrochem_rxns
Boolean flag indicating whether any reaction in the mechanism has a beta electrochemical parameter.
bool m_has_exchange_current_density_formulation
Boolean flag indicating whether any reaction in the mechanism is described by an exchange current density expression.
int m_phaseExistsCheck
Int flag to indicate that some phases in the kinetics mechanism are non-existent.
std::vector< bool > m_phaseExists
Vector of booleans indicating whether phases exist or not.
std::vector< int > m_phaseIsStable
Vector of int indicating whether phases are stable or not.
std::vector< bool * > m_rxnPhaseIsReactant
Vector of vector of booleans indicating whether a phase participates in a reaction as a reactant.
std::vector< bool * > m_rxnPhaseIsProduct
Vector of vector of booleans indicating whether a phase participates in a reaction as a product.
std::vector< int > m_phaseIsIntermediate
Vector of ints indicating whether zeroed phase is an intermediate for the formation of another phase.
int m_numIntermediatePhases
std::vector< doublereal > m_rxnRateFactorPhaseIntermediates
Reaction rate reduction factor for intermediates.
std::vector< doublereal > m_speciesTmpP
Work vector having length number of species.
std::vector< doublereal > m_speciesTmpD
int m_ioFlag
Detailed Description
Heterogeneous reactions at one-dimensional interfaces between multiple adjacent two-dimensional surfaces.
Definition at line 22 of file EdgeKinetics.h.
Constructor & Destructor Documentation
EdgeKinetics () inline
Constructor.
Definition at line 31 of file EdgeKinetics.h.
Referenced by EdgeKinetics::duplMyselfAsKinetics().
virtual ~EdgeKinetics () inline virtual
Destructor.
Definition at line 34 of file EdgeKinetics.h.
Member Function Documentation
virtual Kinetics* duplMyselfAsKinetics (const std::vector< thermo_t * > & tpVector) const inline virtual
Duplication routine for objects which inherit from Kinetics.
This virtual routine can be used to duplicate Kinetics objects inherited from Kinetics even if the application only has a pointer to Kinetics to work with.
These routines are basically wrappers around the derived copy constructor.
Parameters
tpVector Vector of shallow pointers to ThermoPhase objects. this is the m_thermo vector within this object
Reimplemented from InterfaceKinetics.
Definition at line 59 of file EdgeKinetics.h.
References Kinetics::assignShallowPointers(), and EdgeKinetics::EdgeKinetics().
virtual int ID () const inline virtual
Identifies the subclass of the Kinetics manager type.
These are listed in mix_defs.h.
Deprecated:
use type() instead.
Reimplemented from InterfaceKinetics.
Definition at line 70 of file EdgeKinetics.h.
virtual int type () const inline virtual
Identifies the subclass of the Kinetics manager type.
These are listed in mix_defs.h.
Reimplemented from InterfaceKinetics.
Definition at line 78 of file EdgeKinetics.h.
void finalize () virtual
Finish adding reactions and prepare for use.
This function must be called after all reactions are entered into the mechanism and before the mechanism is used to calculate reaction rates.
This function must be called after all reactions are entered into the mechanism and before the mechanism is used to calculate reaction rates.
Here, we resize work arrays based on the number of reactions, since we don't know this number up to now.
Reimplemented from InterfaceKinetics.
Definition at line 1493 of file InterfaceKinetics.cpp.
References Cantera::int2str(), InterfaceKinetics::m_finalized, Kinetics::m_perturb, InterfaceKinetics::m_rwork, InterfaceKinetics::m_surf, Phase::nDim(), Cantera::npos, Kinetics::nReactions(), Kinetics::reactionPhaseIndex(), and Kinetics::thermo().
void setElectricPotential (int n, doublereal V) inherited
Set the electric potential in the nth phase.
Parameters
n phase Index in this kinetics object.
V Electric potential (volts)
Definition at line 265 of file InterfaceKinetics.cpp.
References ThermoPhase::setElectricPotential(), and Kinetics::thermo().
virtual void getFwdRatesOfProgress (doublereal * fwdROP) inline virtual inherited
Return the forward rates of progress for each reaction.
Parameters
fwdROP vector of rates of progress. length = number of reactions, Units are kmol m-2 s-1.
Reimplemented from Kinetics.
Definition at line 181 of file InterfaceKinetics.h.
References InterfaceKinetics::m_kdata, and InterfaceKinetics::updateROP().
virtual void getRevRatesOfProgress (doublereal * revROP) inline virtual inherited
Return the reverse rates of progress for each reaction.
Parameters
revROP vector of rates of progress. length = number of reactions, Units are kmol m-2 s-1.
Reimplemented from Kinetics.
Definition at line 191 of file InterfaceKinetics.h.
References InterfaceKinetics::m_kdata, and InterfaceKinetics::updateROP().
virtual void getNetRatesOfProgress (doublereal * netROP) inline virtual inherited
Return the net rates of progress for each reaction.
Parameters
netROP vector of rates of progress. length = number of reactions, Units are kmol m-2 s-1.
Reimplemented from Kinetics.
Definition at line 201 of file InterfaceKinetics.h.
References InterfaceKinetics::m_kdata, and InterfaceKinetics::updateROP().
void getEquilibriumConstants (doublereal * kc) virtual inherited
Get the equilibrium constants of all reactions, whether the reaction is reversible or not.
Get the equilibrium constants of all reactions, whether reversible or not.
Parameters
kc Returns the concentration equation constant for the reaction. Length is the number of reactions
Reimplemented from Kinetics.
Definition at line 449 of file InterfaceKinetics.cpp.
References Phase::charge(), DATA_PTR, Cantera::GasConstant, ReactionStoichMgr::getReactionDelta(), ThermoPhase::getStandardChemPotentials(), ThermoPhase::logStandardConc(), Kinetics::m_ii, InterfaceKinetics::m_mu0, InterfaceKinetics::m_phi, InterfaceKinetics::m_rxnstoich, Kinetics::m_start, Kinetics::nPhases(), Phase::nSpecies(), Phase::temperature(), and Kinetics::thermo().
Referenced by InterfaceKinetics::getRevRateConstants().
void getDeltaGibbs (doublereal * deltaG) virtual inherited
Return the vector of values for the reaction gibbs free energy change.
These values depend upon the concentration of the solution.
units = J kmol-1
Parameters
deltaG Output vector of deltaG's for reactions Length: m_ii.
Reimplemented from Kinetics.
Definition at line 841 of file InterfaceKinetics.cpp.
References DATA_PTR, ThermoPhase::getChemPotentials(), ReactionStoichMgr::getReactionDelta(), InterfaceKinetics::m_grt, InterfaceKinetics::m_rxnstoich, Kinetics::m_start, Kinetics::nPhases(), and Kinetics::thermo().
void getDeltaElectrochemPotentials (doublereal * deltaM) virtual inherited
Return the vector of values for the reaction electrochemical free energy change.
These values depend upon the concentration of the solution and the voltage of the phases
units = J kmol-1
Parameters
deltaM Output vector of deltaM's for reactions Length: m_ii.
Reimplemented from Kinetics.
Definition at line 871 of file InterfaceKinetics.cpp.
References DATA_PTR, ThermoPhase::getElectrochemPotentials(), ReactionStoichMgr::getReactionDelta(), InterfaceKinetics::m_grt, InterfaceKinetics::m_rxnstoich, Kinetics::m_start, Kinetics::nPhases(), and Kinetics::thermo().
void getDeltaEnthalpy (doublereal * deltaH) virtual inherited
Return the vector of values for the reactions change in enthalpy.
These values depend upon the concentration of the solution.
units = J kmol-1
Reimplemented from Kinetics.
Definition at line 899 of file InterfaceKinetics.cpp.
References DATA_PTR, ThermoPhase::getPartialMolarEnthalpies(), ReactionStoichMgr::getReactionDelta(), InterfaceKinetics::m_grt, InterfaceKinetics::m_rxnstoich, Kinetics::m_start, Kinetics::nPhases(), and Kinetics::thermo().
void getDeltaEntropy (doublereal * deltaS) virtual inherited
Return the vector of values for the change in entropy due to each reaction.
These values depend upon the concentration of the solution.
units = J kmol-1 Kelvin-1
Parameters
deltaS vector of Enthalpy changes Length = m_ii, number of reactions
Reimplemented from Kinetics.
Definition at line 928 of file InterfaceKinetics.cpp.
References DATA_PTR, ThermoPhase::getPartialMolarEntropies(), ReactionStoichMgr::getReactionDelta(), InterfaceKinetics::m_grt, InterfaceKinetics::m_rxnstoich, Kinetics::m_start, Kinetics::nPhases(), and Kinetics::thermo().
void getDeltaSSGibbs (doublereal * deltaG) virtual inherited
Return the vector of values for the reaction standard state gibbs free energy change.
getDeltaSSGibbs():
These values don't depend upon the concentration of the solution.
Parameters
deltaG vector of rxn SS free energy changes units = J kmol-1
Return the vector of values for the reaction standard state gibbs free energy change. These values don't depend upon the concentration of the solution.
units = J kmol-1
Reimplemented from Kinetics.
Definition at line 955 of file InterfaceKinetics.cpp.
References DATA_PTR, ReactionStoichMgr::getReactionDelta(), ThermoPhase::getStandardChemPotentials(), InterfaceKinetics::m_grt, InterfaceKinetics::m_rxnstoich, Kinetics::m_start, Kinetics::nPhases(), and Kinetics::thermo().
void getDeltaSSEnthalpy (doublereal * deltaH) virtual inherited
Return the vector of values for the change in the standard state enthalpies of reaction.
getDeltaSSEnthalpy():
These values don't depend upon the concentration of the solution.
Parameters
deltaH vector of rxn SS enthalpy changes units = J kmol-1
Return the vector of values for the change in the standard state enthalpies of reaction. These values don't depend upon the concentration of the solution.
units = J kmol-1
Reimplemented from Kinetics.
Definition at line 984 of file InterfaceKinetics.cpp.
References DATA_PTR, Cantera::GasConstant, ThermoPhase::getEnthalpy_RT(), ReactionStoichMgr::getReactionDelta(), InterfaceKinetics::m_grt, Kinetics::m_kk, InterfaceKinetics::m_rxnstoich, Kinetics::m_start, Kinetics::nPhases(), Phase::temperature(), and Kinetics::thermo().
void getDeltaSSEntropy (doublereal * deltaS) virtual inherited
Return the vector of values for the change in the standard state entropies for each reaction.
These values don't depend upon the concentration of the solution.
Parameters
deltaS vector of rxn SS entropy changes units = J kmol-1 Kelvin-1
Reimplemented from Kinetics.
Definition at line 1017 of file InterfaceKinetics.cpp.
References DATA_PTR, Cantera::GasConstant, ThermoPhase::getEntropy_R(), ReactionStoichMgr::getReactionDelta(), InterfaceKinetics::m_grt, Kinetics::m_kk, InterfaceKinetics::m_rxnstoich, Kinetics::m_start, Kinetics::nPhases(), and Kinetics::thermo().
void getCreationRates (doublereal * cdot) virtual inherited
Returns the Species creation rates [kmol/m^2/s].
Return the species creation rates in array cdot, which must be dimensioned at least as large as the total number of species in all phases of the kinetics model
Parameters
cdot Vector containing creation rates. length = m_kk. units = kmol/m^2/s
Reimplemented from Kinetics.
Definition at line 513 of file InterfaceKinetics.cpp.
References ReactionStoichMgr::getCreationRates(), InterfaceKinetics::m_kdata, Kinetics::m_kk, InterfaceKinetics::m_rxnstoich, and InterfaceKinetics::updateROP().
void getDestructionRates (doublereal * ddot) virtual inherited
Return the Species destruction rates [kmol/m^2/s].
Return the species destruction rates in array ddot, which must be dimensioned at least as large as the total number of species in all phases of the kinetics model
Parameters
ddot Vector containing destruction rates. length = m_kk. units = kmol/m^2/s
Reimplemented from Kinetics.
Definition at line 526 of file InterfaceKinetics.cpp.
References ReactionStoichMgr::getDestructionRates(), InterfaceKinetics::m_kdata, Kinetics::m_kk, InterfaceKinetics::m_rxnstoich, and InterfaceKinetics::updateROP().
void getNetProductionRates (doublereal * net) virtual inherited
Return the species net production rates [kmol/m^2/s].
Species net production rates [kmol/m^2/s]. Return the species net production rates (creation - destruction) in array wdot, which must be dimensioned at least as large as the total number of species in all phases of the kinetics model
Parameters
net Vector of species production rates. units kmol m-d s-1, where d is dimension.
Reimplemented from Kinetics.
Definition at line 544 of file InterfaceKinetics.cpp.
References ReactionStoichMgr::getNetProductionRates(), InterfaceKinetics::m_kdata, Kinetics::m_kk, InterfaceKinetics::m_rxnstoich, and InterfaceKinetics::updateROP().
Referenced by solveSP::calc_t(), ReactingSurf1D::eval(), solveSP::fun_eval(), solveProb::print_header(), and solveProb::printIteration().
virtual doublereal reactantStoichCoeff (size_t k, size_t i) const inline virtual inherited
Stoichiometric coefficient of species k as a reactant in reaction i.
Reimplemented from Kinetics.
Definition at line 353 of file InterfaceKinetics.h.
References InterfaceKinetics::m_rrxn.
virtual doublereal productStoichCoeff (size_t k, size_t i) const inline virtual inherited
Stoichiometric coefficient of species k as a product in reaction i.
Reimplemented from Kinetics.
Definition at line 361 of file InterfaceKinetics.h.
References InterfaceKinetics::m_prxn.
virtual int reactionType (size_t i) const inline virtual inherited
Flag specifying the type of reaction.
The legal values and their meaning are specific to the particular kinetics manager.
Reimplemented from Kinetics.
Definition at line 370 of file InterfaceKinetics.h.
References InterfaceKinetics::m_index.
void getActivityConcentrations (doublereal *const conc) virtual inherited
Get the vector of activity concentrations used in the kinetics object.
Parameters
conc (output) Vector of activity concentrations. Length is equal to the number of species in the kinetics object
Reimplemented from Kinetics.
Definition at line 348 of file InterfaceKinetics.cpp.
References InterfaceKinetics::_update_rates_C(), and InterfaceKinetics::m_conc.
doublereal electrochem_beta (size_t irxn) const inherited
Return the charge transfer rxn Beta parameter for the ith reaction.
Returns the beta parameter for a charge transfer reaction. This parameter is not important for non-charge transfer reactions. Note, the parameter defaults to zero. However, a value of 0.5 should be supplied for every charge transfer reaction if no information is known, as a value of 0.5 pertains to a symmetric transition state. The value can vary between 0 to 1.
Parameters
irxn Reaction number in the kinetics mechanism
Returns
Beta parameter. This defaults to zero, even for charge transfer reactions.
Definition at line 1363 of file InterfaceKinetics.cpp.
References InterfaceKinetics::m_ctrxn.
virtual bool isReversible (size_t i) inline virtual inherited
True if reaction i has been declared to be reversible.
If isReversible(i) is false, then the reverse rate of progress for reaction i is always zero.
Reimplemented from Kinetics.
Definition at line 404 of file InterfaceKinetics.h.
References InterfaceKinetics::m_revindex.
virtual std::string reactionString (size_t i) const inline virtual inherited
Return a string representing the reaction.
Reimplemented from Kinetics.
Definition at line 416 of file InterfaceKinetics.h.
References InterfaceKinetics::m_rxneqn.
void getFwdRateConstants (doublereal * kfwd) virtual inherited
Update the rates of progress of the reactions in the reaction mechanism.
This routine operates on internal data.
Reimplemented from Kinetics.
Definition at line 641 of file InterfaceKinetics.cpp.
References InterfaceKinetics::m_kdata, Kinetics::m_perturb, Cantera::multiply_each(), Kinetics::nReactions(), and InterfaceKinetics::updateROP().
Referenced by InterfaceKinetics::getRevRateConstants().
void getRevRateConstants (doublereal * krev, bool doIrreversible = false) virtual inherited
Update the rates of progress of the reactions in the reaction mechanism.
This routine operates on internal data.
Reimplemented from Kinetics.
Definition at line 661 of file InterfaceKinetics.cpp.
References DATA_PTR, InterfaceKinetics::getEquilibriumConstants(), InterfaceKinetics::getFwdRateConstants(), Kinetics::m_ii, InterfaceKinetics::m_kdata, Cantera::multiply_each(), and Kinetics::nReactions().
void getActivationEnergies (doublereal * E) virtual inherited
Return the activation energies in Kelvin.
length is the number of reactions
Parameters
E Ouptut vector of activation energies. Length: m_ii.
Reimplemented from Kinetics.
Definition at line 677 of file InterfaceKinetics.cpp.
References InterfaceKinetics::m_E.
void addPhase (thermo_t & thermo) virtual inherited
Add a phase to the kinetics manager object.
This must be done before the function init() is called or before any reactions are input.
This function calls the Kinetics operator addPhase. It also sets the following functions
   m_phaseExists[]
Parameters
thermo Reference to the ThermoPhase to be added.
Reimplemented from Kinetics.
Definition at line 1294 of file InterfaceKinetics.cpp.
References Kinetics::addPhase(), InterfaceKinetics::m_phaseExists, and InterfaceKinetics::m_phaseIsStable.
Referenced by InterfaceKinetics::InterfaceKinetics().
void init () virtual inherited
Prepare the class for the addition of reactions.
This function must be called after instantiation of the class, but before any reactions are actually added to the mechanism. This function calculates m_kk the number of species in all phases participating in the reaction mechanism. We don't know m_kk previously, before all phases have been added.
Reimplemented from Kinetics.
Definition at line 1309 of file InterfaceKinetics.cpp.
References InterfaceKinetics::m_conc, InterfaceKinetics::m_grt, Kinetics::m_kk, InterfaceKinetics::m_mu0, InterfaceKinetics::m_phi, InterfaceKinetics::m_pot, InterfaceKinetics::m_prxn, InterfaceKinetics::m_rrxn, Kinetics::nPhases(), Phase::nSpecies(), and Kinetics::thermo().
void addReaction (ReactionData & r) virtual inherited
Add a single reaction to the mechanism.
Parameters
r Reference to a ReactionData object containing all of the info needed to describe the reaction.
This routine must be called after init() and before finalize(). This function branches on the types of reactions allowed by the interfaceKinetics manager in order to install the reaction correctly in the manager. The manager allows the following reaction types Elementary Surface Global There is no difference between elementary and surface reactions.
Reimplemented from Kinetics.
Definition at line 1052 of file InterfaceKinetics.cpp.
References Kinetics::incrementRxnCount(), InterfaceKinetics::m_rxneqn, InterfaceKinetics::m_rxnPhaseIsProduct, InterfaceKinetics::m_rxnPhaseIsReactant, Kinetics::nPhases(), Kinetics::products(), Kinetics::reactants(), and Kinetics::speciesPhaseIndex().
bool ready () const virtual inherited
Returns true if the kinetics manager has been properly initialized and finalized.
Reimplemented from Kinetics.
Reimplemented in Interface.
Definition at line 1374 of file InterfaceKinetics.cpp.
References InterfaceKinetics::m_finalized.
void updateROP () inherited
Internal routine that updates the Rates of Progress of the reactions.
Update the rates of progress of the reactions in the reaction mechanism.
This is actually the guts of the functionality of the object
This routine operates on internal data.
Definition at line 686 of file InterfaceKinetics.cpp.
References InterfaceKinetics::_update_rates_C(), InterfaceKinetics::_update_rates_T(), DATA_PTR, InterfaceKinetics::m_conc, Kinetics::m_ii, InterfaceKinetics::m_kdata, Kinetics::m_perturb, InterfaceKinetics::m_phaseExists, InterfaceKinetics::m_phaseExistsCheck, InterfaceKinetics::m_phaseIsStable, InterfaceKinetics::m_rxnPhaseIsProduct, InterfaceKinetics::m_rxnPhaseIsReactant, InterfaceKinetics::m_rxnstoich, Cantera::multiply_each(), ReactionStoichMgr::multiplyReactants(), ReactionStoichMgr::multiplyRevProducts(), and Kinetics::nPhases().
Referenced by InterfaceKinetics::getCreationRates(), InterfaceKinetics::getDestructionRates(), InterfaceKinetics::getFwdRateConstants(), InterfaceKinetics::getFwdRatesOfProgress(), InterfaceKinetics::getNetProductionRates(), InterfaceKinetics::getNetRatesOfProgress(), and InterfaceKinetics::getRevRatesOfProgress().
void _update_rates_T () inherited
Update properties that depend on temperature.
This is called to update all of the properties that depend on temperature
Current objects that this function updates m_kdata->m_logtemp m_kdata->m_rfn m_rates. updateKc();
Definition at line 281 of file InterfaceKinetics.cpp.
References InterfaceKinetics::_update_rates_phi(), InterfaceKinetics::applyButlerVolmerCorrection(), InterfaceKinetics::applyExchangeCurrentDensityFormulation(), DATA_PTR, SurfPhase::getCoverages(), InterfaceKinetics::m_conc, InterfaceKinetics::m_has_coverage_dependence, InterfaceKinetics::m_has_electrochem_rxns, InterfaceKinetics::m_has_exchange_current_density_formulation, InterfaceKinetics::m_kdata, InterfaceKineticsData::m_logtemp, InterfaceKinetics::m_rates, InterfaceKinetics::m_surf, InterfaceKineticsData::m_temp, Kinetics::surfacePhaseIndex(), Phase::temperature(), Kinetics::thermo(), Rate1< R >::update(), Rate1< R >::update_C(), and InterfaceKinetics::updateKc().
Referenced by InterfaceKinetics::updateROP().
void _update_rates_phi () inherited
Update properties that depend on the electric potential.
This is called to update all of the properties that depend on potential
Definition at line 307 of file InterfaceKinetics.cpp.
References ThermoPhase::electricPotential(), InterfaceKinetics::m_phi, Kinetics::nPhases(), and Kinetics::thermo().
Referenced by InterfaceKinetics::_update_rates_T().
void _update_rates_C () inherited
Update properties that depend on the species mole fractions and/or concentration.
Update properties that depend on concentrations.
This is called to update all of the properties that depend on concentration
This method fills out the array of generalized concentrations by calling method getActivityConcentrations for each phase, which classes representing phases should overload to return the appropriate quantities.
Definition at line 326 of file InterfaceKinetics.cpp.
References DATA_PTR, ThermoPhase::getActivityConcentrations(), InterfaceKinetics::m_conc, InterfaceKinetics::m_kdata, Kinetics::m_start, Kinetics::nPhases(), and Kinetics::thermo().
Referenced by InterfaceKinetics::getActivityConcentrations(), and InterfaceKinetics::updateROP().
void advanceCoverages (doublereal tstep) inherited
Advance the surface coverages in time.
This method carries out a time-accurate advancement of the surface coverages for a specified amount of time.
\[ \dot {\theta}_k = \dot s_k (\sigma_k / s_0) \]
Parameters
tstep Time value to advance the surface coverages
Definition at line 1384 of file InterfaceKinetics.cpp.
References ImplicitSurfChem::initialize(), ImplicitSurfChem::integrate(), and InterfaceKinetics::m_integrator.
void solvePseudoSteadyStateProblem (int ifuncOverride = -1, doublereal timeScaleOverride = 1.0) inherited
Solve for the pseudo steady-state of the surface problem.
Solve for the steady state of the surface problem. This is the same thing as the advanceCoverages() function, but at infinite times.
Note, a direct solve is carried out under the hood here, to reduce the computational time.
Parameters
ifuncOverride 4 values are possible 1 SFLUX_INITIALIZE 2 SFLUX_RESIDUAL 3 SFLUX_JACOBIAN 4 SFLUX_TRANSIENT The default is -1, which means that the program will decide.
timeScaleOverride When a pseudo transient is selected this value can be used to override the default time scale for integration which is one. When SFLUX_TRANSIENT is used, this is equal to the time over which the equations are integrated. When SFLUX_INITIALIZE is used, this is equal to the time used in the initial transient algorithm, before the equation system is solved directly.
Definition at line 1410 of file InterfaceKinetics.cpp.
References ImplicitSurfChem::initialize(), InterfaceKinetics::m_integrator, and ImplicitSurfChem::solvePseudoSteadyStateProblem().
void updateKc () inherited
Update the equilibrium constants in molar units for all reversible reactions.
Irreversible reactions have their equilibrium constant set to zero.
Definition at line 360 of file InterfaceKinetics.cpp.
References Phase::charge(), DATA_PTR, Cantera::GasConstant, ReactionStoichMgr::getRevReactionDelta(), ThermoPhase::getStandardChemPotentials(), Cantera::int2str(), ThermoPhase::logStandardConc(), Kinetics::m_ii, InterfaceKinetics::m_irrev, InterfaceKinetics::m_kdata, InterfaceKinetics::m_mu0, InterfaceKinetics::m_nirrev, InterfaceKinetics::m_nrev, InterfaceKinetics::m_phi, InterfaceKinetics::m_revindex, InterfaceKinetics::m_rxnstoich, Kinetics::m_start, Kinetics::nPhases(), Cantera::npos, Kinetics::nReactions(), Phase::nSpecies(), Phase::temperature(), and Kinetics::thermo().
Referenced by InterfaceKinetics::_update_rates_T().
void registerReaction (size_t rxnNumber, int type, size_t loc) inline inherited
Write values into m_index.
Parameters
rxnNumber reaction number
type reaction type
loc location ??
Definition at line 572 of file InterfaceKinetics.h.
References InterfaceKinetics::m_index, and InterfaceKinetics::type().
void applyButlerVolmerCorrection (doublereal *const kf) inherited
Apply corrections for interfacial charge transfer reactions.
For reactions that transfer charge across a potential difference, the activation energies are modified by the potential difference. (see, for example, ...). This method applies this correction.
Parameters
kf Vector of forward reaction rate constants on which to have the correction applied
Definition at line 562 of file InterfaceKinetics.cpp.
References Phase::charge(), DATA_PTR, Cantera::fp2str(), Cantera::GasConstant, ReactionStoichMgr::getReactionDelta(), Cantera::int2str(), InterfaceKinetics::m_ctrxn, InterfaceKinetics::m_E, InterfaceKinetics::m_phi, InterfaceKinetics::m_pot, InterfaceKinetics::m_rwork, InterfaceKinetics::m_rxnstoich, Kinetics::nPhases(), Phase::nSpecies(), Phase::temperature(), Kinetics::thermo(), and Cantera::writelog().
Referenced by InterfaceKinetics::_update_rates_T().
void applyExchangeCurrentDensityFormulation (doublereal *const kfwd) inherited
When an electrode reaction rate is optionally specified in terms of its exchange current density, extra vectors need to be precalculated.
Definition at line 618 of file InterfaceKinetics.cpp.
References Cantera::GasConstant, InterfaceKinetics::m_ctrxn, InterfaceKinetics::m_ctrxn_ecdf, Phase::temperature(), and Kinetics::thermo().
Referenced by InterfaceKinetics::_update_rates_T().
void setPhaseExistence (const size_t iphase, const bool exists) inherited
Set the existence of a phase in the reaction object.
Tell the kinetics object whether a phase in the object exists. This is actually an extrinsic specification that must be carried out on top of the intrinsic calculation of the reaction rate. The routine will also flip the IsStable boolean within the kinetics object as well.
Parameters
iphase Index of the phase. This is the order within the internal thermo vector object
exists Boolean indicating whether the phase exists or not
Definition at line 1427 of file InterfaceKinetics.cpp.
References InterfaceKinetics::m_phaseExists, InterfaceKinetics::m_phaseExistsCheck, InterfaceKinetics::m_phaseIsStable, and Kinetics::m_thermo.
void setPhaseStability (const int iphase, const int isStable) inherited
Set the stability of a phase in the reaction object.
Tell the kinetics object whether a phase in the object is stable. Species in an unstable phase will not be allowed to have a positive rate of formation from this kinetics object. This is actually an extrinsic specification that must be carried out on top of the intrinsic calculation of the reaction rate.
While conceptually not needed since kinetics is consistent with thermo when taken as a whole, in practice it has found to be very useful to turn off the creation of phases which shouldn't be forming. Typically this can reduce the oscillations in phase formation and destruction which are observed.
Parameters
iphase Index of the phase. This is the order within the internal thermo vector object
isStable Flag indicating whether the phase is stable or not
Definition at line 1480 of file InterfaceKinetics.cpp.
References InterfaceKinetics::m_phaseIsStable, and Kinetics::m_thermo.
int phaseExistence (const int iphase) const inherited
Gets the phase existence int for the ith phase.
Parameters
iphase Phase Id
Returns
Returns the int specifying whether the kinetics object thinks the phase exists or not. If it exists, then species in that phase can be a reactant in reactions.
Definition at line 1454 of file InterfaceKinetics.cpp.
References InterfaceKinetics::m_phaseExists, and Kinetics::m_thermo.
int phaseStability (const int iphase) const inherited
Gets the phase stability int for the ith phase.
Parameters
iphase Phase Id
Returns
Returns the int specifying whether the kinetics object thinks the phase is stable with nonzero mole numbers. If it stable, then the kinetics object will allow for rates of production of of species in that phase that are positive.
Definition at line 1471 of file InterfaceKinetics.cpp.
References InterfaceKinetics::m_phaseIsStable, and Kinetics::m_thermo.
void assignShallowPointers (const std::vector< thermo_t * > & tpVector) virtual inherited
Reassign the shallow pointers within the FKinetics object.
This type or routine is absolute necessary because the Kinetics object doesn't own the ThermoPhase objects. After a duplication, we need to point to different ThermoPhase objects.
We check that the ThermoPhase objects are aligned in the same order and have the following identical properties to the ones that they are replacing. id() eosType() nSpecies()
Parameters
tpVector Vector of shallow pointers to ThermoPhase objects. this is the m_thermo vector within this object
Definition at line 179 of file Kinetics.cpp.
References ThermoPhase::eosType(), Phase::id(), Kinetics::m_thermo, and Phase::nSpecies().
Referenced by EdgeKinetics::duplMyselfAsKinetics(), AqueousKinetics::duplMyselfAsKinetics(), GasKinetics::duplMyselfAsKinetics(), InterfaceKinetics::duplMyselfAsKinetics(), and Kinetics::duplMyselfAsKinetics().
size_t nReactions () const inline inherited
Number of reactions in the reaction mechanism.
Definition at line 209 of file Kinetics.h.
References Kinetics::m_ii.
Referenced by EdgeKinetics::finalize(), InterfaceKinetics::finalize(), InterfaceKinetics::getFwdRateConstants(), InterfaceKinetics::getRevRateConstants(), and InterfaceKinetics::updateKc().
void checkReactionIndex (size_t m) const inherited
Check that the specified reaction index is in range Throws an exception if i is greater than nReactions()
Definition at line 136 of file Kinetics.cpp.
References Kinetics::m_ii.
void checkReactionArraySize (size_t ii) const inherited
Check that an array size is at least nReactions() Throws an exception if ii is less than nReactions().
Used before calls which take an array pointer.
Definition at line 143 of file Kinetics.cpp.
References Kinetics::m_ii.
void checkSpeciesIndex (size_t k) const inherited
Check that the specified species index is in range Throws an exception if k is greater than nSpecies()-1.
Definition at line 164 of file Kinetics.cpp.
References Kinetics::m_kk.
void checkSpeciesArraySize (size_t mm) const inherited
Check that an array size is at least nSpecies() Throws an exception if kk is less than nSpecies().
Used before calls which take an array pointer.
Definition at line 171 of file Kinetics.cpp.
References Kinetics::m_kk.
size_t nPhases () const inline inherited
The number of phases participating in the reaction mechanism.
For a homogeneous reaction mechanism, this will always return 1, but for a heterogeneous mechanism it will return the total number of phases in the mechanism.
Definition at line 244 of file Kinetics.h.
References Kinetics::m_thermo.
Referenced by InterfaceKinetics::_update_rates_C(), InterfaceKinetics::_update_rates_phi(), Kinetics::addPhase(), InterfaceKinetics::addReaction(), InterfaceKinetics::applyButlerVolmerCorrection(), Kinetics::checkPhaseArraySize(), Kinetics::checkPhaseIndex(), Kinetics::finalize(), InterfaceKinetics::getDeltaElectrochemPotentials(), InterfaceKinetics::getDeltaEnthalpy(), InterfaceKinetics::getDeltaEntropy(), InterfaceKinetics::getDeltaGibbs(), InterfaceKinetics::getDeltaSSEnthalpy(), InterfaceKinetics::getDeltaSSEntropy(), InterfaceKinetics::getDeltaSSGibbs(), InterfaceKinetics::getEquilibriumConstants(), ImplicitSurfChem::ImplicitSurfChem(), InterfaceKinetics::init(), Kinetics::nTotalSpecies(), InterfaceKinetics::operator=(), solveProb::print_header(), Kinetics::selectPhase(), InterfaceKinetics::updateKc(), solveSP::updateMFKinSpecies(), and InterfaceKinetics::updateROP().
void checkPhaseIndex (size_t m) const inherited
Check that the specified phase index is in range Throws an exception if m is greater than nPhases()
Definition at line 150 of file Kinetics.cpp.
References Kinetics::nPhases().
void checkPhaseArraySize (size_t mm) const inherited
Check that an array size is at least nPhases() Throws an exception if mm is less than nPhases().
Used before calls which take an array pointer.
Definition at line 157 of file Kinetics.cpp.
References Kinetics::nPhases().
size_t phaseIndex (std::string ph) inline inherited
Return the phase index of a phase in the list of phases defined within the object.
Parameters
ph std::string name of the phase
If a -1 is returned, then the phase is not defined in the Kinetics object.
Definition at line 266 of file Kinetics.h.
References Kinetics::m_phaseindex, and Cantera::npos.
Referenced by Cantera::importKinetics().
size_t surfacePhaseIndex () inline inherited
This returns the integer index of the phase which has ThermoPhase type cSurf.
For heterogeneous mechanisms, this identifies the one surface phase. For homogeneous mechanisms, this returns -1.
Definition at line 280 of file Kinetics.h.
References Kinetics::m_surfphase.
Referenced by InterfaceKinetics::_update_rates_T(), solveSP::calc_t(), solveSP::fun_eval(), Cantera::getRateCoefficient(), solveProb::print_header(), and solveSP::solveSP().
size_t reactionPhaseIndex () inline inherited
Phase where the reactions occur.
For heterogeneous mechanisms, one of the phases in the list of phases represents the 2D interface or 1D edge at which the reactions take place. This method returns the index of the phase with the smallest spatial dimension (1, 2, or 3) among the list of phases. If there is more than one, the index of the first one is returned. For homogeneous mechanisms, the value 0 is returned.
Definition at line 294 of file Kinetics.h.
References Kinetics::m_rxnphase.
Referenced by EdgeKinetics::finalize(), and InterfaceKinetics::finalize().
thermo_t& thermo (size_t n = 0) inline inherited
This method returns a reference to the nth ThermoPhase object defined in this kinetics mechanism.
It is typically used so that member functions of the ThermoPhase object may be called. For homogeneous mechanisms, there is only one object, and this method can be called without an argument to access it.
Parameters
n Index of the ThermoPhase being sought.
Definition at line 309 of file Kinetics.h.
References Kinetics::m_thermo.
Referenced by AqueousKinetics::_update_rates_C(), InterfaceKinetics::_update_rates_C(), InterfaceKinetics::_update_rates_phi(), InterfaceKinetics::_update_rates_T(), InterfaceKinetics::applyButlerVolmerCorrection(), InterfaceKinetics::applyExchangeCurrentDensityFormulation(), solveSP::calc_t(), EdgeKinetics::finalize(), InterfaceKinetics::finalize(), InterfaceKinetics::getDeltaElectrochemPotentials(), AqueousKinetics::getDeltaEnthalpy(), GasKinetics::getDeltaEnthalpy(), InterfaceKinetics::getDeltaEnthalpy(), AqueousKinetics::getDeltaEntropy(), GasKinetics::getDeltaEntropy(), InterfaceKinetics::getDeltaEntropy(), AqueousKinetics::getDeltaGibbs(), GasKinetics::getDeltaGibbs(), InterfaceKinetics::getDeltaGibbs(), AqueousKinetics::getDeltaSSEnthalpy(), GasKinetics::getDeltaSSEnthalpy(), InterfaceKinetics::getDeltaSSEnthalpy(), AqueousKinetics::getDeltaSSEntropy(), GasKinetics::getDeltaSSEntropy(), InterfaceKinetics::getDeltaSSEntropy(), AqueousKinetics::getDeltaSSGibbs(), GasKinetics::getDeltaSSGibbs(), InterfaceKinetics::getDeltaSSGibbs(), Cantera::getEfficiencies(), AqueousKinetics::getEquilibriumConstants(), GasKinetics::getEquilibriumConstants(), InterfaceKinetics::getEquilibriumConstants(), Cantera::getRateCoefficient(), Cantera::getStick(), ImplicitSurfChem::ImplicitSurfChem(), AqueousKinetics::init(), GasKinetics::init(), InterfaceKinetics::init(), ConstPressureReactor::initialize(), Reactor::initialize(), Kinetics::kineticsSpeciesIndex(), Kinetics::kineticsSpeciesName(), Kinetics::nTotalSpecies(), solveProb::print_header(), InterfaceKinetics::setElectricPotential(), ImplicitSurfChem::solvePseudoSteadyStateProblem(), solveSP::solveSP(), Kinetics::speciesPhase(), AqueousKinetics::updateKc(), GasKinetics::updateKc(), InterfaceKinetics::updateKc(), and solveSP::updateMFKinSpecies().
thermo_t& phase (size_t n = 0) inline inherited
This method returns a reference to the nth ThermoPhase defined in this kinetics mechanism.
It is typically used so that member functions of the ThermoPhase may be called.
Deprecated:
This method is redundant.
Parameters
n Index of the ThermoPhase being sought.
Definition at line 324 of file Kinetics.h.
References Cantera::deprecatedMethod(), and Kinetics::m_thermo.
const thermo_t& phase (size_t n = 0) const inline inherited
This method returns a reference to the nth ThermoPhase defined in this kinetics mechanism.
It is typically used so that member functions of the ThermoPhase may be called.
Deprecated:
This method is redundant.
Parameters
n Index of the ThermoPhase being sought.
Definition at line 336 of file Kinetics.h.
References Cantera::deprecatedMethod(), and Kinetics::m_thermo.
size_t nTotalSpecies () const inline inherited
The total number of species in all phases participating in the kinetics mechanism.
This is useful to dimension arrays for use in calls to methods that return the species production rates, for example.
Definition at line 347 of file Kinetics.h.
References Kinetics::nPhases(), Phase::nSpecies(), and Kinetics::thermo().
Referenced by ReactingSurf1D::init(), and rxninfo::installReaction().
size_t start (size_t n) inline inherited
Returns the starting index of the species in the nth phase associated with the reaction mechanism.
Parameters
n Return the index of first species in the nth phase associated with the reaction mechanism.
Definition at line 363 of file Kinetics.h.
References Cantera::deprecatedMethod(), and Kinetics::m_start.
size_t kineticsSpeciesIndex (size_t k, size_t n) const inline inherited
The location of species k of phase n in species arrays.
Kinetics manager classes return species production rates in flat arrays, with the species of each phases following one another, in the order the phases were added. This method is useful to find the value for a particular species of a particular phase in arrays returned from methods like getCreationRates that return an array of species-specific quantities.
Example: suppose a heterogeneous mechanism involves three phases. The first contains 12 species, the second 26, and the third 3. Then species arrays must have size at least 41, and positions 0 - 11 are the values for the species in the first phase, positions 12 - 37 are the values for the species in the second phase, etc. Then kineticsSpeciesIndex(7, 0) = 7, kineticsSpeciesIndex(4, 1) = 16, and kineticsSpeciesIndex(2, 2) = 40.
Parameters
k species index
n phase index for the species
Definition at line 391 of file Kinetics.h.
References Kinetics::m_start.
Referenced by solveSP::calc_t(), Cantera::checkRxnElementBalance(), ReactingSurf1D::eval(), solveSP::fun_eval(), Cantera::getEfficiencies(), Cantera::getReagents(), Cantera::getStick(), Kinetics::kineticsSpeciesIndex(), solveSP::solveSP(), and solveSP::updateMFKinSpecies().
size_t kineticsSpeciesIndex (const std::string & nm) const inherited
This routine will look up a species number based on the input std::string nm.
The lookup of species will occur for all phases listed in the kinetics object.
return
If a match is found, the position in the species list is returned.
If no match is found, the value -1 is returned.
Parameters
nm Input string name of the species
Definition at line 263 of file Kinetics.cpp.
References Phase::id(), Kinetics::m_start, Kinetics::m_thermo, Cantera::npos, Phase::speciesIndex(), and Kinetics::thermo().
size_t kineticsSpeciesIndex (const std::string & nm, const std::string & ph) const inherited
This routine will look up a species number based on the input std::string nm.
The lookup of species will occur in the specified phase of the object, or all phases if ph is "<any>".
return
If a match is found, the position in the species list is returned.
If no match is found, the value npos (-1) is returned.
Parameters
nm Input string name of the species
ph Input string name of the phase.
Definition at line 288 of file Kinetics.cpp.
References Phase::id(), Kinetics::kineticsSpeciesIndex(), Kinetics::m_start, Kinetics::m_thermo, Cantera::npos, Phase::speciesIndex(), and Kinetics::thermo().
string kineticsSpeciesName (size_t k) const inherited
Return the std::string name of the kth species in the kinetics manager.
kineticsSpeciesName():
k is an integer from 0 to ktot - 1, where ktot is the number of species in the kinetics manager, which is the sum of the number of species in all phases participating in the kinetics manager. If k is out of bounds, the std::string "<unknown>" is returned.
Parameters
k species index
Return the string name of the kth species in the kinetics manager. k is an integer from 0 to ktot - 1, where ktot is the number of species in the kinetics manager, which is the sum of the number of species in all phases participating in the kinetics manager. If k is out of bounds, the string "<unknown>" is returned.
Definition at line 242 of file Kinetics.cpp.
References Kinetics::m_start, Cantera::npos, Phase::speciesName(), and Kinetics::thermo().
Referenced by Cantera::getStick(), solveSP::printFinal(), solveProb::printIteration(), and solveSP::printIteration().
thermo_t & speciesPhase (std::string nm) inherited
This function looks up the std::string name of a species and returns a reference to the ThermoPhase object of the phase where the species resides.
This function looks up the string name of a species and returns a reference to the ThermoPhase object of the phase where the species resides.
Will throw an error if the species std::string doesn't match.
Parameters
nm String containing the name of the species.
Will throw an error if the species string doesn't match.
Definition at line 315 of file Kinetics.cpp.
References Kinetics::m_thermo, Cantera::npos, Phase::speciesIndex(), and Kinetics::thermo().
Referenced by Cantera::checkRxnElementBalance(), Cantera::getStick(), and rxninfo::installReaction().
thermo_t& speciesPhase (size_t k) inline inherited
This function takes as an argument the kineticsSpecies index (i.e., the list index in the list of species in the kinetics manager) and returns the species' owning ThermoPhase object.
Parameters
k Species index
Definition at line 454 of file Kinetics.h.
References Kinetics::speciesPhaseIndex(), and Kinetics::thermo().
size_t speciesPhaseIndex (size_t k) inherited
This function takes as an argument the kineticsSpecies index (i.e., the list index in the list of species in the kinetics manager) and returns the index of the phase owning the species.
Parameters
k Species index
Definition at line 337 of file Kinetics.cpp.
References Cantera::int2str(), Kinetics::m_start, and Cantera::npos.
Referenced by InterfaceKinetics::addReaction(), Cantera::checkRxnElementBalance(), Cantera::getStick(), and Kinetics::speciesPhase().
virtual void getReactionDelta (const doublereal * property, doublereal * deltaProperty) inline virtual inherited
Change in species properties.
Given an array of molar species property values \(z_k, k = 1, \dots, K \), return the array of reaction values
\[ \Delta Z_i = \sum_k \nu_{k,i} z_k, i = 1, \dots, I. \]
For example, if this method is called with the array of standard-state molar Gibbs free energies for the species, then the values returned in array deltaProperty would be the standard-state Gibbs free energies of reaction for each reaction.
Parameters
property Input vector of property value. Length: m_kk.
deltaProperty Output vector of deltaRxn. Length: m_ii.
Definition at line 547 of file Kinetics.h.
References Kinetics::err().
virtual doublereal reactantOrder (size_t k, size_t i) const inline virtual inherited
Reactant order of species k in reaction i.
This is the nominal order of the activity concentration in determining the forward rate of progress of the reaction
Parameters
k kinetic species index
i reaction index
Definition at line 735 of file Kinetics.h.
References Kinetics::err().
virtual doublereal productOrder (int k, int i) const inline virtual inherited
product Order of species k in reaction i.
This is the nominal order of the activity concentration of species k in determining the reverse rate of progress of the reaction i
For irreversible reactions, this will all be zero.
Parameters
k kinetic species index
i reaction index
Definition at line 750 of file Kinetics.h.
References Kinetics::err().
virtual const std::vector<size_t>& reactants (size_t i) const inline virtual inherited
Returns a read-only reference to the vector of reactant index numbers for reaction i.
Parameters
i reaction index
Definition at line 770 of file Kinetics.h.
References Kinetics::m_reactants.
Referenced by InterfaceKinetics::addReaction(), and rxninfo::installReaction().
virtual const std::vector<size_t>& products (size_t i) const inline virtual inherited
Returns a read-only reference to the vector of product index numbers for reaction i.
Parameters
i reaction index
Definition at line 780 of file Kinetics.h.
References Kinetics::m_products.
Referenced by InterfaceKinetics::addReaction(), and rxninfo::installReaction().
doublereal multiplier (size_t i) const inline inherited
The current value of the multiplier for reaction i.
Parameters
i index of the reaction
Definition at line 953 of file Kinetics.h.
References Kinetics::m_perturb.
void setMultiplier (size_t i, doublereal f) inline inherited
Set the multiplier for reaction i to f.
Parameters
i index of the reaction
f value of the multiplier.
Definition at line 962 of file Kinetics.h.
References Kinetics::m_perturb.
void incrementRxnCount () inline inherited
Increment the number of reactions in the mechanism by one.
Todo:
Should be protected?
Definition at line 972 of file Kinetics.h.
References Kinetics::m_ii, and Kinetics::m_perturb.
Referenced by AqueousKinetics::addReaction(), GasKinetics::addReaction(), and InterfaceKinetics::addReaction().
void selectPhase (const doublereal * data, const thermo_t * phase, doublereal * phase_data) inherited
Extract from array data the portion pertaining to phase phase.
Takes as input an array of properties for all species in the mechanism and copies those values beloning to a particular phase to the output array.
Parameters
data data
phase phase
phase_data phase_data
data Input data array.
phase Pointer to one of the phase objects participating in this reaction mechanism
phase_data Output array where the values for the the specified phase are to be written.
Definition at line 217 of file Kinetics.cpp.
References Kinetics::m_start, Kinetics::m_thermo, Kinetics::nPhases(), and Phase::nSpecies().
Member Data Documentation
vector_fp m_grt protected inherited
Temporary work vector of length m_kk.
Definition at line 647 of file InterfaceKinetics.h.
Referenced by InterfaceKinetics::getDeltaElectrochemPotentials(), InterfaceKinetics::getDeltaEnthalpy(), InterfaceKinetics::getDeltaEntropy(), InterfaceKinetics::getDeltaGibbs(), InterfaceKinetics::getDeltaSSEnthalpy(), InterfaceKinetics::getDeltaSSEntropy(), InterfaceKinetics::getDeltaSSGibbs(), InterfaceKinetics::init(), and InterfaceKinetics::operator=().
std::vector<size_t> m_revindex protected inherited
List of reactions numbers which are reversible reactions.
This is a vector of reaction numbers. Each reaction in the list is reversible. Length = number of reversible reactions
Definition at line 655 of file InterfaceKinetics.h.
Referenced by InterfaceKinetics::isReversible(), InterfaceKinetics::operator=(), and InterfaceKinetics::updateKc().
Rate1<SurfaceArrhenius> m_rates protected inherited
Templated class containing the vector of reactions for this interface.
The templated class is described in RateCoeffMgr.h The class SurfaceArrhenius is described in RxnRates.h
Definition at line 662 of file InterfaceKinetics.h.
Referenced by InterfaceKinetics::_update_rates_T(), and InterfaceKinetics::operator=().
std::map<size_t, std::pair<int, size_t> > m_index mutable protected inherited
Vector of information about reactions in the mechanism.
The key is the reaction index (0 < i < m_ii). The first pair is the reactionType of the reaction. The second pair is ...
Definition at line 673 of file InterfaceKinetics.h.
Referenced by InterfaceKinetics::operator=(), InterfaceKinetics::reactionType(), and InterfaceKinetics::registerReaction().
std::vector<size_t> m_irrev protected inherited
Vector of irreversible reaction numbers.
vector containing the reaction numbers of irreversible reactions.
Definition at line 680 of file InterfaceKinetics.h.
Referenced by InterfaceKinetics::operator=(), and InterfaceKinetics::updateKc().
ReactionStoichMgr m_rxnstoich protected inherited
Stoichiometric manager for the reaction mechanism.
This is the manager for the kinetics mechanism that handles turning reaction extents into species production rates and also handles turning thermo properties into reaction thermo properties.
Definition at line 689 of file InterfaceKinetics.h.
Referenced by InterfaceKinetics::applyButlerVolmerCorrection(), InterfaceKinetics::getCreationRates(), InterfaceKinetics::getDeltaElectrochemPotentials(), InterfaceKinetics::getDeltaEnthalpy(), InterfaceKinetics::getDeltaEntropy(), InterfaceKinetics::getDeltaGibbs(), InterfaceKinetics::getDeltaSSEnthalpy(), InterfaceKinetics::getDeltaSSEntropy(), InterfaceKinetics::getDeltaSSGibbs(), InterfaceKinetics::getDestructionRates(), InterfaceKinetics::getEquilibriumConstants(), InterfaceKinetics::getNetProductionRates(), InterfaceKinetics::operator=(), InterfaceKinetics::updateKc(), and InterfaceKinetics::updateROP().
size_t m_nirrev protected inherited
Number of irreversible reactions in the mechanism.
Definition at line 692 of file InterfaceKinetics.h.
Referenced by InterfaceKinetics::operator=(), and InterfaceKinetics::updateKc().
size_t m_nrev protected inherited
Number of reversible reactions in the mechanism.
Definition at line 695 of file InterfaceKinetics.h.
Referenced by InterfaceKinetics::operator=(), and InterfaceKinetics::updateKc().
std::vector<std::map<size_t, doublereal> > m_rrxn mutable protected inherited
m_rrxn is a vector of maps, containing the reactant stoichiometric coefficient information
m_rrxn has a length equal to the total number of species in the kinetics object. For each species, there exists a map, with the reaction number being the key, and the reactant stoichiometric coefficient for the species being the value. HKM -> mutable because search sometimes creates extra entries. To be fixed in future...
Definition at line 709 of file InterfaceKinetics.h.
Referenced by InterfaceKinetics::init(), InterfaceKinetics::operator=(), and InterfaceKinetics::reactantStoichCoeff().
std::vector<std::map<size_t, doublereal> > m_prxn mutable protected inherited
m_prxn is a vector of maps, containing the reactant stoichiometric coefficient information
m_prxn is a vector of maps. m_prxn has a length equal to the total number of species in the kinetics object. For each species, there exists a map, with the reaction number being the key, and the product stoichiometric coefficient for the species being the value.
Definition at line 720 of file InterfaceKinetics.h.
Referenced by InterfaceKinetics::init(), InterfaceKinetics::operator=(), and InterfaceKinetics::productStoichCoeff().
std::vector<std::string> m_rxneqn protected inherited
String expression for each rxn.
Vector of strings of length m_ii, the number of reactions, containing the string expressions for each reaction (e.g., reactants <=> product1 + product2)
Definition at line 729 of file InterfaceKinetics.h.
Referenced by InterfaceKinetics::addReaction(), InterfaceKinetics::operator=(), and InterfaceKinetics::reactionString().
InterfaceKineticsData* m_kdata protected inherited
Temporary data storage used in calculating the rates of of reactions.
Definition at line 735 of file InterfaceKinetics.h.
Referenced by InterfaceKinetics::_update_rates_C(), InterfaceKinetics::_update_rates_T(), InterfaceKinetics::getCreationRates(), InterfaceKinetics::getDestructionRates(), InterfaceKinetics::getFwdRateConstants(), InterfaceKinetics::getFwdRatesOfProgress(), InterfaceKinetics::getNetProductionRates(), InterfaceKinetics::getNetRatesOfProgress(), InterfaceKinetics::getRevRateConstants(), InterfaceKinetics::getRevRatesOfProgress(), InterfaceKinetics::InterfaceKinetics(), InterfaceKinetics::operator=(), InterfaceKinetics::updateKc(), InterfaceKinetics::updateROP(), and InterfaceKinetics::~InterfaceKinetics().
vector_fp m_conc protected inherited
an array of generalized concentrations for each species
An array of generalized concentrations \(C_k \) that are defined such that \(a_k = C_k / C^0_k, \) where \(C^0_k \) is a standard concentration/ These generalized concentrations are used by this kinetics manager class to compute the forward and reverse rates of elementary reactions. The "units" for the concentrations of each phase depend upon the implementation of kinetics within that phase. The order of the species within the vector is based on the order of listed ThermoPhase objects in the class, and the order of the species within each ThermoPhase class.
Definition at line 751 of file InterfaceKinetics.h.
Referenced by InterfaceKinetics::_update_rates_C(), InterfaceKinetics::_update_rates_T(), InterfaceKinetics::getActivityConcentrations(), InterfaceKinetics::init(), InterfaceKinetics::operator=(), and InterfaceKinetics::updateROP().
vector_fp m_mu0 protected inherited
Vector of standard state chemical potentials.
This vector contains a temporary vector of standard state chemical potentials for all of the species in the kinetics object
Length = m_k units = J/kmol
Definition at line 762 of file InterfaceKinetics.h.
Referenced by InterfaceKinetics::getEquilibriumConstants(), InterfaceKinetics::init(), InterfaceKinetics::operator=(), and InterfaceKinetics::updateKc().
vector_fp m_phi protected inherited
Vector of phase electric potentials.
Temporary vector containing the potential of each phase in the kinetics object
length = number of phases units = Volts
Definition at line 772 of file InterfaceKinetics.h.
Referenced by InterfaceKinetics::_update_rates_phi(), InterfaceKinetics::applyButlerVolmerCorrection(), InterfaceKinetics::getEquilibriumConstants(), InterfaceKinetics::init(), InterfaceKinetics::operator=(), and InterfaceKinetics::updateKc().
vector_fp m_pot protected inherited
Vector of potential energies due to Voltages.
Length is the number of species in kinetics mech. It's used to store the potential energy due to the voltage.
Definition at line 779 of file InterfaceKinetics.h.
Referenced by InterfaceKinetics::applyButlerVolmerCorrection(), InterfaceKinetics::init(), and InterfaceKinetics::operator=().
vector_fp m_rwork protected inherited
Vector temporary.
Length is number of reactions. It's used to store the voltage contribution to the activation energy.
Definition at line 786 of file InterfaceKinetics.h.
Referenced by InterfaceKinetics::applyButlerVolmerCorrection(), EdgeKinetics::finalize(), InterfaceKinetics::finalize(), and InterfaceKinetics::operator=().
vector_fp m_E protected inherited
Vector of raw activation energies for the reactions.
units are in Kelvin Length is number of reactions.
Definition at line 793 of file InterfaceKinetics.h.
Referenced by InterfaceKinetics::applyButlerVolmerCorrection(), InterfaceKinetics::getActivationEnergies(), and InterfaceKinetics::operator=().
SurfPhase* m_surf protected inherited
Pointer to the single surface phase.
Definition at line 796 of file InterfaceKinetics.h.
Referenced by InterfaceKinetics::_update_rates_T(), EdgeKinetics::finalize(), InterfaceKinetics::finalize(), and InterfaceKinetics::operator=().
ImplicitSurfChem* m_integrator protected inherited
Pointer to the Implicit surface chemistry object.
Note this object is owned by this InterfaceKinetics object. It may only be used to solve this single InterfaceKinetics objects's surface problem uncoupled from other surface phases.
Definition at line 805 of file InterfaceKinetics.h.
Referenced by InterfaceKinetics::advanceCoverages(), InterfaceKinetics::operator=(), InterfaceKinetics::solvePseudoSteadyStateProblem(), and InterfaceKinetics::~InterfaceKinetics().
std::vector<size_t> m_ctrxn protected inherited
Vector of reaction indexes specifying the id of the current transfer reactions in the mechanism.
Vector of reaction indices which involve current transfers. This provides an index into the m_beta array.
  irxn = m_ctrxn[i]
Definition at line 817 of file InterfaceKinetics.h.
Referenced by InterfaceKinetics::applyButlerVolmerCorrection(), InterfaceKinetics::applyExchangeCurrentDensityFormulation(), InterfaceKinetics::electrochem_beta(), and InterfaceKinetics::operator=().
vector_int m_ctrxn_ecdf protected inherited
Vector of booleans indicating whether the charge transfer reaction may be described by an exchange current density expression.
Definition at line 821 of file InterfaceKinetics.h.
Referenced by InterfaceKinetics::applyExchangeCurrentDensityFormulation(), and InterfaceKinetics::operator=().
bool m_finalized protected inherited
boolean indicating whether mechanism has been finalized
Definition at line 830 of file InterfaceKinetics.h.
Referenced by EdgeKinetics::finalize(), InterfaceKinetics::finalize(), InterfaceKinetics::operator=(), and InterfaceKinetics::ready().
bool m_has_coverage_dependence protected inherited
Boolean flag indicating whether any reaction in the mechanism has a coverage dependent forward reaction rate.
If this is true, then the coverage dependence is multiplied into the forward reaction rates constant
Definition at line 838 of file InterfaceKinetics.h.
Referenced by InterfaceKinetics::_update_rates_T(), and InterfaceKinetics::operator=().
bool m_has_electrochem_rxns protected inherited
Boolean flag indicating whether any reaction in the mechanism has a beta electrochemical parameter.
If this is true, the Butler-Volmer correction is applied to the forward reaction rate for those reactions.
fac = exp (- beta * (delta_phi))
Definition at line 848 of file InterfaceKinetics.h.
Referenced by InterfaceKinetics::_update_rates_T(), and InterfaceKinetics::operator=().
bool m_has_exchange_current_density_formulation protected inherited
Boolean flag indicating whether any reaction in the mechanism is described by an exchange current density expression.
If this is true, the standard state gibbs free energy of the reaction and the product of the reactant standard concentrations must be precalculated in order to calculate the rate constant.
Definition at line 857 of file InterfaceKinetics.h.
Referenced by InterfaceKinetics::_update_rates_T(), and InterfaceKinetics::operator=().
int m_phaseExistsCheck protected inherited
Int flag to indicate that some phases in the kinetics mechanism are non-existent.
We change the ROP vectors to make sure that non-existent phases are treated correctly in the kinetics operator. The value of this is equal to the number of phases which don't exist.
Definition at line 866 of file InterfaceKinetics.h.
Referenced by InterfaceKinetics::operator=(), InterfaceKinetics::setPhaseExistence(), and InterfaceKinetics::updateROP().
std::vector<bool> m_phaseExists protected inherited
Vector of booleans indicating whether phases exist or not.
Vector of booleans indicating whether a phase exists or not. We use this to set the ROP's so that unphysical things don't happen
length = number of phases in the object By default all phases exist.
Definition at line 876 of file InterfaceKinetics.h.
Referenced by InterfaceKinetics::addPhase(), InterfaceKinetics::finalize(), InterfaceKinetics::operator=(), InterfaceKinetics::phaseExistence(), InterfaceKinetics::setPhaseExistence(), and InterfaceKinetics::updateROP().
std::vector<int> m_phaseIsStable protected inherited
Vector of int indicating whether phases are stable or not.
Vector of booleans indicating whether a phase is stable or not under the current conditions. We use this to set the ROP's so that unphysical things don't happen
length = number of phases in the object By default all phases are stable
Definition at line 887 of file InterfaceKinetics.h.
Referenced by InterfaceKinetics::addPhase(), InterfaceKinetics::operator=(), InterfaceKinetics::phaseStability(), InterfaceKinetics::setPhaseExistence(), InterfaceKinetics::setPhaseStability(), and InterfaceKinetics::updateROP().
std::vector<bool*> m_rxnPhaseIsReactant protected inherited
Vector of vector of booleans indicating whether a phase participates in a reaction as a reactant.
m_rxnPhaseIsReactant[j][p] indicates whether a species in phase p participates in reaction j as a reactant.
Definition at line 895 of file InterfaceKinetics.h.
Referenced by InterfaceKinetics::addReaction(), InterfaceKinetics::operator=(), InterfaceKinetics::updateROP(), and InterfaceKinetics::~InterfaceKinetics().
std::vector<bool*> m_rxnPhaseIsProduct protected inherited
Vector of vector of booleans indicating whether a phase participates in a reaction as a product.
m_rxnPhaseIsReactant[j][p] indicates whether a species in phase p participates in reaction j as a product.
Definition at line 903 of file InterfaceKinetics.h.
Referenced by InterfaceKinetics::addReaction(), InterfaceKinetics::operator=(), InterfaceKinetics::updateROP(), and InterfaceKinetics::~InterfaceKinetics().
std::vector<int> m_phaseIsIntermediate protected inherited
Vector of ints indicating whether zeroed phase is an intermediate for the formation of another phase.
If a phase is zeroed out but it is an intermediate, then the phase can be formed whether it is stable or not, but the destruction rate of species in that phase can't exceed the formation rate for species in that phase.
length = number of phases in the object By default all phases are not intermediates
Definition at line 917 of file InterfaceKinetics.h.
std::vector<doublereal> m_rxnRateFactorPhaseIntermediates protected inherited
Reaction rate reduction factor for intermediates.
Individual reaction rates are reduced to accommodate the requirements of intermediate zero phases.
length = number of reactions in the object By default all phases are not intermediates
Definition at line 928 of file InterfaceKinetics.h.
std::vector<doublereal> m_speciesTmpP protected inherited
Work vector having length number of species.
Definition at line 931 of file InterfaceKinetics.h.
size_t m_ii protected inherited
Number of reactions in the mechanism.
Definition at line 1000 of file Kinetics.h.
Referenced by Kinetics::checkReactionArraySize(), Kinetics::checkReactionIndex(), AqueousKinetics::finalize(), GasKinetics::finalize(), AqueousKinetics::getDeltaEnthalpy(), GasKinetics::getDeltaEnthalpy(), AqueousKinetics::getDeltaEntropy(), GasKinetics::getDeltaEntropy(), AqueousKinetics::getDeltaGibbs(), GasKinetics::getDeltaGibbs(), AqueousKinetics::getDeltaSSEnthalpy(), GasKinetics::getDeltaSSEnthalpy(), AqueousKinetics::getDeltaSSEntropy(), GasKinetics::getDeltaSSEntropy(), AqueousKinetics::getDeltaSSGibbs(), GasKinetics::getDeltaSSGibbs(), AqueousKinetics::getEquilibriumConstants(), GasKinetics::getEquilibriumConstants(), InterfaceKinetics::getEquilibriumConstants(), AqueousKinetics::getFwdRateConstants(), GasKinetics::getFwdRateConstants(), AqueousKinetics::getRevRateConstants(), GasKinetics::getRevRateConstants(), InterfaceKinetics::getRevRateConstants(), Kinetics::incrementRxnCount(), Kinetics::nReactions(), InterfaceKinetics::operator=(), Kinetics::operator=(), AqueousKinetics::updateKc(), GasKinetics::updateKc(), InterfaceKinetics::updateKc(), InterfaceKinetics::updateROP(), and InterfaceKinetics::~InterfaceKinetics().
size_t m_kk protected inherited
The number of species in all of the phases that participate in this kinetics mechanism.
Definition at line 1004 of file Kinetics.h.
Referenced by Kinetics::checkSpeciesArraySize(), Kinetics::checkSpeciesIndex(), InterfaceKinetics::finalize(), Kinetics::finalize(), AqueousKinetics::getCreationRates(), GasKinetics::getCreationRates(), InterfaceKinetics::getCreationRates(), AqueousKinetics::getDeltaSSEnthalpy(), GasKinetics::getDeltaSSEnthalpy(), InterfaceKinetics::getDeltaSSEnthalpy(), AqueousKinetics::getDeltaSSEntropy(), GasKinetics::getDeltaSSEntropy(), InterfaceKinetics::getDeltaSSEntropy(), AqueousKinetics::getDestructionRates(), GasKinetics::getDestructionRates(), InterfaceKinetics::getDestructionRates(), AqueousKinetics::getNetProductionRates(), GasKinetics::getNetProductionRates(), InterfaceKinetics::getNetProductionRates(), AqueousKinetics::init(), GasKinetics::init(), InterfaceKinetics::init(), and Kinetics::operator=().
vector_fp m_perturb protected inherited
Vector of perturbation factors for each reaction's rate of progress vector.
It is initialized to one.
Definition at line 1009 of file Kinetics.h.
Referenced by EdgeKinetics::finalize(), AqueousKinetics::finalize(), GasKinetics::finalize(), InterfaceKinetics::finalize(), AqueousKinetics::getFwdRateConstants(), GasKinetics::getFwdRateConstants(), InterfaceKinetics::getFwdRateConstants(), Kinetics::incrementRxnCount(), Kinetics::multiplier(), Kinetics::operator=(), Kinetics::setMultiplier(), and InterfaceKinetics::updateROP().
std::vector<std::vector<size_t> > m_reactants protected inherited
This is a vector of vectors containing the reactants for each reaction.
The outer vector is over the number of reactions, m_ii. The inner vector is a list of species indices. If the stoichiometric coefficient for a reactant is greater than one, then the reactant is listed contiguously in the vector a number of times equal to its stoichiometric coefficient. NOTE: These vectors will be wrong if there are real stoichiometric coefficients in the expression.
Definition at line 1022 of file Kinetics.h.
Referenced by Kinetics::operator=(), and Kinetics::reactants().
std::vector<std::vector<size_t> > m_products protected inherited
This is a vector of vectors containing the products for each reaction.
The outer vector is over the number of reactions, m_ii. The inner vector is a list of species indices. If the stoichiometric coefficient for a product is greater than one, then the reactant is listed contiguously in the vector a number of times equal to its stoichiometric coefficient. NOTE: These vectors will be wrong if there are real stoichiometric coefficients in the expression.
Definition at line 1035 of file Kinetics.h.
Referenced by Kinetics::operator=(), and Kinetics::products().
std::vector<thermo_t*> m_thermo protected inherited
m_thermo is a vector of pointers to ThermoPhase objects that are involved with this kinetics operator
For homogeneous kinetics applications, this vector will only have one entry. For interfacial reactions, this vector will consist of multiple entries; some of them will be surface phases, and the other ones will be bulk phases. The order that the objects are listed determines the order in which the species comprising each phase are listed in the source term vector, originating from the reaction mechanism.
Note that this kinetics object doesn't own these ThermoPhase objects and is not responsible for creating or deleting them.
Definition at line 1052 of file Kinetics.h.
Referenced by Kinetics::addPhase(), Kinetics::assignShallowPointers(), InterfaceKinetics::finalize(), Kinetics::finalize(), GRI_30_Kinetics::gri30_updateKc(), Kinetics::kineticsSpeciesIndex(), Kinetics::nPhases(), Kinetics::operator=(), Kinetics::phase(), InterfaceKinetics::phaseExistence(), InterfaceKinetics::phaseStability(), Kinetics::selectPhase(), InterfaceKinetics::setPhaseExistence(), InterfaceKinetics::setPhaseStability(), Kinetics::speciesPhase(), and Kinetics::thermo().
std::vector<size_t> m_start protected inherited
m_start is a vector of integers specifying the beginning position for the species vector for the n'th phase in the kinetics class.
Definition at line 1059 of file Kinetics.h.
Referenced by InterfaceKinetics::_update_rates_C(), Kinetics::addPhase(), InterfaceKinetics::getDeltaElectrochemPotentials(), InterfaceKinetics::getDeltaEnthalpy(), InterfaceKinetics::getDeltaEntropy(), InterfaceKinetics::getDeltaGibbs(), InterfaceKinetics::getDeltaSSEnthalpy(), InterfaceKinetics::getDeltaSSEntropy(), InterfaceKinetics::getDeltaSSGibbs(), InterfaceKinetics::getEquilibriumConstants(), Kinetics::kineticsSpeciesIndex(), Kinetics::kineticsSpeciesName(), Kinetics::operator=(), Kinetics::selectPhase(), Kinetics::speciesPhaseIndex(), Kinetics::start(), and InterfaceKinetics::updateKc().
std::map<std::string, size_t> m_phaseindex protected inherited
Mapping of the phase id, i.e., the id attribute in the xml phase element to the position of the phase within the kinetics object.
Positions start with the value of 1. The member function, phaseIndex() decrements by one before returning the index value, so that missing phases return -1.
Definition at line 1069 of file Kinetics.h.
Referenced by Kinetics::addPhase(), Kinetics::operator=(), and Kinetics::phaseIndex().
size_t m_surfphase protected inherited
Index in the list of phases of the one surface phase.
Definition at line 1075 of file Kinetics.h.
Referenced by Kinetics::addPhase(), Kinetics::operator=(), and Kinetics::surfacePhaseIndex().
size_t m_rxnphase protected inherited
Phase Index where reactions are assumed to be taking place.
We calculate this by assuming that the phase with the lowest dimensionality is the phase where reactions are taking place
Deprecated:
Definition at line 1083 of file Kinetics.h.
Referenced by Kinetics::addPhase(), Kinetics::operator=(), and Kinetics::reactionPhaseIndex().
size_t m_mindim protected inherited
number of spatial dimensions of lowest-dimensional phase.
Definition at line 1086 of file Kinetics.h.
Referenced by Kinetics::addPhase(), and Kinetics::operator=().
The documentation for this class was generated from the following files:
EdgeKinetics.h
InterfaceKinetics.cpp