Cantera: Fourier1 Class Reference
Fourier1 Class Reference
Fourier cosine/sine series.
#include <Func1.h>
Public Member Functions
Fourier1 (size_t n, doublereal omega, doublereal a0, doublereal *a, doublereal *b)
Fourier1 (const Fourier1 &b)
Fourier1 & operator= (const Fourier1 &right)
virtual Func1 & duplicate () const
Duplicate the current function.
virtual doublereal eval (doublereal t) const
Evaluate the function.
virtual int ID () const
doublereal operator() (doublereal t) const
Calls method eval to evaluate the function.
virtual Func1 & derivative () const
Creates a derivative to the current function.
bool isIdentical (Func1 &other) const
Routine to determine if two functions are the same.
virtual doublereal isProportional (TimesConstant1 &other)
virtual doublereal isProportional (Func1 &other)
virtual std::string write (std::string arg) const
doublereal c () const
accessor function for the stored constant
void setC (doublereal c)
Function to set the stored constant.
Func1 & func1 () const
accessor function for m_f1
Func1 & func2 () const
accessor function for m_f2
virtual int order () const
Return the order of the function, if it makes sense.
Func1 & func1_dup () const
Func1 & func2_dup () const
Func1 * parent () const
void setParent (Func1 *p)
Protected Attributes
size_t m_n
doublereal m_omega
doublereal m_a0_2
vector_fp m_ccos
vector_fp m_csin
doublereal m_c
Func1 * m_f1
Func1 * m_f2
Func1 * m_parent
Detailed Description
Fourier cosine/sine series.
\[ f(t) = \frac{A_0}{2} + \sum_{n=1}^N A_n \cos (n \omega t) + B_n \sin (n \omega t) \]
Definition at line 928 of file Func1.h.
Member Function Documentation
virtual Func1& duplicate () const inline virtual
Duplicate the current function.
This duplicates the current function, returning a reference to the new malloced function.
Reimplemented from Func1.
Definition at line 964 of file Func1.h.
virtual doublereal eval (doublereal t) const inline virtual
Evaluate the function.
Reimplemented from Func1.
Definition at line 969 of file Func1.h.
doublereal operator() (doublereal t) const inherited
Calls method eval to evaluate the function.
Definition at line 55 of file Func1.cpp.
References Func1::eval().
Func1 & derivative () const virtual inherited
Creates a derivative to the current function.
This will malloc a derivative function and return a reference to the function.
Reimplemented in Composite1, Ratio1, PlusConstant1, TimesConstant1, Product1, Diff1, Sum1, Const1, Pow1, Exp1, Cos1, and Sin1.
Definition at line 66 of file Func1.cpp.
Referenced by Sum1::derivative(), Diff1::derivative(), Product1::derivative(), TimesConstant1::derivative(), PlusConstant1::derivative(), Ratio1::derivative(), and Composite1::derivative().
bool isIdentical (Func1 & other) const inherited
Routine to determine if two functions are the same.
Two functions are the same if they are the same function. This means that the ID and stored constant is the same. This means that the m_f1 and m_f2 are identical if they are non-null.
Definition at line 73 of file Func1.cpp.
References Func1::isIdentical().
Referenced by Func1::isIdentical().
doublereal c () const inherited
accessor function for the stored constant
accessor function for the returned constant
Definition at line 98 of file Func1.cpp.
Referenced by Func1::setC().
void setC (doublereal c) inherited
Function to set the stored constant.
Definition at line 104 of file Func1.cpp.
References Func1::c().
Func1 & func1 () const inherited
accessor function for m_f1
Definition at line 110 of file Func1.cpp.
Func1 & func2 () const inherited
accessor function for m_f2
Definition at line 115 of file Func1.cpp.
int order () const virtual inherited
Return the order of the function, if it makes sense.
Reimplemented in Composite1, Ratio1, PlusConstant1, TimesConstant1, Product1, Diff1, and Sum1.
Definition at line 120 of file Func1.cpp.
The documentation for this class was generated from the following file:
Func1.h