Cantera: TortuosityBase Class Reference
TortuosityBase Class Reference
Base case to handle tortuosity corrections for diffusive transport in porous media.
#include <TortuosityBase.h>
Public Member Functions
TortuosityBase ()
Default constructor uses Bruggeman exponent of 1.5.
TortuosityBase (const TortuosityBase &right)
Copy Constructor.
virtual ~TortuosityBase ()
Default destructor for TortuosityBase.
TortuosityBase & operator= (const TortuosityBase &right)
Assignment operator.
virtual TortuosityBase * duplMyselfAsTortuosityBase () const
Duplication operator.
virtual doublereal tortuosityFactor (doublereal porosity)
The tortuosity factor models the effective increase in the diffusive transport length.
virtual doublereal McMillanFactor (doublereal porosity)
The McMillan number is the ratio of the flux-like variable to the value it would have without porous flow.
Detailed Description
Base case to handle tortuosity corrections for diffusive transport in porous media.
Class to compute the increase in diffusive path length associated with tortuous path diffusion through, for example, porous media. This base class implementation relates tortuosity to volume fraction through a power-law relationship that goes back to Bruggeman. The exponent is referred to as the Bruggeman exponent.
Note that the total diffusional flux is generally written as
\[ \frac{ \phi C_T D_i \nabla X_i }{ \tau^2 } \]
where \(\phi \) is the volume fraction of the transported phase, \(\tau \) is referred to as the tortuosity. (Other variables are \(C_T \), the total concentration, \(D_i \), the diffusion coefficient, and \(X_i \), the mole fraction with Fickian transport assumed.)
The tortuosity comes into play in conjunction the the
Definition at line 44 of file TortuosityBase.h.
Constructor & Destructor Documentation
TortuosityBase ()
Default constructor uses Bruggeman exponent of 1.5.
Definition at line 27 of file TortuosityBase.cpp.
Referenced by TortuosityBase::duplMyselfAsTortuosityBase().
TortuosityBase (const TortuosityBase & right)
Copy Constructor.
Parameters
right Object to be copied
Definition at line 35 of file TortuosityBase.cpp.
~TortuosityBase () virtual
Default destructor for TortuosityBase.
Definition at line 41 of file TortuosityBase.cpp.
Member Function Documentation
TortuosityBase & operator= (const TortuosityBase & right)
Assignment operator.
Parameters
right Object to be copied
Definition at line 50 of file TortuosityBase.cpp.
Referenced by TortuosityPercolation::operator=(), TortuosityMaxwell::operator=(), and TortuosityBruggeman::operator=().
TortuosityBase * duplMyselfAsTortuosityBase () const virtual
Duplication operator.
Returns
Returns a pointer to a duplicate of the current object given a base class pointer
Reimplemented in TortuosityBruggeman, TortuosityMaxwell, and TortuosityPercolation.
Definition at line 63 of file TortuosityBase.cpp.
References TortuosityBase::TortuosityBase().
doublereal tortuosityFactor (doublereal porosity) virtual
The tortuosity factor models the effective increase in the diffusive transport length.
This method returns \(1/\tau^2 \) in the description of the flux
\(C_T D_i \nabla X_i / \tau^2 \).
Reimplemented in TortuosityBruggeman, TortuosityMaxwell, and TortuosityPercolation.
Definition at line 77 of file TortuosityBase.cpp.
doublereal McMillanFactor (doublereal porosity) virtual
The McMillan number is the ratio of the flux-like variable to the value it would have without porous flow.
The McMillan number combines the effect of tortuosity and volume fraction of the transported phase. The net flux observed is then the product of the McMillan number and the non-porous transport rate. For a conductivity in a non-porous media, \(\kappa_0 \), the conductivity in the porous media would be \(\kappa = (\rm McMillan) \kappa_0 \).
Reimplemented in TortuosityBruggeman, TortuosityMaxwell, and TortuosityPercolation.
Definition at line 92 of file TortuosityBase.cpp.
The documentation for this class was generated from the following files:
TortuosityBase.h
TortuosityBase.cpp