Cantera: SquareMatrix Class Reference
SquareMatrix Class Reference
A class for full (non-sparse) matrices with Fortran-compatible data storage.
#include <SquareMatrix.h>
Public Types
typedef vector_fp::iterator iterator
Type definition for the iterator class that is can be used by Array2D types.
typedef vector_fp::const_iterator const_iterator
Type definition for the const_iterator class that is can be used by Array2D types.
Public Member Functions
SquareMatrix ()
Base Constructor.
SquareMatrix (size_t n, doublereal v=0.0)
Constructor.
SquareMatrix (const SquareMatrix &right)
Copy Constructor.
SquareMatrix & operator= (const SquareMatrix &right)
Assignment operator.
virtual ~SquareMatrix ()
Destructor. Does nothing.
int solve (doublereal *b)
Solves the Ax = b system returning x in the b spot.
void resize (size_t n, size_t m, doublereal v=0.0)
Resize the matrix.
void zero ()
Zero the matrix.
virtual void mult (const doublereal *b, doublereal *prod) const
Multiply A*b and write result to prod.
virtual void leftMult (const doublereal *const b, doublereal *const prod) const
Multiply b*A and write result to prod.
int factor ()
Factors the A matrix, overwriting A.
virtual int factorQR ()
Factors the A matrix using the QR algorithm, overwriting A.
virtual doublereal rcondQR ()
Returns an estimate of the inverse of the condition number for the matrix.
virtual doublereal rcond (doublereal a1norm)
Returns an estimate of the inverse of the condition number for the matrix.
virtual doublereal oneNorm () const
Returns the one norm of the matrix.
int solveQR (doublereal *b)
Solves the linear problem Ax=b using the QR algorithm returning x in the b spot.
virtual void clearFactorFlag ()
clear the factored flag
void setFactorFlag ()
set the factored flag
virtual bool factored () const
Report whether the current matrix has been factored.
virtual void useFactorAlgorithm (int fAlgorithm)
Change the way the matrix is factored.
virtual int factorAlgorithm () const
Returns the factor algorithm used.
virtual doublereal * ptrColumn (size_t j)
Return a pointer to the top of column j, columns are assumed to be contiguous in memory.
virtual doublereal & operator() (size_t i, size_t j)
Index into the (i,j) element.
virtual void copyData (const GeneralMatrix &y)
Copy the data from one array into another without doing any checking.
virtual doublereal operator() (size_t i, size_t j) const
Constant Index into the (i,j) element.
virtual size_t nRows () const
Return the number of rows in the matrix.
size_t nRowsAndStruct (size_t *const iStruct=0) const
Return the size and structure of the matrix.
virtual GeneralMatrix * duplMyselfAsGeneralMatrix () const
Duplicate this object.
virtual vector_fp::iterator begin ()
Return an iterator pointing to the first element.
virtual vector_fp::const_iterator begin () const
Return a const iterator pointing to the first element.
virtual doublereal *const * colPts ()
Return a vector of const pointers to the columns.
virtual size_t checkRows (doublereal &valueSmall) const
Check to see if we have any zero rows in the jacobian.
virtual size_t checkColumns (doublereal &valueSmall) const
Check to see if we have any zero columns in the jacobian.
const doublereal *const * const_colPts () const
Return a const vector of const pointers to the columns.
vector_int & ipiv ()
Return a changeable value of the pivot vector.
const vector_int & ipiv () const
Return a changeable value of the pivot vector.
void copyData (const Array2D &y)
Copy the data from one array into another without doing any checking.
void appendColumn (const vector_fp &c)
Append a column to the existing matrix using a std vector.
void appendColumn (const doublereal *const c)
Append a column to the existing matrix.
void setRow (size_t n, const doublereal *const rw)
Set the nth row to array rw.
void getRow (size_t n, doublereal *const rw)
Get the nth row and return it in a vector.
void setColumn (size_t m, doublereal *const col)
Set the values in column m to those in array col.
void getColumn (size_t m, doublereal *const col)
Get the values in column m.
void axpy (doublereal a, const Array2D &x, const Array2D &y)
Evaluate z = a*x + y.
doublereal & value (size_t i, size_t j)
Returns a changeable reference to position in the matrix.
doublereal value (size_t i, size_t j) const
Returns the value of a single matrix entry.
size_t nColumns () const
Number of columns.
iterator end ()
Return an iterator pointing past the last element.
const_iterator end () const
Return a const iterator pointing to past the last element.
vector_fp & data ()
Return a reference to the data vector.
const vector_fp & data () const
Return a const reference to the data vector.
const doublereal * ptrColumn (size_t j) const
Return a const pointer to the top of column j, columns are contiguous in memory.
Public Attributes
vector_fp tau
Work vector for QR algorithm.
vector_fp work
Work vector for QR algorithm.
std::vector< int > iwork_
Integer work vector for QR algorithms.
int m_useReturnErrorCode
Error Handling Flag.
int m_printLevel
Print Level.
int matrixType_
Matrix type.
Protected Attributes
int m_factored
the factor flag
doublereal a1norm_
1-norm of the matrix. This is determined immediately before every factorization
int useQR_
Use the QR algorithm to factor and invert the matrix.
vector_int m_ipiv
Vector of pivots. Length is equal to the max of m and n.
std::vector< doublereal * > m_colPts
Vector of column pointers.
vector_fp m_data
Data stored in a single array.
size_t m_nrows
Number of rows.
size_t m_ncols
Number of columns.
Detailed Description
A class for full (non-sparse) matrices with Fortran-compatible data storage.
Adds matrix inversion operations to this class from DenseMatrix.
Definition at line 26 of file SquareMatrix.h.
Member Typedef Documentation
typedef vector_fp::iterator iterator inherited
Type definition for the iterator class that is can be used by Array2D types.
this is just equal to vector_fp iterator.
Definition at line 43 of file Array.h.
typedef vector_fp::const_iterator const_iterator inherited
Type definition for the const_iterator class that is can be used by Array2D types.
this is just equal to vector_fp const_iterator.
Definition at line 51 of file Array.h.
Constructor & Destructor Documentation
SquareMatrix ()
Base Constructor.
Create an 0 by 0 matrix, and initialize all elements to 0.
Definition at line 28 of file SquareMatrix.cpp.
Referenced by SquareMatrix::duplMyselfAsGeneralMatrix().
SquareMatrix (size_t n, doublereal v = 0.0)
Constructor.
Create an n by n matrix, and initialize all elements to v.
Parameters
n size of the square matrix
v initial value of all matrix components.
Definition at line 46 of file SquareMatrix.cpp.
SquareMatrix (const SquareMatrix & right)
Copy Constructor.
Parameters
right Object to be copied
Definition at line 60 of file SquareMatrix.cpp.
~SquareMatrix () virtual
Destructor. Does nothing.
Definition at line 86 of file SquareMatrix.cpp.
Member Function Documentation
SquareMatrix & operator= (const SquareMatrix & right)
Assignment operator.
Parameters
right Object to be copied
Definition at line 73 of file SquareMatrix.cpp.
References SquareMatrix::a1norm_, SquareMatrix::m_factored, GeneralMatrix::operator=(), DenseMatrix::operator=(), and SquareMatrix::useQR_.
int solve (doublereal * b) virtual
Solves the Ax = b system returning x in the b spot.
Parameters
b Vector for the rhs of the equation system
Implements GeneralMatrix.
Definition at line 93 of file SquareMatrix.cpp.
References SquareMatrix::begin(), DATA_PTR, SquareMatrix::factor(), Cantera::int2str(), DenseMatrix::ipiv(), SquareMatrix::m_factored, DenseMatrix::m_printLevel, DenseMatrix::m_useReturnErrorCode, Array2D::nColumns(), SquareMatrix::nRows(), SquareMatrix::solveQR(), SquareMatrix::useQR_, and Cantera::writelogf().
void resize (size_t n, size_t m, doublereal v = 0.0)
Resize the matrix.
Parameters
n Number of rows
m Number of columns
v double to fill the new space (defaults to zero)
Definition at line 142 of file SquareMatrix.cpp.
References DenseMatrix::resize().
void zero () virtual
Zero the matrix.
Implements GeneralMatrix.
Definition at line 128 of file SquareMatrix.cpp.
References Array2D::m_data, and SquareMatrix::nRows().
void mult (const doublereal * b, doublereal * prod) const virtual
Multiply A*b and write result to prod.
Parameters
b Vector to do the rh multiplication
prod OUTPUT vector to receive the result
Reimplemented from DenseMatrix.
Definition at line 153 of file SquareMatrix.cpp.
References DenseMatrix::mult().
void leftMult (const doublereal *const b, doublereal *const prod) const virtual
Multiply b*A and write result to prod.
Parameters
b Vector to do the lh multiplication
prod OUTPUT vector to receive the result
Reimplemented from DenseMatrix.
Definition at line 163 of file SquareMatrix.cpp.
References DenseMatrix::leftMult().
int factor () virtual
Factors the A matrix, overwriting A.
We flip m_factored boolean to indicate that the matrix is now A-1.
Implements GeneralMatrix.
Definition at line 171 of file SquareMatrix.cpp.
References SquareMatrix::a1norm_, SquareMatrix::begin(), DATA_PTR, SquareMatrix::factorQR(), Cantera::int2str(), DenseMatrix::ipiv(), SquareMatrix::m_factored, Array2D::m_nrows, DenseMatrix::m_printLevel, DenseMatrix::m_useReturnErrorCode, SquareMatrix::nRows(), SquareMatrix::useQR_, SquareMatrix::work, and Cantera::writelogf().
Referenced by SquareMatrix::solve().
int factorQR () virtual
Factors the A matrix using the QR algorithm, overwriting A.
we set m_factored to 2 to indicate the matrix is now QR factored
Returns
Returns the info variable from lapack
Implements GeneralMatrix.
Definition at line 208 of file SquareMatrix.cpp.
References SquareMatrix::a1norm_, SquareMatrix::begin(), DATA_PTR, Cantera::int2str(), SquareMatrix::m_factored, Array2D::m_nrows, DenseMatrix::m_printLevel, DenseMatrix::m_useReturnErrorCode, SquareMatrix::tau, SquareMatrix::work, and Cantera::writelogf().
Referenced by SquareMatrix::factor(), and SquareMatrix::solveQR().
doublereal rcondQR () virtual
Returns an estimate of the inverse of the condition number for the matrix.
The matrix must have been previously factored using the QR algorithm
Returns
returns the inverse of the condition number
Implements GeneralMatrix.
Definition at line 328 of file SquareMatrix.cpp.
References SquareMatrix::begin(), Cantera::ct_dtrcon(), DATA_PTR, Cantera::int2str(), SquareMatrix::iwork_, SquareMatrix::m_factored, Array2D::m_nrows, DenseMatrix::m_printLevel, DenseMatrix::m_useReturnErrorCode, SquareMatrix::rcond(), SquareMatrix::work, and Cantera::writelogf().
doublereal rcond (doublereal a1norm) virtual
Returns an estimate of the inverse of the condition number for the matrix.
The matrix must have been previously factored using the LU algorithm
Parameters
a1norm Norm of the matrix
Returns
returns the inverse of the condition number
Implements GeneralMatrix.
Definition at line 292 of file SquareMatrix.cpp.
References SquareMatrix::begin(), DATA_PTR, Cantera::int2str(), SquareMatrix::iwork_, SquareMatrix::m_factored, Array2D::m_nrows, DenseMatrix::m_printLevel, DenseMatrix::m_useReturnErrorCode, SquareMatrix::work, and Cantera::writelogf().
Referenced by SquareMatrix::rcondQR().
doublereal oneNorm () const virtual
Returns the one norm of the matrix.
Implements GeneralMatrix.
Definition at line 323 of file SquareMatrix.cpp.
References SquareMatrix::a1norm_.
int solveQR (doublereal * b)
Solves the linear problem Ax=b using the QR algorithm returning x in the b spot.
Parameters
b RHS to be solved.
Definition at line 239 of file SquareMatrix.cpp.
References SquareMatrix::begin(), DATA_PTR, SquareMatrix::factorQR(), Cantera::int2str(), SquareMatrix::m_factored, Array2D::m_nrows, DenseMatrix::m_printLevel, DenseMatrix::m_useReturnErrorCode, SquareMatrix::tau, SquareMatrix::work, and Cantera::writelogf().
Referenced by SquareMatrix::solve().
void clearFactorFlag () virtual
clear the factored flag
Implements GeneralMatrix.
Definition at line 195 of file SquareMatrix.cpp.
References SquareMatrix::m_factored.
void setFactorFlag ()
set the factored flag
Definition at line 203 of file SquareMatrix.cpp.
References SquareMatrix::m_factored.
bool factored () const virtual
Report whether the current matrix has been factored.
Implements GeneralMatrix.
Definition at line 366 of file SquareMatrix.cpp.
References SquareMatrix::m_factored.
void useFactorAlgorithm (int fAlgorithm) virtual
Change the way the matrix is factored.
Parameters
fAlgorithm integer 0 LU factorization 1 QR factorization
Implements GeneralMatrix.
Definition at line 356 of file SquareMatrix.cpp.
References SquareMatrix::useQR_.
int factorAlgorithm () const virtual
Returns the factor algorithm used.
0 LU decomposition
1 QR decomposition
This routine will always return 0
Implements GeneralMatrix.
Definition at line 361 of file SquareMatrix.cpp.
References SquareMatrix::useQR_.
doublereal * ptrColumn (size_t j) virtual
Return a pointer to the top of column j, columns are assumed to be contiguous in memory.
Parameters
j Value of the column
Returns
Returns a pointer to the top of the column
Implements GeneralMatrix.
Definition at line 377 of file SquareMatrix.cpp.
References Array2D::ptrColumn().
virtual doublereal& operator() (size_t i, size_t j) inline virtual
Index into the (i,j) element.
Parameters
i row
j column
(note, tried a using directive here, and it didn't seem to work)
Returns a changeable reference to the matrix entry
Implements GeneralMatrix.
Definition at line 178 of file SquareMatrix.h.
References Array2D::operator()().
void copyData (const GeneralMatrix & y) virtual
Copy the data from one array into another without doing any checking.
This differs from the assignment operator as no resizing is done and memcpy() is used.
Parameters
y Array to be copied
Implements GeneralMatrix.
Definition at line 387 of file SquareMatrix.cpp.
References Array2D::copyData().
virtual doublereal operator() (size_t i, size_t j) const inline virtual
Constant Index into the (i,j) element.
Parameters
i row
j column
Returns an unchangeable reference to the matrix entry
Implements GeneralMatrix.
Definition at line 196 of file SquareMatrix.h.
References Array2D::operator()().
size_t nRows () const virtual
Return the number of rows in the matrix.
Implements GeneralMatrix.
Definition at line 393 of file SquareMatrix.cpp.
References Array2D::m_nrows.
Referenced by SquareMatrix::factor(), SquareMatrix::solve(), and SquareMatrix::zero().
size_t nRowsAndStruct (size_t *const iStruct = 0) const virtual
Return the size and structure of the matrix.
This is inherited from GeneralMatrix
Parameters
iStruct OUTPUT Pointer to a vector of ints that describe the structure of the matrix. not used
Returns
returns the number of rows and columns in the matrix.
Implements GeneralMatrix.
Definition at line 398 of file SquareMatrix.cpp.
References Array2D::m_nrows.
GeneralMatrix * duplMyselfAsGeneralMatrix () const virtual
Duplicate this object.
Implements GeneralMatrix.
Definition at line 403 of file SquareMatrix.cpp.
References SquareMatrix::SquareMatrix().
vector_fp::iterator begin () virtual
Return an iterator pointing to the first element.
Implements GeneralMatrix.
Definition at line 410 of file SquareMatrix.cpp.
References Array2D::m_data.
Referenced by SquareMatrix::factor(), SquareMatrix::factorQR(), SquareMatrix::rcond(), SquareMatrix::rcondQR(), SquareMatrix::solve(), and SquareMatrix::solveQR().
vector_fp::const_iterator begin () const virtual
Return a const iterator pointing to the first element.
Implements GeneralMatrix.
Definition at line 416 of file SquareMatrix.cpp.
References Array2D::m_data.
doublereal *const * colPts () virtual
Return a vector of const pointers to the columns.
Note the value of the pointers are protected by their being const. However, the value of the matrix is open to being changed.
Returns
returns a vector of pointers to the top of the columns of the matrices.
Reimplemented from DenseMatrix.
Definition at line 429 of file SquareMatrix.cpp.
References DenseMatrix::colPts().
size_t checkRows (doublereal & valueSmall) const virtual
Check to see if we have any zero rows in the jacobian.
This utility routine checks to see if any rows are zero. The smallest row is returned along with the largest coefficient in that row
Parameters
valueSmall OUTPUT value of the largest coefficient in the smallest row
Returns
index of the row that is most nearly zero
Implements GeneralMatrix.
Definition at line 435 of file SquareMatrix.cpp.
References Array2D::m_nrows, Cantera::npos, and Array2D::value().
size_t checkColumns (doublereal & valueSmall) const virtual
Check to see if we have any zero columns in the jacobian.
This utility routine checks to see if any columns are zero. The smallest column is returned along with the largest coefficient in that column
Parameters
valueSmall OUTPUT value of the largest coefficient in the smallest column
Returns
index of the column that is most nearly zero
Implements GeneralMatrix.
Definition at line 454 of file SquareMatrix.cpp.
References Array2D::m_nrows, Cantera::npos, and Array2D::value().
const doublereal *const * const_colPts () const inherited
Return a const vector of const pointers to the columns.
Note, the jacobian can not be altered by this routine, and therefore the member function is const.
Returns
returns a vector of pointers to the top of the columns of the matrices.
Definition at line 103 of file DenseMatrix.cpp.
References DenseMatrix::m_colPts.
vector_int & ipiv () inherited
Return a changeable value of the pivot vector.
Returns
Returns a reference to the pivot vector as a vector_int
Definition at line 130 of file DenseMatrix.cpp.
References DenseMatrix::m_ipiv.
Referenced by DenseMatrix::DenseMatrix(), SquareMatrix::factor(), MultiTransport::getMassFluxes(), MultiTransport::getSpeciesFluxes(), Cantera::invert(), DenseMatrix::operator=(), SquareMatrix::solve(), and Cantera::solve().
const vector_int& ipiv () const inline inherited
Return a changeable value of the pivot vector.
Returns
Returns a reference to the pivot vector as a vector_int
Definition at line 161 of file DenseMatrix.h.
References DenseMatrix::m_ipiv.
void copyData (const Array2D & y) inline inherited
Copy the data from one array into another without doing any checking.
This differs from the assignment operator as no resizing is done and memcpy() is used.
Parameters
y Array to be copied
Definition at line 139 of file Array.h.
References DATA_PTR, Array2D::m_data, Array2D::m_ncols, Array2D::m_nrows, and Array2D::ptrColumn().
Referenced by SquareMatrix::copyData().
void appendColumn (const vector_fp & c) inline inherited
Append a column to the existing matrix using a std vector.
This operation will add a column onto the existing matrix.
Parameters
c This vector<doublereal> is the entries in the column to be added. It must have a length equal to m_nrows or greater.
Definition at line 152 of file Array.h.
References Array2D::m_data, Array2D::m_ncols, Array2D::m_nrows, and Array2D::value().
void appendColumn (const doublereal *const c) inline inherited
Append a column to the existing matrix.
This operation will add a column onto the existing matrix.
Parameters
c This vector of doubles is the entries in the column to be added. It must have a length equal to m_nrows or greater.
Definition at line 169 of file Array.h.
References Array2D::m_data, Array2D::m_ncols, Array2D::m_nrows, and Array2D::value().
void setRow (size_t n, const doublereal *const rw) inline inherited
Set the nth row to array rw.
Parameters
n Index of the row to be changed
rw Vector for the row. Must have a length of m_ncols.
Definition at line 183 of file Array.h.
References Array2D::m_data, Array2D::m_ncols, and Array2D::m_nrows.
void getRow (size_t n, doublereal *const rw) inline inherited
Get the nth row and return it in a vector.
Parameters
n Index of the row to be returned.
rw Return Vector for the operation. Must have a length of m_ncols.
Definition at line 195 of file Array.h.
References Array2D::m_data, Array2D::m_ncols, and Array2D::m_nrows.
Referenced by StFlow::save().
void setColumn (size_t m, doublereal *const col) inline inherited
Set the values in column m to those in array col.
A(i,m) = col(i)
Parameters
m Column to set
col pointer to a col vector. Vector must have a length of m_nrows.
Definition at line 209 of file Array.h.
References Array2D::m_data, and Array2D::m_nrows.
void getColumn (size_t m, doublereal *const col) inline inherited
Get the values in column m.
col(i) = A(i,m)
Parameters
m Column to set
col pointer to a col vector that will be returned
Definition at line 222 of file Array.h.
References Array2D::m_data, and Array2D::m_nrows.
void axpy (doublereal a, const Array2D & x, const Array2D & y) inline inherited
Evaluate z = a*x + y.
This function evaluates the AXPY operation, and stores the result in the object's Array2D object. It's assumed that all 3 objects have the same dimensions, but no error checking is done.
Parameters
a scalar to multiply x with
x First Array2D object to be used
y Second Array2D object to be used
Definition at line 246 of file Array.h.
References Array2D::begin(), and Array2D::end().
doublereal& value (size_t i, size_t j) inline inherited
Returns a changeable reference to position in the matrix.
This is a key entry. Returns a reference to the matrixes (i,j) element. This may be used as an L value.
Parameters
i The row index
j The column index
Returns
Returns a changeable reference to the matrix entry
Definition at line 300 of file Array.h.
References Array2D::m_data, and Array2D::m_nrows.
Referenced by Array2D::appendColumn(), SquareMatrix::checkColumns(), SquareMatrix::checkRows(), DenseMatrix::leftMult(), Array2D::operator()(), and DebyeHuckel::s_update_lnMolalityActCoeff().
doublereal value (size_t i, size_t j) const inline inherited
Returns the value of a single matrix entry.
This is a key entry. Returns the value of the matrix position (i,j) element.
Parameters
i The row index
j The column index
Definition at line 312 of file Array.h.
References Array2D::m_data, and Array2D::m_nrows.
size_t nColumns () const inline inherited
Number of columns.
Definition at line 322 of file Array.h.
References Array2D::m_ncols.
Referenced by MultiTransport::getMassFluxes(), ctml::getMatrixValues(), MultiTransport::getSpeciesFluxes(), DenseMatrix::leftMult(), Cantera::multiply(), Cantera::operator<<(), Cantera::outputExcel(), Cantera::outputTEC(), StFlow::save(), SquareMatrix::solve(), and Cantera::solve().
iterator end () inline inherited
Return an iterator pointing past the last element.
Definition at line 332 of file Array.h.
References Array2D::m_data.
Referenced by Array2D::axpy(), Cantera::operator*=(), and Cantera::operator+=().
const_iterator end () const inline inherited
Return a const iterator pointing to past the last element.
Definition at line 342 of file Array.h.
References Array2D::m_data.
vector_fp& data () inline inherited
Return a reference to the data vector.
Definition at line 347 of file Array.h.
References Array2D::m_data.
const vector_fp& data () const inline inherited
Return a const reference to the data vector.
Definition at line 352 of file Array.h.
References Array2D::m_data.
const doublereal* ptrColumn (size_t j) const inline inherited
Return a const pointer to the top of column j, columns are contiguous in memory.
Parameters
j Value of the column
Returns
Returns a const pointer to the top of the column
Definition at line 374 of file Array.h.
References Array2D::m_data, and Array2D::m_nrows.
Member Data Documentation
int m_factored protected
the factor flag
Definition at line 263 of file SquareMatrix.h.
Referenced by SquareMatrix::clearFactorFlag(), SquareMatrix::factor(), SquareMatrix::factored(), SquareMatrix::factorQR(), SquareMatrix::operator=(), SquareMatrix::rcond(), SquareMatrix::rcondQR(), SquareMatrix::setFactorFlag(), SquareMatrix::solve(), and SquareMatrix::solveQR().
vector_fp tau
Work vector for QR algorithm.
Definition at line 267 of file SquareMatrix.h.
Referenced by SquareMatrix::factorQR(), and SquareMatrix::solveQR().
vector_fp work
Work vector for QR algorithm.
Definition at line 270 of file SquareMatrix.h.
Referenced by SquareMatrix::factor(), SquareMatrix::factorQR(), SquareMatrix::rcond(), SquareMatrix::rcondQR(), and SquareMatrix::solveQR().
std::vector<int> iwork_
Integer work vector for QR algorithms.
Definition at line 273 of file SquareMatrix.h.
Referenced by SquareMatrix::rcond(), and SquareMatrix::rcondQR().
doublereal a1norm_ protected
1-norm of the matrix. This is determined immediately before every factorization
Definition at line 276 of file SquareMatrix.h.
Referenced by SquareMatrix::factor(), SquareMatrix::factorQR(), SquareMatrix::oneNorm(), and SquareMatrix::operator=().
int useQR_ protected
Use the QR algorithm to factor and invert the matrix.
Definition at line 279 of file SquareMatrix.h.
Referenced by SquareMatrix::factor(), SquareMatrix::factorAlgorithm(), SquareMatrix::operator=(), SquareMatrix::solve(), and SquareMatrix::useFactorAlgorithm().
vector_int m_ipiv protected inherited
Vector of pivots. Length is equal to the max of m and n.
Definition at line 168 of file DenseMatrix.h.
Referenced by DenseMatrix::DenseMatrix(), DenseMatrix::ipiv(), DenseMatrix::operator=(), and DenseMatrix::resize().
std::vector<doublereal*> m_colPts protected inherited
Vector of column pointers.
Definition at line 171 of file DenseMatrix.h.
Referenced by DenseMatrix::colPts(), DenseMatrix::const_colPts(), DenseMatrix::DenseMatrix(), DenseMatrix::operator=(), and DenseMatrix::resize().
int m_useReturnErrorCode inherited
Error Handling Flag.
The default is to set this to 0. In this case, if a factorization is requested and can't be achieved, a CESingularMatrix exception is triggered. No return code is used, because an exception is thrown. If this is set to 1, then an exception is not thrown. Routines return with an error code, that is up to the calling routine to handle correctly. Negative return codes always throw an exception.
Definition at line 182 of file DenseMatrix.h.
Referenced by SquareMatrix::factor(), SquareMatrix::factorQR(), Cantera::invert(), DenseMatrix::operator=(), SquareMatrix::rcond(), SquareMatrix::rcondQR(), SquareMatrix::solve(), Cantera::solve(), and SquareMatrix::solveQR().
int m_printLevel inherited
Print Level.
Printing is done to the log file using the routine writelogf().
Level of printing that is carried out. Only error conditions are printed out, if this value is nonzero.
Definition at line 190 of file DenseMatrix.h.
Referenced by SquareMatrix::factor(), SquareMatrix::factorQR(), Cantera::invert(), DenseMatrix::operator=(), SquareMatrix::rcond(), SquareMatrix::rcondQR(), SquareMatrix::solve(), Cantera::solve(), and SquareMatrix::solveQR().
vector_fp m_data protected inherited
Data stored in a single array.
Definition at line 381 of file Array.h.
Referenced by Array2D::appendColumn(), Array2D::Array2D(), SquareMatrix::begin(), Array2D::begin(), Array2D::copyData(), Array2D::data(), DenseMatrix::DenseMatrix(), Array2D::end(), Array2D::getColumn(), Array2D::getRow(), DenseMatrix::operator=(), Array2D::operator=(), Array2D::ptrColumn(), DenseMatrix::resize(), Array2D::resize(), Array2D::setColumn(), Array2D::setRow(), Array2D::value(), SquareMatrix::zero(), and Array2D::zero().
size_t m_nrows protected inherited
Number of rows.
Definition at line 384 of file Array.h.
Referenced by Array2D::appendColumn(), Array2D::Array2D(), SquareMatrix::checkColumns(), SquareMatrix::checkRows(), Array2D::copyData(), DenseMatrix::DenseMatrix(), SquareMatrix::factor(), SquareMatrix::factorQR(), Array2D::getColumn(), Array2D::getRow(), SquareMatrix::nRows(), Array2D::nRows(), SquareMatrix::nRowsAndStruct(), DenseMatrix::operator=(), Array2D::operator=(), Array2D::ptrColumn(), SquareMatrix::rcond(), SquareMatrix::rcondQR(), DenseMatrix::resize(), Array2D::resize(), Array2D::setColumn(), Array2D::setRow(), SquareMatrix::solveQR(), Array2D::value(), and Array2D::zero().
size_t m_ncols protected inherited
Number of columns.
Definition at line 387 of file Array.h.
Referenced by Array2D::appendColumn(), Array2D::Array2D(), Array2D::copyData(), DenseMatrix::DenseMatrix(), Array2D::getRow(), Array2D::nColumns(), DenseMatrix::operator=(), Array2D::operator=(), DenseMatrix::resize(), Array2D::resize(), Array2D::setRow(), and Array2D::zero().
int matrixType_ inherited
Matrix type.
0 Square 1 Banded
Definition at line 236 of file GeneralMatrix.h.
Referenced by NonlinearSolver::beuler_jac(), NonlinearSolver::doAffineNewtonSolve(), GeneralMatrix::operator=(), and NonlinearSolver::scaleMatrix().
The documentation for this class was generated from the following files:
SquareMatrix.h
SquareMatrix.cpp