Cantera: HMWSoln Class Reference
HMWSoln Class Reference
Thermodynamic Properties
Class HMWSoln represents a dilute or concentrated liquid electrolyte phase which obeys the Pitzer formulation for nonideality.
#include <HMWSoln.h>
Public Member Functions
HMWSoln ()
Default Constructor.
HMWSoln (std::string inputFile, std::string id="")
Construct and initialize an HMWSoln ThermoPhase object directly from an ASCII input file.
HMWSoln (XML_Node &phaseRef, std::string id="")
Construct and initialize an HMWSoln ThermoPhase object directly from an XML database.
HMWSoln (const HMWSoln &right)
Copy Constructor.
HMWSoln & operator= (const HMWSoln &right)
Assignment operator.
HMWSoln (int testProb)
This is a special constructor, used to replicate test problems during the initial verification of the object.
virtual ~HMWSoln ()
Destructor.
ThermoPhase * duplMyselfAsThermoPhase () const
Duplicator from the ThermoPhase parent class.
virtual void setParameters (int n, doublereal *const c)
Set the equation of state parameters.
virtual void getParameters (int &n, doublereal *const c) const
Get the equation of state parameters in a vector.
virtual void setParametersFromXML (const XML_Node &eosdata)
Set equation of state parameter values from XML entries.
void constructPhaseFile (std::string inputFile, std::string id)
Initialization of a HMWSoln phase using an xml file.
void constructPhaseXML (XML_Node &phaseNode, std::string id)
Import and initialize a HMWSoln phase specification in an XML tree into the current object.
virtual void initThermo ()
Internal initialization required after all species have been added.
virtual void initThermoXML (XML_Node &phaseNode, std::string id)
Initialize the phase parameters from an XML file.
double speciesMolarVolume (int k) const
Report the molar volume of species k.
virtual double A_Debye_TP (double temperature=-1.0, double pressure=-1.0) const
Value of the Debye Huckel constant as a function of temperature and pressure.
virtual double dA_DebyedT_TP (double temperature=-1.0, double pressure=-1.0) const
Value of the derivative of the Debye Huckel constant with respect to temperature as a function of temperature and pressure.
virtual double dA_DebyedP_TP (double temperature=-1.0, double pressure=-1.0) const
Value of the derivative of the Debye Huckel constant with respect to pressure, as a function of temperature and pressure.
double ADebye_L (double temperature=-1.0, double pressure=-1.0) const
Return Pitzer's definition of A_L.
double ADebye_J (double temperature=-1.0, double pressure=-1.0) const
Return Pitzer's definition of A_J.
double ADebye_V (double temperature=-1.0, double pressure=-1.0) const
Return Pitzer's definition of A_V.
virtual double d2A_DebyedT2_TP (double temperature=-1.0, double pressure=-1.0) const
Value of the 2nd derivative of the Debye Huckel constant with respect to temperature as a function of temperature and pressure.
double AionicRadius (int k=0) const
Reports the ionic radius of the kth species.
int formPitzer () const
formPitzer():
void printCoeffs () const
Print out all of the input coefficients.
void getUnscaledMolalityActivityCoefficients (doublereal *acMolality) const
Get the array of unscaled non-dimensional molality based activity coefficients at the current solution temperature, pressure, and solution concentration.
int debugPrinting ()
Return int specifying the amount of debug printing.
virtual void setStateFromXML (const XML_Node &state)
Set equation of state parameter values from XML entries.
void setState_TPM (doublereal t, doublereal p, const doublereal *const molalities)
Set the temperature (K), pressure (Pa), and molalities (gmol kg-1) of the solutes.
void setState_TPM (doublereal t, doublereal p, compositionMap &m)
Set the temperature (K), pressure (Pa), and molalities.
void setState_TPM (doublereal t, doublereal p, const std::string &m)
Set the temperature (K), pressure (Pa), and molalities.
virtual void getdlnActCoeffdlnN (const size_t ld, doublereal *const dlnActCoeffdlnN)
Get the array of derivatives of the log activity coefficients with respect to the log of the species mole numbers.
virtual std::string report (bool show_thermo=true) const
returns a summary of the state of the phase as a string
virtual void reportCSV (std::ofstream &csvFile) const
returns a summary of the state of the phase to specified comma separated files
doublereal _RT () const
Return the Gas Constant multiplied by the current temperature.
XML_Node & xml ()
Returns a reference to the XML_Node stored for the phase.
void saveState (vector_fp &state) const
Save the current internal state of the phase Write to vector 'state' the current internal state.
void saveState (size_t lenstate, doublereal *state) const
Write to array 'state' the current internal state.
void restoreState (const vector_fp &state)
Restore a state saved on a previous call to saveState.
void restoreState (size_t lenstate, const doublereal *state)
Restore the state of the phase from a previously saved state vector.
doublereal molecularWeight (size_t k) const
Molecular weight of species k.
doublereal molarMass (size_t k) const
Return the Molar mass of species k Alternate name for molecular weight.
void getMolecularWeights (vector_fp &weights) const
Copy the vector of molecular weights into vector weights.
void getMolecularWeights (int iwt, doublereal *weights) const
Copy the vector of molecular weights into array weights.
void getMolecularWeights (doublereal *weights) const
Copy the vector of molecular weights into array weights.
const vector_fp & molecularWeights () const
Return a const reference to the internal vector of molecular weights.
doublereal size (size_t k) const
This routine returns the size of species k.
doublereal charge (size_t k) const
Dimensionless electrical charge of a single molecule of species k The charge is normalized by the the magnitude of the electron charge.
doublereal chargeDensity () const
Charge density [C/m^3].
size_t nDim () const
Returns the number of spatial dimensions (1, 2, or 3)
void setNDim (size_t ndim)
Set the number of spatial dimensions (1, 2, or 3).
virtual void freezeSpecies ()
Call when finished adding species.
bool speciesFrozen ()
True if freezeSpecies has been called.
virtual bool ready () const
int stateMFNumber () const
Return the State Mole Fraction Number.
void stateMFChangeCalc (bool forceChange=false)
Every time the mole fractions have changed, this routine will increment the stateMFNumber.
Utilities
virtual int eosType () const
Equation of state type flag.
Molar Thermodynamic Properties of the Solution --------------
virtual doublereal enthalpy_mole () const
Molar enthalpy. Units: J/kmol.
virtual doublereal relative_enthalpy () const
Excess molar enthalpy of the solution from the mixing process.
virtual doublereal relative_molal_enthalpy () const
Excess molar enthalpy of the solution from the mixing process on a molality basis.
virtual doublereal intEnergy_mole () const
Molar internal energy. Units: J/kmol.
virtual doublereal entropy_mole () const
Molar entropy. Units: J/kmol/K.
virtual doublereal gibbs_mole () const
Molar Gibbs function. Units: J/kmol.
virtual doublereal cp_mole () const
Molar heat capacity at constant pressure. Units: J/kmol/K.
virtual doublereal cv_mole () const
Molar heat capacity at constant volume. Units: J/kmol/K.
Activities, Standard States, and Activity Concentrations
The activity \(a_k\) of a species in solution is related to the chemical potential by
\[ \mu_k = \mu_k^0(T) + \hat R T \log a_k. \]
The quantity \(\mu_k^0(T,P)\) is the chemical potential at unit activity, which depends only on temperature and the pressure.
Activity is assumed to be molality-based here.
virtual void getActivityConcentrations (doublereal *c) const
This method returns an array of generalized activity concentrations.
virtual doublereal standardConcentration (size_t k=0) const
Return the standard concentration for the kth species.
virtual doublereal logStandardConc (size_t k=0) const
Returns the natural logarithm of the standard concentration of the kth species.
virtual void getUnitsStandardConc (double *uA, int k=0, int sizeUA=6) const
Returns the units of the standard and generalized concentrations.
virtual void getActivities (doublereal *ac) const
Get the array of non-dimensional activities at the current solution temperature, pressure, and solution concentration.
Partial Molar Properties of the Solution -----------------
virtual void getChemPotentials (doublereal *mu) const
Get the species chemical potentials. Units: J/kmol.
virtual void getPartialMolarEnthalpies (doublereal *hbar) const
Returns an array of partial molar enthalpies for the species in the mixture.
virtual void getPartialMolarEntropies (doublereal *sbar) const
Returns an array of partial molar entropies of the species in the solution.
virtual void getPartialMolarVolumes (doublereal *vbar) const
Return an array of partial molar volumes for the species in the mixture.
virtual void getPartialMolarCp (doublereal *cpbar) const
Return an array of partial molar heat capacities for the species in the mixture.
Chemical Equilibrium
Chemical equilibrium.
virtual void setToEquilState (const doublereal *lambda_RT)
This method is used by the ChemEquil equilibrium solver.
Critical state properties.
These methods are only implemented by some subclasses.
virtual doublereal critTemperature () const
Critical temperature (K).
virtual doublereal critPressure () const
Critical pressure (Pa).
virtual doublereal critDensity () const
Critical density (kg/m3).
Saturation properties.
These methods are only implemented by subclasses that implement full liquid-vapor equations of state.
virtual doublereal satTemperature (doublereal p) const
Return the saturation temperature given the pressure.
virtual doublereal satPressure (doublereal T) const
Get the saturation pressure for a given temperature.
virtual doublereal vaporFraction () const
Return the fraction of vapor at the current conditions.
virtual void setState_Tsat (doublereal t, doublereal x)
Set the state to a saturated system at a particular temperature.
virtual void setState_Psat (doublereal p, doublereal x)
Set the state to a saturated system at a particular pressure.
Utilities
void setpHScale (const int pHscaleType)
Set the pH scale, which determines the scale for single-ion activity coefficients.
int pHScale () const
Reports the pH scale, which determines the scale for single-ion activity coefficients.
Utilities for Solvent ID and Molality
void setSolvent (size_t k)
This routine sets the index number of the solvent for the phase.
void setMoleFSolventMin (doublereal xmolSolventMIN)
Sets the minimum mole fraction in the molality formulation.
size_t solventIndex () const
Returns the solvent index.
doublereal moleFSolventMin () const
Returns the minimum mole fraction in the molality formulation.
void calcMolalities () const
Calculates the molality of all species and stores the result internally.
void getMolalities (doublereal *const molal) const
This function will return the molalities of the species.
void setMolalities (const doublereal *const molal)
Set the molalities of the solutes in a phase.
void setMolalitiesByName (compositionMap &xMap)
Set the molalities of a phase.
void setMolalitiesByName (const std::string &name)
Set the molalities of a phase.
Activities, Standard States, and Activity Concentrations
The activity \(a_k\) of a species in solution is related to the chemical potential by
\[ \mu_k = \mu_k^0(T) + \hat R T \log a_k. \]
The quantity \(\mu_k^0(T,P)\) is the chemical potential at unit activity, which depends only on temperature and pressure.
int activityConvention () const
This method returns the activity convention.
void getActivityCoefficients (doublereal *ac) const
Get the array of non-dimensional activity coefficients at the current solution temperature, pressure, and solution concentration.
virtual void getMolalityActivityCoefficients (doublereal *acMolality) const
Get the array of non-dimensional molality based activity coefficients at the current solution temperature, pressure, and solution concentration.
virtual double osmoticCoefficient () const
Calculate the osmotic coefficient.
Partial Molar Properties of the Solution
void getElectrochemPotentials (doublereal *mu) const
Get the species electrochemical potentials.
Utilities (VPStandardStateTP)
virtual int standardStateConvention () const
This method returns the convention used in specification of the standard state, of which there are currently two, temperature based, and variable pressure based.
virtual void getdlnActCoeffdlnN_diag (doublereal *dlnActCoeffdlnN_diag) const
Get the array of log concentration-like derivatives of the log activity coefficients.
Partial Molar Properties of the Solution (VPStandardStateTP)
void getChemPotentials_RT (doublereal *mu) const
Get the array of non-dimensional species chemical potentials These are partial molar Gibbs free energies.
Initialization Methods - For Internal use (VPStandardState)
void setVPSSMgr (VPSSMgr *vp_ptr)
set the VPSS Mgr
VPSSMgr * provideVPSSMgr ()
Return a pointer to the VPSSMgr for this phase.
void createInstallPDSS (size_t k, const XML_Node &s, const XML_Node *phaseNode_ptr)
PDSS * providePDSS (size_t k)
const PDSS * providePDSS (size_t k) const
Information Methods
virtual doublereal refPressure () const
Returns the reference pressure in Pa.
virtual doublereal minTemp (size_t k=npos) const
Minimum temperature for which the thermodynamic data for the species or phase are valid.
doublereal Hf298SS (const int k) const
Report the 298 K Heat of Formation of the standard state of one species (J kmol-1)
virtual void modifyOneHf298SS (const int k, const doublereal Hf298New)
Modify the value of the 298 K Heat of Formation of one species in the phase (J kmol-1)
virtual doublereal maxTemp (size_t k=npos) const
Maximum temperature for which the thermodynamic data for the species are valid.
bool chargeNeutralityNecessary () const
Returns the chargeNeutralityNecessity boolean.
Mechanical Properties
virtual void updateDensity ()
Electric Potential
The phase may be at some non-zero electrical potential.
These methods set or get the value of the electric potential.
void setElectricPotential (doublereal v)
Set the electric potential of this phase (V).
doublereal electricPotential () const
Returns the electric potential of this phase (V).
Activities, Standard States, and Activity Concentrations
The activity \(a_k\) of a species in solution is related to the chemical potential by
\[ \mu_k = \mu_k^0(T,P) + \hat R T \log a_k. \]
The quantity \(\mu_k^0(T,P)\) is the standard chemical potential at unit activity, which depends on temperature and pressure, but not on composition.
The activity is dimensionless.
virtual void getLnActivityCoefficients (doublereal *lnac) const
Get the array of non-dimensional molar-based ln activity coefficients at the current solution temperature, pressure, and solution concentration.
Partial Molar Properties of the Solution
virtual void getPartialMolarIntEnergies (doublereal *ubar) const
Return an array of partial molar internal energies for the species in the mixture.
virtual void getdPartialMolarVolumes_dT (doublereal *d_vbar_dT) const
Return an array of derivatives of partial molar volumes wrt temperature for the species in the mixture.
virtual void getdPartialMolarVolumes_dP (doublereal *d_vbar_dP) const
Return an array of derivatives of partial molar volumes wrt pressure for the species in the mixture.
Properties of the Standard State of the Species in the Solution
virtual void getdStandardVolumes_dT (doublereal *d_vol_dT) const
Get the derivative of the molar volumes of the species standard states wrt temperature at the current T and P of the solution.
virtual void getdStandardVolumes_dP (doublereal *d_vol_dP) const
Get the derivative molar volumes of the species standard states wrt pressure at the current T and P of the solution.
Thermodynamic Values for the Species Reference States
virtual void getIntEnergy_RT_ref (doublereal *urt) const
Returns the vector of nondimensional internal Energies of the reference state at the current temperature of the solution and the reference pressure for each species.
virtual void setReferenceComposition (const doublereal *const x)
Sets the reference composition.
virtual void getReferenceComposition (doublereal *const x) const
Gets the reference composition.
Specific Properties
doublereal enthalpy_mass () const
Specific enthalpy.
doublereal intEnergy_mass () const
Specific internal energy.
doublereal entropy_mass () const
Specific entropy.
doublereal gibbs_mass () const
Specific Gibbs function.
doublereal cp_mass () const
Specific heat at constant pressure.
doublereal cv_mass () const
Specific heat at constant volume.
Setting the State
These methods set all or part of the thermodynamic state.
virtual void setState_TPX (doublereal t, doublereal p, const doublereal *x)
Set the temperature (K), pressure (Pa), and mole fractions.
void setState_TPX (doublereal t, doublereal p, compositionMap &x)
Set the temperature (K), pressure (Pa), and mole fractions.
void setState_TPX (doublereal t, doublereal p, const std::string &x)
Set the temperature (K), pressure (Pa), and mole fractions.
void setState_TPY (doublereal t, doublereal p, const doublereal *y)
Set the internally stored temperature (K), pressure (Pa), and mass fractions of the phase.
void setState_TPY (doublereal t, doublereal p, compositionMap &y)
Set the internally stored temperature (K), pressure (Pa), and mass fractions of the phase.
void setState_TPY (doublereal t, doublereal p, const std::string &y)
Set the internally stored temperature (K), pressure (Pa), and mass fractions of the phase.
void setState_PX (doublereal p, doublereal *x)
Set the pressure (Pa) and mole fractions.
void setState_PY (doublereal p, doublereal *y)
Set the internally stored pressure (Pa) and mass fractions.
virtual void setState_HP (doublereal h, doublereal p, doublereal tol=1.e-4)
Set the internally stored specific enthalpy (J/kg) and pressure (Pa) of the phase.
virtual void setState_UV (doublereal u, doublereal v, doublereal tol=1.e-4)
Set the specific internal energy (J/kg) and specific volume (m^3/kg).
virtual void setState_SP (doublereal s, doublereal p, doublereal tol=1.e-4)
Set the specific entropy (J/kg/K) and pressure (Pa).
virtual void setState_SV (doublereal s, doublereal v, doublereal tol=1.e-4)
Set the specific entropy (J/kg/K) and specific volume (m^3/kg).
Chemical Equilibrium
Chemical equilibrium.
void setElementPotentials (const vector_fp &lambda)
Stores the element potentials in the ThermoPhase object.
bool getElementPotentials (doublereal *lambda) const
Returns the element potentials stored in the ThermoPhase object.
Initialization Methods - For Internal Use (ThermoPhase)
void saveSpeciesData (const size_t k, const XML_Node *const data)
Store a reference pointer to the XML tree containing the species data for this phase.
const std::vector< const
XML_Node * > & speciesData () const
Return a pointer to the vector of XML nodes containing the species data for this phase.
void setSpeciesThermo (SpeciesThermo *spthermo)
Install a species thermodynamic property manager.
virtual SpeciesThermo & speciesThermo (int k=-1)
Return a changeable reference to the calculation manager for species reference-state thermodynamic properties.
virtual void initThermoFile (std::string inputFile, std::string id)
virtual void installSlavePhases (Cantera::XML_Node *phaseNode)
Add in species from Slave phases.
Derivatives of Thermodynamic Variables needed for Applications
virtual void getdlnActCoeffds (const doublereal dTds, const doublereal *const dXds, doublereal *dlnActCoeffds) const
Get the change in activity coefficients wrt changes in state (temp, mole fraction, etc) along a line in parameter space or along a line in physical space.
virtual void getdlnActCoeffdlnX_diag (doublereal *dlnActCoeffdlnX_diag) const
Get the array of ln mole fraction derivatives of the log activity coefficients - diagonal component only.
virtual void getdlnActCoeffdlnN_numderiv (const size_t ld, doublereal *const dlnActCoeffdlnN)
Name and ID
Class Phase contains two strings that identify a phase. The ID is the value of the ID attribute of the XML phase node that is used to initialize a phase when it is read. The name field is also initialized to the value of the ID attribute of the XML phase node.
However, the name field may be changed to another value during the course of a calculation. For example, if a phase is located in two places, but has the same constitutive input, the ids of the two phases will be the same, but the names of the two phases may be different.
It is an error to have two phases in a single problem with the same name or the same id (or the name from one phase being the same as the id of another phase). Thus, it is expected that there is a 1-1 correspondence between names and unique phases within a Cantera problem.
std::string id () const
Return the string id for the phase.
void setID (std::string id)
Set the string id for the phase.
std::string name () const
Return the name of the phase.
void setName (std::string nm)
Sets the string name for the phase.
Element and Species Information
std::string elementName (size_t m) const
Name of the element with index m.
size_t elementIndex (std::string name) const
Return the index of element named 'name'.
const std::vector< std::string > & elementNames () const
Return a read-only reference to the vector of element names.
doublereal atomicWeight (size_t m) const
Atomic weight of element m.
doublereal entropyElement298 (size_t m) const
Entropy of the element in its standard state at 298 K and 1 bar.
int atomicNumber (size_t m) const
Atomic number of element m.
int elementType (size_t m) const
Return the element constraint type Possible types include:
int changeElementType (int m, int elem_type)
Change the element type of the mth constraint Reassigns an element type.
const vector_fp & atomicWeights () const
Return a read-only reference to the vector of atomic weights.
size_t nElements () const
Number of elements.
void checkElementIndex (size_t m) const
Check that the specified element index is in range Throws an exception if m is greater than nElements()-1.
void checkElementArraySize (size_t mm) const
Check that an array size is at least nElements() Throws an exception if mm is less than nElements().
doublereal nAtoms (size_t k, size_t m) const
Number of atoms of element m in species k.
void getAtoms (size_t k, double *atomArray) const
Get a vector containing the atomic composition of species k.
size_t speciesIndex (std::string name) const
Returns the index of a species named 'name' within the Phase object.
std::string speciesName (size_t k) const
Name of the species with index k.
std::string speciesSPName (int k) const
Returns the expanded species name of a species, including the phase name This is guaranteed to be unique within a Cantera problem.
const std::vector< std::string > & speciesNames () const
Return a const reference to the vector of species names.
size_t nSpecies () const
Returns the number of species in the phase.
void checkSpeciesIndex (size_t k) const
Check that the specified species index is in range Throws an exception if k is greater than nSpecies()-1.
void checkSpeciesArraySize (size_t kk) const
Check that an array size is at least nSpecies() Throws an exception if kk is less than nSpecies().
Set thermodynamic state
Set the internal thermodynamic state by setting the internally stored temperature, density and species composition. Note that the composition is always set first.
Temperature and density are held constant if not explicitly set.
void setMoleFractionsByName (compositionMap &xMap)
Set the species mole fractions by name.
void setMoleFractionsByName (const std::string &x)
Set the mole fractions of a group of species by name.
void setMassFractionsByName (compositionMap &yMap)
Set the species mass fractions by name.
void setMassFractionsByName (const std::string &x)
Set the species mass fractions by name.
void setState_TRX (doublereal t, doublereal dens, const doublereal *x)
Set the internally stored temperature (K), density, and mole fractions.
void setState_TRX (doublereal t, doublereal dens, compositionMap &x)
Set the internally stored temperature (K), density, and mole fractions.
void setState_TRY (doublereal t, doublereal dens, const doublereal *y)
Set the internally stored temperature (K), density, and mass fractions.
void setState_TRY (doublereal t, doublereal dens, compositionMap &y)
Set the internally stored temperature (K), density, and mass fractions.
void setState_TNX (doublereal t, doublereal n, const doublereal *x)
Set the internally stored temperature (K), molar density (kmol/m^3), and mole fractions.
void setState_TR (doublereal t, doublereal rho)
Set the internally stored temperature (K) and density (kg/m^3)
void setState_TX (doublereal t, doublereal *x)
Set the internally stored temperature (K) and mole fractions.
void setState_TY (doublereal t, doublereal *y)
Set the internally stored temperature (K) and mass fractions.
void setState_RX (doublereal rho, doublereal *x)
Set the density (kg/m^3) and mole fractions.
void setState_RY (doublereal rho, doublereal *y)
Set the density (kg/m^3) and mass fractions.
Composition
void getMoleFractionsByName (compositionMap &x) const
Get the mole fractions by name.
doublereal moleFraction (size_t k) const
Return the mole fraction of a single species.
doublereal moleFraction (std::string name) const
Return the mole fraction of a single species.
doublereal massFraction (size_t k) const
Return the mass fraction of a single species.
doublereal massFraction (std::string name) const
Return the mass fraction of a single species.
void getMoleFractions (doublereal *const x) const
Get the species mole fraction vector.
virtual void setMoleFractions (const doublereal *const x)
Set the mole fractions to the specified values There is no restriction on the sum of the mole fraction vector.
virtual void setMoleFractions_NoNorm (const doublereal *const x)
Set the mole fractions to the specified values without normalizing.
void getMassFractions (doublereal *const y) const
Get the species mass fractions.
const doublereal * massFractions () const
Return a const pointer to the mass fraction array.
virtual void setMassFractions (const doublereal *const y)
Set the mass fractions to the specified values and normalize them.
virtual void setMassFractions_NoNorm (const doublereal *const y)
Set the mass fractions to the specified values without normalizing.
void getConcentrations (doublereal *const c) const
Get the species concentrations (kmol/m^3).
doublereal concentration (const size_t k) const
Concentration of species k.
virtual void setConcentrations (const doublereal *const conc)
Set the concentrations to the specified values within the phase.
const doublereal * moleFractdivMMW () const
Returns a const pointer to the start of the moleFraction/MW array.
Thermodynamic Properties
doublereal temperature () const
Temperature (K).
doublereal molarDensity () const
Molar density (kmol/m^3).
doublereal molarVolume () const
Molar volume (m^3/kmol).
Mean Properties
doublereal mean_X (const doublereal *const Q) const
Evaluate the mole-fraction-weighted mean of an array Q.
doublereal mean_Y (const doublereal *const Q) const
Evaluate the mass-fraction-weighted mean of an array Q.
doublereal meanMolecularWeight () const
The mean molecular weight. Units: (kg/kmol)
doublereal sum_xlogx () const
Evaluate \(\sum_k X_k \log X_k \).
doublereal sum_xlogQ (doublereal *const Q) const
Evaluate \(\sum_k X_k \log Q_k \).
Adding Elements and Species
These methods are used to add new elements or species.
These are not usually called by user programs.
Since species are checked to insure that they are only composed of declared elements, it is necessary to first add all elements before adding any species.
void addElement (const std::string &symbol, doublereal weight=-12345.0)
Add an element.
void addElement (const XML_Node &e)
Add an element from an XML specification.
void addUniqueElement (const std::string &symbol, doublereal weight=-12345.0, int atomicNumber=0, doublereal entropy298=ENTROPY298_UNKNOWN, int elem_type=CT_ELEM_TYPE_ABSPOS)
Add an element, checking for uniqueness The uniqueness is checked by comparing the string symbol.
void addUniqueElement (const XML_Node &e)
Add an element, checking for uniqueness The uniqueness is checked by comparing the string symbol.
void addElementsFromXML (const XML_Node &phase)
Add all elements referenced in an XML_Node tree.
void freezeElements ()
Prohibit addition of more elements, and prepare to add species.
bool elementsFrozen ()
True if freezeElements has been called.
size_t addUniqueElementAfterFreeze (const std::string &symbol, doublereal weight, int atomicNumber, doublereal entropy298=ENTROPY298_UNKNOWN, int elem_type=CT_ELEM_TYPE_ABSPOS)
Add an element after elements have been frozen, checking for uniqueness The uniqueness is checked by comparing the string symbol.
void addSpecies (const std::string &name, const doublereal *comp, doublereal charge=0.0, doublereal size=1.0)
void addUniqueSpecies (const std::string &name, const doublereal *comp, doublereal charge=0.0, doublereal size=1.0)
Add a species to the phase, checking for uniqueness of the name This routine checks for uniqueness of the string name.
Public Attributes
int m_form_A_Debye
Form of the constant outside the Debye-Huckel term called A.
int m_debugCalc
Protected Member Functions
void init (const vector_fp &mw)
void setMolecularWeight (const int k, const double mw)
Set the molecular weight of a single species to a given value.
Protected Attributes
size_t m_indexSolvent
Index of the solvent.
int m_pHScalingType
Scaling to be used for output of single-ion species activity coefficients.
size_t m_indexCLM
Index of the phScale species.
doublereal m_weightSolvent
Molecular weight of the Solvent.
doublereal m_xmolSolventMIN
doublereal m_Mnaught
This is the multiplication factor that goes inside log expressions involving the molalities of species.
vector_fp m_molalities
Current value of the molalities of the species in the phase.
doublereal m_Pcurrent
Current value of the pressure - state variable.
doublereal m_Tlast_ss
The last temperature at which the standard statethermodynamic properties were calculated at.
doublereal m_Plast_ss
The last pressure at which the Standard State thermodynamic properties were calculated at.
doublereal m_P0
VPSSMgr * m_VPSS_ptr
Pointer to the VPSS manager that calculates all of the standard state info efficiently.
std::vector< PDSS * > m_PDSS_storage
Storage for the PDSS objects for the species.
SpeciesThermo * m_spthermo
Pointer to the calculation manager for species reference-state thermodynamic properties.
std::vector< const XML_Node * > m_speciesData
Vector of pointers to the species databases.
doublereal m_phi
Stored value of the electric potential for this phase.
vector_fp m_lambdaRRT
Vector of element potentials.
bool m_hasElementPotentials
Boolean indicating whether there is a valid set of saved element potentials for this phase.
bool m_chargeNeutralityNecessary
Boolean indicating whether a charge neutrality condition is a necessity.
int m_ssConvention
Contains the standard state convention.
std::vector< doublereal > xMol_Ref
Reference Mole Fraction Composition.
size_t m_kk
Number of species in the phase.
size_t m_ndim
Dimensionality of the phase.
vector_fp m_speciesComp
Atomic composition of the species.
vector_fp m_speciesSize
Vector of species sizes.
vector_fp m_speciesCharge
Vector of species charges. length m_kk.
Private Member Functions
void s_updateScaling_pHScaling () const
Apply the current phScale to a set of activity Coefficients.
void s_updateScaling_pHScaling_dT () const
Apply the current phScale to a set of derivatives of the activity Coefficients wrt temperature.
void s_updateScaling_pHScaling_dT2 () const
Apply the current phScale to a set of 2nd derivatives of the activity Coefficients wrt temperature.
void s_updateScaling_pHScaling_dP () const
Apply the current phScale to a set of derivatives of the activity Coefficients wrt pressure.
doublereal s_NBS_CLM_lnMolalityActCoeff () const
Calculate the Chlorine activity coefficient on the NBS scale.
doublereal s_NBS_CLM_dlnMolalityActCoeff_dT () const
Calculate the temperature derivative of the Chlorine activity coefficient on the NBS scale.
doublereal s_NBS_CLM_d2lnMolalityActCoeff_dT2 () const
Calculate the second temperature derivative of the Chlorine activity coefficient on the NBS scale.
doublereal s_NBS_CLM_dlnMolalityActCoeff_dP () const
Calculate the pressure derivative of the Chlorine activity coefficient.
doublereal err (std::string msg) const
Local error routine.
void initLengths ()
Initialize all of the species - dependent lengths in the object.
virtual void applyphScale (doublereal *acMolality) const
Apply the current phScale to a set of activity Coefficients or activities.
void s_update_lnMolalityActCoeff () const
Calculate the natural log of the molality-based activity coefficients.
void s_update_dlnMolalityActCoeff_dT () const
This function calculates the temperature derivative of the natural logarithm of the molality activity coefficients.
void s_update_d2lnMolalityActCoeff_dT2 () const
This function calculates the temperature second derivative of the natural logarithm of the molality activity coefficients.
void s_update_dlnMolalityActCoeff_dP () const
This function calculates the pressure derivative of the natural logarithm of the molality activity coefficients.
void s_updateIMS_lnMolalityActCoeff () const
This function will be called to update the internally stored natural logarithm of the molality activity coefficients.
void s_updatePitzer_lnMolalityActCoeff () const
This function does the main pitzer coefficient calculation.
void s_updatePitzer_dlnMolalityActCoeff_dT () const
Calculates the temperature derivative of the natural logarithm of the molality activity coefficients.
void s_updatePitzer_d2lnMolalityActCoeff_dT2 () const
This function calculates the temperature second derivative of the natural logarithm of the molality activity coefficients.
void s_updatePitzer_dlnMolalityActCoeff_dP () const
Calculates the Pressure derivative of the natural logarithm of the molality activity coefficients.
void s_updatePitzer_CoeffWRTemp (int doDerivs=2) const
Calculates the Pitzer coefficients' dependence on the temperature.
void calc_lambdas (double is) const
Calculate the lambda interactions.
void calc_thetas (int z1, int z2, double *etheta, double *etheta_prime) const
Calculate etheta and etheta_prime.
void counterIJ_setup () const
Set up a counter variable for keeping track of symmetric binary interactions amongst the solute species.
void calcMolalitiesCropped () const
Calculate the cropped molalities.
void readXMLBinarySalt (XML_Node &BinSalt)
Process an XML node called "binarySaltParameters".
void readXMLThetaAnion (XML_Node &BinSalt)
Process an XML node called "thetaAnion".
void readXMLThetaCation (XML_Node &BinSalt)
Process an XML node called "thetaCation".
void readXMLPsiCommonAnion (XML_Node &BinSalt)
Process an XML node called "psiCommonAnion".
void readXMLPsiCommonCation (XML_Node &BinSalt)
Process an XML node called "psiCommonCation".
void readXMLLambdaNeutral (XML_Node &BinSalt)
Process an XML node called "lambdaNeutral".
void readXMLMunnnNeutral (XML_Node &BinSalt)
Process an XML node called "MunnnNeutral".
void readXMLZetaCation (const XML_Node &BinSalt)
Process an XML node called "zetaCation".
void readXMLCroppingCoefficients (const XML_Node &acNode)
Process an XML node called "croppingCoefficients" for the cropping coefficients values.
void calcIMSCutoffParams_ ()
Precalculate the IMS Cutoff parameters for typeCutoff = 2.
void calcMCCutoffParams_ ()
Calculate molality cut-off parameters.
Static Private Member Functions
static int interp_est (std::string estString)
Utility function to assign an integer value from a string for the ElectrolyteSpeciesType field.
Private Attributes
int m_formPitzer
This is the form of the Pitzer parameterization used in this model.
int m_formPitzerTemp
This is the form of the temperature dependence of Pitzer parameterization used in the model.
int m_formGC
Format for the generalized concentration:
vector_int m_electrolyteSpeciesType
Vector containing the electrolyte species type.
vector_fp m_Aionic
a_k = Size of the ionic species in the DH formulation units = meters
double m_IionicMolality
Current value of the ionic strength on the molality scale Associated Salts, if present in the mechanism, don't contribute to the value of the ionic strength in this version of the Ionic strength.
double m_maxIionicStrength
Maximum value of the ionic strength allowed in the calculation of the activity coefficients.
double m_TempPitzerRef
Reference Temperature for the Pitzer formulations.
double m_IionicMolalityStoich
Stoichiometric ionic strength on the molality scale.
double m_A_Debye
A_Debye -> this expression appears on the top of the ln actCoeff term in the general Debye-Huckel expression It depends on temperature.
PDSS * m_waterSS
Water standard state calculator.
double m_densWaterSS
density of standard-state water
WaterProps * m_waterProps
Pointer to the water property calculator.
vector_fp m_expg0_RT
Vector containing the species reference exp(-G/RT) functions at T = m_tlast.
vector_fp m_pe
Vector of potential energies for the species.
vector_fp m_pp
Temporary array used in equilibrium calculations.
vector_fp m_tmpV
vector of size m_kk, used as a temporary holding area.
vector_fp m_speciesCharge_Stoich
Stoichiometric species charge -> This is for calculations of the ionic strength which ignore ion-ion pairing into neutral molecules.
vector_fp m_Beta0MX_ij
Array of 2D data used in the Pitzer/HMW formulation.
vector_fp m_Beta0MX_ij_L
Derivative of Beta0_ij[i][j] wrt T.
vector_fp m_Beta0MX_ij_LL
Derivative of Beta0_ij[i][j] wrt TT.
vector_fp m_Beta0MX_ij_P
Derivative of Beta0_ij[i][j] wrt P.
Array2D m_Beta0MX_ij_coeff
Array of coefficients for Beta0, a variable in Pitzer's papers.
vector_fp m_Beta1MX_ij
vector_fp m_Beta1MX_ij_L
Derivative of Beta1_ij[i][j] wrt T.
vector_fp m_Beta1MX_ij_LL
Derivative of Beta1_ij[i][j] wrt TT.
vector_fp m_Beta1MX_ij_P
Derivative of Beta1_ij[i][j] wrt P.
Array2D m_Beta1MX_ij_coeff
Array of coefficients for Beta1, a variable in Pitzer's papers.
vector_fp m_Beta2MX_ij
Array of 2D data used in the Pitzer/HMW formulation.
vector_fp m_Beta2MX_ij_L
Derivative of Beta2_ij[i][j] wrt T.
vector_fp m_Beta2MX_ij_LL
Derivative of Beta2_ij[i][j] wrt TT.
vector_fp m_Beta2MX_ij_P
Derivative of Beta2_ij[i][j] wrt P.
Array2D m_Beta2MX_ij_coeff
Array of coefficients for Beta2, a variable in Pitzer's papers.
vector_fp m_Alpha1MX_ij
Array of 2D data used in the Pitzer/HMW formulation.
vector_fp m_Alpha2MX_ij
Array of 2D data used in the Pitzer/HMW formulation.
vector_fp m_CphiMX_ij
Array of 2D data used in the Pitzer/HMW formulation.
vector_fp m_CphiMX_ij_L
Derivative of Cphi_ij[i][j] wrt T.
vector_fp m_CphiMX_ij_LL
Derivative of Cphi_ij[i][j] wrt TT.
vector_fp m_CphiMX_ij_P
Derivative of Cphi_ij[i][j] wrt P.
Array2D m_CphiMX_ij_coeff
Array of coefficients for CphiMX, a parameter in the activity coefficient formulation.
vector_fp m_Theta_ij
Array of 2D data for Theta_ij[i][j] in the Pitzer/HMW formulation.
vector_fp m_Theta_ij_L
Derivative of Theta_ij[i][j] wrt T.
vector_fp m_Theta_ij_LL
Derivative of Theta_ij[i][j] wrt TT.
vector_fp m_Theta_ij_P
Derivative of Theta_ij[i][j] wrt P.
Array2D m_Theta_ij_coeff
Array of coefficients for Theta_ij[i][j] in the Pitzer/HMW formulation.
vector_fp m_Psi_ijk
Array of 3D data used in the Pitzer/HMW formulation.
vector_fp m_Psi_ijk_L
Derivative of Psi_ijk[n] wrt T.
vector_fp m_Psi_ijk_LL
Derivative of Psi_ijk[n] wrt TT.
vector_fp m_Psi_ijk_P
Derivative of Psi_ijk[n] wrt P.
Array2D m_Psi_ijk_coeff
Array of coefficients for Psi_ijk[n] in the Pitzer/HMW formulation.
Array2D m_Lambda_nj
Lambda coefficient for the ij interaction.
Array2D m_Lambda_nj_L
Derivative of Lambda_nj[i][j] wrt T. see m_Lambda_ij.
Array2D m_Lambda_nj_LL
Derivative of Lambda_nj[i][j] wrt TT.
Array2D m_Lambda_nj_P
Derivative of Lambda_nj[i][j] wrt P.
Array2D m_Lambda_nj_coeff
Array of coefficients for Lambda_nj[i][j] in the Pitzer/HMW formulation.
vector_fp m_Mu_nnn
Mu coefficient for the self-ternary neutral coefficient.
vector_fp m_Mu_nnn_L
Mu coefficient temperature derivative for the self-ternary neutral coefficient.
vector_fp m_Mu_nnn_LL
Mu coefficient 2nd temperature derivative for the self-ternary neutral coefficient.
vector_fp m_Mu_nnn_P
Mu coefficient pressure derivative for the self-ternary neutral coefficient.
Array2D m_Mu_nnn_coeff
Array of coefficients form_Mu_nnn term.
vector_fp m_lnActCoeffMolal_Scaled
Logarithm of the activity coefficients on the molality scale.
vector_fp m_lnActCoeffMolal_Unscaled
Logarithm of the activity coefficients on the molality scale.
vector_fp m_dlnActCoeffMolaldT_Scaled
Derivative of the Logarithm of the activity coefficients on the molality scale wrt T.
vector_fp m_dlnActCoeffMolaldT_Unscaled
Derivative of the Logarithm of the activity coefficients on the molality scale wrt T.
vector_fp m_d2lnActCoeffMolaldT2_Scaled
Derivative of the Logarithm of the activity coefficients on the molality scale wrt TT.
vector_fp m_d2lnActCoeffMolaldT2_Unscaled
Derivative of the Logarithm of the activity coefficients on the molality scale wrt TT.
vector_fp m_dlnActCoeffMolaldP_Scaled
Derivative of the Logarithm of the activity coefficients on the molality scale wrt P.
vector_fp m_dlnActCoeffMolaldP_Unscaled
Derivative of the Logarithm of the activity coefficients on the molality scale wrt P.
vector_fp m_molalitiesCropped
Cropped and modified values of the molalities used in activity coefficient calculations.
bool m_molalitiesAreCropped
Boolean indicating whether the molalities are cropped or are modified.
vector_int m_CounterIJ
a counter variable for keeping track of symmetric binary interactions amongst the solute species.
double elambda [17]
This is elambda, MEC.
double elambda1 [17]
This is elambda1, MEC.
vector_fp m_gfunc_IJ
Various temporary arrays used in the calculation of the Pitzer activity coefficients.
vector_fp m_g2func_IJ
This is the value of g2(x2) in Pitzer's papers.
vector_fp m_hfunc_IJ
hfunc, was called gprime in Pitzer's paper.
vector_fp m_h2func_IJ
hfunc2, was called gprime in Pitzer's paper.
vector_fp m_BMX_IJ
Intermediate variable called BMX in Pitzer's paper This is the basic cation - anion interaction.
vector_fp m_BMX_IJ_L
Derivative of BMX_IJ wrt T.
vector_fp m_BMX_IJ_LL
Derivative of BMX_IJ wrt TT.
vector_fp m_BMX_IJ_P
Derivative of BMX_IJ wrt P.
vector_fp m_BprimeMX_IJ
Intermediate variable called BprimeMX in Pitzer's paper.
vector_fp m_BprimeMX_IJ_L
Derivative of BprimeMX wrt T.
vector_fp m_BprimeMX_IJ_LL
Derivative of BprimeMX wrt TT.
vector_fp m_BprimeMX_IJ_P
Derivative of BprimeMX wrt P.
vector_fp m_BphiMX_IJ
Intermediate variable called BphiMX in Pitzer's paper.
vector_fp m_BphiMX_IJ_L
Derivative of BphiMX_IJ wrt T.
vector_fp m_BphiMX_IJ_LL
Derivative of BphiMX_IJ wrt TT.
vector_fp m_BphiMX_IJ_P
Derivative of BphiMX_IJ wrt P.
vector_fp m_Phi_IJ
Intermediate variable called Phi in Pitzer's paper.
vector_fp m_Phi_IJ_L
Derivative of m_Phi_IJ wrt T.
vector_fp m_Phi_IJ_LL
Derivative of m_Phi_IJ wrt TT.
vector_fp m_Phi_IJ_P
Derivative of m_Phi_IJ wrt P.
vector_fp m_Phiprime_IJ
Intermediate variable called Phiprime in Pitzer's paper.
vector_fp m_PhiPhi_IJ
Intermediate variable called PhiPhi in Pitzer's paper.
vector_fp m_PhiPhi_IJ_L
Derivative of m_PhiPhi_IJ wrt T.
vector_fp m_PhiPhi_IJ_LL
Derivative of m_PhiPhi_IJ wrt TT.
vector_fp m_PhiPhi_IJ_P
Derivative of m_PhiPhi_IJ wrt P.
vector_fp m_CMX_IJ
Intermediate variable called CMX in Pitzer's paper.
vector_fp m_CMX_IJ_L
Derivative of m_CMX_IJ wrt T.
vector_fp m_CMX_IJ_LL
Derivative of m_CMX_IJ wrt TT.
vector_fp m_CMX_IJ_P
Derivative of m_CMX_IJ wrt P.
vector_fp m_gamma_tmp
Intermediate storage of the activity coefficient itself.
vector_fp IMS_lnActCoeffMolal_
Logarithm of the molal activity coefficients.
int IMS_typeCutoff_
IMS Cutoff type.
doublereal IMS_X_o_cutoff_
value of the solute mole fraction that centers the cutoff polynomials for the cutoff =1 process;
doublereal IMS_gamma_o_min_
gamma_o value for the cutoff process at the zero solvent point
doublereal IMS_gamma_k_min_
gamma_k minimum for the cutoff process at the zero solvent point
doublereal IMS_cCut_
Parameter in the polyExp cutoff treatment having to do with rate of exp decay.
doublereal IMS_slopefCut_
Parameter in the polyExp cutoff treatment.
doublereal IMS_dfCut_
Parameter in the polyExp cutoff treatment having to do with rate of exp decay.
doublereal IMS_efCut_
Parameter in the polyExp cutoff treatment having to do with rate of exp decay.
doublereal IMS_afCut_
Parameter in the polyExp cutoff treatment having to do with rate of exp decay.
doublereal IMS_bfCut_
Parameter in the polyExp cutoff treatment having to do with rate of exp decay.
doublereal IMS_slopegCut_
Parameter in the polyExp cutoff treatment.
doublereal IMS_dgCut_
Parameter in the polyExp cutoff treatment having to do with rate of exp decay.
doublereal IMS_egCut_
Parameter in the polyExp cutoff treatment having to do with rate of exp decay.
doublereal IMS_agCut_
Parameter in the polyExp cutoff treatment having to do with rate of exp decay.
doublereal IMS_bgCut_
Parameter in the polyExp cutoff treatment having to do with rate of exp decay.
doublereal MC_X_o_cutoff_
value of the solvent mole fraction that centers the cutoff polynomials for the cutoff =1 process;
doublereal MC_X_o_min_
gamma_o value for the cutoff process at the zero solvent point
doublereal MC_slopepCut_
Parameter in the Molality Exp cutoff treatment.
doublereal MC_dpCut_
Parameter in the Molality Exp cutoff treatment.
doublereal MC_epCut_
Parameter in the Molality Exp cutoff treatment.
doublereal MC_apCut_
Parameter in the Molality Exp cutoff treatment.
doublereal MC_bpCut_
Parameter in the Molality Exp cutoff treatment.
doublereal MC_cpCut_
Parameter in the Molality Exp cutoff treatment.
doublereal CROP_ln_gamma_o_min
Parameter in the Molality Exp cutoff treatment.
doublereal CROP_ln_gamma_o_max
Parameter in the Molality Exp cutoff treatment.
doublereal CROP_ln_gamma_k_min
Parameter in the Molality Exp cutoff treatment.
doublereal CROP_ln_gamma_k_max
Parameter in the Molality Exp cutoff treatment.
std::vector< int > CROP_speciesCropped_
This is a boolean-type vector indicating whether a species's activity coefficient is in the cropped regime.
Mechanical Equation of State Properties ---------------------
virtual doublereal pressure () const
In this equation of state implementation, the density is a function only of the mole fractions.
virtual void setPressure (doublereal p)
Set the internally stored pressure (Pa) at constant temperature and composition.
virtual doublereal density () const
Returns the current value of the density.
void setDensity (const doublereal rho)
Set the internally stored density (kg/m^3) of the phase.
void setMolarDensity (const doublereal conc)
Set the internally stored molar density (kmol/m^3) for the phase.
virtual void setTemperature (const doublereal temp)
Set the temperature (K)
virtual void setState_TP (doublereal t, doublereal p)
Set the temperature (K) and pressure (Pa)
virtual doublereal isothermalCompressibility () const
The isothermal compressibility.
virtual doublereal thermalExpansionCoeff () const
The thermal expansion coefficient.
void calcDensity ()
Calculate the density of the mixture using the partial molar volumes and mole fractions as input.
Properties of the Standard State of the Species in the Solution
          (VPStandardStateTP)
Within VPStandardStateTP, these properties are calculated via a common routine, _updateStandardStateThermo(), which must be overloaded in inherited objects. The values are cached within this object, and are not recalculated unless the temperature or pressure changes.
virtual void getStandardChemPotentials (doublereal *mu) const
Get the array of chemical potentials at unit activity.
virtual void getEnthalpy_RT (doublereal *hrt) const
Get the nondimensional Enthalpy functions for the species at their standard states at the current T and P of the solution.
virtual void getEntropy_R (doublereal *sr) const
Get the array of nondimensional Enthalpy functions for the standard state species at the current T and P of the solution.
virtual void getGibbs_RT (doublereal *grt) const
Get the nondimensional Gibbs functions for the species at their standard states of solution at the current T and P of the solution.
void getPureGibbs (doublereal *gpure) const
Get the standard state Gibbs functions for each species at the current T and P.
virtual void getIntEnergy_RT (doublereal *urt) const
Returns the vector of nondimensional internal Energies of the standard state at the current temperature and pressure of the solution for each species.
virtual void getCp_R (doublereal *cpr) const
Get the nondimensional Heat Capacities at constant pressure for the standard state of the species at the current T and P.
virtual void getStandardVolumes (doublereal *vol) const
Get the molar volumes of each species in their standard states at the current T and P of the solution.
virtual void updateStandardStateThermo () const
Updates the standard state thermodynamic functions at the current T and P of the solution.
virtual void _updateStandardStateThermo () const
Updates the standard state thermodynamic functions at the current T and P of the solution.
Thermodynamic Values for the Species Reference States (VPStandardStateTP)
virtual void getEnthalpy_RT_ref (doublereal *hrt) const
Returns the vector of nondimensional enthalpies of the reference state at the current temperature of the solution and the reference pressure for the species.
virtual void getGibbs_RT_ref (doublereal *grt) const
Returns the vector of nondimensional Gibbs free energies of the reference state at the current temperature of the solution and the reference pressure for the species.
virtual void getGibbs_ref (doublereal *g) const
virtual void getEntropy_R_ref (doublereal *er) const
virtual void getCp_R_ref (doublereal *cprt) const
virtual void getStandardVolumes_ref (doublereal *vol) const
Get the molar volumes of the species reference states at the current T and P_ref of the solution.
const vector_fp & Gibbs_RT_ref () const
Detailed Description
Class HMWSoln represents a dilute or concentrated liquid electrolyte phase which obeys the Pitzer formulation for nonideality.
As a prerequisite to the specification of thermodynamic quantities, The concentrations of the ionic species are assumed to obey the electroneutrality condition.
Specification of Species Standard State Properties
The solvent is assumed to be liquid water. A real model for liquid water (IAPWS 1995 formulation) is used as its standard state. All standard state properties for the solvent are based on this real model for water, and involve function calls to the object that handles the real water model, Cantera::WaterPropsIAPWS.
The standard states for solutes are on the unit molality basis. Therefore, in the documentation below, the normal \(o \) superscript is replaced with the \(\triangle \) symbol. The reference state symbol is now \(\triangle, ref \).
It is assumed that the reference state thermodynamics may be obtained by a pointer to a populated species thermodynamic property manager class (see ThermoPhase::m_spthermo). How to relate pressure changes to the reference state thermodynamics is resolved at this level.
For solutes that rely on ThermoPhase::m_spthermo, are assumed to have an incompressible standard state mechanical property. In other words, the molar volumes are independent of temperature and pressure.
For these incompressible, standard states, the molar internal energy is independent of pressure. Since the thermodynamic properties are specified by giving the standard-state enthalpy, the term \(P_0 \hat v\) is subtracted from the specified molar enthalpy to compute the molar internal energy. The entropy is assumed to be independent of the pressure.
The enthalpy function is given by the following relation.
\[ \raggedright h^\triangle_k(T,P) = h^{\triangle,ref}_k(T) + \tilde{v}_k \left(P - P_{ref} \right) \]
For an incompressible, stoichiometric substance, the molar internal energy is independent of pressure. Since the thermodynamic properties are specified by giving the standard-state enthalpy, the term \(P_{ref} \tilde v\) is subtracted from the specified reference molar enthalpy to compute the molar internal energy.
\[ u^\triangle_k(T,P) = h^{\triangle,ref}_k(T) - P_{ref} \tilde{v}_k \]
The solute standard state heat capacity and entropy are independent of pressure. The solute standard state gibbs free energy is obtained from the enthalpy and entropy functions.
The vector Phase::m_speciesSize[] is used to hold the base values of species sizes. These are defined as the molar volumes of species at infinite dilution at 300 K and 1 atm of water. m_speciesSize are calculated during the initialization of the HMWSoln object and are then not touched.
The current model assumes that an incompressible molar volume for all solutes. The molar volume for the water solvent, however, is obtained from a pure water equation of state, waterSS. Therefore, the water standard state varies with both T and P. It is an error to request standard state water properties at a T and P where the water phase is not a stable phase, i.e., beyond its spinodal curve.
Specification of Solution Thermodynamic Properties
Chemical potentials of the solutes, \(\mu_k \), and the solvent, \(\mu_o \), which are based on the molality form, have the following general format:
\[ \mu_k = \mu^{\triangle}_k(T,P) + R T ln(\gamma_k^{\triangle} \frac{m_k}{m^\triangle}) \]
\[ \mu_o = \mu^o_o(T,P) + RT ln(a_o) \]
where \(\gamma_k^{\triangle} \) is the molality based activity coefficient for species \(k\).
Individual activity coefficients of ions can not be independently measured. Instead, only binary pairs forming electroneutral solutions can be measured. This problem leads to a redundancy in the evaluation of species standard state properties. The redundancy issue is resolved by setting the standard state chemical potential enthalpy, entropy, and volume for the hydrogen ion, H+, to zero, for every temperature and pressure. After this convention is applied, all other standard state properties of ionic species contain meaningful information.
Ionic Strength
Most of the parameterizations within the model use the ionic strength as a key variable. The ionic strength, \(I\) is defined as follows
\[ I = \frac{1}{2} \sum_k{m_k z_k^2} \]
\(m_k \) is the molality of the kth species. \(z_k \) is the charge of the kth species. Note, the ionic strength is a defined units quantity. The molality has defined units of gmol kg-1, and therefore the ionic strength has units of sqrt(gmol kg-1).
In some instances, from some authors, a different formulation is used for the ionic strength in the equations below. The different formulation is due to the possibility of the existence of weak acids and how association wrt to the weak acid equilibrium relation affects the calculation of the activity coefficients via the assumed value of the ionic strength.
If we are to assume that the association reaction doesn't have an effect on the ionic strength, then we will want to consider the associated weak acid as in effect being fully dissociated, when we calculate an effective value for the ionic strength. We will call this calculated value, the stoichiometric ionic strength, \(I_s \), putting a subscript s to denote it from the more straightforward calculation of \(I \).
\[ I_s = \frac{1}{2} \sum_k{m_k^s z_k^2} \]
Here, \(m_k^s \) is the value of the molalities calculated assuming that all weak acid-base pairs are in their fully dissociated states. This calculation may be simplified by considering that the weakly associated acid may be made up of two charged species, k1 and k2, each with their own charges, obeying the following relationship:
\[ z_k = z_{k1} + z_{k2} \]
Then, we may only need to specify one charge value, say, \(z_{k1}\), the cation charge number, in order to get both numbers, since we have already specified \(z_k \) in the definition of original species. Then, the stoichiometric ionic strength may be calculated via the following formula.
\[ I_s = \frac{1}{2} \left(\sum_{k,ions}{m_k z_k^2}+ \sum_{k,weak_assoc}(m_k z_{k1}^2 + m_k z_{k2}^2) \right) \]
The specification of which species are weakly associated acids is made in the input file via the stoichIsMods XML block, where the charge for k1 is also specified. An example is given below:
<stoichIsMods>
      NaCl(aq):-1.0
</stoichIsMods>
Because we need the concept of a weakly associated acid in order to calculated \(I_s \) we need to catalog all species in the phase. This is done using the following categories:
cEST_solvent : Solvent species (neutral)
cEST_chargedSpecies Charged species (charged)
cEST_weakAcidAssociated Species which can break apart into charged species. It may or may not be charged. These may or may not be be included in the species solution vector.
cEST_strongAcidAssociated Species which always breaks apart into charged species. It may or may not be charged. Normally, these aren't included in the speciation vector.
cEST_polarNeutral Polar neutral species
cEST_nonpolarNeutral Non polar neutral species
Polar and non-polar neutral species are differentiated, because some additions to the activity coefficient expressions distinguish between these two types of solutes. This is the so-called salt-out effect.
The type of species is specified in the electrolyteSpeciesType XML block. Note, this is not considered a part of the specification of the standard state for the species, at this time. Therefore, this information is put under the activityCoefficient XML block. An example is given below
<electrolyteSpeciesType>
       H2L(L):solvent
       H+:chargedSpecies
       NaOH(aq):weakAcidAssociated
       NaCl(aq):strongAcidAssociated
       NH3(aq):polarNeutral
       O2(aq):nonpolarNeutral
</electrolyteSpeciesType>
Much of the species electrolyte type information is inferred from other information in the input file. For example, as species which is charged is given the "chargedSpecies" default category. A neutral solute species is put into the "nonpolarNeutral" category by default.
Specification of the Excess Gibbs Free Energy
Pitzer's formulation may best be represented as a specification of the excess gibbs free energy, \(G^{ex} \), defined as the deviation of the total gibbs free energy from that of an ideal molal solution.
\[ G = G^{id} + G^{ex} \]
The ideal molal solution contribution, not equal to an ideal solution contribution and in fact containing a singularity at the zero solvent mole fraction limit, is given below.
\[ G^{id} = n_o \mu^o_o + \sum_{k\ne o} n_k \mu_k^{\triangle} + \tilde{M}_o n_o (RT (\sum{m_i(\ln(m_i)-1)})) \]
From the excess Gibbs free energy formulation, the activity coefficient expression and the osmotic coefficient expression for the solvent may be defined, by taking the appropriate derivatives. Using this approach guarantees that the entire system will obey the Gibbs-Duhem relations.
Pitzer employs the following general expression for the excess Gibbs free energy
\[ \begin{array}{cclc} \frac{G^{ex}}{\tilde{M}_o n_o RT} &= & \left(\frac{4A_{Debye}I}{3b} \right) \ln(1 + b \sqrt{I}) + 2 \sum_c \sum_a m_c m_a B_{ca} + \sum_c \sum_a m_c m_a Z C_{ca} \\&& + \sum_{c < c'} \sum m_c m_{c'} \left[ 2 \Phi_{c{c'}} + \sum_a m_a \Psi_{c{c'}a} \right] + \sum_{a < a'} \sum m_a m_{a'} \left[ 2 \Phi_{a{a'}} + \sum_c m_c \Psi_{a{a'}c} \right] \\&& + 2 \sum_n \sum_c m_n m_c \lambda_{nc} + 2 \sum_n \sum_a m_n m_a \lambda_{na} + 2 \sum_{n < n'} \sum m_n m_{n'} \lambda_{n{n'}} + \sum_n m^2_n \lambda_{nn} \end{array} \]
a is a subscript over all anions, c is a subscript extending over all cations, and i is a subscript that extends over all anions and cations. n is a subscript that extends only over neutral solute molecules. The second line contains cross terms where cations affect cations and/or cation/anion pairs, and anions affect anions or cation/anion pairs. Note part of the coefficients, \(\Phi_{c{c'}} \) and \(\Phi_{a{a'}} \) stem from the theory of unsymmetrical mixing of electrolytes with different charges. This theory depends on the total ionic strength of the solution, and therefore, \(\Phi_{c{c'}} \) and \(\Phi_{a{a'}} \) will depend on I, the ionic strength. \(B_{ca}\) is a strong function of the total ionic strength, I, of the electrolyte. The rest of the coefficients are assumed to be independent of the molalities or ionic strengths. However, all coefficients are potentially functions of the temperature and pressure of the solution.
A is the Debye-Huckel constant. Its specification is described in its own section below.
\(I\) is the ionic strength of the solution, and is given by:
\[ I = \frac{1}{2} \sum_k{m_k z_k^2} \]
In contrast to several other Debye-Huckel implementations (see \ref DebyeHuckel), the
parameter \form#292 in the above equation is a constant that
does not vary with respect to ion identity. This is an important simplification
as it avoids troubles with satisfaction of the Gibbs-Duhem analysis.
The function \form#293 is given by
\[ Z = \sum_i m_i \left| z_i \right| \]
The value of \form#291 is given by the following function
\[ B_{ca} = \beta^{(0)}_{ca} + \beta^{(1)}_{ca} g(\alpha^{(1)}_{ca} \sqrt{I}) + \beta^{(2)}_{ca} g(\alpha^{(2)}_{ca} \sqrt{I}) \]
where
\[ g(x) = 2 \frac{(1 - (1 + x)\exp[-x])}{x^2} \]
The formulation for \form#291 combined with the formulation of the
Debye-Huckel term in the eqn. for the excess Gibbs free energy stems
essentially from an empirical fit to the ionic strength dependent data
based over a wide sampling of binary electrolyte systems. \form#297,
\(\lambda_{nc} \), \(\lambda_{na} \), \(\lambda_{nn} \), \(\Psi_{c{c'}a} \), \(\Psi_{a{a'}c} \) are experimentally derived coefficients that may have pressure and/or temperature dependencies. The \(\Phi_{c{c'}} \) and \(\Phi_{a{a'}} \) formulations are slightly more complicated. \(b \) is a universal constant defined to be equal to \(1.2\ kg^{1/2}\ gmol^{-1/2} \). The exponential coefficient \(\alpha^{(1)}_{ca} \) is usually fixed at \(\alpha^{(1)}_{ca} = 2.0\ kg^{1/2} gmol^{-1/2}\) except for 2-2 electrolytes, while other parameters were fit to experimental data. For 2-2 electrolytes, \(\alpha^{(1)}_{ca} = 1.4\ kg^{1/2}\ gmol^{-1/2}\) is used in combination with either \(\alpha^{(2)}_{ca} = 12\ kg^{1/2}\ gmol^{-1/2}\) or \(\alpha^{(2)}_{ca} = k A_\psi \), where k is a constant. For electrolytes other than 2-2 electrolytes the \(\beta^{(2)}_{ca} g(\alpha^{(2)}_{ca} \sqrt{I}) \) term is not used in the fitting procedure; it is only used for divalent metal solfates and other high-valence electrolytes which exhibit significant association at low ionic strengths.
The \(\beta^{(0)}_{ca} \), \(\beta^{(1)}_{ca}\), \(\beta^{(2)}_{ca} \), and \(C_{ca} \) binary coefficients are referred to as ion-interaction or Pitzer parameters. These Pitzer parameters may vary with temperature and pressure but they do not depend on the ionic strength. Their values and temperature derivatives of their values have been tabulated for a range of electrolytes
The \(\Phi_{c{c'}} \) and \(\Phi_{a{a'}} \) contributions, which capture cation-cation and anion-anion interactions, also have an ionic strength dependence.
Ternary contributions \(\Psi_{c{c'}a} \) and \(\Psi_{a{a'}c} \) have been measured also for some systems. The success of the Pitzer method lies in its ability to model nonlinear activity coefficients of complex multicomponent systems with just binary and minor ternary contributions, which can be independently measured in binary or ternary subsystems.
Multicomponent Activity Coefficients for Solutes
The formulas for activity coefficients of solutes may be obtained by taking the following derivative of the excess Gibbs Free Energy formulation described above:
\[ \ln(\gamma_k^\triangle) = \frac{d\left(\frac{G^{ex}}{M_o n_o RT} \right)}{d(m_k)}\Bigg|_{n_i} \]
 In the formulas below the following conventions are used. The subscript <I>M</I> refers
 to a particular cation. The subscript X refers to a particular anion, whose
 activity is being currently evaluated. the subscript <I>a</I> refers to a summation
 over all anions in the solution, while the subscript <I>c</I> refers to a summation
 over all cations in the solutions.
  The activity coefficient for a particular cation <I>M</I> is given by
\[ \ln(\gamma_M^\triangle) = -z_M^2(F) + \sum_a m_a \left(2 B_{Ma} + Z C_{Ma} \right) + z_M \left(\sum_a \sum_c m_a m_c C_{ca} \right) + \sum_c m_c \left[ 2 \Phi_{Mc} + \sum_a m_a \Psi_{Mca} \right] + \sum_{a < a'} \sum m_a m_{a'} \Psi_{Ma{a'}} + 2 \sum_n m_n \lambda_{nM} \]
  The activity coefficient for a particular anion <I>X</I> is given by
\[ \ln(\gamma_X^\triangle) = -z_X^2(F) + \sum_a m_c \left(2 B_{cX} + Z C_{cX} \right) + \left|z_X \right| \left(\sum_a \sum_c m_a m_c C_{ca} \right) + \sum_a m_a \left[ 2 \Phi_{Xa} + \sum_c m_c \Psi_{cXa} \right] + \sum_{c < c'} \sum m_c m_{c'} \Psi_{c{c'}X} + 2 \sum_n m_n \lambda_{nM} \]
where the function \(F \) is given by
\[ F = - A_{\phi} \left[ \frac{\sqrt{I}}{1 + b \sqrt{I}} + \frac{2}{b} \ln{\left(1 + b\sqrt{I}\right)} \right] + \sum_a \sum_c m_a m_c B'_{ca} + \sum_{c < c'} \sum m_c m_{c'} \Phi'_{c{c'}} + \sum_{a < a'} \sum m_a m_{a'} \Phi'_{a{a'}} \]
We have employed the definition of \form#318, also used by Pitzer
which is equal to
\[ A_{\phi} = \frac{A_{Debye}}{3} \]
In the above formulas, \form#320  and \form#321 are the
ionic strength derivatives of \form#289  and \form#290,
respectively.
The function \form#322 is defined as:
\[ B'_{MX} = \left(\frac{\beta^{(1)}_{MX} h(\alpha^{(1)}_{MX} \sqrt{I})}{I} \right) \left(\frac{\beta^{(2)}_{MX} h(\alpha^{(2)}_{MX} \sqrt{I})}{I} \right) \]
where \(h(x) \) is defined as
\[ h(x) = g'(x) \frac{x}{2} = \frac{2\left(1 - \left(1 + x + \frac{x^2}{2} \right)\exp(-x) \right)}{x^2} \]
The activity coefficient for neutral species <I>N</I> is given by
\[ \ln(\gamma_N^\triangle) = 2 \left(\sum_i m_i \lambda_{iN}\right) \]
Activity of the Water Solvent
The activity for the solvent water, \(a_o \), is not independent and must be determined either from the Gibbs-Duhem relation or from taking the appropriate derivative of the same excess Gibbs free energy function as was used to formulate the solvent activity coefficients. Pitzer's description follows the later approach to derive a formula for the osmotic coefficient, \(\phi \).
\[ \phi - 1 = - \left(\frac{d\left(\frac{G^{ex}}{RT} \right)}{d(\tilde{M}_o n_o)} \right) \frac{1}{\sum_{i \ne 0} m_i} \]
The osmotic coefficient may be related to the water activity by the following relation:
\[ \phi = - \frac{1}{\tilde{M}_o \sum_{i \neq o} m_i} \ln(a_o) = - \frac{n_o}{\sum_{i \neq o}n_i} \ln(a_o) \]
The result is the following
\[ \begin{array}{ccclc} \phi - 1 &= & \frac{2}{\sum_{i \ne 0} m_i} \bigg[ & - A_{\phi} \frac{I^{3/2}}{1 + b \sqrt{I}} + \sum_c \sum_a m_c m_a \left(B^{\phi}_{ca} + Z C_{ca}\right) \\&&& + \sum_{c < c'} \sum m_c m_{c'} \left[ \Phi^{\phi}_{c{c'}} + \sum_a m_a \Psi_{c{c'}a} \right] + \sum_{a < a'} \sum m_a m_{a'} \left[ \Phi^{\phi}_{a{a'}} + \sum_c m_c \Psi_{a{a'}c} \right] \\&&& + \sum_n \sum_c m_n m_c \lambda_{nc} + \sum_n \sum_a m_n m_a \lambda_{na} + \sum_{n < n'} \sum m_n m_{n'} \lambda_{n{n'}} + \frac{1}{2} \left(\sum_n m^2_n \lambda_{nn}\right) \bigg] \end{array} \]
It can be shown that the expression
\[ B^{\phi}_{ca} = \beta^{(0)}_{ca} + \beta^{(1)}_{ca} \exp{(- \alpha^{(1)}_{ca} \sqrt{I})} + \beta^{(2)}_{ca} \exp{(- \alpha^{(2)}_{ca} \sqrt{I})} \]
is consistent with the expression \(B_{ca} \) in the \(G^{ex} \) expression after carrying out the derivative wrt \(m_M \).
Also taking into account that \({\Phi}_{c{c'}} \) and \({\Phi}_{a{a'}} \) has an ionic strength dependence.
\[ \Phi^{\phi}_{c{c'}} = {\Phi}_{c{c'}} + I \frac{d{\Phi}_{c{c'}}}{dI} \]
\[ \Phi^{\phi}_{a{a'}} = \Phi_{a{a'}} + I \frac{d\Phi_{a{a'}}}{dI} \]
Temperature and Pressure Dependence of the Pitzer Parameters
In general most of the coefficients introduced in the previous section may have a temperature and pressure dependence. The temperature and pressure dependence of these coefficients strongly influence the value of the excess Enthalpy and excess Volumes of Pitzer solutions. Therefore, these are readily measurable quantities. HMWSoln provides several different methods for putting these dependencies into the coefficients. HMWSoln has an implementation described by Silverter and Pitzer (1977), which was used to fit experimental data for NaCl over an extensive range, below the critical temperature of water. They found a temperature functional form for fitting the 3 following coefficients that describe the Pitzer parameterization for a single salt to be adequate to describe how the excess gibbs free energy values for the binary salt changes with respect to temperature. The following functional form was used to fit the temperature dependence of the Pitzer Coefficients for each cation - anion pair, M X.
\[ \beta^{(0)}_{MX} = q^{b0}_0 + q^{b0}_1 \left(T - T_r \right) + q^{b0}_2 \left(T^2 - T_r^2 \right) + q^{b0}_3 \left(\frac{1}{T} - \frac{1}{T_r}\right) + q^{b0}_4 \ln \left(\frac{T}{T_r} \right) \]
\[ \beta^{(1)}_{MX} = q^{b1}_0 + q^{b1}_1 \left(T - T_r \right) + q^{b1}_{2} \left(T^2 - T_r^2 \right) \]
\[ C^{\phi}_{MX} = q^{Cphi}_0 + q^{Cphi}_1 \left(T - T_r \right) + q^{Cphi}_2 \left(T^2 - T_r^2 \right) + q^{Cphi}_3 \left(\frac{1}{T} - \frac{1}{T_r}\right) + q^{Cphi}_4 \ln \left(\frac{T}{T_r} \right) \]
where
\[ C^{\phi}_{MX} = 2 {\left| z_M z_X \right|}^{1/2} C_{MX} \]
In later papers, Pitzer has added additional temperature dependencies to all of the other remaining second and third order virial coefficients. Some of these dependencies are justified and motivated by theory. Therefore, a formalism wherein all of the coefficients in the base theory have temperature dependencies associated with them has been implemented within the HMWSoln object. Much of the formalism, however, has been unexercised.
In the HMWSoln object, the temperature dependence of the Pitzer parameters are specified in the following way.
PIZTER_TEMP_CONSTANT - string name "CONSTANT"
Assumes that all coefficients are independent of temperature and pressure
PIZTER_TEMP_COMPLEX1 - string name "COMPLEX" or "COMPLEX1"
Uses the full temperature dependence for the \(\beta^{(0)}_{MX} \) (5 coeffs), the \(\beta^{(1)}_{MX} \) (3 coeffs), and \(C^{\phi}_{MX} \) (5 coeffs) parameters described above.
PITZER_TEMP_LINEAR - string name "LINEAR"
Uses just the temperature dependence for the \(\beta^{(0)}_{MX} \), the \(\beta^{(1)}_{MX} \), and \(C^{\phi}_{MX} \) coefficients described above. There are 2 coefficients for each term.
The temperature dependence is specified in an attributes field in the activityCoefficients XML block, called TempModel . Permissible values for that attribute are CONSTANT, COMPLEX1, and LINEAR.
The specification of the binary interaction between a cation and an anion is given by the coefficients, \(B_{MX}\) and \(C_{MX}\) The specification of \(B_{MX}\) is a function of \(\beta^{(0)}_{MX} \), \(\beta^{(1)}_{MX} \), \(\beta^{(2)}_{MX} \), \(\alpha^{(1)}_{MX} \), and \(\alpha^{(2)}_{MX} \). \(C_{MX}\) is calculated from \(C^{\phi}_{MX} \) from the formula above. All of the underlying coefficients are specified in the XML element block binarySaltParameters , which has the attribute cation and anion to identify the interaction. XML elements named beta0, beta1, beta2, Cphi, Alpha1, Alpha2 within each binarySaltParameters block specify the parameters. Within each of these blocks multiple parameters describing temperature or pressure dependence are serially listed in the order that they appear in the equation in this document. An example of the beta0 block that fits the COMPLEX1 temperature dependence given above is
<binarySaltParameters cation="Na+" anion="OH-">
  <beta0> q0, q1, q2, q3, q4  </beta0>
</binarySaltParameters>
The parameters for \(\beta^{(0)}\) fit the following equation:
\[ \beta^{(0)} = q_0^{{\beta}0} + q_1^{{\beta}0} \left(T - T_r \right) + q_2^{{\beta}0} \left(T^2 - T_r^2 \right) + q_3^{{\beta}0} \left(\frac{1}{T} - \frac{1}{T_r} \right) + q_4^{{\beta}0} \ln \left(\frac{T}{T_r} \right) \]
This same COMPLEX1 temperature dependence given above is used for the following parameters: \(\beta^{(0)}_{MX} \), \(\beta^{(1)}_{MX} \), \(\beta^{(2)}_{MX} \), \(\Theta_{cc'} \), \(\Theta_{aa'} \), \(\Psi_{c{c'}a} \) and \(\Psi_{ca{a'}} \).
Like-Charged Binary Ion Parameters and the Mixing Parameters
The previous section contained the functions, \(\Phi_{c{c'}} \), \(\Phi_{a{a'}} \) and their derivatives wrt the ionic strength, \(\Phi'_{c{c'}} \) and \(\Phi'_{a{a'}} \). Part of these terms come from theory.
Since like charged ions repel each other and are generally not near each other, the virial coefficients for same-charged ions are small. However, Pitzer doesn't ignore these in his formulation. Relatively larger and longer range terms between like-charged ions exist however, which appear only for unsymmetrical mixing of same-sign charged ions with different charges. \(\Phi_{ij} \), where \(ij \) is either \(a{a'} \) or \(c{c'} \) is given by
\[ {\Phi}_{ij} = \Theta_{ij} + \,^E \Theta_{ij}(I) \]
\(\Theta_{ij} \) is the small virial coefficient expansion term. Dependent in general on temperature and pressure, its ionic strength dependence is ignored in Pitzer's approach. \(\,^E\Theta_{ij}(I) \) accounts for the electrostatic unsymmetrical mixing effects and is dependent only on the charges of the ions i, j, the total ionic strength and on the dielectric constant and density of the solvent. This seems to be a relatively well-documented part of the theory. They theory below comes from Pitzer summation (Pitzer) in the appendix. It's also mentioned in Bethke's book (Bethke), and the equations are summarized in Harvie & Weare (1980). Within the code, \(\,^E\Theta_{ij}(I) \) is evaluated according to the algorithm described in Appendix B [Pitzer] as
\[ \,^E\Theta_{ij}(I) = \left(\frac{z_i z_j}{4I} \right) \left(J(x_{ij}) - \frac{1}{2} J(x_{ii}) - \frac{1}{2} J(x_{jj}) \right) \]
where \(x_{ij} = 6 z_i z_j A_{\phi} \sqrt{I} \) and
\[ J(x) = \frac{1}{x} \int_0^{\infty}{\left(1 + q + \frac{1}{2} q^2 - e^q \right) y^2 dy} \]
and \(q = - (\frac{x}{y}) e^{-y} \). \(J(x) \) is evaluated by numerical integration.
The \(\Theta_{ij} \) term is a constant that is specified by the XML element thetaCation and thetaAnion , which has the attribute cation1 , cation2 and anion1 , anion2 respectively to identify the interaction. No temperature or pressure dependence of this parameter is currently allowed. An example of the block is presented below.
<thetaCation cation1="Na+" cation2="H+">
           <Theta> 0.036 </Theta>
</thetaCation>
Ternary Pitzer Parameters
The \(\Psi_{c{c'}a} \) and \(\Psi_{ca{a'}} \) terms represent ternary interactions between two cations and an anion and two anions and a cation, respectively. In Pitzer's implementation these terms are usually small in absolute size. Currently these parameters do not have any dependence on temperature, pressure, or ionic strength.
Their values are input using the XML element psiCommonCation and psiCommonAnion . The species id's are specified in attribute fields in the XML element. The fields cation, anion1, and anion2 are used for psiCommonCation. The fields anion, cation1 and cation2 are used for psiCommonAnion. An example block is given below. The Theta field below is a duplicate of the thetaAnion field mentioned above. The two fields are input into the same block for convenience, and because their data are highly correlated, in practice. It is an error for the two blocks to specify different information about thetaAnion (or thetaCation) in different blocks. It's ok to specify duplicate but consistent information in multiple blocks.
<psiCommonCation cation="Na+" anion1="Cl-" anion2="OH-">
      <Theta> -0.05 </Theta>
      <Psi> -0.006 </Psi>
</psiCommonCation>
Treatment of Neutral Species
Binary virial-coefficient-like interactions between two neutral species may be specified in the \(\lambda_{mn} \) terms that appear in the formulas above. Currently these interactions are independent of temperature, pressure, and ionic strength. Also, currently, the neutrality of the species are not checked. Therefore, this interaction may involve charged species in the solution as well. The identity of the species is specified by the species1 and species2 attributes to the XML lambdaNeutral node. These terms are symmetrical; species1 and species2 may be reversed and the term will be the same. An example is given below.
<lambdaNeutral species1="CO2" species2="CH4">
      <lambda> 0.05 </lambda>
</lambdaNeutral>
Example of the Specification of Parameters for the Activity Coefficients
An example is given below.
An example activityCoefficients XML block for this formulation is supplied below
  <activityCoefficients model="Pitzer" TempModel="complex1">
              <!-- Pitzer Coefficients
                   These coefficients are from Pitzer's main
                   paper, in his book.
                -->
              <A_Debye model="water" />
              <ionicRadius default="3.042843"  units="Angstroms">
              </ionicRadius>
              <binarySaltParameters cation="Na+" anion="Cl-">
                <beta0> 0.0765, 0.008946, -3.3158E-6,
                        -777.03, -4.4706
                </beta0>
                <beta1> 0.2664, 6.1608E-5, 1.0715E-6, 0.0, 0.0 </beta1>
                <beta2> 0.0,   0.0, 0.0, 0.0, 0.0  </beta2>
                <Cphi> 0.00127, -4.655E-5, 0.0,
                       33.317, 0.09421
                </Cphi>
                <Alpha1> 2.0 </Alpha1>
              </binarySaltParameters>
              <binarySaltParameters cation="H+" anion="Cl-">
                <beta0> 0.1775, 0.0, 0.0, 0.0, 0.0 </beta0>
                <beta1> 0.2945, 0.0, 0.0, 0.0, 0.0 </beta1>
                <beta2> 0.0,    0.0, 0.0, 0.0, 0.0 </beta2>
                <Cphi> 0.0008, 0.0, 0.0, 0.0, 0.0 </Cphi>
                <Alpha1> 2.0 </Alpha1>
              </binarySaltParameters>
              <binarySaltParameters cation="Na+" anion="OH-">
                <beta0> 0.0864, 0.0, 0.0, 0.0, 0.0 </beta0>
                <beta1> 0.253,  0.0, 0.0  0.0, 0.0 </beta1>
                <beta2> 0.0     0.0, 0.0, 0.0, 0.0 </beta2>
                <Cphi> 0.0044,  0.0, 0.0, 0.0, 0.0 </Cphi>
                <Alpha1> 2.0 </Alpha1>
              </binarySaltParameters>
              <thetaAnion anion1="Cl-" anion2="OH-">
                <Theta> -0.05,  0.0, 0.0, 0.0, 0.0 </Theta>
              </thetaAnion>
              <psiCommonCation cation="Na+" anion1="Cl-" anion2="OH-">
                <Theta> -0.05,  0.0, 0.0, 0.0, 0.0 </Theta>
                <Psi> -0.006 </Psi>
              </psiCommonCation>
              <thetaCation cation1="Na+" cation2="H+">
                <Theta> 0.036,  0.0, 0.0, 0.0, 0.0 </Theta>
              </thetaCation>
              <psiCommonAnion anion="Cl-" cation1="Na+" cation2="H+">
                <Theta> 0.036,  0.0, 0.0, 0.0, 0.0 </Theta>
                <Psi> -0.004 </Psi>
              </psiCommonAnion>
     </activityCoefficients>
Specification of the Debye-Huckel Constant
In the equations above, the formula for \(A_{Debye} \) is needed. The HMWSoln object uses two methods for specifying these quantities. The default method is to assume that \(A_{Debye} \) is a constant, given in the initialization process, and stored in the member double, m_A_Debye. Optionally, a full water treatment may be employed that makes \(A_{Debye} \) a full function of T and P and creates nontrivial entries for the excess heat capacity, enthalpy, and excess volumes of solution.
\[ A_{Debye} = \frac{F e B_{Debye}}{8 \pi \epsilon R T} {\left(C_o \tilde{M}_o \right)}^{1/2} \]
where
\[ B_{Debye} = \frac{F} {{(\frac{\epsilon R T}{2})}^{1/2}} \]
Therefore:
\[ A_{Debye} = \frac{1}{8 \pi} {\left(\frac{2 N_a \rho_o}{1000}\right)}^{1/2} {\left(\frac{N_a e^2}{\epsilon R T }\right)}^{3/2} \]
         Units = sqrt(kg/gmol)
  where
   -  \form#238 is Avogadro's number
   -  \form#239 is the density of water
   -  \form#240 is the electronic charge
   -  \form#241 is the permittivity of water
        where \form#242 is the dielectric constant of water,
        and \form#243 is the permittivity of free space.
   -  \form#244 is the density of the solvent in its standard state.
         Nominal value at 298 K and 1 atm = 1.172576 (kg/gmol)<SUP>1/2</SUP>
               based on:
              -    \form#245 = 78.54
                        (water at 25C)
              -   T = 298.15 K
              -   B_Debye = 3.28640E9 (kg/gmol)<SUP>1/2</SUP> m<SUP>-1</SUP>
An example of a fixed value implementation is given below.
<activityCoefficients model="Pitzer">
      <!-- A_Debye units = sqrt(kg/gmol)  -->
      <A_Debye> 1.172576 </A_Debye>
      <!-- object description continues -->
</activityCoefficients>
An example of a variable value implementation within the HMWSoln object is given below. The model attribute, "water", triggers the full implementation.
<activityCoefficients model="Pitzer">
      <!-- A_Debye units = sqrt(kg/gmol)  -->
      <A_Debye model="water" />
      <!-- object description continues -->
</activityCoefficients>
Temperature and Pressure Dependence of the Activity Coefficients
Temperature dependence of the activity coefficients leads to nonzero terms for the excess enthalpy and entropy of solution. This means that the partial molar enthalpies, entropies, and heat capacities are all non-trivial to compute. The following formulas are used.
The partial molar enthalpy, \(\bar s_k(T,P) \):
\[ \bar h_k(T,P) = h^{\triangle}_k(T,P) - R T^2 \frac{d \ln(\gamma_k^\triangle)}{dT} \]
The solvent partial molar enthalpy is equal to
\[ \bar h_o(T,P) = h^{o}_o(T,P) - R T^2 \frac{d \ln(a_o)}{dT} = h^{o}_o(T,P) + R T^2 (\sum_{k \neq o} m_k) \tilde{M_o} (\frac{d \phi}{dT}) \]
The partial molar entropy, \(\bar s_k(T,P) \):
\[ \bar s_k(T,P) = s^{\triangle}_k(T,P) - R \ln(\gamma^{\triangle}_k \frac{m_k}{m^{\triangle}})) - R T \frac{d \ln(\gamma^{\triangle}_k) }{dT} \]
\[ \bar s_o(T,P) = s^o_o(T,P) - R \ln(a_o) - R T \frac{d \ln(a_o)}{dT} \]
The partial molar heat capacity, \(C_{p,k}(T,P)\):
\[ \bar C_{p,k}(T,P) = C^{\triangle}_{p,k}(T,P) - 2 R T \frac{d \ln(\gamma^{\triangle}_k)}{dT} - R T^2 \frac{d^2 \ln(\gamma^{\triangle}_k) }{{dT}^2} \]
\[ \bar C_{p,o}(T,P) = C^o_{p,o}(T,P) - 2 R T \frac{d \ln(a_o)}{dT} - R T^2 \frac{d^2 \ln(a_o)}{{dT}^2} \]
The pressure dependence of the activity coefficients leads to non-zero terms for the excess Volume of the solution. Therefore, the partial molar volumes are functions of the pressure derivatives of the activity coefficients.
\[ \bar V_k(T,P) = V^{\triangle}_k(T,P) + R T \frac{d \ln(\gamma^{\triangle}_k) }{dP} \]
\[ \bar V_o(T,P) = V^o_o(T,P) + R T \frac{d \ln(a_o)}{dP} \]
The majority of work for these functions take place in the internal routines that calculate the first and second derivatives of the log of the activity coefficients wrt temperature, s_update_dlnMolalityActCoeff_dT(), s_update_d2lnMolalityActCoeff_dT2(), and the first derivative of the log activity coefficients wrt pressure, s_update_dlnMolalityActCoeff_dP().
Application within Kinetics Managers
For the time being, we have set the standard concentration for all solute species in this phase equal to the default concentration of the solvent at the system temperature and pressure multiplied by Mnaught (kg solvent / gmol solvent). The solvent standard concentration is just equal to its standard state concentration.
This means that the kinetics operator essentially works on an generalized concentration basis (kmol / m3), with units for the kinetic rate constant specified as if all reactants (solvent or solute) are on a concentration basis (kmol /m3). The concentration will be modified by the activity coefficients.
For example, a bulk-phase binary reaction between liquid solute species j and k, producing a new liquid solute species l would have the following equation for its rate of progress variable, \(R^1 \), which has units of kmol m-3 s-1.
\[ R^1 = k^1 C_j^a C_k^a = k^1 (C^o_o \tilde{M}_o a_j) (C^o_o \tilde{M}_o a_k) \]
where
\[ C_j^a = C^o_o \tilde{M}_o a_j \quad and \quad C_k^a = C^o_o \tilde{M}_o a_k \]
\(C_j^a \) is the activity concentration of species j, and \(C_k^a \) is the activity concentration of species k. \(C^o_o \) is the concentration of water at 298 K and 1 atm. \(\tilde{M}_o \) has units of kg solvent per gmol solvent and is equal to
\[ \tilde{M}_o = \frac{M_o}{1000} \]
\(a_j \) is the activity of species j at the current temperature and pressure and concentration of the liquid phase is given by the molality based activity coefficient multiplied by the molality of the jth species.
\[ a_j = \gamma_j^\triangle m_j = \gamma_j^\triangle \frac{n_j}{\tilde{M}_o n_o} \]
\(k^1 \) has units of m3 kmol-1 s-1.
Therefore the generalized activity concentration of a solute species has the following form
\[ C_j^a = C^o_o \frac{\gamma_j^\triangle n_j}{n_o} \]
The generalized activity concentration of the solvent has the same units, but it's a simpler form
\[ C_o^a = C^o_o a_o \]
The reverse rate constant can then be obtained from the law of microscopic reversibility and the equilibrium expression for the system.
\[ \frac{a_j a_k}{ a_l} = K^{o,1} = \exp(\frac{\mu^o_l - \mu^o_j - \mu^o_k}{R T}) \]
\(K^{o,1} \) is the dimensionless form of the equilibrium constant.
\[ R^{-1} = k^{-1} C_l^a = k^{-1} (C_o \tilde{M}_o a_l) \]
where
\[ k^{-1} = k^1 K^{o,1} C_o \tilde{M}_o \]
\(k^{-1} \) has units of s-1.
Note, this treatment may be modified in the future, as events dictate.
Instantiation of the Class
The constructor for this phase is now located in the default ThermoFactory for Cantera. The following code snippet may be used to initialize the phase using the default construction technique within Cantera.
ThermoPhase *HMW = newPhase("HMW_NaCl.xml", "NaCl_electrolyte");
A new HMWSoln object may be created by the following code snippets:
HMWSoln *HMW = new HMWSoln("HMW_NaCl.xml", "NaCl_electrolyte");
or
char iFile[80], file_ID[80];
strcpy(iFile, "HMW_NaCl.xml");
sprintf(file_ID,"%s#NaCl_electrolyte", iFile);
XML_Node *xm = get_XML_NameID("phase", file_ID, 0);
HMWSoln *dh = new HMWSoln(*xm);
or by the following call to importPhase():
char iFile[80], file_ID[80];
strcpy(iFile, "HMW_NaCl.xml");
sprintf(file_ID,"%s#NaCl_electrolyte", iFile);
XML_Node *xm = get_XML_NameID("phase", file_ID, 0);
HMWSoln dhphase;
importPhase(*xm, &dhphase);
XML Example
The phase model name for this is called StoichSubstance. It must be supplied as the model attribute of the thermo XML element entry. Within the phase XML block, the density of the phase must be specified. An example of an XML file this phase is given below.
 <phase id="NaCl_electrolyte" dim="3">
  <speciesArray datasrc="#species_waterSolution">
             H2O(L) Na+ Cl- H+ OH-
  </speciesArray>
  <state>
    <temperature units="K"> 300  </temperature>
    <pressure units="Pa">101325.0</pressure>
    <soluteMolalities>
           Na+:3.0
           Cl-:3.0
           H+:1.0499E-8
           OH-:1.3765E-6
    </soluteMolalities>
  </state>
  <!-- thermo model identifies the inherited class
       from ThermoPhase that will handle the thermodynamics.
    -->
  <thermo model="HMW">
     <standardConc model="solvent_volume" />
   <activityCoefficients model="Pitzer" TempModel="complex1">
              <!-- Pitzer Coefficients
                   These coefficients are from Pitzer's main
                   paper, in his book.
                -->
              <A_Debye model="water" />
              <ionicRadius default="3.042843"  units="Angstroms">
              </ionicRadius>
              <binarySaltParameters cation="Na+" anion="Cl-">
                <beta0> 0.0765, 0.008946, -3.3158E-6,
                        -777.03, -4.4706
                </beta0>
                <beta1> 0.2664, 6.1608E-5, 1.0715E-6 </beta1>
                <beta2> 0.0    </beta2>
                <Cphi> 0.00127, -4.655E-5, 0.0,
                       33.317, 0.09421
                </Cphi>
                <Alpha1> 2.0 </Alpha1>
              </binarySaltParameters>
              <binarySaltParameters cation="H+" anion="Cl-">
                <beta0> 0.1775, 0.0, 0.0, 0.0, 0.0</beta0>
                <beta1> 0.2945, 0.0, 0.0 </beta1>
                <beta2> 0.0    </beta2>
                <Cphi> 0.0008, 0.0, 0.0, 0.0, 0.0 </Cphi>
                <Alpha1> 2.0 </Alpha1>
              </binarySaltParameters>
              <binarySaltParameters cation="Na+" anion="OH-">
                <beta0> 0.0864, 0.0, 0.0, 0.0, 0.0 </beta0>
                <beta1> 0.253, 0.0, 0.0 </beta1>
                <beta2> 0.0    </beta2>
                <Cphi> 0.0044, 0.0, 0.0, 0.0, 0.0 </Cphi>
                <Alpha1> 2.0 </Alpha1>
              </binarySaltParameters>
              <thetaAnion anion1="Cl-" anion2="OH-">
                <Theta> -0.05 </Theta>
              </thetaAnion>
              <psiCommonCation cation="Na+" anion1="Cl-" anion2="OH-">
                <Theta> -0.05 </Theta>
                <Psi> -0.006 </Psi>
              </psiCommonCation>
              <thetaCation cation1="Na+" cation2="H+">
                <Theta> 0.036 </Theta>
              </thetaCation>
              <psiCommonAnion anion="Cl-" cation1="Na+" cation2="H+">
                <Theta> 0.036 </Theta>
                <Psi> -0.004 </Psi>
              </psiCommonAnion>
     </activityCoefficients>
     <solvent> H2O(L) </solvent>
  </thermo>
  <elementArray datasrc="elements.xml"> O H Na Cl </elementArray>
  <kinetics model="none" >
  </kinetics>
</phase>
Definition at line 1240 of file HMWSoln.h.
Constructor & Destructor Documentation
HMWSoln ()
Default Constructor.
Definition at line 37 of file HMWSoln.cpp.
References HMWSoln::elambda, and HMWSoln::elambda1.
Referenced by HMWSoln::duplMyselfAsThermoPhase().
HMWSoln (std::string inputFile, std::string id = "")
Construct and initialize an HMWSoln ThermoPhase object directly from an ASCII input file.
Working constructors
The two constructors below are the normal way the phase initializes itself. They are shells that call the routine initThermo(), with a reference to the XML database to get the info for the phase.
Parameters
inputFile Name of the input file containing the phase XML data to set up the object
id ID of the phase in the input file. Defaults to the empty string.
Definition at line 94 of file HMWSoln.cpp.
References HMWSoln::constructPhaseFile(), HMWSoln::elambda, and HMWSoln::elambda1.
HMWSoln (XML_Node & phaseRef, std::string id = "")
Construct and initialize an HMWSoln ThermoPhase object directly from an XML database.
Parameters
phaseRef XML phase node containing the description of the phase
id id attribute containing the name of the phase. (default is the empty string)
Definition at line 145 of file HMWSoln.cpp.
References HMWSoln::constructPhaseXML(), HMWSoln::elambda, and HMWSoln::elambda1.
HMWSoln (const HMWSoln & right)
Copy Constructor.
Copy constructor for the object. Constructed object will be a clone of this object, but will also own all of its data. This is a wrapper around the assignment operator
Parameters
right Object to be copied.
Definition at line 202 of file HMWSoln.cpp.
HMWSoln (int testProb)
This is a special constructor, used to replicate test problems during the initial verification of the object.
test problems: 1 = NaCl problem - 5 species - the thermo is read in from an XML file
speci molality charge Cl- 6.0954 6.0997E+00 -1 H+ 1.0000E-08 2.1628E-09 1 Na+ 6.0954E+00 6.0997E+00 1 OH- 7.5982E-07 1.3977E-06 -1 HMW_params____beta0MX__beta1MX__beta2MX__CphiMX_____alphaMX__thetaij 10 1 2 0.1775 0.2945 0.0 0.00080 2.0 0.0 1 3 0.0765 0.2664 0.0 0.00127 2.0 0.0 1 4 0.0 0.0 0.0 0.0 0.0 -0.050 2 3 0.0 0.0 0.0 0.0 0.0 0.036 2 4 0.0 0.0 0.0 0.0 0.0 0.0 3 4 0.0864 0.253 0.0 0.0044 2.0 0.0 Triplet_interaction_parameters_psiaa'_or_psicc' 2 1 2 3 -0.004 1 3 4 -0.006
Parameters
testProb Hard -coded test problem to instantiate. Current valid values are 1.
Definition at line 437 of file HMWSoln.cpp.
References HMWSoln::constructPhaseFile(), HMWSoln::m_Alpha1MX_ij, HMWSoln::m_Beta0MX_ij, HMWSoln::m_Beta1MX_ij, HMWSoln::m_CounterIJ, HMWSoln::m_CphiMX_ij, Phase::m_kk, HMWSoln::m_Psi_ijk, HMWSoln::m_Psi_ijk_coeff, HMWSoln::m_Theta_ij, HMWSoln::printCoeffs(), and Phase::speciesIndex().
~HMWSoln () virtual
Destructor.
Definition at line 583 of file HMWSoln.cpp.
References HMWSoln::m_waterProps.
Member Function Documentation
HMWSoln & operator= (const HMWSoln & right)
Assignment operator.
Assignment operator for the object. Constructed object will be a clone of this object, but will also own all of its data.
Parameters
right Object to be copied.
Definition at line 260 of file HMWSoln.cpp.
References HMWSoln::CROP_ln_gamma_k_max, HMWSoln::CROP_ln_gamma_k_min, HMWSoln::CROP_ln_gamma_o_max, HMWSoln::CROP_ln_gamma_o_min, HMWSoln::CROP_speciesCropped_, HMWSoln::IMS_afCut_, HMWSoln::IMS_agCut_, HMWSoln::IMS_bfCut_, HMWSoln::IMS_bgCut_, HMWSoln::IMS_cCut_, HMWSoln::IMS_dfCut_, HMWSoln::IMS_dgCut_, HMWSoln::IMS_efCut_, HMWSoln::IMS_egCut_, HMWSoln::IMS_gamma_k_min_, HMWSoln::IMS_gamma_o_min_, HMWSoln::IMS_lnActCoeffMolal_, HMWSoln::IMS_slopefCut_, HMWSoln::IMS_slopegCut_, HMWSoln::IMS_typeCutoff_, HMWSoln::IMS_X_o_cutoff_, HMWSoln::m_A_Debye, HMWSoln::m_Aionic, HMWSoln::m_Alpha1MX_ij, HMWSoln::m_Alpha2MX_ij, HMWSoln::m_Beta0MX_ij, HMWSoln::m_Beta0MX_ij_coeff, HMWSoln::m_Beta0MX_ij_L, HMWSoln::m_Beta0MX_ij_LL, HMWSoln::m_Beta0MX_ij_P, HMWSoln::m_Beta1MX_ij, HMWSoln::m_Beta1MX_ij_coeff, HMWSoln::m_Beta1MX_ij_L, HMWSoln::m_Beta1MX_ij_LL, HMWSoln::m_Beta1MX_ij_P, HMWSoln::m_Beta2MX_ij, HMWSoln::m_Beta2MX_ij_coeff, HMWSoln::m_Beta2MX_ij_L, HMWSoln::m_Beta2MX_ij_LL, HMWSoln::m_Beta2MX_ij_P, HMWSoln::m_BMX_IJ, HMWSoln::m_BMX_IJ_L, HMWSoln::m_BMX_IJ_LL, HMWSoln::m_BMX_IJ_P, HMWSoln::m_BphiMX_IJ, HMWSoln::m_BphiMX_IJ_L, HMWSoln::m_BphiMX_IJ_LL, HMWSoln::m_BphiMX_IJ_P, HMWSoln::m_BprimeMX_IJ, HMWSoln::m_BprimeMX_IJ_L, HMWSoln::m_BprimeMX_IJ_LL, HMWSoln::m_BprimeMX_IJ_P, HMWSoln::m_CMX_IJ, HMWSoln::m_CMX_IJ_L, HMWSoln::m_CMX_IJ_LL, HMWSoln::m_CMX_IJ_P, HMWSoln::m_CounterIJ, HMWSoln::m_CphiMX_ij, HMWSoln::m_CphiMX_ij_coeff, HMWSoln::m_CphiMX_ij_L, HMWSoln::m_CphiMX_ij_LL, HMWSoln::m_CphiMX_ij_P, HMWSoln::m_d2lnActCoeffMolaldT2_Scaled, HMWSoln::m_d2lnActCoeffMolaldT2_Unscaled, HMWSoln::m_debugCalc, HMWSoln::m_densWaterSS, HMWSoln::m_dlnActCoeffMolaldP_Scaled, HMWSoln::m_dlnActCoeffMolaldP_Unscaled, HMWSoln::m_dlnActCoeffMolaldT_Scaled, HMWSoln::m_dlnActCoeffMolaldT_Unscaled, HMWSoln::m_expg0_RT, HMWSoln::m_form_A_Debye, HMWSoln::m_formGC, HMWSoln::m_formPitzer, HMWSoln::m_formPitzerTemp, HMWSoln::m_g2func_IJ, HMWSoln::m_gamma_tmp, HMWSoln::m_gfunc_IJ, HMWSoln::m_h2func_IJ, HMWSoln::m_hfunc_IJ, HMWSoln::m_IionicMolality, HMWSoln::m_IionicMolalityStoich, HMWSoln::m_Lambda_nj, HMWSoln::m_Lambda_nj_coeff, HMWSoln::m_Lambda_nj_L, HMWSoln::m_Lambda_nj_LL, HMWSoln::m_Lambda_nj_P, HMWSoln::m_lnActCoeffMolal_Scaled, HMWSoln::m_lnActCoeffMolal_Unscaled, HMWSoln::m_maxIionicStrength, HMWSoln::m_molalitiesAreCropped, HMWSoln::m_molalitiesCropped, HMWSoln::m_pe, HMWSoln::m_Phi_IJ, HMWSoln::m_Phi_IJ_L, HMWSoln::m_Phi_IJ_LL, HMWSoln::m_Phi_IJ_P, HMWSoln::m_PhiPhi_IJ, HMWSoln::m_PhiPhi_IJ_L, HMWSoln::m_PhiPhi_IJ_LL, HMWSoln::m_PhiPhi_IJ_P, HMWSoln::m_Phiprime_IJ, HMWSoln::m_pp, HMWSoln::m_Psi_ijk, HMWSoln::m_Psi_ijk_coeff, HMWSoln::m_Psi_ijk_L, HMWSoln::m_Psi_ijk_LL, HMWSoln::m_Psi_ijk_P, HMWSoln::m_speciesCharge_Stoich, HMWSoln::m_TempPitzerRef, HMWSoln::m_Theta_ij, HMWSoln::m_Theta_ij_coeff, HMWSoln::m_Theta_ij_L, HMWSoln::m_Theta_ij_LL, HMWSoln::m_Theta_ij_P, HMWSoln::m_tmpV, HMWSoln::m_waterProps, HMWSoln::m_waterSS, HMWSoln::MC_apCut_, HMWSoln::MC_bpCut_, HMWSoln::MC_cpCut_, HMWSoln::MC_dpCut_, HMWSoln::MC_epCut_, HMWSoln::MC_slopepCut_, HMWSoln::MC_X_o_cutoff_, HMWSoln::MC_X_o_min_, and MolalityVPSSTP::operator=().
ThermoPhase * duplMyselfAsThermoPhase () const virtual
Duplicator from the ThermoPhase parent class.
Given a pointer to a ThermoPhase object, this function will duplicate the ThermoPhase object and all underlying structures. This is basically a wrapper around the copy constructor.
Returns
returns a pointer to a ThermoPhase
Reimplemented from MolalityVPSSTP.
Definition at line 598 of file HMWSoln.cpp.
References HMWSoln::HMWSoln().
int eosType () const virtual
Equation of state type flag.
The base class returns zero. Subclasses should define this to return a unique non-zero value. Constants defined for this purpose are listed in mix_defs.h.
Reimplemented from MolalityVPSSTP.
Definition at line 610 of file HMWSoln.cpp.
References Cantera::cHMWSoln0, and HMWSoln::m_formGC.
doublereal enthalpy_mole () const virtual
Molar enthalpy. Units: J/kmol.
Molar enthalpy of the solution. Units: J/kmol. (HKM -> Bump up to Parent object)
Reimplemented from ThermoPhase.
Definition at line 635 of file HMWSoln.cpp.
References DATA_PTR, Phase::getMoleFractions(), HMWSoln::getPartialMolarEnthalpies(), HMWSoln::m_pp, HMWSoln::m_tmpV, and Phase::mean_X().
Referenced by HMWSoln::intEnergy_mole().
doublereal relative_enthalpy () const virtual
Excess molar enthalpy of the solution from the mixing process.
Units: J/ kmol.
Note this is kmol of the total solution.
Definition at line 643 of file HMWSoln.cpp.
References DATA_PTR, Cantera::GasConstant, VPStandardStateTP::getEnthalpy_RT(), HMWSoln::getPartialMolarEnthalpies(), HMWSoln::m_gamma_tmp, Phase::m_kk, HMWSoln::m_tmpV, Phase::mean_X(), and Phase::temperature().
Referenced by HMWSoln::relative_molal_enthalpy().
doublereal relative_molal_enthalpy () const virtual
Excess molar enthalpy of the solution from the mixing process on a molality basis.
Units: J/ (kmol add salt).
Note this is kmol of the guessed at salt composition
Definition at line 658 of file HMWSoln.cpp.
References Phase::charge(), DATA_PTR, Phase::getMoleFractions(), Phase::m_kk, Phase::m_speciesCharge, HMWSoln::m_tmpV, Cantera::npos, and HMWSoln::relative_enthalpy().
doublereal intEnergy_mole () const virtual
Molar internal energy. Units: J/kmol.
Molar internal energy of the solution. Units: J/kmol. (HKM -> Bump up to Parent object)
Reimplemented from ThermoPhase.
Definition at line 706 of file HMWSoln.cpp.
References HMWSoln::enthalpy_mole(), Phase::molarDensity(), and HMWSoln::pressure().
doublereal entropy_mole () const virtual
Molar entropy. Units: J/kmol/K.
Molar entropy of the solution. Units: J/kmol/K. For an ideal, constant partial molar volume solution mixture with pure species phases which exhibit zero volume expansivity:
\[ \hat s(T, P, X_k) = \sum_k X_k \hat s^0_k(T) - \hat R \sum_k X_k log(X_k) \]
The reference-state pure-species entropies \(\hat s^0_k(T,p_{ref}) \) are computed by the species thermodynamic property manager. The pure species entropies are independent of temperature since the volume expansivities are equal to zero.
See Also
SpeciesThermo
 (HKM -> Bump up to Parent object)
Reimplemented from ThermoPhase.
Definition at line 720 of file HMWSoln.cpp.
References DATA_PTR, HMWSoln::getPartialMolarEntropies(), HMWSoln::m_tmpV, and Phase::mean_X().
doublereal gibbs_mole () const virtual
Molar Gibbs function. Units: J/kmol.
Reimplemented from ThermoPhase.
Definition at line 727 of file HMWSoln.cpp.
References DATA_PTR, HMWSoln::getChemPotentials(), HMWSoln::m_tmpV, and Phase::mean_X().
doublereal cp_mole () const virtual
Molar heat capacity at constant pressure. Units: J/kmol/K.
Reimplemented from ThermoPhase.
Definition at line 738 of file HMWSoln.cpp.
References DATA_PTR, HMWSoln::getPartialMolarCp(), HMWSoln::m_tmpV, and Phase::mean_X().
Referenced by HMWSoln::cv_mole().
doublereal cv_mole () const virtual
Molar heat capacity at constant volume. Units: J/kmol/K.
Reimplemented from ThermoPhase.
Definition at line 746 of file HMWSoln.cpp.
References ckr::cp(), HMWSoln::cp_mole(), HMWSoln::isothermalCompressibility(), Phase::molarVolume(), Phase::temperature(), and HMWSoln::thermalExpansionCoeff().
doublereal pressure () const virtual
In this equation of state implementation, the density is a function only of the mole fractions.
Pressure.
Therefore, it can't be an independent variable. Instead, the pressure is used as the independent variable. Functions which try to set the thermodynamic state by calling setDensity() may cause an exception to be thrown. Pressure. Units: Pa. For this incompressible system, we return the internally stored independent value of the pressure.
Units: Pa. For this incompressible system, we return the internally stored independent value of the pressure.
Reimplemented from ThermoPhase.
Definition at line 766 of file HMWSoln.cpp.
References VPStandardStateTP::m_Pcurrent.
Referenced by HMWSoln::A_Debye_TP(), HMWSoln::d2A_DebyedT2_TP(), HMWSoln::dA_DebyedP_TP(), HMWSoln::dA_DebyedT_TP(), HMWSoln::intEnergy_mole(), HMWSoln::s_updatePitzer_dlnMolalityActCoeff_dP(), and HMWSoln::satPressure().
void setPressure (doublereal p) virtual
Set the internally stored pressure (Pa) at constant temperature and composition.
This method sets the pressure within the object. The water model is a completely compressible model. Also, the dielectric constant is pressure dependent.
Parameters
p input Pressure (Pa)
Todo:
Implement a variable pressure capability
Reimplemented from VPStandardStateTP.
Definition at line 776 of file HMWSoln.cpp.
References HMWSoln::setState_TP(), and Phase::temperature().
void calcDensity () protected virtual
Calculate the density of the mixture using the partial molar volumes and mole fractions as input.
The formula for this is
\[ \rho = \frac{\sum_k{X_k W_k}}{\sum_k{X_k V_k}} \]
where \(X_k\) are the mole fractions, \(W_k\) are the molecular weights, and \(V_k\) are the pure species molar volumes.
Note, the basis behind this formula is that in an ideal solution the partial molar volumes are equal to the pure species molar volumes. We have additionally specified in this class that the pure species molar volumes are independent of temperature and pressure.
NOTE: This is a non-virtual function, which is not a member of the ThermoPhase base class.
Reimplemented from VPStandardStateTP.
Definition at line 781 of file HMWSoln.cpp.
References Phase::getMoleFractions(), HMWSoln::getPartialMolarVolumes(), Phase::m_kk, HMWSoln::m_pp, HMWSoln::m_tmpV, Phase::meanMolecularWeight(), and Phase::setDensity().
Referenced by HMWSoln::setState_TP().
double density () const virtual
Returns the current value of the density.
Returns
value of the density. Units: kg/m^3
Reimplemented from Phase.
Definition at line 830 of file HMWSoln.cpp.
References Phase::density().
Referenced by HMWSoln::setDensity().
void setDensity (const doublereal rho) virtual
Set the internally stored density (kg/m^3) of the phase.
Overwritten setDensity() function is necessary because of the underlying water model.
Todo:
Now have a compressible ss equation for liquid water. Therefore, this phase is compressible. May still want to change the independent variable however.
NOTE: This is an overwritten function from the State.h class
Parameters
rho Input density (kg/m^3).
Reimplemented from Phase.
Definition at line 856 of file HMWSoln.cpp.
References HMWSoln::density().
void setMolarDensity (const doublereal conc) virtual
Set the internally stored molar density (kmol/m^3) for the phase.
Overwritten setMolarDensity() function is necessary because of the underlying water model.
This function will now throw an error condition if the input isn't exactly equal to the current molar density.
NOTE: This is a virtual function overwritten from the State.h class
Parameters
conc Input molar density (kmol/m^3).
Reimplemented from Phase.
Definition at line 875 of file HMWSoln.cpp.
void setTemperature (const doublereal temp) virtual
Set the temperature (K)
Overwritten setTemperature(double) from State.h. This function sets the temperature, and makes sure that the value propagates to underlying objects, such as the water standard state model.
Todo:
Make Phase::setTemperature a virtual function
Parameters
temp Temperature in kelvin
Reimplemented from VPStandardStateTP.
Definition at line 886 of file HMWSoln.cpp.
References VPStandardStateTP::m_Pcurrent, and HMWSoln::setState_TP().
void setState_TP (doublereal t, doublereal p) virtual
Set the temperature (K) and pressure (Pa)
Set the temperature and pressure.
Parameters
t Temperature (K)
p Pressure (Pa)
Reimplemented from VPStandardStateTP.
Definition at line 896 of file HMWSoln.cpp.
References HMWSoln::calcDensity(), PDSS::density(), HMWSoln::m_densWaterSS, VPStandardStateTP::m_Pcurrent, HMWSoln::m_waterSS, Phase::setTemperature(), and VPStandardStateTP::updateStandardStateThermo().
Referenced by HMWSoln::setPressure(), and HMWSoln::setTemperature().
doublereal isothermalCompressibility () const virtual
The isothermal compressibility.
Units: 1/Pa. The isothermal compressibility is defined as
\[ \kappa_T = -\frac{1}{v}\left(\frac{\partial v}{\partial P}\right)_T \]
Reimplemented from ThermoPhase.
Definition at line 805 of file HMWSoln.cpp.
Referenced by HMWSoln::cv_mole().
doublereal thermalExpansionCoeff () const virtual
The thermal expansion coefficient.
Units: 1/K. The thermal expansion coefficient is defined as
\[ \beta = \frac{1}{v}\left(\frac{\partial v}{\partial T}\right)_P \]
Reimplemented from ThermoPhase.
Definition at line 823 of file HMWSoln.cpp.
Referenced by HMWSoln::cv_mole().
void getActivityConcentrations (doublereal * c) const virtual
This method returns an array of generalized activity concentrations.
The generalized activity concentrations, \(C_k^a\), are defined such that \(a_k = C^a_k / C^0_k, \) where \(C^0_k \) is a standard concentration defined below. These generalized concentrations are used by kinetics manager classes to compute the forward and reverse rates of elementary reactions.
The generalized activity concentration of a solute species has the following form
\[ C_j^a = C^o_o \frac{\gamma_j^\triangle n_j}{n_o} \]
The generalized activity concentration of the solvent has the same units, but it's a simpler form
\[ C_o^a = C^o_o a_o \]
Parameters
c Array of generalized concentrations. The units are kmol m-3 for both the solvent and the solute species
Reimplemented from MolalityVPSSTP.
Definition at line 939 of file HMWSoln.cpp.
References HMWSoln::getActivities(), Phase::m_kk, and HMWSoln::standardConcentration().
doublereal standardConcentration (size_t k = 0) const virtual
Return the standard concentration for the kth species.
The standard concentration \(C^0_k \) used to normalize the activity (i.e., generalized) concentration for use
We have set the standard concentration for all solute species in this phase equal to the default concentration of the solvent at the system temperature and pressure multiplied by Mnaught (kg solvent / gmol solvent). The solvent standard concentration is just equal to its standard state concentration.
\[ C_j^0 = C^o_o \tilde{M}_o \quad and C_o^0 = C^o_o \]
The consequence of this is that the standard concentrations have unequal units between the solvent and the solute. However, both the solvent and the solute activity concentrations will have the same units of kmol kg-3.
This means that the kinetics operator essentially works on an generalized concentration basis (kmol / m3), with units for the kinetic rate constant specified as if all reactants (solvent or solute) are on a concentration basis (kmol /m3). The concentration will be modified by the activity coefficients.
For example, a bulk-phase binary reaction between liquid solute species j and k, producing a new liquid solute species l would have the following equation for its rate of progress variable, \(R^1 \), which has units of kmol m-3 s-1.
\[ R^1 = k^1 C_j^a C_k^a = k^1 (C^o_o \tilde{M}_o a_j) (C^o_o \tilde{M}_o a_k) \]
where
\[ C_j^a = C^o_o \tilde{M}_o a_j \quad and \quad C_k^a = C^o_o \tilde{M}_o a_k \]
\(C_j^a \) is the activity concentration of species j, and \(C_k^a \) is the activity concentration of species k. \(C^o_o \) is the concentration of water at 298 K and 1 atm. \(\tilde{M}_o \) has units of kg solvent per gmol solvent and is equal to
\[ \tilde{M}_o = \frac{M_o}{1000} \]
\(a_j \) is the activity of species j at the current temperature and pressure and concentration of the liquid phase is given by the molality based activity coefficient multiplied by the molality of the jth species.
\[ a_j = \gamma_j^\triangle m_j = \gamma_j^\triangle \frac{n_j}{\tilde{M}_o n_o} \]
\(k^1 \) has units of m3 kmol-1 s-1.
Therefore the generalized activity concentration of a solute species has the following form
\[ C_j^a = C^o_o \frac{\gamma_j^\triangle n_j}{n_o} \]
The generalized activity concentration of the solvent has the same units, but it's a simpler form
\[ C_o^a = C^o_o a_o \]
Parameters
k Optional parameter indicating the species. The default is to assume this refers to species 0.
Returns
Returns the standard Concentration in units of m3 kmol-1.
Parameters
k Species index
Reimplemented from MolalityVPSSTP.
Definition at line 974 of file HMWSoln.cpp.
References DATA_PTR, VPStandardStateTP::getStandardVolumes(), MolalityVPSSTP::m_indexSolvent, MolalityVPSSTP::m_Mnaught, and HMWSoln::m_tmpV.
Referenced by HMWSoln::getActivityConcentrations(), and HMWSoln::logStandardConc().
doublereal logStandardConc (size_t k = 0) const virtual
Returns the natural logarithm of the standard concentration of the kth species.
Parameters
k Species index
Reimplemented from MolalityVPSSTP.
Definition at line 988 of file HMWSoln.cpp.
References HMWSoln::standardConcentration().
void getUnitsStandardConc (double * uA, int k = 0, int sizeUA = 6) const virtual
Returns the units of the standard and generalized concentrations.
Note they have the same units, as their ratio is defined to be equal to the activity of the kth species in the solution, which is unitless.
This routine is used in print out applications where the units are needed. Usually, MKS units are assumed throughout the program and in the XML input files.
The base ThermoPhase class assigns the default quantities of (kmol/m3) for all species. Inherited classes are responsible for overriding the default values if necessary.
Parameters
uA Output vector containing the units uA[0] = kmol units - default = 1 uA[1] = m units - default = -nDim(), the number of spatial dimensions in the Phase class. uA[2] = kg units - default = 0; uA[3] = Pa(pressure) units - default = 0; uA[4] = Temperature units - default = 0; uA[5] = time units - default = 0
k species index. Defaults to 0.
sizeUA output int containing the size of the vector. Currently, this is equal to 6.
Reimplemented from MolalityVPSSTP.
Definition at line 1016 of file HMWSoln.cpp.
References Phase::nDim().
void getActivities (doublereal * ac) const virtual
Get the array of non-dimensional activities at the current solution temperature, pressure, and solution concentration.
We resolve this function at this level by calling on the activityConcentration function. However, derived classes may want to override this default implementation.
(note solvent is on molar scale).
Parameters
ac Output vector of activities. Length: m_kk.
Reimplemented from MolalityVPSSTP.
Definition at line 1047 of file HMWSoln.cpp.
References MolalityVPSSTP::m_indexSolvent, Phase::m_kk, HMWSoln::m_lnActCoeffMolal_Scaled, MolalityVPSSTP::m_molalities, Phase::moleFraction(), HMWSoln::s_update_lnMolalityActCoeff(), and VPStandardStateTP::updateStandardStateThermo().
Referenced by HMWSoln::getActivityConcentrations().
void getChemPotentials (doublereal * mu) const virtual
Get the species chemical potentials. Units: J/kmol.
This function returns a vector of chemical potentials of the species in solution.
\[ \mu_k = \mu^{\triangle}_k(T,P) + R T ln(\gamma_k^{\triangle} m_k) \]
Parameters
mu Output vector of species chemical potentials. Length: m_kk. Units: J/kmol
Reimplemented from ThermoPhase.
Definition at line 1113 of file HMWSoln.cpp.
References Cantera::GasConstant, VPStandardStateTP::getStandardChemPotentials(), MolalityVPSSTP::m_indexSolvent, Phase::m_kk, HMWSoln::m_lnActCoeffMolal_Scaled, MolalityVPSSTP::m_molalities, ckr::max(), Phase::moleFraction(), HMWSoln::s_update_lnMolalityActCoeff(), Phase::temperature(), and Cantera::xxSmall.
Referenced by HMWSoln::gibbs_mole().
void getPartialMolarEnthalpies (doublereal * hbar) const virtual
Returns an array of partial molar enthalpies for the species in the mixture.
Units (J/kmol)
For this phase, the partial molar enthalpies are equal to the standard state enthalpies modified by the derivative of the molality-based activity coefficient wrt temperature
\[ \bar h_k(T,P) = h^{\triangle}_k(T,P) - R T^2 \frac{d \ln(\gamma_k^\triangle)}{dT} \]
The solvent partial molar enthalpy is equal to
\[ \bar h_o(T,P) = h^{o}_o(T,P) - R T^2 \frac{d \ln(a_o)}{dT} = h^{o}_o(T,P) + R T^2 (\sum_{k \neq o} m_k) \tilde{M_o} (\frac{d \phi}{dT}) \]
Parameters
hbar Output vector of species partial molar enthalpies. Length: m_kk. units are J/kmol.
Reimplemented from ThermoPhase.
Definition at line 1162 of file HMWSoln.cpp.
References Cantera::GasConstant, VPStandardStateTP::getEnthalpy_RT(), HMWSoln::m_dlnActCoeffMolaldT_Scaled, Phase::m_kk, HMWSoln::s_update_dlnMolalityActCoeff_dT(), HMWSoln::s_update_lnMolalityActCoeff(), and Phase::temperature().
Referenced by HMWSoln::enthalpy_mole(), and HMWSoln::relative_enthalpy().
void getPartialMolarEntropies (doublereal * sbar) const virtual
Returns an array of partial molar entropies of the species in the solution.
Units: J/kmol/K.
Maxwell's equations provide an answer for how calculate this (p.215 Smith and Van Ness)
d(chemPot_i)/dT = -sbar_i
For this phase, the partial molar entropies are equal to the SS species entropies plus the ideal solution contribution plus complicated functions of the temperature derivative of the activity coefficients.
\[ \bar s_k(T,P) = s^{\triangle}_k(T,P) - R \ln(\gamma^{\triangle}_k \frac{m_k}{m^{\triangle}})) - R T \frac{d \ln(\gamma^{\triangle}_k) }{dT} \]
\[ \bar s_o(T,P) = s^o_o(T,P) - R \ln(a_o) - R T \frac{d \ln(a_o)}{dT} \]
Parameters
sbar Output vector of species partial molar entropies. Length = m_kk. units are J/kmol/K.
Reimplemented from ThermoPhase.
Definition at line 1218 of file HMWSoln.cpp.
References Cantera::GasConstant, VPStandardStateTP::getEntropy_R(), HMWSoln::m_dlnActCoeffMolaldT_Scaled, MolalityVPSSTP::m_indexSolvent, Phase::m_kk, HMWSoln::m_lnActCoeffMolal_Scaled, MolalityVPSSTP::m_molalities, ckr::max(), Phase::moleFraction(), HMWSoln::s_update_dlnMolalityActCoeff_dT(), HMWSoln::s_update_lnMolalityActCoeff(), Cantera::SmallNumber, and Phase::temperature().
Referenced by HMWSoln::entropy_mole().
void getPartialMolarVolumes (doublereal * vbar) const virtual
Return an array of partial molar volumes for the species in the mixture.
Units: m^3/kmol.
For this solution, the partial molar volumes are functions of the pressure derivatives of the activity coefficients.
\[ \bar V_k(T,P) = V^{\triangle}_k(T,P) + R T \frac{d \ln(\gamma^{\triangle}_k) }{dP} \]
\[ \bar V_o(T,P) = V^o_o(T,P) + R T \frac{d \ln(a_o)}{dP} \]
Parameters
vbar Output vector of species partial molar volumes. Length = m_kk. units are m^3/kmol.
Reimplemented from ThermoPhase.
Definition at line 1281 of file HMWSoln.cpp.
References Cantera::GasConstant, VPStandardStateTP::getStandardVolumes(), HMWSoln::m_dlnActCoeffMolaldP_Scaled, Phase::m_kk, HMWSoln::s_update_dlnMolalityActCoeff_dP(), HMWSoln::s_update_lnMolalityActCoeff(), and Phase::temperature().
Referenced by HMWSoln::calcDensity().
void getPartialMolarCp (doublereal * cpbar) const virtual
Return an array of partial molar heat capacities for the species in the mixture.
Units: J/kmol/K
The following formulas are implemented within the code.
\[ \bar C_{p,k}(T,P) = C^{\triangle}_{p,k}(T,P) - 2 R T \frac{d \ln(\gamma^{\triangle}_k)}{dT} - R T^2 \frac{d^2 \ln(\gamma^{\triangle}_k) }{{dT}^2} \]
\[ \bar C_{p,o}(T,P) = C^o_{p,o}(T,P) - 2 R T \frac{d \ln(a_o)}{dT} - R T^2 \frac{d^2 \ln(a_o)}{{dT}^2} \]
Parameters
cpbar Output vector of species partial molar heat capacities at constant pressure. Length = m_kk. units are J/kmol/K.
Reimplemented from ThermoPhase.
Definition at line 1317 of file HMWSoln.cpp.
References Cantera::GasConstant, VPStandardStateTP::getCp_R(), HMWSoln::m_d2lnActCoeffMolaldT2_Scaled, HMWSoln::m_dlnActCoeffMolaldT_Scaled, Phase::m_kk, HMWSoln::s_update_d2lnMolalityActCoeff_dT2(), HMWSoln::s_update_dlnMolalityActCoeff_dT(), HMWSoln::s_update_lnMolalityActCoeff(), and Phase::temperature().
Referenced by HMWSoln::cp_mole().
virtual void setToEquilState (const doublereal * lambda_RT) inline virtual
This method is used by the ChemEquil equilibrium solver.
It sets the state such that the chemical potentials satisfy
\[ \frac{\mu_k}{\hat R T} = \sum_m A_{k,m} \left(\frac{\lambda_m} {\hat R T}\right) \]
where \(\lambda_m \) is the element potential of element m. The temperature is unchanged. Any phase (ideal or not) that implements this method can be equilibrated by ChemEquil.
Parameters
lambda_RT Input vector of dimensionless element potentials The length is equal to nElements().
Reimplemented from MolalityVPSSTP.
Definition at line 1937 of file HMWSoln.h.
References HMWSoln::err(), and VPStandardStateTP::updateStandardStateThermo().
void setParameters (int n, doublereal *const c) virtual
Set the equation of state parameters.
The number and meaning of these depends on the subclass.
Parameters
n number of parameters
c array of n coefficients
Reimplemented from ThermoPhase.
Definition at line 1383 of file HMWSoln.cpp.
void getParameters (int & n, doublereal *const c) const virtual
Get the equation of state parameters in a vector.
The number and meaning of these depends on the subclass.
Parameters
n number of parameters
c array of n coefficients
Reimplemented from ThermoPhase.
Definition at line 1387 of file HMWSoln.cpp.
void setParametersFromXML (const XML_Node & eosdata) virtual
Set equation of state parameter values from XML entries.
This method is called by function importPhase in file importCTML.cpp when processing a phase definition in an input file. It should be overloaded in subclasses to set any parameters that are specific to that particular phase model.
Parameters
eosdata An XML_Node object corresponding to the "thermo" entry for this phase in the input file.
Reimplemented from VPStandardStateTP.
Definition at line 1404 of file HMWSoln.cpp.
virtual doublereal critTemperature () const inline virtual
Critical temperature (K).
Reimplemented from ThermoPhase.
Definition at line 1986 of file HMWSoln.h.
References HMWSoln::err().
virtual doublereal critPressure () const inline virtual
Critical pressure (Pa).
Reimplemented from ThermoPhase.
Definition at line 1992 of file HMWSoln.h.
References HMWSoln::err().
virtual doublereal critDensity () const inline virtual
Critical density (kg/m3).
Reimplemented from ThermoPhase.
Definition at line 1998 of file HMWSoln.h.
References HMWSoln::err().
virtual doublereal satTemperature (doublereal p) const inline virtual
Return the saturation temperature given the pressure.
Parameters
p Pressure (Pa)
Reimplemented from ThermoPhase.
Definition at line 2009 of file HMWSoln.h.
References HMWSoln::err().
doublereal satPressure (doublereal T) const virtual
Get the saturation pressure for a given temperature.
Note the limitations of this function. Stability considerations concerning multiphase equilibrium are ignored in this calculation. Therefore, the call is made directly to the SS of water underneath. The object is put back into its original state at the end of the call.
Todo:
This is probably not implemented correctly. The stability of the salt should be added into this calculation. The underlying water model may be called to get the stability of the pure water solution, if needed.
Parameters
T Temperature (kelvin)
Reimplemented from ThermoPhase.
Definition at line 1416 of file HMWSoln.cpp.
References HMWSoln::m_waterSS, HMWSoln::pressure(), PDSS::satPressure(), PDSS::setState_TP(), and Phase::temperature().
virtual doublereal vaporFraction () const inline virtual
Return the fraction of vapor at the current conditions.
Reimplemented from ThermoPhase.
Definition at line 2031 of file HMWSoln.h.
References HMWSoln::err().
virtual void setState_Tsat (doublereal t, doublereal x) inline virtual
Set the state to a saturated system at a particular temperature.
Parameters
t Temperature (kelvin)
x Fraction of vapor
Reimplemented from ThermoPhase.
Definition at line 2036 of file HMWSoln.h.
References HMWSoln::err().
virtual void setState_Psat (doublereal p, doublereal x) inline virtual
Set the state to a saturated system at a particular pressure.
Parameters
p Pressure (Pa)
x Fraction of vapor
Reimplemented from ThermoPhase.
Definition at line 2040 of file HMWSoln.h.
References HMWSoln::err().
void constructPhaseFile (std::string inputFile, std::string id)
Initialization of a HMWSoln phase using an xml file.
This routine is a precursor to initThermo(XML_Node*) routine, which does most of the work.
Parameters
inputFile XML file containing the description of the phase
id Optional parameter identifying the name of the phase. If none is given, the first XML phase element will be used.
Definition at line 1064 of file HMWSoln_input.cpp.
References XML_Node::build(), XML_Node::copy(), Cantera::findInputFile(), and Cantera::findXMLPhase().
Referenced by HMWSoln::HMWSoln().
void constructPhaseXML (XML_Node & phaseNode, std::string id)
Import and initialize a HMWSoln phase specification in an XML tree into the current object.
Here we read an XML description of the phase. We import descriptions of the elements that make up the species in a phase. We import information about the species, including their reference state thermodynamic polynomials. We then freeze the state of the species.
Then, we read the species molar volumes from the xml tree to finish the initialization.
Parameters
phaseNode This object must be the phase node of a complete XML tree description of the phase, including all of the species data. In other words while "phase" must point to an XML phase object, it must have sibling nodes "speciesData" that describe the species in the phase.
id ID of the phase. If nonnull, a check is done to see if phaseNode is pointing to the phase with the correct id.
Definition at line 1122 of file HMWSoln_input.cpp.
References Cantera::atofCheck(), XML_Node::attrib(), XML_Node::child(), ctml::getStringArray(), XML_Node::hasChild(), XML_Node::id(), Cantera::importPhase(), Cantera::lowercase(), and PITZERFORM_BASE.
Referenced by HMWSoln::HMWSoln(), and Cantera::newPhase().
void initThermo () virtual
Internal initialization required after all species have been added.
Initialize. This method is provided to allow subclasses to perform any initialization required after all species have been added. For example, it might be used to resize internal work arrays that must have an entry for each species. The base class implementation does nothing, and subclasses that do not require initialization do not need to overload this method. When importing a CTML phase description, this method is called just prior to returning from function importPhase.
See Also
importCTML.cpp
Reimplemented from MolalityVPSSTP.
Definition at line 1044 of file HMWSoln_input.cpp.
void initThermoXML (XML_Node & phaseNode, std::string id) virtual
Initialize the phase parameters from an XML file.
Process the XML file after species are set up.
initThermoXML() (virtual from ThermoPhase)
This gets called from importPhase(). It processes the XML file after the species are set up. This is the main routine for reading in activity coefficient parameters.
Parameters
phaseNode This object must be the phase node of a complete XML tree description of the phase, including all of the species data. In other words while "phase" must point to an XML phase object, it must have sibling nodes "speciesData" that describe the species in the phase.
id ID of the phase. If nonnull, a check is done to see if phaseNode is pointing to the phase with the correct id.
This gets called from importPhase(). It processes the XML file after the species are set up. This is the main routine for reading in activity coefficient parameters.
Parameters
phaseNode This object must be the phase node of a complete XML tree description of the phase, including all of the species data. In other words while "phase" must point to an XML phase object, it must have sibling nodes "speciesData" that describe the species in the phase.
id ID of the phase. If nonnull, a check is done to see if phaseNode is pointing to the phase with the correct id.
Reimplemented from VPStandardStateTP.
Definition at line 1270 of file HMWSoln_input.cpp.
References XML_Node::attrib(), Cantera::cEST_solvent, XML_Node::child(), DATA_PTR, XML_Node::findByAttr(), XML_Node::findByName(), ctml::fpValue(), Cantera::get_XML_NameID(), ctml::getChildValue(), ctml::getFloat(), ctml::getMap(), ctml::getOptionalFloat(), ctml::getStringArray(), XML_Node::hasAttrib(), XML_Node::hasChild(), Cantera::interp_est(), Cantera::lowercase(), XML_Node::name(), XML_Node::nChildren(), Cantera::npos, Cantera::OneAtm, XML_Node::root(), and Cantera::toSI().
double speciesMolarVolume (int k) const
Report the molar volume of species k.
units - \(m^3 kmol^-1 \)
Parameters
k species index
Deprecated:
The getPartialMolarVolumes() expression is more precise.
Definition at line 1433 of file HMWSoln.cpp.
References PDSS::density(), Phase::m_speciesSize, HMWSoln::m_waterSS, and Phase::molecularWeight().
double A_Debye_TP (double temperature = -1.0, double pressure = -1.0) const virtual
Value of the Debye Huckel constant as a function of temperature and pressure.
       A_Debye = (F e B_Debye) / (8 Pi epsilon R T)
       Units = sqrt(kg/gmol)
Parameters
temperature Temperature of the derivative calculation or -1 to indicate the current temperature
pressure Pressure of the derivative calculation or -1 to indicate the current pressure
Definition at line 1463 of file HMWSoln.cpp.
References WaterProps::ADebye(), HMWSoln::m_A_Debye, HMWSoln::m_form_A_Debye, HMWSoln::m_waterProps, HMWSoln::pressure(), and Phase::temperature().
Referenced by HMWSoln::getUnscaledMolalityActivityCoefficients().
double dA_DebyedT_TP (double temperature = -1.0, double pressure = -1.0) const virtual
Value of the derivative of the Debye Huckel constant with respect to temperature as a function of temperature and pressure.
       A_Debye = (F e B_Debye) / (8 Pi epsilon R T)
       Units = sqrt(kg/gmol)
Parameters
temperature Temperature of the derivative calculation or -1 to indicate the current temperature
pressure Pressure of the derivative calculation or -1 to indicate the current pressure
Definition at line 1500 of file HMWSoln.cpp.
References WaterProps::ADebye(), HMWSoln::m_form_A_Debye, HMWSoln::m_waterProps, HMWSoln::pressure(), and Phase::temperature().
Referenced by HMWSoln::ADebye_L(), HMWSoln::s_NBS_CLM_dlnMolalityActCoeff_dT(), and HMWSoln::s_updatePitzer_dlnMolalityActCoeff_dT().
double dA_DebyedP_TP (double temperature = -1.0, double pressure = -1.0) const virtual
Value of the derivative of the Debye Huckel constant with respect to pressure, as a function of temperature and pressure.
 A_Debye = (F e B_Debye) / (8 Pi epsilon R T)
Units = sqrt(kg/gmol)
Parameters
temperature Temperature of the derivative calculation or -1 to indicate the current temperature
pressure Pressure of the derivative calculation or -1 to indicate the current pressure
Definition at line 1536 of file HMWSoln.cpp.
References WaterProps::ADebye(), HMWSoln::m_form_A_Debye, HMWSoln::m_waterProps, HMWSoln::pressure(), and Phase::temperature().
Referenced by HMWSoln::ADebye_V(), HMWSoln::s_NBS_CLM_dlnMolalityActCoeff_dP(), and HMWSoln::s_updatePitzer_dlnMolalityActCoeff_dP().
double ADebye_L (double temperature = -1.0, double pressure = -1.0) const
Return Pitzer's definition of A_L.
This is basically the derivative of the A_phi multiplied by 4 R T**2
       A_Debye = (F e B_Debye) / (8 Pi epsilon R T)
       dA_phidT = d(A_Debye)/dT / 3.0
       A_L = dA_phidT * (4 * R * T * T)
       Units = sqrt(kg/gmol) (RT)
Parameters
temperature Temperature of the derivative calculation or -1 to indicate the current temperature
pressure Pressure of the derivative calculation or -1 to indicate the current pressure
Definition at line 1572 of file HMWSoln.cpp.
References HMWSoln::dA_DebyedT_TP(), Cantera::GasConstant, and Phase::temperature().
Referenced by HMWSoln::ADebye_J().
double ADebye_J (double temperature = -1.0, double pressure = -1.0) const
Return Pitzer's definition of A_J.
This is basically the temperature derivative of A_L, and the second derivative of A_phi
       A_Debye = (F e B_Debye) / (8 Pi epsilon R T)
       dA_phidT = d(A_Debye)/dT / 3.0
       A_J = 2 A_L/T + 4 * R * T * T * d2(A_phi)/dT2
       Units = sqrt(kg/gmol) (R)
Parameters
temperature Temperature of the derivative calculation or -1 to indicate the current temperature
pressure Pressure of the derivative calculation or -1 to indicate the current pressure
Definition at line 1624 of file HMWSoln.cpp.
References HMWSoln::ADebye_L(), HMWSoln::d2A_DebyedT2_TP(), Cantera::GasConstant, and Phase::temperature().
double ADebye_V (double temperature = -1.0, double pressure = -1.0) const
Return Pitzer's definition of A_V.
This is the derivative wrt pressure of A_phi multiplied by - 4 R T
       A_Debye = (F e B_Debye) / (8 Pi epsilon R T)
       dA_phidT = d(A_Debye)/dP / 3.0
       A_V = - dA_phidP * (4 * R * T)
       Units = sqrt(kg/gmol) (RT) / Pascal
Parameters
temperature Temperature of the derivative calculation or -1 to indicate the current temperature
pressure Pressure of the derivative calculation or -1 to indicate the current pressure
Definition at line 1594 of file HMWSoln.cpp.
References HMWSoln::dA_DebyedP_TP(), Cantera::GasConstant, and Phase::temperature().
double d2A_DebyedT2_TP (double temperature = -1.0, double pressure = -1.0) const virtual
Value of the 2nd derivative of the Debye Huckel constant with respect to temperature as a function of temperature and pressure.
       A_Debye = (F e B_Debye) / (8 Pi epsilon R T)
       Units = sqrt(kg/gmol)
Parameters
temperature Temperature of the derivative calculation or -1 to indicate the current temperature
pressure Pressure of the derivative calculation or -1 to indicate the current pressure
Definition at line 1647 of file HMWSoln.cpp.
References WaterProps::ADebye(), HMWSoln::m_form_A_Debye, HMWSoln::m_waterProps, HMWSoln::pressure(), and Phase::temperature().
Referenced by HMWSoln::ADebye_J(), HMWSoln::s_NBS_CLM_d2lnMolalityActCoeff_dT2(), and HMWSoln::s_updatePitzer_d2lnMolalityActCoeff_dT2().
double AionicRadius (int k = 0) const
Reports the ionic radius of the kth species.
Parameters
k Species index
Definition at line 1679 of file HMWSoln.cpp.
References HMWSoln::m_Aionic.
int formPitzer () const inline
formPitzer():
Returns the form of the Pitzer parameterization used
Definition at line 2285 of file HMWSoln.h.
References HMWSoln::m_formPitzer.
void printCoeffs () const
Print out all of the input coefficients.
This routine prints out the input pitzer coefficients for the current mechanism.
Definition at line 6347 of file HMWSoln.cpp.
References MolalityVPSSTP::calcMolalities(), Phase::charge(), DATA_PTR, Phase::getMoleFractions(), Cantera::int2str(), HMWSoln::m_Alpha1MX_ij, HMWSoln::m_Beta0MX_ij, HMWSoln::m_Beta1MX_ij, HMWSoln::m_Beta2MX_ij, HMWSoln::m_CounterIJ, HMWSoln::m_CphiMX_ij, Phase::m_kk, HMWSoln::m_molalitiesCropped, HMWSoln::m_Psi_ijk, Phase::m_speciesCharge, HMWSoln::m_Theta_ij, HMWSoln::m_tmpV, HMWSoln::s_updatePitzer_CoeffWRTemp(), and Phase::speciesName().
Referenced by HMWSoln::HMWSoln().
void getUnscaledMolalityActivityCoefficients (doublereal * acMolality) const virtual
Get the array of unscaled non-dimensional molality based activity coefficients at the current solution temperature, pressure, and solution concentration.
See Denbigh p. 278 for a thorough discussion. This class must be overwritten in classes which derive from MolalityVPSSTP. This function takes over from the molar-based activity coefficient calculation, getActivityCoefficients(), in derived classes.
Parameters
acMolality Output vector containing the molality based activity coefficients. length: m_kk.
Reimplemented from MolalityVPSSTP.
Definition at line 1084 of file HMWSoln.cpp.
References HMWSoln::A_Debye_TP(), Phase::m_kk, HMWSoln::m_lnActCoeffMolal_Unscaled, HMWSoln::s_update_lnMolalityActCoeff(), and VPStandardStateTP::updateStandardStateThermo().
void s_updateScaling_pHScaling () const private
Apply the current phScale to a set of activity Coefficients.
See the Eq3/6 Manual for a thorough discussion.
Definition at line 6434 of file HMWSoln.cpp.
References AssertTrace, MolalityVPSSTP::m_indexCLM, Phase::m_kk, HMWSoln::m_lnActCoeffMolal_Scaled, HMWSoln::m_lnActCoeffMolal_Unscaled, MolalityVPSSTP::m_pHScalingType, Phase::m_speciesCharge, Cantera::PHSCALE_NBS, Cantera::PHSCALE_PITZER, and HMWSoln::s_NBS_CLM_lnMolalityActCoeff().
Referenced by HMWSoln::s_update_lnMolalityActCoeff().
void s_updateScaling_pHScaling_dT () const private
Apply the current phScale to a set of derivatives of the activity Coefficients wrt temperature.
See the Eq3/6 Manual for a thorough discussion of the need
Definition at line 6455 of file HMWSoln.cpp.
References AssertTrace, HMWSoln::m_dlnActCoeffMolaldT_Scaled, HMWSoln::m_dlnActCoeffMolaldT_Unscaled, MolalityVPSSTP::m_indexCLM, Phase::m_kk, MolalityVPSSTP::m_pHScalingType, Phase::m_speciesCharge, Cantera::PHSCALE_NBS, Cantera::PHSCALE_PITZER, and HMWSoln::s_NBS_CLM_dlnMolalityActCoeff_dT().
Referenced by HMWSoln::s_update_dlnMolalityActCoeff_dT().
void s_updateScaling_pHScaling_dT2 () const private
Apply the current phScale to a set of 2nd derivatives of the activity Coefficients wrt temperature.
See the Eq3/6 Manual for a thorough discussion of the need
Definition at line 6476 of file HMWSoln.cpp.
References AssertTrace, HMWSoln::m_d2lnActCoeffMolaldT2_Scaled, HMWSoln::m_d2lnActCoeffMolaldT2_Unscaled, MolalityVPSSTP::m_indexCLM, Phase::m_kk, MolalityVPSSTP::m_pHScalingType, Phase::m_speciesCharge, Cantera::PHSCALE_NBS, Cantera::PHSCALE_PITZER, and HMWSoln::s_NBS_CLM_d2lnMolalityActCoeff_dT2().
Referenced by HMWSoln::s_update_d2lnMolalityActCoeff_dT2().
void s_updateScaling_pHScaling_dP () const private
Apply the current phScale to a set of derivatives of the activity Coefficients wrt pressure.
See the Eq3/6 Manual for a thorough discussion of the need
Definition at line 6496 of file HMWSoln.cpp.
References AssertTrace, HMWSoln::m_dlnActCoeffMolaldP_Scaled, HMWSoln::m_dlnActCoeffMolaldP_Unscaled, MolalityVPSSTP::m_indexCLM, Phase::m_kk, MolalityVPSSTP::m_pHScalingType, Phase::m_speciesCharge, Cantera::PHSCALE_NBS, Cantera::PHSCALE_PITZER, and HMWSoln::s_NBS_CLM_dlnMolalityActCoeff_dP().
Referenced by HMWSoln::s_update_dlnMolalityActCoeff_dP().
doublereal s_NBS_CLM_lnMolalityActCoeff () const private
Calculate the Chlorine activity coefficient on the NBS scale.
We assume here that the m_IionicMolality variable is up to date.
Definition at line 6515 of file HMWSoln.cpp.
References HMWSoln::m_A_Debye, and HMWSoln::m_IionicMolality.
Referenced by HMWSoln::applyphScale(), and HMWSoln::s_updateScaling_pHScaling().
doublereal s_NBS_CLM_dlnMolalityActCoeff_dT () const private
Calculate the temperature derivative of the Chlorine activity coefficient on the NBS scale.
We assume here that the m_IionicMolality variable is up to date.
Definition at line 6527 of file HMWSoln.cpp.
References HMWSoln::dA_DebyedT_TP(), and HMWSoln::m_IionicMolality.
Referenced by HMWSoln::s_updateScaling_pHScaling_dT().
doublereal s_NBS_CLM_d2lnMolalityActCoeff_dT2 () const private
Calculate the second temperature derivative of the Chlorine activity coefficient on the NBS scale.
We assume here that the m_IionicMolality variable is up to date.
Definition at line 6539 of file HMWSoln.cpp.
References HMWSoln::d2A_DebyedT2_TP(), and HMWSoln::m_IionicMolality.
Referenced by HMWSoln::s_updateScaling_pHScaling_dT2().
doublereal s_NBS_CLM_dlnMolalityActCoeff_dP () const private
Calculate the pressure derivative of the Chlorine activity coefficient.
We assume here that the m_IionicMolality variable is up to date.
Definition at line 6551 of file HMWSoln.cpp.
References HMWSoln::dA_DebyedP_TP(), and HMWSoln::m_IionicMolality.
Referenced by HMWSoln::s_updateScaling_pHScaling_dP().
doublereal err (std::string msg) const private
Local error routine.
Bail out of functions with an error exit if they are not implemented.
Parameters
msg print out a message and error exit
Definition at line 1692 of file HMWSoln.cpp.
Referenced by HMWSoln::critDensity(), HMWSoln::critPressure(), HMWSoln::critTemperature(), HMWSoln::satTemperature(), HMWSoln::setState_Psat(), HMWSoln::setState_Tsat(), HMWSoln::setToEquilState(), and HMWSoln::vaporFraction().
void initLengths () private
Initialize all of the species - dependent lengths in the object.
Definition at line 1708 of file HMWSoln.cpp.
References HMWSoln::counterIJ_setup(), HMWSoln::CROP_speciesCropped_, HMWSoln::IMS_lnActCoeffMolal_, HMWSoln::m_Aionic, HMWSoln::m_Alpha1MX_ij, HMWSoln::m_Alpha2MX_ij, HMWSoln::m_Beta0MX_ij, HMWSoln::m_Beta0MX_ij_coeff, HMWSoln::m_Beta0MX_ij_L, HMWSoln::m_Beta0MX_ij_LL, HMWSoln::m_Beta0MX_ij_P, HMWSoln::m_Beta1MX_ij, HMWSoln::m_Beta1MX_ij_coeff, HMWSoln::m_Beta1MX_ij_L, HMWSoln::m_Beta1MX_ij_LL, HMWSoln::m_Beta1MX_ij_P, HMWSoln::m_Beta2MX_ij, HMWSoln::m_Beta2MX_ij_coeff, HMWSoln::m_Beta2MX_ij_L, HMWSoln::m_Beta2MX_ij_LL, HMWSoln::m_Beta2MX_ij_P, HMWSoln::m_BMX_IJ, HMWSoln::m_BMX_IJ_L, HMWSoln::m_BMX_IJ_LL, HMWSoln::m_BMX_IJ_P, HMWSoln::m_BphiMX_IJ, HMWSoln::m_BphiMX_IJ_L, HMWSoln::m_BphiMX_IJ_LL, HMWSoln::m_BphiMX_IJ_P, HMWSoln::m_BprimeMX_IJ, HMWSoln::m_BprimeMX_IJ_L, HMWSoln::m_BprimeMX_IJ_LL, HMWSoln::m_BprimeMX_IJ_P, HMWSoln::m_CMX_IJ, HMWSoln::m_CMX_IJ_L, HMWSoln::m_CMX_IJ_LL, HMWSoln::m_CMX_IJ_P, HMWSoln::m_CounterIJ, HMWSoln::m_CphiMX_ij, HMWSoln::m_CphiMX_ij_coeff, HMWSoln::m_CphiMX_ij_L, HMWSoln::m_CphiMX_ij_LL, HMWSoln::m_CphiMX_ij_P, HMWSoln::m_d2lnActCoeffMolaldT2_Scaled, HMWSoln::m_d2lnActCoeffMolaldT2_Unscaled, HMWSoln::m_dlnActCoeffMolaldP_Scaled, HMWSoln::m_dlnActCoeffMolaldP_Unscaled, HMWSoln::m_dlnActCoeffMolaldT_Scaled, HMWSoln::m_dlnActCoeffMolaldT_Unscaled, HMWSoln::m_electrolyteSpeciesType, HMWSoln::m_expg0_RT, HMWSoln::m_formPitzerTemp, HMWSoln::m_g2func_IJ, HMWSoln::m_gamma_tmp, HMWSoln::m_gfunc_IJ, HMWSoln::m_h2func_IJ, HMWSoln::m_hfunc_IJ, Phase::m_kk, HMWSoln::m_Lambda_nj, HMWSoln::m_Lambda_nj_coeff, HMWSoln::m_Lambda_nj_L, HMWSoln::m_Lambda_nj_LL, HMWSoln::m_Lambda_nj_P, HMWSoln::m_lnActCoeffMolal_Scaled, HMWSoln::m_lnActCoeffMolal_Unscaled, HMWSoln::m_molalitiesCropped, HMWSoln::m_Mu_nnn, HMWSoln::m_Mu_nnn_coeff, HMWSoln::m_Mu_nnn_L, HMWSoln::m_Mu_nnn_LL, HMWSoln::m_Mu_nnn_P, HMWSoln::m_pe, HMWSoln::m_Phi_IJ, HMWSoln::m_Phi_IJ_L, HMWSoln::m_Phi_IJ_LL, HMWSoln::m_Phi_IJ_P, HMWSoln::m_PhiPhi_IJ, HMWSoln::m_PhiPhi_IJ_L, HMWSoln::m_PhiPhi_IJ_LL, HMWSoln::m_PhiPhi_IJ_P, HMWSoln::m_Phiprime_IJ, HMWSoln::m_pp, HMWSoln::m_Psi_ijk, HMWSoln::m_Psi_ijk_coeff, HMWSoln::m_Psi_ijk_L, HMWSoln::m_Psi_ijk_LL, HMWSoln::m_Psi_ijk_P, HMWSoln::m_speciesCharge_Stoich, Phase::m_speciesSize, HMWSoln::m_Theta_ij, HMWSoln::m_Theta_ij_coeff, HMWSoln::m_Theta_ij_L, HMWSoln::m_Theta_ij_LL, HMWSoln::m_Theta_ij_P, HMWSoln::m_tmpV, Phase::nSpecies(), and Array2D::resize().
void applyphScale (doublereal * acMolality) const private virtual
Apply the current phScale to a set of activity Coefficients or activities.
See the Eq3/6 Manual for a thorough discussion.
Parameters
acMolality input/Output vector containing the molality based activity coefficients. length: m_kk.
Reimplemented from MolalityVPSSTP.
Definition at line 6413 of file HMWSoln.cpp.
References AssertTrace, MolalityVPSSTP::m_indexCLM, Phase::m_kk, HMWSoln::m_lnActCoeffMolal_Unscaled, MolalityVPSSTP::m_pHScalingType, Phase::m_speciesCharge, Cantera::PHSCALE_NBS, Cantera::PHSCALE_PITZER, and HMWSoln::s_NBS_CLM_lnMolalityActCoeff().
void s_update_lnMolalityActCoeff () const private
Calculate the natural log of the molality-based activity coefficients.
Definition at line 1846 of file HMWSoln.cpp.
References MolalityVPSSTP::calcMolalities(), HMWSoln::calcMolalitiesCropped(), HMWSoln::CROP_ln_gamma_k_max, HMWSoln::CROP_ln_gamma_k_min, HMWSoln::CROP_ln_gamma_o_max, HMWSoln::CROP_ln_gamma_o_min, HMWSoln::CROP_speciesCropped_, HMWSoln::IMS_lnActCoeffMolal_, HMWSoln::m_IionicMolalityStoich, MolalityVPSSTP::m_indexSolvent, Phase::m_kk, HMWSoln::m_lnActCoeffMolal_Unscaled, MolalityVPSSTP::m_molalities, Phase::m_speciesCharge, HMWSoln::m_speciesCharge_Stoich, MolalityVPSSTP::m_xmolSolventMIN, ckr::max(), Phase::moleFraction(), HMWSoln::s_updateIMS_lnMolalityActCoeff(), HMWSoln::s_updatePitzer_CoeffWRTemp(), HMWSoln::s_updatePitzer_lnMolalityActCoeff(), and HMWSoln::s_updateScaling_pHScaling().
Referenced by HMWSoln::getActivities(), HMWSoln::getChemPotentials(), HMWSoln::getPartialMolarCp(), HMWSoln::getPartialMolarEnthalpies(), HMWSoln::getPartialMolarEntropies(), HMWSoln::getPartialMolarVolumes(), and HMWSoln::getUnscaledMolalityActivityCoefficients().
void s_update_dlnMolalityActCoeff_dT () const private
This function calculates the temperature derivative of the natural logarithm of the molality activity coefficients.
s_update_dlnMolalityActCoeff_dT() (private, const)
This is the private function. It does all of the direct work.
Using internally stored values, this function calculates the temperature derivative of the logarithm of the activity coefficient for all species in the mechanism.
We assume that the activity coefficients are current.
solvent activity coefficient is on the molality scale. It's derivative is too.
Definition at line 3476 of file HMWSoln.cpp.
References HMWSoln::CROP_speciesCropped_, HMWSoln::m_dlnActCoeffMolaldT_Unscaled, Phase::m_kk, HMWSoln::s_updatePitzer_dlnMolalityActCoeff_dT(), and HMWSoln::s_updateScaling_pHScaling_dT().
Referenced by HMWSoln::getPartialMolarCp(), HMWSoln::getPartialMolarEnthalpies(), and HMWSoln::getPartialMolarEntropies().
void s_update_d2lnMolalityActCoeff_dT2 () const private
This function calculates the temperature second derivative of the natural logarithm of the molality activity coefficients.
Definition at line 4340 of file HMWSoln.cpp.
References HMWSoln::CROP_speciesCropped_, HMWSoln::m_d2lnActCoeffMolaldT2_Unscaled, Phase::m_kk, HMWSoln::s_updatePitzer_d2lnMolalityActCoeff_dT2(), and HMWSoln::s_updateScaling_pHScaling_dT2().
Referenced by HMWSoln::getPartialMolarCp().
void s_update_dlnMolalityActCoeff_dP () const private
This function calculates the pressure derivative of the natural logarithm of the molality activity coefficients.
Definition at line 5233 of file HMWSoln.cpp.
References HMWSoln::CROP_speciesCropped_, HMWSoln::m_dlnActCoeffMolaldP_Unscaled, Phase::m_kk, HMWSoln::s_updatePitzer_dlnMolalityActCoeff_dP(), and HMWSoln::s_updateScaling_pHScaling_dP().
Referenced by HMWSoln::getPartialMolarVolumes().
void s_updateIMS_lnMolalityActCoeff () const private
This function will be called to update the internally stored natural logarithm of the molality activity coefficients.
Definition at line 6231 of file HMWSoln.cpp.
References MolalityVPSSTP::calcMolalities(), HMWSoln::IMS_afCut_, HMWSoln::IMS_agCut_, HMWSoln::IMS_bfCut_, HMWSoln::IMS_bgCut_, HMWSoln::IMS_cCut_, HMWSoln::IMS_dfCut_, HMWSoln::IMS_dgCut_, HMWSoln::IMS_efCut_, HMWSoln::IMS_egCut_, HMWSoln::IMS_gamma_k_min_, HMWSoln::IMS_gamma_o_min_, HMWSoln::IMS_lnActCoeffMolal_, HMWSoln::IMS_typeCutoff_, HMWSoln::IMS_X_o_cutoff_, MolalityVPSSTP::m_indexSolvent, Phase::m_kk, MolalityVPSSTP::m_xmolSolventMIN, ckr::max(), and Phase::moleFraction().
Referenced by HMWSoln::s_update_lnMolalityActCoeff().
void s_updatePitzer_lnMolalityActCoeff () const private
This function does the main pitzer coefficient calculation.
Definition at line 2428 of file HMWSoln.cpp.
References HMWSoln::calc_lambdas(), HMWSoln::calc_thetas(), Phase::charge(), HMWSoln::counterIJ_setup(), DATA_PTR, HMWSoln::m_A_Debye, HMWSoln::m_Alpha1MX_ij, HMWSoln::m_Alpha2MX_ij, HMWSoln::m_Beta0MX_ij, HMWSoln::m_Beta1MX_ij, HMWSoln::m_Beta2MX_ij, HMWSoln::m_BMX_IJ, HMWSoln::m_BphiMX_IJ, HMWSoln::m_BprimeMX_IJ, HMWSoln::m_CMX_IJ, HMWSoln::m_CounterIJ, HMWSoln::m_CphiMX_ij, HMWSoln::m_debugCalc, HMWSoln::m_g2func_IJ, HMWSoln::m_gamma_tmp, HMWSoln::m_gfunc_IJ, HMWSoln::m_h2func_IJ, HMWSoln::m_hfunc_IJ, HMWSoln::m_IionicMolality, MolalityVPSSTP::m_indexSolvent, Phase::m_kk, HMWSoln::m_Lambda_nj, HMWSoln::m_lnActCoeffMolal_Unscaled, MolalityVPSSTP::m_molalities, HMWSoln::m_molalitiesCropped, HMWSoln::m_Mu_nnn, HMWSoln::m_Phi_IJ, HMWSoln::m_PhiPhi_IJ, HMWSoln::m_Phiprime_IJ, HMWSoln::m_Psi_ijk, Phase::m_speciesCharge, HMWSoln::m_Theta_ij, MolalityVPSSTP::m_weightSolvent, MolalityVPSSTP::m_xmolSolventMIN, ckr::max(), Phase::moleFraction(), Phase::speciesName(), and Phase::temperature().
Referenced by HMWSoln::s_update_lnMolalityActCoeff().
void s_updatePitzer_dlnMolalityActCoeff_dT () const private
Calculates the temperature derivative of the natural logarithm of the molality activity coefficients.
Public function makes sure that all dependent data is up to date, before calling a private function
Definition at line 3522 of file HMWSoln.cpp.
References HMWSoln::calc_lambdas(), HMWSoln::calc_thetas(), Phase::charge(), HMWSoln::counterIJ_setup(), HMWSoln::dA_DebyedT_TP(), DATA_PTR, HMWSoln::m_Alpha1MX_ij, HMWSoln::m_Alpha2MX_ij, HMWSoln::m_Beta0MX_ij_L, HMWSoln::m_Beta1MX_ij_L, HMWSoln::m_Beta2MX_ij_L, HMWSoln::m_BMX_IJ_L, HMWSoln::m_BphiMX_IJ_L, HMWSoln::m_BprimeMX_IJ_L, HMWSoln::m_CMX_IJ_L, HMWSoln::m_CounterIJ, HMWSoln::m_CphiMX_ij_L, HMWSoln::m_debugCalc, HMWSoln::m_dlnActCoeffMolaldT_Unscaled, HMWSoln::m_g2func_IJ, HMWSoln::m_gamma_tmp, HMWSoln::m_gfunc_IJ, HMWSoln::m_h2func_IJ, HMWSoln::m_hfunc_IJ, HMWSoln::m_IionicMolality, MolalityVPSSTP::m_indexSolvent, Phase::m_kk, HMWSoln::m_Lambda_nj_L, HMWSoln::m_molalitiesCropped, HMWSoln::m_Mu_nnn_L, HMWSoln::m_Phi_IJ_L, HMWSoln::m_PhiPhi_IJ_L, HMWSoln::m_Phiprime_IJ, HMWSoln::m_Psi_ijk_L, Phase::m_speciesCharge, HMWSoln::m_Theta_ij_L, MolalityVPSSTP::m_weightSolvent, and Phase::speciesName().
Referenced by HMWSoln::s_update_dlnMolalityActCoeff_dT().
void s_updatePitzer_d2lnMolalityActCoeff_dT2 () const private
This function calculates the temperature second derivative of the natural logarithm of the molality activity coefficients.
Definition at line 4392 of file HMWSoln.cpp.
References HMWSoln::calc_lambdas(), HMWSoln::calc_thetas(), Phase::charge(), HMWSoln::counterIJ_setup(), HMWSoln::d2A_DebyedT2_TP(), DATA_PTR, HMWSoln::m_Alpha1MX_ij, HMWSoln::m_Alpha2MX_ij, HMWSoln::m_Beta0MX_ij_LL, HMWSoln::m_Beta1MX_ij_LL, HMWSoln::m_Beta2MX_ij_LL, HMWSoln::m_BMX_IJ_LL, HMWSoln::m_BphiMX_IJ_LL, HMWSoln::m_BprimeMX_IJ_LL, HMWSoln::m_CMX_IJ_LL, HMWSoln::m_CounterIJ, HMWSoln::m_CphiMX_ij_LL, HMWSoln::m_d2lnActCoeffMolaldT2_Unscaled, HMWSoln::m_debugCalc, HMWSoln::m_g2func_IJ, HMWSoln::m_gfunc_IJ, HMWSoln::m_h2func_IJ, HMWSoln::m_hfunc_IJ, HMWSoln::m_IionicMolality, MolalityVPSSTP::m_indexSolvent, Phase::m_kk, HMWSoln::m_Lambda_nj_LL, HMWSoln::m_molalitiesCropped, HMWSoln::m_Mu_nnn_LL, HMWSoln::m_Phi_IJ_LL, HMWSoln::m_PhiPhi_IJ_LL, HMWSoln::m_Phiprime_IJ, HMWSoln::m_Psi_ijk_LL, Phase::m_speciesCharge, HMWSoln::m_Theta_ij_LL, MolalityVPSSTP::m_weightSolvent, and Phase::speciesName().
Referenced by HMWSoln::s_update_d2lnMolalityActCoeff_dT2().
void s_updatePitzer_dlnMolalityActCoeff_dP () const private
Calculates the Pressure derivative of the natural logarithm of the molality activity coefficients.
Public function makes sure that all dependent data is up to date, before calling a private function
Definition at line 5271 of file HMWSoln.cpp.
References HMWSoln::calc_lambdas(), HMWSoln::calc_thetas(), Phase::charge(), HMWSoln::counterIJ_setup(), HMWSoln::dA_DebyedP_TP(), DATA_PTR, HMWSoln::m_Alpha1MX_ij, HMWSoln::m_Alpha2MX_ij, HMWSoln::m_Beta0MX_ij_P, HMWSoln::m_Beta1MX_ij_P, HMWSoln::m_Beta2MX_ij_P, HMWSoln::m_BMX_IJ_P, HMWSoln::m_BphiMX_IJ_P, HMWSoln::m_BprimeMX_IJ_P, HMWSoln::m_CMX_IJ_P, HMWSoln::m_CounterIJ, HMWSoln::m_CphiMX_ij_P, HMWSoln::m_debugCalc, HMWSoln::m_dlnActCoeffMolaldP_Unscaled, HMWSoln::m_g2func_IJ, HMWSoln::m_gfunc_IJ, HMWSoln::m_h2func_IJ, HMWSoln::m_hfunc_IJ, HMWSoln::m_IionicMolality, MolalityVPSSTP::m_indexSolvent, Phase::m_kk, HMWSoln::m_Lambda_nj_P, HMWSoln::m_molalitiesCropped, HMWSoln::m_Mu_nnn_P, HMWSoln::m_Phi_IJ_P, HMWSoln::m_PhiPhi_IJ_P, HMWSoln::m_Phiprime_IJ, HMWSoln::m_Psi_ijk_P, Phase::m_speciesCharge, HMWSoln::m_Theta_ij_P, MolalityVPSSTP::m_weightSolvent, HMWSoln::pressure(), Phase::speciesName(), and Phase::temperature().
Referenced by HMWSoln::s_update_dlnMolalityActCoeff_dP().
void s_updatePitzer_CoeffWRTemp (int doDerivs = 2) const private
Calculates the Pitzer coefficients' dependence on the temperature.
It will also calculate the temperature derivatives of the coefficients, as they are important in the calculation of the latent heats and the heat capacities of the mixtures.
Parameters
doDerivs If >= 1, then the routine will calculate the first derivative. If >= 2, the routine will calculate the first and second temperature derivative. default = 2
Definition at line 2147 of file HMWSoln.cpp.
References HMWSoln::m_Beta0MX_ij, HMWSoln::m_Beta0MX_ij_coeff, HMWSoln::m_Beta0MX_ij_L, HMWSoln::m_Beta0MX_ij_LL, HMWSoln::m_Beta1MX_ij, HMWSoln::m_Beta1MX_ij_coeff, HMWSoln::m_Beta1MX_ij_L, HMWSoln::m_Beta1MX_ij_LL, HMWSoln::m_Beta2MX_ij, HMWSoln::m_Beta2MX_ij_coeff, HMWSoln::m_Beta2MX_ij_L, HMWSoln::m_Beta2MX_ij_LL, HMWSoln::m_CounterIJ, HMWSoln::m_CphiMX_ij, HMWSoln::m_CphiMX_ij_coeff, HMWSoln::m_CphiMX_ij_L, HMWSoln::m_CphiMX_ij_LL, HMWSoln::m_formPitzerTemp, Phase::m_kk, HMWSoln::m_Lambda_nj, HMWSoln::m_Lambda_nj_coeff, HMWSoln::m_Lambda_nj_L, HMWSoln::m_Lambda_nj_LL, HMWSoln::m_Mu_nnn, HMWSoln::m_Mu_nnn_coeff, HMWSoln::m_Mu_nnn_L, HMWSoln::m_Mu_nnn_LL, HMWSoln::m_Psi_ijk, HMWSoln::m_Psi_ijk_coeff, HMWSoln::m_Psi_ijk_L, HMWSoln::m_Psi_ijk_LL, Phase::m_speciesCharge, HMWSoln::m_TempPitzerRef, HMWSoln::m_Theta_ij, HMWSoln::m_Theta_ij_coeff, HMWSoln::m_Theta_ij_L, HMWSoln::m_Theta_ij_LL, Array2D::ptrColumn(), and Phase::temperature().
Referenced by HMWSoln::printCoeffs(), and HMWSoln::s_update_lnMolalityActCoeff().
void calc_lambdas (double is) const private
Calculate the lambda interactions.
Calculate E-lambda terms for charge combinations of like sign, using method of Pitzer (1975).
Parameters
is Ionic strength
Definition at line 6107 of file HMWSoln.cpp.
References HMWSoln::elambda, HMWSoln::elambda1, and HMWSoln::m_debugCalc.
Referenced by HMWSoln::s_updatePitzer_d2lnMolalityActCoeff_dT2(), HMWSoln::s_updatePitzer_dlnMolalityActCoeff_dP(), HMWSoln::s_updatePitzer_dlnMolalityActCoeff_dT(), and HMWSoln::s_updatePitzer_lnMolalityActCoeff().
void calc_thetas (int z1, int z2, double * etheta, double * etheta_prime) const private
Calculate etheta and etheta_prime.
This interaction will be nonzero for species with the same charge. this routine is not to be called for neutral species; it core dumps or error exits.
MEC implementation routine.
Parameters
z1 charge of the first molecule
z2 charge of the second molecule
etheta return pointer containing etheta
etheta_prime Return pointer containing etheta_prime.
This routine uses the internal variables, elambda[] and elambda1[].
There is no prohibition against calling
Definition at line 6177 of file HMWSoln.cpp.
References HMWSoln::elambda, and HMWSoln::elambda1.
Referenced by HMWSoln::s_updatePitzer_d2lnMolalityActCoeff_dT2(), HMWSoln::s_updatePitzer_dlnMolalityActCoeff_dP(), HMWSoln::s_updatePitzer_dlnMolalityActCoeff_dT(), and HMWSoln::s_updatePitzer_lnMolalityActCoeff().
void counterIJ_setup (void) const private
Set up a counter variable for keeping track of symmetric binary interactions amongst the solute species.
The purpose of this is to squeeze the ij parameters into a compressed single counter.
n = m_kk*i + j m_Counter[n] = counter
Definition at line 2110 of file HMWSoln.cpp.
References HMWSoln::m_CounterIJ, and Phase::m_kk.
Referenced by HMWSoln::initLengths(), HMWSoln::s_updatePitzer_d2lnMolalityActCoeff_dT2(), HMWSoln::s_updatePitzer_dlnMolalityActCoeff_dP(), HMWSoln::s_updatePitzer_dlnMolalityActCoeff_dT(), and HMWSoln::s_updatePitzer_lnMolalityActCoeff().
void calcMolalitiesCropped () const private
Calculate the cropped molalities.
This is an internal routine that calculates values of m_molalitiesCropped from m_molalities
Definition at line 1938 of file HMWSoln.cpp.
References Phase::charge(), DATA_PTR, Phase::getMoleFractions(), HMWSoln::m_gamma_tmp, MolalityVPSSTP::m_indexSolvent, Phase::m_kk, HMWSoln::m_maxIionicStrength, MolalityVPSSTP::m_Mnaught, MolalityVPSSTP::m_molalities, HMWSoln::m_molalitiesAreCropped, HMWSoln::m_molalitiesCropped, Phase::m_speciesCharge, HMWSoln::MC_apCut_, HMWSoln::MC_bpCut_, HMWSoln::MC_cpCut_, HMWSoln::MC_dpCut_, HMWSoln::MC_epCut_, HMWSoln::MC_X_o_cutoff_, and Cantera::npos.
Referenced by HMWSoln::s_update_lnMolalityActCoeff().
void readXMLBinarySalt (XML_Node & BinSalt) private
Process an XML node called "binarySaltParameters".
This node contains all of the parameters necessary to describe the Pitzer model for that particular binary salt. This function reads the XML file and writes the coefficients it finds to an internal data structures.
Parameters
BinSalt reference to the XML_Node named binarySaltParameters containing the anion - cation interaction
Definition at line 70 of file HMWSoln_input.cpp.
References Cantera::atofCheck(), XML_Node::attrib(), XML_Node::child(), DATA_PTR, ctml::getFloatArray(), Cantera::lowercase(), XML_Node::name(), XML_Node::nChildren(), Cantera::npos, and XML_Node::value().
void readXMLThetaAnion (XML_Node & BinSalt) private
Process an XML node called "thetaAnion".
This node contains all of the parameters necessary to describe the binary interactions between two anions.
Parameters
BinSalt reference to the XML_Node named thetaAnion containing the anion - anion interaction
This node contains all of the parameters necessary to describe the binary interactions between two anions.
Definition at line 276 of file HMWSoln_input.cpp.
References XML_Node::attrib(), XML_Node::child(), DATA_PTR, ctml::getFloatArray(), Cantera::lowercase(), XML_Node::name(), XML_Node::nChildren(), and Cantera::npos.
void readXMLThetaCation (XML_Node & BinSalt) private
Process an XML node called "thetaCation".
This node contains all of the parameters necessary to describe the binary interactions between two cations.
Parameters
BinSalt reference to the XML_Node named thetaCation containing the cation - cation interaction
This node contains all of the parameters necessary to describe the binary interactions between two cation.
Definition at line 363 of file HMWSoln_input.cpp.
References XML_Node::attrib(), XML_Node::child(), DATA_PTR, ctml::getFloatArray(), Cantera::lowercase(), XML_Node::name(), XML_Node::nChildren(), and Cantera::npos.
void readXMLPsiCommonAnion (XML_Node & BinSalt) private
Process an XML node called "psiCommonAnion".
Process an XML node called "PsiCommonAnion".
This node contains all of the parameters necessary to describe the ternary interactions between one anion and two cations.
Parameters
BinSalt reference to the XML_Node named psiCommonAnion containing the anion - cation1 - cation2 interaction
This node contains all of the parameters necessary to describe the binary interactions between two cations and one common anion.
Definition at line 596 of file HMWSoln_input.cpp.
References Cantera::atofCheck(), XML_Node::attrib(), XML_Node::child(), DATA_PTR, ctml::getFloatArray(), Cantera::lowercase(), XML_Node::name(), XML_Node::nChildren(), Cantera::npos, and XML_Node::value().
void readXMLPsiCommonCation (XML_Node & BinSalt) private
Process an XML node called "psiCommonCation".
This node contains all of the parameters necessary to describe the ternary interactions between one cation and two anions.
Parameters
BinSalt reference to the XML_Node named psiCommonCation containing the cation - anion1 - anion2 interaction
Definition at line 450 of file HMWSoln_input.cpp.
References Cantera::atofCheck(), XML_Node::attrib(), XML_Node::child(), DATA_PTR, ctml::getFloatArray(), Cantera::lowercase(), XML_Node::name(), XML_Node::nChildren(), Cantera::npos, and XML_Node::value().
void readXMLLambdaNeutral (XML_Node & BinSalt) private
Process an XML node called "lambdaNeutral".
Process an XML node called "LambdaNeutral".
This node contains all of the parameters necessary to describe the binary interactions between one neutral species and any other species (neutral or otherwise) in the mechanism.
Parameters
BinSalt reference to the XML_Node named lambdaNeutral containing multiple Neutral - species interactions
This node contains all of the parameters necessary to describe the binary interactions between one neutral species and any other species (neutral or otherwise) in the mechanism.
Definition at line 746 of file HMWSoln_input.cpp.
References XML_Node::attrib(), XML_Node::child(), DATA_PTR, ctml::getFloatArray(), Cantera::lowercase(), XML_Node::name(), XML_Node::nChildren(), and Cantera::npos.
void readXMLMunnnNeutral (XML_Node & BinSalt) private
Process an XML node called "MunnnNeutral".
This node contains all of the parameters necessary to describe the self-ternary interactions for one neutral species.
Parameters
BinSalt reference to the XML_Node named Munnn containing the self-ternary interaction
This node contains all of the parameters necessary to describe the self-ternary interactions for one neutral species.
Definition at line 832 of file HMWSoln_input.cpp.
References XML_Node::attrib(), XML_Node::child(), DATA_PTR, ctml::getFloatArray(), Cantera::lowercase(), XML_Node::name(), XML_Node::nChildren(), and Cantera::npos.
void readXMLZetaCation (const XML_Node & BinSalt) private
Process an XML node called "zetaCation".
This node contains all of the parameters necessary to describe the ternary interactions between one neutral, one cation, and one anion.
Parameters
BinSalt reference to the XML_Node named psiCommonCation containing the neutral - cation - anion interaction
Definition at line 907 of file HMWSoln_input.cpp.
References XML_Node::attrib(), XML_Node::child(), DATA_PTR, ctml::getFloatArray(), Cantera::lowercase(), XML_Node::name(), XML_Node::nChildren(), and Cantera::npos.
void readXMLCroppingCoefficients (const XML_Node & acNode) private
Process an XML node called "croppingCoefficients" for the cropping coefficients values.
Parameters
acNode Activity Coefficient XML Node
Definition at line 1012 of file HMWSoln_input.cpp.
References XML_Node::child(), ctml::getOptionalFloat(), and XML_Node::hasChild().
void calcIMSCutoffParams_ () private
Precalculate the IMS Cutoff parameters for typeCutoff = 2.
Definition at line 1740 of file HMWSoln_input.cpp.
void calcMCCutoffParams_ () private
Calculate molality cut-off parameters.
Definition at line 1791 of file HMWSoln_input.cpp.
int interp_est (std::string estString) static private
Utility function to assign an integer value from a string for the ElectrolyteSpeciesType field.
utility function to assign an integer value from a string for the ElectrolyteSpeciesType field.
Parameters
estString string name of the electrolyte species type
Definition at line 38 of file HMWSoln_input.cpp.
References Cantera::cEST_solvent, and Cantera::lowercase().
int debugPrinting ()
Return int specifying the amount of debug printing.
This will return 0 if DEBUG_MODE is not turned on
Definition at line 6559 of file HMWSoln.cpp.
References HMWSoln::m_debugCalc.
void setpHScale (const int pHscaleType) inherited
Set the pH scale, which determines the scale for single-ion activity coefficients.
Single ion activity coefficients are not unique in terms of the representing actual measurable quantities.
Parameters
pHscaleType Integer representing the pHscale
Definition at line 143 of file MolalityVPSSTP.cpp.
References Cantera::int2str(), MolalityVPSSTP::m_pHScalingType, Cantera::PHSCALE_NBS, and Cantera::PHSCALE_PITZER.
int pHScale () const inherited
Reports the pH scale, which determines the scale for single-ion activity coefficients.
Single ion activity coefficients are not unique in terms of the representing actual measurable quantities.
Returns
Return the pHscale type
Definition at line 158 of file MolalityVPSSTP.cpp.
References MolalityVPSSTP::m_pHScalingType.
void setSolvent (size_t k) inherited
This routine sets the index number of the solvent for the phase.
Note, having a solvent is a precursor to many things having to do with molality.
Parameters
k the solvent index number
Definition at line 170 of file MolalityVPSSTP.cpp.
References AssertThrowMsg, MolalityVPSSTP::m_indexSolvent, Phase::m_kk, MolalityVPSSTP::m_Mnaught, MolalityVPSSTP::m_weightSolvent, and Phase::molecularWeight().
Referenced by MolalityVPSSTP::initThermo(), and MolalityVPSSTP::initThermoXML().
void setMoleFSolventMin (doublereal xmolSolventMIN) inherited
Sets the minimum mole fraction in the molality formulation.
Note the molality formulation is singular in the limit that the solvent mole fraction goes to zero. Numerically, how this limit is treated and resolved is an ongoing issue within Cantera.
Parameters
xmolSolventMIN Input double containing the minimum mole fraction
Definition at line 196 of file MolalityVPSSTP.cpp.
References MolalityVPSSTP::m_xmolSolventMIN.
Referenced by IdealMolalSoln::initThermoXML().
size_t solventIndex () const inherited
Returns the solvent index.
Definition at line 186 of file MolalityVPSSTP.cpp.
References MolalityVPSSTP::m_indexSolvent.
doublereal moleFSolventMin () const inherited
Returns the minimum mole fraction in the molality formulation.
Definition at line 209 of file MolalityVPSSTP.cpp.
References MolalityVPSSTP::m_xmolSolventMIN.
void calcMolalities () const inherited
Calculates the molality of all species and stores the result internally.
We calculate the vector of molalities of the species in the phase and store the result internally:
\[ m_i = \frac{X_i}{1000 * M_o * X_{o,p}} \]
where
\(M_o \) is the molecular weight of the solvent
\(X_o \) is the mole fraction of the solvent
\(X_i \) is the mole fraction of the solute.
\(X_{o,p} = max (X_{o}^{min}, X_o) \)
\(X_{o}^{min} \) = minimum mole fraction of solvent allowed in the denominator.
Definition at line 229 of file MolalityVPSSTP.cpp.
References DATA_PTR, Phase::getMoleFractions(), MolalityVPSSTP::m_indexSolvent, Phase::m_kk, MolalityVPSSTP::m_Mnaught, MolalityVPSSTP::m_molalities, and MolalityVPSSTP::m_xmolSolventMIN.
Referenced by DebyeHuckel::_lnactivityWaterHelgesonFixedForm(), IdealMolalSoln::getActivities(), IdealMolalSoln::getChemPotentials(), MolalityVPSSTP::getMolalities(), IdealMolalSoln::getPartialMolarEntropies(), HMWSoln::printCoeffs(), DebyeHuckel::s_update_lnMolalityActCoeff(), HMWSoln::s_update_lnMolalityActCoeff(), IdealMolalSoln::s_updateIMS_lnMolalityActCoeff(), HMWSoln::s_updateIMS_lnMolalityActCoeff(), MolalityVPSSTP::setMolalities(), and MolalityVPSSTP::setMolalitiesByName().
void getMolalities (doublereal *const molal) const inherited
This function will return the molalities of the species.
We calculate the vector of molalities of the species in the phase
\[ m_i = \frac{X_i}{1000 * M_o * X_{o,p}} \]
where
\(M_o \) is the molecular weight of the solvent
\(X_o \) is the mole fraction of the solvent
\(X_i \) is the mole fraction of the solute.
\(X_{o,p} = \max (X_{o}^{min}, X_o) \)
\(X_{o}^{min} \) = minimum mole fraction of solvent allowed in the denominator.
Parameters
molal Output vector of molalities. Length: m_kk.
Definition at line 257 of file MolalityVPSSTP.cpp.
References MolalityVPSSTP::calcMolalities(), Phase::m_kk, and MolalityVPSSTP::m_molalities.
Referenced by MolalityVPSSTP::report(), vcs_MultiPhaseEquil::reportCSV(), and MolalityVPSSTP::reportCSV().
void setMolalities (const doublereal *const molal) inherited
Set the molalities of the solutes in a phase.
Note, the entry for the solvent is not used. We are supplied with the molalities of all of the solute species. We then calculate the mole fractions of all species and update the ThermoPhase object.
\[ m_i = \frac{X_i}{M_o/1000 * X_{o,p}} \]
where
\(M_o\) is the molecular weight of the solvent
\(X_o\) is the mole fraction of the solvent
\(X_i\) is the mole fraction of the solute.
\(X_{o,p} = \max(X_o^{min}, X_o)\)
\(X_o^{min}\) = minimum mole fraction of solvent allowed in the denominator.
The formulas for calculating mole fractions are
\[ L^{sum} = \frac{1}{\tilde{M}_o X_o} = \frac{1}{\tilde{M}_o} + \sum_{i\ne o} m_i \]
Then,
\[ X_o = \frac{1}{\tilde{M}_o L^{sum}} \]
\[ X_i = \frac{m_i}{L^{sum}} \]
It is currently an error if the solvent mole fraction is attempted to be set to a value lower than \(X_o^{min}\).
Parameters
molal Input vector of molalities. Length: m_kk.
Definition at line 280 of file MolalityVPSSTP.cpp.
References MolalityVPSSTP::calcMolalities(), DATA_PTR, MolalityVPSSTP::m_indexSolvent, Phase::m_kk, MolalityVPSSTP::m_Mnaught, MolalityVPSSTP::m_molalities, and Phase::setMoleFractions().
Referenced by MolalityVPSSTP::setState_TPM().
void setMolalitiesByName (compositionMap & xMap) inherited
Set the molalities of a phase.
Set the molalities of the solutes in a phase. Note, the entry for the solvent is not used.
Parameters
xMap Composition Map containing the molalities.
Definition at line 318 of file MolalityVPSSTP.cpp.
References MolalityVPSSTP::calcMolalities(), Phase::charge(), DATA_PTR, Phase::getMoleFractions(), MolalityVPSSTP::m_indexSolvent, MolalityVPSSTP::m_Mnaught, MolalityVPSSTP::m_xmolSolventMIN, ckr::max(), Cantera::npos, Phase::nSpecies(), Phase::setMoleFractions(), and Phase::speciesName().
Referenced by MolalityVPSSTP::setMolalitiesByName(), MolalityVPSSTP::setState_TPM(), and MolalityVPSSTP::setStateFromXML().
void setMolalitiesByName (const std::string & name) inherited
Set the molalities of a phase.
Set the molalities of the solutes in a phase. Note, the entry for the solvent is not used.
Parameters
name String containing the information for a composition map.
Definition at line 405 of file MolalityVPSSTP.cpp.
References Phase::nSpecies(), Cantera::parseCompString(), MolalityVPSSTP::setMolalitiesByName(), and Phase::speciesName().
int activityConvention () const virtual inherited
This method returns the activity convention.
Currently, there are two activity conventions Molar-based activities Unit activity of species at either a hypothetical pure solution of the species or at a hypothetical pure ideal solution at infinite dilution cAC_CONVENTION_MOLAR 0
default
Molality based activities (unit activity of solutes at a hypothetical 1 molal solution referenced to infinite dilution at all pressures and temperatures). cAC_CONVENTION_MOLALITY 1
We set the convention to molality here.
Reimplemented from ThermoPhase.
Definition at line 444 of file MolalityVPSSTP.cpp.
References Cantera::cAC_CONVENTION_MOLALITY.
void getActivityCoefficients (doublereal * ac) const virtual inherited
Get the array of non-dimensional activity coefficients at the current solution temperature, pressure, and solution concentration.
These are mole-fraction based activity coefficients. In this object, their calculation is based on translating the values of the molality-based activity coefficients. See Denbigh p. 278 for a thorough discussion.
The molar-based activity coefficients \(\gamma_k \) may be calculated from the molality-based activity coefficients, \(\gamma_k^\triangle \) by the following formula.
\[ \gamma_k = \frac{\gamma_k^\triangle}{X_o} \]
For purposes of establishing a convention, the molar activity coefficient of the solvent is set equal to the molality-based activity coefficient of the solvent:
\[ \gamma_o = \gamma_o^\triangle \]
Derived classes don't need to overload this function. This function is handled at this level.
Parameters
ac Output vector containing the mole-fraction based activity coefficients. length: m_kk.
Reimplemented from ThermoPhase.
Definition at line 484 of file MolalityVPSSTP.cpp.
References AssertThrow, MolalityVPSSTP::getMolalityActivityCoefficients(), MolalityVPSSTP::m_indexSolvent, Phase::m_kk, MolalityVPSSTP::m_xmolSolventMIN, and Phase::moleFraction().
void getMolalityActivityCoefficients (doublereal * acMolality) const virtual inherited
Get the array of non-dimensional molality based activity coefficients at the current solution temperature, pressure, and solution concentration.
See Denbigh p. 278 for a thorough discussion. This class must be overwritten in classes which derive from MolalityVPSSTP. This function takes over from the molar-based activity coefficient calculation, getActivityCoefficients(), in derived classes.
These molality based activity coefficients are scaled according to the current pH scale. See the Eq3/6 manual for details.
Activity coefficients for species k may be altered between scales s1 to s2 using the following formula
\[ ln(\gamma_k^{s2}) = ln(\gamma_k^{s1}) + \frac{z_k}{z_j} \left(ln(\gamma_j^{s2}) - ln(\gamma_j^{s1}) \right) \]
where j is any one species. For the NBS scale, j is equal to the Cl- species and
\[ ln(\gamma_{Cl-}^{s2}) = \frac{-A_{\phi} \sqrt{I}}{1.0 + 1.5 \sqrt{I}} \]
Parameters
acMolality Output vector containing the molality based activity coefficients. length: m_kk.
Reimplemented in DebyeHuckel, and IdealMolalSoln.
Definition at line 511 of file MolalityVPSSTP.cpp.
References MolalityVPSSTP::applyphScale(), and MolalityVPSSTP::getUnscaledMolalityActivityCoefficients().
Referenced by MolalityVPSSTP::getActivityCoefficients(), MolalityVPSSTP::report(), and MolalityVPSSTP::reportCSV().
doublereal osmoticCoefficient () const virtual inherited
Calculate the osmotic coefficient.
\[ \phi = \frac{- ln(a_o)}{\tilde{M}_o \sum_{i \ne o} m_i} \]
Note there are a few of definitions of the osmotic coefficient floating around. We use the one defined in (Activity Coefficients in Electrolyte Solutions, K. S. Pitzer CRC Press, Boca Raton, 1991, p. 85, Eqn. 28). This definition is most clearly related to theoretical calculation.
units = dimensionless
Definition at line 529 of file MolalityVPSSTP.cpp.
References DATA_PTR, MolalityVPSSTP::getActivities(), MolalityVPSSTP::m_indexSolvent, Phase::m_kk, MolalityVPSSTP::m_Mnaught, MolalityVPSSTP::m_molalities, and ckr::max().
void getElectrochemPotentials (doublereal * mu) const inherited
Get the species electrochemical potentials.
These are partial molar quantities. This method adds a term \(Fz_k \phi_k \) to the to each chemical potential.
Units: J/kmol
Parameters
mu output vector containing the species electrochemical potentials. Length: m_kk.
Definition at line 552 of file MolalityVPSSTP.cpp.
References Phase::charge(), ThermoPhase::electricPotential(), ThermoPhase::getChemPotentials(), and Phase::m_kk.
void setStateFromXML (const XML_Node & state) virtual inherited
Set equation of state parameter values from XML entries.
This method is called by function importPhase() in file importCTML.cpp when processing a phase definition in an input file. It should be overloaded in subclasses to set any parameters that are specific to that particular phase model.
The MolalityVPSSTP object defines a new method for setting the concentrations of a phase. The new method is defined by a block called "soluteMolalities". If this block is found, the concentrations within that phase are set to the "name":"molalities pairs found within that XML block. The solvent concentration is then set to everything else.
The function first calls the overloaded function , VPStandardStateTP::setStateFromXML(), to pick up the parent class behavior.
usage: Overloaded functions should call this function before carrying out their own behavior.
Parameters
state An XML_Node object corresponding to the "state" entry for this phase in the input file.
Reimplemented from ThermoPhase.
Definition at line 628 of file MolalityVPSSTP.cpp.
References ctml::getChildValue(), ctml::getFloat(), XML_Node::hasChild(), MolalityVPSSTP::setMolalitiesByName(), VPStandardStateTP::setPressure(), and ThermoPhase::setStateFromXML().
Referenced by IdealMolalSoln::initThermoXML(), and DebyeHuckel::initThermoXML().
void setState_TPM (doublereal t, doublereal p, const doublereal *const molalities) inherited
Set the temperature (K), pressure (Pa), and molalities (gmol kg-1) of the solutes.
Parameters
t Temperature (K)
p Pressure (Pa)
molalities Input vector of molalities of the solutes. Length: m_kk.
Definition at line 645 of file MolalityVPSSTP.cpp.
References MolalityVPSSTP::setMolalities(), and VPStandardStateTP::setState_TP().
void setState_TPM (doublereal t, doublereal p, compositionMap & m) inherited
Set the temperature (K), pressure (Pa), and molalities.
Parameters
t Temperature (K)
p Pressure (Pa)
m compositionMap containing the molalities
Definition at line 655 of file MolalityVPSSTP.cpp.
References MolalityVPSSTP::setMolalitiesByName(), and VPStandardStateTP::setState_TP().
void setState_TPM (doublereal t, doublereal p, const std::string & m) inherited
Set the temperature (K), pressure (Pa), and molalities.
Parameters
t Temperature (K)
p Pressure (Pa)
m String which gets translated into a composition map for the molalities of the solutes.
Definition at line 664 of file MolalityVPSSTP.cpp.
References MolalityVPSSTP::setMolalitiesByName(), and VPStandardStateTP::setState_TP().
virtual void getdlnActCoeffdlnN (const size_t ld, doublereal *const dlnActCoeffdlnN) inline virtual inherited
Get the array of derivatives of the log activity coefficients with respect to the log of the species mole numbers.
Implementations should take the derivative of the logarithm of the activity coefficient with respect to a species log mole number (with all other species mole numbers held constant). The default treatment in the ThermoPhase object is to set this vector to zero.
units = 1 / kmol
dlnActCoeffdlnN[ ld * k + m] will contain the derivative of log act_coeff for the mth species with respect to the number of moles of the kth species.
\[ \frac{d \ln(\gamma_m) }{d \ln(n_k) }\Bigg|_{n_i} \]
Parameters
ld Number of rows in the matrix
dlnActCoeffdlnN Output vector of derivatives of the log Activity Coefficients. length = m_kk * m_kk
Reimplemented from ThermoPhase.
Definition at line 813 of file MolalityVPSSTP.h.
std::string report (bool show_thermo = true) const virtual inherited
returns a summary of the state of the phase as a string
Format a summary of the mixture state for output.
Parameters
show_thermo If true, extra information is printed out about the thermodynamic state of the system.
Reimplemented from ThermoPhase.
Definition at line 836 of file MolalityVPSSTP.cpp.
References ThermoPhase::cp_mass(), ThermoPhase::cp_mole(), ThermoPhase::cv_mass(), ThermoPhase::cv_mole(), Phase::density(), ThermoPhase::electricPotential(), ThermoPhase::enthalpy_mass(), ThermoPhase::enthalpy_mole(), ThermoPhase::entropy_mass(), ThermoPhase::entropy_mole(), MolalityVPSSTP::err(), MolalityVPSSTP::getActivities(), ThermoPhase::getChemPotentials(), MolalityVPSSTP::getMolalities(), MolalityVPSSTP::getMolalityActivityCoefficients(), Phase::getMoleFractions(), VPStandardStateTP::getStandardChemPotentials(), ThermoPhase::gibbs_mass(), ThermoPhase::gibbs_mole(), ThermoPhase::intEnergy_mass(), ThermoPhase::intEnergy_mole(), Phase::meanMolecularWeight(), Phase::name(), Cantera::npos, Phase::nSpecies(), VPStandardStateTP::pressure(), CanteraError::save(), Cantera::SmallNumber, Phase::speciesIndex(), Phase::speciesName(), and Phase::temperature().
void reportCSV (std::ofstream & csvFile) const virtual inherited
returns a summary of the state of the phase to specified comma separated files
Parameters
csvFile ofstream file to print comma separated data for the phase
Reimplemented from ThermoPhase.
Definition at line 958 of file MolalityVPSSTP.cpp.
References ThermoPhase::cp_mass(), ThermoPhase::cp_mole(), ThermoPhase::cv_mass(), ThermoPhase::cv_mole(), Phase::density(), ThermoPhase::electricPotential(), ThermoPhase::enthalpy_mass(), ThermoPhase::enthalpy_mole(), ThermoPhase::entropy_mass(), ThermoPhase::entropy_mole(), MolalityVPSSTP::err(), MolalityVPSSTP::getActivities(), ThermoPhase::getChemPotentials(), MolalityVPSSTP::getMolalities(), MolalityVPSSTP::getMolalityActivityCoefficients(), Phase::getMoleFractions(), ThermoPhase::getPartialMolarCp(), ThermoPhase::getPartialMolarEnthalpies(), ThermoPhase::getPartialMolarEntropies(), ThermoPhase::getPartialMolarIntEnergies(), ThermoPhase::getPartialMolarVolumes(), VPStandardStateTP::getStandardChemPotentials(), ThermoPhase::gibbs_mass(), ThermoPhase::gibbs_mole(), ThermoPhase::intEnergy_mass(), ThermoPhase::intEnergy_mole(), Phase::meanMolecularWeight(), Phase::name(), Cantera::npos, Phase::nSpecies(), VPStandardStateTP::pressure(), CanteraError::save(), Cantera::SmallNumber, Phase::speciesIndex(), Phase::speciesName(), and Phase::temperature().
int standardStateConvention () const virtual inherited
This method returns the convention used in specification of the standard state, of which there are currently two, temperature based, and variable pressure based.
Currently, there are two standard state conventions:
Temperature-based activities cSS_CONVENTION_TEMPERATURE 0
default
Variable Pressure and Temperature -based activities cSS_CONVENTION_VPSS 1
Reimplemented from ThermoPhase.
Definition at line 163 of file VPStandardStateTP.cpp.
References Cantera::cSS_CONVENTION_VPSS.
virtual void getdlnActCoeffdlnN_diag (doublereal * dlnActCoeffdlnN_diag) const inline virtual inherited
Get the array of log concentration-like derivatives of the log activity coefficients.
This function is a virtual method. For ideal mixtures (unity activity coefficients), this can return zero. Implementations should take the derivative of the logarithm of the activity coefficient with respect to the logarithm of the concentration-like variable (i.e. moles) that represents the standard state. This quantity is to be used in conjunction with derivatives of that concentration-like variable when the derivative of the chemical potential is taken.
units = dimensionless
Parameters
dlnActCoeffdlnN_diag Output vector of derivatives of the log Activity Coefficients. length = m_kk
Reimplemented from ThermoPhase.
Reimplemented in MixedSolventElectrolyte, MargulesVPSSTP, RedlichKisterVPSSTP, PhaseCombo_Interaction, and IonsFromNeutralVPSSTP.
Definition at line 140 of file VPStandardStateTP.h.
References VPStandardStateTP::err().
Referenced by IonsFromNeutralVPSSTP::s_update_dlnActCoeff_dlnN_diag().
void getChemPotentials_RT (doublereal * mu) const virtual inherited
Get the array of non-dimensional species chemical potentials These are partial molar Gibbs free energies.
\(\mu_k / \hat R T \). Units: unitless
We close the loop on this function, here, calling getChemPotentials() and then dividing by RT. No need for child classes to handle.
Parameters
mu Output vector of non-dimensional species chemical potentials Length: m_kk.
Reimplemented from ThermoPhase.
Definition at line 194 of file VPStandardStateTP.cpp.
References ThermoPhase::_RT(), ThermoPhase::getChemPotentials(), and Phase::m_kk.
void getStandardChemPotentials (doublereal * mu) const virtual inherited
Get the array of chemical potentials at unit activity.
These are the standard state chemical potentials \(\mu^0_k(T,P) \). The values are evaluated at the current temperature and pressure.
Parameters
mu Output vector of standard state chemical potentials. length = m_kk. units are J / kmol.
Reimplemented from ThermoPhase.
Definition at line 206 of file VPStandardStateTP.cpp.
References ThermoPhase::_RT(), VPStandardStateTP::getGibbs_RT(), and Phase::m_kk.
Referenced by MolarityIonicVPSSTP::getChemPotentials(), IdealSolnGasVPSS::getChemPotentials(), RedlichKisterVPSSTP::getChemPotentials(), MargulesVPSSTP::getChemPotentials(), MixedSolventElectrolyte::getChemPotentials(), PhaseCombo_Interaction::getChemPotentials(), IdealMolalSoln::getChemPotentials(), DebyeHuckel::getChemPotentials(), HMWSoln::getChemPotentials(), PseudoBinaryVPSSTP::report(), MolarityIonicVPSSTP::report(), MolalityVPSSTP::report(), and MolalityVPSSTP::reportCSV().
void getEnthalpy_RT (doublereal * hrt) const inline virtual inherited
Get the nondimensional Enthalpy functions for the species at their standard states at the current T and P of the solution.
Parameters
hrt Output vector of standard state enthalpies. length = m_kk. units are unitless.
Reimplemented from ThermoPhase.
Definition at line 216 of file VPStandardStateTP.cpp.
References VPSSMgr::getEnthalpy_RT(), VPStandardStateTP::m_VPSS_ptr, and VPStandardStateTP::updateStandardStateThermo().
Referenced by IdealSolnGasVPSS::getPartialMolarEnthalpies(), MolarityIonicVPSSTP::getPartialMolarEnthalpies(), IonsFromNeutralVPSSTP::getPartialMolarEnthalpies(), RedlichKisterVPSSTP::getPartialMolarEnthalpies(), MargulesVPSSTP::getPartialMolarEnthalpies(), MixedSolventElectrolyte::getPartialMolarEnthalpies(), PhaseCombo_Interaction::getPartialMolarEnthalpies(), IdealMolalSoln::getPartialMolarEnthalpies(), DebyeHuckel::getPartialMolarEnthalpies(), HMWSoln::getPartialMolarEnthalpies(), and HMWSoln::relative_enthalpy().
void getEntropy_R (doublereal * sr) const virtual inherited
Get the array of nondimensional Enthalpy functions for the standard state species at the current T and P of the solution.
Parameters
sr Output vector of nondimensional standard state entropies. length = m_kk.
Reimplemented from ThermoPhase.
Definition at line 239 of file VPStandardStateTP.cpp.
References VPSSMgr::getEntropy_R(), VPStandardStateTP::m_VPSS_ptr, and VPStandardStateTP::updateStandardStateThermo().
Referenced by IdealSolnGasVPSS::getPartialMolarEntropies(), MolarityIonicVPSSTP::getPartialMolarEntropies(), IonsFromNeutralVPSSTP::getPartialMolarEntropies(), RedlichKisterVPSSTP::getPartialMolarEntropies(), MargulesVPSSTP::getPartialMolarEntropies(), MixedSolventElectrolyte::getPartialMolarEntropies(), PhaseCombo_Interaction::getPartialMolarEntropies(), IdealMolalSoln::getPartialMolarEntropies(), DebyeHuckel::getPartialMolarEntropies(), and HMWSoln::getPartialMolarEntropies().
void getGibbs_RT (doublereal * grt) const inline virtual inherited
Get the nondimensional Gibbs functions for the species at their standard states of solution at the current T and P of the solution.
Parameters
grt Output vector of nondimensional standard state Gibbs free energies. length = m_kk.
Reimplemented from ThermoPhase.
Definition at line 246 of file VPStandardStateTP.cpp.
References VPSSMgr::getGibbs_RT(), VPStandardStateTP::m_VPSS_ptr, and VPStandardStateTP::updateStandardStateThermo().
Referenced by VPStandardStateTP::getStandardChemPotentials().
void getPureGibbs (doublereal * gpure) const inline virtual inherited
Get the standard state Gibbs functions for each species at the current T and P.
(Note resolved at this level)
Parameters
gpure Output vector of standard state Gibbs free energies. length = m_kk. units are J/kmol.
Reimplemented from ThermoPhase.
Definition at line 253 of file VPStandardStateTP.cpp.
References VPSSMgr::getStandardChemPotentials(), VPStandardStateTP::m_VPSS_ptr, and VPStandardStateTP::updateStandardStateThermo().
void getIntEnergy_RT (doublereal * urt) const virtual inherited
Returns the vector of nondimensional internal Energies of the standard state at the current temperature and pressure of the solution for each species.
\[ u^{ss}_k(T,P) = h^{ss}_k(T) - P * V^{ss}_k \]
Parameters
urt Output vector of nondimensional standard state internal energies. length = m_kk.
Reimplemented from ThermoPhase.
Definition at line 259 of file VPStandardStateTP.cpp.
References VPSSMgr::getIntEnergy_RT(), VPStandardStateTP::m_VPSS_ptr, and VPStandardStateTP::updateStandardStateThermo().
Referenced by IdealSolnGasVPSS::getPartialMolarIntEnergies().
void getCp_R (doublereal * cpr) const virtual inherited
Get the nondimensional Heat Capacities at constant pressure for the standard state of the species at the current T and P.
This is redefined here to call the internal function, _updateStandardStateThermo(), which calculates all standard state properties at the same time.
Parameters
cpr Output vector containing the the nondimensional Heat Capacities at constant pressure for the standard state of the species. Length: m_kk.
Reimplemented from ThermoPhase.
Definition at line 265 of file VPStandardStateTP.cpp.
References VPSSMgr::getCp_R(), VPStandardStateTP::m_VPSS_ptr, and VPStandardStateTP::updateStandardStateThermo().
Referenced by IdealSolnGasVPSS::getPartialMolarCp(), MolarityIonicVPSSTP::getPartialMolarCp(), RedlichKisterVPSSTP::getPartialMolarCp(), MargulesVPSSTP::getPartialMolarCp(), MixedSolventElectrolyte::getPartialMolarCp(), PhaseCombo_Interaction::getPartialMolarCp(), IdealMolalSoln::getPartialMolarCp(), DebyeHuckel::getPartialMolarCp(), and HMWSoln::getPartialMolarCp().
void getStandardVolumes (doublereal * vol) const virtual inherited
Get the molar volumes of each species in their standard states at the current T and P of the solution.
units = m^3 / kmol
This is redefined here to call the internal function, _updateStandardStateThermo(), which calculates all standard state properties at the same time.
Parameters
vol Output vector of species volumes. length = m_kk. units = m^3 / kmol
Reimplemented from ThermoPhase.
Definition at line 271 of file VPStandardStateTP.cpp.
References VPSSMgr::getStandardVolumes(), VPStandardStateTP::m_VPSS_ptr, and VPStandardStateTP::updateStandardStateThermo().
Referenced by IdealSolnGasVPSS::getPartialMolarVolumes(), MolarityIonicVPSSTP::getPartialMolarVolumes(), GibbsExcessVPSSTP::getPartialMolarVolumes(), RedlichKisterVPSSTP::getPartialMolarVolumes(), MargulesVPSSTP::getPartialMolarVolumes(), MixedSolventElectrolyte::getPartialMolarVolumes(), IdealMolalSoln::getPartialMolarVolumes(), PhaseCombo_Interaction::getPartialMolarVolumes(), DebyeHuckel::getPartialMolarVolumes(), HMWSoln::getPartialMolarVolumes(), and HMWSoln::standardConcentration().
void _updateStandardStateThermo () const protected virtual inherited
Updates the standard state thermodynamic functions at the current T and P of the solution.
If m_useTmpStandardStateStorage is true, this function must be called for every call to functions in this class.
This function is responsible for updating the following internal members, when m_useTmpStandardStateStorage is true.
m_hss_RT;
m_cpss_R;
m_gss_RT;
m_sss_R;
m_Vss
This function doesn't check to see if the temperature or pressure has changed. It automatically assumes that it has changed. If m_useTmpStandardStateStorage is not true, this function may be required to be called by child classes to update internal member data..
Definition at line 517 of file VPStandardStateTP.cpp.
References AssertThrowMsg, VPStandardStateTP::m_Pcurrent, VPStandardStateTP::m_Plast_ss, VPStandardStateTP::m_Tlast_ss, VPStandardStateTP::m_VPSS_ptr, VPSSMgr::setState_TP(), and Phase::temperature().
Referenced by IdealMolalSoln::getActivities(), DebyeHuckel::getActivities(), DebyeHuckel::getMolalityActivityCoefficients(), DebyeHuckel::setState_TP(), and VPStandardStateTP::updateStandardStateThermo().
void updateStandardStateThermo () const virtual inherited
Updates the standard state thermodynamic functions at the current T and P of the solution.
If m_useTmpStandardStateStorage is true, this function must be called for every call to functions in this class. It checks to see whether the temperature or pressure has changed and thus the ss thermodynamics functions for all of the species must be recalculated.
This function is responsible for updating the following internal members, when m_useTmpStandardStateStorage is true.
m_hss_RT;
m_cpss_R;
m_gss_RT;
m_sss_R;
m_Vss
If m_useTmpStandardStateStorage is not true, this function may be required to be called by child classes to update internal member data.
Definition at line 527 of file VPStandardStateTP.cpp.
References VPStandardStateTP::_updateStandardStateThermo(), VPStandardStateTP::m_Pcurrent, VPStandardStateTP::m_Plast_ss, VPStandardStateTP::m_Tlast_ss, and Phase::temperature().
Referenced by IdealSolnGasVPSS::cp_mole(), IdealSolnGasVPSS::enthalpy_mole(), IdealSolnGasVPSS::entropy_mole(), HMWSoln::getActivities(), VPStandardStateTP::getCp_R(), VPStandardStateTP::getCp_R_ref(), VPStandardStateTP::getEnthalpy_RT(), VPStandardStateTP::getEnthalpy_RT_ref(), VPStandardStateTP::getEntropy_R(), VPStandardStateTP::getEntropy_R_ref(), VPStandardStateTP::getGibbs_ref(), VPStandardStateTP::getGibbs_RT(), VPStandardStateTP::getGibbs_RT_ref(), VPStandardStateTP::getIntEnergy_RT(), VPStandardStateTP::getPureGibbs(), VPStandardStateTP::getStandardVolumes(), VPStandardStateTP::getStandardVolumes_ref(), HMWSoln::getUnscaledMolalityActivityCoefficients(), IdealSolnGasVPSS::setPressure(), VPStandardStateTP::setPressure(), VPStandardStateTP::setState_TP(), IdealMolalSoln::setState_TP(), GibbsExcessVPSSTP::setState_TP(), HMWSoln::setState_TP(), VPStandardStateTP::setTemperature(), IdealSolnGasVPSS::setToEquilState(), MolalityVPSSTP::setToEquilState(), and HMWSoln::setToEquilState().
void getEnthalpy_RT_ref (doublereal * hrt) const virtual inherited
Returns the vector of nondimensional enthalpies of the reference state at the current temperature of the solution and the reference pressure for the species.
There are also temporary variables for holding the species reference-state values of Cp, H, S, and V at the last temperature and reference pressure called. These functions are not recalculated if a new call is made using the previous temperature. All calculations are done within the routine _updateRefStateThermo().
Parameters
hrt Output vector contains the nondimensional enthalpies of the reference state of the species length = m_kk, units = dimensionless.
Reimplemented from ThermoPhase.
Definition at line 286 of file VPStandardStateTP.cpp.
References VPSSMgr::getEnthalpy_RT_ref(), VPStandardStateTP::m_VPSS_ptr, and VPStandardStateTP::updateStandardStateThermo().
void getGibbs_RT_ref (doublereal * grt) const virtual inherited
Returns the vector of nondimensional Gibbs free energies of the reference state at the current temperature of the solution and the reference pressure for the species.
Parameters
grt Output vector contains the nondimensional Gibbs free energies of the reference state of the species length = m_kk, units = dimensionless.
Reimplemented from ThermoPhase.
Definition at line 297 of file VPStandardStateTP.cpp.
References VPSSMgr::getGibbs_RT_ref(), VPStandardStateTP::m_VPSS_ptr, and VPStandardStateTP::updateStandardStateThermo().
void getGibbs_ref (doublereal * g) const virtual inherited
Returns the vector of the gibbs function of the reference state at the current temperature of the solution and the reference pressure for the species. units = J/kmol
Parameters
g Output vector contain the Gibbs free energies of the reference state of the species length = m_kk, units = J/kmol.
Reimplemented from ThermoPhase.
Definition at line 312 of file VPStandardStateTP.cpp.
References VPSSMgr::getGibbs_ref(), VPStandardStateTP::m_VPSS_ptr, and VPStandardStateTP::updateStandardStateThermo().
void getEntropy_R_ref (doublereal * er) const virtual inherited
Returns the vector of nondimensional entropies of the reference state at the current temperature of the solution and the reference pressure for the species.
Parameters
er Output vector contain the nondimensional entropies of the species in their reference states length: m_kk, units: dimensionless.
Reimplemented from ThermoPhase.
Definition at line 329 of file VPStandardStateTP.cpp.
References VPSSMgr::getEntropy_R_ref(), VPStandardStateTP::m_VPSS_ptr, and VPStandardStateTP::updateStandardStateThermo().
void getCp_R_ref (doublereal * cprt) const virtual inherited
Returns the vector of nondimensional constant pressure heat capacities of the reference state at the current temperature of the solution and reference pressure for the species.
Parameters
cprt Output vector contains the nondimensional heat capacities of the species in their reference states length: m_kk, units: dimensionless.
Reimplemented from ThermoPhase.
Definition at line 341 of file VPStandardStateTP.cpp.
References VPSSMgr::getCp_R_ref(), VPStandardStateTP::m_VPSS_ptr, and VPStandardStateTP::updateStandardStateThermo().
void getStandardVolumes_ref (doublereal * vol) const virtual inherited
Get the molar volumes of the species reference states at the current T and P_ref of the solution.
units = m^3 / kmol
Parameters
vol Output vector containing the standard state volumes. Length: m_kk.
Reimplemented from ThermoPhase.
Definition at line 353 of file VPStandardStateTP.cpp.
References VPSSMgr::getStandardVolumes_ref(), VPStandardStateTP::m_VPSS_ptr, and VPStandardStateTP::updateStandardStateThermo().
void setVPSSMgr (VPSSMgr * vp_ptr) inherited
set the VPSS Mgr
Parameters
vp_ptr Pointer to the manager
Definition at line 376 of file VPStandardStateTP.cpp.
References VPStandardStateTP::m_VPSS_ptr.
Referenced by Cantera::importPhase().
VPSSMgr * provideVPSSMgr () inherited
Return a pointer to the VPSSMgr for this phase.
Returns
Returns a pointer to the VPSSMgr for this phase
Definition at line 498 of file VPStandardStateTP.cpp.
References VPStandardStateTP::m_VPSS_ptr.
Referenced by PDSS::initThermo(), and PDSS::PDSS().
virtual doublereal refPressure () const inline virtual inherited
Returns the reference pressure in Pa.
This function is a wrapper that calls the species thermo refPressure function.
Reimplemented in LatticeSolidPhase.
Definition at line 164 of file ThermoPhase.h.
References ThermoPhase::m_spthermo, and SpeciesThermo::refPressure().
Referenced by MixtureFugacityTP::_updateReferenceStateThermo(), RedlichKwongMFTP::getChemPotentials(), RedlichKwongMFTP::getPartialMolarEntropies(), MixtureFugacityTP::getStandardVolumes_ref(), ChemEquil::initialize(), IdealSolidSolnPhase::initLengths(), ConstDensityThermo::initThermo(), StoichSubstance::initThermo(), StoichSubstanceSSTP::initThermo(), PureFluidPhase::initThermo(), SingleSpeciesTP::initThermo(), IdealGasPhase::initThermo(), LatticePhase::initThermo(), and RedlichKwongMFTP::setToEquilState().
virtual doublereal minTemp (size_t k = npos) const inline virtual inherited
Minimum temperature for which the thermodynamic data for the species or phase are valid.
If no argument is supplied, the value returned will be the lowest temperature at which the data for all species are valid. Otherwise, the value will be only for species k. This function is a wrapper that calls the species thermo minTemp function.
Parameters
k index of the species. Default is -1, which will return the max of the min value over all species.
Reimplemented in LatticeSolidPhase.
Definition at line 181 of file ThermoPhase.h.
References ThermoPhase::m_spthermo, and SpeciesThermo::minTemp().
Referenced by MultiPhase::addPhase(), ChemEquil::equilibrate(), LiquidTransport::initLiquid(), SimpleTransport::initLiquid(), AqueousTransport::initLiquid(), ThermoPhase::setState_HPorUV(), ThermoPhase::setState_SPorSV(), TransportFactory::setupLiquidTransport(), and TransportFactory::setupMM().
doublereal Hf298SS (const int k) const inline inherited
Report the 298 K Heat of Formation of the standard state of one species (J kmol-1)
The 298K Heat of Formation is defined as the enthalpy change to create the standard state of the species from its constituent elements in their standard states at 298 K and 1 bar.
Parameters
k species index
Returns
Returns the current value of the Heat of Formation at 298K and 1 bar
Definition at line 221 of file ThermoPhase.h.
References ThermoPhase::err().
virtual void modifyOneHf298SS (const int k, const doublereal Hf298New) inline virtual inherited
Modify the value of the 298 K Heat of Formation of one species in the phase (J kmol-1)
The 298K heat of formation is defined as the enthalpy change to create the standard state of the species from its constituent elements in their standard states at 298 K and 1 bar.
Parameters
k Species k
Hf298New Specify the new value of the Heat of Formation at 298K and 1 bar
Definition at line 233 of file ThermoPhase.h.
References ThermoPhase::err().
virtual doublereal maxTemp (size_t k = npos) const inline virtual inherited
Maximum temperature for which the thermodynamic data for the species are valid.
If no argument is supplied, the value returned will be the highest temperature at which the data for all species are valid. Otherwise, the value will be only for species k. This function is a wrapper that calls the species thermo maxTemp function.
Parameters
k index of the species. Default is -1, which will return the min of the max value over all species.
Reimplemented in LatticeSolidPhase.
Definition at line 250 of file ThermoPhase.h.
References ThermoPhase::m_spthermo, and SpeciesThermo::maxTemp().
Referenced by MultiPhase::addPhase(), ChemEquil::equilibrate(), LiquidTransport::initLiquid(), SimpleTransport::initLiquid(), AqueousTransport::initLiquid(), ThermoPhase::setState_HPorUV(), ThermoPhase::setState_SPorSV(), TransportFactory::setupLiquidTransport(), and TransportFactory::setupMM().
bool chargeNeutralityNecessary () const inline inherited
Returns the chargeNeutralityNecessity boolean.
Some phases must have zero net charge in order for their thermodynamics functions to be valid. If this is so, then the value returned from this function is true. If this is not the case, then this is false. Now, ideal gases have this parameter set to false, while solution with molality-based activity coefficients have this parameter set to true.
Definition at line 261 of file ThermoPhase.h.
References ThermoPhase::m_chargeNeutralityNecessary.
virtual void updateDensity () inline virtual inherited
Deprecated:
Definition at line 366 of file ThermoPhase.h.
References Cantera::deprecatedMethod().
void setElectricPotential (doublereal v) inline inherited
Set the electric potential of this phase (V).
This is used by classes InterfaceKinetics and EdgeKinetics to compute the rates of charge-transfer reactions, and in computing the electrochemical potentials of the species.
Each phase may have its own electric potential.
Parameters
v Input value of the electric potential in Volts
Definition at line 390 of file ThermoPhase.h.
References ThermoPhase::m_phi.
Referenced by InterfaceKinetics::setElectricPotential(), vcs_VolPhase::setElectricPotential(), and vcs_VolPhase::setState_TP().
doublereal electricPotential () const inline inherited
Returns the electric potential of this phase (V).
Units are Volts (which are Joules/coulomb)
Definition at line 398 of file ThermoPhase.h.
References ThermoPhase::m_phi.
Referenced by InterfaceKinetics::_update_rates_phi(), PureFluidPhase::getElectrochemPotentials(), PseudoBinaryVPSSTP::getElectrochemPotentials(), MolarityIonicVPSSTP::getElectrochemPotentials(), GibbsExcessVPSSTP::getElectrochemPotentials(), RedlichKisterVPSSTP::getElectrochemPotentials(), MargulesVPSSTP::getElectrochemPotentials(), MixedSolventElectrolyte::getElectrochemPotentials(), ThermoPhase::getElectrochemPotentials(), MolalityVPSSTP::getElectrochemPotentials(), PhaseCombo_Interaction::getElectrochemPotentials(), PseudoBinaryVPSSTP::report(), MolarityIonicVPSSTP::report(), PureFluidPhase::report(), MolalityVPSSTP::report(), ThermoPhase::report(), PureFluidPhase::reportCSV(), MolalityVPSSTP::reportCSV(), ThermoPhase::reportCSV(), and vcs_VolPhase::setPtrThermoPhase().
void getLnActivityCoefficients (doublereal * lnac) const virtual inherited
Get the array of non-dimensional molar-based ln activity coefficients at the current solution temperature, pressure, and solution concentration.
Parameters
lnac Output vector of ln activity coefficients. Length: m_kk.
Reimplemented in MargulesVPSSTP, RedlichKisterVPSSTP, and MolarityIonicVPSSTP.
Definition at line 166 of file ThermoPhase.cpp.
References ThermoPhase::getActivityCoefficients(), and Phase::m_kk.
Referenced by GibbsExcessVPSSTP::getActivityCoefficients(), IonsFromNeutralVPSSTP::getChemPotentials(), and IonsFromNeutralVPSSTP::s_update_lnActCoeff().
virtual void getPartialMolarIntEnergies (doublereal * ubar) const inline virtual inherited
Return an array of partial molar internal energies for the species in the mixture.
Units: J/kmol.
Parameters
ubar Output vector of species partial molar internal energies. Length = m_kk. units are J/kmol.
Reimplemented in IdealGasPhase, RedlichKwongMFTP, SingleSpeciesTP, IdealSolnGasVPSS, and PureFluidPhase.
Definition at line 650 of file ThermoPhase.h.
References ThermoPhase::err().
Referenced by MolalityVPSSTP::reportCSV(), and ThermoPhase::reportCSV().
virtual void getdPartialMolarVolumes_dT (doublereal * d_vbar_dT) const inline virtual inherited
Return an array of derivatives of partial molar volumes wrt temperature for the species in the mixture.
Units: m^3/kmol.
The derivative is at constant pressure
Parameters
d_vbar_dT Output vector of derivatives of species partial molar volumes wrt T. Length = m_kk. units are m^3/kmol/K.
Definition at line 683 of file ThermoPhase.h.
References ThermoPhase::err().
virtual void getdPartialMolarVolumes_dP (doublereal * d_vbar_dP) const inline virtual inherited
Return an array of derivatives of partial molar volumes wrt pressure for the species in the mixture.
Units: m^3/kmol.
The derivative is at constant temperature
Parameters
d_vbar_dP Output vector of derivatives of species partial molar volumes wrt P. Length = m_kk. units are m^3/kmol/Pa.
Definition at line 695 of file ThermoPhase.h.
References ThermoPhase::err().
virtual void getdStandardVolumes_dT (doublereal * d_vol_dT) const inline virtual inherited
Get the derivative of the molar volumes of the species standard states wrt temperature at the current T and P of the solution.
The derivative is at constant pressure units = m^3 / kmol / K
Parameters
d_vol_dT Output vector containing derivatives of standard state volumes wrt T Length: m_kk.
Definition at line 800 of file ThermoPhase.h.
References ThermoPhase::err().
virtual void getdStandardVolumes_dP (doublereal * d_vol_dP) const inline virtual inherited
Get the derivative molar volumes of the species standard states wrt pressure at the current T and P of the solution.
The derivative is at constant temperature. units = m^3 / kmol / Pa
Parameters
d_vol_dP Output vector containing the derivative of standard state volumes wrt P. Length: m_kk.
Definition at line 813 of file ThermoPhase.h.
References ThermoPhase::err().
virtual void getIntEnergy_RT_ref (doublereal * urt) const inline virtual inherited
Returns the vector of nondimensional internal Energies of the reference state at the current temperature of the solution and the reference pressure for each species.
Parameters
urt Output vector of nondimensional reference state internal energies of the species. Length: m_kk
Reimplemented in IdealSolidSolnPhase, IdealGasPhase, FixedChemPotSSTP, MetalSHEelectrons, MineralEQ3, and StoichSubstanceSSTP.
Definition at line 879 of file ThermoPhase.h.
References ThermoPhase::err().
void setReferenceComposition (const doublereal *const x) virtual inherited
Sets the reference composition.
Parameters
x Mole fraction vector to set the reference composition to. If this is zero, then the reference mole fraction is set to the current mole fraction vector.
Definition at line 992 of file ThermoPhase.cpp.
References DATA_PTR, Phase::getMoleFractions(), Phase::m_kk, and ThermoPhase::xMol_Ref.
Referenced by ThermoPhase::initThermoXML().
void getReferenceComposition (doublereal *const x) const virtual inherited
Gets the reference composition.
The reference mole fraction is a safe mole fraction.
Parameters
x Mole fraction vector containing the reference composition.
Definition at line 1013 of file ThermoPhase.cpp.
References Phase::m_kk, and ThermoPhase::xMol_Ref.
doublereal enthalpy_mass () const inline inherited
Specific enthalpy.
Units: J/kg.
Definition at line 937 of file ThermoPhase.h.
References ThermoPhase::enthalpy_mole(), and Phase::meanMolecularWeight().
Referenced by ConstPressureReactor::initialize(), Reactor::initialize(), PseudoBinaryVPSSTP::report(), MolarityIonicVPSSTP::report(), PureFluidPhase::report(), MolalityVPSSTP::report(), ThermoPhase::report(), PureFluidPhase::reportCSV(), MolalityVPSSTP::reportCSV(), ThermoPhase::reportCSV(), SingleSpeciesTP::setState_HP(), ThermoPhase::setState_HPorUV(), ThermoPhase::setState_SPorSV(), ReactorBase::setThermoMgr(), ConstPressureReactor::updateState(), and Reactor::updateState().
doublereal intEnergy_mass () const inline inherited
Specific internal energy.
Units: J/kg.
Definition at line 944 of file ThermoPhase.h.
References ThermoPhase::intEnergy_mole(), and Phase::meanMolecularWeight().
Referenced by ConstPressureReactor::initialize(), Reactor::initialize(), PseudoBinaryVPSSTP::report(), MolarityIonicVPSSTP::report(), PureFluidPhase::report(), MolalityVPSSTP::report(), ThermoPhase::report(), PureFluidPhase::reportCSV(), MolalityVPSSTP::reportCSV(), ThermoPhase::reportCSV(), ThermoPhase::setState_HPorUV(), SingleSpeciesTP::setState_UV(), ReactorBase::setThermoMgr(), ConstPressureReactor::updateState(), and Reactor::updateState().
doublereal entropy_mass () const inline inherited
Specific entropy.
Units: J/kg/K.
Definition at line 951 of file ThermoPhase.h.
References ThermoPhase::entropy_mole(), and Phase::meanMolecularWeight().
Referenced by PseudoBinaryVPSSTP::report(), MolarityIonicVPSSTP::report(), PureFluidPhase::report(), MolalityVPSSTP::report(), ThermoPhase::report(), PureFluidPhase::reportCSV(), MolalityVPSSTP::reportCSV(), ThermoPhase::reportCSV(), SingleSpeciesTP::setState_SP(), ThermoPhase::setState_SPorSV(), and SingleSpeciesTP::setState_SV().
doublereal gibbs_mass () const inline inherited
Specific Gibbs function.
Units: J/kg.
Definition at line 958 of file ThermoPhase.h.
References ThermoPhase::gibbs_mole(), and Phase::meanMolecularWeight().
Referenced by PseudoBinaryVPSSTP::report(), MolarityIonicVPSSTP::report(), PureFluidPhase::report(), MolalityVPSSTP::report(), ThermoPhase::report(), PureFluidPhase::reportCSV(), MolalityVPSSTP::reportCSV(), and ThermoPhase::reportCSV().
doublereal cp_mass () const inline inherited
Specific heat at constant pressure.
Units: J/kg/K.
Definition at line 965 of file ThermoPhase.h.
References ThermoPhase::cp_mole(), and Phase::meanMolecularWeight().
Referenced by PseudoBinaryVPSSTP::report(), MolarityIonicVPSSTP::report(), PureFluidPhase::report(), MolalityVPSSTP::report(), ThermoPhase::report(), PureFluidPhase::reportCSV(), MolalityVPSSTP::reportCSV(), ThermoPhase::reportCSV(), SingleSpeciesTP::setState_HP(), ThermoPhase::setState_HPorUV(), SingleSpeciesTP::setState_SP(), ThermoPhase::setState_SPorSV(), and StFlow::updateThermo().
doublereal cv_mass () const inline inherited
Specific heat at constant volume.
Units: J/kg/K.
Definition at line 972 of file ThermoPhase.h.
References ThermoPhase::cv_mole(), and Phase::meanMolecularWeight().
Referenced by PseudoBinaryVPSSTP::report(), MolarityIonicVPSSTP::report(), PureFluidPhase::report(), MolalityVPSSTP::report(), ThermoPhase::report(), PureFluidPhase::reportCSV(), MolalityVPSSTP::reportCSV(), ThermoPhase::reportCSV(), ThermoPhase::setState_HPorUV(), ThermoPhase::setState_SPorSV(), SingleSpeciesTP::setState_SV(), and SingleSpeciesTP::setState_UV().
doublereal _RT () const inline inherited
Return the Gas Constant multiplied by the current temperature.
The units are Joules kmol-1
Definition at line 981 of file ThermoPhase.h.
References Cantera::GasConstant, and Phase::temperature().
Referenced by MixtureFugacityTP::corr0(), RedlichKwongMFTP::enthalpy_mole(), VPStandardStateTP::getChemPotentials_RT(), MixtureFugacityTP::getChemPotentials_RT(), IdealSolnGasVPSS::getChemPotentials_RT(), RedlichKwongMFTP::getChemPotentials_RT(), PureFluidPhase::getEnthalpy_RT(), FixedChemPotSSTP::getEnthalpy_RT(), FixedChemPotSSTP::getEnthalpy_RT_ref(), WaterSSTP::getGibbs_ref(), MixtureFugacityTP::getGibbs_ref(), IdealGasPhase::getGibbs_ref(), PureFluidPhase::getGibbs_RT(), FixedChemPotSSTP::getGibbs_RT(), IdealSolidSolnPhase::getGibbs_RT(), LatticePhase::getGibbs_RT(), FixedChemPotSSTP::getGibbs_RT_ref(), MixtureFugacityTP::getIntEnergy_RT(), IdealMolalSoln::getPartialMolarEnthalpies(), ConstDensityThermo::getPureGibbs(), MixtureFugacityTP::getPureGibbs(), IdealGasPhase::getPureGibbs(), IdealSolidSolnPhase::getPureGibbs(), VPStandardStateTP::getStandardChemPotentials(), MixtureFugacityTP::getStandardChemPotentials(), IdealGasPhase::getStandardChemPotentials(), LatticePhase::getStandardChemPotentials(), MixtureFugacityTP::getStandardVolumes(), MixtureFugacityTP::getStandardVolumes_ref(), IdealGasPhase::getStandardVolumes_ref(), and MixtureFugacityTP::z().
void setState_TPX (doublereal t, doublereal p, const doublereal * x) virtual inherited
Set the temperature (K), pressure (Pa), and mole fractions.
Note, the mole fractions are set first before the pressure is set. Setting the pressure may involve the solution of a nonlinear equation.
Parameters
t Temperature (K)
p Pressure (Pa)
x Vector of mole fractions. Length is equal to m_kk.
Reimplemented in SingleSpeciesTP, and MixtureFugacityTP.
Definition at line 174 of file ThermoPhase.cpp.
References Phase::setMoleFractions(), ThermoPhase::setPressure(), and Phase::setTemperature().
Referenced by MultiTransport::getMassFluxes(), DustyGasTransport::getMolarFluxes(), MultiPhase::setMoles(), and MultiPhase::setPhaseMoleFractions().
void setState_TPX (doublereal t, doublereal p, compositionMap & x) inherited
Set the temperature (K), pressure (Pa), and mole fractions.
Note, the mole fractions are set first before the pressure is set. Setting the pressure may involve the solution of a nonlinear equation.
Parameters
t Temperature (K)
p Pressure (Pa)
x Composition map of mole fractions. Species not in the composition map are assumed to have zero mole fraction
Definition at line 181 of file ThermoPhase.cpp.
References Phase::setMoleFractionsByName(), ThermoPhase::setPressure(), and Phase::setTemperature().
void setState_TPX (doublereal t, doublereal p, const std::string & x) inherited
Set the temperature (K), pressure (Pa), and mole fractions.
Note, the mole fractions are set first before the pressure is set. Setting the pressure may involve the solution of a nonlinear equation.
Parameters
t Temperature (K)
p Pressure (Pa)
x String containing a composition map of the mole fractions. Species not in the composition map are assumed to have zero mole fraction
Definition at line 188 of file ThermoPhase.cpp.
References ThermoPhase::err(), Phase::nSpecies(), Cantera::parseCompString(), CanteraError::save(), Phase::setMoleFractionsByName(), ThermoPhase::setPressure(), Phase::setTemperature(), and Phase::speciesName().
void setState_TPY (doublereal t, doublereal p, const doublereal * y) inherited
Set the internally stored temperature (K), pressure (Pa), and mass fractions of the phase.
Note, the mass fractions are set first before the pressure is set. Setting the pressure may involve the solution of a nonlinear equation.
Parameters
t Temperature (K)
p Pressure (Pa)
y Vector of mass fractions. Length is equal to m_kk.
Definition at line 206 of file ThermoPhase.cpp.
References Phase::setMassFractions(), ThermoPhase::setPressure(), and Phase::setTemperature().
void setState_TPY (doublereal t, doublereal p, compositionMap & y) inherited
Set the internally stored temperature (K), pressure (Pa), and mass fractions of the phase.
Note, the mass fractions are set first before the pressure is set. Setting the pressure may involve the solution of a nonlinear equation.
Parameters
t Temperature (K)
p Pressure (Pa)
y Composition map of mass fractions. Species not in the composition map are assumed to have zero mass fraction
Definition at line 214 of file ThermoPhase.cpp.
References Phase::setMassFractionsByName(), ThermoPhase::setPressure(), and Phase::setTemperature().
void setState_TPY (doublereal t, doublereal p, const std::string & y) inherited
Set the internally stored temperature (K), pressure (Pa), and mass fractions of the phase.
Note, the mass fractions are set first before the pressure is set. Setting the pressure may involve the solution of a nonlinear equation.
Parameters
t Temperature (K)
p Pressure (Pa)
y String containing a composition map of the mass fractions. Species not in the composition map are assumed to have zero mass fraction
Definition at line 222 of file ThermoPhase.cpp.
References ThermoPhase::err(), Phase::nSpecies(), Cantera::parseCompString(), CanteraError::save(), Phase::setMassFractionsByName(), ThermoPhase::setPressure(), Phase::setTemperature(), and Phase::speciesName().
void setState_PX (doublereal p, doublereal * x) inherited
Set the pressure (Pa) and mole fractions.
Note, the mole fractions are set first before the pressure is set. Setting the pressure may involve the solution of a nonlinear equation.
Parameters
p Pressure (Pa)
x Vector of mole fractions. Length is equal to m_kk.
Definition at line 249 of file ThermoPhase.cpp.
References Phase::setMoleFractions(), and ThermoPhase::setPressure().
Referenced by vcs_VolPhase::_updateMoleFractionDependencies(), IdealSolnGasVPSS::setToEquilState(), RedlichKwongMFTP::setToEquilState(), IdealGasPhase::setToEquilState(), and IdealSolidSolnPhase::setToEquilState().
void setState_PY (doublereal p, doublereal * y) inherited
Set the internally stored pressure (Pa) and mass fractions.
Note, the temperature is held constant during this operation. Note, the mass fractions are set first before the pressure is set. Setting the pressure may involve the solution of a nonlinear equation.
Parameters
p Pressure (Pa)
y Vector of mass fractions. Length is equal to m_kk.
Definition at line 256 of file ThermoPhase.cpp.
References Phase::setMassFractions(), and ThermoPhase::setPressure().
void setState_HP (doublereal h, doublereal p, doublereal tol = 1.e-4) virtual inherited
Set the internally stored specific enthalpy (J/kg) and pressure (Pa) of the phase.
Parameters
h Specific enthalpy (J/kg)
p Pressure (Pa)
tol Optional parameter setting the tolerance of the calculation. Defaults to 1.0E-4
Reimplemented in SingleSpeciesTP, and PureFluidPhase.
Definition at line 263 of file ThermoPhase.cpp.
References ThermoPhase::setState_HPorUV().
Referenced by FlowReactor::updateState(), and ConstPressureReactor::updateState().
void setState_UV (doublereal u, doublereal v, doublereal tol = 1.e-4) virtual inherited
Set the specific internal energy (J/kg) and specific volume (m^3/kg).
This function fixes the internal state of the phase so that the specific internal energy and specific volume have the value of the input parameters.
Parameters
u specific internal energy (J/kg)
v specific volume (m^3/kg).
tol Optional parameter setting the tolerance of the calculation. Defaults to 1.0E-4
Reimplemented in SingleSpeciesTP, and PureFluidPhase.
Definition at line 270 of file ThermoPhase.cpp.
References ThermoPhase::setState_HPorUV().
Referenced by Reactor::updateState().
void setState_SP (doublereal s, doublereal p, doublereal tol = 1.e-4) virtual inherited
Set the specific entropy (J/kg/K) and pressure (Pa).
This function fixes the internal state of the phase so that the specific entropy and the pressure have the value of the input parameters.
Parameters
s specific entropy (J/kg/K)
p specific pressure (Pa).
tol Optional parameter setting the tolerance of the calculation. Defaults to 1.0E-4
Reimplemented in SingleSpeciesTP, and PureFluidPhase.
Definition at line 546 of file ThermoPhase.cpp.
References ThermoPhase::setState_SPorSV().
void setState_SV (doublereal s, doublereal v, doublereal tol = 1.e-4) virtual inherited
Set the specific entropy (J/kg/K) and specific volume (m^3/kg).
This function fixes the internal state of the phase so that the specific entropy and specific volume have the value of the input parameters.
Parameters
s specific entropy (J/kg/K)
v specific volume (m^3/kg).
tol Optional parameter setting the tolerance of the calculation. Defaults to 1.0E-4
Reimplemented in SingleSpeciesTP, and PureFluidPhase.
Definition at line 553 of file ThermoPhase.cpp.
References ThermoPhase::setState_SPorSV().
void setElementPotentials (const vector_fp & lambda) inherited
Stores the element potentials in the ThermoPhase object.
Called by function 'equilibrate' in ChemEquil.h to transfer the element potentials to this object after every successful equilibration routine. The element potentials are stored in their dimensionless forms, calculated by dividing by RT.
Parameters
lambda Input vector containing the element potentials. Length = nElements. Units are Joules/kmol.
Definition at line 1106 of file ThermoPhase.cpp.
References Cantera::GasConstant, ThermoPhase::m_hasElementPotentials, ThermoPhase::m_lambdaRRT, Phase::nElements(), and Phase::temperature().
Referenced by Cantera::equilibrate(), ChemEquil::equilibrate(), and Cantera::vcs_equilibrate().
bool getElementPotentials (doublereal * lambda) const inherited
Returns the element potentials stored in the ThermoPhase object.
Returns the stored element potentials. The element potentials are retrieved from their stored dimensionless forms by multiplying by RT.
Parameters
lambda Output vector containing the element potentials. Length = nElements. Units are Joules/kmol.
Returns
bool indicating whether there are any valid stored element potentials. The calling routine should check this bool. In the case that there aren't any, lambda is not touched.
Definition at line 1129 of file ThermoPhase.cpp.
References Cantera::GasConstant, ThermoPhase::m_hasElementPotentials, ThermoPhase::m_lambdaRRT, Phase::nElements(), and Phase::temperature().
Referenced by ChemEquil::equilibrate().
void saveSpeciesData (const size_t k, const XML_Node *const data) inherited
Store a reference pointer to the XML tree containing the species data for this phase.
The following methods are used in the process of constructing the phase and setting its parameters from a specification in an input file. They are not normally used in application programs. To see how they are used, see files importCTML.cpp and ThermoFactory.cpp.
This is used to access data needed to construct transport manager later.
Parameters
k Species index
data Pointer to the XML_Node data containing information about the species in the phase.
Definition at line 1050 of file ThermoPhase.cpp.
References ThermoPhase::m_speciesData.
Referenced by FixedChemPotSSTP::FixedChemPotSSTP(), and Cantera::importPhase().
const std::vector< const XML_Node * > & speciesData () const inherited
Return a pointer to the vector of XML nodes containing the species data for this phase.
Definition at line 1060 of file ThermoPhase.cpp.
References Phase::m_kk, and ThermoPhase::m_speciesData.
Referenced by MineralEQ3::initThermoXML(), DebyeHuckel::initThermoXML(), TransportFactory::initTransport(), LatticeSolidPhase::installSlavePhases(), and TransportFactory::setupLiquidTransport().
void setSpeciesThermo (SpeciesThermo * spthermo) inherited
Install a species thermodynamic property manager.
The species thermodynamic property manager computes properties of the pure species for use in constructing solution properties. It is meant for internal use, and some classes derived from ThermoPhase may not use any species thermodynamic property manager. This method is called by function importPhase() in importCTML.cpp.
Parameters
spthermo input pointer to the species thermodynamic property manager.
Definition at line 886 of file ThermoPhase.cpp.
References ThermoPhase::m_spthermo.
Referenced by FixedChemPotSSTP::FixedChemPotSSTP(), Cantera::importPhase(), LatticeSolidPhase::installSlavePhases(), and VPSSMgrFactory::newVPSSMgr().
SpeciesThermo & speciesThermo (int k = -1) virtual inherited
Return a changeable reference to the calculation manager for species reference-state thermodynamic properties.
Parameters
k Speices id. The default is -1, meaning return the default
Reimplemented in LatticeSolidPhase.
Definition at line 904 of file ThermoPhase.cpp.
References ThermoPhase::m_spthermo.
Referenced by PDSS_ConstVol::constructPDSSXML(), PDSS_SSVol::constructPDSSXML(), PDSS_ConstVol::initThermo(), PDSS_IdealGas::initThermo(), PDSS_IonsFromNeutral::initThermo(), PDSS_SSVol::initThermo(), VPSSMgrFactory::newVPSSMgr(), and PDSS::PDSS().
void initThermoFile (std::string inputFile, std::string id) virtual inherited
Initialization of a ThermoPhase object using an ctml file.
This routine is a precursor to initThermoXML(XML_Node*) routine, which does most of the work. Here we read extra information about the XML description of a phase. Regular information about elements and species and their reference state thermodynamic information have already been read at this point. For example, we do not need to call this function for ideal gas equations of state.
Parameters
inputFile XML file containing the description of the phase
id Optional parameter identifying the name of the phase. If none is given, the first XML phase element encountered will be used.
Definition at line 928 of file ThermoPhase.cpp.
References XML_Node::build(), XML_Node::copy(), Cantera::findInputFile(), Cantera::findXMLPhase(), ThermoPhase::initThermoXML(), and Phase::xml().
void installSlavePhases (Cantera::XML_Node * phaseNode) virtual inherited
Add in species from Slave phases.
This hook is used for cSS_CONVENTION_SLAVE phases
Parameters
phaseNode XML Element for the phase
Reimplemented in LatticeSolidPhase.
Definition at line 1045 of file ThermoPhase.cpp.
Referenced by Cantera::importPhase().
virtual void getdlnActCoeffds (const doublereal dTds, const doublereal *const dXds, doublereal * dlnActCoeffds) const inline virtual inherited
Get the change in activity coefficients wrt changes in state (temp, mole fraction, etc) along a line in parameter space or along a line in physical space.
Parameters
dTds Input of temperature change along the path
dXds Input vector of changes in mole fraction along the path. length = m_kk Along the path length it must be the case that the mole fractions sum to one.
dlnActCoeffds Output vector of the directional derivatives of the log Activity Coefficients along the path. length = m_kk units are 1/units(s). if s is a physical coordinate then the units are 1/m.
Reimplemented in MixedSolventElectrolyte, MargulesVPSSTP, RedlichKisterVPSSTP, PhaseCombo_Interaction, and IonsFromNeutralVPSSTP.
Definition at line 1511 of file ThermoPhase.h.
References ThermoPhase::err().
Referenced by IonsFromNeutralVPSSTP::getdlnActCoeffds(), and LiquidTransport::update_Grad_lnAC().
virtual void getdlnActCoeffdlnX_diag (doublereal * dlnActCoeffdlnX_diag) const inline virtual inherited
Get the array of ln mole fraction derivatives of the log activity coefficients - diagonal component only.
This function is a virtual method. For ideal mixtures (unity activity coefficients), this can return zero. Implementations should take the derivative of the logarithm of the activity coefficient with respect to the logarithm of the mole fraction variable that represents the standard state. This quantity is to be used in conjunction with derivatives of that mole fraction variable when the derivative of the chemical potential is taken.
units = dimensionless
Parameters
dlnActCoeffdlnX_diag Output vector of derivatives of the log Activity Coefficients wrt the mole fractions. length = m_kk
Reimplemented in MixedSolventElectrolyte, MargulesVPSSTP, RedlichKisterVPSSTP, PhaseCombo_Interaction, and IonsFromNeutralVPSSTP.
Definition at line 1533 of file ThermoPhase.h.
References ThermoPhase::err().
Referenced by IonsFromNeutralVPSSTP::s_update_dlnActCoeff_dlnX_diag().
XML_Node & xml () inherited
Returns a reference to the XML_Node stored for the phase.
The XML_Node for the phase contains all of the input data used to set up the model for the phase, during its initialization.
Definition at line 125 of file Phase.cpp.
References Phase::m_xml.
Referenced by MolarityIonicVPSSTP::constructPhaseFile(), LatticePhase::constructPhaseFile(), RedlichKisterVPSSTP::constructPhaseFile(), MargulesVPSSTP::constructPhaseFile(), MixedSolventElectrolyte::constructPhaseFile(), WaterSSTP::constructPhaseFile(), PhaseCombo_Interaction::constructPhaseFile(), IonsFromNeutralVPSSTP::constructPhaseFile(), IdealMolalSoln::constructPhaseFile(), IdealSolidSolnPhase::constructPhaseFile(), DebyeHuckel::constructPhaseFile(), Cantera::importPhase(), SimpleTransport::initLiquid(), ThermoPhase::initThermoFile(), TransportFactory::newTransport(), and TransportFactory::setupLiquidTransport().
std::string id () const inherited
Return the string id for the phase.
Definition at line 130 of file Phase.cpp.
References Phase::m_id.
Referenced by Kinetics::assignShallowPointers(), Cantera::equilibrate(), Cantera::getEfficiencies(), Cantera::importPhase(), LatticeSolidPhase::installSlavePhases(), Kinetics::kineticsSpeciesIndex(), MultiPhase::phaseIndex(), MultiPhase::phaseName(), solveProb::print_header(), RedlichKwongMFTP::RedlichKwongMFTP(), Phase::setID(), LatticeSolidPhase::setParametersFromXML(), vcs_VolPhase::transferElementsFM(), and Cantera::vcs_equilibrate().
void setID (std::string id) inherited
Set the string id for the phase.
Parameters
id String id of the phase
Definition at line 135 of file Phase.cpp.
References Phase::id(), and Phase::m_id.
Referenced by FixedChemPotSSTP::FixedChemPotSSTP(), and Cantera::importPhase().
std::string name () const inherited
Return the name of the phase.
Definition at line 140 of file Phase.cpp.
References Phase::m_name.
Referenced by Cantera::operator<<(), PseudoBinaryVPSSTP::report(), MolarityIonicVPSSTP::report(), PureFluidPhase::report(), MolalityVPSSTP::report(), ThermoPhase::report(), PureFluidPhase::reportCSV(), vcs_MultiPhaseEquil::reportCSV(), MolalityVPSSTP::reportCSV(), and ThermoPhase::reportCSV().
void setName (std::string nm) inherited
Sets the string name for the phase.
Parameters
nm String name of the phase
Definition at line 145 of file Phase.cpp.
References Phase::m_name.
Referenced by FixedChemPotSSTP::FixedChemPotSSTP(), and Cantera::importPhase().
string elementName (size_t m) const inherited
Name of the element with index m.
Parameters
m Element index.
Definition at line 169 of file Phase.cpp.
References Phase::checkElementIndex(), and Phase::m_elementNames.
Referenced by MultiPhase::addPhase(), Cantera::checkRxnElementBalance(), Cantera::convertDGFormation(), PDSS_HKFT::convertDGFormation(), ChemEquil::equilibrate(), ChemEquil::equilResidual(), ChemEquil::estimateElementPotentials(), ChemEquil::estimateEP_Brinkley(), MolalityVPSSTP::findCLMIndex(), ChemEquil::initialize(), LatticeSolidPhase::installSlavePhases(), Cantera::installSpecies(), ChemEquil::setInitialMoles(), and vcs_VolPhase::transferElementsFM().
size_t elementIndex (std::string name) const inherited
Return the index of element named 'name'.
The index is an integer assigned to each element in the order it was added. Returns npos if the specified element is not found.
Parameters
name Name of the element
Definition at line 175 of file Phase.cpp.
References Phase::m_elementNames, Phase::m_mm, and Cantera::npos.
Referenced by Phase::addUniqueElementAfterFreeze(), MultiPhase::init(), WaterSSTP::initThermoXML(), LatticeSolidPhase::installSlavePhases(), Cantera::installSpecies(), Cantera::LookupGe(), and PDSS_HKFT::LookupGe().
const vector< string > & elementNames () const inherited
Return a read-only reference to the vector of element names.
Definition at line 185 of file Phase.cpp.
References Phase::m_elementNames.
Referenced by ChemEquil::equilibrate(), ChemEquil::estimateEP_Brinkley(), and IonsFromNeutralVPSSTP::initThermoXML().
doublereal atomicWeight (size_t m) const inherited
Atomic weight of element m.
Parameters
m Element index
Definition at line 190 of file Phase.cpp.
References Phase::m_atomicWeights.
Referenced by ChemEquil::initialize(), and WaterSSTP::initThermoXML().
doublereal entropyElement298 (size_t m) const inherited
Entropy of the element in its standard state at 298 K and 1 bar.
Parameters
m Element index
Definition at line 195 of file Phase.cpp.
References AssertThrowMsg, AssertTrace, ENTROPY298_UNKNOWN, Phase::m_entropy298, and Phase::m_mm.
Referenced by LatticeSolidPhase::installSlavePhases(), Cantera::LookupGe(), and PDSS_HKFT::LookupGe().
int atomicNumber (size_t m) const inherited
Atomic number of element m.
Parameters
m Element index
Definition at line 209 of file Phase.cpp.
References Phase::m_atomicNumbers.
Referenced by MultiPhase::addPhase(), and LatticeSolidPhase::installSlavePhases().
int elementType (size_t m) const inherited
Return the element constraint type Possible types include:
CT_ELEM_TYPE_TURNEDOFF -1 CT_ELEM_TYPE_ABSPOS 0 CT_ELEM_TYPE_ELECTRONCHARGE 1 CT_ELEM_TYPE_CHARGENEUTRALITY 2 CT_ELEM_TYPE_LATTICERATIO 3 CT_ELEM_TYPE_KINETICFROZEN 4 CT_ELEM_TYPE_SURFACECONSTRAINT 5 CT_ELEM_TYPE_OTHERCONSTRAINT 6
The default is CT_ELEM_TYPE_ABSPOS.
Parameters
m Element index
Returns
Returns the element type
Definition at line 214 of file Phase.cpp.
References Phase::m_elem_type.
Referenced by LatticeSolidPhase::installSlavePhases(), and vcs_VolPhase::transferElementsFM().
int changeElementType (int m, int elem_type) inherited
Change the element type of the mth constraint Reassigns an element type.
Parameters
m Element index
elem_type New elem type to be assigned
Returns
Returns the old element type
Definition at line 219 of file Phase.cpp.
References Phase::m_elem_type.
const vector_fp & atomicWeights () const inherited
Return a read-only reference to the vector of atomic weights.
Definition at line 204 of file Phase.cpp.
References Phase::m_atomicWeights.
Referenced by LatticeSolidPhase::installSlavePhases().
size_t nElements () const inherited
Number of elements.
Definition at line 150 of file Phase.cpp.
References Phase::m_mm.
Referenced by MultiPhase::addPhase(), Cantera::checkRxnElementBalance(), Cantera::convertDGFormation(), PDSS_HKFT::convertDGFormation(), ChemEquil::equilibrate(), MolalityVPSSTP::findCLMIndex(), FixedChemPotSSTP::FixedChemPotSSTP(), ThermoPhase::getElementPotentials(), ChemEquil::initialize(), IdealSolidSolnPhase::initLengths(), ConstDensityThermo::initThermo(), LatticeSolidPhase::initThermo(), IdealGasPhase::initThermo(), LatticePhase::initThermo(), IonsFromNeutralVPSSTP::initThermoXML(), LatticeSolidPhase::installSlavePhases(), Cantera::installSpecies(), ThermoPhase::setElementPotentials(), vcs_VolPhase::setPtrThermoPhase(), and vcs_VolPhase::transferElementsFM().
void checkElementIndex (size_t m) const inherited
Check that the specified element index is in range Throws an exception if m is greater than nElements()-1.
Definition at line 155 of file Phase.cpp.
References Phase::m_mm.
Referenced by Phase::elementName(), and Phase::nAtoms().
void checkElementArraySize (size_t mm) const inherited
Check that an array size is at least nElements() Throws an exception if mm is less than nElements().
Used before calls which take an array pointer.
Definition at line 162 of file Phase.cpp.
References Phase::m_mm.
doublereal nAtoms (size_t k, size_t m) const inherited
Number of atoms of element m in species k.
Parameters
k species index
m element index
Definition at line 226 of file Phase.cpp.
References Phase::checkElementIndex(), Phase::checkSpeciesIndex(), Phase::m_mm, and Phase::m_speciesComp.
Referenced by Cantera::checkRxnElementBalance(), Cantera::convertDGFormation(), PDSS_HKFT::convertDGFormation(), MolalityVPSSTP::findCLMIndex(), MultiPhase::init(), ChemEquil::initialize(), IonsFromNeutralVPSSTP::initThermoXML(), IdealSolidSolnPhase::setToEquilState(), and vcs_VolPhase::transferElementsFM().
void getAtoms (size_t k, double * atomArray) const inherited
Get a vector containing the atomic composition of species k.
Parameters
k species index
atomArray vector containing the atomic number in the species. Length: m_mm
Definition at line 233 of file Phase.cpp.
References Phase::m_mm, and Phase::m_speciesComp.
Referenced by LatticeSolidPhase::installSlavePhases().
size_t speciesIndex (std::string name) const inherited
Returns the index of a species named 'name' within the Phase object.
The first species in the phase will have an index 0, and the last one will have an index of nSpecies() - 1.
Parameters
name String name of the species. It may also be in the form phaseName:speciesName
Returns
The index of the species. If the name is not found, the value npos is returned.
Definition at line 240 of file Phase.cpp.
References Phase::m_id, Phase::m_kk, Phase::m_name, Phase::m_speciesNames, Cantera::npos, and Cantera::parseSpeciesName().
Referenced by PDSS_IonsFromNeutral::constructPDSSXML(), TransportFactory::getLiquidInteractionsTransportData(), TransportFactory::getLiquidSpeciesTransportData(), Cantera::getStick(), HMWSoln::HMWSoln(), Cantera::importSolution(), LiquidTranInteraction::init(), DebyeHuckel::initThermoXML(), FlowDevice::install(), Kinetics::kineticsSpeciesIndex(), MargulesVPSSTP::MargulesVPSSTP(), Phase::massFraction(), MixedSolventElectrolyte::MixedSolventElectrolyte(), Phase::moleFraction(), PhaseCombo_Interaction::PhaseCombo_Interaction(), PhaseCombo_Interaction::readXMLBinarySpecies(), RedlichKisterVPSSTP::readXMLBinarySpecies(), MargulesVPSSTP::readXMLBinarySpecies(), MixedSolventElectrolyte::readXMLBinarySpecies(), RedlichKwongMFTP::readXMLCrossFluid(), RedlichKwongMFTP::readXMLPureFluid(), RedlichKisterVPSSTP::RedlichKisterVPSSTP(), MolalityVPSSTP::report(), MolalityVPSSTP::reportCSV(), and Kinetics::speciesPhase().
string speciesName (size_t k) const inherited
Name of the species with index k.
Parameters
k index of the species
Definition at line 257 of file Phase.cpp.
References Phase::checkSpeciesIndex(), and Phase::m_speciesNames.
Referenced by StFlow::componentName(), ReactingSurf1D::componentName(), ChemEquil::estimateElementPotentials(), ChemEquil::estimateEP_Brinkley(), MolalityVPSSTP::findCLMIndex(), TransportFactory::fitProperties(), AqueousTransport::getLiquidTransportData(), Phase::getMoleFractionsByName(), Cantera::importSolution(), MultiPhase::init(), ChemEquil::initialize(), LiquidTransport::initLiquid(), SimpleTransport::initLiquid(), IdealMolalSoln::initThermoXML(), DebyeHuckel::initThermoXML(), FlowDevice::install(), LatticeSolidPhase::installSlavePhases(), Kinetics::kineticsSpeciesName(), solveProb::print_header(), HMWSoln::printCoeffs(), PhaseCombo_Interaction::readXMLBinarySpecies(), RedlichKisterVPSSTP::readXMLBinarySpecies(), MargulesVPSSTP::readXMLBinarySpecies(), MixedSolventElectrolyte::readXMLBinarySpecies(), PureFluidPhase::report(), MolalityVPSSTP::report(), ThermoPhase::report(), PureFluidPhase::reportCSV(), vcs_MultiPhaseEquil::reportCSV(), MolalityVPSSTP::reportCSV(), ThermoPhase::reportCSV(), HMWSoln::s_updatePitzer_d2lnMolalityActCoeff_dT2(), HMWSoln::s_updatePitzer_dlnMolalityActCoeff_dP(), HMWSoln::s_updatePitzer_dlnMolalityActCoeff_dT(), HMWSoln::s_updatePitzer_lnMolalityActCoeff(), StFlow::save(), SurfPhase::setCoveragesByName(), ChemEquil::setInitialMoles(), Phase::setMassFractionsByName(), MolalityVPSSTP::setMolalitiesByName(), Phase::setMoleFractionsByName(), ThermoPhase::setState_TPX(), ThermoPhase::setState_TPY(), Inlet1D::showSolution(), ReactingSurf1D::showSolution(), Phase::speciesSPName(), and ChemEquil::update().
std::string speciesSPName (int k) const inherited
Returns the expanded species name of a species, including the phase name This is guaranteed to be unique within a Cantera problem.
Parameters
k Species index within the phase
Returns
The "phaseName:speciesName" string
Definition at line 282 of file Phase.cpp.
References Phase::m_name, and Phase::speciesName().
const vector< string > & speciesNames () const inherited
Return a const reference to the vector of species names.
Definition at line 263 of file Phase.cpp.
References Phase::m_speciesNames.
Referenced by PDSS_ConstVol::constructPDSSFile(), PDSS_HKFT::constructPDSSFile(), PDSS_IonsFromNeutral::constructPDSSFile(), PDSS_SSVol::constructPDSSFile(), VPSSMgr_ConstVol::initThermoXML(), VPSSMgr_Water_ConstVol::initThermoXML(), VPSSMgr_Water_HKFT::initThermoXML(), IdealMolalSoln::initThermoXML(), LatticePhase::initThermoXML(), IdealSolidSolnPhase::initThermoXML(), DebyeHuckel::initThermoXML(), TransportFactory::setupLiquidTransport(), and TransportFactory::setupMM().
size_t nSpecies () const inline inherited
Returns the number of species in the phase.
Definition at line 252 of file Phase.h.
References Phase::m_kk.
Referenced by MultiPhase::addPhase(), InterfaceKinetics::applyButlerVolmerCorrection(), Kinetics::assignShallowPointers(), MultiPhase::calcElemAbundances(), Phase::chargeDensity(), MultiPhaseEquil::computeReactionSteps(), PDSS_IonsFromNeutral::constructPDSSXML(), RedlichKisterVPSSTP::cp_mole(), MargulesVPSSTP::cp_mole(), MixedSolventElectrolyte::cp_mole(), PhaseCombo_Interaction::cp_mole(), SolidTransport::electricalConductivity(), RedlichKisterVPSSTP::enthalpy_mole(), MargulesVPSSTP::enthalpy_mole(), MixedSolventElectrolyte::enthalpy_mole(), PhaseCombo_Interaction::enthalpy_mole(), RedlichKisterVPSSTP::entropy_mole(), MargulesVPSSTP::entropy_mole(), MixedSolventElectrolyte::entropy_mole(), PhaseCombo_Interaction::entropy_mole(), ChemEquil::equilibrate(), vcs_MultiPhaseEquil::equilibrate_TP(), ChemEquil::estimateElementPotentials(), ThermoPhase::getActivities(), MetalPhase::getActivityConcentrations(), MetalPhase::getChemPotentials(), IonsFromNeutralVPSSTP::getdlnActCoeffds(), MetalPhase::getEnthalpy_RT(), MetalPhase::getEntropy_R(), AqueousKinetics::getEquilibriumConstants(), InterfaceKinetics::getEquilibriumConstants(), MultiTransport::getMassFluxes(), LTI_Pairwise_Interaction::getMatrixTransProp(), LTI_StefanMaxwell_PPN::getMatrixTransProp(), SolidTransport::getMixDiffCoeffs(), LTI_MoleFracs::getMixTransProp(), LTI_MassFracs::getMixTransProp(), LTI_Log_MoleFracs::getMixTransProp(), LTI_Pairwise_Interaction::getMixTransProp(), LTI_StefanMaxwell_PPN::getMixTransProp(), LTI_MoleFracs_ExpT::getMixTransProp(), SolidTransport::getMobilities(), MultiTransport::getMolarFluxes(), Phase::getMoleFractionsByName(), MultiPhase::getMoles(), MetalPhase::getStandardChemPotentials(), ImplicitSurfChem::ImplicitSurfChem(), Cantera::importSolution(), LiquidTranInteraction::init(), MultiPhase::init(), AqueousKinetics::init(), GasKinetics::init(), InterfaceKinetics::init(), GasTransport::initGas(), ChemEquil::initialize(), DustyGasTransport::initialize(), PseudoBinaryVPSSTP::initLengths(), IdealSolnGasVPSS::initLengths(), MolarityIonicVPSSTP::initLengths(), GibbsExcessVPSSTP::initLengths(), VPStandardStateTP::initLengths(), IonsFromNeutralVPSSTP::initLengths(), MixtureFugacityTP::initLengths(), VPSSMgr::initLengths(), PhaseCombo_Interaction::initLengths(), RedlichKisterVPSSTP::initLengths(), MargulesVPSSTP::initLengths(), MixedSolventElectrolyte::initLengths(), MolalityVPSSTP::initLengths(), IdealMolalSoln::initLengths(), IdealSolidSolnPhase::initLengths(), DebyeHuckel::initLengths(), HMWSoln::initLengths(), LiquidTransport::initLiquid(), SimpleTransport::initLiquid(), AqueousTransport::initLiquid(), ConstDensityThermo::initThermo(), StoichSubstance::initThermo(), StoichSubstanceSSTP::initThermo(), LatticeSolidPhase::initThermo(), SingleSpeciesTP::initThermo(), LatticePhase::initThermo(), FlowDevice::install(), rxninfo::installReaction(), LatticeSolidPhase::installSlavePhases(), Kinetics::nTotalSpecies(), solveProb::print_header(), PseudoBinaryVPSSTP::report(), MolarityIonicVPSSTP::report(), PureFluidPhase::report(), MolalityVPSSTP::report(), ThermoPhase::report(), PureFluidPhase::reportCSV(), vcs_MultiPhaseEquil::reportCSV(), MolalityVPSSTP::reportCSV(), ThermoPhase::reportCSV(), Phase::restoreState(), IonsFromNeutralVPSSTP::s_update_dlnActCoeff_dlnN(), Phase::saveState(), Kinetics::selectPhase(), ImplicitSurfChem::setConcSpecies(), SurfPhase::setCoveragesByName(), Phase::setMassFractionsByName(), MolalityVPSSTP::setMolalitiesByName(), Phase::setMoleFractionsByName(), MultiPhase::setMoles(), SolidTransport::setParameters(), MultiPhase::setPhaseMoleFractions(), vcs_VolPhase::setPtrThermoPhase(), ThermoPhase::setState_TPX(), ThermoPhase::setState_TPY(), Transport::setThermo(), ReactorBase::setThermoMgr(), TransportFactory::setupLiquidTransport(), TransportFactory::setupMM(), Inlet1D::showSolution(), solveSP::solveSP(), StFlow::StFlow(), vcs_VolPhase::transferElementsFM(), AqueousKinetics::updateKc(), InterfaceKinetics::updateKc(), ConstPressureReactor::updateState(), Reactor::updateState(), and MultiPhase::uploadMoleFractionsFromPhases().
void checkSpeciesIndex (size_t k) const inherited
Check that the specified species index is in range Throws an exception if k is greater than nSpecies()-1.
Definition at line 268 of file Phase.cpp.
References Phase::m_kk.
Referenced by Phase::concentration(), Phase::massFraction(), Phase::molecularWeight(), Phase::moleFraction(), Phase::nAtoms(), and Phase::speciesName().
void checkSpeciesArraySize (size_t kk) const inherited
Check that an array size is at least nSpecies() Throws an exception if kk is less than nSpecies().
Used before calls which take an array pointer.
Definition at line 275 of file Phase.cpp.
References Phase::m_kk.
void saveState (vector_fp & state) const inherited
Save the current internal state of the phase Write to vector 'state' the current internal state.
Parameters
state output vector. Will be resized to nSpecies() + 2.
Definition at line 288 of file Phase.cpp.
References Phase::nSpecies().
Referenced by ChemEquil::equilibrate(), ChemEquil::estimateEP_Brinkley(), TransportFactory::newTransport(), ReactorBase::setThermoMgr(), FlowReactor::updateState(), ConstPressureReactor::updateState(), and Reactor::updateState().
void saveState (size_t lenstate, doublereal * state) const inherited
Write to array 'state' the current internal state.
Parameters
lenstate length of the state array. Must be >= nSpecies()+2
state output vector. Must be of length nSpecies() + 2 or greater.
Definition at line 293 of file Phase.cpp.
References Phase::density(), Phase::getMassFractions(), and Phase::temperature().
void restoreState (const vector_fp & state) inherited
Restore a state saved on a previous call to saveState.
Parameters
state State vector containing the previously saved state.
Definition at line 300 of file Phase.cpp.
Referenced by ChemEquil::equilibrate(), ChemEquil::estimateEP_Brinkley(), MultiTransport::getMassFluxes(), FlowReactor::initialize(), ConstPressureReactor::initialize(), Reactor::initialize(), and TransportFactory::newTransport().
void restoreState (size_t lenstate, const doublereal * state) inherited
Restore the state of the phase from a previously saved state vector.
Parameters
lenstate Length of the state vector
state Vector of state conditions.
Definition at line 305 of file Phase.cpp.
References Phase::nSpecies(), Phase::setDensity(), Phase::setMassFractions_NoNorm(), and Phase::setTemperature().
void setMoleFractionsByName (compositionMap & xMap) inherited
Set the species mole fractions by name.
@param xMap map from species names to mole fraction values.
Species not listed by name in xMap are set to zero.
Definition at line 362 of file Phase.cpp.
References Phase::nSpecies(), Phase::setMoleFractions(), and Phase::speciesName().
Referenced by Inlet1D::setMoleFractions(), OutletRes1D::setMoleFractions(), Phase::setMoleFractionsByName(), ThermoPhase::setState_TPX(), Phase::setState_TRX(), MixtureFugacityTP::setStateFromXML(), and ThermoPhase::setStateFromXML().
void setMoleFractionsByName (const std::string & x) inherited
Set the mole fractions of a group of species by name.
Species which are not listed by name in the composition map are set to zero.
Parameters
x string x in the form of a composition map
Definition at line 376 of file Phase.cpp.
References Phase::nSpecies(), Cantera::parseCompString(), Phase::setMoleFractionsByName(), and Phase::speciesName().
void setMassFractionsByName (compositionMap & yMap) inherited
Set the species mass fractions by name.
@param yMap map from species names to mass fraction values.
Species not listed by name in yMap are set to zero.
Definition at line 416 of file Phase.cpp.
References Phase::nSpecies(), Phase::setMassFractions(), and Phase::speciesName().
Referenced by Phase::setMassFractionsByName(), ThermoPhase::setState_TPY(), Phase::setState_TRY(), MixtureFugacityTP::setStateFromXML(), and ThermoPhase::setStateFromXML().
void setMassFractionsByName (const std::string & x) inherited
Set the species mass fractions by name.
Species not listed by name in x are set to zero.
Parameters
x String containing a composition map
Definition at line 430 of file Phase.cpp.
References Phase::nSpecies(), Cantera::parseCompString(), Phase::setMassFractionsByName(), and Phase::speciesName().
void setState_TRX (doublereal t, doublereal dens, const doublereal * x) inherited
Set the internally stored temperature (K), density, and mole fractions.
Parameters
t Temperature in kelvin
dens Density (kg/m^3)
x vector of species mole fractions, length m_kk
Definition at line 441 of file Phase.cpp.
References Phase::setDensity(), Phase::setMoleFractions(), and Phase::setTemperature().
void setState_TRX (doublereal t, doublereal dens, compositionMap & x) inherited
Set the internally stored temperature (K), density, and mole fractions.
Parameters
t Temperature in kelvin
dens Density (kg/m^3)
x Composition Map containing the mole fractions. Species not included in the map are assumed to have a zero mole fraction.
Definition at line 455 of file Phase.cpp.
References Phase::setDensity(), Phase::setMoleFractionsByName(), and Phase::setTemperature().
void setState_TRY (doublereal t, doublereal dens, const doublereal * y) inherited
Set the internally stored temperature (K), density, and mass fractions.
Parameters
t Temperature in kelvin
dens Density (kg/m^3)
y vector of species mass fractions, length m_kk
Definition at line 462 of file Phase.cpp.
References Phase::setDensity(), Phase::setMassFractions(), and Phase::setTemperature().
void setState_TRY (doublereal t, doublereal dens, compositionMap & y) inherited
Set the internally stored temperature (K), density, and mass fractions.
Parameters
t Temperature in kelvin
dens Density (kg/m^3)
y Composition Map containing the mass fractions. Species not included in the map are assumed to have a zero mass fraction.
Definition at line 469 of file Phase.cpp.
References Phase::setDensity(), Phase::setMassFractionsByName(), and Phase::setTemperature().
void setState_TNX (doublereal t, doublereal n, const doublereal * x) inherited
Set the internally stored temperature (K), molar density (kmol/m^3), and mole fractions.
Parameters
t Temperature in kelvin
n molar density (kmol/m^3)
x vector of species mole fractions, length m_kk
Definition at line 448 of file Phase.cpp.
References Phase::setMolarDensity(), Phase::setMoleFractions(), and Phase::setTemperature().
void setState_TR (doublereal t, doublereal rho) inherited
Set the internally stored temperature (K) and density (kg/m^3)
Parameters
t Temperature in kelvin
rho Density (kg/m^3)
Definition at line 476 of file Phase.cpp.
References Phase::setDensity(), and Phase::setTemperature().
Referenced by PureFluidPhase::setState_HP(), PureFluidPhase::setState_SP(), PureFluidPhase::setState_SV(), PDSS_IonsFromNeutral::setState_TR(), and PureFluidPhase::setState_UV().
void setState_TX (doublereal t, doublereal * x) inherited
Set the internally stored temperature (K) and mole fractions.
Parameters
t Temperature in kelvin
x vector of species mole fractions, length m_kk
Definition at line 482 of file Phase.cpp.
References Phase::setMoleFractions(), and Phase::setTemperature().
void setState_TY (doublereal t, doublereal * y) inherited
Set the internally stored temperature (K) and mass fractions.
Parameters
t Temperature in kelvin
y vector of species mass fractions, length m_kk
Definition at line 488 of file Phase.cpp.
References Phase::setMassFractions(), and Phase::setTemperature().
void setState_RX (doublereal rho, doublereal * x) inherited
Set the density (kg/m^3) and mole fractions.
Parameters
rho Density (kg/m^3)
x vector of species mole fractions, length m_kk
Definition at line 494 of file Phase.cpp.
References Phase::setDensity(), and Phase::setMoleFractions().
void setState_RY (doublereal rho, doublereal * y) inherited
Set the density (kg/m^3) and mass fractions.
Parameters
rho Density (kg/m^3)
y vector of species mass fractions, length m_kk
Definition at line 500 of file Phase.cpp.
References Phase::setDensity(), and Phase::setMassFractions().
doublereal molecularWeight (size_t k) const inherited
Molecular weight of species k.
Parameters
k index of species k
Returns
Returns the molecular weight of species k.
Definition at line 506 of file Phase.cpp.
References Phase::checkSpeciesIndex(), and Phase::m_molwts.
Referenced by VPSSMgr_Water_ConstVol::_updateRefStateThermo(), VPSSMgr_Water_HKFT::_updateRefStateThermo(), VPSSMgr_Water_ConstVol::_updateStandardStateThermo(), VPSSMgr_Water_HKFT::_updateStandardStateThermo(), SingleSpeciesTP::cv_mole(), SingleSpeciesTP::getPartialMolarVolumes(), SingleSpeciesTP::getStandardVolumes(), VPSSMgr_Water_ConstVol::getStandardVolumes_ref(), PDSS::initThermo(), VPSSMgr_Water_ConstVol::initThermoXML(), VPSSMgr_Water_HKFT::initThermoXML(), PDSS_ConstVol::initThermoXML(), MineralEQ3::initThermoXML(), PDSS_SSVol::initThermoXML(), Phase::molarMass(), MolalityVPSSTP::setSolvent(), HMWSoln::speciesMolarVolume(), and LiquidTransport::stefan_maxwell_solve().
doublereal molarMass (size_t k) const inline inherited
Return the Molar mass of species k Alternate name for molecular weight.
@param k  index for species
@return   Return the molar mass of species k kg/kmol.
Deprecated:
use molecularWeight instead
Definition at line 388 of file Phase.h.
References Phase::molecularWeight().
void getMolecularWeights (vector_fp & weights) const inherited
Copy the vector of molecular weights into vector weights.
Parameters
weights Output vector of molecular weights (kg/kmol)
Definition at line 512 of file Phase.cpp.
References Phase::molecularWeights().
void getMolecularWeights (int iwt, doublereal * weights) const inherited
Copy the vector of molecular weights into array weights.
@param iwt      Unused.
@param weights  Output array of molecular weights (kg/kmol)
Deprecated:
Definition at line 521 of file Phase.cpp.
References Phase::molecularWeights().
void getMolecularWeights (doublereal * weights) const inherited
Copy the vector of molecular weights into array weights.
Parameters
weights Output array of molecular weights (kg/kmol)
Definition at line 527 of file Phase.cpp.
References Phase::molecularWeights().
const vector_fp & molecularWeights () const inherited
Return a const reference to the internal vector of molecular weights.
units = kg / kmol
Definition at line 533 of file Phase.cpp.
References Phase::m_molwts.
Referenced by ReactingSurf1D::eval(), Phase::freezeSpecies(), Phase::getMolecularWeights(), MixTransport::getSpeciesFluxes(), AqueousTransport::getSpeciesFluxesExt(), SimpleTransport::getSpeciesFluxesExt(), Cantera::getStick(), GasTransport::initGas(), DustyGasTransport::initialize(), LiquidTransport::initLiquid(), SimpleTransport::initLiquid(), AqueousTransport::initLiquid(), TransportFactory::setupLiquidTransport(), TransportFactory::setupMM(), AqueousTransport::stefan_maxwell_solve(), LiquidTransport::stefan_maxwell_solve(), and StFlow::StFlow().
doublereal size (size_t k) const inline inherited
This routine returns the size of species k.
Parameters
k index of the species
Returns
The size of the species. Units are meters.
Definition at line 413 of file Phase.h.
References Phase::m_speciesSize.
Referenced by MolarityIonicVPSSTP::constructPhaseXML(), RedlichKisterVPSSTP::constructPhaseXML(), MargulesVPSSTP::constructPhaseXML(), MixedSolventElectrolyte::constructPhaseXML(), PhaseCombo_Interaction::constructPhaseXML(), IonsFromNeutralVPSSTP::constructPhaseXML(), IdealMolalSoln::constructPhaseXML(), IdealSolidSolnPhase::constructPhaseXML(), DebyeHuckel::constructPhaseXML(), ReactingSurf1D::eval(), SurfPhase::getCoverages(), SurfPhase::initThermo(), IdealMolalSoln::initThermoXML(), LatticeSolidPhase::installSlavePhases(), SurfPhase::setCoverages(), SurfPhase::setCoveragesNoNorm(), and SurfPhase::standardConcentration().
void getMoleFractionsByName (compositionMap & x) const inherited
Get the mole fractions by name.
Parameters
[out] x composition map containing the species mole fractions.
Definition at line 538 of file Phase.cpp.
References Phase::moleFraction(), Phase::nSpecies(), and Phase::speciesName().
doublereal moleFraction (size_t k) const inherited
Return the mole fraction of a single species.
Parameters
k species index
Returns
Mole fraction of the species
Definition at line 552 of file Phase.cpp.
References Phase::checkSpeciesIndex(), Phase::m_mmw, and Phase::m_ym.
Referenced by Phase::chargeDensity(), SolidTransport::electricalConductivity(), ChemEquil::equilibrate(), IdealMolalSoln::getActivities(), DebyeHuckel::getActivities(), HMWSoln::getActivities(), MolalityVPSSTP::getActivityCoefficients(), IdealSolnGasVPSS::getActivityConcentrations(), RedlichKwongMFTP::getActivityConcentrations(), ConstDensityThermo::getChemPotentials(), IdealSolnGasVPSS::getChemPotentials(), RedlichKwongMFTP::getChemPotentials(), IdealSolidSolnPhase::getChemPotentials(), IdealMolalSoln::getChemPotentials(), IdealGasPhase::getChemPotentials(), LatticePhase::getChemPotentials(), DebyeHuckel::getChemPotentials(), HMWSoln::getChemPotentials(), IdealSolidSolnPhase::getChemPotentials_RT(), IdealMolalSoln::getMolalityActivityCoefficients(), Phase::getMoleFractionsByName(), IdealSolnGasVPSS::getPartialMolarEntropies(), RedlichKwongMFTP::getPartialMolarEntropies(), IdealGasPhase::getPartialMolarEntropies(), IdealMolalSoln::getPartialMolarEntropies(), IdealSolidSolnPhase::getPartialMolarEntropies(), LatticePhase::getPartialMolarEntropies(), DebyeHuckel::getPartialMolarEntropies(), HMWSoln::getPartialMolarEntropies(), Phase::moleFraction(), DebyeHuckel::s_update_d2lnMolalityActCoeff_dT2(), DebyeHuckel::s_update_dlnMolalityActCoeff_dP(), DebyeHuckel::s_update_dlnMolalityActCoeff_dT(), DebyeHuckel::s_update_lnMolalityActCoeff(), HMWSoln::s_update_lnMolalityActCoeff(), IdealMolalSoln::s_updateIMS_lnMolalityActCoeff(), HMWSoln::s_updateIMS_lnMolalityActCoeff(), HMWSoln::s_updatePitzer_lnMolalityActCoeff(), and ChemEquil::setInitialMoles().
doublereal moleFraction (std::string name) const inherited
Return the mole fraction of a single species.
Parameters
name String name of the species
Returns
Mole fraction of the species
Definition at line 558 of file Phase.cpp.
References Phase::moleFraction(), Cantera::npos, and Phase::speciesIndex().
doublereal massFraction (size_t k) const inherited
Return the mass fraction of a single species.
Parameters
k species index
Returns
Mass fraction of the species
Definition at line 573 of file Phase.cpp.
References Phase::checkSpeciesIndex(), and Phase::m_y.
doublereal massFraction (std::string name) const inherited
Return the mass fraction of a single species.
Parameters
name String name of the species
Returns
Mass Fraction of the species
Definition at line 579 of file Phase.cpp.
References Phase::massFractions(), Cantera::npos, and Phase::speciesIndex().
void getMoleFractions (doublereal *const x) const inherited
Get the species mole fraction vector.
Parameters
x On return, x contains the mole fractions. Must have a length greater than or equal to the number of species.
Definition at line 547 of file Phase.cpp.
References Phase::m_mmw, Phase::m_ym, and Cantera::scale().
Referenced by IdealMolalSoln::calcDensity(), DebyeHuckel::calcDensity(), HMWSoln::calcDensity(), IonsFromNeutralVPSSTP::calcIonMoleFractions(), MolalityVPSSTP::calcMolalities(), HMWSoln::calcMolalitiesCropped(), IdealMolalSoln::enthalpy_mole(), HMWSoln::enthalpy_mole(), ChemEquil::estimateElementPotentials(), ChemEquil::estimateEP_Brinkley(), GibbsExcessVPSSTP::getActivities(), LatticePhase::getActivityConcentrations(), MultiTransport::getMassFluxes(), LTI_Pairwise_Interaction::getMatrixTransProp(), LTI_StefanMaxwell_PPN::getMatrixTransProp(), LTI_MoleFracs::getMixTransProp(), LTI_Log_MoleFracs::getMixTransProp(), LTI_Pairwise_Interaction::getMixTransProp(), LTI_StefanMaxwell_PPN::getMixTransProp(), LTI_MoleFracs_ExpT::getMixTransProp(), LatticeSolidPhase::getMoleFractions(), DustyGasTransport::initialize(), GibbsExcessVPSSTP::initThermo(), HMWSoln::printCoeffs(), HMWSoln::relative_molal_enthalpy(), PseudoBinaryVPSSTP::report(), MolarityIonicVPSSTP::report(), PureFluidPhase::report(), MolalityVPSSTP::report(), ThermoPhase::report(), PureFluidPhase::reportCSV(), MolalityVPSSTP::reportCSV(), ThermoPhase::reportCSV(), MixtureFugacityTP::setConcentrations(), GibbsExcessVPSSTP::setConcentrations(), MixtureFugacityTP::setMassFractions(), GibbsExcessVPSSTP::setMassFractions(), MixtureFugacityTP::setMassFractions_NoNorm(), GibbsExcessVPSSTP::setMassFractions_NoNorm(), MolalityVPSSTP::setMolalitiesByName(), MixtureFugacityTP::setMoleFractions(), GibbsExcessVPSSTP::setMoleFractions(), MixtureFugacityTP::setMoleFractions_NoNorm(), GibbsExcessVPSSTP::setMoleFractions_NoNorm(), MultiPhase::setMoles(), vcs_VolPhase::setPtrThermoPhase(), ThermoPhase::setReferenceComposition(), MixtureFugacityTP::setState_TP(), MixtureFugacityTP::setState_TR(), AqueousTransport::stefan_maxwell_solve(), ChemEquil::update(), MixTransport::update_C(), MultiTransport::update_C(), AqueousTransport::update_C(), SimpleTransport::update_C(), LiquidTransport::update_C(), solveSP::updateMFKinSpecies(), DustyGasTransport::updateTransport_C(), and MultiPhase::uploadMoleFractionsFromPhases().
void setMoleFractions (const doublereal *const x) virtual inherited
Set the mole fractions to the specified values There is no restriction on the sum of the mole fraction vector.
Internally, the Phase object will normalize this vector before storing its contents.
Parameters
x Array of unnormalized mole fraction values (input). Must have a length greater than or equal to the number of species, m_kk.
Reimplemented in IonsFromNeutralVPSSTP, GibbsExcessVPSSTP, LatticePhase, MixtureFugacityTP, IdealSolidSolnPhase, LatticeSolidPhase, and RedlichKwongMFTP.
Definition at line 317 of file Phase.cpp.
References Phase::m_kk, Phase::m_mmw, Phase::m_molwts, Phase::m_y, Phase::m_ym, ckr::max(), and Phase::stateMFChangeCalc().
Referenced by ChemEquil::calcEmoles(), ChemEquil::equilibrate(), ChemEquil::estimateElementPotentials(), ChemEquil::estimateEP_Brinkley(), PureFluidPhase::initThermo(), SingleSpeciesTP::initThermo(), WaterSSTP::initThermoXML(), IonsFromNeutralVPSSTP::setConcentrations(), IonsFromNeutralVPSSTP::setMassFractions(), IonsFromNeutralVPSSTP::setMassFractions_NoNorm(), MolalityVPSSTP::setMolalities(), MolalityVPSSTP::setMolalitiesByName(), Inlet1D::setMoleFractions(), OutletRes1D::setMoleFractions(), LatticeSolidPhase::setMoleFractions(), IdealSolidSolnPhase::setMoleFractions(), MixtureFugacityTP::setMoleFractions(), LatticePhase::setMoleFractions(), GibbsExcessVPSSTP::setMoleFractions(), IonsFromNeutralVPSSTP::setMoleFractions(), IdealSolidSolnPhase::setMoleFractions_NoNorm(), LatticePhase::setMoleFractions_NoNorm(), Phase::setMoleFractionsByName(), ThermoPhase::setState_PX(), Phase::setState_RX(), Phase::setState_TNX(), ThermoPhase::setState_TPX(), Phase::setState_TRX(), and Phase::setState_TX().
void setMoleFractions_NoNorm (const doublereal *const x) virtual inherited
Set the mole fractions to the specified values without normalizing.
This is useful when the normalization condition is being handled by some other means, for example by a constraint equation as part of a larger set of equations.
Parameters
x Input vector of mole fractions. Length is m_kk.
Reimplemented in IonsFromNeutralVPSSTP, GibbsExcessVPSSTP, LatticePhase, MixtureFugacityTP, IdealSolidSolnPhase, and RedlichKwongMFTP.
Definition at line 350 of file Phase.cpp.
References Cantera::dot(), Phase::m_kk, Phase::m_mmw, Phase::m_molwts, Phase::m_y, Phase::m_ym, and Phase::stateMFChangeCalc().
Referenced by MixtureFugacityTP::setMoleFractions_NoNorm(), GibbsExcessVPSSTP::setMoleFractions_NoNorm(), and IonsFromNeutralVPSSTP::setMoleFractions_NoNorm().
void getMassFractions (doublereal *const y) const inherited
Get the species mass fractions.
Parameters
[out] y Array of mass fractions, length nSpecies()
Definition at line 589 of file Phase.cpp.
References Phase::m_y.
Referenced by LTI_MassFracs::getMixTransProp(), Cantera::importSolution(), PureFluidPhase::report(), ThermoPhase::report(), PureFluidPhase::reportCSV(), ThermoPhase::reportCSV(), Phase::saveState(), Inlet1D::setMoleFractions(), OutletRes1D::setMoleFractions(), and LiquidTransport::update_C().
const doublereal* massFractions () const inline inherited
Return a const pointer to the mass fraction array.
Definition at line 469 of file Phase.h.
References Phase::m_y.
Referenced by MultiTransport::getMassFluxes(), MultiTransport::getSpeciesFluxes(), MixTransport::getSpeciesFluxes(), AqueousTransport::getSpeciesFluxesExt(), SimpleTransport::getSpeciesFluxesExt(), SimpleTransport::getSpeciesVdiff(), SimpleTransport::getSpeciesVdiffES(), and Phase::massFraction().
void setMassFractions (const doublereal *const y) virtual inherited
Set the mass fractions to the specified values and normalize them.
@param[in] y Array of unnormalized mass fraction values. Length
must be greater than or equal to the number of species. The Ptate object will normalize this vector before storing its contents.
Reimplemented in IonsFromNeutralVPSSTP, LatticePhase, GibbsExcessVPSSTP, MixtureFugacityTP, LatticeSolidPhase, IdealSolidSolnPhase, and RedlichKwongMFTP.
Definition at line 387 of file Phase.cpp.
References Phase::m_kk, Phase::m_mmw, Phase::m_rmolwts, Phase::m_y, Phase::m_ym, ckr::max(), Cantera::scale(), and Phase::stateMFChangeCalc().
Referenced by Cantera::importSolution(), IdealSolidSolnPhase::setMassFractions(), MixtureFugacityTP::setMassFractions(), GibbsExcessVPSSTP::setMassFractions(), LatticePhase::setMassFractions(), Phase::setMassFractionsByName(), ThermoPhase::setState_PY(), Phase::setState_RY(), ThermoPhase::setState_TPY(), Phase::setState_TRY(), Phase::setState_TY(), FlowReactor::updateState(), ConstPressureReactor::updateState(), and Reactor::updateState().
void setMassFractions_NoNorm (const doublereal *const y) virtual inherited
Set the mass fractions to the specified values without normalizing.
This is useful when the normalization condition is being handled by some other means, for example by a constraint equation as part of a larger set of equations.
Parameters
y Input vector of mass fractions. Length is m_kk.
Reimplemented in IonsFromNeutralVPSSTP, LatticePhase, GibbsExcessVPSSTP, MixtureFugacityTP, LatticeSolidPhase, IdealSolidSolnPhase, and RedlichKwongMFTP.
Definition at line 403 of file Phase.cpp.
References Phase::m_kk, Phase::m_mmw, Phase::m_rmolwts, Phase::m_y, Phase::m_ym, and Phase::stateMFChangeCalc().
Referenced by Phase::restoreState(), StFlow::setGas(), StFlow::setGasAtMidpoint(), IdealSolidSolnPhase::setMassFractions_NoNorm(), MixtureFugacityTP::setMassFractions_NoNorm(), GibbsExcessVPSSTP::setMassFractions_NoNorm(), and LatticePhase::setMassFractions_NoNorm().
void getConcentrations (doublereal *const c) const inherited
Get the species concentrations (kmol/m^3).
@param[out] c Array of species concentrations Length must be
greater than or equal to the number of species.
Definition at line 600 of file Phase.cpp.
References Phase::m_dens, Phase::m_ym, and Cantera::scale().
Referenced by ConstDensityThermo::getActivityConcentrations(), IdealSolnGasVPSS::getActivityConcentrations(), SurfPhase::getActivityConcentrations(), IdealGasPhase::getActivityConcentrations(), SurfPhase::getCoverages(), solveSP::solveSurfProb(), SimpleTransport::update_C(), and LiquidTransport::update_C().
doublereal concentration (const size_t k) const inherited
Concentration of species k.
If k is outside the valid range, an exception will be thrown.
Parameters
k Index of species
Definition at line 594 of file Phase.cpp.
References Phase::checkSpeciesIndex(), Phase::m_dens, Phase::m_rmolwts, and Phase::m_y.
void setConcentrations (const doublereal *const conc) virtual inherited
Set the concentrations to the specified values within the phase.
We set the concentrations here and therefore we set the overall density of the phase. We hold the temperature constant during this operation. Therefore, we have possibly changed the pressure of the phase by calling this routine.
Parameters
[in] conc Array of concentrations in dimensional units. For bulk phases c[k] is the concentration of the kth species in kmol/m3. For surface phases, c[k] is the concentration in kmol/m2. The length of the vector is the numberof species in the phase.
Reimplemented in IonsFromNeutralVPSSTP, GibbsExcessVPSSTP, LatticePhase, MixtureFugacityTP, LatticeSolidPhase, IdealSolidSolnPhase, and RedlichKwongMFTP.
Definition at line 605 of file Phase.cpp.
References Phase::m_kk, Phase::m_mmw, Phase::m_molwts, Phase::m_y, Phase::m_ym, ckr::max(), Phase::setDensity(), and Phase::stateMFChangeCalc().
Referenced by IdealSolidSolnPhase::setConcentrations(), MixtureFugacityTP::setConcentrations(), LatticePhase::setConcentrations(), GibbsExcessVPSSTP::setConcentrations(), ImplicitSurfChem::setConcSpecies(), SurfPhase::setCoverages(), and SurfPhase::setCoveragesNoNorm().
const doublereal * moleFractdivMMW () const inherited
Returns a const pointer to the start of the moleFraction/MW array.
This array is the array of mole fractions, each divided by the mean molecular weight.
Definition at line 568 of file Phase.cpp.
References Phase::m_ym.
Referenced by IdealSolnGasVPSS::calcDensity(), RedlichKwongMFTP::calcDensity(), IdealSolidSolnPhase::calcDensity(), and IdealSolidSolnPhase::getActivityConcentrations().
doublereal charge (size_t k) const inherited
Dimensionless electrical charge of a single molecule of species k The charge is normalized by the the magnitude of the electron charge.
Parameters
k species index
Definition at line 642 of file Phase.cpp.
References Phase::m_speciesCharge.
Referenced by InterfaceKinetics::applyButlerVolmerCorrection(), HMWSoln::calcMolalitiesCropped(), Phase::chargeDensity(), PDSS_HKFT::constructPDSSXML(), SolidTransport::electricalConductivity(), PureFluidPhase::getElectrochemPotentials(), PseudoBinaryVPSSTP::getElectrochemPotentials(), MolarityIonicVPSSTP::getElectrochemPotentials(), GibbsExcessVPSSTP::getElectrochemPotentials(), RedlichKisterVPSSTP::getElectrochemPotentials(), MargulesVPSSTP::getElectrochemPotentials(), ThermoPhase::getElectrochemPotentials(), MixedSolventElectrolyte::getElectrochemPotentials(), MolalityVPSSTP::getElectrochemPotentials(), PhaseCombo_Interaction::getElectrochemPotentials(), InterfaceKinetics::getEquilibriumConstants(), LiquidTransport::initLiquid(), SimpleTransport::initLiquid(), PDSS_HKFT::initThermo(), IonsFromNeutralVPSSTP::initThermoXML(), DebyeHuckel::initThermoXML(), LatticeSolidPhase::installSlavePhases(), HMWSoln::printCoeffs(), PhaseCombo_Interaction::readXMLBinarySpecies(), RedlichKisterVPSSTP::readXMLBinarySpecies(), MargulesVPSSTP::readXMLBinarySpecies(), MixedSolventElectrolyte::readXMLBinarySpecies(), HMWSoln::relative_molal_enthalpy(), HMWSoln::s_updatePitzer_d2lnMolalityActCoeff_dT2(), HMWSoln::s_updatePitzer_dlnMolalityActCoeff_dP(), HMWSoln::s_updatePitzer_dlnMolalityActCoeff_dT(), HMWSoln::s_updatePitzer_lnMolalityActCoeff(), MolalityVPSSTP::setMolalitiesByName(), vcs_VolPhase::transferElementsFM(), and InterfaceKinetics::updateKc().
doublereal chargeDensity () const inherited
Charge density [C/m^3].
Definition at line 647 of file Phase.cpp.
References Phase::charge(), Phase::moleFraction(), and Phase::nSpecies().
size_t nDim () const inline inherited
Returns the number of spatial dimensions (1, 2, or 3)
Definition at line 523 of file Phase.h.
References Phase::m_ndim.
Referenced by Kinetics::addPhase(), EdgeKinetics::finalize(), InterfaceKinetics::finalize(), IdealSolnGasVPSS::getUnitsStandardConc(), RedlichKwongMFTP::getUnitsStandardConc(), IdealMolalSoln::getUnitsStandardConc(), MolalityVPSSTP::getUnitsStandardConc(), IdealSolidSolnPhase::getUnitsStandardConc(), ThermoPhase::getUnitsStandardConc(), DebyeHuckel::getUnitsStandardConc(), and HMWSoln::getUnitsStandardConc().
void setNDim (size_t ndim) inline inherited
Set the number of spatial dimensions (1, 2, or 3).
The number of spatial dimensions is used for vector involving directions.
Parameters
ndim Input number of dimensions.
Definition at line 530 of file Phase.h.
References Phase::m_ndim.
Referenced by EdgePhase::EdgePhase(), FixedChemPotSSTP::FixedChemPotSSTP(), Cantera::importPhase(), EdgePhase::operator=(), and SurfPhase::SurfPhase().
doublereal temperature () const inline inherited
Temperature (K).
Returns
The temperature of the phase
Definition at line 539 of file Phase.h.
References Phase::m_temp.
Referenced by ThermoPhase::_RT(), InterfaceKinetics::_update_rates_T(), MixtureFugacityTP::_updateReferenceStateThermo(), VPStandardStateTP::_updateStandardStateThermo(), ConstDensityThermo::_updateThermo(), SurfPhase::_updateThermo(), LatticeSolidPhase::_updateThermo(), SingleSpeciesTP::_updateThermo(), IdealGasPhase::_updateThermo(), LatticePhase::_updateThermo(), IdealSolidSolnPhase::_updateThermo(), DebyeHuckel::A_Debye_TP(), HMWSoln::A_Debye_TP(), MultiPhase::addPhase(), HMWSoln::ADebye_J(), HMWSoln::ADebye_L(), HMWSoln::ADebye_V(), InterfaceKinetics::applyButlerVolmerCorrection(), InterfaceKinetics::applyExchangeCurrentDensityFormulation(), IdealSolnGasVPSS::calcDensity(), MixtureFugacityTP::calculatePsat(), RedlichKwongMFTP::cp_mole(), SingleSpeciesTP::cv_mole(), HMWSoln::cv_mole(), DebyeHuckel::d2A_DebyedT2_TP(), HMWSoln::d2A_DebyedT2_TP(), DebyeHuckel::dA_DebyedP_TP(), HMWSoln::dA_DebyedP_TP(), DebyeHuckel::dA_DebyedT_TP(), HMWSoln::dA_DebyedT_TP(), WaterSSTP::dthermalExpansionCoeffdT(), IdealSolnGasVPSS::enthalpy_mole(), ConstDensityThermo::enthalpy_mole(), IdealSolidSolnPhase::enthalpy_mole(), LatticePhase::enthalpy_mole(), IdealGasPhase::enthalpy_mole(), ChemEquil::equilibrate(), ChemEquil::estimateElementPotentials(), ChemEquil::estimateEP_Brinkley(), FixedChemPotSSTP::FixedChemPotSSTP(), RedlichKwongMFTP::getActivityCoefficients(), ConstDensityThermo::getChemPotentials(), SurfPhase::getChemPotentials(), MolarityIonicVPSSTP::getChemPotentials(), IdealSolnGasVPSS::getChemPotentials(), IonsFromNeutralVPSSTP::getChemPotentials(), RedlichKwongMFTP::getChemPotentials(), RedlichKisterVPSSTP::getChemPotentials(), MargulesVPSSTP::getChemPotentials(), MixedSolventElectrolyte::getChemPotentials(), PhaseCombo_Interaction::getChemPotentials(), IdealSolidSolnPhase::getChemPotentials(), IdealMolalSoln::getChemPotentials(), IdealGasPhase::getChemPotentials(), LatticePhase::getChemPotentials(), DebyeHuckel::getChemPotentials(), HMWSoln::getChemPotentials(), StoichSubstance::getChemPotentials_RT(), SingleSpeciesTP::getChemPotentials_RT(), IdealSolidSolnPhase::getChemPotentials_RT(), WaterSSTP::getCp_R_ref(), AqueousKinetics::getDeltaSSEnthalpy(), GasKinetics::getDeltaSSEnthalpy(), InterfaceKinetics::getDeltaSSEnthalpy(), PhaseCombo_Interaction::getdlnActCoeffds(), MargulesVPSSTP::getdlnActCoeffds(), MixedSolventElectrolyte::getdlnActCoeffds(), ThermoPhase::getElementPotentials(), WaterSSTP::getEnthalpy_RT(), StoichSubstance::getEnthalpy_RT(), StoichSubstanceSSTP::getEnthalpy_RT(), MineralEQ3::getEnthalpy_RT(), SurfPhase::getEnthalpy_RT(), IdealSolidSolnPhase::getEnthalpy_RT(), LatticePhase::getEnthalpy_RT(), WaterSSTP::getEnthalpy_RT_ref(), PureFluidPhase::getEnthalpy_RT_ref(), WaterSSTP::getEntropy_R_ref(), PureFluidPhase::getEntropy_R_ref(), AqueousKinetics::getEquilibriumConstants(), GasKinetics::getEquilibriumConstants(), InterfaceKinetics::getEquilibriumConstants(), StoichSubstance::getGibbs_ref(), PureFluidPhase::getGibbs_ref(), SingleSpeciesTP::getGibbs_ref(), LatticeSolidPhase::getGibbs_ref(), IdealSolidSolnPhase::getGibbs_ref(), LatticePhase::getGibbs_ref(), WaterSSTP::getGibbs_RT(), StoichSubstance::getGibbs_RT(), SurfPhase::getGibbs_RT(), WaterSSTP::getGibbs_RT_ref(), PureFluidPhase::getGibbs_RT_ref(), StoichSubstanceSSTP::getIntEnergy_RT(), MineralEQ3::getIntEnergy_RT(), IdealSolidSolnPhase::getIntEnergy_RT(), StoichSubstanceSSTP::getIntEnergy_RT_ref(), MineralEQ3::getIntEnergy_RT_ref(), MetalSHEelectrons::getIntEnergy_RT_ref(), IdealSolidSolnPhase::getIntEnergy_RT_ref(), LTI_Pairwise_Interaction::getMatrixTransProp(), LTI_StefanMaxwell_PPN::getMatrixTransProp(), SolidTransport::getMixDiffCoeffs(), LTI_MoleFracs::getMixTransProp(), LTI_MassFracs::getMixTransProp(), LTI_Log_MoleFracs::getMixTransProp(), LTI_MoleFracs_ExpT::getMixTransProp(), SolidTransport::getMobilities(), MolarityIonicVPSSTP::getPartialMolarCp(), RedlichKisterVPSSTP::getPartialMolarCp(), MargulesVPSSTP::getPartialMolarCp(), MixedSolventElectrolyte::getPartialMolarCp(), PhaseCombo_Interaction::getPartialMolarCp(), DebyeHuckel::getPartialMolarCp(), HMWSoln::getPartialMolarCp(), SurfPhase::getPartialMolarEnthalpies(), IdealSolnGasVPSS::getPartialMolarEnthalpies(), MolarityIonicVPSSTP::getPartialMolarEnthalpies(), SingleSpeciesTP::getPartialMolarEnthalpies(), IonsFromNeutralVPSSTP::getPartialMolarEnthalpies(), RedlichKwongMFTP::getPartialMolarEnthalpies(), RedlichKisterVPSSTP::getPartialMolarEnthalpies(), MargulesVPSSTP::getPartialMolarEnthalpies(), MixedSolventElectrolyte::getPartialMolarEnthalpies(), PhaseCombo_Interaction::getPartialMolarEnthalpies(), IdealGasPhase::getPartialMolarEnthalpies(), IdealSolidSolnPhase::getPartialMolarEnthalpies(), LatticePhase::getPartialMolarEnthalpies(), DebyeHuckel::getPartialMolarEnthalpies(), HMWSoln::getPartialMolarEnthalpies(), MolarityIonicVPSSTP::getPartialMolarEntropies(), IonsFromNeutralVPSSTP::getPartialMolarEntropies(), RedlichKwongMFTP::getPartialMolarEntropies(), RedlichKisterVPSSTP::getPartialMolarEntropies(), MargulesVPSSTP::getPartialMolarEntropies(), MixedSolventElectrolyte::getPartialMolarEntropies(), PhaseCombo_Interaction::getPartialMolarEntropies(), DebyeHuckel::getPartialMolarEntropies(), HMWSoln::getPartialMolarEntropies(), IdealSolnGasVPSS::getPartialMolarIntEnergies(), SingleSpeciesTP::getPartialMolarIntEnergies(), RedlichKwongMFTP::getPartialMolarIntEnergies(), IdealGasPhase::getPartialMolarIntEnergies(), RedlichKwongMFTP::getPartialMolarVolumes(), MargulesVPSSTP::getPartialMolarVolumes(), MixedSolventElectrolyte::getPartialMolarVolumes(), PhaseCombo_Interaction::getPartialMolarVolumes(), DebyeHuckel::getPartialMolarVolumes(), HMWSoln::getPartialMolarVolumes(), SingleSpeciesTP::getPureGibbs(), LatticePhase::getPureGibbs(), LTPspecies_Arrhenius::getSpeciesTransProp(), LTPspecies_Poly::getSpeciesTransProp(), LTPspecies_ExpT::getSpeciesTransProp(), WaterSSTP::getStandardChemPotentials(), StoichSubstanceSSTP::getStandardChemPotentials(), MineralEQ3::getStandardChemPotentials(), MetalSHEelectrons::getStandardChemPotentials(), IdealGasPhase::getStandardChemPotentials(), WaterSSTP::getStandardVolumes_ref(), IdealSolnGasVPSS::gibbs_mole(), ConstDensityThermo::gibbs_mole(), StoichSubstance::gibbs_mole(), RedlichKwongMFTP::gibbs_mole(), IdealSolidSolnPhase::gibbs_mole(), ThermoPhase::gibbs_mole(), LatticePhase::gibbs_mole(), IdealGasPhase::gibbs_mole(), RedlichKwongMFTP::hresid(), ConstDensityThermo::intEnergy_mole(), StoichSubstance::intEnergy_mole(), IdealSolidSolnPhase::intEnergy_mole(), LatticePhase::intEnergy_mole(), IdealGasPhase::intEnergy_mole(), IdealGasPhase::logStandardConc(), MixtureFugacityTP::phaseState(), RedlichKwongMFTP::pressure(), IdealGasPhase::pressure(), MixTransport::pressure_ig(), RedlichKwongMFTP::pressureDerivatives(), HMWSoln::relative_enthalpy(), PseudoBinaryVPSSTP::report(), MolarityIonicVPSSTP::report(), PureFluidPhase::report(), MolalityVPSSTP::report(), ThermoPhase::report(), PureFluidPhase::reportCSV(), MolalityVPSSTP::reportCSV(), ThermoPhase::reportCSV(), PhaseCombo_Interaction::s_update_dlnActCoeff_dlnN(), MargulesVPSSTP::s_update_dlnActCoeff_dlnN(), MixedSolventElectrolyte::s_update_dlnActCoeff_dlnN(), PhaseCombo_Interaction::s_update_dlnActCoeff_dlnN_diag(), MargulesVPSSTP::s_update_dlnActCoeff_dlnN_diag(), MixedSolventElectrolyte::s_update_dlnActCoeff_dlnN_diag(), PhaseCombo_Interaction::s_update_dlnActCoeff_dlnX_diag(), MargulesVPSSTP::s_update_dlnActCoeff_dlnX_diag(), MixedSolventElectrolyte::s_update_dlnActCoeff_dlnX_diag(), PhaseCombo_Interaction::s_update_dlnActCoeff_dT(), MargulesVPSSTP::s_update_dlnActCoeff_dT(), MixedSolventElectrolyte::s_update_dlnActCoeff_dT(), RedlichKisterVPSSTP::s_update_dlnActCoeff_dX_(), PhaseCombo_Interaction::s_update_lnActCoeff(), RedlichKisterVPSSTP::s_update_lnActCoeff(), MargulesVPSSTP::s_update_lnActCoeff(), MixedSolventElectrolyte::s_update_lnActCoeff(), HMWSoln::s_updatePitzer_CoeffWRTemp(), HMWSoln::s_updatePitzer_dlnMolalityActCoeff_dP(), HMWSoln::s_updatePitzer_lnMolalityActCoeff(), WaterSSTP::satPressure(), HMWSoln::satPressure(), Phase::saveState(), WaterSSTP::setDensity(), ThermoPhase::setElementPotentials(), ChemEquil::setInitialMoles(), PureFluidPhase::setPressure(), WaterSSTP::setPressure(), GibbsExcessVPSSTP::setPressure(), IdealMolalSoln::setPressure(), VPStandardStateTP::setPressure(), MixtureFugacityTP::setPressure(), IdealGasPhase::setPressure(), IonsFromNeutralVPSSTP::setPressure(), DebyeHuckel::setPressure(), HMWSoln::setPressure(), vcs_VolPhase::setPtrThermoPhase(), SingleSpeciesTP::setState_HP(), ThermoPhase::setState_HPorUV(), SingleSpeciesTP::setState_SP(), ThermoPhase::setState_SPorSV(), SingleSpeciesTP::setState_SV(), SingleSpeciesTP::setState_UV(), MixtureFugacityTP::setStateFromXML(), MixtureFugacityTP::setTemperature(), PureFluidPhase::setTPXState(), ImplicitSurfChem::solvePseudoSteadyStateProblem(), RedlichKwongMFTP::sresid(), IdealSolnGasVPSS::standardConcentration(), IdealGasPhase::standardConcentration(), AqueousTransport::stefan_maxwell_solve(), LiquidTransport::stefan_maxwell_solve(), SolidTransport::thermalConductivity(), MetalSHEelectrons::thermalExpansionCoeff(), IdealGasPhase::thermalExpansionCoeff(), ChemEquil::update(), MixTransport::update_T(), MultiTransport::update_T(), AqueousTransport::update_T(), SimpleTransport::update_T(), LiquidTransport::update_T(), RedlichKwongMFTP::updateAB(), AqueousKinetics::updateKc(), GasKinetics::updateKc(), InterfaceKinetics::updateKc(), VPStandardStateTP::updateStandardStateThermo(), Reactor::updateState(), MultiTransport::updateThermal_T(), DustyGasTransport::updateTransport_T(), and WaterSSTP::vaporFraction().
doublereal molarDensity () const inherited
Molar density (kmol/m^3).
Returns
The molar density of the phase
Definition at line 627 of file Phase.cpp.
References Phase::density(), and Phase::meanMolecularWeight().
Referenced by solveSP::calc_t(), SolidTransport::electricalConductivity(), ConstDensityThermo::enthalpy_mole(), StoichSubstance::enthalpy_mole(), IdealSolidSolnPhase::enthalpy_mole(), LatticePhase::enthalpy_mole(), ConstDensityThermo::getChemPotentials(), StoichSubstanceSSTP::getEnthalpy_RT(), MineralEQ3::getEnthalpy_RT(), StoichSubstanceSSTP::getIntEnergy_RT(), MineralEQ3::getIntEnergy_RT(), StoichSubstanceSSTP::getIntEnergy_RT_ref(), MineralEQ3::getIntEnergy_RT_ref(), MetalSHEelectrons::getIntEnergy_RT_ref(), LatticePhase::getParameters(), PureFluidPhase::getPartialMolarVolumes(), StoichSubstance::getPartialMolarVolumes(), IdealGasPhase::getPartialMolarVolumes(), MixTransport::getSpeciesFluxes(), AqueousTransport::getSpeciesFluxesExt(), SimpleTransport::getSpeciesFluxesExt(), StoichSubstance::getStandardVolumes(), IdealGasPhase::getStandardVolumes(), IdealSolnGasVPSS::intEnergy_mole(), ConstDensityThermo::intEnergy_mole(), StoichSubstance::intEnergy_mole(), RedlichKwongMFTP::intEnergy_mole(), IonsFromNeutralVPSSTP::intEnergy_mole(), IdealSolidSolnPhase::intEnergy_mole(), LatticePhase::intEnergy_mole(), DebyeHuckel::intEnergy_mole(), HMWSoln::intEnergy_mole(), ConstDensityThermo::logStandardConc(), Phase::molarVolume(), IdealGasPhase::pressure(), MixTransport::pressure_ig(), IdealMolalSoln::setMolarDensity(), DebyeHuckel::setMolarDensity(), and ConstDensityThermo::standardConcentration().
doublereal molarVolume () const inherited
Molar volume (m^3/kmol).
Returns
The molar volume of the phase
Definition at line 637 of file Phase.cpp.
References Phase::molarDensity().
Referenced by RedlichKwongMFTP::cp_mole(), HMWSoln::cv_mole(), RedlichKwongMFTP::getActivityCoefficients(), RedlichKwongMFTP::getChemPotentials(), LTI_StefanMaxwell_PPN::getMatrixTransProp(), RedlichKwongMFTP::getPartialMolarEnthalpies(), RedlichKwongMFTP::getPartialMolarEntropies(), RedlichKwongMFTP::getPartialMolarVolumes(), ThermoPhase::intEnergy_mole(), RedlichKwongMFTP::pressureDerivatives(), MixtureFugacityTP::setState_TR(), and LiquidTransport::stefan_maxwell_solve().
doublereal mean_X (const doublereal *const Q) const inherited
Evaluate the mole-fraction-weighted mean of an array Q.
\[ \sum_k X_k Q_k. \]
Q should contain pure-species molar property values.
Parameters
[in] Q Array of length m_kk that is to be averaged.
Returns
mole-fraction-weighted mean of Q
Definition at line 658 of file Phase.cpp.
References Phase::m_mmw, and Phase::m_ym.
Referenced by IdealSolnGasVPSS::cp_mole(), ConstDensityThermo::cp_mole(), RedlichKwongMFTP::cp_mole(), IonsFromNeutralVPSSTP::cp_mole(), IdealSolidSolnPhase::cp_mole(), IdealMolalSoln::cp_mole(), LatticePhase::cp_mole(), IdealGasPhase::cp_mole(), DebyeHuckel::cp_mole(), HMWSoln::cp_mole(), IonsFromNeutralVPSSTP::cv_mole(), IdealSolnGasVPSS::enthalpy_mole(), ConstDensityThermo::enthalpy_mole(), RedlichKwongMFTP::enthalpy_mole(), IdealSolidSolnPhase::enthalpy_mole(), IonsFromNeutralVPSSTP::enthalpy_mole(), IdealMolalSoln::enthalpy_mole(), SurfPhase::enthalpy_mole(), LatticePhase::enthalpy_mole(), IdealGasPhase::enthalpy_mole(), DebyeHuckel::enthalpy_mole(), HMWSoln::enthalpy_mole(), IdealSolnGasVPSS::entropy_mole(), ConstDensityThermo::entropy_mole(), RedlichKwongMFTP::entropy_mole(), IonsFromNeutralVPSSTP::entropy_mole(), IdealSolidSolnPhase::entropy_mole(), IdealMolalSoln::entropy_mole(), LatticePhase::entropy_mole(), IdealGasPhase::entropy_mole(), DebyeHuckel::entropy_mole(), HMWSoln::entropy_mole(), IonsFromNeutralVPSSTP::gibbs_mole(), IdealSolidSolnPhase::gibbs_mole(), IdealMolalSoln::gibbs_mole(), DebyeHuckel::gibbs_mole(), HMWSoln::gibbs_mole(), ConstDensityThermo::intEnergy_mole(), IdealSolidSolnPhase::intEnergy_mole(), IdealMolalSoln::intEnergy_mole(), LatticePhase::intEnergy_mole(), IdealGasPhase::intEnergy_mole(), and HMWSoln::relative_enthalpy().
doublereal mean_Y (const doublereal *const Q) const inherited
Evaluate the mass-fraction-weighted mean of an array Q.
\[ \sum_k Y_k Q_k \]
Parameters
[in] Q Array of species property values in mass units.
Returns
The mass-fraction-weighted mean of Q.
Definition at line 663 of file Phase.cpp.
References Cantera::dot(), and Phase::m_y.
doublereal meanMolecularWeight () const inline inherited
The mean molecular weight. Units: (kg/kmol)
Definition at line 592 of file Phase.h.
References Phase::m_mmw.
Referenced by IdealSolnGasVPSS::calcDensity(), GibbsExcessVPSSTP::calcDensity(), IdealMolalSoln::calcDensity(), LatticePhase::calcDensity(), DebyeHuckel::calcDensity(), HMWSoln::calcDensity(), MixtureFugacityTP::calculatePsat(), ThermoPhase::cp_mass(), RedlichKwongMFTP::critDensity(), ThermoPhase::cv_mass(), RedlichKwongMFTP::densityCalc(), MixtureFugacityTP::densityCalc(), RedlichKwongMFTP::densSpinodalGas(), RedlichKwongMFTP::densSpinodalLiquid(), ThermoPhase::enthalpy_mass(), ThermoPhase::entropy_mass(), IdealSolidSolnPhase::getActivityConcentrations(), GasTransport::getMixDiffCoeffs(), AqueousTransport::getMixDiffCoeffs(), GasTransport::getMixDiffCoeffsMass(), MultiTransport::getMultiDiffCoeffs(), WaterSSTP::getStandardVolumes_ref(), ThermoPhase::gibbs_mass(), RedlichKwongMFTP::hresid(), ThermoPhase::intEnergy_mass(), Phase::molarDensity(), MixtureFugacityTP::phaseState(), RedlichKwongMFTP::pressure(), PseudoBinaryVPSSTP::report(), MolarityIonicVPSSTP::report(), PureFluidPhase::report(), MolalityVPSSTP::report(), ThermoPhase::report(), PureFluidPhase::reportCSV(), MolalityVPSSTP::reportCSV(), ThermoPhase::reportCSV(), Phase::setMolarDensity(), IdealGasPhase::setPressure(), RedlichKwongMFTP::sresid(), SimpleTransport::update_C(), LiquidTransport::update_C(), StFlow::updateThermo(), StFlow::updateTransport(), and MixtureFugacityTP::z().
doublereal sum_xlogx () const inherited
Evaluate \(\sum_k X_k \log X_k \).
Returns
The indicated sum. Dimensionless.
Definition at line 668 of file Phase.cpp.
References Phase::m_mmw, Phase::m_ym, and Cantera::sum_xlogx().
Referenced by IdealSolnGasVPSS::entropy_mole(), ConstDensityThermo::entropy_mole(), RedlichKwongMFTP::entropy_mole(), IdealSolidSolnPhase::entropy_mole(), LatticePhase::entropy_mole(), IdealGasPhase::entropy_mole(), and IdealSolidSolnPhase::gibbs_mole().
doublereal sum_xlogQ (doublereal *const Q) const inherited
Evaluate \(\sum_k X_k \log Q_k \).
Parameters
Q Vector of length m_kk to take the log average of
Returns
The indicated sum.
Definition at line 673 of file Phase.cpp.
References Phase::m_mmw, Phase::m_ym, and Cantera::sum_xlogQ().
void addElement (const std::string & symbol, doublereal weight = -12345.0) inherited
Add an element.
Parameters
symbol Atomic symbol std::string.
weight Atomic mass in amu.
Definition at line 678 of file Phase.cpp.
References CT_ELEM_TYPE_ABSPOS, CT_ELEM_TYPE_ELECTRONCHARGE, Cantera::LookupWtElements(), Phase::m_atomicWeights, Phase::m_elem_type, Phase::m_elementNames, Phase::m_elementsFrozen, and Phase::m_mm.
Referenced by Phase::addElement().
void addElement (const XML_Node & e) inherited
Add an element from an XML specification.
Parameters
e Reference to the XML_Node where the element is described.
Definition at line 701 of file Phase.cpp.
References Phase::addElement().
void addUniqueElement (const std::string & symbol, doublereal weight = -12345.0, int atomicNumber = 0, doublereal entropy298 = ENTROPY298_UNKNOWN, int elem_type = CT_ELEM_TYPE_ABSPOS) inherited
Add an element, checking for uniqueness The uniqueness is checked by comparing the string symbol.
If not unique, nothing is done.
Parameters
symbol String symbol of the element
weight Atomic weight of the element (kg kmol-1).
atomicNumber Atomic number of the element (unitless)
entropy298 Entropy of the element at 298 K and 1 bar in its most stable form. The default is the value ENTROPY298_UNKNOWN, which is interpreted as an unknown, and if used will cause Cantera to throw an error.
elem_type Specifies the type of the element constraint equation. This defaults to CT_ELEM_TYPE_ABSPOS, i.e., an element.
Definition at line 708 of file Phase.cpp.
References CT_ELEM_TYPE_ELECTRONCHARGE, Cantera::LookupWtElements(), Phase::m_atomicNumbers, Phase::m_atomicWeights, Phase::m_elem_type, Phase::m_elementNames, Phase::m_elementsFrozen, Phase::m_entropy298, and Phase::m_mm.
Referenced by Phase::addElementsFromXML(), Phase::addUniqueElement(), Phase::addUniqueElementAfterFreeze(), and FixedChemPotSSTP::FixedChemPotSSTP().
void addUniqueElement (const XML_Node & e) inherited
Add an element, checking for uniqueness The uniqueness is checked by comparing the string symbol.
If not unique, nothing is done.
Parameters
e Reference to the XML_Node where the element is described.
Definition at line 755 of file Phase.cpp.
References Phase::addUniqueElement(), Cantera::atofCheck(), XML_Node::child(), ENTROPY298_UNKNOWN, XML_Node::hasAttrib(), XML_Node::hasChild(), and Cantera::stripws().
void addElementsFromXML (const XML_Node & phase) inherited
Add all elements referenced in an XML_Node tree.
Parameters
phase Reference to the root XML_Node of a phase
Definition at line 780 of file Phase.cpp.
References Phase::addUniqueElement(), XML_Node::child(), XML_Node::findByAttr(), Cantera::get_XML_File(), ctml::getStringArray(), XML_Node::hasAttrib(), XML_Node::hasChild(), and XML_Node::root().
Referenced by Cantera::importPhase().
void freezeElements () inherited
Prohibit addition of more elements, and prepare to add species.
Definition at line 831 of file Phase.cpp.
References Phase::m_elementsFrozen.
Referenced by FixedChemPotSSTP::FixedChemPotSSTP().
bool elementsFrozen () inherited
True if freezeElements has been called.
Definition at line 836 of file Phase.cpp.
References Phase::m_elementsFrozen.
size_t addUniqueElementAfterFreeze (const std::string & symbol, doublereal weight, int atomicNumber, doublereal entropy298 = ENTROPY298_UNKNOWN, int elem_type = CT_ELEM_TYPE_ABSPOS) inherited
Add an element after elements have been frozen, checking for uniqueness The uniqueness is checked by comparing the string symbol.
If not unique, nothing is done.
Parameters
symbol String symbol of the element
weight Atomic weight of the element (kg kmol-1).
atomicNumber Atomic number of the element (unitless)
entropy298 Entropy of the element at 298 K and 1 bar in its most stable form. The default is the value ENTROPY298_UNKNOWN, which if used will cause Cantera to throw an error.
elem_type Specifies the type of the element constraint equation. This defaults to CT_ELEM_TYPE_ABSPOS, i.e., an element.
Definition at line 841 of file Phase.cpp.
References Phase::addUniqueElement(), Phase::elementIndex(), Phase::m_elementsFrozen, Phase::m_kk, Phase::m_mm, Phase::m_speciesComp, and Cantera::npos.
Referenced by LatticeSolidPhase::installSlavePhases().
void addUniqueSpecies (const std::string & name, const doublereal * comp, doublereal charge = 0.0, doublereal size = 1.0) inherited
Add a species to the phase, checking for uniqueness of the name This routine checks for uniqueness of the string name.
It only adds the species if it is unique.
Parameters
name String name of the species
comp Array containing the elemental composition of the species.
charge Charge of the species. Defaults to zero.
size Size of the species (meters). Defaults to 1 meter.
Definition at line 919 of file Phase.cpp.
References Phase::m_kk, Phase::m_mm, Phase::m_speciesCharge, Phase::m_speciesComp, Phase::m_speciesNames, and Phase::m_speciesSize.
Referenced by FixedChemPotSSTP::FixedChemPotSSTP(), LatticeSolidPhase::installSlavePhases(), and Cantera::installSpecies().
void freezeSpecies () virtual inherited
Call when finished adding species.
Prepare to use them for calculation of mixture properties.
Definition at line 952 of file Phase.cpp.
References Phase::init(), Phase::m_speciesFrozen, and Phase::molecularWeights().
Referenced by FixedChemPotSSTP::FixedChemPotSSTP(), and Cantera::importPhase().
bool speciesFrozen () inline inherited
True if freezeSpecies has been called.
Definition at line 694 of file Phase.h.
References Phase::m_speciesFrozen.
int stateMFNumber () const inline inherited
Return the State Mole Fraction Number.
Definition at line 701 of file Phase.h.
References Phase::m_stateNum.
Referenced by SimpleTransport::update_C(), and LiquidTransport::update_C().
void stateMFChangeCalc (bool forceChange = false) inline inherited
Every time the mole fractions have changed, this routine will increment the stateMFNumber.
@param forceChange If this is true then the stateMFNumber always
changes. This defaults to false.
Deprecated:
Definition at line 115 of file Phase.cpp.
References Phase::m_stateNum.
Referenced by Phase::setConcentrations(), Phase::setMassFractions(), Phase::setMassFractions_NoNorm(), Phase::setMoleFractions(), and Phase::setMoleFractions_NoNorm().
void init (const vector_fp & mw) protected inherited
Initialize. Make a local copy of the vector of molecular weights, and resize the composition arrays to the appropriate size.
Parameters
mw Vector of molecular weights of the species.
Definition at line 958 of file Phase.cpp.
References Cantera::int2str(), Phase::m_kk, Phase::m_mmw, Phase::m_molwts, Phase::m_rmolwts, Phase::m_y, Phase::m_ym, and Cantera::Tiny.
Referenced by Phase::freezeSpecies().
void setMolecularWeight (const int k, const double mw) inline protected inherited
Set the molecular weight of a single species to a given value.
Parameters
k id of the species
mw Molecular Weight (kg kmol-1)
Definition at line 722 of file Phase.h.
References Phase::m_molwts, and Phase::m_rmolwts.
Referenced by PureFluidPhase::initThermo(), and WaterSSTP::initThermoXML().
Member Data Documentation
int m_formPitzer private
This is the form of the Pitzer parameterization used in this model.
The options are described at the top of this document, and in the general documentation. The list is repeated here:
PITZERFORM_BASE = 0 (only one supported atm)
Definition at line 2379 of file HMWSoln.h.
Referenced by HMWSoln::formPitzer(), and HMWSoln::operator=().
int m_formPitzerTemp private
This is the form of the temperature dependence of Pitzer parameterization used in the model.
PITZER_TEMP_CONSTANT 0 PITZER_TEMP_LINEAR 1 PITZER_TEMP_COMPLEX1 2
Definition at line 2389 of file HMWSoln.h.
Referenced by HMWSoln::initLengths(), HMWSoln::operator=(), and HMWSoln::s_updatePitzer_CoeffWRTemp().
int m_formGC private
Format for the generalized concentration:
0 = unity 1 = molar_volume 2 = solvent_volume (default)
The generalized concentrations can have three different forms depending on the value of the member attribute m_formGC, which is supplied in the constructor.
m_formGC GeneralizedConc StandardConc
0 X_k 1.0
1 X_k / V_k 1.0 / V_k
2 X_k / V_N 1.0 / V_N
The value and form of the generalized concentration will affect reaction rate constants involving species in this phase.
(HKM Note: Using option #1 may lead to spurious results and has been included only with warnings. The reason is that it molar volumes of electrolytes may often be negative. The molar volume of H+ is defined to be zero too. Either options 0 or 2 are the appropriate choice. Option 0 leads to bulk reaction rate constants which have units of s-1. Option 2 leads to bulk reaction rate constants for bimolecular rxns which have units of m-3 kmol-1 s-1.)
Definition at line 2420 of file HMWSoln.h.
Referenced by HMWSoln::eosType(), and HMWSoln::operator=().
vector_int m_electrolyteSpeciesType private
Vector containing the electrolyte species type.
The possible types are:
solvent
Charged Species
weakAcidAssociated
strongAcidAssociated
polarNeutral
nonpolarNeutral .
Definition at line 2432 of file HMWSoln.h.
Referenced by HMWSoln::initLengths().
vector_fp m_Aionic private
a_k = Size of the ionic species in the DH formulation units = meters
Definition at line 2438 of file HMWSoln.h.
Referenced by HMWSoln::AionicRadius(), HMWSoln::initLengths(), and HMWSoln::operator=().
double m_IionicMolality mutable private
Current value of the ionic strength on the molality scale Associated Salts, if present in the mechanism, don't contribute to the value of the ionic strength in this version of the Ionic strength.
Definition at line 2446 of file HMWSoln.h.
Referenced by HMWSoln::operator=(), HMWSoln::s_NBS_CLM_d2lnMolalityActCoeff_dT2(), HMWSoln::s_NBS_CLM_dlnMolalityActCoeff_dP(), HMWSoln::s_NBS_CLM_dlnMolalityActCoeff_dT(), HMWSoln::s_NBS_CLM_lnMolalityActCoeff(), HMWSoln::s_updatePitzer_d2lnMolalityActCoeff_dT2(), HMWSoln::s_updatePitzer_dlnMolalityActCoeff_dP(), HMWSoln::s_updatePitzer_dlnMolalityActCoeff_dT(), and HMWSoln::s_updatePitzer_lnMolalityActCoeff().
double m_maxIionicStrength private
Maximum value of the ionic strength allowed in the calculation of the activity coefficients.
Definition at line 2452 of file HMWSoln.h.
Referenced by HMWSoln::calcMolalitiesCropped(), and HMWSoln::operator=().
double m_TempPitzerRef private
Reference Temperature for the Pitzer formulations.
Definition at line 2457 of file HMWSoln.h.
Referenced by HMWSoln::operator=(), and HMWSoln::s_updatePitzer_CoeffWRTemp().
double m_IionicMolalityStoich mutable private
Stoichiometric ionic strength on the molality scale.
This differs from m_IionicMolality in the sense that associated salts are treated as unassociated salts, when calculating the Ionic strength by this method.
Definition at line 2465 of file HMWSoln.h.
Referenced by HMWSoln::operator=(), and HMWSoln::s_update_lnMolalityActCoeff().
int m_form_A_Debye
Form of the constant outside the Debye-Huckel term called A.
It's normally a function of temperature and pressure. However, it can be set from the input file in order to aid in numerical comparisons. Acceptable forms:
  A_DEBYE_CONST  0
  A_DEBYE_WATER  1
The A_DEBYE_WATER form may be used for water solvents with needs to cover varying temperatures and pressures. Note, the dielectric constant of water is a relatively strong function of T, and its variability must be accounted for,
Definition at line 2484 of file HMWSoln.h.
Referenced by HMWSoln::A_Debye_TP(), HMWSoln::d2A_DebyedT2_TP(), HMWSoln::dA_DebyedP_TP(), HMWSoln::dA_DebyedT_TP(), and HMWSoln::operator=().
double m_A_Debye mutable private
A_Debye -> this expression appears on the top of the ln actCoeff term in the general Debye-Huckel expression It depends on temperature.
And, therefore, most be recalculated whenever T or P changes. This variable is a local copy of the calculation.
A_Debye = (F e B_Debye) / (8 Pi epsilon R T)
 where B_Debye = F / sqrt(epsilon R T/2)
                 (dw/1000)^(1/2)
A_Debye = (1/ (8 Pi)) (2 Na * dw/1000)^(1/2) (e * e / (epsilon * kb * T))^(3/2)
Units = sqrt(kg/gmol)
Nominal value = 1.172576 sqrt(kg/gmol) based on: epsilon/epsilon_0 = 78.54 (water at 25C) epsilon_0 = 8.854187817E-12 C2 N-1 m-2 e = 1.60217653 E-19 C F = 9.6485309E7 C kmol-1 R = 8.314472E3 kg m2 s-2 kmol-1 K-1 T = 298.15 K B_Debye = 3.28640E9 sqrt(kg/gmol)/m dw = C_0 * M_0 (density of water) (kg/m3) = 1.0E3 at 25C
Definition at line 2518 of file HMWSoln.h.
Referenced by HMWSoln::A_Debye_TP(), HMWSoln::operator=(), HMWSoln::s_NBS_CLM_lnMolalityActCoeff(), and HMWSoln::s_updatePitzer_lnMolalityActCoeff().
PDSS* m_waterSS private
Water standard state calculator.
derived from the equation of state for water.
Definition at line 2524 of file HMWSoln.h.
Referenced by HMWSoln::operator=(), HMWSoln::satPressure(), HMWSoln::setState_TP(), and HMWSoln::speciesMolarVolume().
double m_densWaterSS private
density of standard-state water
internal temporary variable
Definition at line 2530 of file HMWSoln.h.
Referenced by HMWSoln::operator=(), and HMWSoln::setState_TP().
WaterProps* m_waterProps private
Pointer to the water property calculator.
Definition at line 2535 of file HMWSoln.h.
Referenced by HMWSoln::A_Debye_TP(), HMWSoln::d2A_DebyedT2_TP(), HMWSoln::dA_DebyedP_TP(), HMWSoln::dA_DebyedT_TP(), HMWSoln::operator=(), and HMWSoln::~HMWSoln().
vector_fp m_expg0_RT mutable private
Vector containing the species reference exp(-G/RT) functions at T = m_tlast.
Definition at line 2541 of file HMWSoln.h.
Referenced by HMWSoln::initLengths(), and HMWSoln::operator=().
vector_fp m_pe mutable private
Vector of potential energies for the species.
Definition at line 2546 of file HMWSoln.h.
Referenced by HMWSoln::initLengths(), and HMWSoln::operator=().
vector_fp m_pp mutable private
Temporary array used in equilibrium calculations.
Definition at line 2551 of file HMWSoln.h.
Referenced by HMWSoln::calcDensity(), HMWSoln::enthalpy_mole(), HMWSoln::initLengths(), and HMWSoln::operator=().
vector_fp m_tmpV mutable private
vector of size m_kk, used as a temporary holding area.
Definition at line 2556 of file HMWSoln.h.
Referenced by HMWSoln::calcDensity(), HMWSoln::cp_mole(), HMWSoln::enthalpy_mole(), HMWSoln::entropy_mole(), HMWSoln::gibbs_mole(), HMWSoln::initLengths(), HMWSoln::operator=(), HMWSoln::printCoeffs(), HMWSoln::relative_enthalpy(), HMWSoln::relative_molal_enthalpy(), and HMWSoln::standardConcentration().
vector_fp m_speciesCharge_Stoich private
Stoichiometric species charge -> This is for calculations of the ionic strength which ignore ion-ion pairing into neutral molecules.
The Stoichiometric species charge is the charge of one of the ion that would occur if the species broke into two charged ion pairs. NaCl -> m_speciesCharge_Stoich = -1; HSO4- -> H+ + SO42- = -2 -> The other charge is calculated. For species that aren't ion pairs, its equal to the m_speciesCharge[] value.
Definition at line 2570 of file HMWSoln.h.
Referenced by HMWSoln::initLengths(), HMWSoln::operator=(), and HMWSoln::s_update_lnMolalityActCoeff().
vector_fp m_Beta0MX_ij mutable private
Array of 2D data used in the Pitzer/HMW formulation.
Beta0_ij[i][j] is the value of the Beta0 coefficient for the ij salt. It will be nonzero iff i and j are both charged and have opposite sign. The array is also symmetric. counterIJ where counterIJ = m_counterIJ[i][j] is used to access this array.
Definition at line 2581 of file HMWSoln.h.
Referenced by HMWSoln::HMWSoln(), HMWSoln::initLengths(), HMWSoln::operator=(), HMWSoln::printCoeffs(), HMWSoln::s_updatePitzer_CoeffWRTemp(), and HMWSoln::s_updatePitzer_lnMolalityActCoeff().
vector_fp m_Beta0MX_ij_L mutable private
Derivative of Beta0_ij[i][j] wrt T.
vector index is counterIJ
Definition at line 2587 of file HMWSoln.h.
Referenced by HMWSoln::initLengths(), HMWSoln::operator=(), HMWSoln::s_updatePitzer_CoeffWRTemp(), and HMWSoln::s_updatePitzer_dlnMolalityActCoeff_dT().
vector_fp m_Beta0MX_ij_LL mutable private
Derivative of Beta0_ij[i][j] wrt TT.
vector index is counterIJ
Definition at line 2593 of file HMWSoln.h.
Referenced by HMWSoln::initLengths(), HMWSoln::operator=(), HMWSoln::s_updatePitzer_CoeffWRTemp(), and HMWSoln::s_updatePitzer_d2lnMolalityActCoeff_dT2().
vector_fp m_Beta0MX_ij_P mutable private
Derivative of Beta0_ij[i][j] wrt P.
vector index is counterIJ
Definition at line 2599 of file HMWSoln.h.
Referenced by HMWSoln::initLengths(), HMWSoln::operator=(), and HMWSoln::s_updatePitzer_dlnMolalityActCoeff_dP().
Array2D m_Beta0MX_ij_coeff mutable private
Array of coefficients for Beta0, a variable in Pitzer's papers.
column index is counterIJ m_Beta0MX_ij_coeff.ptrColumn(counterIJ) is a double* containing the vector of coefficients for the counterIJ interaction.
Definition at line 2607 of file HMWSoln.h.
Referenced by HMWSoln::initLengths(), HMWSoln::operator=(), and HMWSoln::s_updatePitzer_CoeffWRTemp().
vector_fp m_Beta1MX_ij mutable private
Array of 2D data used in the Pitzer/HMW formulation. Beta1_ij[i][j] is the value of the Beta1 coefficient for the ij salt. It will be nonzero iff i and j are both charged and have opposite sign. The array is also symmetric. counterIJ where counterIJ = m_counterIJ[i][j] is used to access this array.
Definition at line 2618 of file HMWSoln.h.
Referenced by HMWSoln::HMWSoln(), HMWSoln::initLengths(), HMWSoln::operator=(), HMWSoln::printCoeffs(), HMWSoln::s_updatePitzer_CoeffWRTemp(), and HMWSoln::s_updatePitzer_lnMolalityActCoeff().
vector_fp m_Beta1MX_ij_L mutable private
Derivative of Beta1_ij[i][j] wrt T.
vector index is counterIJ
Definition at line 2624 of file HMWSoln.h.
Referenced by HMWSoln::initLengths(), HMWSoln::operator=(), HMWSoln::s_updatePitzer_CoeffWRTemp(), and HMWSoln::s_updatePitzer_dlnMolalityActCoeff_dT().
vector_fp m_Beta1MX_ij_LL mutable private
Derivative of Beta1_ij[i][j] wrt TT.
vector index is counterIJ
Definition at line 2630 of file HMWSoln.h.
Referenced by HMWSoln::initLengths(), HMWSoln::operator=(), HMWSoln::s_updatePitzer_CoeffWRTemp(), and HMWSoln::s_updatePitzer_d2lnMolalityActCoeff_dT2().
vector_fp m_Beta1MX_ij_P mutable private
Derivative of Beta1_ij[i][j] wrt P.
vector index is counterIJ
Definition at line 2636 of file HMWSoln.h.
Referenced by HMWSoln::initLengths(), HMWSoln::operator=(), and HMWSoln::s_updatePitzer_dlnMolalityActCoeff_dP().
Array2D m_Beta1MX_ij_coeff mutable private
Array of coefficients for Beta1, a variable in Pitzer's papers.
column index is counterIJ m_Beta1MX_ij_coeff.ptrColumn(counterIJ) is a double* containing the vector of coefficients for the counterIJ interaction.
Definition at line 2644 of file HMWSoln.h.
Referenced by HMWSoln::initLengths(), HMWSoln::operator=(), and HMWSoln::s_updatePitzer_CoeffWRTemp().
vector_fp m_Beta2MX_ij mutable private
Array of 2D data used in the Pitzer/HMW formulation.
Beta2_ij[i][j] is the value of the Beta2 coefficient for the ij salt. It will be nonzero iff i and j are both charged and have opposite sign, and i and j both have charges of 2 or more. The array is also symmetric. counterIJ where counterIJ = m_counterIJ[i][j] is used to access this array.
Definition at line 2656 of file HMWSoln.h.
Referenced by HMWSoln::initLengths(), HMWSoln::operator=(), HMWSoln::printCoeffs(), HMWSoln::s_updatePitzer_CoeffWRTemp(), and HMWSoln::s_updatePitzer_lnMolalityActCoeff().
vector_fp m_Beta2MX_ij_L mutable private
Derivative of Beta2_ij[i][j] wrt T.
vector index is counterIJ
Definition at line 2662 of file HMWSoln.h.
Referenced by HMWSoln::initLengths(), HMWSoln::operator=(), HMWSoln::s_updatePitzer_CoeffWRTemp(), and HMWSoln::s_updatePitzer_dlnMolalityActCoeff_dT().
vector_fp m_Beta2MX_ij_LL mutable private
Derivative of Beta2_ij[i][j] wrt TT.
vector index is counterIJ
Definition at line 2668 of file HMWSoln.h.
Referenced by HMWSoln::initLengths(), HMWSoln::operator=(), HMWSoln::s_updatePitzer_CoeffWRTemp(), and HMWSoln::s_updatePitzer_d2lnMolalityActCoeff_dT2().
vector_fp m_Beta2MX_ij_P mutable private
Derivative of Beta2_ij[i][j] wrt P.
vector index is counterIJ
Definition at line 2674 of file HMWSoln.h.
Referenced by HMWSoln::initLengths(), HMWSoln::operator=(), and HMWSoln::s_updatePitzer_dlnMolalityActCoeff_dP().
Array2D m_Beta2MX_ij_coeff mutable private
Array of coefficients for Beta2, a variable in Pitzer's papers.
column index is counterIJ m_Beta2MX_ij_coeff.ptrColumn(counterIJ) is a double* containing the vector of coefficients for the counterIJ interaction. This was added for the YMP database version of the code since it contains temperature-dependent parameters for some 2-2 electrolytes.
Definition at line 2684 of file HMWSoln.h.
Referenced by HMWSoln::initLengths(), HMWSoln::operator=(), and HMWSoln::s_updatePitzer_CoeffWRTemp().
vector_fp m_Alpha1MX_ij private
Array of 2D data used in the Pitzer/HMW formulation.
Alpha1MX_ij[i][j] is the value of the alpha1 coefficient for the ij interaction. It will be nonzero iff i and j are both charged and have opposite sign. It is symmetric wrt i, j. counterIJ where counterIJ = m_counterIJ[i][j] is used to access this array.
Definition at line 2695 of file HMWSoln.h.
Referenced by HMWSoln::HMWSoln(), HMWSoln::initLengths(), HMWSoln::operator=(), HMWSoln::printCoeffs(), HMWSoln::s_updatePitzer_d2lnMolalityActCoeff_dT2(), HMWSoln::s_updatePitzer_dlnMolalityActCoeff_dP(), HMWSoln::s_updatePitzer_dlnMolalityActCoeff_dT(), and HMWSoln::s_updatePitzer_lnMolalityActCoeff().
vector_fp m_Alpha2MX_ij private
Array of 2D data used in the Pitzer/HMW formulation.
Alpha2MX_ij[i][j] is the value of the alpha2 coefficient for the ij interaction. It will be nonzero iff i and j are both charged and have opposite sign, and i and j both have charges of 2 or more, usually. It is symmetric wrt i, j. counterIJ, where counterIJ = m_counterIJ[i][j], is used to access this array.
Definition at line 2707 of file HMWSoln.h.
Referenced by HMWSoln::initLengths(), HMWSoln::operator=(), HMWSoln::s_updatePitzer_d2lnMolalityActCoeff_dT2(), HMWSoln::s_updatePitzer_dlnMolalityActCoeff_dP(), HMWSoln::s_updatePitzer_dlnMolalityActCoeff_dT(), and HMWSoln::s_updatePitzer_lnMolalityActCoeff().
vector_fp m_CphiMX_ij mutable private
Array of 2D data used in the Pitzer/HMW formulation.
CphiMX_ij[i][j] is the value of the Cphi coefficient for the ij interaction. It will be nonzero iff i and j are both charged and have opposite sign, and i and j both have charges of 2 or more. The array is also symmetric. counterIJ where counterIJ = m_counterIJ[i][j] is used to access this array.
Definition at line 2719 of file HMWSoln.h.
Referenced by HMWSoln::HMWSoln(), HMWSoln::initLengths(), HMWSoln::operator=(), HMWSoln::printCoeffs(), HMWSoln::s_updatePitzer_CoeffWRTemp(), and HMWSoln::s_updatePitzer_lnMolalityActCoeff().
vector_fp m_CphiMX_ij_L mutable private
Derivative of Cphi_ij[i][j] wrt T.
vector index is counterIJ
Definition at line 2725 of file HMWSoln.h.
Referenced by HMWSoln::initLengths(), HMWSoln::operator=(), HMWSoln::s_updatePitzer_CoeffWRTemp(), and HMWSoln::s_updatePitzer_dlnMolalityActCoeff_dT().
vector_fp m_CphiMX_ij_LL mutable private
Derivative of Cphi_ij[i][j] wrt TT.
vector index is counterIJ
Definition at line 2731 of file HMWSoln.h.
Referenced by HMWSoln::initLengths(), HMWSoln::operator=(), HMWSoln::s_updatePitzer_CoeffWRTemp(), and HMWSoln::s_updatePitzer_d2lnMolalityActCoeff_dT2().
vector_fp m_CphiMX_ij_P mutable private
Derivative of Cphi_ij[i][j] wrt P.
vector index is counterIJ
Definition at line 2737 of file HMWSoln.h.
Referenced by HMWSoln::initLengths(), HMWSoln::operator=(), and HMWSoln::s_updatePitzer_dlnMolalityActCoeff_dP().
Array2D m_CphiMX_ij_coeff mutable private
Array of coefficients for CphiMX, a parameter in the activity coefficient formulation.
Column index is counterIJ m_CphiMX_ij_coeff.ptrColumn(counterIJ) is a double* containing the vector of coefficients for the counterIJ interaction.
Definition at line 2746 of file HMWSoln.h.
Referenced by HMWSoln::initLengths(), HMWSoln::operator=(), and HMWSoln::s_updatePitzer_CoeffWRTemp().
vector_fp m_Theta_ij mutable private
Array of 2D data for Theta_ij[i][j] in the Pitzer/HMW formulation.
Array of 2D data used in the Pitzer/HMW formulation. Theta_ij[i][j] is the value of the theta coefficient for the ij interaction. It will be nonzero for charged ions with the same sign. It is symmetric. counterIJ where counterIJ = m_counterIJ[i][j] is used to access this array.
HKM Recent Pitzer papers have used a functional form for Theta_ij, which depends on the ionic strength.
Definition at line 2760 of file HMWSoln.h.
Referenced by HMWSoln::HMWSoln(), HMWSoln::initLengths(), HMWSoln::operator=(), HMWSoln::printCoeffs(), HMWSoln::s_updatePitzer_CoeffWRTemp(), and HMWSoln::s_updatePitzer_lnMolalityActCoeff().
vector_fp m_Theta_ij_L mutable private
Derivative of Theta_ij[i][j] wrt T.
vector index is counterIJ
Definition at line 2766 of file HMWSoln.h.
Referenced by HMWSoln::initLengths(), HMWSoln::operator=(), HMWSoln::s_updatePitzer_CoeffWRTemp(), and HMWSoln::s_updatePitzer_dlnMolalityActCoeff_dT().
vector_fp m_Theta_ij_LL mutable private
Derivative of Theta_ij[i][j] wrt TT.
vector index is counterIJ
Definition at line 2772 of file HMWSoln.h.
Referenced by HMWSoln::initLengths(), HMWSoln::operator=(), HMWSoln::s_updatePitzer_CoeffWRTemp(), and HMWSoln::s_updatePitzer_d2lnMolalityActCoeff_dT2().
vector_fp m_Theta_ij_P mutable private
Derivative of Theta_ij[i][j] wrt P.
vector index is counterIJ
Definition at line 2778 of file HMWSoln.h.
Referenced by HMWSoln::initLengths(), HMWSoln::operator=(), and HMWSoln::s_updatePitzer_dlnMolalityActCoeff_dP().
Array2D m_Theta_ij_coeff private
Array of coefficients for Theta_ij[i][j] in the Pitzer/HMW formulation.
Theta_ij[i][j] is the value of the theta coefficient for the ij interaction. It will be nonzero for charged ions with the same sign. It is symmetric. Column index is counterIJ. counterIJ where counterIJ = m_counterIJ[i][j] is used to access this array.
m_Theta_ij_coeff.ptrColumn(counterIJ) is a double* containing the vector of coefficients for the counterIJ interaction.
Definition at line 2792 of file HMWSoln.h.
Referenced by HMWSoln::initLengths(), HMWSoln::operator=(), and HMWSoln::s_updatePitzer_CoeffWRTemp().
vector_fp m_Psi_ijk mutable private
Array of 3D data used in the Pitzer/HMW formulation.
Psi_ijk[n] is the value of the psi coefficient for the ijk interaction where
n = k + j * m_kk + i * m_kk * m_kk;
It is potentially nonzero everywhere. The first two coordinates are symmetric wrt cations, and the last two coordinates are symmetric wrt anions.
Definition at line 2805 of file HMWSoln.h.
Referenced by HMWSoln::HMWSoln(), HMWSoln::initLengths(), HMWSoln::operator=(), HMWSoln::printCoeffs(), HMWSoln::s_updatePitzer_CoeffWRTemp(), and HMWSoln::s_updatePitzer_lnMolalityActCoeff().
vector_fp m_Psi_ijk_L mutable private
Derivative of Psi_ijk[n] wrt T.
see m_Psi_ijk for reference on the indexing into this variable.
Definition at line 2811 of file HMWSoln.h.
Referenced by HMWSoln::initLengths(), HMWSoln::operator=(), HMWSoln::s_updatePitzer_CoeffWRTemp(), and HMWSoln::s_updatePitzer_dlnMolalityActCoeff_dT().
vector_fp m_Psi_ijk_LL mutable private
Derivative of Psi_ijk[n] wrt TT.
see m_Psi_ijk for reference on the indexing into this variable.
Definition at line 2817 of file HMWSoln.h.
Referenced by HMWSoln::initLengths(), HMWSoln::operator=(), HMWSoln::s_updatePitzer_CoeffWRTemp(), and HMWSoln::s_updatePitzer_d2lnMolalityActCoeff_dT2().
vector_fp m_Psi_ijk_P mutable private
Derivative of Psi_ijk[n] wrt P.
see m_Psi_ijk for reference on the indexing into this variable.
Definition at line 2823 of file HMWSoln.h.
Referenced by HMWSoln::initLengths(), HMWSoln::operator=(), and HMWSoln::s_updatePitzer_dlnMolalityActCoeff_dP().
Array2D m_Psi_ijk_coeff private
Array of coefficients for Psi_ijk[n] in the Pitzer/HMW formulation.
Psi_ijk[n] is the value of the psi coefficient for the ijk interaction where
n = k + j * m_kk + i * m_kk * m_kk;
It is potentially nonzero everywhere. The first two coordinates are symmetric wrt cations, and the last two coordinates are symmetric wrt anions.
m_Psi_ijk_coeff.ptrColumn(n) is a double* containing the vector of coefficients for the n interaction.
Definition at line 2840 of file HMWSoln.h.
Referenced by HMWSoln::HMWSoln(), HMWSoln::initLengths(), HMWSoln::operator=(), and HMWSoln::s_updatePitzer_CoeffWRTemp().
Array2D m_Lambda_nj mutable private
Lambda coefficient for the ij interaction.
Array of 2D data used in the Pitzer/HMW formulation. Lambda_nj[n][j] represents the lambda coefficient for the ij interaction. This is a general interaction representing neutral species. The neutral species occupy the first index, i.e., n. The charged species occupy the j coordinate. neutral, neutral interactions are also included here.
Definition at line 2851 of file HMWSoln.h.
Referenced by HMWSoln::initLengths(), HMWSoln::operator=(), HMWSoln::s_updatePitzer_CoeffWRTemp(), and HMWSoln::s_updatePitzer_lnMolalityActCoeff().
Array2D m_Lambda_nj_L mutable private
Derivative of Lambda_nj[i][j] wrt T. see m_Lambda_ij.
Definition at line 2854 of file HMWSoln.h.
Referenced by HMWSoln::initLengths(), HMWSoln::operator=(), HMWSoln::s_updatePitzer_CoeffWRTemp(), and HMWSoln::s_updatePitzer_dlnMolalityActCoeff_dT().
Array2D m_Lambda_nj_LL mutable private
Derivative of Lambda_nj[i][j] wrt TT.
Definition at line 2857 of file HMWSoln.h.
Referenced by HMWSoln::initLengths(), HMWSoln::operator=(), HMWSoln::s_updatePitzer_CoeffWRTemp(), and HMWSoln::s_updatePitzer_d2lnMolalityActCoeff_dT2().
Array2D m_Lambda_nj_P mutable private
Derivative of Lambda_nj[i][j] wrt P.
Definition at line 2860 of file HMWSoln.h.
Referenced by HMWSoln::initLengths(), HMWSoln::operator=(), and HMWSoln::s_updatePitzer_dlnMolalityActCoeff_dP().
Array2D m_Lambda_nj_coeff private
Array of coefficients for Lambda_nj[i][j] in the Pitzer/HMW formulation.
Lambda_ij[i][j] is the value of the theta coefficient for the ij interaction. Array of 2D data used in the Pitzer/HMW formulation. Lambda_ij[i][j] represents the lambda coefficient for the ij interaction. This is a general interaction representing neutral species. The neutral species occupy the first index, i.e., i. The charged species occupy the j coordinate. Neutral, neutral interactions are also included here.
n = j + m_kk * i
m_Lambda_ij_coeff.ptrColumn(n) is a double* containing the vector of coefficients for the (i,j) interaction.
Definition at line 2878 of file HMWSoln.h.
Referenced by HMWSoln::initLengths(), HMWSoln::operator=(), and HMWSoln::s_updatePitzer_CoeffWRTemp().
vector_fp m_Mu_nnn mutable private
Mu coefficient for the self-ternary neutral coefficient.
Array of 2D data used in the Pitzer/HMW formulation. Mu_nnn[i] represents the Mu coefficient for the nnn interaction. This is a general interaction representing neutral species interacting with itself.
Definition at line 2888 of file HMWSoln.h.
Referenced by HMWSoln::initLengths(), HMWSoln::s_updatePitzer_CoeffWRTemp(), and HMWSoln::s_updatePitzer_lnMolalityActCoeff().
vector_fp m_Mu_nnn_L mutable private
Mu coefficient temperature derivative for the self-ternary neutral coefficient.
Array of 2D data used in the Pitzer/HMW formulation. Mu_nnn_L[i] represents the Mu coefficient temperature derivative for the nnn interaction. This is a general interaction representing neutral species interacting with itself.
Definition at line 2897 of file HMWSoln.h.
Referenced by HMWSoln::initLengths(), HMWSoln::s_updatePitzer_CoeffWRTemp(), and HMWSoln::s_updatePitzer_dlnMolalityActCoeff_dT().
vector_fp m_Mu_nnn_LL mutable private
Mu coefficient 2nd temperature derivative for the self-ternary neutral coefficient.
Array of 2D data used in the Pitzer/HMW formulation. Mu_nnn_L[i] represents the Mu coefficient 2nd temperature derivative for the nnn interaction. This is a general interaction representing neutral species interacting with itself.
Definition at line 2906 of file HMWSoln.h.
Referenced by HMWSoln::initLengths(), HMWSoln::s_updatePitzer_CoeffWRTemp(), and HMWSoln::s_updatePitzer_d2lnMolalityActCoeff_dT2().
vector_fp m_Mu_nnn_P mutable private
Mu coefficient pressure derivative for the self-ternary neutral coefficient.
Array of 2D data used in the Pitzer/HMW formulation. Mu_nnn_L[i] represents the Mu coefficient pressure derivative for the nnn interaction. This is a general interaction representing neutral species interacting with itself.
Definition at line 2915 of file HMWSoln.h.
Referenced by HMWSoln::initLengths(), and HMWSoln::s_updatePitzer_dlnMolalityActCoeff_dP().
Array2D m_Mu_nnn_coeff private
Array of coefficients form_Mu_nnn term.
Definition at line 2921 of file HMWSoln.h.
Referenced by HMWSoln::initLengths(), and HMWSoln::s_updatePitzer_CoeffWRTemp().
vector_fp m_lnActCoeffMolal_Scaled mutable private
Logarithm of the activity coefficients on the molality scale.
 mutable because we change this if the composition
 or temperature or pressure changes.
index is the species index
Definition at line 2932 of file HMWSoln.h.
Referenced by HMWSoln::getActivities(), HMWSoln::getChemPotentials(), HMWSoln::getPartialMolarEntropies(), HMWSoln::initLengths(), HMWSoln::operator=(), and HMWSoln::s_updateScaling_pHScaling().
vector_fp m_lnActCoeffMolal_Unscaled mutable private
Logarithm of the activity coefficients on the molality scale.
 mutable because we change this if the composition
 or temperature or pressure changes.
index is the species index
Definition at line 2942 of file HMWSoln.h.
Referenced by HMWSoln::applyphScale(), HMWSoln::getUnscaledMolalityActivityCoefficients(), HMWSoln::initLengths(), HMWSoln::operator=(), HMWSoln::s_update_lnMolalityActCoeff(), HMWSoln::s_updatePitzer_lnMolalityActCoeff(), and HMWSoln::s_updateScaling_pHScaling().
vector_fp m_dlnActCoeffMolaldT_Scaled mutable private
Derivative of the Logarithm of the activity coefficients on the molality scale wrt T.
index is the species index
Definition at line 2949 of file HMWSoln.h.
Referenced by HMWSoln::getPartialMolarCp(), HMWSoln::getPartialMolarEnthalpies(), HMWSoln::getPartialMolarEntropies(), HMWSoln::initLengths(), HMWSoln::operator=(), and HMWSoln::s_updateScaling_pHScaling_dT().
vector_fp m_dlnActCoeffMolaldT_Unscaled mutable private
Derivative of the Logarithm of the activity coefficients on the molality scale wrt T.
index is the species index
Definition at line 2956 of file HMWSoln.h.
Referenced by HMWSoln::initLengths(), HMWSoln::operator=(), HMWSoln::s_update_dlnMolalityActCoeff_dT(), HMWSoln::s_updatePitzer_dlnMolalityActCoeff_dT(), and HMWSoln::s_updateScaling_pHScaling_dT().
vector_fp m_d2lnActCoeffMolaldT2_Scaled mutable private
Derivative of the Logarithm of the activity coefficients on the molality scale wrt TT.
index is the species index
Definition at line 2963 of file HMWSoln.h.
Referenced by HMWSoln::getPartialMolarCp(), HMWSoln::initLengths(), HMWSoln::operator=(), and HMWSoln::s_updateScaling_pHScaling_dT2().
vector_fp m_d2lnActCoeffMolaldT2_Unscaled mutable private
Derivative of the Logarithm of the activity coefficients on the molality scale wrt TT.
index is the species index
Definition at line 2970 of file HMWSoln.h.
Referenced by HMWSoln::initLengths(), HMWSoln::operator=(), HMWSoln::s_update_d2lnMolalityActCoeff_dT2(), HMWSoln::s_updatePitzer_d2lnMolalityActCoeff_dT2(), and HMWSoln::s_updateScaling_pHScaling_dT2().
vector_fp m_dlnActCoeffMolaldP_Scaled mutable private
Derivative of the Logarithm of the activity coefficients on the molality scale wrt P.
index is the species index
Definition at line 2977 of file HMWSoln.h.
Referenced by HMWSoln::getPartialMolarVolumes(), HMWSoln::initLengths(), HMWSoln::operator=(), and HMWSoln::s_updateScaling_pHScaling_dP().
vector_fp m_dlnActCoeffMolaldP_Unscaled mutable private
Derivative of the Logarithm of the activity coefficients on the molality scale wrt P.
index is the species index
Definition at line 2984 of file HMWSoln.h.
Referenced by HMWSoln::initLengths(), HMWSoln::operator=(), HMWSoln::s_update_dlnMolalityActCoeff_dP(), HMWSoln::s_updatePitzer_dlnMolalityActCoeff_dP(), and HMWSoln::s_updateScaling_pHScaling_dP().
vector_fp m_molalitiesCropped mutable private
Cropped and modified values of the molalities used in activity coefficient calculations.
Definition at line 2992 of file HMWSoln.h.
Referenced by HMWSoln::calcMolalitiesCropped(), HMWSoln::initLengths(), HMWSoln::operator=(), HMWSoln::printCoeffs(), HMWSoln::s_updatePitzer_d2lnMolalityActCoeff_dT2(), HMWSoln::s_updatePitzer_dlnMolalityActCoeff_dP(), HMWSoln::s_updatePitzer_dlnMolalityActCoeff_dT(), and HMWSoln::s_updatePitzer_lnMolalityActCoeff().
bool m_molalitiesAreCropped mutable private
Boolean indicating whether the molalities are cropped or are modified.
Definition at line 2995 of file HMWSoln.h.
Referenced by HMWSoln::calcMolalitiesCropped(), and HMWSoln::operator=().
vector_int m_CounterIJ mutable private
a counter variable for keeping track of symmetric binary interactions amongst the solute species.
n = m_kk*i + j m_CounterIJ[n] = counterIJ
Definition at line 3003 of file HMWSoln.h.
Referenced by HMWSoln::counterIJ_setup(), HMWSoln::HMWSoln(), HMWSoln::initLengths(), HMWSoln::operator=(), HMWSoln::printCoeffs(), HMWSoln::s_updatePitzer_CoeffWRTemp(), HMWSoln::s_updatePitzer_d2lnMolalityActCoeff_dT2(), HMWSoln::s_updatePitzer_dlnMolalityActCoeff_dP(), HMWSoln::s_updatePitzer_dlnMolalityActCoeff_dT(), and HMWSoln::s_updatePitzer_lnMolalityActCoeff().
double elambda[17] mutable private
This is elambda, MEC.
Definition at line 3008 of file HMWSoln.h.
Referenced by HMWSoln::calc_lambdas(), HMWSoln::calc_thetas(), and HMWSoln::HMWSoln().
double elambda1[17] mutable private
This is elambda1, MEC.
Definition at line 3013 of file HMWSoln.h.
Referenced by HMWSoln::calc_lambdas(), HMWSoln::calc_thetas(), and HMWSoln::HMWSoln().
vector_fp m_gfunc_IJ mutable private
Various temporary arrays used in the calculation of the Pitzer activity coefficients.
The subscript, L, denotes the same quantity's derivative wrt temperatureThis is the value of g(x) in Pitzer's papers
vector index is counterIJ
Definition at line 3026 of file HMWSoln.h.
Referenced by HMWSoln::initLengths(), HMWSoln::operator=(), HMWSoln::s_updatePitzer_d2lnMolalityActCoeff_dT2(), HMWSoln::s_updatePitzer_dlnMolalityActCoeff_dP(), HMWSoln::s_updatePitzer_dlnMolalityActCoeff_dT(), and HMWSoln::s_updatePitzer_lnMolalityActCoeff().
vector_fp m_g2func_IJ mutable private
This is the value of g2(x2) in Pitzer's papers.
vector index is counterIJ
Definition at line 3032 of file HMWSoln.h.
Referenced by HMWSoln::initLengths(), HMWSoln::operator=(), HMWSoln::s_updatePitzer_d2lnMolalityActCoeff_dT2(), HMWSoln::s_updatePitzer_dlnMolalityActCoeff_dP(), HMWSoln::s_updatePitzer_dlnMolalityActCoeff_dT(), and HMWSoln::s_updatePitzer_lnMolalityActCoeff().
vector_fp m_hfunc_IJ mutable private
hfunc, was called gprime in Pitzer's paper.
However, it's not the derivative of gfunc(x), so I renamed it.
vector index is counterIJ
Definition at line 3039 of file HMWSoln.h.
Referenced by HMWSoln::initLengths(), HMWSoln::operator=(), HMWSoln::s_updatePitzer_d2lnMolalityActCoeff_dT2(), HMWSoln::s_updatePitzer_dlnMolalityActCoeff_dP(), HMWSoln::s_updatePitzer_dlnMolalityActCoeff_dT(), and HMWSoln::s_updatePitzer_lnMolalityActCoeff().
vector_fp m_h2func_IJ mutable private
hfunc2, was called gprime in Pitzer's paper.
However, it's not the derivative of gfunc(x), so I renamed it.
vector index is counterIJ
Definition at line 3046 of file HMWSoln.h.
Referenced by HMWSoln::initLengths(), HMWSoln::operator=(), HMWSoln::s_updatePitzer_d2lnMolalityActCoeff_dT2(), HMWSoln::s_updatePitzer_dlnMolalityActCoeff_dP(), HMWSoln::s_updatePitzer_dlnMolalityActCoeff_dT(), and HMWSoln::s_updatePitzer_lnMolalityActCoeff().
vector_fp m_BMX_IJ mutable private
Intermediate variable called BMX in Pitzer's paper This is the basic cation - anion interaction.
vector index is counterIJ
Definition at line 3053 of file HMWSoln.h.
Referenced by HMWSoln::initLengths(), HMWSoln::operator=(), and HMWSoln::s_updatePitzer_lnMolalityActCoeff().
vector_fp m_BMX_IJ_L mutable private
Derivative of BMX_IJ wrt T.
vector index is counterIJ
Definition at line 3059 of file HMWSoln.h.
Referenced by HMWSoln::initLengths(), HMWSoln::operator=(), and HMWSoln::s_updatePitzer_dlnMolalityActCoeff_dT().
vector_fp m_BMX_IJ_LL mutable private
Derivative of BMX_IJ wrt TT.
vector index is counterIJ
Definition at line 3065 of file HMWSoln.h.
Referenced by HMWSoln::initLengths(), HMWSoln::operator=(), and HMWSoln::s_updatePitzer_d2lnMolalityActCoeff_dT2().
vector_fp m_BMX_IJ_P mutable private
Derivative of BMX_IJ wrt P.
vector index is counterIJ
Definition at line 3071 of file HMWSoln.h.
Referenced by HMWSoln::initLengths(), HMWSoln::operator=(), and HMWSoln::s_updatePitzer_dlnMolalityActCoeff_dP().
vector_fp m_BprimeMX_IJ mutable private
Intermediate variable called BprimeMX in Pitzer's paper.
vector index is counterIJ
Definition at line 3077 of file HMWSoln.h.
Referenced by HMWSoln::initLengths(), HMWSoln::operator=(), and HMWSoln::s_updatePitzer_lnMolalityActCoeff().
vector_fp m_BprimeMX_IJ_L mutable private
Derivative of BprimeMX wrt T.
vector index is counterIJ
Definition at line 3083 of file HMWSoln.h.
Referenced by HMWSoln::initLengths(), HMWSoln::operator=(), and HMWSoln::s_updatePitzer_dlnMolalityActCoeff_dT().
vector_fp m_BprimeMX_IJ_LL mutable private
Derivative of BprimeMX wrt TT.
vector index is counterIJ
Definition at line 3089 of file HMWSoln.h.
Referenced by HMWSoln::initLengths(), HMWSoln::operator=(), and HMWSoln::s_updatePitzer_d2lnMolalityActCoeff_dT2().
vector_fp m_BprimeMX_IJ_P mutable private
Derivative of BprimeMX wrt P.
vector index is counterIJ
Definition at line 3095 of file HMWSoln.h.
Referenced by HMWSoln::initLengths(), HMWSoln::operator=(), and HMWSoln::s_updatePitzer_dlnMolalityActCoeff_dP().
vector_fp m_BphiMX_IJ mutable private
Intermediate variable called BphiMX in Pitzer's paper.
vector index is counterIJ
Definition at line 3101 of file HMWSoln.h.
Referenced by HMWSoln::initLengths(), HMWSoln::operator=(), and HMWSoln::s_updatePitzer_lnMolalityActCoeff().
vector_fp m_BphiMX_IJ_L mutable private
Derivative of BphiMX_IJ wrt T.
vector index is counterIJ
Definition at line 3107 of file HMWSoln.h.
Referenced by HMWSoln::initLengths(), HMWSoln::operator=(), and HMWSoln::s_updatePitzer_dlnMolalityActCoeff_dT().
vector_fp m_BphiMX_IJ_LL mutable private
Derivative of BphiMX_IJ wrt TT.
vector index is counterIJ
Definition at line 3113 of file HMWSoln.h.
Referenced by HMWSoln::initLengths(), HMWSoln::operator=(), and HMWSoln::s_updatePitzer_d2lnMolalityActCoeff_dT2().
vector_fp m_BphiMX_IJ_P mutable private
Derivative of BphiMX_IJ wrt P.
vector index is counterIJ
Definition at line 3119 of file HMWSoln.h.
Referenced by HMWSoln::initLengths(), HMWSoln::operator=(), and HMWSoln::s_updatePitzer_dlnMolalityActCoeff_dP().
vector_fp m_Phi_IJ mutable private
Intermediate variable called Phi in Pitzer's paper.
vector index is counterIJ
Definition at line 3125 of file HMWSoln.h.
Referenced by HMWSoln::initLengths(), HMWSoln::operator=(), and HMWSoln::s_updatePitzer_lnMolalityActCoeff().
vector_fp m_Phi_IJ_L mutable private
Derivative of m_Phi_IJ wrt T.
vector index is counterIJ
Definition at line 3131 of file HMWSoln.h.
Referenced by HMWSoln::initLengths(), HMWSoln::operator=(), and HMWSoln::s_updatePitzer_dlnMolalityActCoeff_dT().
vector_fp m_Phi_IJ_LL mutable private
Derivative of m_Phi_IJ wrt TT.
vector index is counterIJ
Definition at line 3137 of file HMWSoln.h.
Referenced by HMWSoln::initLengths(), HMWSoln::operator=(), and HMWSoln::s_updatePitzer_d2lnMolalityActCoeff_dT2().
vector_fp m_Phi_IJ_P mutable private
Derivative of m_Phi_IJ wrt P.
vector index is counterIJ
Definition at line 3143 of file HMWSoln.h.
Referenced by HMWSoln::initLengths(), HMWSoln::operator=(), and HMWSoln::s_updatePitzer_dlnMolalityActCoeff_dP().
vector_fp m_Phiprime_IJ mutable private
Intermediate variable called Phiprime in Pitzer's paper.
vector index is counterIJ
Definition at line 3149 of file HMWSoln.h.
Referenced by HMWSoln::initLengths(), HMWSoln::operator=(), HMWSoln::s_updatePitzer_d2lnMolalityActCoeff_dT2(), HMWSoln::s_updatePitzer_dlnMolalityActCoeff_dP(), HMWSoln::s_updatePitzer_dlnMolalityActCoeff_dT(), and HMWSoln::s_updatePitzer_lnMolalityActCoeff().
vector_fp m_PhiPhi_IJ mutable private
Intermediate variable called PhiPhi in Pitzer's paper.
vector index is counterIJ
Definition at line 3155 of file HMWSoln.h.
Referenced by HMWSoln::initLengths(), HMWSoln::operator=(), and HMWSoln::s_updatePitzer_lnMolalityActCoeff().
vector_fp m_PhiPhi_IJ_L mutable private
Derivative of m_PhiPhi_IJ wrt T.
vector index is counterIJ
Definition at line 3161 of file HMWSoln.h.
Referenced by HMWSoln::initLengths(), HMWSoln::operator=(), and HMWSoln::s_updatePitzer_dlnMolalityActCoeff_dT().
vector_fp m_PhiPhi_IJ_LL mutable private
Derivative of m_PhiPhi_IJ wrt TT.
vector index is counterIJ
Definition at line 3167 of file HMWSoln.h.
Referenced by HMWSoln::initLengths(), HMWSoln::operator=(), and HMWSoln::s_updatePitzer_d2lnMolalityActCoeff_dT2().
vector_fp m_PhiPhi_IJ_P mutable private
Derivative of m_PhiPhi_IJ wrt P.
vector index is counterIJ
Definition at line 3173 of file HMWSoln.h.
Referenced by HMWSoln::initLengths(), HMWSoln::operator=(), and HMWSoln::s_updatePitzer_dlnMolalityActCoeff_dP().
vector_fp m_CMX_IJ mutable private
Intermediate variable called CMX in Pitzer's paper.
vector index is counterIJ
Definition at line 3179 of file HMWSoln.h.
Referenced by HMWSoln::initLengths(), HMWSoln::operator=(), and HMWSoln::s_updatePitzer_lnMolalityActCoeff().
vector_fp m_CMX_IJ_L mutable private
Derivative of m_CMX_IJ wrt T.
vector index is counterIJ
Definition at line 3185 of file HMWSoln.h.
Referenced by HMWSoln::initLengths(), HMWSoln::operator=(), and HMWSoln::s_updatePitzer_dlnMolalityActCoeff_dT().
vector_fp m_CMX_IJ_LL mutable private
Derivative of m_CMX_IJ wrt TT.
vector index is counterIJ
Definition at line 3191 of file HMWSoln.h.
Referenced by HMWSoln::initLengths(), HMWSoln::operator=(), and HMWSoln::s_updatePitzer_d2lnMolalityActCoeff_dT2().
vector_fp m_CMX_IJ_P mutable private
Derivative of m_CMX_IJ wrt P.
vector index is counterIJ
Definition at line 3197 of file HMWSoln.h.
Referenced by HMWSoln::initLengths(), HMWSoln::operator=(), and HMWSoln::s_updatePitzer_dlnMolalityActCoeff_dP().
vector_fp m_gamma_tmp mutable private
Intermediate storage of the activity coefficient itself.
vector index is the species index
Definition at line 3203 of file HMWSoln.h.
Referenced by HMWSoln::calcMolalitiesCropped(), HMWSoln::initLengths(), HMWSoln::operator=(), HMWSoln::relative_enthalpy(), HMWSoln::s_updatePitzer_dlnMolalityActCoeff_dT(), and HMWSoln::s_updatePitzer_lnMolalityActCoeff().
vector_fp IMS_lnActCoeffMolal_ mutable private
Logarithm of the molal activity coefficients.
Normally these are all one. However, stability schemes will change that
Definition at line 3209 of file HMWSoln.h.
Referenced by HMWSoln::initLengths(), HMWSoln::operator=(), HMWSoln::s_update_lnMolalityActCoeff(), and HMWSoln::s_updateIMS_lnMolalityActCoeff().
int IMS_typeCutoff_ private
IMS Cutoff type.
Definition at line 3212 of file HMWSoln.h.
Referenced by HMWSoln::operator=(), and HMWSoln::s_updateIMS_lnMolalityActCoeff().
doublereal IMS_X_o_cutoff_ private
value of the solute mole fraction that centers the cutoff polynomials for the cutoff =1 process;
Definition at line 3216 of file HMWSoln.h.
Referenced by HMWSoln::operator=(), and HMWSoln::s_updateIMS_lnMolalityActCoeff().
doublereal IMS_gamma_o_min_ private
gamma_o value for the cutoff process at the zero solvent point
Definition at line 3219 of file HMWSoln.h.
Referenced by HMWSoln::operator=(), and HMWSoln::s_updateIMS_lnMolalityActCoeff().
doublereal IMS_gamma_k_min_ private
gamma_k minimum for the cutoff process at the zero solvent point
Definition at line 3222 of file HMWSoln.h.
Referenced by HMWSoln::operator=(), and HMWSoln::s_updateIMS_lnMolalityActCoeff().
doublereal IMS_cCut_ private
Parameter in the polyExp cutoff treatment having to do with rate of exp decay.
Definition at line 3225 of file HMWSoln.h.
Referenced by HMWSoln::operator=(), and HMWSoln::s_updateIMS_lnMolalityActCoeff().
doublereal IMS_slopefCut_ private
Parameter in the polyExp cutoff treatment.
This is the slope of the f function at the zero solvent point Default value is 0.6
Definition at line 3232 of file HMWSoln.h.
Referenced by HMWSoln::operator=().
doublereal IMS_dfCut_ private
Parameter in the polyExp cutoff treatment having to do with rate of exp decay.
Definition at line 3235 of file HMWSoln.h.
Referenced by HMWSoln::operator=(), and HMWSoln::s_updateIMS_lnMolalityActCoeff().
doublereal IMS_efCut_ private
Parameter in the polyExp cutoff treatment having to do with rate of exp decay.
Definition at line 3238 of file HMWSoln.h.
Referenced by HMWSoln::operator=(), and HMWSoln::s_updateIMS_lnMolalityActCoeff().
doublereal IMS_afCut_ private
Parameter in the polyExp cutoff treatment having to do with rate of exp decay.
Definition at line 3241 of file HMWSoln.h.
Referenced by HMWSoln::operator=(), and HMWSoln::s_updateIMS_lnMolalityActCoeff().
doublereal IMS_bfCut_ private
Parameter in the polyExp cutoff treatment having to do with rate of exp decay.
Definition at line 3244 of file HMWSoln.h.
Referenced by HMWSoln::operator=(), and HMWSoln::s_updateIMS_lnMolalityActCoeff().
doublereal IMS_slopegCut_ private
Parameter in the polyExp cutoff treatment.
This is the slope of the g function at the zero solvent point Default value is 0.0
Definition at line 3251 of file HMWSoln.h.
Referenced by HMWSoln::operator=().
doublereal IMS_dgCut_ private
Parameter in the polyExp cutoff treatment having to do with rate of exp decay.
Definition at line 3255 of file HMWSoln.h.
Referenced by HMWSoln::operator=(), and HMWSoln::s_updateIMS_lnMolalityActCoeff().
doublereal IMS_egCut_ private
Parameter in the polyExp cutoff treatment having to do with rate of exp decay.
Definition at line 3258 of file HMWSoln.h.
Referenced by HMWSoln::operator=(), and HMWSoln::s_updateIMS_lnMolalityActCoeff().
doublereal IMS_agCut_ private
Parameter in the polyExp cutoff treatment having to do with rate of exp decay.
Definition at line 3261 of file HMWSoln.h.
Referenced by HMWSoln::operator=(), and HMWSoln::s_updateIMS_lnMolalityActCoeff().
doublereal IMS_bgCut_ private
Parameter in the polyExp cutoff treatment having to do with rate of exp decay.
Definition at line 3264 of file HMWSoln.h.
Referenced by HMWSoln::operator=(), and HMWSoln::s_updateIMS_lnMolalityActCoeff().
doublereal MC_X_o_cutoff_ private
value of the solvent mole fraction that centers the cutoff polynomials for the cutoff =1 process;
Definition at line 3268 of file HMWSoln.h.
Referenced by HMWSoln::calcMolalitiesCropped(), and HMWSoln::operator=().
doublereal MC_X_o_min_ private
gamma_o value for the cutoff process at the zero solvent point
Definition at line 3271 of file HMWSoln.h.
Referenced by HMWSoln::operator=().
doublereal MC_slopepCut_ private
Parameter in the Molality Exp cutoff treatment.
This is the slope of the p function at the zero solvent point Default value is 0.0
Definition at line 3278 of file HMWSoln.h.
Referenced by HMWSoln::operator=().
doublereal MC_dpCut_ private
Parameter in the Molality Exp cutoff treatment.
Definition at line 3281 of file HMWSoln.h.
Referenced by HMWSoln::calcMolalitiesCropped(), and HMWSoln::operator=().
doublereal MC_epCut_ private
Parameter in the Molality Exp cutoff treatment.
Definition at line 3284 of file HMWSoln.h.
Referenced by HMWSoln::calcMolalitiesCropped(), and HMWSoln::operator=().
doublereal MC_apCut_ private
Parameter in the Molality Exp cutoff treatment.
Definition at line 3287 of file HMWSoln.h.
Referenced by HMWSoln::calcMolalitiesCropped(), and HMWSoln::operator=().
doublereal MC_bpCut_ private
Parameter in the Molality Exp cutoff treatment.
Definition at line 3290 of file HMWSoln.h.
Referenced by HMWSoln::calcMolalitiesCropped(), and HMWSoln::operator=().
doublereal MC_cpCut_ private
Parameter in the Molality Exp cutoff treatment.
Definition at line 3293 of file HMWSoln.h.
Referenced by HMWSoln::calcMolalitiesCropped(), and HMWSoln::operator=().
doublereal CROP_ln_gamma_o_min private
Parameter in the Molality Exp cutoff treatment.
Definition at line 3296 of file HMWSoln.h.
Referenced by HMWSoln::operator=(), and HMWSoln::s_update_lnMolalityActCoeff().
doublereal CROP_ln_gamma_o_max private
Parameter in the Molality Exp cutoff treatment.
Definition at line 3299 of file HMWSoln.h.
Referenced by HMWSoln::operator=(), and HMWSoln::s_update_lnMolalityActCoeff().
doublereal CROP_ln_gamma_k_min private
Parameter in the Molality Exp cutoff treatment.
Definition at line 3302 of file HMWSoln.h.
Referenced by HMWSoln::operator=(), and HMWSoln::s_update_lnMolalityActCoeff().
doublereal CROP_ln_gamma_k_max private
Parameter in the Molality Exp cutoff treatment.
Definition at line 3305 of file HMWSoln.h.
Referenced by HMWSoln::operator=(), and HMWSoln::s_update_lnMolalityActCoeff().
std::vector<int> CROP_speciesCropped_ mutable private
This is a boolean-type vector indicating whether a species's activity coefficient is in the cropped regime.
0 = Not in cropped regime 1 = In a transition regime where it is altered but there still may be a temperature or pressure dependence 2 = In a cropped regime where there is no temperature or pressure dependence
Definition at line 3317 of file HMWSoln.h.
Referenced by HMWSoln::initLengths(), HMWSoln::operator=(), HMWSoln::s_update_d2lnMolalityActCoeff_dT2(), HMWSoln::s_update_dlnMolalityActCoeff_dP(), HMWSoln::s_update_dlnMolalityActCoeff_dT(), and HMWSoln::s_update_lnMolalityActCoeff().
int m_debugCalc mutable
Turn on copious debug printing when this is true and DEBUG_MODE is turned on.
Definition at line 3594 of file HMWSoln.h.
Referenced by HMWSoln::calc_lambdas(), HMWSoln::debugPrinting(), HMWSoln::operator=(), HMWSoln::s_updatePitzer_d2lnMolalityActCoeff_dT2(), HMWSoln::s_updatePitzer_dlnMolalityActCoeff_dP(), HMWSoln::s_updatePitzer_dlnMolalityActCoeff_dT(), and HMWSoln::s_updatePitzer_lnMolalityActCoeff().
size_t m_indexSolvent protected inherited
Index of the solvent.
Currently the index of the solvent is hard-coded to the value 0
Definition at line 883 of file MolalityVPSSTP.h.
Referenced by DebyeHuckel::_lnactivityWaterHelgesonFixedForm(), MolalityVPSSTP::calcMolalities(), HMWSoln::calcMolalitiesCropped(), IdealMolalSoln::getActivities(), DebyeHuckel::getActivities(), HMWSoln::getActivities(), MolalityVPSSTP::getActivityCoefficients(), IdealMolalSoln::getChemPotentials(), DebyeHuckel::getChemPotentials(), HMWSoln::getChemPotentials(), IdealMolalSoln::getMolalityActivityCoefficients(), IdealMolalSoln::getPartialMolarEntropies(), DebyeHuckel::getPartialMolarEntropies(), HMWSoln::getPartialMolarEntropies(), IdealMolalSoln::initThermoXML(), DebyeHuckel::initThermoXML(), MolalityVPSSTP::operator=(), MolalityVPSSTP::osmoticCoefficient(), DebyeHuckel::s_update_d2lnMolalityActCoeff_dT2(), DebyeHuckel::s_update_dlnMolalityActCoeff_dP(), DebyeHuckel::s_update_dlnMolalityActCoeff_dT(), DebyeHuckel::s_update_lnMolalityActCoeff(), HMWSoln::s_update_lnMolalityActCoeff(), IdealMolalSoln::s_updateIMS_lnMolalityActCoeff(), HMWSoln::s_updateIMS_lnMolalityActCoeff(), HMWSoln::s_updatePitzer_d2lnMolalityActCoeff_dT2(), HMWSoln::s_updatePitzer_dlnMolalityActCoeff_dP(), HMWSoln::s_updatePitzer_dlnMolalityActCoeff_dT(), HMWSoln::s_updatePitzer_lnMolalityActCoeff(), MolalityVPSSTP::setMolalities(), MolalityVPSSTP::setMolalitiesByName(), MolalityVPSSTP::setSolvent(), MolalityVPSSTP::solventIndex(), IdealMolalSoln::standardConcentration(), DebyeHuckel::standardConcentration(), and HMWSoln::standardConcentration().
int m_pHScalingType protected inherited
Scaling to be used for output of single-ion species activity coefficients.
Index of the species to be used in the single-ion scaling law. This is the identity of the Cl- species for the PHSCALE_NBS scaling. Either PHSCALE_PITZER or PHSCALE_NBS
Definition at line 893 of file MolalityVPSSTP.h.
Referenced by HMWSoln::applyphScale(), MolalityVPSSTP::operator=(), MolalityVPSSTP::pHScale(), HMWSoln::s_updateScaling_pHScaling(), HMWSoln::s_updateScaling_pHScaling_dP(), HMWSoln::s_updateScaling_pHScaling_dT(), HMWSoln::s_updateScaling_pHScaling_dT2(), and MolalityVPSSTP::setpHScale().
size_t m_indexCLM protected inherited
Index of the phScale species.
Index of the species to be used in the single-ion scaling law. This is the identity of the Cl- species for the PHSCALE_NBS scaling
Definition at line 901 of file MolalityVPSSTP.h.
Referenced by HMWSoln::applyphScale(), MolalityVPSSTP::initThermo(), MolalityVPSSTP::operator=(), HMWSoln::s_updateScaling_pHScaling(), HMWSoln::s_updateScaling_pHScaling_dP(), HMWSoln::s_updateScaling_pHScaling_dT(), and HMWSoln::s_updateScaling_pHScaling_dT2().
doublereal m_weightSolvent protected inherited
Molecular weight of the Solvent.
Definition at line 904 of file MolalityVPSSTP.h.
Referenced by MolalityVPSSTP::operator=(), HMWSoln::s_updatePitzer_d2lnMolalityActCoeff_dT2(), HMWSoln::s_updatePitzer_dlnMolalityActCoeff_dP(), HMWSoln::s_updatePitzer_dlnMolalityActCoeff_dT(), HMWSoln::s_updatePitzer_lnMolalityActCoeff(), and MolalityVPSSTP::setSolvent().
doublereal m_xmolSolventMIN protected inherited
In any molality implementation, it makes sense to have a minimum solvent mole fraction requirement, since the implementation becomes singular in the xmolSolvent=0 limit. The default is to set it to 0.01. We then modify the molality definition to ensure that molal_solvent = 0 when xmol_solvent = 0.
Definition at line 914 of file MolalityVPSSTP.h.
Referenced by MolalityVPSSTP::calcMolalities(), IdealMolalSoln::getActivities(), MolalityVPSSTP::getActivityCoefficients(), IdealMolalSoln::getMolalityActivityCoefficients(), MolalityVPSSTP::moleFSolventMin(), MolalityVPSSTP::operator=(), HMWSoln::s_update_lnMolalityActCoeff(), IdealMolalSoln::s_updateIMS_lnMolalityActCoeff(), HMWSoln::s_updateIMS_lnMolalityActCoeff(), HMWSoln::s_updatePitzer_lnMolalityActCoeff(), MolalityVPSSTP::setMolalitiesByName(), and MolalityVPSSTP::setMoleFSolventMin().
doublereal m_Mnaught protected inherited
This is the multiplication factor that goes inside log expressions involving the molalities of species.
It's equal to Wt_0 / 1000, where Wt_0 = weight of solvent (kg/kmol)
Definition at line 922 of file MolalityVPSSTP.h.
Referenced by DebyeHuckel::_lnactivityWaterHelgesonFixedForm(), MolalityVPSSTP::calcMolalities(), HMWSoln::calcMolalitiesCropped(), MolalityVPSSTP::operator=(), MolalityVPSSTP::osmoticCoefficient(), DebyeHuckel::s_update_d2lnMolalityActCoeff_dT2(), DebyeHuckel::s_update_dlnMolalityActCoeff_dP(), DebyeHuckel::s_update_dlnMolalityActCoeff_dT(), DebyeHuckel::s_update_lnMolalityActCoeff(), MolalityVPSSTP::setMolalities(), MolalityVPSSTP::setMolalitiesByName(), MolalityVPSSTP::setSolvent(), and HMWSoln::standardConcentration().
vector_fp m_molalities mutable protected inherited
Current value of the molalities of the species in the phase.
Note this vector is a mutable quantity. units are (kg/kmol)
Definition at line 929 of file MolalityVPSSTP.h.
Referenced by DebyeHuckel::_lnactivityWaterHelgesonFixedForm(), MolalityVPSSTP::calcMolalities(), HMWSoln::calcMolalitiesCropped(), IdealMolalSoln::getActivities(), DebyeHuckel::getActivities(), HMWSoln::getActivities(), IdealMolalSoln::getChemPotentials(), DebyeHuckel::getChemPotentials(), HMWSoln::getChemPotentials(), MolalityVPSSTP::getMolalities(), IdealMolalSoln::getPartialMolarEntropies(), DebyeHuckel::getPartialMolarEntropies(), HMWSoln::getPartialMolarEntropies(), MolalityVPSSTP::initLengths(), MolalityVPSSTP::operator=(), MolalityVPSSTP::osmoticCoefficient(), DebyeHuckel::s_update_d2lnMolalityActCoeff_dT2(), DebyeHuckel::s_update_dlnMolalityActCoeff_dP(), DebyeHuckel::s_update_dlnMolalityActCoeff_dT(), DebyeHuckel::s_update_lnMolalityActCoeff(), HMWSoln::s_update_lnMolalityActCoeff(), HMWSoln::s_updatePitzer_lnMolalityActCoeff(), and MolalityVPSSTP::setMolalities().
doublereal m_Pcurrent protected inherited
Current value of the pressure - state variable.
Because we are now using the pressure as a state variable, we need to carry it along within this object
units = Pascals
Definition at line 606 of file VPStandardStateTP.h.
Referenced by VPStandardStateTP::_updateStandardStateThermo(), IdealSolnGasVPSS::calcDensity(), IdealSolnGasVPSS::isothermalCompressibility(), VPStandardStateTP::operator=(), VPStandardStateTP::pressure(), DebyeHuckel::pressure(), HMWSoln::pressure(), IdealSolnGasVPSS::setPressure(), VPStandardStateTP::setState_TP(), IdealMolalSoln::setState_TP(), GibbsExcessVPSSTP::setState_TP(), DebyeHuckel::setState_TP(), HMWSoln::setState_TP(), VPStandardStateTP::setTemperature(), DebyeHuckel::setTemperature(), HMWSoln::setTemperature(), and VPStandardStateTP::updateStandardStateThermo().
doublereal m_Tlast_ss mutable protected inherited
The last temperature at which the standard statethermodynamic properties were calculated at.
Definition at line 609 of file VPStandardStateTP.h.
Referenced by VPStandardStateTP::_updateStandardStateThermo(), VPStandardStateTP::operator=(), and VPStandardStateTP::updateStandardStateThermo().
doublereal m_Plast_ss mutable protected inherited
The last pressure at which the Standard State thermodynamic properties were calculated at.
Definition at line 613 of file VPStandardStateTP.h.
Referenced by VPStandardStateTP::_updateStandardStateThermo(), VPStandardStateTP::operator=(), and VPStandardStateTP::updateStandardStateThermo().
doublereal m_P0 protected inherited
Reference pressure (Pa) must be the same for all species
defaults to OneAtm
Definition at line 619 of file VPStandardStateTP.h.
Referenced by VPStandardStateTP::operator=().
VPSSMgr* m_VPSS_ptr mutable protected inherited
Pointer to the VPSS manager that calculates all of the standard state info efficiently.
Definition at line 626 of file VPStandardStateTP.h.
Referenced by VPStandardStateTP::_updateStandardStateThermo(), IdealSolnGasVPSS::calcDensity(), IdealSolnGasVPSS::cp_mole(), IdealSolnGasVPSS::enthalpy_mole(), IdealSolnGasVPSS::entropy_mole(), IdealSolnGasVPSS::getActivityConcentrations(), VPStandardStateTP::getCp_R(), VPStandardStateTP::getCp_R_ref(), VPStandardStateTP::getEnthalpy_RT(), VPStandardStateTP::getEnthalpy_RT_ref(), VPStandardStateTP::getEntropy_R(), VPStandardStateTP::getEntropy_R_ref(), VPStandardStateTP::getGibbs_ref(), VPStandardStateTP::getGibbs_RT(), VPStandardStateTP::getGibbs_RT_ref(), VPStandardStateTP::getIntEnergy_RT(), VPStandardStateTP::getPureGibbs(), VPStandardStateTP::getStandardVolumes(), VPStandardStateTP::getStandardVolumes_ref(), VPStandardStateTP::initThermo(), VPStandardStateTP::initThermoXML(), VPStandardStateTP::operator=(), VPStandardStateTP::provideVPSSMgr(), IdealSolnGasVPSS::setToEquilState(), VPStandardStateTP::setVPSSMgr(), IdealSolnGasVPSS::standardConcentration(), and VPStandardStateTP::~VPStandardStateTP().
std::vector<PDSS*> m_PDSS_storage protected inherited
Storage for the PDSS objects for the species.
Storage is in species index order. VPStandardStateTp owns each of the objects. Copy operations are deep.
Definition at line 634 of file VPStandardStateTP.h.
Referenced by VPStandardStateTP::initThermo(), VPStandardStateTP::initThermoXML(), VPStandardStateTP::operator=(), and VPStandardStateTP::~VPStandardStateTP().
SpeciesThermo* m_spthermo protected inherited
Pointer to the calculation manager for species reference-state thermodynamic properties.
This class is called when the reference-state thermodynamic properties of all the species in the phase needs to be evaluated.
Definition at line 1611 of file ThermoPhase.h.
Referenced by MixtureFugacityTP::_updateReferenceStateThermo(), ConstDensityThermo::_updateThermo(), SurfPhase::_updateThermo(), SingleSpeciesTP::_updateThermo(), IdealGasPhase::_updateThermo(), LatticePhase::_updateThermo(), IdealSolidSolnPhase::_updateThermo(), ConstDensityThermo::enthalpy_mole(), LatticePhase::enthalpy_mole(), RedlichKwongMFTP::entropy_mole(), IdealGasPhase::entropy_mole(), FixedChemPotSSTP::FixedChemPotSSTP(), ConstDensityThermo::getChemPotentials(), MixtureFugacityTP::getEntropy_R(), IdealGasPhase::getEntropy_R(), PureFluidPhase::getEntropy_R_ref(), MixtureFugacityTP::getGibbs_RT(), IdealGasPhase::getGibbs_RT(), PureFluidPhase::getGibbs_RT_ref(), IdealGasPhase::getPartialMolarEntropies(), MixtureFugacityTP::getPureGibbs(), IdealGasPhase::getPureGibbs(), MixtureFugacityTP::getStandardChemPotentials(), IdealGasPhase::getStandardChemPotentials(), IdealSolidSolnPhase::initLengths(), ConstDensityThermo::initThermo(), StoichSubstance::initThermo(), StoichSubstanceSSTP::initThermo(), PureFluidPhase::initThermo(), SingleSpeciesTP::initThermo(), IdealGasPhase::initThermo(), LatticePhase::initThermo(), WaterSSTP::initThermoXML(), LatticeSolidPhase::installSlavePhases(), ConstDensityThermo::intEnergy_mole(), LatticePhase::intEnergy_mole(), ThermoPhase::maxTemp(), ThermoPhase::minTemp(), VPStandardStateTP::operator=(), ThermoPhase::operator=(), ThermoPhase::refPressure(), ThermoPhase::setSpeciesThermo(), LatticeSolidPhase::speciesThermo(), ThermoPhase::speciesThermo(), and ThermoPhase::~ThermoPhase().
std::vector<const XML_Node*> m_speciesData protected inherited
Vector of pointers to the species databases.
This is used to access data needed to construct the transport manager and other properties later in the initialization process. We create a copy of the XML_Node data read in here. Therefore, we own this data.
Definition at line 1621 of file ThermoPhase.h.
Referenced by LatticeSolidPhase::installSlavePhases(), ThermoPhase::operator=(), ThermoPhase::saveSpeciesData(), ThermoPhase::speciesData(), and ThermoPhase::~ThermoPhase().
doublereal m_phi protected inherited
Stored value of the electric potential for this phase.
Units are Volts
Definition at line 1627 of file ThermoPhase.h.
Referenced by ThermoPhase::electricPotential(), IdealMolalSoln::electricPotential(), ThermoPhase::operator=(), and ThermoPhase::setElectricPotential().
vector_fp m_lambdaRRT protected inherited
Vector of element potentials.
-> length equal to number of elements
Definition at line 1631 of file ThermoPhase.h.
Referenced by ThermoPhase::getElementPotentials(), ThermoPhase::operator=(), and ThermoPhase::setElementPotentials().
bool m_hasElementPotentials protected inherited
Boolean indicating whether there is a valid set of saved element potentials for this phase.
Definition at line 1635 of file ThermoPhase.h.
Referenced by ThermoPhase::getElementPotentials(), ThermoPhase::operator=(), and ThermoPhase::setElementPotentials().
bool m_chargeNeutralityNecessary protected inherited
Boolean indicating whether a charge neutrality condition is a necessity.
Note, the charge neutrality condition is not a necessity for ideal gas phases. There may be a net charge in those phases, because the NASA polynomials for ionized species in Ideal gases take this condition into account. However, liquid phases usually require charge neutrality in order for their derived thermodynamics to be valid.
Definition at line 1645 of file ThermoPhase.h.
Referenced by ThermoPhase::chargeNeutralityNecessary(), MolalityVPSSTP::MolalityVPSSTP(), and ThermoPhase::operator=().
int m_ssConvention protected inherited
Contains the standard state convention.
Definition at line 1648 of file ThermoPhase.h.
Referenced by ThermoPhase::operator=(), and ThermoPhase::standardStateConvention().
std::vector<doublereal> xMol_Ref protected inherited
Reference Mole Fraction Composition.
Occasionally, the need arises to find a safe mole fraction vector to initialize the object to. This contains such a vector. The algorithm will pick up the mole fraction vector that is applied from the state xml file in the input file
Definition at line 1657 of file ThermoPhase.h.
Referenced by ThermoPhase::getReferenceComposition(), ThermoPhase::initThermo(), and ThermoPhase::setReferenceComposition().
size_t m_kk protected inherited
Number of species in the phase.
Definition at line 727 of file Phase.h.
Referenced by DebyeHuckel::_lnactivityWaterHelgesonFixedForm(), MixtureFugacityTP::_updateReferenceStateThermo(), ConstDensityThermo::_updateThermo(), SurfPhase::_updateThermo(), IdealGasPhase::_updateThermo(), LatticePhase::_updateThermo(), IdealSolidSolnPhase::_updateThermo(), Phase::addUniqueElementAfterFreeze(), Phase::addUniqueSpecies(), HMWSoln::applyphScale(), RedlichKwongMFTP::applyStandardMixingRules(), GibbsExcessVPSSTP::calcDensity(), IdealMolalSoln::calcDensity(), DebyeHuckel::calcDensity(), HMWSoln::calcDensity(), IonsFromNeutralVPSSTP::calcIonMoleFractions(), MolalityVPSSTP::calcMolalities(), HMWSoln::calcMolalitiesCropped(), IonsFromNeutralVPSSTP::calcNeutralMoleculeMoleFractions(), PseudoBinaryVPSSTP::calcPseudoBinaryMoleFractions(), MolarityIonicVPSSTP::calcPseudoBinaryMoleFractions(), RedlichKwongMFTP::calculateAB(), GibbsExcessVPSSTP::checkMFSum(), Phase::checkSpeciesArraySize(), Phase::checkSpeciesIndex(), HMWSoln::counterIJ_setup(), RedlichKwongMFTP::critDensity(), RedlichKwongMFTP::critPressure(), RedlichKwongMFTP::critTemperature(), ConstDensityThermo::expGibbs_RT(), IdealGasPhase::expGibbs_RT_ref(), IdealSolidSolnPhase::expGibbs_RT_ref(), MolalityVPSSTP::findCLMIndex(), GibbsExcessVPSSTP::getActivities(), IdealMolalSoln::getActivities(), DebyeHuckel::getActivities(), HMWSoln::getActivities(), ConstDensityThermo::getActivityCoefficients(), SingleSpeciesTP::getActivityCoefficients(), IdealSolnGasVPSS::getActivityCoefficients(), IonsFromNeutralVPSSTP::getActivityCoefficients(), GibbsExcessVPSSTP::getActivityCoefficients(), RedlichKwongMFTP::getActivityCoefficients(), LatticeSolidPhase::getActivityCoefficients(), MixedSolventElectrolyte::getActivityCoefficients(), PhaseCombo_Interaction::getActivityCoefficients(), IdealSolidSolnPhase::getActivityCoefficients(), ThermoPhase::getActivityCoefficients(), MolalityVPSSTP::getActivityCoefficients(), IdealGasPhase::getActivityCoefficients(), LatticePhase::getActivityCoefficients(), IdealSolnGasVPSS::getActivityConcentrations(), RedlichKwongMFTP::getActivityConcentrations(), IdealMolalSoln::getActivityConcentrations(), IdealSolidSolnPhase::getActivityConcentrations(), DebyeHuckel::getActivityConcentrations(), HMWSoln::getActivityConcentrations(), ConstDensityThermo::getChemPotentials(), SurfPhase::getChemPotentials(), MolarityIonicVPSSTP::getChemPotentials(), IdealSolnGasVPSS::getChemPotentials(), RedlichKwongMFTP::getChemPotentials(), RedlichKisterVPSSTP::getChemPotentials(), MargulesVPSSTP::getChemPotentials(), MixedSolventElectrolyte::getChemPotentials(), PhaseCombo_Interaction::getChemPotentials(), IdealSolidSolnPhase::getChemPotentials(), IdealMolalSoln::getChemPotentials(), IdealGasPhase::getChemPotentials(), LatticePhase::getChemPotentials(), DebyeHuckel::getChemPotentials(), HMWSoln::getChemPotentials(), VPStandardStateTP::getChemPotentials_RT(), MixtureFugacityTP::getChemPotentials_RT(), IdealSolnGasVPSS::getChemPotentials_RT(), RedlichKwongMFTP::getChemPotentials_RT(), IdealSolidSolnPhase::getChemPotentials_RT(), SurfPhase::getCoverages(), IdealSolidSolnPhase::getCp_R_ref(), RedlichKisterVPSSTP::getd2lnActCoeffdT2(), MargulesVPSSTP::getd2lnActCoeffdT2(), MixedSolventElectrolyte::getd2lnActCoeffdT2(), PhaseCombo_Interaction::getd2lnActCoeffdT2(), IonsFromNeutralVPSSTP::getdlnActCoeffdlnN(), PhaseCombo_Interaction::getdlnActCoeffdlnN(), RedlichKisterVPSSTP::getdlnActCoeffdlnN(), MargulesVPSSTP::getdlnActCoeffdlnN(), MixedSolventElectrolyte::getdlnActCoeffdlnN(), ThermoPhase::getdlnActCoeffdlnN(), IonsFromNeutralVPSSTP::getdlnActCoeffdlnN_diag(), PhaseCombo_Interaction::getdlnActCoeffdlnN_diag(), RedlichKisterVPSSTP::getdlnActCoeffdlnN_diag(), MargulesVPSSTP::getdlnActCoeffdlnN_diag(), MixedSolventElectrolyte::getdlnActCoeffdlnN_diag(), IonsFromNeutralVPSSTP::getdlnActCoeffdlnX_diag(), PhaseCombo_Interaction::getdlnActCoeffdlnX_diag(), RedlichKisterVPSSTP::getdlnActCoeffdlnX_diag(), MargulesVPSSTP::getdlnActCoeffdlnX_diag(), MixedSolventElectrolyte::getdlnActCoeffdlnX_diag(), IonsFromNeutralVPSSTP::getdlnActCoeffds(), PhaseCombo_Interaction::getdlnActCoeffds(), RedlichKisterVPSSTP::getdlnActCoeffds(), MargulesVPSSTP::getdlnActCoeffds(), MixedSolventElectrolyte::getdlnActCoeffds(), RedlichKisterVPSSTP::getdlnActCoeffdT(), MargulesVPSSTP::getdlnActCoeffdT(), MixedSolventElectrolyte::getdlnActCoeffdT(), PhaseCombo_Interaction::getdlnActCoeffdT(), PureFluidPhase::getElectrochemPotentials(), PseudoBinaryVPSSTP::getElectrochemPotentials(), MolarityIonicVPSSTP::getElectrochemPotentials(), GibbsExcessVPSSTP::getElectrochemPotentials(), RedlichKisterVPSSTP::getElectrochemPotentials(), MargulesVPSSTP::getElectrochemPotentials(), ThermoPhase::getElectrochemPotentials(), MixedSolventElectrolyte::getElectrochemPotentials(), MolalityVPSSTP::getElectrochemPotentials(), PhaseCombo_Interaction::getElectrochemPotentials(), IdealSolidSolnPhase::getEnthalpy_RT(), LatticePhase::getEnthalpy_RT(), IdealSolidSolnPhase::getEnthalpy_RT_ref(), MixtureFugacityTP::getEntropy_R(), IdealGasPhase::getEntropy_R(), IdealSolidSolnPhase::getEntropy_R_ref(), WaterSSTP::getGibbs_ref(), LatticeSolidPhase::getGibbs_ref(), IdealSolidSolnPhase::getGibbs_ref(), LatticePhase::getGibbs_ref(), MixtureFugacityTP::getGibbs_RT(), IdealGasPhase::getGibbs_RT(), IdealSolidSolnPhase::getGibbs_RT(), LatticePhase::getGibbs_RT(), IdealSolidSolnPhase::getGibbs_RT_ref(), LatticePhase::getGibbs_RT_ref(), MixtureFugacityTP::getIntEnergy_RT(), IdealGasPhase::getIntEnergy_RT(), IdealSolidSolnPhase::getIntEnergy_RT(), IdealGasPhase::getIntEnergy_RT_ref(), IdealSolidSolnPhase::getIntEnergy_RT_ref(), MolarityIonicVPSSTP::getLnActivityCoefficients(), RedlichKisterVPSSTP::getLnActivityCoefficients(), MargulesVPSSTP::getLnActivityCoefficients(), ThermoPhase::getLnActivityCoefficients(), MolalityVPSSTP::getMolalities(), IdealMolalSoln::getMolalityActivityCoefficients(), DebyeHuckel::getMolalityActivityCoefficients(), IonsFromNeutralVPSSTP::getNeutralMoleculeMoleGrads(), SurfPhase::getPartialMolarCp(), IdealSolnGasVPSS::getPartialMolarCp(), MolarityIonicVPSSTP::getPartialMolarCp(), RedlichKwongMFTP::getPartialMolarCp(), RedlichKisterVPSSTP::getPartialMolarCp(), MargulesVPSSTP::getPartialMolarCp(), MixedSolventElectrolyte::getPartialMolarCp(), PhaseCombo_Interaction::getPartialMolarCp(), IdealSolidSolnPhase::getPartialMolarCp(), IdealMolalSoln::getPartialMolarCp(), LatticePhase::getPartialMolarCp(), DebyeHuckel::getPartialMolarCp(), HMWSoln::getPartialMolarCp(), SurfPhase::getPartialMolarEnthalpies(), IdealSolnGasVPSS::getPartialMolarEnthalpies(), MolarityIonicVPSSTP::getPartialMolarEnthalpies(), IonsFromNeutralVPSSTP::getPartialMolarEnthalpies(), RedlichKwongMFTP::getPartialMolarEnthalpies(), RedlichKisterVPSSTP::getPartialMolarEnthalpies(), MargulesVPSSTP::getPartialMolarEnthalpies(), MixedSolventElectrolyte::getPartialMolarEnthalpies(), PhaseCombo_Interaction::getPartialMolarEnthalpies(), IdealMolalSoln::getPartialMolarEnthalpies(), DebyeHuckel::getPartialMolarEnthalpies(), HMWSoln::getPartialMolarEnthalpies(), SurfPhase::getPartialMolarEntropies(), IdealSolnGasVPSS::getPartialMolarEntropies(), MolarityIonicVPSSTP::getPartialMolarEntropies(), IonsFromNeutralVPSSTP::getPartialMolarEntropies(), RedlichKwongMFTP::getPartialMolarEntropies(), RedlichKisterVPSSTP::getPartialMolarEntropies(), MargulesVPSSTP::getPartialMolarEntropies(), MixedSolventElectrolyte::getPartialMolarEntropies(), PhaseCombo_Interaction::getPartialMolarEntropies(), IdealGasPhase::getPartialMolarEntropies(), IdealMolalSoln::getPartialMolarEntropies(), IdealSolidSolnPhase::getPartialMolarEntropies(), LatticePhase::getPartialMolarEntropies(), DebyeHuckel::getPartialMolarEntropies(), HMWSoln::getPartialMolarEntropies(), IdealSolnGasVPSS::getPartialMolarIntEnergies(), RedlichKwongMFTP::getPartialMolarIntEnergies(), IdealGasPhase::getPartialMolarIntEnergies(), MolarityIonicVPSSTP::getPartialMolarVolumes(), RedlichKwongMFTP::getPartialMolarVolumes(), RedlichKisterVPSSTP::getPartialMolarVolumes(), MargulesVPSSTP::getPartialMolarVolumes(), MixedSolventElectrolyte::getPartialMolarVolumes(), IdealGasPhase::getPartialMolarVolumes(), PhaseCombo_Interaction::getPartialMolarVolumes(), DebyeHuckel::getPartialMolarVolumes(), HMWSoln::getPartialMolarVolumes(), MixtureFugacityTP::getPureGibbs(), IdealGasPhase::getPureGibbs(), LatticePhase::getPureGibbs(), IdealSolidSolnPhase::getPureGibbs(), ThermoPhase::getReferenceComposition(), VPStandardStateTP::getStandardChemPotentials(), MixtureFugacityTP::getStandardChemPotentials(), IdealGasPhase::getStandardChemPotentials(), MixtureFugacityTP::getStandardVolumes(), SurfPhase::getStandardVolumes(), IdealGasPhase::getStandardVolumes(), MixtureFugacityTP::getStandardVolumes_ref(), IdealGasPhase::getStandardVolumes_ref(), HMWSoln::getUnscaledMolalityActivityCoefficients(), HMWSoln::HMWSoln(), Phase::init(), PseudoBinaryVPSSTP::initLengths(), IdealSolnGasVPSS::initLengths(), MolarityIonicVPSSTP::initLengths(), GibbsExcessVPSSTP::initLengths(), RedlichKwongMFTP::initLengths(), VPStandardStateTP::initLengths(), LatticeSolidPhase::initLengths(), IonsFromNeutralVPSSTP::initLengths(), MixtureFugacityTP::initLengths(), PhaseCombo_Interaction::initLengths(), RedlichKisterVPSSTP::initLengths(), MargulesVPSSTP::initLengths(), MixedSolventElectrolyte::initLengths(), MolalityVPSSTP::initLengths(), IdealMolalSoln::initLengths(), IdealSolidSolnPhase::initLengths(), DebyeHuckel::initLengths(), HMWSoln::initLengths(), ConstDensityThermo::initThermo(), SurfPhase::initThermo(), MolarityIonicVPSSTP::initThermo(), StoichSubstanceSSTP::initThermo(), VPStandardStateTP::initThermo(), LatticeSolidPhase::initThermo(), SingleSpeciesTP::initThermo(), IdealGasPhase::initThermo(), LatticePhase::initThermo(), ThermoPhase::initThermo(), RedlichKwongMFTP::initThermoXML(), VPStandardStateTP::initThermoXML(), IonsFromNeutralVPSSTP::initThermoXML(), IdealMolalSoln::initThermoXML(), LatticePhase::initThermoXML(), IdealSolidSolnPhase::initThermoXML(), DebyeHuckel::initThermoXML(), IdealSolidSolnPhase::logStandardConc(), Phase::nSpecies(), VPStandardStateTP::operator=(), Phase::operator=(), ThermoPhase::operator=(), MolalityVPSSTP::osmoticCoefficient(), HMWSoln::printCoeffs(), RedlichKwongMFTP::readXMLCrossFluid(), RedlichKwongMFTP::readXMLPureFluid(), IdealSolidSolnPhase::referenceConcentration(), HMWSoln::relative_enthalpy(), HMWSoln::relative_molal_enthalpy(), DebyeHuckel::s_update_d2lnMolalityActCoeff_dT2(), HMWSoln::s_update_d2lnMolalityActCoeff_dT2(), IonsFromNeutralVPSSTP::s_update_dlnActCoeff_dlnN(), PhaseCombo_Interaction::s_update_dlnActCoeff_dlnN(), MargulesVPSSTP::s_update_dlnActCoeff_dlnN(), MixedSolventElectrolyte::s_update_dlnActCoeff_dlnN(), IonsFromNeutralVPSSTP::s_update_dlnActCoeff_dlnN_diag(), PhaseCombo_Interaction::s_update_dlnActCoeff_dlnN_diag(), MargulesVPSSTP::s_update_dlnActCoeff_dlnN_diag(), MixedSolventElectrolyte::s_update_dlnActCoeff_dlnN_diag(), IonsFromNeutralVPSSTP::s_update_dlnActCoeff_dlnX_diag(), PhaseCombo_Interaction::s_update_dlnActCoeff_dlnX_diag(), MargulesVPSSTP::s_update_dlnActCoeff_dlnX_diag(), MixedSolventElectrolyte::s_update_dlnActCoeff_dlnX_diag(), PhaseCombo_Interaction::s_update_dlnActCoeff_dT(), RedlichKisterVPSSTP::s_update_dlnActCoeff_dT(), MargulesVPSSTP::s_update_dlnActCoeff_dT(), MixedSolventElectrolyte::s_update_dlnActCoeff_dT(), RedlichKisterVPSSTP::s_update_dlnActCoeff_dX_(), IonsFromNeutralVPSSTP::s_update_dlnActCoeffdT(), DebyeHuckel::s_update_dlnMolalityActCoeff_dP(), HMWSoln::s_update_dlnMolalityActCoeff_dP(), DebyeHuckel::s_update_dlnMolalityActCoeff_dT(), HMWSoln::s_update_dlnMolalityActCoeff_dT(), MolarityIonicVPSSTP::s_update_lnActCoeff(), IonsFromNeutralVPSSTP::s_update_lnActCoeff(), PhaseCombo_Interaction::s_update_lnActCoeff(), RedlichKisterVPSSTP::s_update_lnActCoeff(), MargulesVPSSTP::s_update_lnActCoeff(), MixedSolventElectrolyte::s_update_lnActCoeff(), DebyeHuckel::s_update_lnMolalityActCoeff(), HMWSoln::s_update_lnMolalityActCoeff(), IdealMolalSoln::s_updateIMS_lnMolalityActCoeff(), HMWSoln::s_updateIMS_lnMolalityActCoeff(), HMWSoln::s_updatePitzer_CoeffWRTemp(), HMWSoln::s_updatePitzer_d2lnMolalityActCoeff_dT2(), HMWSoln::s_updatePitzer_dlnMolalityActCoeff_dP(), HMWSoln::s_updatePitzer_dlnMolalityActCoeff_dT(), HMWSoln::s_updatePitzer_lnMolalityActCoeff(), HMWSoln::s_updateScaling_pHScaling(), HMWSoln::s_updateScaling_pHScaling_dP(), HMWSoln::s_updateScaling_pHScaling_dT(), HMWSoln::s_updateScaling_pHScaling_dT2(), Phase::setConcentrations(), SurfPhase::setCoverages(), SurfPhase::setCoveragesNoNorm(), Phase::setMassFractions(), Phase::setMassFractions_NoNorm(), MolalityVPSSTP::setMolalities(), Phase::setMoleFractions(), Phase::setMoleFractions_NoNorm(), ThermoPhase::setReferenceComposition(), MolalityVPSSTP::setSolvent(), IdealSolnGasVPSS::setToEquilState(), RedlichKwongMFTP::setToEquilState(), IdealGasPhase::setToEquilState(), IdealSolidSolnPhase::setToEquilState(), ThermoPhase::speciesData(), Phase::speciesIndex(), IdealSolidSolnPhase::standardConcentration(), RedlichKwongMFTP::updateAB(), and ThermoPhase::~ThermoPhase().
size_t m_ndim protected inherited
Dimensionality of the phase.
Volumetric phases have dimensionality 3 and surface phases have dimensionality 2.
Definition at line 731 of file Phase.h.
Referenced by Phase::nDim(), Phase::operator=(), and Phase::setNDim().
vector_fp m_speciesComp protected inherited
Atomic composition of the species.
The number of atoms of element i in species k is equal to m_speciesComp[k * m_mm + i] The length of this vector is equal to m_kk * m_mm
Definition at line 736 of file Phase.h.
Referenced by Phase::addUniqueElementAfterFreeze(), Phase::addUniqueSpecies(), Phase::getAtoms(), LatticeSolidPhase::installSlavePhases(), Phase::nAtoms(), and Phase::operator=().
vector_fp m_speciesSize protected inherited
Vector of species sizes.
length m_kk. Used in some equations of state which employ the constant partial molar volume approximation.
Definition at line 740 of file Phase.h.
Referenced by Phase::addUniqueSpecies(), DebyeHuckel::initLengths(), HMWSoln::initLengths(), MineralEQ3::initThermoXML(), DebyeHuckel::initThermoXML(), Phase::operator=(), Phase::size(), HMWSoln::speciesMolarVolume(), and DebyeHuckel::standardConcentration().
vector_fp m_speciesCharge protected inherited
Vector of species charges. length m_kk.
Definition at line 742 of file Phase.h.
Referenced by Phase::addUniqueSpecies(), HMWSoln::applyphScale(), HMWSoln::calcMolalitiesCropped(), MolarityIonicVPSSTP::calcPseudoBinaryMoleFractions(), Phase::charge(), IonsFromNeutralVPSSTP::getDissociationCoeffs(), MolarityIonicVPSSTP::initThermo(), DebyeHuckel::initThermoXML(), Phase::operator=(), HMWSoln::printCoeffs(), PhaseCombo_Interaction::readXMLBinarySpecies(), RedlichKisterVPSSTP::readXMLBinarySpecies(), MargulesVPSSTP::readXMLBinarySpecies(), MixedSolventElectrolyte::readXMLBinarySpecies(), HMWSoln::relative_molal_enthalpy(), DebyeHuckel::s_update_d2lnMolalityActCoeff_dT2(), DebyeHuckel::s_update_dlnMolalityActCoeff_dP(), DebyeHuckel::s_update_dlnMolalityActCoeff_dT(), DebyeHuckel::s_update_lnMolalityActCoeff(), HMWSoln::s_update_lnMolalityActCoeff(), HMWSoln::s_updatePitzer_CoeffWRTemp(), HMWSoln::s_updatePitzer_d2lnMolalityActCoeff_dT2(), HMWSoln::s_updatePitzer_dlnMolalityActCoeff_dP(), HMWSoln::s_updatePitzer_dlnMolalityActCoeff_dT(), HMWSoln::s_updatePitzer_lnMolalityActCoeff(), HMWSoln::s_updateScaling_pHScaling(), HMWSoln::s_updateScaling_pHScaling_dP(), HMWSoln::s_updateScaling_pHScaling_dT(), and HMWSoln::s_updateScaling_pHScaling_dT2().
The documentation for this class was generated from the following files:
HMWSoln.h
HMWSoln.cpp
HMWSoln_input.cpp