Cantera: Interface Class Reference
Interface Class Reference
An interface between multiple bulk phases.
#include <Interface.h>
Public Member Functions
Interface (std::string infile, std::string id, std::vector< Cantera::ThermoPhase * > otherPhases)
Constructor.
Interface (const Interface &ii)
Copy Constructor.
Interface & operator= (const Interface &right)
Assignment operator.
virtual ~Interface ()
Destructor. Does nothing.
bool operator! ()
Not operator.
bool ready () const
return whether the object has been instantiated
ThermoPhase * duplMyselfAsThermoPhase () const
Duplicator from the ThermoPhase parent class.
virtual int eosType () const
Equation of state type flag.
virtual doublereal enthalpy_mole () const
Return the Molar Enthalpy. Units: J/kmol.
virtual doublereal intEnergy_mole () const
Return the Molar Internal Energy. Units: J/kmol.
virtual void getChemPotentials (doublereal *mu) const
Get the species chemical potentials. Units: J/kmol.
virtual void getPartialMolarEnthalpies (doublereal *hbar) const
Returns an array of partial molar enthalpies for the species in the mixture.
virtual void getPartialMolarEntropies (doublereal *sbar) const
Returns an array of partial molar entropies of the species in the solution.
virtual void getPartialMolarCp (doublereal *cpbar) const
Return an array of partial molar heat capacities for the species in the mixture.
virtual void getPartialMolarVolumes (doublereal *vbar) const
Return an array of partial molar volumes for the species in the mixture.
virtual void getStandardChemPotentials (doublereal *mu0) const
Get the array of chemical potentials at unit activity for the standard state species at the current T and P of the solution.
virtual void getActivityConcentrations (doublereal *c) const
Return a vector of activity concentrations for each species.
virtual doublereal standardConcentration (size_t k=0) const
Return the standard concentration for the kth species.
virtual doublereal logStandardConc (size_t k=0) const
Return the log of the standard concentration for the kth species.
virtual void setParameters (int n, doublereal *const c)
Set the equation of state parameters from the argument list.
virtual void setParametersFromXML (const XML_Node &thermoData)
Set the Equation-of-State parameters by reading an XML Node Input.
virtual void initThermo ()
Initialize the SurfPhase object after all species have been set up.
virtual void setStateFromXML (const XML_Node &state)
Set the initial state of the Surface Phase from an XML_Node.
doublereal siteDensity ()
Returns the site density.
void setPotentialEnergy (int k, doublereal pe)
Sets the potential energy of species k.
doublereal potentialEnergy (int k)
Return the potential energy of species k.
void setSiteDensity (doublereal n0)
Set the site density of the surface phase (kmol m-2)
virtual void getGibbs_RT (doublereal *grt) const
Get the nondimensional Gibbs functions for the species in their standard states at the current T and P of the solution.
virtual void getEnthalpy_RT (doublereal *hrt) const
Get the nondimensional Enthalpy functions for the species standard states at their standard states at the current T and P of the solution.
virtual void getEntropy_R (doublereal *sr) const
Get the array of nondimensional Entropy functions for the species standard states at the current T and P of the solution.
virtual void getCp_R (doublereal *cpr) const
Get the nondimensional Heat Capacities at constant pressure for the species standard states at the current T and P of the solution.
virtual void getStandardVolumes (doublereal *vol) const
Get the molar volumes of the species standard states at the current T and P of the solution.
virtual doublereal pressure () const
Return the thermodynamic pressure (Pa).
virtual void setPressure (doublereal p)
Set the internally stored pressure (Pa) at constant temperature and composition.
virtual void getGibbs_RT_ref (doublereal *grt) const
Returns the vector of nondimensional Gibbs Free Energies of the reference state at the current temperature of the solution and the reference pressure for the species.
virtual void getEnthalpy_RT_ref (doublereal *hrt) const
Returns the vector of nondimensional enthalpies of the reference state at the current temperature of the solution and the reference pressure for the species.
virtual void getEntropy_R_ref (doublereal *er) const
Returns the vector of nondimensional entropies of the reference state at the current temperature of the solution and the reference pressure for each species.
virtual void getCp_R_ref (doublereal *cprt) const
Returns the vector of nondimensional constant pressure heat capacities of the reference state at the current temperature of the solution and reference pressure for each species.
void setCoverages (const doublereal *theta)
Set the surface site fractions to a specified state.
void setCoveragesNoNorm (const doublereal *theta)
Set the surface site fractions to a specified state.
void setCoveragesByName (std::string cov)
Set the coverages from a string of colon-separated name:value pairs.
void getCoverages (doublereal *theta) const
Return a vector of surface coverages.
doublereal _RT () const
Return the Gas Constant multiplied by the current temperature.
XML_Node & xml ()
Returns a reference to the XML_Node stored for the phase.
void saveState (vector_fp &state) const
Save the current internal state of the phase Write to vector 'state' the current internal state.
void saveState (size_t lenstate, doublereal *state) const
Write to array 'state' the current internal state.
void restoreState (const vector_fp &state)
Restore a state saved on a previous call to saveState.
void restoreState (size_t lenstate, const doublereal *state)
Restore the state of the phase from a previously saved state vector.
doublereal molecularWeight (size_t k) const
Molecular weight of species k.
doublereal molarMass (size_t k) const
Return the Molar mass of species k Alternate name for molecular weight.
void getMolecularWeights (vector_fp &weights) const
Copy the vector of molecular weights into vector weights.
void getMolecularWeights (int iwt, doublereal *weights) const
Copy the vector of molecular weights into array weights.
void getMolecularWeights (doublereal *weights) const
Copy the vector of molecular weights into array weights.
const vector_fp & molecularWeights () const
Return a const reference to the internal vector of molecular weights.
doublereal size (size_t k) const
This routine returns the size of species k.
doublereal charge (size_t k) const
Dimensionless electrical charge of a single molecule of species k The charge is normalized by the the magnitude of the electron charge.
doublereal chargeDensity () const
Charge density [C/m^3].
size_t nDim () const
Returns the number of spatial dimensions (1, 2, or 3)
void setNDim (size_t ndim)
Set the number of spatial dimensions (1, 2, or 3).
virtual void freezeSpecies ()
Call when finished adding species.
bool speciesFrozen ()
True if freezeSpecies has been called.
int stateMFNumber () const
Return the State Mole Fraction Number.
void stateMFChangeCalc (bool forceChange=false)
Every time the mole fractions have changed, this routine will increment the stateMFNumber.
virtual Kinetics * duplMyselfAsKinetics (const std::vector< thermo_t * > &tpVector) const
Duplication routine for objects which inherit from Kinetics.
virtual int ID () const
Return the ID of the kinetics object.
virtual int type () const
Return the type of the kinetics object.
void setElectricPotential (int n, doublereal V)
Set the electric potential in the nth phase.
void incrementRxnCount ()
Increment the number of reactions in the mechanism by one.
void selectPhase (const doublereal *data, const thermo_t *phase, doublereal *phase_data)
Extract from array data the portion pertaining to phase phase.
Information Methods
virtual doublereal refPressure () const
Returns the reference pressure in Pa.
virtual doublereal minTemp (size_t k=npos) const
Minimum temperature for which the thermodynamic data for the species or phase are valid.
doublereal Hf298SS (const int k) const
Report the 298 K Heat of Formation of the standard state of one species (J kmol-1)
virtual void modifyOneHf298SS (const int k, const doublereal Hf298New)
Modify the value of the 298 K Heat of Formation of one species in the phase (J kmol-1)
virtual doublereal maxTemp (size_t k=npos) const
Maximum temperature for which the thermodynamic data for the species are valid.
bool chargeNeutralityNecessary () const
Returns the chargeNeutralityNecessity boolean.
Molar Thermodynamic Properties of the Solution
virtual doublereal entropy_mole () const
Molar entropy. Units: J/kmol/K.
virtual doublereal gibbs_mole () const
Molar Gibbs function. Units: J/kmol.
virtual doublereal cp_mole () const
Molar heat capacity at constant pressure. Units: J/kmol/K.
virtual doublereal cv_mole () const
Molar heat capacity at constant volume. Units: J/kmol/K.
Mechanical Properties
virtual doublereal isothermalCompressibility () const
Returns the isothermal compressibility. Units: 1/Pa.
virtual doublereal thermalExpansionCoeff () const
Return the volumetric thermal expansion coefficient. Units: 1/K.
virtual void updateDensity ()
Electric Potential
The phase may be at some non-zero electrical potential.
These methods set or get the value of the electric potential.
void setElectricPotential (doublereal v)
Set the electric potential of this phase (V).
doublereal electricPotential () const
Returns the electric potential of this phase (V).
Activities, Standard States, and Activity Concentrations
The activity \(a_k\) of a species in solution is related to the chemical potential by
\[ \mu_k = \mu_k^0(T,P) + \hat R T \log a_k. \]
The quantity \(\mu_k^0(T,P)\) is the standard chemical potential at unit activity, which depends on temperature and pressure, but not on composition.
The activity is dimensionless.
virtual int activityConvention () const
This method returns the convention used in specification of the activities, of which there are currently two, molar- and molality-based conventions.
virtual int standardStateConvention () const
This method returns the convention used in specification of the standard state, of which there are currently two, temperature based, and variable pressure based.
virtual void getUnitsStandardConc (double *uA, int k=0, int sizeUA=6) const
Returns the units of the standard and generalized concentrations.
virtual void getActivities (doublereal *a) const
Get the array of non-dimensional activities at the current solution temperature, pressure, and solution concentration.
virtual void getActivityCoefficients (doublereal *ac) const
Get the array of non-dimensional molar-based activity coefficients at the current solution temperature, pressure, and solution concentration.
virtual void getLnActivityCoefficients (doublereal *lnac) const
Get the array of non-dimensional molar-based ln activity coefficients at the current solution temperature, pressure, and solution concentration.
Partial Molar Properties of the Solution
virtual void getChemPotentials_RT (doublereal *mu) const
Get the array of non-dimensional species chemical potentials These are partial molar Gibbs free energies.
void getElectrochemPotentials (doublereal *mu) const
Get the species electrochemical potentials.
virtual void getPartialMolarIntEnergies (doublereal *ubar) const
Return an array of partial molar internal energies for the species in the mixture.
virtual void getdPartialMolarVolumes_dT (doublereal *d_vbar_dT) const
Return an array of derivatives of partial molar volumes wrt temperature for the species in the mixture.
virtual void getdPartialMolarVolumes_dP (doublereal *d_vbar_dP) const
Return an array of derivatives of partial molar volumes wrt pressure for the species in the mixture.
Properties of the Standard State of the Species in the Solution
virtual void getPureGibbs (doublereal *gpure) const
Get the Gibbs functions for the standard state of the species at the current T and P of the solution.
virtual void getIntEnergy_RT (doublereal *urt) const
Returns the vector of nondimensional Internal Energies of the standard state species at the current T and P of the solution.
virtual void getdStandardVolumes_dT (doublereal *d_vol_dT) const
Get the derivative of the molar volumes of the species standard states wrt temperature at the current T and P of the solution.
virtual void getdStandardVolumes_dP (doublereal *d_vol_dP) const
Get the derivative molar volumes of the species standard states wrt pressure at the current T and P of the solution.
Thermodynamic Values for the Species Reference States
virtual void getGibbs_ref (doublereal *g) const
Returns the vector of the gibbs function of the reference state at the current temperature of the solution and the reference pressure for the species.
virtual void getIntEnergy_RT_ref (doublereal *urt) const
Returns the vector of nondimensional internal Energies of the reference state at the current temperature of the solution and the reference pressure for each species.
virtual void getStandardVolumes_ref (doublereal *vol) const
Get the molar volumes of the species reference states at the current T and P_ref of the solution.
virtual void setReferenceComposition (const doublereal *const x)
Sets the reference composition.
virtual void getReferenceComposition (doublereal *const x) const
Gets the reference composition.
Specific Properties
doublereal enthalpy_mass () const
Specific enthalpy.
doublereal intEnergy_mass () const
Specific internal energy.
doublereal entropy_mass () const
Specific entropy.
doublereal gibbs_mass () const
Specific Gibbs function.
doublereal cp_mass () const
Specific heat at constant pressure.
doublereal cv_mass () const
Specific heat at constant volume.
Setting the State
These methods set all or part of the thermodynamic state.
virtual void setState_TPX (doublereal t, doublereal p, const doublereal *x)
Set the temperature (K), pressure (Pa), and mole fractions.
void setState_TPX (doublereal t, doublereal p, compositionMap &x)
Set the temperature (K), pressure (Pa), and mole fractions.
void setState_TPX (doublereal t, doublereal p, const std::string &x)
Set the temperature (K), pressure (Pa), and mole fractions.
void setState_TPY (doublereal t, doublereal p, const doublereal *y)
Set the internally stored temperature (K), pressure (Pa), and mass fractions of the phase.
void setState_TPY (doublereal t, doublereal p, compositionMap &y)
Set the internally stored temperature (K), pressure (Pa), and mass fractions of the phase.
void setState_TPY (doublereal t, doublereal p, const std::string &y)
Set the internally stored temperature (K), pressure (Pa), and mass fractions of the phase.
void setState_TP (doublereal t, doublereal p)
Set the temperature (K) and pressure (Pa)
void setState_PX (doublereal p, doublereal *x)
Set the pressure (Pa) and mole fractions.
void setState_PY (doublereal p, doublereal *y)
Set the internally stored pressure (Pa) and mass fractions.
virtual void setState_HP (doublereal h, doublereal p, doublereal tol=1.e-4)
Set the internally stored specific enthalpy (J/kg) and pressure (Pa) of the phase.
virtual void setState_UV (doublereal u, doublereal v, doublereal tol=1.e-4)
Set the specific internal energy (J/kg) and specific volume (m^3/kg).
virtual void setState_SP (doublereal s, doublereal p, doublereal tol=1.e-4)
Set the specific entropy (J/kg/K) and pressure (Pa).
virtual void setState_SV (doublereal s, doublereal v, doublereal tol=1.e-4)
Set the specific entropy (J/kg/K) and specific volume (m^3/kg).
Chemical Equilibrium
Chemical equilibrium.
virtual void setToEquilState (const doublereal *lambda_RT)
This method is used by the ChemEquil equilibrium solver.
void setElementPotentials (const vector_fp &lambda)
Stores the element potentials in the ThermoPhase object.
bool getElementPotentials (doublereal *lambda) const
Returns the element potentials stored in the ThermoPhase object.
Critical State Properties.
These methods are only implemented by some subclasses, and may be moved out of ThermoPhase at a later date.
virtual doublereal critTemperature () const
Critical temperature (K).
virtual doublereal critPressure () const
Critical pressure (Pa).
virtual doublereal critDensity () const
Critical density (kg/m3).
Saturation Properties.
These methods are only implemented by subclasses that implement full liquid-vapor equations of state.
They may be moved out of ThermoPhase at a later date.
virtual doublereal satTemperature (doublereal p) const
Return the saturation temperature given the pressure.
virtual doublereal satPressure (doublereal t) const
Return the saturation pressure given the temperature.
virtual doublereal vaporFraction () const
Return the fraction of vapor at the current conditions.
virtual void setState_Tsat (doublereal t, doublereal x)
Set the state to a saturated system at a particular temperature.
virtual void setState_Psat (doublereal p, doublereal x)
Set the state to a saturated system at a particular pressure.
Initialization Methods - For Internal Use (ThermoPhase)
void saveSpeciesData (const size_t k, const XML_Node *const data)
Store a reference pointer to the XML tree containing the species data for this phase.
const std::vector< const
XML_Node * > & speciesData () const
Return a pointer to the vector of XML nodes containing the species data for this phase.
void setSpeciesThermo (SpeciesThermo *spthermo)
Install a species thermodynamic property manager.
virtual SpeciesThermo & speciesThermo (int k=-1)
Return a changeable reference to the calculation manager for species reference-state thermodynamic properties.
virtual void initThermoFile (std::string inputFile, std::string id)
virtual void initThermoXML (XML_Node &phaseNode, std::string id)
Import and initialize a ThermoPhase object using an XML tree.
virtual void installSlavePhases (Cantera::XML_Node *phaseNode)
Add in species from Slave phases.
virtual void getParameters (int &n, doublereal *const c) const
Get the equation of state parameters in a vector.
Derivatives of Thermodynamic Variables needed for Applications
virtual void getdlnActCoeffds (const doublereal dTds, const doublereal *const dXds, doublereal *dlnActCoeffds) const
Get the change in activity coefficients wrt changes in state (temp, mole fraction, etc) along a line in parameter space or along a line in physical space.
virtual void getdlnActCoeffdlnX_diag (doublereal *dlnActCoeffdlnX_diag) const
Get the array of ln mole fraction derivatives of the log activity coefficients - diagonal component only.
virtual void getdlnActCoeffdlnN_diag (doublereal *dlnActCoeffdlnN_diag) const
Get the array of log species mole number derivatives of the log activity coefficients.
virtual void getdlnActCoeffdlnN (const size_t ld, doublereal *const dlnActCoeffdlnN)
Get the array of derivatives of the log activity coefficients with respect to the log of the species mole numbers.
virtual void getdlnActCoeffdlnN_numderiv (const size_t ld, doublereal *const dlnActCoeffdlnN)
Printing
virtual std::string report (bool show_thermo=true) const
returns a summary of the state of the phase as a string
virtual void reportCSV (std::ofstream &csvFile) const
returns a summary of the state of the phase to a comma separated file
Name and ID
Class Phase contains two strings that identify a phase. The ID is the value of the ID attribute of the XML phase node that is used to initialize a phase when it is read. The name field is also initialized to the value of the ID attribute of the XML phase node.
However, the name field may be changed to another value during the course of a calculation. For example, if a phase is located in two places, but has the same constitutive input, the ids of the two phases will be the same, but the names of the two phases may be different.
It is an error to have two phases in a single problem with the same name or the same id (or the name from one phase being the same as the id of another phase). Thus, it is expected that there is a 1-1 correspondence between names and unique phases within a Cantera problem.
std::string id () const
Return the string id for the phase.
void setID (std::string id)
Set the string id for the phase.
std::string name () const
Return the name of the phase.
void setName (std::string nm)
Sets the string name for the phase.
Element and Species Information
std::string elementName (size_t m) const
Name of the element with index m.
size_t elementIndex (std::string name) const
Return the index of element named 'name'.
const std::vector< std::string > & elementNames () const
Return a read-only reference to the vector of element names.
doublereal atomicWeight (size_t m) const
Atomic weight of element m.
doublereal entropyElement298 (size_t m) const
Entropy of the element in its standard state at 298 K and 1 bar.
int atomicNumber (size_t m) const
Atomic number of element m.
int elementType (size_t m) const
Return the element constraint type Possible types include:
int changeElementType (int m, int elem_type)
Change the element type of the mth constraint Reassigns an element type.
const vector_fp & atomicWeights () const
Return a read-only reference to the vector of atomic weights.
size_t nElements () const
Number of elements.
void checkElementIndex (size_t m) const
Check that the specified element index is in range Throws an exception if m is greater than nElements()-1.
void checkElementArraySize (size_t mm) const
Check that an array size is at least nElements() Throws an exception if mm is less than nElements().
doublereal nAtoms (size_t k, size_t m) const
Number of atoms of element m in species k.
void getAtoms (size_t k, double *atomArray) const
Get a vector containing the atomic composition of species k.
size_t speciesIndex (std::string name) const
Returns the index of a species named 'name' within the Phase object.
std::string speciesName (size_t k) const
Name of the species with index k.
std::string speciesSPName (int k) const
Returns the expanded species name of a species, including the phase name This is guaranteed to be unique within a Cantera problem.
const std::vector< std::string > & speciesNames () const
Return a const reference to the vector of species names.
size_t nSpecies () const
Returns the number of species in the phase.
void checkSpeciesIndex (size_t k) const
Check that the specified species index is in range Throws an exception if k is greater than nSpecies()-1.
void checkSpeciesArraySize (size_t kk) const
Check that an array size is at least nSpecies() Throws an exception if kk is less than nSpecies().
Set thermodynamic state
Set the internal thermodynamic state by setting the internally stored temperature, density and species composition. Note that the composition is always set first.
Temperature and density are held constant if not explicitly set.
void setMoleFractionsByName (compositionMap &xMap)
Set the species mole fractions by name.
void setMoleFractionsByName (const std::string &x)
Set the mole fractions of a group of species by name.
void setMassFractionsByName (compositionMap &yMap)
Set the species mass fractions by name.
void setMassFractionsByName (const std::string &x)
Set the species mass fractions by name.
void setState_TRX (doublereal t, doublereal dens, const doublereal *x)
Set the internally stored temperature (K), density, and mole fractions.
void setState_TRX (doublereal t, doublereal dens, compositionMap &x)
Set the internally stored temperature (K), density, and mole fractions.
void setState_TRY (doublereal t, doublereal dens, const doublereal *y)
Set the internally stored temperature (K), density, and mass fractions.
void setState_TRY (doublereal t, doublereal dens, compositionMap &y)
Set the internally stored temperature (K), density, and mass fractions.
void setState_TNX (doublereal t, doublereal n, const doublereal *x)
Set the internally stored temperature (K), molar density (kmol/m^3), and mole fractions.
void setState_TR (doublereal t, doublereal rho)
Set the internally stored temperature (K) and density (kg/m^3)
void setState_TX (doublereal t, doublereal *x)
Set the internally stored temperature (K) and mole fractions.
void setState_TY (doublereal t, doublereal *y)
Set the internally stored temperature (K) and mass fractions.
void setState_RX (doublereal rho, doublereal *x)
Set the density (kg/m^3) and mole fractions.
void setState_RY (doublereal rho, doublereal *y)
Set the density (kg/m^3) and mass fractions.
Composition
void getMoleFractionsByName (compositionMap &x) const
Get the mole fractions by name.
doublereal moleFraction (size_t k) const
Return the mole fraction of a single species.
doublereal moleFraction (std::string name) const
Return the mole fraction of a single species.
doublereal massFraction (size_t k) const
Return the mass fraction of a single species.
doublereal massFraction (std::string name) const
Return the mass fraction of a single species.
void getMoleFractions (doublereal *const x) const
Get the species mole fraction vector.
virtual void setMoleFractions (const doublereal *const x)
Set the mole fractions to the specified values There is no restriction on the sum of the mole fraction vector.
virtual void setMoleFractions_NoNorm (const doublereal *const x)
Set the mole fractions to the specified values without normalizing.
void getMassFractions (doublereal *const y) const
Get the species mass fractions.
const doublereal * massFractions () const
Return a const pointer to the mass fraction array.
virtual void setMassFractions (const doublereal *const y)
Set the mass fractions to the specified values and normalize them.
virtual void setMassFractions_NoNorm (const doublereal *const y)
Set the mass fractions to the specified values without normalizing.
void getConcentrations (doublereal *const c) const
Get the species concentrations (kmol/m^3).
doublereal concentration (const size_t k) const
Concentration of species k.
virtual void setConcentrations (const doublereal *const conc)
Set the concentrations to the specified values within the phase.
const doublereal * moleFractdivMMW () const
Returns a const pointer to the start of the moleFraction/MW array.
Thermodynamic Properties
doublereal temperature () const
Temperature (K).
virtual doublereal density () const
Density (kg/m^3).
doublereal molarDensity () const
Molar density (kmol/m^3).
doublereal molarVolume () const
Molar volume (m^3/kmol).
virtual void setDensity (const doublereal density)
Set the internally stored density (kg/m^3) of the phase Note the density of a phase is an independent variable.
virtual void setMolarDensity (const doublereal molarDensity)
Set the internally stored molar density (kmol/m^3) of the phase.
virtual void setTemperature (const doublereal temp)
Set the internally stored temperature of the phase (K).
Mean Properties
doublereal mean_X (const doublereal *const Q) const
Evaluate the mole-fraction-weighted mean of an array Q.
doublereal mean_Y (const doublereal *const Q) const
Evaluate the mass-fraction-weighted mean of an array Q.
doublereal meanMolecularWeight () const
The mean molecular weight. Units: (kg/kmol)
doublereal sum_xlogx () const
Evaluate \(\sum_k X_k \log X_k \).
doublereal sum_xlogQ (doublereal *const Q) const
Evaluate \(\sum_k X_k \log Q_k \).
Adding Elements and Species
These methods are used to add new elements or species.
These are not usually called by user programs.
Since species are checked to insure that they are only composed of declared elements, it is necessary to first add all elements before adding any species.
void addElement (const std::string &symbol, doublereal weight=-12345.0)
Add an element.
void addElement (const XML_Node &e)
Add an element from an XML specification.
void addUniqueElement (const std::string &symbol, doublereal weight=-12345.0, int atomicNumber=0, doublereal entropy298=ENTROPY298_UNKNOWN, int elem_type=CT_ELEM_TYPE_ABSPOS)
Add an element, checking for uniqueness The uniqueness is checked by comparing the string symbol.
void addUniqueElement (const XML_Node &e)
Add an element, checking for uniqueness The uniqueness is checked by comparing the string symbol.
void addElementsFromXML (const XML_Node &phase)
Add all elements referenced in an XML_Node tree.
void freezeElements ()
Prohibit addition of more elements, and prepare to add species.
bool elementsFrozen ()
True if freezeElements has been called.
size_t addUniqueElementAfterFreeze (const std::string &symbol, doublereal weight, int atomicNumber, doublereal entropy298=ENTROPY298_UNKNOWN, int elem_type=CT_ELEM_TYPE_ABSPOS)
Add an element after elements have been frozen, checking for uniqueness The uniqueness is checked by comparing the string symbol.
void addSpecies (const std::string &name, const doublereal *comp, doublereal charge=0.0, doublereal size=1.0)
void addUniqueSpecies (const std::string &name, const doublereal *comp, doublereal charge=0.0, doublereal size=1.0)
Add a species to the phase, checking for uniqueness of the name This routine checks for uniqueness of the string name.
Reaction Rates Of Progress
virtual void getFwdRatesOfProgress (doublereal *fwdROP)
Return the forward rates of progress for each reaction.
virtual void getRevRatesOfProgress (doublereal *revROP)
Return the reverse rates of progress for each reaction.
virtual void getNetRatesOfProgress (doublereal *netROP)
Return the net rates of progress for each reaction.
virtual void getEquilibriumConstants (doublereal *kc)
Get the equilibrium constants of all reactions, whether the reaction is reversible or not.
void getExchangeCurrentQuantities ()
virtual void getDeltaGibbs (doublereal *deltaG)
Return the vector of values for the reaction gibbs free energy change.
virtual void getDeltaElectrochemPotentials (doublereal *deltaM)
Return the vector of values for the reaction electrochemical free energy change.
virtual void getDeltaEnthalpy (doublereal *deltaH)
Return the vector of values for the reactions change in enthalpy.
virtual void getDeltaEntropy (doublereal *deltaS)
Return the vector of values for the change in entropy due to each reaction.
virtual void getDeltaSSGibbs (doublereal *deltaG)
Return the vector of values for the reaction standard state gibbs free energy change.
virtual void getDeltaSSEnthalpy (doublereal *deltaH)
Return the vector of values for the change in the standard state enthalpies of reaction.
virtual void getDeltaSSEntropy (doublereal *deltaS)
Return the vector of values for the change in the standard state entropies for each reaction.
Species Production Rates
virtual void getCreationRates (doublereal *cdot)
Returns the Species creation rates [kmol/m^2/s].
virtual void getDestructionRates (doublereal *ddot)
Return the Species destruction rates [kmol/m^2/s].
virtual void getNetProductionRates (doublereal *net)
Return the species net production rates [kmol/m^2/s].
Reaction Mechanism Informational Query Routines
virtual doublereal reactantStoichCoeff (size_t k, size_t i) const
Stoichiometric coefficient of species k as a reactant in reaction i.
virtual doublereal productStoichCoeff (size_t k, size_t i) const
Stoichiometric coefficient of species k as a product in reaction i.
virtual int reactionType (size_t i) const
Flag specifying the type of reaction.
virtual void getActivityConcentrations (doublereal *const conc)
Get the vector of activity concentrations used in the kinetics object.
doublereal electrochem_beta (size_t irxn) const
Return the charge transfer rxn Beta parameter for the ith reaction.
virtual bool isReversible (size_t i)
True if reaction i has been declared to be reversible.
virtual std::string reactionString (size_t i) const
Return a string representing the reaction.
virtual void getFwdRateConstants (doublereal *kfwd)
Update the rates of progress of the reactions in the reaction mechanism.
virtual void getRevRateConstants (doublereal *krev, bool doIrreversible=false)
Update the rates of progress of the reactions in the reaction mechanism.
virtual void getActivationEnergies (doublereal *E)
Return the activation energies in Kelvin.
Constructors and General Information about Mechanism
virtual void assignShallowPointers (const std::vector< thermo_t * > &tpVector)
Reassign the shallow pointers within the FKinetics object.
size_t nReactions () const
Number of reactions in the reaction mechanism.
void checkReactionIndex (size_t m) const
Check that the specified reaction index is in range Throws an exception if i is greater than nReactions()
void checkReactionArraySize (size_t ii) const
Check that an array size is at least nReactions() Throws an exception if ii is less than nReactions().
void checkSpeciesIndex (size_t k) const
Check that the specified species index is in range Throws an exception if k is greater than nSpecies()-1.
void checkSpeciesArraySize (size_t mm) const
Check that an array size is at least nSpecies() Throws an exception if kk is less than nSpecies().
Information/Lookup Functions about Phases and Species
size_t nPhases () const
The number of phases participating in the reaction mechanism.
void checkPhaseIndex (size_t m) const
Check that the specified phase index is in range Throws an exception if m is greater than nPhases()
void checkPhaseArraySize (size_t mm) const
Check that an array size is at least nPhases() Throws an exception if mm is less than nPhases().
size_t phaseIndex (std::string ph)
Return the phase index of a phase in the list of phases defined within the object.
size_t surfacePhaseIndex ()
This returns the integer index of the phase which has ThermoPhase type cSurf.
size_t reactionPhaseIndex ()
Phase where the reactions occur.
thermo_t & thermo (size_t n=0)
This method returns a reference to the nth ThermoPhase object defined in this kinetics mechanism.
const thermo_t & thermo (size_t n=0) const
thermo_t & phase (size_t n=0)
This method returns a reference to the nth ThermoPhase defined in this kinetics mechanism.
const thermo_t & phase (size_t n=0) const
This method returns a reference to the nth ThermoPhase defined in this kinetics mechanism.
size_t nTotalSpecies () const
The total number of species in all phases participating in the kinetics mechanism.
size_t start (size_t n)
Returns the starting index of the species in the nth phase associated with the reaction mechanism.
size_t kineticsSpeciesIndex (size_t k, size_t n) const
The location of species k of phase n in species arrays.
size_t kineticsSpeciesIndex (const std::string &nm) const
This routine will look up a species number based on the input std::string nm.
size_t kineticsSpeciesIndex (const std::string &nm, const std::string &ph) const
This routine will look up a species number based on the input std::string nm.
std::string kineticsSpeciesName (size_t k) const
Return the std::string name of the kth species in the kinetics manager.
thermo_t & speciesPhase (std::string nm)
This function looks up the std::string name of a species and returns a reference to the ThermoPhase object of the phase where the species resides.
thermo_t & speciesPhase (size_t k)
This function takes as an argument the kineticsSpecies index (i.e., the list index in the list of species in the kinetics manager) and returns the species' owning ThermoPhase object.
size_t speciesPhaseIndex (size_t k)
This function takes as an argument the kineticsSpecies index (i.e., the list index in the list of species in the kinetics manager) and returns the index of the phase owning the species.
Reaction Rates Of Progress
virtual void getReactionDelta (const doublereal *property, doublereal *deltaProperty)
Change in species properties.
Reaction Mechanism Informational Query Routines
virtual doublereal reactantOrder (size_t k, size_t i) const
Reactant order of species k in reaction i.
virtual doublereal productOrder (int k, int i) const
product Order of species k in reaction i.
virtual const std::vector
< size_t > & reactants (size_t i) const
Returns a read-only reference to the vector of reactant index numbers for reaction i.
virtual const std::vector
< size_t > & products (size_t i) const
Returns a read-only reference to the vector of product index numbers for reaction i.
Reaction Mechanism Construction
virtual const std::vector
< grouplist_t > & reactantGroups (size_t i)
virtual const std::vector
< grouplist_t > & productGroups (size_t i)
Altering Reaction Rates
These methods alter reaction rates.
They are designed primarily for carrying out sensitivity analysis, but may be used for any purpose requiring dynamic alteration of rate constants. For each reaction, a real-valued multiplier may be defined that multiplies the reaction rate coefficient. The multiplier may be set to zero to completely remove a reaction from the mechanism.
doublereal multiplier (size_t i) const
The current value of the multiplier for reaction i.
void setMultiplier (size_t i, doublereal f)
Set the multiplier for reaction i to f.
Protected Member Functions
void init (const vector_fp &mw)
void setMolecularWeight (const int k, const double mw)
Set the molecular weight of a single species to a given value.
Protected Attributes
bool m_ok
Flag indicating that the object has been instantiated.
Cantera::XML_Node * m_r
XML_Node pointer to the XML File object that contains the Surface and the Interfacial Reaction object description.
doublereal m_n0
Surface site density (kmol m-2)
doublereal m_logn0
log of the surface site density
doublereal m_tmin
Minimum temperature for valid species standard state thermo props.
doublereal m_tmax
Maximum temperature for valid species standard state thermo props.
doublereal m_press
Current value of the pressure (Pa)
doublereal m_tlast
Current value of the temperature (Kelvin)
vector_fp m_h0
Temporary storage for the reference state enthalpies.
vector_fp m_s0
Temporary storage for the reference state entropies.
vector_fp m_cp0
Temporary storage for the reference state heat capacities.
vector_fp m_mu0
Temporary storage for the reference state gibbs energies.
vector_fp m_work
Temporary work array.
vector_fp m_pe
Potential energy of each species in the surface phase.
vector_fp m_logsize
vector storing the log of the size of each species.
SpeciesThermo * m_spthermo
Pointer to the calculation manager for species reference-state thermodynamic properties.
std::vector< const XML_Node * > m_speciesData
Vector of pointers to the species databases.
doublereal m_phi
Stored value of the electric potential for this phase.
vector_fp m_lambdaRRT
Vector of element potentials.
bool m_hasElementPotentials
Boolean indicating whether there is a valid set of saved element potentials for this phase.
bool m_chargeNeutralityNecessary
Boolean indicating whether a charge neutrality condition is a necessity.
int m_ssConvention
Contains the standard state convention.
std::vector< doublereal > xMol_Ref
Reference Mole Fraction Composition.
size_t m_kk
Number of species in the phase.
size_t m_ndim
Dimensionality of the phase.
vector_fp m_speciesComp
Atomic composition of the species.
vector_fp m_speciesSize
Vector of species sizes.
vector_fp m_speciesCharge
Vector of species charges. length m_kk.
size_t m_ii
Number of reactions in the mechanism.
size_t m_kk
The number of species in all of the phases that participate in this kinetics mechanism.
vector_fp m_perturb
Vector of perturbation factors for each reaction's rate of progress vector.
std::vector< std::vector
< size_t > > m_reactants
This is a vector of vectors containing the reactants for each reaction.
std::vector< std::vector
< size_t > > m_products
This is a vector of vectors containing the products for each reaction.
std::vector< thermo_t * > m_thermo
m_thermo is a vector of pointers to ThermoPhase objects that are involved with this kinetics operator
std::vector< size_t > m_start
m_start is a vector of integers specifying the beginning position for the species vector for the n'th phase in the kinetics class.
std::map< std::string, size_t > m_phaseindex
Mapping of the phase id, i.e., the id attribute in the xml phase element to the position of the phase within the kinetics object.
size_t m_surfphase
Index in the list of phases of the one surface phase.
size_t m_rxnphase
Phase Index where reactions are assumed to be taking place.
size_t m_mindim
number of spatial dimensions of lowest-dimensional phase.
Reaction Mechanism Construction
vector_fp m_grt
Temporary work vector of length m_kk.
std::vector< size_t > m_revindex
List of reactions numbers which are reversible reactions.
Rate1< SurfaceArrhenius > m_rates
Templated class containing the vector of reactions for this interface.
bool m_redo_rates
std::map< size_t, std::pair
< int, size_t > > m_index
Vector of information about reactions in the mechanism.
std::vector< size_t > m_irrev
Vector of irreversible reaction numbers.
ReactionStoichMgr m_rxnstoich
Stoichiometric manager for the reaction mechanism.
size_t m_nirrev
Number of irreversible reactions in the mechanism.
size_t m_nrev
Number of reversible reactions in the mechanism.
std::vector< std::map< size_t,
doublereal > > m_rrxn
m_rrxn is a vector of maps, containing the reactant stoichiometric coefficient information
std::vector< std::map< size_t,
doublereal > > m_prxn
m_prxn is a vector of maps, containing the reactant stoichiometric coefficient information
std::vector< std::string > m_rxneqn
String expression for each rxn.
InterfaceKineticsData * m_kdata
Temporary data storage used in calculating the rates of of reactions.
vector_fp m_conc
an array of generalized concentrations for each species
vector_fp m_mu0
Vector of standard state chemical potentials.
vector_fp m_phi
Vector of phase electric potentials.
vector_fp m_pot
Vector of potential energies due to Voltages.
vector_fp m_rwork
Vector temporary.
vector_fp m_E
Vector of raw activation energies for the reactions.
SurfPhase * m_surf
Pointer to the single surface phase.
ImplicitSurfChem * m_integrator
Pointer to the Implicit surface chemistry object.
vector_fp m_beta
std::vector< size_t > m_ctrxn
Vector of reaction indexes specifying the id of the current transfer reactions in the mechanism.
vector_int m_ctrxn_ecdf
Vector of booleans indicating whether the charge transfer reaction may be described by an exchange current density expression.
vector_fp m_StandardConc
vector_fp m_deltaG0
vector_fp m_ProdStanConcReac
bool m_finalized
boolean indicating whether mechanism has been finalized
bool m_has_coverage_dependence
Boolean flag indicating whether any reaction in the mechanism has a coverage dependent forward reaction rate.
bool m_has_electrochem_rxns
Boolean flag indicating whether any reaction in the mechanism has a beta electrochemical parameter.
bool m_has_exchange_current_density_formulation
Boolean flag indicating whether any reaction in the mechanism is described by an exchange current density expression.
int m_phaseExistsCheck
Int flag to indicate that some phases in the kinetics mechanism are non-existent.
std::vector< bool > m_phaseExists
Vector of booleans indicating whether phases exist or not.
std::vector< int > m_phaseIsStable
Vector of int indicating whether phases are stable or not.
std::vector< bool * > m_rxnPhaseIsReactant
Vector of vector of booleans indicating whether a phase participates in a reaction as a reactant.
std::vector< bool * > m_rxnPhaseIsProduct
Vector of vector of booleans indicating whether a phase participates in a reaction as a product.
std::vector< int > m_phaseIsIntermediate
Vector of ints indicating whether zeroed phase is an intermediate for the formation of another phase.
int m_numIntermediatePhases
std::vector< doublereal > m_rxnRateFactorPhaseIntermediates
Reaction rate reduction factor for intermediates.
std::vector< doublereal > m_speciesTmpP
Work vector having length number of species.
std::vector< doublereal > m_speciesTmpD
int m_ioFlag
virtual void addPhase (thermo_t &thermo)
Add a phase to the kinetics manager object.
virtual void init ()
Prepare the class for the addition of reactions.
virtual void addReaction (ReactionData &r)
Add a single reaction to the mechanism.
virtual void finalize ()
Finish adding reactions and prepare for use.
void updateROP ()
Internal routine that updates the Rates of Progress of the reactions.
void _update_rates_T ()
Update properties that depend on temperature.
void _update_rates_phi ()
Update properties that depend on the electric potential.
void _update_rates_C ()
Update properties that depend on the species mole fractions and/or concentration.
void advanceCoverages (doublereal tstep)
Advance the surface coverages in time.
void solvePseudoSteadyStateProblem (int ifuncOverride=-1, doublereal timeScaleOverride=1.0)
Solve for the pseudo steady-state of the surface problem.
void setIOFlag (int ioFlag)
void checkPartialEquil ()
size_t reactionNumber () const
void addElementaryReaction (ReactionData &r)
void addGlobalReaction (const ReactionData &r)
void installReagents (const ReactionData &r)
void updateKc ()
Update the equilibrium constants in molar units for all reversible reactions.
void registerReaction (size_t rxnNumber, int type, size_t loc)
Write values into m_index.
void applyButlerVolmerCorrection (doublereal *const kf)
Apply corrections for interfacial charge transfer reactions.
void applyExchangeCurrentDensityFormulation (doublereal *const kfwd)
When an electrode reaction rate is optionally specified in terms of its exchange current density, extra vectors need to be precalculated.
void setPhaseExistence (const size_t iphase, const bool exists)
Set the existence of a phase in the reaction object.
void setPhaseStability (const int iphase, const int isStable)
Set the stability of a phase in the reaction object.
int phaseExistence (const int iphase) const
Gets the phase existence int for the ith phase.
int phaseStability (const int iphase) const
Gets the phase stability int for the ith phase.
Detailed Description
An interface between multiple bulk phases.
This class is defined mostly for convenience. It inherits both from Cantera::SurfPhase and Cantera::InterfaceKinetics. It therefore represents a surface phase, and also acts as the kinetics manager to manage reactions occurring on the surface, possibly involving species from other phases.
Definition at line 23 of file Interface.h.
Constructor & Destructor Documentation
Interface (std::string infile, std::string id, std::vector< Cantera::ThermoPhase * > otherPhases) inline
Constructor.
Construct an Interface instance from a specification in an input file.
Parameters
infile Cantera input file in CTI or CTML format.
id Identification string to distinguish between multiple definitions within one input file.
otherPhases Neighboring phases that may participate in the reactions on this interface. Don't include the surface phase
Deprecated:
While it's convenient to have the surface phase and the interfacial reaction together, this class doesn't satisfy the primary issue, which is one of instantiation of all the ThermoPhase classes that accompany a surface reaction. This is accomplished by the PhaseList class along with the ReactingSurface class. These classes will be migrated into Cantera soon.
Definition at line 47 of file Interface.h.
References Cantera::get_XML_File(), Cantera::get_XML_Node(), Cantera::importKinetics(), Cantera::importPhase(), Interface::m_ok, and Interface::m_r.
Interface (const Interface & ii) inline
Copy Constructor.
Parameters
ii Interface object to be copied.
Definition at line 70 of file Interface.h.
virtual ~Interface () inline virtual
Destructor. Does nothing.
Definition at line 93 of file Interface.h.
Member Function Documentation
Interface& operator= (const Interface & right) inline
Assignment operator.
Parameters
right Interface object to be copied.
Definition at line 81 of file Interface.h.
References Interface::m_ok, Interface::m_r, InterfaceKinetics::operator=(), and SurfPhase::operator=().
bool operator! () inline
Not operator.
Definition at line 97 of file Interface.h.
References Interface::m_ok.
bool ready () const inline virtual
return whether the object has been instantiated
Returns
Returns a bool.
Reimplemented from InterfaceKinetics.
Definition at line 105 of file Interface.h.
References Interface::m_ok.
ThermoPhase * duplMyselfAsThermoPhase () const virtual inherited
Duplicator from the ThermoPhase parent class.
Reimplemented from ThermoPhase.
Definition at line 147 of file SurfPhase.cpp.
References SurfPhase::SurfPhase().
virtual int eosType () const inline virtual inherited
Equation of state type flag.
Redefine this to return cSurf, listed in mix_defs.h.
Reimplemented from ThermoPhase.
Reimplemented in EdgePhase.
Definition at line 212 of file SurfPhase.h.
References Cantera::cSurf.
doublereal enthalpy_mole () const virtual inherited
Return the Molar Enthalpy. Units: J/kmol.
For an ideal solution,
\[ \hat h(T,P) = \sum_k X_k \hat h^0_k(T), \]
and is a function only of temperature. The standard-state pure-species Enthalpies \(\hat h^0_k(T) \) are computed by the species thermodynamic property manager.
See Also
SpeciesThermo
Reimplemented from ThermoPhase.
Definition at line 154 of file SurfPhase.cpp.
References SurfPhase::_updateThermo(), DATA_PTR, SurfPhase::m_h0, SurfPhase::m_n0, and Phase::mean_X().
Referenced by SurfPhase::intEnergy_mole().
doublereal intEnergy_mole () const virtual inherited
Return the Molar Internal Energy. Units: J/kmol.
For a surface phase, the pressure is not a relevant thermodynamic variable, and so the Enthalpy is equal to the Internal Energy.
Reimplemented from ThermoPhase.
Definition at line 173 of file SurfPhase.cpp.
References SurfPhase::enthalpy_mole().
void getChemPotentials (doublereal * mu) const virtual inherited
Get the species chemical potentials. Units: J/kmol.
This function returns a vector of chemical potentials of the species in solution at the current temperature, pressure and mole fraction of the solution.
Parameters
mu Output vector of species chemical potentials. Length: m_kk. Units: J/kmol
Reimplemented from ThermoPhase.
Definition at line 232 of file SurfPhase.cpp.
References SurfPhase::_updateThermo(), DATA_PTR, Cantera::GasConstant, SurfPhase::getActivityConcentrations(), SurfPhase::logStandardConc(), Phase::m_kk, SurfPhase::m_mu0, SurfPhase::m_work, and Phase::temperature().
void getPartialMolarEnthalpies (doublereal * hbar) const virtual inherited
Returns an array of partial molar enthalpies for the species in the mixture.
Units (J/kmol)
Parameters
hbar Output vector of species partial molar enthalpies. Length: m_kk. units are J/kmol.
Reimplemented from ThermoPhase.
Definition at line 182 of file SurfPhase.cpp.
References Cantera::GasConstant, SurfPhase::getEnthalpy_RT(), Phase::m_kk, and Phase::temperature().
void getPartialMolarEntropies (doublereal * sbar) const virtual inherited
Returns an array of partial molar entropies of the species in the solution.
Units: J/kmol/K.
Parameters
sbar Output vector of species partial molar entropies. Length = m_kk. units are J/kmol/K.
Reimplemented from ThermoPhase.
Definition at line 197 of file SurfPhase.cpp.
References Cantera::GasConstant, SurfPhase::getEntropy_R(), and Phase::m_kk.
void getPartialMolarCp (doublereal * cpbar) const virtual inherited
Return an array of partial molar heat capacities for the species in the mixture.
Units: J/kmol/K
Parameters
cpbar Output vector of species partial molar heat capacities at constant pressure. Length = m_kk. units are J/kmol/K.
Reimplemented from ThermoPhase.
Definition at line 211 of file SurfPhase.cpp.
References Cantera::GasConstant, SurfPhase::getCp_R(), and Phase::m_kk.
void getPartialMolarVolumes (doublereal * vbar) const virtual inherited
Return an array of partial molar volumes for the species in the mixture.
Units: m^3/kmol.
Parameters
vbar Output vector of species partial molar volumes. Length = m_kk. units are m^3/kmol.
Reimplemented from ThermoPhase.
Definition at line 221 of file SurfPhase.cpp.
References SurfPhase::getStandardVolumes().
void getStandardChemPotentials (doublereal * mu0) const virtual inherited
Get the array of chemical potentials at unit activity for the standard state species at the current T and P of the solution.
These are the standard state chemical potentials \(\mu^0_k(T,P) \). The values are evaluated at the current temperature and pressure of the solution
Parameters
mu0 Output vector of chemical potentials. Length: m_kk.
Reimplemented from ThermoPhase.
Definition at line 226 of file SurfPhase.cpp.
References SurfPhase::_updateThermo(), and SurfPhase::m_mu0.
void getActivityConcentrations (doublereal * c) const virtual inherited
Return a vector of activity concentrations for each species.
For this phase the activity concentrations, \(C^a_k \), are defined to be equal to the actual concentrations, \(C^s_k \). Activity concentrations are
\[ C^a_k = C^s_k = \frac{\theta_k n_0}{s_k} \]
where \(\theta_k \) is the surface site fraction for species k, \(n_0 \) is the surface site density for the phase, and \(s_k \) is the surface size of species k.
\(C^a_k\) that are defined such that \(a_k = C^a_k / C^0_k, \) where \(C^0_k \) is a standard concentration defined below and \(a_k \) are activities used in the thermodynamic functions. These activity concentrations are used by kinetics manager classes to compute the forward and reverse rates of elementary reactions. Note that they may or may not have units of concentration — they might be partial pressures, mole fractions, or surface coverages,
Parameters
c vector of activity concentration (kmol m-2).
Reimplemented from ThermoPhase.
Definition at line 243 of file SurfPhase.cpp.
References Phase::getConcentrations().
Referenced by SurfPhase::getChemPotentials().
doublereal standardConcentration (size_t k = 0) const virtual inherited
Return the standard concentration for the kth species.
The standard concentration \(C^0_k \) used to normalize the activity (i.e., generalized) concentration. For this phase, the standard concentration is species- specific
\[ C^0_k = \frac{n_0}{s_k} \]
This definition implies that the activity is equal to \(\theta_k \).
Parameters
k Optional parameter indicating the species. The default is to assume this refers to species 0.
Returns
Returns the standard Concentration in units of m3 kmol-1.
Reimplemented from ThermoPhase.
Definition at line 248 of file SurfPhase.cpp.
References SurfPhase::m_n0, and Phase::size().
Referenced by SurfPhase::getStandardVolumes().
doublereal logStandardConc (size_t k = 0) const virtual inherited
Return the log of the standard concentration for the kth species.
Parameters
k species index (default 0)
Reimplemented from ThermoPhase.
Definition at line 253 of file SurfPhase.cpp.
References SurfPhase::m_logn0, and SurfPhase::m_logsize.
Referenced by SurfPhase::getChemPotentials().
void setParameters (int n, doublereal *const c) virtual inherited
Set the equation of state parameters from the argument list.
The only parameter that can be set is the site density.
Set equation of state parameters.
Parameters
n number of parameters. Must be one
c array of n coefficients c[0] = The site density (kmol m-2)
Reimplemented from ThermoPhase.
Definition at line 259 of file SurfPhase.cpp.
References SurfPhase::m_logn0, and SurfPhase::m_n0.
Referenced by SurfPhase::setSiteDensity().
void setParametersFromXML (const XML_Node & thermoData) virtual inherited
Set the Equation-of-State parameters by reading an XML Node Input.
The Equation-of-State data consists of one item, the site density.
Parameters
thermoData Reference to an XML_Node named thermo containing the equation-of-state data. The XML_Node is within the phase XML_Node describing the SurfPhase object.
An example of the contents of the thermoData XML_Node is provided below. The units attribute is used to supply the units of the site density in any convenient form. Internally it is changed into MKS form.
*    <thermo model="Surface">
*       <site_density units="mol/cm2"> 3e-09 </site_density>
*    </thermo>
*
Reimplemented from ThermoPhase.
Reimplemented in EdgePhase.
Definition at line 474 of file SurfPhase.cpp.
References XML_Node::_require(), ctml::getFloat(), SurfPhase::m_logn0, and SurfPhase::m_n0.
void initThermo () virtual inherited
Initialize the SurfPhase object after all species have been set up.
Initialize.
This method is provided to allow subclasses to perform any initialization required after all species have been added. For example, it might be used to resize internal work arrays that must have an entry for each species. The base class implementation does nothing, and subclasses that do not require initialization do not need to overload this method. When importing a CTML phase description, this method is called from ThermoPhase::initThermoXML(), which is called from importPhase(), just prior to returning from function importPhase().
See Also
importCTML.cpp
Reimplemented from ThermoPhase.
Definition at line 330 of file SurfPhase.cpp.
References DATA_PTR, SurfPhase::m_cp0, SurfPhase::m_h0, Phase::m_kk, SurfPhase::m_logsize, SurfPhase::m_mu0, SurfPhase::m_pe, SurfPhase::m_s0, SurfPhase::m_work, SurfPhase::setCoverages(), and Phase::size().
void setStateFromXML (const XML_Node & state) virtual inherited
Set the initial state of the Surface Phase from an XML_Node.
State variables that can be set by this routine are the temperature and the surface site coverages.
Parameters
state XML_Node containing the state information
An example of the XML code block is given below.
*   <state>
*      <temperature units="K">1200.0</temperature>
*      <coverages>c6H*:0.1, c6HH:0.9</coverages>
*   </state>
*
Reimplemented from ThermoPhase.
Definition at line 486 of file SurfPhase.cpp.
References ctml::getChildValue(), ctml::getOptionalFloat(), XML_Node::hasChild(), SurfPhase::setCoveragesByName(), and Phase::setTemperature().
doublereal siteDensity () inline inherited
Returns the site density.
Site density kmol m-2
Definition at line 429 of file SurfPhase.h.
References SurfPhase::m_n0.
Referenced by ReactingSurf1D::eval().
void setPotentialEnergy (int k, doublereal pe) inherited
Sets the potential energy of species k.
Parameters
k Species index
pe Value of the potential energy (J kmol-1)
Definition at line 351 of file SurfPhase.cpp.
References SurfPhase::_updateThermo(), and SurfPhase::m_pe.
doublereal potentialEnergy (int k) inline inherited
Return the potential energy of species k.
Returns the potential energy of species, k, J kmol-1
Parameters
k Species index
Definition at line 448 of file SurfPhase.h.
References SurfPhase::m_pe.
void setSiteDensity (doublereal n0) inherited
Set the site density of the surface phase (kmol m-2)
Parameters
n0 Site density of the surface phase (kmol m-2)
Definition at line 357 of file SurfPhase.cpp.
References SurfPhase::setParameters().
void getGibbs_RT (doublereal * grt) const virtual inherited
Get the nondimensional Gibbs functions for the species in their standard states at the current T and P of the solution.
Parameters
grt Output vector of nondimensional standard state gibbs free energies Length: m_kk.
Reimplemented from ThermoPhase.
Definition at line 273 of file SurfPhase.cpp.
References SurfPhase::_updateThermo(), Cantera::GasConstant, SurfPhase::m_mu0, Cantera::scale(), and Phase::temperature().
Referenced by SurfPhase::getGibbs_RT_ref().
void getEnthalpy_RT (doublereal * hrt) const virtual inherited
Get the nondimensional Enthalpy functions for the species standard states at their standard states at the current T and P of the solution.
Parameters
hrt Output vector of nondimensional standard state enthalpies. Length: m_kk.
Reimplemented from ThermoPhase.
Definition at line 281 of file SurfPhase.cpp.
References SurfPhase::_updateThermo(), Cantera::GasConstant, SurfPhase::m_h0, Cantera::scale(), and Phase::temperature().
Referenced by SurfPhase::getEnthalpy_RT_ref(), and SurfPhase::getPartialMolarEnthalpies().
void getEntropy_R (doublereal * sr) const virtual inherited
Get the array of nondimensional Entropy functions for the species standard states at the current T and P of the solution.
Parameters
sr Output vector of nondimensional standard state entropies. Length: m_kk.
Reimplemented from ThermoPhase.
Definition at line 288 of file SurfPhase.cpp.
References SurfPhase::_updateThermo(), Cantera::GasConstant, SurfPhase::m_s0, and Cantera::scale().
Referenced by SurfPhase::getEntropy_R_ref(), and SurfPhase::getPartialMolarEntropies().
void getCp_R (doublereal * cpr) const virtual inherited
Get the nondimensional Heat Capacities at constant pressure for the species standard states at the current T and P of the solution.
Parameters
cpr Output vector of nondimensional standard state heat capacities Length: m_kk.
Reimplemented from ThermoPhase.
Definition at line 295 of file SurfPhase.cpp.
References SurfPhase::_updateThermo(), Cantera::GasConstant, SurfPhase::m_cp0, and Cantera::scale().
Referenced by SurfPhase::getCp_R_ref(), and SurfPhase::getPartialMolarCp().
void getStandardVolumes (doublereal * vol) const virtual inherited
Get the molar volumes of the species standard states at the current T and P of the solution.
units = m^3 / kmol
Parameters
vol Output vector containing the standard state volumes. Length: m_kk.
Reimplemented from ThermoPhase.
Definition at line 302 of file SurfPhase.cpp.
References SurfPhase::_updateThermo(), Phase::m_kk, and SurfPhase::standardConcentration().
Referenced by SurfPhase::getPartialMolarVolumes().
virtual doublereal pressure () const inline virtual inherited
Return the thermodynamic pressure (Pa).
This method must be overloaded in derived classes. Since the mass density, temperature, and mass fractions are stored, this method should use these values to implement the mechanical equation of state \(P(T, \rho, Y_1, \dots, Y_K) \).
Reimplemented from ThermoPhase.
Definition at line 509 of file SurfPhase.h.
References SurfPhase::m_press.
virtual void setPressure (doublereal p) inline virtual inherited
Set the internally stored pressure (Pa) at constant temperature and composition.
This method must be reimplemented in derived classes, where it may involve the solution of a nonlinear equation. Within Cantera, the independent variable is the density. Therefore, this function solves for the density that will yield the desired input pressure. The temperature and composition iare held constant during this process.
This base class function will print an error, if not overwritten.
Parameters
p input Pressure (Pa)
Reimplemented from ThermoPhase.
Definition at line 526 of file SurfPhase.h.
References SurfPhase::m_press.
void getGibbs_RT_ref (doublereal * grt) const virtual inherited
Returns the vector of nondimensional Gibbs Free Energies of the reference state at the current temperature of the solution and the reference pressure for the species.
Parameters
grt Output vector containing the nondimensional reference state Gibbs Free energies. Length: m_kk.
Reimplemented from ThermoPhase.
Definition at line 310 of file SurfPhase.cpp.
References SurfPhase::getGibbs_RT().
void getEnthalpy_RT_ref (doublereal * hrt) const virtual inherited
Returns the vector of nondimensional enthalpies of the reference state at the current temperature of the solution and the reference pressure for the species.
Parameters
hrt Output vector of nondimensional standard state enthalpies. Length: m_kk.
Reimplemented from ThermoPhase.
Definition at line 315 of file SurfPhase.cpp.
References SurfPhase::getEnthalpy_RT().
void getEntropy_R_ref (doublereal * er) const virtual inherited
Returns the vector of nondimensional entropies of the reference state at the current temperature of the solution and the reference pressure for each species.
Parameters
er Output vector containing the nondimensional reference state entropies. Length: m_kk.
Reimplemented from ThermoPhase.
Definition at line 320 of file SurfPhase.cpp.
References SurfPhase::getEntropy_R().
void getCp_R_ref (doublereal * cprt) const virtual inherited
Returns the vector of nondimensional constant pressure heat capacities of the reference state at the current temperature of the solution and reference pressure for each species.
Parameters
cprt Output vector of nondimensional reference state heat capacities at constant pressure for the species. Length: m_kk
Reimplemented from ThermoPhase.
Definition at line 325 of file SurfPhase.cpp.
References SurfPhase::getCp_R().
void setCoverages (const doublereal * theta) inherited
Set the surface site fractions to a specified state.
Set the coverage fractions to a specified state.
This routine converts to concentrations in kmol/m2, using m_n0, the surface site density, and size(k), which is defined to be the number of surface sites occupied by the kth molecule. It then calls Phase::setConcentrations to set the internal concentration in the object.
Parameters
theta This is the surface site fraction for the kth species in the surface phase. This is a dimensionless quantity.
This routine normalizes the theta's to 1, before application
This routine converts to concentrations in kmol/m2, using m_n0, the surface site density, and size(k), which is defined to be the number of surface sites occupied by the kth molecule. It then calls Phase::setConcentrations to set the internal concentration in the object.
Definition at line 382 of file SurfPhase.cpp.
References DATA_PTR, Phase::m_kk, SurfPhase::m_n0, SurfPhase::m_work, Phase::setConcentrations(), and Phase::size().
Referenced by ReactingSurf1D::eval(), SurfPhase::initThermo(), and SurfPhase::setCoveragesByName().
void setCoveragesNoNorm (const doublereal * theta) inherited
Set the surface site fractions to a specified state.
This routine converts to concentrations in kmol/m2, using m_n0, the surface site density, and size(k), which is defined to be the number of surface sites occupied by the kth molecule. It then calls Phase::setConcentrations to set the internal concentration in the object.
Parameters
theta This is the surface site fraction for the kth species in the surface phase. This is a dimensionless quantity.
Definition at line 406 of file SurfPhase.cpp.
References DATA_PTR, Phase::m_kk, SurfPhase::m_n0, SurfPhase::m_work, Phase::setConcentrations(), and Phase::size().
void setCoveragesByName (std::string cov) inherited
Set the coverages from a string of colon-separated name:value pairs.
Parameters
cov String containing colon-separated name:value pairs
Definition at line 428 of file SurfPhase.cpp.
References DATA_PTR, Phase::nSpecies(), Cantera::parseCompString(), SurfPhase::setCoverages(), and Phase::speciesName().
Referenced by SurfPhase::setStateFromXML().
void getCoverages (doublereal * theta) const inherited
Return a vector of surface coverages.
Get the coverages.
Parameters
theta Array theta must be at least as long as the number of species.
Definition at line 419 of file SurfPhase.cpp.
References Phase::getConcentrations(), Phase::m_kk, SurfPhase::m_n0, and Phase::size().
Referenced by ReactingSurf1D::_getInitialSoln(), and InterfaceKinetics::_update_rates_T().
virtual doublereal refPressure () const inline virtual inherited
Returns the reference pressure in Pa.
This function is a wrapper that calls the species thermo refPressure function.
Reimplemented in LatticeSolidPhase.
Definition at line 164 of file ThermoPhase.h.
References ThermoPhase::m_spthermo, and SpeciesThermo::refPressure().
Referenced by MixtureFugacityTP::_updateReferenceStateThermo(), RedlichKwongMFTP::getChemPotentials(), RedlichKwongMFTP::getPartialMolarEntropies(), MixtureFugacityTP::getStandardVolumes_ref(), ChemEquil::initialize(), IdealSolidSolnPhase::initLengths(), ConstDensityThermo::initThermo(), StoichSubstance::initThermo(), StoichSubstanceSSTP::initThermo(), PureFluidPhase::initThermo(), SingleSpeciesTP::initThermo(), IdealGasPhase::initThermo(), LatticePhase::initThermo(), and RedlichKwongMFTP::setToEquilState().
virtual doublereal minTemp (size_t k = npos) const inline virtual inherited
Minimum temperature for which the thermodynamic data for the species or phase are valid.
If no argument is supplied, the value returned will be the lowest temperature at which the data for all species are valid. Otherwise, the value will be only for species k. This function is a wrapper that calls the species thermo minTemp function.
Parameters
k index of the species. Default is -1, which will return the max of the min value over all species.
Reimplemented in LatticeSolidPhase.
Definition at line 181 of file ThermoPhase.h.
References ThermoPhase::m_spthermo, and SpeciesThermo::minTemp().
Referenced by MultiPhase::addPhase(), ChemEquil::equilibrate(), LiquidTransport::initLiquid(), SimpleTransport::initLiquid(), AqueousTransport::initLiquid(), ThermoPhase::setState_HPorUV(), ThermoPhase::setState_SPorSV(), TransportFactory::setupLiquidTransport(), and TransportFactory::setupMM().
doublereal Hf298SS (const int k) const inline inherited
Report the 298 K Heat of Formation of the standard state of one species (J kmol-1)
The 298K Heat of Formation is defined as the enthalpy change to create the standard state of the species from its constituent elements in their standard states at 298 K and 1 bar.
Parameters
k species index
Returns
Returns the current value of the Heat of Formation at 298K and 1 bar
Definition at line 221 of file ThermoPhase.h.
References ThermoPhase::err().
virtual void modifyOneHf298SS (const int k, const doublereal Hf298New) inline virtual inherited
Modify the value of the 298 K Heat of Formation of one species in the phase (J kmol-1)
The 298K heat of formation is defined as the enthalpy change to create the standard state of the species from its constituent elements in their standard states at 298 K and 1 bar.
Parameters
k Species k
Hf298New Specify the new value of the Heat of Formation at 298K and 1 bar
Definition at line 233 of file ThermoPhase.h.
References ThermoPhase::err().
virtual doublereal maxTemp (size_t k = npos) const inline virtual inherited
Maximum temperature for which the thermodynamic data for the species are valid.
If no argument is supplied, the value returned will be the highest temperature at which the data for all species are valid. Otherwise, the value will be only for species k. This function is a wrapper that calls the species thermo maxTemp function.
Parameters
k index of the species. Default is -1, which will return the min of the max value over all species.
Reimplemented in LatticeSolidPhase.
Definition at line 250 of file ThermoPhase.h.
References ThermoPhase::m_spthermo, and SpeciesThermo::maxTemp().
Referenced by MultiPhase::addPhase(), ChemEquil::equilibrate(), LiquidTransport::initLiquid(), SimpleTransport::initLiquid(), AqueousTransport::initLiquid(), ThermoPhase::setState_HPorUV(), ThermoPhase::setState_SPorSV(), TransportFactory::setupLiquidTransport(), and TransportFactory::setupMM().
bool chargeNeutralityNecessary () const inline inherited
Returns the chargeNeutralityNecessity boolean.
Some phases must have zero net charge in order for their thermodynamics functions to be valid. If this is so, then the value returned from this function is true. If this is not the case, then this is false. Now, ideal gases have this parameter set to false, while solution with molality-based activity coefficients have this parameter set to true.
Definition at line 261 of file ThermoPhase.h.
References ThermoPhase::m_chargeNeutralityNecessary.
virtual doublereal entropy_mole () const inline virtual inherited
Molar entropy. Units: J/kmol/K.
Reimplemented in HMWSoln, DebyeHuckel, PhaseCombo_Interaction, MixedSolventElectrolyte, MargulesVPSSTP, RedlichKisterVPSSTP, IdealGasPhase, LatticePhase, LatticeSolidPhase, IdealMolalSoln, IdealSolidSolnPhase, IonsFromNeutralVPSSTP, SingleSpeciesTP, RedlichKwongMFTP, StoichSubstance, ConstDensityThermo, IdealSolnGasVPSS, PureFluidPhase, and MetalPhase.
Definition at line 282 of file ThermoPhase.h.
References ThermoPhase::err().
Referenced by ThermoPhase::entropy_mass(), ThermoPhase::gibbs_mole(), PseudoBinaryVPSSTP::report(), MolarityIonicVPSSTP::report(), MolalityVPSSTP::report(), ThermoPhase::report(), MolalityVPSSTP::reportCSV(), and ThermoPhase::reportCSV().
virtual doublereal gibbs_mole () const inline virtual inherited
Molar Gibbs function. Units: J/kmol.
Reimplemented in HMWSoln, DebyeHuckel, IdealGasPhase, LatticePhase, LatticeSolidPhase, IdealMolalSoln, IdealSolidSolnPhase, IonsFromNeutralVPSSTP, SingleSpeciesTP, RedlichKwongMFTP, StoichSubstance, ConstDensityThermo, IdealSolnGasVPSS, PureFluidPhase, and MetalPhase.
Definition at line 287 of file ThermoPhase.h.
References ThermoPhase::enthalpy_mole(), ThermoPhase::entropy_mole(), and Phase::temperature().
Referenced by MixtureFugacityTP::corr0(), ThermoPhase::gibbs_mass(), PseudoBinaryVPSSTP::report(), MolarityIonicVPSSTP::report(), MolalityVPSSTP::report(), ThermoPhase::report(), MolalityVPSSTP::reportCSV(), and ThermoPhase::reportCSV().
virtual doublereal cp_mole () const inline virtual inherited
Molar heat capacity at constant pressure. Units: J/kmol/K.
Reimplemented in HMWSoln, DebyeHuckel, PhaseCombo_Interaction, MixedSolventElectrolyte, MargulesVPSSTP, RedlichKisterVPSSTP, IdealGasPhase, LatticePhase, LatticeSolidPhase, IdealMolalSoln, IdealSolidSolnPhase, IonsFromNeutralVPSSTP, SingleSpeciesTP, RedlichKwongMFTP, StoichSubstance, ConstDensityThermo, IdealSolnGasVPSS, PureFluidPhase, and MetalPhase.
Definition at line 292 of file ThermoPhase.h.
References ThermoPhase::err().
Referenced by ThermoPhase::cp_mass(), PseudoBinaryVPSSTP::report(), MolarityIonicVPSSTP::report(), MolalityVPSSTP::report(), ThermoPhase::report(), MolalityVPSSTP::reportCSV(), and ThermoPhase::reportCSV().
virtual doublereal cv_mole () const inline virtual inherited
Molar heat capacity at constant volume. Units: J/kmol/K.
Reimplemented in HMWSoln, DebyeHuckel, PhaseCombo_Interaction, MixedSolventElectrolyte, MargulesVPSSTP, RedlichKisterVPSSTP, IdealGasPhase, LatticePhase, LatticeSolidPhase, IdealSolidSolnPhase, IdealMolalSoln, IonsFromNeutralVPSSTP, WaterSSTP, SingleSpeciesTP, RedlichKwongMFTP, StoichSubstance, ConstDensityThermo, IdealSolnGasVPSS, PureFluidPhase, and MetalPhase.
Definition at line 297 of file ThermoPhase.h.
References ThermoPhase::err().
Referenced by ThermoPhase::cv_mass(), PseudoBinaryVPSSTP::report(), MolarityIonicVPSSTP::report(), MolalityVPSSTP::report(), ThermoPhase::report(), MolalityVPSSTP::reportCSV(), and ThermoPhase::reportCSV().
virtual doublereal isothermalCompressibility () const inline virtual inherited
Returns the isothermal compressibility. Units: 1/Pa.
The isothermal compressibility is defined as
\[ \kappa_T = -\frac{1}{v}\left(\frac{\partial v}{\partial P}\right)_T \]
or
\[ \kappa_T = \frac{1}{\rho}\left(\frac{\partial \rho}{\partial P}\right)_T \]
Reimplemented in HMWSoln, DebyeHuckel, IdealGasPhase, IdealMolalSoln, MetalSHEelectrons, PureFluidPhase, FixedChemPotSSTP, MineralEQ3, StoichSubstanceSSTP, WaterSSTP, RedlichKwongMFTP, and IdealSolnGasVPSS.
Definition at line 348 of file ThermoPhase.h.
References ThermoPhase::err().
Referenced by SingleSpeciesTP::cv_mole().
virtual doublereal thermalExpansionCoeff () const inline virtual inherited
Return the volumetric thermal expansion coefficient. Units: 1/K.
The thermal expansion coefficient is defined as
\[ \beta = \frac{1}{v}\left(\frac{\partial v}{\partial T}\right)_P \]
Reimplemented in HMWSoln, DebyeHuckel, IdealGasPhase, IdealMolalSoln, MetalSHEelectrons, PureFluidPhase, FixedChemPotSSTP, MineralEQ3, StoichSubstanceSSTP, and WaterSSTP.
Definition at line 360 of file ThermoPhase.h.
References ThermoPhase::err().
Referenced by SingleSpeciesTP::cv_mole().
virtual void updateDensity () inline virtual inherited
Deprecated:
Definition at line 366 of file ThermoPhase.h.
References Cantera::deprecatedMethod().
void setElectricPotential (doublereal v) inline inherited
Set the electric potential of this phase (V).
This is used by classes InterfaceKinetics and EdgeKinetics to compute the rates of charge-transfer reactions, and in computing the electrochemical potentials of the species.
Each phase may have its own electric potential.
Parameters
v Input value of the electric potential in Volts
Definition at line 390 of file ThermoPhase.h.
References ThermoPhase::m_phi.
Referenced by InterfaceKinetics::setElectricPotential(), vcs_VolPhase::setElectricPotential(), and vcs_VolPhase::setState_TP().
doublereal electricPotential () const inline inherited
Returns the electric potential of this phase (V).
Units are Volts (which are Joules/coulomb)
Definition at line 398 of file ThermoPhase.h.
References ThermoPhase::m_phi.
Referenced by InterfaceKinetics::_update_rates_phi(), PureFluidPhase::getElectrochemPotentials(), PseudoBinaryVPSSTP::getElectrochemPotentials(), MolarityIonicVPSSTP::getElectrochemPotentials(), GibbsExcessVPSSTP::getElectrochemPotentials(), RedlichKisterVPSSTP::getElectrochemPotentials(), MargulesVPSSTP::getElectrochemPotentials(), MixedSolventElectrolyte::getElectrochemPotentials(), ThermoPhase::getElectrochemPotentials(), MolalityVPSSTP::getElectrochemPotentials(), PhaseCombo_Interaction::getElectrochemPotentials(), PseudoBinaryVPSSTP::report(), MolarityIonicVPSSTP::report(), PureFluidPhase::report(), MolalityVPSSTP::report(), ThermoPhase::report(), PureFluidPhase::reportCSV(), MolalityVPSSTP::reportCSV(), ThermoPhase::reportCSV(), and vcs_VolPhase::setPtrThermoPhase().
int activityConvention () const virtual inherited
This method returns the convention used in specification of the activities, of which there are currently two, molar- and molality-based conventions.
Currently, there are two activity conventions:
Molar-based activities Unit activity of species at either a hypothetical pure solution of the species or at a hypothetical pure ideal solution at infinite dilution cAC_CONVENTION_MOLAR 0
default
Molality-based activities (unit activity of solutes at a hypothetical 1 molal solution referenced to infinite dilution at all pressures and temperatures). cAC_CONVENTION_MOLALITY 1
Reimplemented in MolalityVPSSTP.
Definition at line 143 of file ThermoPhase.cpp.
References Cantera::cAC_CONVENTION_MOLAR.
Referenced by vcs_MultiPhaseEquil::reportCSV(), and LiquidTransport::stefan_maxwell_solve().
int standardStateConvention () const virtual inherited
This method returns the convention used in specification of the standard state, of which there are currently two, temperature based, and variable pressure based.
Currently, there are two standard state conventions:
Temperature-based activities cSS_CONVENTION_TEMPERATURE 0
default
Variable Pressure and Temperature -based activities cSS_CONVENTION_VPSS 1
Thermodynamics is set via slave ThermoPhase objects with nothing being carried out at this ThermoPhase object level cSS_CONVENTION_SLAVE 2
Reimplemented in PureFluidPhase, LatticeSolidPhase, MixtureFugacityTP, and VPStandardStateTP.
Definition at line 148 of file ThermoPhase.cpp.
References ThermoPhase::m_ssConvention.
Referenced by Cantera::importPhase().
void getUnitsStandardConc (double * uA, int k = 0, int sizeUA = 6) const virtual inherited
Returns the units of the standard and generalized concentrations.
Note they have the same units, as their ratio is defined to be equal to the activity of the kth species in the solution, which is unitless.
This routine is used in print out applications where the units are needed. Usually, MKS units are assumed throughout the program and in the XML input files.
The base ThermoPhase class assigns the default quantities of (kmol/m3) for all species. Inherited classes are responsible for overriding the default values if necessary.
Parameters
uA Output vector containing the units uA[0] = kmol units - default = 1 uA[1] = m units - default = -nDim(), the number of spatial dimensions in the Phase class. uA[2] = kg units - default = 0; uA[3] = Pa(pressure) units - default = 0; uA[4] = Temperature units - default = 0; uA[5] = time units - default = 0
k species index. Defaults to 0.
sizeUA output int containing the size of the vector. Currently, this is equal to 6.
Reimplemented in HMWSoln, DebyeHuckel, IdealSolidSolnPhase, MolalityVPSSTP, IdealMolalSoln, MetalSHEelectrons, FixedChemPotSSTP, MineralEQ3, StoichSubstanceSSTP, RedlichKwongMFTP, GibbsExcessVPSSTP, IdealSolnGasVPSS, and StoichSubstance.
Definition at line 848 of file ThermoPhase.cpp.
References Phase::nDim().
void getActivities (doublereal * a) const virtual inherited
Get the array of non-dimensional activities at the current solution temperature, pressure, and solution concentration.
Note, for molality based formulations, this returns the molality based activities.
We resolve this function at this level by calling on the activityConcentration function. However, derived classes may want to override this default implementation.
Parameters
a Output vector of activities. Length: m_kk.
Reimplemented in HMWSoln, DebyeHuckel, MolalityVPSSTP, IdealMolalSoln, GibbsExcessVPSSTP, PureFluidPhase, and SingleSpeciesTP.
Definition at line 158 of file ThermoPhase.cpp.
References ThermoPhase::getActivityConcentrations(), Phase::nSpecies(), and ThermoPhase::standardConcentration().
Referenced by vcs_MultiPhaseEquil::reportCSV(), and ThermoPhase::reportCSV().
virtual void getActivityCoefficients (doublereal * ac) const inline virtual inherited
Get the array of non-dimensional molar-based activity coefficients at the current solution temperature, pressure, and solution concentration.
Parameters
ac Output vector of activity coefficients. Length: m_kk.
Reimplemented in LatticePhase, IdealGasPhase, MolalityVPSSTP, IdealSolidSolnPhase, PhaseCombo_Interaction, MixedSolventElectrolyte, LatticeSolidPhase, RedlichKwongMFTP, GibbsExcessVPSSTP, IonsFromNeutralVPSSTP, IdealSolnGasVPSS, SingleSpeciesTP, and ConstDensityThermo.
Definition at line 555 of file ThermoPhase.h.
References ThermoPhase::err(), and Phase::m_kk.
Referenced by vcs_VolPhase::_updateActCoeff(), ChemEquil::calcEmoles(), ChemEquil::estimateEP_Brinkley(), ThermoPhase::getLnActivityCoefficients(), PureFluidPhase::reportCSV(), vcs_MultiPhaseEquil::reportCSV(), ThermoPhase::reportCSV(), and LiquidTransport::stefan_maxwell_solve().
void getLnActivityCoefficients (doublereal * lnac) const virtual inherited
Get the array of non-dimensional molar-based ln activity coefficients at the current solution temperature, pressure, and solution concentration.
Parameters
lnac Output vector of ln activity coefficients. Length: m_kk.
Reimplemented in MargulesVPSSTP, RedlichKisterVPSSTP, and MolarityIonicVPSSTP.
Definition at line 166 of file ThermoPhase.cpp.
References ThermoPhase::getActivityCoefficients(), and Phase::m_kk.
Referenced by GibbsExcessVPSSTP::getActivityCoefficients(), IonsFromNeutralVPSSTP::getChemPotentials(), and IonsFromNeutralVPSSTP::s_update_lnActCoeff().
virtual void getChemPotentials_RT (doublereal * mu) const inline virtual inherited
Get the array of non-dimensional species chemical potentials These are partial molar Gibbs free energies.
\(\mu_k / \hat R T \). Units: unitless
Parameters
mu Output vector of dimensionless chemical potentials. Length: m_kk.
Reimplemented in IdealSolidSolnPhase, RedlichKwongMFTP, SingleSpeciesTP, IdealSolnGasVPSS, StoichSubstance, MixtureFugacityTP, and VPStandardStateTP.
Definition at line 583 of file ThermoPhase.h.
References ThermoPhase::err().
void getElectrochemPotentials (doublereal * mu) const inline inherited
Get the species electrochemical potentials.
These are partial molar quantities. This method adds a term \(F z_k \phi_p \) to each chemical potential. The electrochemical potential of species k in a phase p, \(\zeta_k \), is related to the chemical potential via the following equation,
\[ \zeta_{k}(T,P) = \mu_{k}(T,P) + F z_k \phi_p \]
Parameters
mu Output vector of species electrochemical potentials. Length: m_kk. Units: J/kmol
Definition at line 616 of file ThermoPhase.h.
References Phase::charge(), ThermoPhase::electricPotential(), ThermoPhase::getChemPotentials(), and Phase::m_kk.
Referenced by InterfaceKinetics::getDeltaElectrochemPotentials().
virtual void getPartialMolarIntEnergies (doublereal * ubar) const inline virtual inherited
Return an array of partial molar internal energies for the species in the mixture.
Units: J/kmol.
Parameters
ubar Output vector of species partial molar internal energies. Length = m_kk. units are J/kmol.
Reimplemented in IdealGasPhase, RedlichKwongMFTP, SingleSpeciesTP, IdealSolnGasVPSS, and PureFluidPhase.
Definition at line 650 of file ThermoPhase.h.
References ThermoPhase::err().
Referenced by MolalityVPSSTP::reportCSV(), and ThermoPhase::reportCSV().
virtual void getdPartialMolarVolumes_dT (doublereal * d_vbar_dT) const inline virtual inherited
Return an array of derivatives of partial molar volumes wrt temperature for the species in the mixture.
Units: m^3/kmol.
The derivative is at constant pressure
Parameters
d_vbar_dT Output vector of derivatives of species partial molar volumes wrt T. Length = m_kk. units are m^3/kmol/K.
Definition at line 683 of file ThermoPhase.h.
References ThermoPhase::err().
virtual void getdPartialMolarVolumes_dP (doublereal * d_vbar_dP) const inline virtual inherited
Return an array of derivatives of partial molar volumes wrt pressure for the species in the mixture.
Units: m^3/kmol.
The derivative is at constant temperature
Parameters
d_vbar_dP Output vector of derivatives of species partial molar volumes wrt P. Length = m_kk. units are m^3/kmol/Pa.
Definition at line 695 of file ThermoPhase.h.
References ThermoPhase::err().
virtual void getPureGibbs (doublereal * gpure) const inline virtual inherited
Get the Gibbs functions for the standard state of the species at the current T and P of the solution.
Units are Joules/kmol
Parameters
gpure Output vector of standard state gibbs free energies Length: m_kk.
Reimplemented in IdealSolidSolnPhase, LatticePhase, IdealGasPhase, SingleSpeciesTP, StoichSubstance, MixtureFugacityTP, VPStandardStateTP, and ConstDensityThermo.
Definition at line 754 of file ThermoPhase.h.
References ThermoPhase::err().
virtual void getIntEnergy_RT (doublereal * urt) const inline virtual inherited
Returns the vector of nondimensional Internal Energies of the standard state species at the current T and P of the solution.
Parameters
urt output vector of nondimensional standard state internal energies of the species. Length: m_kk.
Reimplemented in IdealSolidSolnPhase, IdealGasPhase, MetalSHEelectrons, FixedChemPotSSTP, MineralEQ3, StoichSubstanceSSTP, WaterSSTP, MixtureFugacityTP, and VPStandardStateTP.
Definition at line 764 of file ThermoPhase.h.
References ThermoPhase::err().
Referenced by SingleSpeciesTP::getPartialMolarIntEnergies().
virtual void getdStandardVolumes_dT (doublereal * d_vol_dT) const inline virtual inherited
Get the derivative of the molar volumes of the species standard states wrt temperature at the current T and P of the solution.
The derivative is at constant pressure units = m^3 / kmol / K
Parameters
d_vol_dT Output vector containing derivatives of standard state volumes wrt T Length: m_kk.
Definition at line 800 of file ThermoPhase.h.
References ThermoPhase::err().
virtual void getdStandardVolumes_dP (doublereal * d_vol_dP) const inline virtual inherited
Get the derivative molar volumes of the species standard states wrt pressure at the current T and P of the solution.
The derivative is at constant temperature. units = m^3 / kmol / Pa
Parameters
d_vol_dP Output vector containing the derivative of standard state volumes wrt P. Length: m_kk.
Definition at line 813 of file ThermoPhase.h.
References ThermoPhase::err().
virtual void getGibbs_ref (doublereal * g) const inline virtual inherited
Returns the vector of the gibbs function of the reference state at the current temperature of the solution and the reference pressure for the species.
units = J/kmol
Parameters
g Output vector containing the reference state Gibbs Free energies. Length: m_kk. Units: J/kmol.
Reimplemented in LatticePhase, IdealSolidSolnPhase, IdealGasPhase, LatticeSolidPhase, MixtureFugacityTP, FixedChemPotSSTP, VPStandardStateTP, SingleSpeciesTP, PureFluidPhase, StoichSubstance, and WaterSSTP.
Definition at line 856 of file ThermoPhase.h.
References ThermoPhase::err().
Referenced by vcs_VolPhase::_updateG0().
virtual void getIntEnergy_RT_ref (doublereal * urt) const inline virtual inherited
Returns the vector of nondimensional internal Energies of the reference state at the current temperature of the solution and the reference pressure for each species.
Parameters
urt Output vector of nondimensional reference state internal energies of the species. Length: m_kk
Reimplemented in IdealSolidSolnPhase, IdealGasPhase, FixedChemPotSSTP, MetalSHEelectrons, MineralEQ3, and StoichSubstanceSSTP.
Definition at line 879 of file ThermoPhase.h.
References ThermoPhase::err().
virtual void getStandardVolumes_ref (doublereal * vol) const inline virtual inherited
Get the molar volumes of the species reference states at the current T and P_ref of the solution.
units = m^3 / kmol
Parameters
vol Output vector containing the standard state volumes. Length: m_kk.
Reimplemented in IdealGasPhase, MixtureFugacityTP, VPStandardStateTP, and WaterSSTP.
Definition at line 904 of file ThermoPhase.h.
References ThermoPhase::err().
Referenced by PDSS_IonsFromNeutral::molarVolume_ref().
void setReferenceComposition (const doublereal *const x) virtual inherited
Sets the reference composition.
Parameters
x Mole fraction vector to set the reference composition to. If this is zero, then the reference mole fraction is set to the current mole fraction vector.
Definition at line 992 of file ThermoPhase.cpp.
References DATA_PTR, Phase::getMoleFractions(), Phase::m_kk, and ThermoPhase::xMol_Ref.
Referenced by ThermoPhase::initThermoXML().
void getReferenceComposition (doublereal *const x) const virtual inherited
Gets the reference composition.
The reference mole fraction is a safe mole fraction.
Parameters
x Mole fraction vector containing the reference composition.
Definition at line 1013 of file ThermoPhase.cpp.
References Phase::m_kk, and ThermoPhase::xMol_Ref.
doublereal enthalpy_mass () const inline inherited
Specific enthalpy.
Units: J/kg.
Definition at line 937 of file ThermoPhase.h.
References ThermoPhase::enthalpy_mole(), and Phase::meanMolecularWeight().
Referenced by ConstPressureReactor::initialize(), Reactor::initialize(), PseudoBinaryVPSSTP::report(), MolarityIonicVPSSTP::report(), PureFluidPhase::report(), MolalityVPSSTP::report(), ThermoPhase::report(), PureFluidPhase::reportCSV(), MolalityVPSSTP::reportCSV(), ThermoPhase::reportCSV(), SingleSpeciesTP::setState_HP(), ThermoPhase::setState_HPorUV(), ThermoPhase::setState_SPorSV(), ReactorBase::setThermoMgr(), ConstPressureReactor::updateState(), and Reactor::updateState().
doublereal intEnergy_mass () const inline inherited
Specific internal energy.
Units: J/kg.
Definition at line 944 of file ThermoPhase.h.
References ThermoPhase::intEnergy_mole(), and Phase::meanMolecularWeight().
Referenced by ConstPressureReactor::initialize(), Reactor::initialize(), PseudoBinaryVPSSTP::report(), MolarityIonicVPSSTP::report(), PureFluidPhase::report(), MolalityVPSSTP::report(), ThermoPhase::report(), PureFluidPhase::reportCSV(), MolalityVPSSTP::reportCSV(), ThermoPhase::reportCSV(), ThermoPhase::setState_HPorUV(), SingleSpeciesTP::setState_UV(), ReactorBase::setThermoMgr(), ConstPressureReactor::updateState(), and Reactor::updateState().
doublereal entropy_mass () const inline inherited
Specific entropy.
Units: J/kg/K.
Definition at line 951 of file ThermoPhase.h.
References ThermoPhase::entropy_mole(), and Phase::meanMolecularWeight().
Referenced by PseudoBinaryVPSSTP::report(), MolarityIonicVPSSTP::report(), PureFluidPhase::report(), MolalityVPSSTP::report(), ThermoPhase::report(), PureFluidPhase::reportCSV(), MolalityVPSSTP::reportCSV(), ThermoPhase::reportCSV(), SingleSpeciesTP::setState_SP(), ThermoPhase::setState_SPorSV(), and SingleSpeciesTP::setState_SV().
doublereal gibbs_mass () const inline inherited
Specific Gibbs function.
Units: J/kg.
Definition at line 958 of file ThermoPhase.h.
References ThermoPhase::gibbs_mole(), and Phase::meanMolecularWeight().
Referenced by PseudoBinaryVPSSTP::report(), MolarityIonicVPSSTP::report(), PureFluidPhase::report(), MolalityVPSSTP::report(), ThermoPhase::report(), PureFluidPhase::reportCSV(), MolalityVPSSTP::reportCSV(), and ThermoPhase::reportCSV().
doublereal cp_mass () const inline inherited
Specific heat at constant pressure.
Units: J/kg/K.
Definition at line 965 of file ThermoPhase.h.
References ThermoPhase::cp_mole(), and Phase::meanMolecularWeight().
Referenced by PseudoBinaryVPSSTP::report(), MolarityIonicVPSSTP::report(), PureFluidPhase::report(), MolalityVPSSTP::report(), ThermoPhase::report(), PureFluidPhase::reportCSV(), MolalityVPSSTP::reportCSV(), ThermoPhase::reportCSV(), SingleSpeciesTP::setState_HP(), ThermoPhase::setState_HPorUV(), SingleSpeciesTP::setState_SP(), ThermoPhase::setState_SPorSV(), and StFlow::updateThermo().
doublereal cv_mass () const inline inherited
Specific heat at constant volume.
Units: J/kg/K.
Definition at line 972 of file ThermoPhase.h.
References ThermoPhase::cv_mole(), and Phase::meanMolecularWeight().
Referenced by PseudoBinaryVPSSTP::report(), MolarityIonicVPSSTP::report(), PureFluidPhase::report(), MolalityVPSSTP::report(), ThermoPhase::report(), PureFluidPhase::reportCSV(), MolalityVPSSTP::reportCSV(), ThermoPhase::reportCSV(), ThermoPhase::setState_HPorUV(), ThermoPhase::setState_SPorSV(), SingleSpeciesTP::setState_SV(), and SingleSpeciesTP::setState_UV().
doublereal _RT () const inline inherited
Return the Gas Constant multiplied by the current temperature.
The units are Joules kmol-1
Definition at line 981 of file ThermoPhase.h.
References Cantera::GasConstant, and Phase::temperature().
Referenced by MixtureFugacityTP::corr0(), RedlichKwongMFTP::enthalpy_mole(), VPStandardStateTP::getChemPotentials_RT(), MixtureFugacityTP::getChemPotentials_RT(), IdealSolnGasVPSS::getChemPotentials_RT(), RedlichKwongMFTP::getChemPotentials_RT(), PureFluidPhase::getEnthalpy_RT(), FixedChemPotSSTP::getEnthalpy_RT(), FixedChemPotSSTP::getEnthalpy_RT_ref(), WaterSSTP::getGibbs_ref(), MixtureFugacityTP::getGibbs_ref(), IdealGasPhase::getGibbs_ref(), PureFluidPhase::getGibbs_RT(), FixedChemPotSSTP::getGibbs_RT(), IdealSolidSolnPhase::getGibbs_RT(), LatticePhase::getGibbs_RT(), FixedChemPotSSTP::getGibbs_RT_ref(), MixtureFugacityTP::getIntEnergy_RT(), IdealMolalSoln::getPartialMolarEnthalpies(), ConstDensityThermo::getPureGibbs(), MixtureFugacityTP::getPureGibbs(), IdealGasPhase::getPureGibbs(), IdealSolidSolnPhase::getPureGibbs(), VPStandardStateTP::getStandardChemPotentials(), MixtureFugacityTP::getStandardChemPotentials(), IdealGasPhase::getStandardChemPotentials(), LatticePhase::getStandardChemPotentials(), MixtureFugacityTP::getStandardVolumes(), MixtureFugacityTP::getStandardVolumes_ref(), IdealGasPhase::getStandardVolumes_ref(), and MixtureFugacityTP::z().
void setState_TPX (doublereal t, doublereal p, const doublereal * x) virtual inherited
Set the temperature (K), pressure (Pa), and mole fractions.
Note, the mole fractions are set first before the pressure is set. Setting the pressure may involve the solution of a nonlinear equation.
Parameters
t Temperature (K)
p Pressure (Pa)
x Vector of mole fractions. Length is equal to m_kk.
Reimplemented in SingleSpeciesTP, and MixtureFugacityTP.
Definition at line 174 of file ThermoPhase.cpp.
References Phase::setMoleFractions(), ThermoPhase::setPressure(), and Phase::setTemperature().
Referenced by MultiTransport::getMassFluxes(), DustyGasTransport::getMolarFluxes(), MultiPhase::setMoles(), and MultiPhase::setPhaseMoleFractions().
void setState_TPX (doublereal t, doublereal p, compositionMap & x) inherited
Set the temperature (K), pressure (Pa), and mole fractions.
Note, the mole fractions are set first before the pressure is set. Setting the pressure may involve the solution of a nonlinear equation.
Parameters
t Temperature (K)
p Pressure (Pa)
x Composition map of mole fractions. Species not in the composition map are assumed to have zero mole fraction
Definition at line 181 of file ThermoPhase.cpp.
References Phase::setMoleFractionsByName(), ThermoPhase::setPressure(), and Phase::setTemperature().
void setState_TPX (doublereal t, doublereal p, const std::string & x) inherited
Set the temperature (K), pressure (Pa), and mole fractions.
Note, the mole fractions are set first before the pressure is set. Setting the pressure may involve the solution of a nonlinear equation.
Parameters
t Temperature (K)
p Pressure (Pa)
x String containing a composition map of the mole fractions. Species not in the composition map are assumed to have zero mole fraction
Definition at line 188 of file ThermoPhase.cpp.
References ThermoPhase::err(), Phase::nSpecies(), Cantera::parseCompString(), CanteraError::save(), Phase::setMoleFractionsByName(), ThermoPhase::setPressure(), Phase::setTemperature(), and Phase::speciesName().
void setState_TPY (doublereal t, doublereal p, const doublereal * y) inherited
Set the internally stored temperature (K), pressure (Pa), and mass fractions of the phase.
Note, the mass fractions are set first before the pressure is set. Setting the pressure may involve the solution of a nonlinear equation.
Parameters
t Temperature (K)
p Pressure (Pa)
y Vector of mass fractions. Length is equal to m_kk.
Definition at line 206 of file ThermoPhase.cpp.
References Phase::setMassFractions(), ThermoPhase::setPressure(), and Phase::setTemperature().
void setState_TPY (doublereal t, doublereal p, compositionMap & y) inherited
Set the internally stored temperature (K), pressure (Pa), and mass fractions of the phase.
Note, the mass fractions are set first before the pressure is set. Setting the pressure may involve the solution of a nonlinear equation.
Parameters
t Temperature (K)
p Pressure (Pa)
y Composition map of mass fractions. Species not in the composition map are assumed to have zero mass fraction
Definition at line 214 of file ThermoPhase.cpp.
References Phase::setMassFractionsByName(), ThermoPhase::setPressure(), and Phase::setTemperature().
void setState_TPY (doublereal t, doublereal p, const std::string & y) inherited
Set the internally stored temperature (K), pressure (Pa), and mass fractions of the phase.
Note, the mass fractions are set first before the pressure is set. Setting the pressure may involve the solution of a nonlinear equation.
Parameters
t Temperature (K)
p Pressure (Pa)
y String containing a composition map of the mass fractions. Species not in the composition map are assumed to have zero mass fraction
Definition at line 222 of file ThermoPhase.cpp.
References ThermoPhase::err(), Phase::nSpecies(), Cantera::parseCompString(), CanteraError::save(), Phase::setMassFractionsByName(), ThermoPhase::setPressure(), Phase::setTemperature(), and Phase::speciesName().
void setState_TP (doublereal t, doublereal p) inherited
Set the temperature (K) and pressure (Pa)
Setting the pressure may involve the solution of a nonlinear equation.
Parameters
t Temperature (K)
p Pressure (Pa)
Definition at line 242 of file ThermoPhase.cpp.
References ThermoPhase::setPressure(), and Phase::setTemperature().
Referenced by StoichSubstance::initThermo(), ImplicitSurfChem::setCommonState_TP(), SingleSpeciesTP::setState_HP(), ThermoPhase::setState_HPorUV(), SingleSpeciesTP::setState_SP(), ThermoPhase::setState_SPorSV(), vcs_VolPhase::setState_TP(), PDSS_IonsFromNeutral::setState_TP(), IonsFromNeutralVPSSTP::setState_TP(), and FlowReactor::updateState().
void setState_PX (doublereal p, doublereal * x) inherited
Set the pressure (Pa) and mole fractions.
Note, the mole fractions are set first before the pressure is set. Setting the pressure may involve the solution of a nonlinear equation.
Parameters
p Pressure (Pa)
x Vector of mole fractions. Length is equal to m_kk.
Definition at line 249 of file ThermoPhase.cpp.
References Phase::setMoleFractions(), and ThermoPhase::setPressure().
Referenced by vcs_VolPhase::_updateMoleFractionDependencies(), IdealSolnGasVPSS::setToEquilState(), RedlichKwongMFTP::setToEquilState(), IdealGasPhase::setToEquilState(), and IdealSolidSolnPhase::setToEquilState().
void setState_PY (doublereal p, doublereal * y) inherited
Set the internally stored pressure (Pa) and mass fractions.
Note, the temperature is held constant during this operation. Note, the mass fractions are set first before the pressure is set. Setting the pressure may involve the solution of a nonlinear equation.
Parameters
p Pressure (Pa)
y Vector of mass fractions. Length is equal to m_kk.
Definition at line 256 of file ThermoPhase.cpp.
References Phase::setMassFractions(), and ThermoPhase::setPressure().
void setState_HP (doublereal h, doublereal p, doublereal tol = 1.e-4) virtual inherited
Set the internally stored specific enthalpy (J/kg) and pressure (Pa) of the phase.
Parameters
h Specific enthalpy (J/kg)
p Pressure (Pa)
tol Optional parameter setting the tolerance of the calculation. Defaults to 1.0E-4
Reimplemented in SingleSpeciesTP, and PureFluidPhase.
Definition at line 263 of file ThermoPhase.cpp.
References ThermoPhase::setState_HPorUV().
Referenced by FlowReactor::updateState(), and ConstPressureReactor::updateState().
void setState_UV (doublereal u, doublereal v, doublereal tol = 1.e-4) virtual inherited
Set the specific internal energy (J/kg) and specific volume (m^3/kg).
This function fixes the internal state of the phase so that the specific internal energy and specific volume have the value of the input parameters.
Parameters
u specific internal energy (J/kg)
v specific volume (m^3/kg).
tol Optional parameter setting the tolerance of the calculation. Defaults to 1.0E-4
Reimplemented in SingleSpeciesTP, and PureFluidPhase.
Definition at line 270 of file ThermoPhase.cpp.
References ThermoPhase::setState_HPorUV().
Referenced by Reactor::updateState().
void setState_SP (doublereal s, doublereal p, doublereal tol = 1.e-4) virtual inherited
Set the specific entropy (J/kg/K) and pressure (Pa).
This function fixes the internal state of the phase so that the specific entropy and the pressure have the value of the input parameters.
Parameters
s specific entropy (J/kg/K)
p specific pressure (Pa).
tol Optional parameter setting the tolerance of the calculation. Defaults to 1.0E-4
Reimplemented in SingleSpeciesTP, and PureFluidPhase.
Definition at line 546 of file ThermoPhase.cpp.
References ThermoPhase::setState_SPorSV().
void setState_SV (doublereal s, doublereal v, doublereal tol = 1.e-4) virtual inherited
Set the specific entropy (J/kg/K) and specific volume (m^3/kg).
This function fixes the internal state of the phase so that the specific entropy and specific volume have the value of the input parameters.
Parameters
s specific entropy (J/kg/K)
v specific volume (m^3/kg).
tol Optional parameter setting the tolerance of the calculation. Defaults to 1.0E-4
Reimplemented in SingleSpeciesTP, and PureFluidPhase.
Definition at line 553 of file ThermoPhase.cpp.
References ThermoPhase::setState_SPorSV().
virtual void setToEquilState (const doublereal * lambda_RT) inline virtual inherited
This method is used by the ChemEquil equilibrium solver.
It sets the state such that the chemical potentials satisfy
\[ \frac{\mu_k}{\hat R T} = \sum_m A_{k,m} \left(\frac{\lambda_m} {\hat R T}\right) \]
where \(\lambda_m \) is the element potential of element m. The temperature is unchanged. Any phase (ideal or not) that implements this method can be equilibrated by ChemEquil.
Parameters
lambda_RT Input vector of dimensionless element potentials The length is equal to nElements().
Reimplemented in HMWSoln, DebyeHuckel, IdealSolidSolnPhase, IdealGasPhase, IdealMolalSoln, MolalityVPSSTP, RedlichKwongMFTP, IdealSolnGasVPSS, and ConstDensityThermo.
Definition at line 1193 of file ThermoPhase.h.
References ThermoPhase::err().
Referenced by ChemEquil::setToEquilState().
void setElementPotentials (const vector_fp & lambda) inherited
Stores the element potentials in the ThermoPhase object.
Called by function 'equilibrate' in ChemEquil.h to transfer the element potentials to this object after every successful equilibration routine. The element potentials are stored in their dimensionless forms, calculated by dividing by RT.
Parameters
lambda Input vector containing the element potentials. Length = nElements. Units are Joules/kmol.
Definition at line 1106 of file ThermoPhase.cpp.
References Cantera::GasConstant, ThermoPhase::m_hasElementPotentials, ThermoPhase::m_lambdaRRT, Phase::nElements(), and Phase::temperature().
Referenced by Cantera::equilibrate(), ChemEquil::equilibrate(), and Cantera::vcs_equilibrate().
bool getElementPotentials (doublereal * lambda) const inherited
Returns the element potentials stored in the ThermoPhase object.
Returns the stored element potentials. The element potentials are retrieved from their stored dimensionless forms by multiplying by RT.
Parameters
lambda Output vector containing the element potentials. Length = nElements. Units are Joules/kmol.
Returns
bool indicating whether there are any valid stored element potentials. The calling routine should check this bool. In the case that there aren't any, lambda is not touched.
Definition at line 1129 of file ThermoPhase.cpp.
References Cantera::GasConstant, ThermoPhase::m_hasElementPotentials, ThermoPhase::m_lambdaRRT, Phase::nElements(), and Phase::temperature().
Referenced by ChemEquil::equilibrate().
virtual doublereal critTemperature () const inline virtual inherited
Critical temperature (K).
Reimplemented in HMWSoln, IdealMolalSoln, RedlichKwongMFTP, PureFluidPhase, and WaterSSTP.
Definition at line 1236 of file ThermoPhase.h.
References ThermoPhase::err().
Referenced by MixtureFugacityTP::calculatePsat(), MixtureFugacityTP::densityCalc(), MixtureFugacityTP::phaseState(), and MixtureFugacityTP::psatEst().
virtual doublereal critPressure () const inline virtual inherited
Critical pressure (Pa).
Reimplemented in HMWSoln, IdealMolalSoln, RedlichKwongMFTP, PureFluidPhase, and WaterSSTP.
Definition at line 1242 of file ThermoPhase.h.
References ThermoPhase::err().
Referenced by MixtureFugacityTP::calculatePsat(), and MixtureFugacityTP::psatEst().
virtual doublereal critDensity () const inline virtual inherited
Critical density (kg/m3).
Reimplemented in HMWSoln, IdealMolalSoln, RedlichKwongMFTP, PureFluidPhase, and WaterSSTP.
Definition at line 1248 of file ThermoPhase.h.
References ThermoPhase::err().
Referenced by MixtureFugacityTP::densityCalc(), and MixtureFugacityTP::phaseState().
virtual doublereal satTemperature (doublereal p) const inline virtual inherited
Return the saturation temperature given the pressure.
Parameters
p Pressure (Pa)
Reimplemented in HMWSoln, DebyeHuckel, SingleSpeciesTP, and PureFluidPhase.
Definition at line 1267 of file ThermoPhase.h.
References ThermoPhase::err().
virtual doublereal satPressure (doublereal t) const inline virtual inherited
Return the saturation pressure given the temperature.
Parameters
t Temperature (Kelvin)
Reimplemented in HMWSoln, DebyeHuckel, SingleSpeciesTP, PureFluidPhase, and WaterSSTP.
Definition at line 1276 of file ThermoPhase.h.
References ThermoPhase::err().
virtual doublereal vaporFraction () const inline virtual inherited
Return the fraction of vapor at the current conditions.
Reimplemented in HMWSoln, DebyeHuckel, SingleSpeciesTP, PureFluidPhase, and WaterSSTP.
Definition at line 1282 of file ThermoPhase.h.
References ThermoPhase::err().
virtual void setState_Tsat (doublereal t, doublereal x) inline virtual inherited
Set the state to a saturated system at a particular temperature.
Parameters
t Temperature (kelvin)
x Fraction of vapor
Reimplemented in HMWSoln, DebyeHuckel, SingleSpeciesTP, and PureFluidPhase.
Definition at line 1292 of file ThermoPhase.h.
References ThermoPhase::err().
virtual void setState_Psat (doublereal p, doublereal x) inline virtual inherited
Set the state to a saturated system at a particular pressure.
Parameters
p Pressure (Pa)
x Fraction of vapor
Reimplemented in HMWSoln, DebyeHuckel, SingleSpeciesTP, and PureFluidPhase.
Definition at line 1301 of file ThermoPhase.h.
References ThermoPhase::err().
void saveSpeciesData (const size_t k, const XML_Node *const data) inherited
Store a reference pointer to the XML tree containing the species data for this phase.
The following methods are used in the process of constructing the phase and setting its parameters from a specification in an input file. They are not normally used in application programs. To see how they are used, see files importCTML.cpp and ThermoFactory.cpp.
This is used to access data needed to construct transport manager later.
Parameters
k Species index
data Pointer to the XML_Node data containing information about the species in the phase.
Definition at line 1050 of file ThermoPhase.cpp.
References ThermoPhase::m_speciesData.
Referenced by FixedChemPotSSTP::FixedChemPotSSTP(), and Cantera::importPhase().
const std::vector< const XML_Node * > & speciesData () const inherited
Return a pointer to the vector of XML nodes containing the species data for this phase.
Definition at line 1060 of file ThermoPhase.cpp.
References Phase::m_kk, and ThermoPhase::m_speciesData.
Referenced by MineralEQ3::initThermoXML(), DebyeHuckel::initThermoXML(), TransportFactory::initTransport(), LatticeSolidPhase::installSlavePhases(), and TransportFactory::setupLiquidTransport().
void setSpeciesThermo (SpeciesThermo * spthermo) inherited
Install a species thermodynamic property manager.
The species thermodynamic property manager computes properties of the pure species for use in constructing solution properties. It is meant for internal use, and some classes derived from ThermoPhase may not use any species thermodynamic property manager. This method is called by function importPhase() in importCTML.cpp.
Parameters
spthermo input pointer to the species thermodynamic property manager.
Definition at line 886 of file ThermoPhase.cpp.
References ThermoPhase::m_spthermo.
Referenced by FixedChemPotSSTP::FixedChemPotSSTP(), Cantera::importPhase(), LatticeSolidPhase::installSlavePhases(), and VPSSMgrFactory::newVPSSMgr().
SpeciesThermo & speciesThermo (int k = -1) virtual inherited
Return a changeable reference to the calculation manager for species reference-state thermodynamic properties.
Parameters
k Speices id. The default is -1, meaning return the default
Reimplemented in LatticeSolidPhase.
Definition at line 904 of file ThermoPhase.cpp.
References ThermoPhase::m_spthermo.
Referenced by PDSS_ConstVol::constructPDSSXML(), PDSS_SSVol::constructPDSSXML(), PDSS_ConstVol::initThermo(), PDSS_IdealGas::initThermo(), PDSS_IonsFromNeutral::initThermo(), PDSS_SSVol::initThermo(), VPSSMgrFactory::newVPSSMgr(), and PDSS::PDSS().
void initThermoFile (std::string inputFile, std::string id) virtual inherited
Initialization of a ThermoPhase object using an ctml file.
This routine is a precursor to initThermoXML(XML_Node*) routine, which does most of the work. Here we read extra information about the XML description of a phase. Regular information about elements and species and their reference state thermodynamic information have already been read at this point. For example, we do not need to call this function for ideal gas equations of state.
Parameters
inputFile XML file containing the description of the phase
id Optional parameter identifying the name of the phase. If none is given, the first XML phase element encountered will be used.
Definition at line 928 of file ThermoPhase.cpp.
References XML_Node::build(), XML_Node::copy(), Cantera::findInputFile(), Cantera::findXMLPhase(), ThermoPhase::initThermoXML(), and Phase::xml().
void initThermoXML (XML_Node & phaseNode, std::string id) virtual inherited
Import and initialize a ThermoPhase object using an XML tree.
Here we read extra information about the XML description of a phase. Regular information about elements and species and their reference state thermodynamic information have already been read at this point. For example, we do not need to call this function for ideal gas equations of state. This function is called from importPhase() after the elements and the species are initialized with default ideal solution level data.
The default implementation in ThermoPhase calls the virtual function initThermo() and then sets the "state" of the phase by looking for an XML element named "state", and then interpreting its contents by calling the virtual function setStateFromXML().
Parameters
phaseNode This object must be the phase node of a complete XML tree description of the phase, including all of the species data. In other words while "phase" must point to an XML phase object, it must have sibling nodes "speciesData" that describe the species in the phase.
id ID of the phase. If nonnull, a check is done to see if phaseNode is pointing to the phase with the correct id.
Reimplemented in HMWSoln, DebyeHuckel, IdealSolidSolnPhase, LatticePhase, IdealMolalSoln, MolalityVPSSTP, MixedSolventElectrolyte, MargulesVPSSTP, RedlichKisterVPSSTP, PhaseCombo_Interaction, MixtureFugacityTP, IonsFromNeutralVPSSTP, FixedChemPotSSTP, electrodeElectron, VPStandardStateTP, RedlichKwongMFTP, MineralEQ3, MetalSHEelectrons, WaterSSTP, StoichSubstanceSSTP, MolarityIonicVPSSTP, IdealSolnGasVPSS, and PseudoBinaryVPSSTP.
Definition at line 979 of file ThermoPhase.cpp.
References XML_Node::child(), XML_Node::hasChild(), ThermoPhase::setReferenceComposition(), and ThermoPhase::setStateFromXML().
Referenced by Cantera::importPhase(), ThermoPhase::initThermoFile(), StoichSubstanceSSTP::initThermoXML(), MetalSHEelectrons::initThermoXML(), VPStandardStateTP::initThermoXML(), electrodeElectron::initThermoXML(), FixedChemPotSSTP::initThermoXML(), MixtureFugacityTP::initThermoXML(), LatticePhase::initThermoXML(), and IdealSolidSolnPhase::initThermoXML().
void installSlavePhases (Cantera::XML_Node * phaseNode) virtual inherited
Add in species from Slave phases.
This hook is used for cSS_CONVENTION_SLAVE phases
Parameters
phaseNode XML Element for the phase
Reimplemented in LatticeSolidPhase.
Definition at line 1045 of file ThermoPhase.cpp.
Referenced by Cantera::importPhase().
virtual void getParameters (int & n, doublereal *const c) const inline virtual inherited
Get the equation of state parameters in a vector.
The number and meaning of these depends on the subclass.
Parameters
n number of parameters
c array of n coefficients
Reimplemented in HMWSoln, DebyeHuckel, LatticePhase, IdealMolalSoln, SingleSpeciesTP, FixedChemPotSSTP, MineralEQ3, MetalSHEelectrons, StoichSubstanceSSTP, StoichSubstance, and ConstDensityThermo.
Definition at line 1462 of file ThermoPhase.h.
virtual void getdlnActCoeffds (const doublereal dTds, const doublereal *const dXds, doublereal * dlnActCoeffds) const inline virtual inherited
Get the change in activity coefficients wrt changes in state (temp, mole fraction, etc) along a line in parameter space or along a line in physical space.
Parameters
dTds Input of temperature change along the path
dXds Input vector of changes in mole fraction along the path. length = m_kk Along the path length it must be the case that the mole fractions sum to one.
dlnActCoeffds Output vector of the directional derivatives of the log Activity Coefficients along the path. length = m_kk units are 1/units(s). if s is a physical coordinate then the units are 1/m.
Reimplemented in MixedSolventElectrolyte, MargulesVPSSTP, RedlichKisterVPSSTP, PhaseCombo_Interaction, and IonsFromNeutralVPSSTP.
Definition at line 1511 of file ThermoPhase.h.
References ThermoPhase::err().
Referenced by IonsFromNeutralVPSSTP::getdlnActCoeffds(), and LiquidTransport::update_Grad_lnAC().
virtual void getdlnActCoeffdlnX_diag (doublereal * dlnActCoeffdlnX_diag) const inline virtual inherited
Get the array of ln mole fraction derivatives of the log activity coefficients - diagonal component only.
This function is a virtual method. For ideal mixtures (unity activity coefficients), this can return zero. Implementations should take the derivative of the logarithm of the activity coefficient with respect to the logarithm of the mole fraction variable that represents the standard state. This quantity is to be used in conjunction with derivatives of that mole fraction variable when the derivative of the chemical potential is taken.
units = dimensionless
Parameters
dlnActCoeffdlnX_diag Output vector of derivatives of the log Activity Coefficients wrt the mole fractions. length = m_kk
Reimplemented in MixedSolventElectrolyte, MargulesVPSSTP, RedlichKisterVPSSTP, PhaseCombo_Interaction, and IonsFromNeutralVPSSTP.
Definition at line 1533 of file ThermoPhase.h.
References ThermoPhase::err().
Referenced by IonsFromNeutralVPSSTP::s_update_dlnActCoeff_dlnX_diag().
virtual void getdlnActCoeffdlnN_diag (doublereal * dlnActCoeffdlnN_diag) const inline virtual inherited
Get the array of log species mole number derivatives of the log activity coefficients.
This function is a virtual method. For ideal mixtures (unity activity coefficients), this can return zero. Implementations should take the derivative of the logarithm of the activity coefficient with respect to the logarithm of the concentration-like variable (i.e. moles) that represents the standard state. This quantity is to be used in conjunction with derivatives of that species mole number variable when the derivative of the chemical potential is taken.
units = dimensionless
Parameters
dlnActCoeffdlnN_diag Output vector of derivatives of the log Activity Coefficients. length = m_kk
Reimplemented in MixedSolventElectrolyte, MargulesVPSSTP, RedlichKisterVPSSTP, PhaseCombo_Interaction, IonsFromNeutralVPSSTP, MixtureFugacityTP, and VPStandardStateTP.
Definition at line 1554 of file ThermoPhase.h.
References ThermoPhase::err().
void getdlnActCoeffdlnN (const size_t ld, doublereal *const dlnActCoeffdlnN) virtual inherited
Get the array of derivatives of the log activity coefficients with respect to the log of the species mole numbers.
Implementations should take the derivative of the logarithm of the activity coefficient with respect to a species log mole number (with all other species mole numbers held constant). The default treatment in the ThermoPhase object is to set this vector to zero.
units = 1 / kmol
dlnActCoeffdlnN[ ld * k + m] will contain the derivative of log act_coeff for the mth species with respect to the number of moles of the kth species.
\[ \frac{d \ln(\gamma_m) }{d \ln(n_k) }\Bigg|_{n_i} \]
Parameters
ld Number of rows in the matrix
dlnActCoeffdlnN Output vector of derivatives of the log Activity Coefficients. length = m_kk * m_kk
Reimplemented in MolalityVPSSTP, MixedSolventElectrolyte, MargulesVPSSTP, RedlichKisterVPSSTP, PhaseCombo_Interaction, IonsFromNeutralVPSSTP, and GibbsExcessVPSSTP.
Definition at line 1158 of file ThermoPhase.cpp.
References Phase::m_kk.
Referenced by vcs_VolPhase::_updateLnActCoeffJac().
std::string report (bool show_thermo = true) const virtual inherited
returns a summary of the state of the phase as a string
Parameters
show_thermo If true, extra information is printed out about the thermodynamic state of the system.
Reimplemented in MolalityVPSSTP, PureFluidPhase, MolarityIonicVPSSTP, and PseudoBinaryVPSSTP.
Definition at line 1243 of file ThermoPhase.cpp.
References ThermoPhase::cp_mass(), ThermoPhase::cp_mole(), ThermoPhase::cv_mass(), ThermoPhase::cv_mole(), Phase::density(), ThermoPhase::electricPotential(), ThermoPhase::enthalpy_mass(), ThermoPhase::enthalpy_mole(), ThermoPhase::entropy_mass(), ThermoPhase::entropy_mole(), ThermoPhase::err(), Cantera::GasConstant, ThermoPhase::getChemPotentials(), Phase::getMassFractions(), Phase::getMoleFractions(), ThermoPhase::gibbs_mass(), ThermoPhase::gibbs_mole(), ThermoPhase::intEnergy_mass(), ThermoPhase::intEnergy_mole(), Phase::meanMolecularWeight(), Phase::name(), Phase::nSpecies(), ThermoPhase::pressure(), CanteraError::save(), Cantera::SmallNumber, Phase::speciesName(), and Phase::temperature().
Referenced by Cantera::operator<<(), and Cantera::report().
void reportCSV (std::ofstream & csvFile) const virtual inherited
returns a summary of the state of the phase to a comma separated file
Parameters
csvFile ofstream file to print comma separated data for the phase
Reimplemented in MolalityVPSSTP, and PureFluidPhase.
Definition at line 1350 of file ThermoPhase.cpp.
References ThermoPhase::cp_mass(), ThermoPhase::cp_mole(), ThermoPhase::cv_mass(), ThermoPhase::cv_mole(), Phase::density(), ThermoPhase::electricPotential(), ThermoPhase::enthalpy_mass(), ThermoPhase::enthalpy_mole(), ThermoPhase::entropy_mass(), ThermoPhase::entropy_mole(), ThermoPhase::err(), ThermoPhase::getActivities(), ThermoPhase::getActivityCoefficients(), ThermoPhase::getChemPotentials(), Phase::getMassFractions(), Phase::getMoleFractions(), ThermoPhase::getPartialMolarCp(), ThermoPhase::getPartialMolarEnthalpies(), ThermoPhase::getPartialMolarEntropies(), ThermoPhase::getPartialMolarIntEnergies(), ThermoPhase::getPartialMolarVolumes(), ThermoPhase::gibbs_mass(), ThermoPhase::gibbs_mole(), ThermoPhase::intEnergy_mass(), ThermoPhase::intEnergy_mole(), Phase::meanMolecularWeight(), Phase::name(), Phase::nSpecies(), ThermoPhase::pressure(), CanteraError::save(), Cantera::SmallNumber, Phase::speciesName(), and Phase::temperature().
XML_Node & xml () inherited
Returns a reference to the XML_Node stored for the phase.
The XML_Node for the phase contains all of the input data used to set up the model for the phase, during its initialization.
Definition at line 125 of file Phase.cpp.
References Phase::m_xml.
Referenced by MolarityIonicVPSSTP::constructPhaseFile(), LatticePhase::constructPhaseFile(), RedlichKisterVPSSTP::constructPhaseFile(), MargulesVPSSTP::constructPhaseFile(), MixedSolventElectrolyte::constructPhaseFile(), WaterSSTP::constructPhaseFile(), PhaseCombo_Interaction::constructPhaseFile(), IonsFromNeutralVPSSTP::constructPhaseFile(), IdealMolalSoln::constructPhaseFile(), IdealSolidSolnPhase::constructPhaseFile(), DebyeHuckel::constructPhaseFile(), Cantera::importPhase(), SimpleTransport::initLiquid(), ThermoPhase::initThermoFile(), TransportFactory::newTransport(), and TransportFactory::setupLiquidTransport().
std::string id () const inherited
Return the string id for the phase.
Definition at line 130 of file Phase.cpp.
References Phase::m_id.
Referenced by Kinetics::assignShallowPointers(), Cantera::equilibrate(), Cantera::getEfficiencies(), Cantera::importPhase(), LatticeSolidPhase::installSlavePhases(), Kinetics::kineticsSpeciesIndex(), MultiPhase::phaseIndex(), MultiPhase::phaseName(), solveProb::print_header(), RedlichKwongMFTP::RedlichKwongMFTP(), Phase::setID(), LatticeSolidPhase::setParametersFromXML(), vcs_VolPhase::transferElementsFM(), and Cantera::vcs_equilibrate().
void setID (std::string id) inherited
Set the string id for the phase.
Parameters
id String id of the phase
Definition at line 135 of file Phase.cpp.
References Phase::id(), and Phase::m_id.
Referenced by FixedChemPotSSTP::FixedChemPotSSTP(), and Cantera::importPhase().
std::string name () const inherited
Return the name of the phase.
Definition at line 140 of file Phase.cpp.
References Phase::m_name.
Referenced by Cantera::operator<<(), PseudoBinaryVPSSTP::report(), MolarityIonicVPSSTP::report(), PureFluidPhase::report(), MolalityVPSSTP::report(), ThermoPhase::report(), PureFluidPhase::reportCSV(), vcs_MultiPhaseEquil::reportCSV(), MolalityVPSSTP::reportCSV(), and ThermoPhase::reportCSV().
void setName (std::string nm) inherited
Sets the string name for the phase.
Parameters
nm String name of the phase
Definition at line 145 of file Phase.cpp.
References Phase::m_name.
Referenced by FixedChemPotSSTP::FixedChemPotSSTP(), and Cantera::importPhase().
string elementName (size_t m) const inherited
Name of the element with index m.
Parameters
m Element index.
Definition at line 169 of file Phase.cpp.
References Phase::checkElementIndex(), and Phase::m_elementNames.
Referenced by MultiPhase::addPhase(), Cantera::checkRxnElementBalance(), Cantera::convertDGFormation(), PDSS_HKFT::convertDGFormation(), ChemEquil::equilibrate(), ChemEquil::equilResidual(), ChemEquil::estimateElementPotentials(), ChemEquil::estimateEP_Brinkley(), MolalityVPSSTP::findCLMIndex(), ChemEquil::initialize(), LatticeSolidPhase::installSlavePhases(), Cantera::installSpecies(), ChemEquil::setInitialMoles(), and vcs_VolPhase::transferElementsFM().
size_t elementIndex (std::string name) const inherited
Return the index of element named 'name'.
The index is an integer assigned to each element in the order it was added. Returns npos if the specified element is not found.
Parameters
name Name of the element
Definition at line 175 of file Phase.cpp.
References Phase::m_elementNames, Phase::m_mm, and Cantera::npos.
Referenced by Phase::addUniqueElementAfterFreeze(), MultiPhase::init(), WaterSSTP::initThermoXML(), LatticeSolidPhase::installSlavePhases(), Cantera::installSpecies(), Cantera::LookupGe(), and PDSS_HKFT::LookupGe().
const vector< string > & elementNames () const inherited
Return a read-only reference to the vector of element names.
Definition at line 185 of file Phase.cpp.
References Phase::m_elementNames.
Referenced by ChemEquil::equilibrate(), ChemEquil::estimateEP_Brinkley(), and IonsFromNeutralVPSSTP::initThermoXML().
doublereal atomicWeight (size_t m) const inherited
Atomic weight of element m.
Parameters
m Element index
Definition at line 190 of file Phase.cpp.
References Phase::m_atomicWeights.
Referenced by ChemEquil::initialize(), and WaterSSTP::initThermoXML().
doublereal entropyElement298 (size_t m) const inherited
Entropy of the element in its standard state at 298 K and 1 bar.
Parameters
m Element index
Definition at line 195 of file Phase.cpp.
References AssertThrowMsg, AssertTrace, ENTROPY298_UNKNOWN, Phase::m_entropy298, and Phase::m_mm.
Referenced by LatticeSolidPhase::installSlavePhases(), Cantera::LookupGe(), and PDSS_HKFT::LookupGe().
int atomicNumber (size_t m) const inherited
Atomic number of element m.
Parameters
m Element index
Definition at line 209 of file Phase.cpp.
References Phase::m_atomicNumbers.
Referenced by MultiPhase::addPhase(), and LatticeSolidPhase::installSlavePhases().
int elementType (size_t m) const inherited
Return the element constraint type Possible types include:
CT_ELEM_TYPE_TURNEDOFF -1 CT_ELEM_TYPE_ABSPOS 0 CT_ELEM_TYPE_ELECTRONCHARGE 1 CT_ELEM_TYPE_CHARGENEUTRALITY 2 CT_ELEM_TYPE_LATTICERATIO 3 CT_ELEM_TYPE_KINETICFROZEN 4 CT_ELEM_TYPE_SURFACECONSTRAINT 5 CT_ELEM_TYPE_OTHERCONSTRAINT 6
The default is CT_ELEM_TYPE_ABSPOS.
Parameters
m Element index
Returns
Returns the element type
Definition at line 214 of file Phase.cpp.
References Phase::m_elem_type.
Referenced by LatticeSolidPhase::installSlavePhases(), and vcs_VolPhase::transferElementsFM().
int changeElementType (int m, int elem_type) inherited
Change the element type of the mth constraint Reassigns an element type.
Parameters
m Element index
elem_type New elem type to be assigned
Returns
Returns the old element type
Definition at line 219 of file Phase.cpp.
References Phase::m_elem_type.
const vector_fp & atomicWeights () const inherited
Return a read-only reference to the vector of atomic weights.
Definition at line 204 of file Phase.cpp.
References Phase::m_atomicWeights.
Referenced by LatticeSolidPhase::installSlavePhases().
size_t nElements () const inherited
Number of elements.
Definition at line 150 of file Phase.cpp.
References Phase::m_mm.
Referenced by MultiPhase::addPhase(), Cantera::checkRxnElementBalance(), Cantera::convertDGFormation(), PDSS_HKFT::convertDGFormation(), ChemEquil::equilibrate(), MolalityVPSSTP::findCLMIndex(), FixedChemPotSSTP::FixedChemPotSSTP(), ThermoPhase::getElementPotentials(), ChemEquil::initialize(), IdealSolidSolnPhase::initLengths(), ConstDensityThermo::initThermo(), LatticeSolidPhase::initThermo(), IdealGasPhase::initThermo(), LatticePhase::initThermo(), IonsFromNeutralVPSSTP::initThermoXML(), LatticeSolidPhase::installSlavePhases(), Cantera::installSpecies(), ThermoPhase::setElementPotentials(), vcs_VolPhase::setPtrThermoPhase(), and vcs_VolPhase::transferElementsFM().
void checkElementIndex (size_t m) const inherited
Check that the specified element index is in range Throws an exception if m is greater than nElements()-1.
Definition at line 155 of file Phase.cpp.
References Phase::m_mm.
Referenced by Phase::elementName(), and Phase::nAtoms().
void checkElementArraySize (size_t mm) const inherited
Check that an array size is at least nElements() Throws an exception if mm is less than nElements().
Used before calls which take an array pointer.
Definition at line 162 of file Phase.cpp.
References Phase::m_mm.
doublereal nAtoms (size_t k, size_t m) const inherited
Number of atoms of element m in species k.
Parameters
k species index
m element index
Definition at line 226 of file Phase.cpp.
References Phase::checkElementIndex(), Phase::checkSpeciesIndex(), Phase::m_mm, and Phase::m_speciesComp.
Referenced by Cantera::checkRxnElementBalance(), Cantera::convertDGFormation(), PDSS_HKFT::convertDGFormation(), MolalityVPSSTP::findCLMIndex(), MultiPhase::init(), ChemEquil::initialize(), IonsFromNeutralVPSSTP::initThermoXML(), IdealSolidSolnPhase::setToEquilState(), and vcs_VolPhase::transferElementsFM().
void getAtoms (size_t k, double * atomArray) const inherited
Get a vector containing the atomic composition of species k.
Parameters
k species index
atomArray vector containing the atomic number in the species. Length: m_mm
Definition at line 233 of file Phase.cpp.
References Phase::m_mm, and Phase::m_speciesComp.
Referenced by LatticeSolidPhase::installSlavePhases().
size_t speciesIndex (std::string name) const inherited
Returns the index of a species named 'name' within the Phase object.
The first species in the phase will have an index 0, and the last one will have an index of nSpecies() - 1.
Parameters
name String name of the species. It may also be in the form phaseName:speciesName
Returns
The index of the species. If the name is not found, the value npos is returned.
Definition at line 240 of file Phase.cpp.
References Phase::m_id, Phase::m_kk, Phase::m_name, Phase::m_speciesNames, Cantera::npos, and Cantera::parseSpeciesName().
Referenced by PDSS_IonsFromNeutral::constructPDSSXML(), TransportFactory::getLiquidInteractionsTransportData(), TransportFactory::getLiquidSpeciesTransportData(), Cantera::getStick(), HMWSoln::HMWSoln(), Cantera::importSolution(), LiquidTranInteraction::init(), DebyeHuckel::initThermoXML(), FlowDevice::install(), Kinetics::kineticsSpeciesIndex(), MargulesVPSSTP::MargulesVPSSTP(), Phase::massFraction(), MixedSolventElectrolyte::MixedSolventElectrolyte(), Phase::moleFraction(), PhaseCombo_Interaction::PhaseCombo_Interaction(), PhaseCombo_Interaction::readXMLBinarySpecies(), RedlichKisterVPSSTP::readXMLBinarySpecies(), MargulesVPSSTP::readXMLBinarySpecies(), MixedSolventElectrolyte::readXMLBinarySpecies(), RedlichKwongMFTP::readXMLCrossFluid(), RedlichKwongMFTP::readXMLPureFluid(), RedlichKisterVPSSTP::RedlichKisterVPSSTP(), MolalityVPSSTP::report(), MolalityVPSSTP::reportCSV(), and Kinetics::speciesPhase().
string speciesName (size_t k) const inherited
Name of the species with index k.
Parameters
k index of the species
Definition at line 257 of file Phase.cpp.
References Phase::checkSpeciesIndex(), and Phase::m_speciesNames.
Referenced by StFlow::componentName(), ReactingSurf1D::componentName(), ChemEquil::estimateElementPotentials(), ChemEquil::estimateEP_Brinkley(), MolalityVPSSTP::findCLMIndex(), TransportFactory::fitProperties(), AqueousTransport::getLiquidTransportData(), Phase::getMoleFractionsByName(), Cantera::importSolution(), MultiPhase::init(), ChemEquil::initialize(), LiquidTransport::initLiquid(), SimpleTransport::initLiquid(), IdealMolalSoln::initThermoXML(), DebyeHuckel::initThermoXML(), FlowDevice::install(), LatticeSolidPhase::installSlavePhases(), Kinetics::kineticsSpeciesName(), solveProb::print_header(), HMWSoln::printCoeffs(), PhaseCombo_Interaction::readXMLBinarySpecies(), RedlichKisterVPSSTP::readXMLBinarySpecies(), MargulesVPSSTP::readXMLBinarySpecies(), MixedSolventElectrolyte::readXMLBinarySpecies(), PureFluidPhase::report(), MolalityVPSSTP::report(), ThermoPhase::report(), PureFluidPhase::reportCSV(), vcs_MultiPhaseEquil::reportCSV(), MolalityVPSSTP::reportCSV(), ThermoPhase::reportCSV(), HMWSoln::s_updatePitzer_d2lnMolalityActCoeff_dT2(), HMWSoln::s_updatePitzer_dlnMolalityActCoeff_dP(), HMWSoln::s_updatePitzer_dlnMolalityActCoeff_dT(), HMWSoln::s_updatePitzer_lnMolalityActCoeff(), StFlow::save(), SurfPhase::setCoveragesByName(), ChemEquil::setInitialMoles(), Phase::setMassFractionsByName(), MolalityVPSSTP::setMolalitiesByName(), Phase::setMoleFractionsByName(), ThermoPhase::setState_TPX(), ThermoPhase::setState_TPY(), Inlet1D::showSolution(), ReactingSurf1D::showSolution(), Phase::speciesSPName(), and ChemEquil::update().
std::string speciesSPName (int k) const inherited
Returns the expanded species name of a species, including the phase name This is guaranteed to be unique within a Cantera problem.
Parameters
k Species index within the phase
Returns
The "phaseName:speciesName" string
Definition at line 282 of file Phase.cpp.
References Phase::m_name, and Phase::speciesName().
const vector< string > & speciesNames () const inherited
Return a const reference to the vector of species names.
Definition at line 263 of file Phase.cpp.
References Phase::m_speciesNames.
Referenced by PDSS_ConstVol::constructPDSSFile(), PDSS_HKFT::constructPDSSFile(), PDSS_IonsFromNeutral::constructPDSSFile(), PDSS_SSVol::constructPDSSFile(), VPSSMgr_ConstVol::initThermoXML(), VPSSMgr_Water_ConstVol::initThermoXML(), VPSSMgr_Water_HKFT::initThermoXML(), IdealMolalSoln::initThermoXML(), LatticePhase::initThermoXML(), IdealSolidSolnPhase::initThermoXML(), DebyeHuckel::initThermoXML(), TransportFactory::setupLiquidTransport(), and TransportFactory::setupMM().
size_t nSpecies () const inline inherited
Returns the number of species in the phase.
Definition at line 252 of file Phase.h.
References Phase::m_kk.
Referenced by MultiPhase::addPhase(), InterfaceKinetics::applyButlerVolmerCorrection(), Kinetics::assignShallowPointers(), MultiPhase::calcElemAbundances(), Phase::chargeDensity(), MultiPhaseEquil::computeReactionSteps(), PDSS_IonsFromNeutral::constructPDSSXML(), RedlichKisterVPSSTP::cp_mole(), MargulesVPSSTP::cp_mole(), MixedSolventElectrolyte::cp_mole(), PhaseCombo_Interaction::cp_mole(), SolidTransport::electricalConductivity(), RedlichKisterVPSSTP::enthalpy_mole(), MargulesVPSSTP::enthalpy_mole(), MixedSolventElectrolyte::enthalpy_mole(), PhaseCombo_Interaction::enthalpy_mole(), RedlichKisterVPSSTP::entropy_mole(), MargulesVPSSTP::entropy_mole(), MixedSolventElectrolyte::entropy_mole(), PhaseCombo_Interaction::entropy_mole(), ChemEquil::equilibrate(), vcs_MultiPhaseEquil::equilibrate_TP(), ChemEquil::estimateElementPotentials(), ThermoPhase::getActivities(), MetalPhase::getActivityConcentrations(), MetalPhase::getChemPotentials(), IonsFromNeutralVPSSTP::getdlnActCoeffds(), MetalPhase::getEnthalpy_RT(), MetalPhase::getEntropy_R(), AqueousKinetics::getEquilibriumConstants(), InterfaceKinetics::getEquilibriumConstants(), MultiTransport::getMassFluxes(), LTI_Pairwise_Interaction::getMatrixTransProp(), LTI_StefanMaxwell_PPN::getMatrixTransProp(), SolidTransport::getMixDiffCoeffs(), LTI_MoleFracs::getMixTransProp(), LTI_MassFracs::getMixTransProp(), LTI_Log_MoleFracs::getMixTransProp(), LTI_Pairwise_Interaction::getMixTransProp(), LTI_StefanMaxwell_PPN::getMixTransProp(), LTI_MoleFracs_ExpT::getMixTransProp(), SolidTransport::getMobilities(), MultiTransport::getMolarFluxes(), Phase::getMoleFractionsByName(), MultiPhase::getMoles(), MetalPhase::getStandardChemPotentials(), ImplicitSurfChem::ImplicitSurfChem(), Cantera::importSolution(), LiquidTranInteraction::init(), MultiPhase::init(), AqueousKinetics::init(), GasKinetics::init(), InterfaceKinetics::init(), GasTransport::initGas(), ChemEquil::initialize(), DustyGasTransport::initialize(), PseudoBinaryVPSSTP::initLengths(), IdealSolnGasVPSS::initLengths(), MolarityIonicVPSSTP::initLengths(), GibbsExcessVPSSTP::initLengths(), VPStandardStateTP::initLengths(), IonsFromNeutralVPSSTP::initLengths(), MixtureFugacityTP::initLengths(), VPSSMgr::initLengths(), PhaseCombo_Interaction::initLengths(), RedlichKisterVPSSTP::initLengths(), MargulesVPSSTP::initLengths(), MixedSolventElectrolyte::initLengths(), MolalityVPSSTP::initLengths(), IdealMolalSoln::initLengths(), IdealSolidSolnPhase::initLengths(), DebyeHuckel::initLengths(), HMWSoln::initLengths(), LiquidTransport::initLiquid(), SimpleTransport::initLiquid(), AqueousTransport::initLiquid(), ConstDensityThermo::initThermo(), StoichSubstance::initThermo(), StoichSubstanceSSTP::initThermo(), LatticeSolidPhase::initThermo(), SingleSpeciesTP::initThermo(), LatticePhase::initThermo(), FlowDevice::install(), rxninfo::installReaction(), LatticeSolidPhase::installSlavePhases(), Kinetics::nTotalSpecies(), solveProb::print_header(), PseudoBinaryVPSSTP::report(), MolarityIonicVPSSTP::report(), PureFluidPhase::report(), MolalityVPSSTP::report(), ThermoPhase::report(), PureFluidPhase::reportCSV(), vcs_MultiPhaseEquil::reportCSV(), MolalityVPSSTP::reportCSV(), ThermoPhase::reportCSV(), Phase::restoreState(), IonsFromNeutralVPSSTP::s_update_dlnActCoeff_dlnN(), Phase::saveState(), Kinetics::selectPhase(), ImplicitSurfChem::setConcSpecies(), SurfPhase::setCoveragesByName(), Phase::setMassFractionsByName(), MolalityVPSSTP::setMolalitiesByName(), Phase::setMoleFractionsByName(), MultiPhase::setMoles(), SolidTransport::setParameters(), MultiPhase::setPhaseMoleFractions(), vcs_VolPhase::setPtrThermoPhase(), ThermoPhase::setState_TPX(), ThermoPhase::setState_TPY(), Transport::setThermo(), ReactorBase::setThermoMgr(), TransportFactory::setupLiquidTransport(), TransportFactory::setupMM(), Inlet1D::showSolution(), solveSP::solveSP(), StFlow::StFlow(), vcs_VolPhase::transferElementsFM(), AqueousKinetics::updateKc(), InterfaceKinetics::updateKc(), ConstPressureReactor::updateState(), Reactor::updateState(), and MultiPhase::uploadMoleFractionsFromPhases().
void checkSpeciesIndex (size_t k) const inherited
Check that the specified species index is in range Throws an exception if k is greater than nSpecies()-1.
Definition at line 268 of file Phase.cpp.
References Phase::m_kk.
Referenced by Phase::concentration(), Phase::massFraction(), Phase::molecularWeight(), Phase::moleFraction(), Phase::nAtoms(), and Phase::speciesName().
void checkSpeciesArraySize (size_t kk) const inherited
Check that an array size is at least nSpecies() Throws an exception if kk is less than nSpecies().
Used before calls which take an array pointer.
Definition at line 275 of file Phase.cpp.
References Phase::m_kk.
void saveState (vector_fp & state) const inherited
Save the current internal state of the phase Write to vector 'state' the current internal state.
Parameters
state output vector. Will be resized to nSpecies() + 2.
Definition at line 288 of file Phase.cpp.
References Phase::nSpecies().
Referenced by ChemEquil::equilibrate(), ChemEquil::estimateEP_Brinkley(), TransportFactory::newTransport(), ReactorBase::setThermoMgr(), FlowReactor::updateState(), ConstPressureReactor::updateState(), and Reactor::updateState().
void saveState (size_t lenstate, doublereal * state) const inherited
Write to array 'state' the current internal state.
Parameters
lenstate length of the state array. Must be >= nSpecies()+2
state output vector. Must be of length nSpecies() + 2 or greater.
Definition at line 293 of file Phase.cpp.
References Phase::density(), Phase::getMassFractions(), and Phase::temperature().
void restoreState (const vector_fp & state) inherited
Restore a state saved on a previous call to saveState.
Parameters
state State vector containing the previously saved state.
Definition at line 300 of file Phase.cpp.
Referenced by ChemEquil::equilibrate(), ChemEquil::estimateEP_Brinkley(), MultiTransport::getMassFluxes(), FlowReactor::initialize(), ConstPressureReactor::initialize(), Reactor::initialize(), and TransportFactory::newTransport().
void restoreState (size_t lenstate, const doublereal * state) inherited
Restore the state of the phase from a previously saved state vector.
Parameters
lenstate Length of the state vector
state Vector of state conditions.
Definition at line 305 of file Phase.cpp.
References Phase::nSpecies(), Phase::setDensity(), Phase::setMassFractions_NoNorm(), and Phase::setTemperature().
void setMoleFractionsByName (compositionMap & xMap) inherited
Set the species mole fractions by name.
@param xMap map from species names to mole fraction values.
Species not listed by name in xMap are set to zero.
Definition at line 362 of file Phase.cpp.
References Phase::nSpecies(), Phase::setMoleFractions(), and Phase::speciesName().
Referenced by Inlet1D::setMoleFractions(), OutletRes1D::setMoleFractions(), Phase::setMoleFractionsByName(), ThermoPhase::setState_TPX(), Phase::setState_TRX(), MixtureFugacityTP::setStateFromXML(), and ThermoPhase::setStateFromXML().
void setMoleFractionsByName (const std::string & x) inherited
Set the mole fractions of a group of species by name.
Species which are not listed by name in the composition map are set to zero.
Parameters
x string x in the form of a composition map
Definition at line 376 of file Phase.cpp.
References Phase::nSpecies(), Cantera::parseCompString(), Phase::setMoleFractionsByName(), and Phase::speciesName().
void setMassFractionsByName (compositionMap & yMap) inherited
Set the species mass fractions by name.
@param yMap map from species names to mass fraction values.
Species not listed by name in yMap are set to zero.
Definition at line 416 of file Phase.cpp.
References Phase::nSpecies(), Phase::setMassFractions(), and Phase::speciesName().
Referenced by Phase::setMassFractionsByName(), ThermoPhase::setState_TPY(), Phase::setState_TRY(), MixtureFugacityTP::setStateFromXML(), and ThermoPhase::setStateFromXML().
void setMassFractionsByName (const std::string & x) inherited
Set the species mass fractions by name.
Species not listed by name in x are set to zero.
Parameters
x String containing a composition map
Definition at line 430 of file Phase.cpp.
References Phase::nSpecies(), Cantera::parseCompString(), Phase::setMassFractionsByName(), and Phase::speciesName().
void setState_TRX (doublereal t, doublereal dens, const doublereal * x) inherited
Set the internally stored temperature (K), density, and mole fractions.
Parameters
t Temperature in kelvin
dens Density (kg/m^3)
x vector of species mole fractions, length m_kk
Definition at line 441 of file Phase.cpp.
References Phase::setDensity(), Phase::setMoleFractions(), and Phase::setTemperature().
void setState_TRX (doublereal t, doublereal dens, compositionMap & x) inherited
Set the internally stored temperature (K), density, and mole fractions.
Parameters
t Temperature in kelvin
dens Density (kg/m^3)
x Composition Map containing the mole fractions. Species not included in the map are assumed to have a zero mole fraction.
Definition at line 455 of file Phase.cpp.
References Phase::setDensity(), Phase::setMoleFractionsByName(), and Phase::setTemperature().
void setState_TRY (doublereal t, doublereal dens, const doublereal * y) inherited
Set the internally stored temperature (K), density, and mass fractions.
Parameters
t Temperature in kelvin
dens Density (kg/m^3)
y vector of species mass fractions, length m_kk
Definition at line 462 of file Phase.cpp.
References Phase::setDensity(), Phase::setMassFractions(), and Phase::setTemperature().
void setState_TRY (doublereal t, doublereal dens, compositionMap & y) inherited
Set the internally stored temperature (K), density, and mass fractions.
Parameters
t Temperature in kelvin
dens Density (kg/m^3)
y Composition Map containing the mass fractions. Species not included in the map are assumed to have a zero mass fraction.
Definition at line 469 of file Phase.cpp.
References Phase::setDensity(), Phase::setMassFractionsByName(), and Phase::setTemperature().
void setState_TNX (doublereal t, doublereal n, const doublereal * x) inherited
Set the internally stored temperature (K), molar density (kmol/m^3), and mole fractions.
Parameters
t Temperature in kelvin
n molar density (kmol/m^3)
x vector of species mole fractions, length m_kk
Definition at line 448 of file Phase.cpp.
References Phase::setMolarDensity(), Phase::setMoleFractions(), and Phase::setTemperature().
void setState_TR (doublereal t, doublereal rho) inherited
Set the internally stored temperature (K) and density (kg/m^3)
Parameters
t Temperature in kelvin
rho Density (kg/m^3)
Definition at line 476 of file Phase.cpp.
References Phase::setDensity(), and Phase::setTemperature().
Referenced by PureFluidPhase::setState_HP(), PureFluidPhase::setState_SP(), PureFluidPhase::setState_SV(), PDSS_IonsFromNeutral::setState_TR(), and PureFluidPhase::setState_UV().
void setState_TX (doublereal t, doublereal * x) inherited
Set the internally stored temperature (K) and mole fractions.
Parameters
t Temperature in kelvin
x vector of species mole fractions, length m_kk
Definition at line 482 of file Phase.cpp.
References Phase::setMoleFractions(), and Phase::setTemperature().
void setState_TY (doublereal t, doublereal * y) inherited
Set the internally stored temperature (K) and mass fractions.
Parameters
t Temperature in kelvin
y vector of species mass fractions, length m_kk
Definition at line 488 of file Phase.cpp.
References Phase::setMassFractions(), and Phase::setTemperature().
void setState_RX (doublereal rho, doublereal * x) inherited
Set the density (kg/m^3) and mole fractions.
Parameters
rho Density (kg/m^3)
x vector of species mole fractions, length m_kk
Definition at line 494 of file Phase.cpp.
References Phase::setDensity(), and Phase::setMoleFractions().
void setState_RY (doublereal rho, doublereal * y) inherited
Set the density (kg/m^3) and mass fractions.
Parameters
rho Density (kg/m^3)
y vector of species mass fractions, length m_kk
Definition at line 500 of file Phase.cpp.
References Phase::setDensity(), and Phase::setMassFractions().
doublereal molecularWeight (size_t k) const inherited
Molecular weight of species k.
Parameters
k index of species k
Returns
Returns the molecular weight of species k.
Definition at line 506 of file Phase.cpp.
References Phase::checkSpeciesIndex(), and Phase::m_molwts.
Referenced by VPSSMgr_Water_ConstVol::_updateRefStateThermo(), VPSSMgr_Water_HKFT::_updateRefStateThermo(), VPSSMgr_Water_ConstVol::_updateStandardStateThermo(), VPSSMgr_Water_HKFT::_updateStandardStateThermo(), SingleSpeciesTP::cv_mole(), SingleSpeciesTP::getPartialMolarVolumes(), SingleSpeciesTP::getStandardVolumes(), VPSSMgr_Water_ConstVol::getStandardVolumes_ref(), PDSS::initThermo(), VPSSMgr_Water_ConstVol::initThermoXML(), VPSSMgr_Water_HKFT::initThermoXML(), PDSS_ConstVol::initThermoXML(), MineralEQ3::initThermoXML(), PDSS_SSVol::initThermoXML(), Phase::molarMass(), MolalityVPSSTP::setSolvent(), HMWSoln::speciesMolarVolume(), and LiquidTransport::stefan_maxwell_solve().
doublereal molarMass (size_t k) const inline inherited
Return the Molar mass of species k Alternate name for molecular weight.
@param k  index for species
@return   Return the molar mass of species k kg/kmol.
Deprecated:
use molecularWeight instead
Definition at line 388 of file Phase.h.
References Phase::molecularWeight().
void getMolecularWeights (vector_fp & weights) const inherited
Copy the vector of molecular weights into vector weights.
Parameters
weights Output vector of molecular weights (kg/kmol)
Definition at line 512 of file Phase.cpp.
References Phase::molecularWeights().
void getMolecularWeights (int iwt, doublereal * weights) const inherited
Copy the vector of molecular weights into array weights.
@param iwt      Unused.
@param weights  Output array of molecular weights (kg/kmol)
Deprecated:
Definition at line 521 of file Phase.cpp.
References Phase::molecularWeights().
void getMolecularWeights (doublereal * weights) const inherited
Copy the vector of molecular weights into array weights.
Parameters
weights Output array of molecular weights (kg/kmol)
Definition at line 527 of file Phase.cpp.
References Phase::molecularWeights().
const vector_fp & molecularWeights () const inherited
Return a const reference to the internal vector of molecular weights.
units = kg / kmol
Definition at line 533 of file Phase.cpp.
References Phase::m_molwts.
Referenced by ReactingSurf1D::eval(), Phase::freezeSpecies(), Phase::getMolecularWeights(), MixTransport::getSpeciesFluxes(), AqueousTransport::getSpeciesFluxesExt(), SimpleTransport::getSpeciesFluxesExt(), Cantera::getStick(), GasTransport::initGas(), DustyGasTransport::initialize(), LiquidTransport::initLiquid(), SimpleTransport::initLiquid(), AqueousTransport::initLiquid(), TransportFactory::setupLiquidTransport(), TransportFactory::setupMM(), AqueousTransport::stefan_maxwell_solve(), LiquidTransport::stefan_maxwell_solve(), and StFlow::StFlow().
doublereal size (size_t k) const inline inherited
This routine returns the size of species k.
Parameters
k index of the species
Returns
The size of the species. Units are meters.
Definition at line 413 of file Phase.h.
References Phase::m_speciesSize.
Referenced by MolarityIonicVPSSTP::constructPhaseXML(), RedlichKisterVPSSTP::constructPhaseXML(), MargulesVPSSTP::constructPhaseXML(), MixedSolventElectrolyte::constructPhaseXML(), PhaseCombo_Interaction::constructPhaseXML(), IonsFromNeutralVPSSTP::constructPhaseXML(), IdealMolalSoln::constructPhaseXML(), IdealSolidSolnPhase::constructPhaseXML(), DebyeHuckel::constructPhaseXML(), ReactingSurf1D::eval(), SurfPhase::getCoverages(), SurfPhase::initThermo(), IdealMolalSoln::initThermoXML(), LatticeSolidPhase::installSlavePhases(), SurfPhase::setCoverages(), SurfPhase::setCoveragesNoNorm(), and SurfPhase::standardConcentration().
void getMoleFractionsByName (compositionMap & x) const inherited
Get the mole fractions by name.
Parameters
[out] x composition map containing the species mole fractions.
Definition at line 538 of file Phase.cpp.
References Phase::moleFraction(), Phase::nSpecies(), and Phase::speciesName().
doublereal moleFraction (size_t k) const inherited
Return the mole fraction of a single species.
Parameters
k species index
Returns
Mole fraction of the species
Definition at line 552 of file Phase.cpp.
References Phase::checkSpeciesIndex(), Phase::m_mmw, and Phase::m_ym.
Referenced by Phase::chargeDensity(), SolidTransport::electricalConductivity(), ChemEquil::equilibrate(), IdealMolalSoln::getActivities(), DebyeHuckel::getActivities(), HMWSoln::getActivities(), MolalityVPSSTP::getActivityCoefficients(), IdealSolnGasVPSS::getActivityConcentrations(), RedlichKwongMFTP::getActivityConcentrations(), ConstDensityThermo::getChemPotentials(), IdealSolnGasVPSS::getChemPotentials(), RedlichKwongMFTP::getChemPotentials(), IdealSolidSolnPhase::getChemPotentials(), IdealMolalSoln::getChemPotentials(), IdealGasPhase::getChemPotentials(), LatticePhase::getChemPotentials(), DebyeHuckel::getChemPotentials(), HMWSoln::getChemPotentials(), IdealSolidSolnPhase::getChemPotentials_RT(), IdealMolalSoln::getMolalityActivityCoefficients(), Phase::getMoleFractionsByName(), IdealSolnGasVPSS::getPartialMolarEntropies(), RedlichKwongMFTP::getPartialMolarEntropies(), IdealGasPhase::getPartialMolarEntropies(), IdealMolalSoln::getPartialMolarEntropies(), IdealSolidSolnPhase::getPartialMolarEntropies(), LatticePhase::getPartialMolarEntropies(), DebyeHuckel::getPartialMolarEntropies(), HMWSoln::getPartialMolarEntropies(), Phase::moleFraction(), DebyeHuckel::s_update_d2lnMolalityActCoeff_dT2(), DebyeHuckel::s_update_dlnMolalityActCoeff_dP(), DebyeHuckel::s_update_dlnMolalityActCoeff_dT(), DebyeHuckel::s_update_lnMolalityActCoeff(), HMWSoln::s_update_lnMolalityActCoeff(), IdealMolalSoln::s_updateIMS_lnMolalityActCoeff(), HMWSoln::s_updateIMS_lnMolalityActCoeff(), HMWSoln::s_updatePitzer_lnMolalityActCoeff(), and ChemEquil::setInitialMoles().
doublereal moleFraction (std::string name) const inherited
Return the mole fraction of a single species.
Parameters
name String name of the species
Returns
Mole fraction of the species
Definition at line 558 of file Phase.cpp.
References Phase::moleFraction(), Cantera::npos, and Phase::speciesIndex().
doublereal massFraction (size_t k) const inherited
Return the mass fraction of a single species.
Parameters
k species index
Returns
Mass fraction of the species
Definition at line 573 of file Phase.cpp.
References Phase::checkSpeciesIndex(), and Phase::m_y.
doublereal massFraction (std::string name) const inherited
Return the mass fraction of a single species.
Parameters
name String name of the species
Returns
Mass Fraction of the species
Definition at line 579 of file Phase.cpp.
References Phase::massFractions(), Cantera::npos, and Phase::speciesIndex().
void getMoleFractions (doublereal *const x) const inherited
Get the species mole fraction vector.
Parameters
x On return, x contains the mole fractions. Must have a length greater than or equal to the number of species.
Definition at line 547 of file Phase.cpp.
References Phase::m_mmw, Phase::m_ym, and Cantera::scale().
Referenced by IdealMolalSoln::calcDensity(), DebyeHuckel::calcDensity(), HMWSoln::calcDensity(), IonsFromNeutralVPSSTP::calcIonMoleFractions(), MolalityVPSSTP::calcMolalities(), HMWSoln::calcMolalitiesCropped(), IdealMolalSoln::enthalpy_mole(), HMWSoln::enthalpy_mole(), ChemEquil::estimateElementPotentials(), ChemEquil::estimateEP_Brinkley(), GibbsExcessVPSSTP::getActivities(), LatticePhase::getActivityConcentrations(), MultiTransport::getMassFluxes(), LTI_Pairwise_Interaction::getMatrixTransProp(), LTI_StefanMaxwell_PPN::getMatrixTransProp(), LTI_MoleFracs::getMixTransProp(), LTI_Log_MoleFracs::getMixTransProp(), LTI_Pairwise_Interaction::getMixTransProp(), LTI_StefanMaxwell_PPN::getMixTransProp(), LTI_MoleFracs_ExpT::getMixTransProp(), LatticeSolidPhase::getMoleFractions(), DustyGasTransport::initialize(), GibbsExcessVPSSTP::initThermo(), HMWSoln::printCoeffs(), HMWSoln::relative_molal_enthalpy(), PseudoBinaryVPSSTP::report(), MolarityIonicVPSSTP::report(), PureFluidPhase::report(), MolalityVPSSTP::report(), ThermoPhase::report(), PureFluidPhase::reportCSV(), MolalityVPSSTP::reportCSV(), ThermoPhase::reportCSV(), MixtureFugacityTP::setConcentrations(), GibbsExcessVPSSTP::setConcentrations(), MixtureFugacityTP::setMassFractions(), GibbsExcessVPSSTP::setMassFractions(), MixtureFugacityTP::setMassFractions_NoNorm(), GibbsExcessVPSSTP::setMassFractions_NoNorm(), MolalityVPSSTP::setMolalitiesByName(), MixtureFugacityTP::setMoleFractions(), GibbsExcessVPSSTP::setMoleFractions(), MixtureFugacityTP::setMoleFractions_NoNorm(), GibbsExcessVPSSTP::setMoleFractions_NoNorm(), MultiPhase::setMoles(), vcs_VolPhase::setPtrThermoPhase(), ThermoPhase::setReferenceComposition(), MixtureFugacityTP::setState_TP(), MixtureFugacityTP::setState_TR(), AqueousTransport::stefan_maxwell_solve(), ChemEquil::update(), MixTransport::update_C(), MultiTransport::update_C(), AqueousTransport::update_C(), SimpleTransport::update_C(), LiquidTransport::update_C(), solveSP::updateMFKinSpecies(), DustyGasTransport::updateTransport_C(), and MultiPhase::uploadMoleFractionsFromPhases().
void setMoleFractions (const doublereal *const x) virtual inherited
Set the mole fractions to the specified values There is no restriction on the sum of the mole fraction vector.
Internally, the Phase object will normalize this vector before storing its contents.
Parameters
x Array of unnormalized mole fraction values (input). Must have a length greater than or equal to the number of species, m_kk.
Reimplemented in IonsFromNeutralVPSSTP, GibbsExcessVPSSTP, LatticePhase, MixtureFugacityTP, IdealSolidSolnPhase, LatticeSolidPhase, and RedlichKwongMFTP.
Definition at line 317 of file Phase.cpp.
References Phase::m_kk, Phase::m_mmw, Phase::m_molwts, Phase::m_y, Phase::m_ym, ckr::max(), and Phase::stateMFChangeCalc().
Referenced by ChemEquil::calcEmoles(), ChemEquil::equilibrate(), ChemEquil::estimateElementPotentials(), ChemEquil::estimateEP_Brinkley(), PureFluidPhase::initThermo(), SingleSpeciesTP::initThermo(), WaterSSTP::initThermoXML(), IonsFromNeutralVPSSTP::setConcentrations(), IonsFromNeutralVPSSTP::setMassFractions(), IonsFromNeutralVPSSTP::setMassFractions_NoNorm(), MolalityVPSSTP::setMolalities(), MolalityVPSSTP::setMolalitiesByName(), Inlet1D::setMoleFractions(), OutletRes1D::setMoleFractions(), LatticeSolidPhase::setMoleFractions(), IdealSolidSolnPhase::setMoleFractions(), MixtureFugacityTP::setMoleFractions(), LatticePhase::setMoleFractions(), GibbsExcessVPSSTP::setMoleFractions(), IonsFromNeutralVPSSTP::setMoleFractions(), IdealSolidSolnPhase::setMoleFractions_NoNorm(), LatticePhase::setMoleFractions_NoNorm(), Phase::setMoleFractionsByName(), ThermoPhase::setState_PX(), Phase::setState_RX(), Phase::setState_TNX(), ThermoPhase::setState_TPX(), Phase::setState_TRX(), and Phase::setState_TX().
void setMoleFractions_NoNorm (const doublereal *const x) virtual inherited
Set the mole fractions to the specified values without normalizing.
This is useful when the normalization condition is being handled by some other means, for example by a constraint equation as part of a larger set of equations.
Parameters
x Input vector of mole fractions. Length is m_kk.
Reimplemented in IonsFromNeutralVPSSTP, GibbsExcessVPSSTP, LatticePhase, MixtureFugacityTP, IdealSolidSolnPhase, and RedlichKwongMFTP.
Definition at line 350 of file Phase.cpp.
References Cantera::dot(), Phase::m_kk, Phase::m_mmw, Phase::m_molwts, Phase::m_y, Phase::m_ym, and Phase::stateMFChangeCalc().
Referenced by MixtureFugacityTP::setMoleFractions_NoNorm(), GibbsExcessVPSSTP::setMoleFractions_NoNorm(), and IonsFromNeutralVPSSTP::setMoleFractions_NoNorm().
void getMassFractions (doublereal *const y) const inherited
Get the species mass fractions.
Parameters
[out] y Array of mass fractions, length nSpecies()
Definition at line 589 of file Phase.cpp.
References Phase::m_y.
Referenced by LTI_MassFracs::getMixTransProp(), Cantera::importSolution(), PureFluidPhase::report(), ThermoPhase::report(), PureFluidPhase::reportCSV(), ThermoPhase::reportCSV(), Phase::saveState(), Inlet1D::setMoleFractions(), OutletRes1D::setMoleFractions(), and LiquidTransport::update_C().
const doublereal* massFractions () const inline inherited
Return a const pointer to the mass fraction array.
Definition at line 469 of file Phase.h.
References Phase::m_y.
Referenced by MultiTransport::getMassFluxes(), MultiTransport::getSpeciesFluxes(), MixTransport::getSpeciesFluxes(), AqueousTransport::getSpeciesFluxesExt(), SimpleTransport::getSpeciesFluxesExt(), SimpleTransport::getSpeciesVdiff(), SimpleTransport::getSpeciesVdiffES(), and Phase::massFraction().
void setMassFractions (const doublereal *const y) virtual inherited
Set the mass fractions to the specified values and normalize them.
@param[in] y Array of unnormalized mass fraction values. Length
must be greater than or equal to the number of species. The Ptate object will normalize this vector before storing its contents.
Reimplemented in IonsFromNeutralVPSSTP, LatticePhase, GibbsExcessVPSSTP, MixtureFugacityTP, LatticeSolidPhase, IdealSolidSolnPhase, and RedlichKwongMFTP.
Definition at line 387 of file Phase.cpp.
References Phase::m_kk, Phase::m_mmw, Phase::m_rmolwts, Phase::m_y, Phase::m_ym, ckr::max(), Cantera::scale(), and Phase::stateMFChangeCalc().
Referenced by Cantera::importSolution(), IdealSolidSolnPhase::setMassFractions(), MixtureFugacityTP::setMassFractions(), GibbsExcessVPSSTP::setMassFractions(), LatticePhase::setMassFractions(), Phase::setMassFractionsByName(), ThermoPhase::setState_PY(), Phase::setState_RY(), ThermoPhase::setState_TPY(), Phase::setState_TRY(), Phase::setState_TY(), FlowReactor::updateState(), ConstPressureReactor::updateState(), and Reactor::updateState().
void setMassFractions_NoNorm (const doublereal *const y) virtual inherited
Set the mass fractions to the specified values without normalizing.
This is useful when the normalization condition is being handled by some other means, for example by a constraint equation as part of a larger set of equations.
Parameters
y Input vector of mass fractions. Length is m_kk.
Reimplemented in IonsFromNeutralVPSSTP, LatticePhase, GibbsExcessVPSSTP, MixtureFugacityTP, LatticeSolidPhase, IdealSolidSolnPhase, and RedlichKwongMFTP.
Definition at line 403 of file Phase.cpp.
References Phase::m_kk, Phase::m_mmw, Phase::m_rmolwts, Phase::m_y, Phase::m_ym, and Phase::stateMFChangeCalc().
Referenced by Phase::restoreState(), StFlow::setGas(), StFlow::setGasAtMidpoint(), IdealSolidSolnPhase::setMassFractions_NoNorm(), MixtureFugacityTP::setMassFractions_NoNorm(), GibbsExcessVPSSTP::setMassFractions_NoNorm(), and LatticePhase::setMassFractions_NoNorm().
void getConcentrations (doublereal *const c) const inherited
Get the species concentrations (kmol/m^3).
@param[out] c Array of species concentrations Length must be
greater than or equal to the number of species.
Definition at line 600 of file Phase.cpp.
References Phase::m_dens, Phase::m_ym, and Cantera::scale().
Referenced by ConstDensityThermo::getActivityConcentrations(), IdealSolnGasVPSS::getActivityConcentrations(), SurfPhase::getActivityConcentrations(), IdealGasPhase::getActivityConcentrations(), SurfPhase::getCoverages(), solveSP::solveSurfProb(), SimpleTransport::update_C(), and LiquidTransport::update_C().
doublereal concentration (const size_t k) const inherited
Concentration of species k.
If k is outside the valid range, an exception will be thrown.
Parameters
k Index of species
Definition at line 594 of file Phase.cpp.
References Phase::checkSpeciesIndex(), Phase::m_dens, Phase::m_rmolwts, and Phase::m_y.
void setConcentrations (const doublereal *const conc) virtual inherited
Set the concentrations to the specified values within the phase.
We set the concentrations here and therefore we set the overall density of the phase. We hold the temperature constant during this operation. Therefore, we have possibly changed the pressure of the phase by calling this routine.
Parameters
[in] conc Array of concentrations in dimensional units. For bulk phases c[k] is the concentration of the kth species in kmol/m3. For surface phases, c[k] is the concentration in kmol/m2. The length of the vector is the numberof species in the phase.
Reimplemented in IonsFromNeutralVPSSTP, GibbsExcessVPSSTP, LatticePhase, MixtureFugacityTP, LatticeSolidPhase, IdealSolidSolnPhase, and RedlichKwongMFTP.
Definition at line 605 of file Phase.cpp.
References Phase::m_kk, Phase::m_mmw, Phase::m_molwts, Phase::m_y, Phase::m_ym, ckr::max(), Phase::setDensity(), and Phase::stateMFChangeCalc().
Referenced by IdealSolidSolnPhase::setConcentrations(), MixtureFugacityTP::setConcentrations(), LatticePhase::setConcentrations(), GibbsExcessVPSSTP::setConcentrations(), ImplicitSurfChem::setConcSpecies(), SurfPhase::setCoverages(), and SurfPhase::setCoveragesNoNorm().
const doublereal * moleFractdivMMW () const inherited
Returns a const pointer to the start of the moleFraction/MW array.
This array is the array of mole fractions, each divided by the mean molecular weight.
Definition at line 568 of file Phase.cpp.
References Phase::m_ym.
Referenced by IdealSolnGasVPSS::calcDensity(), RedlichKwongMFTP::calcDensity(), IdealSolidSolnPhase::calcDensity(), and IdealSolidSolnPhase::getActivityConcentrations().
doublereal charge (size_t k) const inherited
Dimensionless electrical charge of a single molecule of species k The charge is normalized by the the magnitude of the electron charge.
Parameters
k species index
Definition at line 642 of file Phase.cpp.
References Phase::m_speciesCharge.
Referenced by InterfaceKinetics::applyButlerVolmerCorrection(), HMWSoln::calcMolalitiesCropped(), Phase::chargeDensity(), PDSS_HKFT::constructPDSSXML(), SolidTransport::electricalConductivity(), PureFluidPhase::getElectrochemPotentials(), PseudoBinaryVPSSTP::getElectrochemPotentials(), MolarityIonicVPSSTP::getElectrochemPotentials(), GibbsExcessVPSSTP::getElectrochemPotentials(), RedlichKisterVPSSTP::getElectrochemPotentials(), MargulesVPSSTP::getElectrochemPotentials(), ThermoPhase::getElectrochemPotentials(), MixedSolventElectrolyte::getElectrochemPotentials(), MolalityVPSSTP::getElectrochemPotentials(), PhaseCombo_Interaction::getElectrochemPotentials(), InterfaceKinetics::getEquilibriumConstants(), LiquidTransport::initLiquid(), SimpleTransport::initLiquid(), PDSS_HKFT::initThermo(), IonsFromNeutralVPSSTP::initThermoXML(), DebyeHuckel::initThermoXML(), LatticeSolidPhase::installSlavePhases(), HMWSoln::printCoeffs(), PhaseCombo_Interaction::readXMLBinarySpecies(), RedlichKisterVPSSTP::readXMLBinarySpecies(), MargulesVPSSTP::readXMLBinarySpecies(), MixedSolventElectrolyte::readXMLBinarySpecies(), HMWSoln::relative_molal_enthalpy(), HMWSoln::s_updatePitzer_d2lnMolalityActCoeff_dT2(), HMWSoln::s_updatePitzer_dlnMolalityActCoeff_dP(), HMWSoln::s_updatePitzer_dlnMolalityActCoeff_dT(), HMWSoln::s_updatePitzer_lnMolalityActCoeff(), MolalityVPSSTP::setMolalitiesByName(), vcs_VolPhase::transferElementsFM(), and InterfaceKinetics::updateKc().
doublereal chargeDensity () const inherited
Charge density [C/m^3].
Definition at line 647 of file Phase.cpp.
References Phase::charge(), Phase::moleFraction(), and Phase::nSpecies().
size_t nDim () const inline inherited
Returns the number of spatial dimensions (1, 2, or 3)
Definition at line 523 of file Phase.h.
References Phase::m_ndim.
Referenced by Kinetics::addPhase(), EdgeKinetics::finalize(), InterfaceKinetics::finalize(), IdealSolnGasVPSS::getUnitsStandardConc(), RedlichKwongMFTP::getUnitsStandardConc(), IdealMolalSoln::getUnitsStandardConc(), MolalityVPSSTP::getUnitsStandardConc(), IdealSolidSolnPhase::getUnitsStandardConc(), ThermoPhase::getUnitsStandardConc(), DebyeHuckel::getUnitsStandardConc(), and HMWSoln::getUnitsStandardConc().
void setNDim (size_t ndim) inline inherited
Set the number of spatial dimensions (1, 2, or 3).
The number of spatial dimensions is used for vector involving directions.
Parameters
ndim Input number of dimensions.
Definition at line 530 of file Phase.h.
References Phase::m_ndim.
Referenced by EdgePhase::EdgePhase(), FixedChemPotSSTP::FixedChemPotSSTP(), Cantera::importPhase(), EdgePhase::operator=(), and SurfPhase::SurfPhase().
doublereal temperature () const inline inherited
Temperature (K).
Returns
The temperature of the phase
Definition at line 539 of file Phase.h.
References Phase::m_temp.
Referenced by ThermoPhase::_RT(), InterfaceKinetics::_update_rates_T(), MixtureFugacityTP::_updateReferenceStateThermo(), VPStandardStateTP::_updateStandardStateThermo(), ConstDensityThermo::_updateThermo(), SurfPhase::_updateThermo(), LatticeSolidPhase::_updateThermo(), SingleSpeciesTP::_updateThermo(), IdealGasPhase::_updateThermo(), LatticePhase::_updateThermo(), IdealSolidSolnPhase::_updateThermo(), DebyeHuckel::A_Debye_TP(), HMWSoln::A_Debye_TP(), MultiPhase::addPhase(), HMWSoln::ADebye_J(), HMWSoln::ADebye_L(), HMWSoln::ADebye_V(), InterfaceKinetics::applyButlerVolmerCorrection(), InterfaceKinetics::applyExchangeCurrentDensityFormulation(), IdealSolnGasVPSS::calcDensity(), MixtureFugacityTP::calculatePsat(), RedlichKwongMFTP::cp_mole(), SingleSpeciesTP::cv_mole(), HMWSoln::cv_mole(), DebyeHuckel::d2A_DebyedT2_TP(), HMWSoln::d2A_DebyedT2_TP(), DebyeHuckel::dA_DebyedP_TP(), HMWSoln::dA_DebyedP_TP(), DebyeHuckel::dA_DebyedT_TP(), HMWSoln::dA_DebyedT_TP(), WaterSSTP::dthermalExpansionCoeffdT(), IdealSolnGasVPSS::enthalpy_mole(), ConstDensityThermo::enthalpy_mole(), IdealSolidSolnPhase::enthalpy_mole(), LatticePhase::enthalpy_mole(), IdealGasPhase::enthalpy_mole(), ChemEquil::equilibrate(), ChemEquil::estimateElementPotentials(), ChemEquil::estimateEP_Brinkley(), FixedChemPotSSTP::FixedChemPotSSTP(), RedlichKwongMFTP::getActivityCoefficients(), ConstDensityThermo::getChemPotentials(), SurfPhase::getChemPotentials(), MolarityIonicVPSSTP::getChemPotentials(), IdealSolnGasVPSS::getChemPotentials(), IonsFromNeutralVPSSTP::getChemPotentials(), RedlichKwongMFTP::getChemPotentials(), RedlichKisterVPSSTP::getChemPotentials(), MargulesVPSSTP::getChemPotentials(), MixedSolventElectrolyte::getChemPotentials(), PhaseCombo_Interaction::getChemPotentials(), IdealSolidSolnPhase::getChemPotentials(), IdealMolalSoln::getChemPotentials(), IdealGasPhase::getChemPotentials(), LatticePhase::getChemPotentials(), DebyeHuckel::getChemPotentials(), HMWSoln::getChemPotentials(), StoichSubstance::getChemPotentials_RT(), SingleSpeciesTP::getChemPotentials_RT(), IdealSolidSolnPhase::getChemPotentials_RT(), WaterSSTP::getCp_R_ref(), AqueousKinetics::getDeltaSSEnthalpy(), GasKinetics::getDeltaSSEnthalpy(), InterfaceKinetics::getDeltaSSEnthalpy(), PhaseCombo_Interaction::getdlnActCoeffds(), MargulesVPSSTP::getdlnActCoeffds(), MixedSolventElectrolyte::getdlnActCoeffds(), ThermoPhase::getElementPotentials(), WaterSSTP::getEnthalpy_RT(), StoichSubstance::getEnthalpy_RT(), StoichSubstanceSSTP::getEnthalpy_RT(), MineralEQ3::getEnthalpy_RT(), SurfPhase::getEnthalpy_RT(), IdealSolidSolnPhase::getEnthalpy_RT(), LatticePhase::getEnthalpy_RT(), WaterSSTP::getEnthalpy_RT_ref(), PureFluidPhase::getEnthalpy_RT_ref(), WaterSSTP::getEntropy_R_ref(), PureFluidPhase::getEntropy_R_ref(), AqueousKinetics::getEquilibriumConstants(), GasKinetics::getEquilibriumConstants(), InterfaceKinetics::getEquilibriumConstants(), StoichSubstance::getGibbs_ref(), PureFluidPhase::getGibbs_ref(), SingleSpeciesTP::getGibbs_ref(), LatticeSolidPhase::getGibbs_ref(), IdealSolidSolnPhase::getGibbs_ref(), LatticePhase::getGibbs_ref(), WaterSSTP::getGibbs_RT(), StoichSubstance::getGibbs_RT(), SurfPhase::getGibbs_RT(), WaterSSTP::getGibbs_RT_ref(), PureFluidPhase::getGibbs_RT_ref(), StoichSubstanceSSTP::getIntEnergy_RT(), MineralEQ3::getIntEnergy_RT(), IdealSolidSolnPhase::getIntEnergy_RT(), StoichSubstanceSSTP::getIntEnergy_RT_ref(), MineralEQ3::getIntEnergy_RT_ref(), MetalSHEelectrons::getIntEnergy_RT_ref(), IdealSolidSolnPhase::getIntEnergy_RT_ref(), LTI_Pairwise_Interaction::getMatrixTransProp(), LTI_StefanMaxwell_PPN::getMatrixTransProp(), SolidTransport::getMixDiffCoeffs(), LTI_MoleFracs::getMixTransProp(), LTI_MassFracs::getMixTransProp(), LTI_Log_MoleFracs::getMixTransProp(), LTI_MoleFracs_ExpT::getMixTransProp(), SolidTransport::getMobilities(), MolarityIonicVPSSTP::getPartialMolarCp(), RedlichKisterVPSSTP::getPartialMolarCp(), MargulesVPSSTP::getPartialMolarCp(), MixedSolventElectrolyte::getPartialMolarCp(), PhaseCombo_Interaction::getPartialMolarCp(), DebyeHuckel::getPartialMolarCp(), HMWSoln::getPartialMolarCp(), SurfPhase::getPartialMolarEnthalpies(), IdealSolnGasVPSS::getPartialMolarEnthalpies(), MolarityIonicVPSSTP::getPartialMolarEnthalpies(), SingleSpeciesTP::getPartialMolarEnthalpies(), IonsFromNeutralVPSSTP::getPartialMolarEnthalpies(), RedlichKwongMFTP::getPartialMolarEnthalpies(), RedlichKisterVPSSTP::getPartialMolarEnthalpies(), MargulesVPSSTP::getPartialMolarEnthalpies(), MixedSolventElectrolyte::getPartialMolarEnthalpies(), PhaseCombo_Interaction::getPartialMolarEnthalpies(), IdealGasPhase::getPartialMolarEnthalpies(), IdealSolidSolnPhase::getPartialMolarEnthalpies(), LatticePhase::getPartialMolarEnthalpies(), DebyeHuckel::getPartialMolarEnthalpies(), HMWSoln::getPartialMolarEnthalpies(), MolarityIonicVPSSTP::getPartialMolarEntropies(), IonsFromNeutralVPSSTP::getPartialMolarEntropies(), RedlichKwongMFTP::getPartialMolarEntropies(), RedlichKisterVPSSTP::getPartialMolarEntropies(), MargulesVPSSTP::getPartialMolarEntropies(), MixedSolventElectrolyte::getPartialMolarEntropies(), PhaseCombo_Interaction::getPartialMolarEntropies(), DebyeHuckel::getPartialMolarEntropies(), HMWSoln::getPartialMolarEntropies(), IdealSolnGasVPSS::getPartialMolarIntEnergies(), SingleSpeciesTP::getPartialMolarIntEnergies(), RedlichKwongMFTP::getPartialMolarIntEnergies(), IdealGasPhase::getPartialMolarIntEnergies(), RedlichKwongMFTP::getPartialMolarVolumes(), MargulesVPSSTP::getPartialMolarVolumes(), MixedSolventElectrolyte::getPartialMolarVolumes(), PhaseCombo_Interaction::getPartialMolarVolumes(), DebyeHuckel::getPartialMolarVolumes(), HMWSoln::getPartialMolarVolumes(), SingleSpeciesTP::getPureGibbs(), LatticePhase::getPureGibbs(), LTPspecies_Arrhenius::getSpeciesTransProp(), LTPspecies_Poly::getSpeciesTransProp(), LTPspecies_ExpT::getSpeciesTransProp(), WaterSSTP::getStandardChemPotentials(), StoichSubstanceSSTP::getStandardChemPotentials(), MineralEQ3::getStandardChemPotentials(), MetalSHEelectrons::getStandardChemPotentials(), IdealGasPhase::getStandardChemPotentials(), WaterSSTP::getStandardVolumes_ref(), IdealSolnGasVPSS::gibbs_mole(), ConstDensityThermo::gibbs_mole(), StoichSubstance::gibbs_mole(), RedlichKwongMFTP::gibbs_mole(), IdealSolidSolnPhase::gibbs_mole(), ThermoPhase::gibbs_mole(), LatticePhase::gibbs_mole(), IdealGasPhase::gibbs_mole(), RedlichKwongMFTP::hresid(), ConstDensityThermo::intEnergy_mole(), StoichSubstance::intEnergy_mole(), IdealSolidSolnPhase::intEnergy_mole(), LatticePhase::intEnergy_mole(), IdealGasPhase::intEnergy_mole(), IdealGasPhase::logStandardConc(), MixtureFugacityTP::phaseState(), RedlichKwongMFTP::pressure(), IdealGasPhase::pressure(), MixTransport::pressure_ig(), RedlichKwongMFTP::pressureDerivatives(), HMWSoln::relative_enthalpy(), PseudoBinaryVPSSTP::report(), MolarityIonicVPSSTP::report(), PureFluidPhase::report(), MolalityVPSSTP::report(), ThermoPhase::report(), PureFluidPhase::reportCSV(), MolalityVPSSTP::reportCSV(), ThermoPhase::reportCSV(), PhaseCombo_Interaction::s_update_dlnActCoeff_dlnN(), MargulesVPSSTP::s_update_dlnActCoeff_dlnN(), MixedSolventElectrolyte::s_update_dlnActCoeff_dlnN(), PhaseCombo_Interaction::s_update_dlnActCoeff_dlnN_diag(), MargulesVPSSTP::s_update_dlnActCoeff_dlnN_diag(), MixedSolventElectrolyte::s_update_dlnActCoeff_dlnN_diag(), PhaseCombo_Interaction::s_update_dlnActCoeff_dlnX_diag(), MargulesVPSSTP::s_update_dlnActCoeff_dlnX_diag(), MixedSolventElectrolyte::s_update_dlnActCoeff_dlnX_diag(), PhaseCombo_Interaction::s_update_dlnActCoeff_dT(), MargulesVPSSTP::s_update_dlnActCoeff_dT(), MixedSolventElectrolyte::s_update_dlnActCoeff_dT(), RedlichKisterVPSSTP::s_update_dlnActCoeff_dX_(), PhaseCombo_Interaction::s_update_lnActCoeff(), RedlichKisterVPSSTP::s_update_lnActCoeff(), MargulesVPSSTP::s_update_lnActCoeff(), MixedSolventElectrolyte::s_update_lnActCoeff(), HMWSoln::s_updatePitzer_CoeffWRTemp(), HMWSoln::s_updatePitzer_dlnMolalityActCoeff_dP(), HMWSoln::s_updatePitzer_lnMolalityActCoeff(), WaterSSTP::satPressure(), HMWSoln::satPressure(), Phase::saveState(), WaterSSTP::setDensity(), ThermoPhase::setElementPotentials(), ChemEquil::setInitialMoles(), PureFluidPhase::setPressure(), WaterSSTP::setPressure(), GibbsExcessVPSSTP::setPressure(), IdealMolalSoln::setPressure(), VPStandardStateTP::setPressure(), MixtureFugacityTP::setPressure(), IdealGasPhase::setPressure(), IonsFromNeutralVPSSTP::setPressure(), DebyeHuckel::setPressure(), HMWSoln::setPressure(), vcs_VolPhase::setPtrThermoPhase(), SingleSpeciesTP::setState_HP(), ThermoPhase::setState_HPorUV(), SingleSpeciesTP::setState_SP(), ThermoPhase::setState_SPorSV(), SingleSpeciesTP::setState_SV(), SingleSpeciesTP::setState_UV(), MixtureFugacityTP::setStateFromXML(), MixtureFugacityTP::setTemperature(), PureFluidPhase::setTPXState(), ImplicitSurfChem::solvePseudoSteadyStateProblem(), RedlichKwongMFTP::sresid(), IdealSolnGasVPSS::standardConcentration(), IdealGasPhase::standardConcentration(), AqueousTransport::stefan_maxwell_solve(), LiquidTransport::stefan_maxwell_solve(), SolidTransport::thermalConductivity(), MetalSHEelectrons::thermalExpansionCoeff(), IdealGasPhase::thermalExpansionCoeff(), ChemEquil::update(), MixTransport::update_T(), MultiTransport::update_T(), AqueousTransport::update_T(), SimpleTransport::update_T(), LiquidTransport::update_T(), RedlichKwongMFTP::updateAB(), AqueousKinetics::updateKc(), GasKinetics::updateKc(), InterfaceKinetics::updateKc(), VPStandardStateTP::updateStandardStateThermo(), Reactor::updateState(), MultiTransport::updateThermal_T(), DustyGasTransport::updateTransport_T(), and WaterSSTP::vaporFraction().
virtual doublereal density () const inline virtual inherited
Density (kg/m^3).
Returns
The density of the phase
Reimplemented in HMWSoln.
Definition at line 545 of file Phase.h.
References Phase::m_dens.
Referenced by MixtureFugacityTP::calculatePsat(), SingleSpeciesTP::cv_mole(), HMWSoln::density(), WaterSSTP::dthermalExpansionCoeffdT(), WaterSSTP::getCp_R_ref(), WaterSSTP::getEnthalpy_RT_ref(), WaterSSTP::getEntropy_R_ref(), WaterSSTP::getGibbs_RT_ref(), MultiTransport::getMassFluxes(), ConstDensityThermo::getParameters(), StoichSubstance::getParameters(), StoichSubstanceSSTP::getParameters(), MetalSHEelectrons::getParameters(), MineralEQ3::getParameters(), SingleSpeciesTP::getPartialMolarVolumes(), MultiTransport::getSpeciesFluxes(), SimpleTransport::getSpeciesVdiff(), SimpleTransport::getSpeciesVdiffES(), SingleSpeciesTP::getStandardVolumes(), WaterSSTP::getStandardVolumes_ref(), RedlichKwongMFTP::hresid(), Phase::molarDensity(), MixtureFugacityTP::phaseState(), RedlichKwongMFTP::pressure(), PseudoBinaryVPSSTP::report(), MolarityIonicVPSSTP::report(), PureFluidPhase::report(), MolalityVPSSTP::report(), ThermoPhase::report(), PureFluidPhase::reportCSV(), MolalityVPSSTP::reportCSV(), ThermoPhase::reportCSV(), WaterSSTP::satPressure(), Phase::saveState(), IdealMolalSoln::setDensity(), IdealSolidSolnPhase::setDensity(), Phase::setDensity(), DebyeHuckel::setDensity(), WaterSSTP::setPressure(), MixtureFugacityTP::setState_TP(), IonsFromNeutralVPSSTP::setState_TP(), MixtureFugacityTP::setStateFromXML(), MixtureFugacityTP::setTemperature(), WaterSSTP::setTemperature(), PureFluidPhase::setTPXState(), RedlichKwongMFTP::sresid(), ChemEquil::update(), SimpleTransport::update_C(), LiquidTransport::update_C(), ConstPressureReactor::updateState(), StFlow::updateThermo(), WaterSSTP::vaporFraction(), and MixtureFugacityTP::z().
doublereal molarDensity () const inherited
Molar density (kmol/m^3).
Returns
The molar density of the phase
Definition at line 627 of file Phase.cpp.
References Phase::density(), and Phase::meanMolecularWeight().
Referenced by solveSP::calc_t(), SolidTransport::electricalConductivity(), ConstDensityThermo::enthalpy_mole(), StoichSubstance::enthalpy_mole(), IdealSolidSolnPhase::enthalpy_mole(), LatticePhase::enthalpy_mole(), ConstDensityThermo::getChemPotentials(), StoichSubstanceSSTP::getEnthalpy_RT(), MineralEQ3::getEnthalpy_RT(), StoichSubstanceSSTP::getIntEnergy_RT(), MineralEQ3::getIntEnergy_RT(), StoichSubstanceSSTP::getIntEnergy_RT_ref(), MineralEQ3::getIntEnergy_RT_ref(), MetalSHEelectrons::getIntEnergy_RT_ref(), LatticePhase::getParameters(), PureFluidPhase::getPartialMolarVolumes(), StoichSubstance::getPartialMolarVolumes(), IdealGasPhase::getPartialMolarVolumes(), MixTransport::getSpeciesFluxes(), AqueousTransport::getSpeciesFluxesExt(), SimpleTransport::getSpeciesFluxesExt(), StoichSubstance::getStandardVolumes(), IdealGasPhase::getStandardVolumes(), IdealSolnGasVPSS::intEnergy_mole(), ConstDensityThermo::intEnergy_mole(), StoichSubstance::intEnergy_mole(), RedlichKwongMFTP::intEnergy_mole(), IonsFromNeutralVPSSTP::intEnergy_mole(), IdealSolidSolnPhase::intEnergy_mole(), LatticePhase::intEnergy_mole(), DebyeHuckel::intEnergy_mole(), HMWSoln::intEnergy_mole(), ConstDensityThermo::logStandardConc(), Phase::molarVolume(), IdealGasPhase::pressure(), MixTransport::pressure_ig(), IdealMolalSoln::setMolarDensity(), DebyeHuckel::setMolarDensity(), and ConstDensityThermo::standardConcentration().
doublereal molarVolume () const inherited
Molar volume (m^3/kmol).
Returns
The molar volume of the phase
Definition at line 637 of file Phase.cpp.
References Phase::molarDensity().
Referenced by RedlichKwongMFTP::cp_mole(), HMWSoln::cv_mole(), RedlichKwongMFTP::getActivityCoefficients(), RedlichKwongMFTP::getChemPotentials(), LTI_StefanMaxwell_PPN::getMatrixTransProp(), RedlichKwongMFTP::getPartialMolarEnthalpies(), RedlichKwongMFTP::getPartialMolarEntropies(), RedlichKwongMFTP::getPartialMolarVolumes(), ThermoPhase::intEnergy_mole(), RedlichKwongMFTP::pressureDerivatives(), MixtureFugacityTP::setState_TR(), and LiquidTransport::stefan_maxwell_solve().
virtual void setDensity (const doublereal density) inline virtual inherited
Set the internally stored density (kg/m^3) of the phase Note the density of a phase is an independent variable.
Parameters
[in] density density (kg/m^3).
Reimplemented in HMWSoln, DebyeHuckel, WaterSSTP, IdealSolidSolnPhase, and IdealMolalSoln.
Definition at line 560 of file Phase.h.
References Phase::density(), and Phase::m_dens.
Referenced by IdealSolnGasVPSS::calcDensity(), RedlichKwongMFTP::calcDensity(), GibbsExcessVPSSTP::calcDensity(), IdealMolalSoln::calcDensity(), IdealSolidSolnPhase::calcDensity(), LatticeSolidPhase::calcDensity(), DebyeHuckel::calcDensity(), HMWSoln::calcDensity(), StoichSubstanceSSTP::initThermoXML(), WaterSSTP::initThermoXML(), MetalSHEelectrons::initThermoXML(), MineralEQ3::initThermoXML(), electrodeElectron::initThermoXML(), Phase::restoreState(), Phase::setConcentrations(), WaterSSTP::setDensity(), ConstDensityThermo::setParameters(), StoichSubstance::setParameters(), StoichSubstanceSSTP::setParameters(), MetalSHEelectrons::setParameters(), MineralEQ3::setParameters(), electrodeElectron::setParameters(), SemiconductorPhase::setParametersFromXML(), MetalPhase::setParametersFromXML(), StoichSubstance::setParametersFromXML(), ConstDensityThermo::setParametersFromXML(), StoichSubstanceSSTP::setParametersFromXML(), MetalSHEelectrons::setParametersFromXML(), PureFluidPhase::setPressure(), IdealGasPhase::setPressure(), ThermoPhase::setState_HPorUV(), PureFluidPhase::setState_Psat(), Phase::setState_RX(), Phase::setState_RY(), ThermoPhase::setState_SPorSV(), SingleSpeciesTP::setState_SV(), MixtureFugacityTP::setState_TP(), IonsFromNeutralVPSSTP::setState_TP(), Phase::setState_TR(), MixtureFugacityTP::setState_TR(), Phase::setState_TRX(), Phase::setState_TRY(), PureFluidPhase::setState_Tsat(), SingleSpeciesTP::setState_UV(), ThermoPhase::setStateFromXML(), and Reactor::updateState().
void setMolarDensity (const doublereal molarDensity) virtual inherited
Set the internally stored molar density (kmol/m^3) of the phase.
Parameters
[in] molarDensity Input molar density (kmol/m^3).
Reimplemented in HMWSoln, DebyeHuckel, IdealSolidSolnPhase, and IdealMolalSoln.
Definition at line 632 of file Phase.cpp.
References Phase::m_dens, and Phase::meanMolecularWeight().
Referenced by LatticePhase::calcDensity(), LatticePhase::setParameters(), and Phase::setState_TNX().
virtual void setTemperature (const doublereal temp) inline virtual inherited
Set the internally stored temperature of the phase (K).
Parameters
temp Temperature in Kelvin
Reimplemented in HMWSoln, DebyeHuckel, IonsFromNeutralVPSSTP, WaterSSTP, MixtureFugacityTP, VPStandardStateTP, and RedlichKwongMFTP.
Definition at line 570 of file Phase.h.
References Phase::m_temp.
Referenced by ChemEquil::equilibrate(), ReactingSurf1D::eval(), TransportFactory::fitProperties(), WaterSSTP::initThermoXML(), Phase::restoreState(), StFlow::setGas(), StFlow::setGasAtMidpoint(), ThermoPhase::setState_HPorUV(), PureFluidPhase::setState_Psat(), ThermoPhase::setState_SPorSV(), SingleSpeciesTP::setState_SV(), Phase::setState_TNX(), VPStandardStateTP::setState_TP(), IdealMolalSoln::setState_TP(), MixtureFugacityTP::setState_TP(), GibbsExcessVPSSTP::setState_TP(), DebyeHuckel::setState_TP(), ThermoPhase::setState_TP(), HMWSoln::setState_TP(), SingleSpeciesTP::setState_TPX(), ThermoPhase::setState_TPX(), SingleSpeciesTP::setState_TPY(), ThermoPhase::setState_TPY(), Phase::setState_TR(), MixtureFugacityTP::setState_TR(), Phase::setState_TRX(), Phase::setState_TRY(), PureFluidPhase::setState_Tsat(), Phase::setState_TX(), Phase::setState_TY(), SingleSpeciesTP::setState_UV(), SurfPhase::setStateFromXML(), ThermoPhase::setStateFromXML(), RedlichKwongMFTP::setTemperature(), PDSS_IonsFromNeutral::setTemperature(), WaterSSTP::setTemperature(), ChemEquil::setToEquilState(), and Reactor::updateState().
doublereal mean_X (const doublereal *const Q) const inherited
Evaluate the mole-fraction-weighted mean of an array Q.
\[ \sum_k X_k Q_k. \]
Q should contain pure-species molar property values.
Parameters
[in] Q Array of length m_kk that is to be averaged.
Returns
mole-fraction-weighted mean of Q
Definition at line 658 of file Phase.cpp.
References Phase::m_mmw, and Phase::m_ym.
Referenced by IdealSolnGasVPSS::cp_mole(), ConstDensityThermo::cp_mole(), RedlichKwongMFTP::cp_mole(), IonsFromNeutralVPSSTP::cp_mole(), IdealSolidSolnPhase::cp_mole(), IdealMolalSoln::cp_mole(), LatticePhase::cp_mole(), IdealGasPhase::cp_mole(), DebyeHuckel::cp_mole(), HMWSoln::cp_mole(), IonsFromNeutralVPSSTP::cv_mole(), IdealSolnGasVPSS::enthalpy_mole(), ConstDensityThermo::enthalpy_mole(), RedlichKwongMFTP::enthalpy_mole(), IdealSolidSolnPhase::enthalpy_mole(), IonsFromNeutralVPSSTP::enthalpy_mole(), IdealMolalSoln::enthalpy_mole(), SurfPhase::enthalpy_mole(), LatticePhase::enthalpy_mole(), IdealGasPhase::enthalpy_mole(), DebyeHuckel::enthalpy_mole(), HMWSoln::enthalpy_mole(), IdealSolnGasVPSS::entropy_mole(), ConstDensityThermo::entropy_mole(), RedlichKwongMFTP::entropy_mole(), IonsFromNeutralVPSSTP::entropy_mole(), IdealSolidSolnPhase::entropy_mole(), IdealMolalSoln::entropy_mole(), LatticePhase::entropy_mole(), IdealGasPhase::entropy_mole(), DebyeHuckel::entropy_mole(), HMWSoln::entropy_mole(), IonsFromNeutralVPSSTP::gibbs_mole(), IdealSolidSolnPhase::gibbs_mole(), IdealMolalSoln::gibbs_mole(), DebyeHuckel::gibbs_mole(), HMWSoln::gibbs_mole(), ConstDensityThermo::intEnergy_mole(), IdealSolidSolnPhase::intEnergy_mole(), IdealMolalSoln::intEnergy_mole(), LatticePhase::intEnergy_mole(), IdealGasPhase::intEnergy_mole(), and HMWSoln::relative_enthalpy().
doublereal mean_Y (const doublereal *const Q) const inherited
Evaluate the mass-fraction-weighted mean of an array Q.
\[ \sum_k Y_k Q_k \]
Parameters
[in] Q Array of species property values in mass units.
Returns
The mass-fraction-weighted mean of Q.
Definition at line 663 of file Phase.cpp.
References Cantera::dot(), and Phase::m_y.
doublereal meanMolecularWeight () const inline inherited
The mean molecular weight. Units: (kg/kmol)
Definition at line 592 of file Phase.h.
References Phase::m_mmw.
Referenced by IdealSolnGasVPSS::calcDensity(), GibbsExcessVPSSTP::calcDensity(), IdealMolalSoln::calcDensity(), LatticePhase::calcDensity(), DebyeHuckel::calcDensity(), HMWSoln::calcDensity(), MixtureFugacityTP::calculatePsat(), ThermoPhase::cp_mass(), RedlichKwongMFTP::critDensity(), ThermoPhase::cv_mass(), RedlichKwongMFTP::densityCalc(), MixtureFugacityTP::densityCalc(), RedlichKwongMFTP::densSpinodalGas(), RedlichKwongMFTP::densSpinodalLiquid(), ThermoPhase::enthalpy_mass(), ThermoPhase::entropy_mass(), IdealSolidSolnPhase::getActivityConcentrations(), GasTransport::getMixDiffCoeffs(), AqueousTransport::getMixDiffCoeffs(), GasTransport::getMixDiffCoeffsMass(), MultiTransport::getMultiDiffCoeffs(), WaterSSTP::getStandardVolumes_ref(), ThermoPhase::gibbs_mass(), RedlichKwongMFTP::hresid(), ThermoPhase::intEnergy_mass(), Phase::molarDensity(), MixtureFugacityTP::phaseState(), RedlichKwongMFTP::pressure(), PseudoBinaryVPSSTP::report(), MolarityIonicVPSSTP::report(), PureFluidPhase::report(), MolalityVPSSTP::report(), ThermoPhase::report(), PureFluidPhase::reportCSV(), MolalityVPSSTP::reportCSV(), ThermoPhase::reportCSV(), Phase::setMolarDensity(), IdealGasPhase::setPressure(), RedlichKwongMFTP::sresid(), SimpleTransport::update_C(), LiquidTransport::update_C(), StFlow::updateThermo(), StFlow::updateTransport(), and MixtureFugacityTP::z().
doublereal sum_xlogx () const inherited
Evaluate \(\sum_k X_k \log X_k \).
Returns
The indicated sum. Dimensionless.
Definition at line 668 of file Phase.cpp.
References Phase::m_mmw, Phase::m_ym, and Cantera::sum_xlogx().
Referenced by IdealSolnGasVPSS::entropy_mole(), ConstDensityThermo::entropy_mole(), RedlichKwongMFTP::entropy_mole(), IdealSolidSolnPhase::entropy_mole(), LatticePhase::entropy_mole(), IdealGasPhase::entropy_mole(), and IdealSolidSolnPhase::gibbs_mole().
doublereal sum_xlogQ (doublereal *const Q) const inherited
Evaluate \(\sum_k X_k \log Q_k \).
Parameters
Q Vector of length m_kk to take the log average of
Returns
The indicated sum.
Definition at line 673 of file Phase.cpp.
References Phase::m_mmw, Phase::m_ym, and Cantera::sum_xlogQ().
void addElement (const std::string & symbol, doublereal weight = -12345.0) inherited
Add an element.
Parameters
symbol Atomic symbol std::string.
weight Atomic mass in amu.
Definition at line 678 of file Phase.cpp.
References CT_ELEM_TYPE_ABSPOS, CT_ELEM_TYPE_ELECTRONCHARGE, Cantera::LookupWtElements(), Phase::m_atomicWeights, Phase::m_elem_type, Phase::m_elementNames, Phase::m_elementsFrozen, and Phase::m_mm.
Referenced by Phase::addElement().
void addElement (const XML_Node & e) inherited
Add an element from an XML specification.
Parameters
e Reference to the XML_Node where the element is described.
Definition at line 701 of file Phase.cpp.
References Phase::addElement().
void addUniqueElement (const std::string & symbol, doublereal weight = -12345.0, int atomicNumber = 0, doublereal entropy298 = ENTROPY298_UNKNOWN, int elem_type = CT_ELEM_TYPE_ABSPOS) inherited
Add an element, checking for uniqueness The uniqueness is checked by comparing the string symbol.
If not unique, nothing is done.
Parameters
symbol String symbol of the element
weight Atomic weight of the element (kg kmol-1).
atomicNumber Atomic number of the element (unitless)
entropy298 Entropy of the element at 298 K and 1 bar in its most stable form. The default is the value ENTROPY298_UNKNOWN, which is interpreted as an unknown, and if used will cause Cantera to throw an error.
elem_type Specifies the type of the element constraint equation. This defaults to CT_ELEM_TYPE_ABSPOS, i.e., an element.
Definition at line 708 of file Phase.cpp.
References CT_ELEM_TYPE_ELECTRONCHARGE, Cantera::LookupWtElements(), Phase::m_atomicNumbers, Phase::m_atomicWeights, Phase::m_elem_type, Phase::m_elementNames, Phase::m_elementsFrozen, Phase::m_entropy298, and Phase::m_mm.
Referenced by Phase::addElementsFromXML(), Phase::addUniqueElement(), Phase::addUniqueElementAfterFreeze(), and FixedChemPotSSTP::FixedChemPotSSTP().
void addUniqueElement (const XML_Node & e) inherited
Add an element, checking for uniqueness The uniqueness is checked by comparing the string symbol.
If not unique, nothing is done.
Parameters
e Reference to the XML_Node where the element is described.
Definition at line 755 of file Phase.cpp.
References Phase::addUniqueElement(), Cantera::atofCheck(), XML_Node::child(), ENTROPY298_UNKNOWN, XML_Node::hasAttrib(), XML_Node::hasChild(), and Cantera::stripws().
void addElementsFromXML (const XML_Node & phase) inherited
Add all elements referenced in an XML_Node tree.
Parameters
phase Reference to the root XML_Node of a phase
Definition at line 780 of file Phase.cpp.
References Phase::addUniqueElement(), XML_Node::child(), XML_Node::findByAttr(), Cantera::get_XML_File(), ctml::getStringArray(), XML_Node::hasAttrib(), XML_Node::hasChild(), and XML_Node::root().
Referenced by Cantera::importPhase().
void freezeElements () inherited
Prohibit addition of more elements, and prepare to add species.
Definition at line 831 of file Phase.cpp.
References Phase::m_elementsFrozen.
Referenced by FixedChemPotSSTP::FixedChemPotSSTP().
bool elementsFrozen () inherited
True if freezeElements has been called.
Definition at line 836 of file Phase.cpp.
References Phase::m_elementsFrozen.
size_t addUniqueElementAfterFreeze (const std::string & symbol, doublereal weight, int atomicNumber, doublereal entropy298 = ENTROPY298_UNKNOWN, int elem_type = CT_ELEM_TYPE_ABSPOS) inherited
Add an element after elements have been frozen, checking for uniqueness The uniqueness is checked by comparing the string symbol.
If not unique, nothing is done.
Parameters
symbol String symbol of the element
weight Atomic weight of the element (kg kmol-1).
atomicNumber Atomic number of the element (unitless)
entropy298 Entropy of the element at 298 K and 1 bar in its most stable form. The default is the value ENTROPY298_UNKNOWN, which if used will cause Cantera to throw an error.
elem_type Specifies the type of the element constraint equation. This defaults to CT_ELEM_TYPE_ABSPOS, i.e., an element.
Definition at line 841 of file Phase.cpp.
References Phase::addUniqueElement(), Phase::elementIndex(), Phase::m_elementsFrozen, Phase::m_kk, Phase::m_mm, Phase::m_speciesComp, and Cantera::npos.
Referenced by LatticeSolidPhase::installSlavePhases().
void addUniqueSpecies (const std::string & name, const doublereal * comp, doublereal charge = 0.0, doublereal size = 1.0) inherited
Add a species to the phase, checking for uniqueness of the name This routine checks for uniqueness of the string name.
It only adds the species if it is unique.
Parameters
name String name of the species
comp Array containing the elemental composition of the species.
charge Charge of the species. Defaults to zero.
size Size of the species (meters). Defaults to 1 meter.
Definition at line 919 of file Phase.cpp.
References Phase::m_kk, Phase::m_mm, Phase::m_speciesCharge, Phase::m_speciesComp, Phase::m_speciesNames, and Phase::m_speciesSize.
Referenced by FixedChemPotSSTP::FixedChemPotSSTP(), LatticeSolidPhase::installSlavePhases(), and Cantera::installSpecies().
void freezeSpecies () virtual inherited
Call when finished adding species.
Prepare to use them for calculation of mixture properties.
Definition at line 952 of file Phase.cpp.
References Phase::init(), Phase::m_speciesFrozen, and Phase::molecularWeights().
Referenced by FixedChemPotSSTP::FixedChemPotSSTP(), and Cantera::importPhase().
bool speciesFrozen () inline inherited
True if freezeSpecies has been called.
Definition at line 694 of file Phase.h.
References Phase::m_speciesFrozen.
int stateMFNumber () const inline inherited
Return the State Mole Fraction Number.
Definition at line 701 of file Phase.h.
References Phase::m_stateNum.
Referenced by SimpleTransport::update_C(), and LiquidTransport::update_C().
void stateMFChangeCalc (bool forceChange = false) inline inherited
Every time the mole fractions have changed, this routine will increment the stateMFNumber.
@param forceChange If this is true then the stateMFNumber always
changes. This defaults to false.
Deprecated:
Definition at line 115 of file Phase.cpp.
References Phase::m_stateNum.
Referenced by Phase::setConcentrations(), Phase::setMassFractions(), Phase::setMassFractions_NoNorm(), Phase::setMoleFractions(), and Phase::setMoleFractions_NoNorm().
void init (const vector_fp & mw) protected inherited
Initialize. Make a local copy of the vector of molecular weights, and resize the composition arrays to the appropriate size.
Parameters
mw Vector of molecular weights of the species.
Definition at line 958 of file Phase.cpp.
References Cantera::int2str(), Phase::m_kk, Phase::m_mmw, Phase::m_molwts, Phase::m_rmolwts, Phase::m_y, Phase::m_ym, and Cantera::Tiny.
Referenced by Phase::freezeSpecies().
void setMolecularWeight (const int k, const double mw) inline protected inherited
Set the molecular weight of a single species to a given value.
Parameters
k id of the species
mw Molecular Weight (kg kmol-1)
Definition at line 722 of file Phase.h.
References Phase::m_molwts, and Phase::m_rmolwts.
Referenced by PureFluidPhase::initThermo(), and WaterSSTP::initThermoXML().
Kinetics * duplMyselfAsKinetics (const std::vector< thermo_t * > & tpVector) const virtual inherited
Duplication routine for objects which inherit from Kinetics.
This virtual routine can be used to duplicate Kinetics objects inherited from Kinetics even if the application only has a pointer to Kinetics to work with.
These routines are basically wrappers around the derived copy constructor.
Parameters
tpVector Vector of shallow pointers to ThermoPhase objects. this is the m_thermo vector within this object
Reimplemented from Kinetics.
Reimplemented in EdgeKinetics.
Definition at line 253 of file InterfaceKinetics.cpp.
References Kinetics::assignShallowPointers(), and InterfaceKinetics::InterfaceKinetics().
int ID () const virtual inherited
Return the ID of the kinetics object.
Deprecated:
use type() instead
Reimplemented from Kinetics.
Reimplemented in EdgeKinetics.
Definition at line 231 of file InterfaceKinetics.cpp.
int type () const virtual inherited
Return the type of the kinetics object.
Reimplemented from Kinetics.
Reimplemented in EdgeKinetics.
Definition at line 236 of file InterfaceKinetics.cpp.
Referenced by InterfaceKinetics::registerReaction().
void setElectricPotential (int n, doublereal V) inherited
Set the electric potential in the nth phase.
Parameters
n phase Index in this kinetics object.
V Electric potential (volts)
Definition at line 265 of file InterfaceKinetics.cpp.
References ThermoPhase::setElectricPotential(), and Kinetics::thermo().
virtual void getFwdRatesOfProgress (doublereal * fwdROP) inline virtual inherited
Return the forward rates of progress for each reaction.
Parameters
fwdROP vector of rates of progress. length = number of reactions, Units are kmol m-2 s-1.
Reimplemented from Kinetics.
Definition at line 181 of file InterfaceKinetics.h.
References InterfaceKinetics::m_kdata, and InterfaceKinetics::updateROP().
virtual void getRevRatesOfProgress (doublereal * revROP) inline virtual inherited
Return the reverse rates of progress for each reaction.
Parameters
revROP vector of rates of progress. length = number of reactions, Units are kmol m-2 s-1.
Reimplemented from Kinetics.
Definition at line 191 of file InterfaceKinetics.h.
References InterfaceKinetics::m_kdata, and InterfaceKinetics::updateROP().
virtual void getNetRatesOfProgress (doublereal * netROP) inline virtual inherited
Return the net rates of progress for each reaction.
Parameters
netROP vector of rates of progress. length = number of reactions, Units are kmol m-2 s-1.
Reimplemented from Kinetics.
Definition at line 201 of file InterfaceKinetics.h.
References InterfaceKinetics::m_kdata, and InterfaceKinetics::updateROP().
void getEquilibriumConstants (doublereal * kc) virtual inherited
Get the equilibrium constants of all reactions, whether the reaction is reversible or not.
Get the equilibrium constants of all reactions, whether reversible or not.
Parameters
kc Returns the concentration equation constant for the reaction. Length is the number of reactions
Reimplemented from Kinetics.
Definition at line 449 of file InterfaceKinetics.cpp.
References Phase::charge(), DATA_PTR, Cantera::GasConstant, ReactionStoichMgr::getReactionDelta(), ThermoPhase::getStandardChemPotentials(), ThermoPhase::logStandardConc(), Kinetics::m_ii, InterfaceKinetics::m_mu0, InterfaceKinetics::m_phi, InterfaceKinetics::m_rxnstoich, Kinetics::m_start, Kinetics::nPhases(), Phase::nSpecies(), Phase::temperature(), and Kinetics::thermo().
Referenced by InterfaceKinetics::getRevRateConstants().
void getDeltaGibbs (doublereal * deltaG) virtual inherited
Return the vector of values for the reaction gibbs free energy change.
These values depend upon the concentration of the solution.
units = J kmol-1
Parameters
deltaG Output vector of deltaG's for reactions Length: m_ii.
Reimplemented from Kinetics.
Definition at line 841 of file InterfaceKinetics.cpp.
References DATA_PTR, ThermoPhase::getChemPotentials(), ReactionStoichMgr::getReactionDelta(), InterfaceKinetics::m_grt, InterfaceKinetics::m_rxnstoich, Kinetics::m_start, Kinetics::nPhases(), and Kinetics::thermo().
void getDeltaElectrochemPotentials (doublereal * deltaM) virtual inherited
Return the vector of values for the reaction electrochemical free energy change.
These values depend upon the concentration of the solution and the voltage of the phases
units = J kmol-1
Parameters
deltaM Output vector of deltaM's for reactions Length: m_ii.
Reimplemented from Kinetics.
Definition at line 871 of file InterfaceKinetics.cpp.
References DATA_PTR, ThermoPhase::getElectrochemPotentials(), ReactionStoichMgr::getReactionDelta(), InterfaceKinetics::m_grt, InterfaceKinetics::m_rxnstoich, Kinetics::m_start, Kinetics::nPhases(), and Kinetics::thermo().
void getDeltaEnthalpy (doublereal * deltaH) virtual inherited
Return the vector of values for the reactions change in enthalpy.
These values depend upon the concentration of the solution.
units = J kmol-1
Reimplemented from Kinetics.
Definition at line 899 of file InterfaceKinetics.cpp.
References DATA_PTR, ThermoPhase::getPartialMolarEnthalpies(), ReactionStoichMgr::getReactionDelta(), InterfaceKinetics::m_grt, InterfaceKinetics::m_rxnstoich, Kinetics::m_start, Kinetics::nPhases(), and Kinetics::thermo().
void getDeltaEntropy (doublereal * deltaS) virtual inherited
Return the vector of values for the change in entropy due to each reaction.
These values depend upon the concentration of the solution.
units = J kmol-1 Kelvin-1
Parameters
deltaS vector of Enthalpy changes Length = m_ii, number of reactions
Reimplemented from Kinetics.
Definition at line 928 of file InterfaceKinetics.cpp.
References DATA_PTR, ThermoPhase::getPartialMolarEntropies(), ReactionStoichMgr::getReactionDelta(), InterfaceKinetics::m_grt, InterfaceKinetics::m_rxnstoich, Kinetics::m_start, Kinetics::nPhases(), and Kinetics::thermo().
void getDeltaSSGibbs (doublereal * deltaG) virtual inherited
Return the vector of values for the reaction standard state gibbs free energy change.
getDeltaSSGibbs():
These values don't depend upon the concentration of the solution.
Parameters
deltaG vector of rxn SS free energy changes units = J kmol-1
Return the vector of values for the reaction standard state gibbs free energy change. These values don't depend upon the concentration of the solution.
units = J kmol-1
Reimplemented from Kinetics.
Definition at line 955 of file InterfaceKinetics.cpp.
References DATA_PTR, ReactionStoichMgr::getReactionDelta(), ThermoPhase::getStandardChemPotentials(), InterfaceKinetics::m_grt, InterfaceKinetics::m_rxnstoich, Kinetics::m_start, Kinetics::nPhases(), and Kinetics::thermo().
void getDeltaSSEnthalpy (doublereal * deltaH) virtual inherited
Return the vector of values for the change in the standard state enthalpies of reaction.
getDeltaSSEnthalpy():
These values don't depend upon the concentration of the solution.
Parameters
deltaH vector of rxn SS enthalpy changes units = J kmol-1
Return the vector of values for the change in the standard state enthalpies of reaction. These values don't depend upon the concentration of the solution.
units = J kmol-1
Reimplemented from Kinetics.
Definition at line 984 of file InterfaceKinetics.cpp.
References DATA_PTR, Cantera::GasConstant, ThermoPhase::getEnthalpy_RT(), ReactionStoichMgr::getReactionDelta(), InterfaceKinetics::m_grt, Kinetics::m_kk, InterfaceKinetics::m_rxnstoich, Kinetics::m_start, Kinetics::nPhases(), Phase::temperature(), and Kinetics::thermo().
void getDeltaSSEntropy (doublereal * deltaS) virtual inherited
Return the vector of values for the change in the standard state entropies for each reaction.
These values don't depend upon the concentration of the solution.
Parameters
deltaS vector of rxn SS entropy changes units = J kmol-1 Kelvin-1
Reimplemented from Kinetics.
Definition at line 1017 of file InterfaceKinetics.cpp.
References DATA_PTR, Cantera::GasConstant, ThermoPhase::getEntropy_R(), ReactionStoichMgr::getReactionDelta(), InterfaceKinetics::m_grt, Kinetics::m_kk, InterfaceKinetics::m_rxnstoich, Kinetics::m_start, Kinetics::nPhases(), and Kinetics::thermo().
void getCreationRates (doublereal * cdot) virtual inherited
Returns the Species creation rates [kmol/m^2/s].
Return the species creation rates in array cdot, which must be dimensioned at least as large as the total number of species in all phases of the kinetics model
Parameters
cdot Vector containing creation rates. length = m_kk. units = kmol/m^2/s
Reimplemented from Kinetics.
Definition at line 513 of file InterfaceKinetics.cpp.
References ReactionStoichMgr::getCreationRates(), InterfaceKinetics::m_kdata, Kinetics::m_kk, InterfaceKinetics::m_rxnstoich, and InterfaceKinetics::updateROP().
void getDestructionRates (doublereal * ddot) virtual inherited
Return the Species destruction rates [kmol/m^2/s].
Return the species destruction rates in array ddot, which must be dimensioned at least as large as the total number of species in all phases of the kinetics model
Parameters
ddot Vector containing destruction rates. length = m_kk. units = kmol/m^2/s
Reimplemented from Kinetics.
Definition at line 526 of file InterfaceKinetics.cpp.
References ReactionStoichMgr::getDestructionRates(), InterfaceKinetics::m_kdata, Kinetics::m_kk, InterfaceKinetics::m_rxnstoich, and InterfaceKinetics::updateROP().
void getNetProductionRates (doublereal * net) virtual inherited
Return the species net production rates [kmol/m^2/s].
Species net production rates [kmol/m^2/s]. Return the species net production rates (creation - destruction) in array wdot, which must be dimensioned at least as large as the total number of species in all phases of the kinetics model
Parameters
net Vector of species production rates. units kmol m-d s-1, where d is dimension.
Reimplemented from Kinetics.
Definition at line 544 of file InterfaceKinetics.cpp.
References ReactionStoichMgr::getNetProductionRates(), InterfaceKinetics::m_kdata, Kinetics::m_kk, InterfaceKinetics::m_rxnstoich, and InterfaceKinetics::updateROP().
Referenced by solveSP::calc_t(), ReactingSurf1D::eval(), solveSP::fun_eval(), solveProb::print_header(), and solveProb::printIteration().
virtual doublereal reactantStoichCoeff (size_t k, size_t i) const inline virtual inherited
Stoichiometric coefficient of species k as a reactant in reaction i.
Reimplemented from Kinetics.
Definition at line 353 of file InterfaceKinetics.h.
References InterfaceKinetics::m_rrxn.
virtual doublereal productStoichCoeff (size_t k, size_t i) const inline virtual inherited
Stoichiometric coefficient of species k as a product in reaction i.
Reimplemented from Kinetics.
Definition at line 361 of file InterfaceKinetics.h.
References InterfaceKinetics::m_prxn.
virtual int reactionType (size_t i) const inline virtual inherited
Flag specifying the type of reaction.
The legal values and their meaning are specific to the particular kinetics manager.
Reimplemented from Kinetics.
Definition at line 370 of file InterfaceKinetics.h.
References InterfaceKinetics::m_index.
void getActivityConcentrations (doublereal *const conc) virtual inherited
Get the vector of activity concentrations used in the kinetics object.
Parameters
conc (output) Vector of activity concentrations. Length is equal to the number of species in the kinetics object
Reimplemented from Kinetics.
Definition at line 348 of file InterfaceKinetics.cpp.
References InterfaceKinetics::_update_rates_C(), and InterfaceKinetics::m_conc.
doublereal electrochem_beta (size_t irxn) const inherited
Return the charge transfer rxn Beta parameter for the ith reaction.
Returns the beta parameter for a charge transfer reaction. This parameter is not important for non-charge transfer reactions. Note, the parameter defaults to zero. However, a value of 0.5 should be supplied for every charge transfer reaction if no information is known, as a value of 0.5 pertains to a symmetric transition state. The value can vary between 0 to 1.
Parameters
irxn Reaction number in the kinetics mechanism
Returns
Beta parameter. This defaults to zero, even for charge transfer reactions.
Definition at line 1363 of file InterfaceKinetics.cpp.
References InterfaceKinetics::m_ctrxn.
virtual bool isReversible (size_t i) inline virtual inherited
True if reaction i has been declared to be reversible.
If isReversible(i) is false, then the reverse rate of progress for reaction i is always zero.
Reimplemented from Kinetics.
Definition at line 404 of file InterfaceKinetics.h.
References InterfaceKinetics::m_revindex.
virtual std::string reactionString (size_t i) const inline virtual inherited
Return a string representing the reaction.
Reimplemented from Kinetics.
Definition at line 416 of file InterfaceKinetics.h.
References InterfaceKinetics::m_rxneqn.
void getFwdRateConstants (doublereal * kfwd) virtual inherited
Update the rates of progress of the reactions in the reaction mechanism.
This routine operates on internal data.
Reimplemented from Kinetics.
Definition at line 641 of file InterfaceKinetics.cpp.
References InterfaceKinetics::m_kdata, Kinetics::m_perturb, Cantera::multiply_each(), Kinetics::nReactions(), and InterfaceKinetics::updateROP().
Referenced by InterfaceKinetics::getRevRateConstants().
void getRevRateConstants (doublereal * krev, bool doIrreversible = false) virtual inherited
Update the rates of progress of the reactions in the reaction mechanism.
This routine operates on internal data.
Reimplemented from Kinetics.
Definition at line 661 of file InterfaceKinetics.cpp.
References DATA_PTR, InterfaceKinetics::getEquilibriumConstants(), InterfaceKinetics::getFwdRateConstants(), Kinetics::m_ii, InterfaceKinetics::m_kdata, Cantera::multiply_each(), and Kinetics::nReactions().
void getActivationEnergies (doublereal * E) virtual inherited
Return the activation energies in Kelvin.
length is the number of reactions
Parameters
E Ouptut vector of activation energies. Length: m_ii.
Reimplemented from Kinetics.
Definition at line 677 of file InterfaceKinetics.cpp.
References InterfaceKinetics::m_E.
void addPhase (thermo_t & thermo) virtual inherited
Add a phase to the kinetics manager object.
This must be done before the function init() is called or before any reactions are input.
This function calls the Kinetics operator addPhase. It also sets the following functions
   m_phaseExists[]
Parameters
thermo Reference to the ThermoPhase to be added.
Reimplemented from Kinetics.
Definition at line 1294 of file InterfaceKinetics.cpp.
References Kinetics::addPhase(), InterfaceKinetics::m_phaseExists, and InterfaceKinetics::m_phaseIsStable.
Referenced by InterfaceKinetics::InterfaceKinetics().
void init () virtual inherited
Prepare the class for the addition of reactions.
This function must be called after instantiation of the class, but before any reactions are actually added to the mechanism. This function calculates m_kk the number of species in all phases participating in the reaction mechanism. We don't know m_kk previously, before all phases have been added.
Reimplemented from Kinetics.
Definition at line 1309 of file InterfaceKinetics.cpp.
References InterfaceKinetics::m_conc, InterfaceKinetics::m_grt, Kinetics::m_kk, InterfaceKinetics::m_mu0, InterfaceKinetics::m_phi, InterfaceKinetics::m_pot, InterfaceKinetics::m_prxn, InterfaceKinetics::m_rrxn, Kinetics::nPhases(), Phase::nSpecies(), and Kinetics::thermo().
void addReaction (ReactionData & r) virtual inherited
Add a single reaction to the mechanism.
Parameters
r Reference to a ReactionData object containing all of the info needed to describe the reaction.
This routine must be called after init() and before finalize(). This function branches on the types of reactions allowed by the interfaceKinetics manager in order to install the reaction correctly in the manager. The manager allows the following reaction types Elementary Surface Global There is no difference between elementary and surface reactions.
Reimplemented from Kinetics.
Definition at line 1052 of file InterfaceKinetics.cpp.
References Kinetics::incrementRxnCount(), InterfaceKinetics::m_rxneqn, InterfaceKinetics::m_rxnPhaseIsProduct, InterfaceKinetics::m_rxnPhaseIsReactant, Kinetics::nPhases(), Kinetics::products(), Kinetics::reactants(), and Kinetics::speciesPhaseIndex().
void finalize () virtual inherited
Finish adding reactions and prepare for use.
This function must be called after all reactions are entered into the mechanism and before the mechanism is used to calculate reaction rates.
This function must be called after all reactions are entered into the mechanism and before the mechanism is used to calculate reaction rates.
Here, we resize work arrays based on the number of reactions, since we don't know this number up to now.
Reimplemented from Kinetics.
Reimplemented in EdgeKinetics.
Definition at line 1332 of file InterfaceKinetics.cpp.
References Kinetics::finalize(), Cantera::int2str(), InterfaceKinetics::m_finalized, Kinetics::m_kk, Kinetics::m_perturb, InterfaceKinetics::m_phaseExists, InterfaceKinetics::m_rwork, InterfaceKinetics::m_surf, Kinetics::m_thermo, Phase::nDim(), Cantera::npos, Kinetics::nReactions(), Kinetics::reactionPhaseIndex(), and Kinetics::thermo().
void updateROP () inherited
Internal routine that updates the Rates of Progress of the reactions.
Update the rates of progress of the reactions in the reaction mechanism.
This is actually the guts of the functionality of the object
This routine operates on internal data.
Definition at line 686 of file InterfaceKinetics.cpp.
References InterfaceKinetics::_update_rates_C(), InterfaceKinetics::_update_rates_T(), DATA_PTR, InterfaceKinetics::m_conc, Kinetics::m_ii, InterfaceKinetics::m_kdata, Kinetics::m_perturb, InterfaceKinetics::m_phaseExists, InterfaceKinetics::m_phaseExistsCheck, InterfaceKinetics::m_phaseIsStable, InterfaceKinetics::m_rxnPhaseIsProduct, InterfaceKinetics::m_rxnPhaseIsReactant, InterfaceKinetics::m_rxnstoich, Cantera::multiply_each(), ReactionStoichMgr::multiplyReactants(), ReactionStoichMgr::multiplyRevProducts(), and Kinetics::nPhases().
Referenced by InterfaceKinetics::getCreationRates(), InterfaceKinetics::getDestructionRates(), InterfaceKinetics::getFwdRateConstants(), InterfaceKinetics::getFwdRatesOfProgress(), InterfaceKinetics::getNetProductionRates(), InterfaceKinetics::getNetRatesOfProgress(), and InterfaceKinetics::getRevRatesOfProgress().
void _update_rates_T () inherited
Update properties that depend on temperature.
This is called to update all of the properties that depend on temperature
Current objects that this function updates m_kdata->m_logtemp m_kdata->m_rfn m_rates. updateKc();
Definition at line 281 of file InterfaceKinetics.cpp.
References InterfaceKinetics::_update_rates_phi(), InterfaceKinetics::applyButlerVolmerCorrection(), InterfaceKinetics::applyExchangeCurrentDensityFormulation(), DATA_PTR, SurfPhase::getCoverages(), InterfaceKinetics::m_conc, InterfaceKinetics::m_has_coverage_dependence, InterfaceKinetics::m_has_electrochem_rxns, InterfaceKinetics::m_has_exchange_current_density_formulation, InterfaceKinetics::m_kdata, InterfaceKineticsData::m_logtemp, InterfaceKinetics::m_rates, InterfaceKinetics::m_surf, InterfaceKineticsData::m_temp, Kinetics::surfacePhaseIndex(), Phase::temperature(), Kinetics::thermo(), Rate1< R >::update(), Rate1< R >::update_C(), and InterfaceKinetics::updateKc().
Referenced by InterfaceKinetics::updateROP().
void _update_rates_phi () inherited
Update properties that depend on the electric potential.
This is called to update all of the properties that depend on potential
Definition at line 307 of file InterfaceKinetics.cpp.
References ThermoPhase::electricPotential(), InterfaceKinetics::m_phi, Kinetics::nPhases(), and Kinetics::thermo().
Referenced by InterfaceKinetics::_update_rates_T().
void _update_rates_C () inherited
Update properties that depend on the species mole fractions and/or concentration.
Update properties that depend on concentrations.
This is called to update all of the properties that depend on concentration
This method fills out the array of generalized concentrations by calling method getActivityConcentrations for each phase, which classes representing phases should overload to return the appropriate quantities.
Definition at line 326 of file InterfaceKinetics.cpp.
References DATA_PTR, ThermoPhase::getActivityConcentrations(), InterfaceKinetics::m_conc, InterfaceKinetics::m_kdata, Kinetics::m_start, Kinetics::nPhases(), and Kinetics::thermo().
Referenced by InterfaceKinetics::getActivityConcentrations(), and InterfaceKinetics::updateROP().
void advanceCoverages (doublereal tstep) inherited
Advance the surface coverages in time.
This method carries out a time-accurate advancement of the surface coverages for a specified amount of time.
\[ \dot {\theta}_k = \dot s_k (\sigma_k / s_0) \]
Parameters
tstep Time value to advance the surface coverages
Definition at line 1384 of file InterfaceKinetics.cpp.
References ImplicitSurfChem::initialize(), ImplicitSurfChem::integrate(), and InterfaceKinetics::m_integrator.
void solvePseudoSteadyStateProblem (int ifuncOverride = -1, doublereal timeScaleOverride = 1.0) inherited
Solve for the pseudo steady-state of the surface problem.
Solve for the steady state of the surface problem. This is the same thing as the advanceCoverages() function, but at infinite times.
Note, a direct solve is carried out under the hood here, to reduce the computational time.
Parameters
ifuncOverride 4 values are possible 1 SFLUX_INITIALIZE 2 SFLUX_RESIDUAL 3 SFLUX_JACOBIAN 4 SFLUX_TRANSIENT The default is -1, which means that the program will decide.
timeScaleOverride When a pseudo transient is selected this value can be used to override the default time scale for integration which is one. When SFLUX_TRANSIENT is used, this is equal to the time over which the equations are integrated. When SFLUX_INITIALIZE is used, this is equal to the time used in the initial transient algorithm, before the equation system is solved directly.
Definition at line 1410 of file InterfaceKinetics.cpp.
References ImplicitSurfChem::initialize(), InterfaceKinetics::m_integrator, and ImplicitSurfChem::solvePseudoSteadyStateProblem().
void updateKc () inherited
Update the equilibrium constants in molar units for all reversible reactions.
Irreversible reactions have their equilibrium constant set to zero.
Definition at line 360 of file InterfaceKinetics.cpp.
References Phase::charge(), DATA_PTR, Cantera::GasConstant, ReactionStoichMgr::getRevReactionDelta(), ThermoPhase::getStandardChemPotentials(), Cantera::int2str(), ThermoPhase::logStandardConc(), Kinetics::m_ii, InterfaceKinetics::m_irrev, InterfaceKinetics::m_kdata, InterfaceKinetics::m_mu0, InterfaceKinetics::m_nirrev, InterfaceKinetics::m_nrev, InterfaceKinetics::m_phi, InterfaceKinetics::m_revindex, InterfaceKinetics::m_rxnstoich, Kinetics::m_start, Kinetics::nPhases(), Cantera::npos, Kinetics::nReactions(), Phase::nSpecies(), Phase::temperature(), and Kinetics::thermo().
Referenced by InterfaceKinetics::_update_rates_T().
void registerReaction (size_t rxnNumber, int type, size_t loc) inline inherited
Write values into m_index.
Parameters
rxnNumber reaction number
type reaction type
loc location ??
Definition at line 572 of file InterfaceKinetics.h.
References InterfaceKinetics::m_index, and InterfaceKinetics::type().
void applyButlerVolmerCorrection (doublereal *const kf) inherited
Apply corrections for interfacial charge transfer reactions.
For reactions that transfer charge across a potential difference, the activation energies are modified by the potential difference. (see, for example, ...). This method applies this correction.
Parameters
kf Vector of forward reaction rate constants on which to have the correction applied
Definition at line 562 of file InterfaceKinetics.cpp.
References Phase::charge(), DATA_PTR, Cantera::fp2str(), Cantera::GasConstant, ReactionStoichMgr::getReactionDelta(), Cantera::int2str(), InterfaceKinetics::m_ctrxn, InterfaceKinetics::m_E, InterfaceKinetics::m_phi, InterfaceKinetics::m_pot, InterfaceKinetics::m_rwork, InterfaceKinetics::m_rxnstoich, Kinetics::nPhases(), Phase::nSpecies(), Phase::temperature(), Kinetics::thermo(), and Cantera::writelog().
Referenced by InterfaceKinetics::_update_rates_T().
void applyExchangeCurrentDensityFormulation (doublereal *const kfwd) inherited
When an electrode reaction rate is optionally specified in terms of its exchange current density, extra vectors need to be precalculated.
Definition at line 618 of file InterfaceKinetics.cpp.
References Cantera::GasConstant, InterfaceKinetics::m_ctrxn, InterfaceKinetics::m_ctrxn_ecdf, Phase::temperature(), and Kinetics::thermo().
Referenced by InterfaceKinetics::_update_rates_T().
void setPhaseExistence (const size_t iphase, const bool exists) inherited
Set the existence of a phase in the reaction object.
Tell the kinetics object whether a phase in the object exists. This is actually an extrinsic specification that must be carried out on top of the intrinsic calculation of the reaction rate. The routine will also flip the IsStable boolean within the kinetics object as well.
Parameters
iphase Index of the phase. This is the order within the internal thermo vector object
exists Boolean indicating whether the phase exists or not
Definition at line 1427 of file InterfaceKinetics.cpp.
References InterfaceKinetics::m_phaseExists, InterfaceKinetics::m_phaseExistsCheck, InterfaceKinetics::m_phaseIsStable, and Kinetics::m_thermo.
void setPhaseStability (const int iphase, const int isStable) inherited
Set the stability of a phase in the reaction object.
Tell the kinetics object whether a phase in the object is stable. Species in an unstable phase will not be allowed to have a positive rate of formation from this kinetics object. This is actually an extrinsic specification that must be carried out on top of the intrinsic calculation of the reaction rate.
While conceptually not needed since kinetics is consistent with thermo when taken as a whole, in practice it has found to be very useful to turn off the creation of phases which shouldn't be forming. Typically this can reduce the oscillations in phase formation and destruction which are observed.
Parameters
iphase Index of the phase. This is the order within the internal thermo vector object
isStable Flag indicating whether the phase is stable or not
Definition at line 1480 of file InterfaceKinetics.cpp.
References InterfaceKinetics::m_phaseIsStable, and Kinetics::m_thermo.
int phaseExistence (const int iphase) const inherited
Gets the phase existence int for the ith phase.
Parameters
iphase Phase Id
Returns
Returns the int specifying whether the kinetics object thinks the phase exists or not. If it exists, then species in that phase can be a reactant in reactions.
Definition at line 1454 of file InterfaceKinetics.cpp.
References InterfaceKinetics::m_phaseExists, and Kinetics::m_thermo.
int phaseStability (const int iphase) const inherited
Gets the phase stability int for the ith phase.
Parameters
iphase Phase Id
Returns
Returns the int specifying whether the kinetics object thinks the phase is stable with nonzero mole numbers. If it stable, then the kinetics object will allow for rates of production of of species in that phase that are positive.
Definition at line 1471 of file InterfaceKinetics.cpp.
References InterfaceKinetics::m_phaseIsStable, and Kinetics::m_thermo.
void assignShallowPointers (const std::vector< thermo_t * > & tpVector) virtual inherited
Reassign the shallow pointers within the FKinetics object.
This type or routine is absolute necessary because the Kinetics object doesn't own the ThermoPhase objects. After a duplication, we need to point to different ThermoPhase objects.
We check that the ThermoPhase objects are aligned in the same order and have the following identical properties to the ones that they are replacing. id() eosType() nSpecies()
Parameters
tpVector Vector of shallow pointers to ThermoPhase objects. this is the m_thermo vector within this object
Definition at line 179 of file Kinetics.cpp.
References ThermoPhase::eosType(), Phase::id(), Kinetics::m_thermo, and Phase::nSpecies().
Referenced by EdgeKinetics::duplMyselfAsKinetics(), AqueousKinetics::duplMyselfAsKinetics(), GasKinetics::duplMyselfAsKinetics(), InterfaceKinetics::duplMyselfAsKinetics(), and Kinetics::duplMyselfAsKinetics().
size_t nReactions () const inline inherited
Number of reactions in the reaction mechanism.
Definition at line 209 of file Kinetics.h.
References Kinetics::m_ii.
Referenced by EdgeKinetics::finalize(), InterfaceKinetics::finalize(), InterfaceKinetics::getFwdRateConstants(), InterfaceKinetics::getRevRateConstants(), and InterfaceKinetics::updateKc().
void checkReactionIndex (size_t m) const inherited
Check that the specified reaction index is in range Throws an exception if i is greater than nReactions()
Definition at line 136 of file Kinetics.cpp.
References Kinetics::m_ii.
void checkReactionArraySize (size_t ii) const inherited
Check that an array size is at least nReactions() Throws an exception if ii is less than nReactions().
Used before calls which take an array pointer.
Definition at line 143 of file Kinetics.cpp.
References Kinetics::m_ii.
void checkSpeciesIndex (size_t k) const inherited
Check that the specified species index is in range Throws an exception if k is greater than nSpecies()-1.
Definition at line 164 of file Kinetics.cpp.
References Kinetics::m_kk.
void checkSpeciesArraySize (size_t mm) const inherited
Check that an array size is at least nSpecies() Throws an exception if kk is less than nSpecies().
Used before calls which take an array pointer.
Definition at line 171 of file Kinetics.cpp.
References Kinetics::m_kk.
size_t nPhases () const inline inherited
The number of phases participating in the reaction mechanism.
For a homogeneous reaction mechanism, this will always return 1, but for a heterogeneous mechanism it will return the total number of phases in the mechanism.
Definition at line 244 of file Kinetics.h.
References Kinetics::m_thermo.
Referenced by InterfaceKinetics::_update_rates_C(), InterfaceKinetics::_update_rates_phi(), Kinetics::addPhase(), InterfaceKinetics::addReaction(), InterfaceKinetics::applyButlerVolmerCorrection(), Kinetics::checkPhaseArraySize(), Kinetics::checkPhaseIndex(), Kinetics::finalize(), InterfaceKinetics::getDeltaElectrochemPotentials(), InterfaceKinetics::getDeltaEnthalpy(), InterfaceKinetics::getDeltaEntropy(), InterfaceKinetics::getDeltaGibbs(), InterfaceKinetics::getDeltaSSEnthalpy(), InterfaceKinetics::getDeltaSSEntropy(), InterfaceKinetics::getDeltaSSGibbs(), InterfaceKinetics::getEquilibriumConstants(), ImplicitSurfChem::ImplicitSurfChem(), InterfaceKinetics::init(), Kinetics::nTotalSpecies(), InterfaceKinetics::operator=(), solveProb::print_header(), Kinetics::selectPhase(), InterfaceKinetics::updateKc(), solveSP::updateMFKinSpecies(), and InterfaceKinetics::updateROP().
void checkPhaseIndex (size_t m) const inherited
Check that the specified phase index is in range Throws an exception if m is greater than nPhases()
Definition at line 150 of file Kinetics.cpp.
References Kinetics::nPhases().
void checkPhaseArraySize (size_t mm) const inherited
Check that an array size is at least nPhases() Throws an exception if mm is less than nPhases().
Used before calls which take an array pointer.
Definition at line 157 of file Kinetics.cpp.
References Kinetics::nPhases().
size_t phaseIndex (std::string ph) inline inherited
Return the phase index of a phase in the list of phases defined within the object.
Parameters
ph std::string name of the phase
If a -1 is returned, then the phase is not defined in the Kinetics object.
Definition at line 266 of file Kinetics.h.
References Kinetics::m_phaseindex, and Cantera::npos.
Referenced by Cantera::importKinetics().
size_t surfacePhaseIndex () inline inherited
This returns the integer index of the phase which has ThermoPhase type cSurf.
For heterogeneous mechanisms, this identifies the one surface phase. For homogeneous mechanisms, this returns -1.
Definition at line 280 of file Kinetics.h.
References Kinetics::m_surfphase.
Referenced by InterfaceKinetics::_update_rates_T(), solveSP::calc_t(), solveSP::fun_eval(), Cantera::getRateCoefficient(), solveProb::print_header(), and solveSP::solveSP().
size_t reactionPhaseIndex () inline inherited
Phase where the reactions occur.
For heterogeneous mechanisms, one of the phases in the list of phases represents the 2D interface or 1D edge at which the reactions take place. This method returns the index of the phase with the smallest spatial dimension (1, 2, or 3) among the list of phases. If there is more than one, the index of the first one is returned. For homogeneous mechanisms, the value 0 is returned.
Definition at line 294 of file Kinetics.h.
References Kinetics::m_rxnphase.
Referenced by EdgeKinetics::finalize(), and InterfaceKinetics::finalize().
thermo_t& thermo (size_t n = 0) inline inherited
This method returns a reference to the nth ThermoPhase object defined in this kinetics mechanism.
It is typically used so that member functions of the ThermoPhase object may be called. For homogeneous mechanisms, there is only one object, and this method can be called without an argument to access it.
Parameters
n Index of the ThermoPhase being sought.
Definition at line 309 of file Kinetics.h.
References Kinetics::m_thermo.
Referenced by AqueousKinetics::_update_rates_C(), InterfaceKinetics::_update_rates_C(), InterfaceKinetics::_update_rates_phi(), InterfaceKinetics::_update_rates_T(), InterfaceKinetics::applyButlerVolmerCorrection(), InterfaceKinetics::applyExchangeCurrentDensityFormulation(), solveSP::calc_t(), EdgeKinetics::finalize(), InterfaceKinetics::finalize(), InterfaceKinetics::getDeltaElectrochemPotentials(), AqueousKinetics::getDeltaEnthalpy(), GasKinetics::getDeltaEnthalpy(), InterfaceKinetics::getDeltaEnthalpy(), AqueousKinetics::getDeltaEntropy(), GasKinetics::getDeltaEntropy(), InterfaceKinetics::getDeltaEntropy(), AqueousKinetics::getDeltaGibbs(), GasKinetics::getDeltaGibbs(), InterfaceKinetics::getDeltaGibbs(), AqueousKinetics::getDeltaSSEnthalpy(), GasKinetics::getDeltaSSEnthalpy(), InterfaceKinetics::getDeltaSSEnthalpy(), AqueousKinetics::getDeltaSSEntropy(), GasKinetics::getDeltaSSEntropy(), InterfaceKinetics::getDeltaSSEntropy(), AqueousKinetics::getDeltaSSGibbs(), GasKinetics::getDeltaSSGibbs(), InterfaceKinetics::getDeltaSSGibbs(), Cantera::getEfficiencies(), AqueousKinetics::getEquilibriumConstants(), GasKinetics::getEquilibriumConstants(), InterfaceKinetics::getEquilibriumConstants(), Cantera::getRateCoefficient(), Cantera::getStick(), ImplicitSurfChem::ImplicitSurfChem(), AqueousKinetics::init(), GasKinetics::init(), InterfaceKinetics::init(), ConstPressureReactor::initialize(), Reactor::initialize(), Kinetics::kineticsSpeciesIndex(), Kinetics::kineticsSpeciesName(), Kinetics::nTotalSpecies(), solveProb::print_header(), InterfaceKinetics::setElectricPotential(), ImplicitSurfChem::solvePseudoSteadyStateProblem(), solveSP::solveSP(), Kinetics::speciesPhase(), AqueousKinetics::updateKc(), GasKinetics::updateKc(), InterfaceKinetics::updateKc(), and solveSP::updateMFKinSpecies().
thermo_t& phase (size_t n = 0) inline inherited
This method returns a reference to the nth ThermoPhase defined in this kinetics mechanism.
It is typically used so that member functions of the ThermoPhase may be called.
Deprecated:
This method is redundant.
Parameters
n Index of the ThermoPhase being sought.
Definition at line 324 of file Kinetics.h.
References Cantera::deprecatedMethod(), and Kinetics::m_thermo.
const thermo_t& phase (size_t n = 0) const inline inherited
This method returns a reference to the nth ThermoPhase defined in this kinetics mechanism.
It is typically used so that member functions of the ThermoPhase may be called.
Deprecated:
This method is redundant.
Parameters
n Index of the ThermoPhase being sought.
Definition at line 336 of file Kinetics.h.
References Cantera::deprecatedMethod(), and Kinetics::m_thermo.
size_t nTotalSpecies () const inline inherited
The total number of species in all phases participating in the kinetics mechanism.
This is useful to dimension arrays for use in calls to methods that return the species production rates, for example.
Definition at line 347 of file Kinetics.h.
References Kinetics::nPhases(), Phase::nSpecies(), and Kinetics::thermo().
Referenced by ReactingSurf1D::init(), and rxninfo::installReaction().
size_t start (size_t n) inline inherited
Returns the starting index of the species in the nth phase associated with the reaction mechanism.
Parameters
n Return the index of first species in the nth phase associated with the reaction mechanism.
Definition at line 363 of file Kinetics.h.
References Cantera::deprecatedMethod(), and Kinetics::m_start.
size_t kineticsSpeciesIndex (size_t k, size_t n) const inline inherited
The location of species k of phase n in species arrays.
Kinetics manager classes return species production rates in flat arrays, with the species of each phases following one another, in the order the phases were added. This method is useful to find the value for a particular species of a particular phase in arrays returned from methods like getCreationRates that return an array of species-specific quantities.
Example: suppose a heterogeneous mechanism involves three phases. The first contains 12 species, the second 26, and the third 3. Then species arrays must have size at least 41, and positions 0 - 11 are the values for the species in the first phase, positions 12 - 37 are the values for the species in the second phase, etc. Then kineticsSpeciesIndex(7, 0) = 7, kineticsSpeciesIndex(4, 1) = 16, and kineticsSpeciesIndex(2, 2) = 40.
Parameters
k species index
n phase index for the species
Definition at line 391 of file Kinetics.h.
References Kinetics::m_start.
Referenced by solveSP::calc_t(), Cantera::checkRxnElementBalance(), ReactingSurf1D::eval(), solveSP::fun_eval(), Cantera::getEfficiencies(), Cantera::getReagents(), Cantera::getStick(), Kinetics::kineticsSpeciesIndex(), solveSP::solveSP(), and solveSP::updateMFKinSpecies().
size_t kineticsSpeciesIndex (const std::string & nm) const inherited
This routine will look up a species number based on the input std::string nm.
The lookup of species will occur for all phases listed in the kinetics object.
return
If a match is found, the position in the species list is returned.
If no match is found, the value -1 is returned.
Parameters
nm Input string name of the species
Definition at line 263 of file Kinetics.cpp.
References Phase::id(), Kinetics::m_start, Kinetics::m_thermo, Cantera::npos, Phase::speciesIndex(), and Kinetics::thermo().
size_t kineticsSpeciesIndex (const std::string & nm, const std::string & ph) const inherited
This routine will look up a species number based on the input std::string nm.
The lookup of species will occur in the specified phase of the object, or all phases if ph is "<any>".
return
If a match is found, the position in the species list is returned.
If no match is found, the value npos (-1) is returned.
Parameters
nm Input string name of the species
ph Input string name of the phase.
Definition at line 288 of file Kinetics.cpp.
References Phase::id(), Kinetics::kineticsSpeciesIndex(), Kinetics::m_start, Kinetics::m_thermo, Cantera::npos, Phase::speciesIndex(), and Kinetics::thermo().
string kineticsSpeciesName (size_t k) const inherited
Return the std::string name of the kth species in the kinetics manager.
kineticsSpeciesName():
k is an integer from 0 to ktot - 1, where ktot is the number of species in the kinetics manager, which is the sum of the number of species in all phases participating in the kinetics manager. If k is out of bounds, the std::string "<unknown>" is returned.
Parameters
k species index
Return the string name of the kth species in the kinetics manager. k is an integer from 0 to ktot - 1, where ktot is the number of species in the kinetics manager, which is the sum of the number of species in all phases participating in the kinetics manager. If k is out of bounds, the string "<unknown>" is returned.
Definition at line 242 of file Kinetics.cpp.
References Kinetics::m_start, Cantera::npos, Phase::speciesName(), and Kinetics::thermo().
Referenced by Cantera::getStick(), solveSP::printFinal(), solveProb::printIteration(), and solveSP::printIteration().
thermo_t & speciesPhase (std::string nm) inherited
This function looks up the std::string name of a species and returns a reference to the ThermoPhase object of the phase where the species resides.
This function looks up the string name of a species and returns a reference to the ThermoPhase object of the phase where the species resides.
Will throw an error if the species std::string doesn't match.
Parameters
nm String containing the name of the species.
Will throw an error if the species string doesn't match.
Definition at line 315 of file Kinetics.cpp.
References Kinetics::m_thermo, Cantera::npos, Phase::speciesIndex(), and Kinetics::thermo().
Referenced by Cantera::checkRxnElementBalance(), Cantera::getStick(), and rxninfo::installReaction().
thermo_t& speciesPhase (size_t k) inline inherited
This function takes as an argument the kineticsSpecies index (i.e., the list index in the list of species in the kinetics manager) and returns the species' owning ThermoPhase object.
Parameters
k Species index
Definition at line 454 of file Kinetics.h.
References Kinetics::speciesPhaseIndex(), and Kinetics::thermo().
size_t speciesPhaseIndex (size_t k) inherited
This function takes as an argument the kineticsSpecies index (i.e., the list index in the list of species in the kinetics manager) and returns the index of the phase owning the species.
Parameters
k Species index
Definition at line 337 of file Kinetics.cpp.
References Cantera::int2str(), Kinetics::m_start, and Cantera::npos.
Referenced by InterfaceKinetics::addReaction(), Cantera::checkRxnElementBalance(), Cantera::getStick(), and Kinetics::speciesPhase().
virtual void getReactionDelta (const doublereal * property, doublereal * deltaProperty) inline virtual inherited
Change in species properties.
Given an array of molar species property values \(z_k, k = 1, \dots, K \), return the array of reaction values
\[ \Delta Z_i = \sum_k \nu_{k,i} z_k, i = 1, \dots, I. \]
For example, if this method is called with the array of standard-state molar Gibbs free energies for the species, then the values returned in array deltaProperty would be the standard-state Gibbs free energies of reaction for each reaction.
Parameters
property Input vector of property value. Length: m_kk.
deltaProperty Output vector of deltaRxn. Length: m_ii.
Definition at line 547 of file Kinetics.h.
References Kinetics::err().
virtual doublereal reactantOrder (size_t k, size_t i) const inline virtual inherited
Reactant order of species k in reaction i.
This is the nominal order of the activity concentration in determining the forward rate of progress of the reaction
Parameters
k kinetic species index
i reaction index
Definition at line 735 of file Kinetics.h.
References Kinetics::err().
virtual doublereal productOrder (int k, int i) const inline virtual inherited
product Order of species k in reaction i.
This is the nominal order of the activity concentration of species k in determining the reverse rate of progress of the reaction i
For irreversible reactions, this will all be zero.
Parameters
k kinetic species index
i reaction index
Definition at line 750 of file Kinetics.h.
References Kinetics::err().
virtual const std::vector<size_t>& reactants (size_t i) const inline virtual inherited
Returns a read-only reference to the vector of reactant index numbers for reaction i.
Parameters
i reaction index
Definition at line 770 of file Kinetics.h.
References Kinetics::m_reactants.
Referenced by InterfaceKinetics::addReaction(), and rxninfo::installReaction().
virtual const std::vector<size_t>& products (size_t i) const inline virtual inherited
Returns a read-only reference to the vector of product index numbers for reaction i.
Parameters
i reaction index
Definition at line 780 of file Kinetics.h.
References Kinetics::m_products.
Referenced by InterfaceKinetics::addReaction(), and rxninfo::installReaction().
doublereal multiplier (size_t i) const inline inherited
The current value of the multiplier for reaction i.
Parameters
i index of the reaction
Definition at line 953 of file Kinetics.h.
References Kinetics::m_perturb.
void setMultiplier (size_t i, doublereal f) inline inherited
Set the multiplier for reaction i to f.
Parameters
i index of the reaction
f value of the multiplier.
Definition at line 962 of file Kinetics.h.
References Kinetics::m_perturb.
void incrementRxnCount () inline inherited
Increment the number of reactions in the mechanism by one.
Todo:
Should be protected?
Definition at line 972 of file Kinetics.h.
References Kinetics::m_ii, and Kinetics::m_perturb.
Referenced by AqueousKinetics::addReaction(), GasKinetics::addReaction(), and InterfaceKinetics::addReaction().
void selectPhase (const doublereal * data, const thermo_t * phase, doublereal * phase_data) inherited
Extract from array data the portion pertaining to phase phase.
Takes as input an array of properties for all species in the mechanism and copies those values beloning to a particular phase to the output array.
Parameters
data data
phase phase
phase_data phase_data
data Input data array.
phase Pointer to one of the phase objects participating in this reaction mechanism
phase_data Output array where the values for the the specified phase are to be written.
Definition at line 217 of file Kinetics.cpp.
References Kinetics::m_start, Kinetics::m_thermo, Kinetics::nPhases(), and Phase::nSpecies().
Member Data Documentation
bool m_ok protected
Flag indicating that the object has been instantiated.
Definition at line 112 of file Interface.h.
Referenced by Interface::Interface(), Interface::operator!(), Interface::operator=(), and Interface::ready().
Cantera::XML_Node* m_r protected
XML_Node pointer to the XML File object that contains the Surface and the Interfacial Reaction object description.
Definition at line 116 of file Interface.h.
Referenced by Interface::Interface(), and Interface::operator=().
doublereal m_n0 protected inherited
Surface site density (kmol m-2)
Definition at line 638 of file SurfPhase.h.
Referenced by SurfPhase::enthalpy_mole(), SurfPhase::getCoverages(), SurfPhase::operator=(), SurfPhase::setCoverages(), SurfPhase::setCoveragesNoNorm(), SurfPhase::setParameters(), EdgePhase::setParametersFromXML(), SurfPhase::setParametersFromXML(), SurfPhase::siteDensity(), and SurfPhase::standardConcentration().
doublereal m_logn0 protected inherited
log of the surface site density
Definition at line 641 of file SurfPhase.h.
Referenced by SurfPhase::logStandardConc(), SurfPhase::operator=(), SurfPhase::setParameters(), EdgePhase::setParametersFromXML(), SurfPhase::setParametersFromXML(), and SurfPhase::SurfPhase().
doublereal m_tmin protected inherited
Minimum temperature for valid species standard state thermo props.
This is the minimum temperature at which all species have valid standard state thermo props defined.
Definition at line 648 of file SurfPhase.h.
Referenced by SurfPhase::operator=().
doublereal m_tmax protected inherited
Maximum temperature for valid species standard state thermo props.
This is the maximum temperature at which all species have valid standard state thermo props defined.
Definition at line 655 of file SurfPhase.h.
Referenced by SurfPhase::operator=().
doublereal m_press protected inherited
Current value of the pressure (Pa)
Definition at line 658 of file SurfPhase.h.
Referenced by SurfPhase::operator=(), SurfPhase::pressure(), and SurfPhase::setPressure().
doublereal m_tlast mutable protected inherited
Current value of the temperature (Kelvin)
Definition at line 661 of file SurfPhase.h.
Referenced by SurfPhase::_updateThermo(), and SurfPhase::operator=().
vector_fp m_h0 mutable protected inherited
Temporary storage for the reference state enthalpies.
Definition at line 664 of file SurfPhase.h.
Referenced by SurfPhase::_updateThermo(), SurfPhase::enthalpy_mole(), SurfPhase::getEnthalpy_RT(), SurfPhase::initThermo(), and SurfPhase::operator=().
vector_fp m_s0 mutable protected inherited
Temporary storage for the reference state entropies.
Definition at line 667 of file SurfPhase.h.
Referenced by SurfPhase::_updateThermo(), SurfPhase::getEntropy_R(), SurfPhase::initThermo(), and SurfPhase::operator=().
vector_fp m_cp0 mutable protected inherited
Temporary storage for the reference state heat capacities.
Definition at line 670 of file SurfPhase.h.
Referenced by SurfPhase::_updateThermo(), SurfPhase::getCp_R(), SurfPhase::initThermo(), and SurfPhase::operator=().
vector_fp m_mu0 mutable protected inherited
Temporary storage for the reference state gibbs energies.
Definition at line 673 of file SurfPhase.h.
Referenced by SurfPhase::_updateThermo(), SurfPhase::getChemPotentials(), SurfPhase::getGibbs_RT(), SurfPhase::getStandardChemPotentials(), SurfPhase::initThermo(), and SurfPhase::operator=().
vector_fp m_work mutable protected inherited
Temporary work array.
Definition at line 676 of file SurfPhase.h.
Referenced by SurfPhase::getChemPotentials(), SurfPhase::initThermo(), SurfPhase::operator=(), SurfPhase::setCoverages(), and SurfPhase::setCoveragesNoNorm().
vector_fp m_pe mutable protected inherited
Potential energy of each species in the surface phase.
Todo:
Fix potential energy Note, the potential energy terms seem to be orphaned at the moment. They are not connected to the Gibbs free energy calculation in this object
Deprecated:
Definition at line 687 of file SurfPhase.h.
Referenced by SurfPhase::initThermo(), SurfPhase::operator=(), SurfPhase::potentialEnergy(), and SurfPhase::setPotentialEnergy().
vector_fp m_logsize mutable protected inherited
vector storing the log of the size of each species.
The size of each species is defined as the number of surface sites each species occupies.
Definition at line 694 of file SurfPhase.h.
Referenced by SurfPhase::initThermo(), SurfPhase::logStandardConc(), and SurfPhase::operator=().
SpeciesThermo* m_spthermo protected inherited
Pointer to the calculation manager for species reference-state thermodynamic properties.
This class is called when the reference-state thermodynamic properties of all the species in the phase needs to be evaluated.
Definition at line 1611 of file ThermoPhase.h.
Referenced by MixtureFugacityTP::_updateReferenceStateThermo(), ConstDensityThermo::_updateThermo(), SurfPhase::_updateThermo(), SingleSpeciesTP::_updateThermo(), IdealGasPhase::_updateThermo(), LatticePhase::_updateThermo(), IdealSolidSolnPhase::_updateThermo(), ConstDensityThermo::enthalpy_mole(), LatticePhase::enthalpy_mole(), RedlichKwongMFTP::entropy_mole(), IdealGasPhase::entropy_mole(), FixedChemPotSSTP::FixedChemPotSSTP(), ConstDensityThermo::getChemPotentials(), MixtureFugacityTP::getEntropy_R(), IdealGasPhase::getEntropy_R(), PureFluidPhase::getEntropy_R_ref(), MixtureFugacityTP::getGibbs_RT(), IdealGasPhase::getGibbs_RT(), PureFluidPhase::getGibbs_RT_ref(), IdealGasPhase::getPartialMolarEntropies(), MixtureFugacityTP::getPureGibbs(), IdealGasPhase::getPureGibbs(), MixtureFugacityTP::getStandardChemPotentials(), IdealGasPhase::getStandardChemPotentials(), IdealSolidSolnPhase::initLengths(), ConstDensityThermo::initThermo(), StoichSubstance::initThermo(), StoichSubstanceSSTP::initThermo(), PureFluidPhase::initThermo(), SingleSpeciesTP::initThermo(), IdealGasPhase::initThermo(), LatticePhase::initThermo(), WaterSSTP::initThermoXML(), LatticeSolidPhase::installSlavePhases(), ConstDensityThermo::intEnergy_mole(), LatticePhase::intEnergy_mole(), ThermoPhase::maxTemp(), ThermoPhase::minTemp(), VPStandardStateTP::operator=(), ThermoPhase::operator=(), ThermoPhase::refPressure(), ThermoPhase::setSpeciesThermo(), LatticeSolidPhase::speciesThermo(), ThermoPhase::speciesThermo(), and ThermoPhase::~ThermoPhase().
std::vector<const XML_Node*> m_speciesData protected inherited
Vector of pointers to the species databases.
This is used to access data needed to construct the transport manager and other properties later in the initialization process. We create a copy of the XML_Node data read in here. Therefore, we own this data.
Definition at line 1621 of file ThermoPhase.h.
Referenced by LatticeSolidPhase::installSlavePhases(), ThermoPhase::operator=(), ThermoPhase::saveSpeciesData(), ThermoPhase::speciesData(), and ThermoPhase::~ThermoPhase().
doublereal m_phi protected inherited
Stored value of the electric potential for this phase.
Units are Volts
Definition at line 1627 of file ThermoPhase.h.
Referenced by ThermoPhase::electricPotential(), IdealMolalSoln::electricPotential(), ThermoPhase::operator=(), and ThermoPhase::setElectricPotential().
vector_fp m_lambdaRRT protected inherited
Vector of element potentials.
-> length equal to number of elements
Definition at line 1631 of file ThermoPhase.h.
Referenced by ThermoPhase::getElementPotentials(), ThermoPhase::operator=(), and ThermoPhase::setElementPotentials().
bool m_hasElementPotentials protected inherited
Boolean indicating whether there is a valid set of saved element potentials for this phase.
Definition at line 1635 of file ThermoPhase.h.
Referenced by ThermoPhase::getElementPotentials(), ThermoPhase::operator=(), and ThermoPhase::setElementPotentials().
bool m_chargeNeutralityNecessary protected inherited
Boolean indicating whether a charge neutrality condition is a necessity.
Note, the charge neutrality condition is not a necessity for ideal gas phases. There may be a net charge in those phases, because the NASA polynomials for ionized species in Ideal gases take this condition into account. However, liquid phases usually require charge neutrality in order for their derived thermodynamics to be valid.
Definition at line 1645 of file ThermoPhase.h.
Referenced by ThermoPhase::chargeNeutralityNecessary(), MolalityVPSSTP::MolalityVPSSTP(), and ThermoPhase::operator=().
int m_ssConvention protected inherited
Contains the standard state convention.
Definition at line 1648 of file ThermoPhase.h.
Referenced by ThermoPhase::operator=(), and ThermoPhase::standardStateConvention().
std::vector<doublereal> xMol_Ref protected inherited
Reference Mole Fraction Composition.
Occasionally, the need arises to find a safe mole fraction vector to initialize the object to. This contains such a vector. The algorithm will pick up the mole fraction vector that is applied from the state xml file in the input file
Definition at line 1657 of file ThermoPhase.h.
Referenced by ThermoPhase::getReferenceComposition(), ThermoPhase::initThermo(), and ThermoPhase::setReferenceComposition().
size_t m_kk protected inherited
Number of species in the phase.
Definition at line 727 of file Phase.h.
Referenced by DebyeHuckel::_lnactivityWaterHelgesonFixedForm(), MixtureFugacityTP::_updateReferenceStateThermo(), ConstDensityThermo::_updateThermo(), SurfPhase::_updateThermo(), IdealGasPhase::_updateThermo(), LatticePhase::_updateThermo(), IdealSolidSolnPhase::_updateThermo(), Phase::addUniqueElementAfterFreeze(), Phase::addUniqueSpecies(), HMWSoln::applyphScale(), RedlichKwongMFTP::applyStandardMixingRules(), GibbsExcessVPSSTP::calcDensity(), IdealMolalSoln::calcDensity(), DebyeHuckel::calcDensity(), HMWSoln::calcDensity(), IonsFromNeutralVPSSTP::calcIonMoleFractions(), MolalityVPSSTP::calcMolalities(), HMWSoln::calcMolalitiesCropped(), IonsFromNeutralVPSSTP::calcNeutralMoleculeMoleFractions(), PseudoBinaryVPSSTP::calcPseudoBinaryMoleFractions(), MolarityIonicVPSSTP::calcPseudoBinaryMoleFractions(), RedlichKwongMFTP::calculateAB(), GibbsExcessVPSSTP::checkMFSum(), Phase::checkSpeciesArraySize(), Phase::checkSpeciesIndex(), HMWSoln::counterIJ_setup(), RedlichKwongMFTP::critDensity(), RedlichKwongMFTP::critPressure(), RedlichKwongMFTP::critTemperature(), ConstDensityThermo::expGibbs_RT(), IdealGasPhase::expGibbs_RT_ref(), IdealSolidSolnPhase::expGibbs_RT_ref(), MolalityVPSSTP::findCLMIndex(), GibbsExcessVPSSTP::getActivities(), IdealMolalSoln::getActivities(), DebyeHuckel::getActivities(), HMWSoln::getActivities(), ConstDensityThermo::getActivityCoefficients(), SingleSpeciesTP::getActivityCoefficients(), IdealSolnGasVPSS::getActivityCoefficients(), IonsFromNeutralVPSSTP::getActivityCoefficients(), GibbsExcessVPSSTP::getActivityCoefficients(), RedlichKwongMFTP::getActivityCoefficients(), LatticeSolidPhase::getActivityCoefficients(), MixedSolventElectrolyte::getActivityCoefficients(), PhaseCombo_Interaction::getActivityCoefficients(), IdealSolidSolnPhase::getActivityCoefficients(), ThermoPhase::getActivityCoefficients(), MolalityVPSSTP::getActivityCoefficients(), IdealGasPhase::getActivityCoefficients(), LatticePhase::getActivityCoefficients(), IdealSolnGasVPSS::getActivityConcentrations(), RedlichKwongMFTP::getActivityConcentrations(), IdealMolalSoln::getActivityConcentrations(), IdealSolidSolnPhase::getActivityConcentrations(), DebyeHuckel::getActivityConcentrations(), HMWSoln::getActivityConcentrations(), ConstDensityThermo::getChemPotentials(), SurfPhase::getChemPotentials(), MolarityIonicVPSSTP::getChemPotentials(), IdealSolnGasVPSS::getChemPotentials(), RedlichKwongMFTP::getChemPotentials(), RedlichKisterVPSSTP::getChemPotentials(), MargulesVPSSTP::getChemPotentials(), MixedSolventElectrolyte::getChemPotentials(), PhaseCombo_Interaction::getChemPotentials(), IdealSolidSolnPhase::getChemPotentials(), IdealMolalSoln::getChemPotentials(), IdealGasPhase::getChemPotentials(), LatticePhase::getChemPotentials(), DebyeHuckel::getChemPotentials(), HMWSoln::getChemPotentials(), VPStandardStateTP::getChemPotentials_RT(), MixtureFugacityTP::getChemPotentials_RT(), IdealSolnGasVPSS::getChemPotentials_RT(), RedlichKwongMFTP::getChemPotentials_RT(), IdealSolidSolnPhase::getChemPotentials_RT(), SurfPhase::getCoverages(), IdealSolidSolnPhase::getCp_R_ref(), RedlichKisterVPSSTP::getd2lnActCoeffdT2(), MargulesVPSSTP::getd2lnActCoeffdT2(), MixedSolventElectrolyte::getd2lnActCoeffdT2(), PhaseCombo_Interaction::getd2lnActCoeffdT2(), IonsFromNeutralVPSSTP::getdlnActCoeffdlnN(), PhaseCombo_Interaction::getdlnActCoeffdlnN(), RedlichKisterVPSSTP::getdlnActCoeffdlnN(), MargulesVPSSTP::getdlnActCoeffdlnN(), MixedSolventElectrolyte::getdlnActCoeffdlnN(), ThermoPhase::getdlnActCoeffdlnN(), IonsFromNeutralVPSSTP::getdlnActCoeffdlnN_diag(), PhaseCombo_Interaction::getdlnActCoeffdlnN_diag(), RedlichKisterVPSSTP::getdlnActCoeffdlnN_diag(), MargulesVPSSTP::getdlnActCoeffdlnN_diag(), MixedSolventElectrolyte::getdlnActCoeffdlnN_diag(), IonsFromNeutralVPSSTP::getdlnActCoeffdlnX_diag(), PhaseCombo_Interaction::getdlnActCoeffdlnX_diag(), RedlichKisterVPSSTP::getdlnActCoeffdlnX_diag(), MargulesVPSSTP::getdlnActCoeffdlnX_diag(), MixedSolventElectrolyte::getdlnActCoeffdlnX_diag(), IonsFromNeutralVPSSTP::getdlnActCoeffds(), PhaseCombo_Interaction::getdlnActCoeffds(), RedlichKisterVPSSTP::getdlnActCoeffds(), MargulesVPSSTP::getdlnActCoeffds(), MixedSolventElectrolyte::getdlnActCoeffds(), RedlichKisterVPSSTP::getdlnActCoeffdT(), MargulesVPSSTP::getdlnActCoeffdT(), MixedSolventElectrolyte::getdlnActCoeffdT(), PhaseCombo_Interaction::getdlnActCoeffdT(), PureFluidPhase::getElectrochemPotentials(), PseudoBinaryVPSSTP::getElectrochemPotentials(), MolarityIonicVPSSTP::getElectrochemPotentials(), GibbsExcessVPSSTP::getElectrochemPotentials(), RedlichKisterVPSSTP::getElectrochemPotentials(), MargulesVPSSTP::getElectrochemPotentials(), ThermoPhase::getElectrochemPotentials(), MixedSolventElectrolyte::getElectrochemPotentials(), MolalityVPSSTP::getElectrochemPotentials(), PhaseCombo_Interaction::getElectrochemPotentials(), IdealSolidSolnPhase::getEnthalpy_RT(), LatticePhase::getEnthalpy_RT(), IdealSolidSolnPhase::getEnthalpy_RT_ref(), MixtureFugacityTP::getEntropy_R(), IdealGasPhase::getEntropy_R(), IdealSolidSolnPhase::getEntropy_R_ref(), WaterSSTP::getGibbs_ref(), LatticeSolidPhase::getGibbs_ref(), IdealSolidSolnPhase::getGibbs_ref(), LatticePhase::getGibbs_ref(), MixtureFugacityTP::getGibbs_RT(), IdealGasPhase::getGibbs_RT(), IdealSolidSolnPhase::getGibbs_RT(), LatticePhase::getGibbs_RT(), IdealSolidSolnPhase::getGibbs_RT_ref(), LatticePhase::getGibbs_RT_ref(), MixtureFugacityTP::getIntEnergy_RT(), IdealGasPhase::getIntEnergy_RT(), IdealSolidSolnPhase::getIntEnergy_RT(), IdealGasPhase::getIntEnergy_RT_ref(), IdealSolidSolnPhase::getIntEnergy_RT_ref(), MolarityIonicVPSSTP::getLnActivityCoefficients(), RedlichKisterVPSSTP::getLnActivityCoefficients(), MargulesVPSSTP::getLnActivityCoefficients(), ThermoPhase::getLnActivityCoefficients(), MolalityVPSSTP::getMolalities(), IdealMolalSoln::getMolalityActivityCoefficients(), DebyeHuckel::getMolalityActivityCoefficients(), IonsFromNeutralVPSSTP::getNeutralMoleculeMoleGrads(), SurfPhase::getPartialMolarCp(), IdealSolnGasVPSS::getPartialMolarCp(), MolarityIonicVPSSTP::getPartialMolarCp(), RedlichKwongMFTP::getPartialMolarCp(), RedlichKisterVPSSTP::getPartialMolarCp(), MargulesVPSSTP::getPartialMolarCp(), MixedSolventElectrolyte::getPartialMolarCp(), PhaseCombo_Interaction::getPartialMolarCp(), IdealSolidSolnPhase::getPartialMolarCp(), IdealMolalSoln::getPartialMolarCp(), LatticePhase::getPartialMolarCp(), DebyeHuckel::getPartialMolarCp(), HMWSoln::getPartialMolarCp(), SurfPhase::getPartialMolarEnthalpies(), IdealSolnGasVPSS::getPartialMolarEnthalpies(), MolarityIonicVPSSTP::getPartialMolarEnthalpies(), IonsFromNeutralVPSSTP::getPartialMolarEnthalpies(), RedlichKwongMFTP::getPartialMolarEnthalpies(), RedlichKisterVPSSTP::getPartialMolarEnthalpies(), MargulesVPSSTP::getPartialMolarEnthalpies(), MixedSolventElectrolyte::getPartialMolarEnthalpies(), PhaseCombo_Interaction::getPartialMolarEnthalpies(), IdealMolalSoln::getPartialMolarEnthalpies(), DebyeHuckel::getPartialMolarEnthalpies(), HMWSoln::getPartialMolarEnthalpies(), SurfPhase::getPartialMolarEntropies(), IdealSolnGasVPSS::getPartialMolarEntropies(), MolarityIonicVPSSTP::getPartialMolarEntropies(), IonsFromNeutralVPSSTP::getPartialMolarEntropies(), RedlichKwongMFTP::getPartialMolarEntropies(), RedlichKisterVPSSTP::getPartialMolarEntropies(), MargulesVPSSTP::getPartialMolarEntropies(), MixedSolventElectrolyte::getPartialMolarEntropies(), PhaseCombo_Interaction::getPartialMolarEntropies(), IdealGasPhase::getPartialMolarEntropies(), IdealMolalSoln::getPartialMolarEntropies(), IdealSolidSolnPhase::getPartialMolarEntropies(), LatticePhase::getPartialMolarEntropies(), DebyeHuckel::getPartialMolarEntropies(), HMWSoln::getPartialMolarEntropies(), IdealSolnGasVPSS::getPartialMolarIntEnergies(), RedlichKwongMFTP::getPartialMolarIntEnergies(), IdealGasPhase::getPartialMolarIntEnergies(), MolarityIonicVPSSTP::getPartialMolarVolumes(), RedlichKwongMFTP::getPartialMolarVolumes(), RedlichKisterVPSSTP::getPartialMolarVolumes(), MargulesVPSSTP::getPartialMolarVolumes(), MixedSolventElectrolyte::getPartialMolarVolumes(), IdealGasPhase::getPartialMolarVolumes(), PhaseCombo_Interaction::getPartialMolarVolumes(), DebyeHuckel::getPartialMolarVolumes(), HMWSoln::getPartialMolarVolumes(), MixtureFugacityTP::getPureGibbs(), IdealGasPhase::getPureGibbs(), LatticePhase::getPureGibbs(), IdealSolidSolnPhase::getPureGibbs(), ThermoPhase::getReferenceComposition(), VPStandardStateTP::getStandardChemPotentials(), MixtureFugacityTP::getStandardChemPotentials(), IdealGasPhase::getStandardChemPotentials(), MixtureFugacityTP::getStandardVolumes(), SurfPhase::getStandardVolumes(), IdealGasPhase::getStandardVolumes(), MixtureFugacityTP::getStandardVolumes_ref(), IdealGasPhase::getStandardVolumes_ref(), HMWSoln::getUnscaledMolalityActivityCoefficients(), HMWSoln::HMWSoln(), Phase::init(), PseudoBinaryVPSSTP::initLengths(), IdealSolnGasVPSS::initLengths(), MolarityIonicVPSSTP::initLengths(), GibbsExcessVPSSTP::initLengths(), RedlichKwongMFTP::initLengths(), VPStandardStateTP::initLengths(), LatticeSolidPhase::initLengths(), IonsFromNeutralVPSSTP::initLengths(), MixtureFugacityTP::initLengths(), PhaseCombo_Interaction::initLengths(), RedlichKisterVPSSTP::initLengths(), MargulesVPSSTP::initLengths(), MixedSolventElectrolyte::initLengths(), MolalityVPSSTP::initLengths(), IdealMolalSoln::initLengths(), IdealSolidSolnPhase::initLengths(), DebyeHuckel::initLengths(), HMWSoln::initLengths(), ConstDensityThermo::initThermo(), SurfPhase::initThermo(), MolarityIonicVPSSTP::initThermo(), StoichSubstanceSSTP::initThermo(), VPStandardStateTP::initThermo(), LatticeSolidPhase::initThermo(), SingleSpeciesTP::initThermo(), IdealGasPhase::initThermo(), LatticePhase::initThermo(), ThermoPhase::initThermo(), RedlichKwongMFTP::initThermoXML(), VPStandardStateTP::initThermoXML(), IonsFromNeutralVPSSTP::initThermoXML(), IdealMolalSoln::initThermoXML(), LatticePhase::initThermoXML(), IdealSolidSolnPhase::initThermoXML(), DebyeHuckel::initThermoXML(), IdealSolidSolnPhase::logStandardConc(), Phase::nSpecies(), VPStandardStateTP::operator=(), Phase::operator=(), ThermoPhase::operator=(), MolalityVPSSTP::osmoticCoefficient(), HMWSoln::printCoeffs(), RedlichKwongMFTP::readXMLCrossFluid(), RedlichKwongMFTP::readXMLPureFluid(), IdealSolidSolnPhase::referenceConcentration(), HMWSoln::relative_enthalpy(), HMWSoln::relative_molal_enthalpy(), DebyeHuckel::s_update_d2lnMolalityActCoeff_dT2(), HMWSoln::s_update_d2lnMolalityActCoeff_dT2(), IonsFromNeutralVPSSTP::s_update_dlnActCoeff_dlnN(), PhaseCombo_Interaction::s_update_dlnActCoeff_dlnN(), MargulesVPSSTP::s_update_dlnActCoeff_dlnN(), MixedSolventElectrolyte::s_update_dlnActCoeff_dlnN(), IonsFromNeutralVPSSTP::s_update_dlnActCoeff_dlnN_diag(), PhaseCombo_Interaction::s_update_dlnActCoeff_dlnN_diag(), MargulesVPSSTP::s_update_dlnActCoeff_dlnN_diag(), MixedSolventElectrolyte::s_update_dlnActCoeff_dlnN_diag(), IonsFromNeutralVPSSTP::s_update_dlnActCoeff_dlnX_diag(), PhaseCombo_Interaction::s_update_dlnActCoeff_dlnX_diag(), MargulesVPSSTP::s_update_dlnActCoeff_dlnX_diag(), MixedSolventElectrolyte::s_update_dlnActCoeff_dlnX_diag(), PhaseCombo_Interaction::s_update_dlnActCoeff_dT(), RedlichKisterVPSSTP::s_update_dlnActCoeff_dT(), MargulesVPSSTP::s_update_dlnActCoeff_dT(), MixedSolventElectrolyte::s_update_dlnActCoeff_dT(), RedlichKisterVPSSTP::s_update_dlnActCoeff_dX_(), IonsFromNeutralVPSSTP::s_update_dlnActCoeffdT(), DebyeHuckel::s_update_dlnMolalityActCoeff_dP(), HMWSoln::s_update_dlnMolalityActCoeff_dP(), DebyeHuckel::s_update_dlnMolalityActCoeff_dT(), HMWSoln::s_update_dlnMolalityActCoeff_dT(), MolarityIonicVPSSTP::s_update_lnActCoeff(), IonsFromNeutralVPSSTP::s_update_lnActCoeff(), PhaseCombo_Interaction::s_update_lnActCoeff(), RedlichKisterVPSSTP::s_update_lnActCoeff(), MargulesVPSSTP::s_update_lnActCoeff(), MixedSolventElectrolyte::s_update_lnActCoeff(), DebyeHuckel::s_update_lnMolalityActCoeff(), HMWSoln::s_update_lnMolalityActCoeff(), IdealMolalSoln::s_updateIMS_lnMolalityActCoeff(), HMWSoln::s_updateIMS_lnMolalityActCoeff(), HMWSoln::s_updatePitzer_CoeffWRTemp(), HMWSoln::s_updatePitzer_d2lnMolalityActCoeff_dT2(), HMWSoln::s_updatePitzer_dlnMolalityActCoeff_dP(), HMWSoln::s_updatePitzer_dlnMolalityActCoeff_dT(), HMWSoln::s_updatePitzer_lnMolalityActCoeff(), HMWSoln::s_updateScaling_pHScaling(), HMWSoln::s_updateScaling_pHScaling_dP(), HMWSoln::s_updateScaling_pHScaling_dT(), HMWSoln::s_updateScaling_pHScaling_dT2(), Phase::setConcentrations(), SurfPhase::setCoverages(), SurfPhase::setCoveragesNoNorm(), Phase::setMassFractions(), Phase::setMassFractions_NoNorm(), MolalityVPSSTP::setMolalities(), Phase::setMoleFractions(), Phase::setMoleFractions_NoNorm(), ThermoPhase::setReferenceComposition(), MolalityVPSSTP::setSolvent(), IdealSolnGasVPSS::setToEquilState(), RedlichKwongMFTP::setToEquilState(), IdealGasPhase::setToEquilState(), IdealSolidSolnPhase::setToEquilState(), ThermoPhase::speciesData(), Phase::speciesIndex(), IdealSolidSolnPhase::standardConcentration(), RedlichKwongMFTP::updateAB(), and ThermoPhase::~ThermoPhase().
size_t m_ndim protected inherited
Dimensionality of the phase.
Volumetric phases have dimensionality 3 and surface phases have dimensionality 2.
Definition at line 731 of file Phase.h.
Referenced by Phase::nDim(), Phase::operator=(), and Phase::setNDim().
vector_fp m_speciesComp protected inherited
Atomic composition of the species.
The number of atoms of element i in species k is equal to m_speciesComp[k * m_mm + i] The length of this vector is equal to m_kk * m_mm
Definition at line 736 of file Phase.h.
Referenced by Phase::addUniqueElementAfterFreeze(), Phase::addUniqueSpecies(), Phase::getAtoms(), LatticeSolidPhase::installSlavePhases(), Phase::nAtoms(), and Phase::operator=().
vector_fp m_speciesSize protected inherited
Vector of species sizes.
length m_kk. Used in some equations of state which employ the constant partial molar volume approximation.
Definition at line 740 of file Phase.h.
Referenced by Phase::addUniqueSpecies(), DebyeHuckel::initLengths(), HMWSoln::initLengths(), MineralEQ3::initThermoXML(), DebyeHuckel::initThermoXML(), Phase::operator=(), Phase::size(), HMWSoln::speciesMolarVolume(), and DebyeHuckel::standardConcentration().
vector_fp m_speciesCharge protected inherited
Vector of species charges. length m_kk.
Definition at line 742 of file Phase.h.
Referenced by Phase::addUniqueSpecies(), HMWSoln::applyphScale(), HMWSoln::calcMolalitiesCropped(), MolarityIonicVPSSTP::calcPseudoBinaryMoleFractions(), Phase::charge(), IonsFromNeutralVPSSTP::getDissociationCoeffs(), MolarityIonicVPSSTP::initThermo(), DebyeHuckel::initThermoXML(), Phase::operator=(), HMWSoln::printCoeffs(), PhaseCombo_Interaction::readXMLBinarySpecies(), RedlichKisterVPSSTP::readXMLBinarySpecies(), MargulesVPSSTP::readXMLBinarySpecies(), MixedSolventElectrolyte::readXMLBinarySpecies(), HMWSoln::relative_molal_enthalpy(), DebyeHuckel::s_update_d2lnMolalityActCoeff_dT2(), DebyeHuckel::s_update_dlnMolalityActCoeff_dP(), DebyeHuckel::s_update_dlnMolalityActCoeff_dT(), DebyeHuckel::s_update_lnMolalityActCoeff(), HMWSoln::s_update_lnMolalityActCoeff(), HMWSoln::s_updatePitzer_CoeffWRTemp(), HMWSoln::s_updatePitzer_d2lnMolalityActCoeff_dT2(), HMWSoln::s_updatePitzer_dlnMolalityActCoeff_dP(), HMWSoln::s_updatePitzer_dlnMolalityActCoeff_dT(), HMWSoln::s_updatePitzer_lnMolalityActCoeff(), HMWSoln::s_updateScaling_pHScaling(), HMWSoln::s_updateScaling_pHScaling_dP(), HMWSoln::s_updateScaling_pHScaling_dT(), and HMWSoln::s_updateScaling_pHScaling_dT2().
vector_fp m_grt protected inherited
Temporary work vector of length m_kk.
Definition at line 647 of file InterfaceKinetics.h.
Referenced by InterfaceKinetics::getDeltaElectrochemPotentials(), InterfaceKinetics::getDeltaEnthalpy(), InterfaceKinetics::getDeltaEntropy(), InterfaceKinetics::getDeltaGibbs(), InterfaceKinetics::getDeltaSSEnthalpy(), InterfaceKinetics::getDeltaSSEntropy(), InterfaceKinetics::getDeltaSSGibbs(), InterfaceKinetics::init(), and InterfaceKinetics::operator=().
std::vector<size_t> m_revindex protected inherited
List of reactions numbers which are reversible reactions.
This is a vector of reaction numbers. Each reaction in the list is reversible. Length = number of reversible reactions
Definition at line 655 of file InterfaceKinetics.h.
Referenced by InterfaceKinetics::isReversible(), InterfaceKinetics::operator=(), and InterfaceKinetics::updateKc().
Rate1<SurfaceArrhenius> m_rates protected inherited
Templated class containing the vector of reactions for this interface.
The templated class is described in RateCoeffMgr.h The class SurfaceArrhenius is described in RxnRates.h
Definition at line 662 of file InterfaceKinetics.h.
Referenced by InterfaceKinetics::_update_rates_T(), and InterfaceKinetics::operator=().
std::map<size_t, std::pair<int, size_t> > m_index mutable protected inherited
Vector of information about reactions in the mechanism.
The key is the reaction index (0 < i < m_ii). The first pair is the reactionType of the reaction. The second pair is ...
Definition at line 673 of file InterfaceKinetics.h.
Referenced by InterfaceKinetics::operator=(), InterfaceKinetics::reactionType(), and InterfaceKinetics::registerReaction().
std::vector<size_t> m_irrev protected inherited
Vector of irreversible reaction numbers.
vector containing the reaction numbers of irreversible reactions.
Definition at line 680 of file InterfaceKinetics.h.
Referenced by InterfaceKinetics::operator=(), and InterfaceKinetics::updateKc().
ReactionStoichMgr m_rxnstoich protected inherited
Stoichiometric manager for the reaction mechanism.
This is the manager for the kinetics mechanism that handles turning reaction extents into species production rates and also handles turning thermo properties into reaction thermo properties.
Definition at line 689 of file InterfaceKinetics.h.
Referenced by InterfaceKinetics::applyButlerVolmerCorrection(), InterfaceKinetics::getCreationRates(), InterfaceKinetics::getDeltaElectrochemPotentials(), InterfaceKinetics::getDeltaEnthalpy(), InterfaceKinetics::getDeltaEntropy(), InterfaceKinetics::getDeltaGibbs(), InterfaceKinetics::getDeltaSSEnthalpy(), InterfaceKinetics::getDeltaSSEntropy(), InterfaceKinetics::getDeltaSSGibbs(), InterfaceKinetics::getDestructionRates(), InterfaceKinetics::getEquilibriumConstants(), InterfaceKinetics::getNetProductionRates(), InterfaceKinetics::operator=(), InterfaceKinetics::updateKc(), and InterfaceKinetics::updateROP().
size_t m_nirrev protected inherited
Number of irreversible reactions in the mechanism.
Definition at line 692 of file InterfaceKinetics.h.
Referenced by InterfaceKinetics::operator=(), and InterfaceKinetics::updateKc().
size_t m_nrev protected inherited
Number of reversible reactions in the mechanism.
Definition at line 695 of file InterfaceKinetics.h.
Referenced by InterfaceKinetics::operator=(), and InterfaceKinetics::updateKc().
std::vector<std::map<size_t, doublereal> > m_rrxn mutable protected inherited
m_rrxn is a vector of maps, containing the reactant stoichiometric coefficient information
m_rrxn has a length equal to the total number of species in the kinetics object. For each species, there exists a map, with the reaction number being the key, and the reactant stoichiometric coefficient for the species being the value. HKM -> mutable because search sometimes creates extra entries. To be fixed in future...
Definition at line 709 of file InterfaceKinetics.h.
Referenced by InterfaceKinetics::init(), InterfaceKinetics::operator=(), and InterfaceKinetics::reactantStoichCoeff().
std::vector<std::map<size_t, doublereal> > m_prxn mutable protected inherited
m_prxn is a vector of maps, containing the reactant stoichiometric coefficient information
m_prxn is a vector of maps. m_prxn has a length equal to the total number of species in the kinetics object. For each species, there exists a map, with the reaction number being the key, and the product stoichiometric coefficient for the species being the value.
Definition at line 720 of file InterfaceKinetics.h.
Referenced by InterfaceKinetics::init(), InterfaceKinetics::operator=(), and InterfaceKinetics::productStoichCoeff().
std::vector<std::string> m_rxneqn protected inherited
String expression for each rxn.
Vector of strings of length m_ii, the number of reactions, containing the string expressions for each reaction (e.g., reactants <=> product1 + product2)
Definition at line 729 of file InterfaceKinetics.h.
Referenced by InterfaceKinetics::addReaction(), InterfaceKinetics::operator=(), and InterfaceKinetics::reactionString().
InterfaceKineticsData* m_kdata protected inherited
Temporary data storage used in calculating the rates of of reactions.
Definition at line 735 of file InterfaceKinetics.h.
Referenced by InterfaceKinetics::_update_rates_C(), InterfaceKinetics::_update_rates_T(), InterfaceKinetics::getCreationRates(), InterfaceKinetics::getDestructionRates(), InterfaceKinetics::getFwdRateConstants(), InterfaceKinetics::getFwdRatesOfProgress(), InterfaceKinetics::getNetProductionRates(), InterfaceKinetics::getNetRatesOfProgress(), InterfaceKinetics::getRevRateConstants(), InterfaceKinetics::getRevRatesOfProgress(), InterfaceKinetics::InterfaceKinetics(), InterfaceKinetics::operator=(), InterfaceKinetics::updateKc(), InterfaceKinetics::updateROP(), and InterfaceKinetics::~InterfaceKinetics().
vector_fp m_conc protected inherited
an array of generalized concentrations for each species
An array of generalized concentrations \(C_k \) that are defined such that \(a_k = C_k / C^0_k, \) where \(C^0_k \) is a standard concentration/ These generalized concentrations are used by this kinetics manager class to compute the forward and reverse rates of elementary reactions. The "units" for the concentrations of each phase depend upon the implementation of kinetics within that phase. The order of the species within the vector is based on the order of listed ThermoPhase objects in the class, and the order of the species within each ThermoPhase class.
Definition at line 751 of file InterfaceKinetics.h.
Referenced by InterfaceKinetics::_update_rates_C(), InterfaceKinetics::_update_rates_T(), InterfaceKinetics::getActivityConcentrations(), InterfaceKinetics::init(), InterfaceKinetics::operator=(), and InterfaceKinetics::updateROP().
vector_fp m_mu0 protected inherited
Vector of standard state chemical potentials.
This vector contains a temporary vector of standard state chemical potentials for all of the species in the kinetics object
Length = m_k units = J/kmol
Definition at line 762 of file InterfaceKinetics.h.
Referenced by InterfaceKinetics::getEquilibriumConstants(), InterfaceKinetics::init(), InterfaceKinetics::operator=(), and InterfaceKinetics::updateKc().
vector_fp m_phi protected inherited
Vector of phase electric potentials.
Temporary vector containing the potential of each phase in the kinetics object
length = number of phases units = Volts
Definition at line 772 of file InterfaceKinetics.h.
Referenced by InterfaceKinetics::_update_rates_phi(), InterfaceKinetics::applyButlerVolmerCorrection(), InterfaceKinetics::getEquilibriumConstants(), InterfaceKinetics::init(), InterfaceKinetics::operator=(), and InterfaceKinetics::updateKc().
vector_fp m_pot protected inherited
Vector of potential energies due to Voltages.
Length is the number of species in kinetics mech. It's used to store the potential energy due to the voltage.
Definition at line 779 of file InterfaceKinetics.h.
Referenced by InterfaceKinetics::applyButlerVolmerCorrection(), InterfaceKinetics::init(), and InterfaceKinetics::operator=().
vector_fp m_rwork protected inherited
Vector temporary.
Length is number of reactions. It's used to store the voltage contribution to the activation energy.
Definition at line 786 of file InterfaceKinetics.h.
Referenced by InterfaceKinetics::applyButlerVolmerCorrection(), EdgeKinetics::finalize(), InterfaceKinetics::finalize(), and InterfaceKinetics::operator=().
vector_fp m_E protected inherited
Vector of raw activation energies for the reactions.
units are in Kelvin Length is number of reactions.
Definition at line 793 of file InterfaceKinetics.h.
Referenced by InterfaceKinetics::applyButlerVolmerCorrection(), InterfaceKinetics::getActivationEnergies(), and InterfaceKinetics::operator=().
SurfPhase* m_surf protected inherited
Pointer to the single surface phase.
Definition at line 796 of file InterfaceKinetics.h.
Referenced by InterfaceKinetics::_update_rates_T(), EdgeKinetics::finalize(), InterfaceKinetics::finalize(), and InterfaceKinetics::operator=().
ImplicitSurfChem* m_integrator protected inherited
Pointer to the Implicit surface chemistry object.
Note this object is owned by this InterfaceKinetics object. It may only be used to solve this single InterfaceKinetics objects's surface problem uncoupled from other surface phases.
Definition at line 805 of file InterfaceKinetics.h.
Referenced by InterfaceKinetics::advanceCoverages(), InterfaceKinetics::operator=(), InterfaceKinetics::solvePseudoSteadyStateProblem(), and InterfaceKinetics::~InterfaceKinetics().
std::vector<size_t> m_ctrxn protected inherited
Vector of reaction indexes specifying the id of the current transfer reactions in the mechanism.
Vector of reaction indices which involve current transfers. This provides an index into the m_beta array.
  irxn = m_ctrxn[i]
Definition at line 817 of file InterfaceKinetics.h.
Referenced by InterfaceKinetics::applyButlerVolmerCorrection(), InterfaceKinetics::applyExchangeCurrentDensityFormulation(), InterfaceKinetics::electrochem_beta(), and InterfaceKinetics::operator=().
vector_int m_ctrxn_ecdf protected inherited
Vector of booleans indicating whether the charge transfer reaction may be described by an exchange current density expression.
Definition at line 821 of file InterfaceKinetics.h.
Referenced by InterfaceKinetics::applyExchangeCurrentDensityFormulation(), and InterfaceKinetics::operator=().
bool m_finalized protected inherited
boolean indicating whether mechanism has been finalized
Definition at line 830 of file InterfaceKinetics.h.
Referenced by EdgeKinetics::finalize(), InterfaceKinetics::finalize(), InterfaceKinetics::operator=(), and InterfaceKinetics::ready().
bool m_has_coverage_dependence protected inherited
Boolean flag indicating whether any reaction in the mechanism has a coverage dependent forward reaction rate.
If this is true, then the coverage dependence is multiplied into the forward reaction rates constant
Definition at line 838 of file InterfaceKinetics.h.
Referenced by InterfaceKinetics::_update_rates_T(), and InterfaceKinetics::operator=().
bool m_has_electrochem_rxns protected inherited
Boolean flag indicating whether any reaction in the mechanism has a beta electrochemical parameter.
If this is true, the Butler-Volmer correction is applied to the forward reaction rate for those reactions.
fac = exp (- beta * (delta_phi))
Definition at line 848 of file InterfaceKinetics.h.
Referenced by InterfaceKinetics::_update_rates_T(), and InterfaceKinetics::operator=().
bool m_has_exchange_current_density_formulation protected inherited
Boolean flag indicating whether any reaction in the mechanism is described by an exchange current density expression.
If this is true, the standard state gibbs free energy of the reaction and the product of the reactant standard concentrations must be precalculated in order to calculate the rate constant.
Definition at line 857 of file InterfaceKinetics.h.
Referenced by InterfaceKinetics::_update_rates_T(), and InterfaceKinetics::operator=().
int m_phaseExistsCheck protected inherited
Int flag to indicate that some phases in the kinetics mechanism are non-existent.
We change the ROP vectors to make sure that non-existent phases are treated correctly in the kinetics operator. The value of this is equal to the number of phases which don't exist.
Definition at line 866 of file InterfaceKinetics.h.
Referenced by InterfaceKinetics::operator=(), InterfaceKinetics::setPhaseExistence(), and InterfaceKinetics::updateROP().
std::vector<bool> m_phaseExists protected inherited
Vector of booleans indicating whether phases exist or not.
Vector of booleans indicating whether a phase exists or not. We use this to set the ROP's so that unphysical things don't happen
length = number of phases in the object By default all phases exist.
Definition at line 876 of file InterfaceKinetics.h.
Referenced by InterfaceKinetics::addPhase(), InterfaceKinetics::finalize(), InterfaceKinetics::operator=(), InterfaceKinetics::phaseExistence(), InterfaceKinetics::setPhaseExistence(), and InterfaceKinetics::updateROP().
std::vector<int> m_phaseIsStable protected inherited
Vector of int indicating whether phases are stable or not.
Vector of booleans indicating whether a phase is stable or not under the current conditions. We use this to set the ROP's so that unphysical things don't happen
length = number of phases in the object By default all phases are stable
Definition at line 887 of file InterfaceKinetics.h.
Referenced by InterfaceKinetics::addPhase(), InterfaceKinetics::operator=(), InterfaceKinetics::phaseStability(), InterfaceKinetics::setPhaseExistence(), InterfaceKinetics::setPhaseStability(), and InterfaceKinetics::updateROP().
std::vector<bool*> m_rxnPhaseIsReactant protected inherited
Vector of vector of booleans indicating whether a phase participates in a reaction as a reactant.
m_rxnPhaseIsReactant[j][p] indicates whether a species in phase p participates in reaction j as a reactant.
Definition at line 895 of file InterfaceKinetics.h.
Referenced by InterfaceKinetics::addReaction(), InterfaceKinetics::operator=(), InterfaceKinetics::updateROP(), and InterfaceKinetics::~InterfaceKinetics().
std::vector<bool*> m_rxnPhaseIsProduct protected inherited
Vector of vector of booleans indicating whether a phase participates in a reaction as a product.
m_rxnPhaseIsReactant[j][p] indicates whether a species in phase p participates in reaction j as a product.
Definition at line 903 of file InterfaceKinetics.h.
Referenced by InterfaceKinetics::addReaction(), InterfaceKinetics::operator=(), InterfaceKinetics::updateROP(), and InterfaceKinetics::~InterfaceKinetics().
std::vector<int> m_phaseIsIntermediate protected inherited
Vector of ints indicating whether zeroed phase is an intermediate for the formation of another phase.
If a phase is zeroed out but it is an intermediate, then the phase can be formed whether it is stable or not, but the destruction rate of species in that phase can't exceed the formation rate for species in that phase.
length = number of phases in the object By default all phases are not intermediates
Definition at line 917 of file InterfaceKinetics.h.
std::vector<doublereal> m_rxnRateFactorPhaseIntermediates protected inherited
Reaction rate reduction factor for intermediates.
Individual reaction rates are reduced to accommodate the requirements of intermediate zero phases.
length = number of reactions in the object By default all phases are not intermediates
Definition at line 928 of file InterfaceKinetics.h.
std::vector<doublereal> m_speciesTmpP protected inherited
Work vector having length number of species.
Definition at line 931 of file InterfaceKinetics.h.
size_t m_ii protected inherited
Number of reactions in the mechanism.
Definition at line 1000 of file Kinetics.h.
Referenced by Kinetics::checkReactionArraySize(), Kinetics::checkReactionIndex(), AqueousKinetics::finalize(), GasKinetics::finalize(), AqueousKinetics::getDeltaEnthalpy(), GasKinetics::getDeltaEnthalpy(), AqueousKinetics::getDeltaEntropy(), GasKinetics::getDeltaEntropy(), AqueousKinetics::getDeltaGibbs(), GasKinetics::getDeltaGibbs(), AqueousKinetics::getDeltaSSEnthalpy(), GasKinetics::getDeltaSSEnthalpy(), AqueousKinetics::getDeltaSSEntropy(), GasKinetics::getDeltaSSEntropy(), AqueousKinetics::getDeltaSSGibbs(), GasKinetics::getDeltaSSGibbs(), AqueousKinetics::getEquilibriumConstants(), GasKinetics::getEquilibriumConstants(), InterfaceKinetics::getEquilibriumConstants(), AqueousKinetics::getFwdRateConstants(), GasKinetics::getFwdRateConstants(), AqueousKinetics::getRevRateConstants(), GasKinetics::getRevRateConstants(), InterfaceKinetics::getRevRateConstants(), Kinetics::incrementRxnCount(), Kinetics::nReactions(), InterfaceKinetics::operator=(), Kinetics::operator=(), AqueousKinetics::updateKc(), GasKinetics::updateKc(), InterfaceKinetics::updateKc(), InterfaceKinetics::updateROP(), and InterfaceKinetics::~InterfaceKinetics().
size_t m_kk protected inherited
The number of species in all of the phases that participate in this kinetics mechanism.
Definition at line 1004 of file Kinetics.h.
Referenced by Kinetics::checkSpeciesArraySize(), Kinetics::checkSpeciesIndex(), InterfaceKinetics::finalize(), Kinetics::finalize(), AqueousKinetics::getCreationRates(), GasKinetics::getCreationRates(), InterfaceKinetics::getCreationRates(), AqueousKinetics::getDeltaSSEnthalpy(), GasKinetics::getDeltaSSEnthalpy(), InterfaceKinetics::getDeltaSSEnthalpy(), AqueousKinetics::getDeltaSSEntropy(), GasKinetics::getDeltaSSEntropy(), InterfaceKinetics::getDeltaSSEntropy(), AqueousKinetics::getDestructionRates(), GasKinetics::getDestructionRates(), InterfaceKinetics::getDestructionRates(), AqueousKinetics::getNetProductionRates(), GasKinetics::getNetProductionRates(), InterfaceKinetics::getNetProductionRates(), AqueousKinetics::init(), GasKinetics::init(), InterfaceKinetics::init(), and Kinetics::operator=().
vector_fp m_perturb protected inherited
Vector of perturbation factors for each reaction's rate of progress vector.
It is initialized to one.
Definition at line 1009 of file Kinetics.h.
Referenced by EdgeKinetics::finalize(), AqueousKinetics::finalize(), GasKinetics::finalize(), InterfaceKinetics::finalize(), AqueousKinetics::getFwdRateConstants(), GasKinetics::getFwdRateConstants(), InterfaceKinetics::getFwdRateConstants(), Kinetics::incrementRxnCount(), Kinetics::multiplier(), Kinetics::operator=(), Kinetics::setMultiplier(), and InterfaceKinetics::updateROP().
std::vector<std::vector<size_t> > m_reactants protected inherited
This is a vector of vectors containing the reactants for each reaction.
The outer vector is over the number of reactions, m_ii. The inner vector is a list of species indices. If the stoichiometric coefficient for a reactant is greater than one, then the reactant is listed contiguously in the vector a number of times equal to its stoichiometric coefficient. NOTE: These vectors will be wrong if there are real stoichiometric coefficients in the expression.
Definition at line 1022 of file Kinetics.h.
Referenced by Kinetics::operator=(), and Kinetics::reactants().
std::vector<std::vector<size_t> > m_products protected inherited
This is a vector of vectors containing the products for each reaction.
The outer vector is over the number of reactions, m_ii. The inner vector is a list of species indices. If the stoichiometric coefficient for a product is greater than one, then the reactant is listed contiguously in the vector a number of times equal to its stoichiometric coefficient. NOTE: These vectors will be wrong if there are real stoichiometric coefficients in the expression.
Definition at line 1035 of file Kinetics.h.
Referenced by Kinetics::operator=(), and Kinetics::products().
std::vector<thermo_t*> m_thermo protected inherited
m_thermo is a vector of pointers to ThermoPhase objects that are involved with this kinetics operator
For homogeneous kinetics applications, this vector will only have one entry. For interfacial reactions, this vector will consist of multiple entries; some of them will be surface phases, and the other ones will be bulk phases. The order that the objects are listed determines the order in which the species comprising each phase are listed in the source term vector, originating from the reaction mechanism.
Note that this kinetics object doesn't own these ThermoPhase objects and is not responsible for creating or deleting them.
Definition at line 1052 of file Kinetics.h.
Referenced by Kinetics::addPhase(), Kinetics::assignShallowPointers(), InterfaceKinetics::finalize(), Kinetics::finalize(), GRI_30_Kinetics::gri30_updateKc(), Kinetics::kineticsSpeciesIndex(), Kinetics::nPhases(), Kinetics::operator=(), Kinetics::phase(), InterfaceKinetics::phaseExistence(), InterfaceKinetics::phaseStability(), Kinetics::selectPhase(), InterfaceKinetics::setPhaseExistence(), InterfaceKinetics::setPhaseStability(), Kinetics::speciesPhase(), and Kinetics::thermo().
std::vector<size_t> m_start protected inherited
m_start is a vector of integers specifying the beginning position for the species vector for the n'th phase in the kinetics class.
Definition at line 1059 of file Kinetics.h.
Referenced by InterfaceKinetics::_update_rates_C(), Kinetics::addPhase(), InterfaceKinetics::getDeltaElectrochemPotentials(), InterfaceKinetics::getDeltaEnthalpy(), InterfaceKinetics::getDeltaEntropy(), InterfaceKinetics::getDeltaGibbs(), InterfaceKinetics::getDeltaSSEnthalpy(), InterfaceKinetics::getDeltaSSEntropy(), InterfaceKinetics::getDeltaSSGibbs(), InterfaceKinetics::getEquilibriumConstants(), Kinetics::kineticsSpeciesIndex(), Kinetics::kineticsSpeciesName(), Kinetics::operator=(), Kinetics::selectPhase(), Kinetics::speciesPhaseIndex(), Kinetics::start(), and InterfaceKinetics::updateKc().
std::map<std::string, size_t> m_phaseindex protected inherited
Mapping of the phase id, i.e., the id attribute in the xml phase element to the position of the phase within the kinetics object.
Positions start with the value of 1. The member function, phaseIndex() decrements by one before returning the index value, so that missing phases return -1.
Definition at line 1069 of file Kinetics.h.
Referenced by Kinetics::addPhase(), Kinetics::operator=(), and Kinetics::phaseIndex().
size_t m_surfphase protected inherited
Index in the list of phases of the one surface phase.
Definition at line 1075 of file Kinetics.h.
Referenced by Kinetics::addPhase(), Kinetics::operator=(), and Kinetics::surfacePhaseIndex().
size_t m_rxnphase protected inherited
Phase Index where reactions are assumed to be taking place.
We calculate this by assuming that the phase with the lowest dimensionality is the phase where reactions are taking place
Deprecated:
Definition at line 1083 of file Kinetics.h.
Referenced by Kinetics::addPhase(), Kinetics::operator=(), and Kinetics::reactionPhaseIndex().
size_t m_mindim protected inherited
number of spatial dimensions of lowest-dimensional phase.
Definition at line 1086 of file Kinetics.h.
Referenced by Kinetics::addPhase(), and Kinetics::operator=().
The documentation for this class was generated from the following file:
Interface.h