Cantera: CVodeErr Class Reference
CVodeErr Class Reference
Exception thrown when a CVODE error is encountered.
#include <CVodeInt.h>
Public Member Functions
CVodeErr (std::string msg)
const char * what () const throw ()
Get a description of the error.
void save ()
Function to put this error onto Cantera's error stack.
virtual std::string getMessage () const
Method overridden by derived classes to formatted the error message.
virtual std::string getClass () const
Method overridden by derived classes to indicate their type.
Protected Attributes
std::string procedure_
The name of the procedure where the exception occurred.
Detailed Description
Exception thrown when a CVODE error is encountered.
Definition at line 20 of file CVodeInt.h.
Member Function Documentation
const char * what () const throw () inherited
Get a description of the error.
Definition at line 41 of file ctexceptions.cpp.
References CanteraError::formattedMessage_, CanteraError::getClass(), CanteraError::getMessage(), and CanteraError::procedure_.
Referenced by TransportFactory::getLiquidInteractionsTransportData().
void save () inherited
Function to put this error onto Cantera's error stack.
Definition at line 33 of file ctexceptions.cpp.
References Application::addError(), CanteraError::getMessage(), Application::Instance(), CanteraError::procedure_, and CanteraError::saved_.
Referenced by CanteraError::CanteraError(), Cantera::equilibrate(), ChemEquil::equilibrate(), MultiPhase::equilibrate(), ChemEquil::estimateEP_Brinkley(), TransportFactory::getLiquidSpeciesTransportData(), TransportFactory::getTransportData(), PseudoBinaryVPSSTP::report(), MolarityIonicVPSSTP::report(), PureFluidPhase::report(), MolalityVPSSTP::report(), ThermoPhase::report(), PureFluidPhase::reportCSV(), MolalityVPSSTP::reportCSV(), ThermoPhase::reportCSV(), ChemEquil::setInitialMoles(), ThermoPhase::setState_TPX(), ThermoPhase::setState_TPY(), MultiTransport::solveLMatrixEquation(), Cantera::vcs_equilibrate(), and Cantera::vcs_equilibrate_1().
std::string getMessage () const virtual inherited
Method overridden by derived classes to formatted the error message.
Reimplemented in IndexError, and ArraySizeError.
Definition at line 56 of file ctexceptions.cpp.
References CanteraError::msg_.
Referenced by CanteraError::save(), and CanteraError::what().
virtual std::string getClass () const inline virtual inherited
Method overridden by derived classes to indicate their type.
Reimplemented in IndexError, and ArraySizeError.
Definition at line 97 of file ctexceptions.h.
Referenced by CanteraError::what().
Member Data Documentation
std::string procedure_ protected inherited
The name of the procedure where the exception occurred.
Definition at line 107 of file ctexceptions.h.
Referenced by CanteraError::save(), and CanteraError::what().
The documentation for this class was generated from the following file:
CVodeInt.h