Cantera: TortuosityPercolation Class Reference
TortuosityPercolation Class Reference
This class implements transport coefficient corrections appropriate for porous media where percolation theory applies.
#include <TortuosityPercolation.h>
Public Member Functions
TortuosityPercolation (double percolationThreshold=0.4, double conductivityExponent=2.0)
Default constructor uses Percolation exponent of 1.5.
TortuosityPercolation (const TortuosityPercolation &right)
Copy Constructor.
virtual ~TortuosityPercolation ()
Default destructor for TortuosityPercolation.
TortuosityPercolation & operator= (const TortuosityPercolation &right)
Assignment operator.
virtual TortuosityBase * duplMyselfAsTortuosityBase () const
Duplication operator.
virtual doublereal tortuosityFactor (doublereal porosity)
The tortuosity factor models the effective increase in the diffusive transport length.
virtual doublereal McMillanFactor (doublereal porosity)
The McMillan number is the ratio of the flux-like variable to the value it would have without porous flow.
Protected Attributes
double percolationThreshold_
Critical volume fraction / site density for percolation.
double conductivityExponent_
Conductivity exponent.
Detailed Description
This class implements transport coefficient corrections appropriate for porous media where percolation theory applies.
Definition at line 23 of file TortuosityPercolation.h.
Constructor & Destructor Documentation
TortuosityPercolation (double percolationThreshold = 0.4, double conductivityExponent = 2.0)
Default constructor uses Percolation exponent of 1.5.
Parameters
setPower Exponent in the Percolation factor. The default is 1.5
Definition at line 23 of file TortuosityPercolation.cpp.
Referenced by TortuosityPercolation::duplMyselfAsTortuosityBase().
TortuosityPercolation (const TortuosityPercolation & right)
Copy Constructor.
Parameters
right Object to be copied
Definition at line 35 of file TortuosityPercolation.cpp.
~TortuosityPercolation () virtual
Default destructor for TortuosityPercolation.
Definition at line 44 of file TortuosityPercolation.cpp.
Member Function Documentation
TortuosityPercolation & operator= (const TortuosityPercolation & right)
Assignment operator.
Parameters
right Object to be copied
Definition at line 53 of file TortuosityPercolation.cpp.
References TortuosityPercolation::conductivityExponent_, TortuosityBase::operator=(), and TortuosityPercolation::percolationThreshold_.
TortuosityBase * duplMyselfAsTortuosityBase () const virtual
Duplication operator.
Returns
Returns a pointer to a duplicate of the current object given a base class pointer
Reimplemented from TortuosityBase.
Definition at line 71 of file TortuosityPercolation.cpp.
References TortuosityPercolation::TortuosityPercolation().
doublereal tortuosityFactor (doublereal porosity) virtual
The tortuosity factor models the effective increase in the diffusive transport length.
This method returns \(1/\tau^2 \) in the description of the flux
\(C_T D_i \nabla X_i / \tau^2 \).
Reimplemented from TortuosityBase.
Definition at line 84 of file TortuosityPercolation.cpp.
References TortuosityPercolation::McMillanFactor().
doublereal McMillanFactor (doublereal porosity) virtual
The McMillan number is the ratio of the flux-like variable to the value it would have without porous flow.
The McMillan number combines the effect of tortuosity and volume fraction of the transported phase. The net flux observed is then the product of the McMillan number and the non-porous transport rate. For a conductivity in a non-porous media, \(\kappa_0 \), the conductivity in the porous media would be \(\kappa = (\rm McMillan) \kappa_0 \).
Reimplemented from TortuosityBase.
Definition at line 98 of file TortuosityPercolation.cpp.
References TortuosityPercolation::conductivityExponent_, and TortuosityPercolation::percolationThreshold_.
Referenced by TortuosityPercolation::tortuosityFactor().
Member Data Documentation
double percolationThreshold_ protected
Critical volume fraction / site density for percolation.
Definition at line 82 of file TortuosityPercolation.h.
Referenced by TortuosityPercolation::McMillanFactor(), and TortuosityPercolation::operator=().
double conductivityExponent_ protected
Conductivity exponent.
The McMillan number (ratio of effective conductivity to non-porous conductivity) is
\[ \kappa/\kappa_0 = (\phi - \phi_c)^\mu \]
where \(\mu \) is the conductivity exponent (typical values range from 1.6 to 2.0) and \(\phi_c \) is the percolation threshold.
Definition at line 91 of file TortuosityPercolation.h.
Referenced by TortuosityPercolation::McMillanFactor(), and TortuosityPercolation::operator=().
The documentation for this class was generated from the following files:
TortuosityPercolation.h
TortuosityPercolation.cpp