Cantera: L_Matrix Class Reference
L_Matrix Class Reference
Class L_Matrix is used to represent the "L" matrix.
#include <MultiTransport.h>
Public Types
typedef vector_fp::iterator iterator
Type definition for the iterator class that is can be used by Array2D types.
typedef vector_fp::const_iterator const_iterator
Type definition for the const_iterator class that is can be used by Array2D types.
Public Member Functions
L_Matrix ()
default constructor
virtual ~L_Matrix ()
destructor
virtual void mult (const doublereal *b, doublereal *prod) const
Conduct a multiply with the Dense matrix.
void resize (size_t n, size_t m, doublereal v=0.0)
Resize the matrix.
virtual doublereal *const * colPts ()
Return a vector of const pointers to the columns.
const doublereal *const * const_colPts () const
Return a const vector of const pointers to the columns.
virtual void leftMult (const double *const b, double *const prod) const
Left-multiply the matrix by transpose(b), and write the result to prod.
vector_int & ipiv ()
Return a changeable value of the pivot vector.
const vector_int & ipiv () const
Return a changeable value of the pivot vector.
void copyData (const Array2D &y)
Copy the data from one array into another without doing any checking.
void appendColumn (const vector_fp &c)
Append a column to the existing matrix using a std vector.
void appendColumn (const doublereal *const c)
Append a column to the existing matrix.
void setRow (size_t n, const doublereal *const rw)
Set the nth row to array rw.
void getRow (size_t n, doublereal *const rw)
Get the nth row and return it in a vector.
void setColumn (size_t m, doublereal *const col)
Set the values in column m to those in array col.
void getColumn (size_t m, doublereal *const col)
Get the values in column m.
void axpy (doublereal a, const Array2D &x, const Array2D &y)
Evaluate z = a*x + y.
void zero ()
Set all of the entries to zero.
doublereal & operator() (size_t i, size_t j)
Allows setting elements using the syntax A(i,j) = x.
doublereal operator() (size_t i, size_t j) const
Allows retrieving elements using the syntax x = A(i,j).
doublereal & value (size_t i, size_t j)
Returns a changeable reference to position in the matrix.
doublereal value (size_t i, size_t j) const
Returns the value of a single matrix entry.
size_t nRows () const
Number of rows.
size_t nColumns () const
Number of columns.
iterator begin ()
Return an iterator pointing to the first element.
const_iterator begin () const
Return a const iterator pointing to the first element.
iterator end ()
Return an iterator pointing past the last element.
const_iterator end () const
Return a const iterator pointing to past the last element.
vector_fp & data ()
Return a reference to the data vector.
const vector_fp & data () const
Return a const reference to the data vector.
doublereal * ptrColumn (size_t j)
Return a pointer to the top of column j, columns are contiguous in memory.
const doublereal * ptrColumn (size_t j) const
Return a const pointer to the top of column j, columns are contiguous in memory.
Public Attributes
int m_useReturnErrorCode
Error Handling Flag.
int m_printLevel
Print Level.
Protected Attributes
vector_int m_ipiv
Vector of pivots. Length is equal to the max of m and n.
std::vector< doublereal * > m_colPts
Vector of column pointers.
vector_fp m_data
Data stored in a single array.
size_t m_nrows
Number of rows.
size_t m_ncols
Number of columns.
Detailed Description
Class L_Matrix is used to represent the "L" matrix.
This class is used instead of DenseMatrix so that a version of mult can be used that knows about the structure of the L matrix, specifically that the upper-right and lower-left blocks are zero.
Definition at line 42 of file MultiTransport.h.
Member Typedef Documentation
typedef vector_fp::iterator iterator inherited
Type definition for the iterator class that is can be used by Array2D types.
this is just equal to vector_fp iterator.
Definition at line 43 of file Array.h.
typedef vector_fp::const_iterator const_iterator inherited
Type definition for the const_iterator class that is can be used by Array2D types.
this is just equal to vector_fp const_iterator.
Definition at line 51 of file Array.h.
Constructor & Destructor Documentation
L_Matrix () inline
default constructor
Definition at line 47 of file MultiTransport.h.
virtual ~L_Matrix () inline virtual
destructor
Definition at line 50 of file MultiTransport.h.
Member Function Documentation
void mult (const doublereal * b, doublereal * prod) const virtual
Conduct a multiply with the Dense matrix.
This method is used by GMRES to multiply the L matrix by a vector b.
This method is used by GMRES to multiply the L matrix by a vector b. The L matrix has a 3x3 block structure, where each block is a K x K matrix. The elements of the upper-right and lower-left blocks are all zero. This method is defined so that the multiplication only involves the seven non-zero blocks.
Parameters
b
prod
Deprecated:
GMRES method is not implemented
The L matrix has a 3x3 block structure, where each block is a K x K matrix. The elements of the upper-right and lower-left blocks are all zero. This method is defined so that the multiplication only involves the seven non-zero blocks.
Reimplemented from DenseMatrix.
Definition at line 65 of file MultiTransport.cpp.
References DATA_PTR.
void resize (size_t n, size_t m, doublereal v = 0.0) inherited
Resize the matrix.
Resize the matrix to n rows by m cols.
Parameters
n New number of rows
m New number of columns
v Default fill value. defaults to zero.
Definition at line 86 of file DenseMatrix.cpp.
References DenseMatrix::m_colPts, Array2D::m_data, DenseMatrix::m_ipiv, Array2D::m_ncols, Array2D::m_nrows, ckr::max(), and Array2D::resize().
Referenced by LTI_Pairwise_Interaction::getMatrixTransProp(), LTI_StefanMaxwell_PPN::getMatrixTransProp(), LiquidTranInteraction::init(), MultiPhase::init(), GasTransport::initGas(), MultiTransport::initGas(), DustyGasTransport::initialize(), LiquidTransport::initLiquid(), AqueousTransport::initLiquid(), MultiPhaseEquil::MultiPhaseEquil(), SquareMatrix::resize(), TransportFactory::setupLiquidTransport(), TransportFactory::setupMM(), MultiTransport::solveLMatrixEquation(), and LiquidTransport::stefan_maxwell_solve().
doublereal *const * colPts () virtual inherited
Return a vector of const pointers to the columns.
Note the value of the pointers are protected by their being const. However, the value of the matrix is open to being changed.
Returns
returns a vector of pointers to the top of the columns of the matrices.
Reimplemented in SquareMatrix.
Definition at line 98 of file DenseMatrix.cpp.
References DenseMatrix::m_colPts.
Referenced by SquareMatrix::colPts().
const doublereal *const * const_colPts () const inherited
Return a const vector of const pointers to the columns.
Note, the jacobian can not be altered by this routine, and therefore the member function is const.
Returns
returns a vector of pointers to the top of the columns of the matrices.
Definition at line 103 of file DenseMatrix.cpp.
References DenseMatrix::m_colPts.
void leftMult (const double *const b, double *const prod) const virtual inherited
Left-multiply the matrix by transpose(b), and write the result to prod.
Parameters
b left multiply by this vector. The length must be equal to n the number of rows in the matrix.
prod Resulting vector. This is of length m, the number of columns in the matrix
Reimplemented in SquareMatrix.
Definition at line 116 of file DenseMatrix.cpp.
References Array2D::nColumns(), Array2D::nRows(), and Array2D::value().
Referenced by ChemEquil::equilibrate(), and SquareMatrix::leftMult().
vector_int & ipiv () inherited
Return a changeable value of the pivot vector.
Returns
Returns a reference to the pivot vector as a vector_int
Definition at line 130 of file DenseMatrix.cpp.
References DenseMatrix::m_ipiv.
Referenced by DenseMatrix::DenseMatrix(), SquareMatrix::factor(), MultiTransport::getMassFluxes(), MultiTransport::getSpeciesFluxes(), Cantera::invert(), DenseMatrix::operator=(), SquareMatrix::solve(), and Cantera::solve().
const vector_int& ipiv () const inline inherited
Return a changeable value of the pivot vector.
Returns
Returns a reference to the pivot vector as a vector_int
Definition at line 161 of file DenseMatrix.h.
References DenseMatrix::m_ipiv.
void copyData (const Array2D & y) inline inherited
Copy the data from one array into another without doing any checking.
This differs from the assignment operator as no resizing is done and memcpy() is used.
Parameters
y Array to be copied
Definition at line 139 of file Array.h.
References DATA_PTR, Array2D::m_data, Array2D::m_ncols, Array2D::m_nrows, and Array2D::ptrColumn().
Referenced by SquareMatrix::copyData().
void appendColumn (const vector_fp & c) inline inherited
Append a column to the existing matrix using a std vector.
This operation will add a column onto the existing matrix.
Parameters
c This vector<doublereal> is the entries in the column to be added. It must have a length equal to m_nrows or greater.
Definition at line 152 of file Array.h.
References Array2D::m_data, Array2D::m_ncols, Array2D::m_nrows, and Array2D::value().
void appendColumn (const doublereal *const c) inline inherited
Append a column to the existing matrix.
This operation will add a column onto the existing matrix.
Parameters
c This vector of doubles is the entries in the column to be added. It must have a length equal to m_nrows or greater.
Definition at line 169 of file Array.h.
References Array2D::m_data, Array2D::m_ncols, Array2D::m_nrows, and Array2D::value().
void setRow (size_t n, const doublereal *const rw) inline inherited
Set the nth row to array rw.
Parameters
n Index of the row to be changed
rw Vector for the row. Must have a length of m_ncols.
Definition at line 183 of file Array.h.
References Array2D::m_data, Array2D::m_ncols, and Array2D::m_nrows.
void getRow (size_t n, doublereal *const rw) inline inherited
Get the nth row and return it in a vector.
Parameters
n Index of the row to be returned.
rw Return Vector for the operation. Must have a length of m_ncols.
Definition at line 195 of file Array.h.
References Array2D::m_data, Array2D::m_ncols, and Array2D::m_nrows.
Referenced by StFlow::save().
void setColumn (size_t m, doublereal *const col) inline inherited
Set the values in column m to those in array col.
A(i,m) = col(i)
Parameters
m Column to set
col pointer to a col vector. Vector must have a length of m_nrows.
Definition at line 209 of file Array.h.
References Array2D::m_data, and Array2D::m_nrows.
void getColumn (size_t m, doublereal *const col) inline inherited
Get the values in column m.
col(i) = A(i,m)
Parameters
m Column to set
col pointer to a col vector that will be returned
Definition at line 222 of file Array.h.
References Array2D::m_data, and Array2D::m_nrows.
void axpy (doublereal a, const Array2D & x, const Array2D & y) inline inherited
Evaluate z = a*x + y.
This function evaluates the AXPY operation, and stores the result in the object's Array2D object. It's assumed that all 3 objects have the same dimensions, but no error checking is done.
Parameters
a scalar to multiply x with
x First Array2D object to be used
y Second Array2D object to be used
Definition at line 246 of file Array.h.
References Array2D::begin(), and Array2D::end().
void zero () inline inherited
Set all of the entries to zero.
Definition at line 256 of file Array.h.
References Array2D::m_data, Array2D::m_ncols, and Array2D::m_nrows.
Referenced by IonsFromNeutralVPSSTP::s_update_dlnActCoeff_dlnN(), PhaseCombo_Interaction::s_update_dlnActCoeff_dlnN(), MargulesVPSSTP::s_update_dlnActCoeff_dlnN(), MixedSolventElectrolyte::s_update_dlnActCoeff_dlnN(), and RedlichKisterVPSSTP::s_update_dlnActCoeff_dX_().
doublereal& operator() (size_t i, size_t j) inline inherited
Allows setting elements using the syntax A(i,j) = x.
Parameters
i row index
j column index.
Returns
Returns a reference to A(i,j) which may be assigned.
Definition at line 274 of file Array.h.
References Array2D::value().
Referenced by SquareMatrix::operator()().
doublereal operator() (size_t i, size_t j) const inline inherited
Allows retrieving elements using the syntax x = A(i,j).
Parameters
i Index for the row to be retrieved
j Index for the column to be retrieved.
Returns
Returns the value of the matrix entry
Definition at line 286 of file Array.h.
References Array2D::value().
doublereal& value (size_t i, size_t j) inline inherited
Returns a changeable reference to position in the matrix.
This is a key entry. Returns a reference to the matrixes (i,j) element. This may be used as an L value.
Parameters
i The row index
j The column index
Returns
Returns a changeable reference to the matrix entry
Definition at line 300 of file Array.h.
References Array2D::m_data, and Array2D::m_nrows.
Referenced by Array2D::appendColumn(), SquareMatrix::checkColumns(), SquareMatrix::checkRows(), DenseMatrix::leftMult(), Array2D::operator()(), and DebyeHuckel::s_update_lnMolalityActCoeff().
doublereal value (size_t i, size_t j) const inline inherited
Returns the value of a single matrix entry.
This is a key entry. Returns the value of the matrix position (i,j) element.
Parameters
i The row index
j The column index
Definition at line 312 of file Array.h.
References Array2D::m_data, and Array2D::m_nrows.
size_t nRows () const inline inherited
Number of rows.
Definition at line 317 of file Array.h.
References Array2D::m_nrows.
Referenced by MultiTransport::getMassFluxes(), ctml::getMatrixValues(), MultiTransport::getSpeciesFluxes(), Cantera::increment(), Cantera::invert(), DenseMatrix::leftMult(), DenseMatrix::mult(), Cantera::multiply(), Cantera::operator<<(), Cantera::outputExcel(), Cantera::outputTEC(), and Cantera::solve().
size_t nColumns () const inline inherited
Number of columns.
Definition at line 322 of file Array.h.
References Array2D::m_ncols.
Referenced by MultiTransport::getMassFluxes(), ctml::getMatrixValues(), MultiTransport::getSpeciesFluxes(), DenseMatrix::leftMult(), Cantera::multiply(), Cantera::operator<<(), Cantera::outputExcel(), Cantera::outputTEC(), StFlow::save(), SquareMatrix::solve(), and Cantera::solve().
iterator begin () inline inherited
Return an iterator pointing to the first element.
Definition at line 327 of file Array.h.
References Array2D::m_data.
Referenced by Array2D::axpy(), Cantera::operator*=(), and Cantera::operator+=().
const_iterator begin () const inline inherited
Return a const iterator pointing to the first element.
Definition at line 337 of file Array.h.
References Array2D::m_data.
iterator end () inline inherited
Return an iterator pointing past the last element.
Definition at line 332 of file Array.h.
References Array2D::m_data.
Referenced by Array2D::axpy(), Cantera::operator*=(), and Cantera::operator+=().
const_iterator end () const inline inherited
Return a const iterator pointing to past the last element.
Definition at line 342 of file Array.h.
References Array2D::m_data.
vector_fp& data () inline inherited
Return a reference to the data vector.
Definition at line 347 of file Array.h.
References Array2D::m_data.
const vector_fp& data () const inline inherited
Return a const reference to the data vector.
Definition at line 352 of file Array.h.
References Array2D::m_data.
doublereal* ptrColumn (size_t j) inline inherited
Return a pointer to the top of column j, columns are contiguous in memory.
Parameters
j Value of the column
Returns
Returns a pointer to the top of the column
Definition at line 363 of file Array.h.
References Array2D::m_data, and Array2D::m_nrows.
Referenced by Array2D::copyData(), MultiTransport::getMassFluxes(), MultiTransport::getSpeciesFluxes(), Cantera::increment(), Cantera::invert(), DenseMatrix::mult(), Cantera::multiply(), SquareMatrix::ptrColumn(), HMWSoln::s_updatePitzer_CoeffWRTemp(), Cantera::solve(), solveProb::solveProb(), solveSP::solveSP(), AqueousTransport::stefan_maxwell_solve(), DustyGasTransport::updateBinaryDiffCoeffs(), and StFlow::updateTransport().
const doublereal* ptrColumn (size_t j) const inline inherited
Return a const pointer to the top of column j, columns are contiguous in memory.
Parameters
j Value of the column
Returns
Returns a const pointer to the top of the column
Definition at line 374 of file Array.h.
References Array2D::m_data, and Array2D::m_nrows.
Member Data Documentation
vector_int m_ipiv protected inherited
Vector of pivots. Length is equal to the max of m and n.
Definition at line 168 of file DenseMatrix.h.
Referenced by DenseMatrix::DenseMatrix(), DenseMatrix::ipiv(), DenseMatrix::operator=(), and DenseMatrix::resize().
std::vector<doublereal*> m_colPts protected inherited
Vector of column pointers.
Definition at line 171 of file DenseMatrix.h.
Referenced by DenseMatrix::colPts(), DenseMatrix::const_colPts(), DenseMatrix::DenseMatrix(), DenseMatrix::operator=(), and DenseMatrix::resize().
int m_useReturnErrorCode inherited
Error Handling Flag.
The default is to set this to 0. In this case, if a factorization is requested and can't be achieved, a CESingularMatrix exception is triggered. No return code is used, because an exception is thrown. If this is set to 1, then an exception is not thrown. Routines return with an error code, that is up to the calling routine to handle correctly. Negative return codes always throw an exception.
Definition at line 182 of file DenseMatrix.h.
Referenced by SquareMatrix::factor(), SquareMatrix::factorQR(), Cantera::invert(), DenseMatrix::operator=(), SquareMatrix::rcond(), SquareMatrix::rcondQR(), SquareMatrix::solve(), Cantera::solve(), and SquareMatrix::solveQR().
int m_printLevel inherited
Print Level.
Printing is done to the log file using the routine writelogf().
Level of printing that is carried out. Only error conditions are printed out, if this value is nonzero.
Definition at line 190 of file DenseMatrix.h.
Referenced by SquareMatrix::factor(), SquareMatrix::factorQR(), Cantera::invert(), DenseMatrix::operator=(), SquareMatrix::rcond(), SquareMatrix::rcondQR(), SquareMatrix::solve(), Cantera::solve(), and SquareMatrix::solveQR().
vector_fp m_data protected inherited
Data stored in a single array.
Definition at line 381 of file Array.h.
Referenced by Array2D::appendColumn(), Array2D::Array2D(), SquareMatrix::begin(), Array2D::begin(), Array2D::copyData(), Array2D::data(), DenseMatrix::DenseMatrix(), Array2D::end(), Array2D::getColumn(), Array2D::getRow(), DenseMatrix::operator=(), Array2D::operator=(), Array2D::ptrColumn(), DenseMatrix::resize(), Array2D::resize(), Array2D::setColumn(), Array2D::setRow(), Array2D::value(), SquareMatrix::zero(), and Array2D::zero().
size_t m_nrows protected inherited
Number of rows.
Definition at line 384 of file Array.h.
Referenced by Array2D::appendColumn(), Array2D::Array2D(), SquareMatrix::checkColumns(), SquareMatrix::checkRows(), Array2D::copyData(), DenseMatrix::DenseMatrix(), SquareMatrix::factor(), SquareMatrix::factorQR(), Array2D::getColumn(), Array2D::getRow(), SquareMatrix::nRows(), Array2D::nRows(), SquareMatrix::nRowsAndStruct(), DenseMatrix::operator=(), Array2D::operator=(), Array2D::ptrColumn(), SquareMatrix::rcond(), SquareMatrix::rcondQR(), DenseMatrix::resize(), Array2D::resize(), Array2D::setColumn(), Array2D::setRow(), SquareMatrix::solveQR(), Array2D::value(), and Array2D::zero().
size_t m_ncols protected inherited
Number of columns.
Definition at line 387 of file Array.h.
Referenced by Array2D::appendColumn(), Array2D::Array2D(), Array2D::copyData(), DenseMatrix::DenseMatrix(), Array2D::getRow(), Array2D::nColumns(), DenseMatrix::operator=(), Array2D::operator=(), DenseMatrix::resize(), Array2D::resize(), Array2D::setRow(), and Array2D::zero().
The documentation for this class was generated from the following files:
MultiTransport.h
MultiTransport.cpp