Cantera: ckr Namespace Reference
ckr Namespace Reference
the namespace for the CKReader packaage
Classes
class CK_SyntaxError
Exception class for syntax errors.
class CKParser
Chemkin mechanism file parser.
class CKReader
Chemkin file reader class.
class Constituent
A class for components of a composite object.
class Element
A class for elements.
class RateCoeff
Reaction rate coefficient class.
class ReactionUnits
Specifies the Units for all reactions.
class Reaction
A class for reactions.
class RxnSpecies
A class for species in a reaction.
class Species
Holds species data read in from entries in the THERMO section of a chemkin or nasa9 fortran formatted input file.
Typedefs
typedef std::vector< double > vector_fp
typedef std::vector< double > vector_int
typedef std::vector< Group > groupList
a list (vector) of Groups
typedef std::vector< Element > elementList
a list (vector) of Elements
typedef std::vector< Reaction > reactionList
a list of Reaction objects
typedef vector_int group_t
typedef std::vector< group_t > grouplist_t
typedef std::vector< Species > speciesList
Shorthand for a list of Species.
typedef std::map< std::string,
Species > speciesTable
A map from species names to Species objects.
Functions
void getDefaultAtomicWeights (map< string, double > &weights)
Get table of atomic weights from the internal database.
void writeKnownElements (ostream &s, string fmt)
static string int2s (int n, std::string fmt="%d")
static int parseGroupString (std::string str, std::vector< std::string > &esyms, vector_int &result)
static void illegalThermoLine (std::ostream &f, char n, int linenum=-1)
Throw an exception if one of the four lines that must have 1, 2, 3, or 4 in column 80 do not.
static void illegalNumber (std::ostream &f, std::string s, int linenum=-1)
Throw an exception if number string is bad.
static string d2e (string s)
static double de_atof (std::string s)
static void checkNASA9Temps (std::ostream &log, vector_fp &temp)
Check validity of the temperatures defining the temperature ranges for the NASA9 polynomial species thermodynamic property fits.
static double getNumberFromString (std::string s)
static void addElement (std::string symbol, double atoms, Species &sp, std::ostream &log)
Add an element to a species.
static void checkTemps (std::ostream &log, double tmin, double tmid, double tmax)
Check validity of the three temperatures defining the two temperature ranges for the NASA polynomial species thermodynamic property fits.
static void getSpecies (std::string s, int n, vector< RxnSpecies > &species, bool debug, std::ostream &log)
int getGroups (std::string::const_iterator begin, std::string::const_iterator end, std::vector< std::string > &esyms, std::vector< grouplist_t > &rxngroups)
given a string specifying either the reactant or product side of a reaction equation, construct a list of Constituent objects containing the species symbols and stoichiometric coefficients.
bool match (const std::string &s1, const std::string &s2)
Perform a case-insensitive comparison of the first n2 characters of strings s1 and s2, where n2 is the length of s2.
void removeWhiteSpace (std::string &s)
Remove all white space from string s.
void getTokens (std::string &s, int n, std::vector< std::string > &toks, char delim)
Get tokens from char array of length n beginning at 'begin'.
bool extractSlashData (std::string &s, std::string &name, std::string &data)
Look for a slash-delimited number in string s, and if found set v to the numerical value, and set s to the portion of the string before the first slash.
string capitalize (const std::string &word)
Return a modified version of string word, in which the first letter is upper case, and the rest are lower case.
template<class K , class V >
void getMapKeys (const std::map< K, V > &mp, std::vector< K > &keys)
Fill vector 'keys' with the keys of map 'mp'.
template<class K , class V >
void getMapValues (const std::map< K, V > &mp, std::vector< V > &values)
Fill vector 'values' with the values of map 'mp'.
template<class T , class S >
T max (T a, S b)
Template to compare two objects a and b, possibly of different types, and return the greater of the two, converted to the type of a.
template<class T , class S >
T min (T a, S b)
Template to compare two objects a and b, possibly of different types, and * return the lesser of the two, converted to the type of a.
template<class S >
S pad (const S &s, size_t n)
Template to return a string equal to s, but padded with spaces on the right as necessary to make the length n.
template<class T >
T absval (T x)
Absolute value.
template<class L >
bool valid (L &list)
Iterate through a list of objects that have a numeric member named 'valid', and return false if for any object this attribute is not greater than 0.
bool isKeyword (std::string word)
Check whether string 'word' begins with a Chemkin keyword.
bool checkThermo (std::ostream &log, speciesList &sp, double tol)
Check the thermodynamic property parameterizations for all species.
bool checkBalance (std::ostream &f, speciesTable &speciesData, reactionList &r, std::vector< int > &unbalanced, double tolerance)
Check that all reactions balance.
bool checkBalance (ostream &f, speciesTable &speciesData, reactionList &r, vector< int > &unbalanced, double tolerance=1.0e-3)
bool checkThermo (ostream &f, speciesList &species, double tol)
bool filter (const string &infile, const string &database, const string &outfile, const vector< int > &species, const vector< int > &reactions)
static void addElement (std::string symbol, double atoms, Species &sp, std::ostream &log)
Add an element to a species.
static void illegalNumber (std::ostream &f, std::string s, int linenum=-1)
Throw an exception if number string is bad.
static std::string d2e (std::string s)
static double de_atof (std::string s)
static double getNumberFromString (std::string s)
static int de_atoi (std::ostream &log, std::string s, int line=-1)
Reaction forwardReaction (const Reaction &rxn)
Reaction reverseReaction (const Reaction &rxn)
double cp (double t, const Species &s)
non-dimensional heat capacity (\(C_p/R \)) at constant P for one species
double enthalpy (double t, const Species &s)
enthalpy in Kelvin (\(H/R \)) for one species.
double entropy (double t, const Species &s)
non-dimensional entropy (\(S/R \)) for one species
double gibbs (double t, const Species &s)
Gibbs function in Kelvin (\(G/R \)) for one species.
string newTask (std::string msg)
format a string for the log file message printed when starting a new task
bool writeFalloff (int type, const vector_fp &c, std::ostream &log)
print the falloff parameters for a pressure-dependent reaction
bool writeRateCoeff (const RateCoeff &k, std::ostream &log)
print the rate coefficient parameters
void printReactionEquation (std::ostream &f, const Reaction &r)
Write onto an output stream the chemical equation for a reaction.
string reactionEquation (const Reaction &r)
Write to a string the chemical equation for a reaction.
void writeSpeciesData (std::ostream &log, const Species &spec)
Write a summary of the properties of one species to the log file.
Variables
static double _weights []
static char _symbols [][3]
const double UNDEF = -9999.1234
const int NoThermoDatabase = 10
readability constants
const int HasTempRange = 11
Falloff Parameterizations
These constants are used to specify which falloff parameterization to use for a pressure-dependent reaction.
See Also
Reaction.h
const int Lindemann = 0
const int Troe = 1
const int SRI = 2
Reaction Rate Types
These constant are used to specify the type of rate coefficient
const int Arrhenius = 0
const int LandauTeller = 1
const int Jan = 2
const int Fit1 = 3
Activation Energy Units
These constants specify the supported units for the activation energy of a reaction The default is to assume Cal_per_Mole for unspecified units in the activation energy as this was the original default
const int Cal_per_Mole = 1
const int Kcal_per_Mole = 2
const int Joules_per_Mole = 3
const int Kelvin = 4
const int Electron_Volts = 5
const int Kjoules_per_Mole = 6
Quantity Units
These constants define the supported units for number of molecules.
const int Moles = 100
specify number of moles (6.023e23 molecules / mole)
const int Molecules = 101
specify number of molecules
Reaction Types
const int Elementary = 2000
elementary, pressure-independent reaction
const int ThreeBody = 2001
three-body reaction
const int Falloff = 2002
falloff reaction
const int ChemAct = 2003
chemical activation reaction
Detailed Description
the namespace for the CKReader packaage
Typedef Documentation
typedef std::vector<Group> groupList
a list (vector) of Groups
Definition at line 50 of file CKReader.h.
typedef std::vector<Element> elementList
a list (vector) of Elements
Definition at line 92 of file Element.h.
typedef std::vector<Reaction> reactionList
a list of Reaction objects
Definition at line 255 of file Reaction.h.
typedef std::vector<Species> speciesList
Shorthand for a list of Species.
Definition at line 95 of file Species.h.
typedef std::map<std::string, Species> speciesTable
A map from species names to Species objects.
Definition at line 98 of file Species.h.
Function Documentation
void getDefaultAtomicWeights (map< string, double > & weights)
Get table of atomic weights from the internal database.
Parameters
weights atomic symbol -> atomic weight map
Example usage:
#include "atomicWeightDB.h"
...
map<string, double> atw;
getDefaultAtomicWeights(atw);
double copperAtomicWeight = atw["Cu"];
...
Note that if the atomic weight is requested for an unknown element symbol, the value zero will be returned.
Definition at line 87 of file atomicWeightDB.cpp.
Referenced by CKParser::readElementSection().
static void ckr::illegalThermoLine (std::ostream & f, char n, int linenum = -1) static
Throw an exception if one of the four lines that must have 1, 2, 3, or 4 in column 80 do not.
Definition at line 52 of file CKParser.cpp.
Referenced by CKParser::readThermoRecord().
static void ckr::illegalNumber (std::ostream & f, std::string s, int linenum = -1) static
Throw an exception if number string is bad.
Definition at line 63 of file CKParser.cpp.
Referenced by CKParser::readNASA9ThermoRecord(), and CKParser::readThermoRecord().
static void ckr::checkNASA9Temps (std::ostream & log, vector_fp & temp) static
Check validity of the temperatures defining the temperature ranges for the NASA9 polynomial species thermodynamic property fits.
Parameters
log log file output stream
temp Vector of temperatures
Definition at line 105 of file CKParser.cpp.
Referenced by CKParser::readThermoSection().
static void ckr::addElement (std::string symbol, double atoms, Species & sp, std::ostream & log) static
Add an element to a species.
Parameters
symbol element symbol
atoms number of atoms of this element in the species (may be non-integral)
sp Species object to add element to
log log file output stream
Definition at line 149 of file CKParser.cpp.
References Species::comp, Species::elements, Constituent::name, and Constituent::number.
Referenced by CKParser::readNASA9ThermoRecord(), and CKParser::readThermoRecord().
static void ckr::checkTemps (std::ostream & log, double tmin, double tmid, double tmax) static
Check validity of the three temperatures defining the two temperature ranges for the NASA polynomial species thermodynamic property fits.
Parameters
log log file output stream
tmin minimum temperature
tmid intermediate temperature
tmax maximum temperature
Definition at line 172 of file CKParser.cpp.
Referenced by CKParser::readThermoSection().
int ckr::getGroups (std::string::const_iterator begin, std::string::const_iterator end, std::vector< std::string > & esyms, std::vector< grouplist_t > & rxngroups)
given a string specifying either the reactant or product side of a reaction equation, construct a list of Constituent objects containing the species symbols and stoichiometric coefficients.
Todo:
allow non-integral stoichiometric coefficients
Definition at line 246 of file CKParser.cpp.
Referenced by CKParser::readReactionSection().
bool match (const std::string & s1, const std::string & s2)
Perform a case-insensitive comparison of the first n2 characters of strings s1 and s2, where n2 is the length of s2.
Typically, s1 is an unknown string and s2 is the significant portion of a keyword. Returns true if a match is found, false otherwise. An asterisk in string s2 matches any character at that position.
Example: if s1 = "elements", then match(s1, "ELEM") would return true.
Definition at line 20 of file ckr_utils.cpp.
Referenced by isKeyword(), CKParser::readElementSection(), CKParser::readNASA9ThermoRecord(), CKParser::readNASA9ThermoSection(), CKParser::readReactionSection(), CKParser::readSpeciesSection(), CKParser::readThermoRecord(), and CKParser::readThermoSection().
void removeWhiteSpace (std::string & s)
Remove all white space from string s.
Definition at line 34 of file ckr_utils.cpp.
Referenced by extractSlashData(), and CKParser::readReactionSection().
void getTokens (std::string & s, int n, std::vector< std::string > & toks, char delim)
Get tokens from char array of length n beginning at 'begin'.
Tokens are delimited by character 'delim' (space by default), with the exception of text contained within forward slashes ('/'), which is treated literally.
code vector<string> tokens; char line[] = "a b/3.0 txt/ c /4.0 6/ d"; int n = strlen(line); getTokens(line, n, tokens); for (int i = 0; i < tokens.size(); i++) cout << tokens[i] << endl; endcode
Definition at line 60 of file ckr_utils.cpp.
Referenced by CKParser::readElementSection(), CKParser::readNASA9ThermoRecord(), CKParser::readReactionSection(), CKParser::readSpeciesSection(), CKParser::readThermoRecord(), and CKParser::readThermoSection().
bool extractSlashData (std::string & s, std::string & name, std::string & data)
Look for a slash-delimited number in string s, and if found set v to the numerical value, and set s to the portion of the string before the first slash.
Return true if slash data found, false otherwise.
Definition at line 117 of file ckr_utils.cpp.
References Cantera::npos, and removeWhiteSpace().
Referenced by CKParser::readElementSection(), and CKParser::readReactionSection().
std::string capitalize (const std::string & word)
Return a modified version of string word, in which the first letter is upper case, and the rest are lower case.
Definition at line 153 of file ckr_utils.cpp.
Referenced by CKParser::readElementSection().
void ckr::getMapKeys (const std::map< K, V > & mp, std::vector< K > & keys)
Fill vector 'keys' with the keys of map 'mp'.
Definition at line 23 of file ckr_utils.h.
Referenced by checkBalance(), CKReader::validateSpecies(), and CKReader::writeReactions().
void ckr::getMapValues (const std::map< K, V > & mp, std::vector< V > & values)
Fill vector 'values' with the values of map 'mp'.
Definition at line 37 of file ckr_utils.h.
Referenced by Reaction::operator==().
T ckr::max (T a, S b) inline
Template to compare two objects a and b, possibly of different types, and return the greater of the two, converted to the type of a.
The '<' operator is used for the comparison, and must be defined for the two types in question.
Definition at line 57 of file ckr_utils.h.
Referenced by DebyeHuckel::_lnactivityWaterHelgesonFixedForm(), Cantera::_minTemp(), Cantera::bound_step(), BEulerInt::boundStep(), ResidJacEval::calcDeltaSolnVariables(), PseudoBinaryVPSSTP::calcPseudoBinaryMoleFractions(), MolarityIonicVPSSTP::calcPseudoBinaryMoleFractions(), NonlinearSolver::deltaBoundStep(), DenseMatrix::DenseMatrix(), WaterPropsIAPWS::densSpinodalSteam(), WaterPropsIAPWS::densSpinodalWater(), ChemEquil::equilibrate(), vcs_MultiPhaseEquil::equilibrate_HP(), vcs_MultiPhaseEquil::equilibrate_SP(), vcs_MultiPhaseEquil::equilibrate_TP(), vcs_MultiPhaseEquil::equilibrate_TV(), Troe3::F(), Troe4::F(), SRI3::F(), SRI5::F(), WF93::F(), IdealMolalSoln::getActivities(), ConstDensityThermo::getChemPotentials(), MolarityIonicVPSSTP::getChemPotentials(), IdealSolnGasVPSS::getChemPotentials(), IonsFromNeutralVPSSTP::getChemPotentials(), RedlichKwongMFTP::getChemPotentials(), RedlichKisterVPSSTP::getChemPotentials(), MargulesVPSSTP::getChemPotentials(), MixedSolventElectrolyte::getChemPotentials(), PhaseCombo_Interaction::getChemPotentials(), IdealSolidSolnPhase::getChemPotentials(), IdealMolalSoln::getChemPotentials(), IdealGasPhase::getChemPotentials(), LatticePhase::getChemPotentials(), DebyeHuckel::getChemPotentials(), HMWSoln::getChemPotentials(), IdealSolidSolnPhase::getChemPotentials_RT(), PhaseCombo_Interaction::getdlnActCoeffds(), LTI_StefanMaxwell_PPN::getMatrixTransProp(), IdealMolalSoln::getMolalityActivityCoefficients(), IdealSolnGasVPSS::getPartialMolarEntropies(), MolarityIonicVPSSTP::getPartialMolarEntropies(), IonsFromNeutralVPSSTP::getPartialMolarEntropies(), RedlichKwongMFTP::getPartialMolarEntropies(), RedlichKisterVPSSTP::getPartialMolarEntropies(), MargulesVPSSTP::getPartialMolarEntropies(), MixedSolventElectrolyte::getPartialMolarEntropies(), PhaseCombo_Interaction::getPartialMolarEntropies(), IdealGasPhase::getPartialMolarEntropies(), IdealMolalSoln::getPartialMolarEntropies(), IdealSolidSolnPhase::getPartialMolarEntropies(), LatticePhase::getPartialMolarEntropies(), DebyeHuckel::getPartialMolarEntropies(), HMWSoln::getPartialMolarEntropies(), TransportFactory::getTransportData(), GeneralSpeciesThermo::install(), GeneralSpeciesThermo::install_STIT(), LatticeSolidPhase::maxTemp(), SpeciesThermoDuo< T1, T2 >::minTemp(), MultiPhaseEquil::MultiPhaseEquil(), NonlinearSolver::NonlinearSolver(), MolalityVPSSTP::osmoticCoefficient(), pad(), DenseMatrix::resize(), solveProb::resjac_eval(), solveSP::resjac_eval(), DebyeHuckel::s_update_d2lnMolalityActCoeff_dT2(), PhaseCombo_Interaction::s_update_dlnActCoeff_dlnN(), PhaseCombo_Interaction::s_update_dlnActCoeff_dlnN_diag(), DebyeHuckel::s_update_dlnMolalityActCoeff_dP(), DebyeHuckel::s_update_dlnMolalityActCoeff_dT(), PhaseCombo_Interaction::s_update_lnActCoeff(), DebyeHuckel::s_update_lnMolalityActCoeff(), HMWSoln::s_update_lnMolalityActCoeff(), IdealMolalSoln::s_updateIMS_lnMolalityActCoeff(), HMWSoln::s_updateIMS_lnMolalityActCoeff(), HMWSoln::s_updatePitzer_lnMolalityActCoeff(), Phase::setConcentrations(), NonlinearSolver::setDefaultDeltaBoundsMagnitudes(), Phase::setMassFractions(), MolalityVPSSTP::setMolalitiesByName(), Phase::setMoleFractions(), vcs_VolPhase::setMolesFromVCS(), ThermoPhase::setState_HPorUV(), ThermoPhase::setState_SPorSV(), RootFind::solve(), solveSP::solveSP(), solveSP::solveSurfProb(), OneDim::ssnorm(), BEulerInt::step(), RootFind::theSame(), BEulerInt::time_step_control(), MixTransport::update_C(), MultiTransport::update_C(), AqueousTransport::update_C(), SimpleTransport::update_C(), LiquidTransport::update_C(), Troe3::updateTemp(), Troe4::updateTemp(), MultiTransport::updateThermal_T(), DustyGasTransport::updateTransport_C(), VCS_SOLVE::vcs(), VCS_SOLVE::vcs_deltag(), Cantera::vcs_determine_PhaseStability(), Cantera::vcs_equilibrate_1(), VCS_SOLVE::vcs_phaseStabilityTest(), VCS_SOLVE::vcs_popPhaseRxnStepSizes(), VCS_SOLVE::vcs_report(), and VCS_SOLVE::vcs_solve_TP().
T ckr::min (T a, S b) inline
Template to compare two objects a and b, possibly of different types, and * return the lesser of the two, converted to the type of a.
The '<' operator is used for the comparison, and must be defined for the two types in question.
Definition at line 74 of file ckr_utils.h.
Referenced by Cantera::_maxTemp(), Cantera::bound_step(), MultiNewton::boundStep(), BEulerInt::boundStep(), NonlinearSolver::boundStep(), solveProb::calc_damping(), NonlinearSolver::calcSolnToResNormVector(), NonlinearSolver::computeResidWts(), VCS_SOLVE::delta_species(), MixtureFugacityTP::densityCalc(), WaterPropsIAPWS::densSpinodalSteam(), WaterPropsIAPWS::densSpinodalWater(), ChemEquil::equilibrate(), vcs_MultiPhaseEquil::equilibrate_SP(), Domain1D::eval(), AxiStagnFlow::eval(), FreeFlame::eval(), ReactionPathDiagram::exportToDot(), Cantera::factorOverlap(), MultiPhaseEquil::getComponents(), GeneralSpeciesThermo::install(), GeneralSpeciesThermo::install_STIT(), SpeciesThermoDuo< T1, T2 >::maxTemp(), LatticeSolidPhase::minTemp(), RootFind::solve(), BEulerInt::step(), Cantera::subtractRD(), BEulerInt::time_step_control(), GasKinetics::updateKc(), VCS_SOLVE::vcs_add_all_deleted(), VCS_SOLVE::vcs_basopt(), VCS_SOLVE::vcs_birthGuess(), and VCS_SOLVE::vcs_prob_specifyFully().
S ckr::pad (const S & s, size_t n) inline
Template to return a string equal to s, but padded with spaces on the right as necessary to make the length n.
Definition at line 85 of file ckr_utils.h.
References max().
Referenced by CKReader::read().
T ckr::absval (T x) inline
Absolute value.
Definition at line 95 of file ckr_utils.h.
Referenced by checkThermo().
bool ckr::valid (L & list) inline
Iterate through a list of objects that have a numeric member named 'valid', and return false if for any object this attribute is not greater than 0.
Otherwise return true.
Definition at line 112 of file ckr_utils.h.
Referenced by checkThermo(), CKReader::read(), CKParser::readElementSection(), and CKReader::validateSpecies().
bool ckr::isKeyword (std::string word) inline
Check whether string 'word' begins with a Chemkin keyword.
Definition at line 143 of file ckr_utils.h.
References match().
Referenced by CKParser::readElementSection(), CKParser::readNASA9ThermoRecord(), CKParser::readReactionSection(), CKParser::readSpeciesSection(), and CKParser::readThermoRecord().
bool ckr::checkThermo (std::ostream & log, speciesList & sp, double tol)
Check the thermodynamic property parameterizations for all species.
The following are verified:
The heat capacity is positive throughout the full temperature range;
The entropy at Tmin is positive;
The heat capacity, entropy, and enthalpy evaluated at Tmid using both the high and low polynomial coefficients are the same to within relative error tol
The heat capacity at Tmax is not greater than the equipartition limit for the number of atoms in the molecule
Definition at line 511 of file CKReader.cpp.
References absval(), cp(), Species::elements, enthalpy(), entropy(), Species::name, Species::thigh, Species::tlow, Species::tmid, Species::valid, and valid().
Referenced by CKReader::validateSpecies().
bool ckr::checkBalance (std::ostream & f, speciesTable & speciesData, reactionList & r, std::vector< int > & unbalanced, double tolerance)
Check that all reactions balance.
Parameters
speciesData species property dataset used to look up elemental compositions.
r list of reactions to check
unbalanced list of integers specifying reaction numbers of unbalanced reactions.
Returns
true if all reactions balance
Todo:
use reaction number stored in reaction object
Definition at line 686 of file CKReader.cpp.
References getMapKeys().
Referenced by CKReader::validateReactions().
static void ckr::addElement (std::string symbol, double atoms, Species & sp, std::ostream & log) static
Add an element to a species.
Parameters
symbol element symbol
atoms number of atoms of this element in the species (may be non-integral)
sp Species object to add element to
log log file output stream
Definition at line 39 of file NASA9Parser.cpp.
References Species::comp, Species::elements, Constituent::name, and Constituent::number.
static void ckr::illegalNumber (std::ostream & f, std::string s, int linenum = -1) static
Throw an exception if number string is bad.
Definition at line 56 of file NASA9Parser.cpp.
double cp (double t, const Species & s)
non-dimensional heat capacity (\(C_p/R \)) at constant P for one species
Parameters
t temperature
s species object
Definition at line 21 of file thermoFunctions.cpp.
References Species::highCoeffs, Species::lowCoeffs, Species::nTempRegions, Species::thermoFormatType, and Species::tmid.
Referenced by checkThermo(), PureFluidPhase::cp_mole(), RedlichKwongMFTP::cp_mole(), PDSS_Water::cp_mole(), RedlichKisterVPSSTP::cp_mole(), MargulesVPSSTP::cp_mole(), MixedSolventElectrolyte::cp_mole(), PhaseCombo_Interaction::cp_mole(), PDSS_Water::cp_R_ref(), HMWSoln::cv_mole(), enthalpy(), entropy(), WaterSSTP::getCp_R(), WaterSSTP::getCp_R_ref(), gibbs(), NasaPoly1::updateProperties(), ShomatePoly::updateProperties(), and MultiTransport::updateThermal_T().
double enthalpy (double t, const Species & s)
enthalpy in Kelvin (\(H/R \)) for one species.
Parameters
t temperature
s species object
Definition at line 55 of file thermoFunctions.cpp.
References cp(), Species::highCoeffs, Species::lowCoeffs, Species::nTempRegions, Species::thermoFormatType, and Species::tmid.
Referenced by checkThermo(), and gibbs().
double entropy (double t, const Species & s)
non-dimensional entropy (\(S/R \)) for one species
Parameters
t temperature
s species object
Definition at line 90 of file thermoFunctions.cpp.
References cp(), Species::highCoeffs, Species::lowCoeffs, Species::nTempRegions, Species::thermoFormatType, and Species::tmid.
Referenced by checkThermo(), and gibbs().
double gibbs (double t, const Species & s)
Gibbs function in Kelvin (\(G/R \)) for one species.
Parameters
t temperature
s species object
Definition at line 124 of file thermoFunctions.cpp.
References cp(), enthalpy(), entropy(), Species::highCoeffs, Species::lowCoeffs, Species::thermoFormatType, and Species::tmid.
std::string newTask (std::string msg)
format a string for the log file message printed when starting a new task
Definition at line 18 of file writelog.cpp.
Referenced by CKReader::read(), and CKReader::validateSpecies().
bool ckr::writeFalloff (int type, const vector_fp & c, std::ostream & log)
print the falloff parameters for a pressure-dependent reaction
Definition at line 27 of file writelog.cpp.
Referenced by CKReader::writeReactions().
bool writeRateCoeff (const RateCoeff & k, std::ostream & log)
print the rate coefficient parameters
Definition at line 86 of file writelog.cpp.
References RateCoeff::A, RateCoeff::B, RateCoeff::b, RateCoeff::C, RateCoeff::E, RateCoeff::n, and RateCoeff::type.
Referenced by CKReader::writeReactions().
void printReactionEquation (std::ostream & f, const Reaction & r)
Write onto an output stream the chemical equation for a reaction.
Definition at line 142 of file writelog.cpp.
References reactionEquation().
Referenced by CKReader::writeReactions().
std::string reactionEquation (const Reaction & r)
Write to a string the chemical equation for a reaction.
Definition at line 152 of file writelog.cpp.
References Reaction::isFalloffRxn, Reaction::isReversible, Reaction::isThreeBodyRxn, Reaction::products, Reaction::reactants, and Reaction::thirdBody.
Referenced by printReactionEquation().
void writeSpeciesData (std::ostream & log, const Species & spec)
Write a summary of the properties of one species to the log file.
Parameters
log log file output stream
spec instance of Species class
Definition at line 214 of file writelog.cpp.
References Species::elements, Species::highCoeffs, Species::id, Species::lowCoeffs, Species::nTempRegions, Species::phase, Species::thermoFormatType, Species::thigh, Species::tlow, and Species::tmid.
Referenced by CKParser::readNASA9ThermoSection(), and CKParser::readThermoSection().
Variable Documentation
double _weights[] static
Initial value:
= {
    1.00797,    4.0026,   6.939,    9.01220,   10.811,
    12.01115,    14.0067,  15.9994,  18.9984,    20.183,  22.9898,
    24.312,    26.9815,  28.086,  30.9738,    32.064,
    35.453,    39.948,   39.102,  40.08,      44.956,
    47.9,     50.942,  51.996,   54.938,     55.847,
    58.9332,   58.71,    63.54,   65.37,      69.72,
    72.59,     74.9216,  78.96,    79.9009,     83.8,
    85.47,   87.62,    88.905,  91.22,     92.9064,
    95.94,     98,      101.07,   102.906,    106.42,
    107.868,  112.41,   114.82,   118.71,     121.75,
    127.6,    126.905,  131.29,   132.905,    137.33,
    138.906,  140.12,   140.908,  144.24,     145,
    150.36,   151.96,   157.25,   158.925,    162.5,
    164.93,   167.26,   168.934,  173.04,     174.967,
    178.49,   180.948,  183.85,   186.207,    190.2,
    192.22,   195.08,   196.967,  200.59,     204.383,
    207.2,    208.98,   209,      210,        222,
    223,      226.025,  227.028,  232.038,    231.036,
    238.029,  237.048,  244,      243,        247,
    247,      251,      252,      257,        258,
    259,      269,      2.0141,   5.45e-4,    -1.0
}
Definition at line 18 of file atomicWeightDB.cpp.
char _symbols[][3] static
Initial value:
= {
    "H", "He", "Li", "Be", "B",
    "C", "N", "O", "F", "Ne", "Na",
    "Mg", "Al", "Si", "P", "S",
    "Cl", "Ar", "K", "Ca", "Sc",
    "Ti", "V", "Cr", "Mn", "Fe",
    "Co", "Ni", "Cu", "Zn", "Ga",
    "Ge", "As", "Se", "Br", "Kr",
    "Rb", "Sr", "Y", "Zr", "Nb",
    "Mo", "Tc", "Ru", "Rh", "Pd",
    "Ag", "Cd", "In", "Sn", "Sb",
    "Te", "I", "Xe", "Cs", "Ba",
    "La", "Ce", "Pr", "Nd", "Pm",
    "Sm", "Eu", "Gd", "Tb", "Dy",
    "Ho", "Er", "Tm", "Yb", "Lu",
    "Hf", "Ta", "W", "Re", "Os",
    "Ir", "Pt", "Au", "Hg", "Tl",
    "Pb", "Bi", "Po", "At", "Rn",
    "Fr", "Ra", "Ac", "Th", "Pa",
    "U", "Np", "Pu", "Am", "Cm",
    "Bk", "Cf", "Ei", "Fm", "Md",
    "No", "Lw", "D", "E", "!"
}
Definition at line 44 of file atomicWeightDB.cpp.
const int NoThermoDatabase = 10
readability constants
Definition at line 28 of file CKParser.h.
Referenced by CKReader::read(), and CKParser::readThermoSection().
const int Moles = 100
specify number of moles (6.023e23 molecules / mole)
Definition at line 85 of file ckr_defs.h.
Referenced by CKParser::readReactionSection().
const int Molecules = 101
specify number of molecules
Definition at line 86 of file ckr_defs.h.
Referenced by CKParser::readReactionSection().
const int Elementary = 2000
elementary, pressure-independent reaction
Definition at line 29 of file Reaction.h.
const int ThreeBody = 2001
three-body reaction
Definition at line 30 of file Reaction.h.
Referenced by CKParser::readReactionSection().
const int Falloff = 2002
falloff reaction
Definition at line 31 of file Reaction.h.
Referenced by CKParser::readReactionSection().
const int ChemAct = 2003
chemical activation reaction
Definition at line 32 of file Reaction.h.
Referenced by CKParser::readReactionSection().