Cantera: Integrator Class Reference
Integrator Class Reference
ODE Integrators
Abstract base class for ODE system integrators.
#include <Integrator.h>
Public Member Functions
Integrator ()
Default Constructor.
virtual ~Integrator ()
Destructor.
virtual void setTolerances (doublereal reltol, size_t n, doublereal *abstol)
Set or reset the number of equations.
virtual void setTolerances (doublereal reltol, doublereal abstol)
Set error tolerances.
virtual void setSensitivityTolerances (doublereal reltol, doublereal abstol)
Set the sensitivity error tolerances.
virtual void setProblemType (int probtype)
Set the problem type.
virtual void initialize (doublereal t0, FuncEval &func)
Initialize the integrator for a new problem.
virtual void reinitialize (doublereal t0, FuncEval &func)
virtual void integrate (doublereal tout)
Integrate the system of equations.
virtual doublereal step (doublereal tout)
Integrate the system of equations.
virtual doublereal & solution (size_t k)
The current value of the solution of equation k.
virtual doublereal * solution ()
The current value of the solution of the system of equations.
virtual int nEquations () const
The number of equations.
virtual int nEvals () const
The number of function evaluations.
virtual void setMaxOrder (int n)
Set the maximum integration order that will be used.
virtual void setMethod (MethodType t)
Set the solution method.
virtual void setIterator (IterType t)
Set the linear iterator.
virtual void setMaxStepSize (double hmax)
Set the maximum step size.
virtual void setMinStepSize (double hmin)
Set the minimum step size.
virtual void setMaxErrTestFails (int n)
Set the maximum permissible number of error test failures.
virtual void setMaxSteps (int nmax)
virtual void setBandwidth (int N_Upper, int N_Lower)
virtual int nSensParams ()
virtual double sensitivity (size_t k, size_t p)
Private Member Functions
void warn (const std::string &msg) const
Private Attributes
doublereal m_dummy
Detailed Description
Abstract base class for ODE system integrators.
Definition at line 52 of file Integrator.h.
Constructor & Destructor Documentation
Integrator () inline
Default Constructor.
Definition at line 56 of file Integrator.h.
virtual ~Integrator () inline virtual
Destructor.
Definition at line 60 of file Integrator.h.
Member Function Documentation
virtual void setTolerances (doublereal reltol, size_t n, doublereal * abstol) inline virtual
Set or reset the number of equations.
Set error tolerances.
Parameters
reltol scalar relative tolerance
n Number of equations
abstol array of N absolute tolerance values
Reimplemented in BEulerInt, CVodesIntegrator, and CVodeInt.
Definition at line 72 of file Integrator.h.
Referenced by ImplicitSurfChem::initialize(), and ReactorNet::initialize().
virtual void setTolerances (doublereal reltol, doublereal abstol) inline virtual
Set error tolerances.
Parameters
reltol scalar relative tolerance
abstol scalar absolute tolerance
Reimplemented in BEulerInt, CVodesIntegrator, and CVodeInt.
Definition at line 82 of file Integrator.h.
virtual void setSensitivityTolerances (doublereal reltol, doublereal abstol) inline virtual
Set the sensitivity error tolerances.
Parameters
reltol scalar relative tolerance
abstol scalar absolute tolerance
Reimplemented in CVodesIntegrator.
Definition at line 91 of file Integrator.h.
Referenced by ReactorNet::initialize().
virtual void setProblemType (int probtype) inline virtual
Set the problem type.
Parameters
probtype Type of the problem
Reimplemented in BEulerInt, CVodesIntegrator, and CVodeInt.
Definition at line 98 of file Integrator.h.
Referenced by ImplicitSurfChem::ImplicitSurfChem().
virtual void initialize (doublereal t0, FuncEval & func) inline virtual
Initialize the integrator for a new problem.
Call after all options have been set.
Parameters
t0 initial time
func RHS evaluator object for system of equations.
Reimplemented in CVodesIntegrator, and CVodeInt.
Definition at line 108 of file Integrator.h.
Referenced by ImplicitSurfChem::initialize(), ReactorNet::initialize(), and ImplicitSurfChem::integrate().
virtual void integrate (doublereal tout) inline virtual
Integrate the system of equations.
Parameters
tout Integrate to this time. Note that this is the absolute time value, not a time interval.
Reimplemented in CVodesIntegrator, and CVodeInt.
Definition at line 121 of file Integrator.h.
Referenced by ReactorNet::advance(), ImplicitSurfChem::integrate(), and ImplicitSurfChem::integrate0().
virtual doublereal step (doublereal tout) inline virtual
Integrate the system of equations.
Parameters
tout integrate to this time. Note that this is the absolute time value, not a time interval.
Reimplemented in BEulerInt, CVodesIntegrator, and CVodeInt.
Definition at line 130 of file Integrator.h.
Referenced by ReactorNet::step().
virtual doublereal& solution (size_t k) inline virtual
The current value of the solution of equation k.
Reimplemented in BEulerInt, CVodesIntegrator, and CVodeInt.
Definition at line 136 of file Integrator.h.
Referenced by ReactorNet::advance(), ImplicitSurfChem::integrate(), ImplicitSurfChem::integrate0(), ReactorNet::sensitivity(), and ReactorNet::step().
virtual doublereal* solution () inline virtual
The current value of the solution of the system of equations.
Reimplemented in BEulerInt, CVodesIntegrator, and CVodeInt.
Definition at line 142 of file Integrator.h.
virtual int nEquations () const inline virtual
The number of equations.
Reimplemented in BEulerInt, CVodesIntegrator, and CVodeInt.
Definition at line 148 of file Integrator.h.
virtual int nEvals () const inline virtual
The number of function evaluations.
Reimplemented in BEulerInt, CVodesIntegrator, and CVodeInt.
Definition at line 154 of file Integrator.h.
virtual void setMaxOrder (int n) inline virtual
Set the maximum integration order that will be used.
Reimplemented in CVodesIntegrator, and CVodeInt.
Definition at line 160 of file Integrator.h.
virtual void setMethod (MethodType t) inline virtual
Set the solution method.
Reimplemented in CVodesIntegrator, and CVodeInt.
Definition at line 165 of file Integrator.h.
Referenced by ImplicitSurfChem::ImplicitSurfChem().
virtual void setIterator (IterType t) inline virtual
Set the linear iterator.
Reimplemented in BEulerInt, CVodesIntegrator, and CVodeInt.
Definition at line 170 of file Integrator.h.
Referenced by ImplicitSurfChem::ImplicitSurfChem().
virtual void setMaxStepSize (double hmax) inline virtual
Set the maximum step size.
Reimplemented in CVodesIntegrator, and CVodeInt.
Definition at line 175 of file Integrator.h.
Referenced by ReactorNet::initialize(), and ImplicitSurfChem::integrate().
virtual void setMinStepSize (double hmin) inline virtual
Set the minimum step size.
Reimplemented in CVodesIntegrator, and CVodeInt.
Definition at line 180 of file Integrator.h.
virtual void setMaxErrTestFails (int n) inline virtual
Set the maximum permissible number of error test failures.
Reimplemented in CVodesIntegrator, and CVodeInt.
Definition at line 185 of file Integrator.h.
Referenced by ReactorNet::initialize().
The documentation for this class was generated from the following file:
Integrator.h