Cantera: FalloffMgr Class Reference
FalloffMgr Class Reference
Falloff Parameterizations This section describes the
A falloff manager that implements any set of falloff functions.
#include <FalloffMgr.h>
Public Member Functions
FalloffMgr ()
Constructor.
void install (size_t rxn, int falloffType, int reactionType, const vector_fp &c)
Install a new falloff function calculator.
void install (size_t rxn, int reactionType, shared_ptr< Falloff > f)
Install a new falloff function calculator.
void replace (size_t rxn, shared_ptr< Falloff > f)
size_t workSize ()
Size of the work array required to store intermediate results.
void updateTemp (doublereal t, doublereal *work)
Update the cached temperature-dependent intermediate results for all installed falloff functions.
void pr_to_falloff (doublereal *values, const doublereal *work)
Given a vector of reduced pressures for each falloff reaction, replace each entry by the value of the falloff function.
Protected Attributes
std::vector< size_t > m_rxn
std::vector< shared_ptr
< Falloff > > m_falloff
FalloffFactory * m_factory
vector_int m_loc
std::vector
< vector_fp::difference_type > m_offset
size_t m_worksize
vector_int m_reactionType
Distinguish between falloff and chemically activated reactions.
std::map< size_t, size_t > m_indices
map of external reaction index to local index
Detailed Description
A falloff manager that implements any set of falloff functions.
Definition at line 21 of file FalloffMgr.h.
Constructor & Destructor Documentation
FalloffMgr () inline
Constructor.
Definition at line 25 of file FalloffMgr.h.
References FalloffFactory::factory().
Member Function Documentation
void install (size_t rxn, int falloffType, int reactionType, const vector_fp & c) inline
Install a new falloff function calculator.
Definition at line 43 of file FalloffMgr.h.
References FalloffFactory::newFalloff(), and Cantera::warn_deprecated().
void install (size_t rxn, int reactionType, shared_ptr< Falloff > f) inline
Install a new falloff function calculator.
Definition at line 58 of file FalloffMgr.h.
References FalloffMgr::m_indices, and FalloffMgr::m_reactionType.
void replace (size_t rxn, shared_ptr< Falloff > f) inline
Replace an existing falloff function calculator
Parameters
rxn External reaction index
f New falloff function, of the same kind as the existing one
Definition at line 73 of file FalloffMgr.h.
References FalloffMgr::m_indices.
size_t workSize () inline
Size of the work array required to store intermediate results.
Definition at line 78 of file FalloffMgr.h.
Referenced by GasKinetics::finalize().
void updateTemp (doublereal t, doublereal * work) inline
Update the cached temperature-dependent intermediate results for all installed falloff functions.
Parameters
t Temperature [K].
work Work array. Must be dimensioned at least workSize().
Definition at line 88 of file FalloffMgr.h.
Referenced by GasKinetics::update_rates_T().
void pr_to_falloff (doublereal * values, const doublereal * work) inline
Given a vector of reduced pressures for each falloff reaction, replace each entry by the value of the falloff function.
Definition at line 98 of file FalloffMgr.h.
References Cantera::FALLOFF_RXN, and FalloffMgr::m_reactionType.
Member Data Documentation
vector_int m_reactionType protected
Distinguish between falloff and chemically activated reactions.
Definition at line 122 of file FalloffMgr.h.
Referenced by FalloffMgr::install(), and FalloffMgr::pr_to_falloff().
std::map<size_t, size_t> m_indices protected
map of external reaction index to local index
Definition at line 125 of file FalloffMgr.h.
Referenced by FalloffMgr::install(), and FalloffMgr::replace().
The documentation for this class was generated from the following file:
FalloffMgr.h