Cantera: StatMech Class Reference
StatMech Class Reference
Species Reference-State Thermodynamic Properties
Statistical mechanics.
#include <StatMech.h>
Public Member Functions
StatMech ()
Empty constructor.
StatMech (int n, doublereal tlow, doublereal thigh, doublereal pref, const doublereal *coeffs, const std::string &my_name)
constructor used in templated instantiations
StatMech (const StatMech &b)
copy constructor
StatMech & operator= (const StatMech &b)
assignment operator
virtual SpeciesThermoInterpType * duplMyselfAsSpeciesThermoInterpType () const
duplicator
virtual int reportType () const
Returns an integer representing the type of parameterization.
int buildmap ()
Build a series of maps for the properties needed for species.
virtual void updateProperties (const doublereal *tt, doublereal *cp_R, doublereal *h_RT, doublereal *s_R) const
Update the properties for this species, given a temperature polynomial.
virtual void updatePropertiesTemp (const doublereal temp, doublereal *cp_R, doublereal *h_RT, doublereal *s_R) const
Compute the reference-state property of one species.
virtual void reportParameters (size_t &n, int &type, doublereal &tlow, doublereal &thigh, doublereal &pref, doublereal *const coeffs) const
This utility function reports back the type of parameterization and all of the parameters for the species, index.
virtual void modifyParameters (doublereal *coeffs)
Modify parameters for the standard state.
Public Member Functions inherited from SpeciesThermoInterpType
SpeciesThermoInterpType (size_t n, doublereal tlow, doublereal thigh, doublereal pref)
SpeciesThermoInterpType (double tlow, double thigh, double pref)
SpeciesThermoInterpType (const SpeciesThermoInterpType &b)
virtual doublereal minTemp () const
Returns the minimum temperature that the thermo parameterization is valid.
virtual doublereal maxTemp () const
Returns the maximum temperature that the thermo parameterization is valid.
virtual doublereal refPressure () const
Returns the reference pressure (Pa)
virtual void validate (const std::string &name)
Check for problems with the parameterization, and generate warnings or throw and exception if any are found.
virtual size_t speciesIndex () const
Returns an integer representing the species index.
virtual void setIndex (size_t index)
virtual size_t temperaturePolySize () const
Number of terms in the temperature polynomial for this parameterization.
virtual void updateTemperaturePoly (double T, double *T_poly) const
Given the temperature T, compute the terms of the temperature polynomial T_poly.
virtual doublereal reportHf298 (doublereal *const h298=0) const
Report the 298 K Heat of Formation of the standard state of one species (J kmol-1)
virtual void modifyOneHf298 (const size_t k, const doublereal Hf298New)
Modify the value of the 298 K Heat of Formation of one species in the phase (J kmol-1)
Protected Attributes
vector_fp m_coeff
array of polynomial coefficients
std::string sp_name
std::map< std::string, species * > name_map
Protected Attributes inherited from SpeciesThermoInterpType
doublereal m_lowT
lowest valid temperature
doublereal m_highT
Highest valid temperature.
doublereal m_Pref
Reference state pressure.
size_t m_index
species index
Detailed Description
Statistical mechanics.
Deprecated:
Incomplete stub class, to be removed after Cantera 2.2.
Definition at line 27 of file StatMech.h.
Constructor & Destructor Documentation
StatMech ()
Empty constructor.
Definition at line 13 of file StatMech.cpp.
References Cantera::warn_deprecated().
Referenced by StatMech::duplMyselfAsSpeciesThermoInterpType().
StatMech (int n, doublereal tlow, doublereal thigh, doublereal pref, const doublereal * coeffs, const std::string & my_name)
constructor used in templated instantiations
Parameters
n Species index
tlow Minimum temperature
thigh Maximum temperature
pref reference pressure (Pa).
coeffs Vector of coefficients used to set the parameters for the standard state.
Definition at line 17 of file StatMech.cpp.
References StatMech::buildmap(), and SpeciesThermoInterpType::m_lowT.
StatMech (const StatMech & b)
copy constructor
Parameters
b object to be copied
Definition at line 32 of file StatMech.cpp.
Member Function Documentation
StatMech & operator= (const StatMech & b)
assignment operator
Parameters
b object to be copied
Definition at line 37 of file StatMech.cpp.
SpeciesThermoInterpType * duplMyselfAsSpeciesThermoInterpType () const virtual
duplicator
Implements SpeciesThermoInterpType.
Definition at line 46 of file StatMech.cpp.
References StatMech::StatMech().
int reportType () const virtual
Returns an integer representing the type of parameterization.
Implements SpeciesThermoInterpType.
Definition at line 51 of file StatMech.cpp.
References STAT.
int buildmap ()
Build a series of maps for the properties needed for species.
Definition at line 56 of file StatMech.cpp.
Referenced by StatMech::StatMech().
void updateProperties (const doublereal * tt, doublereal * cp_R, doublereal * h_RT, doublereal * s_R) const virtual
Update the properties for this species, given a temperature polynomial.
This method is called with a pointer to an array containing the functions of temperature needed by this parameterization, and three pointers to arrays where the computed property values should be written. This method updates only one value in each array.
\[ \frac{C_p^0(T)}{R} = \frac{C_v^0(T)}{R} + 1 \]
Where,
\[ \frac{C_v^0(T)}{R} = \frac{C_v^{tr}(T)}{R} + \frac{C_v^{vib}(T)}{R} \]
Temperature Polynomial: tt[0] = t;
Parameters
tt vector of temperature polynomials
cp_R Vector of Dimensionless heat capacities. (length m_kk).
h_RT Vector of Dimensionless enthalpies. (length m_kk).
s_R Vector of Dimensionless entropies. (length m_kk).
Reimplemented from SpeciesThermoInterpType.
Definition at line 554 of file StatMech.cpp.
References Cantera::GasConstant, and SpeciesThermoInterpType::m_index.
Referenced by StatMech::updatePropertiesTemp().
void updatePropertiesTemp (const doublereal temp, doublereal * cp_R, doublereal * h_RT, doublereal * s_R) const virtual
Compute the reference-state property of one species.
Given temperature T in K, this method updates the values of the non- dimensional heat capacity at constant pressure, enthalpy, and entropy, at the reference pressure, Pref of one of the species. The species index is used to reference into the cp_R, h_RT, and s_R arrays.
Parameters
temp Temperature (Kelvin)
cp_R Vector of Dimensionless heat capacities. (length m_kk).
h_RT Vector of Dimensionless enthalpies. (length m_kk).
s_R Vector of Dimensionless entropies. (length m_kk).
Implements SpeciesThermoInterpType.
Definition at line 599 of file StatMech.cpp.
References StatMech::updateProperties().
void reportParameters (size_t & n, int & type, doublereal & tlow, doublereal & thigh, doublereal & pref, doublereal *const coeffs) const virtual
This utility function reports back the type of parameterization and all of the parameters for the species, index.
All parameters are output variables
Parameters
n Species index
type Integer type of the standard type
tlow output - Minimum temperature
thigh output - Maximum temperature
pref output - reference pressure (Pa).
coeffs Vector of coefficients used to set the parameters for the standard state. There are 12 of them, designed to be compatible with the multiple temperature formulation. coeffs[0] is equal to one. coeffs[1] is min temperature coeffs[2] is max temperature coeffs[3+i] from i =0,9 are the coefficients themselves
Implements SpeciesThermoInterpType.
Definition at line 608 of file StatMech.cpp.
References Cantera::GasConstant, SpeciesThermoInterpType::m_highT, SpeciesThermoInterpType::m_index, SpeciesThermoInterpType::m_lowT, SpeciesThermoInterpType::m_Pref, and STAT.
void modifyParameters (doublereal * coeffs) virtual
Modify parameters for the standard state.
Parameters
coeffs Vector of coefficients used to set the parameters for the standard state.
Reimplemented from SpeciesThermoInterpType.
Definition at line 651 of file StatMech.cpp.
Member Data Documentation
vector_fp m_coeff protected
array of polynomial coefficients
Definition at line 146 of file StatMech.h.
The documentation for this class was generated from the following files:
StatMech.h
StatMech.cpp