Cantera: Nasa9Poly1 Class Reference
Nasa9Poly1 Class Reference
Species Reference-State Thermodynamic Properties
The NASA 9 polynomial parameterization for one temperature range.
#include <Nasa9Poly1.h>
Public Member Functions
Nasa9Poly1 ()
Empty constructor.
Nasa9Poly1 (size_t n, doublereal tlow, doublereal thigh, doublereal pref, const doublereal *coeffs)
constructor used in templated instantiations
Nasa9Poly1 (double tlow, double thigh, double pref, const double *coeffs)
Normal constructor.
Nasa9Poly1 (const Nasa9Poly1 &b)
copy constructor
Nasa9Poly1 & operator= (const Nasa9Poly1 &b)
assignment operator
virtual SpeciesThermoInterpType * duplMyselfAsSpeciesThermoInterpType () const
virtual int reportType () const
Returns an integer representing the type of parameterization.
virtual size_t temperaturePolySize () const
Number of terms in the temperature polynomial for this parameterization.
virtual void updateTemperaturePoly (double T, double *T_poly) const
Given the temperature T, compute the terms of the temperature polynomial T_poly.
virtual void updateProperties (const doublereal *tt, doublereal *cp_R, doublereal *h_RT, doublereal *s_R) const
Update the properties for this species, given a temperature polynomial.
virtual void updatePropertiesTemp (const doublereal temp, doublereal *cp_R, doublereal *h_RT, doublereal *s_R) const
Compute the reference-state property of one species.
virtual void reportParameters (size_t &n, int &type, doublereal &tlow, doublereal &thigh, doublereal &pref, doublereal *const coeffs) const
This utility function reports back the type of parameterization and all of the parameters for the species, index.
virtual void modifyParameters (doublereal *coeffs)
Modify parameters for the standard state.
Public Member Functions inherited from SpeciesThermoInterpType
SpeciesThermoInterpType (size_t n, doublereal tlow, doublereal thigh, doublereal pref)
SpeciesThermoInterpType (double tlow, double thigh, double pref)
SpeciesThermoInterpType (const SpeciesThermoInterpType &b)
virtual doublereal minTemp () const
Returns the minimum temperature that the thermo parameterization is valid.
virtual doublereal maxTemp () const
Returns the maximum temperature that the thermo parameterization is valid.
virtual doublereal refPressure () const
Returns the reference pressure (Pa)
virtual void validate (const std::string &name)
Check for problems with the parameterization, and generate warnings or throw and exception if any are found.
virtual size_t speciesIndex () const
Returns an integer representing the species index.
virtual void setIndex (size_t index)
virtual doublereal reportHf298 (doublereal *const h298=0) const
Report the 298 K Heat of Formation of the standard state of one species (J kmol-1)
virtual void modifyOneHf298 (const size_t k, const doublereal Hf298New)
Modify the value of the 298 K Heat of Formation of one species in the phase (J kmol-1)
Protected Attributes
vector_fp m_coeff
array of polynomial coefficients
Protected Attributes inherited from SpeciesThermoInterpType
doublereal m_lowT
lowest valid temperature
doublereal m_highT
Highest valid temperature.
doublereal m_Pref
Reference state pressure.
size_t m_index
species index
Detailed Description
The NASA 9 polynomial parameterization for one temperature range.
This parameterization expresses the heat capacity via a 7 coefficient polynomial. Note that this is the form used in the 2002 NASA equilibrium program. A reference to the form is provided below:
"NASA Glenn Coefficients for Calculating Thermodynamic Properties of Individual Species," B. J. McBride, M. J. Zehe, S. Gordon NASA/TP-2002-211556, Sept. 2002
Nine coefficients \((a_0,\dots,a_8)\) are used to represent \(C_p^0(T)\), \(H^0(T)\), and \(S^0(T) \) as polynomials in \(T \) :
\[ \frac{C_p^0(T)}{R} = a_0 T^{-2} + a_1 T^{-1} + a_2 + a_3 T + a_4 T^2 + a_5 T^3 + a_6 T^4 \]
\[ \frac{H^0(T)}{RT} = - a_0 T^{-2} + a_1 \frac{\ln T}{T} + a_2 + \frac{a_3}{2} T + \frac{a_4}{3} T^2 + \frac{a_5}{4} T^3 + \frac{a_6}{5} T^4 + \frac{a_7}{T} \]
\[ \frac{s^0(T)}{R} = - \frac{a_0}{2} T^{-2} - a_1 T^{-1} + a_2 \ln T + a_3 T + \frac{a_4}{2} T^2 + \frac{a_5}{3} T^3 + \frac{a_6}{4} T^4 + a_8 \]
The standard state is assumed to be an ideal gas at the standard pressure of 1 bar, for gases. For condensed species, the standard state is the pure crystalline or liquid substance at the standard pressure of 1 atm.
These NASA representations may have multiple temperature regions through the use of the Nasa9PolyMultiTempRegion object, which uses multiple copies of this Nasa9Poly1 object to handle multiple temperature regions.
See Also
Nasa9PolyMultiTempRegion
Definition at line 71 of file Nasa9Poly1.h.
Constructor & Destructor Documentation
Nasa9Poly1 ()
Empty constructor.
Definition at line 18 of file Nasa9Poly1.cpp.
References SpeciesThermoInterpType::m_Pref.
Nasa9Poly1 (size_t n, doublereal tlow, doublereal thigh, doublereal pref, const doublereal * coeffs)
constructor used in templated instantiations
Parameters
n Species index
tlow Minimum temperature
thigh Maximum temperature
pref reference pressure (Pa).
coeffs Vector of coefficients used to set the parameters for the standard state.
Deprecated:
Use the constructor whic hdoes not require the species index. To be removed after Cantera 2.2.
Definition at line 24 of file Nasa9Poly1.cpp.
Nasa9Poly1 (double tlow, double thigh, double pref, const double * coeffs)
Normal constructor.
Parameters
tlow Minimum temperature
thigh Maximum temperature
pref reference pressure (Pa).
coeffs Vector of coefficients used to set the parameters for the standard state.
Definition at line 32 of file Nasa9Poly1.cpp.
Nasa9Poly1 (const Nasa9Poly1 & b)
copy constructor
Parameters
b object to be copied
Definition at line 39 of file Nasa9Poly1.cpp.
Member Function Documentation
Nasa9Poly1 & operator= (const Nasa9Poly1 & b)
assignment operator
Parameters
b object to be copied
Definition at line 45 of file Nasa9Poly1.cpp.
References Nasa9Poly1::m_coeff.
int reportType () const virtual
Returns an integer representing the type of parameterization.
Implements SpeciesThermoInterpType.
Definition at line 60 of file Nasa9Poly1.cpp.
References NASA9.
virtual size_t temperaturePolySize () const inline virtual
Number of terms in the temperature polynomial for this parameterization.
Reimplemented from SpeciesThermoInterpType.
Definition at line 118 of file Nasa9Poly1.h.
void updateTemperaturePoly (double T, double * T_poly) const virtual
Given the temperature T, compute the terms of the temperature polynomial T_poly.
Reimplemented from SpeciesThermoInterpType.
Definition at line 65 of file Nasa9Poly1.cpp.
Referenced by Nasa9Poly1::updatePropertiesTemp().
void updateProperties (const doublereal * tt, doublereal * cp_R, doublereal * h_RT, doublereal * s_R) const virtual
Update the properties for this species, given a temperature polynomial.
This method is called with a pointer to an array containing the functions of temperature needed by this parameterization, and three pointers to arrays where the computed property values should be written. This method updates only one value in each array.
Temperature Polynomial: tt[0] = t; tt[1] = t*t; tt[2] = t*t*t; tt[3] = t*t*t*t; tt[4] = 1.0/t; tt[5] = 1.0/(t*t); tt[6] = std::log(t);
Parameters
tt vector of temperature polynomials
cp_R Vector of Dimensionless heat capacities. (length m_kk).
h_RT Vector of Dimensionless enthalpies. (length m_kk).
s_R Vector of Dimensionless entropies. (length m_kk).
Reimplemented from SpeciesThermoInterpType.
Definition at line 76 of file Nasa9Poly1.cpp.
References Nasa9Poly1::m_coeff, and SpeciesThermoInterpType::m_index.
Referenced by Nasa9Poly1::updatePropertiesTemp().
void updatePropertiesTemp (const doublereal temp, doublereal * cp_R, doublereal * h_RT, doublereal * s_R) const virtual
Compute the reference-state property of one species.
Given temperature T in K, this method updates the values of the non- dimensional heat capacity at constant pressure, enthalpy, and entropy, at the reference pressure, Pref of one of the species. The species index is used to reference into the cp_R, h_RT, and s_R arrays.
Temperature Polynomial: tt[0] = t; tt[1] = t*t; tt[2] = t*t*t; tt[3] = t*t*t*t; tt[4] = 1.0/t; tt[5] = 1.0/(t*t); tt[6] = std::log(t);
Parameters
temp Temperature (Kelvin)
cp_R Vector of Dimensionless heat capacities. (length m_kk).
h_RT Vector of Dimensionless enthalpies. (length m_kk).
s_R Vector of Dimensionless entropies. (length m_kk).
Implements SpeciesThermoInterpType.
Definition at line 103 of file Nasa9Poly1.cpp.
References Nasa9Poly1::updateProperties(), and Nasa9Poly1::updateTemperaturePoly().
void reportParameters (size_t & n, int & type, doublereal & tlow, doublereal & thigh, doublereal & pref, doublereal *const coeffs) const virtual
This utility function reports back the type of parameterization and all of the parameters for the species, index.
All parameters are output variables
Parameters
n Species index
type Integer type of the standard type
tlow output - Minimum temperature
thigh output - Maximum temperature
pref output - reference pressure (Pa).
coeffs Vector of coefficients used to set the parameters for the standard state. There are 12 of them, designed to be compatible with the multiple temperature formulation. coeffs[0] is equal to one. coeffs[1] is min temperature coeffs[2] is max temperature coeffs[3+i] from i =0,9 are the coefficients themselves
Implements SpeciesThermoInterpType.
Definition at line 112 of file Nasa9Poly1.cpp.
References Nasa9Poly1::m_coeff, SpeciesThermoInterpType::m_highT, SpeciesThermoInterpType::m_index, SpeciesThermoInterpType::m_lowT, SpeciesThermoInterpType::m_Pref, and NASA9.
void modifyParameters (doublereal * coeffs) virtual
Modify parameters for the standard state.
Parameters
coeffs Vector of coefficients used to set the parameters for the standard state.
Reimplemented from SpeciesThermoInterpType.
Definition at line 130 of file Nasa9Poly1.cpp.
References Nasa9Poly1::m_coeff.
Member Data Documentation
vector_fp m_coeff protected
array of polynomial coefficients
Definition at line 204 of file Nasa9Poly1.h.
Referenced by Nasa9Poly1::modifyParameters(), Nasa9Poly1::operator=(), Nasa9Poly1::reportParameters(), and Nasa9Poly1::updateProperties().
The documentation for this class was generated from the following files:
Nasa9Poly1.h
Nasa9Poly1.cpp