Cantera: Reaction Class Reference
Reaction Class Reference
Intermediate class which stores data about a reaction and its rate parameterization so that it can be added to a Kinetics object.
#include <Reaction.h>
Public Member Functions
Reaction (int type)
Reaction (int type, const Composition &reactants, const Composition &products)
virtual std::string reactantString () const
The reactant side of the chemical equation for this reaction.
virtual std::string productString () const
The product side of the chemical equation for this reaction.
std::string equation () const
The chemical equation for this reaction.
virtual void validate ()
Ensure that the rate constant and other parameters for this reaction are valid.
Public Attributes
int reaction_type
Type of the reaction.
Composition reactants
Reactant species and stoichiometric coefficients.
Composition products
Product species and stoichiometric coefficients.
Composition orders
Forward reaction order with respect to specific species.
std::string id
An identification string for the reaction, used in some filtering operations.
bool reversible
True if the current reaction is reversible. False otherwise.
bool duplicate
True if the current reaction is marked as duplicate.
bool allow_nonreactant_orders
True if reaction orders can be specified for non-reactant species.
bool allow_negative_orders
True if negative reaction orders are allowed. Default is false.
Detailed Description
Intermediate class which stores data about a reaction and its rate parameterization so that it can be added to a Kinetics object.
Definition at line 20 of file Reaction.h.
Member Function Documentation
std::string reactantString () const virtual
The reactant side of the chemical equation for this reaction.
Reimplemented in FalloffReaction, and ThreeBodyReaction.
Definition at line 60 of file Reaction.cpp.
Referenced by ThreeBodyReaction::reactantString(), and FalloffReaction::reactantString().
std::string productString () const virtual
The product side of the chemical equation for this reaction.
Reimplemented in FalloffReaction, and ThreeBodyReaction.
Definition at line 77 of file Reaction.cpp.
Referenced by ThreeBodyReaction::productString(), and FalloffReaction::productString().
std::string equation () const
The chemical equation for this reaction.
Definition at line 94 of file Reaction.cpp.
Referenced by InterfaceKinetics::buildSurfaceArrhenius(), Kinetics::checkDuplicates(), Kinetics::checkReactionBalance(), ElementaryReaction::validate(), FalloffReaction::validate(), and PlogReaction::validate().
void validate () virtual
Ensure that the rate constant and other parameters for this reaction are valid.
Reimplemented in PlogReaction, FalloffReaction, and ElementaryReaction.
Definition at line 35 of file Reaction.cpp.
Referenced by ElementaryReaction::validate(), FalloffReaction::validate(), and PlogReaction::validate().
Member Data Documentation
int reaction_type
Type of the reaction.
The valid types are listed in the file, reaction_defs.h, with constants ending in RXN.
Definition at line 43 of file Reaction.h.
Referenced by InterfaceKinetics::addReaction(), and Kinetics::checkDuplicates().
Composition reactants
Reactant species and stoichiometric coefficients.
Definition at line 46 of file Reaction.h.
Referenced by InterfaceKinetics::addReaction(), InterfaceKinetics::buildSurfaceArrhenius(), Kinetics::checkDuplicates(), and Kinetics::checkReactionBalance().
Composition products
Product species and stoichiometric coefficients.
Definition at line 49 of file Reaction.h.
Referenced by InterfaceKinetics::addReaction(), Kinetics::checkDuplicates(), and Kinetics::checkReactionBalance().
Composition orders
Forward reaction order with respect to specific species.
By default, mass-action kinetics is assumed, with the reaction order equal to each reactant's stoichiometric coefficient.
Definition at line 54 of file Reaction.h.
Referenced by InterfaceKinetics::addReaction(), and InterfaceKinetics::buildSurfaceArrhenius().
std::string id
An identification string for the reaction, used in some filtering operations.
Definition at line 58 of file Reaction.h.
bool reversible
True if the current reaction is reversible. False otherwise.
Definition at line 61 of file Reaction.h.
Referenced by InterfaceKinetics::addReaction(), and Kinetics::checkDuplicates().
bool duplicate
True if the current reaction is marked as duplicate.
Definition at line 64 of file Reaction.h.
Referenced by Kinetics::checkDuplicates().
bool allow_nonreactant_orders
True if reaction orders can be specified for non-reactant species.
Default is false.
Definition at line 68 of file Reaction.h.
bool allow_negative_orders
True if negative reaction orders are allowed. Default is false.
Definition at line 71 of file Reaction.h.
The documentation for this class was generated from the following files:
Reaction.h
Reaction.cpp