Cantera: SurfPhase Class Reference
SurfPhase Class Reference
Thermodynamic Properties
A simple thermodynamic model for a surface phase, assuming an ideal solution model.
#include <SurfPhase.h>
Public Member Functions
SurfPhase (doublereal n0=1.0)
Constructor.
SurfPhase (const std::string &infile, std::string id)
Construct and initialize a SurfPhase ThermoPhase object directly from an ASCII input file.
SurfPhase (XML_Node &xmlphase)
Construct and initialize a SurfPhase ThermoPhase object directly from an XML database.
SurfPhase (const SurfPhase &right)
Copy Constructor.
SurfPhase & operator= (const SurfPhase &right)
Assignment operator.
ThermoPhase * duplMyselfAsThermoPhase () const
Duplicator from the ThermoPhase parent class.
virtual int eosType () const
Equation of state type flag.
virtual doublereal enthalpy_mole () const
Return the Molar Enthalpy. Units: J/kmol.
virtual doublereal intEnergy_mole () const
Return the Molar Internal Energy. Units: J/kmol.
virtual doublereal entropy_mole () const
Return the Molar Entropy. Units: J/kmol-K.
virtual doublereal cp_mole () const
Molar heat capacity at constant pressure. Units: J/kmol/K.
virtual doublereal cv_mole () const
Molar heat capacity at constant volume. Units: J/kmol/K.
virtual void getChemPotentials (doublereal *mu) const
Get the species chemical potentials. Units: J/kmol.
virtual void getPartialMolarEnthalpies (doublereal *hbar) const
Returns an array of partial molar enthalpies for the species in the mixture.
virtual void getPartialMolarEntropies (doublereal *sbar) const
Returns an array of partial molar entropies of the species in the solution.
virtual void getPartialMolarCp (doublereal *cpbar) const
Return an array of partial molar heat capacities for the species in the mixture.
virtual void getPartialMolarVolumes (doublereal *vbar) const
Return an array of partial molar volumes for the species in the mixture.
virtual void getStandardChemPotentials (doublereal *mu0) const
Get the array of chemical potentials at unit activity for the standard state species at the current T and P of the solution.
virtual void getActivityConcentrations (doublereal *c) const
Return a vector of activity concentrations for each species.
virtual doublereal standardConcentration (size_t k=0) const
Return the standard concentration for the kth species.
virtual doublereal logStandardConc (size_t k=0) const
Return the log of the standard concentration for the kth species.
virtual void setParameters (int n, doublereal *const c)
Set the equation of state parameters from the argument list.
virtual void setParametersFromXML (const XML_Node &thermoData)
Set the Equation-of-State parameters by reading an XML Node Input.
virtual void initThermo ()
Initialize the SurfPhase object after all species have been set up.
virtual void setStateFromXML (const XML_Node &state)
Set the initial state of the Surface Phase from an XML_Node.
doublereal siteDensity ()
Returns the site density.
void setSiteDensity (doublereal n0)
Set the site density of the surface phase (kmol m-2)
virtual void getGibbs_RT (doublereal *grt) const
Get the nondimensional Gibbs functions for the species in their standard states at the current T and P of the solution.
virtual void getEnthalpy_RT (doublereal *hrt) const
Get the nondimensional Enthalpy functions for the species standard states at their standard states at the current T and P of the solution.
virtual void getEntropy_R (doublereal *sr) const
Get the array of nondimensional Entropy functions for the species standard states at the current T and P of the solution.
virtual void getCp_R (doublereal *cpr) const
Get the nondimensional Heat Capacities at constant pressure for the species standard states at the current T and P of the solution.
virtual void getStandardVolumes (doublereal *vol) const
Get the molar volumes of the species standard states at the current T and P of the solution.
virtual doublereal pressure () const
Return the thermodynamic pressure (Pa).
virtual void setPressure (doublereal p)
Set the internally stored pressure (Pa) at constant temperature and composition.
virtual void getPureGibbs (doublereal *g) const
Get the Gibbs functions for the standard state of the species at the current T and P of the solution.
virtual void getGibbs_RT_ref (doublereal *grt) const
Returns the vector of nondimensional Gibbs Free Energies of the reference state at the current temperature of the solution and the reference pressure for the species.
virtual void getEnthalpy_RT_ref (doublereal *hrt) const
Returns the vector of nondimensional enthalpies of the reference state at the current temperature of the solution and the reference pressure for the species.
virtual void getEntropy_R_ref (doublereal *er) const
Returns the vector of nondimensional entropies of the reference state at the current temperature of the solution and the reference pressure for each species.
virtual void getCp_R_ref (doublereal *cprt) const
Returns the vector of nondimensional constant pressure heat capacities of the reference state at the current temperature of the solution and reference pressure for each species.
void setCoverages (const doublereal *theta)
Set the surface site fractions to a specified state.
void setCoveragesNoNorm (const doublereal *theta)
Set the surface site fractions to a specified state.
void setCoveragesByName (const std::string &cov)
Set the coverages from a string of colon-separated name:value pairs.
void setCoveragesByName (const compositionMap &cov)
Set the coverages from a map of name:value pairs.
void getCoverages (doublereal *theta) const
Return a vector of surface coverages.
Public Member Functions inherited from ThermoPhase
ThermoPhase ()
Constructor.
virtual ~ThermoPhase ()
Destructor. Deletes the species thermo manager.
ThermoPhase (const ThermoPhase &right)
Copy Constructor for the ThermoPhase object.
ThermoPhase & operator= (const ThermoPhase &right)
Assignment operator.
doublereal _RT () const
Return the Gas Constant multiplied by the current temperature.
virtual doublereal refPressure () const
Returns the reference pressure in Pa.
virtual doublereal minTemp (size_t k=npos) const
Minimum temperature for which the thermodynamic data for the species or phase are valid.
doublereal Hf298SS (const int k) const
Report the 298 K Heat of Formation of the standard state of one species (J kmol-1)
virtual void modifyOneHf298SS (const size_t k, const doublereal Hf298New)
Modify the value of the 298 K Heat of Formation of one species in the phase (J kmol-1)
virtual doublereal maxTemp (size_t k=npos) const
Maximum temperature for which the thermodynamic data for the species are valid.
bool chargeNeutralityNecessary () const
Returns the chargeNeutralityNecessity boolean.
virtual doublereal gibbs_mole () const
Molar Gibbs function. Units: J/kmol.
virtual doublereal cv_vib (int, double) const
virtual doublereal isothermalCompressibility () const
Returns the isothermal compressibility. Units: 1/Pa.
virtual doublereal thermalExpansionCoeff () const
Return the volumetric thermal expansion coefficient. Units: 1/K.
void setElectricPotential (doublereal v)
Set the electric potential of this phase (V).
doublereal electricPotential () const
Returns the electric potential of this phase (V).
virtual int activityConvention () const
This method returns the convention used in specification of the activities, of which there are currently two, molar- and molality-based conventions.
virtual int standardStateConvention () const
This method returns the convention used in specification of the standard state, of which there are currently two, temperature based, and variable pressure based.
virtual void getUnitsStandardConc (double *uA, int k=0, int sizeUA=6) const
Returns the units of the standard and generalized concentrations.
virtual void getActivities (doublereal *a) const
Get the array of non-dimensional activities at the current solution temperature, pressure, and solution concentration.
virtual void getActivityCoefficients (doublereal *ac) const
Get the array of non-dimensional molar-based activity coefficients at the current solution temperature, pressure, and solution concentration.
virtual void getLnActivityCoefficients (doublereal *lnac) const
Get the array of non-dimensional molar-based ln activity coefficients at the current solution temperature, pressure, and solution concentration.
virtual void getChemPotentials_RT (doublereal *mu) const
Get the array of non-dimensional species chemical potentials These are partial molar Gibbs free energies.
void getElectrochemPotentials (doublereal *mu) const
Get the species electrochemical potentials.
virtual void getPartialMolarIntEnergies (doublereal *ubar) const
Return an array of partial molar internal energies for the species in the mixture.
virtual void getdPartialMolarVolumes_dT (doublereal *d_vbar_dT) const
Return an array of derivatives of partial molar volumes wrt temperature for the species in the mixture.
virtual void getdPartialMolarVolumes_dP (doublereal *d_vbar_dP) const
Return an array of derivatives of partial molar volumes wrt pressure for the species in the mixture.
virtual void getIntEnergy_RT (doublereal *urt) const
Returns the vector of nondimensional Internal Energies of the standard state species at the current T and P of the solution.
virtual void getdStandardVolumes_dT (doublereal *d_vol_dT) const
Get the derivative of the molar volumes of the species standard states wrt temperature at the current T and P of the solution.
virtual void getdStandardVolumes_dP (doublereal *d_vol_dP) const
Get the derivative molar volumes of the species standard states wrt pressure at the current T and P of the solution.
virtual void getGibbs_ref (doublereal *g) const
Returns the vector of the Gibbs function of the reference state at the current temperature of the solution and the reference pressure for the species.
virtual void getIntEnergy_RT_ref (doublereal *urt) const
Returns the vector of nondimensional internal Energies of the reference state at the current temperature of the solution and the reference pressure for each species.
virtual void getStandardVolumes_ref (doublereal *vol) const
Get the molar volumes of the species reference states at the current T and P_ref of the solution.
virtual void setReferenceComposition (const doublereal *const x)
Sets the reference composition.
virtual void getReferenceComposition (doublereal *const x) const
Gets the reference composition.
doublereal enthalpy_mass () const
Specific enthalpy.
doublereal intEnergy_mass () const
Specific internal energy.
doublereal entropy_mass () const
Specific entropy.
doublereal gibbs_mass () const
Specific Gibbs function.
doublereal cp_mass () const
Specific heat at constant pressure.
doublereal cv_mass () const
Specific heat at constant volume.
virtual void setState_TPX (doublereal t, doublereal p, const doublereal *x)
Set the temperature (K), pressure (Pa), and mole fractions.
virtual void setState_TPX (doublereal t, doublereal p, const compositionMap &x)
Set the temperature (K), pressure (Pa), and mole fractions.
virtual void setState_TPX (doublereal t, doublereal p, const std::string &x)
Set the temperature (K), pressure (Pa), and mole fractions.
virtual void setState_TPY (doublereal t, doublereal p, const doublereal *y)
Set the internally stored temperature (K), pressure (Pa), and mass fractions of the phase.
virtual void setState_TPY (doublereal t, doublereal p, const compositionMap &y)
Set the internally stored temperature (K), pressure (Pa), and mass fractions of the phase.
virtual void setState_TPY (doublereal t, doublereal p, const std::string &y)
Set the internally stored temperature (K), pressure (Pa), and mass fractions of the phase.
virtual void setState_TP (doublereal t, doublereal p)
Set the temperature (K) and pressure (Pa)
virtual void setState_PX (doublereal p, doublereal *x)
Set the pressure (Pa) and mole fractions.
virtual void setState_PY (doublereal p, doublereal *y)
Set the internally stored pressure (Pa) and mass fractions.
virtual void setState_HP (doublereal h, doublereal p, doublereal tol=1.e-4)
Set the internally stored specific enthalpy (J/kg) and pressure (Pa) of the phase.
virtual void setState_UV (doublereal u, doublereal v, doublereal tol=1.e-4)
Set the specific internal energy (J/kg) and specific volume (m^3/kg).
virtual void setState_SP (doublereal s, doublereal p, doublereal tol=1.e-4)
Set the specific entropy (J/kg/K) and pressure (Pa).
virtual void setState_SV (doublereal s, doublereal v, doublereal tol=1.e-4)
Set the specific entropy (J/kg/K) and specific volume (m^3/kg).
void equilibrate (const std::string &XY, const std::string &solver="auto", double rtol=1e-9, int max_steps=50000, int max_iter=100, int estimate_equil=0, int log_level=0)
Equilibrate a ThermoPhase object.
virtual void setToEquilState (const doublereal *lambda_RT)
This method is used by the ChemEquil equilibrium solver.
void setElementPotentials (const vector_fp &lambda)
Stores the element potentials in the ThermoPhase object.
bool getElementPotentials (doublereal *lambda) const
Returns the element potentials stored in the ThermoPhase object.
virtual doublereal critTemperature () const
Critical temperature (K).
virtual doublereal critPressure () const
Critical pressure (Pa).
virtual doublereal critVolume () const
Critical volume (m3/kmol).
virtual doublereal critCompressibility () const
Critical compressibility (unitless).
virtual doublereal critDensity () const
Critical density (kg/m3).
virtual doublereal satTemperature (doublereal p) const
Return the saturation temperature given the pressure.
virtual doublereal satPressure (doublereal t)
Return the saturation pressure given the temperature.
virtual doublereal vaporFraction () const
Return the fraction of vapor at the current conditions.
virtual void setState_Tsat (doublereal t, doublereal x)
Set the state to a saturated system at a particular temperature.
virtual void setState_Psat (doublereal p, doublereal x)
Set the state to a saturated system at a particular pressure.
virtual bool addSpecies (shared_ptr< Species > spec)
Add a Species to this Phase.
void saveSpeciesData (const size_t k, const XML_Node *const data)
Store a reference pointer to the XML tree containing the species data for this phase.
const std::vector< const
XML_Node * > & speciesData () const
Return a pointer to the vector of XML nodes containing the species data for this phase.
void setSpeciesThermo (SpeciesThermo *spthermo)
Install a species thermodynamic property manager.
virtual SpeciesThermo & speciesThermo (int k=-1)
Return a changeable reference to the calculation manager for species reference-state thermodynamic properties.
virtual void initThermoFile (const std::string &inputFile, const std::string &id)
virtual void initThermoXML (XML_Node &phaseNode, const std::string &id)
Import and initialize a ThermoPhase object using an XML tree.
virtual void installSlavePhases (Cantera::XML_Node *phaseNode)
Add in species from Slave phases.
virtual void getParameters (int &n, doublereal *const c) const
Get the equation of state parameters in a vector.
virtual void getdlnActCoeffds (const doublereal dTds, const doublereal *const dXds, doublereal *dlnActCoeffds) const
Get the change in activity coefficients wrt changes in state (temp, mole fraction, etc) along a line in parameter space or along a line in physical space.
virtual void getdlnActCoeffdlnX_diag (doublereal *dlnActCoeffdlnX_diag) const
Get the array of ln mole fraction derivatives of the log activity coefficients - diagonal component only.
virtual void getdlnActCoeffdlnN_diag (doublereal *dlnActCoeffdlnN_diag) const
Get the array of log species mole number derivatives of the log activity coefficients.
virtual void getdlnActCoeffdlnN (const size_t ld, doublereal *const dlnActCoeffdlnN)
Get the array of derivatives of the log activity coefficients with respect to the log of the species mole numbers.
virtual void getdlnActCoeffdlnN_numderiv (const size_t ld, doublereal *const dlnActCoeffdlnN)
virtual std::string report (bool show_thermo=true, doublereal threshold=-1e-14) const
returns a summary of the state of the phase as a string
virtual void reportCSV (std::ofstream &csvFile) const
returns a summary of the state of the phase to a comma separated file.
Public Member Functions inherited from Phase
Phase ()
Default constructor.
virtual ~Phase ()
Destructor.
Phase (const Phase &right)
Copy Constructor.
Phase & operator= (const Phase &right)
Assignment operator.
XML_Node & xml () const
Returns a const reference to the XML_Node that describes the phase.
void setXMLdata (XML_Node &xmlPhase)
Stores the XML tree information for the current phase.
void saveState (vector_fp &state) const
Save the current internal state of the phase Write to vector 'state' the current internal state.
void saveState (size_t lenstate, doublereal *state) const
Write to array 'state' the current internal state.
void restoreState (const vector_fp &state)
Restore a state saved on a previous call to saveState.
void restoreState (size_t lenstate, const doublereal *state)
Restore the state of the phase from a previously saved state vector.
doublereal molecularWeight (size_t k) const
Molecular weight of species k.
void getMolecularWeights (vector_fp &weights) const
Copy the vector of molecular weights into vector weights.
void getMolecularWeights (doublereal *weights) const
Copy the vector of molecular weights into array weights.
const vector_fp & molecularWeights () const
Return a const reference to the internal vector of molecular weights.
doublereal size (size_t k) const
This routine returns the size of species k.
doublereal charge (size_t k) const
Dimensionless electrical charge of a single molecule of species k The charge is normalized by the the magnitude of the electron charge.
doublereal chargeDensity () const
Charge density [C/m^3].
size_t nDim () const
Returns the number of spatial dimensions (1, 2, or 3)
void setNDim (size_t ndim)
Set the number of spatial dimensions (1, 2, or 3).
virtual bool ready () const
Returns a bool indicating whether the object is ready for use.
int stateMFNumber () const
Return the State Mole Fraction Number.
std::string id () const
Return the string id for the phase.
void setID (const std::string &id)
Set the string id for the phase.
std::string name () const
Return the name of the phase.
void setName (const std::string &nm)
Sets the string name for the phase.
std::string elementName (size_t m) const
Name of the element with index m.
size_t elementIndex (const std::string &name) const
Return the index of element named 'name'.
const std::vector< std::string > & elementNames () const
Return a read-only reference to the vector of element names.
doublereal atomicWeight (size_t m) const
Atomic weight of element m.
doublereal entropyElement298 (size_t m) const
Entropy of the element in its standard state at 298 K and 1 bar.
int atomicNumber (size_t m) const
Atomic number of element m.
int elementType (size_t m) const
Return the element constraint type Possible types include:
int changeElementType (int m, int elem_type)
Change the element type of the mth constraint Reassigns an element type.
const vector_fp & atomicWeights () const
Return a read-only reference to the vector of atomic weights.
size_t nElements () const
Number of elements.
void checkElementIndex (size_t m) const
Check that the specified element index is in range Throws an exception if m is greater than nElements()-1.
void checkElementArraySize (size_t mm) const
Check that an array size is at least nElements() Throws an exception if mm is less than nElements().
doublereal nAtoms (size_t k, size_t m) const
Number of atoms of element m in species k.
void getAtoms (size_t k, double *atomArray) const
Get a vector containing the atomic composition of species k.
size_t speciesIndex (const std::string &name) const
Returns the index of a species named 'name' within the Phase object.
std::string speciesName (size_t k) const
Name of the species with index k.
std::string speciesSPName (int k) const
Returns the expanded species name of a species, including the phase name This is guaranteed to be unique within a Cantera problem.
const std::vector< std::string > & speciesNames () const
Return a const reference to the vector of species names.
size_t nSpecies () const
Returns the number of species in the phase.
void checkSpeciesIndex (size_t k) const
Check that the specified species index is in range Throws an exception if k is greater than nSpecies()-1.
void checkSpeciesArraySize (size_t kk) const
Check that an array size is at least nSpecies() Throws an exception if kk is less than nSpecies().
void setMoleFractionsByName (const compositionMap &xMap)
Set the species mole fractions by name.
void setMoleFractionsByName (const std::string &x)
Set the mole fractions of a group of species by name.
void setMassFractionsByName (const compositionMap &yMap)
Set the species mass fractions by name.
void setMassFractionsByName (const std::string &x)
Set the species mass fractions by name.
void setState_TRX (doublereal t, doublereal dens, const doublereal *x)
Set the internally stored temperature (K), density, and mole fractions.
void setState_TRX (doublereal t, doublereal dens, const compositionMap &x)
Set the internally stored temperature (K), density, and mole fractions.
void setState_TRY (doublereal t, doublereal dens, const doublereal *y)
Set the internally stored temperature (K), density, and mass fractions.
void setState_TRY (doublereal t, doublereal dens, const compositionMap &y)
Set the internally stored temperature (K), density, and mass fractions.
void setState_TNX (doublereal t, doublereal n, const doublereal *x)
Set the internally stored temperature (K), molar density (kmol/m^3), and mole fractions.
void setState_TR (doublereal t, doublereal rho)
Set the internally stored temperature (K) and density (kg/m^3)
void setState_TX (doublereal t, doublereal *x)
Set the internally stored temperature (K) and mole fractions.
void setState_TY (doublereal t, doublereal *y)
Set the internally stored temperature (K) and mass fractions.
void setState_RX (doublereal rho, doublereal *x)
Set the density (kg/m^3) and mole fractions.
void setState_RY (doublereal rho, doublereal *y)
Set the density (kg/m^3) and mass fractions.
void getMoleFractionsByName (compositionMap &x) const
Get the mole fractions by name.
compositionMap getMoleFractionsByName (double threshold=0.0) const
Get the mole fractions by name.
doublereal moleFraction (size_t k) const
Return the mole fraction of a single species.
doublereal moleFraction (const std::string &name) const
Return the mole fraction of a single species.
compositionMap getMassFractionsByName (double threshold=0.0) const
Get the mass fractions by name.
doublereal massFraction (size_t k) const
Return the mass fraction of a single species.
doublereal massFraction (const std::string &name) const
Return the mass fraction of a single species.
void getMoleFractions (doublereal *const x) const
Get the species mole fraction vector.
virtual void setMoleFractions (const doublereal *const x)
Set the mole fractions to the specified values There is no restriction on the sum of the mole fraction vector.
virtual void setMoleFractions_NoNorm (const doublereal *const x)
Set the mole fractions to the specified values without normalizing.
void getMassFractions (doublereal *const y) const
Get the species mass fractions.
const doublereal * massFractions () const
Return a const pointer to the mass fraction array.
virtual void setMassFractions (const doublereal *const y)
Set the mass fractions to the specified values and normalize them.
virtual void setMassFractions_NoNorm (const doublereal *const y)
Set the mass fractions to the specified values without normalizing.
void getConcentrations (doublereal *const c) const
Get the species concentrations (kmol/m^3).
doublereal concentration (const size_t k) const
Concentration of species k.
virtual void setConcentrations (const doublereal *const conc)
Set the concentrations to the specified values within the phase.
doublereal elementalMassFraction (const size_t m) const
Elemental mass fraction of element m.
doublereal elementalMoleFraction (const size_t m) const
Elemental mole fraction of element m.
const doublereal * moleFractdivMMW () const
Returns a const pointer to the start of the moleFraction/MW array.
doublereal temperature () const
Temperature (K).
virtual doublereal density () const
Density (kg/m^3).
doublereal molarDensity () const
Molar density (kmol/m^3).
doublereal molarVolume () const
Molar volume (m^3/kmol).
virtual void setDensity (const doublereal density_)
Set the internally stored density (kg/m^3) of the phase Note the density of a phase is an independent variable.
virtual void setMolarDensity (const doublereal molarDensity)
Set the internally stored molar density (kmol/m^3) of the phase.
virtual void setTemperature (const doublereal temp)
Set the internally stored temperature of the phase (K).
doublereal mean_X (const doublereal *const Q) const
Evaluate the mole-fraction-weighted mean of an array Q.
doublereal mean_X (const vector_fp &Q) const
Evaluate the mole-fraction-weighted mean of an array Q.
doublereal mean_Y (const doublereal *const Q) const
Evaluate the mass-fraction-weighted mean of an array Q.
doublereal meanMolecularWeight () const
The mean molecular weight. Units: (kg/kmol)
doublereal sum_xlogx () const
Evaluate \(\sum_k X_k \log X_k \).
doublereal sum_xlogQ (doublereal *const Q) const
Evaluate \(\sum_k X_k \log Q_k \).
size_t addElement (const std::string &symbol, doublereal weight=-12345.0, int atomicNumber=0, doublereal entropy298=ENTROPY298_UNKNOWN, int elem_type=CT_ELEM_TYPE_ABSPOS)
Add an element.
void addElement (const XML_Node &e)
Add an element from an XML specification.
void addUniqueElement (const std::string &symbol, doublereal weight=-12345.0, int atomicNumber=0, doublereal entropy298=ENTROPY298_UNKNOWN, int elem_type=CT_ELEM_TYPE_ABSPOS)
Add an element, checking for uniqueness The uniqueness is checked by comparing the string symbol.
void addUniqueElement (const XML_Node &e)
Add an element, checking for uniqueness The uniqueness is checked by comparing the string symbol.
void addElementsFromXML (const XML_Node &phase)
Add all elements referenced in an XML_Node tree.
void freezeElements ()
Prohibit addition of more elements, and prepare to add species.
bool elementsFrozen ()
True if freezeElements has been called.
size_t addUniqueElementAfterFreeze (const std::string &symbol, doublereal weight, int atomicNumber, doublereal entropy298=ENTROPY298_UNKNOWN, int elem_type=CT_ELEM_TYPE_ABSPOS)
Add an element after elements have been frozen, checking for uniqueness The uniqueness is checked by comparing the string symbol.
void addSpecies (const std::string &name, const doublereal *comp, doublereal charge=0.0, doublereal size=1.0)
void addUniqueSpecies (const std::string &name, const doublereal *comp, doublereal charge=0.0, doublereal size=1.0)
Add a species to the phase, checking for uniqueness of the name This routine checks for uniqueness of the string name.
shared_ptr< Species > species (const std::string &name) const
Return the Species object for the named species.
shared_ptr< Species > species (size_t k) const
Return the Species object for species whose index is k.
void ignoreUndefinedElements ()
Set behavior when adding a species containing undefined elements to just skip the species.
void addUndefinedElements ()
Set behavior when adding a species containing undefined elements to add those elements to the phase.
void throwUndefinedElements ()
Set the behavior when adding a species containing undefined elements to throw an exception.
Protected Attributes
doublereal m_n0
Surface site density (kmol m-2)
doublereal m_logn0
log of the surface site density
doublereal m_press
Current value of the pressure (Pa)
vector_fp m_h0
Temporary storage for the reference state enthalpies.
vector_fp m_s0
Temporary storage for the reference state entropies.
vector_fp m_cp0
Temporary storage for the reference state heat capacities.
vector_fp m_mu0
Temporary storage for the reference state Gibbs energies.
vector_fp m_work
Temporary work array.
vector_fp m_logsize
vector storing the log of the size of each species.
Protected Attributes inherited from ThermoPhase
SpeciesThermo * m_spthermo
Pointer to the calculation manager for species reference-state thermodynamic properties.
std::vector< const XML_Node * > m_speciesData
Vector of pointers to the species databases.
doublereal m_phi
Stored value of the electric potential for this phase.
vector_fp m_lambdaRRT
Vector of element potentials.
bool m_hasElementPotentials
Boolean indicating whether there is a valid set of saved element potentials for this phase.
bool m_chargeNeutralityNecessary
Boolean indicating whether a charge neutrality condition is a necessity.
int m_ssConvention
Contains the standard state convention.
std::vector< doublereal > xMol_Ref
Reference Mole Fraction Composition.
doublereal m_tlast
last value of the temperature processed by reference state
Protected Attributes inherited from Phase
ValueCache m_cache
Cached for saved calculations within each ThermoPhase.
size_t m_kk
Number of species in the phase.
size_t m_ndim
Dimensionality of the phase.
vector_fp m_speciesComp
Atomic composition of the species.
vector_fp m_speciesSize
Vector of species sizes.
vector_fp m_speciesCharge
Vector of species charges. length m_kk.
std::map< std::string,
shared_ptr< Species > > m_species
UndefElement::behavior m_undefinedElementBehavior
Flag determining behavior when adding species with an undefined element.
Private Member Functions
void _updateThermo (bool force=false) const
Update the species reference state thermodynamic functions.
Additional Inherited Members
Public Attributes inherited from Phase
enum CT_RealNumber_Range_Behavior realNumberRangeBehavior_
Overflow behavior of real number calculations involving this thermo object.
Protected Member Functions inherited from ThermoPhase
virtual void getCsvReportData (std::vector< std::string > &names, std::vector< vector_fp > &data) const
Fills names and data with the column names and species thermo properties to be included in the output of the reportCSV method.
Protected Member Functions inherited from Phase
void setMolecularWeight (const int k, const double mw)
Set the molecular weight of a single species to a given value.
Detailed Description
A simple thermodynamic model for a surface phase, assuming an ideal solution model.
The surface consists of a grid of equivalent sites. Surface species may be defined to occupy one or more sites. The surface species are assumed to be independent, and thus the species form an ideal solution.
The density of surface sites is given by the variable \(n_0 \), which has SI units of kmol m-2.
Specification of Species Standard State Properties
It is assumed that the reference state thermodynamics may be obtained by a pointer to a populated species thermodynamic property manager class (see ThermoPhase::m_spthermo). How to relate pressure changes to the reference state thermodynamics is resolved at this level.
Pressure is defined as an independent variable in this phase. However, it has no effect on any quantities, as the molar concentration is a constant.
Therefore, The standard state internal energy for species k is equal to the enthalpy for species k.
\[ u^o_k = h^o_k \]
Also, the standard state chemical potentials, entropy, and heat capacities are independent of pressure. The standard state Gibbs free energy is obtained from the enthalpy and entropy functions.
Specification of Solution Thermodynamic Properties
The activity of species defined in the phase is given by
\[ a_k = \theta_k \]
The chemical potential for species k is equal to
\[ \mu_k(T,P) = \mu^o_k(T) + R T \log(\theta_k) \]
Pressure is defined as an independent variable in this phase. However, it has no effect on any quantities, as the molar concentration is a constant.
The internal energy for species k is equal to the enthalpy for species k
\[ u_k = h_k \]
The entropy for the phase is given by the following relation, which is independent of the pressure:
\[ s_k(T,P) = s^o_k(T) - R \log(\theta_k) \]
Application within Kinetics Managers
The activity concentration, \(C^a_k \), used by the kinetics manager, is equal to the actual concentration, \(C^s_k \), and is given by the following expression.
\[ C^a_k = C^s_k = \frac{\theta_k n_0}{s_k} \]
The standard concentration for species k is:
\[ C^0_k = \frac{n_0}{s_k} \]
Instantiation of the Class
The constructor for this phase is located in the default ThermoFactory for Cantera. A new SurfPhase may be created by the following code snippet:
XML_Node *xc = get_XML_File("diamond.xml");
XML_Node * const xs = xc->findNameID("phase", "diamond_100");
ThermoPhase *diamond100TP_tp = newPhase(*xs);
SurfPhase *diamond100TP = dynamic_cast <SurfPhase *>(diamond100TP_tp);
or by the following constructor:
XML_Node *xc = get_XML_File("diamond.xml");
XML_Node * const xs = xc->findNameID("phase", "diamond_100");
SurfPhase *diamond100TP = new SurfPhase(*xs);
XML Example
An example of an XML Element named phase setting up a SurfPhase object named diamond_100 is given below.
<phase dim="2" id="diamond_100">
   <elementArray datasrc="elements.xml">H C</elementArray>
   <speciesArray datasrc="#species_data">c6HH c6H* c6*H c6** c6HM c6HM* c6*M c6B </speciesArray>
   <reactionArray datasrc="#reaction_data"/>
   <state>
      <temperature units="K">1200.0</temperature>
      <coverages>c6H*:0.1, c6HH:0.9</coverages>
   </state>
   <thermo model="Surface">
      <site_density units="mol/cm2">3e-09</site_density>
   </thermo>
   <kinetics model="Interface"/>
   <transport model="None"/>
   <phaseArray>
        gas_phase diamond_bulk
   </phaseArray>
</phase>
The model attribute, "Surface", on the thermo element identifies the phase as being a SurfPhase object.
Definition at line 143 of file SurfPhase.h.
Constructor & Destructor Documentation
SurfPhase (doublereal n0 = 1.0)
Constructor.
Parameters
n0 Site Density of the Surface Phase Units: kmol m-2.
Definition at line 21 of file SurfPhase.cpp.
References Phase::setNDim(), and SurfPhase::setSiteDensity().
Referenced by SurfPhase::duplMyselfAsThermoPhase().
SurfPhase (const std::string & infile, std::string id)
Construct and initialize a SurfPhase ThermoPhase object directly from an ASCII input file.
Parameters
infile name of the input file
id name of the phase id in the file. If this is blank, the first phase in the file is used.
Definition at line 28 of file SurfPhase.cpp.
References XML_Node::child(), Cantera::get_XML_File(), Cantera::get_XML_NameID(), and Cantera::importPhase().
SurfPhase (XML_Node & xmlphase)
Construct and initialize a SurfPhase ThermoPhase object directly from an XML database.
Parameters
xmlphase XML node pointing to a SurfPhase description
Definition at line 49 of file SurfPhase.cpp.
References XML_Node::child(), and Cantera::importPhase().
SurfPhase (const SurfPhase & right)
Copy Constructor.
Copy constructor for the object. Constructed object will be a clone of this object, but will also own all of its data. This is a wrapper around the assignment operator
Parameters
right Object to be copied.
Definition at line 60 of file SurfPhase.cpp.
References SurfPhase::operator=().
Member Function Documentation
SurfPhase & operator= (const SurfPhase & right)
Assignment operator.
Assignment operator for the object. Constructed object will be a clone of this object, but will also own all of its data.
Parameters
right Object to be copied.
Definition at line 68 of file SurfPhase.cpp.
References SurfPhase::m_cp0, SurfPhase::m_h0, SurfPhase::m_logn0, SurfPhase::m_logsize, SurfPhase::m_mu0, SurfPhase::m_n0, SurfPhase::m_press, SurfPhase::m_s0, SurfPhase::m_work, and ThermoPhase::operator=().
Referenced by EdgePhase::operator=(), Interface::operator=(), and SurfPhase::SurfPhase().
ThermoPhase * duplMyselfAsThermoPhase () const virtual
Duplicator from the ThermoPhase parent class.
Reimplemented from ThermoPhase.
Definition at line 85 of file SurfPhase.cpp.
References SurfPhase::SurfPhase().
virtual int eosType () const inline virtual
Equation of state type flag.
Redefine this to return cSurf, listed in mix_defs.h.
Reimplemented from ThermoPhase.
Reimplemented in EdgePhase.
Definition at line 204 of file SurfPhase.h.
References Cantera::cSurf.
doublereal enthalpy_mole () const virtual
Return the Molar Enthalpy. Units: J/kmol.
For an ideal solution,
\[ \hat h(T,P) = \sum_k X_k \hat h^0_k(T), \]
and is a function only of temperature. The standard-state pure-species Enthalpies \(\hat h^0_k(T) \) are computed by the species thermodynamic property manager.
See Also
SpeciesThermo
Reimplemented from ThermoPhase.
Definition at line 90 of file SurfPhase.cpp.
References SurfPhase::_updateThermo(), SurfPhase::m_h0, SurfPhase::m_n0, and Phase::mean_X().
Referenced by SurfPhase::intEnergy_mole().
doublereal intEnergy_mole () const virtual
Return the Molar Internal Energy. Units: J/kmol.
For a surface phase, the pressure is not a relevant thermodynamic variable, and so the Enthalpy is equal to the Internal Energy.
Reimplemented from ThermoPhase.
Definition at line 99 of file SurfPhase.cpp.
References SurfPhase::enthalpy_mole().
doublereal entropy_mole () const virtual
Return the Molar Entropy. Units: J/kmol-K.
\[ \hat s(T,P) = \sum_k X_k (\hat s^0_k(T) - R \log(\theta_k)) \]
Reimplemented from ThermoPhase.
Definition at line 104 of file SurfPhase.cpp.
References SurfPhase::_updateThermo(), Phase::concentration(), Cantera::GasConstant, Phase::m_kk, SurfPhase::m_n0, SurfPhase::m_s0, Phase::moleFraction(), Phase::size(), and Cantera::SmallNumber.
doublereal cp_mole () const virtual
Molar heat capacity at constant pressure. Units: J/kmol/K.
Reimplemented from ThermoPhase.
Definition at line 115 of file SurfPhase.cpp.
References SurfPhase::_updateThermo(), SurfPhase::m_cp0, and Phase::mean_X().
Referenced by SurfPhase::cv_mole().
doublereal cv_mole () const virtual
Molar heat capacity at constant volume. Units: J/kmol/K.
Reimplemented from ThermoPhase.
Definition at line 121 of file SurfPhase.cpp.
References SurfPhase::cp_mole().
void getChemPotentials (doublereal * mu) const virtual
Get the species chemical potentials. Units: J/kmol.
This function returns a vector of chemical potentials of the species in solution at the current temperature, pressure and mole fraction of the solution.
Parameters
mu Output vector of species chemical potentials. Length: m_kk. Units: J/kmol
Reimplemented from ThermoPhase.
Definition at line 164 of file SurfPhase.cpp.
References SurfPhase::_updateThermo(), DATA_PTR, Cantera::GasConstant, SurfPhase::getActivityConcentrations(), SurfPhase::logStandardConc(), Phase::m_kk, SurfPhase::m_mu0, SurfPhase::m_work, and Phase::temperature().
void getPartialMolarEnthalpies (doublereal * hbar) const virtual
Returns an array of partial molar enthalpies for the species in the mixture.
Units (J/kmol)
Parameters
hbar Output vector of species partial molar enthalpies. Length: m_kk. units are J/kmol.
Reimplemented from ThermoPhase.
Definition at line 126 of file SurfPhase.cpp.
References Cantera::GasConstant, SurfPhase::getEnthalpy_RT(), Phase::m_kk, and Phase::temperature().
void getPartialMolarEntropies (doublereal * sbar) const virtual
Returns an array of partial molar entropies of the species in the solution.
Units: J/kmol/K.
Parameters
sbar Output vector of species partial molar entropies. Length = m_kk. units are J/kmol/K.
Reimplemented from ThermoPhase.
Definition at line 135 of file SurfPhase.cpp.
References Cantera::GasConstant, SurfPhase::getEntropy_R(), and Phase::m_kk.
void getPartialMolarCp (doublereal * cpbar) const virtual
Return an array of partial molar heat capacities for the species in the mixture.
Units: J/kmol/K
Parameters
cpbar Output vector of species partial molar heat capacities at constant pressure. Length = m_kk. units are J/kmol/K.
Reimplemented from ThermoPhase.
Definition at line 143 of file SurfPhase.cpp.
References Cantera::GasConstant, SurfPhase::getCp_R(), and Phase::m_kk.
void getPartialMolarVolumes (doublereal * vbar) const virtual
Return an array of partial molar volumes for the species in the mixture.
Units: m^3/kmol.
Parameters
vbar Output vector of species partial molar volumes. Length = m_kk. units are m^3/kmol.
Reimplemented from ThermoPhase.
Definition at line 153 of file SurfPhase.cpp.
References SurfPhase::getStandardVolumes().
void getStandardChemPotentials (doublereal * mu0) const virtual
Get the array of chemical potentials at unit activity for the standard state species at the current T and P of the solution.
These are the standard state chemical potentials \(\mu^0_k(T,P) \). The values are evaluated at the current temperature and pressure of the solution
Parameters
mu0 Output vector of chemical potentials. Length: m_kk.
Reimplemented from ThermoPhase.
Definition at line 158 of file SurfPhase.cpp.
References SurfPhase::_updateThermo(), and SurfPhase::m_mu0.
void getActivityConcentrations (doublereal * c) const virtual
Return a vector of activity concentrations for each species.
For this phase the activity concentrations, \(C^a_k \), are defined to be equal to the actual concentrations, \(C^s_k \). Activity concentrations are
\[ C^a_k = C^s_k = \frac{\theta_k n_0}{s_k} \]
where \(\theta_k \) is the surface site fraction for species k, \(n_0 \) is the surface site density for the phase, and \(s_k \) is the surface size of species k.
\(C^a_k\) that are defined such that \(a_k = C^a_k / C^0_k, \) where \(C^0_k \) is a standard concentration defined below and \(a_k \) are activities used in the thermodynamic functions. These activity concentrations are used by kinetics manager classes to compute the forward and reverse rates of elementary reactions. Note that they may or may not have units of concentration — they might be partial pressures, mole fractions, or surface coverages,
Parameters
c vector of activity concentration (kmol m-2).
Reimplemented from ThermoPhase.
Definition at line 175 of file SurfPhase.cpp.
References Phase::getConcentrations().
Referenced by SurfPhase::getChemPotentials().
doublereal standardConcentration (size_t k = 0) const virtual
Return the standard concentration for the kth species.
The standard concentration \(C^0_k \) used to normalize the activity (i.e., generalized) concentration. For this phase, the standard concentration is species- specific
\[ C^0_k = \frac{n_0}{s_k} \]
This definition implies that the activity is equal to \(\theta_k \).
Parameters
k Optional parameter indicating the species. The default is to assume this refers to species 0.
Returns
Returns the standard Concentration in units of m3 kmol-1.
Reimplemented from ThermoPhase.
Definition at line 180 of file SurfPhase.cpp.
References SurfPhase::m_n0, and Phase::size().
Referenced by SurfPhase::getStandardVolumes().
doublereal logStandardConc (size_t k = 0) const virtual
Return the log of the standard concentration for the kth species.
Parameters
k species index (default 0)
Reimplemented from ThermoPhase.
Definition at line 185 of file SurfPhase.cpp.
References SurfPhase::m_logn0, and SurfPhase::m_logsize.
Referenced by SurfPhase::getChemPotentials().
void setParameters (int n, doublereal *const c) virtual
Set the equation of state parameters from the argument list.
Set equation of state parameters.
Parameters
n number of parameters. Must be one
c array of n coefficients c[0] = The site density (kmol m-2)
Reimplemented from ThermoPhase.
Definition at line 190 of file SurfPhase.cpp.
References SurfPhase::setSiteDensity().
void setParametersFromXML (const XML_Node & thermoData) virtual
Set the Equation-of-State parameters by reading an XML Node Input.
The Equation-of-State data consists of one item, the site density.
Parameters
thermoData Reference to an XML_Node named thermo containing the equation-of-state data. The XML_Node is within the phase XML_Node describing the SurfPhase object.
An example of the contents of the thermoData XML_Node is provided below. The units attribute is used to supply the units of the site density in any convenient form. Internally it is changed into MKS form.
<thermo model="Surface">
   <site_density units="mol/cm2"> 3e-09 </site_density>
</thermo>
Reimplemented from ThermoPhase.
Reimplemented in EdgePhase.
Definition at line 367 of file SurfPhase.cpp.
References XML_Node::_require(), Cantera::getFloat(), and SurfPhase::setSiteDensity().
void initThermo () virtual
Initialize the SurfPhase object after all species have been set up.
Reimplemented from ThermoPhase.
Definition at line 257 of file SurfPhase.cpp.
References DATA_PTR, ThermoPhase::initThermo(), SurfPhase::m_cp0, SurfPhase::m_h0, Phase::m_kk, SurfPhase::m_logsize, SurfPhase::m_mu0, SurfPhase::m_s0, SurfPhase::m_work, SurfPhase::setCoverages(), and Phase::size().
void setStateFromXML (const XML_Node & state) virtual
Set the initial state of the Surface Phase from an XML_Node.
State variables that can be set by this routine are the temperature and the surface site coverages.
Parameters
state XML_Node containing the state information
An example of the XML code block is given below.
<state>
   <temperature units="K">1200.0</temperature>
   <coverages>c6H*:0.1, c6HH:0.9</coverages>
</state>
Reimplemented from ThermoPhase.
Definition at line 374 of file SurfPhase.cpp.
References Cantera::getChildValue(), Cantera::getOptionalFloat(), XML_Node::hasChild(), SurfPhase::setCoveragesByName(), and Phase::setTemperature().
doublereal siteDensity () inline
Returns the site density.
Site density kmol m-2
Definition at line 410 of file SurfPhase.h.
References SurfPhase::m_n0.
Referenced by ReactingSurf1D::eval(), and Reactor::evalSurfaces().
void setSiteDensity (doublereal n0)
Set the site density of the surface phase (kmol m-2)
Parameters
n0 Site density of the surface phase (kmol m-2)
Definition at line 274 of file SurfPhase.cpp.
References Cantera::fp2str(), SurfPhase::m_logn0, and SurfPhase::m_n0.
Referenced by SurfPhase::setParameters(), EdgePhase::setParametersFromXML(), SurfPhase::setParametersFromXML(), and SurfPhase::SurfPhase().
void getGibbs_RT (doublereal * grt) const virtual
Get the nondimensional Gibbs functions for the species in their standard states at the current T and P of the solution.
Parameters
grt Output vector of nondimensional standard state Gibbs free energies Length: m_kk.
Reimplemented from ThermoPhase.
Definition at line 205 of file SurfPhase.cpp.
References SurfPhase::_updateThermo(), Cantera::GasConstant, SurfPhase::m_mu0, Cantera::scale(), and Phase::temperature().
Referenced by SurfPhase::getGibbs_RT_ref().
void getEnthalpy_RT (doublereal * hrt) const virtual
Get the nondimensional Enthalpy functions for the species standard states at their standard states at the current T and P of the solution.
Parameters
hrt Output vector of nondimensional standard state enthalpies. Length: m_kk.
Reimplemented from ThermoPhase.
Definition at line 211 of file SurfPhase.cpp.
References SurfPhase::_updateThermo(), Cantera::GasConstant, SurfPhase::m_h0, Cantera::scale(), and Phase::temperature().
Referenced by SurfPhase::getEnthalpy_RT_ref(), and SurfPhase::getPartialMolarEnthalpies().
void getEntropy_R (doublereal * sr) const virtual
Get the array of nondimensional Entropy functions for the species standard states at the current T and P of the solution.
Parameters
sr Output vector of nondimensional standard state entropies. Length: m_kk.
Reimplemented from ThermoPhase.
Definition at line 217 of file SurfPhase.cpp.
References SurfPhase::_updateThermo(), Cantera::GasConstant, SurfPhase::m_s0, and Cantera::scale().
Referenced by SurfPhase::getEntropy_R_ref(), and SurfPhase::getPartialMolarEntropies().
void getCp_R (doublereal * cpr) const virtual
Get the nondimensional Heat Capacities at constant pressure for the species standard states at the current T and P of the solution.
Parameters
cpr Output vector of nondimensional standard state heat capacities Length: m_kk.
Reimplemented from ThermoPhase.
Definition at line 223 of file SurfPhase.cpp.
References SurfPhase::_updateThermo(), Cantera::GasConstant, SurfPhase::m_cp0, and Cantera::scale().
Referenced by SurfPhase::getCp_R_ref(), and SurfPhase::getPartialMolarCp().
void getStandardVolumes (doublereal * vol) const virtual
Get the molar volumes of the species standard states at the current T and P of the solution.
units = m^3 / kmol
Parameters
vol Output vector containing the standard state volumes. Length: m_kk.
Reimplemented from ThermoPhase.
Definition at line 229 of file SurfPhase.cpp.
References SurfPhase::_updateThermo(), Phase::m_kk, and SurfPhase::standardConcentration().
Referenced by SurfPhase::getPartialMolarVolumes().
virtual doublereal pressure () const inline virtual
Return the thermodynamic pressure (Pa).
Reimplemented from ThermoPhase.
Definition at line 464 of file SurfPhase.h.
References SurfPhase::m_press.
virtual void setPressure (doublereal p) inline virtual
Set the internally stored pressure (Pa) at constant temperature and composition.
Parameters
p input Pressure (Pa)
Reimplemented from ThermoPhase.
Definition at line 473 of file SurfPhase.h.
References SurfPhase::m_press.
void getPureGibbs (doublereal * gpure) const virtual
Get the Gibbs functions for the standard state of the species at the current T and P of the solution.
Units are Joules/kmol
Parameters
gpure Output vector of standard state Gibbs free energies Length: m_kk.
Reimplemented from ThermoPhase.
Definition at line 199 of file SurfPhase.cpp.
References SurfPhase::_updateThermo(), and SurfPhase::m_mu0.
void getGibbs_RT_ref (doublereal * grt) const virtual
Returns the vector of nondimensional Gibbs Free Energies of the reference state at the current temperature of the solution and the reference pressure for the species.
Parameters
grt Output vector containing the nondimensional reference state Gibbs Free energies. Length: m_kk.
Reimplemented from ThermoPhase.
Definition at line 237 of file SurfPhase.cpp.
References SurfPhase::getGibbs_RT().
void getEnthalpy_RT_ref (doublereal * hrt) const virtual
Returns the vector of nondimensional enthalpies of the reference state at the current temperature of the solution and the reference pressure for the species.
Parameters
hrt Output vector of nondimensional standard state enthalpies. Length: m_kk.
Reimplemented from ThermoPhase.
Definition at line 242 of file SurfPhase.cpp.
References SurfPhase::getEnthalpy_RT().
void getEntropy_R_ref (doublereal * er) const virtual
Returns the vector of nondimensional entropies of the reference state at the current temperature of the solution and the reference pressure for each species.
Parameters
er Output vector containing the nondimensional reference state entropies. Length: m_kk.
Reimplemented from ThermoPhase.
Definition at line 247 of file SurfPhase.cpp.
References SurfPhase::getEntropy_R().
void getCp_R_ref (doublereal * cprt) const virtual
Returns the vector of nondimensional constant pressure heat capacities of the reference state at the current temperature of the solution and reference pressure for each species.
Parameters
cprt Output vector of nondimensional reference state heat capacities at constant pressure for the species. Length: m_kk
Reimplemented from ThermoPhase.
Definition at line 252 of file SurfPhase.cpp.
References SurfPhase::getCp_R().
void setCoverages (const doublereal * theta)
Set the surface site fractions to a specified state.
This routine converts to concentrations in kmol/m2, using m_n0, the surface site density, and size(k), which is defined to be the number of surface sites occupied by the kth molecule. It then calls Phase::setConcentrations to set the internal concentration in the object.
Parameters
theta This is the surface site fraction for the kth species in the surface phase. This is a dimensionless quantity.
This routine normalizes the theta's to 1, before application
Definition at line 284 of file SurfPhase.cpp.
References DATA_PTR, Phase::m_kk, SurfPhase::m_n0, SurfPhase::m_work, Phase::setConcentrations(), and Phase::size().
Referenced by ReactingSurf1D::eval(), SurfPhase::initThermo(), ReactingSurf1D::restore(), SurfPhase::setCoveragesByName(), and Wall::syncCoverages().
void setCoveragesNoNorm (const doublereal * theta)
Set the surface site fractions to a specified state.
This routine converts to concentrations in kmol/m2, using m_n0, the surface site density, and size(k), which is defined to be the number of surface sites occupied by the kth molecule. It then calls Phase::setConcentrations to set the internal concentration in the object.
Parameters
theta This is the surface site fraction for the kth species in the surface phase. This is a dimensionless quantity.
Definition at line 307 of file SurfPhase.cpp.
References DATA_PTR, Phase::m_kk, SurfPhase::m_n0, SurfPhase::m_work, Phase::setConcentrations(), and Phase::size().
void setCoveragesByName (const std::string & cov)
Set the coverages from a string of colon-separated name:value pairs.
Parameters
cov String containing colon-separated name:value pairs
Definition at line 327 of file SurfPhase.cpp.
References Cantera::parseCompString(), and Phase::speciesNames().
Referenced by Wall::setCoverages(), and SurfPhase::setStateFromXML().
void setCoveragesByName (const compositionMap & cov)
Set the coverages from a map of name:value pairs.
Definition at line 332 of file SurfPhase.cpp.
References DATA_PTR, Cantera::getValue(), Phase::m_kk, SurfPhase::setCoverages(), and Phase::speciesName().
void getCoverages (doublereal * theta) const
Return a vector of surface coverages.
Get the coverages.
Parameters
theta Array theta must be at least as long as the number of species.
Definition at line 319 of file SurfPhase.cpp.
References Phase::getConcentrations(), Phase::m_kk, SurfPhase::m_n0, and Phase::size().
Referenced by ReactingSurf1D::_getInitialSoln(), InterfaceKinetics::_update_rates_T(), Wall::setCoverages(), and Wall::setKinetics().
void _updateThermo (bool force = false) const private
Update the species reference state thermodynamic functions.
The polynomials for the standard state functions are only reevaluated if the temperature has changed.
Parameters
force Boolean, which if true, forces a reevaluation of the thermo polynomials. default = false.
Definition at line 350 of file SurfPhase.cpp.
References DATA_PTR, Cantera::GasConstant, SurfPhase::m_cp0, SurfPhase::m_h0, Phase::m_kk, SurfPhase::m_mu0, SurfPhase::m_s0, ThermoPhase::m_spthermo, ThermoPhase::m_tlast, Phase::temperature(), and SpeciesThermo::update().
Referenced by SurfPhase::cp_mole(), SurfPhase::enthalpy_mole(), SurfPhase::entropy_mole(), SurfPhase::getChemPotentials(), SurfPhase::getCp_R(), SurfPhase::getEnthalpy_RT(), SurfPhase::getEntropy_R(), SurfPhase::getGibbs_RT(), SurfPhase::getPureGibbs(), SurfPhase::getStandardChemPotentials(), and SurfPhase::getStandardVolumes().
Member Data Documentation
doublereal m_n0 protected
Surface site density (kmol m-2)
Definition at line 568 of file SurfPhase.h.
Referenced by SurfPhase::enthalpy_mole(), SurfPhase::entropy_mole(), SurfPhase::getCoverages(), SurfPhase::operator=(), SurfPhase::setCoverages(), SurfPhase::setCoveragesNoNorm(), SurfPhase::setSiteDensity(), SurfPhase::siteDensity(), and SurfPhase::standardConcentration().
doublereal m_logn0 protected
log of the surface site density
Definition at line 571 of file SurfPhase.h.
Referenced by SurfPhase::logStandardConc(), SurfPhase::operator=(), and SurfPhase::setSiteDensity().
doublereal m_press protected
Current value of the pressure (Pa)
Definition at line 574 of file SurfPhase.h.
Referenced by SurfPhase::operator=(), SurfPhase::pressure(), and SurfPhase::setPressure().
vector_fp m_h0 mutable protected
Temporary storage for the reference state enthalpies.
Definition at line 577 of file SurfPhase.h.
Referenced by SurfPhase::_updateThermo(), SurfPhase::enthalpy_mole(), SurfPhase::getEnthalpy_RT(), SurfPhase::initThermo(), and SurfPhase::operator=().
vector_fp m_s0 mutable protected
Temporary storage for the reference state entropies.
Definition at line 580 of file SurfPhase.h.
Referenced by SurfPhase::_updateThermo(), SurfPhase::entropy_mole(), SurfPhase::getEntropy_R(), SurfPhase::initThermo(), and SurfPhase::operator=().
vector_fp m_cp0 mutable protected
Temporary storage for the reference state heat capacities.
Definition at line 583 of file SurfPhase.h.
Referenced by SurfPhase::_updateThermo(), SurfPhase::cp_mole(), SurfPhase::getCp_R(), SurfPhase::initThermo(), and SurfPhase::operator=().
vector_fp m_mu0 mutable protected
Temporary storage for the reference state Gibbs energies.
Definition at line 586 of file SurfPhase.h.
Referenced by SurfPhase::_updateThermo(), SurfPhase::getChemPotentials(), SurfPhase::getGibbs_RT(), SurfPhase::getPureGibbs(), SurfPhase::getStandardChemPotentials(), SurfPhase::initThermo(), and SurfPhase::operator=().
vector_fp m_work mutable protected
Temporary work array.
Definition at line 589 of file SurfPhase.h.
Referenced by SurfPhase::getChemPotentials(), SurfPhase::initThermo(), SurfPhase::operator=(), SurfPhase::setCoverages(), and SurfPhase::setCoveragesNoNorm().
vector_fp m_logsize mutable protected
vector storing the log of the size of each species.
The size of each species is defined as the number of surface sites each species occupies.
Definition at line 596 of file SurfPhase.h.
Referenced by SurfPhase::initThermo(), SurfPhase::logStandardConc(), and SurfPhase::operator=().
The documentation for this class was generated from the following files:
SurfPhase.h
SurfPhase.cpp