Cantera: RedlichKwongMFTP Class Reference
RedlichKwongMFTP Class Reference
Thermodynamic Properties
This class can handle either an ideal solution or an ideal gas approximation of a phase.
#include <RedlichKwongMFTP.h>
Public Member Functions
virtual void getActivityConcentrations (doublereal *c) const
This method returns an array of generalized concentrations.
virtual doublereal standardConcentration (size_t k=0) const
Returns the standard concentration \(C^0_k \), which is used to normalize the generalized concentration.
virtual void getUnitsStandardConc (double *uA, int k=0, int sizeUA=6) const
Returns the units of the standard and generalized concentrations.
virtual void getActivityCoefficients (doublereal *ac) const
Get the array of non-dimensional activity coefficients at the current solution temperature, pressure, and solution concentration.
virtual doublereal liquidVolEst (doublereal TKelvin, doublereal &pres) const
Estimate for the molar volume of the liquid.
virtual doublereal densityCalc (doublereal TKelvin, doublereal pressure, int phase, doublereal rhoguess)
Calculates the density given the temperature and the pressure and a guess at the density.
virtual doublereal densSpinodalLiquid () const
Return the value of the density at the liquid spinodal point (on the liquid side) for the current temperature.
virtual doublereal densSpinodalGas () const
Return the value of the density at the gas spinodal point (on the gas side) for the current temperature.
virtual doublereal pressureCalc (doublereal TKelvin, doublereal molarVol) const
Calculate the pressure given the temperature and the molar volume.
virtual doublereal dpdVCalc (doublereal TKelvin, doublereal molarVol, doublereal &presCalc) const
Calculate the pressure and the pressure derivative given the temperature and the molar volume.
void pressureDerivatives () const
Calculate dpdV and dpdT at the current conditions.
virtual void updateMixingExpressions ()
void updateAB ()
Update the a and b parameters.
void calculateAB (doublereal temp, doublereal &aCalc, doublereal &bCalc) const
Calculate the a and the b parameters given the temperature.
doublereal da_dt () const
void calcCriticalConditions (doublereal a, doublereal b, doublereal a0_coeff, doublereal aT_coeff, doublereal &pc, doublereal &tc, doublereal &vc) const
int NicholsSolve (double TKelvin, double pres, doublereal a, doublereal b, doublereal Vroot[3]) const
Solve the cubic equation of state.
Constructors and Duplicators
RedlichKwongMFTP ()
Base constructor.
RedlichKwongMFTP (const std::string &infile, std::string id="")
Construct and initialize a RedlichKwongMFTP object directly from an ASCII input file.
RedlichKwongMFTP (XML_Node &phaseRef, const std::string &id="")
Construct and initialize a RedlichKwongMFTP object directly from an XML database.
RedlichKwongMFTP (int testProb)
This is a special constructor, used to replicate test problems during the initial verification of the object.
RedlichKwongMFTP (const RedlichKwongMFTP &right)
Copy Constructor.
RedlichKwongMFTP & operator= (const RedlichKwongMFTP &right)
Assignment operator.
virtual ThermoPhase * duplMyselfAsThermoPhase () const
Duplicator from the ThermoPhase parent class.
virtual int eosType () const
Equation of state type flag.
Molar Thermodynamic properties
virtual doublereal enthalpy_mole () const
Molar enthalpy. Units: J/kmol.
virtual doublereal entropy_mole () const
Molar entropy. Units: J/kmol/K.
virtual doublereal cp_mole () const
Molar heat capacity at constant pressure. Units: J/kmol/K.
virtual doublereal cv_mole () const
Molar heat capacity at constant volume. Units: J/kmol/K.
Mechanical Properties
virtual doublereal pressure () const
Return the thermodynamic pressure (Pa).
Partial Molar Properties of the Solution
void getChemPotentials_RT (doublereal *mu) const
Get the array of non-dimensional species chemical potentials.
virtual void getChemPotentials (doublereal *mu) const
Get the species chemical potentials. Units: J/kmol.
virtual void getPartialMolarEnthalpies (doublereal *hbar) const
Get the species partial molar enthalpies. Units: J/kmol.
virtual void getPartialMolarEntropies (doublereal *sbar) const
Get the species partial molar entropies. Units: J/kmol/K.
virtual void getPartialMolarIntEnergies (doublereal *ubar) const
Get the species partial molar enthalpies. Units: J/kmol.
virtual void getPartialMolarCp (doublereal *cpbar) const
Get the partial molar heat capacities Units: J/kmol/K.
virtual void getPartialMolarVolumes (doublereal *vbar) const
Get the species partial molar volumes. Units: m^3/kmol.
Critical State Properties.
These methods are only implemented by some subclasses, and may be moved out of ThermoPhase at a later date.
virtual doublereal critTemperature () const
Critical temperature (K).
virtual doublereal critPressure () const
Critical pressure (Pa).
virtual doublereal critVolume () const
Critical volume (m3/kmol)
virtual doublereal critCompressibility () const
Critical compressibility (unitless).
virtual doublereal critDensity () const
Critical density (kg/m3).
Public Member Functions inherited from MixtureFugacityTP
virtual void setPressure (doublereal p)
Set the internally stored pressure (Pa) at constant temperature and composition.
virtual void setState_TP (doublereal T, doublereal pres)
Set the temperature and pressure at the same time.
virtual void setState_TR (doublereal T, doublereal rho)
Set the internally stored temperature (K) and density (kg/m^3)
virtual void setState_TPX (doublereal t, doublereal p, const doublereal *x)
Set the temperature (K), pressure (Pa), and mole fractions.
MixtureFugacityTP ()
Constructor.
MixtureFugacityTP (const MixtureFugacityTP &b)
Copy Constructor.
MixtureFugacityTP & operator= (const MixtureFugacityTP &b)
Assignment operator.
virtual int standardStateConvention () const
This method returns the convention used in specification of the standard state, of which there are currently two, temperature based, and variable pressure based.
virtual void setForcedSolutionBranch (int solnBranch)
Set the solution branch to force the ThermoPhase to exist on one branch or another.
virtual int forcedSolutionBranch () const
Report the solution branch which the solution is restricted to.
virtual int reportSolnBranchActual () const
Report the solution branch which the solution is actually on.
virtual void getdlnActCoeffdlnN_diag (doublereal *dlnActCoeffdlnN_diag) const
Get the array of log concentration-like derivatives of the log activity coefficients.
virtual void getStandardChemPotentials (doublereal *mu) const
Get the array of chemical potentials at unit activity.
virtual void getEnthalpy_RT (doublereal *hrt) const
Get the nondimensional Enthalpy functions for the species at their standard states at the current T and P of the solution.
virtual void getEntropy_R (doublereal *sr) const
Get the array of nondimensional Enthalpy functions for the standard state species.
virtual void getGibbs_RT (doublereal *grt) const
Get the nondimensional Gibbs functions for the species at their standard states of solution at the current T and P of the solution.
void getPureGibbs (doublereal *gpure) const
Get the pure Gibbs free energies of each species.
virtual void getIntEnergy_RT (doublereal *urt) const
Returns the vector of nondimensional internal Energies of the standard state at the current temperature and pressure of the solution for each species.
virtual void getCp_R (doublereal *cpr) const
Get the nondimensional Heat Capacities at constant pressure for the standard state of the species at the current T and P.
virtual void getStandardVolumes (doublereal *vol) const
Get the molar volumes of each species in their standard states at the current T and P of the solution.
virtual void getEnthalpy_RT_ref (doublereal *hrt) const
Returns the vector of nondimensional enthalpies of the reference state at the current temperature of the solution and the reference pressure for the species.
void modifyOneHf298SS (const size_t k, const doublereal Hf298New)
Modify the value of the 298 K Heat of Formation of the standard state of one species in the phase (J kmol-1)
virtual void getGibbs_RT_ref (doublereal *grt) const
Returns the vector of nondimensional Gibbs free energies of the reference state at the current temperature of the solution and the reference pressure for the species.
virtual void getGibbs_ref (doublereal *g) const
virtual void getEntropy_R_ref (doublereal *er) const
virtual void getCp_R_ref (doublereal *cprt) const
virtual void getStandardVolumes_ref (doublereal *vol) const
Get the molar volumes of the species reference states at the current T and reference pressure of the solution.
virtual void setStateFromXML (const XML_Node &state)
Set the initial state of the phase to the conditions specified in the state XML element.
int phaseState (bool checkState=false) const
Returns the Phase State flag for the current state of the object.
doublereal calculatePsat (doublereal TKelvin, doublereal &molarVolGas, doublereal &molarVolLiquid)
Calculate the saturation pressure at the current mixture content for the given temperature.
virtual doublereal satPressure (doublereal TKelvin)
Calculate the saturation pressure at the current mixture content for the given temperature.
Public Member Functions inherited from ThermoPhase
ThermoPhase ()
Constructor.
virtual ~ThermoPhase ()
Destructor. Deletes the species thermo manager.
ThermoPhase (const ThermoPhase &right)
Copy Constructor for the ThermoPhase object.
ThermoPhase & operator= (const ThermoPhase &right)
Assignment operator.
doublereal _RT () const
Return the Gas Constant multiplied by the current temperature.
virtual doublereal refPressure () const
Returns the reference pressure in Pa.
virtual doublereal minTemp (size_t k=npos) const
Minimum temperature for which the thermodynamic data for the species or phase are valid.
doublereal Hf298SS (const int k) const
Report the 298 K Heat of Formation of the standard state of one species (J kmol-1)
virtual doublereal maxTemp (size_t k=npos) const
Maximum temperature for which the thermodynamic data for the species are valid.
bool chargeNeutralityNecessary () const
Returns the chargeNeutralityNecessity boolean.
virtual doublereal intEnergy_mole () const
Molar internal energy. Units: J/kmol.
virtual doublereal gibbs_mole () const
Molar Gibbs function. Units: J/kmol.
virtual doublereal cv_vib (int, double) const
virtual doublereal isothermalCompressibility () const
Returns the isothermal compressibility. Units: 1/Pa.
virtual doublereal thermalExpansionCoeff () const
Return the volumetric thermal expansion coefficient. Units: 1/K.
void setElectricPotential (doublereal v)
Set the electric potential of this phase (V).
doublereal electricPotential () const
Returns the electric potential of this phase (V).
virtual int activityConvention () const
This method returns the convention used in specification of the activities, of which there are currently two, molar- and molality-based conventions.
virtual doublereal logStandardConc (size_t k=0) const
Natural logarithm of the standard concentration of the kth species.
virtual void getActivities (doublereal *a) const
Get the array of non-dimensional activities at the current solution temperature, pressure, and solution concentration.
virtual void getLnActivityCoefficients (doublereal *lnac) const
Get the array of non-dimensional molar-based ln activity coefficients at the current solution temperature, pressure, and solution concentration.
void getElectrochemPotentials (doublereal *mu) const
Get the species electrochemical potentials.
virtual void getdPartialMolarVolumes_dT (doublereal *d_vbar_dT) const
Return an array of derivatives of partial molar volumes wrt temperature for the species in the mixture.
virtual void getdPartialMolarVolumes_dP (doublereal *d_vbar_dP) const
Return an array of derivatives of partial molar volumes wrt pressure for the species in the mixture.
virtual void getdStandardVolumes_dT (doublereal *d_vol_dT) const
Get the derivative of the molar volumes of the species standard states wrt temperature at the current T and P of the solution.
virtual void getdStandardVolumes_dP (doublereal *d_vol_dP) const
Get the derivative molar volumes of the species standard states wrt pressure at the current T and P of the solution.
virtual void getIntEnergy_RT_ref (doublereal *urt) const
Returns the vector of nondimensional internal Energies of the reference state at the current temperature of the solution and the reference pressure for each species.
virtual void setReferenceComposition (const doublereal *const x)
Sets the reference composition.
virtual void getReferenceComposition (doublereal *const x) const
Gets the reference composition.
doublereal enthalpy_mass () const
Specific enthalpy.
doublereal intEnergy_mass () const
Specific internal energy.
doublereal entropy_mass () const
Specific entropy.
doublereal gibbs_mass () const
Specific Gibbs function.
doublereal cp_mass () const
Specific heat at constant pressure.
doublereal cv_mass () const
Specific heat at constant volume.
virtual void setState_TPX (doublereal t, doublereal p, const compositionMap &x)
Set the temperature (K), pressure (Pa), and mole fractions.
virtual void setState_TPX (doublereal t, doublereal p, const std::string &x)
Set the temperature (K), pressure (Pa), and mole fractions.
virtual void setState_TPY (doublereal t, doublereal p, const doublereal *y)
Set the internally stored temperature (K), pressure (Pa), and mass fractions of the phase.
virtual void setState_TPY (doublereal t, doublereal p, const compositionMap &y)
Set the internally stored temperature (K), pressure (Pa), and mass fractions of the phase.
virtual void setState_TPY (doublereal t, doublereal p, const std::string &y)
Set the internally stored temperature (K), pressure (Pa), and mass fractions of the phase.
virtual void setState_PX (doublereal p, doublereal *x)
Set the pressure (Pa) and mole fractions.
virtual void setState_PY (doublereal p, doublereal *y)
Set the internally stored pressure (Pa) and mass fractions.
virtual void setState_HP (doublereal h, doublereal p, doublereal tol=1.e-4)
Set the internally stored specific enthalpy (J/kg) and pressure (Pa) of the phase.
virtual void setState_UV (doublereal u, doublereal v, doublereal tol=1.e-4)
Set the specific internal energy (J/kg) and specific volume (m^3/kg).
virtual void setState_SP (doublereal s, doublereal p, doublereal tol=1.e-4)
Set the specific entropy (J/kg/K) and pressure (Pa).
virtual void setState_SV (doublereal s, doublereal v, doublereal tol=1.e-4)
Set the specific entropy (J/kg/K) and specific volume (m^3/kg).
void equilibrate (const std::string &XY, const std::string &solver="auto", double rtol=1e-9, int max_steps=50000, int max_iter=100, int estimate_equil=0, int log_level=0)
Equilibrate a ThermoPhase object.
void setElementPotentials (const vector_fp &lambda)
Stores the element potentials in the ThermoPhase object.
bool getElementPotentials (doublereal *lambda) const
Returns the element potentials stored in the ThermoPhase object.
virtual doublereal satTemperature (doublereal p) const
Return the saturation temperature given the pressure.
virtual doublereal vaporFraction () const
Return the fraction of vapor at the current conditions.
virtual void setState_Tsat (doublereal t, doublereal x)
Set the state to a saturated system at a particular temperature.
virtual void setState_Psat (doublereal p, doublereal x)
Set the state to a saturated system at a particular pressure.
virtual bool addSpecies (shared_ptr< Species > spec)
Add a Species to this Phase.
void saveSpeciesData (const size_t k, const XML_Node *const data)
Store a reference pointer to the XML tree containing the species data for this phase.
const std::vector< const
XML_Node * > & speciesData () const
Return a pointer to the vector of XML nodes containing the species data for this phase.
void setSpeciesThermo (SpeciesThermo *spthermo)
Install a species thermodynamic property manager.
virtual SpeciesThermo & speciesThermo (int k=-1)
Return a changeable reference to the calculation manager for species reference-state thermodynamic properties.
virtual void initThermoFile (const std::string &inputFile, const std::string &id)
virtual void installSlavePhases (Cantera::XML_Node *phaseNode)
Add in species from Slave phases.
virtual void setParameters (int n, doublereal *const c)
Set the equation of state parameters.
virtual void getParameters (int &n, doublereal *const c) const
Get the equation of state parameters in a vector.
virtual void getdlnActCoeffds (const doublereal dTds, const doublereal *const dXds, doublereal *dlnActCoeffds) const
Get the change in activity coefficients wrt changes in state (temp, mole fraction, etc) along a line in parameter space or along a line in physical space.
virtual void getdlnActCoeffdlnX_diag (doublereal *dlnActCoeffdlnX_diag) const
Get the array of ln mole fraction derivatives of the log activity coefficients - diagonal component only.
virtual void getdlnActCoeffdlnN (const size_t ld, doublereal *const dlnActCoeffdlnN)
Get the array of derivatives of the log activity coefficients with respect to the log of the species mole numbers.
virtual void getdlnActCoeffdlnN_numderiv (const size_t ld, doublereal *const dlnActCoeffdlnN)
virtual std::string report (bool show_thermo=true, doublereal threshold=-1e-14) const
returns a summary of the state of the phase as a string
virtual void reportCSV (std::ofstream &csvFile) const
returns a summary of the state of the phase to a comma separated file.
Public Member Functions inherited from Phase
Phase ()
Default constructor.
virtual ~Phase ()
Destructor.
Phase (const Phase &right)
Copy Constructor.
Phase & operator= (const Phase &right)
Assignment operator.
XML_Node & xml () const
Returns a const reference to the XML_Node that describes the phase.
void setXMLdata (XML_Node &xmlPhase)
Stores the XML tree information for the current phase.
void saveState (vector_fp &state) const
Save the current internal state of the phase Write to vector 'state' the current internal state.
void saveState (size_t lenstate, doublereal *state) const
Write to array 'state' the current internal state.
void restoreState (const vector_fp &state)
Restore a state saved on a previous call to saveState.
void restoreState (size_t lenstate, const doublereal *state)
Restore the state of the phase from a previously saved state vector.
doublereal molecularWeight (size_t k) const
Molecular weight of species k.
void getMolecularWeights (vector_fp &weights) const
Copy the vector of molecular weights into vector weights.
void getMolecularWeights (doublereal *weights) const
Copy the vector of molecular weights into array weights.
const vector_fp & molecularWeights () const
Return a const reference to the internal vector of molecular weights.
doublereal size (size_t k) const
This routine returns the size of species k.
doublereal charge (size_t k) const
Dimensionless electrical charge of a single molecule of species k The charge is normalized by the the magnitude of the electron charge.
doublereal chargeDensity () const
Charge density [C/m^3].
size_t nDim () const
Returns the number of spatial dimensions (1, 2, or 3)
void setNDim (size_t ndim)
Set the number of spatial dimensions (1, 2, or 3).
virtual bool ready () const
Returns a bool indicating whether the object is ready for use.
int stateMFNumber () const
Return the State Mole Fraction Number.
std::string id () const
Return the string id for the phase.
void setID (const std::string &id)
Set the string id for the phase.
std::string name () const
Return the name of the phase.
void setName (const std::string &nm)
Sets the string name for the phase.
std::string elementName (size_t m) const
Name of the element with index m.
size_t elementIndex (const std::string &name) const
Return the index of element named 'name'.
const std::vector< std::string > & elementNames () const
Return a read-only reference to the vector of element names.
doublereal atomicWeight (size_t m) const
Atomic weight of element m.
doublereal entropyElement298 (size_t m) const
Entropy of the element in its standard state at 298 K and 1 bar.
int atomicNumber (size_t m) const
Atomic number of element m.
int elementType (size_t m) const
Return the element constraint type Possible types include:
int changeElementType (int m, int elem_type)
Change the element type of the mth constraint Reassigns an element type.
const vector_fp & atomicWeights () const
Return a read-only reference to the vector of atomic weights.
size_t nElements () const
Number of elements.
void checkElementIndex (size_t m) const
Check that the specified element index is in range Throws an exception if m is greater than nElements()-1.
void checkElementArraySize (size_t mm) const
Check that an array size is at least nElements() Throws an exception if mm is less than nElements().
doublereal nAtoms (size_t k, size_t m) const
Number of atoms of element m in species k.
void getAtoms (size_t k, double *atomArray) const
Get a vector containing the atomic composition of species k.
size_t speciesIndex (const std::string &name) const
Returns the index of a species named 'name' within the Phase object.
std::string speciesName (size_t k) const
Name of the species with index k.
std::string speciesSPName (int k) const
Returns the expanded species name of a species, including the phase name This is guaranteed to be unique within a Cantera problem.
const std::vector< std::string > & speciesNames () const
Return a const reference to the vector of species names.
size_t nSpecies () const
Returns the number of species in the phase.
void checkSpeciesIndex (size_t k) const
Check that the specified species index is in range Throws an exception if k is greater than nSpecies()-1.
void checkSpeciesArraySize (size_t kk) const
Check that an array size is at least nSpecies() Throws an exception if kk is less than nSpecies().
void setMoleFractionsByName (const compositionMap &xMap)
Set the species mole fractions by name.
void setMoleFractionsByName (const std::string &x)
Set the mole fractions of a group of species by name.
void setMassFractionsByName (const compositionMap &yMap)
Set the species mass fractions by name.
void setMassFractionsByName (const std::string &x)
Set the species mass fractions by name.
void setState_TRX (doublereal t, doublereal dens, const doublereal *x)
Set the internally stored temperature (K), density, and mole fractions.
void setState_TRX (doublereal t, doublereal dens, const compositionMap &x)
Set the internally stored temperature (K), density, and mole fractions.
void setState_TRY (doublereal t, doublereal dens, const doublereal *y)
Set the internally stored temperature (K), density, and mass fractions.
void setState_TRY (doublereal t, doublereal dens, const compositionMap &y)
Set the internally stored temperature (K), density, and mass fractions.
void setState_TNX (doublereal t, doublereal n, const doublereal *x)
Set the internally stored temperature (K), molar density (kmol/m^3), and mole fractions.
void setState_TR (doublereal t, doublereal rho)
Set the internally stored temperature (K) and density (kg/m^3)
void setState_TX (doublereal t, doublereal *x)
Set the internally stored temperature (K) and mole fractions.
void setState_TY (doublereal t, doublereal *y)
Set the internally stored temperature (K) and mass fractions.
void setState_RX (doublereal rho, doublereal *x)
Set the density (kg/m^3) and mole fractions.
void setState_RY (doublereal rho, doublereal *y)
Set the density (kg/m^3) and mass fractions.
void getMoleFractionsByName (compositionMap &x) const
Get the mole fractions by name.
compositionMap getMoleFractionsByName (double threshold=0.0) const
Get the mole fractions by name.
doublereal moleFraction (size_t k) const
Return the mole fraction of a single species.
doublereal moleFraction (const std::string &name) const
Return the mole fraction of a single species.
compositionMap getMassFractionsByName (double threshold=0.0) const
Get the mass fractions by name.
doublereal massFraction (size_t k) const
Return the mass fraction of a single species.
doublereal massFraction (const std::string &name) const
Return the mass fraction of a single species.
void getMoleFractions (doublereal *const x) const
Get the species mole fraction vector.
void getMassFractions (doublereal *const y) const
Get the species mass fractions.
const doublereal * massFractions () const
Return a const pointer to the mass fraction array.
void getConcentrations (doublereal *const c) const
Get the species concentrations (kmol/m^3).
doublereal concentration (const size_t k) const
Concentration of species k.
doublereal elementalMassFraction (const size_t m) const
Elemental mass fraction of element m.
doublereal elementalMoleFraction (const size_t m) const
Elemental mole fraction of element m.
const doublereal * moleFractdivMMW () const
Returns a const pointer to the start of the moleFraction/MW array.
doublereal temperature () const
Temperature (K).
virtual doublereal density () const
Density (kg/m^3).
doublereal molarDensity () const
Molar density (kmol/m^3).
doublereal molarVolume () const
Molar volume (m^3/kmol).
virtual void setDensity (const doublereal density_)
Set the internally stored density (kg/m^3) of the phase Note the density of a phase is an independent variable.
virtual void setMolarDensity (const doublereal molarDensity)
Set the internally stored molar density (kmol/m^3) of the phase.
doublereal mean_X (const doublereal *const Q) const
Evaluate the mole-fraction-weighted mean of an array Q.
doublereal mean_X (const vector_fp &Q) const
Evaluate the mole-fraction-weighted mean of an array Q.
doublereal mean_Y (const doublereal *const Q) const
Evaluate the mass-fraction-weighted mean of an array Q.
doublereal meanMolecularWeight () const
The mean molecular weight. Units: (kg/kmol)
doublereal sum_xlogx () const
Evaluate \(\sum_k X_k \log X_k \).
doublereal sum_xlogQ (doublereal *const Q) const
Evaluate \(\sum_k X_k \log Q_k \).
size_t addElement (const std::string &symbol, doublereal weight=-12345.0, int atomicNumber=0, doublereal entropy298=ENTROPY298_UNKNOWN, int elem_type=CT_ELEM_TYPE_ABSPOS)
Add an element.
void addElement (const XML_Node &e)
Add an element from an XML specification.
void addUniqueElement (const std::string &symbol, doublereal weight=-12345.0, int atomicNumber=0, doublereal entropy298=ENTROPY298_UNKNOWN, int elem_type=CT_ELEM_TYPE_ABSPOS)
Add an element, checking for uniqueness The uniqueness is checked by comparing the string symbol.
void addUniqueElement (const XML_Node &e)
Add an element, checking for uniqueness The uniqueness is checked by comparing the string symbol.
void addElementsFromXML (const XML_Node &phase)
Add all elements referenced in an XML_Node tree.
void freezeElements ()
Prohibit addition of more elements, and prepare to add species.
bool elementsFrozen ()
True if freezeElements has been called.
size_t addUniqueElementAfterFreeze (const std::string &symbol, doublereal weight, int atomicNumber, doublereal entropy298=ENTROPY298_UNKNOWN, int elem_type=CT_ELEM_TYPE_ABSPOS)
Add an element after elements have been frozen, checking for uniqueness The uniqueness is checked by comparing the string symbol.
void addSpecies (const std::string &name, const doublereal *comp, doublereal charge=0.0, doublereal size=1.0)
void addUniqueSpecies (const std::string &name, const doublereal *comp, doublereal charge=0.0, doublereal size=1.0)
Add a species to the phase, checking for uniqueness of the name This routine checks for uniqueness of the string name.
shared_ptr< Species > species (const std::string &name) const
Return the Species object for the named species.
shared_ptr< Species > species (size_t k) const
Return the Species object for species whose index is k.
void ignoreUndefinedElements ()
Set behavior when adding a species containing undefined elements to just skip the species.
void addUndefinedElements ()
Set behavior when adding a species containing undefined elements to add those elements to the phase.
void throwUndefinedElements ()
Set the behavior when adding a species containing undefined elements to throw an exception.
Static Public Attributes
static const doublereal omega_a = 4.27480233540E-01
Omega constant for a -> value of a in terms of critical properties.
static const doublereal omega_b = 8.66403499650E-02
Omega constant for b.
static const doublereal omega_vc = 3.33333333333333E-01
Omega constant for the critical molar volume.
Protected Member Functions
virtual void calcDensity ()
Calculate the density of the mixture using the partial molar volumes and mole fractions as input.
virtual void setTemperature (const doublereal temp)
Set the temperature (K)
virtual void setMassFractions (const doublereal *const y)
Set the mass fractions to the specified values, and then normalize them so that they sum to 1.0.
virtual void setMassFractions_NoNorm (const doublereal *const y)
Set the mass fractions to the specified values without normalizing.
virtual void setMoleFractions (const doublereal *const x)
Set the mole fractions to the specified values, and then normalize them so that they sum to 1.0.
virtual void setMoleFractions_NoNorm (const doublereal *const x)
Set the mole fractions to the specified values without normalizing.
virtual void setConcentrations (const doublereal *const c)
Set the concentrations to the specified values within the phase.
virtual doublereal sresid () const
Calculate the deviation terms for the total entropy of the mixture from the ideal gas mixture.
virtual doublereal hresid () const
Calculate the deviation terms for the total enthalpy of the mixture from the ideal gas mixture.
Protected Member Functions inherited from MixtureFugacityTP
void setMoleFractions_NoState (const doublereal *const x)
virtual void _updateReferenceStateThermo () const
Updates the reference state thermodynamic functions at the current T of the solution.
const vector_fp & gibbs_RT_ref () const
Returns the vector of nondimensional Gibbs free energies of the reference state at the current temperature of the solution and the reference pressure for the species.
doublereal z () const
Calculate the value of z.
virtual doublereal psatEst (doublereal TKelvin) const
Estimate for the saturation pressure.
int corr0 (doublereal TKelvin, doublereal pres, doublereal &densLiq, doublereal &densGas, doublereal &liqGRT, doublereal &gasGRT)
Utility routine in the calculation of the saturation pressure.
Protected Member Functions inherited from ThermoPhase
virtual void getCsvReportData (std::vector< std::string > &names, std::vector< vector_fp > &data) const
Fills names and data with the column names and species thermo properties to be included in the output of the reportCSV method.
Protected Member Functions inherited from Phase
void setMolecularWeight (const int k, const double mw)
Set the molecular weight of a single species to a given value.
Protected Attributes
int m_standardMixingRules
boolean indicating whether standard mixing rules are applied
int m_formTempParam
Form of the temperature parameterization.
doublereal m_b_current
Value of b in the equation of state.
doublereal m_a_current
Value of a in the equation of state.
vector_fp a_vec_Curr_
vector_fp b_vec_Curr_
Array2D a_coeff_vec
vector_fp m_pc_Species
vector_fp m_tc_Species
vector_fp m_vc_Species
int NSolns_
doublereal Vroot_ [3]
vector_fp m_pp
Temporary storage - length = m_kk.
vector_fp m_tmpV
Temporary storage - length = m_kk.
vector_fp m_partialMolarVolumes
doublereal dpdV_
The derivative of the pressure wrt the volume.
doublereal dpdT_
The derivative of the pressure wrt the temperature.
vector_fp dpdni_
Vector of derivatives of pressure wrt mole number.
Protected Attributes inherited from MixtureFugacityTP
doublereal m_Pcurrent
Current value of the pressures.
std::vector< doublereal > moleFractions_
Storage for the current values of the mole fractions of the species.
int iState_
Current state of the fluid.
int forcedState_
Force the system to be on a particular side of the spinodal curve.
doublereal m_Tlast_ref
The last temperature at which the reference state thermodynamic properties were calculated at.
doublereal m_logc0
Temporary storage for log of p/rt.
vector_fp m_h0_RT
Temporary storage for dimensionless reference state enthalpies.
vector_fp m_cp0_R
Temporary storage for dimensionless reference state heat capacities.
vector_fp m_g0_RT
Temporary storage for dimensionless reference state Gibbs energies.
vector_fp m_s0_R
Temporary storage for dimensionless reference state entropies.
spinodalFunc * fdpdv_
Protected Attributes inherited from ThermoPhase
SpeciesThermo * m_spthermo
Pointer to the calculation manager for species reference-state thermodynamic properties.
std::vector< const XML_Node * > m_speciesData
Vector of pointers to the species databases.
doublereal m_phi
Stored value of the electric potential for this phase.
vector_fp m_lambdaRRT
Vector of element potentials.
bool m_hasElementPotentials
Boolean indicating whether there is a valid set of saved element potentials for this phase.
bool m_chargeNeutralityNecessary
Boolean indicating whether a charge neutrality condition is a necessity.
int m_ssConvention
Contains the standard state convention.
std::vector< doublereal > xMol_Ref
Reference Mole Fraction Composition.
doublereal m_tlast
last value of the temperature processed by reference state
Protected Attributes inherited from Phase
ValueCache m_cache
Cached for saved calculations within each ThermoPhase.
size_t m_kk
Number of species in the phase.
size_t m_ndim
Dimensionality of the phase.
vector_fp m_speciesComp
Atomic composition of the species.
vector_fp m_speciesSize
Vector of species sizes.
vector_fp m_speciesCharge
Vector of species charges. length m_kk.
std::map< std::string,
shared_ptr< Species > > m_species
UndefElement::behavior m_undefinedElementBehavior
Flag determining behavior when adding species with an undefined element.
Initialization Methods - For Internal use
virtual void setParametersFromXML (const XML_Node &thermoNode)
Set equation of state parameter values from XML entries.
virtual void initThermo ()
void setToEquilState (const doublereal *lambda_RT)
This method is used by the ChemEquil equilibrium solver.
virtual void initThermoXML (XML_Node &phaseNode, const std::string &id)
Initialize a ThermoPhase object, potentially reading activity coefficient information from an XML database.
void readXMLPureFluid (XML_Node &pureFluidParam)
Read the pure species RedlichKwong input parameters.
void applyStandardMixingRules ()
Apply mixing rules for a coefficients.
void readXMLCrossFluid (XML_Node &pureFluidParam)
Read the cross species RedlichKwong input parameters.
void initLengths ()
Additional Inherited Members
Public Attributes inherited from Phase
enum CT_RealNumber_Range_Behavior realNumberRangeBehavior_
Overflow behavior of real number calculations involving this thermo object.
Detailed Description
This class can handle either an ideal solution or an ideal gas approximation of a phase.
Definition at line 29 of file RedlichKwongMFTP.h.
Constructor & Destructor Documentation
RedlichKwongMFTP ()
Base constructor.
Definition at line 32 of file RedlichKwongMFTP.cpp.
Referenced by RedlichKwongMFTP::duplMyselfAsThermoPhase().
RedlichKwongMFTP (const std::string & infile, std::string id = "")
Construct and initialize a RedlichKwongMFTP object directly from an ASCII input file.
Parameters
infile Name of the input file containing the phase XML data to set up the object
id ID of the phase in the input file. Defaults to the empty string.
Definition at line 46 of file RedlichKwongMFTP.cpp.
References Cantera::get_XML_File(), Cantera::get_XML_NameID(), and Cantera::importPhase().
RedlichKwongMFTP (XML_Node & phaseRef, const std::string & id = "")
Construct and initialize a RedlichKwongMFTP object directly from an XML database.
Parameters
phaseRef XML phase node containing the description of the phase
id id attribute containing the name of the phase. (default is the empty string)
Definition at line 70 of file RedlichKwongMFTP.cpp.
References Cantera::get_XML_NameID(), and Cantera::importPhase().
RedlichKwongMFTP (int testProb)
This is a special constructor, used to replicate test problems during the initial verification of the object.
test problems: 1: Pure CO2 problem input file = CO2_RedlickKwongMFTP.xml
Parameters
testProb Hard -coded test problem to instantiate. Current valid values are 1.
Deprecated:
To be removed after Cantera 2.2.
Definition at line 89 of file RedlichKwongMFTP.cpp.
References Cantera::get_XML_File(), Cantera::get_XML_NameID(), Cantera::importPhase(), and Cantera::warn_deprecated().
RedlichKwongMFTP (const RedlichKwongMFTP & right)
Copy Constructor.
Copy constructor for the object. Constructed object will be a clone of this object, but will also own all of its data. This is a wrapper around the assignment operator
Parameters
right Object to be copied.
Definition at line 120 of file RedlichKwongMFTP.cpp.
Member Function Documentation
RedlichKwongMFTP & operator= (const RedlichKwongMFTP & right)
Assignment operator.
Assignment operator for the object. Constructed object will be a clone of this object, but will also own all of its data.
Parameters
right Object to be copied.
Definition at line 132 of file RedlichKwongMFTP.cpp.
References RedlichKwongMFTP::dpdni_, RedlichKwongMFTP::dpdT_, RedlichKwongMFTP::dpdV_, RedlichKwongMFTP::m_a_current, RedlichKwongMFTP::m_b_current, RedlichKwongMFTP::m_formTempParam, RedlichKwongMFTP::m_pp, RedlichKwongMFTP::m_standardMixingRules, RedlichKwongMFTP::m_tmpV, and MixtureFugacityTP::operator=().
ThermoPhase * duplMyselfAsThermoPhase () const virtual
Duplicator from the ThermoPhase parent class.
Given a pointer to a ThermoPhase object, this function will duplicate the ThermoPhase object and all underlying structures. This is basically a wrapper around the copy constructor.
Returns
returns a pointer to a ThermoPhase
Reimplemented from MixtureFugacityTP.
Definition at line 168 of file RedlichKwongMFTP.cpp.
References RedlichKwongMFTP::RedlichKwongMFTP().
int eosType () const virtual
Equation of state type flag.
The base class returns zero. Subclasses should define this to return a unique non-zero value. Constants defined for this purpose are listed in mix_defs.h.
Reimplemented from ThermoPhase.
Definition at line 173 of file RedlichKwongMFTP.cpp.
doublereal enthalpy_mole () const virtual
Molar enthalpy. Units: J/kmol.
Reimplemented from ThermoPhase.
Definition at line 182 of file RedlichKwongMFTP.cpp.
References ThermoPhase::_RT(), MixtureFugacityTP::_updateReferenceStateThermo(), RedlichKwongMFTP::hresid(), MixtureFugacityTP::m_h0_RT, and Phase::mean_X().
doublereal entropy_mole () const virtual
Molar entropy. Units: J/kmol/K.
Reimplemented from ThermoPhase.
Definition at line 190 of file RedlichKwongMFTP.cpp.
References MixtureFugacityTP::_updateReferenceStateThermo(), Cantera::GasConstant, MixtureFugacityTP::m_s0_R, ThermoPhase::m_spthermo, Phase::mean_X(), RedlichKwongMFTP::pressure(), SpeciesThermo::refPressure(), RedlichKwongMFTP::sresid(), and Phase::sum_xlogx().
doublereal cp_mole () const virtual
Molar heat capacity at constant pressure. Units: J/kmol/K.
Reimplemented from ThermoPhase.
Definition at line 199 of file RedlichKwongMFTP.cpp.
References MixtureFugacityTP::_updateReferenceStateThermo(), RedlichKwongMFTP::dpdT_, RedlichKwongMFTP::dpdV_, Cantera::GasConstant, RedlichKwongMFTP::m_a_current, RedlichKwongMFTP::m_b_current, MixtureFugacityTP::m_cp0_R, Phase::mean_X(), Phase::molarVolume(), RedlichKwongMFTP::pressureDerivatives(), and Phase::temperature().
Referenced by RedlichKwongMFTP::cv_mole().
doublereal cv_mole () const virtual
Molar heat capacity at constant volume. Units: J/kmol/K.
Reimplemented from ThermoPhase.
Definition at line 215 of file RedlichKwongMFTP.cpp.
References RedlichKwongMFTP::cp_mole(), and Cantera::GasConstant.
doublereal pressure () const virtual
Return the thermodynamic pressure (Pa).
Since the mass density, temperature, and mass fractions are stored, this method uses these values to implement the mechanical equation of state \(P(T, \rho, Y_1, \dots, Y_K) \).
\[ P = \frac{RT}{v-b_{mix}} - \frac{a_{mix}}{T^{0.5} v \left(v + b_{mix} \right) } \]
Reimplemented from MixtureFugacityTP.
Definition at line 221 of file RedlichKwongMFTP.cpp.
References MixtureFugacityTP::_updateReferenceStateThermo(), Phase::density(), Cantera::GasConstant, RedlichKwongMFTP::m_a_current, RedlichKwongMFTP::m_b_current, MixtureFugacityTP::m_Pcurrent, Phase::meanMolecularWeight(), and Phase::temperature().
Referenced by RedlichKwongMFTP::entropy_mole(), RedlichKwongMFTP::getActivityCoefficients(), and RedlichKwongMFTP::getChemPotentials().
void calcDensity () protected virtual
Calculate the density of the mixture using the partial molar volumes and mole fractions as input.
The formula for this is
\[ \rho = \frac{\sum_k{X_k W_k}}{\sum_k{X_k V_k}} \]
where \(X_k\) are the mole fractions, \(W_k\) are the molecular weights, and \(V_k\) are the pure species molar volumes.
Note, the basis behind this formula is that in an ideal solution the partial molar volumes are equal to the species standard state molar volumes. The species molar volumes may be functions of temperature and pressure.
Reimplemented from MixtureFugacityTP.
Definition at line 239 of file RedlichKwongMFTP.cpp.
References DATA_PTR, Cantera::dot(), RedlichKwongMFTP::getPartialMolarVolumes(), RedlichKwongMFTP::m_tmpV, Phase::moleFractdivMMW(), and Phase::setDensity().
void setTemperature (const doublereal temp) protected virtual
Set the temperature (K)
This function sets the temperature, and makes sure that the value propagates to underlying objects
Parameters
temp Temperature in kelvin
Reimplemented from MixtureFugacityTP.
Definition at line 255 of file RedlichKwongMFTP.cpp.
References MixtureFugacityTP::_updateReferenceStateThermo(), Phase::setTemperature(), and RedlichKwongMFTP::updateAB().
Referenced by RedlichKwongMFTP::densityCalc().
void setMassFractions (const doublereal *const y) protected virtual
Set the mass fractions to the specified values, and then normalize them so that they sum to 1.0.
Parameters
y Array of unnormalized mass fraction values (input). Must have a length greater than or equal to the number of species.
Reimplemented from MixtureFugacityTP.
Definition at line 262 of file RedlichKwongMFTP.cpp.
References MixtureFugacityTP::setMassFractions(), and RedlichKwongMFTP::updateAB().
void setMassFractions_NoNorm (const doublereal *const y) protected virtual
Set the mass fractions to the specified values without normalizing.
This is useful when the normalization condition is being handled by some other means, for example by a constraint equation as part of a larger set of equations.
Parameters
y Input vector of mass fractions. Length is m_kk.
Reimplemented from MixtureFugacityTP.
Definition at line 268 of file RedlichKwongMFTP.cpp.
References MixtureFugacityTP::setMassFractions_NoNorm(), and RedlichKwongMFTP::updateAB().
void setMoleFractions (const doublereal *const x) protected virtual
Set the mole fractions to the specified values, and then normalize them so that they sum to 1.0.
Parameters
x Array of unnormalized mole fraction values (input). Must have a length greater than or equal to the number of species.
Reimplemented from MixtureFugacityTP.
Definition at line 274 of file RedlichKwongMFTP.cpp.
References MixtureFugacityTP::setMoleFractions(), and RedlichKwongMFTP::updateAB().
void setMoleFractions_NoNorm (const doublereal *const x) protected virtual
Set the mole fractions to the specified values without normalizing.
This is useful when the normalization condition is being handled by some other means, for example by a constraint equation as part of a larger set of equations.
Parameters
x Input vector of mole fractions. Length is m_kk.
Reimplemented from MixtureFugacityTP.
Definition at line 280 of file RedlichKwongMFTP.cpp.
References MixtureFugacityTP::setMoleFractions(), and RedlichKwongMFTP::updateAB().
void setConcentrations (const doublereal *const c) protected virtual
Set the concentrations to the specified values within the phase.
Parameters
c The input vector to this routine is in dimensional units. For volumetric phases c[k] is the concentration of the kth species in kmol/m3. For surface phases, c[k] is the concentration in kmol/m2. The length of the vector is the number of species in the phase.
Reimplemented from MixtureFugacityTP.
Definition at line 286 of file RedlichKwongMFTP.cpp.
References MixtureFugacityTP::setConcentrations(), and RedlichKwongMFTP::updateAB().
void getActivityConcentrations (doublereal * c) const virtual
This method returns an array of generalized concentrations.
\(C^a_k\) are defined such that \(a_k = C^a_k / C^0_k, \) where \(C^0_k \) is a standard concentration defined below and \(a_k \) are activities used in the thermodynamic functions. These activity (or generalized) concentrations are used by kinetics manager classes to compute the forward and reverse rates of elementary reactions. Note that they may or may not have units of concentration — they might be partial pressures, mole fractions, or surface coverages, for example.
Parameters
c Output array of generalized concentrations. The units depend upon the implementation of the reaction rate expressions within the phase.
Reimplemented from ThermoPhase.
Definition at line 292 of file RedlichKwongMFTP.cpp.
References DATA_PTR, RedlichKwongMFTP::getPartialMolarVolumes(), Phase::m_kk, and Phase::moleFraction().
doublereal standardConcentration (size_t k = 0) const virtual
Returns the standard concentration \(C^0_k \), which is used to normalize the generalized concentration.
This is defined as the concentration by which the generalized concentration is normalized to produce the activity. In many cases, this quantity will be the same for all species in a phase. Since the activity for an ideal gas mixture is simply the mole fraction, for an ideal gas \(C^0_k = P/\hat R T \).
Parameters
k Optional parameter indicating the species. The default is to assume this refers to species 0.
Returns
Returns the standard Concentration in units of m3 kmol-1.
Reimplemented from ThermoPhase.
Definition at line 300 of file RedlichKwongMFTP.cpp.
References DATA_PTR, MixtureFugacityTP::getStandardVolumes(), and RedlichKwongMFTP::m_tmpV.
void getUnitsStandardConc (double * uA, int k = 0, int sizeUA = 6) const virtual
Returns the units of the standard and generalized concentrations.
Note they have the same units, as their ratio is defined to be equal to the activity of the kth species in the solution, which is unitless.
This routine is used in print out applications where the units are needed. Usually, MKS units are assumed throughout the program and in the XML input files.
The base ThermoPhase class assigns the default quantities of (kmol/m3) for all species. Inherited classes are responsible for overriding the default values if necessary.
Parameters
uA Output vector containing the units:
uA[0] = kmol units - default  = 1
uA[1] = m    units - default  = -nDim(), the number of spatial
                              dimensions in the Phase class.
uA[2] = kg   units - default  = 0;
uA[3] = Pa(pressure) units - default = 0;
uA[4] = Temperature units - default = 0;
uA[5] = time units - default = 0
k species index. Defaults to 0.
sizeUA output int containing the size of the vector. Currently, this is equal to 6.
Deprecated:
To be removed after Cantera 2.2.
Reimplemented from ThermoPhase.
Definition at line 306 of file RedlichKwongMFTP.cpp.
References Phase::nDim(), and Cantera::warn_deprecated().
void getActivityCoefficients (doublereal * ac) const virtual
Get the array of non-dimensional activity coefficients at the current solution temperature, pressure, and solution concentration.
For all objects with the Mixture Fugacity approximation, we define the standard state as an ideal gas at the current temperature and pressure of the solution. The activities are based on this standard state.
Parameters
ac Output vector of activity coefficients. Length: m_kk.
Reimplemented from ThermoPhase.
Definition at line 336 of file RedlichKwongMFTP.cpp.
References Cantera::GasConstant, RedlichKwongMFTP::m_a_current, RedlichKwongMFTP::m_b_current, Phase::m_kk, RedlichKwongMFTP::m_pp, Phase::molarVolume(), MixtureFugacityTP::moleFractions_, RedlichKwongMFTP::pressure(), and Phase::temperature().
void getChemPotentials_RT (doublereal * mu) const virtual
Get the array of non-dimensional species chemical potentials.
These are partial molar Gibbs free energies.
\(\mu_k / \hat R T \). Units: unitless
We close the loop on this function, here, calling getChemPotentials() and then dividing by RT. No need for child classes to handle.
Parameters
mu Output vector of non-dimensional species chemical potentials Length: m_kk.
Reimplemented from MixtureFugacityTP.
Definition at line 372 of file RedlichKwongMFTP.cpp.
References ThermoPhase::_RT(), RedlichKwongMFTP::getChemPotentials(), and Phase::m_kk.
void getChemPotentials (doublereal * mu) const virtual
Get the species chemical potentials. Units: J/kmol.
This function returns a vector of chemical potentials of the species in solution at the current temperature, pressure and mole fraction of the solution.
Parameters
mu Output vector of species chemical potentials. Length: m_kk. Units: J/kmol
Reimplemented from ThermoPhase.
Definition at line 381 of file RedlichKwongMFTP.cpp.
References Cantera::GasConstant, MixtureFugacityTP::getGibbs_ref(), RedlichKwongMFTP::m_a_current, RedlichKwongMFTP::m_b_current, Phase::m_kk, RedlichKwongMFTP::m_pp, Phase::molarVolume(), Phase::moleFraction(), MixtureFugacityTP::moleFractions_, RedlichKwongMFTP::pressure(), ThermoPhase::refPressure(), Cantera::SmallNumber, and Phase::temperature().
Referenced by RedlichKwongMFTP::getChemPotentials_RT().
void getPartialMolarEnthalpies (doublereal * hbar) const virtual
Get the species partial molar enthalpies. Units: J/kmol.
Parameters
hbar Output vector of species partial molar enthalpies. Length: m_kk. units are J/kmol.
Reimplemented from ThermoPhase.
Definition at line 417 of file RedlichKwongMFTP.cpp.
References RedlichKwongMFTP::dpdni_, RedlichKwongMFTP::dpdT_, RedlichKwongMFTP::dpdV_, Cantera::GasConstant, MixtureFugacityTP::getEnthalpy_RT_ref(), RedlichKwongMFTP::m_a_current, RedlichKwongMFTP::m_b_current, Phase::m_kk, RedlichKwongMFTP::m_pp, RedlichKwongMFTP::m_tmpV, Phase::molarVolume(), MixtureFugacityTP::moleFractions_, RedlichKwongMFTP::pressureDerivatives(), Cantera::scale(), and Phase::temperature().
void getPartialMolarEntropies (doublereal * sbar) const virtual
Get the species partial molar entropies. Units: J/kmol/K.
Parameters
sbar Output vector of species partial molar entropies. Length = m_kk. units are J/kmol/K.
Reimplemented from ThermoPhase.
Definition at line 476 of file RedlichKwongMFTP.cpp.
References DATA_PTR, RedlichKwongMFTP::dpdT_, Cantera::GasConstant, MixtureFugacityTP::getEntropy_R_ref(), RedlichKwongMFTP::getPartialMolarVolumes(), RedlichKwongMFTP::m_a_current, RedlichKwongMFTP::m_b_current, Phase::m_kk, RedlichKwongMFTP::m_pp, RedlichKwongMFTP::m_tmpV, Phase::molarVolume(), Phase::moleFraction(), MixtureFugacityTP::moleFractions_, RedlichKwongMFTP::pressureDerivatives(), ThermoPhase::refPressure(), Cantera::scale(), Cantera::SmallNumber, and Phase::temperature().
void getPartialMolarIntEnergies (doublereal * ubar) const virtual
Get the species partial molar enthalpies. Units: J/kmol.
Parameters
ubar Output vector of species partial molar internal energies. Length = m_kk. units are J/kmol.
Reimplemented from ThermoPhase.
Definition at line 533 of file RedlichKwongMFTP.cpp.
References Cantera::GasConstant, MixtureFugacityTP::getIntEnergy_RT(), Phase::m_kk, Cantera::scale(), and Phase::temperature().
void getPartialMolarCp (doublereal * cpbar) const virtual
Get the partial molar heat capacities Units: J/kmol/K.
Parameters
cpbar Output vector of species partial molar heat capacities at constant pressure. Length = m_kk. units are J/kmol/K.
Reimplemented from ThermoPhase.
Definition at line 540 of file RedlichKwongMFTP.cpp.
References Cantera::GasConstant, MixtureFugacityTP::getCp_R(), Phase::m_kk, and Cantera::scale().
void getPartialMolarVolumes (doublereal * vbar) const virtual
Get the species partial molar volumes. Units: m^3/kmol.
Parameters
vbar Output vector of species partial molar volumes. Length = m_kk. units are m^3/kmol.
Reimplemented from ThermoPhase.
Definition at line 547 of file RedlichKwongMFTP.cpp.
References Cantera::GasConstant, RedlichKwongMFTP::m_a_current, RedlichKwongMFTP::m_b_current, Phase::m_kk, MixtureFugacityTP::m_Pcurrent, RedlichKwongMFTP::m_pp, RedlichKwongMFTP::m_tmpV, Phase::molarVolume(), MixtureFugacityTP::moleFractions_, and Phase::temperature().
Referenced by RedlichKwongMFTP::calcDensity(), RedlichKwongMFTP::getActivityConcentrations(), and RedlichKwongMFTP::getPartialMolarEntropies().
doublereal critTemperature () const virtual
Critical temperature (K).
Reimplemented from ThermoPhase.
Definition at line 590 of file RedlichKwongMFTP.cpp.
References RedlichKwongMFTP::m_a_current, RedlichKwongMFTP::m_b_current, Phase::m_kk, and MixtureFugacityTP::moleFractions_.
Referenced by RedlichKwongMFTP::densityCalc().
doublereal critPressure () const virtual
Critical pressure (Pa).
Reimplemented from ThermoPhase.
Definition at line 606 of file RedlichKwongMFTP.cpp.
References RedlichKwongMFTP::m_a_current, RedlichKwongMFTP::m_b_current, Phase::m_kk, and MixtureFugacityTP::moleFractions_.
Referenced by RedlichKwongMFTP::liquidVolEst().
doublereal critVolume () const virtual
Critical volume (m3/kmol)
Reimplemented from ThermoPhase.
Definition at line 623 of file RedlichKwongMFTP.cpp.
References RedlichKwongMFTP::m_a_current, RedlichKwongMFTP::m_b_current, Phase::m_kk, and MixtureFugacityTP::moleFractions_.
doublereal critCompressibility () const virtual
Critical compressibility (unitless).
Reimplemented from ThermoPhase.
Definition at line 639 of file RedlichKwongMFTP.cpp.
References Cantera::GasConstant, RedlichKwongMFTP::m_a_current, RedlichKwongMFTP::m_b_current, Phase::m_kk, and MixtureFugacityTP::moleFractions_.
doublereal critDensity () const virtual
Critical density (kg/m3).
Reimplemented from ThermoPhase.
Definition at line 655 of file RedlichKwongMFTP.cpp.
References RedlichKwongMFTP::m_a_current, RedlichKwongMFTP::m_b_current, Phase::m_kk, Phase::meanMolecularWeight(), and MixtureFugacityTP::moleFractions_.
Referenced by RedlichKwongMFTP::densSpinodalGas(), and RedlichKwongMFTP::densSpinodalLiquid().
void setParametersFromXML (const XML_Node & thermoNode) virtual
Set equation of state parameter values from XML entries.
The following methods are used in the process of constructing the phase and setting its parameters from a specification in an input file. They are not normally used in application programs. To see how they are used, see importPhase().
This method is called by function importPhase() when processing a phase definition in an input file. It should be overloaded in subclasses to set any parameters that are specific to that particular phase model.
Parameters
thermoNode An XML_Node object corresponding to the "thermo" entry for this phase in the input file.
Reimplemented from ThermoPhase.
Definition at line 963 of file RedlichKwongMFTP.cpp.
References ThermoPhase::setParametersFromXML().
void initThermo () virtual
Initialize the object
This method is provided to allow subclasses to perform any initialization required after all species have been added. For example, it might be used to resize internal work arrays that must have an entry for each species. The base class implementation does nothing, and subclasses that do not require initialization do not need to overload this method. When importing a CTML phase description, this method is called just prior to returning from function importPhase().
Reimplemented from MixtureFugacityTP.
Definition at line 673 of file RedlichKwongMFTP.cpp.
References RedlichKwongMFTP::initLengths(), and MixtureFugacityTP::initThermo().
void setToEquilState (const doublereal * lambda_RT) virtual
This method is used by the ChemEquil equilibrium solver.
It sets the state such that the chemical potentials satisfy
\[ \frac{\mu_k}{\hat R T} = \sum_m A_{k,m} \left(\frac{\lambda_m} {\hat R T}\right) \]
where \(\lambda_m \) is the element potential of element m. The temperature is unchanged. Any phase (ideal or not) that implements this method can be equilibrated by ChemEquil.
Parameters
lambda_RT Input vector of dimensionless element potentials The length is equal to nElements().
Reimplemented from ThermoPhase.
Definition at line 679 of file RedlichKwongMFTP.cpp.
References MixtureFugacityTP::_updateReferenceStateThermo(), DATA_PTR, MixtureFugacityTP::getGibbs_RT_ref(), Phase::m_kk, RedlichKwongMFTP::m_pp, RedlichKwongMFTP::m_tmpV, ThermoPhase::refPressure(), and ThermoPhase::setState_PX().
void initThermoXML (XML_Node & phaseNode, const std::string & id) virtual
Initialize a ThermoPhase object, potentially reading activity coefficient information from an XML database.
This routine initializes the lengths in the current object and then calls the parent routine. This method is provided to allow subclasses to perform any initialization required after all species have been added. For example, it might be used to resize internal work arrays that must have an entry for each species. The base class implementation does nothing, and subclasses that do not require initialization do not need to overload this method. When importing a CTML phase description, this method is called just prior to returning from function importPhase().
Parameters
phaseNode This object must be the phase node of a complete XML tree description of the phase, including all of the species data. In other words while "phase" must point to an XML phase object, it must have sibling nodes "speciesData" that describe the species in the phase.
id ID of the phase. If nonnull, a check is done to see if phaseNode is pointing to the phase with the correct id.
Reimplemented from MixtureFugacityTP.
Definition at line 731 of file RedlichKwongMFTP.cpp.
References RedlichKwongMFTP::applyStandardMixingRules(), XML_Node::child(), XML_Node::hasChild(), RedlichKwongMFTP::initLengths(), MixtureFugacityTP::initThermoXML(), Cantera::lowercase(), Phase::m_kk, RedlichKwongMFTP::m_standardMixingRules, XML_Node::name(), XML_Node::nChildren(), RedlichKwongMFTP::readXMLCrossFluid(), and RedlichKwongMFTP::readXMLPureFluid().
void readXMLPureFluid (XML_Node & pureFluidParam) private
Read the pure species RedlichKwong input parameters.
Parameters
pureFluidParam XML_Node for the pure fluid parameters
Definition at line 815 of file RedlichKwongMFTP.cpp.
References XML_Node::attrib(), XML_Node::child(), Cantera::getFloatArray(), Cantera::lowercase(), RedlichKwongMFTP::m_formTempParam, Phase::m_kk, XML_Node::name(), XML_Node::nChildren(), Cantera::npos, and Phase::speciesIndex().
Referenced by RedlichKwongMFTP::initThermoXML().
void applyStandardMixingRules () private
Apply mixing rules for a coefficients.
Definition at line 879 of file RedlichKwongMFTP.cpp.
References Phase::m_kk.
Referenced by RedlichKwongMFTP::initThermoXML().
void readXMLCrossFluid (XML_Node & pureFluidParam) private
Read the cross species RedlichKwong input parameters.
Parameters
pureFluidParam XML_Node for the cross fluid parameters
Definition at line 896 of file RedlichKwongMFTP.cpp.
References XML_Node::attrib(), XML_Node::child(), Cantera::getFloatArray(), Cantera::lowercase(), RedlichKwongMFTP::m_formTempParam, Phase::m_kk, XML_Node::name(), XML_Node::nChildren(), Cantera::npos, and Phase::speciesIndex().
Referenced by RedlichKwongMFTP::initThermoXML().
void initLengths () private
Initialize the internal lengths in this object.
Note this is not a virtual function and only handles this object
Definition at line 714 of file RedlichKwongMFTP.cpp.
References RedlichKwongMFTP::dpdni_, Phase::m_kk, RedlichKwongMFTP::m_pp, RedlichKwongMFTP::m_tmpV, and Array2D::resize().
Referenced by RedlichKwongMFTP::initThermo(), and RedlichKwongMFTP::initThermoXML().
doublereal sresid () const protected virtual
Calculate the deviation terms for the total entropy of the mixture from the ideal gas mixture.
Here we use the current state conditions
Returns
Returns the change in entropy in units of J kmol-1 K-1.
Reimplemented from MixtureFugacityTP.
Definition at line 969 of file RedlichKwongMFTP.cpp.
References Phase::density(), Cantera::GasConstant, RedlichKwongMFTP::m_a_current, RedlichKwongMFTP::m_b_current, Phase::meanMolecularWeight(), Phase::temperature(), and MixtureFugacityTP::z().
Referenced by RedlichKwongMFTP::entropy_mole().
doublereal hresid () const protected virtual
Calculate the deviation terms for the total enthalpy of the mixture from the ideal gas mixture.
Reimplemented from MixtureFugacityTP.
Definition at line 985 of file RedlichKwongMFTP.cpp.
References Phase::density(), Cantera::GasConstant, RedlichKwongMFTP::m_a_current, RedlichKwongMFTP::m_b_current, Phase::meanMolecularWeight(), Phase::temperature(), and MixtureFugacityTP::z().
Referenced by RedlichKwongMFTP::enthalpy_mole().
doublereal liquidVolEst (doublereal TKelvin, doublereal & pres) const virtual
Estimate for the molar volume of the liquid.
Note: this is only used as a starting guess for later routines that actually calculate an accurate value for the liquid molar volume. This routine doesn't change the state of the system.
Parameters
TKelvin temperature in kelvin
pres Pressure in Pa. This is used as an initial guess. If the routine needs to change the pressure to find a stable liquid state, the new pressure is returned in this variable.
Returns
Returns the estimate of the liquid volume.
Reimplemented from MixtureFugacityTP.
Definition at line 1000 of file RedlichKwongMFTP.cpp.
References RedlichKwongMFTP::calculateAB(), RedlichKwongMFTP::critPressure(), RedlichKwongMFTP::m_b_current, RedlichKwongMFTP::NicholsSolve(), and MixtureFugacityTP::psatEst().
Referenced by RedlichKwongMFTP::densityCalc().
doublereal densityCalc (doublereal TKelvin, doublereal pressure, int phase, doublereal rhoguess) virtual
Calculates the density given the temperature and the pressure and a guess at the density.
Note, below T_c, this is a multivalued function. We do not cross the vapor dome in this. This is protected because it is called during setState_TP() routines. Infinite loops would result if it were not protected.
-> why is this not const?
parameters:
Parameters
TKelvin Temperature in Kelvin
pressure Pressure in Pascals (Newton/m**2)
phase int representing the phase whose density we are requesting. If we put a gas or liquid phase here, we will attempt to find a volume in that part of the volume space, only, in this routine. A value of FLUID_UNDEFINED means that we will accept anything.
rhoguess Guessed density of the fluid. A value of -1.0 indicates that there is no guessed density
Returns
We return the density of the fluid at the requested phase. If we have not found any acceptable density we return a -1. If we have found an acceptable density at a different phase, we return a -2.
Reimplemented from MixtureFugacityTP.
Definition at line 1037 of file RedlichKwongMFTP.cpp.
References RedlichKwongMFTP::critTemperature(), Cantera::GasConstant, RedlichKwongMFTP::liquidVolEst(), RedlichKwongMFTP::m_a_current, RedlichKwongMFTP::m_b_current, Phase::meanMolecularWeight(), RedlichKwongMFTP::NicholsSolve(), and RedlichKwongMFTP::setTemperature().
doublereal densSpinodalLiquid () const virtual
Return the value of the density at the liquid spinodal point (on the liquid side) for the current temperature.
Returns
returns the density with units of kg m-3
Reimplemented from MixtureFugacityTP.
Definition at line 1105 of file RedlichKwongMFTP.cpp.
References RedlichKwongMFTP::critDensity(), Phase::meanMolecularWeight(), ROOTFIND_SUCCESS, RootFind::setFuncIsGenerallyDecreasing(), RootFind::setPrintLvl(), RootFind::setTol(), and RootFind::solve().
doublereal densSpinodalGas () const virtual
Return the value of the density at the gas spinodal point (on the gas side) for the current temperature.
Returns
returns the density with units of kg m-3
Reimplemented from MixtureFugacityTP.
Definition at line 1128 of file RedlichKwongMFTP.cpp.
References RedlichKwongMFTP::critDensity(), Phase::meanMolecularWeight(), ROOTFIND_SUCCESS, RootFind::setFuncIsGenerallyIncreasing(), RootFind::setPrintLvl(), RootFind::setTol(), and RootFind::solve().
doublereal pressureCalc (doublereal TKelvin, doublereal molarVol) const virtual
Calculate the pressure given the temperature and the molar volume.
Calculate the pressure given the temperature and the molar volume
Parameters
TKelvin temperature in kelvin
molarVol molar volume (m3/kmol)
Returns
Returns the pressure.
Reimplemented from MixtureFugacityTP.
Definition at line 1151 of file RedlichKwongMFTP.cpp.
References Cantera::GasConstant, RedlichKwongMFTP::m_a_current, and RedlichKwongMFTP::m_b_current.
doublereal dpdVCalc (doublereal TKelvin, doublereal molarVol, doublereal & presCalc) const virtual
Calculate the pressure and the pressure derivative given the temperature and the molar volume.
Temperature and mole number are held constant
Parameters
TKelvin temperature in kelvin
molarVol molar volume (m3/kmol)
presCalc Returns the pressure.
Returns
Returns the derivative of the pressure wrt the molar volume
Reimplemented from MixtureFugacityTP.
Definition at line 1159 of file RedlichKwongMFTP.cpp.
References Cantera::GasConstant, RedlichKwongMFTP::m_a_current, and RedlichKwongMFTP::m_b_current.
Referenced by RedlichKwongMFTP::pressureDerivatives().
void pressureDerivatives () const
Calculate dpdV and dpdT at the current conditions.
These are stored internally.
Definition at line 1172 of file RedlichKwongMFTP.cpp.
References RedlichKwongMFTP::dpdT_, RedlichKwongMFTP::dpdV_, RedlichKwongMFTP::dpdVCalc(), Cantera::GasConstant, RedlichKwongMFTP::m_a_current, RedlichKwongMFTP::m_b_current, Phase::molarVolume(), and Phase::temperature().
Referenced by RedlichKwongMFTP::cp_mole(), RedlichKwongMFTP::getPartialMolarEnthalpies(), and RedlichKwongMFTP::getPartialMolarEntropies().
void updateAB ()
Update the a and b parameters.
The a and the b parameters depend on the mole fraction and the temperature. This function updates the internal numbers based on the state of the object.
Definition at line 1194 of file RedlichKwongMFTP.cpp.
References RedlichKwongMFTP::m_a_current, RedlichKwongMFTP::m_b_current, RedlichKwongMFTP::m_formTempParam, Phase::m_kk, MixtureFugacityTP::moleFractions_, and Phase::temperature().
Referenced by RedlichKwongMFTP::setConcentrations(), RedlichKwongMFTP::setMassFractions(), RedlichKwongMFTP::setMassFractions_NoNorm(), RedlichKwongMFTP::setMoleFractions(), RedlichKwongMFTP::setMoleFractions_NoNorm(), and RedlichKwongMFTP::setTemperature().
void calculateAB (doublereal temp, doublereal & aCalc, doublereal & bCalc) const
Calculate the a and the b parameters given the temperature.
This function doesn't change the internal state of the object, so it is a const function. It does use the stored mole fractions in the object.
Parameters
temp Temperature (TKelvin)
aCalc (output) Returns the a value
bCalc (output) Returns the b value.
Definition at line 1216 of file RedlichKwongMFTP.cpp.
References RedlichKwongMFTP::m_formTempParam, Phase::m_kk, and MixtureFugacityTP::moleFractions_.
Referenced by RedlichKwongMFTP::liquidVolEst().
int NicholsSolve (double TKelvin, double pres, doublereal a, doublereal b, doublereal Vroot[3]) const
Solve the cubic equation of state.
The R-K equation of state may be solved via the following formula:
V**3 - V**2(RT/P)  - V(RTb/P - a/(P T**.5) + b*b) - (a b / (P T**.5)) = 0
Returns the number of solutions found. If it only finds the liquid branch solution, it will return a -1 or a -2 instead of 1 or 2. If it returns 0, then there is an error.
Definition at line 1298 of file RedlichKwongMFTP.cpp.
References Cantera::fp2str(), Cantera::GasConstant, RedlichKwongMFTP::omega_a, RedlichKwongMFTP::omega_b, RedlichKwongMFTP::omega_vc, Cantera::Pi, Cantera::writelog(), and Cantera::writelogendl().
Referenced by RedlichKwongMFTP::densityCalc(), and RedlichKwongMFTP::liquidVolEst().
Member Data Documentation
int m_standardMixingRules protected
boolean indicating whether standard mixing rules are applied
1 = Yes, there are standard cross terms in the a coefficient matrices.
0 = No, there are nonstandard cross terms in the a coefficient matrices.
Definition at line 641 of file RedlichKwongMFTP.h.
Referenced by RedlichKwongMFTP::initThermoXML(), and RedlichKwongMFTP::operator=().
int m_formTempParam protected
Form of the temperature parameterization.
0 = There is no temperature parameterization of a or b
1 = The a_ij parameter is a linear function of the temperature
Definition at line 648 of file RedlichKwongMFTP.h.
Referenced by RedlichKwongMFTP::calculateAB(), RedlichKwongMFTP::operator=(), RedlichKwongMFTP::readXMLCrossFluid(), RedlichKwongMFTP::readXMLPureFluid(), and RedlichKwongMFTP::updateAB().
doublereal m_b_current protected
Value of b in the equation of state.
m_b is a function of the temperature and the mole fraction.
Definition at line 654 of file RedlichKwongMFTP.h.
Referenced by RedlichKwongMFTP::cp_mole(), RedlichKwongMFTP::critCompressibility(), RedlichKwongMFTP::critDensity(), RedlichKwongMFTP::critPressure(), RedlichKwongMFTP::critTemperature(), RedlichKwongMFTP::critVolume(), RedlichKwongMFTP::densityCalc(), RedlichKwongMFTP::dpdVCalc(), RedlichKwongMFTP::getActivityCoefficients(), RedlichKwongMFTP::getChemPotentials(), RedlichKwongMFTP::getPartialMolarEnthalpies(), RedlichKwongMFTP::getPartialMolarEntropies(), RedlichKwongMFTP::getPartialMolarVolumes(), RedlichKwongMFTP::hresid(), RedlichKwongMFTP::liquidVolEst(), RedlichKwongMFTP::operator=(), RedlichKwongMFTP::pressure(), RedlichKwongMFTP::pressureCalc(), RedlichKwongMFTP::pressureDerivatives(), RedlichKwongMFTP::sresid(), and RedlichKwongMFTP::updateAB().
doublereal m_a_current protected
Value of a in the equation of state.
a_b is a function of the temperature and the mole fraction.
Definition at line 660 of file RedlichKwongMFTP.h.
Referenced by RedlichKwongMFTP::cp_mole(), RedlichKwongMFTP::critCompressibility(), RedlichKwongMFTP::critDensity(), RedlichKwongMFTP::critPressure(), RedlichKwongMFTP::critTemperature(), RedlichKwongMFTP::critVolume(), RedlichKwongMFTP::densityCalc(), RedlichKwongMFTP::dpdVCalc(), RedlichKwongMFTP::getActivityCoefficients(), RedlichKwongMFTP::getChemPotentials(), RedlichKwongMFTP::getPartialMolarEnthalpies(), RedlichKwongMFTP::getPartialMolarEntropies(), RedlichKwongMFTP::getPartialMolarVolumes(), RedlichKwongMFTP::hresid(), RedlichKwongMFTP::operator=(), RedlichKwongMFTP::pressure(), RedlichKwongMFTP::pressureCalc(), RedlichKwongMFTP::pressureDerivatives(), RedlichKwongMFTP::sresid(), and RedlichKwongMFTP::updateAB().
vector_fp m_pp mutable protected
Temporary storage - length = m_kk.
Definition at line 676 of file RedlichKwongMFTP.h.
Referenced by RedlichKwongMFTP::getActivityCoefficients(), RedlichKwongMFTP::getChemPotentials(), RedlichKwongMFTP::getPartialMolarEnthalpies(), RedlichKwongMFTP::getPartialMolarEntropies(), RedlichKwongMFTP::getPartialMolarVolumes(), RedlichKwongMFTP::initLengths(), RedlichKwongMFTP::operator=(), and RedlichKwongMFTP::setToEquilState().
vector_fp m_tmpV mutable protected
Temporary storage - length = m_kk.
Definition at line 679 of file RedlichKwongMFTP.h.
Referenced by RedlichKwongMFTP::calcDensity(), RedlichKwongMFTP::getPartialMolarEnthalpies(), RedlichKwongMFTP::getPartialMolarEntropies(), RedlichKwongMFTP::getPartialMolarVolumes(), RedlichKwongMFTP::initLengths(), RedlichKwongMFTP::operator=(), RedlichKwongMFTP::setToEquilState(), and RedlichKwongMFTP::standardConcentration().
doublereal dpdV_ mutable protected
The derivative of the pressure wrt the volume.
Calculated at the current conditions temperature and mole number kept constant
Definition at line 691 of file RedlichKwongMFTP.h.
Referenced by RedlichKwongMFTP::cp_mole(), RedlichKwongMFTP::getPartialMolarEnthalpies(), RedlichKwongMFTP::operator=(), and RedlichKwongMFTP::pressureDerivatives().
doublereal dpdT_ mutable protected
The derivative of the pressure wrt the temperature.
Calculated at the current conditions Total volume and mole number kept constant
Definition at line 698 of file RedlichKwongMFTP.h.
Referenced by RedlichKwongMFTP::cp_mole(), RedlichKwongMFTP::getPartialMolarEnthalpies(), RedlichKwongMFTP::getPartialMolarEntropies(), RedlichKwongMFTP::operator=(), and RedlichKwongMFTP::pressureDerivatives().
vector_fp dpdni_ mutable protected
Vector of derivatives of pressure wrt mole number.
Calculated at the current conditions Total volume, temperature and other mole number kept constant
Definition at line 705 of file RedlichKwongMFTP.h.
Referenced by RedlichKwongMFTP::getPartialMolarEnthalpies(), RedlichKwongMFTP::initLengths(), and RedlichKwongMFTP::operator=().
const doublereal omega_a = 4.27480233540E-01 static
Omega constant for a -> value of a in terms of critical properties.
this was calculated from a small nonlinear solve
Definition at line 712 of file RedlichKwongMFTP.h.
Referenced by RedlichKwongMFTP::NicholsSolve().
const doublereal omega_b = 8.66403499650E-02 static
Omega constant for b.
Definition at line 715 of file RedlichKwongMFTP.h.
Referenced by RedlichKwongMFTP::NicholsSolve().
const doublereal omega_vc = 3.33333333333333E-01 static
Omega constant for the critical molar volume.
Definition at line 718 of file RedlichKwongMFTP.h.
Referenced by RedlichKwongMFTP::NicholsSolve().
The documentation for this class was generated from the following files:
RedlichKwongMFTP.h
RedlichKwongMFTP.cpp