Cantera: StoichSubstance Class Reference
StoichSubstance Class Reference
Thermodynamic Properties
Class StoichSubstance represents a stoichiometric (fixed composition) incompressible substance.
#include <StoichSubstance.h>
Public Member Functions
StoichSubstance ()
Default empty constructor.
StoichSubstance (const StoichSubstance &right)
Copy Constructor.
StoichSubstance & operator= (const StoichSubstance &right)
Assignment operator.
ThermoPhase * duplMyselfAsThermoPhase () const
Duplicator from the ThermoPhase parent class.
virtual int eosType () const
Equation of state flag.
virtual void initThermo ()
Initialize the ThermoPhase object after all species have been set up.
virtual void setParameters (int n, double *const c)
Set the equation of state parameters.
virtual void getParameters (int &n, double *const c) const
Get the equation of state parameters in a vector.
virtual void setParametersFromXML (const XML_Node &eosdata)
Set equation of state parameter values from XML entries.
Molar Thermodynamic Properties of the Solution
virtual doublereal enthalpy_mole () const
Molar enthalpy.
virtual doublereal intEnergy_mole () const
Molar internal energy.
virtual doublereal entropy_mole () const
Molar entropy.
virtual doublereal cp_mole () const
Molar heat capacity at constant pressure.
virtual doublereal cv_mole () const
Molar heat capacity at constant volume.
Mechanical Equation of State
virtual doublereal pressure () const
Report the Pressure. Units: Pa.
virtual void setPressure (doublereal p)
Set the pressure at constant temperature. Units: Pa.
Chemical Potentials and Activities
virtual void getActivityConcentrations (doublereal *c) const
This method returns the array of generalized concentrations.
virtual doublereal standardConcentration (size_t k=0) const
The standard concentration.
virtual doublereal logStandardConc (size_t k=0) const
Returns the natural logarithm of the standard concentration of the kth species.
virtual void getStandardChemPotentials (doublereal *mu0) const
Get the array of chemical potentials at unit activity \(\mu^0_k \).
virtual void getUnitsStandardConc (double *uA, int k=0, int sizeUA=6) const
Returns the units of the standard and generalized concentrations.
Partial Molar Properties of the Solution
virtual void getChemPotentials_RT (doublereal *mu) const
Get the array of non-dimensional chemical potentials \(\mu_k / \hat R T \).
virtual void getChemPotentials (doublereal *mu) const
For a stoichiometric substance, there is only one species.
void getElectrochemPotentials (doublereal *mu) const
Get the species electrochemical potentials.
virtual void getPartialMolarEnthalpies (doublereal *hbar) const
Returns an array of partial molar enthalpies for the species in the mixture.
virtual void getPartialMolarEntropies (doublereal *sbar) const
Returns an array of partial molar entropies of the species in the solution.
virtual void getPartialMolarIntEnergies (doublereal *ubar) const
Get the species partial molar enthalpies. Units: J/kmol.
virtual void getPartialMolarCp (doublereal *cpbar) const
Get the partial molar heat capacities Units: J/kmol/K.
virtual void getPartialMolarVolumes (doublereal *vbar) const
returns an array of partial molar volumes of the species in the solution.
Properties of the Standard State of the Species in the Solution
virtual void getEnthalpy_RT (doublereal *hrt) const
Get the nondimensional Enthalpy functions for the species at their standard states at the current T and P of the solution.
virtual void getEntropy_R (doublereal *sr) const
Get the array of nondimensional Enthalpy functions for the standard state species at the current T and P of the solution.
virtual void getGibbs_RT (doublereal *grt) const
Get the nondimensional Gibbs functions for the species at their standard states of solution at the current T and P of the solution.
virtual void getPureGibbs (doublereal *gpure) const
Get the Gibbs functions for the standard state of the species at the current T and P of the solution.
virtual void getCp_R (doublereal *cpr) const
Get the nondimensional Heat Capacities at constant pressure for the standard state of the species at the current T and P.
virtual void getStandardVolumes (doublereal *vol) const
Get the standard volumes for the standard state of the species at the current T and P.
Thermodynamic Values for the Species Reference States
virtual void getEnthalpy_RT_ref (doublereal *hrt) const
Returns the vector of nondimensional enthalpies of the reference state at the current temperature of the solution and the reference pressure for the species.
virtual void getGibbs_RT_ref (doublereal *grt) const
Returns the vector of nondimensional enthalpies of the reference state at the current temperature of the solution and the reference pressure for the species.
virtual void getGibbs_ref (doublereal *g) const
Returns the vector of the Gibbs function of the reference state at the current temperature of the solution and the reference pressure for the species.
virtual void getEntropy_R_ref (doublereal *er) const
Returns the vector of nondimensional entropies of the reference state at the current temperature of the solution and the reference pressure for the species.
virtual void getCp_R_ref (doublereal *cprt) const
Returns the vector of nondimensional constant pressure heat capacities of the reference state at the current temperature of the solution and reference pressure for each species.
Public Member Functions inherited from ThermoPhase
ThermoPhase ()
Constructor.
virtual ~ThermoPhase ()
Destructor. Deletes the species thermo manager.
ThermoPhase (const ThermoPhase &right)
Copy Constructor for the ThermoPhase object.
ThermoPhase & operator= (const ThermoPhase &right)
Assignment operator.
doublereal _RT () const
Return the Gas Constant multiplied by the current temperature.
virtual doublereal refPressure () const
Returns the reference pressure in Pa.
virtual doublereal minTemp (size_t k=npos) const
Minimum temperature for which the thermodynamic data for the species or phase are valid.
doublereal Hf298SS (const int k) const
Report the 298 K Heat of Formation of the standard state of one species (J kmol-1)
virtual void modifyOneHf298SS (const size_t k, const doublereal Hf298New)
Modify the value of the 298 K Heat of Formation of one species in the phase (J kmol-1)
virtual doublereal maxTemp (size_t k=npos) const
Maximum temperature for which the thermodynamic data for the species are valid.
bool chargeNeutralityNecessary () const
Returns the chargeNeutralityNecessity boolean.
virtual doublereal gibbs_mole () const
Molar Gibbs function. Units: J/kmol.
virtual doublereal cv_vib (int, double) const
virtual doublereal isothermalCompressibility () const
Returns the isothermal compressibility. Units: 1/Pa.
virtual doublereal thermalExpansionCoeff () const
Return the volumetric thermal expansion coefficient. Units: 1/K.
void setElectricPotential (doublereal v)
Set the electric potential of this phase (V).
doublereal electricPotential () const
Returns the electric potential of this phase (V).
virtual int activityConvention () const
This method returns the convention used in specification of the activities, of which there are currently two, molar- and molality-based conventions.
virtual int standardStateConvention () const
This method returns the convention used in specification of the standard state, of which there are currently two, temperature based, and variable pressure based.
virtual void getActivities (doublereal *a) const
Get the array of non-dimensional activities at the current solution temperature, pressure, and solution concentration.
virtual void getActivityCoefficients (doublereal *ac) const
Get the array of non-dimensional molar-based activity coefficients at the current solution temperature, pressure, and solution concentration.
virtual void getLnActivityCoefficients (doublereal *lnac) const
Get the array of non-dimensional molar-based ln activity coefficients at the current solution temperature, pressure, and solution concentration.
void getElectrochemPotentials (doublereal *mu) const
Get the species electrochemical potentials.
virtual void getdPartialMolarVolumes_dT (doublereal *d_vbar_dT) const
Return an array of derivatives of partial molar volumes wrt temperature for the species in the mixture.
virtual void getdPartialMolarVolumes_dP (doublereal *d_vbar_dP) const
Return an array of derivatives of partial molar volumes wrt pressure for the species in the mixture.
virtual void getIntEnergy_RT (doublereal *urt) const
Returns the vector of nondimensional Internal Energies of the standard state species at the current T and P of the solution.
virtual void getdStandardVolumes_dT (doublereal *d_vol_dT) const
Get the derivative of the molar volumes of the species standard states wrt temperature at the current T and P of the solution.
virtual void getdStandardVolumes_dP (doublereal *d_vol_dP) const
Get the derivative molar volumes of the species standard states wrt pressure at the current T and P of the solution.
virtual void getIntEnergy_RT_ref (doublereal *urt) const
Returns the vector of nondimensional internal Energies of the reference state at the current temperature of the solution and the reference pressure for each species.
virtual void getStandardVolumes_ref (doublereal *vol) const
Get the molar volumes of the species reference states at the current T and P_ref of the solution.
virtual void setReferenceComposition (const doublereal *const x)
Sets the reference composition.
virtual void getReferenceComposition (doublereal *const x) const
Gets the reference composition.
doublereal enthalpy_mass () const
Specific enthalpy.
doublereal intEnergy_mass () const
Specific internal energy.
doublereal entropy_mass () const
Specific entropy.
doublereal gibbs_mass () const
Specific Gibbs function.
doublereal cp_mass () const
Specific heat at constant pressure.
doublereal cv_mass () const
Specific heat at constant volume.
virtual void setState_TPX (doublereal t, doublereal p, const doublereal *x)
Set the temperature (K), pressure (Pa), and mole fractions.
virtual void setState_TPX (doublereal t, doublereal p, const compositionMap &x)
Set the temperature (K), pressure (Pa), and mole fractions.
virtual void setState_TPX (doublereal t, doublereal p, const std::string &x)
Set the temperature (K), pressure (Pa), and mole fractions.
virtual void setState_TPY (doublereal t, doublereal p, const doublereal *y)
Set the internally stored temperature (K), pressure (Pa), and mass fractions of the phase.
virtual void setState_TPY (doublereal t, doublereal p, const compositionMap &y)
Set the internally stored temperature (K), pressure (Pa), and mass fractions of the phase.
virtual void setState_TPY (doublereal t, doublereal p, const std::string &y)
Set the internally stored temperature (K), pressure (Pa), and mass fractions of the phase.
virtual void setState_TP (doublereal t, doublereal p)
Set the temperature (K) and pressure (Pa)
virtual void setState_PX (doublereal p, doublereal *x)
Set the pressure (Pa) and mole fractions.
virtual void setState_PY (doublereal p, doublereal *y)
Set the internally stored pressure (Pa) and mass fractions.
virtual void setState_HP (doublereal h, doublereal p, doublereal tol=1.e-4)
Set the internally stored specific enthalpy (J/kg) and pressure (Pa) of the phase.
virtual void setState_UV (doublereal u, doublereal v, doublereal tol=1.e-4)
Set the specific internal energy (J/kg) and specific volume (m^3/kg).
virtual void setState_SP (doublereal s, doublereal p, doublereal tol=1.e-4)
Set the specific entropy (J/kg/K) and pressure (Pa).
virtual void setState_SV (doublereal s, doublereal v, doublereal tol=1.e-4)
Set the specific entropy (J/kg/K) and specific volume (m^3/kg).
void equilibrate (const std::string &XY, const std::string &solver="auto", double rtol=1e-9, int max_steps=50000, int max_iter=100, int estimate_equil=0, int log_level=0)
Equilibrate a ThermoPhase object.
virtual void setToEquilState (const doublereal *lambda_RT)
This method is used by the ChemEquil equilibrium solver.
void setElementPotentials (const vector_fp &lambda)
Stores the element potentials in the ThermoPhase object.
bool getElementPotentials (doublereal *lambda) const
Returns the element potentials stored in the ThermoPhase object.
virtual doublereal critTemperature () const
Critical temperature (K).
virtual doublereal critPressure () const
Critical pressure (Pa).
virtual doublereal critVolume () const
Critical volume (m3/kmol).
virtual doublereal critCompressibility () const
Critical compressibility (unitless).
virtual doublereal critDensity () const
Critical density (kg/m3).
virtual doublereal satTemperature (doublereal p) const
Return the saturation temperature given the pressure.
virtual doublereal satPressure (doublereal t)
Return the saturation pressure given the temperature.
virtual doublereal vaporFraction () const
Return the fraction of vapor at the current conditions.
virtual void setState_Tsat (doublereal t, doublereal x)
Set the state to a saturated system at a particular temperature.
virtual void setState_Psat (doublereal p, doublereal x)
Set the state to a saturated system at a particular pressure.
virtual bool addSpecies (shared_ptr< Species > spec)
Add a Species to this Phase.
void saveSpeciesData (const size_t k, const XML_Node *const data)
Store a reference pointer to the XML tree containing the species data for this phase.
const std::vector< const
XML_Node * > & speciesData () const
Return a pointer to the vector of XML nodes containing the species data for this phase.
void setSpeciesThermo (SpeciesThermo *spthermo)
Install a species thermodynamic property manager.
virtual SpeciesThermo & speciesThermo (int k=-1)
Return a changeable reference to the calculation manager for species reference-state thermodynamic properties.
virtual void initThermoFile (const std::string &inputFile, const std::string &id)
virtual void initThermoXML (XML_Node &phaseNode, const std::string &id)
Import and initialize a ThermoPhase object using an XML tree.
virtual void installSlavePhases (Cantera::XML_Node *phaseNode)
Add in species from Slave phases.
virtual void setStateFromXML (const XML_Node &state)
Set the initial state of the phase to the conditions specified in the state XML element.
virtual void getdlnActCoeffds (const doublereal dTds, const doublereal *const dXds, doublereal *dlnActCoeffds) const
Get the change in activity coefficients wrt changes in state (temp, mole fraction, etc) along a line in parameter space or along a line in physical space.
virtual void getdlnActCoeffdlnX_diag (doublereal *dlnActCoeffdlnX_diag) const
Get the array of ln mole fraction derivatives of the log activity coefficients - diagonal component only.
virtual void getdlnActCoeffdlnN_diag (doublereal *dlnActCoeffdlnN_diag) const
Get the array of log species mole number derivatives of the log activity coefficients.
virtual void getdlnActCoeffdlnN (const size_t ld, doublereal *const dlnActCoeffdlnN)
Get the array of derivatives of the log activity coefficients with respect to the log of the species mole numbers.
virtual void getdlnActCoeffdlnN_numderiv (const size_t ld, doublereal *const dlnActCoeffdlnN)
virtual std::string report (bool show_thermo=true, doublereal threshold=-1e-14) const
returns a summary of the state of the phase as a string
virtual void reportCSV (std::ofstream &csvFile) const
returns a summary of the state of the phase to a comma separated file.
Public Member Functions inherited from Phase
Phase ()
Default constructor.
virtual ~Phase ()
Destructor.
Phase (const Phase &right)
Copy Constructor.
Phase & operator= (const Phase &right)
Assignment operator.
XML_Node & xml () const
Returns a const reference to the XML_Node that describes the phase.
void setXMLdata (XML_Node &xmlPhase)
Stores the XML tree information for the current phase.
void saveState (vector_fp &state) const
Save the current internal state of the phase Write to vector 'state' the current internal state.
void saveState (size_t lenstate, doublereal *state) const
Write to array 'state' the current internal state.
void restoreState (const vector_fp &state)
Restore a state saved on a previous call to saveState.
void restoreState (size_t lenstate, const doublereal *state)
Restore the state of the phase from a previously saved state vector.
doublereal molecularWeight (size_t k) const
Molecular weight of species k.
void getMolecularWeights (vector_fp &weights) const
Copy the vector of molecular weights into vector weights.
void getMolecularWeights (doublereal *weights) const
Copy the vector of molecular weights into array weights.
const vector_fp & molecularWeights () const
Return a const reference to the internal vector of molecular weights.
doublereal size (size_t k) const
This routine returns the size of species k.
doublereal charge (size_t k) const
Dimensionless electrical charge of a single molecule of species k The charge is normalized by the the magnitude of the electron charge.
doublereal chargeDensity () const
Charge density [C/m^3].
size_t nDim () const
Returns the number of spatial dimensions (1, 2, or 3)
void setNDim (size_t ndim)
Set the number of spatial dimensions (1, 2, or 3).
virtual bool ready () const
Returns a bool indicating whether the object is ready for use.
int stateMFNumber () const
Return the State Mole Fraction Number.
std::string id () const
Return the string id for the phase.
void setID (const std::string &id)
Set the string id for the phase.
std::string name () const
Return the name of the phase.
void setName (const std::string &nm)
Sets the string name for the phase.
std::string elementName (size_t m) const
Name of the element with index m.
size_t elementIndex (const std::string &name) const
Return the index of element named 'name'.
const std::vector< std::string > & elementNames () const
Return a read-only reference to the vector of element names.
doublereal atomicWeight (size_t m) const
Atomic weight of element m.
doublereal entropyElement298 (size_t m) const
Entropy of the element in its standard state at 298 K and 1 bar.
int atomicNumber (size_t m) const
Atomic number of element m.
int elementType (size_t m) const
Return the element constraint type Possible types include:
int changeElementType (int m, int elem_type)
Change the element type of the mth constraint Reassigns an element type.
const vector_fp & atomicWeights () const
Return a read-only reference to the vector of atomic weights.
size_t nElements () const
Number of elements.
void checkElementIndex (size_t m) const
Check that the specified element index is in range Throws an exception if m is greater than nElements()-1.
void checkElementArraySize (size_t mm) const
Check that an array size is at least nElements() Throws an exception if mm is less than nElements().
doublereal nAtoms (size_t k, size_t m) const
Number of atoms of element m in species k.
void getAtoms (size_t k, double *atomArray) const
Get a vector containing the atomic composition of species k.
size_t speciesIndex (const std::string &name) const
Returns the index of a species named 'name' within the Phase object.
std::string speciesName (size_t k) const
Name of the species with index k.
std::string speciesSPName (int k) const
Returns the expanded species name of a species, including the phase name This is guaranteed to be unique within a Cantera problem.
const std::vector< std::string > & speciesNames () const
Return a const reference to the vector of species names.
size_t nSpecies () const
Returns the number of species in the phase.
void checkSpeciesIndex (size_t k) const
Check that the specified species index is in range Throws an exception if k is greater than nSpecies()-1.
void checkSpeciesArraySize (size_t kk) const
Check that an array size is at least nSpecies() Throws an exception if kk is less than nSpecies().
void setMoleFractionsByName (const compositionMap &xMap)
Set the species mole fractions by name.
void setMoleFractionsByName (const std::string &x)
Set the mole fractions of a group of species by name.
void setMassFractionsByName (const compositionMap &yMap)
Set the species mass fractions by name.
void setMassFractionsByName (const std::string &x)
Set the species mass fractions by name.
void setState_TRX (doublereal t, doublereal dens, const doublereal *x)
Set the internally stored temperature (K), density, and mole fractions.
void setState_TRX (doublereal t, doublereal dens, const compositionMap &x)
Set the internally stored temperature (K), density, and mole fractions.
void setState_TRY (doublereal t, doublereal dens, const doublereal *y)
Set the internally stored temperature (K), density, and mass fractions.
void setState_TRY (doublereal t, doublereal dens, const compositionMap &y)
Set the internally stored temperature (K), density, and mass fractions.
void setState_TNX (doublereal t, doublereal n, const doublereal *x)
Set the internally stored temperature (K), molar density (kmol/m^3), and mole fractions.
void setState_TR (doublereal t, doublereal rho)
Set the internally stored temperature (K) and density (kg/m^3)
void setState_TX (doublereal t, doublereal *x)
Set the internally stored temperature (K) and mole fractions.
void setState_TY (doublereal t, doublereal *y)
Set the internally stored temperature (K) and mass fractions.
void setState_RX (doublereal rho, doublereal *x)
Set the density (kg/m^3) and mole fractions.
void setState_RY (doublereal rho, doublereal *y)
Set the density (kg/m^3) and mass fractions.
void getMoleFractionsByName (compositionMap &x) const
Get the mole fractions by name.
compositionMap getMoleFractionsByName (double threshold=0.0) const
Get the mole fractions by name.
doublereal moleFraction (size_t k) const
Return the mole fraction of a single species.
doublereal moleFraction (const std::string &name) const
Return the mole fraction of a single species.
compositionMap getMassFractionsByName (double threshold=0.0) const
Get the mass fractions by name.
doublereal massFraction (size_t k) const
Return the mass fraction of a single species.
doublereal massFraction (const std::string &name) const
Return the mass fraction of a single species.
void getMoleFractions (doublereal *const x) const
Get the species mole fraction vector.
virtual void setMoleFractions (const doublereal *const x)
Set the mole fractions to the specified values There is no restriction on the sum of the mole fraction vector.
virtual void setMoleFractions_NoNorm (const doublereal *const x)
Set the mole fractions to the specified values without normalizing.
void getMassFractions (doublereal *const y) const
Get the species mass fractions.
const doublereal * massFractions () const
Return a const pointer to the mass fraction array.
virtual void setMassFractions (const doublereal *const y)
Set the mass fractions to the specified values and normalize them.
virtual void setMassFractions_NoNorm (const doublereal *const y)
Set the mass fractions to the specified values without normalizing.
void getConcentrations (doublereal *const c) const
Get the species concentrations (kmol/m^3).
doublereal concentration (const size_t k) const
Concentration of species k.
virtual void setConcentrations (const doublereal *const conc)
Set the concentrations to the specified values within the phase.
doublereal elementalMassFraction (const size_t m) const
Elemental mass fraction of element m.
doublereal elementalMoleFraction (const size_t m) const
Elemental mole fraction of element m.
const doublereal * moleFractdivMMW () const
Returns a const pointer to the start of the moleFraction/MW array.
doublereal temperature () const
Temperature (K).
virtual doublereal density () const
Density (kg/m^3).
doublereal molarDensity () const
Molar density (kmol/m^3).
doublereal molarVolume () const
Molar volume (m^3/kmol).
virtual void setDensity (const doublereal density_)
Set the internally stored density (kg/m^3) of the phase Note the density of a phase is an independent variable.
virtual void setMolarDensity (const doublereal molarDensity)
Set the internally stored molar density (kmol/m^3) of the phase.
virtual void setTemperature (const doublereal temp)
Set the internally stored temperature of the phase (K).
doublereal mean_X (const doublereal *const Q) const
Evaluate the mole-fraction-weighted mean of an array Q.
doublereal mean_X (const vector_fp &Q) const
Evaluate the mole-fraction-weighted mean of an array Q.
doublereal mean_Y (const doublereal *const Q) const
Evaluate the mass-fraction-weighted mean of an array Q.
doublereal meanMolecularWeight () const
The mean molecular weight. Units: (kg/kmol)
doublereal sum_xlogx () const
Evaluate \(\sum_k X_k \log X_k \).
doublereal sum_xlogQ (doublereal *const Q) const
Evaluate \(\sum_k X_k \log Q_k \).
size_t addElement (const std::string &symbol, doublereal weight=-12345.0, int atomicNumber=0, doublereal entropy298=ENTROPY298_UNKNOWN, int elem_type=CT_ELEM_TYPE_ABSPOS)
Add an element.
void addElement (const XML_Node &e)
Add an element from an XML specification.
void addUniqueElement (const std::string &symbol, doublereal weight=-12345.0, int atomicNumber=0, doublereal entropy298=ENTROPY298_UNKNOWN, int elem_type=CT_ELEM_TYPE_ABSPOS)
Add an element, checking for uniqueness The uniqueness is checked by comparing the string symbol.
void addUniqueElement (const XML_Node &e)
Add an element, checking for uniqueness The uniqueness is checked by comparing the string symbol.
void addElementsFromXML (const XML_Node &phase)
Add all elements referenced in an XML_Node tree.
void freezeElements ()
Prohibit addition of more elements, and prepare to add species.
bool elementsFrozen ()
True if freezeElements has been called.
size_t addUniqueElementAfterFreeze (const std::string &symbol, doublereal weight, int atomicNumber, doublereal entropy298=ENTROPY298_UNKNOWN, int elem_type=CT_ELEM_TYPE_ABSPOS)
Add an element after elements have been frozen, checking for uniqueness The uniqueness is checked by comparing the string symbol.
void addSpecies (const std::string &name, const doublereal *comp, doublereal charge=0.0, doublereal size=1.0)
void addUniqueSpecies (const std::string &name, const doublereal *comp, doublereal charge=0.0, doublereal size=1.0)
Add a species to the phase, checking for uniqueness of the name This routine checks for uniqueness of the string name.
shared_ptr< Species > species (const std::string &name) const
Return the Species object for the named species.
shared_ptr< Species > species (size_t k) const
Return the Species object for species whose index is k.
void ignoreUndefinedElements ()
Set behavior when adding a species containing undefined elements to just skip the species.
void addUndefinedElements ()
Set behavior when adding a species containing undefined elements to add those elements to the phase.
void throwUndefinedElements ()
Set the behavior when adding a species containing undefined elements to throw an exception.
Protected Attributes
doublereal m_press
doublereal m_p0
vector_fp m_h0_RT
vector_fp m_cp0_R
vector_fp m_s0_R
Protected Attributes inherited from ThermoPhase
SpeciesThermo * m_spthermo
Pointer to the calculation manager for species reference-state thermodynamic properties.
std::vector< const XML_Node * > m_speciesData
Vector of pointers to the species databases.
doublereal m_phi
Stored value of the electric potential for this phase.
vector_fp m_lambdaRRT
Vector of element potentials.
bool m_hasElementPotentials
Boolean indicating whether there is a valid set of saved element potentials for this phase.
bool m_chargeNeutralityNecessary
Boolean indicating whether a charge neutrality condition is a necessity.
int m_ssConvention
Contains the standard state convention.
std::vector< doublereal > xMol_Ref
Reference Mole Fraction Composition.
doublereal m_tlast
last value of the temperature processed by reference state
Protected Attributes inherited from Phase
ValueCache m_cache
Cached for saved calculations within each ThermoPhase.
size_t m_kk
Number of species in the phase.
size_t m_ndim
Dimensionality of the phase.
vector_fp m_speciesComp
Atomic composition of the species.
vector_fp m_speciesSize
Vector of species sizes.
vector_fp m_speciesCharge
Vector of species charges. length m_kk.
std::map< std::string,
shared_ptr< Species > > m_species
UndefElement::behavior m_undefinedElementBehavior
Flag determining behavior when adding species with an undefined element.
Private Member Functions
void _updateThermo () const
Additional Inherited Members
Public Attributes inherited from Phase
enum CT_RealNumber_Range_Behavior realNumberRangeBehavior_
Overflow behavior of real number calculations involving this thermo object.
Protected Member Functions inherited from ThermoPhase
virtual void getCsvReportData (std::vector< std::string > &names, std::vector< vector_fp > &data) const
Fills names and data with the column names and species thermo properties to be included in the output of the reportCSV method.
Protected Member Functions inherited from Phase
void setMolecularWeight (const int k, const double mw)
Set the molecular weight of a single species to a given value.
Detailed Description
Class StoichSubstance represents a stoichiometric (fixed composition) incompressible substance.
Definition at line 24 of file StoichSubstance.h.
Constructor & Destructor Documentation
StoichSubstance ()
Default empty constructor.
Definition at line 14 of file StoichSubstance.cpp.
Referenced by StoichSubstance::duplMyselfAsThermoPhase().
StoichSubstance (const StoichSubstance & right)
Copy Constructor.
Copy constructor for the object. Constructed object will be a clone of this object, but will also own all of its data. This is a wrapper around the assignment operator
Parameters
right Object to be copied.
Definition at line 20 of file StoichSubstance.cpp.
Member Function Documentation
StoichSubstance & operator= (const StoichSubstance & right)
Assignment operator.
Assignment operator for the object. Constructed object will be a clone of this object, but will also own all of its data.
Parameters
right Object to be copied.
Definition at line 27 of file StoichSubstance.cpp.
References ThermoPhase::operator=().
ThermoPhase * duplMyselfAsThermoPhase () const virtual
Duplicator from the ThermoPhase parent class.
Reimplemented from ThermoPhase.
Definition at line 40 of file StoichSubstance.cpp.
References StoichSubstance::StoichSubstance().
virtual int eosType () const inline virtual
Equation of state flag.
Returns the value cStoichSubstance, defined in mix_defs.h.
Reimplemented from ThermoPhase.
Definition at line 65 of file StoichSubstance.h.
doublereal enthalpy_mole () const virtual
Molar enthalpy.
Units: J/kmol. For an incompressible, stoichiometric substance, the internal energy is independent of pressure, and therefore the molar enthalpy is
\[ \hat h(T, P) = \hat u(T) + P \hat v \]
, where the molar specific volume is constant.
Reimplemented from ThermoPhase.
Definition at line 45 of file StoichSubstance.cpp.
References StoichSubstance::intEnergy_mole(), and Phase::molarDensity().
Referenced by StoichSubstance::getEnthalpy_RT(), and StoichSubstance::getPartialMolarEnthalpies().
doublereal intEnergy_mole () const virtual
Molar internal energy.
J/kmol. For an incompressible, stoichiometric substance, the molar internal energy is independent of pressure. Since the thermodynamic properties are specified by giving the standard-state enthalpy, the term \(P_0 \hat v\) is subtracted from the specified molar enthalpy to compute the molar internal energy.
Reimplemented from ThermoPhase.
Definition at line 50 of file StoichSubstance.cpp.
References Cantera::GasConstant, Phase::molarDensity(), and Phase::temperature().
Referenced by StoichSubstance::enthalpy_mole(), and StoichSubstance::getPartialMolarIntEnergies().
doublereal entropy_mole () const virtual
Molar entropy.
Units: J/kmol/K. For an incompressible, stoichiometric substance, the molar entropy depends only on the temperature.
Reimplemented from ThermoPhase.
Definition at line 57 of file StoichSubstance.cpp.
References Cantera::GasConstant.
Referenced by StoichSubstance::getEntropy_R(), and StoichSubstance::getPartialMolarEntropies().
doublereal cp_mole () const virtual
Molar heat capacity at constant pressure.
Units: J/kmol/K. For an incompressible substance, \(\hat c_p = \hat c_v\).
Reimplemented from ThermoPhase.
Definition at line 63 of file StoichSubstance.cpp.
References Cantera::GasConstant.
Referenced by StoichSubstance::cv_mole(), StoichSubstance::getCp_R(), and StoichSubstance::getPartialMolarCp().
doublereal cv_mole () const virtual
Molar heat capacity at constant volume.
Units: J/kmol/K. For an incompressible substance, \(\hat c_p = \hat c_v\).
Reimplemented from ThermoPhase.
Definition at line 69 of file StoichSubstance.cpp.
References StoichSubstance::cp_mole().
doublereal pressure () const virtual
Report the Pressure. Units: Pa.
For an incompressible substance, the density is independent of pressure. This method simply returns the stored pressure value.
Reimplemented from ThermoPhase.
Definition at line 109 of file StoichSubstance.cpp.
void setPressure (doublereal p) virtual
Set the pressure at constant temperature. Units: Pa.
For an incompressible substance, the density is independent of pressure. Therefore, this method only stores the specified pressure value. It does not modify the density.
Parameters
p Pressure (units - Pa)
Reimplemented from ThermoPhase.
Definition at line 114 of file StoichSubstance.cpp.
void getActivityConcentrations (doublereal * c) const virtual
This method returns the array of generalized concentrations.
For a stoichiometric substance, there is only one species, and the generalized concentration is 1.0.
Reimplemented from ThermoPhase.
Definition at line 119 of file StoichSubstance.cpp.
doublereal standardConcentration (size_t k = 0) const virtual
The standard concentration.
This is defined as the concentration by which the generalized concentration is normalized to produce the activity.
Reimplemented from ThermoPhase.
Definition at line 124 of file StoichSubstance.cpp.
doublereal logStandardConc (size_t k = 0) const virtual
Returns the natural logarithm of the standard concentration of the kth species.
Reimplemented from ThermoPhase.
Definition at line 129 of file StoichSubstance.cpp.
void getStandardChemPotentials (doublereal * mu0) const virtual
Get the array of chemical potentials at unit activity \(\mu^0_k \).
For a stoichiometric substance, there is no activity term in the chemical potential expression, and therefore the standard chemical potential and the chemical potential are both equal to the molar Gibbs function.
Reimplemented from ThermoPhase.
Definition at line 134 of file StoichSubstance.cpp.
References ThermoPhase::gibbs_mole().
void getUnitsStandardConc (double * uA, int k = 0, int sizeUA = 6) const virtual
Returns the units of the standard and generalized concentrations.
Note they have the same units, as their ratio is defined to be equal to the activity of the kth species in the solution, which is unitless.
This routine is used in print out applications where the units are needed. Usually, MKS units are assumed throughout the program and in the XML input files.
uA[0] = kmol units - default  = 0
uA[1] = m    units - default  = 0
uA[2] = kg   units - default  = 0;
uA[3] = Pa(pressure) units - default = 0;
uA[4] = Temperature units - default = 0;
uA[5] = time units - default = 0
Deprecated:
To be removed after Cantera 2.2.
Reimplemented from ThermoPhase.
Definition at line 139 of file StoichSubstance.cpp.
References Cantera::warn_deprecated().
void getChemPotentials_RT (doublereal * mu) const virtual
Get the array of non-dimensional chemical potentials \(\mu_k / \hat R T \).
Reimplemented from ThermoPhase.
Definition at line 148 of file StoichSubstance.cpp.
References Cantera::GasConstant, ThermoPhase::gibbs_mole(), and Phase::temperature().
void getChemPotentials (doublereal * mu) const virtual
For a stoichiometric substance, there is only one species.
This method returns the molar Gibbs function in the first element of array mu.
Reimplemented from ThermoPhase.
Definition at line 153 of file StoichSubstance.cpp.
References ThermoPhase::gibbs_mole().
Referenced by StoichSubstance::getElectrochemPotentials().
void getElectrochemPotentials (doublereal * mu) const
Get the species electrochemical potentials.
Units: J/kmol. This method adds a term \(Fz_k \phi_k \) to the to each chemical potential.
Definition at line 158 of file StoichSubstance.cpp.
References StoichSubstance::getChemPotentials().
void getPartialMolarEnthalpies (doublereal * hbar) const virtual
Returns an array of partial molar enthalpies for the species in the mixture.
Units (J/kmol)
Reimplemented from ThermoPhase.
Definition at line 163 of file StoichSubstance.cpp.
References StoichSubstance::enthalpy_mole().
void getPartialMolarEntropies (doublereal * sbar) const virtual
Returns an array of partial molar entropies of the species in the solution.
Units: J/kmol/K.
Reimplemented from ThermoPhase.
Definition at line 168 of file StoichSubstance.cpp.
References StoichSubstance::entropy_mole().
void getPartialMolarIntEnergies (doublereal * ubar) const virtual
Get the species partial molar enthalpies. Units: J/kmol.
Parameters
ubar Output vector of species partial molar internal energies. Length = m_kk. units are J/kmol.
Reimplemented from ThermoPhase.
Definition at line 173 of file StoichSubstance.cpp.
References StoichSubstance::intEnergy_mole().
void getPartialMolarCp (doublereal * cpbar) const virtual
Get the partial molar heat capacities Units: J/kmol/K.
Parameters
cpbar Output vector of species partial molar heat capacities at constant pressure. Length = m_kk. units are J/kmol/K.
Reimplemented from ThermoPhase.
Definition at line 178 of file StoichSubstance.cpp.
References StoichSubstance::cp_mole().
void getPartialMolarVolumes (doublereal * vbar) const virtual
returns an array of partial molar volumes of the species in the solution.
Units: m^3 kmol-1.
Reimplemented from ThermoPhase.
Definition at line 183 of file StoichSubstance.cpp.
References Phase::molarDensity().
void getEnthalpy_RT (doublereal * hrt) const virtual
Get the nondimensional Enthalpy functions for the species at their standard states at the current T and P of the solution.
Reimplemented from ThermoPhase.
Definition at line 188 of file StoichSubstance.cpp.
References StoichSubstance::enthalpy_mole(), Cantera::GasConstant, and Phase::temperature().
void getEntropy_R (doublereal * sr) const virtual
Get the array of nondimensional Enthalpy functions for the standard state species at the current T and P of the solution.
Reimplemented from ThermoPhase.
Definition at line 193 of file StoichSubstance.cpp.
References StoichSubstance::entropy_mole(), and Cantera::GasConstant.
void getGibbs_RT (doublereal * grt) const virtual
Get the nondimensional Gibbs functions for the species at their standard states of solution at the current T and P of the solution.
Reimplemented from ThermoPhase.
Definition at line 198 of file StoichSubstance.cpp.
References Cantera::GasConstant, ThermoPhase::gibbs_mole(), and Phase::temperature().
void getPureGibbs (doublereal * gpure) const virtual
Get the Gibbs functions for the standard state of the species at the current T and P of the solution.
Units are Joules/kmol
Parameters
gpure Output vector of standard state Gibbs free energies Length: m_kk.
Reimplemented from ThermoPhase.
Definition at line 203 of file StoichSubstance.cpp.
References ThermoPhase::gibbs_mole().
void getCp_R (doublereal * cpr) const virtual
Get the nondimensional Heat Capacities at constant pressure for the standard state of the species at the current T and P.
Reimplemented from ThermoPhase.
Definition at line 208 of file StoichSubstance.cpp.
References StoichSubstance::cp_mole(), and Cantera::GasConstant.
void getStandardVolumes (doublereal * vol) const virtual
Get the standard volumes for the standard state of the species at the current T and P.
Reimplemented from ThermoPhase.
Definition at line 213 of file StoichSubstance.cpp.
References Phase::molarDensity().
void getEnthalpy_RT_ref (doublereal * hrt) const virtual
Returns the vector of nondimensional enthalpies of the reference state at the current temperature of the solution and the reference pressure for the species.
This function fills in its one entry in hrt[] by calling the underlying species thermo function for the dimensionless enthalpy.
Reimplemented from ThermoPhase.
Definition at line 218 of file StoichSubstance.cpp.
void getGibbs_RT_ref (doublereal * grt) const virtual
Returns the vector of nondimensional enthalpies of the reference state at the current temperature of the solution and the reference pressure for the species.
This function fills in its one entry in hrt[] by calling the underlying species thermo function for the dimensionless Gibbs free energy, calculated from the dimensionless enthalpy and entropy.
Reimplemented from ThermoPhase.
Definition at line 224 of file StoichSubstance.cpp.
Referenced by StoichSubstance::getGibbs_ref().
void getGibbs_ref (doublereal * g) const virtual
Returns the vector of the Gibbs function of the reference state at the current temperature of the solution and the reference pressure for the species.
units = J/kmol
This function fills in its one entry in g[] by calling the underlying species thermo functions for the Gibbs free energy, calculated from enthalpy and the entropy, and the multiplying by RT.
Reimplemented from ThermoPhase.
Definition at line 230 of file StoichSubstance.cpp.
References Cantera::GasConstant, StoichSubstance::getGibbs_RT_ref(), and Phase::temperature().
void getEntropy_R_ref (doublereal * er) const virtual
Returns the vector of nondimensional entropies of the reference state at the current temperature of the solution and the reference pressure for the species.
This function fills in its one entry in hrt[] by calling the underlying species thermo function for the dimensionless entropy.
Reimplemented from ThermoPhase.
Definition at line 236 of file StoichSubstance.cpp.
void getCp_R_ref (doublereal * cprt) const virtual
Returns the vector of nondimensional constant pressure heat capacities of the reference state at the current temperature of the solution and reference pressure for each species.
Parameters
cprt Output vector of nondimensional reference state heat capacities at constant pressure for the species. Length: m_kk
Reimplemented from ThermoPhase.
Definition at line 242 of file StoichSubstance.cpp.
void initThermo () virtual
Initialize the ThermoPhase object after all species have been set up.
Initialize.
This method is provided to allow subclasses to perform any initialization required after all species have been added. For example, it might be used to resize internal work arrays that must have an entry for each species. The base class implementation does nothing, and subclasses that do not require initialization do not need to overload this method. When importing a CTML phase description, this method is called from ThermoPhase::initThermoXML(), which is called from importPhase(), just prior to returning from function importPhase().
Reimplemented from ThermoPhase.
Definition at line 74 of file StoichSubstance.cpp.
References ThermoPhase::initThermo(), Phase::m_kk, ThermoPhase::m_spthermo, SpeciesThermo::maxTemp(), SpeciesThermo::minTemp(), ThermoPhase::refPressure(), and ThermoPhase::setState_TP().
void setParameters (int n, double *const c) virtual
Set the equation of state parameters.
The number and meaning of these depends on the subclass.
Parameters
n number of parameters
c array of n coefficients
Reimplemented from ThermoPhase.
Definition at line 248 of file StoichSubstance.cpp.
References Phase::setDensity().
void getParameters (int & n, double *const c) const virtual
Get the equation of state parameters in a vector.
The number and meaning of these depends on the subclass.
Parameters
n number of parameters
c array of n coefficients
Reimplemented from ThermoPhase.
Definition at line 254 of file StoichSubstance.cpp.
References Phase::density().
void setParametersFromXML (const XML_Node & eosdata) virtual
Set equation of state parameter values from XML entries.
This method is called by function importPhase() when processing a phase definition in an input file. It should be overloaded in subclasses to set any parameters that are specific to that particular phase model. Note, this method is called before the phase is initialized with elements and/or species.
Parameters
eosdata An XML_Node object corresponding to the "thermo" entry for this phase in the input file.
Reimplemented from ThermoPhase.
Definition at line 260 of file StoichSubstance.cpp.
References XML_Node::_require(), Cantera::getFloat(), and Phase::setDensity().
The documentation for this class was generated from the following files:
StoichSubstance.h
StoichSubstance.cpp