Cantera: PDSS_Molar Class Reference
PDSS_Molar Class Reference
Base class for PDSS classes which compute molar properties directly.
#include <PDSS.h>
Public Member Functions
virtual doublereal enthalpy_RT () const
Return the standard state molar enthalpy divided by RT.
virtual doublereal entropy_R () const
Return the standard state entropy divided by RT.
virtual doublereal gibbs_RT () const
Return the molar Gibbs free energy divided by RT.
virtual doublereal cp_R () const
Return the molar const pressure heat capacity divided by RT.
Public Member Functions inherited from PDSS
PDSS ()
Empty Constructor.
PDSS (VPStandardStateTP *tp, size_t spindex)
Constructor that initializes the object by examining the XML entries from the ThermoPhase object.
PDSS (const PDSS &b)
Copy Constructor.
PDSS & operator= (const PDSS &b)
Assignment operator.
virtual ~PDSS ()
Destructor for the phase.
virtual PDSS * duplMyselfAsPDSS () const
Duplication routine for objects which inherit from PDSS.
PDSS_enumType reportPDSSType () const
Returns the type of the standard state parameterization.
virtual doublereal enthalpy_mole () const
Return the molar enthalpy in units of J kmol-1.
virtual doublereal intEnergy_mole () const
Return the molar internal Energy in units of J kmol-1.
virtual doublereal entropy_mole () const
Return the molar entropy in units of J kmol-1 K-1.
virtual doublereal gibbs_mole () const
Return the molar Gibbs free energy in units of J kmol-1.
virtual doublereal cp_mole () const
Return the molar const pressure heat capacity in units of J kmol-1 K-1.
virtual doublereal cv_mole () const
Return the molar const volume heat capacity in units of J kmol-1 K-1.
virtual doublereal molarVolume () const
Return the molar volume at standard state.
virtual doublereal density () const
Return the standard state density at standard state.
virtual doublereal enthalpyDelp_mole () const
Get the difference in the standard state enthalpy between the current pressure and the reference pressure, p0.
virtual doublereal entropyDelp_mole () const
Get the difference in the standard state entropy between the current pressure and the reference pressure, p0.
virtual doublereal gibbsDelp_mole () const
Get the difference in the standard state Gibbs free energy between the current pressure and the reference pressure, p0.
virtual doublereal cpDelp_mole () const
Get the difference in standard state heat capacity between the current pressure and the reference pressure, p0.
doublereal refPressure () const
Return the reference pressure for this phase.
doublereal minTemp () const
return the minimum temperature
doublereal maxTemp () const
return the minimum temperature
virtual doublereal gibbs_RT_ref () const
Return the molar Gibbs free energy divided by RT at reference pressure.
virtual doublereal enthalpy_RT_ref () const
Return the molar enthalpy divided by RT at reference pressure.
virtual doublereal entropy_R_ref () const
Return the molar entropy divided by R at reference pressure.
virtual doublereal cp_R_ref () const
Return the molar heat capacity divided by R at reference pressure.
virtual doublereal molarVolume_ref () const
Return the molar volume at reference pressure.
virtual doublereal pressure () const
Returns the pressure (Pa)
virtual void setPressure (doublereal pres)
Sets the pressure in the object.
virtual doublereal thermalExpansionCoeff () const
Return the volumetric thermal expansion coefficient. Units: 1/K.
virtual void setTemperature (doublereal temp)
Set the internal temperature.
virtual doublereal temperature () const
Return the current stored temperature.
virtual void setState_TP (doublereal temp, doublereal pres)
Set the internal temperature and pressure.
virtual void setState_TR (doublereal temp, doublereal rho)
Set the internal temperature and density.
virtual doublereal critTemperature () const
critical temperature
virtual doublereal critPressure () const
critical pressure
virtual doublereal critDensity () const
critical density
virtual doublereal satPressure (doublereal T)
saturation pressure
doublereal molecularWeight () const
Return the molecular weight of the species in units of kg kmol-1.
void setMolecularWeight (doublereal mw)
Set the molecular weight of the species.
virtual void initThermo ()
Initialization routine for all of the shallow pointers.
virtual void initThermoXML (const XML_Node &phaseNode, const std::string &id)
Initialization routine for the PDSS object based on the phaseNode.
virtual void reportParams (size_t &kindex, int &type, doublereal *const c, doublereal &minTemp, doublereal &maxTemp, doublereal &refPressure) const
This utility function reports back the type of parameterization and all of the parameters for the species, index.
virtual void initAllPtrs (VPStandardStateTP *vptp_ptr, VPSSMgr *vpssmgr_ptr, SpeciesThermo *spthermo_ptr)
Initialize or Reinitialize all shallow pointers in the object.
Additional Inherited Members
Protected Attributes inherited from PDSS
PDSS_enumType m_pdssType
Enumerated type describing the type of the PDSS object.
doublereal m_temp
Current temperature used by the PDSS object.
doublereal m_pres
State of the system - pressure.
doublereal m_p0
Reference state pressure of the species.
doublereal m_minTemp
Minimum temperature.
doublereal m_maxTemp
Maximum temperature.
VPStandardStateTP * m_tp
ThermoPhase which this species belongs to.
VPSSMgr * m_vpssmgr_ptr
Pointer to the VPSS manager for this object.
doublereal m_mw
Molecular Weight of the species.
size_t m_spindex
Species index in the ThermoPhase corresponding to this species.
SpeciesThermo * m_spthermo
Pointer to the species thermodynamic property manager.
doublereal * m_h0_RT_ptr
Reference state enthalpy divided by RT.
doublereal * m_cp0_R_ptr
Reference state heat capacity divided by R.
doublereal * m_s0_R_ptr
Reference state entropy divided by R.
doublereal * m_g0_RT_ptr
Reference state Gibbs free energy divided by RT.
doublereal * m_V0_ptr
Reference state molar volume (m3 kg-1)
doublereal * m_hss_RT_ptr
Standard state enthalpy divided by RT.
doublereal * m_cpss_R_ptr
Standard state heat capacity divided by R.
doublereal * m_sss_R_ptr
Standard state entropy divided by R.
doublereal * m_gss_RT_ptr
Standard state Gibbs free energy divided by RT.
doublereal * m_Vss_ptr
Standard State molar volume (m3 kg-1)
Detailed Description
Base class for PDSS classes which compute molar properties directly.
Definition at line 677 of file PDSS.h.
Member Function Documentation
doublereal enthalpy_RT () const virtual
Return the standard state molar enthalpy divided by RT.
Returns
The dimensionless species standard state enthalpy divided at the current temperature and pressure.
Reimplemented from PDSS.
Definition at line 392 of file PDSS.cpp.
References PDSS::enthalpy_mole(), Cantera::GasConstant, and PDSS::temperature().
Referenced by PDSS_HKFT::enthalpy_RT_ref(), and PDSS_HKFT::intEnergy_mole().
doublereal entropy_R () const virtual
Return the standard state entropy divided by RT.
Returns
The species standard state entropy divided by RT at the current temperature and pressure.
Reimplemented from PDSS.
Definition at line 397 of file PDSS.cpp.
References PDSS::entropy_mole(), and Cantera::GasConstant.
Referenced by PDSS_HKFT::entropy_R_ref().
doublereal gibbs_RT () const virtual
Return the molar Gibbs free energy divided by RT.
Returns
The species standard state Gibbs free energy divided by RT at the current temperature and pressure.
Reimplemented from PDSS.
Definition at line 402 of file PDSS.cpp.
References Cantera::GasConstant, PDSS::gibbs_mole(), and PDSS::temperature().
Referenced by PDSS_HKFT::gibbs_RT_ref().
doublereal cp_R () const virtual
Return the molar const pressure heat capacity divided by RT.
Returns
The species standard state Cp divided by RT at the current temperature and pressure.
Reimplemented from PDSS.
Definition at line 407 of file PDSS.cpp.
References PDSS::cp_mole(), and Cantera::GasConstant.
Referenced by PDSS_HKFT::cp_R_ref().
The documentation for this class was generated from the following files:
PDSS.h
PDSS.cpp