Cantera: MolalityVPSSTP Class Reference
MolalityVPSSTP Class Reference
Thermodynamic Properties
#include <MolalityVPSSTP.h>
Public Member Functions
MolalityVPSSTP ()
Default Constructor.
MolalityVPSSTP (const MolalityVPSSTP &b)
Copy constructor.
MolalityVPSSTP & operator= (const MolalityVPSSTP &b)
Assignment operator.
virtual ThermoPhase * duplMyselfAsThermoPhase () const
Duplication routine for objects which inherit from ThermoPhase.
virtual void setStateFromXML (const XML_Node &state)
Set equation of state parameter values from XML entries.
void setState_TPM (doublereal t, doublereal p, const doublereal *const molalities)
Set the temperature (K), pressure (Pa), and molalities (gmol kg-1) of the solutes.
void setState_TPM (doublereal t, doublereal p, const compositionMap &m)
Set the temperature (K), pressure (Pa), and molalities.
void setState_TPM (doublereal t, doublereal p, const std::string &m)
Set the temperature (K), pressure (Pa), and molalities.
virtual void getdlnActCoeffdlnN (const size_t ld, doublereal *const dlnActCoeffdlnN)
Get the array of derivatives of the log activity coefficients with respect to the log of the species mole numbers.
virtual std::string report (bool show_thermo=true, doublereal threshold=1e-14) const
returns a summary of the state of the phase as a string
Utilities
void setpHScale (const int pHscaleType)
Set the pH scale, which determines the scale for single-ion activity coefficients.
int pHScale () const
Reports the pH scale, which determines the scale for single-ion activity coefficients.
Utilities for Solvent ID and Molality
void setSolvent (size_t k)
This routine sets the index number of the solvent for the phase.
size_t solventIndex () const
Returns the solvent index.
void setMoleFSolventMin (doublereal xmolSolventMIN)
Sets the minimum mole fraction in the molality formulation.
doublereal moleFSolventMin () const
Returns the minimum mole fraction in the molality formulation.
void calcMolalities () const
Calculates the molality of all species and stores the result internally.
void getMolalities (doublereal *const molal) const
This function will return the molalities of the species.
void setMolalities (const doublereal *const molal)
Set the molalities of the solutes in a phase.
void setMolalitiesByName (const compositionMap &xMap)
Set the molalities of a phase.
void setMolalitiesByName (const std::string &name)
Set the molalities of a phase.
Activities, Standard States, and Activity Concentrations
The activity \(a_k\) of a species in solution is related to the chemical potential by
\[ \mu_k = \mu_k^0(T) + \hat R T \log a_k. \]
The quantity \(\mu_k^0(T,P)\) is the chemical potential at unit activity, which depends only on temperature and pressure.
int activityConvention () const
This method returns the activity convention.
virtual void getActivityConcentrations (doublereal *c) const
This method returns an array of generalized concentrations \(C_k\) that are defined such that \(a_k = C_k / C^0_k, \) where \(C^0_k \) is a standard concentration defined below.
virtual doublereal standardConcentration (size_t k=0) const
The standard concentration \(C^0_k \) used to normalize the generalized concentration.
virtual void getUnitsStandardConc (double *uA, int k=0, int sizeUA=6) const
Returns the units of the standard and generalized concentrations Note they have the same units, as their ratio is defined to be equal to the activity of the kth species in the solution, which is unitless.
virtual void getActivities (doublereal *ac) const
Get the array of non-dimensional activities (molality based for this class and classes that derive from it) at the current solution temperature, pressure, and solution concentration.
void getActivityCoefficients (doublereal *ac) const
Get the array of non-dimensional activity coefficients at the current solution temperature, pressure, and solution concentration.
virtual void getMolalityActivityCoefficients (doublereal *acMolality) const
Get the array of non-dimensional molality based activity coefficients at the current solution temperature, pressure, and solution concentration.
virtual double osmoticCoefficient () const
Calculate the osmotic coefficient.
Partial Molar Properties of the Solution
void getElectrochemPotentials (doublereal *mu) const
Get the species electrochemical potentials.
Chemical Equilibrium
Routines that implement the Chemical equilibrium capability for a single phase, based on the element-potential method.
virtual void setToEquilState (const doublereal *lambda_RT)
This method is used by the ChemEquil element-potential based equilibrium solver.
Initialization
The following methods are used in the process of constructing the phase and setting its parameters from a specification in an input file.
They are not normally used in application programs. To see how they are used, see importPhase().
virtual void initThermo ()
void initThermoXML (XML_Node &phaseNode, const std::string &id)
Import and initialize a ThermoPhase object.
Public Member Functions inherited from VPStandardStateTP
VPStandardStateTP ()
Constructor.
VPStandardStateTP (const VPStandardStateTP &b)
Copy Constructor.
VPStandardStateTP & operator= (const VPStandardStateTP &b)
Assignment operator.
virtual ~VPStandardStateTP ()
Destructor.
virtual int standardStateConvention () const
This method returns the convention used in specification of the standard state, of which there are currently two, temperature based, and variable pressure based.
virtual void getdlnActCoeffdlnN_diag (doublereal *dlnActCoeffdlnN_diag) const
Get the array of log concentration-like derivatives of the log activity coefficients.
void getChemPotentials_RT (doublereal *mu) const
Get the array of non-dimensional species chemical potentials.
virtual void getStandardChemPotentials (doublereal *mu) const
Get the array of chemical potentials at unit activity.
virtual void getEnthalpy_RT (doublereal *hrt) const
Get the nondimensional Enthalpy functions for the species at their standard states at the current T and P of the solution.
virtual void getEntropy_R (doublereal *sr) const
Get the array of nondimensional Enthalpy functions for the standard state species at the current T and P of the solution.
virtual void getGibbs_RT (doublereal *grt) const
Get the nondimensional Gibbs functions for the species at their standard states of solution at the current T and P of the solution.
void getPureGibbs (doublereal *gpure) const
Get the standard state Gibbs functions for each species at the current T and P.
virtual void getIntEnergy_RT (doublereal *urt) const
Returns the vector of nondimensional internal Energies of the standard state at the current temperature and pressure of the solution for each species.
virtual void getCp_R (doublereal *cpr) const
Get the nondimensional Heat Capacities at constant pressure for the standard state of the species at the current T and P.
virtual void getStandardVolumes (doublereal *vol) const
Get the molar volumes of each species in their standard states at the current T and P of the solution.
virtual const vector_fp & getStandardVolumes () const
virtual void setTemperature (const doublereal temp)
Set the temperature of the phase.
virtual void setPressure (doublereal p)
Set the internally stored pressure (Pa) at constant temperature and composition.
virtual void setState_TP (doublereal T, doublereal pres)
Set the temperature and pressure at the same time.
doublereal pressure () const
Returns the current pressure of the phase.
virtual void updateStandardStateThermo () const
Updates the standard state thermodynamic functions at the current T and P of the solution.
virtual bool addSpecies (shared_ptr< Species > spec)
Add a Species to this Phase.
void setVPSSMgr (VPSSMgr *vp_ptr)
set the VPSS Mgr
VPSSMgr * provideVPSSMgr ()
Return a pointer to the VPSSMgr for this phase.
void createInstallPDSS (size_t k, const XML_Node &s, const XML_Node *phaseNode_ptr)
PDSS * providePDSS (size_t k)
const PDSS * providePDSS (size_t k) const
virtual void getEnthalpy_RT_ref (doublereal *hrt) const
Returns the vector of nondimensional enthalpies of the reference state at the current temperature of the solution and the reference pressure for the species.
void modifyOneHf298SS (const size_t k, const doublereal Hf298New)
Modify the value of the 298 K Heat of Formation of the standard state of one species in the phase (J kmol-1)
virtual void getGibbs_RT_ref (doublereal *grt) const
Returns the vector of nondimensional Gibbs free energies of the reference state at the current temperature of the solution and the reference pressure for the species.
virtual void getGibbs_ref (doublereal *g) const
virtual void getEntropy_R_ref (doublereal *er) const
virtual void getCp_R_ref (doublereal *cprt) const
virtual void getStandardVolumes_ref (doublereal *vol) const
Get the molar volumes of the species reference states at the current T and P_ref of the solution.
Public Member Functions inherited from ThermoPhase
ThermoPhase ()
Constructor.
virtual ~ThermoPhase ()
Destructor. Deletes the species thermo manager.
ThermoPhase (const ThermoPhase &right)
Copy Constructor for the ThermoPhase object.
ThermoPhase & operator= (const ThermoPhase &right)
Assignment operator.
doublereal _RT () const
Return the Gas Constant multiplied by the current temperature.
virtual int eosType () const
Equation of state type flag.
virtual doublereal refPressure () const
Returns the reference pressure in Pa.
virtual doublereal minTemp (size_t k=npos) const
Minimum temperature for which the thermodynamic data for the species or phase are valid.
doublereal Hf298SS (const int k) const
Report the 298 K Heat of Formation of the standard state of one species (J kmol-1)
virtual doublereal maxTemp (size_t k=npos) const
Maximum temperature for which the thermodynamic data for the species are valid.
bool chargeNeutralityNecessary () const
Returns the chargeNeutralityNecessity boolean.
virtual doublereal enthalpy_mole () const
Molar enthalpy. Units: J/kmol.
virtual doublereal intEnergy_mole () const
Molar internal energy. Units: J/kmol.
virtual doublereal entropy_mole () const
Molar entropy. Units: J/kmol/K.
virtual doublereal gibbs_mole () const
Molar Gibbs function. Units: J/kmol.
virtual doublereal cp_mole () const
Molar heat capacity at constant pressure. Units: J/kmol/K.
virtual doublereal cv_mole () const
Molar heat capacity at constant volume. Units: J/kmol/K.
virtual doublereal cv_vib (int, double) const
virtual doublereal isothermalCompressibility () const
Returns the isothermal compressibility. Units: 1/Pa.
virtual doublereal thermalExpansionCoeff () const
Return the volumetric thermal expansion coefficient. Units: 1/K.
void setElectricPotential (doublereal v)
Set the electric potential of this phase (V).
doublereal electricPotential () const
Returns the electric potential of this phase (V).
virtual doublereal logStandardConc (size_t k=0) const
Natural logarithm of the standard concentration of the kth species.
virtual void getLnActivityCoefficients (doublereal *lnac) const
Get the array of non-dimensional molar-based ln activity coefficients at the current solution temperature, pressure, and solution concentration.
virtual void getChemPotentials (doublereal *mu) const
Get the species chemical potentials. Units: J/kmol.
void getElectrochemPotentials (doublereal *mu) const
Get the species electrochemical potentials.
virtual void getPartialMolarEnthalpies (doublereal *hbar) const
Returns an array of partial molar enthalpies for the species in the mixture.
virtual void getPartialMolarEntropies (doublereal *sbar) const
Returns an array of partial molar entropies of the species in the solution.
virtual void getPartialMolarIntEnergies (doublereal *ubar) const
Return an array of partial molar internal energies for the species in the mixture.
virtual void getPartialMolarCp (doublereal *cpbar) const
Return an array of partial molar heat capacities for the species in the mixture.
virtual void getPartialMolarVolumes (doublereal *vbar) const
Return an array of partial molar volumes for the species in the mixture.
virtual void getdPartialMolarVolumes_dT (doublereal *d_vbar_dT) const
Return an array of derivatives of partial molar volumes wrt temperature for the species in the mixture.
virtual void getdPartialMolarVolumes_dP (doublereal *d_vbar_dP) const
Return an array of derivatives of partial molar volumes wrt pressure for the species in the mixture.
virtual void getdStandardVolumes_dT (doublereal *d_vol_dT) const
Get the derivative of the molar volumes of the species standard states wrt temperature at the current T and P of the solution.
virtual void getdStandardVolumes_dP (doublereal *d_vol_dP) const
Get the derivative molar volumes of the species standard states wrt pressure at the current T and P of the solution.
virtual void getIntEnergy_RT_ref (doublereal *urt) const
Returns the vector of nondimensional internal Energies of the reference state at the current temperature of the solution and the reference pressure for each species.
virtual void setReferenceComposition (const doublereal *const x)
Sets the reference composition.
virtual void getReferenceComposition (doublereal *const x) const
Gets the reference composition.
doublereal enthalpy_mass () const
Specific enthalpy.
doublereal intEnergy_mass () const
Specific internal energy.
doublereal entropy_mass () const
Specific entropy.
doublereal gibbs_mass () const
Specific Gibbs function.
doublereal cp_mass () const
Specific heat at constant pressure.
doublereal cv_mass () const
Specific heat at constant volume.
virtual void setState_TPX (doublereal t, doublereal p, const doublereal *x)
Set the temperature (K), pressure (Pa), and mole fractions.
virtual void setState_TPX (doublereal t, doublereal p, const compositionMap &x)
Set the temperature (K), pressure (Pa), and mole fractions.
virtual void setState_TPX (doublereal t, doublereal p, const std::string &x)
Set the temperature (K), pressure (Pa), and mole fractions.
virtual void setState_TPY (doublereal t, doublereal p, const doublereal *y)
Set the internally stored temperature (K), pressure (Pa), and mass fractions of the phase.
virtual void setState_TPY (doublereal t, doublereal p, const compositionMap &y)
Set the internally stored temperature (K), pressure (Pa), and mass fractions of the phase.
virtual void setState_TPY (doublereal t, doublereal p, const std::string &y)
Set the internally stored temperature (K), pressure (Pa), and mass fractions of the phase.
virtual void setState_PX (doublereal p, doublereal *x)
Set the pressure (Pa) and mole fractions.
virtual void setState_PY (doublereal p, doublereal *y)
Set the internally stored pressure (Pa) and mass fractions.
virtual void setState_HP (doublereal h, doublereal p, doublereal tol=1.e-4)
Set the internally stored specific enthalpy (J/kg) and pressure (Pa) of the phase.
virtual void setState_UV (doublereal u, doublereal v, doublereal tol=1.e-4)
Set the specific internal energy (J/kg) and specific volume (m^3/kg).
virtual void setState_SP (doublereal s, doublereal p, doublereal tol=1.e-4)
Set the specific entropy (J/kg/K) and pressure (Pa).
virtual void setState_SV (doublereal s, doublereal v, doublereal tol=1.e-4)
Set the specific entropy (J/kg/K) and specific volume (m^3/kg).
void equilibrate (const std::string &XY, const std::string &solver="auto", double rtol=1e-9, int max_steps=50000, int max_iter=100, int estimate_equil=0, int log_level=0)
Equilibrate a ThermoPhase object.
void setElementPotentials (const vector_fp &lambda)
Stores the element potentials in the ThermoPhase object.
bool getElementPotentials (doublereal *lambda) const
Returns the element potentials stored in the ThermoPhase object.
virtual doublereal critTemperature () const
Critical temperature (K).
virtual doublereal critPressure () const
Critical pressure (Pa).
virtual doublereal critVolume () const
Critical volume (m3/kmol).
virtual doublereal critCompressibility () const
Critical compressibility (unitless).
virtual doublereal critDensity () const
Critical density (kg/m3).
virtual doublereal satTemperature (doublereal p) const
Return the saturation temperature given the pressure.
virtual doublereal satPressure (doublereal t)
Return the saturation pressure given the temperature.
virtual doublereal vaporFraction () const
Return the fraction of vapor at the current conditions.
virtual void setState_Tsat (doublereal t, doublereal x)
Set the state to a saturated system at a particular temperature.
virtual void setState_Psat (doublereal p, doublereal x)
Set the state to a saturated system at a particular pressure.
void saveSpeciesData (const size_t k, const XML_Node *const data)
Store a reference pointer to the XML tree containing the species data for this phase.
const std::vector< const
XML_Node * > & speciesData () const
Return a pointer to the vector of XML nodes containing the species data for this phase.
void setSpeciesThermo (SpeciesThermo *spthermo)
Install a species thermodynamic property manager.
virtual SpeciesThermo & speciesThermo (int k=-1)
Return a changeable reference to the calculation manager for species reference-state thermodynamic properties.
virtual void initThermoFile (const std::string &inputFile, const std::string &id)
virtual void installSlavePhases (Cantera::XML_Node *phaseNode)
Add in species from Slave phases.
virtual void setParameters (int n, doublereal *const c)
Set the equation of state parameters.
virtual void getParameters (int &n, doublereal *const c) const
Get the equation of state parameters in a vector.
virtual void setParametersFromXML (const XML_Node &eosdata)
Set equation of state parameter values from XML entries.
virtual void getdlnActCoeffds (const doublereal dTds, const doublereal *const dXds, doublereal *dlnActCoeffds) const
Get the change in activity coefficients wrt changes in state (temp, mole fraction, etc) along a line in parameter space or along a line in physical space.
virtual void getdlnActCoeffdlnX_diag (doublereal *dlnActCoeffdlnX_diag) const
Get the array of ln mole fraction derivatives of the log activity coefficients - diagonal component only.
virtual void getdlnActCoeffdlnN_numderiv (const size_t ld, doublereal *const dlnActCoeffdlnN)
virtual void reportCSV (std::ofstream &csvFile) const
returns a summary of the state of the phase to a comma separated file.
Public Member Functions inherited from Phase
Phase ()
Default constructor.
virtual ~Phase ()
Destructor.
Phase (const Phase &right)
Copy Constructor.
Phase & operator= (const Phase &right)
Assignment operator.
XML_Node & xml () const
Returns a const reference to the XML_Node that describes the phase.
void setXMLdata (XML_Node &xmlPhase)
Stores the XML tree information for the current phase.
void saveState (vector_fp &state) const
Save the current internal state of the phase Write to vector 'state' the current internal state.
void saveState (size_t lenstate, doublereal *state) const
Write to array 'state' the current internal state.
void restoreState (const vector_fp &state)
Restore a state saved on a previous call to saveState.
void restoreState (size_t lenstate, const doublereal *state)
Restore the state of the phase from a previously saved state vector.
doublereal molecularWeight (size_t k) const
Molecular weight of species k.
void getMolecularWeights (vector_fp &weights) const
Copy the vector of molecular weights into vector weights.
void getMolecularWeights (doublereal *weights) const
Copy the vector of molecular weights into array weights.
const vector_fp & molecularWeights () const
Return a const reference to the internal vector of molecular weights.
doublereal size (size_t k) const
This routine returns the size of species k.
doublereal charge (size_t k) const
Dimensionless electrical charge of a single molecule of species k The charge is normalized by the the magnitude of the electron charge.
doublereal chargeDensity () const
Charge density [C/m^3].
size_t nDim () const
Returns the number of spatial dimensions (1, 2, or 3)
void setNDim (size_t ndim)
Set the number of spatial dimensions (1, 2, or 3).
virtual bool ready () const
Returns a bool indicating whether the object is ready for use.
int stateMFNumber () const
Return the State Mole Fraction Number.
std::string id () const
Return the string id for the phase.
void setID (const std::string &id)
Set the string id for the phase.
std::string name () const
Return the name of the phase.
void setName (const std::string &nm)
Sets the string name for the phase.
std::string elementName (size_t m) const
Name of the element with index m.
size_t elementIndex (const std::string &name) const
Return the index of element named 'name'.
const std::vector< std::string > & elementNames () const
Return a read-only reference to the vector of element names.
doublereal atomicWeight (size_t m) const
Atomic weight of element m.
doublereal entropyElement298 (size_t m) const
Entropy of the element in its standard state at 298 K and 1 bar.
int atomicNumber (size_t m) const
Atomic number of element m.
int elementType (size_t m) const
Return the element constraint type Possible types include:
int changeElementType (int m, int elem_type)
Change the element type of the mth constraint Reassigns an element type.
const vector_fp & atomicWeights () const
Return a read-only reference to the vector of atomic weights.
size_t nElements () const
Number of elements.
void checkElementIndex (size_t m) const
Check that the specified element index is in range Throws an exception if m is greater than nElements()-1.
void checkElementArraySize (size_t mm) const
Check that an array size is at least nElements() Throws an exception if mm is less than nElements().
doublereal nAtoms (size_t k, size_t m) const
Number of atoms of element m in species k.
void getAtoms (size_t k, double *atomArray) const
Get a vector containing the atomic composition of species k.
size_t speciesIndex (const std::string &name) const
Returns the index of a species named 'name' within the Phase object.
std::string speciesName (size_t k) const
Name of the species with index k.
std::string speciesSPName (int k) const
Returns the expanded species name of a species, including the phase name This is guaranteed to be unique within a Cantera problem.
const std::vector< std::string > & speciesNames () const
Return a const reference to the vector of species names.
size_t nSpecies () const
Returns the number of species in the phase.
void checkSpeciesIndex (size_t k) const
Check that the specified species index is in range Throws an exception if k is greater than nSpecies()-1.
void checkSpeciesArraySize (size_t kk) const
Check that an array size is at least nSpecies() Throws an exception if kk is less than nSpecies().
void setMoleFractionsByName (const compositionMap &xMap)
Set the species mole fractions by name.
void setMoleFractionsByName (const std::string &x)
Set the mole fractions of a group of species by name.
void setMassFractionsByName (const compositionMap &yMap)
Set the species mass fractions by name.
void setMassFractionsByName (const std::string &x)
Set the species mass fractions by name.
void setState_TRX (doublereal t, doublereal dens, const doublereal *x)
Set the internally stored temperature (K), density, and mole fractions.
void setState_TRX (doublereal t, doublereal dens, const compositionMap &x)
Set the internally stored temperature (K), density, and mole fractions.
void setState_TRY (doublereal t, doublereal dens, const doublereal *y)
Set the internally stored temperature (K), density, and mass fractions.
void setState_TRY (doublereal t, doublereal dens, const compositionMap &y)
Set the internally stored temperature (K), density, and mass fractions.
void setState_TNX (doublereal t, doublereal n, const doublereal *x)
Set the internally stored temperature (K), molar density (kmol/m^3), and mole fractions.
void setState_TR (doublereal t, doublereal rho)
Set the internally stored temperature (K) and density (kg/m^3)
void setState_TX (doublereal t, doublereal *x)
Set the internally stored temperature (K) and mole fractions.
void setState_TY (doublereal t, doublereal *y)
Set the internally stored temperature (K) and mass fractions.
void setState_RX (doublereal rho, doublereal *x)
Set the density (kg/m^3) and mole fractions.
void setState_RY (doublereal rho, doublereal *y)
Set the density (kg/m^3) and mass fractions.
void getMoleFractionsByName (compositionMap &x) const
Get the mole fractions by name.
compositionMap getMoleFractionsByName (double threshold=0.0) const
Get the mole fractions by name.
doublereal moleFraction (size_t k) const
Return the mole fraction of a single species.
doublereal moleFraction (const std::string &name) const
Return the mole fraction of a single species.
compositionMap getMassFractionsByName (double threshold=0.0) const
Get the mass fractions by name.
doublereal massFraction (size_t k) const
Return the mass fraction of a single species.
doublereal massFraction (const std::string &name) const
Return the mass fraction of a single species.
void getMoleFractions (doublereal *const x) const
Get the species mole fraction vector.
virtual void setMoleFractions (const doublereal *const x)
Set the mole fractions to the specified values There is no restriction on the sum of the mole fraction vector.
virtual void setMoleFractions_NoNorm (const doublereal *const x)
Set the mole fractions to the specified values without normalizing.
void getMassFractions (doublereal *const y) const
Get the species mass fractions.
const doublereal * massFractions () const
Return a const pointer to the mass fraction array.
virtual void setMassFractions (const doublereal *const y)
Set the mass fractions to the specified values and normalize them.
virtual void setMassFractions_NoNorm (const doublereal *const y)
Set the mass fractions to the specified values without normalizing.
void getConcentrations (doublereal *const c) const
Get the species concentrations (kmol/m^3).
doublereal concentration (const size_t k) const
Concentration of species k.
virtual void setConcentrations (const doublereal *const conc)
Set the concentrations to the specified values within the phase.
doublereal elementalMassFraction (const size_t m) const
Elemental mass fraction of element m.
doublereal elementalMoleFraction (const size_t m) const
Elemental mole fraction of element m.
const doublereal * moleFractdivMMW () const
Returns a const pointer to the start of the moleFraction/MW array.
doublereal temperature () const
Temperature (K).
virtual doublereal density () const
Density (kg/m^3).
doublereal molarDensity () const
Molar density (kmol/m^3).
doublereal molarVolume () const
Molar volume (m^3/kmol).
virtual void setDensity (const doublereal density_)
Set the internally stored density (kg/m^3) of the phase Note the density of a phase is an independent variable.
virtual void setMolarDensity (const doublereal molarDensity)
Set the internally stored molar density (kmol/m^3) of the phase.
doublereal mean_X (const doublereal *const Q) const
Evaluate the mole-fraction-weighted mean of an array Q.
doublereal mean_X (const vector_fp &Q) const
Evaluate the mole-fraction-weighted mean of an array Q.
doublereal mean_Y (const doublereal *const Q) const
Evaluate the mass-fraction-weighted mean of an array Q.
doublereal meanMolecularWeight () const
The mean molecular weight. Units: (kg/kmol)
doublereal sum_xlogx () const
Evaluate \(\sum_k X_k \log X_k \).
doublereal sum_xlogQ (doublereal *const Q) const
Evaluate \(\sum_k X_k \log Q_k \).
size_t addElement (const std::string &symbol, doublereal weight=-12345.0, int atomicNumber=0, doublereal entropy298=ENTROPY298_UNKNOWN, int elem_type=CT_ELEM_TYPE_ABSPOS)
Add an element.
void addElement (const XML_Node &e)
Add an element from an XML specification.
void addUniqueElement (const std::string &symbol, doublereal weight=-12345.0, int atomicNumber=0, doublereal entropy298=ENTROPY298_UNKNOWN, int elem_type=CT_ELEM_TYPE_ABSPOS)
Add an element, checking for uniqueness The uniqueness is checked by comparing the string symbol.
void addUniqueElement (const XML_Node &e)
Add an element, checking for uniqueness The uniqueness is checked by comparing the string symbol.
void addElementsFromXML (const XML_Node &phase)
Add all elements referenced in an XML_Node tree.
void freezeElements ()
Prohibit addition of more elements, and prepare to add species.
bool elementsFrozen ()
True if freezeElements has been called.
size_t addUniqueElementAfterFreeze (const std::string &symbol, doublereal weight, int atomicNumber, doublereal entropy298=ENTROPY298_UNKNOWN, int elem_type=CT_ELEM_TYPE_ABSPOS)
Add an element after elements have been frozen, checking for uniqueness The uniqueness is checked by comparing the string symbol.
void addSpecies (const std::string &name, const doublereal *comp, doublereal charge=0.0, doublereal size=1.0)
void addUniqueSpecies (const std::string &name, const doublereal *comp, doublereal charge=0.0, doublereal size=1.0)
Add a species to the phase, checking for uniqueness of the name This routine checks for uniqueness of the string name.
shared_ptr< Species > species (const std::string &name) const
Return the Species object for the named species.
shared_ptr< Species > species (size_t k) const
Return the Species object for species whose index is k.
void ignoreUndefinedElements ()
Set behavior when adding a species containing undefined elements to just skip the species.
void addUndefinedElements ()
Set behavior when adding a species containing undefined elements to add those elements to the phase.
void throwUndefinedElements ()
Set the behavior when adding a species containing undefined elements to throw an exception.
Protected Member Functions
virtual void getCsvReportData (std::vector< std::string > &names, std::vector< vector_fp > &data) const
Fills names and data with the column names and species thermo properties to be included in the output of the reportCSV method.
virtual void getUnscaledMolalityActivityCoefficients (doublereal *acMolality) const
Get the array of unscaled non-dimensional molality based activity coefficients at the current solution temperature, pressure, and solution concentration.
virtual void applyphScale (doublereal *acMolality) const
Apply the current phScale to a set of activity Coefficients or activities.
Protected Member Functions inherited from VPStandardStateTP
virtual void calcDensity ()
Calculate the density of the mixture using the partial molar volumes and mole fractions as input.
virtual void _updateStandardStateThermo () const
Updates the standard state thermodynamic functions at the current T and P of the solution.
const vector_fp & Gibbs_RT_ref () const
Protected Member Functions inherited from Phase
void setMolecularWeight (const int k, const double mw)
Set the molecular weight of a single species to a given value.
Protected Attributes
size_t m_indexSolvent
Index of the solvent.
int m_pHScalingType
Scaling to be used for output of single-ion species activity coefficients.
size_t m_indexCLM
Index of the phScale species.
doublereal m_weightSolvent
Molecular weight of the Solvent.
doublereal m_xmolSolventMIN
doublereal m_Mnaught
This is the multiplication factor that goes inside log expressions involving the molalities of species.
vector_fp m_molalities
Current value of the molalities of the species in the phase.
Protected Attributes inherited from VPStandardStateTP
doublereal m_Pcurrent
Current value of the pressure - state variable.
doublereal m_Tlast_ss
The last temperature at which the standard statethermodynamic properties were calculated at.
doublereal m_Plast_ss
The last pressure at which the Standard State thermodynamic properties were calculated at.
doublereal m_P0
VPSSMgr * m_VPSS_ptr
Pointer to the VPSS manager that calculates all of the standard state info efficiently.
std::vector< PDSS * > m_PDSS_storage
Storage for the PDSS objects for the species.
Protected Attributes inherited from ThermoPhase
SpeciesThermo * m_spthermo
Pointer to the calculation manager for species reference-state thermodynamic properties.
std::vector< const XML_Node * > m_speciesData
Vector of pointers to the species databases.
doublereal m_phi
Stored value of the electric potential for this phase.
vector_fp m_lambdaRRT
Vector of element potentials.
bool m_hasElementPotentials
Boolean indicating whether there is a valid set of saved element potentials for this phase.
bool m_chargeNeutralityNecessary
Boolean indicating whether a charge neutrality condition is a necessity.
int m_ssConvention
Contains the standard state convention.
std::vector< doublereal > xMol_Ref
Reference Mole Fraction Composition.
doublereal m_tlast
last value of the temperature processed by reference state
Protected Attributes inherited from Phase
ValueCache m_cache
Cached for saved calculations within each ThermoPhase.
size_t m_kk
Number of species in the phase.
size_t m_ndim
Dimensionality of the phase.
vector_fp m_speciesComp
Atomic composition of the species.
vector_fp m_speciesSize
Vector of species sizes.
vector_fp m_speciesCharge
Vector of species charges. length m_kk.
std::map< std::string,
shared_ptr< Species > > m_species
UndefElement::behavior m_undefinedElementBehavior
Flag determining behavior when adding species with an undefined element.
Private Member Functions
virtual size_t findCLMIndex () const
Returns the index of the Cl- species.
void initLengths ()
Initialize lengths of local variables after all species have been identified.
Additional Inherited Members
Public Attributes inherited from Phase
enum CT_RealNumber_Range_Behavior realNumberRangeBehavior_
Overflow behavior of real number calculations involving this thermo object.
Detailed Description
MolalityVPSSTP is a derived class of ThermoPhase that handles variable pressure standard state methods for calculating thermodynamic properties that are further based on molality-scaled activities. This category incorporates most of the methods for calculating liquid electrolyte thermodynamics that have been developed since the 1970's.
This class adds additional functions onto the ThermoPhase interface that handle molality based standard states. The ThermoPhase class includes a member function, ThermoPhase::activityConvention() that indicates which convention the activities are based on. The default is to assume activities are based on the molar convention. However, classes which derive from the MolalityVPSSTP class return cAC_CONVENTION_MOLALITY from this member function.
The molality of a solute, \(m_i \), is defined as
\[ m_i = \frac{n_i}{\tilde{M}_o n_o} \]
where
\[ \tilde{M}_o = \frac{M_o}{1000} \]
where \(M_o \) is the molecular weight of the solvent. The molality has units of gmol kg-1. For the solute, the molality may be considered as the amount of gmol's of solute per kg of solvent, a natural experimental quantity.
The formulas for calculating mole fractions if given the molalities of the solutes is stated below. First calculate \(L^{sum} \), an intermediate quantity.
\[ L^{sum} = \frac{1}{\tilde{M}_o X_o} = \frac{1}{\tilde{M}_o} + \sum_{i\ne o} m_i \]
Then,
\[ X_o = \frac{1}{\tilde{M}_o L^{sum}} \]
\[ X_i = \frac{m_i}{L^{sum}} \]
where \(X_o \) is the mole fraction of solvent, and \(X_o \) is the mole fraction of solute i. Thus, the molality scale and the mole fraction scale offer a one-to-one mapping between each other, except in the limit of a zero solvent mole fraction.
The standard states for thermodynamic objects that derive from MolalityVPSSTP are on the unit molality basis. Chemical potentials of the solutes, \(\mu_k \), and the solvent, \(\mu_o \), which are based on the molality form, have the following general format:
\[ \mu_k = \mu^{\triangle}_k(T,P) + R T ln(\gamma_k^{\triangle} \frac{m_k}{m^\triangle}) \]
\[ \mu_o = \mu^o_o(T,P) + RT ln(a_o) \]
where \(\gamma_k^{\triangle} \) is the molality based activity coefficient for species \(k\).
The chemical potential of the solvent is thus expressed in a different format than the chemical potential of the solutes. Additionally, the activity of the solvent, \(a_o \), is further reexpressed in terms of an osmotic coefficient, \(\phi \).
\[ \phi = \frac{- ln(a_o)}{\tilde{M}_o \sum_{i \ne o} m_i} \]
MolalityVPSSTP::osmoticCoefficient() returns the value of \(\phi \). Note there are a few of definitions of the osmotic coefficient floating around. We use the one defined in (Activity Coefficients in Electrolyte Solutions, K. S. Pitzer CRC Press, Boca Raton, 1991, p. 85, Eqn. 28). This definition is most clearly related to theoretical calculation.
The molar-based activity coefficients \(\gamma_k \) may be calculated from the molality-based activity coefficients, \(\gamma_k^\triangle \) by the following formula.
\[ \gamma_k = \frac{\gamma_k^\triangle}{X_o} \]
For purposes of establishing a convention, the molar activity coefficient of the solvent is set equal to the molality-based activity coefficient of the solvent:
\[ \gamma_o = \gamma_o^\triangle \]
The molality-based and molarity-based standard states may be related to one another by the following formula.
\[ \mu_k^\triangle(T,P) = \mu_k^o(T,P) + R T \ln(\tilde{M}_o m^\triangle) \]
An important convention is followed in all routines that derive from MolalityVPSSTP. Standard state thermodynamic functions and reference state thermodynamic functions return the molality-based quantities. Also all functions which return activities return the molality-based activities. The reason for this convention has been discussed in supporting memos. However, it's important because the term in the equation above is non-trivial. For example it's equal to 2.38 kcal gmol-1 for water at 298 K.
In order to prevent a singularity, this class includes the concept of a minimum value for the solvent mole fraction. All calculations involving the formulation of activity coefficients and other non-ideal solution behavior adhere to this concept of a minimal value for the solvent mole fraction. This makes sense because these solution behavior were all designed and measured far away from the zero solvent singularity condition and are not applicable in that limit.
This objects add a layer that supports molality. It inherits from VPStandardStateTP.
All objects that derive from this are assumed to have molality based standard states.
Molality based activity coefficients are scaled according to the current pH scale. See the Eq3/6 manual for details.
Activity coefficients for species k may be altered between scales s1 to s2 using the following formula
\[ ln(\gamma_k^{s2}) = ln(\gamma_k^{s1}) + \frac{z_k}{z_j} \left(ln(\gamma_j^{s2}) - ln(\gamma_j^{s1}) \right) \]
where j is any one species. For the NBS scale, j is equal to the Cl- species and
\[ ln(\gamma_{Cl-}^{s2}) = \frac{-A_{\phi} \sqrt{I}}{1.0 + 1.5 \sqrt{I}} \]
The Pitzer scale doesn't actually change anything. The pitzer scale is defined as the raw unscaled activity coefficients produced by the underlying objects.
SetState Strategy
The MolalityVPSSTP object does not have a setState strategy concerning the molalities. It does not keep track of whether the molalities have changed. It's strictly an interfacial layer that writes the current mole fractions to the State object. When molalities are needed it recalculates the molalities from the State object's mole fraction vector.
Todo:
Make two solvent minimum fractions. One would be for calculation of the non-ideal factors. The other one would be for purposes of stoichiometry evaluation. the stoichiometry evaluation one would be a 1E-13 limit. Anything less would create problems with roundoff error.
Definition at line 189 of file MolalityVPSSTP.h.
Constructor & Destructor Documentation
MolalityVPSSTP ()
Default Constructor.
This doesn't do much more than initialize constants with default values for water at 25C. Water molecular weight comes from the default elements.xml file. It actually differs slightly from the IAPWS95 value of 18.015268. However, density conservation and therefore element conservation is the more important principle to follow.
Definition at line 31 of file MolalityVPSSTP.cpp.
References ThermoPhase::m_chargeNeutralityNecessary.
Referenced by MolalityVPSSTP::duplMyselfAsThermoPhase().
MolalityVPSSTP (const MolalityVPSSTP & b)
Copy constructor.
Parameters
b class to be copied
Definition at line 47 of file MolalityVPSSTP.cpp.
Member Function Documentation
MolalityVPSSTP & operator= (const MolalityVPSSTP & b)
Assignment operator.
Parameters
b class to be copied.
Definition at line 58 of file MolalityVPSSTP.cpp.
References MolalityVPSSTP::m_indexCLM, MolalityVPSSTP::m_indexSolvent, MolalityVPSSTP::m_Mnaught, MolalityVPSSTP::m_molalities, MolalityVPSSTP::m_pHScalingType, MolalityVPSSTP::m_weightSolvent, MolalityVPSSTP::m_xmolSolventMIN, and VPStandardStateTP::operator=().
Referenced by IdealMolalSoln::operator=(), DebyeHuckel::operator=(), and HMWSoln::operator=().
ThermoPhase * duplMyselfAsThermoPhase () const virtual
Duplication routine for objects which inherit from ThermoPhase.
This virtual routine can be used to duplicate objects inherited from ThermoPhase even if the application only has a pointer to ThermoPhase to work with.
Reimplemented from VPStandardStateTP.
Reimplemented in HMWSoln, DebyeHuckel, and IdealMolalSoln.
Definition at line 73 of file MolalityVPSSTP.cpp.
References MolalityVPSSTP::MolalityVPSSTP().
void setpHScale (const int pHscaleType)
Set the pH scale, which determines the scale for single-ion activity coefficients.
Single ion activity coefficients are not unique in terms of the representing actual measurable quantities.
Parameters
pHscaleType Integer representing the pHscale
Definition at line 82 of file MolalityVPSSTP.cpp.
References Cantera::int2str(), MolalityVPSSTP::m_pHScalingType, Cantera::PHSCALE_NBS, and Cantera::PHSCALE_PITZER.
int pHScale () const
Reports the pH scale, which determines the scale for single-ion activity coefficients.
Single ion activity coefficients are not unique in terms of the representing actual measurable quantities.
Returns
Return the pHscale type
Definition at line 91 of file MolalityVPSSTP.cpp.
References MolalityVPSSTP::m_pHScalingType.
void setSolvent (size_t k)
This routine sets the index number of the solvent for the phase.
Note, having a solvent is a precursor to many things having to do with molality.
Parameters
k the solvent index number
Definition at line 96 of file MolalityVPSSTP.cpp.
References AssertThrowMsg, MolalityVPSSTP::m_indexSolvent, Phase::m_kk, MolalityVPSSTP::m_Mnaught, MolalityVPSSTP::m_weightSolvent, and Phase::molecularWeight().
Referenced by MolalityVPSSTP::initThermo(), and MolalityVPSSTP::initThermoXML().
size_t solventIndex () const
Returns the solvent index.
Definition at line 109 of file MolalityVPSSTP.cpp.
References MolalityVPSSTP::m_indexSolvent.
void setMoleFSolventMin (doublereal xmolSolventMIN)
Sets the minimum mole fraction in the molality formulation.
Note the molality formulation is singular in the limit that the solvent mole fraction goes to zero. Numerically, how this limit is treated and resolved is an ongoing issue within Cantera. The minimum mole fraction must be in the range 0 to 0.9.
Parameters
xmolSolventMIN Input double containing the minimum mole fraction
Definition at line 114 of file MolalityVPSSTP.cpp.
References MolalityVPSSTP::m_xmolSolventMIN.
Referenced by IdealMolalSoln::initThermoXML().
doublereal moleFSolventMin () const
Returns the minimum mole fraction in the molality formulation.
Definition at line 124 of file MolalityVPSSTP.cpp.
References MolalityVPSSTP::m_xmolSolventMIN.
void calcMolalities () const
Calculates the molality of all species and stores the result internally.
We calculate the vector of molalities of the species in the phase and store the result internally:
\[ m_i = \frac{X_i}{1000 * M_o * X_{o,p}} \]
where
\(M_o \) is the molecular weight of the solvent
\(X_o \) is the mole fraction of the solvent
\(X_i \) is the mole fraction of the solute.
\(X_{o,p} = \max (X_{o}^{min}, X_o) \)
\(X_{o}^{min} \) = minimum mole fraction of solvent allowed in the denominator.
Definition at line 129 of file MolalityVPSSTP.cpp.
References DATA_PTR, Phase::getMoleFractions(), MolalityVPSSTP::m_indexSolvent, Phase::m_kk, MolalityVPSSTP::m_Mnaught, MolalityVPSSTP::m_molalities, and MolalityVPSSTP::m_xmolSolventMIN.
Referenced by DebyeHuckel::_lnactivityWaterHelgesonFixedForm(), IdealMolalSoln::getActivities(), IdealMolalSoln::getChemPotentials(), MolalityVPSSTP::getMolalities(), IdealMolalSoln::getPartialMolarEntropies(), HMWSoln::printCoeffs(), DebyeHuckel::s_update_lnMolalityActCoeff(), IdealMolalSoln::s_updateIMS_lnMolalityActCoeff(), HMWSoln::s_updateIMS_lnMolalityActCoeff(), MolalityVPSSTP::setMolalities(), and MolalityVPSSTP::setMolalitiesByName().
void getMolalities (doublereal *const molal) const
This function will return the molalities of the species.
We calculate the vector of molalities of the species in the phase
\[ m_i = \frac{X_i}{1000 * M_o * X_{o,p}} \]
where
\(M_o \) is the molecular weight of the solvent
\(X_o \) is the mole fraction of the solvent
\(X_i \) is the mole fraction of the solute.
\(X_{o,p} = \max (X_{o}^{min}, X_o) \)
\(X_{o}^{min} \) = minimum mole fraction of solvent allowed in the denominator.
Parameters
molal Output vector of molalities. Length: m_kk.
Definition at line 139 of file MolalityVPSSTP.cpp.
References MolalityVPSSTP::calcMolalities(), Phase::m_kk, and MolalityVPSSTP::m_molalities.
Referenced by MolalityVPSSTP::getCsvReportData(), MolalityVPSSTP::report(), and vcs_MultiPhaseEquil::reportCSV().
void setMolalities (const doublereal *const molal)
Set the molalities of the solutes in a phase.
Note, the entry for the solvent is not used. We are supplied with the molalities of all of the solute species. We then calculate the mole fractions of all species and update the ThermoPhase object.
\[ m_i = \frac{X_i}{M_o/1000 * X_{o,p}} \]
where
\(M_o\) is the molecular weight of the solvent
\(X_o\) is the mole fraction of the solvent
\(X_i\) is the mole fraction of the solute.
\(X_{o,p} = \max(X_o^{min}, X_o)\)
\(X_o^{min}\) = minimum mole fraction of solvent allowed in the denominator.
The formulas for calculating mole fractions are
\[ L^{sum} = \frac{1}{\tilde{M}_o X_o} = \frac{1}{\tilde{M}_o} + \sum_{i\ne o} m_i \]
Then,
\[ X_o = \frac{1}{\tilde{M}_o L^{sum}} \]
\[ X_i = \frac{m_i}{L^{sum}} \]
It is currently an error if the solvent mole fraction is attempted to be set to a value lower than \(X_o^{min}\).
Parameters
molal Input vector of molalities. Length: m_kk.
Definition at line 147 of file MolalityVPSSTP.cpp.
References MolalityVPSSTP::calcMolalities(), DATA_PTR, MolalityVPSSTP::m_indexSolvent, Phase::m_kk, MolalityVPSSTP::m_Mnaught, MolalityVPSSTP::m_molalities, and Phase::setMoleFractions().
Referenced by MolalityVPSSTP::setState_TPM().
void setMolalitiesByName (const compositionMap & xMap)
Set the molalities of a phase.
Set the molalities of the solutes in a phase. Note, the entry for the solvent is not used.
Parameters
xMap Composition Map containing the molalities.
Definition at line 176 of file MolalityVPSSTP.cpp.
References MolalityVPSSTP::calcMolalities(), Phase::charge(), DATA_PTR, Phase::getMoleFractions(), Cantera::getValue(), MolalityVPSSTP::m_indexSolvent, Phase::m_kk, MolalityVPSSTP::m_Mnaught, MolalityVPSSTP::m_xmolSolventMIN, Cantera::npos, Phase::setMoleFractions(), and Phase::speciesName().
Referenced by MolalityVPSSTP::setMolalitiesByName(), MolalityVPSSTP::setState_TPM(), and MolalityVPSSTP::setStateFromXML().
void setMolalitiesByName (const std::string & name)
Set the molalities of a phase.
Set the molalities of the solutes in a phase. Note, the entry for the solvent is not used.
Parameters
name String containing the information for a composition map.
Definition at line 256 of file MolalityVPSSTP.cpp.
References Cantera::parseCompString(), MolalityVPSSTP::setMolalitiesByName(), and Phase::speciesNames().
int activityConvention () const virtual
This method returns the activity convention.
Currently, there are two activity conventions:
Molar-based activities: Unit activity of species at either a hypothetical pure solution of the species or at a hypothetical pure ideal solution at infinite dilution. cAC_CONVENTION_MOLAR 0 (default)
Molality based activities: unit activity of solutes at a hypothetical 1 molal solution referenced to infinite dilution at all pressures and temperatures. The solvent is still on molar basis. cAC_CONVENTION_MOLALITY 1
We set the convention to molality here.
Reimplemented from ThermoPhase.
Definition at line 266 of file MolalityVPSSTP.cpp.
References Cantera::cAC_CONVENTION_MOLALITY.
void getActivityConcentrations (doublereal * c) const virtual
This method returns an array of generalized concentrations \(C_k\) that are defined such that \(a_k = C_k / C^0_k, \) where \(C^0_k \) is a standard concentration defined below.
These generalized concentrations are used by kinetics manager classes to compute the forward and reverse rates of elementary reactions.
Parameters
c Array of generalized concentrations. The units depend upon the implementation of the reaction rate expressions within the phase.
Reimplemented from ThermoPhase.
Reimplemented in HMWSoln, DebyeHuckel, and IdealMolalSoln.
Definition at line 271 of file MolalityVPSSTP.cpp.
doublereal standardConcentration (size_t k = 0) const virtual
The standard concentration \(C^0_k \) used to normalize the generalized concentration.
In many cases, this quantity will be the same for all species in a phase - for example, for an ideal gas \(C^0_k = P/\hat R T \). For this reason, this method returns a single value, instead of an array. However, for phases in which the standard concentration is species-specific (e.g. surface species of different sizes), this method may be called with an optional parameter indicating the species.
Parameters
k species index. Defaults to zero.
Reimplemented from ThermoPhase.
Reimplemented in HMWSoln, DebyeHuckel, and IdealMolalSoln.
Definition at line 276 of file MolalityVPSSTP.cpp.
void getUnitsStandardConc (double * uA, int k = 0, int sizeUA = 6) const virtual
Returns the units of the standard and generalized concentrations Note they have the same units, as their ratio is defined to be equal to the activity of the kth species in the solution, which is unitless.
This routine is used in print out applications where the units are needed. Usually, MKS units are assumed throughout the program and in the XML input files.
Parameters
uA Output vector containing the units uA[0] = kmol units - default = 1 uA[1] = m units - default = -nDim(), the number of spatial dimensions in the Phase class. uA[2] = kg units - default = 0; uA[3] = Pa(pressure) units - default = 0; uA[4] = Temperature units - default = 0; uA[5] = time units - default = 0
k species index. Defaults to 0.
sizeUA output int containing the size of the vector. Currently, this is equal to 6.
Deprecated:
To be removed after Cantera 2.2.
Reimplemented from ThermoPhase.
Reimplemented in HMWSoln, DebyeHuckel, and IdealMolalSoln.
Definition at line 332 of file MolalityVPSSTP.cpp.
References Phase::nDim(), and Cantera::warn_deprecated().
void getActivities (doublereal * ac) const virtual
Get the array of non-dimensional activities (molality based for this class and classes that derive from it) at the current solution temperature, pressure, and solution concentration.
All standard state properties for molality-based phases are evaluated consistent with the molality scale. Therefore, this function must return molality-based activities.
\[ a_i^\triangle = \gamma_k^{\triangle} \frac{m_k}{m^\triangle} \]
This function must be implemented in derived classes.
Parameters
ac Output vector of molality-based activities. Length: m_kk.
Reimplemented from ThermoPhase.
Reimplemented in HMWSoln, DebyeHuckel, and IdealMolalSoln.
Definition at line 281 of file MolalityVPSSTP.cpp.
Referenced by MolalityVPSSTP::getCsvReportData(), MolalityVPSSTP::osmoticCoefficient(), and MolalityVPSSTP::report().
void getActivityCoefficients (doublereal * ac) const virtual
Get the array of non-dimensional activity coefficients at the current solution temperature, pressure, and solution concentration.
These are mole-fraction based activity coefficients. In this object, their calculation is based on translating the values of the molality-based activity coefficients. See Denbigh p. 278 for a thorough discussion.
The molar-based activity coefficients \(\gamma_k \) may be calculated from the molality-based activity coefficients, \(\gamma_k^\triangle \) by the following formula.
\[ \gamma_k = \frac{\gamma_k^\triangle}{X_o} \]
For purposes of establishing a convention, the molar activity coefficient of the solvent is set equal to the molality-based activity coefficient of the solvent:
\[ \gamma_o = \gamma_o^\triangle \]
Derived classes don't need to overload this function. This function is handled at this level.
Parameters
ac Output vector containing the mole-fraction based activity coefficients. length: m_kk.
Reimplemented from ThermoPhase.
Definition at line 286 of file MolalityVPSSTP.cpp.
References AssertThrow, MolalityVPSSTP::getMolalityActivityCoefficients(), MolalityVPSSTP::m_indexSolvent, Phase::m_kk, MolalityVPSSTP::m_xmolSolventMIN, and Phase::moleFraction().
void getMolalityActivityCoefficients (doublereal * acMolality) const virtual
Get the array of non-dimensional molality based activity coefficients at the current solution temperature, pressure, and solution concentration.
See Denbigh p. 278 for a thorough discussion. This class must be overwritten in classes which derive from MolalityVPSSTP. This function takes over from the molar-based activity coefficient calculation, getActivityCoefficients(), in derived classes.
These molality based activity coefficients are scaled according to the current pH scale. See the Eq3/6 manual for details.
Activity coefficients for species k may be altered between scales s1 to s2 using the following formula
\[ ln(\gamma_k^{s2}) = ln(\gamma_k^{s1}) + \frac{z_k}{z_j} \left(ln(\gamma_j^{s2}) - ln(\gamma_j^{s1}) \right) \]
where j is any one species. For the NBS scale, j is equal to the Cl- species and
\[ ln(\gamma_{Cl-}^{s2}) = \frac{-A_{\phi} \sqrt{I}}{1.0 + 1.5 \sqrt{I}} \]
Parameters
acMolality Output vector containing the molality based activity coefficients. length: m_kk.
Reimplemented in DebyeHuckel, and IdealMolalSoln.
Definition at line 296 of file MolalityVPSSTP.cpp.
References MolalityVPSSTP::applyphScale(), and MolalityVPSSTP::getUnscaledMolalityActivityCoefficients().
Referenced by MolalityVPSSTP::getActivityCoefficients(), MolalityVPSSTP::getCsvReportData(), and MolalityVPSSTP::report().
doublereal osmoticCoefficient () const virtual
Calculate the osmotic coefficient.
\[ \phi = \frac{- ln(a_o)}{\tilde{M}_o \sum_{i \ne o} m_i} \]
Note there are a few of definitions of the osmotic coefficient floating around. We use the one defined in (Activity Coefficients in Electrolyte Solutions, K. S. Pitzer CRC Press, Boca Raton, 1991, p. 85, Eqn. 28). This definition is most clearly related to theoretical calculation.
units = dimensionless
Definition at line 302 of file MolalityVPSSTP.cpp.
References DATA_PTR, MolalityVPSSTP::getActivities(), MolalityVPSSTP::m_indexSolvent, Phase::m_kk, MolalityVPSSTP::m_Mnaught, and MolalityVPSSTP::m_molalities.
void getElectrochemPotentials (doublereal * mu) const
Get the species electrochemical potentials.
These are partial molar quantities. This method adds a term \(Fz_k \phi_k \) to each chemical potential.
Units: J/kmol
Parameters
mu output vector containing the species electrochemical potentials. Length: m_kk.
Definition at line 323 of file MolalityVPSSTP.cpp.
References Phase::charge(), ThermoPhase::electricPotential(), ThermoPhase::getChemPotentials(), and Phase::m_kk.
void setToEquilState (const doublereal * lambda_RT) virtual
This method is used by the ChemEquil element-potential based equilibrium solver.
It sets the state such that the chemical potentials of the species within the current phase satisfy
\[ \frac{\mu_k}{\hat R T} = \sum_m A_{k,m} \left(\frac{\lambda_m} {\hat R T}\right) \]
where \(\lambda_m \) is the element potential of element m. The temperature is unchanged. Any phase (ideal or not) that implements this method can be equilibrated by ChemEquil.
Parameters
lambda_RT Input vector containing the dimensionless element potentials.
Reimplemented from ThermoPhase.
Reimplemented in HMWSoln, DebyeHuckel, and IdealMolalSoln.
Definition at line 359 of file MolalityVPSSTP.cpp.
References VPStandardStateTP::updateStandardStateThermo().
void setStateFromXML (const XML_Node & state) virtual
Set equation of state parameter values from XML entries.
This method is called by function importPhase() when processing a phase definition in an input file. It should be overloaded in subclasses to set any parameters that are specific to that particular phase model.
The MolalityVPSSTP object defines a new method for setting the concentrations of a phase. The new method is defined by a block called "soluteMolalities". If this block is found, the concentrations within that phase are set to the "name":"molalities pairs found within that XML block. The solvent concentration is then set to everything else.
The function first calls the overloaded function, VPStandardStateTP::setStateFromXML(), to pick up the parent class behavior.
usage: Overloaded functions should call this function before carrying out their own behavior.
Parameters
state An XML_Node object corresponding to the "state" entry for this phase in the input file.
Reimplemented from ThermoPhase.
Definition at line 365 of file MolalityVPSSTP.cpp.
References Cantera::getChildValue(), Cantera::getFloat(), XML_Node::hasChild(), MolalityVPSSTP::setMolalitiesByName(), VPStandardStateTP::setPressure(), and ThermoPhase::setStateFromXML().
Referenced by IdealMolalSoln::initThermoXML(), and DebyeHuckel::initThermoXML().
void initThermo () virtual
The following methods are used in the process of constructing the phase and setting its parameters from a specification in an input file. They are not normally used in application programs. To see how they are used, see importPhase().
Reimplemented from VPStandardStateTP.
Reimplemented in HMWSoln, DebyeHuckel, and IdealMolalSoln.
Definition at line 398 of file MolalityVPSSTP.cpp.
References MolalityVPSSTP::findCLMIndex(), MolalityVPSSTP::initLengths(), VPStandardStateTP::initThermo(), MolalityVPSSTP::m_indexCLM, and MolalityVPSSTP::setSolvent().
Referenced by IdealMolalSoln::initThermo(), and DebyeHuckel::initThermo().
void initThermoXML (XML_Node & phaseNode, const std::string & id) virtual
Import and initialize a ThermoPhase object.
Parameters
phaseNode This object must be the phase node of a complete XML tree description of the phase, including all of the species data. In other words while "phase" must point to an XML phase object, it must have sibling nodes "speciesData" that describe the species in the phase.
id ID of the phase. If nonnull, a check is done to see if phaseNode is pointing to the phase with the correct id.
Reimplemented from VPStandardStateTP.
Definition at line 486 of file MolalityVPSSTP.cpp.
References MolalityVPSSTP::initLengths(), VPStandardStateTP::initThermoXML(), and MolalityVPSSTP::setSolvent().
Referenced by IdealMolalSoln::initThermoXML().
void setState_TPM (doublereal t, doublereal p, const doublereal *const molalities)
Set the temperature (K), pressure (Pa), and molalities (gmol kg-1) of the solutes.
Parameters
t Temperature (K)
p Pressure (Pa)
molalities Input vector of molalities of the solutes. Length: m_kk.
Definition at line 378 of file MolalityVPSSTP.cpp.
References MolalityVPSSTP::setMolalities(), and VPStandardStateTP::setState_TP().
void setState_TPM (doublereal t, doublereal p, const compositionMap & m)
Set the temperature (K), pressure (Pa), and molalities.
Parameters
t Temperature (K)
p Pressure (Pa)
m compositionMap containing the molalities
Definition at line 385 of file MolalityVPSSTP.cpp.
References MolalityVPSSTP::setMolalitiesByName(), and VPStandardStateTP::setState_TP().
void setState_TPM (doublereal t, doublereal p, const std::string & m)
Set the temperature (K), pressure (Pa), and molalities.
Parameters
t Temperature (K)
p Pressure (Pa)
m String which gets translated into a composition map for the molalities of the solutes.
Definition at line 391 of file MolalityVPSSTP.cpp.
References MolalityVPSSTP::setMolalitiesByName(), and VPStandardStateTP::setState_TP().
virtual void getdlnActCoeffdlnN (const size_t ld, doublereal *const dlnActCoeffdlnN) inline virtual
Get the array of derivatives of the log activity coefficients with respect to the log of the species mole numbers.
Implementations should take the derivative of the logarithm of the activity coefficient with respect to a species log mole number (with all other species mole numbers held constant). The default treatment in the ThermoPhase object is to set this vector to zero.
units = 1 / kmol
dlnActCoeffdlnN[ ld * k + m] will contain the derivative of log act_coeff for the mth species with respect to the number of moles of the kth species.
\[ \frac{d \ln(\gamma_m) }{d \ln(n_k) }\Bigg|_{n_i} \]
Parameters
ld Number of rows in the matrix
dlnActCoeffdlnN Output vector of derivatives of the log Activity Coefficients. length = m_kk * m_kk
Reimplemented from ThermoPhase.
Definition at line 691 of file MolalityVPSSTP.h.
std::string report (bool show_thermo = true, doublereal threshold = 1e-14) const virtual
returns a summary of the state of the phase as a string
Format a summary of the mixture state for output.
Parameters
show_thermo If true, extra information is printed out about the thermodynamic state of the system.
threshold Show information about species with mole fractions greater than threshold.
Reimplemented from ThermoPhase.
Definition at line 501 of file MolalityVPSSTP.cpp.
References ThermoPhase::cp_mass(), ThermoPhase::cp_mole(), ThermoPhase::cv_mass(), ThermoPhase::cv_mole(), Phase::density(), ThermoPhase::electricPotential(), ThermoPhase::enthalpy_mass(), ThermoPhase::enthalpy_mole(), ThermoPhase::entropy_mass(), ThermoPhase::entropy_mole(), MolalityVPSSTP::getActivities(), ThermoPhase::getChemPotentials(), MolalityVPSSTP::getMolalities(), MolalityVPSSTP::getMolalityActivityCoefficients(), Phase::getMoleFractions(), VPStandardStateTP::getStandardChemPotentials(), ThermoPhase::gibbs_mass(), ThermoPhase::gibbs_mole(), ThermoPhase::intEnergy_mass(), ThermoPhase::intEnergy_mole(), Phase::m_kk, Phase::meanMolecularWeight(), Phase::name(), Cantera::npos, VPStandardStateTP::pressure(), CanteraError::save(), Cantera::SmallNumber, Phase::speciesIndex(), Phase::speciesName(), and Phase::temperature().
void getCsvReportData (std::vector< std::string > & names, std::vector< vector_fp > & data) const protected virtual
Fills names and data with the column names and species thermo properties to be included in the output of the reportCSV method.
Reimplemented from ThermoPhase.
Definition at line 633 of file MolalityVPSSTP.cpp.
References MolalityVPSSTP::getActivities(), ThermoPhase::getChemPotentials(), MolalityVPSSTP::getMolalities(), MolalityVPSSTP::getMolalityActivityCoefficients(), Phase::getMoleFractions(), ThermoPhase::getPartialMolarCp(), ThermoPhase::getPartialMolarEnthalpies(), ThermoPhase::getPartialMolarEntropies(), ThermoPhase::getPartialMolarIntEnergies(), ThermoPhase::getPartialMolarVolumes(), VPStandardStateTP::getStandardChemPotentials(), and Phase::nSpecies().
void getUnscaledMolalityActivityCoefficients (doublereal * acMolality) const protected virtual
Get the array of unscaled non-dimensional molality based activity coefficients at the current solution temperature, pressure, and solution concentration.
See Denbigh p. 278 for a thorough discussion. This class must be overwritten in classes which derive from MolalityVPSSTP. This function takes over from the molar-based activity coefficient calculation, getActivityCoefficients(), in derived classes.
Parameters
acMolality Output vector containing the molality based activity coefficients. length: m_kk.
Reimplemented in HMWSoln.
Definition at line 413 of file MolalityVPSSTP.cpp.
Referenced by MolalityVPSSTP::getMolalityActivityCoefficients().
void applyphScale (doublereal * acMolality) const protected virtual
Apply the current phScale to a set of activity Coefficients or activities.
See the Eq3/6 Manual for a thorough discussion.
Parameters
acMolality input/Output vector containing the molality based activity coefficients. length: m_kk.
Reimplemented in HMWSoln.
Definition at line 418 of file MolalityVPSSTP.cpp.
Referenced by MolalityVPSSTP::getMolalityActivityCoefficients().
size_t findCLMIndex () const private virtual
Returns the index of the Cl- species.
The Cl- species is special in the sense that its single ion molality-based activity coefficient is used in the specification of the pH scale for single ions. Therefore, we need to know what species index is Cl-. If the species isn't in the species list then this routine returns -1, and we can't use the NBS pH scale.
Right now we use a restrictive interpretation. The species must be named "Cl-". It must consist of exactly one Cl and one E atom.
Definition at line 423 of file MolalityVPSSTP.cpp.
References Phase::elementName(), Phase::m_kk, Phase::nAtoms(), Phase::nElements(), Cantera::npos, and Phase::speciesName().
Referenced by MolalityVPSSTP::initThermo().
void initLengths () private
Initialize lengths of local variables after all species have been identified.
Definition at line 481 of file MolalityVPSSTP.cpp.
References Phase::m_kk, and MolalityVPSSTP::m_molalities.
Referenced by MolalityVPSSTP::initThermo(), and MolalityVPSSTP::initThermoXML().
Member Data Documentation
size_t m_indexSolvent protected
Index of the solvent.
Currently the index of the solvent is hard-coded to the value 0
Definition at line 759 of file MolalityVPSSTP.h.
Referenced by DebyeHuckel::_lnactivityWaterHelgesonFixedForm(), MolalityVPSSTP::calcMolalities(), HMWSoln::calcMolalitiesCropped(), IdealMolalSoln::getActivities(), DebyeHuckel::getActivities(), HMWSoln::getActivities(), MolalityVPSSTP::getActivityCoefficients(), IdealMolalSoln::getChemPotentials(), DebyeHuckel::getChemPotentials(), HMWSoln::getChemPotentials(), IdealMolalSoln::getMolalityActivityCoefficients(), IdealMolalSoln::getPartialMolarEntropies(), DebyeHuckel::getPartialMolarEntropies(), HMWSoln::getPartialMolarEntropies(), IdealMolalSoln::initThermoXML(), DebyeHuckel::initThermoXML(), MolalityVPSSTP::operator=(), MolalityVPSSTP::osmoticCoefficient(), DebyeHuckel::s_update_d2lnMolalityActCoeff_dT2(), DebyeHuckel::s_update_dlnMolalityActCoeff_dP(), DebyeHuckel::s_update_dlnMolalityActCoeff_dT(), DebyeHuckel::s_update_lnMolalityActCoeff(), IdealMolalSoln::s_updateIMS_lnMolalityActCoeff(), HMWSoln::s_updateIMS_lnMolalityActCoeff(), HMWSoln::s_updatePitzer_d2lnMolalityActCoeff_dT2(), HMWSoln::s_updatePitzer_dlnMolalityActCoeff_dP(), HMWSoln::s_updatePitzer_dlnMolalityActCoeff_dT(), HMWSoln::s_updatePitzer_lnMolalityActCoeff(), MolalityVPSSTP::setMolalities(), MolalityVPSSTP::setMolalitiesByName(), MolalityVPSSTP::setSolvent(), MolalityVPSSTP::solventIndex(), IdealMolalSoln::standardConcentration(), DebyeHuckel::standardConcentration(), and HMWSoln::standardConcentration().
int m_pHScalingType protected
Scaling to be used for output of single-ion species activity coefficients.
Index of the species to be used in the single-ion scaling law. This is the identity of the Cl- species for the PHSCALE_NBS scaling. Either PHSCALE_PITZER or PHSCALE_NBS
Definition at line 769 of file MolalityVPSSTP.h.
Referenced by HMWSoln::applyphScale(), MolalityVPSSTP::operator=(), MolalityVPSSTP::pHScale(), HMWSoln::s_updateScaling_pHScaling(), HMWSoln::s_updateScaling_pHScaling_dP(), HMWSoln::s_updateScaling_pHScaling_dT(), HMWSoln::s_updateScaling_pHScaling_dT2(), and MolalityVPSSTP::setpHScale().
size_t m_indexCLM protected
Index of the phScale species.
Index of the species to be used in the single-ion scaling law. This is the identity of the Cl- species for the PHSCALE_NBS scaling
Definition at line 777 of file MolalityVPSSTP.h.
Referenced by HMWSoln::applyphScale(), MolalityVPSSTP::initThermo(), MolalityVPSSTP::operator=(), HMWSoln::s_updateScaling_pHScaling(), HMWSoln::s_updateScaling_pHScaling_dP(), HMWSoln::s_updateScaling_pHScaling_dT(), and HMWSoln::s_updateScaling_pHScaling_dT2().
doublereal m_weightSolvent protected
Molecular weight of the Solvent.
Definition at line 780 of file MolalityVPSSTP.h.
Referenced by MolalityVPSSTP::operator=(), HMWSoln::s_updatePitzer_d2lnMolalityActCoeff_dT2(), HMWSoln::s_updatePitzer_dlnMolalityActCoeff_dP(), HMWSoln::s_updatePitzer_dlnMolalityActCoeff_dT(), HMWSoln::s_updatePitzer_lnMolalityActCoeff(), and MolalityVPSSTP::setSolvent().
doublereal m_xmolSolventMIN protected
In any molality implementation, it makes sense to have a minimum solvent mole fraction requirement, since the implementation becomes singular in the xmolSolvent=0 limit. The default is to set it to 0.01. We then modify the molality definition to ensure that molal_solvent = 0 when xmol_solvent = 0.
Definition at line 790 of file MolalityVPSSTP.h.
Referenced by MolalityVPSSTP::calcMolalities(), IdealMolalSoln::getActivities(), MolalityVPSSTP::getActivityCoefficients(), IdealMolalSoln::getMolalityActivityCoefficients(), MolalityVPSSTP::moleFSolventMin(), MolalityVPSSTP::operator=(), IdealMolalSoln::s_updateIMS_lnMolalityActCoeff(), HMWSoln::s_updateIMS_lnMolalityActCoeff(), HMWSoln::s_updatePitzer_lnMolalityActCoeff(), MolalityVPSSTP::setMolalitiesByName(), and MolalityVPSSTP::setMoleFSolventMin().
doublereal m_Mnaught protected
This is the multiplication factor that goes inside log expressions involving the molalities of species.
It's equal to Wt_0 / 1000, where Wt_0 = weight of solvent (kg/kmol)
Definition at line 798 of file MolalityVPSSTP.h.
Referenced by DebyeHuckel::_lnactivityWaterHelgesonFixedForm(), MolalityVPSSTP::calcMolalities(), HMWSoln::calcMolalitiesCropped(), MolalityVPSSTP::operator=(), MolalityVPSSTP::osmoticCoefficient(), DebyeHuckel::s_update_d2lnMolalityActCoeff_dT2(), DebyeHuckel::s_update_dlnMolalityActCoeff_dP(), DebyeHuckel::s_update_dlnMolalityActCoeff_dT(), DebyeHuckel::s_update_lnMolalityActCoeff(), MolalityVPSSTP::setMolalities(), MolalityVPSSTP::setMolalitiesByName(), MolalityVPSSTP::setSolvent(), and HMWSoln::standardConcentration().
vector_fp m_molalities mutable protected
Current value of the molalities of the species in the phase.
Note this vector is a mutable quantity. units are (kg/kmol)
Definition at line 805 of file MolalityVPSSTP.h.
Referenced by DebyeHuckel::_lnactivityWaterHelgesonFixedForm(), MolalityVPSSTP::calcMolalities(), HMWSoln::calcMolalitiesCropped(), IdealMolalSoln::getActivities(), DebyeHuckel::getActivities(), HMWSoln::getActivities(), IdealMolalSoln::getChemPotentials(), DebyeHuckel::getChemPotentials(), HMWSoln::getChemPotentials(), MolalityVPSSTP::getMolalities(), IdealMolalSoln::getPartialMolarEntropies(), DebyeHuckel::getPartialMolarEntropies(), HMWSoln::getPartialMolarEntropies(), MolalityVPSSTP::initLengths(), MolalityVPSSTP::operator=(), MolalityVPSSTP::osmoticCoefficient(), DebyeHuckel::s_update_d2lnMolalityActCoeff_dT2(), DebyeHuckel::s_update_dlnMolalityActCoeff_dP(), DebyeHuckel::s_update_dlnMolalityActCoeff_dT(), DebyeHuckel::s_update_lnMolalityActCoeff(), HMWSoln::s_updatePitzer_lnMolalityActCoeff(), and MolalityVPSSTP::setMolalities().
The documentation for this class was generated from the following files:
MolalityVPSSTP.h
MolalityVPSSTP.cpp