Cantera: LiquidTranInteraction Class Reference
LiquidTranInteraction Class Reference
Base class to handle transport property evaluation in a mixture.
#include <LiquidTranInteraction.h>
Public Member Functions
LiquidTranInteraction (TransportPropertyType tp_ind=TP_UNKNOWN)
Constructor.
LiquidTranInteraction (const LiquidTranInteraction &right)
LiquidTranInteraction & operator= (const LiquidTranInteraction &right)
virtual void init (const XML_Node &compModelNode=XML_Node(), thermo_t *thermo=0)
initialize LiquidTranInteraction objects with thermo and XML node
virtual void setParameters (LiquidTransportParams &trParam)
virtual doublereal getMixTransProp (doublereal *speciesValues, doublereal *weightSpecies=0)
Return the mixture transport property value.
virtual doublereal getMixTransProp (std::vector< LTPspecies * > LTPptrs)
virtual void getMatrixTransProp (DenseMatrix &mat, doublereal *speciesValues=0)
Protected Attributes
LiquidTranMixingModel m_model
Model for species interaction effects Takes enum LiquidTranMixingModel.
TransportPropertyType m_property
enum indicating what property this is (i.e viscosity)
thermo_t * m_thermo
pointer to thermo object to get current temperature
std::vector< DenseMatrix * > m_Aij
Matrix of interaction coefficients for polynomial in molefraction*weight of speciesA (no temperature dependence, dimensionless)
std::vector< DenseMatrix * > m_Bij
Matrix of interaction coefficients for polynomial in molefraction*weight of speciesA (linear temperature dependence, units 1/K)
DenseMatrix m_Eij
Matrix of interactions (in energy units, 1/RT temperature dependence)
std::vector< DenseMatrix * > m_Hij
Matrix of interaction coefficients for polynomial in molefraction*weight of speciesA (in energy units, 1/RT temperature dependence)
std::vector< DenseMatrix * > m_Sij
Matrix of interaction coefficients for polynomial in molefraction*weight of speciesA (in entropy units, divided by R)
DenseMatrix m_Dij
Matrix of interactions.
Detailed Description
Base class to handle transport property evaluation in a mixture.
In a mixture, the mixture transport properties will generally depend on the contributions of each of the standard state species transport properties. Many composition dependencies are possible. This class, LiquidTranInteraction, is designed to be a base class for the implementation of various models for the mixing of standard state species transport properties.
There are two very broad types of transport properties to consider. First, there are properties for which a mixture value can be obtained through some mixing rule. These are obtained using the method getMixTransProp(). Viscosity is typical of this. Second, there are properties for which a matrix of properties may exist. This matrix of properties is obtained from the method getMatrixTransProp(). Diffusion coefficients are of this type. Subclasses should implement the appropriate one or both of these methods.
Definition at line 103 of file LiquidTranInteraction.h.
Constructor & Destructor Documentation
LiquidTranInteraction (TransportPropertyType tp_ind = TP_UNKNOWN)
Constructor.
Parameters
tp_ind Index indicating the transport property type (e.g., viscosity)
Definition at line 42 of file LiquidTranInteraction.cpp.
Member Function Documentation
void init (const XML_Node & compModelNode = XML_Node(), thermo_t * thermo = 0) virtual
initialize LiquidTranInteraction objects with thermo and XML node
Parameters
compModelNode <compositionDependence> XML node
thermo Pointer to thermo object
Definition at line 68 of file LiquidTranInteraction.cpp.
References XML_Node::attrib(), XML_Node::child(), Cantera::GasConstant, Cantera::getFloat(), Cantera::getFloatArray(), XML_Node::hasChild(), Cantera::lowercase(), LiquidTranInteraction::m_Aij, LiquidTranInteraction::m_Bij, LiquidTranInteraction::m_Dij, LiquidTranInteraction::m_Eij, LiquidTranInteraction::m_Hij, LiquidTranInteraction::m_Sij, LiquidTranInteraction::m_thermo, XML_Node::name(), XML_Node::nChildren(), Cantera::npos, Phase::nSpecies(), DenseMatrix::resize(), and Phase::speciesIndex().
Referenced by TransportFactory::newLTI().
virtual doublereal getMixTransProp (doublereal * speciesValues, doublereal * weightSpecies = 0) inline virtual
Return the mixture transport property value.
(Must be implemented in subclasses.)
Reimplemented in LTI_MoleFracs_ExpT, LTI_StefanMaxwell_PPN, LTI_Pairwise_Interaction, LTI_Log_MoleFracs, LTI_MassFracs, and LTI_MoleFracs.
Definition at line 130 of file LiquidTranInteraction.h.
Referenced by LTI_StefanMaxwell_PPN::getMatrixTransProp(), LiquidTransport::ionConductivity(), LiquidTransport::thermalConductivity(), and LiquidTransport::viscosity().
Member Data Documentation
LiquidTranMixingModel m_model protected
Model for species interaction effects Takes enum LiquidTranMixingModel.
Definition at line 146 of file LiquidTranInteraction.h.
TransportPropertyType m_property protected
enum indicating what property this is (i.e viscosity)
Definition at line 149 of file LiquidTranInteraction.h.
thermo_t* m_thermo protected
pointer to thermo object to get current temperature
Definition at line 152 of file LiquidTranInteraction.h.
Referenced by LTI_Pairwise_Interaction::getMatrixTransProp(), LTI_StefanMaxwell_PPN::getMatrixTransProp(), LTI_MoleFracs::getMixTransProp(), LTI_MassFracs::getMixTransProp(), LTI_Log_MoleFracs::getMixTransProp(), LTI_Pairwise_Interaction::getMixTransProp(), LTI_StefanMaxwell_PPN::getMixTransProp(), LTI_MoleFracs_ExpT::getMixTransProp(), LiquidTranInteraction::init(), LTI_Pairwise_Interaction::setParameters(), and LTI_StefanMaxwell_PPN::setParameters().
std::vector<DenseMatrix*> m_Aij protected
Matrix of interaction coefficients for polynomial in molefraction*weight of speciesA (no temperature dependence, dimensionless)
Definition at line 158 of file LiquidTranInteraction.h.
Referenced by LTI_MoleFracs::getMatrixTransProp(), LTI_MassFracs::getMatrixTransProp(), LTI_MoleFracs_ExpT::getMatrixTransProp(), LTI_MoleFracs::getMixTransProp(), LTI_MassFracs::getMixTransProp(), LTI_MoleFracs_ExpT::getMixTransProp(), and LiquidTranInteraction::init().
std::vector<DenseMatrix*> m_Bij protected
Matrix of interaction coefficients for polynomial in molefraction*weight of speciesA (linear temperature dependence, units 1/K)
Definition at line 162 of file LiquidTranInteraction.h.
Referenced by LTI_MoleFracs::getMixTransProp(), LTI_MassFracs::getMixTransProp(), LTI_MoleFracs_ExpT::getMixTransProp(), and LiquidTranInteraction::init().
DenseMatrix m_Eij protected
Matrix of interactions (in energy units, 1/RT temperature dependence)
Definition at line 165 of file LiquidTranInteraction.h.
Referenced by LTI_Log_MoleFracs::getMatrixTransProp(), LTI_Pairwise_Interaction::getMatrixTransProp(), and LiquidTranInteraction::init().
std::vector<DenseMatrix*> m_Hij protected
Matrix of interaction coefficients for polynomial in molefraction*weight of speciesA (in energy units, 1/RT temperature dependence)
Definition at line 169 of file LiquidTranInteraction.h.
Referenced by LTI_Log_MoleFracs::getMixTransProp(), and LiquidTranInteraction::init().
std::vector<DenseMatrix*> m_Sij protected
Matrix of interaction coefficients for polynomial in molefraction*weight of speciesA (in entropy units, divided by R)
Definition at line 173 of file LiquidTranInteraction.h.
Referenced by LTI_Log_MoleFracs::getMixTransProp(), and LiquidTranInteraction::init().
DenseMatrix m_Dij protected
Matrix of interactions.
Definition at line 176 of file LiquidTranInteraction.h.
Referenced by LTI_Pairwise_Interaction::getMatrixTransProp(), and LiquidTranInteraction::init().
The documentation for this class was generated from the following files:
LiquidTranInteraction.h
LiquidTranInteraction.cpp