Cantera: KineticsFactory Class Reference
KineticsFactory Class Reference
Factory for kinetics managers.
#include <KineticsFactory.h>
Public Member Functions
virtual void deleteFactory ()
Virtual abstract function that deletes the factory.
virtual Kinetics * newKinetics (XML_Node &phase, std::vector< ThermoPhase * > th)
Return a new kinetics manager that implements a reaction mechanism specified in a CTML file.
virtual Kinetics * newKinetics (const std::string &model)
Return a new, empty kinetics manager.
Public Member Functions inherited from FactoryBase
virtual ~FactoryBase ()
destructor
Static Public Member Functions
static KineticsFactory * factory ()
Static Public Member Functions inherited from FactoryBase
static void deleteFactories ()
static function that deletes all factories in the internal registry maintained in a static variable
Static Private Attributes
static KineticsFactory * s_factory = 0
static mutex_t kinetics_mutex
Additional Inherited Members
Protected Member Functions inherited from FactoryBase
FactoryBase ()
Constructor.
Detailed Description
Factory for kinetics managers.
Definition at line 29 of file KineticsFactory.h.
Member Function Documentation
virtual void deleteFactory () inline virtual
Virtual abstract function that deletes the factory.
This must be properly defined in child objects.
Implements FactoryBase.
Definition at line 40 of file KineticsFactory.h.
Kinetics * newKinetics (XML_Node & phase, std::vector< ThermoPhase * > th) virtual
Return a new kinetics manager that implements a reaction mechanism specified in a CTML file.
In other words, the kinetics manager, given the rate constants and formulation of the reactions that make up a kinetics mechanism, is responsible for calculating the rates of progress of the reactions and for calculating the source terms for species.
Parameters
phase An XML_Node that contains the XML data describing the phase. Of particular note to this routine is the child XML element called "kinetics". The element has one attribute called "model", with a string value. The value of this string is used to decide which kinetics manager is used to calculate the reaction mechanism.
th Vector of phases. The first phase is the phase in which the reactions occur, and the subsequent phases (if any) are e.g. bulk phases adjacent to a reacting surface.
Returns
Pointer to the new kinetics manager.
Definition at line 23 of file KineticsFactory.cpp.
References XML_Node::child(), and Cantera::importKinetics().
Kinetics * newKinetics (const std::string & model) virtual
Return a new, empty kinetics manager.
Definition at line 43 of file KineticsFactory.cpp.
References Cantera::lowercase().
The documentation for this class was generated from the following files:
KineticsFactory.h
KineticsFactory.cpp