Cantera: NasaPoly1 Class Reference
NasaPoly1 Class Reference
Species Reference-State Thermodynamic Properties
The NASA polynomial parameterization for one temperature range.
#include <NasaPoly1.h>
Public Member Functions
NasaPoly1 ()
Empty constructor.
NasaPoly1 (size_t n, doublereal tlow, doublereal thigh, doublereal pref, const doublereal *coeffs)
constructor used in templated instantiations
NasaPoly1 (double tlow, double thigh, double pref, const double *coeffs)
Normal constructor.
NasaPoly1 (const NasaPoly1 &b)
copy constructor
NasaPoly1 & operator= (const NasaPoly1 &b)
assignment operator
virtual SpeciesThermoInterpType * duplMyselfAsSpeciesThermoInterpType () const
virtual int reportType () const
Returns an integer representing the type of parameterization.
virtual size_t temperaturePolySize () const
Number of terms in the temperature polynomial for this parameterization.
virtual void updateTemperaturePoly (double T, double *T_poly) const
Given the temperature T, compute the terms of the temperature polynomial T_poly.
virtual void updateProperties (const doublereal *tt, doublereal *cp_R, doublereal *h_RT, doublereal *s_R) const
Update the properties for this species, given a temperature polynomial.
virtual void updatePropertiesTemp (const doublereal temp, doublereal *cp_R, doublereal *h_RT, doublereal *s_R) const
Compute the reference-state property of one species.
virtual void reportParameters (size_t &n, int &type, doublereal &tlow, doublereal &thigh, doublereal &pref, doublereal *const coeffs) const
This utility function reports back the type of parameterization and all of the parameters for the species, index.
virtual void modifyParameters (doublereal *coeffs)
Modify parameters for the standard state.
virtual doublereal reportHf298 (doublereal *const h298=0) const
Report the 298 K Heat of Formation of the standard state of one species (J kmol-1)
virtual void modifyOneHf298 (const size_t k, const doublereal Hf298New)
Modify the value of the 298 K Heat of Formation of one species in the phase (J kmol-1)
Public Member Functions inherited from SpeciesThermoInterpType
SpeciesThermoInterpType (size_t n, doublereal tlow, doublereal thigh, doublereal pref)
SpeciesThermoInterpType (double tlow, double thigh, double pref)
SpeciesThermoInterpType (const SpeciesThermoInterpType &b)
virtual doublereal minTemp () const
Returns the minimum temperature that the thermo parameterization is valid.
virtual doublereal maxTemp () const
Returns the maximum temperature that the thermo parameterization is valid.
virtual doublereal refPressure () const
Returns the reference pressure (Pa)
virtual void validate (const std::string &name)
Check for problems with the parameterization, and generate warnings or throw and exception if any are found.
virtual size_t speciesIndex () const
Returns an integer representing the species index.
virtual void setIndex (size_t index)
Protected Attributes
vector_fp m_coeff
array of polynomial coefficients, stored in the order [a0, ..., a6]
Protected Attributes inherited from SpeciesThermoInterpType
doublereal m_lowT
lowest valid temperature
doublereal m_highT
Highest valid temperature.
doublereal m_Pref
Reference state pressure.
size_t m_index
species index
Detailed Description
The NASA polynomial parameterization for one temperature range.
This parameterization expresses the heat capacity as a fourth-order polynomial. Note that this is the form used in the 1971 NASA equilibrium program and by the Chemkin software package, but differs from the form used in the more recent NASA equilibrium program.
Seven coefficients \((a_0,\dots,a_6)\) are used to represent \(c_p^0(T)\), \(h^0(T)\), and \(s^0(T) \) as polynomials in \(T \) :
\[ \frac{c_p(T)}{R} = a_0 + a_1 T + a_2 T^2 + a_3 T^3 + a_4 T^4 \]
\[ \frac{h^0(T)}{RT} = a_0 + \frac{a_1}{2} T + \frac{a_2}{3} T^2 + \frac{a_3}{4} T^3 + \frac{a_4}{5} T^4 + \frac{a_5}{T}. \]
\[ \frac{s^0(T)}{R} = a_0\ln T + a_1 T + \frac{a_2}{2} T^2 + \frac{a_3}{3} T^3 + \frac{a_4}{4} T^4 + a_6. \]
This class is designed specifically for use by class NasaThermo.
Definition at line 46 of file NasaPoly1.h.
Constructor & Destructor Documentation
NasaPoly1 () inline
Empty constructor.
Definition at line 50 of file NasaPoly1.h.
NasaPoly1 (size_t n, doublereal tlow, doublereal thigh, doublereal pref, const doublereal * coeffs) inline
constructor used in templated instantiations
Parameters
n Species index
tlow Minimum temperature
thigh Maximum temperature
pref reference pressure (Pa).
coeffs Vector of coefficients used to set the parameters for the standard state, in the order [a5,a6,a0,a1,a2,a3,a4]
Deprecated:
Use the constructor which does not take species index. To be removed after Cantera 2.2.
Definition at line 64 of file NasaPoly1.h.
References NasaPoly1::m_coeff.
NasaPoly1 (double tlow, double thigh, double pref, const double * coeffs) inline
Normal constructor.
Parameters
tlow Minimum temperature
thigh Maximum temperature
pref reference pressure (Pa).
coeffs Vector of coefficients used to set the parameters for the standard state, in the order [a0,a1,a2,a3,a4,a5,a6]
Definition at line 84 of file NasaPoly1.h.
NasaPoly1 (const NasaPoly1 & b) inline
copy constructor
Parameters
b object to be copied
Definition at line 94 of file NasaPoly1.h.
Member Function Documentation
NasaPoly1& operator= (const NasaPoly1 & b) inline
assignment operator
Parameters
b object to be copied
Definition at line 104 of file NasaPoly1.h.
References NasaPoly1::m_coeff.
virtual int reportType () const inline virtual
Returns an integer representing the type of parameterization.
Implements SpeciesThermoInterpType.
Definition at line 118 of file NasaPoly1.h.
References NASA1.
virtual size_t temperaturePolySize () const inline virtual
Number of terms in the temperature polynomial for this parameterization.
Reimplemented from SpeciesThermoInterpType.
Definition at line 122 of file NasaPoly1.h.
virtual void updateTemperaturePoly (double T, double * T_poly) const inline virtual
Given the temperature T, compute the terms of the temperature polynomial T_poly.
Reimplemented from SpeciesThermoInterpType.
Definition at line 124 of file NasaPoly1.h.
Referenced by NasaPoly1::reportHf298(), NasaPoly1::updatePropertiesTemp(), and NasaPoly2::updateTemperaturePoly().
virtual void updateProperties (const doublereal * tt, doublereal * cp_R, doublereal * h_RT, doublereal * s_R) const inline virtual
Update the properties for this species, given a temperature polynomial.
This method is called with a pointer to an array containing the functions of temperature needed by this parameterization, and three pointers to arrays where the computed property values should be written. This method updates only one value in each array.
Temperature Polynomial: tt[0] = t; tt[1] = t*t; tt[2] = m_t[1]*t; tt[3] = m_t[2]*t; tt[4] = 1.0/t; tt[5] = std::log(t);
Parameters
tt vector of temperature polynomials
cp_R Vector of Dimensionless heat capacities. (length m_kk).
h_RT Vector of Dimensionless enthalpies. (length m_kk).
s_R Vector of Dimensionless entropies. (length m_kk).
Reimplemented from SpeciesThermoInterpType.
Definition at line 153 of file NasaPoly1.h.
References NasaPoly1::m_coeff, and SpeciesThermoInterpType::m_index.
Referenced by NasaThermo::update_one(), NasaPoly2::updateProperties(), and NasaPoly1::updatePropertiesTemp().
virtual void updatePropertiesTemp (const doublereal temp, doublereal * cp_R, doublereal * h_RT, doublereal * s_R) const inline virtual
Compute the reference-state property of one species.
Given temperature T in K, this method updates the values of the non-dimensional heat capacity at constant pressure, enthalpy, and entropy, at the reference pressure, Pref of one of the species. The species index is used to reference into the cp_R, h_RT, and s_R arrays.
Parameters
temp Temperature (Kelvin)
cp_R Vector of Dimensionless heat capacities. (length m_kk).
h_RT Vector of Dimensionless enthalpies. (length m_kk).
s_R Vector of Dimensionless entropies. (length m_kk).
Implements SpeciesThermoInterpType.
Definition at line 177 of file NasaPoly1.h.
References NasaPoly1::updateProperties(), and NasaPoly1::updateTemperaturePoly().
Referenced by NasaPoly2::updatePropertiesTemp(), and NasaPoly2::validate().
virtual void reportParameters (size_t & index, int & type, doublereal & minTemp, doublereal & maxTemp, doublereal & refPressure, doublereal *const coeffs) const inline virtual
This utility function reports back the type of parameterization and all of the parameters for the species, index.
All parameters are output variables
Parameters
index Species index
type Integer type of the standard type
minTemp output - Minimum temperature
maxTemp output - Maximum temperature
refPressure output - reference pressure (Pa).
coeffs Vector of coefficients used to set the parameters for the standard state.
Implements SpeciesThermoInterpType.
Definition at line 185 of file NasaPoly1.h.
References NasaPoly1::m_coeff, SpeciesThermoInterpType::m_highT, SpeciesThermoInterpType::m_index, SpeciesThermoInterpType::m_lowT, SpeciesThermoInterpType::m_Pref, and NASA1.
Referenced by NasaThermo::reportParams().
virtual void modifyParameters (doublereal * coeffs) inline virtual
Modify parameters for the standard state.
Parameters
coeffs Vector of coefficients used to set the parameters for the standard state.
Reimplemented from SpeciesThermoInterpType.
Definition at line 202 of file NasaPoly1.h.
References NasaPoly1::m_coeff.
virtual doublereal reportHf298 (doublereal *const h298 = 0) const inline virtual
Report the 298 K Heat of Formation of the standard state of one species (J kmol-1)
The 298K Heat of Formation is defined as the enthalpy change to create the standard state of the species from its constituent elements in their standard states at 298 K and 1 bar.
Parameters
h298 If this is nonnull, the current value of the Heat of Formation at 298K and 1 bar for species m_speciesIndex is returned in h298[m_speciesIndex].
Returns
Returns the current value of the Heat of Formation at 298K and 1 bar for species m_speciesIndex.
Reimplemented from SpeciesThermoInterpType.
Definition at line 206 of file NasaPoly1.h.
References Cantera::GasConstant, NasaPoly1::m_coeff, SpeciesThermoInterpType::m_index, and NasaPoly1::updateTemperaturePoly().
Referenced by NasaThermo::modifyOneHf298(), NasaPoly2::modifyOneHf298(), NasaPoly1::modifyOneHf298(), NasaPoly2::reportHf298(), and NasaThermo::reportOneHf298().
virtual void modifyOneHf298 (const size_t k, const doublereal Hf298New) inline virtual
Modify the value of the 298 K Heat of Formation of one species in the phase (J kmol-1)
The 298K heat of formation is defined as the enthalpy change to create the standard state of the species from its constituent elements in their standard states at 298 K and 1 bar.
Parameters
k Species k
Hf298New Specify the new value of the Heat of Formation at 298K and 1 bar
Reimplemented from SpeciesThermoInterpType.
Definition at line 226 of file NasaPoly1.h.
References Cantera::GasConstant, NasaPoly1::m_coeff, SpeciesThermoInterpType::m_index, and NasaPoly1::reportHf298().
Referenced by NasaThermo::modifyOneHf298(), and NasaPoly2::modifyOneHf298().
Member Data Documentation
vector_fp m_coeff protected
array of polynomial coefficients, stored in the order [a0, ..., a6]
Definition at line 237 of file NasaPoly1.h.
Referenced by NasaPoly1::modifyOneHf298(), NasaPoly1::modifyParameters(), NasaPoly1::NasaPoly1(), NasaPoly1::operator=(), NasaPoly1::reportHf298(), NasaPoly1::reportParameters(), and NasaPoly1::updateProperties().
The documentation for this class was generated from the following file:
NasaPoly1.h