Cantera: CVodeInt Class Reference
CVodeInt Class Reference
Wrapper class for 'CVODE' integrator from LLNL.
#include <CVodeInt.h>
Public Member Functions
CVodeInt ()
virtual void setTolerances (double reltol, size_t n, double *abstol)
Set or reset the number of equations.
virtual void setTolerances (double reltol, double abstol)
Set error tolerances.
virtual void setProblemType (int probtype)
Set the problem type.
virtual void initialize (double t0, FuncEval &func)
Initialize the integrator for a new problem.
virtual void reinitialize (double t0, FuncEval &func)
virtual void integrate (double tout)
Integrate the system of equations.
virtual doublereal step (double tout)
Integrate the system of equations.
virtual double & solution (size_t k)
The current value of the solution of equation k.
virtual double * solution ()
The current value of the solution of the system of equations.
virtual int nEquations () const
The number of equations.
virtual int nEvals () const
The number of function evaluations.
virtual void setMaxOrder (int n)
Set the maximum integration order that will be used.
virtual void setMethod (MethodType t)
Set the solution method.
virtual void setIterator (IterType t)
Set the linear iterator.
virtual void setMaxStepSize (double hmax)
Set the maximum step size.
virtual void setMinStepSize (double hmin)
Set the minimum step size.
virtual void setMaxSteps (int nmax)
virtual void setMaxErrTestFails (int nmax)
Set the maximum permissible number of error test failures.
Public Member Functions inherited from Integrator
Integrator ()
Default Constructor.
virtual ~Integrator ()
Destructor.
virtual void setSensitivityTolerances (doublereal reltol, doublereal abstol)
Set the sensitivity error tolerances.
virtual void setBandwidth (int N_Upper, int N_Lower)
virtual int nSensParams ()
virtual double sensitivity (size_t k, size_t p)
Private Attributes
int m_neq
void * m_cvode_mem
double m_t0
N_Vector m_y
N_Vector m_abstol
int m_type
int m_itol
int m_method
int m_iter
int m_maxord
double m_reltol
double m_abstols
int m_nabs
double m_hmax
double m_hmin
int m_maxsteps
vector_fp m_ropt
long int * m_iopt
void * m_data
Detailed Description
Wrapper class for 'CVODE' integrator from LLNL.
The unmodified CVODE code is in directory ext/cvode.
See Also
FuncEval.h. Classes that use CVodeInt: ImplicitChem, ImplicitSurfChem, Reactor
Definition at line 34 of file CVodeInt.h.
Constructor & Destructor Documentation
CVodeInt ()
Constructor. Default settings: dense Jacobian, no user-supplied Jacobian function, Newton iteration.
Definition at line 79 of file CVodeInt.cpp.
Member Function Documentation
void setTolerances (double reltol, size_t n, double * abstol) virtual
Set or reset the number of equations.
Set error tolerances.
Parameters
reltol scalar relative tolerance
n Number of equations
abstol array of N absolute tolerance values
Reimplemented from Integrator.
Definition at line 123 of file CVodeInt.cpp.
void setTolerances (double reltol, double abstol) virtual
Set error tolerances.
Parameters
reltol scalar relative tolerance
abstol scalar absolute tolerance
Reimplemented from Integrator.
Definition at line 139 of file CVodeInt.cpp.
void setProblemType (int probtype) virtual
Set the problem type.
Parameters
probtype Type of the problem
Reimplemented from Integrator.
Definition at line 146 of file CVodeInt.cpp.
void initialize (double t0, FuncEval & func) virtual
Initialize the integrator for a new problem.
Call after all options have been set.
Parameters
t0 initial time
func RHS evaluator object for system of equations.
Reimplemented from Integrator.
Definition at line 191 of file CVodeInt.cpp.
References cvode_jac(), cvode_rhs(), DATA_PTR, FuncEval::getInitialConditions(), and FuncEval::neq().
void integrate (double tout) virtual
Integrate the system of equations.
Parameters
tout Integrate to this time. Note that this is the absolute time value, not a time interval.
Reimplemented from Integrator.
Definition at line 291 of file CVodeInt.cpp.
References Cantera::int2str().
double step (double tout) virtual
Integrate the system of equations.
Parameters
tout integrate to this time. Note that this is the absolute time value, not a time interval.
Reimplemented from Integrator.
Definition at line 301 of file CVodeInt.cpp.
References Cantera::int2str().
double & solution (size_t k) virtual
The current value of the solution of equation k.
Reimplemented from Integrator.
Definition at line 114 of file CVodeInt.cpp.
double * solution () virtual
The current value of the solution of the system of equations.
Reimplemented from Integrator.
Definition at line 118 of file CVodeInt.cpp.
virtual int nEquations () const inline virtual
The number of equations.
Reimplemented from Integrator.
Definition at line 52 of file CVodeInt.h.
int nEvals () const virtual
The number of function evaluations.
Reimplemented from Integrator.
Definition at line 312 of file CVodeInt.cpp.
virtual void setMaxOrder (int n) inline virtual
Set the maximum integration order that will be used.
Reimplemented from Integrator.
Definition at line 56 of file CVodeInt.h.
void setMethod (MethodType t) virtual
Set the solution method.
Reimplemented from Integrator.
Definition at line 151 of file CVodeInt.cpp.
References Cantera::Adams_Method, and Cantera::BDF_Method.
void setIterator (IterType t) virtual
Set the linear iterator.
Reimplemented from Integrator.
Definition at line 180 of file CVodeInt.cpp.
References Cantera::Functional_Iter, and Cantera::Newton_Iter.
void setMaxStepSize (double hmax) virtual
Set the maximum step size.
Reimplemented from Integrator.
Definition at line 162 of file CVodeInt.cpp.
void setMinStepSize (double hmin) virtual
Set the minimum step size.
Reimplemented from Integrator.
Definition at line 168 of file CVodeInt.cpp.
virtual void setMaxErrTestFails (int n) inline virtual
Set the maximum permissible number of error test failures.
Reimplemented from Integrator.
Definition at line 64 of file CVodeInt.h.
The documentation for this class was generated from the following files:
CVodeInt.h
CVodeInt.cpp