Cantera: PDSS_Water Class Reference
PDSS_Water Class Reference
Species Standard-State Thermodynamic Properties
Class for the liquid water pressure dependent standard state.
#include <PDSS_Water.h>
Public Member Functions
Constructors
PDSS_Water ()
Bare constructor.
PDSS_Water (VPStandardStateTP *tp, int spindex)
Constructor that initializes the object by examining the XML entries from the ThermoPhase object.
PDSS_Water (const PDSS_Water &b)
Copy Constructor.
PDSS_Water & operator= (const PDSS_Water &b)
Assignment operator.
PDSS_Water (VPStandardStateTP *tp, int spindex, const std::string &inputFile, const std::string &id="")
Constructor that initializes the object by examining the input file of the variable pressure ThermoPhase object.
PDSS_Water (VPStandardStateTP *tp, int spindex, const XML_Node &speciesNode, const XML_Node &phaseRef, bool spInstalled)
Constructor that initializes the object by examining the input file of the variable pressure ThermoPhase object.
virtual PDSS * duplMyselfAsPDSS () const
Duplication routine for objects which inherit from PDSS.
Molar Thermodynamic Properties of the Species Standard State in the Solution
virtual doublereal enthalpy_mole () const
Return the molar enthalpy in units of J kmol-1.
virtual doublereal intEnergy_mole () const
Return the molar internal Energy in units of J kmol-1.
virtual doublereal entropy_mole () const
Return the molar entropy in units of J kmol-1 K-1.
virtual doublereal gibbs_mole () const
Return the molar Gibbs free energy in units of J kmol-1.
virtual doublereal cp_mole () const
Return the molar const pressure heat capacity in units of J kmol-1 K-1.
virtual doublereal cv_mole () const
Return the molar const volume heat capacity in units of J kmol-1 K-1.
virtual doublereal molarVolume () const
Return the molar volume at standard state.
virtual doublereal density () const
Return the standard state density at standard state.
Properties of the Reference State of the Species in the Solution
doublereal pref_safe (doublereal temp) const
Returns a reference pressure value that can be safely calculated by the underlying real equation of state for water.
virtual doublereal gibbs_RT_ref () const
Return the molar Gibbs free energy divided by RT at reference pressure.
virtual doublereal enthalpy_RT_ref () const
Return the molar enthalpy divided by RT at reference pressure.
virtual doublereal entropy_R_ref () const
Return the molar entropy divided by R at reference pressure.
virtual doublereal cp_R_ref () const
Return the molar heat capacity divided by R at reference pressure.
virtual doublereal molarVolume_ref () const
Return the molar volume at reference pressure.
Mechanical Equation of State Properties
virtual doublereal pressure () const
Returns the pressure (Pa)
virtual void setPressure (doublereal pres)
Sets the pressure in the object.
virtual void setTemperature (doublereal temp)
Set the internal temperature.
virtual void setState_TP (doublereal temp, doublereal pres)
Set the internal temperature and pressure.
virtual void setState_TR (doublereal temp, doublereal rho)
Set the internal temperature and density.
void setDensity (doublereal dens)
Set the density of the water phase.
virtual doublereal thermalExpansionCoeff () const
Return the volumetric thermal expansion coefficient. Units: 1/K.
virtual doublereal dthermalExpansionCoeffdT () const
Return the derivative of the volumetric thermal expansion coefficient. Units: 1/K2.
virtual doublereal isothermalCompressibility () const
Returns the isothermal compressibility. Units: 1/Pa.
Miscellaneous properties of the standard state
virtual doublereal critTemperature () const
critical temperature
virtual doublereal critPressure () const
critical pressure
virtual doublereal critDensity () const
critical density
virtual doublereal satPressure (doublereal t)
saturation pressure
WaterPropsIAPWS * getWater ()
Get a pointer to a changeable WaterPropsIAPWS object.
WaterProps * getWaterProps ()
Get a pointer to a changeable WaterPropsIAPWS object.
Initialization of the Object
void constructSet ()
Internal routine that initializes the underlying water model.
void constructPDSSFile (VPStandardStateTP *vptp_ptr, int spindex, const std::string &inputFile, const std::string &id)
Initialization of a PDSS object using an input XML file.
void constructPDSSXML (VPStandardStateTP *vptp_ptr, int spindex, const XML_Node &phaseNode, const std::string &id)
Initialization of a PDSS object using an XML tree.
Public Member Functions inherited from PDSS_Molar
virtual doublereal enthalpy_RT () const
Return the standard state molar enthalpy divided by RT.
virtual doublereal entropy_R () const
Return the standard state entropy divided by RT.
virtual doublereal gibbs_RT () const
Return the molar Gibbs free energy divided by RT.
virtual doublereal cp_R () const
Return the molar const pressure heat capacity divided by RT.
Public Member Functions inherited from PDSS
PDSS ()
Empty Constructor.
PDSS (VPStandardStateTP *tp, size_t spindex)
Constructor that initializes the object by examining the XML entries from the ThermoPhase object.
PDSS (const PDSS &b)
Copy Constructor.
PDSS & operator= (const PDSS &b)
Assignment operator.
virtual ~PDSS ()
Destructor for the phase.
PDSS_enumType reportPDSSType () const
Returns the type of the standard state parameterization.
virtual doublereal enthalpyDelp_mole () const
Get the difference in the standard state enthalpy between the current pressure and the reference pressure, p0.
virtual doublereal entropyDelp_mole () const
Get the difference in the standard state entropy between the current pressure and the reference pressure, p0.
virtual doublereal gibbsDelp_mole () const
Get the difference in the standard state Gibbs free energy between the current pressure and the reference pressure, p0.
virtual doublereal cpDelp_mole () const
Get the difference in standard state heat capacity between the current pressure and the reference pressure, p0.
doublereal refPressure () const
Return the reference pressure for this phase.
doublereal minTemp () const
return the minimum temperature
doublereal maxTemp () const
return the minimum temperature
virtual doublereal temperature () const
Return the current stored temperature.
doublereal molecularWeight () const
Return the molecular weight of the species in units of kg kmol-1.
void setMolecularWeight (doublereal mw)
Set the molecular weight of the species.
virtual void initThermo ()
Initialization routine for all of the shallow pointers.
virtual void initThermoXML (const XML_Node &phaseNode, const std::string &id)
Initialization routine for the PDSS object based on the phaseNode.
virtual void reportParams (size_t &kindex, int &type, doublereal *const c, doublereal &minTemp, doublereal &maxTemp, doublereal &refPressure) const
This utility function reports back the type of parameterization and all of the parameters for the species, index.
virtual void initAllPtrs (VPStandardStateTP *vptp_ptr, VPSSMgr *vpssmgr_ptr, SpeciesThermo *spthermo_ptr)
Initialize or Reinitialize all shallow pointers in the object.
Public Attributes
bool m_allowGasPhase
Since this phase represents a liquid phase, it's an error to return a gas-phase answer.
Private Attributes
WaterPropsIAPWS m_sub
Pointer to the WaterPropsIAPWS object, which does the actual calculations for the real equation of state.
WaterProps m_waterProps
Pointer to the WaterProps object.
doublereal m_dens
State of the system - density.
int m_iState
state of the fluid
doublereal EW_Offset
Offset constants used to obtain consistency with the NIST database.
doublereal SW_Offset
Offset constant used to obtain consistency with NIST convention.
bool m_verbose
Verbose flag - used?
Additional Inherited Members
Protected Attributes inherited from PDSS
PDSS_enumType m_pdssType
Enumerated type describing the type of the PDSS object.
doublereal m_temp
Current temperature used by the PDSS object.
doublereal m_pres
State of the system - pressure.
doublereal m_p0
Reference state pressure of the species.
doublereal m_minTemp
Minimum temperature.
doublereal m_maxTemp
Maximum temperature.
VPStandardStateTP * m_tp
ThermoPhase which this species belongs to.
VPSSMgr * m_vpssmgr_ptr
Pointer to the VPSS manager for this object.
doublereal m_mw
Molecular Weight of the species.
size_t m_spindex
Species index in the ThermoPhase corresponding to this species.
SpeciesThermo * m_spthermo
Pointer to the species thermodynamic property manager.
doublereal * m_h0_RT_ptr
Reference state enthalpy divided by RT.
doublereal * m_cp0_R_ptr
Reference state heat capacity divided by R.
doublereal * m_s0_R_ptr
Reference state entropy divided by R.
doublereal * m_g0_RT_ptr
Reference state Gibbs free energy divided by RT.
doublereal * m_V0_ptr
Reference state molar volume (m3 kg-1)
doublereal * m_hss_RT_ptr
Standard state enthalpy divided by RT.
doublereal * m_cpss_R_ptr
Standard state heat capacity divided by R.
doublereal * m_sss_R_ptr
Standard state entropy divided by R.
doublereal * m_gss_RT_ptr
Standard state Gibbs free energy divided by RT.
doublereal * m_Vss_ptr
Standard State molar volume (m3 kg-1)
Detailed Description
Class for the liquid water pressure dependent standard state.
Notes: Base state for thermodynamic properties:
The thermodynamic base state for water is set to the NIST basis here by specifying constants EW_Offset and SW_Offset. These offsets are specified so that the following properties hold:
Delta_Hfo_gas(298.15) = -241.826 kJ/gmol So_gas(298.15, 1bar) = 188.835 J/gmolK
(http://webbook.nist.gov)
The "o" here refers to a hypothetical ideal gas state. The way we achieve this in practice is to evaluate at a very low pressure and then use the theoretical ideal gas results to scale up to higher pressures:
Ho(1bar) = H(P0)
So(1bar) = S(P0) + RT ln(1bar/P0)
The offsets used in the steam tables are different than NIST's. They assume u_liq(TP) = 0.0, s_liq(TP) = 0.0, where TP is the triple point conditions.
Definition at line 51 of file PDSS_Water.h.
Constructor & Destructor Documentation
PDSS_Water ()
Bare constructor.
eliminate?
Definition at line 19 of file PDSS_Water.cpp.
References PDSS_Water::constructSet(), PDSS::m_maxTemp, PDSS::m_minTemp, PDSS::m_pdssType, and PDSS::m_spthermo.
Referenced by PDSS_Water::duplMyselfAsPDSS().
PDSS_Water (VPStandardStateTP * tp, int spindex)
Constructor that initializes the object by examining the XML entries from the ThermoPhase object.
This function calls the constructPDSS member function.
Parameters
tp Pointer to the ThermoPhase object pertaining to the phase
spindex Species index of the species in the phase
Definition at line 35 of file PDSS_Water.cpp.
References PDSS_Water::constructSet(), PDSS::m_maxTemp, PDSS::m_minTemp, PDSS::m_pdssType, and PDSS::m_spthermo.
PDSS_Water (const PDSS_Water & b)
Copy Constructor.
Parameters
b object to be copied
Definition at line 91 of file PDSS_Water.cpp.
PDSS_Water (VPStandardStateTP * tp, int spindex, const std::string & inputFile, const std::string & id = "")
Constructor that initializes the object by examining the input file of the variable pressure ThermoPhase object.
This function calls the constructPDSSFile member function.
Parameters
tp Pointer to the variable pressure ThermoPhase object pertaining to the phase
spindex Species index of the species in the phase
inputFile String name of the input file
id String name of the phase in the input file. The default is the empty string, in which case the first phase in the file is used.
Definition at line 52 of file PDSS_Water.cpp.
References PDSS_Water::constructPDSSFile(), PDSS::m_maxTemp, PDSS::m_minTemp, PDSS::m_pdssType, and PDSS::m_spthermo.
PDSS_Water (VPStandardStateTP * tp, int spindex, const XML_Node & speciesNode, const XML_Node & phaseRef, bool spInstalled)
Constructor that initializes the object by examining the input file of the variable pressure ThermoPhase object.
This function calls the constructPDSSXML member function.
Parameters
tp Pointer to the ThermoPhase object pertaining to the phase
spindex Species index of the species in the phase
speciesNode Reference to the species XML tree.
phaseRef Reference to the XML tree containing the phase information.
spInstalled Is the species already installed.
Definition at line 70 of file PDSS_Water.cpp.
References PDSS_Water::constructPDSSXML(), PDSS::initThermo(), PDSS::m_maxTemp, PDSS::m_minTemp, PDSS::m_pdssType, and PDSS::m_spthermo.
Member Function Documentation
PDSS_Water & operator= (const PDSS_Water & b)
Assignment operator.
Parameters
b Object to be copied
Definition at line 108 of file PDSS_Water.cpp.
References PDSS_Water::EW_Offset, PDSS_Water::m_allowGasPhase, PDSS_Water::m_dens, PDSS_Water::m_iState, PDSS_Water::m_sub, PDSS_Water::m_verbose, PDSS_Water::m_waterProps, PDSS::operator=(), and PDSS_Water::SW_Offset.
PDSS * duplMyselfAsPDSS () const virtual
Duplication routine for objects which inherit from PDSS.
This virtual routine can be used to duplicate PDSS objects inherited from PDSS even if the application only has a pointer to PDSS to work with.
Returns
returns a pointer to the base PDSS object type
Reimplemented from PDSS.
Definition at line 130 of file PDSS_Water.cpp.
References PDSS_Water::PDSS_Water().
doublereal enthalpy_mole () const virtual
Return the molar enthalpy in units of J kmol-1.
Returns
the species standard state enthalpy in J kmol-1 at the current temperature and pressure.
Reimplemented from PDSS.
Definition at line 214 of file PDSS_Water.cpp.
References WaterPropsIAPWS::enthalpy(), PDSS_Water::EW_Offset, and PDSS_Water::m_sub.
Referenced by VPSSMgr_Water_ConstVol::_updateRefStateThermo(), VPSSMgr_Water_HKFT::_updateRefStateThermo(), VPSSMgr_Water_ConstVol::_updateStandardStateThermo(), VPSSMgr_Water_HKFT::_updateStandardStateThermo(), PDSS_Water::constructSet(), and VPSSMgr_Water_ConstVol::getEnthalpy_RT_ref().
doublereal intEnergy_mole () const virtual
Return the molar internal Energy in units of J kmol-1.
Returns
The species standard state internal Energy in J kmol-1 at the current temperature and pressure.
Reimplemented from PDSS.
Definition at line 219 of file PDSS_Water.cpp.
References PDSS_Water::EW_Offset, WaterPropsIAPWS::intEnergy(), and PDSS_Water::m_sub.
doublereal entropy_mole () const virtual
Return the molar entropy in units of J kmol-1 K-1.
Returns
The species standard state entropy in J kmol-1 K-1 at the current temperature and pressure.
Reimplemented from PDSS.
Definition at line 224 of file PDSS_Water.cpp.
References WaterPropsIAPWS::entropy(), PDSS_Water::m_sub, and PDSS_Water::SW_Offset.
Referenced by VPSSMgr_Water_ConstVol::_updateRefStateThermo(), VPSSMgr_Water_HKFT::_updateRefStateThermo(), VPSSMgr_Water_ConstVol::_updateStandardStateThermo(), VPSSMgr_Water_HKFT::_updateStandardStateThermo(), PDSS_Water::constructSet(), and VPSSMgr_Water_ConstVol::getEntropy_R_ref().
doublereal gibbs_mole () const virtual
Return the molar Gibbs free energy in units of J kmol-1.
Returns
The species standard state Gibbs free energy in J kmol-1 at the current temperature and pressure.
Reimplemented from PDSS.
Definition at line 229 of file PDSS_Water.cpp.
References PDSS_Water::EW_Offset, WaterPropsIAPWS::Gibbs(), PDSS_Water::m_sub, PDSS::m_temp, and PDSS_Water::SW_Offset.
Referenced by VPSSMgr_Water_ConstVol::getGibbs_RT_ref().
doublereal cp_mole () const virtual
Return the molar const pressure heat capacity in units of J kmol-1 K-1.
Returns
The species standard state Cp in J kmol-1 K-1 at the current temperature and pressure.
Reimplemented from PDSS.
Definition at line 234 of file PDSS_Water.cpp.
References WaterPropsIAPWS::cp(), and PDSS_Water::m_sub.
Referenced by VPSSMgr_Water_ConstVol::_updateRefStateThermo(), VPSSMgr_Water_HKFT::_updateRefStateThermo(), VPSSMgr_Water_ConstVol::_updateStandardStateThermo(), VPSSMgr_Water_HKFT::_updateStandardStateThermo(), and VPSSMgr_Water_ConstVol::getCp_R_ref().
doublereal cv_mole () const virtual
Return the molar const volume heat capacity in units of J kmol-1 K-1.
Returns
The species standard state Cv in J kmol-1 K-1 at the current temperature and pressure.
Reimplemented from PDSS.
Definition at line 239 of file PDSS_Water.cpp.
References WaterPropsIAPWS::cv(), and PDSS_Water::m_sub.
doublereal molarVolume () const virtual
Return the molar volume at standard state.
Returns
The standard state molar volume at the current temperature and pressure. Units are m**3 kmol-1.
Reimplemented from PDSS.
Definition at line 244 of file PDSS_Water.cpp.
References PDSS_Water::m_sub, and WaterPropsIAPWS::molarVolume().
doublereal density () const virtual
Return the standard state density at standard state.
Returns
The standard state density at the current temperature and pressure. units are kg m-3
Reimplemented from PDSS.
Definition at line 378 of file PDSS_Water.cpp.
References PDSS_Water::m_dens.
Referenced by VPSSMgr_Water_ConstVol::_updateRefStateThermo(), VPSSMgr_Water_HKFT::_updateRefStateThermo(), VPSSMgr_Water_ConstVol::_updateStandardStateThermo(), VPSSMgr_Water_HKFT::_updateStandardStateThermo(), DebyeHuckel::calcDensity(), PDSS_HKFT::g(), VPSSMgr_Water_ConstVol::getStandardVolumes_ref(), PDSS_HKFT::initThermo(), VPSSMgr_Water_ConstVol::initThermoXML(), VPSSMgr_Water_HKFT::initThermoXML(), and DebyeHuckel::initThermoXML().
doublereal pref_safe (doublereal temp) const
Returns a reference pressure value that can be safely calculated by the underlying real equation of state for water.
Note, this function is needed because trying to calculate a one atm value around the critical point will cause a crash
Parameters
temp Temperature (Kelvin)
Definition at line 402 of file PDSS_Water.cpp.
References PDSS_Water::m_sub, Cantera::OneAtm, WaterPropsIAPWS::Pcrit(), WaterPropsIAPWS::psat_est(), and WaterPropsIAPWS::Tcrit().
Referenced by VPSSMgr_Water_ConstVol::_updateRefStateThermo(), VPSSMgr_Water_HKFT::_updateRefStateThermo(), PDSS_HKFT::cp_R_ref(), PDSS_HKFT::enthalpy_RT_ref(), PDSS_HKFT::entropy_R_ref(), VPSSMgr_Water_ConstVol::getCp_R_ref(), VPSSMgr_Water_ConstVol::getEnthalpy_RT_ref(), VPSSMgr_Water_ConstVol::getEntropy_R_ref(), VPSSMgr_Water_ConstVol::getGibbs_RT_ref(), VPSSMgr_Water_ConstVol::getStandardVolumes_ref(), PDSS_HKFT::gibbs_RT_ref(), and PDSS_HKFT::molarVolume_ref().
doublereal gibbs_RT_ref () const virtual
Return the molar Gibbs free energy divided by RT at reference pressure.
Returns
The reference state Gibbs free energy at the current temperature, divided by RT.
Reimplemented from PDSS.
Definition at line 249 of file PDSS_Water.cpp.
References WaterPropsIAPWS::density(), WaterPropsIAPWS::enthalpy(), PDSS_Water::EW_Offset, Cantera::GasConstant, PDSS_Water::m_dens, PDSS::m_p0, PDSS_Water::m_sub, PDSS::m_temp, WaterPropsIAPWS::setState_TR(), and PDSS_Water::SW_Offset.
doublereal enthalpy_RT_ref () const virtual
Return the molar enthalpy divided by RT at reference pressure.
Returns
The species reference state enthalpy at the current temperature, divided by RT.
Reimplemented from PDSS.
Definition at line 258 of file PDSS_Water.cpp.
References WaterPropsIAPWS::density(), WaterPropsIAPWS::enthalpy(), PDSS_Water::EW_Offset, Cantera::GasConstant, PDSS_Water::m_dens, PDSS::m_p0, PDSS_Water::m_sub, PDSS::m_temp, and WaterPropsIAPWS::setState_TR().
doublereal entropy_R_ref () const virtual
Return the molar entropy divided by R at reference pressure.
Returns
The species reference state entropy at the current temperature, divided by R.
Reimplemented from PDSS.
Definition at line 267 of file PDSS_Water.cpp.
References WaterPropsIAPWS::density(), WaterPropsIAPWS::entropy(), Cantera::GasConstant, PDSS_Water::m_dens, PDSS::m_p0, PDSS_Water::m_sub, PDSS::m_temp, WaterPropsIAPWS::setState_TR(), and PDSS_Water::SW_Offset.
doublereal cp_R_ref () const virtual
Return the molar heat capacity divided by R at reference pressure.
Returns
The species reference state heat capacity divided by R at the current temperature.
Reimplemented from PDSS.
Definition at line 276 of file PDSS_Water.cpp.
References WaterPropsIAPWS::cp(), WaterPropsIAPWS::density(), Cantera::GasConstant, PDSS_Water::m_dens, PDSS::m_p0, PDSS_Water::m_sub, PDSS::m_temp, and WaterPropsIAPWS::setState_TR().
doublereal molarVolume_ref () const virtual
Return the molar volume at reference pressure.
Returns
The reference state molar volume. units are m**3 kmol-1.
Reimplemented from PDSS.
Definition at line 285 of file PDSS_Water.cpp.
References WaterPropsIAPWS::density(), PDSS_Water::m_dens, PDSS::m_p0, PDSS_Water::m_sub, PDSS::m_temp, WaterPropsIAPWS::molarVolume(), and WaterPropsIAPWS::setState_TR().
doublereal pressure () const virtual
Returns the pressure (Pa)
Reimplemented from PDSS.
Definition at line 294 of file PDSS_Water.cpp.
References PDSS::m_pres, PDSS_Water::m_sub, and WaterPropsIAPWS::pressure().
Referenced by PDSS_Water::dthermalExpansionCoeffdT().
void setPressure (doublereal pres) virtual
Sets the pressure in the object.
Currently, this sets the pressure in the PDSS object. It is indeterminant what happens to the owning VPStandardStateTP object and to the VPSSMgr object.
Parameters
pres Pressure to be set (Pascal)
Reimplemented from PDSS.
Definition at line 300 of file PDSS_Water.cpp.
References WaterPropsIAPWS::density(), Cantera::fp2str(), PDSS_Water::m_allowGasPhase, PDSS_Water::m_dens, PDSS_Water::m_iState, PDSS::m_pres, PDSS_Water::m_sub, PDSS::m_temp, WaterPropsIAPWS::phaseState(), and WaterPropsIAPWS::Tcrit().
Referenced by PDSS_Water::setState_TP().
void setTemperature (doublereal temp) virtual
Set the internal temperature.
Parameters
temp Temperature (Kelvin)
Reimplemented from PDSS.
Definition at line 383 of file PDSS_Water.cpp.
References PDSS_Water::m_dens, PDSS_Water::m_sub, PDSS::m_temp, and WaterPropsIAPWS::setState_TR().
Referenced by PDSS_Water::constructSet().
void setState_TP (doublereal temp, doublereal pres) virtual
Set the internal temperature and pressure.
Parameters
temp Temperature (Kelvin)
pres pressure (Pascals)
Reimplemented from PDSS.
Definition at line 389 of file PDSS_Water.cpp.
References PDSS::m_temp, and PDSS_Water::setPressure().
Referenced by VPSSMgr_Water_ConstVol::_updateRefStateThermo(), VPSSMgr_Water_HKFT::_updateRefStateThermo(), VPSSMgr_Water_ConstVol::_updateStandardStateThermo(), VPSSMgr_Water_HKFT::_updateStandardStateThermo(), PDSS_HKFT::g(), VPSSMgr_Water_ConstVol::getCp_R_ref(), VPSSMgr_Water_ConstVol::getEnthalpy_RT_ref(), VPSSMgr_Water_ConstVol::getEntropy_R_ref(), VPSSMgr_Water_ConstVol::getGibbs_RT_ref(), VPSSMgr_Water_ConstVol::getStandardVolumes_ref(), PDSS_HKFT::initThermo(), VPSSMgr_Water_ConstVol::initThermoXML(), VPSSMgr_Water_HKFT::initThermoXML(), and DebyeHuckel::initThermoXML().
void setState_TR (doublereal temp, doublereal rho) virtual
Set the internal temperature and density.
Parameters
temp Temperature (Kelvin)
rho Density (kg m-3)
Reimplemented from PDSS.
Definition at line 395 of file PDSS_Water.cpp.
References PDSS_Water::m_dens, PDSS_Water::m_sub, PDSS::m_temp, and WaterPropsIAPWS::setState_TR().
void setDensity (doublereal dens)
Set the density of the water phase.
This is a non-virtual function because it specific to this object.
Parameters
dens Density of the water (kg/m3)
Definition at line 372 of file PDSS_Water.cpp.
References PDSS_Water::m_dens, PDSS_Water::m_sub, PDSS::m_temp, and WaterPropsIAPWS::setState_TR().
doublereal thermalExpansionCoeff () const virtual
Return the volumetric thermal expansion coefficient. Units: 1/K.
The thermal expansion coefficient is defined as
\[ \beta = \frac{1}{v}\left(\frac{\partial v}{\partial T}\right)_P \]
Reimplemented from PDSS.
Definition at line 331 of file PDSS_Water.cpp.
References WaterPropsIAPWS::coeffThermExp(), and PDSS_Water::m_sub.
Referenced by PDSS_HKFT::g().
doublereal dthermalExpansionCoeffdT () const virtual
Return the derivative of the volumetric thermal expansion coefficient. Units: 1/K2.
The thermal expansion coefficient is defined as
\[ \beta = \frac{1}{v}\left(\frac{\partial v}{\partial T}\right)_P \]
Definition at line 336 of file PDSS_Water.cpp.
References WaterPropsIAPWS::coeffThermExp(), WaterPropsIAPWS::density(), Cantera::fp2str(), PDSS_Water::m_dens, PDSS_Water::m_iState, PDSS_Water::m_sub, PDSS::m_temp, PDSS_Water::pressure(), and WaterPropsIAPWS::setState_TR().
Referenced by PDSS_HKFT::g().
doublereal isothermalCompressibility () const virtual
Returns the isothermal compressibility. Units: 1/Pa.
The isothermal compressibility is defined as
\[ \kappa_T = -\frac{1}{v}\left(\frac{\partial v}{\partial P}\right)_T \]
or
\[ \kappa_T = \frac{1}{\rho}\left(\frac{\partial \rho}{\partial P}\right)_T \]
Definition at line 352 of file PDSS_Water.cpp.
References WaterPropsIAPWS::isothermalCompressibility(), and PDSS_Water::m_sub.
Referenced by PDSS_HKFT::g().
doublereal critTemperature () const virtual
critical temperature
Reimplemented from PDSS.
Definition at line 357 of file PDSS_Water.cpp.
References PDSS_Water::m_sub, and WaterPropsIAPWS::Tcrit().
doublereal critPressure () const virtual
critical pressure
Reimplemented from PDSS.
Definition at line 362 of file PDSS_Water.cpp.
References PDSS_Water::m_sub, and WaterPropsIAPWS::Pcrit().
doublereal critDensity () const virtual
critical density
Reimplemented from PDSS.
Definition at line 367 of file PDSS_Water.cpp.
References PDSS_Water::m_sub, and WaterPropsIAPWS::Rhocrit().
doublereal satPressure (doublereal T) virtual
saturation pressure
Parameters
T Temperature (Kelvin)
Reimplemented from PDSS.
Definition at line 415 of file PDSS_Water.cpp.
References WaterPropsIAPWS::density(), PDSS_Water::m_dens, PDSS_Water::m_sub, PDSS::m_temp, and WaterPropsIAPWS::psat().
WaterPropsIAPWS* getWater () inline
Get a pointer to a changeable WaterPropsIAPWS object.
Definition at line 212 of file PDSS_Water.h.
References PDSS_Water::m_sub.
Referenced by WaterTransport::initTP(), and WaterProps::WaterProps().
WaterProps* getWaterProps () inline
Get a pointer to a changeable WaterPropsIAPWS object.
Definition at line 217 of file PDSS_Water.h.
References PDSS_Water::m_waterProps.
Referenced by WaterTransport::initTP().
void constructSet ()
Internal routine that initializes the underlying water model.
Definition at line 170 of file PDSS_Water.cpp.
References WaterPropsIAPWS::density(), PDSS_Water::enthalpy_mole(), PDSS_Water::entropy_mole(), PDSS_Water::EW_Offset, Cantera::GasConstant, PDSS_Water::m_dens, PDSS::m_mw, PDSS::m_p0, PDSS::m_pres, PDSS_Water::m_sub, Cantera::OneAtm, PDSS_Water::setTemperature(), and PDSS_Water::SW_Offset.
Referenced by PDSS_Water::constructPDSSXML(), and PDSS_Water::PDSS_Water().
void constructPDSSFile (VPStandardStateTP * vptp_ptr, int spindex, const std::string & inputFile, const std::string & id)
Initialization of a PDSS object using an input XML file.
This routine is a precursor to constructPDSSXML(XML_Node*) routine, which does most of the work.
Parameters
vptp_ptr Pointer to the Variable pressure ThermoPhase object This object must have already been malloced.
spindex Species index within the phase
inputFile XML file containing the description of the phase
id Optional parameter identifying the name of the phase. If none is given, the first XML phase element will be used.
Definition at line 141 of file PDSS_Water.cpp.
References XML_Node::build(), PDSS_Water::constructPDSSXML(), Cantera::findInputFile(), and Cantera::findXMLPhase().
Referenced by PDSS_Water::PDSS_Water().
void constructPDSSXML (VPStandardStateTP * vptp_ptr, int spindex, const XML_Node & phaseNode, const std::string & id)
Initialization of a PDSS object using an XML tree.
This routine is a driver for the initialization of the object.
basic logic:
initThermo() (cascade)
getStuff from species Part of XML file
initThermoXML(phaseNode) (cascade)
Parameters
vptp_ptr Pointer to the Variable pressure ThermoPhase object This object must have already been malloced.
spindex Species index within the phase
phaseNode Reference to the phase Information for the phase that owns this species.
id Optional parameter identifying the name of the phase. If none is given, the first XML phase element will be used.
Definition at line 135 of file PDSS_Water.cpp.
References PDSS_Water::constructSet().
Referenced by PDSS_Water::constructPDSSFile(), and PDSS_Water::PDSS_Water().
Member Data Documentation
WaterPropsIAPWS m_sub mutable private
Pointer to the WaterPropsIAPWS object, which does the actual calculations for the real equation of state.
This object owns m_sub
Definition at line 280 of file PDSS_Water.h.
Referenced by PDSS_Water::constructSet(), PDSS_Water::cp_mole(), PDSS_Water::cp_R_ref(), PDSS_Water::critDensity(), PDSS_Water::critPressure(), PDSS_Water::critTemperature(), PDSS_Water::cv_mole(), PDSS_Water::dthermalExpansionCoeffdT(), PDSS_Water::enthalpy_mole(), PDSS_Water::enthalpy_RT_ref(), PDSS_Water::entropy_mole(), PDSS_Water::entropy_R_ref(), PDSS_Water::getWater(), PDSS_Water::gibbs_mole(), PDSS_Water::gibbs_RT_ref(), PDSS_Water::intEnergy_mole(), PDSS_Water::isothermalCompressibility(), PDSS_Water::molarVolume(), PDSS_Water::molarVolume_ref(), PDSS_Water::operator=(), PDSS_Water::pref_safe(), PDSS_Water::pressure(), PDSS_Water::satPressure(), PDSS_Water::setDensity(), PDSS_Water::setPressure(), PDSS_Water::setState_TR(), PDSS_Water::setTemperature(), and PDSS_Water::thermalExpansionCoeff().
WaterProps m_waterProps private
Pointer to the WaterProps object.
This class is used to house several approximation routines for properties of water.
This object owns m_waterProps, and the WaterPropsIAPWS object used by WaterProps is m_sub, which is defined above.
Definition at line 290 of file PDSS_Water.h.
Referenced by PDSS_Water::getWaterProps(), and PDSS_Water::operator=().
doublereal m_dens private
State of the system - density.
Density is the independent variable here, but it's hidden behind the object's interface.
Definition at line 297 of file PDSS_Water.h.
Referenced by PDSS_Water::constructSet(), PDSS_Water::cp_R_ref(), PDSS_Water::density(), PDSS_Water::dthermalExpansionCoeffdT(), PDSS_Water::enthalpy_RT_ref(), PDSS_Water::entropy_R_ref(), PDSS_Water::gibbs_RT_ref(), PDSS_Water::molarVolume_ref(), PDSS_Water::operator=(), PDSS_Water::satPressure(), PDSS_Water::setDensity(), PDSS_Water::setPressure(), PDSS_Water::setState_TR(), and PDSS_Water::setTemperature().
int m_iState private
state of the fluid
0  WATER_GAS
1  WATER_LIQUID
2  WATER_SUPERCRIT
3  WATER_UNSTABLELIQUID
4  WATER_UNSTABLEGAS
Definition at line 309 of file PDSS_Water.h.
Referenced by PDSS_Water::dthermalExpansionCoeffdT(), PDSS_Water::operator=(), and PDSS_Water::setPressure().
doublereal EW_Offset private
Offset constants used to obtain consistency with the NIST database.
This is added to all internal energy and enthalpy results. units = J kmol-1.
Definition at line 316 of file PDSS_Water.h.
Referenced by PDSS_Water::constructSet(), PDSS_Water::enthalpy_mole(), PDSS_Water::enthalpy_RT_ref(), PDSS_Water::gibbs_mole(), PDSS_Water::gibbs_RT_ref(), PDSS_Water::intEnergy_mole(), and PDSS_Water::operator=().
doublereal SW_Offset private
Offset constant used to obtain consistency with NIST convention.
This is added to all internal entropy results. units = J kmol-1 K-1.
Definition at line 323 of file PDSS_Water.h.
Referenced by PDSS_Water::constructSet(), PDSS_Water::entropy_mole(), PDSS_Water::entropy_R_ref(), PDSS_Water::gibbs_mole(), PDSS_Water::gibbs_RT_ref(), and PDSS_Water::operator=().
bool m_verbose private
Verbose flag - used?
Definition at line 326 of file PDSS_Water.h.
Referenced by PDSS_Water::operator=().
bool m_allowGasPhase
Since this phase represents a liquid phase, it's an error to return a gas-phase answer.
However, if the below is true, then a gas-phase answer is allowed. This is used to check the thermodynamic consistency with ideal-gas thermo functions for example.
Definition at line 335 of file PDSS_Water.h.
Referenced by PDSS_Water::operator=(), and PDSS_Water::setPressure().
The documentation for this class was generated from the following files:
PDSS_Water.h
PDSS_Water.cpp