Cantera: C3 Class Reference
C3 Class Reference
Stoichiometry
Handles three species in a reaction.
#include <StoichManager.h>
Public Member Functions
C3 (size_t rxn=0, size_t ic0=0, size_t ic1=0, size_t ic2=0)
size_t data (std::vector< size_t > &ic)
void incrementSpecies (const doublereal *R, doublereal *S) const
void decrementSpecies (const doublereal *R, doublereal *S) const
void multiply (const doublereal *S, doublereal *R) const
void incrementReaction (const doublereal *S, doublereal *R) const
void decrementReaction (const doublereal *S, doublereal *R) const
size_t rxnNumber () const
size_t speciesIndex (size_t n) const
size_t nSpecies ()
void writeMultiply (const std::string &r, std::map< size_t, std::string > &out)
void writeIncrementReaction (const std::string &r, std::map< size_t, std::string > &out)
void writeDecrementReaction (const std::string &r, std::map< size_t, std::string > &out)
void writeIncrementSpecies (const std::string &r, std::map< size_t, std::string > &out)
void writeDecrementSpecies (const std::string &r, std::map< size_t, std::string > &out)
Private Attributes
size_t m_rxn
size_t m_ic0
size_t m_ic1
size_t m_ic2
Detailed Description
Handles three species in a reaction.
See Stoichiometry
Definition at line 318 of file StoichManager.h.
Member Function Documentation
void writeMultiply (const std::string & r, std::map< size_t, std::string > & out) inline
Deprecated:
To be removed after Cantera 2.2
Definition at line 367 of file StoichManager.h.
References Cantera::fmt().
void writeIncrementReaction (const std::string & r, std::map< size_t, std::string > & out) inline
Deprecated:
To be removed after Cantera 2.2
Definition at line 372 of file StoichManager.h.
References Cantera::fmt().
void writeDecrementReaction (const std::string & r, std::map< size_t, std::string > & out) inline
Deprecated:
To be removed after Cantera 2.2
Definition at line 377 of file StoichManager.h.
References Cantera::fmt().
void writeIncrementSpecies (const std::string & r, std::map< size_t, std::string > & out) inline
Deprecated:
To be removed after Cantera 2.2
Definition at line 382 of file StoichManager.h.
References Cantera::fmt().
void writeDecrementSpecies (const std::string & r, std::map< size_t, std::string > & out) inline
Deprecated:
To be removed after Cantera 2.2
Definition at line 390 of file StoichManager.h.
References Cantera::fmt().
The documentation for this class was generated from the following file:
StoichManager.h