Cantera: IdealGasReactor Class Reference
IdealGasReactor Class Reference
Class IdealGasReactor is a class for stirred reactors that is specifically optimized for ideal gases.
#include <IdealGasReactor.h>
Public Member Functions
virtual int type () const
Return a constant indicating the type of this Reactor.
virtual void setThermoMgr (ThermoPhase &thermo)
Specify the mixture contained in the reactor.
virtual void getInitialConditions (doublereal t0, size_t leny, doublereal *y)
Called by ReactorNet to get the initial conditions.
virtual void initialize (doublereal t0=0.0)
Initialize the reactor.
virtual void evalEqs (doublereal t, doublereal *y, doublereal *ydot, doublereal *params)
virtual void updateState (doublereal *y)
Set the state of the reactor to correspond to the state vector y.
virtual size_t componentIndex (const std::string &nm) const
Return the index in the solution vector for this reactor of the component named nm.
Public Member Functions inherited from Reactor
template<class G >
void insert (G &contents)
Insert something into the reactor.
void setKineticsMgr (Kinetics &kin)
void disableChemistry ()
Disable changes in reactor composition due to chemical reactions.
void enableChemistry ()
Enable changes in reactor composition due to chemical reactions.
void setEnergy (int eflag=1)
Set the energy equation on or off.
bool energyEnabled () const
Returns true if solution of the energy equation is enabled.
virtual size_t neq ()
Number of equations (state variables) for this reactor.
virtual void syncState ()
Set the state of the reactor to correspond to the state of the associated ThermoPhase object.
virtual size_t nSensParams ()
Number of sensitivity parameters associated with this reactor (including walls)
virtual void addSensitivityReaction (size_t rxn)
Add a sensitivity parameter associated with the reaction number rxn (in the homogeneous phase).
std::vector< std::pair< void
*, int > > getSensitivityOrder () const
Return a vector specifying the ordering of objects to use when determining sensitivity parameter indices.
Public Member Functions inherited from ReactorBase
ReactorBase (const std::string &name="(none)")
std::string name () const
Return the name of this reactor.
void setName (const std::string &name)
Set the name of this reactor.
void restoreState ()
Set the state of the Phase object associated with this reactor to the reactor's current state.
thermo_t & contents ()
return a reference to the contents.
const thermo_t & contents () const
doublereal residenceTime ()
Return the residence time (s) of the contents of this reactor, based on the outlet mass flow rates and the mass of the reactor contents.
ReactorNet & network ()
The ReactorNet that this reactor belongs to.
void setNetwork (ReactorNet *net)
Set the ReactorNet that this reactor belongs to.
void setInitialVolume (doublereal vol)
Set the initial reactor volume.
void addInlet (FlowDevice &inlet)
Connect an inlet FlowDevice to this reactor.
void addOutlet (FlowDevice &outlet)
Connect an outlet FlowDevice to this reactor.
FlowDevice & inlet (size_t n=0)
Return a reference to the n-th inlet FlowDevice connected to this reactor.
FlowDevice & outlet (size_t n=0)
Return a reference to the n-th outlet FlowDevice connected to this reactor.
size_t nInlets ()
Return the number of inlet FlowDevice objects connected to this reactor.
size_t nOutlets ()
Return the number of outlet FlowDevice objects connected to this reactor.
size_t nWalls ()
Return the number of Wall objects connected to this reactor.
void addWall (Wall &w, int lr)
Insert a Wall between this reactor and another reactor.
Wall & wall (size_t n)
Return a reference to the n-th Wall connected to this reactor.
doublereal volume () const
Returns the current volume (m^3) of the reactor.
doublereal density () const
Returns the current density (kg/m^3) of the reactor's contents.
doublereal temperature () const
Returns the current temperature (K) of the reactor's contents.
doublereal enthalpy_mass () const
Returns the current enthalpy (J/kg) of the reactor's contents.
doublereal intEnergy_mass () const
Returns the current internal energy (J/kg) of the reactor's contents.
doublereal pressure () const
Returns the current pressure (Pa) of the reactor.
doublereal mass () const
Returns the mass (kg) of the reactor's contents.
const doublereal * massFractions () const
Return the vector of species mass fractions.
doublereal massFraction (size_t k) const
Return the mass fraction of the k-th species.
Protected Attributes
vector_fp m_uk
Species molar internal energies.
Protected Attributes inherited from Reactor
Kinetics * m_kin
Pointer to the homogeneous Kinetics object that handles the reactions.
doublereal m_vdot
net rate of volume change from moving walls [m^3/s]
doublereal m_Q
net heat transfer through walls [W]
doublereal m_mass
total mass
vector_fp m_work
vector_fp m_sdot
Production rates of gas phase species on surfaces [kmol/s].
vector_fp m_wdot
Species net molar production rates.
vector_fp m_uk
Species molar internal energies.
bool m_chem
bool m_energy
size_t m_nv
size_t m_nsens
std::vector< size_t > m_pnum
std::vector< size_t > m_nsens_wall
vector_fp m_mult_save
Protected Attributes inherited from ReactorBase
size_t m_nsp
Number of homogeneous species in the mixture.
thermo_t * m_thermo
doublereal m_vol
doublereal m_enthalpy
doublereal m_intEnergy
doublereal m_pressure
vector_fp m_state
std::vector< FlowDevice * > m_inlet
std::vector< FlowDevice * > m_outlet
std::vector< Wall * > m_wall
vector_int m_lr
std::string m_name
ReactorNet * m_net
The ReactorNet that this reactor is part of.
Additional Inherited Members
Protected Member Functions inherited from Reactor
virtual void applySensitivity (double *params)
Set reaction rate multipliers based on the sensitivity variables in params.
virtual void resetSensitivity (double *params)
Reset the reaction rate multipliers.
virtual size_t speciesIndex (const std::string &nm) const
Return the index in the solution vector for this reactor of the species named nm, in either the homogeneous phase or a surface phase, relative to the start of the species terms.
virtual void evalWalls (double t)
Evaluate terms related to Walls Calculates m_vdot and m_Q based on wall movement and heat transfer.
virtual double evalSurfaces (double t, double *ydot)
Evaluate terms related to surface reactions Calculates m_sdot and rate of change in surface species coverages.
virtual void updateSurfaceState (double *y)
Update the state of SurfPhase objects attached to this reactor.
virtual void getSurfaceInitialConditions (double *y)
Get initial conditions for SurfPhase objects attached to this reactor.
Detailed Description
Class IdealGasReactor is a class for stirred reactors that is specifically optimized for ideal gases.
In this formulation, temperature replaces the total internal energy as a state variable.
Definition at line 20 of file IdealGasReactor.h.
Member Function Documentation
virtual int type () const inline virtual
Return a constant indicating the type of this Reactor.
Reimplemented from Reactor.
Definition at line 25 of file IdealGasReactor.h.
void setThermoMgr (ThermoPhase & thermo) virtual
Specify the mixture contained in the reactor.
Note that a pointer to this substance is stored, and as the integration proceeds, the state of the substance is modified.
Reimplemented from ReactorBase.
Definition at line 14 of file IdealGasReactor.cpp.
References Cantera::cIdealGas, and ThermoPhase::eosType().
void getInitialConditions (doublereal t0, size_t leny, doublereal * y) virtual
Called by ReactorNet to get the initial conditions.
Parameters
[in] t0 Time at which initial conditions are determined
[in] leny Length of y (unused)
[out] y state vector representing the initial state of the reactor
Reimplemented from Reactor.
Definition at line 25 of file IdealGasReactor.cpp.
void initialize (doublereal t0 = 0.0) virtual
Initialize the reactor.
Called automatically by ReactorNet::initialize.
Reimplemented from Reactor.
Definition at line 51 of file IdealGasReactor.cpp.
void evalEqs (doublereal t, doublereal * y, doublereal * ydot, doublereal * params) virtual
Evaluate the reactor governing equations. Called by ReactorNet::eval.
Parameters
[in] t time.
[in] y solution vector, length neq()
[out] ydot rate of change of solution vector, length neq()
[in] params sensitivity parameter vector, length ReactorNet::nparams()
Reimplemented from Reactor.
Definition at line 80 of file IdealGasReactor.cpp.
References AssertFinite, and Cantera::int2str().
void updateState (doublereal * y) virtual
Set the state of the reactor to correspond to the state vector y.
Reimplemented from Reactor.
Definition at line 57 of file IdealGasReactor.cpp.
References AssertFinite, and Cantera::int2str().
size_t componentIndex (const std::string & nm) const virtual
Return the index in the solution vector for this reactor of the component named nm.
Possible values for nm are "m", "V", "T", the name of a homogeneous phase species, or the name of a surface species.
Reimplemented from Reactor.
Definition at line 153 of file IdealGasReactor.cpp.
References Cantera::npos.
Member Data Documentation
vector_fp m_uk protected
Species molar internal energies.
Definition at line 44 of file IdealGasReactor.h.
The documentation for this class was generated from the following files:
IdealGasReactor.h
IdealGasReactor.cpp