Cantera: DebyeHuckel Class Reference
DebyeHuckel Class Reference
Thermodynamic Properties
Class DebyeHuckel represents a dilute liquid electrolyte phase which obeys the Debye Huckel formulation for nonideality.
#include <DebyeHuckel.h>
Public Member Functions
DebyeHuckel ()
Default Constructor.
DebyeHuckel (const DebyeHuckel &)
Copy constructor.
DebyeHuckel & operator= (const DebyeHuckel &)
Assignment operator.
DebyeHuckel (const std::string &inputFile, const std::string &id="")
Full constructor for creating the phase.
DebyeHuckel (XML_Node &phaseRef, const std::string &id="")
Full constructor for creating the phase.
virtual ~DebyeHuckel ()
Destructor.
ThermoPhase * duplMyselfAsThermoPhase () const
Duplicator from the ThermoPhase parent class.
virtual void initThermo ()
Initialize the object's internal lengths after species are set.
virtual void initThermoXML (XML_Node &phaseNode, const std::string &id)
Process the XML file after species are set up.
virtual double A_Debye_TP (double temperature=-1.0, double pressure=-1.0) const
Return the Debye Huckel constant as a function of temperature and pressure (Units = sqrt(kg/gmol))
virtual double dA_DebyedT_TP (double temperature=-1.0, double pressure=-1.0) const
Value of the derivative of the Debye Huckel constant with respect to temperature.
virtual double d2A_DebyedT2_TP (double temperature=-1.0, double pressure=-1.0) const
Value of the 2nd derivative of the Debye Huckel constant with respect to temperature as a function of temperature and pressure.
virtual double dA_DebyedP_TP (double temperature=-1.0, double pressure=-1.0) const
Value of the derivative of the Debye Huckel constant with respect to pressure, as a function of temperature and pressure.
double AionicRadius (int k=0) const
Reports the ionic radius of the kth species.
int formDH () const
Returns the form of the Debye-Huckel parameterization used.
Array2D & get_Beta_ij ()
Returns a reference to M_Beta_ij.
Utilities
virtual int eosType () const
Equation of state type flag.
Molar Thermodynamic Properties of the Solution
virtual doublereal enthalpy_mole () const
Molar enthalpy of the solution. Units: J/kmol.
virtual doublereal entropy_mole () const
Molar entropy. Units: J/kmol/K.
virtual doublereal gibbs_mole () const
Molar Gibbs function. Units: J/kmol.
virtual doublereal cp_mole () const
Molar heat capacity at constant pressure. Units: J/kmol/K.
virtual doublereal cv_mole () const
Molar heat capacity at constant volume. Units: J/kmol/K.
Activities, Standard States, and Activity Concentrations
The activity \(a_k\) of a species in solution is related to the chemical potential by
\[ \mu_k = \mu_k^0(T) + \hat R T \log a_k. \]
The quantity \(\mu_k^0(T,P)\) is the chemical potential at unit activity, which depends only on temperature and the pressure.
Activity is assumed to be molality-based here.
virtual void getActivityConcentrations (doublereal *c) const
This method returns an array of generalized concentrations.
virtual doublereal standardConcentration (size_t k=0) const
Return the standard concentration for the kth species.
virtual void getUnitsStandardConc (double *uA, int k=0, int sizeUA=6) const
Returns the units of the standard and generalized concentrations.
virtual void getActivities (doublereal *ac) const
Get the array of non-dimensional activities at the current solution temperature, pressure, and solution concentration.
virtual void getMolalityActivityCoefficients (doublereal *acMolality) const
Get the array of non-dimensional molality-based activity coefficients at the current solution temperature, pressure, and solution concentration.
Partial Molar Properties of the Solution
virtual void getChemPotentials (doublereal *mu) const
Get the species chemical potentials. Units: J/kmol.
virtual void getPartialMolarEnthalpies (doublereal *hbar) const
Returns an array of partial molar enthalpies for the species in the mixture.
virtual void getPartialMolarEntropies (doublereal *sbar) const
Returns an array of partial molar entropies of the species in the solution.
virtual void getPartialMolarCp (doublereal *cpbar) const
Return an array of partial molar heat capacities for the species in the mixture.
virtual void getPartialMolarVolumes (doublereal *vbar) const
Return an array of partial molar volumes for the species in the mixture.
Chemical Equilibrium
virtual void setToEquilState (const doublereal *lambda_RT)
This method is used by the ChemEquil equilibrium solver.
Public Member Functions inherited from MolalityVPSSTP
MolalityVPSSTP ()
Default Constructor.
MolalityVPSSTP (const MolalityVPSSTP &b)
Copy constructor.
MolalityVPSSTP & operator= (const MolalityVPSSTP &b)
Assignment operator.
virtual void setStateFromXML (const XML_Node &state)
Set equation of state parameter values from XML entries.
void setState_TPM (doublereal t, doublereal p, const doublereal *const molalities)
Set the temperature (K), pressure (Pa), and molalities (gmol kg-1) of the solutes.
void setState_TPM (doublereal t, doublereal p, const compositionMap &m)
Set the temperature (K), pressure (Pa), and molalities.
void setState_TPM (doublereal t, doublereal p, const std::string &m)
Set the temperature (K), pressure (Pa), and molalities.
virtual void getdlnActCoeffdlnN (const size_t ld, doublereal *const dlnActCoeffdlnN)
Get the array of derivatives of the log activity coefficients with respect to the log of the species mole numbers.
virtual std::string report (bool show_thermo=true, doublereal threshold=1e-14) const
returns a summary of the state of the phase as a string
void setpHScale (const int pHscaleType)
Set the pH scale, which determines the scale for single-ion activity coefficients.
int pHScale () const
Reports the pH scale, which determines the scale for single-ion activity coefficients.
void setSolvent (size_t k)
This routine sets the index number of the solvent for the phase.
size_t solventIndex () const
Returns the solvent index.
void setMoleFSolventMin (doublereal xmolSolventMIN)
Sets the minimum mole fraction in the molality formulation.
doublereal moleFSolventMin () const
Returns the minimum mole fraction in the molality formulation.
void calcMolalities () const
Calculates the molality of all species and stores the result internally.
void getMolalities (doublereal *const molal) const
This function will return the molalities of the species.
void setMolalities (const doublereal *const molal)
Set the molalities of the solutes in a phase.
void setMolalitiesByName (const compositionMap &xMap)
Set the molalities of a phase.
void setMolalitiesByName (const std::string &name)
Set the molalities of a phase.
int activityConvention () const
This method returns the activity convention.
void getActivityCoefficients (doublereal *ac) const
Get the array of non-dimensional activity coefficients at the current solution temperature, pressure, and solution concentration.
virtual double osmoticCoefficient () const
Calculate the osmotic coefficient.
void getElectrochemPotentials (doublereal *mu) const
Get the species electrochemical potentials.
void initThermoXML (XML_Node &phaseNode, const std::string &id)
Import and initialize a ThermoPhase object.
Public Member Functions inherited from VPStandardStateTP
VPStandardStateTP ()
Constructor.
VPStandardStateTP (const VPStandardStateTP &b)
Copy Constructor.
VPStandardStateTP & operator= (const VPStandardStateTP &b)
Assignment operator.
virtual ~VPStandardStateTP ()
Destructor.
virtual int standardStateConvention () const
This method returns the convention used in specification of the standard state, of which there are currently two, temperature based, and variable pressure based.
virtual void getdlnActCoeffdlnN_diag (doublereal *dlnActCoeffdlnN_diag) const
Get the array of log concentration-like derivatives of the log activity coefficients.
void getChemPotentials_RT (doublereal *mu) const
Get the array of non-dimensional species chemical potentials.
virtual void getStandardChemPotentials (doublereal *mu) const
Get the array of chemical potentials at unit activity.
virtual void getEnthalpy_RT (doublereal *hrt) const
Get the nondimensional Enthalpy functions for the species at their standard states at the current T and P of the solution.
virtual void getEntropy_R (doublereal *sr) const
Get the array of nondimensional Enthalpy functions for the standard state species at the current T and P of the solution.
virtual void getGibbs_RT (doublereal *grt) const
Get the nondimensional Gibbs functions for the species at their standard states of solution at the current T and P of the solution.
void getPureGibbs (doublereal *gpure) const
Get the standard state Gibbs functions for each species at the current T and P.
virtual void getIntEnergy_RT (doublereal *urt) const
Returns the vector of nondimensional internal Energies of the standard state at the current temperature and pressure of the solution for each species.
virtual void getCp_R (doublereal *cpr) const
Get the nondimensional Heat Capacities at constant pressure for the standard state of the species at the current T and P.
virtual void getStandardVolumes (doublereal *vol) const
Get the molar volumes of each species in their standard states at the current T and P of the solution.
virtual const vector_fp & getStandardVolumes () const
doublereal pressure () const
Returns the current pressure of the phase.
virtual void updateStandardStateThermo () const
Updates the standard state thermodynamic functions at the current T and P of the solution.
virtual bool addSpecies (shared_ptr< Species > spec)
Add a Species to this Phase.
void setVPSSMgr (VPSSMgr *vp_ptr)
set the VPSS Mgr
VPSSMgr * provideVPSSMgr ()
Return a pointer to the VPSSMgr for this phase.
void createInstallPDSS (size_t k, const XML_Node &s, const XML_Node *phaseNode_ptr)
PDSS * providePDSS (size_t k)
const PDSS * providePDSS (size_t k) const
virtual void getEnthalpy_RT_ref (doublereal *hrt) const
Returns the vector of nondimensional enthalpies of the reference state at the current temperature of the solution and the reference pressure for the species.
void modifyOneHf298SS (const size_t k, const doublereal Hf298New)
Modify the value of the 298 K Heat of Formation of the standard state of one species in the phase (J kmol-1)
virtual void getGibbs_RT_ref (doublereal *grt) const
Returns the vector of nondimensional Gibbs free energies of the reference state at the current temperature of the solution and the reference pressure for the species.
virtual void getGibbs_ref (doublereal *g) const
virtual void getEntropy_R_ref (doublereal *er) const
virtual void getCp_R_ref (doublereal *cprt) const
virtual void getStandardVolumes_ref (doublereal *vol) const
Get the molar volumes of the species reference states at the current T and P_ref of the solution.
Public Member Functions inherited from ThermoPhase
ThermoPhase ()
Constructor.
virtual ~ThermoPhase ()
Destructor. Deletes the species thermo manager.
ThermoPhase (const ThermoPhase &right)
Copy Constructor for the ThermoPhase object.
ThermoPhase & operator= (const ThermoPhase &right)
Assignment operator.
doublereal _RT () const
Return the Gas Constant multiplied by the current temperature.
virtual doublereal refPressure () const
Returns the reference pressure in Pa.
virtual doublereal minTemp (size_t k=npos) const
Minimum temperature for which the thermodynamic data for the species or phase are valid.
doublereal Hf298SS (const int k) const
Report the 298 K Heat of Formation of the standard state of one species (J kmol-1)
virtual doublereal maxTemp (size_t k=npos) const
Maximum temperature for which the thermodynamic data for the species are valid.
bool chargeNeutralityNecessary () const
Returns the chargeNeutralityNecessity boolean.
virtual doublereal intEnergy_mole () const
Molar internal energy. Units: J/kmol.
virtual doublereal cv_vib (int, double) const
virtual doublereal isothermalCompressibility () const
Returns the isothermal compressibility. Units: 1/Pa.
virtual doublereal thermalExpansionCoeff () const
Return the volumetric thermal expansion coefficient. Units: 1/K.
void setElectricPotential (doublereal v)
Set the electric potential of this phase (V).
doublereal electricPotential () const
Returns the electric potential of this phase (V).
virtual doublereal logStandardConc (size_t k=0) const
Natural logarithm of the standard concentration of the kth species.
virtual void getLnActivityCoefficients (doublereal *lnac) const
Get the array of non-dimensional molar-based ln activity coefficients at the current solution temperature, pressure, and solution concentration.
void getElectrochemPotentials (doublereal *mu) const
Get the species electrochemical potentials.
virtual void getPartialMolarIntEnergies (doublereal *ubar) const
Return an array of partial molar internal energies for the species in the mixture.
virtual void getdPartialMolarVolumes_dT (doublereal *d_vbar_dT) const
Return an array of derivatives of partial molar volumes wrt temperature for the species in the mixture.
virtual void getdPartialMolarVolumes_dP (doublereal *d_vbar_dP) const
Return an array of derivatives of partial molar volumes wrt pressure for the species in the mixture.
virtual void getdStandardVolumes_dT (doublereal *d_vol_dT) const
Get the derivative of the molar volumes of the species standard states wrt temperature at the current T and P of the solution.
virtual void getdStandardVolumes_dP (doublereal *d_vol_dP) const
Get the derivative molar volumes of the species standard states wrt pressure at the current T and P of the solution.
virtual void getIntEnergy_RT_ref (doublereal *urt) const
Returns the vector of nondimensional internal Energies of the reference state at the current temperature of the solution and the reference pressure for each species.
virtual void setReferenceComposition (const doublereal *const x)
Sets the reference composition.
virtual void getReferenceComposition (doublereal *const x) const
Gets the reference composition.
doublereal enthalpy_mass () const
Specific enthalpy.
doublereal intEnergy_mass () const
Specific internal energy.
doublereal entropy_mass () const
Specific entropy.
doublereal gibbs_mass () const
Specific Gibbs function.
doublereal cp_mass () const
Specific heat at constant pressure.
doublereal cv_mass () const
Specific heat at constant volume.
virtual void setState_TPX (doublereal t, doublereal p, const doublereal *x)
Set the temperature (K), pressure (Pa), and mole fractions.
virtual void setState_TPX (doublereal t, doublereal p, const compositionMap &x)
Set the temperature (K), pressure (Pa), and mole fractions.
virtual void setState_TPX (doublereal t, doublereal p, const std::string &x)
Set the temperature (K), pressure (Pa), and mole fractions.
virtual void setState_TPY (doublereal t, doublereal p, const doublereal *y)
Set the internally stored temperature (K), pressure (Pa), and mass fractions of the phase.
virtual void setState_TPY (doublereal t, doublereal p, const compositionMap &y)
Set the internally stored temperature (K), pressure (Pa), and mass fractions of the phase.
virtual void setState_TPY (doublereal t, doublereal p, const std::string &y)
Set the internally stored temperature (K), pressure (Pa), and mass fractions of the phase.
virtual void setState_PX (doublereal p, doublereal *x)
Set the pressure (Pa) and mole fractions.
virtual void setState_PY (doublereal p, doublereal *y)
Set the internally stored pressure (Pa) and mass fractions.
virtual void setState_HP (doublereal h, doublereal p, doublereal tol=1.e-4)
Set the internally stored specific enthalpy (J/kg) and pressure (Pa) of the phase.
virtual void setState_UV (doublereal u, doublereal v, doublereal tol=1.e-4)
Set the specific internal energy (J/kg) and specific volume (m^3/kg).
virtual void setState_SP (doublereal s, doublereal p, doublereal tol=1.e-4)
Set the specific entropy (J/kg/K) and pressure (Pa).
virtual void setState_SV (doublereal s, doublereal v, doublereal tol=1.e-4)
Set the specific entropy (J/kg/K) and specific volume (m^3/kg).
void equilibrate (const std::string &XY, const std::string &solver="auto", double rtol=1e-9, int max_steps=50000, int max_iter=100, int estimate_equil=0, int log_level=0)
Equilibrate a ThermoPhase object.
void setElementPotentials (const vector_fp &lambda)
Stores the element potentials in the ThermoPhase object.
bool getElementPotentials (doublereal *lambda) const
Returns the element potentials stored in the ThermoPhase object.
virtual doublereal critTemperature () const
Critical temperature (K).
virtual doublereal critPressure () const
Critical pressure (Pa).
virtual doublereal critVolume () const
Critical volume (m3/kmol).
virtual doublereal critCompressibility () const
Critical compressibility (unitless).
virtual doublereal critDensity () const
Critical density (kg/m3).
virtual doublereal satTemperature (doublereal p) const
Return the saturation temperature given the pressure.
virtual doublereal satPressure (doublereal t)
Return the saturation pressure given the temperature.
virtual doublereal vaporFraction () const
Return the fraction of vapor at the current conditions.
virtual void setState_Tsat (doublereal t, doublereal x)
Set the state to a saturated system at a particular temperature.
virtual void setState_Psat (doublereal p, doublereal x)
Set the state to a saturated system at a particular pressure.
void saveSpeciesData (const size_t k, const XML_Node *const data)
Store a reference pointer to the XML tree containing the species data for this phase.
const std::vector< const
XML_Node * > & speciesData () const
Return a pointer to the vector of XML nodes containing the species data for this phase.
void setSpeciesThermo (SpeciesThermo *spthermo)
Install a species thermodynamic property manager.
virtual SpeciesThermo & speciesThermo (int k=-1)
Return a changeable reference to the calculation manager for species reference-state thermodynamic properties.
virtual void initThermoFile (const std::string &inputFile, const std::string &id)
virtual void installSlavePhases (Cantera::XML_Node *phaseNode)
Add in species from Slave phases.
virtual void setParameters (int n, doublereal *const c)
Set the equation of state parameters.
virtual void getParameters (int &n, doublereal *const c) const
Get the equation of state parameters in a vector.
virtual void setParametersFromXML (const XML_Node &eosdata)
Set equation of state parameter values from XML entries.
virtual void getdlnActCoeffds (const doublereal dTds, const doublereal *const dXds, doublereal *dlnActCoeffds) const
Get the change in activity coefficients wrt changes in state (temp, mole fraction, etc) along a line in parameter space or along a line in physical space.
virtual void getdlnActCoeffdlnX_diag (doublereal *dlnActCoeffdlnX_diag) const
Get the array of ln mole fraction derivatives of the log activity coefficients - diagonal component only.
virtual void getdlnActCoeffdlnN_numderiv (const size_t ld, doublereal *const dlnActCoeffdlnN)
virtual void reportCSV (std::ofstream &csvFile) const
returns a summary of the state of the phase to a comma separated file.
Public Member Functions inherited from Phase
Phase ()
Default constructor.
virtual ~Phase ()
Destructor.
Phase (const Phase &right)
Copy Constructor.
Phase & operator= (const Phase &right)
Assignment operator.
XML_Node & xml () const
Returns a const reference to the XML_Node that describes the phase.
void setXMLdata (XML_Node &xmlPhase)
Stores the XML tree information for the current phase.
void saveState (vector_fp &state) const
Save the current internal state of the phase Write to vector 'state' the current internal state.
void saveState (size_t lenstate, doublereal *state) const
Write to array 'state' the current internal state.
void restoreState (const vector_fp &state)
Restore a state saved on a previous call to saveState.
void restoreState (size_t lenstate, const doublereal *state)
Restore the state of the phase from a previously saved state vector.
doublereal molecularWeight (size_t k) const
Molecular weight of species k.
void getMolecularWeights (vector_fp &weights) const
Copy the vector of molecular weights into vector weights.
void getMolecularWeights (doublereal *weights) const
Copy the vector of molecular weights into array weights.
const vector_fp & molecularWeights () const
Return a const reference to the internal vector of molecular weights.
doublereal size (size_t k) const
This routine returns the size of species k.
doublereal charge (size_t k) const
Dimensionless electrical charge of a single molecule of species k The charge is normalized by the the magnitude of the electron charge.
doublereal chargeDensity () const
Charge density [C/m^3].
size_t nDim () const
Returns the number of spatial dimensions (1, 2, or 3)
void setNDim (size_t ndim)
Set the number of spatial dimensions (1, 2, or 3).
virtual bool ready () const
Returns a bool indicating whether the object is ready for use.
int stateMFNumber () const
Return the State Mole Fraction Number.
std::string id () const
Return the string id for the phase.
void setID (const std::string &id)
Set the string id for the phase.
std::string name () const
Return the name of the phase.
void setName (const std::string &nm)
Sets the string name for the phase.
std::string elementName (size_t m) const
Name of the element with index m.
size_t elementIndex (const std::string &name) const
Return the index of element named 'name'.
const std::vector< std::string > & elementNames () const
Return a read-only reference to the vector of element names.
doublereal atomicWeight (size_t m) const
Atomic weight of element m.
doublereal entropyElement298 (size_t m) const
Entropy of the element in its standard state at 298 K and 1 bar.
int atomicNumber (size_t m) const
Atomic number of element m.
int elementType (size_t m) const
Return the element constraint type Possible types include:
int changeElementType (int m, int elem_type)
Change the element type of the mth constraint Reassigns an element type.
const vector_fp & atomicWeights () const
Return a read-only reference to the vector of atomic weights.
size_t nElements () const
Number of elements.
void checkElementIndex (size_t m) const
Check that the specified element index is in range Throws an exception if m is greater than nElements()-1.
void checkElementArraySize (size_t mm) const
Check that an array size is at least nElements() Throws an exception if mm is less than nElements().
doublereal nAtoms (size_t k, size_t m) const
Number of atoms of element m in species k.
void getAtoms (size_t k, double *atomArray) const
Get a vector containing the atomic composition of species k.
size_t speciesIndex (const std::string &name) const
Returns the index of a species named 'name' within the Phase object.
std::string speciesName (size_t k) const
Name of the species with index k.
std::string speciesSPName (int k) const
Returns the expanded species name of a species, including the phase name This is guaranteed to be unique within a Cantera problem.
const std::vector< std::string > & speciesNames () const
Return a const reference to the vector of species names.
size_t nSpecies () const
Returns the number of species in the phase.
void checkSpeciesIndex (size_t k) const
Check that the specified species index is in range Throws an exception if k is greater than nSpecies()-1.
void checkSpeciesArraySize (size_t kk) const
Check that an array size is at least nSpecies() Throws an exception if kk is less than nSpecies().
void setMoleFractionsByName (const compositionMap &xMap)
Set the species mole fractions by name.
void setMoleFractionsByName (const std::string &x)
Set the mole fractions of a group of species by name.
void setMassFractionsByName (const compositionMap &yMap)
Set the species mass fractions by name.
void setMassFractionsByName (const std::string &x)
Set the species mass fractions by name.
void setState_TRX (doublereal t, doublereal dens, const doublereal *x)
Set the internally stored temperature (K), density, and mole fractions.
void setState_TRX (doublereal t, doublereal dens, const compositionMap &x)
Set the internally stored temperature (K), density, and mole fractions.
void setState_TRY (doublereal t, doublereal dens, const doublereal *y)
Set the internally stored temperature (K), density, and mass fractions.
void setState_TRY (doublereal t, doublereal dens, const compositionMap &y)
Set the internally stored temperature (K), density, and mass fractions.
void setState_TNX (doublereal t, doublereal n, const doublereal *x)
Set the internally stored temperature (K), molar density (kmol/m^3), and mole fractions.
void setState_TR (doublereal t, doublereal rho)
Set the internally stored temperature (K) and density (kg/m^3)
void setState_TX (doublereal t, doublereal *x)
Set the internally stored temperature (K) and mole fractions.
void setState_TY (doublereal t, doublereal *y)
Set the internally stored temperature (K) and mass fractions.
void setState_RX (doublereal rho, doublereal *x)
Set the density (kg/m^3) and mole fractions.
void setState_RY (doublereal rho, doublereal *y)
Set the density (kg/m^3) and mass fractions.
void getMoleFractionsByName (compositionMap &x) const
Get the mole fractions by name.
compositionMap getMoleFractionsByName (double threshold=0.0) const
Get the mole fractions by name.
doublereal moleFraction (size_t k) const
Return the mole fraction of a single species.
doublereal moleFraction (const std::string &name) const
Return the mole fraction of a single species.
compositionMap getMassFractionsByName (double threshold=0.0) const
Get the mass fractions by name.
doublereal massFraction (size_t k) const
Return the mass fraction of a single species.
doublereal massFraction (const std::string &name) const
Return the mass fraction of a single species.
void getMoleFractions (doublereal *const x) const
Get the species mole fraction vector.
virtual void setMoleFractions (const doublereal *const x)
Set the mole fractions to the specified values There is no restriction on the sum of the mole fraction vector.
virtual void setMoleFractions_NoNorm (const doublereal *const x)
Set the mole fractions to the specified values without normalizing.
void getMassFractions (doublereal *const y) const
Get the species mass fractions.
const doublereal * massFractions () const
Return a const pointer to the mass fraction array.
virtual void setMassFractions (const doublereal *const y)
Set the mass fractions to the specified values and normalize them.
virtual void setMassFractions_NoNorm (const doublereal *const y)
Set the mass fractions to the specified values without normalizing.
void getConcentrations (doublereal *const c) const
Get the species concentrations (kmol/m^3).
doublereal concentration (const size_t k) const
Concentration of species k.
virtual void setConcentrations (const doublereal *const conc)
Set the concentrations to the specified values within the phase.
doublereal elementalMassFraction (const size_t m) const
Elemental mass fraction of element m.
doublereal elementalMoleFraction (const size_t m) const
Elemental mole fraction of element m.
const doublereal * moleFractdivMMW () const
Returns a const pointer to the start of the moleFraction/MW array.
doublereal temperature () const
Temperature (K).
virtual doublereal density () const
Density (kg/m^3).
doublereal molarDensity () const
Molar density (kmol/m^3).
doublereal molarVolume () const
Molar volume (m^3/kmol).
doublereal mean_X (const doublereal *const Q) const
Evaluate the mole-fraction-weighted mean of an array Q.
doublereal mean_X (const vector_fp &Q) const
Evaluate the mole-fraction-weighted mean of an array Q.
doublereal mean_Y (const doublereal *const Q) const
Evaluate the mass-fraction-weighted mean of an array Q.
doublereal meanMolecularWeight () const
The mean molecular weight. Units: (kg/kmol)
doublereal sum_xlogx () const
Evaluate \(\sum_k X_k \log X_k \).
doublereal sum_xlogQ (doublereal *const Q) const
Evaluate \(\sum_k X_k \log Q_k \).
size_t addElement (const std::string &symbol, doublereal weight=-12345.0, int atomicNumber=0, doublereal entropy298=ENTROPY298_UNKNOWN, int elem_type=CT_ELEM_TYPE_ABSPOS)
Add an element.
void addElement (const XML_Node &e)
Add an element from an XML specification.
void addUniqueElement (const std::string &symbol, doublereal weight=-12345.0, int atomicNumber=0, doublereal entropy298=ENTROPY298_UNKNOWN, int elem_type=CT_ELEM_TYPE_ABSPOS)
Add an element, checking for uniqueness The uniqueness is checked by comparing the string symbol.
void addUniqueElement (const XML_Node &e)
Add an element, checking for uniqueness The uniqueness is checked by comparing the string symbol.
void addElementsFromXML (const XML_Node &phase)
Add all elements referenced in an XML_Node tree.
void freezeElements ()
Prohibit addition of more elements, and prepare to add species.
bool elementsFrozen ()
True if freezeElements has been called.
size_t addUniqueElementAfterFreeze (const std::string &symbol, doublereal weight, int atomicNumber, doublereal entropy298=ENTROPY298_UNKNOWN, int elem_type=CT_ELEM_TYPE_ABSPOS)
Add an element after elements have been frozen, checking for uniqueness The uniqueness is checked by comparing the string symbol.
void addSpecies (const std::string &name, const doublereal *comp, doublereal charge=0.0, doublereal size=1.0)
void addUniqueSpecies (const std::string &name, const doublereal *comp, doublereal charge=0.0, doublereal size=1.0)
Add a species to the phase, checking for uniqueness of the name This routine checks for uniqueness of the string name.
shared_ptr< Species > species (const std::string &name) const
Return the Species object for the named species.
shared_ptr< Species > species (size_t k) const
Return the Species object for species whose index is k.
void ignoreUndefinedElements ()
Set behavior when adding a species containing undefined elements to just skip the species.
void addUndefinedElements ()
Set behavior when adding a species containing undefined elements to add those elements to the phase.
void throwUndefinedElements ()
Set the behavior when adding a species containing undefined elements to throw an exception.
Public Attributes
bool m_useHelgesonFixedForm
If true, then the fixed for of Helgeson's activity for water is used instead of the rigorous form obtained from Gibbs-Duhem relation.
int m_form_A_Debye
Form of the constant outside the Debye-Huckel term called A.
Public Attributes inherited from Phase
enum CT_RealNumber_Range_Behavior realNumberRangeBehavior_
Overflow behavior of real number calculations involving this thermo object.
Protected Attributes
int m_formDH
form of the Debye-Huckel parameterization used in the model.
int m_formGC
Format for the generalized concentration:
vector_int m_electrolyteSpeciesType
Vector containing the electrolyte species type.
vector_fp m_Aionic
a_k = Size of the ionic species in the DH formulation units = meters
double m_IionicMolality
Current value of the ionic strength on the molality scale.
double m_maxIionicStrength
Maximum value of the ionic strength allowed in the calculation of the activity coefficients.
double m_IionicMolalityStoich
Stoichiometric ionic strength on the molality scale.
double m_A_Debye
Current value of the Debye Constant, A_Debye.
double m_B_Debye
Current value of the constant that appears in the denominator.
vector_fp m_B_Dot
Array of B_Dot values.
vector_fp m_npActCoeff
These are coefficients to describe the increase in activity coeff for non-polar molecules due to the electrolyte becoming stronger (the so-called salt-out effect)
PDSS_Water * m_waterSS
Pointer to the Water standard state object.
double m_densWaterSS
Storage for the density of water's standard state.
WaterProps * m_waterProps
Pointer to the water property calculator.
vector_fp m_pp
Temporary array used in equilibrium calculations.
vector_fp m_tmpV
vector of size m_kk, used as a temporary holding area.
vector_fp m_speciesCharge_Stoich
Stoichiometric species charge -> This is for calculations of the ionic strength which ignore ion-ion pairing into neutral molecules.
Array2D m_Beta_ij
Array of 2D data used in the DHFORM_BETAIJ formulation Beta_ij.value(i,j) is the coefficient of the jth species for the specification of the chemical potential of the ith species.
vector_fp m_lnActCoeffMolal
Logarithm of the activity coefficients on the molality scale.
vector_fp m_dlnActCoeffMolaldT
Derivative of log act coeff wrt T.
vector_fp m_d2lnActCoeffMolaldT2
2nd Derivative of log act coeff wrt T
vector_fp m_dlnActCoeffMolaldP
Derivative of log act coeff wrt P.
Protected Attributes inherited from MolalityVPSSTP
size_t m_indexSolvent
Index of the solvent.
int m_pHScalingType
Scaling to be used for output of single-ion species activity coefficients.
size_t m_indexCLM
Index of the phScale species.
doublereal m_weightSolvent
Molecular weight of the Solvent.
doublereal m_xmolSolventMIN
doublereal m_Mnaught
This is the multiplication factor that goes inside log expressions involving the molalities of species.
vector_fp m_molalities
Current value of the molalities of the species in the phase.
Protected Attributes inherited from VPStandardStateTP
doublereal m_Pcurrent
Current value of the pressure - state variable.
doublereal m_Tlast_ss
The last temperature at which the standard statethermodynamic properties were calculated at.
doublereal m_Plast_ss
The last pressure at which the Standard State thermodynamic properties were calculated at.
doublereal m_P0
VPSSMgr * m_VPSS_ptr
Pointer to the VPSS manager that calculates all of the standard state info efficiently.
std::vector< PDSS * > m_PDSS_storage
Storage for the PDSS objects for the species.
Protected Attributes inherited from ThermoPhase
SpeciesThermo * m_spthermo
Pointer to the calculation manager for species reference-state thermodynamic properties.
std::vector< const XML_Node * > m_speciesData
Vector of pointers to the species databases.
doublereal m_phi
Stored value of the electric potential for this phase.
vector_fp m_lambdaRRT
Vector of element potentials.
bool m_hasElementPotentials
Boolean indicating whether there is a valid set of saved element potentials for this phase.
bool m_chargeNeutralityNecessary
Boolean indicating whether a charge neutrality condition is a necessity.
int m_ssConvention
Contains the standard state convention.
std::vector< doublereal > xMol_Ref
Reference Mole Fraction Composition.
doublereal m_tlast
last value of the temperature processed by reference state
Protected Attributes inherited from Phase
ValueCache m_cache
Cached for saved calculations within each ThermoPhase.
size_t m_kk
Number of species in the phase.
size_t m_ndim
Dimensionality of the phase.
vector_fp m_speciesComp
Atomic composition of the species.
vector_fp m_speciesSize
Vector of species sizes.
vector_fp m_speciesCharge
Vector of species charges. length m_kk.
std::map< std::string,
shared_ptr< Species > > m_species
UndefElement::behavior m_undefinedElementBehavior
Flag determining behavior when adding species with an undefined element.
Private Member Functions
double _nonpolarActCoeff (double IionicMolality) const
Static function that implements the non-polar species salt-out modifications.
double _osmoticCoeffHelgesonFixedForm () const
Formula for the osmotic coefficient that occurs in the GWB.
double _lnactivityWaterHelgesonFixedForm () const
Formula for the log of the water activity that occurs in the GWB.
void initLengths ()
Initialize the internal lengths.
void s_update_lnMolalityActCoeff () const
Calculate the log activity coefficients.
void s_update_dlnMolalityActCoeff_dT () const
Calculation of temperature derivative of activity coefficient.
void s_update_d2lnMolalityActCoeff_dT2 () const
Calculate the temperature 2nd derivative of the activity coefficient.
void s_update_dlnMolalityActCoeff_dP () const
Calculate the pressure derivative of the activity coefficient.
Mechanical Equation of State Properties
In this equation of state implementation, the density is a function only of the mole fractions.
Therefore, it can't be an independent variable. Instead, the pressure is used as the independent variable. Functions which try to set the thermodynamic state by calling setDensity() may cause an exception to be thrown.
virtual doublereal pressure () const
Return the thermodynamic pressure (Pa).
virtual void setPressure (doublereal p)
Set the internally stored pressure (Pa) at constant temperature and composition.
void setDensity (const doublereal rho)
Set the internally stored density (gm/m^3) of the phase.
virtual void setMolarDensity (const doublereal conc)
Set the internally stored molar density (kmol/m^3) of the phase.
virtual void setTemperature (const doublereal temp)
Set the temperature (K)
virtual void setState_TP (doublereal t, doublereal p)
Set the temperature (K) and pressure (Pa)
virtual void calcDensity ()
Calculate the density of the mixture using the partial molar volumes and mole fractions as input.
Additional Inherited Members
Protected Member Functions inherited from MolalityVPSSTP
virtual void getCsvReportData (std::vector< std::string > &names, std::vector< vector_fp > &data) const
Fills names and data with the column names and species thermo properties to be included in the output of the reportCSV method.
virtual void getUnscaledMolalityActivityCoefficients (doublereal *acMolality) const
Get the array of unscaled non-dimensional molality based activity coefficients at the current solution temperature, pressure, and solution concentration.
virtual void applyphScale (doublereal *acMolality) const
Apply the current phScale to a set of activity Coefficients or activities.
Protected Member Functions inherited from VPStandardStateTP
virtual void _updateStandardStateThermo () const
Updates the standard state thermodynamic functions at the current T and P of the solution.
const vector_fp & Gibbs_RT_ref () const
Protected Member Functions inherited from Phase
void setMolecularWeight (const int k, const double mw)
Set the molecular weight of a single species to a given value.
Detailed Description
Class DebyeHuckel represents a dilute liquid electrolyte phase which obeys the Debye Huckel formulation for nonideality.
The concentrations of the ionic species are assumed to obey the electroneutrality condition.
Specification of Species Standard State Properties
The standard states are on the unit molality basis. Therefore, in the documentation below, the normal \(o \) superscript is replaced with the \(\triangle \) symbol. The reference state symbol is now \(\triangle, ref \).
It is assumed that the reference state thermodynamics may be
obtained by a pointer to a populated species thermodynamic property
manager class (see ThermoPhase::m_spthermo). How to relate pressure
changes to the reference state thermodynamics is resolved at this level.
For an incompressible,
stoichiometric substance, the molar internal energy is independent of pressure. Since the thermodynamic properties are specified by giving the standard-state enthalpy, the term \(P_0 \hat v\) is subtracted from the specified molar enthalpy to compute the molar internal energy. The entropy is assumed to be independent of the pressure.
The enthalpy function is given by the following relation.
\[ h^\triangle_k(T,P) = h^{\triangle,ref}_k(T) + \tilde v \left(P - P_{ref} \right) \]
For an incompressible, stoichiometric substance, the molar internal energy is independent of pressure. Since the thermodynamic properties are specified by giving the standard-state enthalpy, the term \(P_{ref} \tilde v\) is subtracted from the specified reference molar enthalpy to compute the molar internal energy.
\[ u^\triangle_k(T,P) = h^{\triangle,ref}_k(T) - P_{ref} \tilde v \]
The standard state heat capacity and entropy are independent of pressure. The standard state Gibbs free energy is obtained from the enthalpy and entropy functions.
The vector Phase::m_speciesSize[] is used to hold the base values of species sizes. These are defined as the molar volumes of species at infinite dilution at 300 K and 1 atm of water. m_speciesSize are calculated during the initialization of the DebyeHuckel object and are then not touched.
The current model assumes that an incompressible molar volume for all solutes. The molar volume for the water solvent, however, is obtained from a pure water equation of state, waterSS. Therefore, the water standard state varies with both T and P. It is an error to request standard state water properties at a T and P where the water phase is not a stable phase, i.e., beyond its spinodal curve.
Specification of Solution Thermodynamic Properties
Chemical potentials of the solutes, \(\mu_k \), and the solvent, \(\mu_o \), which are based on the molality form, have the following general format:
\[ \mu_k = \mu^{\triangle}_k(T,P) + R T ln(\gamma_k^{\triangle} \frac{m_k}{m^\triangle}) \]
\[ \mu_o = \mu^o_o(T,P) + RT ln(a_o) \]
where \(\gamma_k^{\triangle} \) is the molality based activity coefficient for species \(k\).
Individual activity coefficients of ions can not be independently measured. Instead, only binary pairs forming electroneutral solutions can be measured.
<H3> Ionic Strength </H3>
Most of the parameterizations within the model use the ionic strength
as a key variable. The ionic strength, \form#129 is defined as follows
\[ I = \frac{1}{2} \sum_k{m_k z_k^2} \]
\(m_k \) is the molality of the kth species. \(z_k \) is the charge of the kth species. Note, the ionic strength is a defined units quantity. The molality has defined units of gmol kg-1, and therefore the ionic strength has units of sqrt(gmol kg-1).
In some instances, from some authors, a different formulation is used for the ionic strength in the equations below. The different formulation is due to the possibility of the existence of weak acids and how association wrt to the weak acid equilibrium relation affects the calculation of the activity coefficients via the assumed value of the ionic strength.
If we are to assume that the association reaction doesn't have an effect on the ionic strength, then we will want to consider the associated weak acid as in effect being fully dissociated, when we calculate an effective value for the ionic strength. We will call this calculated value, the stoichiometric ionic strength, \(I_s \), putting a subscript s to denote it from the more straightforward calculation of \(I \).
\[ I_s = \frac{1}{2} \sum_k{m_k^s z_k^2} \]
Here, \(m_k^s \) is the value of the molalities calculated assuming that all weak acid-base pairs are in their fully dissociated states. This calculation may be simplified by considering that the weakly associated acid may be made up of two charged species, k1 and k2, each with their own charges, obeying the following relationship:
\[ z_k = z_{k1} + z_{k2} \]
Then, we may only need to specify one charge value, say, \(z_{k1}\), the cation charge number, in order to get both numbers, since we have already specified \(z_k \) in the definition of original species. Then, the stoichiometric ionic strength may be calculated via the following formula.
\[ I_s = \frac{1}{2} \left(\sum_{k,ions}{m_k z_k^2}+ \sum_{k,weak_assoc}(m_k z_{k1}^2 + m_k z_{k2}^2) \right) \]
The specification of which species are weakly associated acids is made in the input file via the stoichIsMods XML block, where the charge for k1 is also specified. An example is given below:
<stoichIsMods>
      NaCl(aq):-1.0
</stoichIsMods>
Because we need the concept of a weakly associated acid in order to calculated \(I_s \) we need to catalog all species in the phase. This is done using the following categories:
cEST_solvent Solvent species (neutral)
cEST_chargedSpecies Charged species (charged)
cEST_weakAcidAssociated Species which can break apart into charged species. It may or may not be charged. These may or may not be be included in the species solution vector.
cEST_strongAcidAssociated Species which always breaks apart into charged species. It may or may not be charged. Normally, these aren't included in the speciation vector.
cEST_polarNeutral Polar neutral species
cEST_nonpolarNeutral Non polar neutral species
Polar and non-polar neutral species are differentiated, because some additions to the activity coefficient expressions distinguish between these two types of solutes. This is the so-called salt-out effect.
The type of species is specified in the electrolyteSpeciesType XML block. Note, this is not considered a part of the specification of the standard state for the species, at this time. Therefore, this information is put under the activityCoefficient XML block. An example is given below
<electrolyteSpeciesType>
       H2L(L):solvent
       H+:chargedSpecies
       NaOH(aq):weakAcidAssociated
       NaCl(aq):strongAcidAssociated
       NH3(aq):polarNeutral
       O2(aq):nonpolarNeutral
</electrolyteSpeciesType>
Much of the species electrolyte type information is inferred from other information in the input file. For example, as species which is charged is given the "chargedSpecies" default category. A neutral solute species is put into the "nonpolarNeutral" category by default.
The specification of solute activity coefficients depends on the model assumed for the Debye-Huckel term. The model is set by the internal parameter m_formDH. We will now describe each category in its own section.
<H3> Debye-Huckel Dilute Limit </H3>
DHFORM_DILUTE_LIMIT = 0
This form assumes a dilute limit to DH, and is mainly for informational purposes:
\[ \ln(\gamma_k^\triangle) = - z_k^2 A_{Debye} \sqrt{I} \]
where \(I\) is the ionic strength
\[ I = \frac{1}{2} \sum_k{m_k z_k^2} \]
The activity for the solvent water, \(a_o \), is not independent and must be determined from the Gibbs-Duhem relation.
\[ \ln(a_o) = \frac{X_o - 1.0}{X_o} + \frac{ 2 A_{Debye} \tilde{M}_o}{3} (I)^{3/2} \]
<H3> Bdot Formulation </H3>
  DHFORM_BDOT_AK       = 1
    This form assumes Bethke's format for the Debye Huckel activity coefficient:
\[ \ln(\gamma_k^\triangle) = -z_k^2 \frac{A_{Debye} \sqrt{I}}{ 1 + B_{Debye} a_k \sqrt{I}} + \log(10) B^{dot}_k I \]
Note, this particular form where \(a_k \) can differ in multielectrolyte solutions has problems with respect to a Gibbs-Duhem analysis. However, we include it here because there is a lot of data fit to it.
The activity for the solvent water, \(a_o \), is not independent and must be determined from the Gibbs-Duhem relation. Here, we use:
\[ \ln(a_o) = \frac{X_o - 1.0}{X_o} + \frac{ 2 A_{Debye} \tilde{M}_o}{3} (I)^{1/2} \left[ \sum_k{\frac{1}{2} m_k z_k^2 \sigma(B_{Debye} a_k \sqrt{I}) } \right] - \frac{\log(10)}{2} \tilde{M}_o I \sum_k{ B^{dot}_k m_k} \]
where
\[ \sigma (y) = \frac{3}{y^3} \left[ (1+y) - 2 \ln(1 + y) - \frac{1}{1+y} \right] \]
Additionally, Helgeson's formulation for the water activity is offered as an alternative.
<H3> Bdot Formulation with Uniform Size Parameter in the Denominator </H3>
DHFORM_BDOT_AUNIFORM = 2
This form assumes Bethke's format for the Debye-Huckel activity coefficient
\[ \ln(\gamma_k^\triangle) = -z_k^2 \frac{A_{Debye} \sqrt{I}}{ 1 + B_{Debye} a \sqrt{I}} + \log(10) B^{dot}_k I \]
The value of a is determined at the beginning of the calculation, and not changed.
\[ \ln(a_o) = \frac{X_o - 1.0}{X_o} + \frac{ 2 A_{Debye} \tilde{M}_o}{3} (I)^{3/2} \sigma(B_{Debye} a \sqrt{I}) - \frac{\log(10)}{2} \tilde{M}_o I \sum_k{ B^{dot}_k m_k} \]
<H3> Beta_IJ formulation </H3>
DHFORM_BETAIJ        = 3
This form assumes a linear expansion in a virial coefficient form.
It is used extensively in the book by Newmann, "Electrochemistry Systems",
and is the beginning of more complex treatments for stronger electrolytes,
fom Pitzer and from Harvey, Moller, and Weire.
\[ \ln(\gamma_k^\triangle) = -z_k^2 \frac{A_{Debye} \sqrt{I}}{ 1 + B_{Debye} a \sqrt{I}} + 2 \sum_j \beta_{j,k} m_j \]
In the current treatment the binary interaction coefficients, \(\beta_{j,k}\), are independent of temperature and pressure.
\[ \ln(a_o) = \frac{X_o - 1.0}{X_o} + \frac{ 2 A_{Debye} \tilde{M}_o}{3} (I)^{3/2} \sigma(B_{Debye} a \sqrt{I}) - \tilde{M}_o \sum_j \sum_k \beta_{j,k} m_j m_k \]
In this formulation the ionic radius, \(a \), is a constant. This must be supplied to the model, in an ionicRadius XML block.
The \(\beta_{j,k} \) parameters are binary interaction parameters. They are supplied to the object in an DHBetaMatrix XML block. There are in principle \(N (N-1) /2 \) different, symmetric interaction parameters, where \(N \) are the number of solute species in the mechanism. An example is given below.
An example activityCoefficients XML block for this formulation is supplied below
<activityCoefficients model="Beta_ij">
       <!-- A_Debye units = sqrt(kg/gmol) -->
       <A_Debye> 1.172576 </A_Debye>
       <!-- B_Debye units = sqrt(kg/gmol)/m   -->
       <B_Debye> 3.28640E9 </B_Debye>
       <ionicRadius default="3.042843"  units="Angstroms">
       </ionicRadius>
       <DHBetaMatrix>
             H+:Cl-:0.27
             Na+:Cl-:0.15
             Na+:OH-:0.06
       </DHBetaMatrix>
       <stoichIsMods>
              NaCl(aq):-1.0
       </stoichIsMods>
       <electrolyteSpeciesType>
              H+:chargedSpecies
              NaCl(aq):weakAcidAssociated
       </electrolyteSpeciesType>
</activityCoefficients>
Pitzer Beta_IJ formulation
DHFORM_PITZER_BETAIJ = 4
This form assumes an activity coefficient formulation consistent with a truncated form of Pitzer's formulation. Pitzer's formulation is equivalent to the formulations above in the dilute limit, where rigorous theory may be applied.
\[ \ln(\gamma_k^\triangle) = -z_k^2 \frac{A_{Debye}}{3} \frac{\sqrt{I}}{ 1 + B_{Debye} a \sqrt{I}} -2 z_k^2 \frac{A_{Debye}}{3} \frac{\ln(1 + B_{Debye} a \sqrt{I})}{ B_{Debye} a} + 2 \sum_j \beta_{j,k} m_j \]
\[ \ln(a_o) = \frac{X_o - 1.0}{X_o} + \frac{ 2 A_{Debye} \tilde{M}_o}{3} \frac{(I)^{3/2} }{1 + B_{Debye} a \sqrt{I} } - \tilde{M}_o \sum_j \sum_k \beta_{j,k} m_j m_k \]
Specification of the Debye Huckel Constants
In the equations above, the formulas for \(A_{Debye} \) and \(B_{Debye} \) are needed. The DebyeHuckel object uses two methods for specifying these quantities. The default method is to assume that \(A_{Debye} \) is a constant, given in the initialization process, and stored in the member double, m_A_Debye. Optionally, a full water treatment may be employed that makes \(A_{Debye} \) a full function of T and P.
\[ A_{Debye} = \frac{F e B_{Debye}}{8 \pi \epsilon R T} {\left(C_o \tilde{M}_o \right)}^{1/2} \]
where
\[ B_{Debye} = \frac{F} {{(\frac{\epsilon R T}{2})}^{1/2}} \]
Therefore:
\[ A_{Debye} = \frac{1}{8 \pi} {\left(\frac{2 N_a \rho_o}{1000}\right)}^{1/2} {\left(\frac{N_a e^2}{\epsilon R T }\right)}^{3/2} \]
where
\(N_a \) is Avogadro's number
\(\rho_w \) is the density of water
\(e \) is the electronic charge
\(\epsilon = K \epsilon_o \) is the permittivity of water
\(K \) is the dielectric constant of water
\(\epsilon_o \) is the permittivity of free space
\(\rho_o \) is the density of the solvent in its standard state.
Nominal value at 298 K and 1 atm = 1.172576 (kg/gmol)1/2 based on:
\(\epsilon / \epsilon_0 \) = 78.54 (water at 25C)
T = 298.15 K
B_Debye = 3.28640E9 (kg/gmol)1/2 m-1
An example of a fixed value implementation is given below.
<activityCoefficients model="Beta_ij">
      <!-- A_Debye units = sqrt(kg/gmol)  -->
      <A_Debye> 1.172576 </A_Debye>
      <!-- B_Debye units = sqrt(kg/gmol)/m  -->
      <B_Debye> 3.28640E9 </B_Debye>
</activityCoefficients>
An example of a variable value implementation is given below.
<activityCoefficients model="Beta_ij">
      <A_Debye model="water" />
      <!-- B_Debye units = sqrt(kg/gmol)/m  -->
      <B_Debye> 3.28640E9 </B_Debye>
</activityCoefficients>
Currently, \(B_{Debye} \) is a constant in the model, specified either by a default water value, or through the input file. This may have to be looked at, in the future.
Application within Kinetics Managers
For the time being, we have set the standard concentration for all species in this phase equal to the default concentration of the solvent at 298 K and 1 atm. This means that the kinetics operator essentially works on an activities basis, with units specified as if it were on a concentration basis.
For example, a bulk-phase binary reaction between liquid species j and k, producing a new liquid species l would have the following equation for its rate of progress variable, \(R^1 \), which has units of kmol m-3 s-1.
\[ R^1 = k^1 C_j^a C_k^a = k^1 (C_o a_j) (C_o a_k) \]
where
\[ C_j^a = C_o a_j \quad and \quad C_k^a = C_o a_k \]
\(C_j^a \) is the activity concentration of species j, and \(C_k^a \) is the activity concentration of species k. \(C_o \) is the concentration of water at 298 K and 1 atm. \(a_j \) is the activity of species j at the current temperature and pressure and concentration of the liquid phase. \(k^1 \) has units of m3 kmol-1 s-1.
The reverse rate constant can then be obtained from the law of microscopic reversibility and the equilibrium expression for the system.
\[ \frac{a_j a_k}{ a_l} = K^{o,1} = \exp(\frac{\mu^o_l - \mu^o_j - \mu^o_k}{R T}) \]
\(K^{o,1} \) is the dimensionless form of the equilibrium constant.
\[ R^{-1} = k^{-1} C_l^a = k^{-1} (C_o a_l) \]
where
\[ k^{-1} = k^1 K^{o,1} C_o \]
\(k^{-1} \) has units of s-1.
Note, this treatment may be modified in the future, as events dictate.
Instantiation of the Class
The constructor for this phase is NOT located in the default ThermoFactory for Cantera. However, a new DebyeHuckel object may be created by the following code snippets:
DebyeHuckel *DH = new DebyeHuckel("DH_NaCl.xml", "NaCl_electrolyte");
or
XML_Node *xm = get_XML_NameID("phase", "DH_NaCl.xml#NaCl_electrolyte", 0);
DebyeHuckel *dh = new DebyeHuckel(*xm);
or by the following call to importPhase():
XML_Node *xm = get_XML_NameID("phase", "DH_NaCl.xml#NaCl_electrolyte", 0);
DebyeHuckel dhphase;
importPhase(*xm, &dhphase);
XML Example
The phase model name for this is called StoichSubstance. It must be supplied as the model attribute of the thermo XML element entry. Within the phase XML block, the density of the phase must be specified. An example of an XML file this phase is given below.
 <phase id="NaCl_electrolyte" dim="3">
  <speciesArray datasrc="#species_waterSolution">
             H2O(L) Na+ Cl- H+ OH- NaCl(aq) NaOH(aq)
  </speciesArray>
  <state>
    <temperature units="K"> 300  </temperature>
    <pressure units="Pa">101325.0</pressure>
    <soluteMolalities>
           Na+:3.0
           Cl-:3.0
           H+:1.0499E-8
           OH-:1.3765E-6
           NaCl(aq):0.98492
           NaOH(aq):3.8836E-6
    </soluteMolalities>
  </state>
  <!-- thermo model identifies the inherited class
       from ThermoPhase that will handle the thermodynamics.
    -->
  <thermo model="DebyeHuckel">
     <standardConc model="solvent_volume" />
     <activityCoefficients model="Beta_ij">
              <!-- A_Debye units = sqrt(kg/gmol)  -->
              <A_Debye> 1.172576 </A_Debye>
              <!-- B_Debye units = sqrt(kg/gmol)/m   -->
              <B_Debye> 3.28640E9 </B_Debye>
              <ionicRadius default="3.042843"  units="Angstroms">
              </ionicRadius>
              <DHBetaMatrix>
                H+:Cl-:0.27
                Na+:Cl-:0.15
                Na+:OH-:0.06
              </DHBetaMatrix>
              <stoichIsMods>
                 NaCl(aq):-1.0
              </stoichIsMods>
              <electrolyteSpeciesType>
                 H+:chargedSpecies
                 NaCl(aq):weakAcidAssociated
              </electrolyteSpeciesType>
     </activityCoefficients>
     <solvent> H2O(L) </solvent>
  </thermo>
  <elementArray datasrc="elements.xml"> O H Na Cl </elementArray>
</phase>
Definition at line 599 of file DebyeHuckel.h.
Constructor & Destructor Documentation
DebyeHuckel ()
Default Constructor.
Definition at line 30 of file DebyeHuckel.cpp.
References DebyeHuckel::m_npActCoeff.
Referenced by DebyeHuckel::duplMyselfAsThermoPhase().
DebyeHuckel (const DebyeHuckel & b)
Copy constructor.
Definition at line 94 of file DebyeHuckel.cpp.
DebyeHuckel (const std::string & inputFile, const std::string & id = "")
Full constructor for creating the phase.
Parameters
inputFile File name containing the XML description of the phase
id id attribute containing the name of the phase.
Definition at line 51 of file DebyeHuckel.cpp.
References ThermoPhase::initThermoFile(), and DebyeHuckel::m_npActCoeff.
DebyeHuckel (XML_Node & phaseRef, const std::string & id = "")
Full constructor for creating the phase.
Parameters
phaseRef XML phase node containing the description of the phase
id id attribute containing the name of the phase.
Definition at line 73 of file DebyeHuckel.cpp.
References Cantera::findXMLPhase(), Cantera::importPhase(), and DebyeHuckel::m_npActCoeff.
~DebyeHuckel () virtual
Destructor.
Definition at line 157 of file DebyeHuckel.cpp.
References DebyeHuckel::m_waterProps.
Member Function Documentation
DebyeHuckel & operator= (const DebyeHuckel & b)
Assignment operator.
Definition at line 115 of file DebyeHuckel.cpp.
References DebyeHuckel::m_A_Debye, DebyeHuckel::m_Aionic, DebyeHuckel::m_B_Debye, DebyeHuckel::m_B_Dot, DebyeHuckel::m_Beta_ij, DebyeHuckel::m_d2lnActCoeffMolaldT2, DebyeHuckel::m_densWaterSS, DebyeHuckel::m_form_A_Debye, DebyeHuckel::m_formDH, DebyeHuckel::m_formGC, DebyeHuckel::m_IionicMolality, DebyeHuckel::m_IionicMolalityStoich, DebyeHuckel::m_lnActCoeffMolal, DebyeHuckel::m_maxIionicStrength, DebyeHuckel::m_npActCoeff, DebyeHuckel::m_pp, DebyeHuckel::m_speciesCharge_Stoich, DebyeHuckel::m_tmpV, DebyeHuckel::m_useHelgesonFixedForm, DebyeHuckel::m_waterProps, DebyeHuckel::m_waterSS, and MolalityVPSSTP::operator=().
ThermoPhase * duplMyselfAsThermoPhase () const virtual
Duplicator from the ThermoPhase parent class.
Given a pointer to a ThermoPhase object, this function will duplicate the ThermoPhase object and all underlying structures. This is basically a wrapper around the copy constructor.
Returns
returns a pointer to a ThermoPhase
Reimplemented from MolalityVPSSTP.
Definition at line 163 of file DebyeHuckel.cpp.
References DebyeHuckel::DebyeHuckel().
int eosType () const virtual
Equation of state type flag.
The base class returns zero. Subclasses should define this to return a unique non-zero value. Constants defined for this purpose are listed in mix_defs.h.
Reimplemented from ThermoPhase.
Definition at line 168 of file DebyeHuckel.cpp.
References Cantera::cDebyeHuckel0, and DebyeHuckel::m_formGC.
doublereal enthalpy_mole () const virtual
Molar enthalpy of the solution. Units: J/kmol.
Reimplemented from ThermoPhase.
Definition at line 191 of file DebyeHuckel.cpp.
References DATA_PTR, DebyeHuckel::getPartialMolarEnthalpies(), DebyeHuckel::m_tmpV, and Phase::mean_X().
doublereal entropy_mole () const virtual
Molar entropy. Units: J/kmol/K.
For an ideal, constant partial molar volume solution mixture with pure species phases which exhibit zero volume expansivity:
\[ \hat s(T, P, X_k) = \sum_k X_k \hat s^0_k(T) - \hat R \sum_k X_k log(X_k) \]
The reference-state pure-species entropies \(\hat s^0_k(T,p_{ref}) \) are computed by the species thermodynamic property manager. The pure species entropies are independent of temperature since the volume expansivities are equal to zero.
See Also
SpeciesThermo
Reimplemented from ThermoPhase.
Definition at line 197 of file DebyeHuckel.cpp.
References DATA_PTR, DebyeHuckel::getPartialMolarEntropies(), DebyeHuckel::m_tmpV, and Phase::mean_X().
doublereal gibbs_mole () const virtual
Molar Gibbs function. Units: J/kmol.
Reimplemented from ThermoPhase.
Definition at line 203 of file DebyeHuckel.cpp.
References DATA_PTR, DebyeHuckel::getChemPotentials(), DebyeHuckel::m_tmpV, and Phase::mean_X().
doublereal cp_mole () const virtual
Molar heat capacity at constant pressure. Units: J/kmol/K.
Reimplemented from ThermoPhase.
Definition at line 209 of file DebyeHuckel.cpp.
References DATA_PTR, DebyeHuckel::getPartialMolarCp(), DebyeHuckel::m_tmpV, and Phase::mean_X().
doublereal cv_mole () const virtual
Molar heat capacity at constant volume. Units: J/kmol/K.
Reimplemented from ThermoPhase.
Definition at line 215 of file DebyeHuckel.cpp.
doublereal pressure () const virtual
Return the thermodynamic pressure (Pa).
For this incompressible system, we return the internally stored independent value of the pressure.
Reimplemented from ThermoPhase.
Definition at line 226 of file DebyeHuckel.cpp.
References VPStandardStateTP::m_Pcurrent.
Referenced by DebyeHuckel::A_Debye_TP(), DebyeHuckel::d2A_DebyedT2_TP(), DebyeHuckel::dA_DebyedP_TP(), and DebyeHuckel::dA_DebyedT_TP().
void setPressure (doublereal p) virtual
Set the internally stored pressure (Pa) at constant temperature and composition.
This method sets the pressure within the object. The water model is a completely compressible model. Also, the dielectric constant is pressure dependent.
Parameters
p input Pressure (Pa)
Todo:
Implement a variable pressure capability
Reimplemented from VPStandardStateTP.
Definition at line 231 of file DebyeHuckel.cpp.
References DebyeHuckel::setState_TP(), and Phase::temperature().
void calcDensity () protected virtual
Calculate the density of the mixture using the partial molar volumes and mole fractions as input.
The formula for this is
\[ \rho = \frac{\sum_k{X_k W_k}}{\sum_k{X_k V_k}} \]
where \(X_k\) are the mole fractions, \(W_k\) are the molecular weights, and \(V_k\) are the pure species molar volumes.
Note, the basis behind this formula is that in an ideal solution the partial molar volumes are equal to the pure species molar volumes. We have additionally specified in this class that the pure species molar volumes are independent of temperature and pressure.
Reimplemented from VPStandardStateTP.
Definition at line 258 of file DebyeHuckel.cpp.
References PDSS_Water::density(), Phase::getMoleFractions(), DebyeHuckel::getPartialMolarVolumes(), DebyeHuckel::m_densWaterSS, Phase::m_kk, DebyeHuckel::m_pp, DebyeHuckel::m_tmpV, DebyeHuckel::m_waterSS, Phase::meanMolecularWeight(), and Phase::setDensity().
Referenced by DebyeHuckel::setState_TP().
void setDensity (const doublereal rho) virtual
Set the internally stored density (gm/m^3) of the phase.
Overwritten setDensity() function is necessary because the density is not an independent variable.
This function will now throw an error condition
May have to adjust the strategy here to make the eos for these materials slightly compressible, in order to create a condition where the density is a function of the pressure.
This function will now throw an error condition if the input isn't exactly equal to the current density.
Todo:
Now have a compressible ss equation for liquid water. Therefore, this phase is compressible. May still want to change the independent variable however.
Parameters
rho Input density (kg/m^3).
Reimplemented from Phase.
Definition at line 281 of file DebyeHuckel.cpp.
References Phase::density().
void setMolarDensity (const doublereal conc) virtual
Set the internally stored molar density (kmol/m^3) of the phase.
Overwritten setMolarDensity() function is necessary because the density is not an independent variable.
This function will now throw an error condition if the input isn't exactly equal to the current molar density.
Parameters
conc Input molar density (kmol/m^3).
Reimplemented from Phase.
Definition at line 290 of file DebyeHuckel.cpp.
References Phase::molarDensity().
void setTemperature (const doublereal temp) virtual
Set the temperature (K)
This function sets the temperature, and makes sure that the value propagates to underlying objects, such as the water standard state model.
Parameters
temp Temperature in kelvin
Reimplemented from VPStandardStateTP.
Definition at line 299 of file DebyeHuckel.cpp.
References VPStandardStateTP::m_Pcurrent, and DebyeHuckel::setState_TP().
void setState_TP (doublereal t, doublereal p) virtual
Set the temperature (K) and pressure (Pa)
Set the temperature and pressure.
Parameters
t Temperature (K)
p Pressure (Pa)
Reimplemented from VPStandardStateTP.
Definition at line 236 of file DebyeHuckel.cpp.
References VPStandardStateTP::_updateStandardStateThermo(), DebyeHuckel::calcDensity(), VPStandardStateTP::m_Pcurrent, and Phase::setTemperature().
Referenced by DebyeHuckel::setPressure(), and DebyeHuckel::setTemperature().
void getActivityConcentrations (doublereal * c) const virtual
This method returns an array of generalized concentrations.
\(C_k\) that are defined such that \(a_k = C_k / C^0_k, \) where \(C^0_k \) is a standard concentration defined below. These generalized concentrations are used by kinetics manager classes to compute the forward and reverse rates of elementary reactions.
Parameters
c Array of generalized concentrations. The units depend upon the implementation of the reaction rate expressions within the phase.
Reimplemented from MolalityVPSSTP.
Definition at line 308 of file DebyeHuckel.cpp.
References DebyeHuckel::getActivities(), Phase::m_kk, and DebyeHuckel::standardConcentration().
doublereal standardConcentration (size_t k = 0) const virtual
Return the standard concentration for the kth species.
The standard concentration \(C^0_k \) used to normalize the activity (i.e., generalized) concentration in kinetics calculations.
For the time being, we will use the concentration of pure solvent for the the standard concentration of all species. This has the effect of making reaction rates based on the molality of species proportional to the molality of the species.
Parameters
k Optional parameter indicating the species. The default is to assume this refers to species 0.
Returns
Returns the standard Concentration in units of m3 kmol-1.
Reimplemented from MolalityVPSSTP.
Definition at line 317 of file DebyeHuckel.cpp.
References MolalityVPSSTP::m_indexSolvent, and Phase::m_speciesSize.
Referenced by DebyeHuckel::getActivityConcentrations().
void getUnitsStandardConc (double * uA, int k = 0, int sizeUA = 6) const virtual
Returns the units of the standard and generalized concentrations.
Note they have the same units, as their ratio is defined to be equal to the activity of the kth species in the solution, which is unitless.
This routine is used in print out applications where the units are needed. Usually, MKS units are assumed throughout the program and in the XML input files.
The base ThermoPhase class assigns the default quantities of (kmol/m3) for all species. Inherited classes are responsible for overriding the default values if necessary.
On return uA contains the powers of the units (MKS assumed) of the standard concentrations and generalized concentrations for the kth species.
Parameters
uA Output vector containing the units uA[0] = kmol units - default = 1 uA[1] = m units - default = -nDim(), the number of spatial dimensions in the Phase class. uA[2] = kg units - default = 0; uA[3] = Pa(pressure) units - default = 0; uA[4] = Temperature units - default = 0; uA[5] = time units - default = 0
k species index. Defaults to 0.
sizeUA output int containing the size of the vector. Currently, this is equal to 6.
Deprecated:
To be removed after Cantera 2.2.
Reimplemented from MolalityVPSSTP.
Definition at line 323 of file DebyeHuckel.cpp.
References Phase::nDim(), and Cantera::warn_deprecated().
void getActivities (doublereal * ac) const virtual
Get the array of non-dimensional activities at the current solution temperature, pressure, and solution concentration.
We resolve this function at this level by calling on the activityConcentration function. However, derived classes may want to override this default implementation.
(note solvent activity coefficient is on molar scale).
Parameters
ac Output vector of activities. Length: m_kk.
Reimplemented from MolalityVPSSTP.
Definition at line 349 of file DebyeHuckel.cpp.
References VPStandardStateTP::_updateStandardStateThermo(), MolalityVPSSTP::m_indexSolvent, Phase::m_kk, DebyeHuckel::m_lnActCoeffMolal, MolalityVPSSTP::m_molalities, Phase::moleFraction(), and DebyeHuckel::s_update_lnMolalityActCoeff().
Referenced by DebyeHuckel::getActivityConcentrations().
void getMolalityActivityCoefficients (doublereal * acMolality) const virtual
Get the array of non-dimensional molality-based activity coefficients at the current solution temperature, pressure, and solution concentration.
note solvent is on molar scale. The solvent molar based activity coefficient is returned.
Note, most of the work is done in an internal private routine
Parameters
acMolality Vector of Molality-based activity coefficients Length: m_kk
Reimplemented from MolalityVPSSTP.
Definition at line 367 of file DebyeHuckel.cpp.
References VPStandardStateTP::_updateStandardStateThermo(), DebyeHuckel::A_Debye_TP(), Phase::m_kk, DebyeHuckel::m_lnActCoeffMolal, and DebyeHuckel::s_update_lnMolalityActCoeff().
void getChemPotentials (doublereal * mu) const virtual
Get the species chemical potentials. Units: J/kmol.
This function returns a vector of chemical potentials of the species in solution.
\[ \mu_k = \mu^{\triangle}_k(T,P) + R T ln(\gamma_k^{\triangle} m_k) \]
Parameters
mu Output vector of species chemical potentials. Length: m_kk. Units: J/kmol
Reimplemented from ThermoPhase.
Definition at line 381 of file DebyeHuckel.cpp.
References Cantera::GasConstant, VPStandardStateTP::getStandardChemPotentials(), MolalityVPSSTP::m_indexSolvent, Phase::m_kk, DebyeHuckel::m_lnActCoeffMolal, MolalityVPSSTP::m_molalities, Phase::moleFraction(), DebyeHuckel::s_update_lnMolalityActCoeff(), Cantera::SmallNumber, and Phase::temperature().
Referenced by DebyeHuckel::gibbs_mole().
void getPartialMolarEnthalpies (doublereal * hbar) const virtual
Returns an array of partial molar enthalpies for the species in the mixture.
Units (J/kmol)
For this phase, the partial molar enthalpies are equal to the standard state enthalpies modified by the derivative of the molality-based activity coefficient wrt temperature
\[ \bar h_k(T,P) = h^{\triangle}_k(T,P) - R T^2 \frac{d \ln(\gamma_k^\triangle)}{dT} \]
The solvent partial molar enthalpy is equal to
\[ \bar h_o(T,P) = h^{o}_o(T,P) - R T^2 \frac{d \ln(a_o}{dT} \]
The temperature dependence of the activity coefficients currently only occurs through the temperature dependence of the Debye constant.
Parameters
hbar Output vector of species partial molar enthalpies. Length: m_kk. units are J/kmol.
Reimplemented from ThermoPhase.
Definition at line 409 of file DebyeHuckel.cpp.
References DebyeHuckel::dA_DebyedT_TP(), Cantera::GasConstant, VPStandardStateTP::getEnthalpy_RT(), DebyeHuckel::m_dlnActCoeffMolaldT, Phase::m_kk, DebyeHuckel::s_update_dlnMolalityActCoeff_dT(), DebyeHuckel::s_update_lnMolalityActCoeff(), and Phase::temperature().
Referenced by DebyeHuckel::enthalpy_mole().
void getPartialMolarEntropies (doublereal * sbar) const virtual
Returns an array of partial molar entropies of the species in the solution.
Units: J/kmol/K. Maxwell's equations provide an insight in how to calculate this (p.215 Smith and Van Ness)
\[ \frac{d\mu_i}{dT} = -\bar{s}_i \]
For this phase, the partial molar entropies are equal to the SS species entropies plus the ideal solution contribution.following contribution:
\[ \bar s_k(T,P) = \hat s^0_k(T) - R log(M0 * molality[k]) \]
\[ \bar s_{solvent}(T,P) = \hat s^0_{solvent}(T) - R ((xmolSolvent - 1.0) / xmolSolvent) \]
The reference-state pure-species entropies, \(\hat s^0_k(T) \), at the reference pressure, \(P_{ref} \), are computed by the species thermodynamic property manager. They are polynomial functions of temperature.
See Also
SpeciesThermo
Parameters
sbar Output vector of species partial molar entropies. Length = m_kk. units are J/kmol/K.
Reimplemented from ThermoPhase.
Definition at line 443 of file DebyeHuckel.cpp.
References DebyeHuckel::dA_DebyedT_TP(), Cantera::GasConstant, VPStandardStateTP::getEntropy_R(), DebyeHuckel::m_dlnActCoeffMolaldT, MolalityVPSSTP::m_indexSolvent, Phase::m_kk, DebyeHuckel::m_lnActCoeffMolal, MolalityVPSSTP::m_molalities, Phase::moleFraction(), DebyeHuckel::s_update_dlnMolalityActCoeff_dT(), DebyeHuckel::s_update_lnMolalityActCoeff(), Cantera::SmallNumber, and Phase::temperature().
Referenced by DebyeHuckel::entropy_mole().
void getPartialMolarCp (doublereal * cpbar) const virtual
Return an array of partial molar heat capacities for the species in the mixture.
Units: J/kmol/K
Parameters
cpbar Output vector of species partial molar heat capacities at constant pressure. Length = m_kk. units are J/kmol/K.
Reimplemented from ThermoPhase.
Definition at line 506 of file DebyeHuckel.cpp.
References DebyeHuckel::dA_DebyedT_TP(), Cantera::GasConstant, VPStandardStateTP::getCp_R(), DebyeHuckel::m_d2lnActCoeffMolaldT2, DebyeHuckel::m_dlnActCoeffMolaldT, Phase::m_kk, DebyeHuckel::s_update_d2lnMolalityActCoeff_dT2(), DebyeHuckel::s_update_dlnMolalityActCoeff_dT(), DebyeHuckel::s_update_lnMolalityActCoeff(), and Phase::temperature().
Referenced by DebyeHuckel::cp_mole().
void getPartialMolarVolumes (doublereal * vbar) const virtual
Return an array of partial molar volumes for the species in the mixture.
Units: m^3/kmol.
For this solution, the partial molar volumes are normally equal to theconstant species molar volumes, except when the activity coefficients depend on pressure.
The general relation is
  vbar_i = d(chemPot_i)/dP at const T, n
         = V0_i + d(Gex)/dP)_T,M
         = V0_i + RT d(lnActCoeffi)dP _T,M
Parameters
vbar Output vector of species partial molar volumes. Length = m_kk. units are m^3/kmol.
Reimplemented from ThermoPhase.
Definition at line 491 of file DebyeHuckel.cpp.
References Cantera::GasConstant, VPStandardStateTP::getStandardVolumes(), DebyeHuckel::m_dlnActCoeffMolaldP, Phase::m_kk, DebyeHuckel::s_update_dlnMolalityActCoeff_dP(), DebyeHuckel::s_update_lnMolalityActCoeff(), and Phase::temperature().
Referenced by DebyeHuckel::calcDensity().
virtual void setToEquilState (const doublereal * lambda_RT) inline virtual
This method is used by the ChemEquil equilibrium solver.
It sets the state such that the chemical potentials satisfy
\[ \frac{\mu_k}{\hat R T} = \sum_m A_{k,m} \left(\frac{\lambda_m} {\hat R T}\right) \]
where \(\lambda_m \) is the element potential of element m. The temperature is unchanged. Any phase (ideal or not) that implements this method can be equilibrated by ChemEquil.
Parameters
lambda_RT Input vector of dimensionless element potentials The length is equal to nElements().
Reimplemented from MolalityVPSSTP.
Definition at line 1026 of file DebyeHuckel.h.
void initThermo () virtual
Initialize the object's internal lengths after species are set.
Initialize. This method is provided to allow subclasses to perform any initialization required after all species have been added. For example, it might be used to resize internal work arrays that must have an entry for each species. The base class implementation does nothing, and subclasses that do not require initialization do not need to overload this method. When importing a CTML phase description, this method is called just prior to returning from function importPhase().
Cascading call sequence downwards starting with Parent.
Reimplemented from MolalityVPSSTP.
Definition at line 546 of file DebyeHuckel.cpp.
References DebyeHuckel::initLengths(), and MolalityVPSSTP::initThermo().
Referenced by DebyeHuckel::initThermoXML().
void initThermoXML (XML_Node & phaseNode, const std::string & id) virtual
Process the XML file after species are set up.
This gets called from importPhase(). It processes the XML file after the species are set up. This is the main routine for reading in activity coefficient parameters.
Parameters
phaseNode This object must be the phase node of a complete XML tree description of the phase, including all of the species data. In other words while "phase" must point to an XML phase object, it must have sibling nodes "speciesData" that describe the species in the phase.
id ID of the phase. If nonnull, a check is done to see if phaseNode is pointing to the phase with the correct id.
Reimplemented from VPStandardStateTP.
Definition at line 581 of file DebyeHuckel.cpp.
References XML_Node::attrib(), Cantera::cEST_solvent, Phase::charge(), XML_Node::child(), PDSS_Water::density(), XML_Node::findByAttr(), XML_Node::findByName(), Cantera::fpValue(), Cantera::get_XML_NameID(), Cantera::getChildValue(), Cantera::getFloat(), Cantera::getMap(), Cantera::getMatrixValues(), Cantera::getStringArray(), XML_Node::hasAttrib(), XML_Node::hasChild(), XML_Node::id(), DebyeHuckel::initThermo(), Cantera::interp_est(), Cantera::lowercase(), DebyeHuckel::m_A_Debye, DebyeHuckel::m_Aionic, DebyeHuckel::m_B_Debye, DebyeHuckel::m_B_Dot, DebyeHuckel::m_Beta_ij, DebyeHuckel::m_electrolyteSpeciesType, DebyeHuckel::m_form_A_Debye, DebyeHuckel::m_formDH, DebyeHuckel::m_formGC, MolalityVPSSTP::m_indexSolvent, Phase::m_kk, DebyeHuckel::m_maxIionicStrength, Phase::m_speciesCharge, DebyeHuckel::m_speciesCharge_Stoich, Phase::m_speciesSize, DebyeHuckel::m_useHelgesonFixedForm, DebyeHuckel::m_waterProps, DebyeHuckel::m_waterSS, PDSS::molecularWeight(), Cantera::npos, Cantera::OneAtm, XML_Node::root(), PDSS_Water::setState_TP(), MolalityVPSSTP::setStateFromXML(), ThermoPhase::speciesData(), Phase::speciesIndex(), Phase::speciesName(), Phase::speciesNames(), and Cantera::toSI().
double A_Debye_TP (double temperature = -1.0, double pressure = -1.0) const virtual
Return the Debye Huckel constant as a function of temperature and pressure (Units = sqrt(kg/gmol))
The default is to assume that it is constant, given in the initialization process, and stored in the member double, m_A_Debye. Optionally, a full water treatment may be employed that makes \(A_{Debye} \) a full function of T and P.
\[ A_{Debye} = \frac{F e B_{Debye}}{8 \pi \epsilon R T} {\left(C_o \tilde{M}_o \right)}^{1/2} \]
where
\[ B_{Debye} = \frac{F} {{(\frac{\epsilon R T}{2})}^{1/2}} \]
Therefore:
\[ A_{Debye} = \frac{1}{8 \pi} {\left(\frac{2 N_a \rho_o}{1000}\right)}^{1/2} {\left(\frac{N_a e^2}{\epsilon R T }\right)}^{3/2} \]
where
Units = sqrt(kg/gmol)
\(N_a \) is Avogadro's number
\(\rho_w \) is the density of water
\(e \) is the electronic charge
\(\epsilon = K \epsilon_o \) is the permittivity of water
\(K \) is the dielectric constant of water,
\(\epsilon_o \) is the permittivity of free space.
\(\rho_o \) is the density of the solvent in its standard state.
Nominal value at 298 K and 1 atm = 1.172576 (kg/gmol)1/2 based on:
\(\epsilon / \epsilon_0 \) = 78.54 (water at 25C)
T = 298.15 K
B_Debye = 3.28640E9 (kg/gmol)1/2 m-1
Parameters
temperature Temperature in kelvin. Defaults to -1, in which case the temperature of the phase is assumed.
pressure Pressure (Pa). Defaults to -1, in which case the pressure of the phase is assumed.
Definition at line 1081 of file DebyeHuckel.cpp.
References WaterProps::ADebye(), DebyeHuckel::m_A_Debye, DebyeHuckel::m_form_A_Debye, DebyeHuckel::m_waterProps, DebyeHuckel::pressure(), and Phase::temperature().
Referenced by DebyeHuckel::getMolalityActivityCoefficients(), and DebyeHuckel::s_update_lnMolalityActCoeff().
double dA_DebyedT_TP (double temperature = -1.0, double pressure = -1.0) const virtual
Value of the derivative of the Debye Huckel constant with respect to temperature.
This is a function of temperature and pressure. See A_Debye_TP() for a definition of \(A_{Debye} \).
Units = sqrt(kg/gmol) K-1
Parameters
temperature Temperature in kelvin. Defaults to -1, in which case the temperature of the phase is assumed.
pressure Pressure (Pa). Defaults to -1, in which case the pressure of the phase is assumed.
Definition at line 1107 of file DebyeHuckel.cpp.
References WaterProps::ADebye(), DebyeHuckel::m_form_A_Debye, DebyeHuckel::m_waterProps, DebyeHuckel::pressure(), and Phase::temperature().
Referenced by DebyeHuckel::getPartialMolarCp(), DebyeHuckel::getPartialMolarEnthalpies(), DebyeHuckel::getPartialMolarEntropies(), DebyeHuckel::s_update_d2lnMolalityActCoeff_dT2(), and DebyeHuckel::s_update_dlnMolalityActCoeff_dT().
double d2A_DebyedT2_TP (double temperature = -1.0, double pressure = -1.0) const virtual
Value of the 2nd derivative of the Debye Huckel constant with respect to temperature as a function of temperature and pressure.
This is a function of temperature and pressure. See A_Debye_TP() for a definition of \(A_{Debye} \).
Units = sqrt(kg/gmol) K-2
Parameters
temperature Temperature in kelvin. Defaults to -1, in which case the temperature of the phase is assumed.
pressure Pressure (Pa). Defaults to -1, in which case the pressure of the phase is assumed.
Definition at line 1131 of file DebyeHuckel.cpp.
References WaterProps::ADebye(), DebyeHuckel::m_form_A_Debye, DebyeHuckel::m_waterProps, DebyeHuckel::pressure(), and Phase::temperature().
Referenced by DebyeHuckel::s_update_d2lnMolalityActCoeff_dT2().
double dA_DebyedP_TP (double temperature = -1.0, double pressure = -1.0) const virtual
Value of the derivative of the Debye Huckel constant with respect to pressure, as a function of temperature and pressure.
This is a function of temperature and pressure. See A_Debye_TP() for a definition of \(A_{Debye} \).
Units = sqrt(kg/gmol) Pa-1
Parameters
temperature Temperature in kelvin. Defaults to -1, in which case the temperature of the phase is assumed.
pressure Pressure (Pa). Defaults to -1, in which case the pressure of the phase is assumed.
Definition at line 1155 of file DebyeHuckel.cpp.
References WaterProps::ADebye(), DebyeHuckel::m_form_A_Debye, DebyeHuckel::m_waterProps, DebyeHuckel::pressure(), and Phase::temperature().
Referenced by DebyeHuckel::s_update_dlnMolalityActCoeff_dP().
double AionicRadius (int k = 0) const
Reports the ionic radius of the kth species.
Parameters
k species index.
Definition at line 1183 of file DebyeHuckel.cpp.
References DebyeHuckel::m_Aionic.
int formDH () const inline
Returns the form of the Debye-Huckel parameterization used.
Definition at line 1178 of file DebyeHuckel.h.
References DebyeHuckel::m_formDH.
Array2D& get_Beta_ij () inline
Returns a reference to M_Beta_ij.
Definition at line 1183 of file DebyeHuckel.h.
References DebyeHuckel::m_Beta_ij.
double _nonpolarActCoeff (double IionicMolality) const private
Static function that implements the non-polar species salt-out modifications.
Returns the calculated activity coefficients.
Parameters
IionicMolality Value of the ionic molality (sqrt(gmol/kg))
Definition at line 1214 of file DebyeHuckel.cpp.
References DebyeHuckel::m_npActCoeff.
Referenced by DebyeHuckel::s_update_lnMolalityActCoeff().
double _osmoticCoeffHelgesonFixedForm () const private
Formula for the osmotic coefficient that occurs in the GWB.
It is originally from Helgeson for a variable NaCl brine. It's to be used with extreme caution.
Definition at line 1224 of file DebyeHuckel.cpp.
References DebyeHuckel::m_A_Debye, and DebyeHuckel::m_IionicMolalityStoich.
Referenced by DebyeHuckel::_lnactivityWaterHelgesonFixedForm().
double _lnactivityWaterHelgesonFixedForm () const private
Formula for the log of the water activity that occurs in the GWB.
It is originally from Helgeson for a variable NaCl brine. It's to be used with extreme caution.
Definition at line 1243 of file DebyeHuckel.cpp.
References DebyeHuckel::_osmoticCoeffHelgesonFixedForm(), MolalityVPSSTP::calcMolalities(), MolalityVPSSTP::m_indexSolvent, Phase::m_kk, DebyeHuckel::m_maxIionicStrength, MolalityVPSSTP::m_Mnaught, and MolalityVPSSTP::m_molalities.
Referenced by DebyeHuckel::s_update_lnMolalityActCoeff().
void initLengths () private
Initialize the internal lengths.
This internal function adjusts the lengths of arrays based on the number of species.
Definition at line 1192 of file DebyeHuckel.cpp.
References DebyeHuckel::m_Aionic, DebyeHuckel::m_B_Dot, DebyeHuckel::m_Beta_ij, DebyeHuckel::m_d2lnActCoeffMolaldT2, DebyeHuckel::m_dlnActCoeffMolaldP, DebyeHuckel::m_dlnActCoeffMolaldT, DebyeHuckel::m_electrolyteSpeciesType, DebyeHuckel::m_formDH, Phase::m_kk, DebyeHuckel::m_lnActCoeffMolal, DebyeHuckel::m_pp, Phase::m_speciesSize, DebyeHuckel::m_tmpV, and Array2D::resize().
Referenced by DebyeHuckel::initThermo().
void s_update_lnMolalityActCoeff () const private
Calculate the log activity coefficients.
This function updates the internally stored natural logarithm of the molality activity coefficients. This is the main routine for implementing the activity coefficient formulation.
Definition at line 1262 of file DebyeHuckel.cpp.
References DebyeHuckel::_lnactivityWaterHelgesonFixedForm(), DebyeHuckel::_nonpolarActCoeff(), DebyeHuckel::A_Debye_TP(), MolalityVPSSTP::calcMolalities(), DebyeHuckel::m_A_Debye, DebyeHuckel::m_Aionic, DebyeHuckel::m_B_Debye, DebyeHuckel::m_B_Dot, DebyeHuckel::m_Beta_ij, DebyeHuckel::m_electrolyteSpeciesType, DebyeHuckel::m_formDH, DebyeHuckel::m_IionicMolality, DebyeHuckel::m_IionicMolalityStoich, MolalityVPSSTP::m_indexSolvent, Phase::m_kk, DebyeHuckel::m_lnActCoeffMolal, DebyeHuckel::m_maxIionicStrength, MolalityVPSSTP::m_Mnaught, MolalityVPSSTP::m_molalities, Phase::m_speciesCharge, DebyeHuckel::m_speciesCharge_Stoich, DebyeHuckel::m_useHelgesonFixedForm, Phase::moleFraction(), and Array2D::value().
Referenced by DebyeHuckel::getActivities(), DebyeHuckel::getChemPotentials(), DebyeHuckel::getMolalityActivityCoefficients(), DebyeHuckel::getPartialMolarCp(), DebyeHuckel::getPartialMolarEnthalpies(), DebyeHuckel::getPartialMolarEntropies(), and DebyeHuckel::getPartialMolarVolumes().
void s_update_dlnMolalityActCoeff_dT () const private
Calculation of temperature derivative of activity coefficient.
Using internally stored values, this function calculates the temperature derivative of the logarithm of the activity coefficient for all species in the mechanism.
We assume that the activity coefficients are current in this routine
The solvent activity coefficient is on the molality scale. Its derivative is too.
Definition at line 1513 of file DebyeHuckel.cpp.
References DebyeHuckel::dA_DebyedT_TP(), DebyeHuckel::m_A_Debye, DebyeHuckel::m_Aionic, DebyeHuckel::m_B_Debye, DebyeHuckel::m_dlnActCoeffMolaldT, DebyeHuckel::m_formDH, DebyeHuckel::m_IionicMolality, MolalityVPSSTP::m_indexSolvent, Phase::m_kk, DebyeHuckel::m_lnActCoeffMolal, MolalityVPSSTP::m_Mnaught, MolalityVPSSTP::m_molalities, Phase::m_speciesCharge, and Phase::moleFraction().
Referenced by DebyeHuckel::getPartialMolarCp(), DebyeHuckel::getPartialMolarEnthalpies(), and DebyeHuckel::getPartialMolarEntropies().
void s_update_d2lnMolalityActCoeff_dT2 () const private
Calculate the temperature 2nd derivative of the activity coefficient.
Using internally stored values, this function calculates the temperature 2nd derivative of the logarithm of the activity coefficient for all species in the mechanism.
We assume that the activity coefficients are current in this routine
solvent activity coefficient is on the molality scale. Its derivatives are too.
Definition at line 1639 of file DebyeHuckel.cpp.
References DebyeHuckel::d2A_DebyedT2_TP(), DebyeHuckel::dA_DebyedT_TP(), DebyeHuckel::m_A_Debye, DebyeHuckel::m_Aionic, DebyeHuckel::m_B_Debye, DebyeHuckel::m_d2lnActCoeffMolaldT2, DebyeHuckel::m_formDH, DebyeHuckel::m_IionicMolality, MolalityVPSSTP::m_indexSolvent, Phase::m_kk, DebyeHuckel::m_lnActCoeffMolal, MolalityVPSSTP::m_Mnaught, MolalityVPSSTP::m_molalities, Phase::m_speciesCharge, and Phase::moleFraction().
Referenced by DebyeHuckel::getPartialMolarCp().
void s_update_dlnMolalityActCoeff_dP () const private
Calculate the pressure derivative of the activity coefficient.
Using internally stored values, this function calculates the pressure derivative of the logarithm of the activity coefficient for all species in the mechanism.
We assume that the activity coefficients, molalities, and A_Debye are current.
solvent activity coefficient is on the molality scale. Its derivatives are too.
Definition at line 1760 of file DebyeHuckel.cpp.
References DebyeHuckel::dA_DebyedP_TP(), DebyeHuckel::m_A_Debye, DebyeHuckel::m_Aionic, DebyeHuckel::m_B_Debye, DebyeHuckel::m_dlnActCoeffMolaldP, DebyeHuckel::m_electrolyteSpeciesType, DebyeHuckel::m_formDH, DebyeHuckel::m_IionicMolality, MolalityVPSSTP::m_indexSolvent, Phase::m_kk, DebyeHuckel::m_lnActCoeffMolal, MolalityVPSSTP::m_Mnaught, MolalityVPSSTP::m_molalities, Phase::m_speciesCharge, and Phase::moleFraction().
Referenced by DebyeHuckel::getPartialMolarVolumes().
Member Data Documentation
int m_formDH protected
form of the Debye-Huckel parameterization used in the model.
The options are described at the top of this document, and in the general documentation. The list is repeated here:
DHFORM_DILUTE_LIMIT = 0 (default) DHFORM_BDOT_AK = 1 DHFORM_BDOT_AUNIFORM = 2 DHFORM_BETAIJ = 3 DHFORM_PITZER_BETAIJ = 4
Definition at line 1225 of file DebyeHuckel.h.
Referenced by DebyeHuckel::formDH(), DebyeHuckel::initLengths(), DebyeHuckel::initThermoXML(), DebyeHuckel::operator=(), DebyeHuckel::s_update_d2lnMolalityActCoeff_dT2(), DebyeHuckel::s_update_dlnMolalityActCoeff_dP(), DebyeHuckel::s_update_dlnMolalityActCoeff_dT(), and DebyeHuckel::s_update_lnMolalityActCoeff().
int m_formGC protected
Format for the generalized concentration:
0 = unity 1 = molar_volume 2 = solvent_volume (default)
The generalized concentrations can have three different forms depending on the value of the member attribute m_formGC, which is supplied in the constructor.
m_formGC GeneralizedConc StandardConc
0 X_k 1.0
1 X_k / V_k 1.0 / V_k
2 X_k / V_N 1.0 / V_N
The value and form of the generalized concentration will affect reaction rate constants involving species in this phase.
(HKM Note: Using option #1 may lead to spurious results and has been included only with warnings. The reason is that it molar volumes of electrolytes may often be negative. The molar volume of H+ is defined to be zero too. Either options 0 or 2 are the appropriate choice. Option 0 leads to bulk reaction rate constants which have units of s-1. Option 2 leads to bulk reaction rate constants for bimolecular rxns which have units of m-3 kmol-1 s-1.)
Definition at line 1256 of file DebyeHuckel.h.
Referenced by DebyeHuckel::eosType(), DebyeHuckel::initThermoXML(), and DebyeHuckel::operator=().
vector_int m_electrolyteSpeciesType protected
Vector containing the electrolyte species type.
The possible types are:
solvent
Charged Species
weakAcidAssociated
strongAcidAssociated
polarNeutral
nonpolarNeutral
Definition at line 1269 of file DebyeHuckel.h.
Referenced by DebyeHuckel::initLengths(), DebyeHuckel::initThermoXML(), DebyeHuckel::s_update_dlnMolalityActCoeff_dP(), and DebyeHuckel::s_update_lnMolalityActCoeff().
vector_fp m_Aionic protected
a_k = Size of the ionic species in the DH formulation units = meters
Definition at line 1275 of file DebyeHuckel.h.
Referenced by DebyeHuckel::AionicRadius(), DebyeHuckel::initLengths(), DebyeHuckel::initThermoXML(), DebyeHuckel::operator=(), DebyeHuckel::s_update_d2lnMolalityActCoeff_dT2(), DebyeHuckel::s_update_dlnMolalityActCoeff_dP(), DebyeHuckel::s_update_dlnMolalityActCoeff_dT(), and DebyeHuckel::s_update_lnMolalityActCoeff().
double m_IionicMolality mutable protected
Current value of the ionic strength on the molality scale.
Definition at line 1278 of file DebyeHuckel.h.
Referenced by DebyeHuckel::operator=(), DebyeHuckel::s_update_d2lnMolalityActCoeff_dT2(), DebyeHuckel::s_update_dlnMolalityActCoeff_dP(), DebyeHuckel::s_update_dlnMolalityActCoeff_dT(), and DebyeHuckel::s_update_lnMolalityActCoeff().
double m_maxIionicStrength protected
Maximum value of the ionic strength allowed in the calculation of the activity coefficients.
Definition at line 1284 of file DebyeHuckel.h.
Referenced by DebyeHuckel::_lnactivityWaterHelgesonFixedForm(), DebyeHuckel::initThermoXML(), DebyeHuckel::operator=(), and DebyeHuckel::s_update_lnMolalityActCoeff().
bool m_useHelgesonFixedForm
If true, then the fixed for of Helgeson's activity for water is used instead of the rigorous form obtained from Gibbs-Duhem relation.
This should be used with caution, and is really only included as a validation exercise.
Definition at line 1295 of file DebyeHuckel.h.
Referenced by DebyeHuckel::initThermoXML(), DebyeHuckel::operator=(), and DebyeHuckel::s_update_lnMolalityActCoeff().
double m_IionicMolalityStoich mutable protected
Stoichiometric ionic strength on the molality scale.
Definition at line 1299 of file DebyeHuckel.h.
Referenced by DebyeHuckel::_osmoticCoeffHelgesonFixedForm(), DebyeHuckel::operator=(), and DebyeHuckel::s_update_lnMolalityActCoeff().
int m_form_A_Debye
Form of the constant outside the Debye-Huckel term called A.
It's normally a function of temperature and pressure. However, it can be set from the input file in order to aid in numerical comparisons. Acceptable forms:
  A_DEBYE_CONST  0
  A_DEBYE_WATER  1
The A_DEBYE_WATER form may be used for water solvents with needs to cover varying temperatures and pressures. Note, the dielectric constant of water is a relatively strong function of T, and its variability must be accounted for,
Definition at line 1318 of file DebyeHuckel.h.
Referenced by DebyeHuckel::A_Debye_TP(), DebyeHuckel::d2A_DebyedT2_TP(), DebyeHuckel::dA_DebyedP_TP(), DebyeHuckel::dA_DebyedT_TP(), DebyeHuckel::initThermoXML(), and DebyeHuckel::operator=().
double m_A_Debye mutable protected
Current value of the Debye Constant, A_Debye.
A_Debye -> this expression appears on the top of the ln actCoeff term in the general Debye-Huckel expression It depends on temperature and pressure.
A_Debye = (F e B_Debye) / (8 Pi epsilon R T)
Units = sqrt(kg/gmol)
Nominal value(298K, atm) = 1.172576 sqrt(kg/gmol) based on: epsilon/epsilon_0 = 78.54 (water at 25C) T = 298.15 K B_Debye = 3.28640E9 sqrt(kg/gmol)/m
note in Pitzer's nomenclature, A_phi = A_Debye/3.0
Definition at line 1341 of file DebyeHuckel.h.
Referenced by DebyeHuckel::_osmoticCoeffHelgesonFixedForm(), DebyeHuckel::A_Debye_TP(), DebyeHuckel::initThermoXML(), DebyeHuckel::operator=(), DebyeHuckel::s_update_d2lnMolalityActCoeff_dT2(), DebyeHuckel::s_update_dlnMolalityActCoeff_dP(), DebyeHuckel::s_update_dlnMolalityActCoeff_dT(), and DebyeHuckel::s_update_lnMolalityActCoeff().
double m_B_Debye protected
Current value of the constant that appears in the denominator.
B_Debye -> this expression appears on the bottom of the ln actCoeff term in the general Debye-Huckel expression It depends on temperature
B_Bebye = F / sqrt(epsilon R T / 2)
Units = sqrt(kg/gmol) / m
Nominal value = 3.28640E9 sqrt(kg/gmol) / m based on: epsilon/epsilon_0 = 78.54 (water at 25C) T = 298.15 K
Definition at line 1360 of file DebyeHuckel.h.
Referenced by DebyeHuckel::initThermoXML(), DebyeHuckel::operator=(), DebyeHuckel::s_update_d2lnMolalityActCoeff_dT2(), DebyeHuckel::s_update_dlnMolalityActCoeff_dP(), DebyeHuckel::s_update_dlnMolalityActCoeff_dT(), and DebyeHuckel::s_update_lnMolalityActCoeff().
vector_fp m_B_Dot protected
Array of B_Dot values.
This expression is an extension of the Debye-Huckel expression used in some formulations to extend DH to higher molalities. B_dot is specific to the major ionic pair.
Definition at line 1368 of file DebyeHuckel.h.
Referenced by DebyeHuckel::initLengths(), DebyeHuckel::initThermoXML(), DebyeHuckel::operator=(), and DebyeHuckel::s_update_lnMolalityActCoeff().
vector_fp m_npActCoeff protected
These are coefficients to describe the increase in activity coeff for non-polar molecules due to the electrolyte becoming stronger (the so-called salt-out effect)
Definition at line 1375 of file DebyeHuckel.h.
Referenced by DebyeHuckel::_nonpolarActCoeff(), DebyeHuckel::DebyeHuckel(), and DebyeHuckel::operator=().
PDSS_Water* m_waterSS protected
Pointer to the Water standard state object.
derived from the equation of state for water.
Definition at line 1382 of file DebyeHuckel.h.
Referenced by DebyeHuckel::calcDensity(), DebyeHuckel::initThermoXML(), and DebyeHuckel::operator=().
double m_densWaterSS protected
Storage for the density of water's standard state.
Density depends on temperature and pressure.
Definition at line 1388 of file DebyeHuckel.h.
Referenced by DebyeHuckel::calcDensity(), and DebyeHuckel::operator=().
WaterProps* m_waterProps protected
Pointer to the water property calculator.
Definition at line 1391 of file DebyeHuckel.h.
Referenced by DebyeHuckel::A_Debye_TP(), DebyeHuckel::d2A_DebyedT2_TP(), DebyeHuckel::dA_DebyedP_TP(), DebyeHuckel::dA_DebyedT_TP(), DebyeHuckel::initThermoXML(), DebyeHuckel::operator=(), and DebyeHuckel::~DebyeHuckel().
vector_fp m_pp mutable protected
Temporary array used in equilibrium calculations.
Definition at line 1394 of file DebyeHuckel.h.
Referenced by DebyeHuckel::calcDensity(), DebyeHuckel::initLengths(), and DebyeHuckel::operator=().
vector_fp m_tmpV mutable protected
vector of size m_kk, used as a temporary holding area.
Definition at line 1397 of file DebyeHuckel.h.
Referenced by DebyeHuckel::calcDensity(), DebyeHuckel::cp_mole(), DebyeHuckel::enthalpy_mole(), DebyeHuckel::entropy_mole(), DebyeHuckel::gibbs_mole(), DebyeHuckel::initLengths(), and DebyeHuckel::operator=().
vector_fp m_speciesCharge_Stoich protected
Stoichiometric species charge -> This is for calculations of the ionic strength which ignore ion-ion pairing into neutral molecules.
The Stoichiometric species charge is the charge of one of the ion that would occur if the species broke into two charged ion pairs. NaCl -> m_speciesCharge_Stoich = -1; HSO4- -> H+ + SO42- = -2 -> The other charge is calculated. For species that aren't ion pairs, it's equal to the m_speciesCharge[] value.
Definition at line 1411 of file DebyeHuckel.h.
Referenced by DebyeHuckel::initThermoXML(), DebyeHuckel::operator=(), and DebyeHuckel::s_update_lnMolalityActCoeff().
Array2D m_Beta_ij protected
Array of 2D data used in the DHFORM_BETAIJ formulation Beta_ij.value(i,j) is the coefficient of the jth species for the specification of the chemical potential of the ith species.
Definition at line 1419 of file DebyeHuckel.h.
Referenced by DebyeHuckel::get_Beta_ij(), DebyeHuckel::initLengths(), DebyeHuckel::initThermoXML(), DebyeHuckel::operator=(), and DebyeHuckel::s_update_lnMolalityActCoeff().
vector_fp m_lnActCoeffMolal mutable protected
Logarithm of the activity coefficients on the molality scale.
mutable because we change this if the composition or temperature or pressure changes.
Definition at line 1426 of file DebyeHuckel.h.
Referenced by DebyeHuckel::getActivities(), DebyeHuckel::getChemPotentials(), DebyeHuckel::getMolalityActivityCoefficients(), DebyeHuckel::getPartialMolarEntropies(), DebyeHuckel::initLengths(), DebyeHuckel::operator=(), DebyeHuckel::s_update_d2lnMolalityActCoeff_dT2(), DebyeHuckel::s_update_dlnMolalityActCoeff_dP(), DebyeHuckel::s_update_dlnMolalityActCoeff_dT(), and DebyeHuckel::s_update_lnMolalityActCoeff().
vector_fp m_dlnActCoeffMolaldT mutable protected
Derivative of log act coeff wrt T.
Definition at line 1429 of file DebyeHuckel.h.
Referenced by DebyeHuckel::getPartialMolarCp(), DebyeHuckel::getPartialMolarEnthalpies(), DebyeHuckel::getPartialMolarEntropies(), DebyeHuckel::initLengths(), and DebyeHuckel::s_update_dlnMolalityActCoeff_dT().
vector_fp m_d2lnActCoeffMolaldT2 mutable protected
2nd Derivative of log act coeff wrt T
Definition at line 1432 of file DebyeHuckel.h.
Referenced by DebyeHuckel::getPartialMolarCp(), DebyeHuckel::initLengths(), DebyeHuckel::operator=(), and DebyeHuckel::s_update_d2lnMolalityActCoeff_dT2().
vector_fp m_dlnActCoeffMolaldP mutable protected
Derivative of log act coeff wrt P.
Definition at line 1435 of file DebyeHuckel.h.
Referenced by DebyeHuckel::getPartialMolarVolumes(), DebyeHuckel::initLengths(), and DebyeHuckel::s_update_dlnMolalityActCoeff_dP().
The documentation for this class was generated from the following files:
DebyeHuckel.h
DebyeHuckel.cpp