Cantera: ExtraGlobalRxn Class Reference
ExtraGlobalRxn Class Reference
Class describing an extra global reaction, which is defined as a linear combination of actuals reactions, global or mass-action, creating a global stoichiometric result.
#include <ExtraGlobalRxn.h>
Public Member Functions
ExtraGlobalRxn (Kinetics *k_ptr)
Constructor takes a default kinetics pointer.
virtual ~ExtraGlobalRxn ()
Destructor.
void setupElemRxnVector (double *RxnVector, int specialSpecies=-1)
std::string reactionString ()
double deltaSpecValue (double *speciesVectorProperty)
std::vector< int > & reactants ()
std::vector< int > & products ()
bool isReversible ()
double ROPValue (double *ROPKinVector)
double FwdROPValue (double *FwdROPElemKinVector, double *RevROPElemKinVector)
double RevROPValue (double *FwdROPElemKinVector, double *RevROPElemKinVector)
double reactantStoichCoeff (int kKin)
double productStoichCoeff (int kKin)
double deltaRxnVecValue (double *rxnVectorProperty)
Public Attributes
bool m_ThisIsASurfaceRxn
Cantera::Kinetics * m_kinetics
This kinetics operator is associated with just one homogeneous phase, associated with tpList[0] phase.
Cantera::InterfaceKinetics * m_InterfaceKinetics
This kinetics operator is associated with multiple homogeneous and surface phases.
int m_nKinSpecies
int m_nReactants
Number of reactants in the global reaction.
std::vector< int > m_Reactants
Vector of reactants that make up the global reaction.
std::vector< doublereal > m_ReactantStoich
Vector of reactant stoichiometries that make up the global reaction.
int m_nProducts
std::vector< int > m_Products
std::vector< doublereal > m_ProductStoich
int m_nNetSpecies
std::vector< int > m_NetSpecies
std::vector< doublereal > m_netStoich
int m_nRxns
std::vector< doublereal > m_ElemRxnVector
int m_SpecialSpecies
bool m_SpecialSpeciesProduct
int m_SS_index
int iphaseKin
bool m_ok
bool m_reversible
Detailed Description
Class describing an extra global reaction, which is defined as a linear combination of actuals reactions, global or mass-action, creating a global stoichiometric result.
This is useful for defining thermodynamics of global processes that occur on a surface or in a homogeneous phase.
The class is set up via the function setupElemRxnVector(RxnVector, specialSpecies) which defines the vector of stoichiometric coefficients representing the base reaction to combine in order to achieve the global result that's to be calculated. specialSpecies is the index of the species within the kinetics object that is used to identify the global reaction. Rates of progress are defined in terms of the production rate of the special species.
Deprecated:
Unfinished implementation to be removed after Cantera 2.2.
Definition at line 35 of file ExtraGlobalRxn.h.
Constructor & Destructor Documentation
ExtraGlobalRxn (Kinetics * k_ptr)
Constructor takes a default kinetics pointer.
Parameters
[in] k_ptr Pointer to a Kinetics class that will be used as the basis for constructing this class.
Definition at line 86 of file ExtraGlobalRxn.cpp.
References ExtraGlobalRxn::m_InterfaceKinetics, ExtraGlobalRxn::m_kinetics, Kinetics::nReactions(), Kinetics::nTotalSpecies(), and Cantera::warn_deprecated().
virtual ~ExtraGlobalRxn () inline virtual
Destructor.
Definition at line 47 of file ExtraGlobalRxn.h.
Member Data Documentation
Cantera::Kinetics* m_kinetics
This kinetics operator is associated with just one homogeneous phase, associated with tpList[0] phase.
Kinetics object pointer
Definition at line 72 of file ExtraGlobalRxn.h.
Referenced by ExtraGlobalRxn::ExtraGlobalRxn().
Cantera::InterfaceKinetics* m_InterfaceKinetics
This kinetics operator is associated with multiple homogeneous and surface phases.
This object owns the Kinetics object
Definition at line 79 of file ExtraGlobalRxn.h.
Referenced by ExtraGlobalRxn::ExtraGlobalRxn().
int m_nReactants
Number of reactants in the global reaction.
Definition at line 84 of file ExtraGlobalRxn.h.
std::vector<int> m_Reactants
Vector of reactants that make up the global reaction.
This is a list of reactants using the kinetic species index
Definition at line 90 of file ExtraGlobalRxn.h.
std::vector<doublereal> m_ReactantStoich
Vector of reactant stoichiometries that make up the global reaction.
This is a list of reactant stoichiometries. The species index is given in the member m_Reactants using the kinetic species index.
Definition at line 97 of file ExtraGlobalRxn.h.
The documentation for this class was generated from the following files:
ExtraGlobalRxn.h
ExtraGlobalRxn.cpp