Cantera: PlogReaction Class Reference
PlogReaction Class Reference
A pressure-dependent reaction parameterized by logarithmically interpolating between Arrhenius rate expressions at various pressures.
#include <Reaction.h>
Public Member Functions
PlogReaction (const Composition &reactants, const Composition &products, const Plog &rate)
virtual void validate ()
Ensure that the rate constant and other parameters for this reaction are valid.
Public Member Functions inherited from Reaction
Reaction (int type)
Reaction (int type, const Composition &reactants, const Composition &products)
virtual std::string reactantString () const
The reactant side of the chemical equation for this reaction.
virtual std::string productString () const
The product side of the chemical equation for this reaction.
std::string equation () const
The chemical equation for this reaction.
Public Attributes
Plog rate
Public Attributes inherited from Reaction
int reaction_type
Type of the reaction.
Composition reactants
Reactant species and stoichiometric coefficients.
Composition products
Product species and stoichiometric coefficients.
Composition orders
Forward reaction order with respect to specific species.
std::string id
An identification string for the reaction, used in some filtering operations.
bool reversible
True if the current reaction is reversible. False otherwise.
bool duplicate
True if the current reaction is marked as duplicate.
bool allow_nonreactant_orders
True if reaction orders can be specified for non-reactant species.
bool allow_negative_orders
True if negative reaction orders are allowed. Default is false.
Detailed Description
A pressure-dependent reaction parameterized by logarithmically interpolating between Arrhenius rate expressions at various pressures.
Definition at line 166 of file Reaction.h.
Member Function Documentation
void validate () virtual
Ensure that the rate constant and other parameters for this reaction are valid.
Reimplemented from Reaction.
Definition at line 450 of file Reaction.cpp.
References Reaction::equation(), Reaction::validate(), and Plog::validate().
The documentation for this class was generated from the following files:
Reaction.h
Reaction.cpp