Cantera: DenseMatrix Class Reference
DenseMatrix Class Reference
Numerical Utilities within Cantera
A class for full (non-sparse) matrices with Fortran-compatible data storage, which adds matrix operations to class Array2D.
#include <DenseMatrix.h>
Public Member Functions
DenseMatrix ()
Default Constructor.
DenseMatrix (size_t n, size_t m, doublereal v=0.0)
Constructor.
DenseMatrix (const DenseMatrix &y)
Copy constructor.
DenseMatrix & operator= (const DenseMatrix &y)
Assignment operator.
void resize (size_t n, size_t m, doublereal v=0.0)
Resize the matrix.
virtual doublereal *const * colPts ()
const doublereal *const * const_colPts () const
Return a const vector of const pointers to the columns.
virtual void mult (const double *b, double *prod) const
virtual void mult (const DenseMatrix &b, DenseMatrix &prod) const
Multiply A*B and write result to prod.
virtual void leftMult (const double *const b, double *const prod) const
Left-multiply the matrix by transpose(b), and write the result to prod.
vector_int & ipiv ()
Return a changeable value of the pivot vector.
const vector_int & ipiv () const
Return a changeable value of the pivot vector.
Public Member Functions inherited from Array2D
Array2D ()
Default constructor.
Array2D (const size_t m, const size_t n, const doublereal v=0.0)
Constructor.
Array2D (const size_t m, const size_t n, const doublereal *values)
Constructor.
Array2D (const Array2D &y)
Copy constructor.
Array2D & operator= (const Array2D &y)
assignment operator
void resize (size_t n, size_t m, doublereal v=0.0)
Resize the array, and fill the new entries with 'v'.
void copyData (const Array2D &y)
Copy the data from one array into another without doing any checking.
void appendColumn (const vector_fp &c)
Append a column to the existing matrix using a std vector.
void appendColumn (const doublereal *const c)
Append a column to the existing matrix.
void setRow (size_t n, const doublereal *const rw)
Set the nth row to array rw.
void getRow (size_t n, doublereal *const rw)
Get the nth row and return it in a vector.
void setColumn (size_t m, doublereal *const col)
Set the values in column m to those in array col.
void getColumn (size_t m, doublereal *const col)
Get the values in column m.
virtual ~Array2D ()
Destructor.
void axpy (doublereal a, const Array2D &x, const Array2D &y)
Evaluate z = a*x + y.
void zero ()
Set all of the entries to zero.
doublereal & operator() (size_t i, size_t j)
Allows setting elements using the syntax A(i,j) = x.
doublereal operator() (size_t i, size_t j) const
Allows retrieving elements using the syntax x = A(i,j).
doublereal & value (size_t i, size_t j)
Returns a changeable reference to position in the matrix.
doublereal value (size_t i, size_t j) const
Returns the value of a single matrix entry.
size_t nRows () const
Number of rows.
size_t nColumns () const
Number of columns.
iterator begin ()
Return an iterator pointing to the first element.
iterator end ()
Return an iterator pointing past the last element.
const_iterator begin () const
Return a const iterator pointing to the first element.
const_iterator end () const
Return a const iterator pointing to past the last element.
vector_fp & data ()
Return a reference to the data vector.
const vector_fp & data () const
Return a const reference to the data vector.
doublereal * ptrColumn (size_t j)
Return a pointer to the top of column j, columns are contiguous in memory.
const doublereal * ptrColumn (size_t j) const
Return a const pointer to the top of column j, columns are contiguous in memory.
Public Attributes
int m_useReturnErrorCode
Error Handling Flag.
int m_printLevel
Print Level.
Protected Attributes
vector_int m_ipiv
Vector of pivots. Length is equal to the max of m and n.
std::vector< doublereal * > m_colPts
Vector of column pointers.
Protected Attributes inherited from Array2D
vector_fp m_data
Data stored in a single array.
size_t m_nrows
Number of rows.
size_t m_ncols
Number of columns.
Friends
int solve (DenseMatrix &A, double *b, size_t nrhs, size_t ldb)
Solve Ax = b. Array b is overwritten on exit with x.
int solve (DenseMatrix &A, DenseMatrix &b)
Solve Ax = b for multiple right-hand-side vectors.
int invert (DenseMatrix &A, int nn)
Additional Inherited Members
Public Types inherited from Array2D
typedef vector_fp::iterator iterator
Type definition for the iterator class that is can be used by Array2D types.
typedef vector_fp::const_iterator const_iterator
Type definition for the const_iterator class that is can be used by Array2D types.
Detailed Description
A class for full (non-sparse) matrices with Fortran-compatible data storage, which adds matrix operations to class Array2D.
The dense matrix class adds matrix operations onto the Array2D class. These matrix operations are carried out by the appropriate BLAS and LAPACK routines
Error handling from BLAS and LAPACK are handled via the following formulation. Depending on a variable, a singular matrix or other terminal error condition from LAPACK is handled by either throwing an exception of type, CELapackError, or by returning the error code condition to the calling routine.
The int variable, m_useReturnErrorCode, determines which method is used. The default value of zero means that an exception is thrown. A value of 1 means that a return code is used.
Reporting of these LAPACK error conditions is handled by the class variable m_printLevel. The default is for no reporting. If m_printLevel is nonzero, the error condition is reported to Cantera's log file.
Definition at line 71 of file DenseMatrix.h.
Constructor & Destructor Documentation
DenseMatrix ()
Default Constructor.
Definition at line 14 of file DenseMatrix.cpp.
DenseMatrix (size_t n, size_t m, doublereal v = 0.0)
Constructor.
Create an n by m matrix, and initialize all elements to v.
Parameters
n New number of rows
m New number of columns
v Default fill value. defaults to zero.
Definition at line 20 of file DenseMatrix.cpp.
References DenseMatrix::m_colPts, Array2D::m_data, DenseMatrix::m_ipiv, and Array2D::m_nrows.
DenseMatrix (const DenseMatrix & y)
Copy constructor.
Parameters
y Object to be copied
Definition at line 34 of file DenseMatrix.cpp.
References DenseMatrix::ipiv(), DenseMatrix::m_colPts, Array2D::m_data, DenseMatrix::m_ipiv, Array2D::m_ncols, and Array2D::m_nrows.
Member Function Documentation
DenseMatrix & operator= (const DenseMatrix & y)
Assignment operator.
Parameters
y Object to be copied
Definition at line 48 of file DenseMatrix.cpp.
References DenseMatrix::ipiv(), DenseMatrix::m_colPts, Array2D::m_data, DenseMatrix::m_ipiv, Array2D::m_ncols, Array2D::m_nrows, DenseMatrix::m_printLevel, DenseMatrix::m_useReturnErrorCode, and Array2D::operator=().
Referenced by SquareMatrix::operator=().
void resize (size_t n, size_t m, doublereal v = 0.0)
Resize the matrix.
Resize the matrix to n rows by m cols.
Parameters
n New number of rows
m New number of columns
v Default fill value. defaults to zero.
Definition at line 64 of file DenseMatrix.cpp.
References DenseMatrix::m_colPts, Array2D::m_data, DenseMatrix::m_ipiv, Array2D::m_ncols, Array2D::m_nrows, and Array2D::resize().
Referenced by LTI_Pairwise_Interaction::getMatrixTransProp(), LTI_StefanMaxwell_PPN::getMatrixTransProp(), MultiTransport::init(), LiquidTranInteraction::init(), MultiPhase::init(), PecosTransport::initGas(), DustyGasTransport::initialize(), LiquidTransport::initLiquid(), AqueousTransport::initLiquid(), MultiPhaseEquil::MultiPhaseEquil(), LTI_StefanMaxwell_PPN::setParameters(), TransportFactory::setupLiquidTransport(), and LiquidTransport::stefan_maxwell_solve().
const doublereal *const * const_colPts () const
Return a const vector of const pointers to the columns.
Note, the Jacobian can not be altered by this routine, and therefore the member function is const.
Returns
returns a vector of pointers to the top of the columns of the matrices.
Definition at line 81 of file DenseMatrix.cpp.
References DenseMatrix::m_colPts.
Referenced by DenseMatrix::mult().
void mult (const DenseMatrix & b, DenseMatrix & prod) const virtual
Multiply A*B and write result to prod.
Parameters
b input DenseMatrix B of size NxN
prod output output DenseMatrix prod size NxN
Reimplemented in SquareMatrix.
Definition at line 94 of file DenseMatrix.cpp.
References DenseMatrix::const_colPts(), Array2D::m_ncols, Array2D::m_nrows, Array2D::nColumns(), and Array2D::nRows().
void leftMult (const double *const b, double *const prod) const virtual
Left-multiply the matrix by transpose(b), and write the result to prod.
Parameters
b left multiply by this vector. The length must be equal to n the number of rows in the matrix.
prod Resulting vector. This is of length m, the number of columns in the matrix
Reimplemented in SquareMatrix.
Definition at line 108 of file DenseMatrix.cpp.
References Array2D::nColumns(), Array2D::nRows(), and Array2D::value().
Referenced by SquareMatrix::leftMult().
vector_int & ipiv ()
Return a changeable value of the pivot vector.
Returns
Returns a reference to the pivot vector as a vector_int
Definition at line 122 of file DenseMatrix.cpp.
References DenseMatrix::m_ipiv.
Referenced by DenseMatrix::DenseMatrix(), SquareMatrix::factor(), Cantera::invert(), DenseMatrix::operator=(), SquareMatrix::solve(), and Cantera::solve().
const vector_int& ipiv () const inline
Return a changeable value of the pivot vector.
Returns
Returns a reference to the pivot vector as a vector_int
Definition at line 149 of file DenseMatrix.h.
References DenseMatrix::m_ipiv.
Friends And Related Function Documentation
int solve (DenseMatrix & A, double * b, size_t nrhs, size_t ldb) friend
Solve Ax = b. Array b is overwritten on exit with x.
The solve class uses the LAPACK routine dgetrf to invert the m xy n matrix.
The factorization has the form A = P * L * U where P is a permutation matrix, L is lower triangular with unit diagonal elements (lower trapezoidal if m > n), and U is upper triangular (upper trapezoidal if m < n).
The system is then solved using the LAPACK routine dgetrs
Parameters
A Dense matrix to be factored
b RHS(s) to be solved.
nrhs Number of right hand sides to solve
ldb Leading dimension of b, if nrhs > 1
Definition at line 127 of file DenseMatrix.cpp.
int solve (DenseMatrix & A, DenseMatrix & b) friend
Solve Ax = b for multiple right-hand-side vectors.
Parameters
A Dense matrix to be factored
b Dense matrix of RHS's. Each column is a RHS
Definition at line 176 of file DenseMatrix.cpp.
Member Data Documentation
vector_int m_ipiv protected
Vector of pivots. Length is equal to the max of m and n.
Definition at line 155 of file DenseMatrix.h.
Referenced by DenseMatrix::DenseMatrix(), DenseMatrix::ipiv(), DenseMatrix::operator=(), and DenseMatrix::resize().
std::vector<doublereal*> m_colPts protected
Vector of column pointers.
Definition at line 158 of file DenseMatrix.h.
Referenced by DenseMatrix::const_colPts(), DenseMatrix::DenseMatrix(), DenseMatrix::operator=(), and DenseMatrix::resize().
int m_useReturnErrorCode
Error Handling Flag.
The default is to set this to 0. In this case, if a factorization is requested and can't be achieved, a CESingularMatrix exception is triggered. No return code is used, because an exception is thrown. If this is set to 1, then an exception is not thrown. Routines return with an error code, that is up to the calling routine to handle correctly. Negative return codes always throw an exception.
Definition at line 168 of file DenseMatrix.h.
Referenced by SquareMatrix::factor(), SquareMatrix::factorQR(), Cantera::invert(), DenseMatrix::operator=(), SquareMatrix::rcond(), SquareMatrix::rcondQR(), SquareMatrix::solve(), Cantera::solve(), and SquareMatrix::solveQR().
int m_printLevel
Print Level.
Printing is done to the log file using the routine writelogf().
Level of printing that is carried out. Only error conditions are printed out, if this value is nonzero.
Definition at line 176 of file DenseMatrix.h.
Referenced by SquareMatrix::factor(), SquareMatrix::factorQR(), Cantera::invert(), DenseMatrix::operator=(), SquareMatrix::rcond(), SquareMatrix::rcondQR(), SquareMatrix::solve(), Cantera::solve(), and SquareMatrix::solveQR().
The documentation for this class was generated from the following files:
DenseMatrix.h
DenseMatrix.cpp