Cantera: RxnMolChange Class Reference
RxnMolChange Class Reference
Class that includes some bookeeping entries for a reaction or a global reaction defined on a surface.
#include <RxnMolChange.h>
Public Member Functions
RxnMolChange (Cantera::Kinetics *kinPtr, int irxn)
Main constructor for the class.
~RxnMolChange ()
Destructor.
RxnMolChange (Cantera::Kinetics *kinPtr, Cantera::ExtraGlobalRxn *egr)
Constructor for the object if the object refers to a global reaction.
Public Attributes
std::vector< double > m_phaseMoleChange
Vector of mole changes for each phase in the Kinetics object due to the current reaction.
std::vector< double > m_phaseReactantMoles
std::vector< double > m_phaseProductMoles
std::vector< double > m_phaseMassChange
Vector of mass changes for each phase in the Kinetics object due to the current reaction.
std::vector< double > m_phaseChargeChange
Vector of mass changes for each phase in the Kinetics object due to the current reaction.
std::vector< int > m_phaseTypes
Vector of phase types in the reaction.
std::vector< int > m_phaseDims
Vector of phase dimensions for the reaction.
int m_nPhases
Number of phases in the kientics object.
Cantera::Kinetics * m_kinBase
Shallow pointer pointing to the kinetics object.
int m_iRxn
Reaction number within the kinetics object.
double m_ChargeTransferInRxn
Maximum change in charge of any phase due to this reaction.
double m_beta
Electrochemical beta parameter for the reaction.
Cantera::ExtraGlobalRxn * m_egr
Pointer to the specification of the global reaction.
Detailed Description
Class that includes some bookeeping entries for a reaction or a global reaction defined on a surface.
Note that all indexes refer to a specific interfacial or homogeneous kinetics object. It does not refer to the Phase list indexes.
Deprecated:
Unfinished implementation to be removed after Cantera 2.2.
Definition at line 29 of file RxnMolChange.h.
Constructor & Destructor Documentation
RxnMolChange (Cantera::Kinetics * kinPtr, int irxn)
Main constructor for the class.
Parameters
kinPtr Pointer to the kinetics base class
irxn Specific reaction index.
Definition at line 31 of file RxnMolChange.cpp.
References AssertTrace, Phase::charge(), InterfaceKinetics::electrochem_beta(), ThermoPhase::eosType(), Kinetics::kineticsSpeciesIndex(), RxnMolChange::m_beta, RxnMolChange::m_ChargeTransferInRxn, RxnMolChange::m_kinBase, RxnMolChange::m_nPhases, RxnMolChange::m_phaseChargeChange, RxnMolChange::m_phaseDims, RxnMolChange::m_phaseMassChange, RxnMolChange::m_phaseMoleChange, RxnMolChange::m_phaseTypes, Phase::molecularWeight(), Phase::nDim(), Kinetics::nPhases(), Kinetics::nReactions(), Kinetics::nTotalSpecies(), Kinetics::productStoichCoeff(), Kinetics::reactantStoichCoeff(), Kinetics::speciesPhaseIndex(), Kinetics::thermo(), and Cantera::warn_deprecated().
~RxnMolChange () inline
Destructor.
Definition at line 40 of file RxnMolChange.h.
RxnMolChange (Cantera::Kinetics * kinPtr, Cantera::ExtraGlobalRxn * egr)
Constructor for the object if the object refers to a global reaction.
Parameters
kinPtr Pointer to the kinetics base class
egr Specific reaction index.
Definition at line 95 of file RxnMolChange.cpp.
References AssertTrace, Phase::charge(), ThermoPhase::eosType(), Kinetics::kineticsSpeciesIndex(), RxnMolChange::m_beta, RxnMolChange::m_ChargeTransferInRxn, RxnMolChange::m_kinBase, RxnMolChange::m_nPhases, RxnMolChange::m_phaseChargeChange, RxnMolChange::m_phaseDims, RxnMolChange::m_phaseMassChange, RxnMolChange::m_phaseMoleChange, RxnMolChange::m_phaseTypes, Phase::molecularWeight(), Phase::nDim(), Kinetics::nPhases(), Kinetics::nTotalSpecies(), Kinetics::speciesPhaseIndex(), and Kinetics::thermo().
Member Data Documentation
std::vector<double> m_phaseMoleChange
Vector of mole changes for each phase in the Kinetics object due to the current reaction.
This is the sum of the product stoichiometric coefficient minum the reactant stoichioemtric coefficient for all the species in a phase. The index is over all the phases listed in the Kinetics object.
Definition at line 55 of file RxnMolChange.h.
Referenced by RxnMolChange::RxnMolChange().
std::vector<double> m_phaseMassChange
Vector of mass changes for each phase in the Kinetics object due to the current reaction.
This is the sum of the product stoichiometric coefficient minum the reactant stoichioemtric coefficient index multiplied by the molecular weight for all species in a phase. The index is over all of the phases listed in the Kinetics object.
Definition at line 67 of file RxnMolChange.h.
Referenced by RxnMolChange::RxnMolChange().
std::vector<double> m_phaseChargeChange
Vector of mass changes for each phase in the Kinetics object due to the current reaction.
This is the sum of the product stoichiometric coefficient minum the reactant stoichioemtric coefficient index multiplied by the charg for all species in a phase. The index is over all of the phases listed in the Kinetics object.
Definition at line 75 of file RxnMolChange.h.
Referenced by ElectrodeKinetics::openCircuitVoltage(), RxnMolChange::RxnMolChange(), and ElectrodeKinetics::updateROP().
std::vector<int> m_phaseTypes
Vector of phase types in the reaction.
Collection of eosTypes for all phases in the kinetics object The index is over all of the phases listed in the Kinetics object.
Definition at line 82 of file RxnMolChange.h.
Referenced by RxnMolChange::RxnMolChange().
std::vector<int> m_phaseDims
Vector of phase dimensions for the reaction.
Collection of nDims for all phases in the kinetics object The index is over all of the phases listed in the Kinetics object.
Definition at line 89 of file RxnMolChange.h.
Referenced by RxnMolChange::RxnMolChange().
int m_nPhases
Number of phases in the kientics object.
Definition at line 92 of file RxnMolChange.h.
Referenced by RxnMolChange::RxnMolChange().
Cantera::Kinetics* m_kinBase
Shallow pointer pointing to the kinetics object.
Definition at line 95 of file RxnMolChange.h.
Referenced by RxnMolChange::RxnMolChange().
int m_iRxn
Reaction number within the kinetics object.
If this is neg 1, then this reaction refers to a global reaction specified by the m_egr pointer.
Definition at line 102 of file RxnMolChange.h.
double m_ChargeTransferInRxn
Maximum change in charge of any phase due to this reaction.
Definition at line 105 of file RxnMolChange.h.
Referenced by RxnMolChange::RxnMolChange().
double m_beta
Electrochemical beta parameter for the reaction.
Definition at line 108 of file RxnMolChange.h.
Referenced by RxnMolChange::RxnMolChange().
Cantera::ExtraGlobalRxn* m_egr
Pointer to the specification of the global reaction.
This is 0, if the class refers to a single reaction in the kinetics object
Definition at line 114 of file RxnMolChange.h.
The documentation for this class was generated from the following files:
RxnMolChange.h
RxnMolChange.cpp