Cantera: C_AnyN Class Reference
C_AnyN Class Reference
Stoichiometry
Handles any number of species in a reaction, including fractional stoichiometric coefficients, and arbitrary reaction orders.
#include <StoichManager.h>
Public Member Functions
C_AnyN (size_t rxn, const std::vector< size_t > &ic, const vector_fp &order_, const vector_fp &stoich_)
size_t data (std::vector< size_t > &ic)
doublereal order (size_t n) const
doublereal stoich (size_t n) const
size_t speciesIndex (size_t n) const
void multiply (const doublereal *input, doublereal *output) const
void incrementSpecies (const doublereal *input, doublereal *output) const
void decrementSpecies (const doublereal *input, doublereal *output) const
void incrementReaction (const doublereal *input, doublereal *output) const
void decrementReaction (const doublereal *input, doublereal *output) const
void writeMultiply (const std::string &r, std::map< size_t, std::string > &out)
void writeIncrementReaction (const std::string &r, std::map< size_t, std::string > &out)
void writeDecrementReaction (const std::string &r, std::map< size_t, std::string > &out)
void writeIncrementSpecies (const std::string &r, std::map< size_t, std::string > &out)
void writeDecrementSpecies (const std::string &r, std::map< size_t, std::string > &out)
Private Attributes
size_t m_n
Length of the m_ic vector.
size_t m_rxn
ID of the reaction corresponding to this stoichiometric manager.
std::vector< size_t > m_ic
Vector of species which are involved with this stoichiometric manager calculations.
vector_fp m_order
Reaction orders for the reaction.
vector_fp m_stoich
Stoichiometric coefficients for the reaction, reactant or product side.
Detailed Description
Handles any number of species in a reaction, including fractional stoichiometric coefficients, and arbitrary reaction orders.
See Stoichiometry
Definition at line 409 of file StoichManager.h.
Member Function Documentation
void writeMultiply (const std::string & r, std::map< size_t, std::string > & out) inline
Deprecated:
To be removed after Cantera 2.2
Definition at line 488 of file StoichManager.h.
References Cantera::fmt(), Cantera::fp2str(), C_AnyN::m_ic, C_AnyN::m_n, C_AnyN::m_order, and C_AnyN::m_rxn.
void writeIncrementReaction (const std::string & r, std::map< size_t, std::string > & out) inline
Deprecated:
To be removed after Cantera 2.2
Definition at line 503 of file StoichManager.h.
References Cantera::fmt(), Cantera::fp2str(), C_AnyN::m_ic, C_AnyN::m_n, C_AnyN::m_rxn, and C_AnyN::m_stoich.
void writeDecrementReaction (const std::string & r, std::map< size_t, std::string > & out) inline
Deprecated:
To be removed after Cantera 2.2
Definition at line 510 of file StoichManager.h.
References Cantera::fmt(), Cantera::fp2str(), C_AnyN::m_ic, C_AnyN::m_n, C_AnyN::m_rxn, and C_AnyN::m_stoich.
void writeIncrementSpecies (const std::string & r, std::map< size_t, std::string > & out) inline
Deprecated:
To be removed after Cantera 2.2
Definition at line 517 of file StoichManager.h.
References Cantera::fmt(), Cantera::fp2str(), C_AnyN::m_ic, C_AnyN::m_n, C_AnyN::m_rxn, and C_AnyN::m_stoich.
void writeDecrementSpecies (const std::string & r, std::map< size_t, std::string > & out) inline
Deprecated:
To be removed after Cantera 2.2
Definition at line 525 of file StoichManager.h.
References Cantera::fmt(), Cantera::fp2str(), C_AnyN::m_ic, C_AnyN::m_n, C_AnyN::m_rxn, and C_AnyN::m_stoich.
Member Data Documentation
size_t m_n private
Length of the m_ic vector.
This is the number of species which participate in the reaction order and stoichiometric coefficient vectors for the reactant or product description of the reaction.
Definition at line 540 of file StoichManager.h.
Referenced by C_AnyN::writeDecrementReaction(), C_AnyN::writeDecrementSpecies(), C_AnyN::writeIncrementReaction(), C_AnyN::writeIncrementSpecies(), and C_AnyN::writeMultiply().
size_t m_rxn private
ID of the reaction corresponding to this stoichiometric manager.
This is used within the interface to select the array position to read and write to Normally this is associated with the reaction number in an array of quantities indexed by the reaction number, e.g., ROP[irxn].
Definition at line 548 of file StoichManager.h.
Referenced by C_AnyN::writeDecrementReaction(), C_AnyN::writeDecrementSpecies(), C_AnyN::writeIncrementReaction(), C_AnyN::writeIncrementSpecies(), and C_AnyN::writeMultiply().
std::vector<size_t> m_ic private
Vector of species which are involved with this stoichiometric manager calculations.
This is an integer list of species which participate in either the reaction order matrix or the stoichiometric order matrix for this reaction, m_rxn.
Definition at line 555 of file StoichManager.h.
Referenced by C_AnyN::writeDecrementReaction(), C_AnyN::writeDecrementSpecies(), C_AnyN::writeIncrementReaction(), C_AnyN::writeIncrementSpecies(), and C_AnyN::writeMultiply().
vector_fp m_order private
Reaction orders for the reaction.
This is either for the reactants or products. Length = m_n Species number, m_ic[n], has a reaction order of m_order[n].
Definition at line 563 of file StoichManager.h.
Referenced by C_AnyN::writeMultiply().
vector_fp m_stoich private
Stoichiometric coefficients for the reaction, reactant or product side.
This is either for the reactants or products. Length = m_n Species number m_ic[m], has a stoichiometric coefficient of m_stoich[n].
Definition at line 571 of file StoichManager.h.
Referenced by C_AnyN::writeDecrementReaction(), C_AnyN::writeDecrementSpecies(), C_AnyN::writeIncrementReaction(), and C_AnyN::writeIncrementSpecies().
The documentation for this class was generated from the following file:
StoichManager.h