Cantera: ODE Integrators
ODE Integrators
Classes
class FuncEval
Virtual base class for ODE right-hand-side function evaluators.
class Integrator
Abstract base class for ODE system integrators.
Functions
static void cvode_rhs (integer N, real t, N_Vector y, N_Vector ydot, void *f_data)
Function called by CVODE to evaluate ydot given y.
static void cvode_jac (integer N, DenseMat J, RhsFn f, void *f_data, real t, N_Vector y, N_Vector fy, N_Vector ewt, real h, real uround, void *jac_data, long int *nfePtr, N_Vector vtemp1, N_Vector vtemp2, N_Vector vtemp3)
Function called by CVODE to evaluate the Jacobian matrix.
static int cvodes_rhs (realtype t, N_Vector y, N_Vector ydot, void *f_data)
Function called by cvodes to evaluate ydot given y.
Detailed Description
Function Documentation
static void cvode_rhs (integer N, real t, N_Vector y, N_Vector ydot, void * f_data) static
Function called by CVODE to evaluate ydot given y.
The CVODE integrator allows passing in a void* pointer to access external data. This pointer is cast to a pointer to a instance of class FuncEval. The equations to be integrated should be specified by deriving a class from FuncEval that evaluates the desired equations.
Definition at line 32 of file CVodeInt.cpp.
References FuncEval::eval().
Referenced by CVodeInt::initialize().
static void cvode_jac (integer N, DenseMat J, RhsFn f, void * f_data, real t, N_Vector y, N_Vector fy, N_Vector ewt, real h, real uround, void * jac_data, long int * nfePtr, N_Vector vtemp1, N_Vector vtemp2, N_Vector vtemp3) static
Function called by CVODE to evaluate the Jacobian matrix.
(temporary)
Definition at line 46 of file CVodeInt.cpp.
References FuncEval::eval().
Referenced by CVodeInt::initialize().
static int Cantera::cvodes_rhs (realtype t, N_Vector y, N_Vector ydot, void * f_data) static
Function called by cvodes to evaluate ydot given y.
The CVODE integrator allows passing in a void* pointer to access external data. This pointer is cast to a pointer to a instance of class FuncEval. The equations to be integrated should be specified by deriving a class from FuncEval that evaluates the desired equations.
Definition at line 64 of file CVodesIntegrator.cpp.
References DATA_PTR, FuncEval::eval(), and CanteraError::what().
Referenced by CVodesIntegrator::initialize().