Cantera: MixtureFugacityTP Class Reference
MixtureFugacityTP Class Reference
Models of Phases of Matter » Thermodynamic Properties
This is a filter class for ThermoPhase that implements some preparatory steps for efficiently handling mixture of gases that whose standard states are defined as ideal gases, but which describe also non-ideal solutions.
#include <MixtureFugacityTP.h>
Public Member Functions
Constructors and Duplicators for MixtureFugacityTP
MixtureFugacityTP ()
Constructor.
Utilities
virtual std::string type () const
String indicating the thermodynamic model implemented.
virtual int standardStateConvention () const
This method returns the convention used in specification of the standard state, of which there are currently two, temperature based, and variable pressure based.
virtual void setForcedSolutionBranch (int solnBranch)
Set the solution branch to force the ThermoPhase to exist on one branch or another.
virtual int forcedSolutionBranch () const
Report the solution branch which the solution is restricted to.
virtual int reportSolnBranchActual () const
Report the solution branch which the solution is actually on.
virtual void getdlnActCoeffdlnN_diag (doublereal *dlnActCoeffdlnN_diag) const
Get the array of log species mole number derivatives of the log activity coefficients.
Partial Molar Properties of the Solution
virtual void getChemPotentials_RT (doublereal *mu) const
Get the array of non-dimensional species chemical potentials These are partial molar Gibbs free energies.
Initialization Methods - For Internal use
virtual bool addSpecies (shared_ptr< Species > spec)
virtual void setStateFromXML (const XML_Node &state)
Set the initial state of the phase to the conditions specified in the state XML element.
Public Member Functions inherited from ThermoPhase
ThermoPhase ()
Constructor.
virtual std::string phaseOfMatter () const
String indicating the mechanical phase of the matter in this Phase.
virtual doublereal refPressure () const
Returns the reference pressure in Pa.
virtual doublereal minTemp (size_t k=npos) const
Minimum temperature for which the thermodynamic data for the species or phase are valid.
doublereal Hf298SS (const size_t k) const
Report the 298 K Heat of Formation of the standard state of one species (J kmol-1)
virtual void modifyOneHf298SS (const size_t k, const doublereal Hf298New)
Modify the value of the 298 K Heat of Formation of one species in the phase (J kmol-1)
virtual void resetHf298 (const size_t k=npos)
Restore the original heat of formation of one or more species.
virtual doublereal maxTemp (size_t k=npos) const
Maximum temperature for which the thermodynamic data for the species are valid.
bool chargeNeutralityNecessary () const
Returns the chargeNeutralityNecessity boolean.
virtual doublereal enthalpy_mole () const
Molar enthalpy. Units: J/kmol.
virtual doublereal intEnergy_mole () const
Molar internal energy. Units: J/kmol.
virtual doublereal entropy_mole () const
Molar entropy. Units: J/kmol/K.
virtual doublereal gibbs_mole () const
Molar Gibbs function. Units: J/kmol.
virtual doublereal cp_mole () const
Molar heat capacity at constant pressure. Units: J/kmol/K.
virtual doublereal cv_mole () const
Molar heat capacity at constant volume. Units: J/kmol/K.
virtual doublereal isothermalCompressibility () const
Returns the isothermal compressibility. Units: 1/Pa.
virtual doublereal thermalExpansionCoeff () const
Return the volumetric thermal expansion coefficient. Units: 1/K.
void setElectricPotential (doublereal v)
Set the electric potential of this phase (V).
doublereal electricPotential () const
Returns the electric potential of this phase (V).
virtual int activityConvention () const
This method returns the convention used in specification of the activities, of which there are currently two, molar- and molality-based conventions.
virtual Units standardConcentrationUnits () const
Returns the units of the "standard concentration" for this phase.
virtual void getActivityConcentrations (doublereal *c) const
This method returns an array of generalized concentrations.
virtual doublereal standardConcentration (size_t k=0) const
Return the standard concentration for the kth species.
virtual doublereal logStandardConc (size_t k=0) const
Natural logarithm of the standard concentration of the kth species.
virtual void getActivities (doublereal *a) const
Get the array of non-dimensional activities at the current solution temperature, pressure, and solution concentration.
virtual void getActivityCoefficients (doublereal *ac) const
Get the array of non-dimensional molar-based activity coefficients at the current solution temperature, pressure, and solution concentration.
virtual void getLnActivityCoefficients (doublereal *lnac) const
Get the array of non-dimensional molar-based ln activity coefficients at the current solution temperature, pressure, and solution concentration.
virtual void getChemPotentials (doublereal *mu) const
Get the species chemical potentials. Units: J/kmol.
void getElectrochemPotentials (doublereal *mu) const
Get the species electrochemical potentials.
virtual void getPartialMolarEnthalpies (doublereal *hbar) const
Returns an array of partial molar enthalpies for the species in the mixture.
virtual void getPartialMolarEntropies (doublereal *sbar) const
Returns an array of partial molar entropies of the species in the solution.
virtual void getPartialMolarIntEnergies (doublereal *ubar) const
Return an array of partial molar internal energies for the species in the mixture.
virtual void getPartialMolarCp (doublereal *cpbar) const
Return an array of partial molar heat capacities for the species in the mixture.
virtual void getPartialMolarVolumes (doublereal *vbar) const
Return an array of partial molar volumes for the species in the mixture.
virtual void getIntEnergy_RT_ref (doublereal *urt) const
Returns the vector of nondimensional internal Energies of the reference state at the current temperature of the solution and the reference pressure for each species.
doublereal enthalpy_mass () const
Specific enthalpy. Units: J/kg.
doublereal intEnergy_mass () const
Specific internal energy. Units: J/kg.
doublereal entropy_mass () const
Specific entropy. Units: J/kg/K.
doublereal gibbs_mass () const
Specific Gibbs function. Units: J/kg.
doublereal cp_mass () const
Specific heat at constant pressure. Units: J/kg/K.
doublereal cv_mass () const
Specific heat at constant volume. Units: J/kg/K.
doublereal RT () const
Return the Gas Constant multiplied by the current temperature.
virtual void setState_TPX (doublereal t, doublereal p, const compositionMap &x)
Set the temperature (K), pressure (Pa), and mole fractions.
virtual void setState_TPX (doublereal t, doublereal p, const std::string &x)
Set the temperature (K), pressure (Pa), and mole fractions.
virtual void setState_TPY (doublereal t, doublereal p, const doublereal *y)
Set the internally stored temperature (K), pressure (Pa), and mass fractions of the phase.
virtual void setState_TPY (doublereal t, doublereal p, const compositionMap &y)
Set the internally stored temperature (K), pressure (Pa), and mass fractions of the phase.
virtual void setState_TPY (doublereal t, doublereal p, const std::string &y)
Set the internally stored temperature (K), pressure (Pa), and mass fractions of the phase.
virtual void setState_PX (doublereal p, doublereal *x)
Set the pressure (Pa) and mole fractions.
virtual void setState_PY (doublereal p, doublereal *y)
Set the internally stored pressure (Pa) and mass fractions.
virtual void setState_HP (double h, double p, double tol=1e-9)
Set the internally stored specific enthalpy (J/kg) and pressure (Pa) of the phase.
virtual void setState_UV (double u, double v, double tol=1e-9)
Set the specific internal energy (J/kg) and specific volume (m^3/kg).
virtual void setState_SP (double s, double p, double tol=1e-9)
Set the specific entropy (J/kg/K) and pressure (Pa).
virtual void setState_SV (double s, double v, double tol=1e-9)
Set the specific entropy (J/kg/K) and specific volume (m^3/kg).
virtual void setState_ST (double s, double t, double tol=1e-9)
Set the specific entropy (J/kg/K) and temperature (K).
virtual void setState_TV (double t, double v, double tol=1e-9)
Set the temperature (K) and specific volume (m^3/kg).
virtual void setState_PV (double p, double v, double tol=1e-9)
Set the pressure (Pa) and specific volume (m^3/kg).
virtual void setState_UP (double u, double p, double tol=1e-9)
Set the specific internal energy (J/kg) and pressure (Pa).
virtual void setState_VH (double v, double h, double tol=1e-9)
Set the specific volume (m^3/kg) and the specific enthalpy (J/kg)
virtual void setState_TH (double t, double h, double tol=1e-9)
Set the temperature (K) and the specific enthalpy (J/kg)
virtual void setState_SH (double s, double h, double tol=1e-9)
Set the specific entropy (J/kg/K) and the specific enthalpy (J/kg)
virtual void setState_RP (doublereal rho, doublereal p)
Set the density (kg/m**3) and pressure (Pa) at constant composition.
virtual void setState_RPX (doublereal rho, doublereal p, const doublereal *x)
Set the density (kg/m**3), pressure (Pa) and mole fractions.
virtual void setState_RPX (doublereal rho, doublereal p, const compositionMap &x)
Set the density (kg/m**3), pressure (Pa) and mole fractions.
virtual void setState_RPX (doublereal rho, doublereal p, const std::string &x)
Set the density (kg/m**3), pressure (Pa) and mole fractions.
virtual void setState_RPY (doublereal rho, doublereal p, const doublereal *y)
Set the density (kg/m**3), pressure (Pa) and mass fractions.
virtual void setState_RPY (doublereal rho, doublereal p, const compositionMap &y)
Set the density (kg/m**3), pressure (Pa) and mass fractions.
virtual void setState_RPY (doublereal rho, doublereal p, const std::string &y)
Set the density (kg/m**3), pressure (Pa) and mass fractions.
virtual void setState (const AnyMap &state)
Set the state using an AnyMap containing any combination of properties supported by the thermodynamic model.
void setMixtureFraction (double mixFrac, const double *fuelComp, const double *oxComp, ThermoBasis basis=ThermoBasis::molar)
Set the mixture composition according to the mixture fraction = kg fuel / (kg oxidizer + kg fuel)
void setMixtureFraction (double mixFrac, const std::string &fuelComp, const std::string &oxComp, ThermoBasis basis=ThermoBasis::molar)
Set the mixture composition according to the mixture fraction = kg fuel / (kg oxidizer + kg fuel)
void setMixtureFraction (double mixFrac, const compositionMap &fuelComp, const compositionMap &oxComp, ThermoBasis basis=ThermoBasis::molar)
Set the mixture composition according to the mixture fraction = kg fuel / (kg oxidizer + kg fuel)
double mixtureFraction (const double *fuelComp, const double *oxComp, ThermoBasis basis=ThermoBasis::molar, const std::string &element="Bilger") const
Compute the mixture fraction = kg fuel / (kg oxidizer + kg fuel) for the current mixture given fuel and oxidizer compositions.
double mixtureFraction (const std::string &fuelComp, const std::string &oxComp, ThermoBasis basis=ThermoBasis::molar, const std::string &element="Bilger") const
Compute the mixture fraction = kg fuel / (kg oxidizer + kg fuel) for the current mixture given fuel and oxidizer compositions.
double mixtureFraction (const compositionMap &fuelComp, const compositionMap &oxComp, ThermoBasis basis=ThermoBasis::molar, const std::string &element="Bilger") const
Compute the mixture fraction = kg fuel / (kg oxidizer + kg fuel) for the current mixture given fuel and oxidizer compositions.
void setEquivalenceRatio (double phi, const double *fuelComp, const double *oxComp, ThermoBasis basis=ThermoBasis::molar)
Set the mixture composition according to the equivalence ratio.
void setEquivalenceRatio (double phi, const std::string &fuelComp, const std::string &oxComp, ThermoBasis basis=ThermoBasis::molar)
Set the mixture composition according to the equivalence ratio.
void setEquivalenceRatio (double phi, const compositionMap &fuelComp, const compositionMap &oxComp, ThermoBasis basis=ThermoBasis::molar)
Set the mixture composition according to the equivalence ratio.
double equivalenceRatio (const double *fuelComp, const double *oxComp, ThermoBasis basis=ThermoBasis::molar) const
Compute the equivalence ratio for the current mixture given the compositions of fuel and oxidizer.
double equivalenceRatio (const std::string &fuelComp, const std::string &oxComp, ThermoBasis basis=ThermoBasis::molar) const
Compute the equivalence ratio for the current mixture given the compositions of fuel and oxidizer.
double equivalenceRatio (const compositionMap &fuelComp, const compositionMap &oxComp, ThermoBasis basis=ThermoBasis::molar) const
Compute the equivalence ratio for the current mixture given the compositions of fuel and oxidizer.
double equivalenceRatio () const
Compute the equivalence ratio for the current mixture from available oxygen and required oxygen.
void equilibrate (const std::string &XY, const std::string &solver="auto", double rtol=1e-9, int max_steps=50000, int max_iter=100, int estimate_equil=0, int log_level=0)
Equilibrate a ThermoPhase object.
virtual void setToEquilState (const doublereal *mu_RT)
This method is used by the ChemEquil equilibrium solver.
virtual bool compatibleWithMultiPhase () const
Indicates whether this phase type can be used with class MultiPhase for equilibrium calculations.
virtual doublereal critTemperature () const
Critical temperature (K).
virtual doublereal critPressure () const
Critical pressure (Pa).
virtual doublereal critVolume () const
Critical volume (m3/kmol).
virtual doublereal critCompressibility () const
Critical compressibility (unitless).
virtual doublereal critDensity () const
Critical density (kg/m3).
virtual doublereal satTemperature (doublereal p) const
Return the saturation temperature given the pressure.
virtual doublereal vaporFraction () const
Return the fraction of vapor at the current conditions.
virtual void setState_Tsat (doublereal t, doublereal x)
Set the state to a saturated system at a particular temperature.
virtual void setState_Psat (doublereal p, doublereal x)
Set the state to a saturated system at a particular pressure.
void setState_TPQ (double T, double P, double Q)
Set the temperature, pressure, and vapor fraction (quality).
virtual void modifySpecies (size_t k, shared_ptr< Species > spec)
Modify the thermodynamic data associated with a species.
void saveSpeciesData (const size_t k, const XML_Node *const data)
Store a reference pointer to the XML tree containing the species data for this phase.
const std::vector< const XML_Node * > & speciesData () const
Return a pointer to the vector of XML nodes containing the species data for this phase.
virtual MultiSpeciesThermo & speciesThermo (int k=-1)
Return a changeable reference to the calculation manager for species reference-state thermodynamic properties.
virtual const MultiSpeciesThermo & speciesThermo (int k=-1) const
virtual void initThermoFile (const std::string &inputFile, const std::string &id)
virtual void initThermoXML (XML_Node &phaseNode, const std::string &id)
Import and initialize a ThermoPhase object using an XML tree.
virtual void initThermo ()
Initialize the ThermoPhase object after all species have been set up.
virtual void setParameters (int n, doublereal *const c)
Set the equation of state parameters.
virtual void getParameters (int &n, doublereal *const c) const
Get the equation of state parameters in a vector.
virtual void setParameters (const AnyMap &phaseNode, const AnyMap &rootNode=AnyMap())
Set equation of state parameters from an AnyMap phase description.
const AnyMap & input () const
Access input data associated with the phase description.
AnyMap & input ()
virtual void setParametersFromXML (const XML_Node &eosdata)
Set equation of state parameter values from XML entries.
virtual void getdlnActCoeffds (const doublereal dTds, const doublereal *const dXds, doublereal *dlnActCoeffds) const
Get the change in activity coefficients wrt changes in state (temp, mole fraction, etc) along a line in parameter space or along a line in physical space.
virtual void getdlnActCoeffdlnX_diag (doublereal *dlnActCoeffdlnX_diag) const
Get the array of ln mole fraction derivatives of the log activity coefficients - diagonal component only.
virtual void getdlnActCoeffdlnN (const size_t ld, doublereal *const dlnActCoeffdlnN)
Get the array of derivatives of the log activity coefficients with respect to the log of the species mole numbers.
virtual void getdlnActCoeffdlnN_numderiv (const size_t ld, doublereal *const dlnActCoeffdlnN)
virtual std::string report (bool show_thermo=true, doublereal threshold=-1e-14) const
returns a summary of the state of the phase as a string
virtual void reportCSV (std::ofstream &csvFile) const
returns a summary of the state of the phase to a comma separated file.
double stoichAirFuelRatio (const double *fuelComp, const double *oxComp, ThermoBasis basis=ThermoBasis::molar) const
Compute the stoichiometric air to fuel ratio (kg oxidizer / kg fuel) given fuel and oxidizer compositions.
double stoichAirFuelRatio (const std::string &fuelComp, const std::string &oxComp, ThermoBasis basis=ThermoBasis::molar) const
Compute the stoichiometric air to fuel ratio (kg oxidizer / kg fuel) given fuel and oxidizer compositions.
double stoichAirFuelRatio (const compositionMap &fuelComp, const compositionMap &oxComp, ThermoBasis basis=ThermoBasis::molar) const
Compute the stoichiometric air to fuel ratio (kg oxidizer / kg fuel) given fuel and oxidizer compositions.
Public Member Functions inherited from Phase
Phase ()
Default constructor.
Phase (const Phase &)=delete
Phase & operator= (const Phase &)=delete
XML_Node & xml () const
Returns a const reference to the XML_Node that describes the phase.
void setXMLdata (XML_Node &xmlPhase)
Stores the XML tree information for the current phase.
virtual bool isPure () const
Return whether phase represents a pure (single species) substance.
virtual bool hasPhaseTransition () const
Return whether phase represents a substance with phase transitions.
virtual bool isCompressible () const
Return whether phase represents a compressible substance.
virtual std::map< std::string, size_t > nativeState () const
Return a map of properties defining the native state of a substance.
virtual std::vector< std::string > fullStates () const
Return a vector containing full states defining a phase.
virtual std::vector< std::string > partialStates () const
Return a vector of settable partial property sets within a phase.
virtual size_t stateSize () const
Return size of vector defining internal state of the phase.
void saveState (vector_fp &state) const
Save the current internal state of the phase.
virtual void saveState (size_t lenstate, doublereal *state) const
Write to array 'state' the current internal state.
void restoreState (const vector_fp &state)
Restore a state saved on a previous call to saveState.
virtual void restoreState (size_t lenstate, const doublereal *state)
Restore the state of the phase from a previously saved state vector.
doublereal molecularWeight (size_t k) const
Molecular weight of species k.
void getMolecularWeights (vector_fp &weights) const
Copy the vector of molecular weights into vector weights.
void getMolecularWeights (doublereal *weights) const
Copy the vector of molecular weights into array weights.
const vector_fp & molecularWeights () const
Return a const reference to the internal vector of molecular weights.
void getCharges (double *charges) const
Copy the vector of species charges into array charges.
virtual bool ready () const
Returns a bool indicating whether the object is ready for use.
int stateMFNumber () const
Return the State Mole Fraction Number.
bool caseSensitiveSpecies () const
Returns true if case sensitive species names are enforced.
void setCaseSensitiveSpecies (bool cflag=true)
Set flag that determines whether case sensitive species are enforced in look-up operations, e.g.
virtual void setRoot (std::shared_ptr< Solution > root)
Set root Solution holding all phase information.
vector_fp getCompositionFromMap (const compositionMap &comp) const
Converts a compositionMap to a vector with entries for each species Species that are not specified are set to zero in the vector.
void massFractionsToMoleFractions (const double *Y, double *X) const
Converts a mixture composition from mole fractions to mass fractions.
void moleFractionsToMassFractions (const double *X, double *Y) const
Converts a mixture composition from mass fractions to mole fractions.
std::string id () const
Return the string id for the phase.
void setID (const std::string &id)
Set the string id for the phase.
std::string name () const
Return the name of the phase.
void setName (const std::string &nm)
Sets the string name for the phase.
std::string elementName (size_t m) const
Name of the element with index m.
size_t elementIndex (const std::string &name) const
Return the index of element named 'name'.
const std::vector< std::string > & elementNames () const
Return a read-only reference to the vector of element names.
doublereal atomicWeight (size_t m) const
Atomic weight of element m.
doublereal entropyElement298 (size_t m) const
Entropy of the element in its standard state at 298 K and 1 bar.
int atomicNumber (size_t m) const
Atomic number of element m.
int elementType (size_t m) const
Return the element constraint type Possible types include:
int changeElementType (int m, int elem_type)
Change the element type of the mth constraint Reassigns an element type.
const vector_fp & atomicWeights () const
Return a read-only reference to the vector of atomic weights.
size_t nElements () const
Number of elements.
void checkElementIndex (size_t m) const
Check that the specified element index is in range.
void checkElementArraySize (size_t mm) const
Check that an array size is at least nElements().
doublereal nAtoms (size_t k, size_t m) const
Number of atoms of element m in species k.
void getAtoms (size_t k, double *atomArray) const
Get a vector containing the atomic composition of species k.
size_t speciesIndex (const std::string &name) const
Returns the index of a species named 'name' within the Phase object.
std::string speciesName (size_t k) const
Name of the species with index k.
std::string speciesSPName (int k) const
Returns the expanded species name of a species, including the phase name This is guaranteed to be unique within a Cantera problem.
const std::vector< std::string > & speciesNames () const
Return a const reference to the vector of species names.
size_t nSpecies () const
Returns the number of species in the phase.
void checkSpeciesIndex (size_t k) const
Check that the specified species index is in range.
void checkSpeciesArraySize (size_t kk) const
Check that an array size is at least nSpecies().
void setMoleFractionsByName (const compositionMap &xMap)
Set the species mole fractions by name.
void setMoleFractionsByName (const std::string &x)
Set the mole fractions of a group of species by name.
void setMassFractionsByName (const compositionMap &yMap)
Set the species mass fractions by name.
void setMassFractionsByName (const std::string &x)
Set the species mass fractions by name.
void setState_TRX (doublereal t, doublereal dens, const doublereal *x)
Set the internally stored temperature (K), density, and mole fractions.
void setState_TRX (doublereal t, doublereal dens, const compositionMap &x)
Set the internally stored temperature (K), density, and mole fractions.
void setState_TRY (doublereal t, doublereal dens, const doublereal *y)
Set the internally stored temperature (K), density, and mass fractions.
void setState_TRY (doublereal t, doublereal dens, const compositionMap &y)
Set the internally stored temperature (K), density, and mass fractions.
void setState_TNX (doublereal t, doublereal n, const doublereal *x)
Set the internally stored temperature (K), molar density (kmol/m^3), and mole fractions.
void setState_TR (doublereal t, doublereal rho)
Set the internally stored temperature (K) and density (kg/m^3)
void setState_TX (doublereal t, doublereal *x)
Set the internally stored temperature (K) and mole fractions.
void setState_TY (doublereal t, doublereal *y)
Set the internally stored temperature (K) and mass fractions.
void setState_RX (doublereal rho, doublereal *x)
Set the density (kg/m^3) and mole fractions.
void setState_RY (doublereal rho, doublereal *y)
Set the density (kg/m^3) and mass fractions.
compositionMap getMoleFractionsByName (double threshold=0.0) const
Get the mole fractions by name.
double moleFraction (size_t k) const
Return the mole fraction of a single species.
double moleFraction (const std::string &name) const
Return the mole fraction of a single species.
compositionMap getMassFractionsByName (double threshold=0.0) const
Get the mass fractions by name.
double massFraction (size_t k) const
Return the mass fraction of a single species.
double massFraction (const std::string &name) const
Return the mass fraction of a single species.
void getMoleFractions (double *const x) const
Get the species mole fraction vector.
virtual void setMoleFractions (const double *const x)
Set the mole fractions to the specified values.
virtual void setMoleFractions_NoNorm (const double *const x)
Set the mole fractions to the specified values without normalizing.
void getMassFractions (double *const y) const
Get the species mass fractions.
const double * massFractions () const
Return a const pointer to the mass fraction array.
virtual void setMassFractions (const double *const y)
Set the mass fractions to the specified values and normalize them.
virtual void setMassFractions_NoNorm (const double *const y)
Set the mass fractions to the specified values without normalizing.
void getConcentrations (double *const c) const
Get the species concentrations (kmol/m^3).
double concentration (const size_t k) const
Concentration of species k.
virtual void setConcentrations (const double *const conc)
Set the concentrations to the specified values within the phase.
virtual void setConcentrationsNoNorm (const double *const conc)
Set the concentrations without ignoring negative concentrations.
doublereal elementalMassFraction (const size_t m) const
Elemental mass fraction of element m.
doublereal elementalMoleFraction (const size_t m) const
Elemental mole fraction of element m.
const double * moleFractdivMMW () const
Returns a const pointer to the start of the moleFraction/MW array.
doublereal charge (size_t k) const
Dimensionless electrical charge of a single molecule of species k The charge is normalized by the the magnitude of the electron charge.
doublereal chargeDensity () const
Charge density [C/m^3].
size_t nDim () const
Returns the number of spatial dimensions (1, 2, or 3)
void setNDim (size_t ndim)
Set the number of spatial dimensions (1, 2, or 3).
doublereal temperature () const
Temperature (K).
virtual double pressure () const
Return the thermodynamic pressure (Pa).
virtual double density () const
Density (kg/m^3).
double molarDensity () const
Molar density (kmol/m^3).
double molarVolume () const
Molar volume (m^3/kmol).
virtual void setDensity (const double density_)
Set the internally stored density (kg/m^3) of the phase.
virtual void setMolarDensity (const double molarDensity)
Set the internally stored molar density (kmol/m^3) of the phase.
doublereal mean_X (const doublereal *const Q) const
Evaluate the mole-fraction-weighted mean of an array Q.
doublereal mean_X (const vector_fp &Q) const
Evaluate the mole-fraction-weighted mean of an array Q.
doublereal meanMolecularWeight () const
The mean molecular weight. Units: (kg/kmol)
doublereal sum_xlogx () const
Evaluate \(\sum_k X_k \log X_k \).
size_t addElement (const std::string &symbol, doublereal weight=-12345.0, int atomicNumber=0, doublereal entropy298=ENTROPY298_UNKNOWN, int elem_type=CT_ELEM_TYPE_ABSPOS)
Add an element.
void addSpeciesAlias (const std::string &name, const std::string &alias)
Add a species alias (i.e.
virtual std::vector< std::string > findIsomers (const compositionMap &compMap) const
Return a vector with isomers names matching a given composition map.
virtual std::vector< std::string > findIsomers (const std::string &comp) const
Return a vector with isomers names matching a given composition string.
shared_ptr< Species > species (const std::string &name) const
Return the Species object for the named species.
shared_ptr< Species > species (size_t k) const
Return the Species object for species whose index is k.
void ignoreUndefinedElements ()
Set behavior when adding a species containing undefined elements to just skip the species.
void addUndefinedElements ()
Set behavior when adding a species containing undefined elements to add those elements to the phase.
void throwUndefinedElements ()
Set the behavior when adding a species containing undefined elements to throw an exception.
Special Functions for fugacity classes
vector_fp moleFractions_
Storage for the current values of the mole fractions of the species.
int iState_
Current state of the fluid.
int forcedState_
Force the system to be on a particular side of the spinodal curve.
doublereal m_Tlast_ref
The last temperature at which the reference state thermodynamic properties were calculated at.
vector_fp m_h0_RT
Temporary storage for dimensionless reference state enthalpies.
vector_fp m_cp0_R
Temporary storage for dimensionless reference state heat capacities.
vector_fp m_g0_RT
Temporary storage for dimensionless reference state Gibbs energies.
vector_fp m_s0_R
Temporary storage for dimensionless reference state entropies.
virtual doublereal liquidVolEst (doublereal TKelvin, doublereal &pres) const
Estimate for the molar volume of the liquid.
virtual doublereal densityCalc (doublereal TKelvin, doublereal pressure, int phaseRequested, doublereal rhoguess)
Calculates the density given the temperature and the pressure and a guess at the density.
int phaseState (bool checkState=false) const
Returns the Phase State flag for the current state of the object.
virtual doublereal densSpinodalLiquid () const
Return the value of the density at the liquid spinodal point (on the liquid side) for the current temperature.
virtual doublereal densSpinodalGas () const
Return the value of the density at the gas spinodal point (on the gas side) for the current temperature.
doublereal calculatePsat (doublereal TKelvin, doublereal &molarVolGas, doublereal &molarVolLiquid)
Calculate the saturation pressure at the current mixture content for the given temperature.
virtual doublereal satPressure (doublereal TKelvin)
Calculate the saturation pressure at the current mixture content for the given temperature.
doublereal z () const
Calculate the value of z.
virtual doublereal sresid () const
Calculate the deviation terms for the total entropy of the mixture from the ideal gas mixture.
virtual doublereal hresid () const
Calculate the deviation terms for the total enthalpy of the mixture from the ideal gas mixture.
virtual doublereal psatEst (doublereal TKelvin) const
Estimate for the saturation pressure.
int corr0 (doublereal TKelvin, doublereal pres, doublereal &densLiq, doublereal &densGas, doublereal &liqGRT, doublereal &gasGRT)
Utility routine in the calculation of the saturation pressure.
virtual doublereal pressureCalc (doublereal TKelvin, doublereal molarVol) const
Calculate the pressure given the temperature and the molar volume.
virtual doublereal dpdVCalc (doublereal TKelvin, doublereal molarVol, doublereal &presCalc) const
Calculate the pressure and the pressure derivative given the temperature and the molar volume.
virtual void updateMixingExpressions ()
virtual void invalidateCache ()
Invalidate any cached values which are normally updated only when a change in state is detected.
Properties of the Standard State of the Species in the Solution
Within MixtureFugacityTP, these properties are calculated via a common routine, _updateStandardStateThermo(), which must be overloaded in inherited objects. The values are cached within this object, and are not recalculated unless the temperature or pressure changes.
virtual void getStandardChemPotentials (doublereal *mu) const
Get the array of chemical potentials at unit activity.
virtual void getEnthalpy_RT (doublereal *hrt) const
Get the nondimensional Enthalpy functions for the species at their standard states at the current T and P of the solution.
virtual void getEntropy_R (doublereal *sr) const
Get the array of nondimensional Enthalpy functions for the standard state species at the current T and P of the solution.
virtual void getGibbs_RT (doublereal *grt) const
Get the nondimensional Gibbs functions for the species at their standard states of solution at the current T and P of the solution.
virtual void getPureGibbs (doublereal *gpure) const
Get the pure Gibbs free energies of each species.
virtual void getIntEnergy_RT (doublereal *urt) const
Returns the vector of nondimensional internal Energies of the standard state at the current temperature and pressure of the solution for each species.
virtual void getCp_R (doublereal *cpr) const
Get the nondimensional Heat Capacities at constant pressure for the standard state of the species at the current T and P.
virtual void getStandardVolumes (doublereal *vol) const
Get the molar volumes of each species in their standard states at the current T and P of the solution.
virtual void setTemperature (const doublereal temp)
Set the temperature of the phase.
virtual void setPressure (doublereal p)
Set the internally stored pressure (Pa) at constant temperature and composition.
virtual void setState_TP (doublereal T, doublereal pres)
Set the temperature (K) and pressure (Pa)
virtual void setState_TR (doublereal T, doublereal rho)
virtual void setState_TPX (doublereal t, doublereal p, const doublereal *x)
Set the temperature (K), pressure (Pa), and mole fractions.
virtual void calcDensity ()
Calculate the density of the mixture using the partial molar volumes and mole fractions as input.
virtual void compositionChanged ()
Apply changes to the state which are needed after the composition changes.
void setMoleFractions_NoState (const doublereal *const x)
virtual void _updateReferenceStateThermo () const
Updates the reference state thermodynamic functions at the current T of the solution.
Thermodynamic Values for the Species Reference States
virtual void getEnthalpy_RT_ref (doublereal *hrt) const
virtual void getGibbs_RT_ref (doublereal *grt) const
Returns the vector of nondimensional Gibbs Free Energies of the reference state at the current temperature of the solution and the reference pressure for the species.
virtual void getGibbs_ref (doublereal *g) const
Returns the vector of the Gibbs function of the reference state at the current temperature of the solution and the reference pressure for the species.
virtual void getEntropy_R_ref (doublereal *er) const
Returns the vector of nondimensional entropies of the reference state at the current temperature of the solution and the reference pressure for each species.
virtual void getCp_R_ref (doublereal *cprt) const
Returns the vector of nondimensional constant pressure heat capacities of the reference state at the current temperature of the solution and reference pressure for each species.
virtual void getStandardVolumes_ref (doublereal *vol) const
Get the molar volumes of the species reference states at the current T and P_ref of the solution.
const vector_fp & gibbs_RT_ref () const
Returns the vector of nondimensional Gibbs free energies of the reference state at the current temperature of the solution and the reference pressure for the species.
Additional Inherited Members
Protected Member Functions inherited from ThermoPhase
virtual void getCsvReportData (std::vector< std::string > &names, std::vector< vector_fp > &data) const
Fills names and data with the column names and species thermo properties to be included in the output of the reportCSV method.
Protected Member Functions inherited from Phase
void assertCompressible (const std::string &setter) const
Ensure that phase is compressible.
void assignDensity (const double density_)
Set the internally stored constant density (kg/m^3) of the phase.
void setMolecularWeight (const int k, const double mw)
Set the molecular weight of a single species to a given value.
Protected Attributes inherited from ThermoPhase
MultiSpeciesThermo m_spthermo
Pointer to the calculation manager for species reference-state thermodynamic properties.
AnyMap m_input
Data supplied via setParameters.
std::vector< const XML_Node * > m_speciesData
Vector of pointers to the species databases.
doublereal m_phi
Stored value of the electric potential for this phase. Units are Volts.
bool m_chargeNeutralityNecessary
Boolean indicating whether a charge neutrality condition is a necessity.
int m_ssConvention
Contains the standard state convention.
doublereal m_tlast
last value of the temperature processed by reference state
Protected Attributes inherited from Phase
ValueCache m_cache
Cached for saved calculations within each ThermoPhase.
size_t m_kk
Number of species in the phase.
size_t m_ndim
Dimensionality of the phase.
vector_fp m_speciesComp
Atomic composition of the species.
vector_fp m_speciesCharge
Vector of species charges. length m_kk.
std::map< std::string, shared_ptr< Species > > m_species
UndefElement::behavior m_undefinedElementBehavior
Flag determining behavior when adding species with an undefined element.
bool m_caseSensitiveSpecies
Flag determining whether case sensitive species names are enforced.
Detailed Description
This is a filter class for ThermoPhase that implements some preparatory steps for efficiently handling mixture of gases that whose standard states are defined as ideal gases, but which describe also non-ideal solutions.
In addition a multicomponent liquid phase below the critical temperature of the mixture is also allowed. The main subclass is currently a mixture Redlich- Kwong class.
Attention
This class currently does not have any test cases or examples. Its implementation may be incomplete, and future changes to Cantera may unexpectedly cause this class to stop working. If you use this class, please consider contributing examples or test cases. In the absence of new tests or examples, this class may be deprecated and removed in a future version of Cantera. See https://github.com/Cantera/cantera/issues/267 for additional information.
Several concepts are introduced. The first concept is there are temporary variables for holding the species standard state values of Cp, H, S, G, and V at the last temperature and pressure called. These functions are not recalculated if a new call is made using the previous temperature and pressure.
The other concept is that the current state of the mixture is tracked. The state variable is either GAS, LIQUID, or SUPERCRIT fluid. Additionally, the variable LiquidContent is used and may vary between 0 and 1.
Typically, only one liquid phase is allowed to be formed within these classes. Additionally, there is an inherent contradiction between three phase models and the ThermoPhase class. The ThermoPhase class is really only meant to represent a single instantiation of a phase. The three phase models may be in equilibrium with multiple phases of the fluid in equilibrium with each other. This has yet to be resolved.
This class is usually used for non-ideal gases.
Definition at line 74 of file MixtureFugacityTP.h.
Constructor & Destructor Documentation
MixtureFugacityTP()
MixtureFugacityTP ()
Constructor.
Definition at line 20 of file MixtureFugacityTP.cpp.
Member Function Documentation
type()
virtual std::string type () const inline virtual
String indicating the thermodynamic model implemented.
Usually corresponds to the name of the derived class, less any suffixes such as "Phase", TP", "VPSS", etc.
Reimplemented from ThermoPhase.
Reimplemented in RedlichKwongMFTP.
Definition at line 87 of file MixtureFugacityTP.h.
standardStateConvention()
int standardStateConvention () const virtual
This method returns the convention used in specification of the standard state, of which there are currently two, temperature based, and variable pressure based.
Currently, there are two standard state conventions:
Temperature-based activities cSS_CONVENTION_TEMPERATURE 0
default
Variable Pressure and Temperature -based activities cSS_CONVENTION_VPSS 1
Thermodynamics is set via slave ThermoPhase objects with nothing being carried out at this ThermoPhase object level cSS_CONVENTION_SLAVE 2
Reimplemented from ThermoPhase.
Definition at line 27 of file MixtureFugacityTP.cpp.
References Cantera::cSS_CONVENTION_TEMPERATURE.
setForcedSolutionBranch()
void setForcedSolutionBranch (int solnBranch) virtual
Set the solution branch to force the ThermoPhase to exist on one branch or another.
Parameters
solnBranch Branch that the solution is restricted to. the value -1 means gas. The value -2 means unrestricted. Values of zero or greater refer to species dominated condensed phases.
Definition at line 32 of file MixtureFugacityTP.cpp.
References MixtureFugacityTP::forcedState_.
forcedSolutionBranch()
int forcedSolutionBranch () const virtual
Report the solution branch which the solution is restricted to.
Returns
Branch that the solution is restricted to. the value -1 means gas. The value -2 means unrestricted. Values of zero or greater refer to species dominated condensed phases.
Definition at line 37 of file MixtureFugacityTP.cpp.
References MixtureFugacityTP::forcedState_.
reportSolnBranchActual()
int reportSolnBranchActual () const virtual
Report the solution branch which the solution is actually on.
Returns
Branch that the solution is restricted to. the value -1 means gas. The value -2 means superfluid.. Values of zero or greater refer to species dominated condensed phases.
Definition at line 42 of file MixtureFugacityTP.cpp.
References MixtureFugacityTP::iState_.
getdlnActCoeffdlnN_diag()
virtual void getdlnActCoeffdlnN_diag (doublereal * dlnActCoeffdlnN_diag) const inline virtual
Get the array of log species mole number derivatives of the log activity coefficients.
For ideal mixtures (unity activity coefficients), this can return zero. Implementations should take the derivative of the logarithm of the activity coefficient with respect to the logarithm of the concentration- like variable (i.e. moles) that represents the standard state. This quantity is to be used in conjunction with derivatives of that species mole number variable when the derivative of the chemical potential is taken.
units = dimensionless
Parameters
dlnActCoeffdlnN_diag Output vector of derivatives of the log Activity Coefficients. length = m_kk
Reimplemented from ThermoPhase.
Definition at line 118 of file MixtureFugacityTP.h.
getChemPotentials_RT()
void getChemPotentials_RT (doublereal * mu) const virtual
Get the array of non-dimensional species chemical potentials These are partial molar Gibbs free energies.
\(\mu_k / \hat R T \). Units: unitless
We close the loop on this function, here, calling getChemPotentials() and then dividing by RT. No need for child classes to handle.
Parameters
mu Output vector of non-dimensional species chemical potentials Length: m_kk.
Reimplemented from ThermoPhase.
Reimplemented in RedlichKwongMFTP.
Definition at line 49 of file MixtureFugacityTP.cpp.
References ThermoPhase::getChemPotentials(), Phase::m_kk, and ThermoPhase::RT().
getStandardChemPotentials()
void getStandardChemPotentials (doublereal * mu) const virtual
Get the array of chemical potentials at unit activity.
These are the standard state chemical potentials \(\mu^0_k(T,P) \). The values are evaluated at the current temperature and pressure.
For all objects with the Mixture Fugacity approximation, we define the standard state as an ideal gas at the current temperature and pressure of the solution.
Parameters
mu Output vector of standard state chemical potentials. length = m_kk. units are J / kmol.
Reimplemented from ThermoPhase.
Definition at line 59 of file MixtureFugacityTP.cpp.
References MixtureFugacityTP::_updateReferenceStateThermo(), MixtureFugacityTP::m_g0_RT, Phase::m_kk, Phase::pressure(), ThermoPhase::refPressure(), and ThermoPhase::RT().
getEnthalpy_RT()
void getEnthalpy_RT (doublereal * hrt) const virtual
Get the nondimensional Enthalpy functions for the species at their standard states at the current T and P of the solution.
For all objects with the Mixture Fugacity approximation, we define the standard state as an ideal gas at the current temperature and pressure of the solution.
Parameters
hrt Output vector of standard state enthalpies. length = m_kk. units are unitless.
Reimplemented from ThermoPhase.
Definition at line 69 of file MixtureFugacityTP.cpp.
References MixtureFugacityTP::getEnthalpy_RT_ref().
getEntropy_R()
void getEntropy_R (doublereal * sr) const virtual
Get the array of nondimensional Enthalpy functions for the standard state species at the current T and P of the solution.
For all objects with the Mixture Fugacity approximation, we define the standard state as an ideal gas at the current temperature and pressure of the solution.
Parameters
sr Output vector of nondimensional standard state entropies. length = m_kk.
Reimplemented from ThermoPhase.
Definition at line 74 of file MixtureFugacityTP.cpp.
References MixtureFugacityTP::_updateReferenceStateThermo(), Phase::m_kk, MixtureFugacityTP::m_s0_R, Phase::pressure(), and ThermoPhase::refPressure().
getGibbs_RT()
void getGibbs_RT (doublereal * grt) const virtual
Get the nondimensional Gibbs functions for the species at their standard states of solution at the current T and P of the solution.
For all objects with the Mixture Fugacity approximation, we define the standard state as an ideal gas at the current temperature and pressure of the solution.
Parameters
grt Output vector of nondimensional standard state Gibbs free energies. length = m_kk.
Reimplemented from ThermoPhase.
Definition at line 84 of file MixtureFugacityTP.cpp.
References MixtureFugacityTP::_updateReferenceStateThermo(), MixtureFugacityTP::m_g0_RT, Phase::m_kk, Phase::pressure(), and ThermoPhase::refPressure().
getPureGibbs()
void getPureGibbs (doublereal * gpure) const virtual
Get the pure Gibbs free energies of each species.
Species are assumed to be in their standard states.
This is the same as getStandardChemPotentials().
Parameters
[out] gpure Array of standard state Gibbs free energies. length = m_kk. units are J/kmol.
Reimplemented from ThermoPhase.
Definition at line 94 of file MixtureFugacityTP.cpp.
References MixtureFugacityTP::_updateReferenceStateThermo(), MixtureFugacityTP::m_g0_RT, Phase::m_kk, Phase::pressure(), ThermoPhase::refPressure(), ThermoPhase::RT(), and Cantera::scale().
getIntEnergy_RT()
void getIntEnergy_RT (doublereal * urt) const virtual
Returns the vector of nondimensional internal Energies of the standard state at the current temperature and pressure of the solution for each species.
For all objects with the Mixture Fugacity approximation, we define the standard state as an ideal gas at the current temperature and pressure of the solution.
\[ u^{ss}_k(T,P) = h^{ss}_k(T) - P * V^{ss}_k \]
Parameters
urt Output vector of nondimensional standard state internal energies. length = m_kk.
Reimplemented from ThermoPhase.
Definition at line 104 of file MixtureFugacityTP.cpp.
References MixtureFugacityTP::_updateReferenceStateThermo(), MixtureFugacityTP::m_h0_RT, and Phase::m_kk.
Referenced by RedlichKwongMFTP::getPartialMolarIntEnergies().
getCp_R()
void getCp_R (doublereal * cpr) const virtual
Get the nondimensional Heat Capacities at constant pressure for the standard state of the species at the current T and P.
For all objects with the Mixture Fugacity approximation, we define the standard state as an ideal gas at the current temperature and pressure of the solution.
Parameters
cpr Output vector containing the the nondimensional Heat Capacities at constant pressure for the standard state of the species. Length: m_kk.
Reimplemented from ThermoPhase.
Definition at line 113 of file MixtureFugacityTP.cpp.
References MixtureFugacityTP::_updateReferenceStateThermo(), and MixtureFugacityTP::m_cp0_R.
Referenced by RedlichKwongMFTP::getPartialMolarCp().
getStandardVolumes()
void getStandardVolumes (doublereal * vol) const virtual
Get the molar volumes of each species in their standard states at the current T and P of the solution.
For all objects with the Mixture Fugacity approximation, we define the standard state as an ideal gas at the current temperature and pressure of the solution.
units = m^3 / kmol
Parameters
vol Output vector of species volumes. length = m_kk. units = m^3 / kmol
Reimplemented from ThermoPhase.
Definition at line 119 of file MixtureFugacityTP.cpp.
References MixtureFugacityTP::_updateReferenceStateThermo(), Phase::m_kk, Phase::pressure(), and ThermoPhase::RT().
Referenced by RedlichKwongMFTP::standardConcentration().
setTemperature()
void setTemperature (const doublereal temp) virtual
Set the temperature of the phase.
Currently this passes down to setState_TP(). It does not make sense to calculate the standard state without first setting T and P.
Parameters
temp Temperature (kelvin)
Reimplemented from Phase.
Reimplemented in RedlichKwongMFTP.
Definition at line 223 of file MixtureFugacityTP.cpp.
References MixtureFugacityTP::_updateReferenceStateThermo(), Phase::density(), and Phase::temperature().
Referenced by MixtureFugacityTP::calculatePsat().
setPressure()
void setPressure (doublereal p) virtual
Set the internally stored pressure (Pa) at constant temperature and composition.
Currently this passes down to setState_TP(). It does not make sense to calculate the standard state without first setting T and P.
Parameters
p input Pressure (Pa)
Reimplemented from Phase.
Definition at line 229 of file MixtureFugacityTP.cpp.
References MixtureFugacityTP::setState_TP(), and Phase::temperature().
calcDensity()
void calcDensity () protected virtual
Calculate the density of the mixture using the partial molar volumes and mole fractions as input.
The formula for this is
\[ \rho = \frac{\sum_k{X_k W_k}}{\sum_k{X_k V_k}} \]
where \(X_k\) are the mole fractions, \(W_k\) are the molecular weights, and \(V_k\) are the pure species molar volumes.
Note, the basis behind this formula is that in an ideal solution the partial molar volumes are equal to the pure species molar volumes. We have additionally specified in this class that the pure species molar volumes are independent of temperature and pressure.
Reimplemented in RedlichKwongMFTP.
Definition at line 247 of file MixtureFugacityTP.cpp.
setState_TP()
void setState_TP (doublereal t, doublereal p) virtual
Set the temperature (K) and pressure (Pa)
Setting the pressure may involve the solution of a nonlinear equation.
Parameters
t Temperature (K)
p Pressure (Pa)
Reimplemented from ThermoPhase.
Definition at line 252 of file MixtureFugacityTP.cpp.
References MixtureFugacityTP::_updateReferenceStateThermo(), MixtureFugacityTP::forcedState_, Phase::getMoleFractions(), MixtureFugacityTP::moleFractions_, and Phase::setTemperature().
Referenced by MixtureFugacityTP::setPressure(), MixtureFugacityTP::setState_TPX(), and MixtureFugacityTP::setStateFromXML().
setState_TPX()
void setState_TPX (doublereal t, doublereal p, const doublereal * x) virtual
Set the temperature (K), pressure (Pa), and mole fractions.
Note, the mole fractions are set first before the pressure is set. Setting the pressure may involve the solution of a nonlinear equation.
Parameters
t Temperature (K)
p Pressure (Pa)
x Vector of mole fractions. Length is equal to m_kk.
Reimplemented from ThermoPhase.
Definition at line 328 of file MixtureFugacityTP.cpp.
References MixtureFugacityTP::setState_TP().
compositionChanged()
void compositionChanged () protected virtual
Apply changes to the state which are needed after the composition changes.
This function is called after any call to setMassFractions(), setMoleFractions(), or similar. For phases which need to execute a callback after any change to the composition, it should be done by overriding this function rather than overriding all of the composition- setting functions. Derived class implementations of compositionChanged() should call the parent class method as well.
Reimplemented from Phase.
Reimplemented in RedlichKwongMFTP.
Definition at line 234 of file MixtureFugacityTP.cpp.
References Phase::compositionChanged(), Phase::getMoleFractions(), and MixtureFugacityTP::moleFractions_.
Referenced by RedlichKwongMFTP::compositionChanged().
_updateReferenceStateThermo()
void _updateReferenceStateThermo () const protected virtual
Updates the reference state thermodynamic functions at the current T of the solution.
This function must be called for every call to functions in this class. It checks to see whether the temperature has changed and thus the ss thermodynamics functions for all of the species must be recalculated.
This function is responsible for updating the following internal members:
m_h0_RT;
m_cp0_R;
m_g0_RT;
m_s0_R;
Definition at line 792 of file MixtureFugacityTP.cpp.
References MixtureFugacityTP::m_cp0_R, MixtureFugacityTP::m_g0_RT, MixtureFugacityTP::m_h0_RT, Phase::m_kk, MixtureFugacityTP::m_s0_R, ThermoPhase::m_spthermo, MixtureFugacityTP::m_Tlast_ref, ThermoPhase::refPressure(), Phase::temperature(), and MultiSpeciesThermo::update().
Referenced by RedlichKwongMFTP::cp_mole(), RedlichKwongMFTP::cv_mole(), RedlichKwongMFTP::enthalpy_mole(), RedlichKwongMFTP::entropy_mole(), MixtureFugacityTP::getCp_R(), MixtureFugacityTP::getCp_R_ref(), MixtureFugacityTP::getEnthalpy_RT_ref(), MixtureFugacityTP::getEntropy_R(), MixtureFugacityTP::getEntropy_R_ref(), MixtureFugacityTP::getGibbs_RT(), MixtureFugacityTP::getGibbs_RT_ref(), MixtureFugacityTP::getIntEnergy_RT(), MixtureFugacityTP::getPureGibbs(), MixtureFugacityTP::getStandardChemPotentials(), MixtureFugacityTP::getStandardVolumes(), MixtureFugacityTP::getStandardVolumes_ref(), MixtureFugacityTP::gibbs_RT_ref(), RedlichKwongMFTP::pressure(), MixtureFugacityTP::setState_TP(), MixtureFugacityTP::setTemperature(), and RedlichKwongMFTP::setTemperature().
getEnthalpy_RT_ref()
void getEnthalpy_RT_ref (doublereal * hrt) const virtual
There are also temporary variables for holding the species reference- state values of Cp, H, S, and V at the last temperature and reference pressure called. These functions are not recalculated if a new call is made using the previous temperature. All calculations are done within the routine _updateRefStateThermo().
Reimplemented from ThermoPhase.
Definition at line 129 of file MixtureFugacityTP.cpp.
References MixtureFugacityTP::_updateReferenceStateThermo(), and MixtureFugacityTP::m_h0_RT.
Referenced by MixtureFugacityTP::getEnthalpy_RT(), and RedlichKwongMFTP::getPartialMolarEnthalpies().
getGibbs_RT_ref()
void getGibbs_RT_ref (doublereal * grt) const virtual
Returns the vector of nondimensional Gibbs Free Energies of the reference state at the current temperature of the solution and the reference pressure for the species.
Parameters
grt Output vector containing the nondimensional reference state Gibbs Free energies. Length: m_kk.
Reimplemented from ThermoPhase.
Definition at line 135 of file MixtureFugacityTP.cpp.
References MixtureFugacityTP::_updateReferenceStateThermo(), and MixtureFugacityTP::m_g0_RT.
gibbs_RT_ref()
const vector_fp & gibbs_RT_ref () const protected
Returns the vector of nondimensional Gibbs free energies of the reference state at the current temperature of the solution and the reference pressure for the species.
Returns
Output vector contains the nondimensional Gibbs free energies of the reference state of the species length = m_kk, units = dimensionless.
Definition at line 147 of file MixtureFugacityTP.cpp.
References MixtureFugacityTP::_updateReferenceStateThermo(), and MixtureFugacityTP::m_g0_RT.
Referenced by MixtureFugacityTP::getGibbs_ref().
getGibbs_ref()
void getGibbs_ref (doublereal * g) const virtual
Returns the vector of the Gibbs function of the reference state at the current temperature of the solution and the reference pressure for the species.
Parameters
g Output vector containing the reference state Gibbs Free energies. Length: m_kk. Units: J/kmol.
Reimplemented from ThermoPhase.
Definition at line 141 of file MixtureFugacityTP.cpp.
References MixtureFugacityTP::gibbs_RT_ref(), ThermoPhase::RT(), and Cantera::scale().
Referenced by RedlichKwongMFTP::getChemPotentials().
getEntropy_R_ref()
void getEntropy_R_ref (doublereal * er) const virtual
Returns the vector of nondimensional entropies of the reference state at the current temperature of the solution and the reference pressure for each species.
Parameters
er Output vector containing the nondimensional reference state entropies. Length: m_kk.
Reimplemented from ThermoPhase.
Definition at line 153 of file MixtureFugacityTP.cpp.
References MixtureFugacityTP::_updateReferenceStateThermo(), and MixtureFugacityTP::m_s0_R.
Referenced by RedlichKwongMFTP::getPartialMolarEntropies().
getCp_R_ref()
void getCp_R_ref (doublereal * cprt) const virtual
Returns the vector of nondimensional constant pressure heat capacities of the reference state at the current temperature of the solution and reference pressure for each species.
Parameters
cprt Output vector of nondimensional reference state heat capacities at constant pressure for the species. Length: m_kk
Reimplemented from ThermoPhase.
Definition at line 159 of file MixtureFugacityTP.cpp.
References MixtureFugacityTP::_updateReferenceStateThermo(), and MixtureFugacityTP::m_cp0_R.
getStandardVolumes_ref()
void getStandardVolumes_ref (doublereal * vol) const virtual
Get the molar volumes of the species reference states at the current T and P_ref of the solution.
units = m^3 / kmol
Parameters
vol Output vector containing the standard state volumes. Length: m_kk.
Reimplemented from ThermoPhase.
Definition at line 165 of file MixtureFugacityTP.cpp.
References MixtureFugacityTP::_updateReferenceStateThermo(), Phase::m_kk, ThermoPhase::refPressure(), and ThermoPhase::RT().
addSpecies()
bool addSpecies (shared_ptr< Species > spec) virtual
The following methods are used in the process of constructing the phase and setting its parameters from a specification in an input file. They are not normally used in application programs. To see how they are used, see importPhase().
Reimplemented from ThermoPhase.
Reimplemented in RedlichKwongMFTP.
Definition at line 206 of file MixtureFugacityTP.cpp.
References ThermoPhase::addSpecies(), MixtureFugacityTP::m_cp0_R, MixtureFugacityTP::m_g0_RT, MixtureFugacityTP::m_h0_RT, Phase::m_kk, MixtureFugacityTP::m_s0_R, and MixtureFugacityTP::moleFractions_.
Referenced by RedlichKwongMFTP::addSpecies().
setStateFromXML()
void setStateFromXML (const XML_Node & state) virtual
Set the initial state of the phase to the conditions specified in the state XML element.
This method sets the temperature, pressure, and mole fraction vector to a set default value.
Parameters
state AN XML_Node object corresponding to the "state" entry for this phase in the input file.
Deprecated:
The XML input format is deprecated and will be removed in Cantera 3.0.
Reimplemented from ThermoPhase.
Definition at line 173 of file MixtureFugacityTP.cpp.
References Phase::density(), Cantera::getChildValue(), Cantera::getFloat(), XML_Node::hasChild(), Phase::setMassFractionsByName(), Phase::setMoleFractionsByName(), MixtureFugacityTP::setState_TP(), and Phase::temperature().
z()
doublereal z () const protected
Calculate the value of z.
\[ z = \frac{P v}{R T} \]
returns the value of z
Definition at line 334 of file MixtureFugacityTP.cpp.
References Phase::density(), Phase::meanMolecularWeight(), Phase::pressure(), and ThermoPhase::RT().
Referenced by RedlichKwongMFTP::hresid(), and RedlichKwongMFTP::sresid().
sresid()
doublereal sresid () const protected virtual
Calculate the deviation terms for the total entropy of the mixture from the ideal gas mixture.
Reimplemented in RedlichKwongMFTP.
Definition at line 339 of file MixtureFugacityTP.cpp.
hresid()
doublereal hresid () const protected virtual
Calculate the deviation terms for the total enthalpy of the mixture from the ideal gas mixture.
Reimplemented in RedlichKwongMFTP.
Definition at line 344 of file MixtureFugacityTP.cpp.
psatEst()
doublereal psatEst (doublereal TKelvin) const protected virtual
Estimate for the saturation pressure.
Note: this is only used as a starting guess for later routines that actually calculate an accurate value for the saturation pressure.
Parameters
TKelvin temperature in kelvin
Returns
the estimated saturation pressure at the given temperature
Definition at line 349 of file MixtureFugacityTP.cpp.
References ThermoPhase::critPressure(), and ThermoPhase::critTemperature().
Referenced by MixtureFugacityTP::calculatePsat(), and RedlichKwongMFTP::liquidVolEst().
liquidVolEst()
doublereal liquidVolEst (doublereal TKelvin, doublereal & pres) const virtual
Estimate for the molar volume of the liquid.
Note: this is only used as a starting guess for later routines that actually calculate an accurate value for the liquid molar volume. This routine doesn't change the state of the system.
Parameters
TKelvin temperature in kelvin
pres Pressure in Pa. This is used as an initial guess. If the routine needs to change the pressure to find a stable liquid state, the new pressure is returned in this variable.
Returns
the estimate of the liquid volume. If the liquid can't be found, this routine returns -1.
Reimplemented in RedlichKwongMFTP.
Definition at line 360 of file MixtureFugacityTP.cpp.
Referenced by MixtureFugacityTP::calculatePsat().
densityCalc()
doublereal densityCalc (doublereal TKelvin, doublereal pressure, int phaseRequested, doublereal rhoguess) virtual
Calculates the density given the temperature and the pressure and a guess at the density.
Note, below T_c, this is a multivalued function. We do not cross the vapor dome in this. This is protected because it is called during setState_TP() routines. Infinite loops would result if it were not protected.
-> why is this not const?
Parameters
TKelvin Temperature in Kelvin
pressure Pressure in Pascals (Newton/m**2)
phaseRequested int representing the phase whose density we are requesting. If we put a gas or liquid phase here, we will attempt to find a volume in that part of the volume space, only, in this routine. A value of FLUID_UNDEFINED means that we will accept anything.
rhoguess Guessed density of the fluid. A value of -1.0 indicates that there is no guessed density
Returns
We return the density of the fluid at the requested phase. If we have not found any acceptable density we return a -1. If we have found an acceptable density at a different phase, we return a -2.
Reimplemented in RedlichKwongMFTP.
Definition at line 365 of file MixtureFugacityTP.cpp.
References ThermoPhase::critTemperature(), Cantera::GasConstant, and Phase::meanMolecularWeight().
Referenced by MixtureFugacityTP::calculatePsat(), and MixtureFugacityTP::corr0().
corr0()
int corr0 (doublereal TKelvin, doublereal pres, doublereal & densLiq, doublereal & densGas, doublereal & liqGRT, doublereal & gasGRT) protected
Utility routine in the calculation of the saturation pressure.
Parameters
TKelvin temperature (kelvin)
pres pressure (Pascal)
[out] densLiq density of liquid
[out] densGas density of gas
[out] liqGRT deltaG/RT of liquid
[out] gasGRT deltaG/RT of gas
Definition at line 505 of file MixtureFugacityTP.cpp.
References MixtureFugacityTP::densityCalc().
phaseState()
int phaseState (bool checkState = false) const
Returns the Phase State flag for the current state of the object.
Parameters
checkState If true, this function does a complete check to see where in parameters space we are
There are three values:
WATER_GAS below the critical temperature but below the critical density
WATER_LIQUID below the critical temperature but above the critical density
WATER_SUPERCRIT above the critical temperature
Definition at line 534 of file MixtureFugacityTP.cpp.
References ThermoPhase::critDensity(), ThermoPhase::critTemperature(), MixtureFugacityTP::iState_, and Phase::temperature().
densSpinodalLiquid()
doublereal densSpinodalLiquid () const virtual
Return the value of the density at the liquid spinodal point (on the liquid side) for the current temperature.
Returns
the density with units of kg m-3
Reimplemented in RedlichKwongMFTP.
Definition at line 575 of file MixtureFugacityTP.cpp.
densSpinodalGas()
doublereal densSpinodalGas () const virtual
Return the value of the density at the gas spinodal point (on the gas side) for the current temperature.
Returns
the density with units of kg m-3
Reimplemented in RedlichKwongMFTP.
Definition at line 580 of file MixtureFugacityTP.cpp.
calculatePsat()
doublereal calculatePsat (doublereal TKelvin, doublereal & molarVolGas, doublereal & molarVolLiquid)
Calculate the saturation pressure at the current mixture content for the given temperature.
Parameters
TKelvin (input) Temperature (Kelvin)
molarVolGas (return) Molar volume of the gas
molarVolLiquid (return) Molar volume of the liquid
Returns
the saturation pressure at the given temperature
Definition at line 592 of file MixtureFugacityTP.cpp.
References ThermoPhase::critTemperature(), Phase::density(), MixtureFugacityTP::densityCalc(), Cantera::GasConstant, MixtureFugacityTP::liquidVolEst(), Phase::meanMolecularWeight(), MixtureFugacityTP::psatEst(), MixtureFugacityTP::setTemperature(), and Phase::temperature().
Referenced by MixtureFugacityTP::satPressure().
satPressure()
doublereal satPressure (doublereal TKelvin) virtual
Calculate the saturation pressure at the current mixture content for the given temperature.
Parameters
TKelvin Temperature (Kelvin)
Returns
The saturation pressure at the given temperature
Reimplemented from ThermoPhase.
Definition at line 585 of file MixtureFugacityTP.cpp.
References MixtureFugacityTP::calculatePsat().
pressureCalc()
doublereal pressureCalc (doublereal TKelvin, doublereal molarVol) const protected virtual
Calculate the pressure given the temperature and the molar volume.
Parameters
TKelvin temperature in kelvin
molarVol molar volume (m3/kmol)
Returns
the pressure.
Reimplemented in RedlichKwongMFTP.
Definition at line 782 of file MixtureFugacityTP.cpp.
dpdVCalc()
doublereal dpdVCalc (doublereal TKelvin, doublereal molarVol, doublereal & presCalc) const protected virtual
Calculate the pressure and the pressure derivative given the temperature and the molar volume.
Temperature and mole number are held constant
Parameters
TKelvin temperature in kelvin
molarVol molar volume (m3/kmol)
presCalc Returns the pressure.
Returns
the derivative of the pressure wrt the molar volume
Reimplemented in RedlichKwongMFTP.
Definition at line 787 of file MixtureFugacityTP.cpp.
invalidateCache()
void invalidateCache () protected virtual
Invalidate any cached values which are normally updated only when a change in state is detected.
Reimplemented from ThermoPhase.
Definition at line 813 of file MixtureFugacityTP.cpp.
References ThermoPhase::invalidateCache(), and MixtureFugacityTP::m_Tlast_ref.
Member Data Documentation
moleFractions_
vector_fp moleFractions_ protected
Storage for the current values of the mole fractions of the species.
This vector is kept up-to-date when some the setState functions are called.
Definition at line 545 of file MixtureFugacityTP.h.
Referenced by MixtureFugacityTP::addSpecies(), RedlichKwongMFTP::calculateAB(), MixtureFugacityTP::compositionChanged(), RedlichKwongMFTP::critCompressibility(), RedlichKwongMFTP::critDensity(), RedlichKwongMFTP::critPressure(), RedlichKwongMFTP::critTemperature(), RedlichKwongMFTP::critVolume(), RedlichKwongMFTP::getActivityCoefficients(), RedlichKwongMFTP::getChemPotentials(), RedlichKwongMFTP::getPartialMolarEnthalpies(), RedlichKwongMFTP::getPartialMolarEntropies(), RedlichKwongMFTP::getPartialMolarVolumes(), MixtureFugacityTP::setState_TP(), and RedlichKwongMFTP::updateAB().
iState_
int iState_ protected
Current state of the fluid.
There are three possible states of the fluid:
FLUID_GAS
FLUID_LIQUID
FLUID_SUPERCRIT
Definition at line 554 of file MixtureFugacityTP.h.
Referenced by MixtureFugacityTP::phaseState(), and MixtureFugacityTP::reportSolnBranchActual().
forcedState_
int forcedState_ protected
Force the system to be on a particular side of the spinodal curve.
Definition at line 557 of file MixtureFugacityTP.h.
Referenced by MixtureFugacityTP::forcedSolutionBranch(), MixtureFugacityTP::setForcedSolutionBranch(), and MixtureFugacityTP::setState_TP().
m_Tlast_ref
doublereal m_Tlast_ref mutable protected
The last temperature at which the reference state thermodynamic properties were calculated at.
Definition at line 561 of file MixtureFugacityTP.h.
Referenced by MixtureFugacityTP::_updateReferenceStateThermo(), and MixtureFugacityTP::invalidateCache().
m_h0_RT
vector_fp m_h0_RT mutable protected
Temporary storage for dimensionless reference state enthalpies.
Definition at line 564 of file MixtureFugacityTP.h.
Referenced by MixtureFugacityTP::_updateReferenceStateThermo(), MixtureFugacityTP::addSpecies(), RedlichKwongMFTP::enthalpy_mole(), MixtureFugacityTP::getEnthalpy_RT_ref(), and MixtureFugacityTP::getIntEnergy_RT().
m_cp0_R
vector_fp m_cp0_R mutable protected
Temporary storage for dimensionless reference state heat capacities.
Definition at line 567 of file MixtureFugacityTP.h.
Referenced by MixtureFugacityTP::_updateReferenceStateThermo(), MixtureFugacityTP::addSpecies(), RedlichKwongMFTP::cp_mole(), RedlichKwongMFTP::cv_mole(), MixtureFugacityTP::getCp_R(), and MixtureFugacityTP::getCp_R_ref().
m_g0_RT
vector_fp m_g0_RT mutable protected
Temporary storage for dimensionless reference state Gibbs energies.
Definition at line 570 of file MixtureFugacityTP.h.
Referenced by MixtureFugacityTP::_updateReferenceStateThermo(), MixtureFugacityTP::addSpecies(), MixtureFugacityTP::getGibbs_RT(), MixtureFugacityTP::getGibbs_RT_ref(), MixtureFugacityTP::getPureGibbs(), MixtureFugacityTP::getStandardChemPotentials(), and MixtureFugacityTP::gibbs_RT_ref().
m_s0_R
vector_fp m_s0_R mutable protected
Temporary storage for dimensionless reference state entropies.
Definition at line 573 of file MixtureFugacityTP.h.
Referenced by MixtureFugacityTP::_updateReferenceStateThermo(), MixtureFugacityTP::addSpecies(), RedlichKwongMFTP::entropy_mole(), MixtureFugacityTP::getEntropy_R(), and MixtureFugacityTP::getEntropy_R_ref().
The documentation for this class was generated from the following files:
MixtureFugacityTP.h
MixtureFugacityTP.cpp