Cantera: LTI_MoleFracs Class Reference
LTI_MoleFracs Class Reference
Simple mole fraction weighting of transport properties.
#include <LiquidTranInteraction.h>
Public Member Functions
LTI_MoleFracs (TransportPropertyType tp_ind=TP_UNKNOWN)
doublereal getMixTransProp (doublereal *valueSpecies, doublereal *weightSpecies=0)
Return the mixture transport property value.
doublereal getMixTransProp (std::vector< LTPspecies *> LTPptrs)
void getMatrixTransProp (DenseMatrix &mat, doublereal *speciesValues=0)
Return the matrix of binary interaction parameters.
Public Member Functions inherited from LiquidTranInteraction
LiquidTranInteraction (TransportPropertyType tp_ind=TP_UNKNOWN)
Constructor.
virtual void init (const XML_Node &compModelNode=XML_Node(), thermo_t *thermo=0)
initialize LiquidTranInteraction objects with thermo and XML node
virtual void setParameters (LiquidTransportParams &trParam)
Additional Inherited Members
Protected Attributes inherited from LiquidTranInteraction
LiquidTranMixingModel m_model
Model for species interaction effects. Takes enum LiquidTranMixingModel.
TransportPropertyType m_property
enum indicating what property this is (i.e viscosity)
thermo_t * m_thermo
pointer to thermo object to get current temperature
std::vector< DenseMatrix * > m_Aij
Matrix of interaction coefficients for polynomial in molefraction*weight of speciesA (no temperature dependence, dimensionless)
std::vector< DenseMatrix * > m_Bij
Matrix of interaction coefficients for polynomial in molefraction*weight of speciesA (linear temperature dependence, units 1/K)
DenseMatrix m_Eij
Matrix of interactions (in energy units, 1/RT temperature dependence)
std::vector< DenseMatrix * > m_Hij
Matrix of interaction coefficients for polynomial in molefraction*weight of speciesA (in energy units, 1/RT temperature dependence)
std::vector< DenseMatrix * > m_Sij
Matrix of interaction coefficients for polynomial in molefraction*weight of speciesA (in entropy units, divided by R)
DenseMatrix m_Dij
Matrix of interactions.
Detailed Description
Simple mole fraction weighting of transport properties.
This model weights the transport property by the mole fractions. The overall formula for the mixture viscosity is
\[ \eta_{mix} = \sum_i X_i \eta_i + \sum_i \sum_j X_i X_j A_{i,j} \]
Definition at line 206 of file LiquidTranInteraction.h.
Member Function Documentation
getMixTransProp()
doublereal getMixTransProp (doublereal * valueSpecies, doublereal * weightSpecies = 0) virtual
Return the mixture transport property value.
Takes the separate species transport properties as input (this method does not know what transport property it is at this point.
Reimplemented from LiquidTranInteraction.
Definition at line 226 of file LiquidTranInteraction.cpp.
References Phase::getMoleFractions(), LiquidTranInteraction::m_Aij, LiquidTranInteraction::m_Bij, LiquidTranInteraction::m_thermo, Phase::nSpecies(), and Phase::temperature().
getMatrixTransProp()
void getMatrixTransProp (DenseMatrix & mat, doublereal * speciesValues = 0) inline virtual
Return the matrix of binary interaction parameters.
Takes the proper mixing rule for the binary interaction parameters and calculates them: Not Implemented for this Mixing rule;
Reimplemented from LiquidTranInteraction.
Definition at line 227 of file LiquidTranInteraction.h.
References LiquidTranInteraction::m_Aij.
The documentation for this class was generated from the following files:
LiquidTranInteraction.h
LiquidTranInteraction.cpp