Cantera: ThermoFactory Class Reference
ThermoFactory Class Reference
Factory class for thermodynamic property managers.
#include <ThermoFactory.h>
Public Member Functions
virtual void deleteFactory ()
delete the static instance of this factory
virtual ThermoPhase * newThermoPhase (const std::string &model)
Create a new thermodynamic property manager.
Public Member Functions inherited from Factory< ThermoPhase >
ThermoPhase * create (const std::string &name, Args... args)
Create an object using the object construction function corresponding to "name" and the provided constructor arguments.
void reg (const std::string &name, std::function< ThermoPhase *(Args...)> f)
Register a new object construction function.
void addAlias (const std::string &original, const std::string &alias)
Add an alias for an existing registered type.
std::string canonicalize (const std::string &name)
Get the canonical name registered for a type.
bool exists (const std::string &name) const
Returns true if name is registered with this factory.
Public Member Functions inherited from FactoryBase
virtual ~FactoryBase ()
destructor
Static Public Member Functions
static ThermoFactory * factory ()
Static function that creates a static instance of the factory.
Static Public Member Functions inherited from FactoryBase
static void deleteFactories ()
static function that deletes all factories in the internal registry maintained in a static variable
Private Member Functions
ThermoFactory ()
Private constructors prevents usage.
Static Private Attributes
static ThermoFactory * s_factory = 0
static member of a single instance
static std::mutex thermo_mutex
Decl for locking mutex for thermo factory singleton.
Additional Inherited Members
Protected Member Functions inherited from Factory< ThermoPhase >
void addDeprecatedAlias (const std::string &original, const std::string &alias)
Add a deprecated alias for an existing registered type.
Protected Member Functions inherited from FactoryBase
FactoryBase ()
Constructor.
Detailed Description
Factory class for thermodynamic property managers.
This class keeps a list of the known ThermoPhase classes, and is used to create new instances of these classes.
Definition at line 54 of file ThermoFactory.h.
Constructor & Destructor Documentation
ThermoFactory()
ThermoFactory () private
Private constructors prevents usage.
Definition at line 50 of file ThermoFactory.cpp.
Referenced by ThermoFactory::factory().
Member Function Documentation
factory()
static ThermoFactory* factory () inline static
Static function that creates a static instance of the factory.
Definition at line 58 of file ThermoFactory.h.
References ThermoFactory::s_factory, ThermoFactory::thermo_mutex, and ThermoFactory::ThermoFactory().
Referenced by Cantera::newThermoPhase().
deleteFactory()
virtual void deleteFactory () inline virtual
delete the static instance of this factory
Implements FactoryBase.
Definition at line 67 of file ThermoFactory.h.
References ThermoFactory::s_factory, and ThermoFactory::thermo_mutex.
newThermoPhase()
ThermoPhase * newThermoPhase (const std::string & model) virtual
Create a new thermodynamic property manager.
Parameters
model String to look up the model against
Returns
a pointer to a new ThermoPhase instance matching the model string. Returns NULL if something went wrong. Throws an exception UnknownThermoPhaseModel if the string wasn't matched.
Definition at line 99 of file ThermoFactory.cpp.
Member Data Documentation
s_factory
ThermoFactory * s_factory = 0 static private
static member of a single instance
Definition at line 84 of file ThermoFactory.h.
Referenced by ThermoFactory::deleteFactory(), and ThermoFactory::factory().
thermo_mutex
std::mutex thermo_mutex static private
Decl for locking mutex for thermo factory singleton.
Definition at line 90 of file ThermoFactory.h.
Referenced by ThermoFactory::deleteFactory(), and ThermoFactory::factory().
The documentation for this class was generated from the following files:
ThermoFactory.h
ThermoFactory.cpp