Cantera: VCS_SPECIES_THERMO Class Reference
VCS_SPECIES_THERMO Class Reference
#include <vcs_species_thermo.h>
Public Member Functions
VCS_SPECIES_THERMO (size_t indexPhase, size_t indexSpeciesPhase)
virtual VCS_SPECIES_THERMO * duplMyselfAsVCS_SPECIES_THERMO ()
Duplication function for derived classes.
virtual double GStar_R_calc (size_t kspec, double TKelvin, double pres)
This function calculates the standard state Gibbs free energy for species, kspec, at the temperature TKelvin and pressure, Pres.
virtual double G0_R_calc (size_t kglob, double TKelvin)
This function calculates the standard state Gibbs free energy for species, kspec, at the temperature TKelvin.
virtual double VolStar_calc (size_t kglob, double TKelvin, double Pres)
This function calculates the standard state molar volume for species, kspec, at the temperature TKelvin and pressure, Pres,.
virtual double eval_ac (size_t kspec)
This function evaluates the activity coefficient for species, kspec.
Public Attributes
size_t IndexPhase
Index of the phase that this species belongs to.
size_t IndexSpeciesPhase
Index of this species in the current phase.
vcs_VolPhase * OwningPhase
Pointer to the owning phase object.
int SS0_Model
Integer representing the models for the species standard state Naught temperature dependence.
double SS0_feSave
Internal storage of the last calculation of the reference naught Gibbs free energy at SS0_TSave.
double SS0_TSave
Internal storage of the last temperature used in the calculation of the reference naught Gibbs free energy.
double SS0_T0
Base temperature used in the VCS_SS0_CONSTANT_CP model.
double SS0_H0
Base enthalpy used in the VCS_SS0_CONSTANT_CP model.
double SS0_S0
Base entropy used in the VCS_SS0_CONSTANT_CP model.
double SS0_Cp0
Base heat capacity used in the VCS_SS0_CONSTANT_CP model.
double SS0_Pref
Value of the pressure for the reference state.
int SSStar_Model
Integer value representing the star state model.
int SSStar_Vol_Model
Models for the standard state volume of each species.
double SSStar_Vol0
parameter that is used in the VCS_SSVOL_CONSTANT model.
Detailed Description
Identifies the thermo model for the species. This structure is shared by volumetric and surface species. However, each will have its own types of thermodynamic models. These quantities all have appropriate units.
Definition at line 32 of file vcs_species_thermo.h.
Member Function Documentation
duplMyselfAsVCS_SPECIES_THERMO()
VCS_SPECIES_THERMO * duplMyselfAsVCS_SPECIES_THERMO () virtual
Duplication function for derived classes.
Definition at line 39 of file vcs_species_thermo.cpp.
GStar_R_calc()
double GStar_R_calc (size_t kspec, double TKelvin, double pres) virtual
This function calculates the standard state Gibbs free energy for species, kspec, at the temperature TKelvin and pressure, Pres.
Parameters
kspec species global index
TKelvin Temperature in Kelvin
pres pressure in Pa
Returns
standard state free energy in units of Kelvin.
Deprecated:
Unused. To be removed after Cantera 2.3.
Definition at line 44 of file vcs_species_thermo.cpp.
References VCS_SPECIES_THERMO::G0_R_calc(), Cantera::GasConstant, vcs_VolPhase::GStar_calc_one(), VCS_SPECIES_THERMO::IndexSpeciesPhase, VCS_SPECIES_THERMO::OwningPhase, vcs_VolPhase::setState_TP(), and Cantera::warn_deprecated().
G0_R_calc()
double G0_R_calc (size_t kglob, double TKelvin) virtual
This function calculates the standard state Gibbs free energy for species, kspec, at the temperature TKelvin.
Parameters
kglob species global index.
TKelvin Temperature in Kelvin
Returns
standard state free energy in Kelvin.
Deprecated:
Unused. To be removed after Cantera 2.3.
Definition at line 64 of file vcs_species_thermo.cpp.
References VCS_SPECIES_THERMO::SS0_Model, and Cantera::warn_deprecated().
Referenced by VCS_SPECIES_THERMO::GStar_R_calc().
VolStar_calc()
double VolStar_calc (size_t kglob, double TKelvin, double Pres) virtual
This function calculates the standard state molar volume for species, kspec, at the temperature TKelvin and pressure, Pres,.
Returns
standard state volume in m**3 / kmol
Deprecated:
Unused. To be removed after Cantera 2.3.
Definition at line 55 of file vcs_species_thermo.cpp.
References VCS_SPECIES_THERMO::IndexSpeciesPhase, VCS_SPECIES_THERMO::OwningPhase, vcs_VolPhase::setState_TP(), vcs_VolPhase::VolStar_calc_one(), and Cantera::warn_deprecated().
eval_ac()
double eval_ac (size_t kspec) virtual
This function evaluates the activity coefficient for species, kspec.
Note, T, P and mole fractions are obtained from the single private instance of VCS_SOLVE
Parameters
kspec index of the species in the global species list within VCS_SOLVE. Phase and local species id can be looked up within object.
Returns
activity coefficient for species kspec
Deprecated:
Unused. To be removed after Cantera 2.3.
Definition at line 82 of file vcs_species_thermo.cpp.
References vcs_VolPhase::AC_calc_one(), VCS_SPECIES_THERMO::IndexSpeciesPhase, VCS_SPECIES_THERMO::OwningPhase, and Cantera::warn_deprecated().
Member Data Documentation
IndexPhase
size_t IndexPhase
Index of the phase that this species belongs to.
Definition at line 39 of file vcs_species_thermo.h.
IndexSpeciesPhase
size_t IndexSpeciesPhase
Index of this species in the current phase.
Definition at line 42 of file vcs_species_thermo.h.
Referenced by VCS_SPECIES_THERMO::eval_ac(), VCS_SPECIES_THERMO::GStar_R_calc(), and VCS_SPECIES_THERMO::VolStar_calc().
OwningPhase
vcs_VolPhase* OwningPhase
Pointer to the owning phase object.
Definition at line 45 of file vcs_species_thermo.h.
Referenced by VCS_SPECIES_THERMO::eval_ac(), VCS_SPECIES_THERMO::GStar_R_calc(), and VCS_SPECIES_THERMO::VolStar_calc().
SS0_Model
int SS0_Model
Integer representing the models for the species standard state Naught temperature dependence.
They are listed above and start with VCS_SS0_...
Definition at line 49 of file vcs_species_thermo.h.
Referenced by VCS_SPECIES_THERMO::G0_R_calc().
SS0_feSave
double SS0_feSave
Internal storage of the last calculation of the reference naught Gibbs free energy at SS0_TSave.
(always in units of Kelvin)
Definition at line 53 of file vcs_species_thermo.h.
SS0_TSave
double SS0_TSave
Internal storage of the last temperature used in the calculation of the reference naught Gibbs free energy.
units = kelvin
Definition at line 57 of file vcs_species_thermo.h.
SS0_T0
double SS0_T0
Base temperature used in the VCS_SS0_CONSTANT_CP model.
Definition at line 60 of file vcs_species_thermo.h.
SS0_H0
double SS0_H0
Base enthalpy used in the VCS_SS0_CONSTANT_CP model.
Definition at line 63 of file vcs_species_thermo.h.
SS0_S0
double SS0_S0
Base entropy used in the VCS_SS0_CONSTANT_CP model.
Definition at line 66 of file vcs_species_thermo.h.
SS0_Cp0
double SS0_Cp0
Base heat capacity used in the VCS_SS0_CONSTANT_CP model.
Definition at line 69 of file vcs_species_thermo.h.
SS0_Pref
double SS0_Pref
Value of the pressure for the reference state.
defaults to 1.01325E5 = 1 atm
Definition at line 73 of file vcs_species_thermo.h.
SSStar_Model
int SSStar_Model
Integer value representing the star state model.
Definition at line 76 of file vcs_species_thermo.h.
SSStar_Vol_Model
int SSStar_Vol_Model
Models for the standard state volume of each species.
Definition at line 79 of file vcs_species_thermo.h.
SSStar_Vol0
double SSStar_Vol0
parameter that is used in the VCS_SSVOL_CONSTANT model.
Definition at line 82 of file vcs_species_thermo.h.
The documentation for this class was generated from the following files:
vcs_species_thermo.h
vcs_species_thermo.cpp