Cantera: AqueousKinetics Class Reference
AqueousKinetics Class Reference
Kinetics manager for elementary aqueous-phase chemistry.
#include <AqueousKinetics.h>
Public Member Functions
AqueousKinetics (thermo_t *thermo=0)
Constructor. Creates an empty reaction mechanism.
virtual Kinetics * duplMyselfAsKinetics (const std::vector< thermo_t *> &tpVector) const
Duplication routine for objects which inherit from Kinetics.
virtual int type () const
Identifies the kinetics manager type.
virtual std::string kineticsType () const
Identifies the Kinetics manager type.
virtual void getEquilibriumConstants (doublereal *kc)
Return a vector of Equilibrium constants.
virtual void getFwdRateConstants (doublereal *kfwd)
Return the forward rate constants.
void updateROP ()
void _update_rates_T ()
Update temperature-dependent portions of reaction rates.
void _update_rates_C ()
Update properties that depend on concentrations.
void updateKc ()
Update the equilibrium constants in molar units.
virtual bool addReaction (shared_ptr< Reaction > r)
Add a single reaction to the mechanism.
virtual void modifyReaction (size_t i, shared_ptr< Reaction > rNew)
Modify the rate expression associated with a reaction.
Public Member Functions inherited from BulkKinetics
BulkKinetics (thermo_t *thermo=0)
virtual bool isReversible (size_t i)
True if reaction i has been declared to be reversible.
virtual void getDeltaGibbs (doublereal *deltaG)
Return the vector of values for the reaction Gibbs free energy change.
virtual void getDeltaEnthalpy (doublereal *deltaH)
Return the vector of values for the reactions change in enthalpy.
virtual void getDeltaEntropy (doublereal *deltaS)
Return the vector of values for the reactions change in entropy.
virtual void getDeltaSSGibbs (doublereal *deltaG)
Return the vector of values for the reaction standard state Gibbs free energy change.
virtual void getDeltaSSEnthalpy (doublereal *deltaH)
Return the vector of values for the change in the standard state enthalpies of reaction.
virtual void getDeltaSSEntropy (doublereal *deltaS)
Return the vector of values for the change in the standard state entropies for each reaction.
virtual void getRevRateConstants (doublereal *krev, bool doIrreversible=false)
Return the reverse rate constants.
virtual void resizeSpecies ()
Resize arrays with sizes that depend on the total number of species.
virtual void setMultiplier (size_t i, double f)
Set the multiplier for reaction i to f.
virtual void invalidateCache ()
Public Member Functions inherited from Kinetics
virtual bool ready () const
Returns true if the kinetics manager has been properly initialized and finalized.
virtual std::pair< size_t, size_t > checkDuplicates (bool throw_err=true) const
Check for duplicate reactions.
void selectPhase (const doublereal *data, const thermo_t *phase, doublereal *phase_data)
Kinetics ()
Default constructor.
virtual ~Kinetics ()
Kinetics (const Kinetics &)
Kinetics & operator= (const Kinetics &right)
virtual void assignShallowPointers (const std::vector< thermo_t *> &tpVector)
Reassign the pointers within the Kinetics object.
size_t nReactions () const
Number of reactions in the reaction mechanism.
void checkReactionIndex (size_t m) const
Check that the specified reaction index is in range Throws an exception if i is greater than nReactions()
void checkReactionArraySize (size_t ii) const
Check that an array size is at least nReactions() Throws an exception if ii is less than nReactions().
void checkSpeciesIndex (size_t k) const
Check that the specified species index is in range Throws an exception if k is greater than nSpecies()-1.
void checkSpeciesArraySize (size_t mm) const
Check that an array size is at least nSpecies() Throws an exception if kk is less than nSpecies().
size_t nPhases () const
The number of phases participating in the reaction mechanism.
void checkPhaseIndex (size_t m) const
Check that the specified phase index is in range Throws an exception if m is greater than nPhases()
void checkPhaseArraySize (size_t mm) const
Check that an array size is at least nPhases() Throws an exception if mm is less than nPhases().
size_t phaseIndex (const std::string &ph)
Return the phase index of a phase in the list of phases defined within the object.
size_t surfacePhaseIndex ()
This returns the integer index of the phase which has ThermoPhase type cSurf.
size_t reactionPhaseIndex ()
Phase where the reactions occur.
thermo_t & thermo (size_t n=0)
This method returns a reference to the nth ThermoPhase object defined in this kinetics mechanism.
const thermo_t & thermo (size_t n=0) const
size_t nTotalSpecies () const
The total number of species in all phases participating in the kinetics mechanism.
size_t kineticsSpeciesIndex (size_t k, size_t n) const
The location of species k of phase n in species arrays.
std::string kineticsSpeciesName (size_t k) const
Return the name of the kth species in the kinetics manager.
size_t kineticsSpeciesIndex (const std::string &nm) const
This routine will look up a species number based on the input std::string nm.
size_t kineticsSpeciesIndex (const std::string &nm, const std::string &ph) const
This routine will look up a species number based on the input std::string nm.
thermo_t & speciesPhase (const std::string &nm)
This function looks up the name of a species and returns a reference to the ThermoPhase object of the phase where the species resides.
thermo_t & speciesPhase (size_t k)
This function takes as an argument the kineticsSpecies index (i.e., the list index in the list of species in the kinetics manager) and returns the species' owning ThermoPhase object.
size_t speciesPhaseIndex (size_t k)
This function takes as an argument the kineticsSpecies index (i.e., the list index in the list of species in the kinetics manager) and returns the index of the phase owning the species.
virtual void getFwdRatesOfProgress (doublereal *fwdROP)
Return the forward rates of progress of the reactions.
virtual void getRevRatesOfProgress (doublereal *revROP)
Return the Reverse rates of progress of the reactions.
virtual void getNetRatesOfProgress (doublereal *netROP)
Net rates of progress.
virtual void getReactionDelta (const doublereal *property, doublereal *deltaProperty)
Change in species properties.
virtual void getRevReactionDelta (const doublereal *g, doublereal *dg)
Given an array of species properties 'g', return in array 'dg' the change in this quantity in the reversible reactions.
virtual void getDeltaElectrochemPotentials (doublereal *deltaM)
Return the vector of values for the reaction electrochemical free energy change.
virtual void getCreationRates (doublereal *cdot)
Species creation rates [kmol/m^3/s or kmol/m^2/s].
virtual void getDestructionRates (doublereal *ddot)
Species destruction rates [kmol/m^3/s or kmol/m^2/s].
virtual void getNetProductionRates (doublereal *wdot)
Species net production rates [kmol/m^3/s or kmol/m^2/s].
virtual double reactantStoichCoeff (size_t k, size_t i) const
Stoichiometric coefficient of species k as a reactant in reaction i.
virtual double productStoichCoeff (size_t k, size_t i) const
Stoichiometric coefficient of species k as a product in reaction i.
virtual doublereal reactantOrder (size_t k, size_t i) const
Reactant order of species k in reaction i.
virtual doublereal productOrder (int k, int i) const
product Order of species k in reaction i.
virtual void getActivityConcentrations (doublereal *const conc)
Get the vector of activity concentrations used in the kinetics object.
virtual int reactionType (size_t i) const
Flag specifying the type of reaction.
std::string reactionString (size_t i) const
Return a string representing the reaction.
std::string reactantString (size_t i) const
Returns a string containing the reactants side of the reaction equation.
std::string productString (size_t i) const
Returns a string containing the products side of the reaction equation.
virtual void addPhase (thermo_t &thermo)
Add a phase to the kinetics manager object.
virtual void init ()
Prepare the class for the addition of reactions, after all phases have been added.
virtual void finalize ()
Finish adding reactions and prepare for use.
shared_ptr< Reaction > reaction (size_t i)
Return the Reaction object for reaction i.
shared_ptr< const Reaction > reaction (size_t i) const
void skipUndeclaredSpecies (bool skip)
Determine behavior when adding a new reaction that contains species not defined in any of the phases associated with this kinetics manager.
void skipUndeclaredThirdBodies (bool skip)
Determine behavior when adding a new reaction that contains third-body efficiencies for species not defined in any of the phases associated with this kinetics manager.
doublereal multiplier (size_t i) const
The current value of the multiplier for reaction i.
Additional Inherited Members
Protected Member Functions inherited from BulkKinetics
virtual void addElementaryReaction (ElementaryReaction &r)
virtual void modifyElementaryReaction (size_t i, ElementaryReaction &rNew)
Protected Member Functions inherited from Kinetics
double checkDuplicateStoich (std::map< int, double > &r1, std::map< int, double > &r2) const
Check whether r1 and r2 represent duplicate stoichiometries This function returns a ratio if two reactions are duplicates of one another, and 0.0 otherwise.
void checkReactionBalance (const Reaction &R)
Check that the specified reaction is balanced (same number of atoms for each element in the reactants and products).
Protected Attributes inherited from BulkKinetics
Rate1< Arrhenius > m_rates
std::vector< size_t > m_revindex
Indices of reversible reactions.
std::vector< size_t > m_irrev
Indices of irreversible reactions.
vector_fp m_dn
Difference between the global reactants order and the global products order.
vector_fp m_conc
vector_fp m_grt
bool m_ROP_ok
doublereal m_temp
Protected Attributes inherited from Kinetics
ValueCache m_cache
Cache for saved calculations within each Kinetics object.
size_t m_kk
The number of species in all of the phases that participate in this kinetics mechanism.
vector_fp m_perturb
Vector of perturbation factors for each reaction's rate of progress vector.
std::vector< shared_ptr< Reaction > > m_reactions
Vector of Reaction objects represented by this Kinetics manager.
std::vector< thermo_t * > m_thermo
m_thermo is a vector of pointers to ThermoPhase objects that are involved with this kinetics operator
std::vector< size_t > m_start
m_start is a vector of integers specifying the beginning position for the species vector for the n'th phase in the kinetics class.
std::map< std::string, size_t > m_phaseindex
Mapping of the phase id, i.e., the id attribute in the XML phase element to the position of the phase within the kinetics object.
size_t m_surfphase
Index in the list of phases of the one surface phase.
size_t m_rxnphase
Phase Index where reactions are assumed to be taking place.
size_t m_mindim
number of spatial dimensions of lowest-dimensional phase.
vector_fp m_rfn
Forward rate constant for each reaction.
vector_fp m_rkcn
Reciprocal of the equilibrium constant in concentration units.
vector_fp m_ropf
Forward rate-of-progress for each reaction.
vector_fp m_ropr
Reverse rate-of-progress for each reaction.
vector_fp m_ropnet
Net rate-of-progress for each reaction.
bool m_skipUndeclaredSpecies
bool m_skipUndeclaredThirdBodies
StoichManagerN m_reactantStoich
Stoichiometry manager for the reactants for each reaction.
StoichManagerN m_revProductStoich
Stoichiometry manager for the products of reversible reactions.
StoichManagerN m_irrevProductStoich
Stoichiometry manager for the products of irreversible reactions.
Detailed Description
Kinetics manager for elementary aqueous-phase chemistry.
This kinetics manager implements standard mass-action reaction rate expressions for liquids
Attention
This class currently does not have any test cases or examples. Its implementation may be incomplete, and future changes to Cantera may unexpectedly cause this class to stop working. If you use this class, please consider contributing examples or test cases. In the absence of new tests or examples, this class may be deprecated and removed in a future version of Cantera. See https://github.com/Cantera/cantera/issues/267 for additional information.
Definition at line 31 of file AqueousKinetics.h.
Constructor & Destructor Documentation
AqueousKinetics()
AqueousKinetics (thermo_t * thermo = 0)
Constructor. Creates an empty reaction mechanism.
Definition at line 18 of file AqueousKinetics.cpp.
Referenced by AqueousKinetics::duplMyselfAsKinetics().
Member Function Documentation
duplMyselfAsKinetics()
Kinetics * duplMyselfAsKinetics (const std::vector< thermo_t *> & tpVector) const virtual
Duplication routine for objects which inherit from Kinetics.
This virtual routine can be used to duplicate Kinetics objects inherited from Kinetics even if the application only has a pointer to Kinetics to work with.
These routines are basically wrappers around the derived copy constructor.
Parameters
tpVector Vector of shallow pointers to ThermoPhase objects. this is the m_thermo vector within this object
Reimplemented from BulkKinetics.
Definition at line 23 of file AqueousKinetics.cpp.
References AqueousKinetics::AqueousKinetics(), and Kinetics::assignShallowPointers().
type()
virtual int type () const inline virtual
Identifies the kinetics manager type.
Each class derived from Kinetics should overload this method to return a unique integer. Standard values are defined in file mix_defs.h.
Deprecated:
Use kineticsType() instead. To be removed after Cantera 2.3.
Reimplemented from Kinetics.
Definition at line 50 of file AqueousKinetics.h.
References Cantera::warn_deprecated().
kineticsType()
virtual std::string kineticsType () const inline virtual
Identifies the Kinetics manager type.
Each class derived from Kinetics should override this method to return a meaningful identifier.
Reimplemented from Kinetics.
Definition at line 56 of file AqueousKinetics.h.
getEquilibriumConstants()
void getEquilibriumConstants (doublereal * kc) virtual
Return a vector of Equilibrium constants.
Return the equilibrium constants of the reactions in concentration units in array kc, which must be dimensioned at least as large as the total number of reactions.
\[ Kc_i = exp [ \Delta G_{ss,i} ] prod(Cs_k) exp(\sum_k \nu_{k,i} F \phi_n) ] \]
Parameters
kc Output vector containing the equilibrium constants. Length: nReactions().
Reimplemented from Kinetics.
Definition at line 69 of file AqueousKinetics.cpp.
References AqueousKinetics::_update_rates_T(), Cantera::GasConstant, Kinetics::getReactionDelta(), ThermoPhase::getStandardChemPotentials(), ThermoPhase::logStandardConc(), Kinetics::m_rkcn, Kinetics::nReactions(), Phase::nSpecies(), ThermoPhase::RT(), and Kinetics::thermo().
getFwdRateConstants()
void getFwdRateConstants (doublereal * kfwd) virtual
Return the forward rate constants.
length is the number of reactions. units depends on many issues.
Parameters
kfwd Output vector containing the forward reaction rate constants. Length: nReactions().
Reimplemented from Kinetics.
Definition at line 128 of file AqueousKinetics.cpp.
References AqueousKinetics::_update_rates_C(), AqueousKinetics::_update_rates_T(), Kinetics::m_perturb, Kinetics::m_rfn, Kinetics::m_ropf, Cantera::multiply_each(), and Kinetics::nReactions().
_update_rates_T()
void _update_rates_T ()
Update temperature-dependent portions of reaction rates.
Definition at line 30 of file AqueousKinetics.cpp.
Referenced by AqueousKinetics::getEquilibriumConstants(), and AqueousKinetics::getFwdRateConstants().
_update_rates_C()
void _update_rates_C ()
Update properties that depend on concentrations.
Definition at line 40 of file AqueousKinetics.cpp.
References ThermoPhase::getActivityConcentrations(), and Kinetics::thermo().
Referenced by AqueousKinetics::getFwdRateConstants().
updateKc()
void updateKc ()
Update the equilibrium constants in molar units.
Definition at line 46 of file AqueousKinetics.cpp.
References Cantera::GasConstant, Kinetics::getRevReactionDelta(), ThermoPhase::getStandardChemPotentials(), ThermoPhase::logStandardConc(), BulkKinetics::m_irrev, BulkKinetics::m_revindex, Kinetics::m_rkcn, Phase::nSpecies(), ThermoPhase::RT(), and Kinetics::thermo().
addReaction()
bool addReaction (shared_ptr< Reaction > r) virtual
Add a single reaction to the mechanism.
Derived classes should call the base class method in addition to handling their own specialized behavior.
Parameters
r Pointer to the Reaction object to be added.
Returns
true if the reaction is added or false if it was skipped
Reimplemented from BulkKinetics.
Definition at line 144 of file AqueousKinetics.cpp.
References BulkKinetics::addReaction(), and Cantera::ELEMENTARY_RXN.
modifyReaction()
void modifyReaction (size_t i, shared_ptr< Reaction > rNew) virtual
Modify the rate expression associated with a reaction.
The stoichiometric equation, type of the reaction, reaction orders, third body efficiencies, reversibility, etc. must be unchanged.
Parameters
i Index of the reaction to be modified
rNew Reaction with the new rate expressions
Reimplemented from Kinetics.
Definition at line 159 of file AqueousKinetics.cpp.
References Kinetics::modifyReaction().
The documentation for this class was generated from the following files:
AqueousKinetics.h
AqueousKinetics.cpp