Cantera: LatticePhase Class Reference
LatticePhase Class Reference
Models of Phases of Matter » Thermodynamic Properties
A simple thermodynamic model for a bulk phase, assuming a lattice of solid atoms.
#include <LatticePhase.h>
Public Member Functions
LatticePhase ()
Base Empty constructor.
LatticePhase (const LatticePhase &right)
LatticePhase & operator= (const LatticePhase &right)
virtual ThermoPhase * duplMyselfAsThermoPhase () const
Duplication routine for objects which inherit from ThermoPhase.
LatticePhase (const std::string &inputFile, const std::string &id="")
Full constructor for a lattice phase.
LatticePhase (XML_Node &phaseRef, const std::string &id="")
Full constructor for a water phase.
virtual int eosType () const
Equation of state flag.
virtual std::string type () const
String indicating the thermodynamic model implemented.
Molar Thermodynamic Properties of the Solution
virtual doublereal enthalpy_mole () const
Return the Molar Enthalpy. Units: J/kmol.
virtual doublereal entropy_mole () const
Molar entropy of the solution. Units: J/kmol/K.
virtual doublereal cp_mole () const
Molar heat capacity at constant pressure of the solution.
virtual doublereal cv_mole () const
Molar heat capacity at constant volume of the solution.
Mechanical Equation of State Properties
virtual doublereal pressure () const
In this equation of state implementation, the density is a function only of the mole fractions.
virtual void setPressure (doublereal p)
Set the internally stored pressure (Pa) at constant temperature and composition.
doublereal calcDensity ()
Calculate the density of the mixture using the partial molar volumes and mole fractions as input.
Activities, Standard States, and Activity Concentrations
virtual void getActivityConcentrations (doublereal *c) const
The activity \(a_k\) of a species in solution is related to the chemical potential by
\[ \mu_k = \mu_k^0(T) + \hat R T \log a_k. \]
The quantity \(\mu_k^0(T,P)\) is the chemical potential at unit activity, which depends only on temperature and the pressure.
virtual doublereal standardConcentration (size_t k=0) const
Return the standard concentration for the kth species.
virtual doublereal logStandardConc (size_t k=0) const
Natural logarithm of the standard concentration of the kth species.
virtual void getActivityCoefficients (doublereal *ac) const
Get the array of non-dimensional activity coefficients at the current solution temperature, pressure, and solution concentration.
Partial Molar Properties of the Solution
virtual void getChemPotentials (doublereal *mu) const
Get the species chemical potentials. Units: J/kmol.
virtual void getPartialMolarEnthalpies (doublereal *hbar) const
Returns an array of partial molar enthalpies for the species in the mixture.
virtual void getPartialMolarEntropies (doublereal *sbar) const
Returns an array of partial molar entropies of the species in the solution.
virtual void getPartialMolarCp (doublereal *cpbar) const
Returns an array of partial molar Heat Capacities at constant pressure of the species in the solution.
virtual void getPartialMolarVolumes (doublereal *vbar) const
Return an array of partial molar volumes for the species in the mixture.
virtual void getStandardChemPotentials (doublereal *mu) const
Get the array of chemical potentials at unit activity for the species at their standard states at the current T and P of the solution.
virtual void getPureGibbs (doublereal *gpure) const
Get the Gibbs functions for the standard state of the species at the current T and P of the solution.
Properties of the Standard State of the Species in the Solution
virtual void getEnthalpy_RT (doublereal *hrt) const
Get the nondimensional Enthalpy functions for the species standard states at their standard states at the current T and P of the solution.
virtual void getEntropy_R (doublereal *sr) const
Get the array of nondimensional Entropy functions for the species standard states at the current T and P of the solution.
virtual void getGibbs_RT (doublereal *grt) const
Get the nondimensional Gibbs functions for the species standard states at the current T and P of the solution.
virtual void getCp_R (doublereal *cpr) const
Get the nondimensional Heat Capacities at constant pressure for the species standard states at the current T and P of the solution.
virtual void getStandardVolumes (doublereal *vol) const
Get the molar volumes of the species standard states at the current T and P of the solution.
Thermodynamic Values for the Species Reference States
const vector_fp & enthalpy_RT_ref () const
const vector_fp & gibbs_RT_ref () const
Returns a reference to the dimensionless reference state Gibbs free energy vector.
virtual void getGibbs_RT_ref (doublereal *grt) const
Returns the vector of nondimensional Gibbs Free Energies of the reference state at the current temperature of the solution and the reference pressure for the species.
virtual void getGibbs_ref (doublereal *g) const
Returns the vector of the Gibbs function of the reference state at the current temperature of the solution and the reference pressure for the species.
const vector_fp & entropy_R_ref () const
Returns a reference to the dimensionless reference state Entropy vector.
const vector_fp & cp_R_ref () const
Returns a reference to the dimensionless reference state Heat Capacity vector.
Utilities for Initialization of the Object
virtual bool addSpecies (shared_ptr< Species > spec)
virtual void initThermoXML (XML_Node &phaseNode, const std::string &id)
Import and initialize a ThermoPhase object using an XML tree.
virtual void setParameters (int n, doublereal *const c)
Set the equation of state parameters from the argument list.
virtual void getParameters (int &n, doublereal *const c) const
Get the equation of state parameters in a vector.
virtual void setParametersFromXML (const XML_Node &eosdata)
Set equation of state parameter values from XML entries.
Public Member Functions inherited from ThermoPhase
ThermoPhase ()
Constructor.
ThermoPhase (const ThermoPhase &right)
ThermoPhase & operator= (const ThermoPhase &right)
doublereal _RT () const
Return the Gas Constant multiplied by the current temperature.
doublereal RT () const
Return the Gas Constant multiplied by the current temperature.
virtual doublereal refPressure () const
Returns the reference pressure in Pa.
virtual doublereal minTemp (size_t k=npos) const
Minimum temperature for which the thermodynamic data for the species or phase are valid.
doublereal Hf298SS (const size_t k) const
Report the 298 K Heat of Formation of the standard state of one species (J kmol-1)
virtual void modifyOneHf298SS (const size_t k, const doublereal Hf298New)
Modify the value of the 298 K Heat of Formation of one species in the phase (J kmol-1)
virtual void resetHf298 (const size_t k=npos)
Restore the original heat of formation of one or more species.
virtual doublereal maxTemp (size_t k=npos) const
Maximum temperature for which the thermodynamic data for the species are valid.
bool chargeNeutralityNecessary () const
Returns the chargeNeutralityNecessity boolean.
virtual doublereal intEnergy_mole () const
Molar internal energy. Units: J/kmol.
virtual doublereal gibbs_mole () const
Molar Gibbs function. Units: J/kmol.
virtual doublereal isothermalCompressibility () const
Returns the isothermal compressibility. Units: 1/Pa.
virtual doublereal thermalExpansionCoeff () const
Return the volumetric thermal expansion coefficient. Units: 1/K.
void setElectricPotential (doublereal v)
Set the electric potential of this phase (V).
doublereal electricPotential () const
Returns the electric potential of this phase (V).
virtual int activityConvention () const
This method returns the convention used in specification of the activities, of which there are currently two, molar- and molality-based conventions.
virtual int standardStateConvention () const
This method returns the convention used in specification of the standard state, of which there are currently two, temperature based, and variable pressure based.
virtual void getActivities (doublereal *a) const
Get the array of non-dimensional activities at the current solution temperature, pressure, and solution concentration.
virtual void getLnActivityCoefficients (doublereal *lnac) const
Get the array of non-dimensional molar-based ln activity coefficients at the current solution temperature, pressure, and solution concentration.
virtual void getChemPotentials_RT (doublereal *mu) const
Get the array of non-dimensional species chemical potentials These are partial molar Gibbs free energies.
void getElectrochemPotentials (doublereal *mu) const
Get the species electrochemical potentials.
virtual void getPartialMolarIntEnergies (doublereal *ubar) const
Return an array of partial molar internal energies for the species in the mixture.
virtual void getIntEnergy_RT (doublereal *urt) const
Returns the vector of nondimensional Internal Energies of the standard state species at the current T and P of the solution.
virtual void getEnthalpy_RT_ref (doublereal *hrt) const
Returns the vector of nondimensional enthalpies of the reference state at the current temperature of the solution and the reference pressure for the species.
virtual void getEntropy_R_ref (doublereal *er) const
Returns the vector of nondimensional entropies of the reference state at the current temperature of the solution and the reference pressure for each species.
virtual void getIntEnergy_RT_ref (doublereal *urt) const
Returns the vector of nondimensional internal Energies of the reference state at the current temperature of the solution and the reference pressure for each species.
virtual void getCp_R_ref (doublereal *cprt) const
Returns the vector of nondimensional constant pressure heat capacities of the reference state at the current temperature of the solution and reference pressure for each species.
virtual void getStandardVolumes_ref (doublereal *vol) const
Get the molar volumes of the species reference states at the current T and P_ref of the solution.
virtual void setReferenceComposition (const doublereal *const x)
Sets the reference composition.
virtual void getReferenceComposition (doublereal *const x) const
Gets the reference composition.
doublereal enthalpy_mass () const
Specific enthalpy. Units: J/kg.
doublereal intEnergy_mass () const
Specific internal energy. Units: J/kg.
doublereal entropy_mass () const
Specific entropy. Units: J/kg/K.
doublereal gibbs_mass () const
Specific Gibbs function. Units: J/kg.
doublereal cp_mass () const
Specific heat at constant pressure. Units: J/kg/K.
doublereal cv_mass () const
Specific heat at constant volume. Units: J/kg/K.
virtual void setState_TPX (doublereal t, doublereal p, const doublereal *x)
Set the temperature (K), pressure (Pa), and mole fractions.
virtual void setState_TPX (doublereal t, doublereal p, const compositionMap &x)
Set the temperature (K), pressure (Pa), and mole fractions.
virtual void setState_TPX (doublereal t, doublereal p, const std::string &x)
Set the temperature (K), pressure (Pa), and mole fractions.
virtual void setState_TPY (doublereal t, doublereal p, const doublereal *y)
Set the internally stored temperature (K), pressure (Pa), and mass fractions of the phase.
virtual void setState_TPY (doublereal t, doublereal p, const compositionMap &y)
Set the internally stored temperature (K), pressure (Pa), and mass fractions of the phase.
virtual void setState_TPY (doublereal t, doublereal p, const std::string &y)
Set the internally stored temperature (K), pressure (Pa), and mass fractions of the phase.
virtual void setState_TP (doublereal t, doublereal p)
Set the temperature (K) and pressure (Pa)
virtual void setState_PX (doublereal p, doublereal *x)
Set the pressure (Pa) and mole fractions.
virtual void setState_PY (doublereal p, doublereal *y)
Set the internally stored pressure (Pa) and mass fractions.
virtual void setState_HP (double h, double p, double tol=1e-9)
Set the internally stored specific enthalpy (J/kg) and pressure (Pa) of the phase.
virtual void setState_UV (double u, double v, double tol=1e-9)
Set the specific internal energy (J/kg) and specific volume (m^3/kg).
virtual void setState_SP (double s, double p, double tol=1e-9)
Set the specific entropy (J/kg/K) and pressure (Pa).
virtual void setState_SV (double s, double v, double tol=1e-9)
Set the specific entropy (J/kg/K) and specific volume (m^3/kg).
virtual void setState_ST (double s, double t, double tol=1e-9)
Set the specific entropy (J/kg/K) and temperature (K).
virtual void setState_TV (double t, double v, double tol=1e-9)
Set the temperature (K) and specific volume (m^3/kg).
virtual void setState_PV (double p, double v, double tol=1e-9)
Set the pressure (Pa) and specific volume (m^3/kg).
virtual void setState_UP (double u, double p, double tol=1e-9)
Set the specific internal energy (J/kg) and pressure (Pa).
virtual void setState_VH (double v, double h, double tol=1e-9)
Set the specific volume (m^3/kg) and the specific enthalpy (J/kg)
virtual void setState_TH (double t, double h, double tol=1e-9)
Set the temperature (K) and the specific enthalpy (J/kg)
virtual void setState_SH (double s, double h, double tol=1e-9)
Set the specific entropy (J/kg/K) and the specific enthalpy (J/kg)
virtual void setState_RP (doublereal rho, doublereal p)
Set the density (kg/m**3) and pressure (Pa) at constant composition.
virtual void setState_RPX (doublereal rho, doublereal p, const doublereal *x)
Set the density (kg/m**3), pressure (Pa) and mole fractions.
virtual void setState_RPX (doublereal rho, doublereal p, const compositionMap &x)
Set the density (kg/m**3), pressure (Pa) and mole fractions.
virtual void setState_RPX (doublereal rho, doublereal p, const std::string &x)
Set the density (kg/m**3), pressure (Pa) and mole fractions.
virtual void setState_RPY (doublereal rho, doublereal p, const doublereal *y)
Set the density (kg/m**3), pressure (Pa) and mass fractions.
virtual void setState_RPY (doublereal rho, doublereal p, const compositionMap &y)
Set the density (kg/m**3), pressure (Pa) and mass fractions.
virtual void setState_RPY (doublereal rho, doublereal p, const std::string &y)
Set the density (kg/m**3), pressure (Pa) and mass fractions.
void equilibrate (const std::string &XY, const std::string &solver="auto", double rtol=1e-9, int max_steps=50000, int max_iter=100, int estimate_equil=0, int log_level=0)
Equilibrate a ThermoPhase object.
virtual void setToEquilState (const doublereal *lambda_RT)
This method is used by the ChemEquil equilibrium solver.
void setElementPotentials (const vector_fp &lambda)
Stores the element potentials in the ThermoPhase object.
bool getElementPotentials (doublereal *lambda) const
Returns the element potentials stored in the ThermoPhase object.
virtual bool compatibleWithMultiPhase () const
Indicates whether this phase type can be used with class MultiPhase for equilibrium calculations.
virtual doublereal critTemperature () const
Critical temperature (K).
virtual doublereal critPressure () const
Critical pressure (Pa).
virtual doublereal critVolume () const
Critical volume (m3/kmol).
virtual doublereal critCompressibility () const
Critical compressibility (unitless).
virtual doublereal critDensity () const
Critical density (kg/m3).
virtual doublereal satTemperature (doublereal p) const
Return the saturation temperature given the pressure.
virtual doublereal satPressure (doublereal t)
Return the saturation pressure given the temperature.
virtual doublereal vaporFraction () const
Return the fraction of vapor at the current conditions.
virtual void setState_Tsat (doublereal t, doublereal x)
Set the state to a saturated system at a particular temperature.
virtual void setState_Psat (doublereal p, doublereal x)
Set the state to a saturated system at a particular pressure.
virtual void modifySpecies (size_t k, shared_ptr< Species > spec)
Modify the thermodynamic data associated with a species.
void saveSpeciesData (const size_t k, const XML_Node *const data)
Store a reference pointer to the XML tree containing the species data for this phase.
const std::vector< const XML_Node * > & speciesData () const
Return a pointer to the vector of XML nodes containing the species data for this phase.
void setSpeciesThermo (MultiSpeciesThermo *spthermo)
Install a species thermodynamic property manager.
virtual MultiSpeciesThermo & speciesThermo (int k=-1)
Return a changeable reference to the calculation manager for species reference-state thermodynamic properties.
virtual void initThermoFile (const std::string &inputFile, const std::string &id)
virtual void initThermo ()
Initialize the ThermoPhase object after all species have been set up.
virtual void installSlavePhases (XML_Node *phaseNode)
Add in species from Slave phases.
virtual void setStateFromXML (const XML_Node &state)
Set the initial state of the phase to the conditions specified in the state XML element.
virtual void invalidateCache ()
Invalidate any cached values which are normally updated only when a change in state is detected.
virtual void getdlnActCoeffds (const doublereal dTds, const doublereal *const dXds, doublereal *dlnActCoeffds) const
Get the change in activity coefficients wrt changes in state (temp, mole fraction, etc) along a line in parameter space or along a line in physical space.
virtual void getdlnActCoeffdlnX_diag (doublereal *dlnActCoeffdlnX_diag) const
Get the array of ln mole fraction derivatives of the log activity coefficients - diagonal component only.
virtual void getdlnActCoeffdlnN_diag (doublereal *dlnActCoeffdlnN_diag) const
Get the array of log species mole number derivatives of the log activity coefficients.
virtual void getdlnActCoeffdlnN (const size_t ld, doublereal *const dlnActCoeffdlnN)
Get the array of derivatives of the log activity coefficients with respect to the log of the species mole numbers.
virtual void getdlnActCoeffdlnN_numderiv (const size_t ld, doublereal *const dlnActCoeffdlnN)
virtual std::string report (bool show_thermo=true, doublereal threshold=-1e-14) const
returns a summary of the state of the phase as a string
virtual void reportCSV (std::ofstream &csvFile) const
returns a summary of the state of the phase to a comma separated file.
Public Member Functions inherited from Phase
Phase ()
Default constructor.
Phase (const Phase &right)
Phase & operator= (const Phase &right)
XML_Node & xml () const
Returns a const reference to the XML_Node that describes the phase.
void setXMLdata (XML_Node &xmlPhase)
Stores the XML tree information for the current phase.
void saveState (vector_fp &state) const
Save the current internal state of the phase.
void saveState (size_t lenstate, doublereal *state) const
Write to array 'state' the current internal state.
void restoreState (const vector_fp &state)
Restore a state saved on a previous call to saveState.
void restoreState (size_t lenstate, const doublereal *state)
Restore the state of the phase from a previously saved state vector.
doublereal molecularWeight (size_t k) const
Molecular weight of species k.
void getMolecularWeights (vector_fp &weights) const
Copy the vector of molecular weights into vector weights.
void getMolecularWeights (doublereal *weights) const
Copy the vector of molecular weights into array weights.
const vector_fp & molecularWeights () const
Return a const reference to the internal vector of molecular weights.
doublereal size (size_t k) const
This routine returns the size of species k.
doublereal charge (size_t k) const
Dimensionless electrical charge of a single molecule of species k The charge is normalized by the the magnitude of the electron charge.
doublereal chargeDensity () const
Charge density [C/m^3].
size_t nDim () const
Returns the number of spatial dimensions (1, 2, or 3)
void setNDim (size_t ndim)
Set the number of spatial dimensions (1, 2, or 3).
virtual bool ready () const
Returns a bool indicating whether the object is ready for use.
int stateMFNumber () const
Return the State Mole Fraction Number.
std::string id () const
Return the string id for the phase.
void setID (const std::string &id)
Set the string id for the phase.
std::string name () const
Return the name of the phase.
void setName (const std::string &nm)
Sets the string name for the phase.
std::string elementName (size_t m) const
Name of the element with index m.
size_t elementIndex (const std::string &name) const
Return the index of element named 'name'.
const std::vector< std::string > & elementNames () const
Return a read-only reference to the vector of element names.
doublereal atomicWeight (size_t m) const
Atomic weight of element m.
doublereal entropyElement298 (size_t m) const
Entropy of the element in its standard state at 298 K and 1 bar.
int atomicNumber (size_t m) const
Atomic number of element m.
int elementType (size_t m) const
Return the element constraint type Possible types include:
int changeElementType (int m, int elem_type)
Change the element type of the mth constraint Reassigns an element type.
const vector_fp & atomicWeights () const
Return a read-only reference to the vector of atomic weights.
size_t nElements () const
Number of elements.
void checkElementIndex (size_t m) const
Check that the specified element index is in range.
void checkElementArraySize (size_t mm) const
Check that an array size is at least nElements().
doublereal nAtoms (size_t k, size_t m) const
Number of atoms of element m in species k.
void getAtoms (size_t k, double *atomArray) const
Get a vector containing the atomic composition of species k.
size_t speciesIndex (const std::string &name) const
Returns the index of a species named 'name' within the Phase object.
std::string speciesName (size_t k) const
Name of the species with index k.
std::string speciesSPName (int k) const
Returns the expanded species name of a species, including the phase name This is guaranteed to be unique within a Cantera problem.
const std::vector< std::string > & speciesNames () const
Return a const reference to the vector of species names.
size_t nSpecies () const
Returns the number of species in the phase.
void checkSpeciesIndex (size_t k) const
Check that the specified species index is in range.
void checkSpeciesArraySize (size_t kk) const
Check that an array size is at least nSpecies().
void setMoleFractionsByName (const compositionMap &xMap)
Set the species mole fractions by name.
void setMoleFractionsByName (const std::string &x)
Set the mole fractions of a group of species by name.
void setMassFractionsByName (const compositionMap &yMap)
Set the species mass fractions by name.
void setMassFractionsByName (const std::string &x)
Set the species mass fractions by name.
void setState_TRX (doublereal t, doublereal dens, const doublereal *x)
Set the internally stored temperature (K), density, and mole fractions.
void setState_TRX (doublereal t, doublereal dens, const compositionMap &x)
Set the internally stored temperature (K), density, and mole fractions.
void setState_TRY (doublereal t, doublereal dens, const doublereal *y)
Set the internally stored temperature (K), density, and mass fractions.
void setState_TRY (doublereal t, doublereal dens, const compositionMap &y)
Set the internally stored temperature (K), density, and mass fractions.
void setState_TNX (doublereal t, doublereal n, const doublereal *x)
Set the internally stored temperature (K), molar density (kmol/m^3), and mole fractions.
void setState_TR (doublereal t, doublereal rho)
Set the internally stored temperature (K) and density (kg/m^3)
void setState_TX (doublereal t, doublereal *x)
Set the internally stored temperature (K) and mole fractions.
void setState_TY (doublereal t, doublereal *y)
Set the internally stored temperature (K) and mass fractions.
void setState_RX (doublereal rho, doublereal *x)
Set the density (kg/m^3) and mole fractions.
void setState_RY (doublereal rho, doublereal *y)
Set the density (kg/m^3) and mass fractions.
compositionMap getMoleFractionsByName (double threshold=0.0) const
Get the mole fractions by name.
doublereal moleFraction (size_t k) const
Return the mole fraction of a single species.
doublereal moleFraction (const std::string &name) const
Return the mole fraction of a single species.
compositionMap getMassFractionsByName (double threshold=0.0) const
Get the mass fractions by name.
doublereal massFraction (size_t k) const
Return the mass fraction of a single species.
doublereal massFraction (const std::string &name) const
Return the mass fraction of a single species.
void getMoleFractions (doublereal *const x) const
Get the species mole fraction vector.
virtual void setMoleFractions (const doublereal *const x)
Set the mole fractions to the specified values.
virtual void setMoleFractions_NoNorm (const doublereal *const x)
Set the mole fractions to the specified values without normalizing.
void getMassFractions (doublereal *const y) const
Get the species mass fractions.
const doublereal * massFractions () const
Return a const pointer to the mass fraction array.
virtual void setMassFractions (const doublereal *const y)
Set the mass fractions to the specified values and normalize them.
virtual void setMassFractions_NoNorm (const doublereal *const y)
Set the mass fractions to the specified values without normalizing.
void getConcentrations (doublereal *const c) const
Get the species concentrations (kmol/m^3).
doublereal concentration (const size_t k) const
Concentration of species k.
virtual void setConcentrations (const doublereal *const conc)
Set the concentrations to the specified values within the phase.
virtual void setConcentrationsNoNorm (const double *const conc)
Set the concentrations without ignoring negative concentrations.
doublereal elementalMassFraction (const size_t m) const
Elemental mass fraction of element m.
doublereal elementalMoleFraction (const size_t m) const
Elemental mole fraction of element m.
const doublereal * moleFractdivMMW () const
Returns a const pointer to the start of the moleFraction/MW array.
doublereal temperature () const
Temperature (K).
virtual doublereal density () const
Density (kg/m^3).
doublereal molarDensity () const
Molar density (kmol/m^3).
doublereal molarVolume () const
Molar volume (m^3/kmol).
virtual void setDensity (const doublereal density_)
Set the internally stored density (kg/m^3) of the phase.
virtual void setMolarDensity (const doublereal molarDensity)
Set the internally stored molar density (kmol/m^3) of the phase.
virtual void setTemperature (const doublereal temp)
Set the internally stored temperature of the phase (K).
doublereal mean_X (const doublereal *const Q) const
Evaluate the mole-fraction-weighted mean of an array Q.
doublereal mean_X (const vector_fp &Q) const
Evaluate the mole-fraction-weighted mean of an array Q.
doublereal meanMolecularWeight () const
The mean molecular weight. Units: (kg/kmol)
doublereal sum_xlogx () const
Evaluate \(\sum_k X_k \log X_k \).
size_t addElement (const std::string &symbol, doublereal weight=-12345.0, int atomicNumber=0, doublereal entropy298=ENTROPY298_UNKNOWN, int elem_type=CT_ELEM_TYPE_ABSPOS)
Add an element.
shared_ptr< Species > species (const std::string &name) const
Return the Species object for the named species.
shared_ptr< Species > species (size_t k) const
Return the Species object for species whose index is k.
void ignoreUndefinedElements ()
Set behavior when adding a species containing undefined elements to just skip the species.
void addUndefinedElements ()
Set behavior when adding a species containing undefined elements to add those elements to the phase.
void throwUndefinedElements ()
Set the behavior when adding a species containing undefined elements to throw an exception.
Protected Member Functions
virtual void compositionChanged ()
Apply changes to the state which are needed after the composition changes.
Protected Member Functions inherited from ThermoPhase
virtual void getCsvReportData (std::vector< std::string > &names, std::vector< vector_fp > &data) const
Fills names and data with the column names and species thermo properties to be included in the output of the reportCSV method.
Protected Member Functions inherited from Phase
void setMolecularWeight (const int k, const double mw)
Set the molecular weight of a single species to a given value.
Protected Attributes
doublereal m_Pref
Reference state pressure.
doublereal m_Pcurrent
The current pressure.
vector_fp m_h0_RT
Reference state enthalpies / RT.
vector_fp m_cp0_R
Temporary storage for the reference state heat capacities.
vector_fp m_g0_RT
Temporary storage for the reference state Gibbs energies.
vector_fp m_s0_R
Temporary storage for the reference state entropies at the current temperature.
std::string m_vacancy
String name for the species which represents a vacancy in the lattice.
vector_fp m_speciesMolarVolume
Vector of molar volumes for each species in the solution.
doublereal m_site_density
Site Density of the lattice solid.
Protected Attributes inherited from ThermoPhase
MultiSpeciesThermo * m_spthermo
Pointer to the calculation manager for species reference-state thermodynamic properties.
std::vector< const XML_Node * > m_speciesData
Vector of pointers to the species databases.
doublereal m_phi
Stored value of the electric potential for this phase. Units are Volts.
vector_fp m_lambdaRRT
Vector of element potentials. Length equal to number of elements.
bool m_hasElementPotentials
Boolean indicating whether there is a valid set of saved element potentials for this phase.
bool m_chargeNeutralityNecessary
Boolean indicating whether a charge neutrality condition is a necessity.
int m_ssConvention
Contains the standard state convention.
vector_fp xMol_Ref
Reference Mole Fraction Composition.
doublereal m_tlast
last value of the temperature processed by reference state
Protected Attributes inherited from Phase
ValueCache m_cache
Cached for saved calculations within each ThermoPhase.
size_t m_kk
Number of species in the phase.
size_t m_ndim
Dimensionality of the phase.
vector_fp m_speciesComp
Atomic composition of the species.
vector_fp m_speciesSize
Vector of species sizes.
vector_fp m_speciesCharge
Vector of species charges. length m_kk.
std::map< std::string, shared_ptr< Species > > m_species
UndefElement::behavior m_undefinedElementBehavior
Flag determining behavior when adding species with an undefined element.
Private Member Functions
void _updateThermo () const
Update the species reference state thermodynamic functions.
Detailed Description
A simple thermodynamic model for a bulk phase, assuming a lattice of solid atoms.
The bulk consists of a matrix of equivalent sites whose molar density does not vary with temperature or pressure. The thermodynamics obeys the ideal solution laws. The phase and the pure species phases which comprise the standard states of the species are assumed to have zero volume expansivity and zero isothermal compressibility.
The density of matrix sites is given by the variable \(C_o \), which has SI units of kmol m-3.
Specification of Species Standard State Properties
It is assumed that the reference state thermodynamics may be obtained by a pointer to a populated species thermodynamic property manager class (see ThermoPhase::m_spthermo). However, how to relate pressure changes to the reference state thermodynamics is within this class.
Pressure is defined as an independent variable in this phase. However, it has no effect on any quantities, as the molar concentration is a constant.
The standard state enthalpy function is given by the following relation, which has a weak dependence on the system pressure, \(P\).
\[ h^o_k(T,P) = h^{ref}_k(T) + \left(\frac{P - P_{ref}}{C_o} \right) \]
For an incompressible substance, the molar internal energy is independent of pressure. Since the thermodynamic properties are specified by giving the standard-state enthalpy, the term \(\frac{P_{ref}}{C_o} \) is subtracted from the specified reference molar enthalpy to compute the standard state molar internal energy:
\[ u^o_k(T,P) = h^{ref}_k(T) - \frac{P_{ref}}{C_o} \]
The standard state heat capacity, internal energy, and entropy are independent of pressure. The standard state Gibbs free energy is obtained from the enthalpy and entropy functions.
The standard state molar volume is independent of temperature, pressure, and species identity:
\[ V^o_k(T,P) = \frac{1.0}{C_o} \]
Specification of Solution Thermodynamic Properties
The activity of species \(k \) defined in the phase, \(a_k \), is given by the ideal solution law:
\[ a_k = X_k , \]
where \(X_k \) is the mole fraction of species k. The chemical potential for species k is equal to
\[ \mu_k(T,P) = \mu^o_k(T, P) + R T \log(X_k) \]
The partial molar entropy for species k is given by the following relation,
\[ \tilde{s}_k(T,P) = s^o_k(T,P) - R \log(X_k) = s^{ref}_k(T) - R \log(X_k) \]
The partial molar enthalpy for species k is
\[ \tilde{h}_k(T,P) = h^o_k(T,P) = h^{ref}_k(T) + \left(\frac{P - P_{ref}}{C_o} \right) \]
The partial molar Internal Energy for species k is
\[ \tilde{u}_k(T,P) = u^o_k(T,P) = u^{ref}_k(T) \]
The partial molar Heat Capacity for species k is
\[ \tilde{Cp}_k(T,P) = Cp^o_k(T,P) = Cp^{ref}_k(T) \]
The partial molar volume is independent of temperature, pressure, and species identity:
\[ \tilde{V}_k(T,P) = V^o_k(T,P) = \frac{1.0}{C_o} \]
It is assumed that the reference state thermodynamics may be obtained by a pointer to a populated species thermodynamic property manager class (see ThermoPhase::m_spthermo). How to relate pressure changes to the reference state thermodynamics is resolved at this level.
Pressure is defined as an independent variable in this phase. However, it only has a weak dependence on the enthalpy, and doesn't effect the molar concentration.
Application within Kinetics Managers
\(C^a_k\) are defined such that \(C^a_k = a_k = X_k \). \(C^s_k \), the standard concentration, is defined to be equal to one. \(a_k \) are activities used in the thermodynamic functions. These activity (or generalized) concentrations are used by kinetics manager classes to compute the forward and reverse rates of elementary reactions. The activity concentration, \(C^a_k \), is given by the following expression.
\[ C^a_k = C^s_k X_k = X_k \]
The standard concentration for species k is identically one
\[ C^s_k = C^s = 1.0 \]
For example, a bulk-phase binary gas reaction between species j and k, producing a new species l would have the following equation for its rate of progress variable, \(R^1 \), which has units of kmol m-3 s-1.
\[ R^1 = k^1 C_j^a C_k^a = k^1 X_j X_k \]
The reverse rate constant can then be obtained from the law of microscopic reversibility and the equilibrium expression for the system.
\[ \frac{X_j X_k}{ X_l} = K_a^{o,1} = \exp(\frac{\mu^o_l - \mu^o_j - \mu^o_k}{R T}) \]
\(K_a^{o,1} \) is the dimensionless form of the equilibrium constant, associated with the pressure dependent standard states \(\mu^o_l(T,P) \) and their associated activities, \(a_l \), repeated here:
\[ \mu_l(T,P) = \mu^o_l(T, P) + R T \log(a_l) \]
The concentration equilibrium constant, \(K_c \), may be obtained by changing over to activity concentrations. When this is done:
\[ \frac{C^a_j C^a_k}{ C^a_l} = C^o K_a^{o,1} = K_c^1 = \exp(\frac{\mu^{o}_l - \mu^{o}_j - \mu^{o}_k}{R T}) \]
Kinetics managers will calculate the concentration equilibrium constant, \(K_c \), using the second and third part of the above expression as a definition for the concentration equilibrium constant.
Instantiation of the Class
The constructor for this phase is located in the default ThermoFactory for Cantera. A new LatticePhase object may be created by the following code snippet:
XML_Node *xc = get_XML_File("O_lattice_SiO2.xml");
XML_Node * const xs = xc->findNameID("phase", "O_lattice_SiO2");
ThermoPhase *tp = newPhase(*xs);
LatticePhase *o_lattice = dynamic_cast <LatticPhase *>(tp);
or by the following constructor:
XML_Node *xc = get_XML_File("O_lattice_SiO2.xml");
XML_Node * const xs = xc->findNameID("phase", "O_lattice_SiO2");
LatticePhase *o_lattice = new LatticePhase(*xs);
The XML file used in this example is listed in the next section
XML Example
An example of an XML Element named phase setting up a LatticePhase object named "O_lattice_SiO2" is given below.
<!--     phase O_lattice_SiO2      -->
  <phase dim="3" id="O_lattice_SiO2">
    <elementArray datasrc="elements.xml"> Si  H  He </elementArray>
    <speciesArray datasrc="#species_data">
      O_O  Vac_O
    </speciesArray>
    <reactionArray datasrc="#reaction_data"/>
    <thermo model="Lattice">
      <site_density> 73.159 </site_density>
      <vacancy_species>  Vac_O </vacancy_species>
    </thermo>
    <kinetics model="BulkKinetics"/>
    <transport model="None"/>
 </phase>
The model attribute "Lattice" of the thermo XML element identifies the phase as being of the type handled by the LatticePhase object.
Definition at line 232 of file LatticePhase.h.
Constructor & Destructor Documentation
LatticePhase() [1/3]
LatticePhase ()
Base Empty constructor.
Definition at line 21 of file LatticePhase.cpp.
Referenced by LatticePhase::duplMyselfAsThermoPhase().
LatticePhase() [2/3]
LatticePhase (const std::string & inputFile, const std::string & id = "")
Full constructor for a lattice phase.
Parameters
inputFile String name of the input file
id string id of the phase name
Definition at line 55 of file LatticePhase.cpp.
References ThermoPhase::initThermoFile().
LatticePhase() [3/3]
LatticePhase (XML_Node & phaseRef, const std::string & id = "")
Full constructor for a water phase.
Parameters
phaseRef XML node referencing the lattice phase.
id string id of the phase name
Definition at line 60 of file LatticePhase.cpp.
References Cantera::importPhase().
Member Function Documentation
duplMyselfAsThermoPhase()
ThermoPhase * duplMyselfAsThermoPhase () const virtual
Duplication routine for objects which inherit from ThermoPhase.
This virtual routine can be used to duplicate ThermoPhase objects inherited from ThermoPhase even if the application only has a pointer to ThermoPhase to work with.
These routines are basically wrappers around the derived copy constructor.
Deprecated:
To be removed after Cantera 2.3 for all classes derived from ThermoPhase.
Reimplemented from ThermoPhase.
Definition at line 65 of file LatticePhase.cpp.
References LatticePhase::LatticePhase().
eosType()
virtual int eosType () const inline virtual
Equation of state flag.
Returns the value cLattice
Deprecated:
To be removed after Cantera 2.3.
Reimplemented from ThermoPhase.
Definition at line 258 of file LatticePhase.h.
References Cantera::warn_deprecated().
type()
virtual std::string type () const inline virtual
String indicating the thermodynamic model implemented.
Usually corresponds to the name of the derived class, less any suffixes such as "Phase", TP", "VPSS", etc.
Reimplemented from ThermoPhase.
Definition at line 263 of file LatticePhase.h.
enthalpy_mole()
doublereal enthalpy_mole () const virtual
Return the Molar Enthalpy. Units: J/kmol.
For an ideal solution,
\[ \hat h(T,P) = \sum_k X_k \hat h^0_k(T,P), \]
The standard-state pure-species Enthalpies \(\hat h^0_k(T,P) \) are computed first by the species reference state thermodynamic property manager and then a small pressure dependent term is added in.
See also
MultiSpeciesThermo
Reimplemented from ThermoPhase.
Definition at line 70 of file LatticePhase.cpp.
References LatticePhase::m_Pref, Phase::mean_X(), Phase::molarDensity(), LatticePhase::pressure(), and ThermoPhase::RT().
entropy_mole()
doublereal entropy_mole () const virtual
Molar entropy of the solution. Units: J/kmol/K.
For an ideal, constant partial molar volume solution mixture with pure species phases which exhibit zero volume expansivity:
\[ \hat s(T, P, X_k) = \sum_k X_k \hat s^0_k(T) - \hat R \sum_k X_k log(X_k) \]
The reference-state pure-species entropies \(\hat s^0_k(T,p_{ref}) \) are computed by the species thermodynamic property manager. The pure species entropies are independent of pressure since the volume expansivities are equal to zero.
Units: J/kmol/K.
See also
MultiSpeciesThermo
Reimplemented from ThermoPhase.
Definition at line 76 of file LatticePhase.cpp.
References LatticePhase::entropy_R_ref(), Cantera::GasConstant, Phase::mean_X(), and Phase::sum_xlogx().
cp_mole()
doublereal cp_mole () const virtual
Molar heat capacity at constant pressure of the solution.
Units: J/kmol/K.
For an ideal, constant partial molar volume solution mixture with pure species phases which exhibit zero volume expansivity:
\[ \hat c_p(T,P) = \sum_k X_k \hat c^0_{p,k}(T) . \]
The heat capacity is independent of pressure. The reference-state pure- species heat capacities \(\hat c^0_{p,k}(T) \) are computed by the species thermodynamic property manager.
See also
MultiSpeciesThermo
Reimplemented from ThermoPhase.
Definition at line 81 of file LatticePhase.cpp.
References LatticePhase::cp_R_ref(), Cantera::GasConstant, and Phase::mean_X().
Referenced by LatticePhase::cv_mole().
cv_mole()
doublereal cv_mole () const virtual
Molar heat capacity at constant volume of the solution.
Units: J/kmol/K.
For an ideal, constant partial molar volume solution mixture with pure species phases which exhibit zero volume expansivity:
\[ \hat c_v(T,P) = \hat c_p(T,P) \]
The two heat capacities are equal.
Reimplemented from ThermoPhase.
Definition at line 86 of file LatticePhase.cpp.
References LatticePhase::cp_mole().
pressure()
virtual doublereal pressure () const inline virtual
In this equation of state implementation, the density is a function only of the mole fractions.
Therefore, it can't be an independent variable. Instead, the pressure is used as the independent variable. Functions which try to set the thermodynamic state by calling setDensity() may cause an exception to be thrown.Pressure. Units: Pa.
For this incompressible system, we return the internally stored independent value of the pressure.
Reimplemented from ThermoPhase.
Definition at line 349 of file LatticePhase.h.
References LatticePhase::m_Pcurrent.
Referenced by LatticePhase::enthalpy_mole().
setPressure()
void setPressure (doublereal p) virtual
Set the internally stored pressure (Pa) at constant temperature and composition.
This method sets the pressure within the object. The mass density is not a function of pressure.
Parameters
p Input Pressure (Pa)
Reimplemented from ThermoPhase.
Definition at line 97 of file LatticePhase.cpp.
References LatticePhase::calcDensity(), and LatticePhase::m_Pcurrent.
calcDensity()
doublereal calcDensity ()
Calculate the density of the mixture using the partial molar volumes and mole fractions as input.
The formula for this is
\[ \rho = \frac{\sum_k{X_k W_k}}{\sum_k{X_k V_k}} \]
where \(X_k\) are the mole fractions, \(W_k\) are the molecular weights, and \(V_k\) are the pure species molar volumes.
Note, the basis behind this formula is that in an ideal solution the partial molar volumes are equal to the pure species molar volumes. We have additionally specified in this class that the pure species molar volumes are independent of temperature and pressure.
Definition at line 91 of file LatticePhase.cpp.
References LatticePhase::m_site_density, Phase::meanMolecularWeight(), and Phase::setMolarDensity().
Referenced by LatticePhase::compositionChanged(), and LatticePhase::setPressure().
getActivityConcentrations()
void getActivityConcentrations (doublereal * c) const virtual
The activity \(a_k\) of a species in solution is related to the chemical potential by
\[ \mu_k = \mu_k^0(T) + \hat R T \log a_k. \]
The quantity \(\mu_k^0(T,P)\) is the chemical potential at unit activity, which depends only on temperature and the pressure.
Activity is assumed to be molality-based here.
Reimplemented from ThermoPhase.
Definition at line 109 of file LatticePhase.cpp.
standardConcentration()
doublereal standardConcentration (size_t k = 0) const virtual
Return the standard concentration for the kth species.
The standard concentration \(C^0_k \) used to normalize the activity (i.e., generalized) concentration for use
For the time being, we will use the concentration of pure solvent for the the standard concentration of all species. This has the effect of making mass-action reaction rates based on the molality of species proportional to the molality of the species.
Parameters
k Optional parameter indicating the species. The default is to assume this refers to species 0.
Returns
the standard Concentration in units of m^3/kmol.
Parameters
k Species index
Reimplemented from ThermoPhase.
Definition at line 121 of file LatticePhase.cpp.
logStandardConc()
doublereal logStandardConc (size_t k = 0) const virtual
Natural logarithm of the standard concentration of the kth species.
Parameters
k index of the species (defaults to zero)
Reimplemented from ThermoPhase.
Definition at line 126 of file LatticePhase.cpp.
getActivityCoefficients()
void getActivityCoefficients (doublereal * ac) const virtual
Get the array of non-dimensional activity coefficients at the current solution temperature, pressure, and solution concentration.
For this phase, the activity coefficients are all equal to one.
Parameters
ac Output vector of activity coefficients. Length: m_kk.
Reimplemented from ThermoPhase.
Definition at line 114 of file LatticePhase.cpp.
References Phase::m_kk.
getChemPotentials()
void getChemPotentials (doublereal * mu) const virtual
Get the species chemical potentials. Units: J/kmol.
This function returns a vector of chemical potentials of the species in solid solution at the current temperature, pressure and mole fraction of the solid solution.
Parameters
mu Output vector of species chemical potentials. Length: m_kk. Units: J/kmol
Reimplemented from ThermoPhase.
Definition at line 131 of file LatticePhase.cpp.
References LatticePhase::gibbs_RT_ref(), Phase::m_kk, LatticePhase::m_Pcurrent, LatticePhase::m_Pref, LatticePhase::m_speciesMolarVolume, Phase::moleFraction(), ThermoPhase::RT(), and Cantera::SmallNumber.
getPartialMolarEnthalpies()
void getPartialMolarEnthalpies (doublereal * hbar) const virtual
Returns an array of partial molar enthalpies for the species in the mixture.
Units (J/kmol). For this phase, the partial molar enthalpies are equal to the pure species enthalpies
\[ \bar h_k(T,P) = \hat h^{ref}_k(T) + (P - P_{ref}) \hat V^0_k \]
The reference-state pure-species enthalpies, \(\hat h^{ref}_k(T) \), at the reference pressure, \(P_{ref} \), are computed by the species thermodynamic property manager. They are polynomial functions of temperature.
See also
MultiSpeciesThermo
Parameters
hbar Output vector containing partial molar enthalpies. Length: m_kk.
Reimplemented from ThermoPhase.
Definition at line 142 of file LatticePhase.cpp.
References ThermoPhase::RT(), and Cantera::scale().
getPartialMolarEntropies()
void getPartialMolarEntropies (doublereal * sbar) const virtual
Returns an array of partial molar entropies of the species in the solution.
Units: J/kmol/K. For this phase, the partial molar entropies are equal to the pure species entropies plus the ideal solution contribution.
\[ \bar s_k(T,P) = \hat s^0_k(T) - R log(X_k) \]
The reference-state pure-species entropies, \(\hat s^{ref}_k(T) \), at the reference pressure, \(P_{ref} \), are computed by the species thermodynamic property manager. They are polynomial functions of temperature.
See also
MultiSpeciesThermo
Parameters
sbar Output vector containing partial molar entropies. Length: m_kk.
Reimplemented from ThermoPhase.
Definition at line 148 of file LatticePhase.cpp.
References LatticePhase::entropy_R_ref(), Cantera::GasConstant, Phase::m_kk, Phase::moleFraction(), and Cantera::SmallNumber.
getPartialMolarCp()
void getPartialMolarCp (doublereal * cpbar) const virtual
Returns an array of partial molar Heat Capacities at constant pressure of the species in the solution.
Units: J/kmol/K. For this phase, the partial molar heat capacities are equal to the standard state heat capacities.
Parameters
cpbar Output vector of partial heat capacities. Length: m_kk.
Reimplemented from ThermoPhase.
Definition at line 157 of file LatticePhase.cpp.
References Cantera::GasConstant, LatticePhase::getCp_R(), and Phase::m_kk.
getPartialMolarVolumes()
void getPartialMolarVolumes (doublereal * vbar) const virtual
Return an array of partial molar volumes for the species in the mixture.
Units: m^3/kmol.
Parameters
vbar Output vector of species partial molar volumes. Length = m_kk. units are m^3/kmol.
Reimplemented from ThermoPhase.
Definition at line 165 of file LatticePhase.cpp.
References LatticePhase::getStandardVolumes().
getStandardChemPotentials()
void getStandardChemPotentials (doublereal * mu) const virtual
Get the array of chemical potentials at unit activity for the species at their standard states at the current T and P of the solution.
These are the standard state chemical potentials \(\mu^0_k(T,P) \). The values are evaluated at the current temperature and pressure of the solution
Parameters
mu Output vector of chemical potentials. Length: m_kk.
Reimplemented from ThermoPhase.
Definition at line 170 of file LatticePhase.cpp.
References LatticePhase::gibbs_RT_ref(), ThermoPhase::RT(), and Cantera::scale().
getPureGibbs()
void getPureGibbs (doublereal * gpure) const virtual
Get the Gibbs functions for the standard state of the species at the current T and P of the solution.
Units are Joules/kmol
Parameters
gpure Output vector of standard state Gibbs free energies. Length: m_kk.
Reimplemented from ThermoPhase.
Definition at line 176 of file LatticePhase.cpp.
References LatticePhase::gibbs_RT_ref(), Phase::m_kk, LatticePhase::m_Pcurrent, LatticePhase::m_Pref, LatticePhase::m_speciesMolarVolume, and ThermoPhase::RT().
getEnthalpy_RT()
void getEnthalpy_RT (doublereal * hrt) const virtual
Get the nondimensional Enthalpy functions for the species standard states at their standard states at the current T and P of the solution.
A small pressure dependent term is added onto the reference state enthalpy to get the pressure dependence of this term.
\[ h^o_k(T,P) = h^{ref}_k(T) + \left(\frac{P - P_{ref}}{C_o} \right) \]
The reference state thermodynamics is obtained by a pointer to a populated species thermodynamic property manager class (see ThermoPhase::m_spthermo). How to relate pressure changes to the reference state thermodynamics is resolved at this level.
Parameters
hrt Output vector of nondimensional standard state enthalpies. Length: m_kk.
Reimplemented from ThermoPhase.
Definition at line 185 of file LatticePhase.cpp.
References Phase::m_kk, LatticePhase::m_Pcurrent, LatticePhase::m_Pref, LatticePhase::m_speciesMolarVolume, and ThermoPhase::RT().
getEntropy_R()
void getEntropy_R (doublereal * sr) const virtual
Get the array of nondimensional Entropy functions for the species standard states at the current T and P of the solution.
The entropy of the standard state is defined as independent of pressure here.
\[ s^o_k(T,P) = s^{ref}_k(T) \]
The reference state thermodynamics is obtained by a pointer to a populated species thermodynamic property manager class (see ThermoPhase::m_spthermo). How to relate pressure changes to the reference state thermodynamics is resolved at this level.
Parameters
sr Output vector of nondimensional standard state entropies. Length: m_kk.
Reimplemented from ThermoPhase.
Definition at line 194 of file LatticePhase.cpp.
References LatticePhase::entropy_R_ref().
getGibbs_RT()
void getGibbs_RT (doublereal * grt) const virtual
Get the nondimensional Gibbs functions for the species standard states at the current T and P of the solution.
The standard Gibbs free energies are obtained from the enthalpy and entropy formulation.
\[ g^o_k(T,P) = h^{o}_k(T,P) - T s^{o}_k(T,P) \]
Parameters
grt Output vector of nondimensional standard state Gibbs free energies. Length: m_kk.
Reimplemented from ThermoPhase.
Definition at line 200 of file LatticePhase.cpp.
References LatticePhase::gibbs_RT_ref(), Phase::m_kk, LatticePhase::m_Pcurrent, LatticePhase::m_Pref, LatticePhase::m_speciesMolarVolume, and ThermoPhase::RT().
getCp_R()
void getCp_R (doublereal * cpr) const virtual
Get the nondimensional Heat Capacities at constant pressure for the species standard states at the current T and P of the solution.
The heat capacity of the standard state is independent of pressure
\[ Cp^o_k(T,P) = Cp^{ref}_k(T) \]
The reference state thermodynamics is obtained by a pointer to a populated species thermodynamic property manager class (see ThermoPhase::m_spthermo). How to relate pressure changes to the reference state thermodynamics is resolved at this level.
Parameters
cpr Output vector of nondimensional standard state heat capacities. Length: m_kk.
Reimplemented from ThermoPhase.
Definition at line 217 of file LatticePhase.cpp.
References LatticePhase::cp_R_ref().
Referenced by LatticePhase::getPartialMolarCp().
getStandardVolumes()
void getStandardVolumes (doublereal * vol) const virtual
Get the molar volumes of the species standard states at the current T and P of the solution.
units = m^3 / kmol
Parameters
vol Output vector containing the standard state volumes. Length: m_kk.
Reimplemented from ThermoPhase.
Definition at line 223 of file LatticePhase.cpp.
References LatticePhase::m_speciesMolarVolume.
Referenced by LatticePhase::getPartialMolarVolumes().
gibbs_RT_ref()
const vector_fp & gibbs_RT_ref () const
Returns a reference to the dimensionless reference state Gibbs free energy vector.
This function is part of the layer that checks/recalculates the reference state thermo functions.
Definition at line 234 of file LatticePhase.cpp.
References LatticePhase::_updateThermo(), and LatticePhase::m_g0_RT.
Referenced by LatticePhase::getChemPotentials(), LatticePhase::getGibbs_RT(), LatticePhase::getPureGibbs(), and LatticePhase::getStandardChemPotentials().
getGibbs_RT_ref()
void getGibbs_RT_ref (doublereal * grt) const virtual
Returns the vector of nondimensional Gibbs Free Energies of the reference state at the current temperature of the solution and the reference pressure for the species.
Parameters
grt Output vector containing the nondimensional reference state Gibbs Free energies. Length: m_kk.
Reimplemented from ThermoPhase.
Definition at line 240 of file LatticePhase.cpp.
References LatticePhase::_updateThermo(), LatticePhase::m_g0_RT, and Phase::m_kk.
Referenced by LatticePhase::getGibbs_ref().
getGibbs_ref()
void getGibbs_ref (doublereal * g) const virtual
Returns the vector of the Gibbs function of the reference state at the current temperature of the solution and the reference pressure for the species.
Parameters
g Output vector containing the reference state Gibbs Free energies. Length: m_kk. Units: J/kmol.
Reimplemented from ThermoPhase.
Definition at line 209 of file LatticePhase.cpp.
References LatticePhase::getGibbs_RT_ref(), Phase::m_kk, and ThermoPhase::RT().
entropy_R_ref()
const vector_fp & entropy_R_ref () const
Returns a reference to the dimensionless reference state Entropy vector.
This function is part of the layer that checks/recalculates the reference state thermo functions.
Definition at line 248 of file LatticePhase.cpp.
References LatticePhase::_updateThermo(), and LatticePhase::m_s0_R.
Referenced by LatticePhase::entropy_mole(), LatticePhase::getEntropy_R(), and LatticePhase::getPartialMolarEntropies().
cp_R_ref()
const vector_fp & cp_R_ref () const
Returns a reference to the dimensionless reference state Heat Capacity vector.
This function is part of the layer that checks/recalculates the reference state thermo functions.
Definition at line 254 of file LatticePhase.cpp.
References LatticePhase::_updateThermo(), and LatticePhase::m_cp0_R.
Referenced by LatticePhase::cp_mole(), and LatticePhase::getCp_R().
addSpecies()
bool addSpecies (shared_ptr< Species > spec) virtual
The following methods are used in the process of constructing the phase and setting its parameters from a specification in an input file. They are not normally used in application programs. To see how they are used, see importPhase().
Reimplemented from ThermoPhase.
Definition at line 260 of file LatticePhase.cpp.
References ThermoPhase::addSpecies(), LatticePhase::m_cp0_R, LatticePhase::m_g0_RT, LatticePhase::m_h0_RT, Phase::m_kk, LatticePhase::m_Pref, LatticePhase::m_s0_R, LatticePhase::m_speciesMolarVolume, and ThermoPhase::refPressure().
initThermoXML()
void initThermoXML (XML_Node & phaseNode, const std::string & id) virtual
Import and initialize a ThermoPhase object using an XML tree.
Here we read extra information about the XML description of a phase. Regular information about elements and species and their reference state thermodynamic information have already been read at this point. For example, we do not need to call this function for ideal gas equations of state. This function is called from importPhase() after the elements and the species are initialized with default ideal solution level data.
The default implementation in ThermoPhase calls the virtual function initThermo() and then sets the "state" of the phase by looking for an XML element named "state", and then interpreting its contents by calling the virtual function setStateFromXML().
Parameters
phaseNode This object must be the phase node of a complete XML tree description of the phase, including all of the species data. In other words while "phase" must point to an XML phase object, it must have sibling nodes "speciesData" that describe the species in the phase.
id ID of the phase. If nonnull, a check is done to see if phaseNode is pointing to the phase with the correct id.
Reimplemented from ThermoPhase.
Definition at line 276 of file LatticePhase.cpp.
References XML_Node::child(), XML_Node::findByAttr(), XML_Node::findByName(), Cantera::get_XML_NameID(), Cantera::getFloat(), XML_Node::hasChild(), XML_Node::id(), ThermoPhase::initThermoXML(), Phase::m_kk, LatticePhase::m_site_density, LatticePhase::m_speciesMolarVolume, XML_Node::root(), and Phase::speciesName().
setParameters()
void setParameters (int n, doublereal *const c) virtual
Set the equation of state parameters from the argument list.
Set equation of state parameters.
Parameters
n number of parameters. Must be one
c array of n coefficients c[0] = The bulk lattice density (kmol m-3)
Reimplemented from ThermoPhase.
Definition at line 329 of file LatticePhase.cpp.
getParameters()
void getParameters (int & n, doublereal *const c) const virtual
Get the equation of state parameters in a vector.
Parameters
n number of parameters
c array of n coefficients
For this phase:
n = 1
c[0] = molar density of phase [ kmol/m^3 ]
Reimplemented from ThermoPhase.
Definition at line 335 of file LatticePhase.cpp.
setParametersFromXML()
void setParametersFromXML (const XML_Node & eosdata) virtual
Set equation of state parameter values from XML entries.
This method is called by function importPhase() when processing a phase definition in an input file. It should be overloaded in subclasses to set any parameters that are specific to that particular phase model. Note, this method is called before the phase is initialized with elements and/or species.
For this phase, the molar density of the phase is specified in this block, and is a required parameter.
Parameters
eosdata An XML_Node object corresponding to the "thermo" entry for this phase in the input file.
eosdata points to the thermo block, and looks like this:
<phase id="O_lattice_SiO2" >
  <thermo model="Lattice">
    <site_density units="kmol/m^3"> 73.159 </site_density>
    <vacancy_species> "O_vacancy"  </vacancy_species>
  </thermo>
</phase>
Reimplemented from ThermoPhase.
Definition at line 341 of file LatticePhase.cpp.
References XML_Node::_require(), Cantera::getChildValue(), Cantera::getFloat(), LatticePhase::m_site_density, and LatticePhase::m_vacancy.
compositionChanged()
void compositionChanged () protected virtual
Apply changes to the state which are needed after the composition changes.
This function is called after any call to setMassFractions(), setMoleFractions(), or similar. For phases which need to execute a callback after any change to the composition, it should be done by overriding this function rather than overriding all of the composition- setting functions. Derived class implementations of compositionChanged() should call the parent class method as well.
Reimplemented from Phase.
Definition at line 103 of file LatticePhase.cpp.
References LatticePhase::calcDensity(), and Phase::compositionChanged().
_updateThermo()
void _updateThermo () const private
Update the species reference state thermodynamic functions.
The polynomials for the standard state functions are only reevaluated if the temperature has changed.
Definition at line 316 of file LatticePhase.cpp.
References LatticePhase::m_cp0_R, LatticePhase::m_g0_RT, LatticePhase::m_h0_RT, Phase::m_kk, LatticePhase::m_s0_R, ThermoPhase::m_spthermo, ThermoPhase::m_tlast, Phase::temperature(), and MultiSpeciesThermo::update().
Referenced by LatticePhase::cp_R_ref(), LatticePhase::entropy_R_ref(), LatticePhase::getGibbs_RT_ref(), and LatticePhase::gibbs_RT_ref().
Member Data Documentation
m_Pref
doublereal m_Pref protected
Reference state pressure.
Definition at line 676 of file LatticePhase.h.
Referenced by LatticePhase::addSpecies(), LatticePhase::enthalpy_mole(), LatticePhase::getChemPotentials(), LatticePhase::getEnthalpy_RT(), LatticePhase::getGibbs_RT(), and LatticePhase::getPureGibbs().
m_Pcurrent
doublereal m_Pcurrent protected
The current pressure.
Since the density isn't a function of pressure, but only of the mole fractions, we need to independently specify the pressure. The density variable which is inherited as part of the State class, m_dens, is always kept current whenever T, P, or X[] change.
Definition at line 685 of file LatticePhase.h.
Referenced by LatticePhase::getChemPotentials(), LatticePhase::getEnthalpy_RT(), LatticePhase::getGibbs_RT(), LatticePhase::getPureGibbs(), LatticePhase::pressure(), and LatticePhase::setPressure().
m_h0_RT
vector_fp m_h0_RT mutable protected
Reference state enthalpies / RT.
Definition at line 688 of file LatticePhase.h.
Referenced by LatticePhase::_updateThermo(), and LatticePhase::addSpecies().
m_cp0_R
vector_fp m_cp0_R mutable protected
Temporary storage for the reference state heat capacities.
Definition at line 691 of file LatticePhase.h.
Referenced by LatticePhase::_updateThermo(), LatticePhase::addSpecies(), and LatticePhase::cp_R_ref().
m_g0_RT
vector_fp m_g0_RT mutable protected
Temporary storage for the reference state Gibbs energies.
Definition at line 694 of file LatticePhase.h.
Referenced by LatticePhase::_updateThermo(), LatticePhase::addSpecies(), LatticePhase::getGibbs_RT_ref(), and LatticePhase::gibbs_RT_ref().
m_s0_R
vector_fp m_s0_R mutable protected
Temporary storage for the reference state entropies at the current temperature.
Definition at line 698 of file LatticePhase.h.
Referenced by LatticePhase::_updateThermo(), LatticePhase::addSpecies(), and LatticePhase::entropy_R_ref().
m_vacancy
std::string m_vacancy protected
String name for the species which represents a vacancy in the lattice.
This string is currently unused
Definition at line 704 of file LatticePhase.h.
Referenced by LatticePhase::setParametersFromXML().
m_speciesMolarVolume
vector_fp m_speciesMolarVolume protected
Vector of molar volumes for each species in the solution.
Species molar volumes \(m^3 kmol^-1 \)
Definition at line 710 of file LatticePhase.h.
Referenced by LatticePhase::addSpecies(), LatticePhase::getChemPotentials(), LatticePhase::getEnthalpy_RT(), LatticePhase::getGibbs_RT(), LatticePhase::getPureGibbs(), LatticePhase::getStandardVolumes(), and LatticePhase::initThermoXML().
m_site_density
doublereal m_site_density protected
Site Density of the lattice solid.
Currently, this is imposed as a function of T, P or composition
units are kmol m-3
Definition at line 718 of file LatticePhase.h.
Referenced by LatticePhase::calcDensity(), LatticePhase::initThermoXML(), and LatticePhase::setParametersFromXML().
The documentation for this class was generated from the following files:
LatticePhase.h
LatticePhase.cpp