Cantera: ShomatePoly2 Class Reference
ShomatePoly2 Class Reference
Models of Phases of Matter » Thermodynamic Properties » Species Reference-State Thermodynamic Properties
The Shomate polynomial parameterization for two temperature ranges for one species.
#include <ShomatePoly.h>
Public Member Functions
ShomatePoly2 ()
Empty constructor.
ShomatePoly2 (double tlow, double thigh, double pref, const double *coeffs)
Normal constructor.
virtual SpeciesThermoInterpType * duplMyselfAsSpeciesThermoInterpType () const
virtual int reportType () const
Returns an integer representing the type of parameterization.
virtual size_t temperaturePolySize () const
Number of terms in the temperature polynomial for this parameterization.
virtual void updateTemperaturePoly (double T, double *T_poly) const
Given the temperature T, compute the terms of the temperature polynomial T_poly.
virtual void updateProperties (const doublereal *tt, doublereal *cp_R, doublereal *h_RT, doublereal *s_R) const
Update the properties for this species, given a temperature polynomial.
virtual void updatePropertiesTemp (const doublereal temp, doublereal *cp_R, doublereal *h_RT, doublereal *s_R) const
Compute the reference-state property of one species.
virtual void reportParameters (size_t &n, int &type, doublereal &tlow, doublereal &thigh, doublereal &pref, doublereal *const coeffs) const
This utility function reports back the type of parameterization and all of the parameters for the species.
virtual void modifyParameters (doublereal *coeffs)
Modify parameters for the standard state.
virtual doublereal reportHf298 (doublereal *const h298=0) const
Report the 298 K Heat of Formation of the standard state of one species (J kmol-1)
virtual void modifyOneHf298 (const size_t k, const doublereal Hf298New)
Modify the value of the 298 K Heat of Formation of one species in the phase (J kmol-1)
virtual void resetHf298 ()
Restore the original heat of formation for this species.
Public Member Functions inherited from SpeciesThermoInterpType
SpeciesThermoInterpType (double tlow, double thigh, double pref)
SpeciesThermoInterpType (const SpeciesThermoInterpType &b)
SpeciesThermoInterpType & operator= (const SpeciesThermoInterpType &b)
virtual doublereal minTemp () const
Returns the minimum temperature that the thermo parameterization is valid.
virtual doublereal maxTemp () const
Returns the maximum temperature that the thermo parameterization is valid.
virtual doublereal refPressure () const
Returns the reference pressure (Pa)
virtual void validate (const std::string &name)
Check for problems with the parameterization, and generate warnings or throw and exception if any are found.
Protected Attributes
doublereal m_midT
Midrange temperature (kelvin)
ShomatePoly msp_low
Shomate polynomial for the low temperature region.
ShomatePoly msp_high
Shomate polynomial for the high temperature region.
vector_fp m_coeff
Array of the original coefficients.
Protected Attributes inherited from SpeciesThermoInterpType
doublereal m_lowT
lowest valid temperature
doublereal m_highT
Highest valid temperature.
doublereal m_Pref
Reference state pressure.
Detailed Description
The Shomate polynomial parameterization for two temperature ranges for one species.
Seven coefficients \((A,\dots,G)\) are used to represent \(c_p^0(T)\), \(h^0(T)\), and \(s^0(T) \) as polynomials in the temperature, \(T \), in one temperature region:
\[ \tilde{c}_p^0(T) = A + B t + C t^2 + D t^3 + \frac{E}{t^2} \]
\[ \tilde{h}^0(T) = A t + \frac{B t^2}{2} + \frac{C t^3}{3} + \frac{D t^4}{4} - \frac{E}{t} + F. \]
\[ \tilde{s}^0(T) = A\ln t + B t + \frac{C t^2}{2} + \frac{D t^3}{3} - \frac{E}{2t^2} + G. \]
In the above expressions, the thermodynamic polynomials are expressed in dimensional units, but the temperature, \(t \), is divided by 1000. The following dimensions are assumed in the above expressions:
\(\tilde{c}_p^0(T)\) = Heat Capacity (J/gmol*K)
\(\tilde{h}^0(T) \) = standard Enthalpy (kJ/gmol)
\(\tilde{s}^0(T) \)= standard Entropy (J/gmol*K)
\(t \)= temperature (K) / 1000.
For more information about Shomate polynomials, see the NIST website, http://webbook.nist.gov/
Before being used within Cantera, the dimensions must be adjusted to those used by Cantera (i.e., Joules and kmol).
This function uses two temperature regions, each with a Shomate polynomial representation to represent the thermo functions. There are 15 coefficients, therefore, in this representation. The first coefficient is the midrange temperature.
Definition at line 232 of file ShomatePoly.h.
Constructor & Destructor Documentation
ShomatePoly2() [1/2]
ShomatePoly2 () inline
Empty constructor.
Deprecated:
Default constructor to be removed after Cantera 2.3.
Definition at line 237 of file ShomatePoly.h.
References ShomatePoly2::m_coeff, and Cantera::warn_deprecated().
Referenced by ShomatePoly2::duplMyselfAsSpeciesThermoInterpType().
ShomatePoly2() [2/2]
ShomatePoly2 (double tlow, double thigh, double pref, const double * coeffs) inline
Normal constructor.
Parameters
tlow Minimum temperature
thigh Maximum temperature
pref reference pressure (Pa).
coeffs Vector of coefficients used to set the parameters for the standard state. [Tmid, 7 low-T coeffs, 7 high-T coeffs]
Definition at line 253 of file ShomatePoly.h.
Member Function Documentation
duplMyselfAsSpeciesThermoInterpType()
virtual SpeciesThermoInterpType* duplMyselfAsSpeciesThermoInterpType () const inline virtual
Deprecated:
To be removed after Cantera 2.3 for all classes derived from SpeciesThermoInterpType.
Implements SpeciesThermoInterpType.
Definition at line 263 of file ShomatePoly.h.
References ShomatePoly2::ShomatePoly2().
reportType()
virtual int reportType () const inline virtual
Returns an integer representing the type of parameterization.
Implements SpeciesThermoInterpType.
Definition at line 267 of file ShomatePoly.h.
References SHOMATE2.
temperaturePolySize()
virtual size_t temperaturePolySize () const inline virtual
Number of terms in the temperature polynomial for this parameterization.
Reimplemented from SpeciesThermoInterpType.
Definition at line 271 of file ShomatePoly.h.
updateTemperaturePoly()
virtual void updateTemperaturePoly (double T, double * T_poly) const inline virtual
Given the temperature T, compute the terms of the temperature polynomial T_poly.
Reimplemented from SpeciesThermoInterpType.
Definition at line 273 of file ShomatePoly.h.
updateProperties()
virtual void updateProperties (const doublereal * tt, doublereal * cp_R, doublereal * h_RT, doublereal * s_R) const inline virtual
Update the properties for this species, given a temperature polynomial.
This method is called with a pointer to an array containing the functions of temperature needed by this parameterization, and three pointers to arrays where the computed property values should be written. This method updates only one value in each array.
The form and length of the Temperature Polynomial may vary depending on the parameterization.
Parameters
tt vector of evaluated temperature functions
cp_R Vector of Dimensionless heat capacities. (length m_kk).
h_RT Vector of Dimensionless enthalpies. (length m_kk).
s_R Vector of Dimensionless entropies. (length m_kk).
Form of the temperature polynomial:
t is T/1000.
t[0] = t
t[1] = t*t
t[2] = t[1]*t
t[3] = 1.0/t[1]
t[4] = log(t)
`t[5] = 1.0/t;
Reimplemented from SpeciesThermoInterpType.
Definition at line 278 of file ShomatePoly.h.
updatePropertiesTemp()
virtual void updatePropertiesTemp (const doublereal temp, doublereal * cp_R, doublereal * h_RT, doublereal * s_R) const inline virtual
Compute the reference-state property of one species.
Given temperature T in K, this method updates the values of the non- dimensional heat capacity at constant pressure, enthalpy, and entropy, at the reference pressure, of the species.
Parameters
temp Temperature (Kelvin)
cp_R Vector of Dimensionless heat capacities. (length m_kk).
h_RT Vector of Dimensionless enthalpies. (length m_kk).
s_R Vector of Dimensionless entropies. (length m_kk).
Implements SpeciesThermoInterpType.
Definition at line 289 of file ShomatePoly.h.
References ShomatePoly2::m_midT, ShomatePoly2::msp_high, ShomatePoly2::msp_low, and ShomatePoly::updatePropertiesTemp().
reportParameters()
virtual void reportParameters (size_t & index, int & type, doublereal & minTemp, doublereal & maxTemp, doublereal & refPressure, doublereal *const coeffs) const inline virtual
This utility function reports back the type of parameterization and all of the parameters for the species.
All parameters are output variables
Parameters
index Species index
type Integer type of the standard type
minTemp output - Minimum temperature
maxTemp output - Maximum temperature
refPressure output - reference pressure (Pa).
coeffs Vector of coefficients used to set the parameters for the standard state.
Implements SpeciesThermoInterpType.
Definition at line 300 of file ShomatePoly.h.
modifyParameters()
virtual void modifyParameters (doublereal * coeffs) inline virtual
Modify parameters for the standard state.
Here, we take the tact that we will just regenerate the object.
Parameters
coeffs Vector of coefficients used to set the parameters for the standard state.
Deprecated:
To be removed after Cantera 2.3. Use MultiSpeciesThermo::modifySpecies instead.
Reimplemented from SpeciesThermoInterpType.
Definition at line 323 of file ShomatePoly.h.
References ShomatePoly2::m_coeff, SpeciesThermoInterpType::m_highT, SpeciesThermoInterpType::m_lowT, ShomatePoly2::m_midT, SpeciesThermoInterpType::m_Pref, ShomatePoly2::msp_high, ShomatePoly2::msp_low, and Cantera::warn_deprecated().
reportHf298()
virtual doublereal reportHf298 (doublereal *const h298 = 0) const inline virtual
Report the 298 K Heat of Formation of the standard state of one species (J kmol-1)
The 298K Heat of Formation is defined as the enthalpy change to create the standard state of the species from its constituent elements in their standard states at 298 K and 1 bar.
Parameters
h298 If this is nonnull, the current value of the Heat of Formation at 298K and 1 bar for species m_speciesIndex is returned in h298[m_speciesIndex].
Returns
the current value of the Heat of Formation at 298K and 1 bar for species m_speciesIndex.
Reimplemented from SpeciesThermoInterpType.
Definition at line 332 of file ShomatePoly.h.
References ShomatePoly2::m_midT, ShomatePoly2::msp_high, ShomatePoly2::msp_low, and ShomatePoly::reportHf298().
Referenced by ShomatePoly2::modifyOneHf298().
modifyOneHf298()
virtual void modifyOneHf298 (const size_t k, const doublereal Hf298New) inline virtual
Modify the value of the 298 K Heat of Formation of one species in the phase (J kmol-1)
The 298K heat of formation is defined as the enthalpy change to create the standard state of the species from its constituent elements in their standard states at 298 K and 1 bar.
Parameters
k Species k
Hf298New Specify the new value of the Heat of Formation at 298K and 1 bar
Reimplemented from SpeciesThermoInterpType.
Definition at line 345 of file ShomatePoly.h.
References ShomatePoly::modifyOneHf298(), ShomatePoly2::msp_high, ShomatePoly2::msp_low, ShomatePoly::reportHf298(), and ShomatePoly2::reportHf298().
resetHf298()
virtual void resetHf298 () inline virtual
Restore the original heat of formation for this species.
Resets changes made by modifyOneHf298().
Reimplemented from SpeciesThermoInterpType.
Definition at line 356 of file ShomatePoly.h.
References ShomatePoly2::msp_high, ShomatePoly2::msp_low, and ShomatePoly::resetHf298().
Member Data Documentation
m_midT
doublereal m_midT protected
Midrange temperature (kelvin)
Definition at line 363 of file ShomatePoly.h.
Referenced by ShomatePoly2::modifyParameters(), ShomatePoly2::reportHf298(), and ShomatePoly2::updatePropertiesTemp().
msp_low
ShomatePoly msp_low protected
Shomate polynomial for the low temperature region.
Definition at line 365 of file ShomatePoly.h.
Referenced by ShomatePoly2::modifyOneHf298(), ShomatePoly2::modifyParameters(), ShomatePoly2::reportHf298(), ShomatePoly2::resetHf298(), and ShomatePoly2::updatePropertiesTemp().
msp_high
ShomatePoly msp_high protected
Shomate polynomial for the high temperature region.
Definition at line 367 of file ShomatePoly.h.
Referenced by ShomatePoly2::modifyOneHf298(), ShomatePoly2::modifyParameters(), ShomatePoly2::reportHf298(), ShomatePoly2::resetHf298(), and ShomatePoly2::updatePropertiesTemp().
m_coeff
vector_fp m_coeff protected
Array of the original coefficients.
Definition at line 369 of file ShomatePoly.h.
Referenced by ShomatePoly2::modifyParameters(), and ShomatePoly2::ShomatePoly2().
The documentation for this class was generated from the following file:
ShomatePoly.h