Cantera: PDSS_IdealGas Class Reference
PDSS_IdealGas Class Reference
Models of Phases of Matter » Thermodynamic Properties » Species Standard-State Thermodynamic Properties
Derived class for pressure dependent standard states of an ideal gas species.
#include <PDSS_IdealGas.h>
Public Member Functions
Constructors
PDSS_IdealGas (VPStandardStateTP *tp, int spindex)
Constructor.
PDSS_IdealGas (VPStandardStateTP *tp, int spindex, const std::string &inputFile, const std::string &id="")
Constructor that initializes the object by examining the input file of the ThermoPhase object.
PDSS_IdealGas (VPStandardStateTP *vptp_ptr, size_t spindex, const XML_Node &speciesNode, const XML_Node &phaseRef, bool spInstalled)
Constructor that initializes the object by examining the input file of the ThermoPhase object.
PDSS_IdealGas (const PDSS_IdealGas &b)
PDSS_IdealGas & operator= (const PDSS_IdealGas &b)
virtual PDSS * duplMyselfAsPDSS () const
Duplication routine for objects which inherit from PDSS.
Molar Thermodynamic Properties of the Species Standard State in the Solution
virtual doublereal enthalpy_RT () const
Return the standard state molar enthalpy divided by RT.
virtual doublereal intEnergy_mole () const
Return the molar internal Energy in units of J kmol-1.
virtual doublereal entropy_R () const
Return the standard state entropy divided by RT.
virtual doublereal gibbs_RT () const
Return the molar Gibbs free energy divided by RT.
virtual doublereal cp_R () const
Return the molar const pressure heat capacity divided by RT.
virtual doublereal cv_mole () const
Return the molar const volume heat capacity in units of J kmol-1 K-1.
virtual doublereal molarVolume () const
Return the molar volume at standard state.
virtual doublereal density () const
Return the standard state density at standard state.
Properties of the Reference State of the Species in the Solution
virtual doublereal gibbs_RT_ref () const
Return the molar Gibbs free energy divided by RT at reference pressure.
virtual doublereal enthalpy_RT_ref () const
Return the molar enthalpy divided by RT at reference pressure.
virtual doublereal entropy_R_ref () const
Return the molar entropy divided by R at reference pressure.
virtual doublereal cp_R_ref () const
Return the molar heat capacity divided by R at reference pressure.
virtual doublereal molarVolume_ref () const
Return the molar volume at reference pressure.
Mechanical Equation of State Properties
virtual doublereal pressure () const
Returns the pressure (Pa)
virtual void setPressure (doublereal pres)
Sets the pressure in the object.
virtual void setTemperature (doublereal temp)
Set the internal temperature.
virtual doublereal temperature () const
Return the current stored temperature.
virtual void setState_TP (doublereal temp, doublereal pres)
Set the internal temperature and pressure.
virtual void setState_TR (doublereal temp, doublereal rho)
Set the internal temperature and density.
Initialization of the Object
void constructPDSSFile (VPStandardStateTP *vptp_ptr, size_t spindex, const std::string &inputFile, const std::string &id)
Initialization of a PDSS object using an input XML file.
void constructPDSSXML (VPStandardStateTP *vptp_ptr, size_t spindex, const XML_Node &phaseNode, const std::string &id)
Initialization of a PDSS object using an XML tree.
virtual void initThermo ()
Initialization routine for all of the shallow pointers.
Public Member Functions inherited from PDSS_Nondimensional
virtual doublereal enthalpy_mole () const
Return the molar enthalpy in units of J kmol-1.
virtual doublereal entropy_mole () const
Return the molar entropy in units of J kmol-1 K-1.
virtual doublereal gibbs_mole () const
Return the molar Gibbs free energy in units of J kmol-1.
virtual doublereal cp_mole () const
Return the molar const pressure heat capacity in units of J kmol-1 K-1.
Public Member Functions inherited from PDSS
PDSS ()
Empty Constructor.
PDSS (VPStandardStateTP *tp, size_t spindex)
Constructor that initializes the object by examining the XML entries from the ThermoPhase object.
PDSS (const PDSS &b)
PDSS & operator= (const PDSS &b)
virtual ~PDSS ()
PDSS_enumType reportPDSSType () const
Returns the type of the standard state parameterization.
virtual doublereal enthalpyDelp_mole () const
Get the difference in the standard state enthalpy between the current pressure and the reference pressure, p0.
virtual doublereal entropyDelp_mole () const
Get the difference in the standard state entropy between the current pressure and the reference pressure, p0.
virtual doublereal gibbsDelp_mole () const
Get the difference in the standard state Gibbs free energy between the current pressure and the reference pressure, p0.
virtual doublereal cpDelp_mole () const
Get the difference in standard state heat capacity between the current pressure and the reference pressure, p0.
doublereal refPressure () const
Return the reference pressure for this phase.
doublereal minTemp () const
return the minimum temperature
doublereal maxTemp () const
return the minimum temperature
virtual doublereal thermalExpansionCoeff () const
Return the volumetric thermal expansion coefficient. Units: 1/K.
virtual doublereal critTemperature () const
critical temperature
virtual doublereal critPressure () const
critical pressure
virtual doublereal critDensity () const
critical density
virtual doublereal satPressure (doublereal T)
saturation pressure
doublereal molecularWeight () const
Return the molecular weight of the species in units of kg kmol-1.
void setMolecularWeight (doublereal mw)
Set the molecular weight of the species.
virtual void initThermoXML (const XML_Node &phaseNode, const std::string &id)
Initialization routine for the PDSS object based on the phaseNode.
virtual void reportParams (size_t &kindex, int &type, doublereal *const c, doublereal &minTemp, doublereal &maxTemp, doublereal &refPressure) const
This utility function reports back the type of parameterization and all of the parameters for the species, index.
virtual void initAllPtrs (VPStandardStateTP *vptp_ptr, VPSSMgr *vpssmgr_ptr, MultiSpeciesThermo *spthermo_ptr)
Initialize or Reinitialize all shallow pointers in the object.
Additional Inherited Members
Protected Attributes inherited from PDSS
PDSS_enumType m_pdssType
Enumerated type describing the type of the PDSS object.
doublereal m_temp
Current temperature used by the PDSS object.
doublereal m_pres
State of the system - pressure.
doublereal m_p0
Reference state pressure of the species.
doublereal m_minTemp
Minimum temperature.
doublereal m_maxTemp
Maximum temperature.
VPStandardStateTP * m_tp
ThermoPhase which this species belongs to.
VPSSMgr * m_vpssmgr_ptr
Pointer to the VPSS manager for this object.
doublereal m_mw
Molecular Weight of the species.
size_t m_spindex
Species index in the ThermoPhase corresponding to this species.
MultiSpeciesThermo * m_spthermo
Pointer to the species thermodynamic property manager.
doublereal * m_h0_RT_ptr
Reference state enthalpy divided by RT.
doublereal * m_cp0_R_ptr
Reference state heat capacity divided by R.
doublereal * m_s0_R_ptr
Reference state entropy divided by R.
doublereal * m_g0_RT_ptr
Reference state Gibbs free energy divided by RT.
doublereal * m_V0_ptr
Reference state molar volume (m3 kg-1)
doublereal * m_hss_RT_ptr
Standard state enthalpy divided by RT.
doublereal * m_cpss_R_ptr
Standard state heat capacity divided by R.
doublereal * m_sss_R_ptr
Standard state entropy divided by R.
doublereal * m_gss_RT_ptr
Standard state Gibbs free energy divided by RT.
doublereal * m_Vss_ptr
Standard State molar volume (m3 kg-1)
Detailed Description
Derived class for pressure dependent standard states of an ideal gas species.
This class is for a single Ideal Gas species.
Definition at line 24 of file PDSS_IdealGas.h.
Constructor & Destructor Documentation
PDSS_IdealGas() [1/3]
PDSS_IdealGas (VPStandardStateTP * tp, int spindex)
Constructor.
Parameters
tp Pointer to the ThermoPhase object pertaining to the phase
spindex Species index of the species in the phase
Definition at line 18 of file PDSS_IdealGas.cpp.
References PDSS::m_pdssType.
Referenced by PDSS_IdealGas::duplMyselfAsPDSS().
PDSS_IdealGas() [2/3]
PDSS_IdealGas (VPStandardStateTP * tp, int spindex, const std::string & inputFile, const std::string & id = "")
Constructor that initializes the object by examining the input file of the ThermoPhase object.
This function calls the constructPDSSFile member function.
Parameters
tp Pointer to the ThermoPhase object pertaining to the phase
spindex Species index of the species in the phase
inputFile String name of the input file
id String name of the phase in the input file. The default is the empty string, in which case the first phase in the file is used.
Deprecated:
To be removed after Cantera 2.3.
Definition at line 24 of file PDSS_IdealGas.cpp.
References PDSS_IdealGas::constructPDSSFile(), PDSS::m_pdssType, and Cantera::warn_deprecated().
PDSS_IdealGas() [3/3]
PDSS_IdealGas (VPStandardStateTP * vptp_ptr, size_t spindex, const XML_Node & speciesNode, const XML_Node & phaseRef, bool spInstalled)
Constructor that initializes the object by examining the input file of the ThermoPhase object.
This function calls the constructPDSSXML member function.
Parameters
vptp_ptr Pointer to the ThermoPhase object pertaining to the phase
spindex Species index of the species in the phase
speciesNode Reference to the species XML tree.
phaseRef Reference to the XML tree containing the phase information.
spInstalled Boolean indicating whether the species is installed yet or not.
Definition at line 34 of file PDSS_IdealGas.cpp.
References PDSS_IdealGas::constructPDSSXML(), and PDSS::m_pdssType.
Member Function Documentation
duplMyselfAsPDSS()
PDSS * duplMyselfAsPDSS () const virtual
Duplication routine for objects which inherit from PDSS.
This function can be used to duplicate objects derived from PDSS even if the application only has a pointer to PDSS to work with.
Returns
A pointer to the base PDSS object type
Deprecated:
To be removed after Cantera 2.3 for all classes derived from PDSS.
Reimplemented from PDSS.
Definition at line 62 of file PDSS_IdealGas.cpp.
References PDSS_IdealGas::PDSS_IdealGas().
enthalpy_RT()
doublereal enthalpy_RT () const virtual
Return the standard state molar enthalpy divided by RT.
Returns
The dimensionless species standard state enthalpy divided at the current temperature and pressure.
Reimplemented from PDSS.
Definition at line 104 of file PDSS_IdealGas.cpp.
References PDSS::m_h0_RT_ptr, and PDSS::m_spindex.
intEnergy_mole()
doublereal intEnergy_mole () const virtual
Return the molar internal Energy in units of J kmol-1.
Returns
The species standard state internal Energy in J kmol-1 at the current temperature and pressure.
Reimplemented from PDSS.
Definition at line 109 of file PDSS_IdealGas.cpp.
References Cantera::GasConstant, PDSS::m_h0_RT_ptr, PDSS::m_spindex, and PDSS::m_temp.
entropy_R()
doublereal entropy_R () const virtual
Return the standard state entropy divided by RT.
Returns
The species standard state entropy divided by RT at the current temperature and pressure.
Reimplemented from PDSS.
Definition at line 114 of file PDSS_IdealGas.cpp.
References PDSS::m_p0, PDSS::m_pres, PDSS::m_s0_R_ptr, and PDSS::m_spindex.
gibbs_RT()
doublereal gibbs_RT () const virtual
Return the molar Gibbs free energy divided by RT.
Returns
The species standard state Gibbs free energy divided by RT at the current temperature and pressure.
Reimplemented from PDSS.
Definition at line 119 of file PDSS_IdealGas.cpp.
References PDSS::m_g0_RT_ptr, PDSS::m_p0, PDSS::m_pres, and PDSS::m_spindex.
cp_R()
doublereal cp_R () const virtual
Return the molar const pressure heat capacity divided by RT.
Returns
The species standard state Cp divided by RT at the current temperature and pressure.
Reimplemented from PDSS.
Definition at line 124 of file PDSS_IdealGas.cpp.
References PDSS::m_cp0_R_ptr, and PDSS::m_spindex.
Referenced by PDSS_IdealGas::cp_R_ref().
cv_mole()
doublereal cv_mole () const virtual
Return the molar const volume heat capacity in units of J kmol-1 K-1.
Returns
The species standard state Cv in J kmol-1 K-1 at the current temperature and pressure.
Reimplemented from PDSS.
Definition at line 139 of file PDSS_IdealGas.cpp.
References PDSS_Nondimensional::cp_mole(), and Cantera::GasConstant.
molarVolume()
doublereal molarVolume () const virtual
Return the molar volume at standard state.
Returns
The standard state molar volume at the current temperature and pressure. Units are m**3 kmol-1.
Reimplemented from PDSS.
Definition at line 129 of file PDSS_IdealGas.cpp.
References Cantera::GasConstant, PDSS::m_pres, and PDSS::m_temp.
density()
doublereal density () const virtual
Return the standard state density at standard state.
Returns
The standard state density at the current temperature and pressure. units are kg m-3
Reimplemented from PDSS.
Definition at line 134 of file PDSS_IdealGas.cpp.
References Cantera::GasConstant, PDSS::m_mw, PDSS::m_pres, and PDSS::m_temp.
gibbs_RT_ref()
doublereal gibbs_RT_ref () const virtual
Return the molar Gibbs free energy divided by RT at reference pressure.
Returns
The reference state Gibbs free energy at the current temperature, divided by RT.
Reimplemented from PDSS.
Definition at line 144 of file PDSS_IdealGas.cpp.
References PDSS::m_g0_RT_ptr, and PDSS::m_spindex.
enthalpy_RT_ref()
doublereal enthalpy_RT_ref () const virtual
Return the molar enthalpy divided by RT at reference pressure.
Returns
The species reference state enthalpy at the current temperature, divided by RT.
Reimplemented from PDSS.
Definition at line 149 of file PDSS_IdealGas.cpp.
References PDSS::m_h0_RT_ptr, and PDSS::m_spindex.
entropy_R_ref()
doublereal entropy_R_ref () const virtual
Return the molar entropy divided by R at reference pressure.
Returns
The species reference state entropy at the current temperature, divided by R.
Reimplemented from PDSS.
Definition at line 154 of file PDSS_IdealGas.cpp.
References PDSS::m_s0_R_ptr, and PDSS::m_spindex.
cp_R_ref()
doublereal cp_R_ref () const virtual
Return the molar heat capacity divided by R at reference pressure.
Returns
The species reference state heat capacity divided by R at the current temperature.
Reimplemented from PDSS.
Definition at line 159 of file PDSS_IdealGas.cpp.
References PDSS_IdealGas::cp_R().
molarVolume_ref()
doublereal molarVolume_ref () const virtual
Return the molar volume at reference pressure.
Returns
The reference state molar volume. units are m**3 kmol-1.
Reimplemented from PDSS.
Definition at line 164 of file PDSS_IdealGas.cpp.
References Cantera::GasConstant, PDSS::m_p0, and PDSS::m_temp.
pressure()
doublereal pressure () const virtual
Returns the pressure (Pa)
Reimplemented from PDSS.
Definition at line 169 of file PDSS_IdealGas.cpp.
setPressure()
void setPressure (doublereal pres) virtual
Sets the pressure in the object.
Currently, this sets the pressure in the PDSS object. It is indeterminant what happens to the owning VPStandardStateTP object and to the VPSSMgr object.
Parameters
pres Pressure to be set (Pascal)
Reimplemented from PDSS.
Definition at line 174 of file PDSS_IdealGas.cpp.
References Cantera::GasConstant, PDSS::m_gss_RT_ptr, PDSS::m_hss_RT_ptr, PDSS::m_p0, PDSS::m_pres, PDSS::m_s0_R_ptr, PDSS::m_spindex, PDSS::m_sss_R_ptr, PDSS::m_temp, and PDSS::m_Vss_ptr.
setTemperature()
void setTemperature (doublereal temp) virtual
Set the internal temperature.
Parameters
temp Temperature (Kelvin)
Reimplemented from PDSS.
Definition at line 187 of file PDSS_IdealGas.cpp.
References Cantera::GasConstant, PDSS::m_cp0_R_ptr, PDSS::m_cpss_R_ptr, PDSS::m_g0_RT_ptr, PDSS::m_gss_RT_ptr, PDSS::m_h0_RT_ptr, PDSS::m_hss_RT_ptr, PDSS::m_p0, PDSS::m_pres, PDSS::m_s0_R_ptr, PDSS::m_spindex, PDSS::m_spthermo, PDSS::m_sss_R_ptr, PDSS::m_temp, PDSS::m_V0_ptr, PDSS::m_Vss_ptr, and MultiSpeciesThermo::update_one().
Referenced by PDSS_IdealGas::setState_TP(), and PDSS_IdealGas::setState_TR().
temperature()
doublereal temperature () const virtual
Return the current stored temperature.
Reimplemented from PDSS.
Definition at line 181 of file PDSS_IdealGas.cpp.
References PDSS::m_temp, PDSS::m_vpssmgr_ptr, and VPSSMgr::temperature().
setState_TP()
void setState_TP (doublereal temp, doublereal pres) virtual
Set the internal temperature and pressure.
Parameters
temp Temperature (Kelvin)
pres pressure (Pascals)
Reimplemented from PDSS.
Definition at line 201 of file PDSS_IdealGas.cpp.
References PDSS::m_pres, and PDSS_IdealGas::setTemperature().
setState_TR()
void setState_TR (doublereal temp, doublereal rho) virtual
Set the internal temperature and density.
Parameters
temp Temperature (Kelvin)
rho Density (kg m-3)
Reimplemented from PDSS.
Definition at line 207 of file PDSS_IdealGas.cpp.
References Cantera::GasConstant, PDSS::m_mw, PDSS::m_pres, and PDSS_IdealGas::setTemperature().
constructPDSSFile()
void constructPDSSFile (VPStandardStateTP * vptp_ptr, size_t spindex, const std::string & inputFile, const std::string & id)
Initialization of a PDSS object using an input XML file.
This routine is a precursor to constructPDSSXML(XML_Node*) routine, which does most of the work.
Parameters
vptp_ptr Pointer to the Variable pressure ThermoPhase object
spindex Species index within the phase
inputFile XML file containing the description of the phase
id Optional parameter identifying the name of the phase. If none is given, the first XML phase element will be used.
Deprecated:
To be removed after Cantera 2.3.
Definition at line 72 of file PDSS_IdealGas.cpp.
References XML_Node::build(), PDSS_IdealGas::constructPDSSXML(), Cantera::findInputFile(), Cantera::findXMLPhase(), and Cantera::warn_deprecated().
Referenced by PDSS_IdealGas::PDSS_IdealGas().
constructPDSSXML()
void constructPDSSXML (VPStandardStateTP * vptp_ptr, size_t spindex, const XML_Node & phaseNode, const std::string & id)
Initialization of a PDSS object using an XML tree.
This routine is a driver for the initialization of the object.
basic logic:
initThermo() (cascade)
get stuff from species part of XML file
initThermoXML(phaseNode) (cascade)
Parameters
vptp_ptr Pointer to the Variable pressure ThermoPhase object
spindex Species index within the phase
phaseNode Reference to the phase Information for the phase that owns this species.
id Optional parameter identifying the name of the phase. If none is given, the first XML phase element will be used.
Definition at line 67 of file PDSS_IdealGas.cpp.
Referenced by PDSS_IdealGas::constructPDSSFile(), and PDSS_IdealGas::PDSS_IdealGas().
initThermo()
void initThermo () virtual
Initialization routine for all of the shallow pointers.
This is a cascading call, where each level should call the the parent level.
The initThermo() routines get called before the initThermoXML() routines from the constructPDSSXML() routine.
Calls initPtrs();
Reimplemented from PDSS.
Definition at line 96 of file PDSS_IdealGas.cpp.
References PDSS::initThermo(), PDSS::m_maxTemp, PDSS::m_minTemp, PDSS::m_p0, PDSS::m_spindex, PDSS::m_spthermo, PDSS::m_tp, MultiSpeciesThermo::maxTemp(), MultiSpeciesThermo::minTemp(), MultiSpeciesThermo::refPressure(), and ThermoPhase::speciesThermo().
The documentation for this class was generated from the following files:
PDSS_IdealGas.h
PDSS_IdealGas.cpp