Cantera: Wall Class Reference
Wall Class Reference
Represents a wall between between two ReactorBase objects.
#include <Wall.h>
Public Member Functions
virtual doublereal vdot (doublereal t)
Rate of volume change (m^3/s) for the adjacent reactors.
virtual doublereal Q (doublereal t)
Heat flow rate through the wall (W).
doublereal area ()
Area in m^2.
void setArea (doublereal a)
Set the area [m^2].
double getArea () const
Get the area [m^2].
void setThermalResistance (doublereal Rth)
void setHeatTransferCoeff (doublereal U)
Set the overall heat transfer coefficient [W/m^2/K].
double getHeatTransferCoeff () const
Get the overall heat transfer coefficient [W/m^2/K].
void setEmissivity (doublereal epsilon)
Set the emissivity.
double getEmissivity () const
void setVelocity (Func1 *f=0)
Set the wall velocity to a specified function of time.
void setExpansionRateCoeff (doublereal k)
Set the expansion rate coefficient.
double getExpansionRateCoeff () const
Get the expansion rate coefficient.
void setHeatFlux (Func1 *q)
Specify the heat flux function \(q_0(t) \).
bool install (ReactorBase &leftReactor, ReactorBase &rightReactor)
Install the wall between two reactors or reservoirs.
virtual void initialize ()
Called just before the start of integration.
virtual bool ready ()
True if the wall is correctly configured and ready to use.
ReactorBase & left () const
Return a reference to the Reactor or Reservoir to the left of the wall.
const ReactorBase & right ()
Return a reference to the Reactor or Reservoir to the right of the wall.
void setKinetics (Kinetics *leftMechanism, Kinetics *rightMechanism)
Specify the heterogeneous reaction mechanisms for each side of the wall.
SurfPhase * surface (int leftright)
Return a pointer to the surface phase object for the left (leftright=0) or right (leftright=1) wall surface.
ReactorSurface * reactorSurface (int leftright)
Kinetics * kinetics (int leftright)
Return a pointer to the surface kinetics object for the left (leftright=0) or right (leftright=1) wall surface.
void setCoverages (int leftright, const doublereal *cov)
Set the surface coverages on the left (leftright = 0) or right (leftright = 1) surface to the values in array cov.
void setCoverages (int leftright, const compositionMap &cov)
Set the surface coverages on the left (leftright = 0) or right (leftright = 1) surface to the values in array cov.
void setCoverages (int leftright, const std::string &cov)
Set the surface coverages on the left (leftright = 0) or right (leftright = 1) surface to the values in array cov.
void getCoverages (int leftright, doublereal *cov)
Write the coverages of the left or right surface into array cov.
void syncCoverages (int leftright)
Set the coverages in the surface phase object to the values for this wall surface.
size_t nSensParams (int lr) const
Number of sensitivity parameters associated with reactions on the left (lr = 0) or right (lr = 1) side of the wall.
void addSensitivityReaction (int leftright, size_t rxn)
void setSensitivityParameters (double *params)
void resetSensitivityParameters ()
Protected Attributes
ReactorBase * m_left
ReactorBase * m_right
std::vector< ReactorSurface > m_surf
doublereal m_area
doublereal m_k
doublereal m_rrth
doublereal m_emiss
Func1 * m_vf
Func1 * m_qf
Detailed Description
Represents a wall between between two ReactorBase objects.
Walls can move (changing the volume of the adjacent reactors) and allow heat transfer between reactors.
Definition at line 25 of file Wall.h.
Member Function Documentation
vdot()
doublereal vdot (doublereal t) virtual
Rate of volume change (m^3/s) for the adjacent reactors.
The volume rate of change is given by
\[ \dot V = K A (P_{left} - P_{right}) + F(t) \]
where K is the specified expansion rate coefficient, A is the wall area, and F(t) is a specified function of time. Positive values for vdot correspond to increases in the volume of reactor on left, and decreases in the volume of the reactor on the right.
Definition at line 44 of file Wall.cpp.
References Func1::eval(), and ReactorBase::pressure().
Q()
doublereal Q (doublereal t) virtual
Heat flow rate through the wall (W).
The heat flux is given by
\[ Q = h A (T_{left} - T_{right}) + A G(t) \]
where h is the heat transfer coefficient, A is the wall area, and G(t) is a specified function of time. Positive values denote a flux from left to right.
Definition at line 53 of file Wall.cpp.
References Func1::eval(), Cantera::StefanBoltz, and ReactorBase::temperature().
area()
doublereal area () inline
Area in m^2.
Definition at line 58 of file Wall.h.
setArea()
void setArea (doublereal a) inline
Set the area [m^2].
Definition at line 63 of file Wall.h.
getArea()
double getArea () const inline
Get the area [m^2].
Definition at line 70 of file Wall.h.
setHeatTransferCoeff()
void setHeatTransferCoeff (doublereal U) inline
Set the overall heat transfer coefficient [W/m^2/K].
Definition at line 79 of file Wall.h.
getHeatTransferCoeff()
double getHeatTransferCoeff () const inline
Get the overall heat transfer coefficient [W/m^2/K].
Definition at line 84 of file Wall.h.
setEmissivity()
void setEmissivity (doublereal epsilon) inline
Set the emissivity.
Definition at line 89 of file Wall.h.
setVelocity()
void setVelocity (Func1 * f = 0) inline
Set the wall velocity to a specified function of time.
Definition at line 102 of file Wall.h.
setExpansionRateCoeff()
void setExpansionRateCoeff (doublereal k) inline
Set the expansion rate coefficient.
Definition at line 109 of file Wall.h.
getExpansionRateCoeff()
double getExpansionRateCoeff () const inline
Get the expansion rate coefficient.
Definition at line 114 of file Wall.h.
setHeatFlux()
void setHeatFlux (Func1 * q) inline
Specify the heat flux function \(q_0(t) \).
Definition at line 119 of file Wall.h.
install()
bool install (ReactorBase & leftReactor, ReactorBase & rightReactor)
Install the wall between two reactors or reservoirs.
Definition at line 21 of file Wall.cpp.
References ReactorBase::addWall().
initialize()
virtual void initialize () inline virtual
Called just before the start of integration.
Definition at line 127 of file Wall.h.
Referenced by Reactor::initialize().
ready()
virtual bool ready () inline virtual
True if the wall is correctly configured and ready to use.
Definition at line 130 of file Wall.h.
left()
ReactorBase& left () const inline
Return a reference to the Reactor or Reservoir to the left of the wall.
Definition at line 135 of file Wall.h.
Referenced by Wall::setKinetics().
right()
const ReactorBase& right () inline
Return a reference to the Reactor or Reservoir to the right of the wall.
Definition at line 140 of file Wall.h.
Referenced by Wall::setKinetics().
setKinetics()
void setKinetics (Kinetics * leftMechanism, Kinetics * rightMechanism)
Specify the heterogeneous reaction mechanisms for each side of the wall.
Passing a null pointer indicates that there is no reaction mechanism for the corresponding wall surface.
Deprecated:
Use class ReactorSurface instead. To be removed after Cantera 2.3.
Definition at line 36 of file Wall.cpp.
References Wall::left(), Wall::right(), and Cantera::warn_deprecated().
surface()
SurfPhase* surface (int leftright) inline
Return a pointer to the surface phase object for the left (leftright=0) or right (leftright=1) wall surface.
Deprecated:
Use class ReactorSurface instead. To be removed after Cantera 2.3.
Definition at line 156 of file Wall.h.
reactorSurface()
ReactorSurface* reactorSurface (int leftright) inline
Deprecated:
Use class ReactorSurface instead.
To be removed after Cantera 2.3.
Definition at line 162 of file Wall.h.
Referenced by Reactor::initialize().
kinetics()
Kinetics* kinetics (int leftright) inline
Return a pointer to the surface kinetics object for the left (leftright=0) or right (leftright=1) wall surface.
Deprecated:
Use class ReactorSurface instead. To be removed after Cantera 2.3.
Definition at line 170 of file Wall.h.
Referenced by Reactor::initialize().
setCoverages() [1/3]
void setCoverages (int leftright, const doublereal * cov)
Set the surface coverages on the left (leftright = 0) or right (leftright = 1) surface to the values in array cov.
Deprecated:
Use class ReactorSurface instead. To be removed after Cantera 2.3.
Definition at line 68 of file Wall.cpp.
setCoverages() [2/3]
void setCoverages (int leftright, const compositionMap & cov)
Set the surface coverages on the left (leftright = 0) or right (leftright = 1) surface to the values in array cov.
Deprecated:
Use class ReactorSurface instead. To be removed after Cantera 2.3.
Definition at line 73 of file Wall.cpp.
setCoverages() [3/3]
void setCoverages (int leftright, const std::string & cov)
Set the surface coverages on the left (leftright = 0) or right (leftright = 1) surface to the values in array cov.
Deprecated:
Use class ReactorSurface instead. To be removed after Cantera 2.3.
Definition at line 78 of file Wall.cpp.
getCoverages()
void getCoverages (int leftright, doublereal * cov)
Write the coverages of the left or right surface into array cov.
Deprecated:
Use class ReactorSurface instead. To be removed after Cantera 2.3.
Definition at line 83 of file Wall.cpp.
syncCoverages()
void syncCoverages (int leftright)
Set the coverages in the surface phase object to the values for this wall surface.
Deprecated:
Use class ReactorSurface instead. To be removed after Cantera 2.3.
Definition at line 88 of file Wall.cpp.
nSensParams()
size_t nSensParams (int lr) const inline
Number of sensitivity parameters associated with reactions on the left (lr = 0) or right (lr = 1) side of the wall.
Deprecated:
Use class ReactorSurface instead. To be removed after Cantera 2.3.
Definition at line 207 of file Wall.h.
addSensitivityReaction()
void addSensitivityReaction (int leftright, size_t rxn)
Deprecated:
Use class ReactorSurface instead.
To be removed after Cantera 2.3.
Definition at line 93 of file Wall.cpp.
setSensitivityParameters()
void setSensitivityParameters (double * params)
Deprecated:
Use class ReactorSurface instead.
To be removed after Cantera 2.3.
Definition at line 98 of file Wall.cpp.
resetSensitivityParameters()
void resetSensitivityParameters ()
Deprecated:
Use class ReactorSurface instead.
To be removed after Cantera 2.3.
Definition at line 104 of file Wall.cpp.
The documentation for this class was generated from the following files:
Wall.h
Wall.cpp