Cantera: VPSSMgr_ConstVol Class Reference
VPSSMgr_ConstVol Class Reference
Models of Phases of Matter » Thermodynamic Properties » Managers for Calculating Standard-State
Constant Molar Volume e VPSS species thermo manager class.
#include <VPSSMgr_ConstVol.h>
Public Member Functions
VPSSMgr_ConstVol (VPStandardStateTP *vp_ptr, MultiSpeciesThermo *spth)
Constructor.
VPSSMgr_ConstVol (const VPSSMgr_ConstVol &right)
VPSSMgr_ConstVol & operator= (const VPSSMgr_ConstVol &right)
virtual VPSSMgr * duplMyselfAsVPSSMgr () const
Duplication routine for objects which derive from VPSSMgr.
virtual PDSS_enumType reportPDSSType (int index=-1) const
This utility function reports the type of parameterization used for the species with index number index.
virtual VPSSMgr_enumType reportVPSSMgrType () const
This utility function reports the type of manager for the calculation of ss properties.
Initialization Methods - For Internal use
The following methods are used in the process of constructing the phase and setting its parameters from a specification in an input file. They are not normally seen by application programs
virtual void initThermoXML (XML_Node &phaseNode, const std::string &id)
Finalize the thermo after all species have been entered.
virtual PDSS * createInstallPDSS (size_t k, const XML_Node &speciesNode, const XML_Node *const phaseNode_ptr)
Create and install a constant volume pressure dependent standard state for one species within this object.
Public Member Functions inherited from VPSSMgr
VPSSMgr (VPStandardStateTP *vptp_ptr, MultiSpeciesThermo *spth=0)
Constructor.
VPSSMgr (const VPSSMgr &right)
VPSSMgr & operator= (const VPSSMgr &right)
virtual void getStandardChemPotentials (doublereal *mu) const
Get the array of chemical potentials at unit activity.
virtual void getGibbs_RT (doublereal *grt) const
Get the nondimensional Gibbs functions for the species at their standard states of solution at the current T and P of the solution.
virtual void getEnthalpy_RT (doublereal *hrt) const
Get the nondimensional Enthalpy functions for the species at their standard states at the current T and P of the solution.
const vector_fp & enthalpy_RT () const
Return a reference to a vector of the molar enthalpies of the species in their standard states.
virtual void getEntropy_R (doublereal *sr) const
Get the array of nondimensional Enthalpy functions for the standard state species at the current T and P of the solution.
const vector_fp & entropy_R () const
Return a reference to a vector of the entropies of the species.
virtual void getIntEnergy_RT (doublereal *urt) const
Returns the vector of nondimensional internal Energies of the standard state at the current temperature and pressure of the solution for each species.
virtual void getCp_R (doublereal *cpr) const
Get the nondimensional Heat Capacities at constant pressure for the standard state of the species at the current T and P.
const vector_fp & cp_R () const
Return a reference to a vector of the constant pressure heat capacities of the species.
virtual void getStandardVolumes (doublereal *vol) const
Get the molar volumes of each species in their standard states at the current T and P of the solution.
virtual const vector_fp & getStandardVolumes () const
const vector_fp & standardVolumes () const
Return a reference to a vector of the species standard molar volumes.
virtual void getEnthalpy_RT_ref (doublereal *hrt) const
const vector_fp & Gibbs_RT_ref () const
Return a reference to the vector of Gibbs free energies of the species.
virtual void getGibbs_ref (doublereal *g) const
virtual void getEntropy_R_ref (doublereal *er) const
virtual void getCp_R_ref (doublereal *cpr) const
virtual doublereal minTemp (size_t k=npos) const
Minimum temperature.
virtual doublereal maxTemp (size_t k=npos) const
Maximum temperature.
virtual doublereal refPressure (size_t k=npos) const
The reference-state pressure for the standard state.
virtual void initThermo ()
void initLengths ()
Initialize the lengths within the object.
void installSTSpecies (size_t k, const XML_Node &speciesNode, const XML_Node *phaseNode_ptr)
Install specific content for species k in the reference-state thermodynamic SpeciesManager object.
virtual void initAllPtrs (VPStandardStateTP *vp_ptr, MultiSpeciesThermo *sp_ptr)
Initialize the internal shallow pointers in this object.
virtual void setState_TP (doublereal T, doublereal P)
Set the temperature (K) and pressure (Pa)
virtual void setState_T (doublereal T)
Set the temperature (K)
virtual void setState_P (doublereal P)
Set the pressure (Pa)
doublereal temperature () const
Return the temperature stored in the object.
doublereal pressure () const
Return the pressure stored in the object.
MultiSpeciesThermo * SpeciesThermoMgr ()
Return the pointer to the reference-state Thermo calculator MultiSpeciesThermo object.
virtual void updateStandardStateThermo ()
Updates the internal standard state thermodynamic vectors at the current T and P of the solution.
virtual void updateRefStateThermo () const
Updates the internal reference state thermodynamic vectors at the current T of the solution and the reference pressure.
Protected Member Functions
Properties of the Standard State of the Species in the Solution
Within VPStandardStateTP, these properties are calculated via a common routine, _updateStandardStateThermo(), which must be overloaded in inherited objects. The values are cached within this object, and are not recalculated unless the temperature or pressure changes.
virtual void _updateStandardStateThermo ()
Updates the standard state thermodynamic functions at the current T and P of the solution.
Thermodynamic Values for the Species Reference States
There are also temporary variables for holding the species reference- state values of Cp, H, S, and V at the last temperature and reference pressure called. These functions are not recalculated if a new call is made using the previous temperature. All calculations are done within the routine _updateRefStateThermo(). _updateRefStateThermo() is defined in the parent object.
virtual void getGibbs_RT_ref (doublereal *grt) const
virtual void getStandardVolumes_ref (doublereal *vol) const
Get the molar volumes of the species reference states at the current T and P_ref of the solution.
Protected Member Functions inherited from VPSSMgr
virtual void _updateRefStateThermo () const
Updates the reference state thermodynamic functions at the current T of the solution and the reference pressure.
Additional Inherited Members
Protected Attributes inherited from VPSSMgr
size_t m_kk
Number of species in the phase.
VPStandardStateTP * m_vptp_ptr
Variable pressure ThermoPhase object.
MultiSpeciesThermo * m_spthermo
Pointer to reference state thermo calculator.
doublereal m_tlast
The last temperature at which the standard state thermodynamic properties were calculated at.
doublereal m_plast
The last pressure at which the Standard State thermodynamic properties were calculated at.
doublereal m_p0
Reference pressure (Pa) must be the same for all species - defaults to 1 atm.
doublereal m_minTemp
minimum temperature for the standard state calculations
doublereal m_maxTemp
maximum temperature for the standard state calculations
bool m_useTmpRefStateStorage
boolean indicating whether temporary reference state storage is used -> default is false
vector_fp m_h0_RT
Vector containing the species reference enthalpies at T = m_tlast and P = p_ref.
vector_fp m_cp0_R
Vector containing the species reference constant pressure heat capacities at T = m_tlast and P = p_ref.
vector_fp m_g0_RT
Vector containing the species reference Gibbs functions at T = m_tlast and P = p_ref.
vector_fp m_s0_R
Vector containing the species reference entropies at T = m_tlast and P = p_ref.
vector_fp m_V0
Vector containing the species reference molar volumes.
bool m_useTmpStandardStateStorage
boolean indicating whether temporary standard state storage is used -> default is false
vector_fp m_hss_RT
Vector containing the species Standard State enthalpies at T = m_tlast and P = m_plast.
vector_fp m_cpss_R
Vector containing the species Standard State constant pressure heat capacities at T = m_tlast and P = m_plast.
vector_fp m_gss_RT
Vector containing the species Standard State Gibbs functions at T = m_tlast and P = m_plast.
vector_fp m_sss_R
Vector containing the species Standard State entropies at T = m_tlast and P = m_plast.
vector_fp m_Vss
Vector containing the species standard state volumes at T = m_tlast and P = m_plast.
vector_fp mPDSS_h0_RT
species reference enthalpies - used by individual PDSS objects
vector_fp mPDSS_cp0_R
species reference heat capacities - used by individual PDSS objects
vector_fp mPDSS_g0_RT
species reference Gibbs free energies - used by individual PDSS objects
vector_fp mPDSS_s0_R
species reference entropies - used by individual PDSS objects
vector_fp mPDSS_V0
species reference state molar Volumes - used by individual PDSS objects
vector_fp mPDSS_hss_RT
species standard state enthalpies - used by individual PDSS objects
vector_fp mPDSS_cpss_R
species standard state heat capacities - used by individual PDSS objects
vector_fp mPDSS_gss_RT
species standard state Gibbs free energies - used by individual PDSS objects
vector_fp mPDSS_sss_R
species standard state entropies - used by individual PDSS objects
vector_fp mPDSS_Vss
species standard state molar Volumes - used by individual PDSS objects
Detailed Description
Constant Molar Volume e VPSS species thermo manager class.
The calculation of multiple-species thermodynamic property managers for variable temperature and pressure standard states assuming a constant partial molar volume assumption.
Definition at line 27 of file VPSSMgr_ConstVol.h.
Constructor & Destructor Documentation
VPSSMgr_ConstVol()
VPSSMgr_ConstVol (VPStandardStateTP * vp_ptr, MultiSpeciesThermo * spth)
Constructor.
Parameters
vp_ptr Pointer to the owning VPStandardStateTP object for the phase.
spth Pointer to the MultiSpeciesThermo object for the phase.
Definition at line 23 of file VPSSMgr_ConstVol.cpp.
References VPSSMgr::m_useTmpRefStateStorage, and VPSSMgr::m_useTmpStandardStateStorage.
Referenced by VPSSMgr_ConstVol::duplMyselfAsVPSSMgr().
Member Function Documentation
duplMyselfAsVPSSMgr()
VPSSMgr * duplMyselfAsVPSSMgr () const virtual
Duplication routine for objects which derive from VPSSMgr.
This function can be used to duplicate objects derived from VPSSMgr even if the application only has a pointer to VPSSMgr to work with.
Deprecated:
To be removed after Cantera 2.3 for all classes derived from VPSSMgr.
Reimplemented from VPSSMgr.
Definition at line 47 of file VPSSMgr_ConstVol.cpp.
References VPSSMgr_ConstVol::VPSSMgr_ConstVol().
_updateStandardStateThermo()
void _updateStandardStateThermo () protected virtual
Updates the standard state thermodynamic functions at the current T and P of the solution.
If m_useTmpStandardStateStorage is true, this function must be called for every call to functions in this class. It checks to see whether the temperature or pressure has changed and thus the ss thermodynamics functions for all of the species must be recalculated.
This function is responsible for updating the following internal members, when m_useTmpStandardStateStorage is true.
m_hss_RT;
m_cpss_R;
m_gss_RT;
m_sss_R;
m_Vss
If m_useTmpStandardStateStorage is not true, this function may be required to be called by child classes to update internal member data.
Note, the base class implementation will throw an error. It must be reimplemented in derived classes.
Underscore updates never check for the state of the system They just do the calculation.
Reimplemented from VPSSMgr.
Definition at line 57 of file VPSSMgr_ConstVol.cpp.
References Cantera::GasConstant, VPSSMgr::m_cp0_R, VPSSMgr::m_cpss_R, VPSSMgr::m_gss_RT, VPSSMgr::m_h0_RT, VPSSMgr::m_hss_RT, VPSSMgr::m_kk, VPSSMgr::m_p0, VPSSMgr::m_plast, VPSSMgr::m_s0_R, VPSSMgr::m_sss_R, VPSSMgr::m_tlast, and VPSSMgr::m_Vss.
getGibbs_RT_ref()
void getGibbs_RT_ref (doublereal * grt) const protected virtual
Returns the vector of nondimensional Gibbs free energies of the reference state at the current temperature of the solution and the reference pressure for the species.
Parameters
grt Output vector contains the nondimensional Gibbs free energies of the reference state of the species. length = m_kk, units = dimensionless.
Reimplemented from VPSSMgr.
Definition at line 70 of file VPSSMgr_ConstVol.cpp.
References VPSSMgr::m_g0_RT, and VPSSMgr::m_useTmpRefStateStorage.
getStandardVolumes_ref()
void getStandardVolumes_ref (doublereal * vol) const protected virtual
Get the molar volumes of the species reference states at the current T and P_ref of the solution.
units = m^3 / kmol
Parameters
vol Output vector containing the standard state volumes. Length: m_kk.
Reimplemented from VPSSMgr.
Definition at line 80 of file VPSSMgr_ConstVol.cpp.
References VPSSMgr::m_useTmpStandardStateStorage, and VPSSMgr::m_Vss.
initThermoXML()
void initThermoXML (XML_Node & phaseNode, const std::string & id) virtual
Finalize the thermo after all species have been entered.
This function is the LAST initialization routine to be called. It's called after createInstallPDSS() has been called for each species in the phase, and after initThermo() has been called. It's called via an inner- to-outer onion shell like manner.
In this routine, we currently calculate the reference pressure, the minimum and maximum temperature for the applicability of the thermo formulation.
Parameters
phaseNode Reference to the phaseNode XML node.
id ID of the phase.
Reimplemented from VPSSMgr.
Definition at line 90 of file VPSSMgr_ConstVol.cpp.
References XML_Node::attrib(), XML_Node::child(), XML_Node::findByAttr(), XML_Node::findByName(), Cantera::get_XML_NameID(), Cantera::getFloat(), VPSSMgr::initThermoXML(), VPSSMgr::m_kk, VPSSMgr::m_vptp_ptr, VPSSMgr::m_Vss, XML_Node::root(), and Phase::speciesName().
createInstallPDSS()
PDSS * createInstallPDSS (size_t k, const XML_Node & speciesNode, const XML_Node *const phaseNode_ptr) virtual
Create and install a constant volume pressure dependent standard state for one species within this object.
This function sets up the internal data within this object for handling the calculation of the standard state for the species.
It registers the species with the MultiSpeciesThermo object for the containing VPStandardStateTP phase.
It grabs the molar volume property and installs its value within this object.
It also creates a PDSS object, which basically contains a duplication of some of this information and returns a pointer to the new object.
Parameters
k Species index within the phase
speciesNode Reference to the species node in the XML tree
phaseNode_ptr Pointer to the phase node in the XML tree
Returns
A pointer to the a newly created PDSS object containing the parameterization
Reimplemented from VPSSMgr.
Definition at line 117 of file VPSSMgr_ConstVol.cpp.
References XML_Node::attrib(), XML_Node::findByName(), Cantera::getFloat(), VPSSMgr::installSTSpecies(), VPSSMgr::m_vptp_ptr, and VPSSMgr::m_Vss.
reportPDSSType()
PDSS_enumType reportPDSSType (int index = -1) const virtual
This utility function reports the type of parameterization used for the species with index number index.
The following methods are used in the process of reporting various states and attributes
Parameters
index Species index
Deprecated:
To be removed after Cantera 2.3.
Reimplemented from VPSSMgr.
Definition at line 140 of file VPSSMgr_ConstVol.cpp.
References Cantera::warn_deprecated().
reportVPSSMgrType()
VPSSMgr_enumType reportVPSSMgrType () const virtual
This utility function reports the type of manager for the calculation of ss properties.
Returns
an enum type called VPSSMgr_enumType, which is a list of the known VPSSMgr objects
Deprecated:
Unused. To be removed after Cantera 2.3.
Reimplemented from VPSSMgr.
Definition at line 147 of file VPSSMgr_ConstVol.cpp.
References Cantera::cVPSSMGR_CONSTVOL, and Cantera::warn_deprecated().
The documentation for this class was generated from the following files:
VPSSMgr_ConstVol.h
VPSSMgr_ConstVol.cpp