Cantera: Reactor Class Reference
Reactor Class Reference
Class Reactor is a general-purpose class for stirred reactors.
#include <Reactor.h>
Public Member Functions
virtual int type () const
Return a constant indicating the type of this Reactor.
template<class G >
void insert (G &contents)
Insert something into the reactor.
void setKineticsMgr (Kinetics &kin)
void disableChemistry ()
Disable changes in reactor composition due to chemical reactions.
void enableChemistry ()
Enable changes in reactor composition due to chemical reactions.
void setChemistry (bool cflag=true)
Enable or disable changes in reactor composition due to chemical reactions.
bool chemistryEnabled () const
Returns true if changes in the reactor composition due to chemical reactions are enabled.
void setEnergy (int eflag=1)
Set the energy equation on or off.
bool energyEnabled () const
Returns true if solution of the energy equation is enabled.
virtual size_t neq ()
Number of equations (state variables) for this reactor.
virtual void getInitialConditions (doublereal t0, size_t leny, doublereal *y)
Called by ReactorNet to get the initial conditions.
virtual void getState (doublereal *y)
Get the the current state of the reactor.
virtual void initialize (doublereal t0=0.0)
Initialize the reactor.
virtual void evalEqs (doublereal t, doublereal *y, doublereal *ydot, doublereal *params)
virtual void syncState ()
Set the state of the reactor to correspond to the state of the associated ThermoPhase object.
virtual void updateState (doublereal *y)
Set the state of the reactor to correspond to the state vector y.
virtual size_t nSensParams ()
Number of sensitivity parameters associated with this reactor (including walls)
virtual void addSensitivityReaction (size_t rxn)
Add a sensitivity parameter associated with the reaction number rxn (in the homogeneous phase).
virtual void addSensitivitySpeciesEnthalpy (size_t k)
Add a sensitivity parameter associated with the enthalpy formation of species k (in the homogeneous phase)
virtual size_t componentIndex (const std::string &nm) const
Return the index in the solution vector for this reactor of the component named nm.
virtual std::string componentName (size_t k)
Return the name of the solution component with index i.
Public Member Functions inherited from ReactorBase
ReactorBase (const std::string &name="(none)")
std::string name () const
Return the name of this reactor.
void setName (const std::string &name)
Set the name of this reactor.
void restoreState ()
Set the state of the Phase object associated with this reactor to the reactor's current state.
thermo_t & contents ()
return a reference to the contents.
const thermo_t & contents () const
doublereal residenceTime ()
Return the residence time (s) of the contents of this reactor, based on the outlet mass flow rates and the mass of the reactor contents.
ReactorNet & network ()
The ReactorNet that this reactor belongs to.
void setNetwork (ReactorNet *net)
Set the ReactorNet that this reactor belongs to.
void setInitialVolume (doublereal vol)
Set the initial reactor volume. By default, the volume is 1.0 m^3.
virtual void setThermoMgr (thermo_t &thermo)
Specify the mixture contained in the reactor.
void addInlet (FlowDevice &inlet)
Connect an inlet FlowDevice to this reactor.
void addOutlet (FlowDevice &outlet)
Connect an outlet FlowDevice to this reactor.
FlowDevice & inlet (size_t n=0)
Return a reference to the n-th inlet FlowDevice connected to this reactor.
FlowDevice & outlet (size_t n=0)
Return a reference to the n-th outlet FlowDevice connected to this reactor.
size_t nInlets ()
Return the number of inlet FlowDevice objects connected to this reactor.
size_t nOutlets ()
Return the number of outlet FlowDevice objects connected to this reactor.
size_t nWalls ()
Return the number of Wall objects connected to this reactor.
void addWall (Wall &w, int lr)
Insert a Wall between this reactor and another reactor.
Wall & wall (size_t n)
Return a reference to the n-th Wall connected to this reactor.
void addSurface (ReactorSurface *surf)
ReactorSurface * surface (size_t n)
Return a reference to the n-th ReactorSurface connected to this reactor.
doublereal volume () const
Returns the current volume (m^3) of the reactor.
doublereal density () const
Returns the current density (kg/m^3) of the reactor's contents.
doublereal temperature () const
Returns the current temperature (K) of the reactor's contents.
doublereal enthalpy_mass () const
Returns the current enthalpy (J/kg) of the reactor's contents.
doublereal intEnergy_mass () const
Returns the current internal energy (J/kg) of the reactor's contents.
doublereal pressure () const
Returns the current pressure (Pa) of the reactor.
doublereal mass () const
Returns the mass (kg) of the reactor's contents.
const doublereal * massFractions () const
Return the vector of species mass fractions.
doublereal massFraction (size_t k) const
Return the mass fraction of the k-th species.
Protected Member Functions
virtual void applySensitivity (double *params)
Set reaction rate multipliers based on the sensitivity variables in params.
virtual void resetSensitivity (double *params)
Reset the reaction rate multipliers.
virtual size_t speciesIndex (const std::string &nm) const
Return the index in the solution vector for this reactor of the species named nm, in either the homogeneous phase or a surface phase, relative to the start of the species terms.
virtual void evalWalls (double t)
Evaluate terms related to Walls.
virtual double evalSurfaces (double t, double *ydot)
Evaluate terms related to surface reactions.
virtual void updateSurfaceState (double *y)
Update the state of SurfPhase objects attached to this reactor.
virtual void getSurfaceInitialConditions (double *y)
Get initial conditions for SurfPhase objects attached to this reactor.
Protected Attributes
Kinetics * m_kin
Pointer to the homogeneous Kinetics object that handles the reactions.
doublereal m_vdot
net rate of volume change from moving walls [m^3/s]
doublereal m_Q
net heat transfer through walls [W]
doublereal m_mass
total mass
vector_fp m_work
vector_fp m_sdot
Production rates of gas phase species on surfaces [kmol/s].
vector_fp m_wdot
Species net molar production rates.
vector_fp m_uk
Species molar internal energies.
bool m_chem
bool m_energy
size_t m_nv
std::vector< SensitivityParameter > m_sensParams
Protected Attributes inherited from ReactorBase
size_t m_nsp
Number of homogeneous species in the mixture.
thermo_t * m_thermo
doublereal m_vol
doublereal m_enthalpy
doublereal m_intEnergy
doublereal m_pressure
vector_fp m_state
std::vector< FlowDevice * > m_inlet
std::vector< FlowDevice * > m_outlet
std::vector< Wall * > m_wall
std::vector< ReactorSurface * > m_surfaces
vector_int m_lr
std::string m_name
ReactorNet * m_net
The ReactorNet that this reactor is part of.
Detailed Description
Class Reactor is a general-purpose class for stirred reactors.
The reactor may have an arbitrary number of inlets and outlets, each of which may be connected to a "flow device" such as a mass flow controller, a pressure regulator, etc. Additional reactors may be connected to the other end of the flow device, allowing construction of arbitrary reactor networks.
The reactor class integrates the same governing equations no matter what type of reactor is simulated. The differences among reactor types are completely specified by the attached flow devices and the time-dependent user-specified boundary conditions.
If an instance of class Reactor is used directly, it will simulate an adiabatic, constant volume reactor with gas-phase chemistry but no surface chemistry. Other reactor types may be simulated by deriving a class from Reactor. This method allows specifying the following in terms of the instantaneous reactor state:
rate of change of the total volume (m^3/s)
surface heat loss rate (W)
species surface production rates (kmol/s)
Definition at line 37 of file Reactor.h.
Member Function Documentation
type()
virtual int type () const inline virtual
Return a constant indicating the type of this Reactor.
Reimplemented from ReactorBase.
Reimplemented in ConstPressureReactor, IdealGasConstPressureReactor, IdealGasReactor, and FlowReactor.
Definition at line 42 of file Reactor.h.
insert()
void insert (G & contents) inline
Insert something into the reactor.
The 'something' must belong to a class that is a subclass of both ThermoPhase and Kinetics.
Definition at line 51 of file Reactor.h.
disableChemistry()
void disableChemistry () inline
Disable changes in reactor composition due to chemical reactions.
Deprecated:
Use setChemistry instead. To be removed after Cantera 2.3
Definition at line 60 of file Reactor.h.
References Reactor::setChemistry(), and Cantera::warn_deprecated().
enableChemistry()
void enableChemistry () inline
Enable changes in reactor composition due to chemical reactions.
Deprecated:
Use setChemistry instead. To be removed after Cantera 2.3
Definition at line 68 of file Reactor.h.
References Reactor::setChemistry(), and Cantera::warn_deprecated().
setChemistry()
void setChemistry (bool cflag = true) inline
Enable or disable changes in reactor composition due to chemical reactions.
Definition at line 75 of file Reactor.h.
Referenced by Reactor::disableChemistry(), and Reactor::enableChemistry().
chemistryEnabled()
bool chemistryEnabled () const inline
Returns true if changes in the reactor composition due to chemical reactions are enabled.
Definition at line 80 of file Reactor.h.
setEnergy()
void setEnergy (int eflag = 1) inline
Set the energy equation on or off.
Definition at line 85 of file Reactor.h.
energyEnabled()
bool energyEnabled () const inline
Returns true if solution of the energy equation is enabled.
Definition at line 94 of file Reactor.h.
neq()
virtual size_t neq () inline virtual
Number of equations (state variables) for this reactor.
Definition at line 99 of file Reactor.h.
References Reactor::initialize().
Referenced by Reactor::componentName().
getInitialConditions()
void getInitialConditions (doublereal t0, size_t leny, doublereal * y) virtual
Called by ReactorNet to get the initial conditions.
Essentially calls function getState()
Parameters
[in] t0 Time at which initial conditions are determined
[in] leny Length of y (unused)
[out] y state vector representing the initial state of the reactor
Deprecated:
Use getState instead. To be removed after Cantera 2.3.
Reimplemented in IdealGasConstPressureReactor, ConstPressureReactor, IdealGasReactor, and FlowReactor.
Definition at line 40 of file Reactor.cpp.
References Reactor::getState(), and Cantera::warn_deprecated().
getState()
void getState (doublereal * y) virtual
Get the the current state of the reactor.
Parameters
[out] y state vector representing the initial state of the reactor
Reimplemented in IdealGasConstPressureReactor, ConstPressureReactor, IdealGasReactor, and FlowReactor.
Definition at line 47 of file Reactor.cpp.
References Phase::density(), Phase::getMassFractions(), Reactor::getSurfaceInitialConditions(), ThermoPhase::intEnergy_mass(), Reactor::m_mass, ReactorBase::m_nsp, and Phase::restoreState().
Referenced by Reactor::getInitialConditions().
initialize()
void initialize (doublereal t0 = 0.0) virtual
Initialize the reactor.
Called automatically by ReactorNet::initialize.
Reimplemented from ReactorBase.
Reimplemented in IdealGasConstPressureReactor, ConstPressureReactor, IdealGasReactor, and FlowReactor.
Definition at line 82 of file Reactor.cpp.
References ThermoPhase::enthalpy_mass(), Wall::initialize(), ThermoPhase::intEnergy_mass(), Wall::kinetics(), Reactor::m_kin, ReactorBase::m_nsp, Reactor::m_sdot, Reactor::m_wdot, ThermoPhase::pressure(), Wall::reactorSurface(), and Phase::restoreState().
Referenced by Reactor::neq().
evalEqs()
void evalEqs (doublereal t, doublereal * y, doublereal * ydot, doublereal * params) virtual
Evaluate the reactor governing equations. Called by ReactorNet::eval.
Parameters
[in] t time.
[in] y solution vector, length neq()
[out] ydot rate of change of solution vector, length neq()
[in] params sensitivity parameter vector, length ReactorNet::nparams()
Reimplemented in IdealGasConstPressureReactor, ConstPressureReactor, IdealGasReactor, and FlowReactor.
Definition at line 188 of file Reactor.cpp.
References Reactor::applySensitivity(), Reactor::evalSurfaces(), Reactor::evalWalls(), Kinetics::getNetProductionRates(), Reactor::m_kin, Reactor::m_mass, ReactorBase::m_nsp, Reactor::m_Q, Reactor::m_sdot, Reactor::m_vdot, Reactor::m_wdot, Phase::massFractions(), Phase::molecularWeights(), ThermoPhase::pressure(), Reactor::resetSensitivity(), and Phase::restoreState().
syncState()
void syncState () virtual
Set the state of the reactor to correspond to the state of the associated ThermoPhase object.
This is the inverse of restoreState(). Calling this will trigger integrator reinitialization.
Reimplemented from ReactorBase.
Definition at line 127 of file Reactor.cpp.
References Phase::density(), Reactor::m_mass, and ReactorBase::syncState().
updateState()
void updateState (doublereal * y) virtual
Set the state of the reactor to correspond to the state vector y.
Reimplemented in IdealGasConstPressureReactor, ConstPressureReactor, IdealGasReactor, and FlowReactor.
Definition at line 133 of file Reactor.cpp.
References Reactor::m_mass, and Phase::setMassFractions_NoNorm().
nSensParams()
size_t nSensParams () virtual
Number of sensitivity parameters associated with this reactor (including walls)
Definition at line 118 of file Reactor.cpp.
addSensitivityReaction()
void addSensitivityReaction (size_t rxn) virtual
Add a sensitivity parameter associated with the reaction number rxn (in the homogeneous phase).
Definition at line 300 of file Reactor.cpp.
References Reactor::m_kin, ReactorBase::name(), ReactorBase::network(), Kinetics::nReactions(), Kinetics::reactionString(), and ReactorNet::registerSensitivityParameter().
addSensitivitySpeciesEnthalpy()
void addSensitivitySpeciesEnthalpy (size_t k) virtual
Add a sensitivity parameter associated with the enthalpy formation of species k (in the homogeneous phase)
Definition at line 313 of file Reactor.cpp.
References Cantera::GasConstant, ThermoPhase::Hf298SS(), ReactorBase::name(), ReactorBase::network(), Phase::nSpecies(), ReactorNet::registerSensitivityParameter(), and Phase::speciesName().
componentIndex()
size_t componentIndex (const std::string & nm) const virtual
Return the index in the solution vector for this reactor of the component named nm.
Possible values for nm are "mass", "volume", "int_energy", the name of a homogeneous phase species, or the name of a surface species.
Reimplemented in FlowReactor, IdealGasConstPressureReactor, ConstPressureReactor, and IdealGasReactor.
Definition at line 350 of file Reactor.cpp.
References Cantera::npos, Reactor::speciesIndex(), and Cantera::warn_deprecated().
componentName()
std::string componentName (size_t k) virtual
Return the name of the solution component with index i.
See also
componentIndex()
Reimplemented in IdealGasConstPressureReactor, ConstPressureReactor, and IdealGasReactor.
Definition at line 381 of file Reactor.cpp.
References Reactor::neq(), Phase::nSpecies(), and Phase::speciesName().
applySensitivity()
void applySensitivity (double * params) protected virtual
Set reaction rate multipliers based on the sensitivity variables in params.
Definition at line 407 of file Reactor.cpp.
References Reactor::m_kin, ThermoPhase::modifyOneHf298SS(), Kinetics::multiplier(), and Kinetics::setMultiplier().
Referenced by FlowReactor::evalEqs(), and Reactor::evalEqs().
resetSensitivity()
void resetSensitivity (double * params) protected virtual
Reset the reaction rate multipliers.
Definition at line 429 of file Reactor.cpp.
References Reactor::m_kin, ThermoPhase::resetHf298(), and Kinetics::setMultiplier().
Referenced by FlowReactor::evalEqs(), and Reactor::evalEqs().
speciesIndex()
size_t speciesIndex (const std::string & nm) const protected virtual
Return the index in the solution vector for this reactor of the species named nm, in either the homogeneous phase or a surface phase, relative to the start of the species terms.
Used to implement componentIndex for specific reactor implementations.
Definition at line 328 of file Reactor.cpp.
References ReactorBase::m_nsp, Cantera::npos, and Phase::speciesIndex().
Referenced by Reactor::componentIndex().
evalWalls()
void evalWalls (double t) protected virtual
Evaluate terms related to Walls.
Calculates m_vdot and m_Q based on wall movement and heat transfer.
Parameters
t the current time
Definition at line 254 of file Reactor.cpp.
References Reactor::m_Q, and Reactor::m_vdot.
Referenced by Reactor::evalEqs().
evalSurfaces()
double evalSurfaces (double t, double * ydot) protected virtual
Evaluate terms related to surface reactions.
Calculates m_sdot and rate of change in surface species coverages.
Parameters
t the current time
[out] ydot array of d(coverage)/dt for surface species
Returns
Net mass flux from surfaces
Definition at line 265 of file Reactor.cpp.
References Reactor::m_sdot, and Phase::molecularWeights().
Referenced by Reactor::evalEqs().
updateSurfaceState()
void updateSurfaceState (double * y) protected virtual
Update the state of SurfPhase objects attached to this reactor.
Definition at line 179 of file Reactor.cpp.
getSurfaceInitialConditions()
void getSurfaceInitialConditions (double * y) protected virtual
Get initial conditions for SurfPhase objects attached to this reactor.
Definition at line 73 of file Reactor.cpp.
Referenced by Reactor::getState().
Member Data Documentation
m_kin
Kinetics* m_kin protected
Pointer to the homogeneous Kinetics object that handles the reactions.
Definition at line 195 of file Reactor.h.
Referenced by Reactor::addSensitivityReaction(), Reactor::applySensitivity(), FlowReactor::evalEqs(), Reactor::evalEqs(), Reactor::initialize(), and Reactor::resetSensitivity().
m_vdot
doublereal m_vdot protected
net rate of volume change from moving walls [m^3/s]
Definition at line 197 of file Reactor.h.
Referenced by Reactor::evalEqs(), and Reactor::evalWalls().
m_Q
doublereal m_Q protected
net heat transfer through walls [W]
Definition at line 198 of file Reactor.h.
Referenced by Reactor::evalEqs(), and Reactor::evalWalls().
m_mass
doublereal m_mass protected
total mass
Definition at line 199 of file Reactor.h.
Referenced by Reactor::evalEqs(), Reactor::getState(), Reactor::syncState(), and Reactor::updateState().
m_sdot
vector_fp m_sdot protected
Production rates of gas phase species on surfaces [kmol/s].
Definition at line 203 of file Reactor.h.
Referenced by Reactor::evalEqs(), Reactor::evalSurfaces(), and Reactor::initialize().
m_wdot
vector_fp m_wdot protected
Species net molar production rates.
Definition at line 205 of file Reactor.h.
Referenced by Reactor::evalEqs(), and Reactor::initialize().
m_uk
vector_fp m_uk protected
Species molar internal energies.
Definition at line 206 of file Reactor.h.
The documentation for this class was generated from the following files:
Reactor.h
Reactor.cpp