Cantera: FalloffReaction Class Reference
FalloffReaction Class Reference
A reaction that is first-order in [M] at low pressure, like a third-body reaction, but zeroth-order in [M] as pressure increases.
#include <Reaction.h>
Public Member Functions
FalloffReaction (const Composition &reactants, const Composition &products, const Arrhenius &low_rate, const Arrhenius &high_rate, const ThirdBody &tbody)
virtual std::string reactantString () const
The reactant side of the chemical equation for this reaction.
virtual std::string productString () const
The product side of the chemical equation for this reaction.
virtual void validate ()
Ensure that the rate constant and other parameters for this reaction are valid.
Public Member Functions inherited from Reaction
Reaction (int type)
Reaction (int type, const Composition &reactants, const Composition &products)
std::string equation () const
The chemical equation for this reaction.
Public Attributes
Arrhenius low_rate
The rate constant in the low-pressure limit.
Arrhenius high_rate
The rate constant in the high-pressure limit.
ThirdBody third_body
Relative efficiencies of third-body species in enhancing the reaction rate.
shared_ptr< Falloff > falloff
Falloff function which determines how low_rate and high_rate are combined to determine the rate constant for the reaction.
Public Attributes inherited from Reaction
int reaction_type
Type of the reaction.
Composition reactants
Reactant species and stoichiometric coefficients.
Composition products
Product species and stoichiometric coefficients.
Composition orders
Forward reaction order with respect to specific species.
std::string id
An identification string for the reaction, used in some filtering operations.
bool reversible
True if the current reaction is reversible. False otherwise.
bool duplicate
True if the current reaction is marked as duplicate.
bool allow_nonreactant_orders
True if reaction orders can be specified for non-reactant species.
bool allow_negative_orders
True if negative reaction orders are allowed. Default is false.
Detailed Description
A reaction that is first-order in [M] at low pressure, like a third-body reaction, but zeroth-order in [M] as pressure increases.
Definition at line 128 of file Reaction.h.
Member Function Documentation
reactantString()
std::string reactantString () const virtual
The reactant side of the chemical equation for this reaction.
Reimplemented from Reaction.
Definition at line 170 of file Reaction.cpp.
References ThirdBody::default_efficiency, ThirdBody::efficiencies, Reaction::reactantString(), and FalloffReaction::third_body.
productString()
std::string productString () const virtual
The product side of the chemical equation for this reaction.
Reimplemented from Reaction.
Definition at line 180 of file Reaction.cpp.
References ThirdBody::default_efficiency, ThirdBody::efficiencies, Reaction::productString(), and FalloffReaction::third_body.
validate()
void validate () virtual
Ensure that the rate constant and other parameters for this reaction are valid.
Reimplemented from Reaction.
Definition at line 190 of file Reaction.cpp.
References Reaction::equation(), FalloffReaction::high_rate, FalloffReaction::low_rate, Arrhenius::preExponentialFactor(), and Reaction::validate().
Member Data Documentation
low_rate
Arrhenius low_rate
The rate constant in the low-pressure limit.
Definition at line 140 of file Reaction.h.
Referenced by FalloffReaction::validate().
high_rate
Arrhenius high_rate
The rate constant in the high-pressure limit.
Definition at line 143 of file Reaction.h.
Referenced by FalloffReaction::validate().
third_body
ThirdBody third_body
Relative efficiencies of third-body species in enhancing the reaction rate.
Definition at line 146 of file Reaction.h.
Referenced by FalloffReaction::productString(), and FalloffReaction::reactantString().
falloff
shared_ptr<Falloff> falloff
Falloff function which determines how low_rate and high_rate are combined to determine the rate constant for the reaction.
Definition at line 150 of file Reaction.h.
The documentation for this class was generated from the following files:
Reaction.h
Reaction.cpp