Cantera: LTPspecies_ExpT Class Reference
LTPspecies_ExpT Class Reference
Class LTPspecies_ExpT holds transport parameters for a specific liquid- phase species (LTPspecies) when the transport property is expressed as an exponential in temperature.
#include <LTPspecies.h>
Public Member Functions
LTPspecies_ExpT (const XML_Node &propNode, const std::string name, TransportPropertyType tp_ind, const thermo_t *thermo)
Construct an LTPspecies object for a liquid transport property expressed as an exponential in temperature.
virtual LTPspecies * duplMyselfAsLTPspecies () const
Duplication routine.
doublereal getSpeciesTransProp ()
Returns the vector of standard state species transport property.
Public Member Functions inherited from LTPspecies
LTPspecies (const XML_Node *const propNode=0, const std::string name="-", TransportPropertyType tp_ind=TP_UNKNOWN, const thermo_t *thermo=0)
Construct an LTPspecies object for a liquid transport property.
virtual bool checkPositive () const
Check to see if the property evaluation will be positive.
doublereal getMixWeight () const
Return the weight mixture.
Protected Attributes
doublereal m_temp
temperature from thermo object
doublereal m_prop
most recent evaluation of the transport property
Protected Attributes inherited from LTPspecies
std::string m_speciesName
Species Name for the property that is being described.
LTPTemperatureDependenceType m_model
Model type for the temperature dependence.
TransportPropertyType m_property
enum indicating which property this is (i.e viscosity)
vector_fp m_coeffs
Model temperature-dependence ceofficients.
const thermo_t * m_thermo
Pointer to a const thermo object to get current temperature.
doublereal m_mixWeight
Weighting used for mixing.
Detailed Description
Class LTPspecies_ExpT holds transport parameters for a specific liquid- phase species (LTPspecies) when the transport property is expressed as an exponential in temperature.
Used for standard state species properties with equations of the form
\[ x = f[0] \exp(f[1] T + ... + f[N] T^{N}) \]
where f[i] are elements of the float array passed in.
As an example of the input required for LTPspecies_ExpT consider the following XML fragment
*    <species>
*      <!-- thermodynamic properties -->
*      <transport>
*        <thermalConductivity model="expT">
*           <floatArray size="2">  0.6, -15.0e-5 </floatArray>
*        </thermalConductivity>
*        <!-- other transport properties -->
*      </transport>
*    </species>
*
Definition at line 382 of file LTPspecies.h.
Constructor & Destructor Documentation
LTPspecies_ExpT()
LTPspecies_ExpT (const XML_Node & propNode, const std::string name, TransportPropertyType tp_ind, const thermo_t * thermo)
Construct an LTPspecies object for a liquid transport property expressed as an exponential in temperature.
The transport property is constructed from the XML node, <propNode>, that is a child of the <transport> node and specifies a type of transport property (like viscosity).
Parameters
propNode Reference to the XML node that contains the property information. This class must be parameterized by reading XML_Node information.
name String containing the species name
tp_ind enum TransportPropertyType containing the property id that this object is creating a parameterization for (e.g., viscosity)
thermo const pointer to the ThermoPhase object, which is used to find the temperature.
Definition at line 189 of file LTPspecies.cpp.
References Cantera::getFloatArray(), LTPspecies::m_coeffs, and LTPspecies::m_model.
Referenced by LTPspecies_ExpT::duplMyselfAsLTPspecies().
Member Function Documentation
duplMyselfAsLTPspecies()
LTPspecies * duplMyselfAsLTPspecies () const virtual
Duplication routine.
(virtual from LTPspecies)
Returns
a copy of this routine as a pointer to LTPspecies
Reimplemented from LTPspecies.
Definition at line 200 of file LTPspecies.cpp.
References LTPspecies_ExpT::LTPspecies_ExpT().
getSpeciesTransProp()
doublereal getSpeciesTransProp () virtual
Returns the vector of standard state species transport property.
The standard state species transport property is returned. Any temperature and composition dependence will be adjusted internally according to the information provided by the subclass object.
Returns
a single double containing the property evaluation at the current ThermoPhase temperature.
Reimplemented from LTPspecies.
Definition at line 205 of file LTPspecies.cpp.
References LTPspecies::m_coeffs, LTPspecies_ExpT::m_prop, LTPspecies_ExpT::m_temp, LTPspecies::m_thermo, and Phase::temperature().
Member Data Documentation
m_temp
doublereal m_temp protected
temperature from thermo object
Definition at line 410 of file LTPspecies.h.
Referenced by LTPspecies_ExpT::getSpeciesTransProp().
m_prop
doublereal m_prop protected
most recent evaluation of the transport property
Definition at line 413 of file LTPspecies.h.
Referenced by LTPspecies_ExpT::getSpeciesTransProp().
The documentation for this class was generated from the following files:
LTPspecies.h
LTPspecies.cpp