Cantera: DustyGasTransport Class Reference
DustyGasTransport Class Reference
Transport Properties for Species in Phases
Class DustyGasTransport implements the Dusty Gas model for transport in porous media.
#include <DustyGasTransport.h>
Public Member Functions
DustyGasTransport (thermo_t *thermo=0)
default constructor
DustyGasTransport (const DustyGasTransport &right)
DustyGasTransport & operator= (const DustyGasTransport &right)
Assignment operator.
virtual Transport * duplMyselfAsTransport () const
Duplication routine for objects which inherit from Transport.
virtual void setThermo (thermo_t &thermo)
Specifies the ThermoPhase object.
virtual int model () const
Transport model.
virtual void setParameters (const int type, const int k, const doublereal *const p)
Set the Parameters in the model.
virtual void getMultiDiffCoeffs (const size_t ld, doublereal *const d)
Return the Multicomponent diffusion coefficients. Units: [m^2/s].
virtual void getMolarFluxes (const doublereal *const state1, const doublereal *const state2, const doublereal delta, doublereal *const fluxes)
Get the molar fluxes [kmol/m^2/s], given the thermodynamic state at two nearby points.
void setPorosity (doublereal porosity)
Set the porosity (dimensionless)
void setTortuosity (doublereal tort)
Set the tortuosity (dimensionless)
void setMeanPoreRadius (doublereal rbar)
Set the mean pore radius (m)
void setMeanParticleDiameter (doublereal dbar)
Set the mean particle diameter.
void setPermeability (doublereal B)
Set the permeability of the media.
Transport & gasTransport ()
Return a reference to the transport manager used to compute the gas binary diffusion coefficients and the viscosity.
Public Member Functions inherited from Transport
Transport (thermo_t *thermo=0, size_t ndim=1)
Constructor.
Transport (const Transport &right)
Transport & operator= (const Transport &right)
thermo_t & thermo ()
bool ready ()
void setNDim (const int ndim)
Set the number of dimensions to be expected in flux expressions.
size_t nDim () const
Return the number of dimensions in flux expressions.
void checkSpeciesIndex (size_t k) const
Check that the specified species index is in range Throws an exception if k is greater than nSpecies()
void checkSpeciesArraySize (size_t kk) const
Check that an array size is at least nSpecies() Throws an exception if kk is less than nSpecies().
virtual doublereal getElectricConduct ()
Compute the mixture electrical conductivity (S m-1) at the current conditions of the phase (Siemens m-1)
virtual void getElectricCurrent (int ndim, const doublereal *grad_T, int ldx, const doublereal *grad_X, int ldf, const doublereal *grad_V, doublereal *current)
Compute the electric current density in A/m^2.
virtual void getSpeciesFluxes (size_t ndim, const doublereal *const grad_T, size_t ldx, const doublereal *const grad_X, size_t ldf, doublereal *const fluxes)
Get the species diffusive mass fluxes wrt to the specified solution averaged velocity, given the gradients in mole fraction and temperature.
virtual void getSpeciesFluxesES (size_t ndim, const doublereal *grad_T, size_t ldx, const doublereal *grad_X, size_t ldf, const doublereal *grad_Phi, doublereal *fluxes)
Get the species diffusive mass fluxes wrt to the mass averaged velocity, given the gradients in mole fraction, temperature and electrostatic potential.
virtual void getSpeciesVdiff (size_t ndim, const doublereal *grad_T, int ldx, const doublereal *grad_X, int ldf, doublereal *Vdiff)
Get the species diffusive velocities wrt to the mass averaged velocity, given the gradients in mole fraction and temperature.
virtual void getSpeciesVdiffES (size_t ndim, const doublereal *grad_T, int ldx, const doublereal *grad_X, int ldf, const doublereal *grad_Phi, doublereal *Vdiff)
Get the species diffusive velocities wrt to the mass averaged velocity, given the gradients in mole fraction, temperature, and electrostatic potential.
virtual void getMassFluxes (const doublereal *state1, const doublereal *state2, doublereal delta, doublereal *mfluxes)
Get the mass fluxes [kg/m^2/s], given the thermodynamic state at two nearby points.
virtual void getThermalDiffCoeffs (doublereal *const dt)
Return a vector of Thermal diffusion coefficients [kg/m/sec].
virtual void getBinaryDiffCoeffs (const size_t ld, doublereal *const d)
Returns the matrix of binary diffusion coefficients [m^2/s].
virtual void getMixDiffCoeffs (doublereal *const d)
Returns a vector of mixture averaged diffusion coefficients.
virtual void getMixDiffCoeffsMole (doublereal *const d)
Returns a vector of mixture averaged diffusion coefficients.
virtual void getMixDiffCoeffsMass (doublereal *const d)
Returns a vector of mixture averaged diffusion coefficients.
void setVelocityBasis (VelocityBasis ivb)
Sets the velocity basis.
VelocityBasis getVelocityBasis () const
Gets the velocity basis.
virtual doublereal viscosity ()
virtual void getSpeciesViscosities (doublereal *const visc)
Returns the pure species viscosities.
virtual doublereal bulkViscosity ()
The bulk viscosity in Pa-s.
virtual doublereal ionConductivity ()
The ionic conductivity in 1/ohm/m.
virtual void getSpeciesIonConductivity (doublereal *const ionCond)
Returns the pure species ionic conductivity.
virtual void mobilityRatio (double *mobRat)
Returns the pointer to the mobility ratios of the species in the phase.
virtual void getSpeciesMobilityRatio (double **mobRat)
Returns the pure species limit of the mobility ratios.
virtual void selfDiffusion (doublereal *const selfDiff)
Returns the self diffusion coefficients of the species in the phase.
virtual void getSpeciesSelfDiffusion (double **selfDiff)
Returns the pure species self diffusion in solution of each species.
virtual doublereal thermalConductivity ()
Returns the mixture thermal conductivity in W/m/K.
virtual doublereal electricalConductivity ()
virtual void getMobilities (doublereal *const mobil_e)
Get the Electrical mobilities (m^2/V/s).
virtual void getFluidMobilities (doublereal *const mobil_f)
Get the fluid mobilities (s kmol/kg).
virtual bool initSolid (SolidTransportData &tr)
Called by TransportFactory to set parameters.
Protected Member Functions
void initialize (ThermoPhase *phase, Transport *gastr)
Initialization routine called by TransportFactory.
Protected Member Functions inherited from Transport
virtual bool initGas (GasTransportParams &tr)
Called by TransportFactory to set parameters.
virtual bool initLiquid (LiquidTransportParams &tr)
Called by TransportFactory to set parameters.
void finalize ()
Enable the transport object for use.
Private Member Functions
void updateTransport_T ()
Update temperature-dependent quantities within the object.
void updateTransport_C ()
Update concentration-dependent quantities within the object.
void updateBinaryDiffCoeffs ()
Private routine to update the dusty gas binary diffusion coefficients.
void updateMultiDiffCoeffs ()
Update the Multicomponent diffusion coefficients that are used in the approximation.
void updateKnudsenDiffCoeffs ()
Update the Knudsen diffusion coefficients.
void eval_H_matrix ()
Calculate the H matrix.
Private Attributes
vector_fp m_mw
Local copy of the species molecular weights.
DenseMatrix m_d
binary diffusion coefficients
vector_fp m_x
mole fractions
vector_fp m_dk
Knudsen diffusion coefficients.
doublereal m_temp
temperature
DenseMatrix m_multidiff
Multicomponent diffusion coefficients.
vector_fp m_spwork
work space of size m_nsp;
vector_fp m_spwork2
work space of size m_nsp;
doublereal m_gradP
Pressure Gradient.
bool m_knudsen_ok
Update-to-date variable for Knudsen diffusion coefficients.
bool m_bulk_ok
Update-to-date variable for Binary diffusion coefficients.
doublereal m_porosity
Porosity.
doublereal m_tortuosity
Tortuosity.
doublereal m_pore_radius
Pore radius (meter)
doublereal m_diam
Particle diameter.
doublereal m_perm
Permeability of the media.
Transport * m_gastran
Pointer to the transport object for the gas phase.
Friends
class TransportFactory
Make the TransportFactory object a friend, because this object has restricted its instantiation to classes which are friends.
Additional Inherited Members
Protected Attributes inherited from Transport
thermo_t * m_thermo
pointer to the object representing the phase
bool m_ready
true if finalize has been called
size_t m_nsp
Number of species.
size_t m_nDim
Number of dimensions used in flux expressions.
int m_velocityBasis
Velocity basis from which diffusion velocities are computed.
Detailed Description
Class DustyGasTransport implements the Dusty Gas model for transport in porous media.
As implemented here, only species transport is handled. The viscosity, thermal conductivity, and thermal diffusion coefficients are not implemented.
The dusty gas model includes the effects of Darcy's law. There is a net flux of species due to a pressure gradient that is part of Darcy's law.
The dusty gas model expresses the value of the molar flux of species \(k \), \(J_k \) by the following formula.
\[ \sum_{j \ne k}{\frac{X_j J_k - X_k J_j}{D^e_{kj}}} + \frac{J_k}{\mathcal{D}^{e}_{k,knud}} = - \nabla C_k - \frac{C_k}{\mathcal{D}^{e}_{k,knud}} \frac{\kappa}{\mu} \nabla p \]
\(j \) is a sum over all species in the gas.
The effective Knudsen diffusion coefficients are given by the following form
\[ \mathcal{D}^e_{k,knud} = \frac{2}{3} \frac{r_{pore} \phi}{\tau} \left(\frac{8 R T}{\pi W_k} \right)^{1/2} \]
The effective knudsen diffusion coefficients take into account the effects of collisions of gas-phase molecules with the wall.
References for the Dusty Gas Model
(1) H. Zhu, R. J. Kee, "Modeling Electrochemical Impedance Spectra in SOFC Button Cells with Internal Methane Reforming," J. Electrochem. Soc., 153(9) A1765-1772 (2006).
(2) H. Zhu, R. J. Kee, V. M. Janardhanan, O. Deutschmann, D. G. Goodwin, J. Electrochem. Soc., 152, A2427 (2005).
(3) E. A. Mason, A. P. Malinauskas," Gas Transport in Porous Media: the Dusty-Gas Model", American Elsevier, New York (1983).
(4) J. W. Veldsink, R. M. J. van Damme, G. F. Versteeg, W. P. M. van Swaaij, "The use of the dusty gas model for the description of mass transport with chemical reaction in porous media," Chemical Engineering Journal, 57, 115 - 125 (1995).
Definition at line 62 of file DustyGasTransport.h.
Constructor & Destructor Documentation
DustyGasTransport (thermo_t * thermo = 0)
default constructor
Parameters
thermo Pointer to the ThermoPhase object for this phase. Defaults to zero.
Definition at line 19 of file DustyGasTransport.cpp.
Referenced by DustyGasTransport::duplMyselfAsTransport().
Member Function Documentation
DustyGasTransport & operator= (const DustyGasTransport & right)
Assignment operator.
Warning -> Shallow pointer copies are made of m_thermo and m_gastran.. gastran may not point to the correct object after this copy. The routine initialize() must be called after this routine to complete the copy.
Parameters
right Reference to DustyGasTransport object to be copied into the current one.
Definition at line 60 of file DustyGasTransport.cpp.
References DustyGasTransport::duplMyselfAsTransport(), DustyGasTransport::m_bulk_ok, DustyGasTransport::m_d, DustyGasTransport::m_diam, DustyGasTransport::m_dk, DustyGasTransport::m_gastran, DustyGasTransport::m_gradP, DustyGasTransport::m_knudsen_ok, DustyGasTransport::m_multidiff, DustyGasTransport::m_mw, DustyGasTransport::m_perm, DustyGasTransport::m_pore_radius, DustyGasTransport::m_porosity, DustyGasTransport::m_spwork, DustyGasTransport::m_spwork2, DustyGasTransport::m_temp, DustyGasTransport::m_tortuosity, and DustyGasTransport::m_x.
Transport * duplMyselfAsTransport () const virtual
Duplication routine for objects which inherit from Transport.
This virtual routine can be used to duplicate objects derived from Transport even if the application only has a pointer to Transport to work with.
These routines are basically wrappers around the derived copy constructor.
Reimplemented from Transport.
Definition at line 98 of file DustyGasTransport.cpp.
References DustyGasTransport::DustyGasTransport().
Referenced by DustyGasTransport::operator=().
void setThermo (thermo_t & thermo) virtual
Specifies the ThermoPhase object.
We have relaxed this operation so that it will succeed when the underlying old and new ThermoPhase objects have the same number of species and the same names of the species in the same order. The idea here is to allow copy constructors and duplicators to work. In order for them to work, we need a method to switch the internal pointer within the Transport object after the duplication takes place. Also, different thermodynamic instanteations of the same species should also work.
Parameters
thermo Reference to the ThermoPhase object that the transport object will use
Reimplemented from Transport.
Definition at line 104 of file DustyGasTransport.cpp.
References DustyGasTransport::m_gastran, and Transport::setThermo().
virtual int model () const inline virtual
Transport model.
The transport model is the set of equations used to compute the transport properties. This method returns an integer flag that identifies the transport model implemented. The base class returns 0.
Reimplemented from Transport.
Definition at line 92 of file DustyGasTransport.h.
void setParameters (const int type, const int k, const doublereal *const p) virtual
Set the Parameters in the model.
Parameters
type Type of the parameter to set 0 - porosity 1 - tortuosity 2 - mean pore radius 3 - mean particle radius 4 - permeability
k Unused int
p pointer to double for the input list of parameters
Deprecated:
Use the individual methods setPorosity(), setTortuosity(), setMeanPoreRadius(), setMeanParticleDiameter(), and setPermeability()
Reimplemented from Transport.
Definition at line 111 of file DustyGasTransport.cpp.
References DustyGasTransport::setMeanParticleDiameter(), DustyGasTransport::setMeanPoreRadius(), DustyGasTransport::setPermeability(), DustyGasTransport::setPorosity(), DustyGasTransport::setTortuosity(), and Cantera::warn_deprecated().
void getMultiDiffCoeffs (const size_t ld, doublereal *const d) virtual
Return the Multicomponent diffusion coefficients. Units: [m^2/s].
Returns the array of multicomponent diffusion coefficients.
Parameters
ld The dimension of the inner loop of d (usually equal to m_nsp)
d flat vector of diffusion coefficients, fortran ordering. d[ld*j+i] is the D_ij diffusion coefficient (the diffusion coefficient for species i due to species j).
Reimplemented from Transport.
Definition at line 300 of file DustyGasTransport.cpp.
References DustyGasTransport::m_multidiff, Transport::m_nsp, and DustyGasTransport::updateMultiDiffCoeffs().
void getMolarFluxes (const doublereal *const state1, const doublereal *const state2, const doublereal delta, doublereal *const fluxes) virtual
Get the molar fluxes [kmol/m^2/s], given the thermodynamic state at two nearby points.
\[ J_k = - \sum_{j = 1, N} \left[D^{multi}_{kj}\right]^{-1} \left(\nabla C_j + \frac{C_j}{\mathcal{D}^{knud}_j} \frac{\kappa}{\mu} \nabla p \right) \]
Parameters
state1 Array of temperature, density, and mass fractions for state 1.
state2 Array of temperature, density, and mass fractions for state 2.
delta Distance from state 1 to state 2 (m).
fluxes Vector of species molar fluxes due to diffusional driving force
Reimplemented from Transport.
Definition at line 219 of file DustyGasTransport.cpp.
References DATA_PTR, Cantera::divide_each(), Cantera::GasConstant, Cantera::increment(), DustyGasTransport::m_diam, DustyGasTransport::m_dk, DustyGasTransport::m_gastran, DustyGasTransport::m_multidiff, DustyGasTransport::m_mw, Transport::m_nsp, DustyGasTransport::m_perm, DustyGasTransport::m_porosity, DustyGasTransport::m_spwork, DustyGasTransport::m_spwork2, Transport::m_thermo, DustyGasTransport::m_tortuosity, Cantera::multiply(), Cantera::scale(), ThermoPhase::setState_TPX(), DustyGasTransport::updateMultiDiffCoeffs(), and Transport::viscosity().
void setPorosity (doublereal porosity)
Set the porosity (dimensionless)
Parameters
porosity Set the value of the porosity
Definition at line 333 of file DustyGasTransport.cpp.
References DustyGasTransport::m_bulk_ok, DustyGasTransport::m_knudsen_ok, and DustyGasTransport::m_porosity.
Referenced by DustyGasTransport::setParameters().
void setTortuosity (doublereal tort)
Set the tortuosity (dimensionless)
Tortuosity is considered to be constant within the object
Parameters
tort Value of the tortuosity
Definition at line 340 of file DustyGasTransport.cpp.
References DustyGasTransport::m_bulk_ok, DustyGasTransport::m_knudsen_ok, and DustyGasTransport::m_tortuosity.
Referenced by DustyGasTransport::setParameters().
void setMeanPoreRadius (doublereal rbar)
Set the mean pore radius (m)
Parameters
rbar Value of the pore radius (m)
Definition at line 347 of file DustyGasTransport.cpp.
References DustyGasTransport::m_knudsen_ok, and DustyGasTransport::m_pore_radius.
Referenced by DustyGasTransport::setParameters().
void setMeanParticleDiameter (doublereal dbar)
Set the mean particle diameter.
Parameters
dbar Set the mean particle diameter (m)
Definition at line 353 of file DustyGasTransport.cpp.
References DustyGasTransport::m_diam.
Referenced by DustyGasTransport::setParameters().
void setPermeability (doublereal B)
Set the permeability of the media.
If not set, the value for close-packed spheres will be used by default.
The value for close-packed spheres is given below, where p is the porosity, t is the tortuosity, and d is the diameter of the sphere
\[ \kappa = \frac{p^3 d^2}{72 t (1 - p)^2} \]
Parameters
B set the permeability of the media (units = m^2)
Definition at line 358 of file DustyGasTransport.cpp.
References DustyGasTransport::m_perm.
Referenced by DustyGasTransport::setParameters().
Transport & gasTransport ()
Return a reference to the transport manager used to compute the gas binary diffusion coefficients and the viscosity.
Returns
Returns a reference to the gas transport object
Definition at line 363 of file DustyGasTransport.cpp.
References DustyGasTransport::m_gastran.
void initialize (ThermoPhase * phase, Transport * gastr) protected
Initialization routine called by TransportFactory.
The DustyGas model is a subordinate model to the gas phase transport model. Here we set the gas phase models.
This is a protected routine, so that initialization of the Model must occur within Cantera's setup
Parameters
phase Pointer to the underlying ThermoPhase model for the gas phase
gastr Pointer to the underlying Transport model for transport in the gas phase.
Definition at line 135 of file DustyGasTransport.cpp.
References DATA_PTR, Phase::getMoleFractions(), DustyGasTransport::m_bulk_ok, DustyGasTransport::m_d, DustyGasTransport::m_dk, DustyGasTransport::m_gastran, DustyGasTransport::m_knudsen_ok, DustyGasTransport::m_multidiff, DustyGasTransport::m_mw, Transport::m_nsp, DustyGasTransport::m_spwork, DustyGasTransport::m_spwork2, Transport::m_thermo, DustyGasTransport::m_x, Phase::molecularWeights(), Phase::nSpecies(), and DenseMatrix::resize().
Referenced by TransportFactory::newTransport().
void updateTransport_T () private
Update temperature-dependent quantities within the object.
The object keeps a value m_temp, which is the temperature at which quantities were last evaluated at. If the temperature is changed, update Booleans are set false, triggering recomputation.
Definition at line 310 of file DustyGasTransport.cpp.
References DustyGasTransport::m_bulk_ok, DustyGasTransport::m_knudsen_ok, DustyGasTransport::m_temp, Transport::m_thermo, and Phase::temperature().
Referenced by DustyGasTransport::updateMultiDiffCoeffs().
void updateTransport_C () private
Update concentration-dependent quantities within the object.
The object keeps a value m_temp, which is the temperature at which quantities were last evaluated at. If the temperature is changed, update Booleans are set false, triggering recomputation.
Definition at line 320 of file DustyGasTransport.cpp.
References DATA_PTR, Phase::getMoleFractions(), DustyGasTransport::m_bulk_ok, Transport::m_nsp, Transport::m_thermo, DustyGasTransport::m_x, and Cantera::Tiny.
Referenced by DustyGasTransport::updateMultiDiffCoeffs().
void updateBinaryDiffCoeffs () private
Private routine to update the dusty gas binary diffusion coefficients.
The dusty gas binary diffusion coefficients \(D^{dg}_{i,j} \) are evaluated from the binary gas-phase diffusion coefficients \(D^{bin}_{i,j} \) using the following formula
\[ D^{dg}_{i,j} = \frac{\phi}{\tau} D^{bin}_{i,j} \]
where \(\phi \) is the porosity of the media and \(\tau \) is the tortuosity of the media.
Definition at line 165 of file DustyGasTransport.cpp.
References Transport::getBinaryDiffCoeffs(), DustyGasTransport::m_bulk_ok, DustyGasTransport::m_d, DustyGasTransport::m_gastran, Transport::m_nsp, DustyGasTransport::m_porosity, DustyGasTransport::m_tortuosity, and Array2D::ptrColumn().
Referenced by DustyGasTransport::eval_H_matrix().
void updateMultiDiffCoeffs () private
Update the Multicomponent diffusion coefficients that are used in the approximation.
This routine updates the H matrix and then inverts it.
Definition at line 281 of file DustyGasTransport.cpp.
References DustyGasTransport::eval_H_matrix(), Cantera::int2str(), Cantera::invert(), DustyGasTransport::m_multidiff, DustyGasTransport::updateTransport_C(), and DustyGasTransport::updateTransport_T().
Referenced by DustyGasTransport::getMolarFluxes(), and DustyGasTransport::getMultiDiffCoeffs().
void updateKnudsenDiffCoeffs () private
Update the Knudsen diffusion coefficients.
The Knudsen diffusion coefficients are given by the following form
\[ \mathcal{D}^{knud}_k = \frac{2}{3} \frac{r_{pore} \phi}{\tau} \left(\frac{8 R T}{\pi W_k} \right)^{1/2} \]
Definition at line 182 of file DustyGasTransport.cpp.
References Cantera::GasConstant, DustyGasTransport::m_dk, DustyGasTransport::m_knudsen_ok, DustyGasTransport::m_mw, Transport::m_nsp, DustyGasTransport::m_pore_radius, DustyGasTransport::m_porosity, DustyGasTransport::m_temp, DustyGasTransport::m_tortuosity, and Cantera::Pi.
Referenced by DustyGasTransport::eval_H_matrix().
void eval_H_matrix () private
Calculate the H matrix.
The multicomponent diffusion H matrix \(H_{k,l} \) is given by the following form
\[ H_{k,l} = - \frac{X_k}{D_{k,l}} \]
\[ H_{k,k} = \frac{1}{\mathcal(D)^{knud}_{k}} + \sum_{j \ne k}^N{ \frac{X_j}{D_{k,j}} } \]
Definition at line 196 of file DustyGasTransport.cpp.
References DustyGasTransport::m_d, DustyGasTransport::m_dk, DustyGasTransport::m_multidiff, Transport::m_nsp, DustyGasTransport::m_x, DustyGasTransport::updateBinaryDiffCoeffs(), and DustyGasTransport::updateKnudsenDiffCoeffs().
Referenced by DustyGasTransport::updateMultiDiffCoeffs().
Friends And Related Function Documentation
friend class TransportFactory friend
Make the TransportFactory object a friend, because this object has restricted its instantiation to classes which are friends.
Definition at line 192 of file DustyGasTransport.h.
Member Data Documentation
vector_fp m_mw private
Local copy of the species molecular weights.
units kg /kmol length = m_nsp;
Definition at line 276 of file DustyGasTransport.h.
Referenced by DustyGasTransport::getMolarFluxes(), DustyGasTransport::initialize(), DustyGasTransport::operator=(), and DustyGasTransport::updateKnudsenDiffCoeffs().
DenseMatrix m_d private
binary diffusion coefficients
Definition at line 279 of file DustyGasTransport.h.
Referenced by DustyGasTransport::eval_H_matrix(), DustyGasTransport::initialize(), DustyGasTransport::operator=(), and DustyGasTransport::updateBinaryDiffCoeffs().
vector_fp m_x private
mole fractions
Definition at line 282 of file DustyGasTransport.h.
Referenced by DustyGasTransport::eval_H_matrix(), DustyGasTransport::initialize(), DustyGasTransport::operator=(), and DustyGasTransport::updateTransport_C().
vector_fp m_dk private
Knudsen diffusion coefficients.
The Knudsen diffusion coefficients are given by the following form
\[ \mathcal{D}^{knud}_k = \frac{2}{3} \frac{r_{pore} \phi}{\tau} \left(\frac{8 R T}{\pi W_k} \right)^{1/2} \]
Definition at line 292 of file DustyGasTransport.h.
Referenced by DustyGasTransport::eval_H_matrix(), DustyGasTransport::getMolarFluxes(), DustyGasTransport::initialize(), DustyGasTransport::operator=(), and DustyGasTransport::updateKnudsenDiffCoeffs().
doublereal m_temp private
temperature
Definition at line 295 of file DustyGasTransport.h.
Referenced by DustyGasTransport::operator=(), DustyGasTransport::updateKnudsenDiffCoeffs(), and DustyGasTransport::updateTransport_T().
DenseMatrix m_multidiff private
Multicomponent diffusion coefficients.
The multicomponent diffusion matrix \(H_{k,l} \) is given by the following form
\[ H_{k,l} = - \frac{X_k}{D_{k,l}} \]
\[ H_{k,k} = \frac{1}{\mathcal(D)^{knud}_{k}} + \sum_{j \ne k}^N{ \frac{X_j}{D_{k,j}} } \]
Definition at line 308 of file DustyGasTransport.h.
Referenced by DustyGasTransport::eval_H_matrix(), DustyGasTransport::getMolarFluxes(), DustyGasTransport::getMultiDiffCoeffs(), DustyGasTransport::initialize(), DustyGasTransport::operator=(), and DustyGasTransport::updateMultiDiffCoeffs().
vector_fp m_spwork private
work space of size m_nsp;
Definition at line 311 of file DustyGasTransport.h.
Referenced by DustyGasTransport::getMolarFluxes(), DustyGasTransport::initialize(), and DustyGasTransport::operator=().
vector_fp m_spwork2 private
work space of size m_nsp;
Definition at line 314 of file DustyGasTransport.h.
Referenced by DustyGasTransport::getMolarFluxes(), DustyGasTransport::initialize(), and DustyGasTransport::operator=().
doublereal m_gradP private
Pressure Gradient.
Definition at line 317 of file DustyGasTransport.h.
Referenced by DustyGasTransport::operator=().
bool m_knudsen_ok private
Update-to-date variable for Knudsen diffusion coefficients.
Definition at line 320 of file DustyGasTransport.h.
Referenced by DustyGasTransport::initialize(), DustyGasTransport::operator=(), DustyGasTransport::setMeanPoreRadius(), DustyGasTransport::setPorosity(), DustyGasTransport::setTortuosity(), DustyGasTransport::updateKnudsenDiffCoeffs(), and DustyGasTransport::updateTransport_T().
bool m_bulk_ok private
Update-to-date variable for Binary diffusion coefficients.
Definition at line 323 of file DustyGasTransport.h.
Referenced by DustyGasTransport::initialize(), DustyGasTransport::operator=(), DustyGasTransport::setPorosity(), DustyGasTransport::setTortuosity(), DustyGasTransport::updateBinaryDiffCoeffs(), DustyGasTransport::updateTransport_C(), and DustyGasTransport::updateTransport_T().
doublereal m_porosity private
Porosity.
Definition at line 326 of file DustyGasTransport.h.
Referenced by DustyGasTransport::getMolarFluxes(), DustyGasTransport::operator=(), DustyGasTransport::setPorosity(), DustyGasTransport::updateBinaryDiffCoeffs(), and DustyGasTransport::updateKnudsenDiffCoeffs().
doublereal m_tortuosity private
Tortuosity.
Definition at line 329 of file DustyGasTransport.h.
Referenced by DustyGasTransport::getMolarFluxes(), DustyGasTransport::operator=(), DustyGasTransport::setTortuosity(), DustyGasTransport::updateBinaryDiffCoeffs(), and DustyGasTransport::updateKnudsenDiffCoeffs().
doublereal m_pore_radius private
Pore radius (meter)
Definition at line 332 of file DustyGasTransport.h.
Referenced by DustyGasTransport::operator=(), DustyGasTransport::setMeanPoreRadius(), and DustyGasTransport::updateKnudsenDiffCoeffs().
doublereal m_diam private
Particle diameter.
The medium is assumed to consist of particles of size m_diam units = m
Definition at line 339 of file DustyGasTransport.h.
Referenced by DustyGasTransport::getMolarFluxes(), DustyGasTransport::operator=(), and DustyGasTransport::setMeanParticleDiameter().
doublereal m_perm private
Permeability of the media.
The permeability is the proportionality constant for Darcy's law which relates discharge rate and viscosity to the applied pressure gradient.
Below is Darcy's law, where \(\kappa \) is the permeability
\[ v = \frac{\kappa}{\mu} \frac{\delta P}{\delta x} \]
units are m2
Definition at line 355 of file DustyGasTransport.h.
Referenced by DustyGasTransport::getMolarFluxes(), DustyGasTransport::operator=(), and DustyGasTransport::setPermeability().
Transport* m_gastran private
Pointer to the transport object for the gas phase.
Note, this object owns the gastran object
Definition at line 361 of file DustyGasTransport.h.
Referenced by DustyGasTransport::gasTransport(), DustyGasTransport::getMolarFluxes(), DustyGasTransport::initialize(), DustyGasTransport::operator=(), DustyGasTransport::setThermo(), and DustyGasTransport::updateBinaryDiffCoeffs().
The documentation for this class was generated from the following files:
DustyGasTransport.h
DustyGasTransport.cpp