Cantera: Rotor Class Reference
Rotor Class Reference
Spectroscopic Models
Class Rotor represents a non-rigid quantum-mechanical rotor.
#include <rotor.h>
Public Member Functions
Rotor ()
Default Constructor.
virtual ~Rotor ()
Destructor.
Rotor (doublereal Bv, doublereal dipoleMoment=0.0, doublereal Dv=0.0, doublereal Hv=0.0)
Full Constructor.
doublereal energy_w (int J)
The energy of the level with rotational quantum number J, in wavenumber units.
int degeneracy (int J)
The number of quantum states with the same J.
doublereal partitionFunction (doublereal T, int cutoff=-1)
The rotational partition function.
doublereal frequency (int J_lower, int J_upper)
The frequency at which radiation is absorbed by a transition from the lower to the upper state in wavenumber units.
doublereal relPopulation (int J, doublereal T)
Ratio of the population of all states with rotational quantum number J to the ground state population.
doublereal population (int J, doublereal T)
doublereal intensity (int J_lower, int J_upper, doublereal T)
The spectral intensity of a rotational transition.
Protected Attributes
doublereal m_Bv
doublereal m_Dv
doublereal m_Hv
doublereal m_dipole
Detailed Description
Class Rotor represents a non-rigid quantum-mechanical rotor.
Deprecated:
incomplete / abandoned
Definition at line 30 of file rotor.h.
Constructor & Destructor Documentation
Rotor () inline
Default Constructor.
Definition at line 35 of file rotor.h.
References Cantera::warn_deprecated().
virtual ~Rotor () inline virtual
Destructor.
Definition at line 40 of file rotor.h.
Rotor (doublereal Bv, doublereal dipoleMoment = 0.0, doublereal Dv = 0.0, doublereal Hv = 0.0)
Full Constructor.
Constructor.
Parameters
Bv Rotational constant, wavenumbers. permanent dipole moment.
Dv Coefficient describing centrifugal effects on the bond length. For a rigid rotor, Bv = 0.
Hv Coefficient describing higher-order vibration-rotation interactions. For a rigid rotor, Hv = 0.
Definition at line 21 of file rotor.cpp.
Member Function Documentation
doublereal energy_w (int J)
The energy of the level with rotational quantum number J, in wavenumber units.
\[ E(J) = J(J+1)B - [J(J+1)]^2 D + [J(J+1)]^3H \]
For a rigid rotor, only B is non-zero. The parameters B, D, and H are set in the constructor.
Definition at line 36 of file rotor.cpp.
Referenced by Rotor::frequency(), Rotor::partitionFunction(), and Rotor::relPopulation().
int degeneracy (int J)
The number of quantum states with the same J.
For a quantum-mechanical rotor, this is simply 2J+1.
Definition at line 46 of file rotor.cpp.
Referenced by Rotor::partitionFunction(), and Rotor::relPopulation().
doublereal partitionFunction (doublereal T, int cutoff = -1)
The rotational partition function.
If T/Trot > 100, then the classical value (T/Trot) is is returned. Otherwise, it is computed as a sum
\[ z = \sum_{J=0}^{J_{max}} (2J + 1) \exp(-E(J)/kT) \]
Definition at line 60 of file rotor.cpp.
References Cantera::Boltzmann, Rotor::degeneracy(), Rotor::energy_w(), and Cantera::wnum_to_J().
doublereal frequency (int J_lower, int J_upper)
The frequency at which radiation is absorbed by a transition from the lower to the upper state in wavenumber units.
Definition at line 92 of file rotor.cpp.
References Rotor::energy_w().
doublereal relPopulation (int J, doublereal T)
Ratio of the population of all states with rotational quantum number J to the ground state population.
Definition at line 83 of file rotor.cpp.
References Cantera::Boltzmann, Rotor::degeneracy(), Rotor::energy_w(), and Cantera::wnum_to_J().
Referenced by Rotor::intensity().
doublereal intensity (int J_lower, int J_upper, doublereal T)
The spectral intensity of a rotational transition.
Definition at line 100 of file rotor.cpp.
References Rotor::relPopulation().
The documentation for this class was generated from the following files:
rotor.h
rotor.cpp