Cantera: Adsorbate Class Reference
Adsorbate Class Reference
Species Reference-State Thermodynamic Properties
An adsorbed surface species.
#include <AdsorbateThermo.h>
Public Member Functions
Adsorbate ()
Empty constructor.
Adsorbate (size_t n, doublereal tlow, doublereal thigh, doublereal pref, const doublereal *coeffs)
Full Constructor.
Adsorbate (const Adsorbate &b)
Copy Constructor.
virtual SpeciesThermoInterpType * duplMyselfAsSpeciesThermoInterpType () const
duplicator
virtual void install (const std::string &name, size_t index, int type, const doublereal *c, doublereal minTemp_, doublereal maxTemp_, doublereal refPressure_)
virtual int reportType () const
Returns an integer representing the type of parameterization.
void updatePropertiesTemp (const doublereal temp, doublereal *cp_R, doublereal *h_RT, doublereal *s_R) const
Compute the reference-state property of one species.
void reportParameters (size_t &n, int &type, doublereal &tlow, doublereal &thigh, doublereal &pref, doublereal *const coeffs) const
Public Member Functions inherited from SpeciesThermoInterpType
SpeciesThermoInterpType ()
Constructor.
SpeciesThermoInterpType (size_t n, doublereal tlow, doublereal thigh, doublereal pref)
Constructor.
virtual ~SpeciesThermoInterpType ()
Destructor.
virtual doublereal minTemp () const
Returns the minimum temperature that the thermo parameterization is valid.
virtual doublereal maxTemp () const
Returns the maximum temperature that the thermo parameterization is valid.
virtual doublereal refPressure () const
Returns the reference pressure (Pa)
virtual size_t speciesIndex () const
Returns an integer representing the species index.
virtual void updateProperties (const doublereal *tempPoly, doublereal *cp_R, doublereal *h_RT, doublereal *s_R) const
Update the properties for this species, given a temperature polynomial.
virtual void modifyParameters (doublereal *coeffs)
Modify parameters for the standard state.
Protected Member Functions
doublereal _energy_RT (double T) const
doublereal _free_energy_RT (double T) const
doublereal _entropy_R (double T) const
Protected Attributes
size_t m_nFreqs
vector_fp m_freq
array of vib frequencies
doublereal m_be
Protected Attributes inherited from SpeciesThermoInterpType
doublereal m_lowT
lowest valid temperature
doublereal m_highT
Highest valid temperature.
doublereal m_Pref
Reference state pressure.
size_t m_index
species index
Detailed Description
An adsorbed surface species.
This class is designed specifically for use by the class GeneralSpeciesThermo. It implements a model for the thermodynamic properties of a molecule that can be modeled as a set of independent quantum harmonic oscillators.
Definition at line 30 of file AdsorbateThermo.h.
Constructor & Destructor Documentation
Adsorbate () inline
Empty constructor.
Definition at line 35 of file AdsorbateThermo.h.
Referenced by Adsorbate::duplMyselfAsSpeciesThermoInterpType().
Adsorbate (size_t n, doublereal tlow, doublereal thigh, doublereal pref, const doublereal * coeffs) inline
Full Constructor.
Parameters
n Species index
tlow output - Minimum temperature
thigh output - Maximum temperature
pref output - reference pressure (Pa).
Definition at line 46 of file AdsorbateThermo.h.
References Adsorbate::m_freq.
Adsorbate (const Adsorbate & b) inline
Copy Constructor.
Definition at line 57 of file AdsorbateThermo.h.
References Adsorbate::m_freq.
Member Function Documentation
virtual SpeciesThermoInterpType* duplMyselfAsSpeciesThermoInterpType () const inline virtual
duplicator
Implements SpeciesThermoInterpType.
Definition at line 65 of file AdsorbateThermo.h.
References Adsorbate::Adsorbate().
virtual void install (const std::string & name, size_t index, int type, const doublereal * c, doublereal minTemp_, doublereal maxTemp_, doublereal refPressure_) inline virtual
Deprecated:
Not a member of the base class
Definition at line 71 of file AdsorbateThermo.h.
References Adsorbate::m_freq, SpeciesThermoInterpType::m_highT, SpeciesThermoInterpType::m_index, SpeciesThermoInterpType::m_lowT, SpeciesThermoInterpType::m_Pref, and Cantera::warn_deprecated().
virtual int reportType () const inline virtual
Returns an integer representing the type of parameterization.
Implements SpeciesThermoInterpType.
Definition at line 87 of file AdsorbateThermo.h.
References ADSORBATE.
void updatePropertiesTemp (const doublereal temp, doublereal * cp_R, doublereal * h_RT, doublereal * s_R) const inline virtual
Compute the reference-state property of one species.
Given temperature T in K, this method updates the values of the non-dimensional heat capacity at constant pressure, enthalpy, and entropy, at the reference pressure, Pref of one of the species. The species index is used to reference into the cp_R, h_RT, and s_R arrays.
Parameters
temp Temperature (Kelvin)
cp_R Vector of Dimensionless heat capacities. (length m_kk).
h_RT Vector of Dimensionless enthalpies. (length m_kk).
s_R Vector of Dimensionless entropies. (length m_kk).
Implements SpeciesThermoInterpType.
Definition at line 91 of file AdsorbateThermo.h.
References SpeciesThermoInterpType::m_index.
void reportParameters (size_t & n, int & type, doublereal & tlow, doublereal & thigh, doublereal & pref, doublereal *const coeffs) const inline virtual
Deprecated:
Implements SpeciesThermoInterpType.
Definition at line 102 of file AdsorbateThermo.h.
References ADSORBATE, Adsorbate::m_freq, SpeciesThermoInterpType::m_highT, SpeciesThermoInterpType::m_index, SpeciesThermoInterpType::m_lowT, SpeciesThermoInterpType::m_Pref, and Cantera::warn_deprecated().
Member Data Documentation
vector_fp m_freq protected
array of vib frequencies
Definition at line 122 of file AdsorbateThermo.h.
Referenced by Adsorbate::Adsorbate(), Adsorbate::install(), and Adsorbate::reportParameters().
The documentation for this class was generated from the following file:
AdsorbateThermo.h