Cantera: IonsFromNeutralVPSSTP Class Reference
IonsFromNeutralVPSSTP Class Reference
#include <IonsFromNeutralVPSSTP.h>
Public Member Functions
void constructPhaseFile (std::string inputFile, std::string id)
The following methods are used in the process of constructing the phase and setting its parameters from a specification in an input file.
void constructPhaseXML (XML_Node &phaseNode, std::string id)
Import and initialize an IonsFromNeutralVPSSTP phase specification in an XML tree into the current object.
void getDissociationCoeffs (vector_fp &fm_neutralMolec_ions, vector_fp &charges, std::vector< size_t > &neutMolIndex) const
Get the Salt Dissociation Coefficients Returns the vector of dissociation coefficients and vector of charges.
void getNeutralMolecMoleFractions (vector_fp &neutralMoleculeMoleFractions) const
Return the current value of the neutral mole fraction vector.
void getNeutralMoleculeMoleGrads (const doublereal *const dx, doublereal *const dy) const
Calculate neutral molecule mole fractions.
void getCationList (std::vector< size_t > &cation) const
Get the list of cations in this object.
void getAnionList (std::vector< size_t > &anion) const
Get the list of anions in this object.
virtual void initThermo ()
void initThermoXML (XML_Node &phaseNode, const std::string &id)
Import and initialize a ThermoPhase object.
Constructors
IonsFromNeutralVPSSTP ()
IonsFromNeutralVPSSTP (const std::string &inputFile, const std::string &id="", ThermoPhase *neutralPhase=0)
Construct and initialize an IonsFromNeutralVPSSTP object directly from an ASCII input file.
IonsFromNeutralVPSSTP (XML_Node &phaseRoot, const std::string &id="", ThermoPhase *neutralPhase=0)
Construct and initialize an IonsFromNeutralVPSSTP object directly from an XML database.
IonsFromNeutralVPSSTP (const IonsFromNeutralVPSSTP &b)
Copy constructor.
IonsFromNeutralVPSSTP & operator= (const IonsFromNeutralVPSSTP &b)
Assignment operator.
virtual ~IonsFromNeutralVPSSTP ()
Destructor.
virtual ThermoPhase * duplMyselfAsThermoPhase () const
Duplication routine for objects which inherit from ThermoPhase.
Utilities
virtual int eosType () const
Equation of state type flag.
Molar Thermodynamic Properties
virtual doublereal enthalpy_mole () const
Return the Molar enthalpy. Units: J/kmol.
virtual doublereal intEnergy_mole () const
Molar internal energy.
virtual doublereal entropy_mole () const
Molar entropy. Units: J/kmol/K.
virtual doublereal gibbs_mole () const
Molar Gibbs free Energy for an ideal gas. Units = J/kmol.
virtual doublereal cp_mole () const
Molar heat capacity at constant pressure. Units: J/kmol/K.
virtual doublereal cv_mole () const
Molar heat capacity at constant volume. Units: J/kmol/K.
Activities, Standard States, and Activity Concentrations
The activity \(a_k\) of a species in solution is related to the chemical potential by
\[ \mu_k = \mu_k^0(T) + \hat R T \log a_k. \]
The quantity \(\mu_k^0(T,P)\) is the chemical potential at unit activity, which depends only on temperature and pressure.
virtual void getActivityCoefficients (doublereal *ac) const
Get the array of non-dimensional molar-based activity coefficients at the current solution temperature, pressure, and solution concentration.
Partial Molar Properties of the Solution
virtual void getChemPotentials (doublereal *mu) const
Get the species chemical potentials. Units: J/kmol.
virtual void getPartialMolarEnthalpies (doublereal *hbar) const
Returns an array of partial molar enthalpies for the species in the mixture.
virtual void getPartialMolarEntropies (doublereal *sbar) const
Returns an array of partial molar entropies for the species in the mixture.
virtual void getdlnActCoeffds (const doublereal dTds, const doublereal *const dXds, doublereal *dlnActCoeffds) const
Get the change in activity coefficients w.r.t.
virtual void getdlnActCoeffdlnX_diag (doublereal *dlnActCoeffdlnX_diag) const
Get the array of log concentration-like derivatives of the log activity coefficients - diagonal component.
virtual void getdlnActCoeffdlnN_diag (doublereal *dlnActCoeffdlnN_diag) const
Get the array of log concentration-like derivatives of the log activity coefficients - diagonal components.
virtual void getdlnActCoeffdlnN (const size_t ld, doublereal *const dlnActCoeffdlnN)
Get the array of derivatives of the ln activity coefficients with respect to the ln species mole numbers.
Setting the State
These methods set all or part of the thermodynamic state.
virtual void setTemperature (const doublereal t)
Set the temperature of the phase.
virtual void setPressure (doublereal p)
Set the internally stored pressure (Pa) at constant temperature and composition.
virtual void setState_TP (doublereal t, doublereal p)
Set the temperature (K) and pressure (Pa)
virtual void calcIonMoleFractions (doublereal *const mf) const
Calculate ion mole fractions from neutral molecule mole fractions.
virtual void calcNeutralMoleculeMoleFractions () const
Calculate neutral molecule mole fractions.
virtual void setMassFractions (const doublereal *const y)
Set the mass fractions to the specified values, and then normalize them so that they sum to 1.0.
virtual void setMassFractions_NoNorm (const doublereal *const y)
Set the mass fractions to the specified values without normalizing.
virtual void setMoleFractions (const doublereal *const x)
Set the mole fractions to the specified values, and then normalize them so that they sum to 1.0.
virtual void setMoleFractions_NoNorm (const doublereal *const x)
Set the mole fractions to the specified values without normalizing.
virtual void setConcentrations (const doublereal *const c)
Set the concentrations to the specified values within the phase.
Public Member Functions inherited from GibbsExcessVPSSTP
GibbsExcessVPSSTP ()
GibbsExcessVPSSTP (const GibbsExcessVPSSTP &b)
Copy constructor.
GibbsExcessVPSSTP & operator= (const GibbsExcessVPSSTP &b)
Assignment operator.
virtual void getActivityConcentrations (doublereal *c) const
This method returns an array of generalized concentrations.
virtual doublereal standardConcentration (size_t k=0) const
The standard concentration \(C^0_k \) used to normalize the generalized concentration.
virtual doublereal logStandardConc (size_t k=0) const
Returns the natural logarithm of the standard concentration of the kth species.
virtual void getUnitsStandardConc (double *uA, int k=0, int sizeUA=6) const
Returns the units of the standard and generalized concentrations Note they have the same units, as their ratio is defined to be equal to the activity of the kth species in the solution, which is unitless.
virtual void getActivities (doublereal *ac) const
Get the array of non-dimensional activities (molality based for this class and classes that derive from it) at the current solution temperature, pressure, and solution concentration.
virtual void getdlnActCoeffdT (doublereal *dlnActCoeffdT) const
Get the array of temperature derivatives of the log activity coefficients.
virtual void getdlnActCoeffdlnX (doublereal *dlnActCoeffdlnX) const
Get the array of log concentration-like derivatives of the log activity coefficients.
void getElectrochemPotentials (doublereal *mu) const
Get the species electrochemical potentials.
virtual void getPartialMolarVolumes (doublereal *vbar) const
Return an array of partial molar volumes for the species in the mixture.
virtual const vector_fp & getPartialMolarVolumes () const
Public Member Functions inherited from VPStandardStateTP
VPStandardStateTP ()
Constructor.
VPStandardStateTP (const VPStandardStateTP &b)
Copy Constructor.
VPStandardStateTP & operator= (const VPStandardStateTP &b)
Assignment operator.
virtual ~VPStandardStateTP ()
Destructor.
virtual int standardStateConvention () const
This method returns the convention used in specification of the standard state, of which there are currently two, temperature based, and variable pressure based.
void getChemPotentials_RT (doublereal *mu) const
Get the array of non-dimensional species chemical potentials.
virtual void getStandardChemPotentials (doublereal *mu) const
Get the array of chemical potentials at unit activity.
virtual void getEnthalpy_RT (doublereal *hrt) const
Get the nondimensional Enthalpy functions for the species at their standard states at the current T and P of the solution.
virtual void getEntropy_R (doublereal *sr) const
Get the array of nondimensional Enthalpy functions for the standard state species at the current T and P of the solution.
virtual void getGibbs_RT (doublereal *grt) const
Get the nondimensional Gibbs functions for the species at their standard states of solution at the current T and P of the solution.
void getPureGibbs (doublereal *gpure) const
Get the standard state Gibbs functions for each species at the current T and P.
virtual void getIntEnergy_RT (doublereal *urt) const
Returns the vector of nondimensional internal Energies of the standard state at the current temperature and pressure of the solution for each species.
virtual void getCp_R (doublereal *cpr) const
Get the nondimensional Heat Capacities at constant pressure for the standard state of the species at the current T and P.
virtual void getStandardVolumes (doublereal *vol) const
Get the molar volumes of each species in their standard states at the current T and P of the solution.
virtual const vector_fp & getStandardVolumes () const
doublereal pressure () const
Returns the current pressure of the phase.
virtual void updateStandardStateThermo () const
Updates the standard state thermodynamic functions at the current T and P of the solution.
virtual void getEnthalpy_RT_ref (doublereal *hrt) const
Returns the vector of nondimensional enthalpies of the reference state at the current temperature of the solution and the reference pressure for the species.
virtual void getGibbs_RT_ref (doublereal *grt) const
Returns the vector of nondimensional Gibbs free energies of the reference state at the current temperature of the solution and the reference pressure for the species.
virtual void getGibbs_ref (doublereal *g) const
virtual void getEntropy_R_ref (doublereal *er) const
virtual void getCp_R_ref (doublereal *cprt) const
virtual void getStandardVolumes_ref (doublereal *vol) const
Get the molar volumes of the species reference states at the current T and P_ref of the solution.
virtual void setParametersFromXML (const XML_Node &eosdata)
Set equation of state parameter values from XML entries.
void setVPSSMgr (VPSSMgr *vp_ptr)
set the VPSS Mgr
VPSSMgr * provideVPSSMgr ()
Return a pointer to the VPSSMgr for this phase.
void createInstallPDSS (size_t k, const XML_Node &s, const XML_Node *phaseNode_ptr)
PDSS * providePDSS (size_t k)
const PDSS * providePDSS (size_t k) const
Public Member Functions inherited from ThermoPhase
ThermoPhase ()
Constructor.
virtual ~ThermoPhase ()
Destructor. Deletes the species thermo manager.
ThermoPhase (const ThermoPhase &right)
Copy Constructor for the ThermoPhase object.
ThermoPhase & operator= (const ThermoPhase &right)
Assignment operator.
doublereal _RT () const
Return the Gas Constant multiplied by the current temperature.
virtual doublereal refPressure () const
Returns the reference pressure in Pa.
virtual doublereal minTemp (size_t k=npos) const
Minimum temperature for which the thermodynamic data for the species or phase are valid.
doublereal Hf298SS (const int k) const
Report the 298 K Heat of Formation of the standard state of one species (J kmol-1)
virtual void modifyOneHf298SS (const int k, const doublereal Hf298New)
Modify the value of the 298 K Heat of Formation of one species in the phase (J kmol-1)
virtual doublereal maxTemp (size_t k=npos) const
Maximum temperature for which the thermodynamic data for the species are valid.
bool chargeNeutralityNecessary () const
Returns the chargeNeutralityNecessity boolean.
virtual doublereal cv_vib (int, double) const
virtual doublereal isothermalCompressibility () const
Returns the isothermal compressibility. Units: 1/Pa.
virtual doublereal thermalExpansionCoeff () const
Return the volumetric thermal expansion coefficient. Units: 1/K.
void setElectricPotential (doublereal v)
Set the electric potential of this phase (V).
doublereal electricPotential () const
Returns the electric potential of this phase (V).
virtual int activityConvention () const
This method returns the convention used in specification of the activities, of which there are currently two, molar- and molality-based conventions.
virtual void getLnActivityCoefficients (doublereal *lnac) const
Get the array of non-dimensional molar-based ln activity coefficients at the current solution temperature, pressure, and solution concentration.
void getElectrochemPotentials (doublereal *mu) const
Get the species electrochemical potentials.
virtual void getPartialMolarIntEnergies (doublereal *ubar) const
Return an array of partial molar internal energies for the species in the mixture.
virtual void getPartialMolarCp (doublereal *cpbar) const
Return an array of partial molar heat capacities for the species in the mixture.
virtual void getdPartialMolarVolumes_dT (doublereal *d_vbar_dT) const
Return an array of derivatives of partial molar volumes wrt temperature for the species in the mixture.
virtual void getdPartialMolarVolumes_dP (doublereal *d_vbar_dP) const
Return an array of derivatives of partial molar volumes wrt pressure for the species in the mixture.
virtual void getdStandardVolumes_dT (doublereal *d_vol_dT) const
Get the derivative of the molar volumes of the species standard states wrt temperature at the current T and P of the solution.
virtual void getdStandardVolumes_dP (doublereal *d_vol_dP) const
Get the derivative molar volumes of the species standard states wrt pressure at the current T and P of the solution.
virtual void getIntEnergy_RT_ref (doublereal *urt) const
Returns the vector of nondimensional internal Energies of the reference state at the current temperature of the solution and the reference pressure for each species.
virtual void setReferenceComposition (const doublereal *const x)
Sets the reference composition.
virtual void getReferenceComposition (doublereal *const x) const
Gets the reference composition.
doublereal enthalpy_mass () const
Specific enthalpy.
doublereal intEnergy_mass () const
Specific internal energy.
doublereal entropy_mass () const
Specific entropy.
doublereal gibbs_mass () const
Specific Gibbs function.
doublereal cp_mass () const
Specific heat at constant pressure.
doublereal cv_mass () const
Specific heat at constant volume.
virtual void setToEquilState (const doublereal *lambda_RT)
This method is used by the ChemEquil equilibrium solver.
void setElementPotentials (const vector_fp &lambda)
Stores the element potentials in the ThermoPhase object.
bool getElementPotentials (doublereal *lambda) const
Returns the element potentials stored in the ThermoPhase object.
virtual doublereal critTemperature () const
Critical temperature (K).
virtual doublereal critPressure () const
Critical pressure (Pa).
virtual doublereal critDensity () const
Critical density (kg/m3).
virtual doublereal satTemperature (doublereal p) const
Return the saturation temperature given the pressure.
virtual doublereal satPressure (doublereal t)
Return the saturation pressure given the temperature.
virtual doublereal vaporFraction () const
Return the fraction of vapor at the current conditions.
virtual void setState_Tsat (doublereal t, doublereal x)
Set the state to a saturated system at a particular temperature.
virtual void setState_Psat (doublereal p, doublereal x)
Set the state to a saturated system at a particular pressure.
void saveSpeciesData (const size_t k, const XML_Node *const data)
Store a reference pointer to the XML tree containing the species data for this phase.
const std::vector< const
XML_Node * > & speciesData () const
Return a pointer to the vector of XML nodes containing the species data for this phase.
void setSpeciesThermo (SpeciesThermo *spthermo)
Install a species thermodynamic property manager.
virtual SpeciesThermo & speciesThermo (int k=-1)
Return a changeable reference to the calculation manager for species reference-state thermodynamic properties.
virtual void initThermoFile (const std::string &inputFile, const std::string &id)
virtual void installSlavePhases (Cantera::XML_Node *phaseNode)
Add in species from Slave phases.
virtual void setParameters (int n, doublereal *const c)
Set the equation of state parameters.
virtual void getParameters (int &n, doublereal *const c) const
Get the equation of state parameters in a vector.
virtual void setStateFromXML (const XML_Node &state)
Set the initial state of the phase to the conditions specified in the state XML element.
virtual void getdlnActCoeffdlnN_numderiv (const size_t ld, doublereal *const dlnActCoeffdlnN)
virtual std::string report (bool show_thermo=true) const
returns a summary of the state of the phase as a string
virtual void reportCSV (std::ofstream &csvFile) const
returns a summary of the state of the phase to a comma separated file.
virtual void setState_TPX (doublereal t, doublereal p, const doublereal *x)
Set the temperature (K), pressure (Pa), and mole fractions.
virtual void setState_TPX (doublereal t, doublereal p, compositionMap &x)
Set the temperature (K), pressure (Pa), and mole fractions.
virtual void setState_TPX (doublereal t, doublereal p, const std::string &x)
Set the temperature (K), pressure (Pa), and mole fractions.
virtual void setState_TPY (doublereal t, doublereal p, const doublereal *y)
Set the internally stored temperature (K), pressure (Pa), and mass fractions of the phase.
virtual void setState_TPY (doublereal t, doublereal p, compositionMap &y)
Set the internally stored temperature (K), pressure (Pa), and mass fractions of the phase.
virtual void setState_TPY (doublereal t, doublereal p, const std::string &y)
Set the internally stored temperature (K), pressure (Pa), and mass fractions of the phase.
virtual void setState_PX (doublereal p, doublereal *x)
Set the pressure (Pa) and mole fractions.
virtual void setState_PY (doublereal p, doublereal *y)
Set the internally stored pressure (Pa) and mass fractions.
virtual void setState_HP (doublereal h, doublereal p, doublereal tol=1.e-4)
Set the internally stored specific enthalpy (J/kg) and pressure (Pa) of the phase.
virtual void setState_UV (doublereal u, doublereal v, doublereal tol=1.e-4)
Set the specific internal energy (J/kg) and specific volume (m^3/kg).
virtual void setState_SP (doublereal s, doublereal p, doublereal tol=1.e-4)
Set the specific entropy (J/kg/K) and pressure (Pa).
virtual void setState_SV (doublereal s, doublereal v, doublereal tol=1.e-4)
Set the specific entropy (J/kg/K) and specific volume (m^3/kg).
Public Member Functions inherited from Phase
Phase ()
Default constructor.
virtual ~Phase ()
Destructor.
Phase (const Phase &right)
Copy Constructor.
Phase & operator= (const Phase &right)
Assignment operator.
XML_Node & xml ()
Returns a reference to the XML_Node stored for the phase.
void saveState (vector_fp &state) const
Save the current internal state of the phase Write to vector 'state' the current internal state.
void saveState (size_t lenstate, doublereal *state) const
Write to array 'state' the current internal state.
void restoreState (const vector_fp &state)
Restore a state saved on a previous call to saveState.
void restoreState (size_t lenstate, const doublereal *state)
Restore the state of the phase from a previously saved state vector.
doublereal molecularWeight (size_t k) const
Molecular weight of species k.
void getMolecularWeights (vector_fp &weights) const
Copy the vector of molecular weights into vector weights.
void getMolecularWeights (doublereal *weights) const
Copy the vector of molecular weights into array weights.
const vector_fp & molecularWeights () const
Return a const reference to the internal vector of molecular weights.
doublereal size (size_t k) const
This routine returns the size of species k.
doublereal charge (size_t k) const
Dimensionless electrical charge of a single molecule of species k The charge is normalized by the the magnitude of the electron charge.
doublereal chargeDensity () const
Charge density [C/m^3].
size_t nDim () const
Returns the number of spatial dimensions (1, 2, or 3)
void setNDim (size_t ndim)
Set the number of spatial dimensions (1, 2, or 3).
virtual void freezeSpecies ()
Call when finished adding species.
bool speciesFrozen ()
True if freezeSpecies has been called.
virtual bool ready () const
int stateMFNumber () const
Return the State Mole Fraction Number.
std::string id () const
Return the string id for the phase.
void setID (const std::string &id)
Set the string id for the phase.
std::string name () const
Return the name of the phase.
void setName (const std::string &nm)
Sets the string name for the phase.
std::string elementName (size_t m) const
Name of the element with index m.
size_t elementIndex (const std::string &name) const
Return the index of element named 'name'.
const std::vector< std::string > & elementNames () const
Return a read-only reference to the vector of element names.
doublereal atomicWeight (size_t m) const
Atomic weight of element m.
doublereal entropyElement298 (size_t m) const
Entropy of the element in its standard state at 298 K and 1 bar.
int atomicNumber (size_t m) const
Atomic number of element m.
int elementType (size_t m) const
Return the element constraint type Possible types include:
int changeElementType (int m, int elem_type)
Change the element type of the mth constraint Reassigns an element type.
const vector_fp & atomicWeights () const
Return a read-only reference to the vector of atomic weights.
size_t nElements () const
Number of elements.
void checkElementIndex (size_t m) const
Check that the specified element index is in range Throws an exception if m is greater than nElements()-1.
void checkElementArraySize (size_t mm) const
Check that an array size is at least nElements() Throws an exception if mm is less than nElements().
doublereal nAtoms (size_t k, size_t m) const
Number of atoms of element m in species k.
void getAtoms (size_t k, double *atomArray) const
Get a vector containing the atomic composition of species k.
size_t speciesIndex (const std::string &name) const
Returns the index of a species named 'name' within the Phase object.
std::string speciesName (size_t k) const
Name of the species with index k.
std::string speciesSPName (int k) const
Returns the expanded species name of a species, including the phase name This is guaranteed to be unique within a Cantera problem.
const std::vector< std::string > & speciesNames () const
Return a const reference to the vector of species names.
size_t nSpecies () const
Returns the number of species in the phase.
void checkSpeciesIndex (size_t k) const
Check that the specified species index is in range Throws an exception if k is greater than nSpecies()-1.
void checkSpeciesArraySize (size_t kk) const
Check that an array size is at least nSpecies() Throws an exception if kk is less than nSpecies().
void setMoleFractionsByName (compositionMap &xMap)
Set the species mole fractions by name.
void setMoleFractionsByName (const std::string &x)
Set the mole fractions of a group of species by name.
void setMassFractionsByName (compositionMap &yMap)
Set the species mass fractions by name.
void setMassFractionsByName (const std::string &x)
Set the species mass fractions by name.
void setState_TRX (doublereal t, doublereal dens, const doublereal *x)
Set the internally stored temperature (K), density, and mole fractions.
void setState_TRX (doublereal t, doublereal dens, compositionMap &x)
Set the internally stored temperature (K), density, and mole fractions.
void setState_TRY (doublereal t, doublereal dens, const doublereal *y)
Set the internally stored temperature (K), density, and mass fractions.
void setState_TRY (doublereal t, doublereal dens, compositionMap &y)
Set the internally stored temperature (K), density, and mass fractions.
void setState_TNX (doublereal t, doublereal n, const doublereal *x)
Set the internally stored temperature (K), molar density (kmol/m^3), and mole fractions.
void setState_TR (doublereal t, doublereal rho)
Set the internally stored temperature (K) and density (kg/m^3)
void setState_TX (doublereal t, doublereal *x)
Set the internally stored temperature (K) and mole fractions.
void setState_TY (doublereal t, doublereal *y)
Set the internally stored temperature (K) and mass fractions.
void setState_RX (doublereal rho, doublereal *x)
Set the density (kg/m^3) and mole fractions.
void setState_RY (doublereal rho, doublereal *y)
Set the density (kg/m^3) and mass fractions.
void getMoleFractionsByName (compositionMap &x) const
Get the mole fractions by name.
doublereal moleFraction (size_t k) const
Return the mole fraction of a single species.
doublereal moleFraction (const std::string &name) const
Return the mole fraction of a single species.
doublereal massFraction (size_t k) const
Return the mass fraction of a single species.
doublereal massFraction (const std::string &name) const
Return the mass fraction of a single species.
void getMoleFractions (doublereal *const x) const
Get the species mole fraction vector.
void getMassFractions (doublereal *const y) const
Get the species mass fractions.
const doublereal * massFractions () const
Return a const pointer to the mass fraction array.
void getConcentrations (doublereal *const c) const
Get the species concentrations (kmol/m^3).
doublereal concentration (const size_t k) const
Concentration of species k.
const doublereal * moleFractdivMMW () const
Returns a const pointer to the start of the moleFraction/MW array.
doublereal temperature () const
Temperature (K).
virtual doublereal density () const
Density (kg/m^3).
doublereal molarDensity () const
Molar density (kmol/m^3).
doublereal molarVolume () const
Molar volume (m^3/kmol).
virtual void setDensity (const doublereal density_)
Set the internally stored density (kg/m^3) of the phase Note the density of a phase is an independent variable.
virtual void setMolarDensity (const doublereal molarDensity)
Set the internally stored molar density (kmol/m^3) of the phase.
doublereal mean_X (const doublereal *const Q) const
Evaluate the mole-fraction-weighted mean of an array Q.
doublereal mean_Y (const doublereal *const Q) const
Evaluate the mass-fraction-weighted mean of an array Q.
doublereal meanMolecularWeight () const
The mean molecular weight. Units: (kg/kmol)
doublereal sum_xlogx () const
Evaluate \(\sum_k X_k \log X_k \).
doublereal sum_xlogQ (doublereal *const Q) const
Evaluate \(\sum_k X_k \log Q_k \).
void addElement (const std::string &symbol, doublereal weight=-12345.0)
Add an element.
void addElement (const XML_Node &e)
Add an element from an XML specification.
void addUniqueElement (const std::string &symbol, doublereal weight=-12345.0, int atomicNumber=0, doublereal entropy298=ENTROPY298_UNKNOWN, int elem_type=CT_ELEM_TYPE_ABSPOS)
Add an element, checking for uniqueness The uniqueness is checked by comparing the string symbol.
void addUniqueElement (const XML_Node &e)
Add an element, checking for uniqueness The uniqueness is checked by comparing the string symbol.
void addElementsFromXML (const XML_Node &phase)
Add all elements referenced in an XML_Node tree.
void freezeElements ()
Prohibit addition of more elements, and prepare to add species.
bool elementsFrozen ()
True if freezeElements has been called.
size_t addUniqueElementAfterFreeze (const std::string &symbol, doublereal weight, int atomicNumber, doublereal entropy298=ENTROPY298_UNKNOWN, int elem_type=CT_ELEM_TYPE_ABSPOS)
Add an element after elements have been frozen, checking for uniqueness The uniqueness is checked by comparing the string symbol.
void addSpecies (const std::string &name, const doublereal *comp, doublereal charge=0.0, doublereal size=1.0)
void addUniqueSpecies (const std::string &name, const doublereal *comp, doublereal charge=0.0, doublereal size=1.0)
Add a species to the phase, checking for uniqueness of the name This routine checks for uniqueness of the string name.
Public Attributes
ThermoPhase * neutralMoleculePhase_
This is a pointer to the neutral Molecule Phase.
Protected Attributes
IonSolnType_enumType ionSolnType_
Ion solution type.
size_t numNeutralMoleculeSpecies_
Number of neutral molecule species.
size_t indexSpecialSpecies_
Index of special species.
size_t indexSecondSpecialSpecies_
Index of special species.
std::vector< double > fm_neutralMolec_ions_
Formula Matrix for composition of neutral molecules in terms of the molecules in this ThermoPhase.
std::vector< size_t > fm_invert_ionForNeutral
Mapping between ion species and neutral molecule for quick invert.
std::vector< doublereal > NeutralMolecMoleFractions_
Mole fractions using the Neutral Molecule Mole fraction basis.
std::vector< size_t > cationList_
List of the species in this ThermoPhase which are cation species.
int numCationSpecies_
Number of cation species.
std::vector< size_t > anionList_
List of the species in this ThermoPhase which are anion species.
int numAnionSpecies_
Number of anion species.
std::vector< size_t > passThroughList_
List of the species in this ThermoPhase which are passed through to the neutralMoleculePhase ThermoPhase.
size_t numPassThroughSpecies_
Number of the species in this ThermoPhase which are passed through to the neutralMoleculePhase ThermoPhase.
Protected Attributes inherited from GibbsExcessVPSSTP
std::vector< doublereal > moleFractions_
Storage for the current values of the mole fractions of the species.
std::vector< doublereal > lnActCoeff_Scaled_
Storage for the current values of the activity coefficients of the species.
std::vector< doublereal > dlnActCoeffdT_Scaled_
Storage for the current derivative values of the gradients with respect to temperature of the log of the activity coefficients of the species.
std::vector< doublereal > d2lnActCoeffdT2_Scaled_
Storage for the current derivative values of the gradients with respect to temperature of the log of the activity coefficients of the species.
std::vector< doublereal > dlnActCoeffdlnN_diag_
Storage for the current derivative values of the gradients with respect to logarithm of the mole fraction of the log of the activity coefficients of the species.
std::vector< doublereal > dlnActCoeffdlnX_diag_
Storage for the current derivative values of the gradients with respect to logarithm of the mole fraction of the log of the activity coefficients of the species.
Array2D dlnActCoeffdlnN_
Storage for the current derivative values of the gradients with respect to logarithm of the species mole number of the log of the activity coefficients of the species.
std::vector< doublereal > m_pp
Temporary storage space that is fair game.
Protected Attributes inherited from VPStandardStateTP
doublereal m_Pcurrent
Current value of the pressure - state variable.
doublereal m_Tlast_ss
The last temperature at which the standard statethermodynamic properties were calculated at.
doublereal m_Plast_ss
The last pressure at which the Standard State thermodynamic properties were calculated at.
doublereal m_P0
VPSSMgr * m_VPSS_ptr
Pointer to the VPSS manager that calculates all of the standard state info efficiently.
std::vector< PDSS * > m_PDSS_storage
Storage for the PDSS objects for the species.
Protected Attributes inherited from ThermoPhase
SpeciesThermo * m_spthermo
Pointer to the calculation manager for species reference-state thermodynamic properties.
std::vector< const XML_Node * > m_speciesData
Vector of pointers to the species databases.
doublereal m_phi
Stored value of the electric potential for this phase.
vector_fp m_lambdaRRT
Vector of element potentials.
bool m_hasElementPotentials
Boolean indicating whether there is a valid set of saved element potentials for this phase.
bool m_chargeNeutralityNecessary
Boolean indicating whether a charge neutrality condition is a necessity.
int m_ssConvention
Contains the standard state convention.
std::vector< doublereal > xMol_Ref
Reference Mole Fraction Composition.
Protected Attributes inherited from Phase
size_t m_kk
Number of species in the phase.
size_t m_ndim
Dimensionality of the phase.
vector_fp m_speciesComp
Atomic composition of the species.
vector_fp m_speciesSize
Vector of species sizes.
vector_fp m_speciesCharge
Vector of species charges. length m_kk.
Private Member Functions
void initLengths ()
Initialize lengths of local variables after all species have been identified.
void s_update_lnActCoeff () const
Update the activity coefficients.
void s_update_dlnActCoeffdT () const
Update the temperature derivative of the ln activity coefficients.
void s_update_dlnActCoeff () const
Update the change in the ln activity coefficients.
void s_update_dlnActCoeff_dlnX_diag () const
Update the derivative of the log of the activity coefficients wrt log(mole fraction)
void s_update_dlnActCoeff_dlnN_diag () const
Update the derivative of the log of the activity coefficients wrt log(number of moles) - diagonal components.
void s_update_dlnActCoeff_dlnN () const
Update the derivative of the log of the activity coefficients wrt log(number of moles) - diagonal components.
doublereal err (const std::string &msg) const
Error function.
Private Attributes
GibbsExcessVPSSTP * geThermo
vector_fp y_
vector_fp dlnActCoeff_NeutralMolecule_
vector_fp dX_NeutralMolecule_
bool IOwnNThermoPhase_
If true then we own the underlying neutral Molecule Phase.
std::vector< doublereal > moleFractionsTmp_
Temporary mole fraction vector.
std::vector< doublereal > muNeutralMolecule_
Storage vector for the neutral molecule chemical potentials.
std::vector< doublereal > lnActCoeff_NeutralMolecule_
Storage vector for the neutral molecule ln activity coefficients.
std::vector< doublereal > dlnActCoeffdT_NeutralMolecule_
Storage vector for the neutral molecule d ln activity coefficients dT.
std::vector< doublereal > dlnActCoeffdlnX_diag_NeutralMolecule_
Storage vector for the neutral molecule d ln activity coefficients dX - diagonal component.
std::vector< doublereal > dlnActCoeffdlnN_diag_NeutralMolecule_
Storage vector for the neutral molecule d ln activity coefficients dlnN - diagonal component.
Array2D dlnActCoeffdlnN_NeutralMolecule_
Storage vector for the neutral molecule d ln activity coefficients dlnN.
Additional Inherited Members
Protected Member Functions inherited from GibbsExcessVPSSTP
double checkMFSum (const doublereal *const x) const
utility routine to check mole fraction sum
void calcDensity ()
Calculate the density of the mixture using the partial molar volumes and mole fractions as input.
Protected Member Functions inherited from VPStandardStateTP
virtual void _updateStandardStateThermo () const
Updates the standard state thermodynamic functions at the current T and P of the solution.
const vector_fp & Gibbs_RT_ref () const
Protected Member Functions inherited from ThermoPhase
virtual void getCsvReportData (std::vector< std::string > &names, std::vector< vector_fp > &data) const
Fills names and data with the column names and species thermo properties to be included in the output of the reportCSV method.
Protected Member Functions inherited from Phase
void init (const vector_fp &mw)
void setMolecularWeight (const int k, const double mw)
Set the molecular weight of a single species to a given value.
Detailed Description
The IonsFromNeutralVPSSTP is a derived class of ThermoPhase that handles the specification of the chemical potentials for ionic species, given a specification of the chemical potentials for the same phase expressed in terms of combinations of the ionic species that represent neutral molecules. It's expected that the neutral molecules will be represented in terms of an excess gibbs free energy approximation that is a derivative of the GbbsExcessVPSSTP object. All of the e Excess Gibbs free energy formulations in this area employ symmetrical formulations.
This class is used for molten salts.
This object actually employs 4 different mole fraction types.
There is a mole fraction associated the the cations and anions and neutrals from this ThermoPhase object. This is the normal mole fraction vector for this object. Note, however, it isn't the appropriate mole fraction vector to use even for obtaining the correct ideal free energies of mixing.
There is a mole fraction vector associated with the neutral molecule ThermoPhase object.
There is a mole fraction vector associated with the cation lattice.
There is a mole fraction vector associated with the anion lattice
This object can translate between any of the four mole fraction representations.
Definition at line 72 of file IonsFromNeutralVPSSTP.h.
Constructor & Destructor Documentation
IonsFromNeutralVPSSTP ()
Default constructor
Definition at line 31 of file IonsFromNeutralVPSSTP.cpp.
Referenced by IonsFromNeutralVPSSTP::duplMyselfAsThermoPhase().
IonsFromNeutralVPSSTP (const std::string & inputFile, const std::string & id = "", ThermoPhase * neutralPhase = 0)
Construct and initialize an IonsFromNeutralVPSSTP object directly from an ASCII input file.
This constructor is a shell around the routine initThermo(), with a reference to the XML database to get the info for the phase.
Parameters
inputFile Name of the input file containing the phase XML data to set up the object
id ID of the phase in the input file. Defaults to the empty string.
neutralPhase The object takes a neutralPhase ThermoPhase object as input. It can either take a pointer to an existing object in the parameter list, in which case it does not own the object, or it can construct a neutral Phase as a slave object, in which case, it does own the slave object, for purposes of who gets to destroy the object. If this parameter is zero, then a slave neutral phase object is created and used.
Definition at line 49 of file IonsFromNeutralVPSSTP.cpp.
References IonsFromNeutralVPSSTP::constructPhaseFile(), IonsFromNeutralVPSSTP::IOwnNThermoPhase_, and IonsFromNeutralVPSSTP::neutralMoleculePhase_.
IonsFromNeutralVPSSTP (XML_Node & phaseRoot, const std::string & id = "", ThermoPhase * neutralPhase = 0)
Construct and initialize an IonsFromNeutralVPSSTP object directly from an XML database.
Parameters
phaseRoot XML phase node containing the description of the phase
id id attribute containing the name of the phase. (default is the empty string)
neutralPhase The object takes a neutralPhase ThermoPhase object as input. It can either take a pointer to an existing object in the parameter list, in which case it does not own the object, or it can construct a neutral Phase as a slave object, in which case, it does own the slave object, for purposes of who gets to destroy the object. If this parameter is zero, then a slave neutral phase object is created and used.
Definition at line 77 of file IonsFromNeutralVPSSTP.cpp.
References IonsFromNeutralVPSSTP::constructPhaseXML(), IonsFromNeutralVPSSTP::IOwnNThermoPhase_, IonsFromNeutralVPSSTP::neutralMoleculePhase_, Phase::nSpecies(), and IonsFromNeutralVPSSTP::numNeutralMoleculeSpecies_.
IonsFromNeutralVPSSTP (const IonsFromNeutralVPSSTP & b)
Copy constructor.
Parameters
b class to be copied
Definition at line 105 of file IonsFromNeutralVPSSTP.cpp.
References IonsFromNeutralVPSSTP::operator=().
~IonsFromNeutralVPSSTP () virtual
Destructor.
Definition at line 185 of file IonsFromNeutralVPSSTP.cpp.
References IonsFromNeutralVPSSTP::IOwnNThermoPhase_, and IonsFromNeutralVPSSTP::neutralMoleculePhase_.
Member Function Documentation
IonsFromNeutralVPSSTP & operator= (const IonsFromNeutralVPSSTP & b)
Assignment operator.
Parameters
b class to be copied.
Definition at line 126 of file IonsFromNeutralVPSSTP.cpp.
References IonsFromNeutralVPSSTP::anionList_, IonsFromNeutralVPSSTP::cationList_, IonsFromNeutralVPSSTP::dlnActCoeffdlnN_diag_NeutralMolecule_, IonsFromNeutralVPSSTP::dlnActCoeffdlnN_NeutralMolecule_, IonsFromNeutralVPSSTP::dlnActCoeffdlnX_diag_NeutralMolecule_, IonsFromNeutralVPSSTP::dlnActCoeffdT_NeutralMolecule_, IonsFromNeutralVPSSTP::duplMyselfAsThermoPhase(), IonsFromNeutralVPSSTP::fm_invert_ionForNeutral, IonsFromNeutralVPSSTP::fm_neutralMolec_ions_, IonsFromNeutralVPSSTP::indexSecondSpecialSpecies_, IonsFromNeutralVPSSTP::indexSpecialSpecies_, IonsFromNeutralVPSSTP::ionSolnType_, IonsFromNeutralVPSSTP::IOwnNThermoPhase_, IonsFromNeutralVPSSTP::lnActCoeff_NeutralMolecule_, IonsFromNeutralVPSSTP::moleFractionsTmp_, IonsFromNeutralVPSSTP::muNeutralMolecule_, IonsFromNeutralVPSSTP::NeutralMolecMoleFractions_, IonsFromNeutralVPSSTP::neutralMoleculePhase_, IonsFromNeutralVPSSTP::numAnionSpecies_, IonsFromNeutralVPSSTP::numCationSpecies_, IonsFromNeutralVPSSTP::numNeutralMoleculeSpecies_, IonsFromNeutralVPSSTP::numPassThroughSpecies_, GibbsExcessVPSSTP::operator=(), and IonsFromNeutralVPSSTP::passThroughList_.
Referenced by IonsFromNeutralVPSSTP::IonsFromNeutralVPSSTP().
ThermoPhase * duplMyselfAsThermoPhase () const virtual
Duplication routine for objects which inherit from ThermoPhase.
This virtual routine can be used to duplicate ThermoPhase objects inherited from ThermoPhase even if the application only has a pointer to ThermoPhase to work with.
Reimplemented from GibbsExcessVPSSTP.
Definition at line 194 of file IonsFromNeutralVPSSTP.cpp.
References IonsFromNeutralVPSSTP::IonsFromNeutralVPSSTP().
Referenced by IonsFromNeutralVPSSTP::operator=().
void constructPhaseFile (std::string inputFile, std::string id)
The following methods are used in the process of constructing the phase and setting its parameters from a specification in an input file.
Initialization of an IonsFromNeutralVPSSTP phase using an xml file
This routine is a precursor to initThermo(XML_Node*) routine, which does most of the work.
Parameters
inputFile XML file containing the description of the phase
id Optional parameter identifying the name of the phase. If none is given, the first XML phase element will be used.
Definition at line 199 of file IonsFromNeutralVPSSTP.cpp.
References XML_Node::build(), IonsFromNeutralVPSSTP::constructPhaseXML(), XML_Node::copy(), Cantera::findInputFile(), Cantera::findXMLPhase(), and Phase::xml().
Referenced by IonsFromNeutralVPSSTP::IonsFromNeutralVPSSTP().
void constructPhaseXML (XML_Node & phaseNode, std::string id)
Import and initialize an IonsFromNeutralVPSSTP phase specification in an XML tree into the current object.
Here we read an XML description of the phase. We import descriptions of the elements that make up the species in a phase. We import information about the species, including their reference state thermodynamic polynomials. We then freeze the state of the species.
Then, we read the species molar volumes from the xml tree to finish the initialization.
Parameters
phaseNode This object must be the phase node of a complete XML tree description of the phase, including all of the species data. In other words while "phase" must point to an XML phase object, it must have sibling nodes "speciesData" that describe the species in the phase.
id ID of the phase. If nonnull, a check is done to see if phaseNode is pointing to the phase with the correct id.
Definition at line 230 of file IonsFromNeutralVPSSTP.cpp.
References XML_Node::attrib(), XML_Node::child(), Cantera::get_XML_Node(), XML_Node::hasChild(), XML_Node::id(), Cantera::importPhase(), Cantera::lowercase(), IonsFromNeutralVPSSTP::neutralMoleculePhase_, and Cantera::newPhase().
Referenced by IonsFromNeutralVPSSTP::constructPhaseFile(), IonsFromNeutralVPSSTP::IonsFromNeutralVPSSTP(), and Cantera::newPhase().
int eosType () const virtual
Equation of state type flag.
The ThermoPhase base class returns zero. Subclasses should define this to return a unique non-zero value. Known constants defined for this purpose are listed in mix_defs.h. The MolalityVPSSTP class also returns zero, as it is a non-complete class.
Reimplemented from GibbsExcessVPSSTP.
Definition at line 302 of file IonsFromNeutralVPSSTP.cpp.
Referenced by IonsFromNeutralVPSSTP::err().
doublereal enthalpy_mole () const virtual
Return the Molar enthalpy. Units: J/kmol.
This is calculated from the partial molar enthalpies of the species.
Reimplemented from ThermoPhase.
Definition at line 311 of file IonsFromNeutralVPSSTP.cpp.
References DATA_PTR, IonsFromNeutralVPSSTP::getPartialMolarEnthalpies(), GibbsExcessVPSSTP::m_pp, and Phase::mean_X().
Referenced by IonsFromNeutralVPSSTP::intEnergy_mole().
doublereal intEnergy_mole () const virtual
Molar internal energy.
J/kmol.
This is calculated from the soln enthalpy and then subtracting pV.
Reimplemented from ThermoPhase.
Definition at line 317 of file IonsFromNeutralVPSSTP.cpp.
References IonsFromNeutralVPSSTP::enthalpy_mole(), Phase::molarDensity(), and VPStandardStateTP::pressure().
doublereal entropy_mole () const virtual
Molar entropy. Units: J/kmol/K.
Reimplemented from ThermoPhase.
Definition at line 325 of file IonsFromNeutralVPSSTP.cpp.
References DATA_PTR, IonsFromNeutralVPSSTP::getPartialMolarEntropies(), GibbsExcessVPSSTP::m_pp, and Phase::mean_X().
doublereal gibbs_mole () const virtual
Molar Gibbs free Energy for an ideal gas. Units = J/kmol.
Reimplemented from ThermoPhase.
Definition at line 331 of file IonsFromNeutralVPSSTP.cpp.
References DATA_PTR, IonsFromNeutralVPSSTP::getChemPotentials(), GibbsExcessVPSSTP::m_pp, and Phase::mean_X().
doublereal cp_mole () const virtual
Molar heat capacity at constant pressure. Units: J/kmol/K.
Reimplemented from ThermoPhase.
Definition at line 337 of file IonsFromNeutralVPSSTP.cpp.
References DATA_PTR, ThermoPhase::getPartialMolarCp(), GibbsExcessVPSSTP::m_pp, and Phase::mean_X().
doublereal cv_mole () const virtual
Molar heat capacity at constant volume. Units: J/kmol/K.
Reimplemented from ThermoPhase.
Definition at line 343 of file IonsFromNeutralVPSSTP.cpp.
References DATA_PTR, ThermoPhase::getPartialMolarCp(), GibbsExcessVPSSTP::m_pp, and Phase::mean_X().
void getActivityCoefficients (doublereal * ac) const virtual
Get the array of non-dimensional molar-based activity coefficients at the current solution temperature, pressure, and solution concentration.
Parameters
ac Output vector of activity coefficients. Length: m_kk.
Reimplemented from GibbsExcessVPSSTP.
Definition at line 364 of file IonsFromNeutralVPSSTP.cpp.
References GibbsExcessVPSSTP::lnActCoeff_Scaled_, Phase::m_kk, and IonsFromNeutralVPSSTP::s_update_lnActCoeff().
void getChemPotentials (doublereal * mu) const virtual
Get the species chemical potentials. Units: J/kmol.
This function returns a vector of chemical potentials of the species in solution at the current temperature, pressure and mole fraction of the solution.
Parameters
mu Output vector of species chemical potentials. Length: m_kk. Units: J/kmol
Reimplemented from ThermoPhase.
Definition at line 389 of file IonsFromNeutralVPSSTP.cpp.
References IonsFromNeutralVPSSTP::anionList_, IonsFromNeutralVPSSTP::cationList_, DATA_PTR, IonsFromNeutralVPSSTP::fm_invert_ionForNeutral, Cantera::GasConstant, ThermoPhase::getChemPotentials(), ThermoPhase::getLnActivityCoefficients(), ThermoPhase::getStandardChemPotentials(), IonsFromNeutralVPSSTP::ionSolnType_, IonsFromNeutralVPSSTP::lnActCoeff_NeutralMolecule_, GibbsExcessVPSSTP::moleFractions_, IonsFromNeutralVPSSTP::muNeutralMolecule_, IonsFromNeutralVPSSTP::neutralMoleculePhase_, IonsFromNeutralVPSSTP::numPassThroughSpecies_, IonsFromNeutralVPSSTP::passThroughList_, Cantera::SmallNumber, and Phase::temperature().
Referenced by IonsFromNeutralVPSSTP::gibbs_mole().
void getPartialMolarEnthalpies (doublereal * hbar) const virtual
Returns an array of partial molar enthalpies for the species in the mixture.
Units (J/kmol)
For this phase, the partial molar enthalpies are equal to the standard state enthalpies modified by the derivative of the molality-based activity coefficient wrt temperature
\[ \bar h_k(T,P) = h^o_k(T,P) - R T^2 \frac{d \ln(\gamma_k)}{dT} \]
Parameters
hbar Output vector of species partial molar enthalpies. Length: m_kk. Units: J/kmol
Reimplemented from ThermoPhase.
Definition at line 454 of file IonsFromNeutralVPSSTP.cpp.
References GibbsExcessVPSSTP::dlnActCoeffdT_Scaled_, Cantera::GasConstant, VPStandardStateTP::getEnthalpy_RT(), Phase::m_kk, IonsFromNeutralVPSSTP::s_update_dlnActCoeffdT(), IonsFromNeutralVPSSTP::s_update_lnActCoeff(), and Phase::temperature().
Referenced by IonsFromNeutralVPSSTP::enthalpy_mole().
void getPartialMolarEntropies (doublereal * sbar) const virtual
Returns an array of partial molar entropies for the species in the mixture.
Units (J/kmol)
For this phase, the partial molar enthalpies are equal to the standard state enthalpies modified by the derivative of the activity coefficient wrt temperature
\[ \bar s_k(T,P) = s^o_k(T,P) - R T^2 \frac{d \ln(\gamma_k)}{dT} - R \ln(\gamma_k X_k) - R T \frac{d \ln(\gamma_k) }{dT} \]
Parameters
sbar Output vector of species partial molar entropies. Length: m_kk. Units: J/kmol/K
Reimplemented from ThermoPhase.
Definition at line 480 of file IonsFromNeutralVPSSTP.cpp.
References GibbsExcessVPSSTP::dlnActCoeffdT_Scaled_, Cantera::GasConstant, VPStandardStateTP::getEntropy_R(), GibbsExcessVPSSTP::lnActCoeff_Scaled_, Phase::m_kk, GibbsExcessVPSSTP::moleFractions_, IonsFromNeutralVPSSTP::s_update_dlnActCoeffdT(), IonsFromNeutralVPSSTP::s_update_lnActCoeff(), Cantera::SmallNumber, and Phase::temperature().
Referenced by IonsFromNeutralVPSSTP::entropy_mole().
void getdlnActCoeffds (const doublereal dTds, const doublereal *const dXds, doublereal * dlnActCoeffds) const virtual
Get the change in activity coefficients w.r.t.
change in state (temp, mole fraction, etc.) along a line in parameter space or along a line in physical space
Parameters
dTds Input of temperature change along the path
dXds Input vector of changes in mole fraction along the path. length = m_kk Along the path length it must be the case that the mole fractions sum to one.
dlnActCoeffds Output vector of the directional derivatives of the log Activity Coefficients along the path. length = m_kk
Reimplemented from ThermoPhase.
Definition at line 1181 of file IonsFromNeutralVPSSTP.cpp.
References IonsFromNeutralVPSSTP::anionList_, IonsFromNeutralVPSSTP::cationList_, DATA_PTR, IonsFromNeutralVPSSTP::fm_invert_ionForNeutral, IonsFromNeutralVPSSTP::fm_neutralMolec_ions_, ThermoPhase::getdlnActCoeffds(), IonsFromNeutralVPSSTP::getNeutralMoleculeMoleGrads(), IonsFromNeutralVPSSTP::ionSolnType_, Phase::m_kk, GibbsExcessVPSSTP::moleFractions_, IonsFromNeutralVPSSTP::numPassThroughSpecies_, and IonsFromNeutralVPSSTP::passThroughList_.
void getdlnActCoeffdlnX_diag (doublereal * dlnActCoeffdlnX_diag) const virtual
Get the array of log concentration-like derivatives of the log activity coefficients - diagonal component.
For ideal mixtures (unity activity coefficients), this can return zero. Implementations should take the derivative of the logarithm of the activity coefficient with respect to the logarithm of the mole fraction. This quantity is to be used in conjunction with derivatives of that concentration-like variable when the derivative of the chemical potential is taken.
units = dimensionless
Parameters
dlnActCoeffdlnX_diag Output vector of log(mole fraction) derivatives of the log Activity Coefficients. length = m_kk
Reimplemented from ThermoPhase.
Definition at line 507 of file IonsFromNeutralVPSSTP.cpp.
References GibbsExcessVPSSTP::dlnActCoeffdlnX_diag_, Phase::m_kk, IonsFromNeutralVPSSTP::s_update_dlnActCoeff_dlnX_diag(), and IonsFromNeutralVPSSTP::s_update_lnActCoeff().
void getdlnActCoeffdlnN_diag (doublereal * dlnActCoeffdlnN_diag) const virtual
Get the array of log concentration-like derivatives of the log activity coefficients - diagonal components.
For ideal mixtures (unity activity coefficients), this can return zero. Implementations should take the derivative of the logarithm of the activity coefficient with respect to the logarithm of the species mole numbe. This routine just does the diagonal entries.
units = dimensionless
Parameters
dlnActCoeffdlnN_diag Output vector of diagonal components of the log(mole fraction) derivatives of the log Activity Coefficients. length = m_kk
Reimplemented from VPStandardStateTP.
Definition at line 517 of file IonsFromNeutralVPSSTP.cpp.
References GibbsExcessVPSSTP::dlnActCoeffdlnN_diag_, Phase::m_kk, IonsFromNeutralVPSSTP::s_update_dlnActCoeff_dlnN_diag(), and IonsFromNeutralVPSSTP::s_update_lnActCoeff().
void getdlnActCoeffdlnN (const size_t ld, doublereal *const dlnActCoeffdlnN) virtual
Get the array of derivatives of the ln activity coefficients with respect to the ln species mole numbers.
Implementations should take the derivative of the logarithm of the activity coefficient with respect to a log of a species mole number (with all other species mole numbers held constant)
units = 1 / kmol
dlnActCoeffdlnN[ ld * k + m] will contain the derivative of log act_coeff for the mth species with respect to the number of moles of the kth species.
\[ \frac{d \ln(\gamma_m) }{d \ln(n_k) }\Bigg|_{n_i} \]
Parameters
ld Number of rows in the matrix
dlnActCoeffdlnN Output vector of derivatives of the log Activity Coefficients. length = m_kk * m_kk
Reimplemented from GibbsExcessVPSSTP.
Definition at line 527 of file IonsFromNeutralVPSSTP.cpp.
References GibbsExcessVPSSTP::dlnActCoeffdlnN_, Phase::m_kk, IonsFromNeutralVPSSTP::s_update_dlnActCoeff_dlnN(), and IonsFromNeutralVPSSTP::s_update_lnActCoeff().
void getDissociationCoeffs (vector_fp & fm_neutralMolec_ions, vector_fp & charges, std::vector< size_t > & neutMolIndex) const
Get the Salt Dissociation Coefficients Returns the vector of dissociation coefficients and vector of charges.
Parameters
fm_neutralMolec_ions Returns the formula matrix for the composition of neutral molecules in terms of the ions.
charges Returns a vector containing the charges of all species in this phase
neutMolIndex Returns the vector fm_invert_ionForNeutral This is the mapping between ion species and neutral molecule for quick invert.
Definition at line 356 of file IonsFromNeutralVPSSTP.cpp.
References IonsFromNeutralVPSSTP::fm_invert_ionForNeutral, IonsFromNeutralVPSSTP::fm_neutralMolec_ions_, and Phase::m_speciesCharge.
Referenced by LTI_StefanMaxwell_PPN::getMatrixTransProp().
void getNeutralMolecMoleFractions (vector_fp & neutralMoleculeMoleFractions) const inline
Return the current value of the neutral mole fraction vector.
Parameters
neutralMoleculeMoleFractions Vector of neutral molecule mole fractions.
Definition at line 398 of file IonsFromNeutralVPSSTP.h.
References IonsFromNeutralVPSSTP::NeutralMolecMoleFractions_.
Referenced by LTI_StefanMaxwell_PPN::getMatrixTransProp().
void getNeutralMoleculeMoleGrads (const doublereal *const dx, doublereal *const dy) const
Calculate neutral molecule mole fractions.
This routine calculates the neutral molecule mole fraction given the vector of ion mole fractions, i.e., the mole fractions from this ThermoPhase. Note, this routine basically assumes that there is charge neutrality. If there isn't, then it wouldn't make much sense.
for the case of cIonSolnType_SINGLEANION, some slough in the charge neutrality is allowed. The cation number is followed, while the difference in charge neutrality is dumped into the anion mole number to fix the imbalance.
Parameters
dx input vector of ion mole fraction gradients
dy output Vector of neutral molecule mole fraction gradients
Definition at line 715 of file IonsFromNeutralVPSSTP.cpp.
References IonsFromNeutralVPSSTP::anionList_, AssertTrace, IonsFromNeutralVPSSTP::cationList_, IonsFromNeutralVPSSTP::fm_invert_ionForNeutral, IonsFromNeutralVPSSTP::fm_neutralMolec_ions_, IonsFromNeutralVPSSTP::ionSolnType_, Phase::m_kk, GibbsExcessVPSSTP::moleFractions_, IonsFromNeutralVPSSTP::moleFractionsTmp_, Cantera::npos, IonsFromNeutralVPSSTP::numNeutralMoleculeSpecies_, IonsFromNeutralVPSSTP::numPassThroughSpecies_, and IonsFromNeutralVPSSTP::passThroughList_.
Referenced by IonsFromNeutralVPSSTP::getdlnActCoeffds().
void getCationList (std::vector< size_t > & cation) const inline
Get the list of cations in this object.
Parameters
cation List of cations
Definition at line 425 of file IonsFromNeutralVPSSTP.h.
References IonsFromNeutralVPSSTP::cationList_.
Referenced by LTI_StefanMaxwell_PPN::getMatrixTransProp().
void getAnionList (std::vector< size_t > & anion) const inline
Get the list of anions in this object.
Parameters
anion List of anions
Definition at line 433 of file IonsFromNeutralVPSSTP.h.
References IonsFromNeutralVPSSTP::anionList_.
Referenced by LTI_StefanMaxwell_PPN::getMatrixTransProp().
void setTemperature (const doublereal temp) virtual
Set the temperature of the phase.
Currently this passes down to setState_TP(). It does not make sense to calculate the standard state without first setting T and P.
Parameters
temp Temperature (kelvin)
Reimplemented from VPStandardStateTP.
Definition at line 539 of file IonsFromNeutralVPSSTP.cpp.
References VPStandardStateTP::pressure(), and IonsFromNeutralVPSSTP::setState_TP().
void setPressure (doublereal p) virtual
Set the internally stored pressure (Pa) at constant temperature and composition.
This method sets the pressure within the object. The water model is a completely compressible model. Also, the dielectric constant is pressure dependent.
Parameters
p input Pressure (Pa)
Todo:
Implement a variable pressure capability
Reimplemented from GibbsExcessVPSSTP.
Definition at line 545 of file IonsFromNeutralVPSSTP.cpp.
References IonsFromNeutralVPSSTP::setState_TP(), and Phase::temperature().
void setState_TP (doublereal t, doublereal p) virtual
Set the temperature (K) and pressure (Pa)
Setting the pressure may involve the solution of a nonlinear equation.
Parameters
t Temperature (K)
p Pressure (Pa)
Reimplemented from GibbsExcessVPSSTP.
Definition at line 551 of file IonsFromNeutralVPSSTP.cpp.
References Phase::density(), IonsFromNeutralVPSSTP::neutralMoleculePhase_, Phase::setDensity(), VPStandardStateTP::setState_TP(), and ThermoPhase::setState_TP().
Referenced by IonsFromNeutralVPSSTP::setPressure(), and IonsFromNeutralVPSSTP::setTemperature().
void calcIonMoleFractions (doublereal *const mf) const virtual
Calculate ion mole fractions from neutral molecule mole fractions.
Parameters
mf Dump the mole fractions into this vector.
Definition at line 569 of file IonsFromNeutralVPSSTP.cpp.
References DATA_PTR, IonsFromNeutralVPSSTP::fm_neutralMolec_ions_, Phase::getMoleFractions(), Phase::m_kk, IonsFromNeutralVPSSTP::NeutralMolecMoleFractions_, IonsFromNeutralVPSSTP::neutralMoleculePhase_, and IonsFromNeutralVPSSTP::numNeutralMoleculeSpecies_.
void calcNeutralMoleculeMoleFractions () const virtual
Calculate neutral molecule mole fractions.
This routine calculates the neutral molecule mole fraction given the vector of ion mole fractions, i.e., the mole fractions from this ThermoPhase. Note, this routine basically assumes that there is charge neutrality. If there isn't, then it wouldn't make much sense.
for the case of cIonSolnType_SINGLEANION, some slough in the charge neutrality is allowed. The cation number is followed, while the difference in charge neutrality is dumped into the anion mole number to fix the imbalance.
Definition at line 606 of file IonsFromNeutralVPSSTP.cpp.
References IonsFromNeutralVPSSTP::anionList_, AssertTrace, IonsFromNeutralVPSSTP::cationList_, IonsFromNeutralVPSSTP::fm_invert_ionForNeutral, IonsFromNeutralVPSSTP::fm_neutralMolec_ions_, Cantera::fp2str(), IonsFromNeutralVPSSTP::ionSolnType_, Phase::m_kk, GibbsExcessVPSSTP::moleFractions_, IonsFromNeutralVPSSTP::moleFractionsTmp_, IonsFromNeutralVPSSTP::NeutralMolecMoleFractions_, Cantera::npos, IonsFromNeutralVPSSTP::numNeutralMoleculeSpecies_, IonsFromNeutralVPSSTP::numPassThroughSpecies_, and IonsFromNeutralVPSSTP::passThroughList_.
Referenced by IonsFromNeutralVPSSTP::setConcentrations(), IonsFromNeutralVPSSTP::setMassFractions(), IonsFromNeutralVPSSTP::setMassFractions_NoNorm(), IonsFromNeutralVPSSTP::setMoleFractions(), and IonsFromNeutralVPSSTP::setMoleFractions_NoNorm().
void setMassFractions (const doublereal *const y) virtual
Set the mass fractions to the specified values, and then normalize them so that they sum to 1.0.
Parameters
y Array of unnormalized mass fraction values (input). Must have a length greater than or equal to the number of species.
y Input vector of mass fractions. Length is m_kk.
Reimplemented from GibbsExcessVPSSTP.
Definition at line 819 of file IonsFromNeutralVPSSTP.cpp.
References IonsFromNeutralVPSSTP::calcNeutralMoleculeMoleFractions(), DATA_PTR, IonsFromNeutralVPSSTP::NeutralMolecMoleFractions_, IonsFromNeutralVPSSTP::neutralMoleculePhase_, GibbsExcessVPSSTP::setMassFractions(), and Phase::setMoleFractions().
void setMassFractions_NoNorm (const doublereal *const y) virtual
Set the mass fractions to the specified values without normalizing.
This is useful when the normalization condition is being handled by some other means, for example by a constraint equation as part of a larger set of equations.
Parameters
y Input vector of mass fractions. Length is m_kk.
Reimplemented from GibbsExcessVPSSTP.
Definition at line 826 of file IonsFromNeutralVPSSTP.cpp.
References IonsFromNeutralVPSSTP::calcNeutralMoleculeMoleFractions(), DATA_PTR, IonsFromNeutralVPSSTP::NeutralMolecMoleFractions_, IonsFromNeutralVPSSTP::neutralMoleculePhase_, GibbsExcessVPSSTP::setMassFractions_NoNorm(), and Phase::setMoleFractions().
void setMoleFractions (const doublereal *const x) virtual
Set the mole fractions to the specified values, and then normalize them so that they sum to 1.0.
Parameters
x Array of unnormalized mole fraction values (input). Must have a length greater than or equal to the number of species.
x Input vector of mole fractions. Length is m_kk.
Reimplemented from GibbsExcessVPSSTP.
Definition at line 833 of file IonsFromNeutralVPSSTP.cpp.
References IonsFromNeutralVPSSTP::calcNeutralMoleculeMoleFractions(), DATA_PTR, IonsFromNeutralVPSSTP::NeutralMolecMoleFractions_, IonsFromNeutralVPSSTP::neutralMoleculePhase_, GibbsExcessVPSSTP::setMoleFractions(), and Phase::setMoleFractions().
void setMoleFractions_NoNorm (const doublereal *const x) virtual
Set the mole fractions to the specified values without normalizing.
This is useful when the normalization condition is being handled by some other means, for example by a constraint equation as part of a larger set of equations.
Parameters
x Input vector of mole fractions. Length is m_kk.
Reimplemented from GibbsExcessVPSSTP.
Definition at line 840 of file IonsFromNeutralVPSSTP.cpp.
References IonsFromNeutralVPSSTP::calcNeutralMoleculeMoleFractions(), DATA_PTR, IonsFromNeutralVPSSTP::NeutralMolecMoleFractions_, IonsFromNeutralVPSSTP::neutralMoleculePhase_, GibbsExcessVPSSTP::setMoleFractions_NoNorm(), and Phase::setMoleFractions_NoNorm().
void setConcentrations (const doublereal *const c) virtual
Set the concentrations to the specified values within the phase.
Parameters
c The input vector to this routine is in dimensional units. For volumetric phases c[k] is the concentration of the kth species in kmol/m3. For surface phases, c[k] is the concentration in kmol/m2. The length of the vector is the number of species in the phase.
Reimplemented from GibbsExcessVPSSTP.
Definition at line 847 of file IonsFromNeutralVPSSTP.cpp.
References IonsFromNeutralVPSSTP::calcNeutralMoleculeMoleFractions(), DATA_PTR, IonsFromNeutralVPSSTP::NeutralMolecMoleFractions_, IonsFromNeutralVPSSTP::neutralMoleculePhase_, GibbsExcessVPSSTP::setConcentrations(), and Phase::setMoleFractions().
void initThermo () virtual
Initialize. This method is provided to allow subclasses to perform any initialization required after all species have been added. For example, it might be used to resize internal work arrays that must have an entry for each species. The base class implementation does nothing, and subclasses that do not require initialization do not need to overload this method. When importing a CTML phase description, this method is called just prior to returning from function importPhase.
See Also
importCTML.cpp
Reimplemented from GibbsExcessVPSSTP.
Definition at line 865 of file IonsFromNeutralVPSSTP.cpp.
References IonsFromNeutralVPSSTP::initLengths(), and GibbsExcessVPSSTP::initThermo().
void initThermoXML (XML_Node & phaseNode, const std::string & id) virtual
Import and initialize a ThermoPhase object.
Parameters
phaseNode This object must be the phase node of a complete XML tree description of the phase, including all of the species data. In other words while "phase" must point to an XML phase object, it must have sibling nodes "speciesData" that describe the species in the phase.
id ID of the phase. If nonnull, a check is done to see if phaseNode is pointing to the phase with the correct id.
Reimplemented from VPStandardStateTP.
Definition at line 930 of file IonsFromNeutralVPSSTP.cpp.
References IonsFromNeutralVPSSTP::anionList_, XML_Node::attrib(), IonsFromNeutralVPSSTP::cationList_, Phase::charge(), XML_Node::child(), Phase::elementNames(), Cantera::factorOverlap(), IonsFromNeutralVPSSTP::fm_invert_ionForNeutral, IonsFromNeutralVPSSTP::fm_neutralMolec_ions_, Cantera::get_XML_Node(), XML_Node::hasChild(), XML_Node::id(), IonsFromNeutralVPSSTP::indexSecondSpecialSpecies_, IonsFromNeutralVPSSTP::indexSpecialSpecies_, VPStandardStateTP::initThermoXML(), Cantera::lowercase(), Phase::m_kk, Phase::nAtoms(), Phase::nElements(), IonsFromNeutralVPSSTP::neutralMoleculePhase_, Cantera::newPhase(), Cantera::npos, IonsFromNeutralVPSSTP::numAnionSpecies_, IonsFromNeutralVPSSTP::numCationSpecies_, IonsFromNeutralVPSSTP::numNeutralMoleculeSpecies_, IonsFromNeutralVPSSTP::numPassThroughSpecies_, IonsFromNeutralVPSSTP::passThroughList_, and PDSS_IonsFromNeutral::specialSpecies_.
void initLengths () private
Initialize lengths of local variables after all species have been identified.
Definition at line 871 of file IonsFromNeutralVPSSTP.cpp.
References IonsFromNeutralVPSSTP::anionList_, IonsFromNeutralVPSSTP::cationList_, IonsFromNeutralVPSSTP::dlnActCoeffdlnN_diag_NeutralMolecule_, IonsFromNeutralVPSSTP::dlnActCoeffdlnN_NeutralMolecule_, IonsFromNeutralVPSSTP::dlnActCoeffdlnX_diag_NeutralMolecule_, IonsFromNeutralVPSSTP::dlnActCoeffdT_NeutralMolecule_, IonsFromNeutralVPSSTP::fm_invert_ionForNeutral, IonsFromNeutralVPSSTP::fm_neutralMolec_ions_, IonsFromNeutralVPSSTP::lnActCoeff_NeutralMolecule_, Phase::m_kk, GibbsExcessVPSSTP::moleFractions_, IonsFromNeutralVPSSTP::moleFractionsTmp_, IonsFromNeutralVPSSTP::muNeutralMolecule_, IonsFromNeutralVPSSTP::NeutralMolecMoleFractions_, IonsFromNeutralVPSSTP::neutralMoleculePhase_, Phase::nSpecies(), IonsFromNeutralVPSSTP::numNeutralMoleculeSpecies_, IonsFromNeutralVPSSTP::passThroughList_, and Array2D::resize().
Referenced by IonsFromNeutralVPSSTP::initThermo().
void s_update_lnActCoeff () const private
Update the activity coefficients.
This function will be called to update the internally stored natural logarithm of the activity coefficients
Definition at line 1132 of file IonsFromNeutralVPSSTP.cpp.
References IonsFromNeutralVPSSTP::anionList_, IonsFromNeutralVPSSTP::cationList_, DATA_PTR, IonsFromNeutralVPSSTP::fm_invert_ionForNeutral, IonsFromNeutralVPSSTP::fm_neutralMolec_ions_, ThermoPhase::getLnActivityCoefficients(), IonsFromNeutralVPSSTP::ionSolnType_, IonsFromNeutralVPSSTP::lnActCoeff_NeutralMolecule_, GibbsExcessVPSSTP::lnActCoeff_Scaled_, Phase::m_kk, IonsFromNeutralVPSSTP::neutralMoleculePhase_, IonsFromNeutralVPSSTP::numPassThroughSpecies_, and IonsFromNeutralVPSSTP::passThroughList_.
Referenced by IonsFromNeutralVPSSTP::getActivityCoefficients(), IonsFromNeutralVPSSTP::getdlnActCoeffdlnN(), IonsFromNeutralVPSSTP::getdlnActCoeffdlnN_diag(), IonsFromNeutralVPSSTP::getdlnActCoeffdlnX_diag(), IonsFromNeutralVPSSTP::getPartialMolarEnthalpies(), and IonsFromNeutralVPSSTP::getPartialMolarEntropies().
void s_update_dlnActCoeffdT () const private
Update the temperature derivative of the ln activity coefficients.
This function will be called to update the internally stored temperature derivative of the natural logarithm of the activity coefficients
Definition at line 1246 of file IonsFromNeutralVPSSTP.cpp.
References IonsFromNeutralVPSSTP::anionList_, IonsFromNeutralVPSSTP::cationList_, DATA_PTR, IonsFromNeutralVPSSTP::dlnActCoeffdT_NeutralMolecule_, GibbsExcessVPSSTP::dlnActCoeffdT_Scaled_, IonsFromNeutralVPSSTP::fm_invert_ionForNeutral, IonsFromNeutralVPSSTP::fm_neutralMolec_ions_, GibbsExcessVPSSTP::getdlnActCoeffdT(), IonsFromNeutralVPSSTP::ionSolnType_, Phase::m_kk, IonsFromNeutralVPSSTP::numPassThroughSpecies_, and IonsFromNeutralVPSSTP::passThroughList_.
Referenced by IonsFromNeutralVPSSTP::getPartialMolarEnthalpies(), and IonsFromNeutralVPSSTP::getPartialMolarEntropies().
void s_update_dlnActCoeff () const private
Update the change in the ln activity coefficients.
This function will be called to update the internally stored change of the natural logarithm of the activity coefficients w.r.t a change in state (temp, mole fraction, etc)
void s_update_dlnActCoeff_dlnX_diag () const private
Update the derivative of the log of the activity coefficients wrt log(mole fraction)
This function will be called to update the internally stored derivative of the natural logarithm of the activity coefficients wrt logarithm of the mole fractions.
Definition at line 1300 of file IonsFromNeutralVPSSTP.cpp.
References IonsFromNeutralVPSSTP::anionList_, IonsFromNeutralVPSSTP::cationList_, DATA_PTR, GibbsExcessVPSSTP::dlnActCoeffdlnX_diag_, IonsFromNeutralVPSSTP::dlnActCoeffdlnX_diag_NeutralMolecule_, IonsFromNeutralVPSSTP::fm_invert_ionForNeutral, IonsFromNeutralVPSSTP::fm_neutralMolec_ions_, ThermoPhase::getdlnActCoeffdlnX_diag(), IonsFromNeutralVPSSTP::ionSolnType_, Phase::m_kk, IonsFromNeutralVPSSTP::numPassThroughSpecies_, and IonsFromNeutralVPSSTP::passThroughList_.
Referenced by IonsFromNeutralVPSSTP::getdlnActCoeffdlnX_diag().
void s_update_dlnActCoeff_dlnN_diag () const private
Update the derivative of the log of the activity coefficients wrt log(number of moles) - diagonal components.
This function will be called to update the internally stored derivative of the natural logarithm of the activity coefficients wrt logarithm of the number of moles of given species.
Definition at line 1354 of file IonsFromNeutralVPSSTP.cpp.
References IonsFromNeutralVPSSTP::anionList_, IonsFromNeutralVPSSTP::cationList_, DATA_PTR, GibbsExcessVPSSTP::dlnActCoeffdlnN_diag_, IonsFromNeutralVPSSTP::dlnActCoeffdlnN_diag_NeutralMolecule_, IonsFromNeutralVPSSTP::fm_invert_ionForNeutral, IonsFromNeutralVPSSTP::fm_neutralMolec_ions_, VPStandardStateTP::getdlnActCoeffdlnN_diag(), IonsFromNeutralVPSSTP::ionSolnType_, Phase::m_kk, IonsFromNeutralVPSSTP::numPassThroughSpecies_, and IonsFromNeutralVPSSTP::passThroughList_.
Referenced by IonsFromNeutralVPSSTP::getdlnActCoeffdlnN_diag().
void s_update_dlnActCoeff_dlnN () const private
Update the derivative of the log of the activity coefficients wrt log(number of moles) - diagonal components.
This function will be called to update the internally stored derivative of the natural logarithm of the activity coefficients wrt logarithm of the number of moles of given species.
Definition at line 1408 of file IonsFromNeutralVPSSTP.cpp.
References IonsFromNeutralVPSSTP::anionList_, IonsFromNeutralVPSSTP::cationList_, GibbsExcessVPSSTP::dlnActCoeffdlnN_, GibbsExcessVPSSTP::dlnActCoeffdlnN_diag_, IonsFromNeutralVPSSTP::dlnActCoeffdlnN_diag_NeutralMolecule_, IonsFromNeutralVPSSTP::dlnActCoeffdlnN_NeutralMolecule_, IonsFromNeutralVPSSTP::fm_invert_ionForNeutral, IonsFromNeutralVPSSTP::fm_neutralMolec_ions_, GibbsExcessVPSSTP::getdlnActCoeffdlnN(), IonsFromNeutralVPSSTP::ionSolnType_, Phase::m_kk, Phase::nSpecies(), IonsFromNeutralVPSSTP::numPassThroughSpecies_, IonsFromNeutralVPSSTP::passThroughList_, and Array2D::zero().
Referenced by IonsFromNeutralVPSSTP::getdlnActCoeffdlnN().
doublereal err (const std::string & msg) const private
Error function.
Print an error string and exit
Parameters
msg Message to be printed
Definition at line 858 of file IonsFromNeutralVPSSTP.cpp.
References IonsFromNeutralVPSSTP::eosType(), and Cantera::int2str().
Member Data Documentation
IonSolnType_enumType ionSolnType_ protected
Ion solution type.
There is either mixing on the anion, cation, or both lattices. There is also a passthrough option
Defaults to cIonSolnType_SINGLEANION, so that LiKCl can be hardwired
Definition at line 645 of file IonsFromNeutralVPSSTP.h.
Referenced by IonsFromNeutralVPSSTP::calcNeutralMoleculeMoleFractions(), IonsFromNeutralVPSSTP::getChemPotentials(), IonsFromNeutralVPSSTP::getdlnActCoeffds(), IonsFromNeutralVPSSTP::getNeutralMoleculeMoleGrads(), IonsFromNeutralVPSSTP::operator=(), IonsFromNeutralVPSSTP::s_update_dlnActCoeff_dlnN(), IonsFromNeutralVPSSTP::s_update_dlnActCoeff_dlnN_diag(), IonsFromNeutralVPSSTP::s_update_dlnActCoeff_dlnX_diag(), IonsFromNeutralVPSSTP::s_update_dlnActCoeffdT(), and IonsFromNeutralVPSSTP::s_update_lnActCoeff().
size_t numNeutralMoleculeSpecies_ protected
Number of neutral molecule species.
This is equal to the number of species in the neutralMoleculePhase_ ThermoPhase.
Definition at line 652 of file IonsFromNeutralVPSSTP.h.
Referenced by IonsFromNeutralVPSSTP::calcIonMoleFractions(), IonsFromNeutralVPSSTP::calcNeutralMoleculeMoleFractions(), IonsFromNeutralVPSSTP::getNeutralMoleculeMoleGrads(), IonsFromNeutralVPSSTP::initLengths(), IonsFromNeutralVPSSTP::initThermoXML(), IonsFromNeutralVPSSTP::IonsFromNeutralVPSSTP(), and IonsFromNeutralVPSSTP::operator=().
size_t indexSpecialSpecies_ protected
Index of special species.
Definition at line 655 of file IonsFromNeutralVPSSTP.h.
Referenced by IonsFromNeutralVPSSTP::initThermoXML(), and IonsFromNeutralVPSSTP::operator=().
size_t indexSecondSpecialSpecies_ protected
Index of special species.
Definition at line 658 of file IonsFromNeutralVPSSTP.h.
Referenced by IonsFromNeutralVPSSTP::initThermoXML(), and IonsFromNeutralVPSSTP::operator=().
std::vector<double> fm_neutralMolec_ions_ protected
Formula Matrix for composition of neutral molecules in terms of the molecules in this ThermoPhase.
fm_neutralMolec_ions[ i + jNeut * m_kk ]
This is the number of ions of type i in the neutral molecule jNeut.
Definition at line 668 of file IonsFromNeutralVPSSTP.h.
Referenced by IonsFromNeutralVPSSTP::calcIonMoleFractions(), IonsFromNeutralVPSSTP::calcNeutralMoleculeMoleFractions(), IonsFromNeutralVPSSTP::getDissociationCoeffs(), IonsFromNeutralVPSSTP::getdlnActCoeffds(), IonsFromNeutralVPSSTP::getNeutralMoleculeMoleGrads(), IonsFromNeutralVPSSTP::initLengths(), IonsFromNeutralVPSSTP::initThermoXML(), IonsFromNeutralVPSSTP::operator=(), IonsFromNeutralVPSSTP::s_update_dlnActCoeff_dlnN(), IonsFromNeutralVPSSTP::s_update_dlnActCoeff_dlnN_diag(), IonsFromNeutralVPSSTP::s_update_dlnActCoeff_dlnX_diag(), IonsFromNeutralVPSSTP::s_update_dlnActCoeffdT(), and IonsFromNeutralVPSSTP::s_update_lnActCoeff().
std::vector<size_t> fm_invert_ionForNeutral protected
Mapping between ion species and neutral molecule for quick invert.
fm_invert_ionForNeutral returns vector of int. Each element represents an ionic species and stores the value of the corresponding neutral molecule
For the case of fm_invert_simple_ = true, we assume that there is a quick way to invert the formula matrix so that we can quickly calculate the neutral molecule mole fraction given the ion mole fraction vector.
We assume that for a selected set of ion species, that that ion is only in the neutral molecule, jNeut.
therefore,
NeutralMolecMoleFractions_[jNeut] += moleFractions_[i_ion] / fmij;
where fmij is the number of ions in neutral molecule jNeut.
Thus, we formulate the neutral molecule mole fraction NeutralMolecMoleFractions_[] vector from this association. We further assume that there are no other associations. If fm_invert_simple_ is not true, then we need to do a formal inversion which takes a great deal of time and is not currently implemented.
Definition at line 696 of file IonsFromNeutralVPSSTP.h.
Referenced by IonsFromNeutralVPSSTP::calcNeutralMoleculeMoleFractions(), IonsFromNeutralVPSSTP::getChemPotentials(), IonsFromNeutralVPSSTP::getDissociationCoeffs(), IonsFromNeutralVPSSTP::getdlnActCoeffds(), IonsFromNeutralVPSSTP::getNeutralMoleculeMoleGrads(), IonsFromNeutralVPSSTP::initLengths(), IonsFromNeutralVPSSTP::initThermoXML(), IonsFromNeutralVPSSTP::operator=(), IonsFromNeutralVPSSTP::s_update_dlnActCoeff_dlnN(), IonsFromNeutralVPSSTP::s_update_dlnActCoeff_dlnN_diag(), IonsFromNeutralVPSSTP::s_update_dlnActCoeff_dlnX_diag(), IonsFromNeutralVPSSTP::s_update_dlnActCoeffdT(), and IonsFromNeutralVPSSTP::s_update_lnActCoeff().
std::vector<doublereal> NeutralMolecMoleFractions_ mutable protected
Mole fractions using the Neutral Molecule Mole fraction basis.
Definition at line 699 of file IonsFromNeutralVPSSTP.h.
Referenced by IonsFromNeutralVPSSTP::calcIonMoleFractions(), IonsFromNeutralVPSSTP::calcNeutralMoleculeMoleFractions(), IonsFromNeutralVPSSTP::getNeutralMolecMoleFractions(), IonsFromNeutralVPSSTP::initLengths(), IonsFromNeutralVPSSTP::operator=(), IonsFromNeutralVPSSTP::setConcentrations(), IonsFromNeutralVPSSTP::setMassFractions(), IonsFromNeutralVPSSTP::setMassFractions_NoNorm(), IonsFromNeutralVPSSTP::setMoleFractions(), and IonsFromNeutralVPSSTP::setMoleFractions_NoNorm().
std::vector<size_t> cationList_ protected
List of the species in this ThermoPhase which are cation species.
Definition at line 702 of file IonsFromNeutralVPSSTP.h.
Referenced by IonsFromNeutralVPSSTP::calcNeutralMoleculeMoleFractions(), IonsFromNeutralVPSSTP::getCationList(), IonsFromNeutralVPSSTP::getChemPotentials(), IonsFromNeutralVPSSTP::getdlnActCoeffds(), IonsFromNeutralVPSSTP::getNeutralMoleculeMoleGrads(), IonsFromNeutralVPSSTP::initLengths(), IonsFromNeutralVPSSTP::initThermoXML(), IonsFromNeutralVPSSTP::operator=(), IonsFromNeutralVPSSTP::s_update_dlnActCoeff_dlnN(), IonsFromNeutralVPSSTP::s_update_dlnActCoeff_dlnN_diag(), IonsFromNeutralVPSSTP::s_update_dlnActCoeff_dlnX_diag(), IonsFromNeutralVPSSTP::s_update_dlnActCoeffdT(), and IonsFromNeutralVPSSTP::s_update_lnActCoeff().
int numCationSpecies_ protected
Number of cation species.
Definition at line 705 of file IonsFromNeutralVPSSTP.h.
Referenced by IonsFromNeutralVPSSTP::initThermoXML(), and IonsFromNeutralVPSSTP::operator=().
std::vector<size_t> anionList_ protected
List of the species in this ThermoPhase which are anion species.
Definition at line 708 of file IonsFromNeutralVPSSTP.h.
Referenced by IonsFromNeutralVPSSTP::calcNeutralMoleculeMoleFractions(), IonsFromNeutralVPSSTP::getAnionList(), IonsFromNeutralVPSSTP::getChemPotentials(), IonsFromNeutralVPSSTP::getdlnActCoeffds(), IonsFromNeutralVPSSTP::getNeutralMoleculeMoleGrads(), IonsFromNeutralVPSSTP::initLengths(), IonsFromNeutralVPSSTP::initThermoXML(), IonsFromNeutralVPSSTP::operator=(), IonsFromNeutralVPSSTP::s_update_dlnActCoeff_dlnN(), IonsFromNeutralVPSSTP::s_update_dlnActCoeff_dlnN_diag(), IonsFromNeutralVPSSTP::s_update_dlnActCoeff_dlnX_diag(), IonsFromNeutralVPSSTP::s_update_dlnActCoeffdT(), and IonsFromNeutralVPSSTP::s_update_lnActCoeff().
int numAnionSpecies_ protected
Number of anion species.
Definition at line 711 of file IonsFromNeutralVPSSTP.h.
Referenced by IonsFromNeutralVPSSTP::initThermoXML(), and IonsFromNeutralVPSSTP::operator=().
std::vector<size_t> passThroughList_ protected
List of the species in this ThermoPhase which are passed through to the neutralMoleculePhase ThermoPhase.
These have neutral charges.
Definition at line 718 of file IonsFromNeutralVPSSTP.h.
Referenced by IonsFromNeutralVPSSTP::calcNeutralMoleculeMoleFractions(), IonsFromNeutralVPSSTP::getChemPotentials(), IonsFromNeutralVPSSTP::getdlnActCoeffds(), IonsFromNeutralVPSSTP::getNeutralMoleculeMoleGrads(), IonsFromNeutralVPSSTP::initLengths(), IonsFromNeutralVPSSTP::initThermoXML(), IonsFromNeutralVPSSTP::operator=(), IonsFromNeutralVPSSTP::s_update_dlnActCoeff_dlnN(), IonsFromNeutralVPSSTP::s_update_dlnActCoeff_dlnN_diag(), IonsFromNeutralVPSSTP::s_update_dlnActCoeff_dlnX_diag(), IonsFromNeutralVPSSTP::s_update_dlnActCoeffdT(), and IonsFromNeutralVPSSTP::s_update_lnActCoeff().
size_t numPassThroughSpecies_ protected
Number of the species in this ThermoPhase which are passed through to the neutralMoleculePhase ThermoPhase.
Definition at line 722 of file IonsFromNeutralVPSSTP.h.
Referenced by IonsFromNeutralVPSSTP::calcNeutralMoleculeMoleFractions(), IonsFromNeutralVPSSTP::getChemPotentials(), IonsFromNeutralVPSSTP::getdlnActCoeffds(), IonsFromNeutralVPSSTP::getNeutralMoleculeMoleGrads(), IonsFromNeutralVPSSTP::initThermoXML(), IonsFromNeutralVPSSTP::operator=(), IonsFromNeutralVPSSTP::s_update_dlnActCoeff_dlnN(), IonsFromNeutralVPSSTP::s_update_dlnActCoeff_dlnN_diag(), IonsFromNeutralVPSSTP::s_update_dlnActCoeff_dlnX_diag(), IonsFromNeutralVPSSTP::s_update_dlnActCoeffdT(), and IonsFromNeutralVPSSTP::s_update_lnActCoeff().
ThermoPhase* neutralMoleculePhase_
This is a pointer to the neutral Molecule Phase.
If the variable, IOwnNThermoPhase_ is true, then we own the pointer. If not, then this is considered a shallow pointer.
Definition at line 730 of file IonsFromNeutralVPSSTP.h.
Referenced by IonsFromNeutralVPSSTP::calcIonMoleFractions(), PDSS_IonsFromNeutral::constructPDSSXML(), IonsFromNeutralVPSSTP::constructPhaseXML(), IonsFromNeutralVPSSTP::getChemPotentials(), LTI_StefanMaxwell_PPN::getMatrixTransProp(), PDSS_IonsFromNeutral::initAllPtrs(), IonsFromNeutralVPSSTP::initLengths(), IonsFromNeutralVPSSTP::initThermoXML(), IonsFromNeutralVPSSTP::IonsFromNeutralVPSSTP(), IonsFromNeutralVPSSTP::operator=(), IonsFromNeutralVPSSTP::s_update_lnActCoeff(), IonsFromNeutralVPSSTP::setConcentrations(), IonsFromNeutralVPSSTP::setMassFractions(), IonsFromNeutralVPSSTP::setMassFractions_NoNorm(), IonsFromNeutralVPSSTP::setMoleFractions(), IonsFromNeutralVPSSTP::setMoleFractions_NoNorm(), IonsFromNeutralVPSSTP::setState_TP(), and IonsFromNeutralVPSSTP::~IonsFromNeutralVPSSTP().
bool IOwnNThermoPhase_ private
If true then we own the underlying neutral Molecule Phase.
If this is false, then the neutral molecule phase is considered as a shallow pointer.
Definition at line 744 of file IonsFromNeutralVPSSTP.h.
Referenced by IonsFromNeutralVPSSTP::IonsFromNeutralVPSSTP(), IonsFromNeutralVPSSTP::operator=(), and IonsFromNeutralVPSSTP::~IonsFromNeutralVPSSTP().
std::vector<doublereal> moleFractionsTmp_ mutable private
Temporary mole fraction vector.
Definition at line 747 of file IonsFromNeutralVPSSTP.h.
Referenced by IonsFromNeutralVPSSTP::calcNeutralMoleculeMoleFractions(), IonsFromNeutralVPSSTP::getNeutralMoleculeMoleGrads(), IonsFromNeutralVPSSTP::initLengths(), and IonsFromNeutralVPSSTP::operator=().
std::vector<doublereal> muNeutralMolecule_ mutable private
Storage vector for the neutral molecule chemical potentials.
This vector is used as a temporary storage area when calculating the ion chemical potentials.
Units = Joules/kmol
Length = numNeutralMoleculeSpecies_
Definition at line 757 of file IonsFromNeutralVPSSTP.h.
Referenced by IonsFromNeutralVPSSTP::getChemPotentials(), IonsFromNeutralVPSSTP::initLengths(), and IonsFromNeutralVPSSTP::operator=().
std::vector<doublereal> lnActCoeff_NeutralMolecule_ mutable private
Storage vector for the neutral molecule ln activity coefficients.
This vector is used as a temporary storage area when calculating the ion chemical potentials and activity coefficients
Units = none
Length = numNeutralMoleculeSpecies_
Definition at line 767 of file IonsFromNeutralVPSSTP.h.
Referenced by IonsFromNeutralVPSSTP::getChemPotentials(), IonsFromNeutralVPSSTP::initLengths(), IonsFromNeutralVPSSTP::operator=(), and IonsFromNeutralVPSSTP::s_update_lnActCoeff().
std::vector<doublereal> dlnActCoeffdT_NeutralMolecule_ mutable private
Storage vector for the neutral molecule d ln activity coefficients dT.
This vector is used as a temporary storage area when calculating the ion derivatives
Units = 1/Kelvin
Length = numNeutralMoleculeSpecies_
Definition at line 776 of file IonsFromNeutralVPSSTP.h.
Referenced by IonsFromNeutralVPSSTP::initLengths(), IonsFromNeutralVPSSTP::operator=(), and IonsFromNeutralVPSSTP::s_update_dlnActCoeffdT().
std::vector<doublereal> dlnActCoeffdlnX_diag_NeutralMolecule_ mutable private
Storage vector for the neutral molecule d ln activity coefficients dX - diagonal component.
This vector is used as a temporary storage area when calculating the ion derivatives
Units = none
Length = numNeutralMoleculeSpecies_
Definition at line 785 of file IonsFromNeutralVPSSTP.h.
Referenced by IonsFromNeutralVPSSTP::initLengths(), IonsFromNeutralVPSSTP::operator=(), and IonsFromNeutralVPSSTP::s_update_dlnActCoeff_dlnX_diag().
std::vector<doublereal> dlnActCoeffdlnN_diag_NeutralMolecule_ mutable private
Storage vector for the neutral molecule d ln activity coefficients dlnN - diagonal component.
This vector is used as a temporary storage area when calculating the ion derivatives
Units = none
Length = numNeutralMoleculeSpecies_
Definition at line 794 of file IonsFromNeutralVPSSTP.h.
Referenced by IonsFromNeutralVPSSTP::initLengths(), IonsFromNeutralVPSSTP::operator=(), IonsFromNeutralVPSSTP::s_update_dlnActCoeff_dlnN(), and IonsFromNeutralVPSSTP::s_update_dlnActCoeff_dlnN_diag().
Array2D dlnActCoeffdlnN_NeutralMolecule_ mutable private
Storage vector for the neutral molecule d ln activity coefficients dlnN.
This vector is used as a temporary storage area when calculating the ion derivatives
Units = none
Length = numNeutralMoleculeSpecies_
Definition at line 803 of file IonsFromNeutralVPSSTP.h.
Referenced by IonsFromNeutralVPSSTP::initLengths(), IonsFromNeutralVPSSTP::operator=(), and IonsFromNeutralVPSSTP::s_update_dlnActCoeff_dlnN().
The documentation for this class was generated from the following files:
IonsFromNeutralVPSSTP.h
IonsFromNeutralVPSSTP.cpp