Cantera: ConstDensityThermo Class Reference
ConstDensityThermo Class Reference
Thermodynamic Properties
Overloads the virtual methods of class ThermoPhase to implement the incompressible equation of state.
#include <ConstDensityThermo.h>
Public Member Functions
ConstDensityThermo ()
Constructor.
ConstDensityThermo (const ConstDensityThermo &right)
Copy Constructor.
ConstDensityThermo & operator= (const ConstDensityThermo &right)
Assignment Operator.
virtual ThermoPhase * duplMyselfAsThermoPhase () const
Duplication routine for objects which inherit from ThermoPhase.
virtual int eosType () const
Returns a constant corresponding to this class's equation of state.
virtual doublereal enthalpy_mole () const
Molar enthalpy. Units: J/kmol.
virtual doublereal intEnergy_mole () const
Molar internal energy. Units: J/kmol.
virtual doublereal entropy_mole () const
Molar entropy. Units: J/kmol/K.
virtual doublereal gibbs_mole () const
Molar Gibbs function. Units: J/kmol.
virtual doublereal cp_mole () const
Molar heat capacity at constant pressure. Units: J/kmol/K.
virtual doublereal cv_mole () const
Molar heat capacity at constant volume. Units: J/kmol/K.
virtual doublereal pressure () const
Return the thermodynamic pressure (Pa).
virtual void setPressure (doublereal p)
Set the internally stored pressure (Pa) at constant temperature and composition.
virtual void getActivityConcentrations (doublereal *c) const
This method returns an array of generalized concentrations.
virtual void getActivityCoefficients (doublereal *ac) const
Get the array of non-dimensional molar-based activity coefficients at the current solution temperature, pressure, and solution concentration.
virtual void getChemPotentials (doublereal *mu) const
Get the species chemical potentials. Units: J/kmol.
virtual void getStandardChemPotentials (doublereal *mu0) const
Get the array of chemical potentials at unit activity for the species at their standard states at the current T and P of the solution.
virtual doublereal standardConcentration (size_t k=0) const
Return the standard concentration for the kth species.
virtual doublereal logStandardConc (size_t k=0) const
Natural logarithm of the standard concentration of the kth species.
virtual void getPureGibbs (doublereal *gpure) const
Get the Gibbs functions for the standard state of the species at the current T and P of the solution.
void getEnthalpy_RT (doublereal *hrt) const
Get the nondimensional Enthalpy functions for the species at their standard states at the current T and P of the solution.
void getEntropy_R (doublereal *sr) const
Get the array of nondimensional Entropy functions for the standard state species at the current T and P of the solution.
virtual void getGibbs_RT (doublereal *grt) const
Get the nondimensional Gibbs functions for the species in their standard states at the current T and P of the solution.
void getCp_R (doublereal *cpr) const
Get the nondimensional Heat Capacities at constant pressure for the species standard states at the current T and P of the solution.
const vector_fp & enthalpy_RT () const
Returns a reference to the vector of nondimensional enthalpies of the reference state at the current temperature of the solution and the reference pressure for the species.
const vector_fp & gibbs_RT () const
Returns a reference to the vector of nondimensional Gibbs Free Energies of the reference state at the current temperature of the solution and the reference pressure for the species.
const vector_fp & entropy_R () const
Returns a reference to the vector of nondimensional entropies of the reference state at the current temperature of the solution and the reference pressure for each species.
const vector_fp & cp_R () const
Returns a reference to the vector of nondimensional constant pressure heat capacities of the reference state at the current temperature of the solution and reference pressure for each species.
virtual void initThermo ()
Initialize the ThermoPhase object after all species have been set up.
virtual void setToEquilState (const doublereal *lambda_RT)
This method is used by the ChemEquil equilibrium solver.
virtual void setParameters (int n, doublereal *const c)
Set the equation of state parameters.
virtual void getParameters (int &n, doublereal *const c) const
Get the equation of state parameters in a vector.
virtual void setParametersFromXML (const XML_Node &eosdata)
Set equation of state parameter values from XML entries.
Public Member Functions inherited from ThermoPhase
ThermoPhase ()
Constructor.
virtual ~ThermoPhase ()
Destructor. Deletes the species thermo manager.
ThermoPhase (const ThermoPhase &right)
Copy Constructor for the ThermoPhase object.
ThermoPhase & operator= (const ThermoPhase &right)
Assignment operator.
doublereal _RT () const
Return the Gas Constant multiplied by the current temperature.
virtual doublereal refPressure () const
Returns the reference pressure in Pa.
virtual doublereal minTemp (size_t k=npos) const
Minimum temperature for which the thermodynamic data for the species or phase are valid.
doublereal Hf298SS (const int k) const
Report the 298 K Heat of Formation of the standard state of one species (J kmol-1)
virtual void modifyOneHf298SS (const int k, const doublereal Hf298New)
Modify the value of the 298 K Heat of Formation of one species in the phase (J kmol-1)
virtual doublereal maxTemp (size_t k=npos) const
Maximum temperature for which the thermodynamic data for the species are valid.
bool chargeNeutralityNecessary () const
Returns the chargeNeutralityNecessity boolean.
virtual doublereal cv_vib (int, double) const
virtual doublereal isothermalCompressibility () const
Returns the isothermal compressibility. Units: 1/Pa.
virtual doublereal thermalExpansionCoeff () const
Return the volumetric thermal expansion coefficient. Units: 1/K.
void setElectricPotential (doublereal v)
Set the electric potential of this phase (V).
doublereal electricPotential () const
Returns the electric potential of this phase (V).
virtual int activityConvention () const
This method returns the convention used in specification of the activities, of which there are currently two, molar- and molality-based conventions.
virtual int standardStateConvention () const
This method returns the convention used in specification of the standard state, of which there are currently two, temperature based, and variable pressure based.
virtual void getUnitsStandardConc (double *uA, int k=0, int sizeUA=6) const
Returns the units of the standard and generalized concentrations.
virtual void getActivities (doublereal *a) const
Get the array of non-dimensional activities at the current solution temperature, pressure, and solution concentration.
virtual void getLnActivityCoefficients (doublereal *lnac) const
Get the array of non-dimensional molar-based ln activity coefficients at the current solution temperature, pressure, and solution concentration.
virtual void getChemPotentials_RT (doublereal *mu) const
Get the array of non-dimensional species chemical potentials These are partial molar Gibbs free energies.
void getElectrochemPotentials (doublereal *mu) const
Get the species electrochemical potentials.
virtual void getPartialMolarEnthalpies (doublereal *hbar) const
Returns an array of partial molar enthalpies for the species in the mixture.
virtual void getPartialMolarEntropies (doublereal *sbar) const
Returns an array of partial molar entropies of the species in the solution.
virtual void getPartialMolarIntEnergies (doublereal *ubar) const
Return an array of partial molar internal energies for the species in the mixture.
virtual void getPartialMolarCp (doublereal *cpbar) const
Return an array of partial molar heat capacities for the species in the mixture.
virtual void getPartialMolarVolumes (doublereal *vbar) const
Return an array of partial molar volumes for the species in the mixture.
virtual void getdPartialMolarVolumes_dT (doublereal *d_vbar_dT) const
Return an array of derivatives of partial molar volumes wrt temperature for the species in the mixture.
virtual void getdPartialMolarVolumes_dP (doublereal *d_vbar_dP) const
Return an array of derivatives of partial molar volumes wrt pressure for the species in the mixture.
virtual void getIntEnergy_RT (doublereal *urt) const
Returns the vector of nondimensional Internal Energies of the standard state species at the current T and P of the solution.
virtual void getStandardVolumes (doublereal *vol) const
Get the molar volumes of the species standard states at the current T and P of the solution.
virtual void getdStandardVolumes_dT (doublereal *d_vol_dT) const
Get the derivative of the molar volumes of the species standard states wrt temperature at the current T and P of the solution.
virtual void getdStandardVolumes_dP (doublereal *d_vol_dP) const
Get the derivative molar volumes of the species standard states wrt pressure at the current T and P of the solution.
virtual void getEnthalpy_RT_ref (doublereal *hrt) const
Returns the vector of nondimensional enthalpies of the reference state at the current temperature of the solution and the reference pressure for the species.
virtual void getGibbs_RT_ref (doublereal *grt) const
Returns the vector of nondimensional Gibbs Free Energies of the reference state at the current temperature of the solution and the reference pressure for the species.
virtual void getGibbs_ref (doublereal *g) const
Returns the vector of the gibbs function of the reference state at the current temperature of the solution and the reference pressure for the species.
virtual void getEntropy_R_ref (doublereal *er) const
Returns the vector of nondimensional entropies of the reference state at the current temperature of the solution and the reference pressure for each species.
virtual void getIntEnergy_RT_ref (doublereal *urt) const
Returns the vector of nondimensional internal Energies of the reference state at the current temperature of the solution and the reference pressure for each species.
virtual void getCp_R_ref (doublereal *cprt) const
Returns the vector of nondimensional constant pressure heat capacities of the reference state at the current temperature of the solution and reference pressure for each species.
virtual void getStandardVolumes_ref (doublereal *vol) const
Get the molar volumes of the species reference states at the current T and P_ref of the solution.
virtual void setReferenceComposition (const doublereal *const x)
Sets the reference composition.
virtual void getReferenceComposition (doublereal *const x) const
Gets the reference composition.
doublereal enthalpy_mass () const
Specific enthalpy.
doublereal intEnergy_mass () const
Specific internal energy.
doublereal entropy_mass () const
Specific entropy.
doublereal gibbs_mass () const
Specific Gibbs function.
doublereal cp_mass () const
Specific heat at constant pressure.
doublereal cv_mass () const
Specific heat at constant volume.
void setElementPotentials (const vector_fp &lambda)
Stores the element potentials in the ThermoPhase object.
bool getElementPotentials (doublereal *lambda) const
Returns the element potentials stored in the ThermoPhase object.
virtual doublereal critTemperature () const
Critical temperature (K).
virtual doublereal critPressure () const
Critical pressure (Pa).
virtual doublereal critDensity () const
Critical density (kg/m3).
virtual doublereal satTemperature (doublereal p) const
Return the saturation temperature given the pressure.
virtual doublereal satPressure (doublereal t)
Return the saturation pressure given the temperature.
virtual doublereal vaporFraction () const
Return the fraction of vapor at the current conditions.
virtual void setState_Tsat (doublereal t, doublereal x)
Set the state to a saturated system at a particular temperature.
virtual void setState_Psat (doublereal p, doublereal x)
Set the state to a saturated system at a particular pressure.
void saveSpeciesData (const size_t k, const XML_Node *const data)
Store a reference pointer to the XML tree containing the species data for this phase.
const std::vector< const
XML_Node * > & speciesData () const
Return a pointer to the vector of XML nodes containing the species data for this phase.
void setSpeciesThermo (SpeciesThermo *spthermo)
Install a species thermodynamic property manager.
virtual SpeciesThermo & speciesThermo (int k=-1)
Return a changeable reference to the calculation manager for species reference-state thermodynamic properties.
virtual void initThermoFile (const std::string &inputFile, const std::string &id)
virtual void initThermoXML (XML_Node &phaseNode, const std::string &id)
Import and initialize a ThermoPhase object using an XML tree.
virtual void installSlavePhases (Cantera::XML_Node *phaseNode)
Add in species from Slave phases.
virtual void setStateFromXML (const XML_Node &state)
Set the initial state of the phase to the conditions specified in the state XML element.
virtual void getdlnActCoeffds (const doublereal dTds, const doublereal *const dXds, doublereal *dlnActCoeffds) const
Get the change in activity coefficients wrt changes in state (temp, mole fraction, etc) along a line in parameter space or along a line in physical space.
virtual void getdlnActCoeffdlnX_diag (doublereal *dlnActCoeffdlnX_diag) const
Get the array of ln mole fraction derivatives of the log activity coefficients - diagonal component only.
virtual void getdlnActCoeffdlnN_diag (doublereal *dlnActCoeffdlnN_diag) const
Get the array of log species mole number derivatives of the log activity coefficients.
virtual void getdlnActCoeffdlnN (const size_t ld, doublereal *const dlnActCoeffdlnN)
Get the array of derivatives of the log activity coefficients with respect to the log of the species mole numbers.
virtual void getdlnActCoeffdlnN_numderiv (const size_t ld, doublereal *const dlnActCoeffdlnN)
virtual std::string report (bool show_thermo=true) const
returns a summary of the state of the phase as a string
virtual void reportCSV (std::ofstream &csvFile) const
returns a summary of the state of the phase to a comma separated file.
virtual void setState_TPX (doublereal t, doublereal p, const doublereal *x)
Set the temperature (K), pressure (Pa), and mole fractions.
virtual void setState_TPX (doublereal t, doublereal p, compositionMap &x)
Set the temperature (K), pressure (Pa), and mole fractions.
virtual void setState_TPX (doublereal t, doublereal p, const std::string &x)
Set the temperature (K), pressure (Pa), and mole fractions.
virtual void setState_TPY (doublereal t, doublereal p, const doublereal *y)
Set the internally stored temperature (K), pressure (Pa), and mass fractions of the phase.
virtual void setState_TPY (doublereal t, doublereal p, compositionMap &y)
Set the internally stored temperature (K), pressure (Pa), and mass fractions of the phase.
virtual void setState_TPY (doublereal t, doublereal p, const std::string &y)
Set the internally stored temperature (K), pressure (Pa), and mass fractions of the phase.
virtual void setState_TP (doublereal t, doublereal p)
Set the temperature (K) and pressure (Pa)
virtual void setState_PX (doublereal p, doublereal *x)
Set the pressure (Pa) and mole fractions.
virtual void setState_PY (doublereal p, doublereal *y)
Set the internally stored pressure (Pa) and mass fractions.
virtual void setState_HP (doublereal h, doublereal p, doublereal tol=1.e-4)
Set the internally stored specific enthalpy (J/kg) and pressure (Pa) of the phase.
virtual void setState_UV (doublereal u, doublereal v, doublereal tol=1.e-4)
Set the specific internal energy (J/kg) and specific volume (m^3/kg).
virtual void setState_SP (doublereal s, doublereal p, doublereal tol=1.e-4)
Set the specific entropy (J/kg/K) and pressure (Pa).
virtual void setState_SV (doublereal s, doublereal v, doublereal tol=1.e-4)
Set the specific entropy (J/kg/K) and specific volume (m^3/kg).
Public Member Functions inherited from Phase
Phase ()
Default constructor.
virtual ~Phase ()
Destructor.
Phase (const Phase &right)
Copy Constructor.
Phase & operator= (const Phase &right)
Assignment operator.
XML_Node & xml ()
Returns a reference to the XML_Node stored for the phase.
void saveState (vector_fp &state) const
Save the current internal state of the phase Write to vector 'state' the current internal state.
void saveState (size_t lenstate, doublereal *state) const
Write to array 'state' the current internal state.
void restoreState (const vector_fp &state)
Restore a state saved on a previous call to saveState.
void restoreState (size_t lenstate, const doublereal *state)
Restore the state of the phase from a previously saved state vector.
doublereal molecularWeight (size_t k) const
Molecular weight of species k.
void getMolecularWeights (vector_fp &weights) const
Copy the vector of molecular weights into vector weights.
void getMolecularWeights (doublereal *weights) const
Copy the vector of molecular weights into array weights.
const vector_fp & molecularWeights () const
Return a const reference to the internal vector of molecular weights.
doublereal size (size_t k) const
This routine returns the size of species k.
doublereal charge (size_t k) const
Dimensionless electrical charge of a single molecule of species k The charge is normalized by the the magnitude of the electron charge.
doublereal chargeDensity () const
Charge density [C/m^3].
size_t nDim () const
Returns the number of spatial dimensions (1, 2, or 3)
void setNDim (size_t ndim)
Set the number of spatial dimensions (1, 2, or 3).
virtual void freezeSpecies ()
Call when finished adding species.
bool speciesFrozen ()
True if freezeSpecies has been called.
virtual bool ready () const
int stateMFNumber () const
Return the State Mole Fraction Number.
std::string id () const
Return the string id for the phase.
void setID (const std::string &id)
Set the string id for the phase.
std::string name () const
Return the name of the phase.
void setName (const std::string &nm)
Sets the string name for the phase.
std::string elementName (size_t m) const
Name of the element with index m.
size_t elementIndex (const std::string &name) const
Return the index of element named 'name'.
const std::vector< std::string > & elementNames () const
Return a read-only reference to the vector of element names.
doublereal atomicWeight (size_t m) const
Atomic weight of element m.
doublereal entropyElement298 (size_t m) const
Entropy of the element in its standard state at 298 K and 1 bar.
int atomicNumber (size_t m) const
Atomic number of element m.
int elementType (size_t m) const
Return the element constraint type Possible types include:
int changeElementType (int m, int elem_type)
Change the element type of the mth constraint Reassigns an element type.
const vector_fp & atomicWeights () const
Return a read-only reference to the vector of atomic weights.
size_t nElements () const
Number of elements.
void checkElementIndex (size_t m) const
Check that the specified element index is in range Throws an exception if m is greater than nElements()-1.
void checkElementArraySize (size_t mm) const
Check that an array size is at least nElements() Throws an exception if mm is less than nElements().
doublereal nAtoms (size_t k, size_t m) const
Number of atoms of element m in species k.
void getAtoms (size_t k, double *atomArray) const
Get a vector containing the atomic composition of species k.
size_t speciesIndex (const std::string &name) const
Returns the index of a species named 'name' within the Phase object.
std::string speciesName (size_t k) const
Name of the species with index k.
std::string speciesSPName (int k) const
Returns the expanded species name of a species, including the phase name This is guaranteed to be unique within a Cantera problem.
const std::vector< std::string > & speciesNames () const
Return a const reference to the vector of species names.
size_t nSpecies () const
Returns the number of species in the phase.
void checkSpeciesIndex (size_t k) const
Check that the specified species index is in range Throws an exception if k is greater than nSpecies()-1.
void checkSpeciesArraySize (size_t kk) const
Check that an array size is at least nSpecies() Throws an exception if kk is less than nSpecies().
void setMoleFractionsByName (compositionMap &xMap)
Set the species mole fractions by name.
void setMoleFractionsByName (const std::string &x)
Set the mole fractions of a group of species by name.
void setMassFractionsByName (compositionMap &yMap)
Set the species mass fractions by name.
void setMassFractionsByName (const std::string &x)
Set the species mass fractions by name.
void setState_TRX (doublereal t, doublereal dens, const doublereal *x)
Set the internally stored temperature (K), density, and mole fractions.
void setState_TRX (doublereal t, doublereal dens, compositionMap &x)
Set the internally stored temperature (K), density, and mole fractions.
void setState_TRY (doublereal t, doublereal dens, const doublereal *y)
Set the internally stored temperature (K), density, and mass fractions.
void setState_TRY (doublereal t, doublereal dens, compositionMap &y)
Set the internally stored temperature (K), density, and mass fractions.
void setState_TNX (doublereal t, doublereal n, const doublereal *x)
Set the internally stored temperature (K), molar density (kmol/m^3), and mole fractions.
void setState_TR (doublereal t, doublereal rho)
Set the internally stored temperature (K) and density (kg/m^3)
void setState_TX (doublereal t, doublereal *x)
Set the internally stored temperature (K) and mole fractions.
void setState_TY (doublereal t, doublereal *y)
Set the internally stored temperature (K) and mass fractions.
void setState_RX (doublereal rho, doublereal *x)
Set the density (kg/m^3) and mole fractions.
void setState_RY (doublereal rho, doublereal *y)
Set the density (kg/m^3) and mass fractions.
void getMoleFractionsByName (compositionMap &x) const
Get the mole fractions by name.
doublereal moleFraction (size_t k) const
Return the mole fraction of a single species.
doublereal moleFraction (const std::string &name) const
Return the mole fraction of a single species.
doublereal massFraction (size_t k) const
Return the mass fraction of a single species.
doublereal massFraction (const std::string &name) const
Return the mass fraction of a single species.
void getMoleFractions (doublereal *const x) const
Get the species mole fraction vector.
virtual void setMoleFractions (const doublereal *const x)
Set the mole fractions to the specified values There is no restriction on the sum of the mole fraction vector.
virtual void setMoleFractions_NoNorm (const doublereal *const x)
Set the mole fractions to the specified values without normalizing.
void getMassFractions (doublereal *const y) const
Get the species mass fractions.
const doublereal * massFractions () const
Return a const pointer to the mass fraction array.
virtual void setMassFractions (const doublereal *const y)
Set the mass fractions to the specified values and normalize them.
virtual void setMassFractions_NoNorm (const doublereal *const y)
Set the mass fractions to the specified values without normalizing.
void getConcentrations (doublereal *const c) const
Get the species concentrations (kmol/m^3).
doublereal concentration (const size_t k) const
Concentration of species k.
virtual void setConcentrations (const doublereal *const conc)
Set the concentrations to the specified values within the phase.
const doublereal * moleFractdivMMW () const
Returns a const pointer to the start of the moleFraction/MW array.
doublereal temperature () const
Temperature (K).
virtual doublereal density () const
Density (kg/m^3).
doublereal molarDensity () const
Molar density (kmol/m^3).
doublereal molarVolume () const
Molar volume (m^3/kmol).
virtual void setDensity (const doublereal density_)
Set the internally stored density (kg/m^3) of the phase Note the density of a phase is an independent variable.
virtual void setMolarDensity (const doublereal molarDensity)
Set the internally stored molar density (kmol/m^3) of the phase.
virtual void setTemperature (const doublereal temp)
Set the internally stored temperature of the phase (K).
doublereal mean_X (const doublereal *const Q) const
Evaluate the mole-fraction-weighted mean of an array Q.
doublereal mean_Y (const doublereal *const Q) const
Evaluate the mass-fraction-weighted mean of an array Q.
doublereal meanMolecularWeight () const
The mean molecular weight. Units: (kg/kmol)
doublereal sum_xlogx () const
Evaluate \(\sum_k X_k \log X_k \).
doublereal sum_xlogQ (doublereal *const Q) const
Evaluate \(\sum_k X_k \log Q_k \).
void addElement (const std::string &symbol, doublereal weight=-12345.0)
Add an element.
void addElement (const XML_Node &e)
Add an element from an XML specification.
void addUniqueElement (const std::string &symbol, doublereal weight=-12345.0, int atomicNumber=0, doublereal entropy298=ENTROPY298_UNKNOWN, int elem_type=CT_ELEM_TYPE_ABSPOS)
Add an element, checking for uniqueness The uniqueness is checked by comparing the string symbol.
void addUniqueElement (const XML_Node &e)
Add an element, checking for uniqueness The uniqueness is checked by comparing the string symbol.
void addElementsFromXML (const XML_Node &phase)
Add all elements referenced in an XML_Node tree.
void freezeElements ()
Prohibit addition of more elements, and prepare to add species.
bool elementsFrozen ()
True if freezeElements has been called.
size_t addUniqueElementAfterFreeze (const std::string &symbol, doublereal weight, int atomicNumber, doublereal entropy298=ENTROPY298_UNKNOWN, int elem_type=CT_ELEM_TYPE_ABSPOS)
Add an element after elements have been frozen, checking for uniqueness The uniqueness is checked by comparing the string symbol.
void addSpecies (const std::string &name, const doublereal *comp, doublereal charge=0.0, doublereal size=1.0)
void addUniqueSpecies (const std::string &name, const doublereal *comp, doublereal charge=0.0, doublereal size=1.0)
Add a species to the phase, checking for uniqueness of the name This routine checks for uniqueness of the string name.
Protected Attributes
doublereal m_tlast
last value of the temperature processed by reference state
vector_fp m_h0_RT
Temporary storage for dimensionless reference state enthalpies.
vector_fp m_cp0_R
Temporary storage for dimensionless reference state heat capacities.
vector_fp m_g0_RT
Temporary storage for dimensionless reference state gibbs energies.
vector_fp m_s0_R
Temporary storage for dimensionless reference state entropies.
vector_fp m_pp
Temporary array containing internally calculated partial pressures.
doublereal m_press
Current pressure (Pa)
Protected Attributes inherited from ThermoPhase
SpeciesThermo * m_spthermo
Pointer to the calculation manager for species reference-state thermodynamic properties.
std::vector< const XML_Node * > m_speciesData
Vector of pointers to the species databases.
doublereal m_phi
Stored value of the electric potential for this phase.
vector_fp m_lambdaRRT
Vector of element potentials.
bool m_hasElementPotentials
Boolean indicating whether there is a valid set of saved element potentials for this phase.
bool m_chargeNeutralityNecessary
Boolean indicating whether a charge neutrality condition is a necessity.
int m_ssConvention
Contains the standard state convention.
std::vector< doublereal > xMol_Ref
Reference Mole Fraction Composition.
Protected Attributes inherited from Phase
size_t m_kk
Number of species in the phase.
size_t m_ndim
Dimensionality of the phase.
vector_fp m_speciesComp
Atomic composition of the species.
vector_fp m_speciesSize
Vector of species sizes.
vector_fp m_speciesCharge
Vector of species charges. length m_kk.
Private Member Functions
void _updateThermo () const
Function to update the reference state thermo functions.
Additional Inherited Members
Protected Member Functions inherited from ThermoPhase
virtual void getCsvReportData (std::vector< std::string > &names, std::vector< vector_fp > &data) const
Fills names and data with the column names and species thermo properties to be included in the output of the reportCSV method.
Protected Member Functions inherited from Phase
void init (const vector_fp &mw)
void setMolecularWeight (const int k, const double mw)
Set the molecular weight of a single species to a given value.
Detailed Description
Overloads the virtual methods of class ThermoPhase to implement the incompressible equation of state.
Specification of Solution Thermodynamic Properties
The density is assumed to be constant, no matter what the concentration of the solution.
Definition at line 31 of file ConstDensityThermo.h.
Constructor & Destructor Documentation
ConstDensityThermo ()
Constructor.
Definition at line 19 of file ConstDensityThermo.cpp.
Referenced by ConstDensityThermo::duplMyselfAsThermoPhase().
ConstDensityThermo (const ConstDensityThermo & right)
Copy Constructor.
Parameters
right Object to be copied
Definition at line 24 of file ConstDensityThermo.cpp.
References ConstDensityThermo::operator=().
Member Function Documentation
ConstDensityThermo & operator= (const ConstDensityThermo & right)
Assignment Operator.
Parameters
right Object to be copied
Definition at line 30 of file ConstDensityThermo.cpp.
References ConstDensityThermo::m_cp0_R, ConstDensityThermo::m_g0_RT, ConstDensityThermo::m_h0_RT, ConstDensityThermo::m_pp, ConstDensityThermo::m_s0_R, and ConstDensityThermo::m_tlast.
Referenced by ConstDensityThermo::ConstDensityThermo().
ThermoPhase * duplMyselfAsThermoPhase () const virtual
Duplication routine for objects which inherit from ThermoPhase.
This virtual routine can be used to duplicate objects derived from ThermoPhase even if the application only has a pointer to ThermoPhase to work with.
Reimplemented from ThermoPhase.
Definition at line 47 of file ConstDensityThermo.cpp.
References ConstDensityThermo::ConstDensityThermo().
int eosType () const virtual
Returns a constant corresponding to this class's equation of state.
Reimplemented from ThermoPhase.
Definition at line 53 of file ConstDensityThermo.cpp.
doublereal enthalpy_mole () const virtual
Molar enthalpy. Units: J/kmol.
Reimplemented from ThermoPhase.
Definition at line 58 of file ConstDensityThermo.cpp.
References ConstDensityThermo::enthalpy_RT(), Cantera::GasConstant, ThermoPhase::m_spthermo, Phase::mean_X(), Phase::molarDensity(), ConstDensityThermo::pressure(), SpeciesThermo::refPressure(), and Phase::temperature().
Referenced by ConstDensityThermo::gibbs_mole().
doublereal intEnergy_mole () const virtual
Molar internal energy. Units: J/kmol.
Reimplemented from ThermoPhase.
Definition at line 66 of file ConstDensityThermo.cpp.
References ConstDensityThermo::enthalpy_RT(), Cantera::GasConstant, ThermoPhase::m_spthermo, Phase::mean_X(), Phase::molarDensity(), SpeciesThermo::refPressure(), and Phase::temperature().
doublereal entropy_mole () const virtual
Molar entropy. Units: J/kmol/K.
Reimplemented from ThermoPhase.
Definition at line 74 of file ConstDensityThermo.cpp.
References ConstDensityThermo::entropy_R(), Cantera::GasConstant, Phase::mean_X(), and Phase::sum_xlogx().
Referenced by ConstDensityThermo::gibbs_mole().
doublereal gibbs_mole () const virtual
Molar Gibbs function. Units: J/kmol.
Reimplemented from ThermoPhase.
Definition at line 80 of file ConstDensityThermo.cpp.
References ConstDensityThermo::enthalpy_mole(), ConstDensityThermo::entropy_mole(), and Phase::temperature().
doublereal cp_mole () const virtual
Molar heat capacity at constant pressure. Units: J/kmol/K.
Reimplemented from ThermoPhase.
Definition at line 85 of file ConstDensityThermo.cpp.
References ConstDensityThermo::cp_R(), Cantera::GasConstant, and Phase::mean_X().
Referenced by ConstDensityThermo::cv_mole().
doublereal cv_mole () const virtual
Molar heat capacity at constant volume. Units: J/kmol/K.
Reimplemented from ThermoPhase.
Definition at line 90 of file ConstDensityThermo.cpp.
References ConstDensityThermo::cp_mole().
doublereal pressure () const virtual
Return the thermodynamic pressure (Pa).
Reimplemented from ThermoPhase.
Definition at line 95 of file ConstDensityThermo.cpp.
References ConstDensityThermo::m_press.
Referenced by ConstDensityThermo::enthalpy_mole(), and ConstDensityThermo::getChemPotentials().
void setPressure (doublereal p) virtual
Set the internally stored pressure (Pa) at constant temperature and composition.
Parameters
p input Pressure (Pa)
Reimplemented from ThermoPhase.
Definition at line 100 of file ConstDensityThermo.cpp.
References ConstDensityThermo::m_press.
void getActivityConcentrations (doublereal * c) const virtual
This method returns an array of generalized concentrations.
\(C^a_k\) are defined such that \(a_k = C^a_k / C^0_k, \) where \(C^0_k \) is a standard concentration defined below and \(a_k \) are activities used in the thermodynamic functions. These activity (or generalized) concentrations are used by kinetics manager classes to compute the forward and reverse rates of elementary reactions. Note that they may or may not have units of concentration — they might be partial pressures, mole fractions, or surface coverages, for example.
Parameters
c Output array of generalized concentrations. The units depend upon the implementation of the reaction rate expressions within the phase.
Reimplemented from ThermoPhase.
Definition at line 105 of file ConstDensityThermo.cpp.
References Phase::getConcentrations().
void getActivityCoefficients (doublereal * ac) const virtual
Get the array of non-dimensional molar-based activity coefficients at the current solution temperature, pressure, and solution concentration.
Parameters
ac Output vector of activity coefficients. Length: m_kk.
Reimplemented from ThermoPhase.
Definition at line 110 of file ConstDensityThermo.cpp.
References Phase::m_kk.
void getChemPotentials (doublereal * mu) const virtual
Get the species chemical potentials. Units: J/kmol.
This function returns a vector of chemical potentials of the species in solution at the current temperature, pressure and mole fraction of the solution.
Parameters
mu Output vector of species chemical potentials. Length: m_kk. Units: J/kmol
Reimplemented from ThermoPhase.
Definition at line 127 of file ConstDensityThermo.cpp.
References Cantera::GasConstant, ConstDensityThermo::gibbs_RT(), Phase::m_kk, ThermoPhase::m_spthermo, Phase::molarDensity(), Phase::moleFraction(), ConstDensityThermo::pressure(), SpeciesThermo::refPressure(), Cantera::SmallNumber, and Phase::temperature().
void getStandardChemPotentials (doublereal * mu0) const virtual
Get the array of chemical potentials at unit activity for the species at their standard states at the current T and P of the solution.
These are the standard state chemical potentials \(\mu^0_k(T,P) \). The values are evaluated at the current temperature and pressure of the solution
Parameters
mu0 Output vector of chemical potentials. Length: m_kk.
Reimplemented from ThermoPhase.
Definition at line 141 of file ConstDensityThermo.cpp.
References ConstDensityThermo::getPureGibbs().
doublereal standardConcentration (size_t k = 0) const virtual
Return the standard concentration for the kth species.
The standard concentration \(C^0_k \) used to normalize the activity (i.e., generalized) concentration. In many cases, this quantity will be the same for all species in a phase - for example, for an ideal gas \(C^0_k = P/\hat R T \). For this reason, this method returns a single value, instead of an array. However, for phases in which the standard concentration is species-specific (e.g. surface species of different sizes), this method may be called with an optional parameter indicating the species.
Parameters
k Optional parameter indicating the species. The default is to assume this refers to species 0.
Returns
Returns the standard Concentration in units of m3 kmol-1.
Reimplemented from ThermoPhase.
Definition at line 117 of file ConstDensityThermo.cpp.
References Phase::molarDensity().
doublereal logStandardConc (size_t k = 0) const virtual
Natural logarithm of the standard concentration of the kth species.
Parameters
k index of the species (defaults to zero)
Reimplemented from ThermoPhase.
Definition at line 122 of file ConstDensityThermo.cpp.
References Phase::molarDensity().
virtual void getPureGibbs (doublereal * gpure) const inline virtual
Get the Gibbs functions for the standard state of the species at the current T and P of the solution.
Units are Joules/kmol
Parameters
gpure Output vector of standard state gibbs free energies Length: m_kk.
Reimplemented from ThermoPhase.
Definition at line 169 of file ConstDensityThermo.h.
References ThermoPhase::_RT(), ConstDensityThermo::gibbs_RT(), and Cantera::scale().
Referenced by ConstDensityThermo::getStandardChemPotentials().
void getEnthalpy_RT (doublereal * hrt) const inline virtual
Get the nondimensional Enthalpy functions for the species at their standard states at the current T and P of the solution.
Parameters
hrt Output vector of nondimensional standard state enthalpies. Length: m_kk.
Reimplemented from ThermoPhase.
Definition at line 180 of file ConstDensityThermo.h.
References ConstDensityThermo::enthalpy_RT().
void getEntropy_R (doublereal * sr) const inline virtual
Get the array of nondimensional Entropy functions for the standard state species at the current T and P of the solution.
Parameters
sr Output vector of nondimensional standard state entropies. Length: m_kk.
Reimplemented from ThermoPhase.
Definition at line 191 of file ConstDensityThermo.h.
References ConstDensityThermo::entropy_R().
virtual void getGibbs_RT (doublereal * grt) const inline virtual
Get the nondimensional Gibbs functions for the species in their standard states at the current T and P of the solution.
Parameters
grt Output vector of nondimensional standard state gibbs free energies Length: m_kk.
Reimplemented from ThermoPhase.
Definition at line 202 of file ConstDensityThermo.h.
References ConstDensityThermo::gibbs_RT().
void getCp_R (doublereal * cpr) const inline virtual
Get the nondimensional Heat Capacities at constant pressure for the species standard states at the current T and P of the solution.
Parameters
cpr Output vector of nondimensional standard state heat capacities Length: m_kk.
Reimplemented from ThermoPhase.
Definition at line 214 of file ConstDensityThermo.h.
References ConstDensityThermo::cp_R().
const vector_fp& enthalpy_RT () const inline
Returns a reference to the vector of nondimensional enthalpies of the reference state at the current temperature of the solution and the reference pressure for the species.
Definition at line 222 of file ConstDensityThermo.h.
References ConstDensityThermo::_updateThermo(), and ConstDensityThermo::m_h0_RT.
Referenced by ConstDensityThermo::enthalpy_mole(), ConstDensityThermo::getEnthalpy_RT(), and ConstDensityThermo::intEnergy_mole().
const vector_fp& gibbs_RT () const inline
Returns a reference to the vector of nondimensional Gibbs Free Energies of the reference state at the current temperature of the solution and the reference pressure for the species.
Definition at line 230 of file ConstDensityThermo.h.
References ConstDensityThermo::_updateThermo(), and ConstDensityThermo::m_g0_RT.
Referenced by ConstDensityThermo::getChemPotentials(), ConstDensityThermo::getGibbs_RT(), and ConstDensityThermo::getPureGibbs().
const vector_fp& entropy_R () const inline
Returns a reference to the vector of nondimensional entropies of the reference state at the current temperature of the solution and the reference pressure for each species.
Definition at line 238 of file ConstDensityThermo.h.
References ConstDensityThermo::_updateThermo(), and ConstDensityThermo::m_s0_R.
Referenced by ConstDensityThermo::entropy_mole(), and ConstDensityThermo::getEntropy_R().
const vector_fp& cp_R () const inline
Returns a reference to the vector of nondimensional constant pressure heat capacities of the reference state at the current temperature of the solution and reference pressure for each species.
Definition at line 247 of file ConstDensityThermo.h.
References ConstDensityThermo::_updateThermo(), and ConstDensityThermo::m_cp0_R.
Referenced by ConstDensityThermo::cp_mole(), and ConstDensityThermo::getCp_R().
void initThermo () virtual
Initialize the ThermoPhase object after all species have been set up.
Initialize.
This method is provided to allow subclasses to perform any initialization required after all species have been added. For example, it might be used to resize internal work arrays that must have an entry for each species. The base class implementation does nothing, and subclasses that do not require initialization do not need to overload this method. When importing a CTML phase description, this method is called from ThermoPhase::initThermoXML(), which is called from importPhase(), just prior to returning from function importPhase().
See Also
importCTML.cpp
Reimplemented from ThermoPhase.
Definition at line 146 of file ConstDensityThermo.cpp.
References ConstDensityThermo::m_cp0_R, ConstDensityThermo::m_g0_RT, ConstDensityThermo::m_h0_RT, Phase::m_kk, ConstDensityThermo::m_pp, ConstDensityThermo::m_s0_R, and Phase::nSpecies().
void setToEquilState (const doublereal * lambda_RT) virtual
This method is used by the ChemEquil equilibrium solver.
It sets the state such that the chemical potentials satisfy
\[ \frac{\mu_k}{\hat R T} = \sum_m A_{k,m} \left(\frac{\lambda_m} {\hat R T}\right) \]
where \(\lambda_m \) is the element potential of element m. The temperature is unchanged. Any phase (ideal or not) that implements this method can be equilibrated by ChemEquil.
Parameters
lambda_RT Input vector of dimensionless element potentials The length is equal to nElements().
Reimplemented from ThermoPhase.
Definition at line 157 of file ConstDensityThermo.cpp.
virtual void setParameters (int n, doublereal *const c) inline virtual
Set the equation of state parameters.
The number and meaning of these depends on the subclass.
Parameters
n number of parameters
c array of n coefficients
Deprecated:
Use setDensity()
Reimplemented from ThermoPhase.
Definition at line 294 of file ConstDensityThermo.h.
References Phase::setDensity(), and Cantera::warn_deprecated().
virtual void getParameters (int & n, doublereal *const c) const inline virtual
Get the equation of state parameters in a vector.
The number and meaning of these depends on the subclass.
Parameters
n number of parameters
c array of n coefficients
Deprecated:
Use density()
Reimplemented from ThermoPhase.
Definition at line 308 of file ConstDensityThermo.h.
References Phase::density(), and Cantera::warn_deprecated().
void setParametersFromXML (const XML_Node & eosdata) virtual
Set equation of state parameter values from XML entries.
This method is called by function importPhase() in file importCTML.cpp when processing a phase definition in an input file. It should be overloaded in subclasses to set any parameters that are specific to that particular phase model. Note, this method is called before the phase is initialized with elements and/or species.
Parameters
eosdata An XML_Node object corresponding to the "thermo" entry for this phase in the input file.
Reimplemented from ThermoPhase.
Definition at line 176 of file ConstDensityThermo.cpp.
References XML_Node::_require(), ctml::getFloat(), and Phase::setDensity().
void _updateThermo () const private
Function to update the reference state thermo functions.
Definition at line 162 of file ConstDensityThermo.cpp.
References ConstDensityThermo::m_cp0_R, ConstDensityThermo::m_g0_RT, ConstDensityThermo::m_h0_RT, Phase::m_kk, ConstDensityThermo::m_s0_R, ThermoPhase::m_spthermo, ConstDensityThermo::m_tlast, Phase::temperature(), and SpeciesThermo::update().
Referenced by ConstDensityThermo::cp_R(), ConstDensityThermo::enthalpy_RT(), ConstDensityThermo::entropy_R(), and ConstDensityThermo::gibbs_RT().
Member Data Documentation
doublereal m_tlast mutable protected
last value of the temperature processed by reference state
Definition at line 332 of file ConstDensityThermo.h.
Referenced by ConstDensityThermo::_updateThermo(), and ConstDensityThermo::operator=().
vector_fp m_h0_RT mutable protected
Temporary storage for dimensionless reference state enthalpies.
Definition at line 335 of file ConstDensityThermo.h.
Referenced by ConstDensityThermo::_updateThermo(), ConstDensityThermo::enthalpy_RT(), ConstDensityThermo::initThermo(), and ConstDensityThermo::operator=().
vector_fp m_cp0_R mutable protected
Temporary storage for dimensionless reference state heat capacities.
Definition at line 338 of file ConstDensityThermo.h.
Referenced by ConstDensityThermo::_updateThermo(), ConstDensityThermo::cp_R(), ConstDensityThermo::initThermo(), and ConstDensityThermo::operator=().
vector_fp m_g0_RT mutable protected
Temporary storage for dimensionless reference state gibbs energies.
Definition at line 341 of file ConstDensityThermo.h.
Referenced by ConstDensityThermo::_updateThermo(), ConstDensityThermo::gibbs_RT(), ConstDensityThermo::initThermo(), and ConstDensityThermo::operator=().
vector_fp m_s0_R mutable protected
Temporary storage for dimensionless reference state entropies.
Definition at line 344 of file ConstDensityThermo.h.
Referenced by ConstDensityThermo::_updateThermo(), ConstDensityThermo::entropy_R(), ConstDensityThermo::initThermo(), and ConstDensityThermo::operator=().
vector_fp m_pp mutable protected
Temporary array containing internally calculated partial pressures.
Definition at line 347 of file ConstDensityThermo.h.
Referenced by ConstDensityThermo::initThermo(), and ConstDensityThermo::operator=().
doublereal m_press protected
Current pressure (Pa)
Definition at line 350 of file ConstDensityThermo.h.
Referenced by ConstDensityThermo::pressure(), and ConstDensityThermo::setPressure().
The documentation for this class was generated from the following files:
ConstDensityThermo.h
ConstDensityThermo.cpp