Cantera: LTPspecies_Const Class Reference
LTPspecies_Const Class Reference
Class LTPspecies_Const holds transport parameters for a specific liquid-phase species (LTPspecies) when the transport property is just a constant value.
#include <LTPspecies.h>
Public Member Functions
LTPspecies_Const (const XML_Node &propNode, const std::string name, TransportPropertyType tp_ind, const thermo_t *const thermo)
Construct an LTPspecies object for a liquid transport property expressed as a constant value.
LTPspecies_Const (const LTPspecies_Const &right)
LTPspecies_Const & operator= (const LTPspecies_Const &right)
virtual LTPspecies * duplMyselfAsLTPspecies () const
Duplication routine.
doublereal getSpeciesTransProp ()
Returns the pure species transport property.
Public Member Functions inherited from LTPspecies
LTPspecies (const XML_Node *const propNode=0, const std::string name="-", TransportPropertyType tp_ind=TP_UNKNOWN, const thermo_t *thermo=0)
Construct an LTPspecies object for a liquid transport property.
LTPspecies (const LTPspecies &right)
LTPspecies & operator= (const LTPspecies &right)
virtual bool checkPositive () const
Check to see if the property evaluation will be positive.
doublereal getMixWeight () const
Return the weight mixture.
Additional Inherited Members
Protected Attributes inherited from LTPspecies
std::string m_speciesName
Species Name.
LTPTemperatureDependenceType m_model
Model type for the temperature dependence.
TransportPropertyType m_property
enum indicating which property this is (i.e viscosity)
vector_fp m_coeffs
Model temperature-dependence ceofficients.
const thermo_t * m_thermo
Pointer to a const thermo object to get current temperature.
doublereal m_mixWeight
Weighting used for mixing.
Detailed Description
Class LTPspecies_Const holds transport parameters for a specific liquid-phase species (LTPspecies) when the transport property is just a constant value.
As an example of the input required for LTPspecies_Const consider the following XML fragment
*    <species>
*      <!-- thermodynamic properties -->
*      <transport>
*        <hydrodynamicRadius model="Constant" units="A">
*            1.000
*        </hydrodynamicRadius>
*        <!-- other transport properties -->
*      </transport>
*    </species>
*
Definition at line 182 of file LTPspecies.h.
Constructor & Destructor Documentation
LTPspecies_Const (const XML_Node & propNode, const std::string name, TransportPropertyType tp_ind, const thermo_t *const thermo)
Construct an LTPspecies object for a liquid transport property expressed as a constant value.
The transport property is constructed from the XML node, <propNode>, that is a child of the <transport> node and specifies a type of transport property (like viscosity).
Parameters
propNode Reference to the XML node that contains the property information.
name String containing the species name
tp_ind enum TransportPropertyType containing the property id that this object is creating a parameterization for (e.g., viscosity)
thermo const pointer to the ThermoPhase object, which is used to find the temperature.
Definition at line 116 of file LTPspecies.cpp.
References ctml::getFloatCurrent(), LTPspecies::m_coeffs, LTPspecies::m_model, and XML_Node::name().
Referenced by LTPspecies_Const::duplMyselfAsLTPspecies().
Member Function Documentation
LTPspecies * duplMyselfAsLTPspecies () const virtual
Duplication routine.
Returns
Returns a copy of this routine as a pointer to LTPspecies
Reimplemented from LTPspecies.
Definition at line 143 of file LTPspecies.cpp.
References LTPspecies_Const::LTPspecies_Const().
doublereal getSpeciesTransProp () virtual
Returns the pure species transport property.
The pure species transport property (i.e. pure species viscosity) is returned. Any temperature and composition dependence will be adjusted internally according to the information provided.
Reimplemented from LTPspecies.
Definition at line 148 of file LTPspecies.cpp.
References LTPspecies::m_coeffs.
The documentation for this class was generated from the following files:
LTPspecies.h
LTPspecies.cpp