Cantera: WaterTransport Class Reference
WaterTransport Class Reference
Transport Properties for Species in Phases
Transport Parameters for pure water.
#include <WaterTransport.h>
Public Member Functions
WaterTransport (thermo_t *thermo=0, int ndim=1)
default constructor
WaterTransport (const WaterTransport &right)
WaterTransport & operator= (const WaterTransport &right)
virtual Transport * duplMyselfAsTransport () const
Duplication routine for objects which inherit from Transport.
virtual int model () const
Transport model.
virtual doublereal viscosity ()
Returns the viscosity of water at the current conditions (kg/m/s)
virtual doublereal bulkViscosity ()
The bulk viscosity in Pa-s.
virtual doublereal thermalConductivity ()
Returns the thermal conductivity of water at the current conditions (W/m/K)
Public Member Functions inherited from Transport
Transport (thermo_t *thermo=0, size_t ndim=1)
Constructor.
Transport (const Transport &right)
Transport & operator= (const Transport &right)
thermo_t & thermo ()
bool ready ()
void setNDim (const int ndim)
Set the number of dimensions to be expected in flux expressions.
size_t nDim () const
Return the number of dimensions in flux expressions.
void checkSpeciesIndex (size_t k) const
Check that the specified species index is in range Throws an exception if k is greater than nSpecies()
void checkSpeciesArraySize (size_t kk) const
Check that an array size is at least nSpecies() Throws an exception if kk is less than nSpecies().
virtual doublereal getElectricConduct ()
Compute the mixture electrical conductivity (S m-1) at the current conditions of the phase (Siemens m-1)
virtual void getElectricCurrent (int ndim, const doublereal *grad_T, int ldx, const doublereal *grad_X, int ldf, const doublereal *grad_V, doublereal *current)
Compute the electric current density in A/m^2.
virtual void getSpeciesFluxes (size_t ndim, const doublereal *const grad_T, size_t ldx, const doublereal *const grad_X, size_t ldf, doublereal *const fluxes)
Get the species diffusive mass fluxes wrt to the specified solution averaged velocity, given the gradients in mole fraction and temperature.
virtual void getSpeciesFluxesES (size_t ndim, const doublereal *grad_T, size_t ldx, const doublereal *grad_X, size_t ldf, const doublereal *grad_Phi, doublereal *fluxes)
Get the species diffusive mass fluxes wrt to the mass averaged velocity, given the gradients in mole fraction, temperature and electrostatic potential.
virtual void getSpeciesVdiff (size_t ndim, const doublereal *grad_T, int ldx, const doublereal *grad_X, int ldf, doublereal *Vdiff)
Get the species diffusive velocities wrt to the mass averaged velocity, given the gradients in mole fraction and temperature.
virtual void getSpeciesVdiffES (size_t ndim, const doublereal *grad_T, int ldx, const doublereal *grad_X, int ldf, const doublereal *grad_Phi, doublereal *Vdiff)
Get the species diffusive velocities wrt to the mass averaged velocity, given the gradients in mole fraction, temperature, and electrostatic potential.
virtual void getMolarFluxes (const doublereal *const state1, const doublereal *const state2, const doublereal delta, doublereal *const cfluxes)
Get the molar fluxes [kmol/m^2/s], given the thermodynamic state at two nearby points.
virtual void getMassFluxes (const doublereal *state1, const doublereal *state2, doublereal delta, doublereal *mfluxes)
Get the mass fluxes [kg/m^2/s], given the thermodynamic state at two nearby points.
virtual void getThermalDiffCoeffs (doublereal *const dt)
Return a vector of Thermal diffusion coefficients [kg/m/sec].
virtual void getBinaryDiffCoeffs (const size_t ld, doublereal *const d)
Returns the matrix of binary diffusion coefficients [m^2/s].
virtual void getMultiDiffCoeffs (const size_t ld, doublereal *const d)
Return the Multicomponent diffusion coefficients. Units: [m^2/s].
virtual void getMixDiffCoeffs (doublereal *const d)
Returns a vector of mixture averaged diffusion coefficients.
virtual void getMixDiffCoeffsMole (doublereal *const d)
Returns a vector of mixture averaged diffusion coefficients.
virtual void getMixDiffCoeffsMass (doublereal *const d)
Returns a vector of mixture averaged diffusion coefficients.
virtual void setParameters (const int type, const int k, const doublereal *const p)
Set model parameters for derived classes.
void setVelocityBasis (VelocityBasis ivb)
Sets the velocity basis.
VelocityBasis getVelocityBasis () const
Gets the velocity basis.
virtual void getSpeciesViscosities (doublereal *const visc)
Returns the pure species viscosities.
virtual doublereal ionConductivity ()
The ionic conductivity in 1/ohm/m.
virtual void getSpeciesIonConductivity (doublereal *const ionCond)
Returns the pure species ionic conductivity.
virtual void mobilityRatio (double *mobRat)
Returns the pointer to the mobility ratios of the species in the phase.
virtual void getSpeciesMobilityRatio (double **mobRat)
Returns the pure species limit of the mobility ratios.
virtual void selfDiffusion (doublereal *const selfDiff)
Returns the self diffusion coefficients of the species in the phase.
virtual void getSpeciesSelfDiffusion (double **selfDiff)
Returns the pure species self diffusion in solution of each species.
virtual doublereal electricalConductivity ()
virtual void getMobilities (doublereal *const mobil_e)
Get the Electrical mobilities (m^2/V/s).
virtual void getFluidMobilities (doublereal *const mobil_f)
Get the fluid mobilities (s kmol/kg).
virtual bool initSolid (SolidTransportData &tr)
Called by TransportFactory to set parameters.
virtual void setThermo (thermo_t &thermo)
Specifies the ThermoPhase object.
Private Member Functions
void initTP ()
Routine to do some common initializations at the start of using this routine.
Private Attributes
WaterPropsIAPWS * m_sub
Pointer to the WaterPropsIAPWS object, which does the actual calculations for the real equation of state.
WaterProps * m_waterProps
Pointer to the WaterProps object.
PDSS_Water * m_waterPDSS
Pressure dependent standard state object for water.
Additional Inherited Members
Protected Member Functions inherited from Transport
virtual bool initGas (GasTransportParams &tr)
Called by TransportFactory to set parameters.
virtual bool initLiquid (LiquidTransportParams &tr)
Called by TransportFactory to set parameters.
void finalize ()
Enable the transport object for use.
Protected Attributes inherited from Transport
thermo_t * m_thermo
pointer to the object representing the phase
bool m_ready
true if finalize has been called
size_t m_nsp
Number of species.
size_t m_nDim
Number of dimensions used in flux expressions.
int m_velocityBasis
Velocity basis from which diffusion velocities are computed.
Detailed Description
Transport Parameters for pure water.
Definition at line 31 of file WaterTransport.h.
Constructor & Destructor Documentation
WaterTransport (thermo_t * thermo = 0, int ndim = 1)
default constructor
Parameters
thermo ThermoPhase object that represents the phase. Defaults to zero
ndim Number of dimensions of the flux expressions. Defaults to a value of one.
Definition at line 19 of file WaterTransport.cpp.
References WaterTransport::initTP().
Referenced by WaterTransport::duplMyselfAsTransport().
Member Function Documentation
Transport * duplMyselfAsTransport () const virtual
Duplication routine for objects which inherit from Transport.
This virtual routine can be used to duplicate objects derived from Transport even if the application only has a pointer to Transport to work with.
These routines are basically wrappers around the derived copy constructor.
Reimplemented from Transport.
Definition at line 45 of file WaterTransport.cpp.
References WaterTransport::WaterTransport().
virtual int model () const inline virtual
Transport model.
The transport model is the set of equations used to compute the transport properties. This method returns an integer flag that identifies the transport model implemented. The base class returns 0.
Reimplemented from Transport.
Definition at line 48 of file WaterTransport.h.
doublereal viscosity () virtual
Returns the viscosity of water at the current conditions (kg/m/s)
This function calculates the value of the viscosity of pure water at the current T and P.
The formulas used are from the paper
J. V. Sengers, J. T. R. Watson, "Improved International Formulations for the Viscosity and Thermal Conductivity of Water Substance", J. Phys. Chem. Ref. Data, 15, 1291 (1986).
The formulation is accurate for all temperatures and pressures, for steam and for water, even near the critical point. Pressures above 500 MPa and temperature above 900 C are suspect.
Reimplemented from Transport.
Definition at line 83 of file WaterTransport.cpp.
References WaterTransport::m_waterProps, and WaterProps::viscosityWater().
virtual doublereal bulkViscosity () inline virtual
The bulk viscosity in Pa-s.
The bulk viscosity is only non-zero in rare cases. Most transport managers either overload this method to return zero, or do not implement it, in which case an exception is thrown if called.
Reimplemented from Transport.
Definition at line 70 of file WaterTransport.h.
doublereal thermalConductivity () virtual
Returns the thermal conductivity of water at the current conditions (W/m/K)
This function calculates the value of the thermal conductivity of water at the current T and P.
The formulas used are from the paper J. V. Sengers, J. T. R. Watson, "Improved International Formulations for the Viscosity and Thermal Conductivity of Water Substance", J. Phys. Chem. Ref. Data, 15, 1291 (1986).
The formulation is accurate for all temperatures and pressures, for steam and for water, even near the critical point. Pressures above 500 MPa and temperature above 900 C are suspect.
Reimplemented from Transport.
Definition at line 88 of file WaterTransport.cpp.
References WaterTransport::m_waterProps, and WaterProps::thermalConductivityWater().
void initTP () private
Routine to do some common initializations at the start of using this routine.
Definition at line 50 of file WaterTransport.cpp.
References AssertTrace, PDSS_Water::getWater(), WaterSSTP::getWater(), PDSS_Water::getWaterProps(), WaterSSTP::getWaterProps(), WaterTransport::m_sub, Transport::m_thermo, WaterTransport::m_waterPDSS, and WaterTransport::m_waterProps.
Referenced by WaterTransport::WaterTransport().
Member Data Documentation
WaterPropsIAPWS* m_sub mutable private
Pointer to the WaterPropsIAPWS object, which does the actual calculations for the real equation of state.
This object owns m_sub
Definition at line 102 of file WaterTransport.h.
Referenced by WaterTransport::initTP().
WaterProps* m_waterProps private
Pointer to the WaterProps object.
This class is used to house several approximation routines for properties of water.
This object owns m_waterProps, and the WaterPropsIAPWS object used by WaterProps is m_sub, which is defined above.
Definition at line 112 of file WaterTransport.h.
Referenced by WaterTransport::initTP(), WaterTransport::thermalConductivity(), and WaterTransport::viscosity().
PDSS_Water* m_waterPDSS private
Pressure dependent standard state object for water.
We assume that species 0 is water, with a PDSS_Water object.
Definition at line 118 of file WaterTransport.h.
Referenced by WaterTransport::initTP().
The documentation for this class was generated from the following files:
WaterTransport.h
WaterTransport.cpp