Cantera: SingleSpeciesTP Class Reference
SingleSpeciesTP Class Reference
Thermodynamic Properties
The SingleSpeciesTP class is a filter class for ThermoPhase.
#include <SingleSpeciesTP.h>
Public Member Functions
SingleSpeciesTP ()
Base empty constructor.
SingleSpeciesTP (const SingleSpeciesTP &right)
Copy constructor.
SingleSpeciesTP & operator= (const SingleSpeciesTP &right)
Assignment operator.
ThermoPhase * duplMyselfAsThermoPhase () const
Duplication function.
virtual int eosType () const
Returns the equation of state type flag.
virtual void initThermo ()
Public Member Functions inherited from ThermoPhase
ThermoPhase ()
Constructor.
virtual ~ThermoPhase ()
Destructor. Deletes the species thermo manager.
ThermoPhase (const ThermoPhase &right)
Copy Constructor for the ThermoPhase object.
ThermoPhase & operator= (const ThermoPhase &right)
Assignment operator.
doublereal _RT () const
Return the Gas Constant multiplied by the current temperature.
virtual doublereal refPressure () const
Returns the reference pressure in Pa.
virtual doublereal minTemp (size_t k=npos) const
Minimum temperature for which the thermodynamic data for the species or phase are valid.
doublereal Hf298SS (const int k) const
Report the 298 K Heat of Formation of the standard state of one species (J kmol-1)
virtual void modifyOneHf298SS (const int k, const doublereal Hf298New)
Modify the value of the 298 K Heat of Formation of one species in the phase (J kmol-1)
virtual doublereal maxTemp (size_t k=npos) const
Maximum temperature for which the thermodynamic data for the species are valid.
bool chargeNeutralityNecessary () const
Returns the chargeNeutralityNecessity boolean.
virtual doublereal cv_vib (int, double) const
virtual doublereal pressure () const
Return the thermodynamic pressure (Pa).
virtual void setPressure (doublereal p)
Set the internally stored pressure (Pa) at constant temperature and composition.
virtual doublereal isothermalCompressibility () const
Returns the isothermal compressibility. Units: 1/Pa.
virtual doublereal thermalExpansionCoeff () const
Return the volumetric thermal expansion coefficient. Units: 1/K.
void setElectricPotential (doublereal v)
Set the electric potential of this phase (V).
doublereal electricPotential () const
Returns the electric potential of this phase (V).
virtual int activityConvention () const
This method returns the convention used in specification of the activities, of which there are currently two, molar- and molality-based conventions.
virtual int standardStateConvention () const
This method returns the convention used in specification of the standard state, of which there are currently two, temperature based, and variable pressure based.
virtual void getActivityConcentrations (doublereal *c) const
This method returns an array of generalized concentrations.
virtual doublereal standardConcentration (size_t k=0) const
Return the standard concentration for the kth species.
virtual doublereal logStandardConc (size_t k=0) const
Natural logarithm of the standard concentration of the kth species.
virtual void getUnitsStandardConc (double *uA, int k=0, int sizeUA=6) const
Returns the units of the standard and generalized concentrations.
virtual void getLnActivityCoefficients (doublereal *lnac) const
Get the array of non-dimensional molar-based ln activity coefficients at the current solution temperature, pressure, and solution concentration.
void getElectrochemPotentials (doublereal *mu) const
Get the species electrochemical potentials.
virtual void getdPartialMolarVolumes_dT (doublereal *d_vbar_dT) const
Return an array of derivatives of partial molar volumes wrt temperature for the species in the mixture.
virtual void getdPartialMolarVolumes_dP (doublereal *d_vbar_dP) const
Return an array of derivatives of partial molar volumes wrt pressure for the species in the mixture.
virtual void getStandardChemPotentials (doublereal *mu) const
Get the array of chemical potentials at unit activity for the species at their standard states at the current T and P of the solution.
virtual void getEnthalpy_RT (doublereal *hrt) const
Get the nondimensional Enthalpy functions for the species at their standard states at the current T and P of the solution.
virtual void getEntropy_R (doublereal *sr) const
Get the array of nondimensional Entropy functions for the standard state species at the current T and P of the solution.
virtual void getGibbs_RT (doublereal *grt) const
Get the nondimensional Gibbs functions for the species in their standard states at the current T and P of the solution.
virtual void getIntEnergy_RT (doublereal *urt) const
Returns the vector of nondimensional Internal Energies of the standard state species at the current T and P of the solution.
virtual void getCp_R (doublereal *cpr) const
Get the nondimensional Heat Capacities at constant pressure for the species standard states at the current T and P of the solution.
virtual void getdStandardVolumes_dT (doublereal *d_vol_dT) const
Get the derivative of the molar volumes of the species standard states wrt temperature at the current T and P of the solution.
virtual void getdStandardVolumes_dP (doublereal *d_vol_dP) const
Get the derivative molar volumes of the species standard states wrt pressure at the current T and P of the solution.
virtual void getIntEnergy_RT_ref (doublereal *urt) const
Returns the vector of nondimensional internal Energies of the reference state at the current temperature of the solution and the reference pressure for each species.
virtual void getStandardVolumes_ref (doublereal *vol) const
Get the molar volumes of the species reference states at the current T and P_ref of the solution.
virtual void setReferenceComposition (const doublereal *const x)
Sets the reference composition.
virtual void getReferenceComposition (doublereal *const x) const
Gets the reference composition.
doublereal enthalpy_mass () const
Specific enthalpy.
doublereal intEnergy_mass () const
Specific internal energy.
doublereal entropy_mass () const
Specific entropy.
doublereal gibbs_mass () const
Specific Gibbs function.
doublereal cp_mass () const
Specific heat at constant pressure.
doublereal cv_mass () const
Specific heat at constant volume.
virtual void setToEquilState (const doublereal *lambda_RT)
This method is used by the ChemEquil equilibrium solver.
void setElementPotentials (const vector_fp &lambda)
Stores the element potentials in the ThermoPhase object.
bool getElementPotentials (doublereal *lambda) const
Returns the element potentials stored in the ThermoPhase object.
virtual doublereal critTemperature () const
Critical temperature (K).
virtual doublereal critPressure () const
Critical pressure (Pa).
virtual doublereal critDensity () const
Critical density (kg/m3).
void saveSpeciesData (const size_t k, const XML_Node *const data)
Store a reference pointer to the XML tree containing the species data for this phase.
const std::vector< const
XML_Node * > & speciesData () const
Return a pointer to the vector of XML nodes containing the species data for this phase.
void setSpeciesThermo (SpeciesThermo *spthermo)
Install a species thermodynamic property manager.
virtual SpeciesThermo & speciesThermo (int k=-1)
Return a changeable reference to the calculation manager for species reference-state thermodynamic properties.
virtual void initThermoFile (const std::string &inputFile, const std::string &id)
virtual void initThermoXML (XML_Node &phaseNode, const std::string &id)
Import and initialize a ThermoPhase object using an XML tree.
virtual void installSlavePhases (Cantera::XML_Node *phaseNode)
Add in species from Slave phases.
virtual void setStateFromXML (const XML_Node &state)
Set the initial state of the phase to the conditions specified in the state XML element.
virtual void getdlnActCoeffds (const doublereal dTds, const doublereal *const dXds, doublereal *dlnActCoeffds) const
Get the change in activity coefficients wrt changes in state (temp, mole fraction, etc) along a line in parameter space or along a line in physical space.
virtual void getdlnActCoeffdlnX_diag (doublereal *dlnActCoeffdlnX_diag) const
Get the array of ln mole fraction derivatives of the log activity coefficients - diagonal component only.
virtual void getdlnActCoeffdlnN_diag (doublereal *dlnActCoeffdlnN_diag) const
Get the array of log species mole number derivatives of the log activity coefficients.
virtual void getdlnActCoeffdlnN (const size_t ld, doublereal *const dlnActCoeffdlnN)
Get the array of derivatives of the log activity coefficients with respect to the log of the species mole numbers.
virtual void getdlnActCoeffdlnN_numderiv (const size_t ld, doublereal *const dlnActCoeffdlnN)
virtual std::string report (bool show_thermo=true) const
returns a summary of the state of the phase as a string
virtual void reportCSV (std::ofstream &csvFile) const
returns a summary of the state of the phase to a comma separated file.
virtual void setState_TP (doublereal t, doublereal p)
Set the temperature (K) and pressure (Pa)
Public Member Functions inherited from Phase
Phase ()
Default constructor.
virtual ~Phase ()
Destructor.
Phase (const Phase &right)
Copy Constructor.
Phase & operator= (const Phase &right)
Assignment operator.
XML_Node & xml ()
Returns a reference to the XML_Node stored for the phase.
void saveState (vector_fp &state) const
Save the current internal state of the phase Write to vector 'state' the current internal state.
void saveState (size_t lenstate, doublereal *state) const
Write to array 'state' the current internal state.
void restoreState (const vector_fp &state)
Restore a state saved on a previous call to saveState.
void restoreState (size_t lenstate, const doublereal *state)
Restore the state of the phase from a previously saved state vector.
doublereal molecularWeight (size_t k) const
Molecular weight of species k.
void getMolecularWeights (vector_fp &weights) const
Copy the vector of molecular weights into vector weights.
void getMolecularWeights (doublereal *weights) const
Copy the vector of molecular weights into array weights.
const vector_fp & molecularWeights () const
Return a const reference to the internal vector of molecular weights.
doublereal size (size_t k) const
This routine returns the size of species k.
doublereal charge (size_t k) const
Dimensionless electrical charge of a single molecule of species k The charge is normalized by the the magnitude of the electron charge.
doublereal chargeDensity () const
Charge density [C/m^3].
size_t nDim () const
Returns the number of spatial dimensions (1, 2, or 3)
void setNDim (size_t ndim)
Set the number of spatial dimensions (1, 2, or 3).
virtual void freezeSpecies ()
Call when finished adding species.
bool speciesFrozen ()
True if freezeSpecies has been called.
virtual bool ready () const
int stateMFNumber () const
Return the State Mole Fraction Number.
std::string id () const
Return the string id for the phase.
void setID (const std::string &id)
Set the string id for the phase.
std::string name () const
Return the name of the phase.
void setName (const std::string &nm)
Sets the string name for the phase.
std::string elementName (size_t m) const
Name of the element with index m.
size_t elementIndex (const std::string &name) const
Return the index of element named 'name'.
const std::vector< std::string > & elementNames () const
Return a read-only reference to the vector of element names.
doublereal atomicWeight (size_t m) const
Atomic weight of element m.
doublereal entropyElement298 (size_t m) const
Entropy of the element in its standard state at 298 K and 1 bar.
int atomicNumber (size_t m) const
Atomic number of element m.
int elementType (size_t m) const
Return the element constraint type Possible types include:
int changeElementType (int m, int elem_type)
Change the element type of the mth constraint Reassigns an element type.
const vector_fp & atomicWeights () const
Return a read-only reference to the vector of atomic weights.
size_t nElements () const
Number of elements.
void checkElementIndex (size_t m) const
Check that the specified element index is in range Throws an exception if m is greater than nElements()-1.
void checkElementArraySize (size_t mm) const
Check that an array size is at least nElements() Throws an exception if mm is less than nElements().
doublereal nAtoms (size_t k, size_t m) const
Number of atoms of element m in species k.
void getAtoms (size_t k, double *atomArray) const
Get a vector containing the atomic composition of species k.
size_t speciesIndex (const std::string &name) const
Returns the index of a species named 'name' within the Phase object.
std::string speciesName (size_t k) const
Name of the species with index k.
std::string speciesSPName (int k) const
Returns the expanded species name of a species, including the phase name This is guaranteed to be unique within a Cantera problem.
const std::vector< std::string > & speciesNames () const
Return a const reference to the vector of species names.
size_t nSpecies () const
Returns the number of species in the phase.
void checkSpeciesIndex (size_t k) const
Check that the specified species index is in range Throws an exception if k is greater than nSpecies()-1.
void checkSpeciesArraySize (size_t kk) const
Check that an array size is at least nSpecies() Throws an exception if kk is less than nSpecies().
void setMoleFractionsByName (compositionMap &xMap)
Set the species mole fractions by name.
void setMoleFractionsByName (const std::string &x)
Set the mole fractions of a group of species by name.
void setMassFractionsByName (compositionMap &yMap)
Set the species mass fractions by name.
void setMassFractionsByName (const std::string &x)
Set the species mass fractions by name.
void setState_TRX (doublereal t, doublereal dens, const doublereal *x)
Set the internally stored temperature (K), density, and mole fractions.
void setState_TRX (doublereal t, doublereal dens, compositionMap &x)
Set the internally stored temperature (K), density, and mole fractions.
void setState_TRY (doublereal t, doublereal dens, const doublereal *y)
Set the internally stored temperature (K), density, and mass fractions.
void setState_TRY (doublereal t, doublereal dens, compositionMap &y)
Set the internally stored temperature (K), density, and mass fractions.
void setState_TNX (doublereal t, doublereal n, const doublereal *x)
Set the internally stored temperature (K), molar density (kmol/m^3), and mole fractions.
void setState_TR (doublereal t, doublereal rho)
Set the internally stored temperature (K) and density (kg/m^3)
void setState_TX (doublereal t, doublereal *x)
Set the internally stored temperature (K) and mole fractions.
void setState_TY (doublereal t, doublereal *y)
Set the internally stored temperature (K) and mass fractions.
void setState_RX (doublereal rho, doublereal *x)
Set the density (kg/m^3) and mole fractions.
void setState_RY (doublereal rho, doublereal *y)
Set the density (kg/m^3) and mass fractions.
void getMoleFractionsByName (compositionMap &x) const
Get the mole fractions by name.
doublereal moleFraction (size_t k) const
Return the mole fraction of a single species.
doublereal moleFraction (const std::string &name) const
Return the mole fraction of a single species.
doublereal massFraction (size_t k) const
Return the mass fraction of a single species.
doublereal massFraction (const std::string &name) const
Return the mass fraction of a single species.
void getMoleFractions (doublereal *const x) const
Get the species mole fraction vector.
virtual void setMoleFractions (const doublereal *const x)
Set the mole fractions to the specified values There is no restriction on the sum of the mole fraction vector.
virtual void setMoleFractions_NoNorm (const doublereal *const x)
Set the mole fractions to the specified values without normalizing.
void getMassFractions (doublereal *const y) const
Get the species mass fractions.
const doublereal * massFractions () const
Return a const pointer to the mass fraction array.
virtual void setMassFractions (const doublereal *const y)
Set the mass fractions to the specified values and normalize them.
virtual void setMassFractions_NoNorm (const doublereal *const y)
Set the mass fractions to the specified values without normalizing.
void getConcentrations (doublereal *const c) const
Get the species concentrations (kmol/m^3).
doublereal concentration (const size_t k) const
Concentration of species k.
virtual void setConcentrations (const doublereal *const conc)
Set the concentrations to the specified values within the phase.
const doublereal * moleFractdivMMW () const
Returns a const pointer to the start of the moleFraction/MW array.
doublereal temperature () const
Temperature (K).
virtual doublereal density () const
Density (kg/m^3).
doublereal molarDensity () const
Molar density (kmol/m^3).
doublereal molarVolume () const
Molar volume (m^3/kmol).
virtual void setDensity (const doublereal density_)
Set the internally stored density (kg/m^3) of the phase Note the density of a phase is an independent variable.
virtual void setMolarDensity (const doublereal molarDensity)
Set the internally stored molar density (kmol/m^3) of the phase.
virtual void setTemperature (const doublereal temp)
Set the internally stored temperature of the phase (K).
doublereal mean_X (const doublereal *const Q) const
Evaluate the mole-fraction-weighted mean of an array Q.
doublereal mean_Y (const doublereal *const Q) const
Evaluate the mass-fraction-weighted mean of an array Q.
doublereal meanMolecularWeight () const
The mean molecular weight. Units: (kg/kmol)
doublereal sum_xlogx () const
Evaluate \(\sum_k X_k \log X_k \).
doublereal sum_xlogQ (doublereal *const Q) const
Evaluate \(\sum_k X_k \log Q_k \).
void addElement (const std::string &symbol, doublereal weight=-12345.0)
Add an element.
void addElement (const XML_Node &e)
Add an element from an XML specification.
void addUniqueElement (const std::string &symbol, doublereal weight=-12345.0, int atomicNumber=0, doublereal entropy298=ENTROPY298_UNKNOWN, int elem_type=CT_ELEM_TYPE_ABSPOS)
Add an element, checking for uniqueness The uniqueness is checked by comparing the string symbol.
void addUniqueElement (const XML_Node &e)
Add an element, checking for uniqueness The uniqueness is checked by comparing the string symbol.
void addElementsFromXML (const XML_Node &phase)
Add all elements referenced in an XML_Node tree.
void freezeElements ()
Prohibit addition of more elements, and prepare to add species.
bool elementsFrozen ()
True if freezeElements has been called.
size_t addUniqueElementAfterFreeze (const std::string &symbol, doublereal weight, int atomicNumber, doublereal entropy298=ENTROPY298_UNKNOWN, int elem_type=CT_ELEM_TYPE_ABSPOS)
Add an element after elements have been frozen, checking for uniqueness The uniqueness is checked by comparing the string symbol.
void addSpecies (const std::string &name, const doublereal *comp, doublereal charge=0.0, doublereal size=1.0)
void addUniqueSpecies (const std::string &name, const doublereal *comp, doublereal charge=0.0, doublereal size=1.0)
Add a species to the phase, checking for uniqueness of the name This routine checks for uniqueness of the string name.
Protected Member Functions
void _updateThermo () const
Protected Member Functions inherited from ThermoPhase
virtual void getCsvReportData (std::vector< std::string > &names, std::vector< vector_fp > &data) const
Fills names and data with the column names and species thermo properties to be included in the output of the reportCSV method.
Protected Member Functions inherited from Phase
void init (const vector_fp &mw)
void setMolecularWeight (const int k, const double mw)
Set the molecular weight of a single species to a given value.
Protected Attributes
doublereal m_press
The current pressure of the solution (Pa)
doublereal m_p0
doublereal m_tlast
Last temperature used to evaluate the thermodynamic polynomial.
vector_fp m_h0_RT
Dimensionless enthalpy at the (mtlast, m_p0)
vector_fp m_cp0_R
Dimensionless heat capacity at the (mtlast, m_p0)
vector_fp m_s0_R
Dimensionless entropy at the (mtlast, m_p0)
Protected Attributes inherited from ThermoPhase
SpeciesThermo * m_spthermo
Pointer to the calculation manager for species reference-state thermodynamic properties.
std::vector< const XML_Node * > m_speciesData
Vector of pointers to the species databases.
doublereal m_phi
Stored value of the electric potential for this phase.
vector_fp m_lambdaRRT
Vector of element potentials.
bool m_hasElementPotentials
Boolean indicating whether there is a valid set of saved element potentials for this phase.
bool m_chargeNeutralityNecessary
Boolean indicating whether a charge neutrality condition is a necessity.
int m_ssConvention
Contains the standard state convention.
std::vector< doublereal > xMol_Ref
Reference Mole Fraction Composition.
Protected Attributes inherited from Phase
size_t m_kk
Number of species in the phase.
size_t m_ndim
Dimensionality of the phase.
vector_fp m_speciesComp
Atomic composition of the species.
vector_fp m_speciesSize
Vector of species sizes.
vector_fp m_speciesCharge
Vector of species charges. length m_kk.
Private Member Functions
doublereal err (const std::string &msg) const
Error return for unhandled cases.
Molar Thermodynamic Properties of the Solution
These functions are resolved at this level, by reference to the partial molar functions and standard state functions for species 0.
Derived classes don't need to supply entries for these functions.
doublereal enthalpy_mole () const
Molar enthalpy. Units: J/kmol.
doublereal intEnergy_mole () const
Molar internal energy. Units: J/kmol.
doublereal entropy_mole () const
Molar entropy. Units: J/kmol/K.
doublereal gibbs_mole () const
Molar Gibbs function. Units: J/kmol.
doublereal cp_mole () const
Molar heat capacity at constant pressure. Units: J/kmol/K.
doublereal cv_mole () const
Molar heat capacity at constant volume. Units: J/kmol/K.
Activities, Standard State, and Activity Concentrations
The activity \(a_k\) of a species in solution is related to the chemical potential by
\[ \mu_k = \mu_k^0(T) + \hat R T \log a_k. \]
The quantity \(\mu_k^0(T)\) is the chemical potential at unit activity, which depends only on temperature.
virtual void getActivities (doublereal *a) const
Get the array of non-dimensional activities at the current solution temperature, pressure, and solution concentration.
virtual void getActivityCoefficients (doublereal *ac) const
Get the array of non-dimensional activity coefficients at the current solution temperature, pressure, and solution concentration.
Partial Molar Properties of the Solution
These functions are resolved at this level, by reference to the partial molar functions and standard state functions for species 0.
Derived classes don't need to supply entries for these functions.
void getChemPotentials_RT (doublereal *murt) const
Get the array of non-dimensional species chemical potentials These are partial molar Gibbs free energies.
void getChemPotentials (doublereal *mu) const
Get the array of chemical potentials.
void getElectrochemPotentials (doublereal *mu) const
Get the species electrochemical potentials. Units: J/kmol.
void getPartialMolarEnthalpies (doublereal *hbar) const
Get the species partial molar enthalpies. Units: J/kmol.
virtual void getPartialMolarIntEnergies (doublereal *ubar) const
Get the species partial molar internal energies. Units: J/kmol.
void getPartialMolarEntropies (doublereal *sbar) const
Get the species partial molar entropy. Units: J/kmol K.
void getPartialMolarCp (doublereal *cpbar) const
Get the species partial molar Heat Capacities. Units: J/ kmol /K.
void getPartialMolarVolumes (doublereal *vbar) const
Get the species partial molar volumes. Units: m^3/kmol.
Properties of the Standard State of the Species in the Solution
These functions are the primary way real properties are supplied to derived thermodynamics classes of SingleSpeciesTP.
These functions must be supplied in derived classes. They are not resolved at the SingleSpeciesTP level.
void getPureGibbs (doublereal *gpure) const
Get the dimensional Gibbs functions for the standard state of the species at the current T and P.
void getStandardVolumes (doublereal *vbar) const
Get the molar volumes of each species in their standard states at the current T and P of the solution.
Thermodynamic Values for the Species Reference State
Almost all functions in this group are resolved by this class.
It is assumed that the m_spthermo species thermo pointer is populated and yields the reference state thermodynamics The internal energy function is not given by this class, since it would involve a specification of the equation of state.
virtual void getEnthalpy_RT_ref (doublereal *hrt) const
virtual void getGibbs_RT_ref (doublereal *grt) const
virtual void getGibbs_ref (doublereal *g) const
virtual void getEntropy_R_ref (doublereal *er) const
virtual void getCp_R_ref (doublereal *cprt) const
Setting the State
These methods set all or part of the thermodynamic state.
void setState_TPX (doublereal t, doublereal p, const doublereal *x)
Set the temperature (K), pressure (Pa), and mole fractions.
void setState_TPX (doublereal t, doublereal p, compositionMap &x)
Set the temperature (K), pressure (Pa), and mole fractions.
void setState_TPX (doublereal t, doublereal p, const std::string &x)
Set the temperature (K), pressure (Pa), and mole fractions.
void setState_TPY (doublereal t, doublereal p, const doublereal *y)
Set the internally stored temperature (K), pressure (Pa), and mass fractions of the phase.
void setState_TPY (doublereal t, doublereal p, compositionMap &y)
Set the internally stored temperature (K), pressure (Pa), and mass fractions of the phase.
void setState_TPY (doublereal t, doublereal p, const std::string &y)
Set the internally stored temperature (K), pressure (Pa), and mass fractions of the phase.
void setState_PX (doublereal p, doublereal *x)
Set the pressure (Pa) and mole fractions.
void setState_PY (doublereal p, doublereal *y)
Set the internally stored pressure (Pa) and mass fractions.
virtual void setState_HP (doublereal h, doublereal p, doublereal tol=1.e-8)
Set the internally stored specific enthalpy (J/kg) and pressure (Pa) of the phase.
virtual void setState_UV (doublereal u, doublereal v, doublereal tol=1.e-8)
Set the specific internal energy (J/kg) and specific volume (m^3/kg).
virtual void setState_SP (doublereal s, doublereal p, doublereal tol=1.e-8)
Set the specific entropy (J/kg/K) and pressure (Pa).
virtual void setState_SV (doublereal s, doublereal v, doublereal tol=1.e-8)
Set the specific entropy (J/kg/K) and specific volume (m^3/kg).
virtual void setParameters (int n, doublereal *const c)
virtual void getParameters (int &n, doublereal *const c) const
virtual void setParametersFromXML (const XML_Node &eosdata)
Set equation of state parameter values from XML entries.
Saturation properties.
These methods are only implemented by subclasses that implement full liquid-vapor equations of state.
virtual doublereal satTemperature (doublereal p) const
Return the saturation temperature given the pressure.
virtual doublereal satPressure (doublereal t)
Return the saturation pressure given the temperature.
virtual doublereal vaporFraction () const
Return the fraction of vapor at the current conditions.
virtual void setState_Tsat (doublereal t, doublereal x)
Set the state to a saturated system at a particular temperature.
virtual void setState_Psat (doublereal p, doublereal x)
Set the state to a saturated system at a particular pressure.
Detailed Description
The SingleSpeciesTP class is a filter class for ThermoPhase.
What it does is to simplify the construction of ThermoPhase objects by assuming that the phase consists of one and only one type of species. In other words, it's a stoichiometric phase. However, no assumptions are made concerning the thermodynamic functions or the equation of state of the phase. Therefore it's an incomplete description of the thermodynamics. The complete description must be made in a derived class of SingleSpeciesTP.
Several different groups of thermodynamic functions are resolved at this level by this class. For example, All partial molar property routines call their single species standard state equivalents. All molar solution thermodynamic routines call the single species standard state equivalents. Activities routines are resolved at this level, as there is only one species.
It is assumed that the reference state thermodynamics may be obtained by a pointer to a populated species thermodynamic property manager class (see ThermoPhase::m_spthermo). How to relate pressure changes to the reference state thermodynamics is again left open to implementation.
Mole fraction and Mass fraction vectors are assumed to be equal to x[0] = 1 y[0] = 1, respectively. Simplifications to the interface of setState_TPY() and setState_TPX() functions result and are made within the class.
Note, this class can handle the thermodynamic description of one phase of one species. It can not handle the description of phase equilibrium between two phases of a stoichiometric compound (e.g. water liquid and water vapor, below the critical point). However, it may be used to describe the thermodynamics of one phase of such a compound even past the phase equilibrium point, up to the point where the phase itself ceases to be a stable phase.
This class doesn't do much at the initialization level. Its SingleSpeciesTP::initThermo() member does check that one and only one species has been defined to occupy the phase.
Definition at line 69 of file SingleSpeciesTP.h.
Constructor & Destructor Documentation
SingleSpeciesTP ()
Base empty constructor.
Definition at line 20 of file SingleSpeciesTP.cpp.
Referenced by SingleSpeciesTP::duplMyselfAsThermoPhase().
SingleSpeciesTP (const SingleSpeciesTP & right)
Copy constructor.
Parameters
right Object to be copied
Definition at line 28 of file SingleSpeciesTP.cpp.
References SingleSpeciesTP::operator=().
Member Function Documentation
SingleSpeciesTP & operator= (const SingleSpeciesTP & right)
Assignment operator.
Parameters
right Object to be copied
Definition at line 37 of file SingleSpeciesTP.cpp.
References SingleSpeciesTP::m_cp0_R, SingleSpeciesTP::m_h0_RT, SingleSpeciesTP::m_p0, SingleSpeciesTP::m_press, SingleSpeciesTP::m_s0_R, SingleSpeciesTP::m_tlast, and ThermoPhase::operator=().
Referenced by StoichSubstanceSSTP::operator=(), FixedChemPotSSTP::operator=(), MetalSHEelectrons::operator=(), and SingleSpeciesTP::SingleSpeciesTP().
ThermoPhase * duplMyselfAsThermoPhase () const virtual
Duplication function.
This virtual function is used to create a duplicate of the current phase. It's used to duplicate the phase when given a ThermoPhase pointer to the phase.
Returns
It returns a ThermoPhase pointer.
Reimplemented from ThermoPhase.
Reimplemented in StoichSubstanceSSTP, and WaterSSTP.
Definition at line 51 of file SingleSpeciesTP.cpp.
References SingleSpeciesTP::SingleSpeciesTP().
int eosType () const virtual
Returns the equation of state type flag.
This is a modified base class. Therefore, if not overridden in derivied classes, this call will throw an exception.
Reimplemented from ThermoPhase.
Reimplemented in MetalSHEelectrons, FixedChemPotSSTP, StoichSubstanceSSTP, WaterSSTP, and MineralEQ3.
Definition at line 56 of file SingleSpeciesTP.cpp.
References SingleSpeciesTP::err().
Referenced by SingleSpeciesTP::err().
doublereal enthalpy_mole () const virtual
Molar enthalpy. Units: J/kmol.
This function is resolved here by calling the standard state thermo function.
Reimplemented from ThermoPhase.
Definition at line 66 of file SingleSpeciesTP.cpp.
References SingleSpeciesTP::getPartialMolarEnthalpies().
Referenced by WaterSSTP::initThermoXML().
doublereal intEnergy_mole () const virtual
Molar internal energy. Units: J/kmol.
This function is resolved here by calling the standard state thermo function.
Reimplemented from ThermoPhase.
Definition at line 73 of file SingleSpeciesTP.cpp.
References SingleSpeciesTP::getPartialMolarIntEnergies().
doublereal entropy_mole () const virtual
Molar entropy. Units: J/kmol/K.
This function is resolved here by calling the standard state thermo function.
Reimplemented from ThermoPhase.
Definition at line 80 of file SingleSpeciesTP.cpp.
References SingleSpeciesTP::getPartialMolarEntropies().
Referenced by WaterSSTP::initThermoXML().
doublereal gibbs_mole () const virtual
Molar Gibbs function. Units: J/kmol.
This function is resolved here by calling the standard state thermo function.
Reimplemented from ThermoPhase.
Definition at line 87 of file SingleSpeciesTP.cpp.
References SingleSpeciesTP::getChemPotentials().
doublereal cp_mole () const virtual
Molar heat capacity at constant pressure. Units: J/kmol/K.
This function is resolved here by calling the standard state thermo function.
Reimplemented from ThermoPhase.
Definition at line 99 of file SingleSpeciesTP.cpp.
References Cantera::GasConstant, and ThermoPhase::getCp_R().
Referenced by SingleSpeciesTP::cv_mole().
doublereal cv_mole () const virtual
Molar heat capacity at constant volume. Units: J/kmol/K.
This function is resolved here by calling the standard state thermo function.
Reimplemented from ThermoPhase.
Reimplemented in WaterSSTP.
Definition at line 113 of file SingleSpeciesTP.cpp.
References SingleSpeciesTP::cp_mole(), Phase::density(), ThermoPhase::isothermalCompressibility(), Phase::molecularWeight(), Phase::temperature(), and ThermoPhase::thermalExpansionCoeff().
virtual void getActivities (doublereal * a) const inline virtual
Get the array of non-dimensional activities at the current solution temperature, pressure, and solution concentration.
We redefine this function to just return 1.0 here.
Parameters
a Output vector of activities. Length: 1.
Reimplemented from ThermoPhase.
Definition at line 178 of file SingleSpeciesTP.h.
virtual void getActivityCoefficients (doublereal * ac) const inline virtual
Get the array of non-dimensional activity coefficients at the current solution temperature, pressure, and solution concentration.
Parameters
ac Output vector of activity coefficients. Length: 1.
Reimplemented from ThermoPhase.
Definition at line 189 of file SingleSpeciesTP.h.
References SingleSpeciesTP::err(), and Phase::m_kk.
void getChemPotentials_RT (doublereal * murt) const virtual
Get the array of non-dimensional species chemical potentials These are partial molar Gibbs free energies.
These are the phase, partial molar, and the standard state dimensionless chemical potentials. \(\mu_k / \hat R T \).
Units: unitless
Parameters
murt On return, Contains the chemical potential / RT of the single species and the phase. Units are unitless. Length = 1
Reimplemented from ThermoPhase.
Definition at line 145 of file SingleSpeciesTP.cpp.
References Cantera::GasConstant, ThermoPhase::getStandardChemPotentials(), and Phase::temperature().
void getChemPotentials (doublereal * mu) const virtual
Get the array of chemical potentials.
These are the phase, partial molar, and the standard state chemical potentials. \(\mu(T,P) = \mu^0_k(T,P) \).
Parameters
mu On return, Contains the chemical potential of the single species and the phase. Units are J / kmol . Length = 1
Reimplemented from ThermoPhase.
Definition at line 140 of file SingleSpeciesTP.cpp.
References ThermoPhase::getStandardChemPotentials().
Referenced by SingleSpeciesTP::getElectrochemPotentials(), and SingleSpeciesTP::gibbs_mole().
void getElectrochemPotentials (doublereal * mu) const
Get the species electrochemical potentials. Units: J/kmol.
This method adds a term \(Fz_k \phi_k \) to each chemical potential.
This is resolved here. A single species phase is not allowed to have anything other than a zero charge.
Parameters
mu On return, Contains the electrochemical potential of the single species and the phase. Units J/kmol . Length = 1
Definition at line 152 of file SingleSpeciesTP.cpp.
References SingleSpeciesTP::getChemPotentials().
void getPartialMolarEnthalpies (doublereal * hbar) const virtual
Get the species partial molar enthalpies. Units: J/kmol.
These are the phase enthalpies. \(h_k \).
Parameters
hbar Output vector of species partial molar enthalpies. Length: 1. units are J/kmol.
Reimplemented from ThermoPhase.
Definition at line 158 of file SingleSpeciesTP.cpp.
References Cantera::GasConstant, ThermoPhase::getEnthalpy_RT(), and Phase::temperature().
Referenced by SingleSpeciesTP::enthalpy_mole().
void getPartialMolarIntEnergies (doublereal * ubar) const virtual
Get the species partial molar internal energies. Units: J/kmol.
These are the phase internal energies. \(u_k \).
Parameters
ubar On return, Contains the internal energy of the single species and the phase. Units are J / kmol . Length = 1
Reimplemented from ThermoPhase.
Definition at line 166 of file SingleSpeciesTP.cpp.
References Cantera::GasConstant, ThermoPhase::getIntEnergy_RT(), and Phase::temperature().
Referenced by SingleSpeciesTP::intEnergy_mole().
void getPartialMolarEntropies (doublereal * sbar) const virtual
Get the species partial molar entropy. Units: J/kmol K.
This is the phase entropy. \(s(T,P) = s_o(T,P) \).
Parameters
sbar On return, Contains the entropy of the single species and the phase. Units are J / kmol / K . Length = 1
Reimplemented from ThermoPhase.
Definition at line 174 of file SingleSpeciesTP.cpp.
References Cantera::GasConstant, and ThermoPhase::getEntropy_R().
Referenced by SingleSpeciesTP::entropy_mole().
void getPartialMolarCp (doublereal * cpbar) const virtual
Get the species partial molar Heat Capacities. Units: J/ kmol /K.
This is the phase heat capacity. \(Cp(T,P) = Cp_o(T,P) \).
Parameters
cpbar On return, Contains the heat capacity of the single species and the phase. Units are J / kmol / K . Length = 1
Reimplemented from ThermoPhase.
Definition at line 180 of file SingleSpeciesTP.cpp.
References Cantera::GasConstant, and ThermoPhase::getCp_R().
void getPartialMolarVolumes (doublereal * vbar) const virtual
Get the species partial molar volumes. Units: m^3/kmol.
This is the phase molar volume. \(V(T,P) = V_o(T,P) \).
Parameters
vbar On return, Contains the molar volume of the single species and the phase. Units are m^3 / kmol. Length = 1
Reimplemented from ThermoPhase.
Definition at line 186 of file SingleSpeciesTP.cpp.
References Phase::density(), and Phase::molecularWeight().
void getPureGibbs (doublereal * gpure) const virtual
Get the dimensional Gibbs functions for the standard state of the species at the current T and P.
Parameters
gpure returns a vector of size 1, containing the Gibbs function Units: J/kmol.
Reimplemented from ThermoPhase.
Definition at line 197 of file SingleSpeciesTP.cpp.
References Cantera::GasConstant, ThermoPhase::getGibbs_RT(), and Phase::temperature().
void getStandardVolumes (doublereal * vbar) const virtual
Get the molar volumes of each species in their standard states at the current T and P of the solution.
units = m^3 / kmol
We resolve this function at this level, by assigning the molecular weight divided by the phase density
Parameters
vbar On output this contains the standard volume of the species and phase (m^3/kmol). Vector of length 1
Reimplemented from ThermoPhase.
Definition at line 203 of file SingleSpeciesTP.cpp.
References Phase::density(), and Phase::molecularWeight().
void getEnthalpy_RT_ref (doublereal * hrt) const virtual
Returns the vector of nondimensional enthalpies of the reference state at the current temperature of the solution and the reference pressure for the species.
This function is resolved in this class. It is assumed that the m_spthermo species thermo pointer is populated and yields the reference state.
Parameters
hrt Output vector containing the nondimensional reference state enthalpies Length: m_kk.
Reimplemented from ThermoPhase.
Reimplemented in FixedChemPotSSTP, and WaterSSTP.
Definition at line 214 of file SingleSpeciesTP.cpp.
References SingleSpeciesTP::_updateThermo(), and SingleSpeciesTP::m_h0_RT.
Referenced by MineralEQ3::getEnthalpy_RT(), StoichSubstanceSSTP::getEnthalpy_RT(), and MetalSHEelectrons::getEnthalpy_RT().
void getGibbs_RT_ref (doublereal * grt) const virtual
Returns the vector of nondimensional enthalpies of the reference state at the current temperature of the solution and the reference pressure for the species.
This function is resolved in this class. It is assumed that the m_spthermo species thermo pointer is populated and yields the reference state.
Parameters
grt Output vector containing the nondimensional reference state Gibbs Free energies. Length: m_kk.
Reimplemented from ThermoPhase.
Reimplemented in FixedChemPotSSTP, and WaterSSTP.
Definition at line 220 of file SingleSpeciesTP.cpp.
References SingleSpeciesTP::_updateThermo(), SingleSpeciesTP::m_h0_RT, and SingleSpeciesTP::m_s0_R.
Referenced by SingleSpeciesTP::getGibbs_ref(), and MetalSHEelectrons::getGibbs_RT().
void getGibbs_ref (doublereal * g) const virtual
Returns the vector of the gibbs function of the reference state at the current temperature of the solution and the reference pressure for the species. units = J/kmol
This function is resolved in this class. It is assumed that the m_spthermo species thermo pointer is populated and yields the reference state.
Parameters
g Output vector containing the reference state Gibbs Free energies. Length: m_kk. Units: J/kmol.
Reimplemented from ThermoPhase.
Reimplemented in FixedChemPotSSTP, and WaterSSTP.
Definition at line 226 of file SingleSpeciesTP.cpp.
References Cantera::GasConstant, SingleSpeciesTP::getGibbs_RT_ref(), and Phase::temperature().
void getEntropy_R_ref (doublereal * er) const virtual
Returns the vector of nondimensional entropies of the reference state at the current temperature of the solution and the reference pressure for each species.
This function is resolved in this class. It is assumed that the m_spthermo species thermo pointer is populated and yields the reference state.
Parameters
er Output vector containing the nondimensional reference state entropies. Length: m_kk.
Reimplemented from ThermoPhase.
Reimplemented in FixedChemPotSSTP, and WaterSSTP.
Definition at line 232 of file SingleSpeciesTP.cpp.
References SingleSpeciesTP::_updateThermo(), and SingleSpeciesTP::m_s0_R.
Referenced by MineralEQ3::getEntropy_R(), StoichSubstanceSSTP::getEntropy_R(), and MetalSHEelectrons::getEntropy_R().
void getCp_R_ref (doublereal * cprt) const virtual
Returns the vector of nondimensional constant pressure heat capacities of the reference state at the current temperature of the solution and reference pressure for each species.
This function is resolved in this class. It is assumed that the m_spthermo species thermo pointer is populated and yields the reference state.
Parameters
cprt Output vector of nondimensional reference state heat capacities at constant pressure for the species. Length: m_kk
Reimplemented from ThermoPhase.
Reimplemented in FixedChemPotSSTP, and WaterSSTP.
Definition at line 238 of file SingleSpeciesTP.cpp.
References SingleSpeciesTP::_updateThermo(), and SingleSpeciesTP::m_cp0_R.
void setState_TPX (doublereal t, doublereal p, const doublereal * x) virtual
Set the temperature (K), pressure (Pa), and mole fractions.
Note, the mole fractions are set to X[0] = 1.0. Setting the pressure may involve the solution of a nonlinear equation.
Parameters
t Temperature (K)
p Pressure (Pa)
x Vector of mole fractions. Length is equal to m_kk.
Reimplemented from ThermoPhase.
Definition at line 248 of file SingleSpeciesTP.cpp.
References ThermoPhase::setPressure(), and Phase::setTemperature().
void setState_TPX (doublereal t, doublereal p, compositionMap & x) virtual
Set the temperature (K), pressure (Pa), and mole fractions.
Note, the mole fractions are set to X[0] = 1.0. Setting the pressure may involve the solution of a nonlinear equation.
Parameters
t Temperature (K)
p Pressure (Pa)
x String containing a composition map of the mole fractions. Species not in the composition map are assumed to have zero mole fraction
Reimplemented from ThermoPhase.
Definition at line 255 of file SingleSpeciesTP.cpp.
References ThermoPhase::setPressure(), and Phase::setTemperature().
void setState_TPX (doublereal t, doublereal p, const std::string & x) virtual
Set the temperature (K), pressure (Pa), and mole fractions.
Note, the mole fractions are set to X[0] = 1.0. Setting the pressure may involve the solution of a nonlinear equation.
Parameters
t Temperature (K)
p Pressure (Pa)
x String containing a composition map of the mole fractions. Species not in the composition map are assumed to have zero mole fraction
Reimplemented from ThermoPhase.
Definition at line 262 of file SingleSpeciesTP.cpp.
References ThermoPhase::setPressure(), and Phase::setTemperature().
void setState_TPY (doublereal t, doublereal p, const doublereal * y) virtual
Set the internally stored temperature (K), pressure (Pa), and mass fractions of the phase.
Note, the mass fractions are set to Y[0] = 1.0. Setting the pressure may involve the solution of a nonlinear equation.
Parameters
t Temperature (K)
p Pressure (Pa)
y Vector of mass fractions. Length is equal to m_kk.
Reimplemented from ThermoPhase.
Definition at line 269 of file SingleSpeciesTP.cpp.
References ThermoPhase::setPressure(), and Phase::setTemperature().
void setState_TPY (doublereal t, doublereal p, compositionMap & y) virtual
Set the internally stored temperature (K), pressure (Pa), and mass fractions of the phase.
Note, the mass fractions are set to Y[0] = 1.0. Setting the pressure may involve the solution of a nonlinear equation.
Parameters
t Temperature (K)
p Pressure (Pa)
y Composition map of mass fractions. Species not in the composition map are assumed to have zero mass fraction
Reimplemented from ThermoPhase.
Definition at line 276 of file SingleSpeciesTP.cpp.
References ThermoPhase::setPressure(), and Phase::setTemperature().
void setState_TPY (doublereal t, doublereal p, const std::string & y) virtual
Set the internally stored temperature (K), pressure (Pa), and mass fractions of the phase.
Note, the mass fractions are set to Y[0] = 1.0. Setting the pressure may involve the solution of a nonlinear equation.
Parameters
t Temperature (K)
p Pressure (Pa)
y String containing a composition map of the mass fractions. Species not in the composition map are assumed to have zero mass fraction
Reimplemented from ThermoPhase.
Definition at line 283 of file SingleSpeciesTP.cpp.
References ThermoPhase::setPressure(), and Phase::setTemperature().
void setState_PX (doublereal p, doublereal * x) virtual
Set the pressure (Pa) and mole fractions.
Note, the mole fractions are set to X[0] = 1.0. Setting the pressure may involve the solution of a nonlinear equation.
Parameters
p Pressure (Pa)
x Vector of mole fractions. Length is equal to m_kk.
Reimplemented from ThermoPhase.
Definition at line 290 of file SingleSpeciesTP.cpp.
References SingleSpeciesTP::err(), and ThermoPhase::setPressure().
void setState_PY (doublereal p, doublereal * y) virtual
Set the internally stored pressure (Pa) and mass fractions.
Note, the mass fractions are set to Y[0] = 1.0. Note, the temperature is held constant during this operation. Setting the pressure may involve the solution of a nonlinear equation.
Parameters
p Pressure (Pa)
y Vector of mass fractions. Length is equal to m_kk.
Reimplemented from ThermoPhase.
Definition at line 298 of file SingleSpeciesTP.cpp.
References SingleSpeciesTP::err(), and ThermoPhase::setPressure().
void setState_HP (doublereal h, doublereal p, doublereal tol = 1.e-8) virtual
Set the internally stored specific enthalpy (J/kg) and pressure (Pa) of the phase.
Parameters
h Specific enthalpy (J/kg)
p Pressure (Pa)
tol Optional parameter setting the tolerance of the calculation.
Reimplemented from ThermoPhase.
Definition at line 306 of file SingleSpeciesTP.cpp.
References ThermoPhase::cp_mass(), ThermoPhase::enthalpy_mass(), Cantera::fp2str(), ThermoPhase::setPressure(), ThermoPhase::setState_TP(), and Phase::temperature().
void setState_UV (doublereal u, doublereal v, doublereal tol = 1.e-8) virtual
Set the specific internal energy (J/kg) and specific volume (m^3/kg).
This function fixes the internal state of the phase so that the specific internal energy and specific volume have the value of the input parameters.
Parameters
u specific internal energy (J/kg)
v specific volume (m^3/kg).
tol Optional parameter setting the tolerance of the calculation.
Reimplemented from ThermoPhase.
Definition at line 326 of file SingleSpeciesTP.cpp.
References ThermoPhase::cv_mass(), Cantera::fp2str(), ThermoPhase::intEnergy_mass(), Phase::setDensity(), Phase::setTemperature(), and Phase::temperature().
void setState_SP (doublereal s, doublereal p, doublereal tol = 1.e-8) virtual
Set the specific entropy (J/kg/K) and pressure (Pa).
This function fixes the internal state of the phase so that the specific entropy and the pressure have the value of the input parameters.
Parameters
s specific entropy (J/kg/K)
p specific pressure (Pa).
tol Optional parameter setting the tolerance of the calculation.
Reimplemented from ThermoPhase.
Definition at line 352 of file SingleSpeciesTP.cpp.
References ThermoPhase::cp_mass(), ThermoPhase::entropy_mass(), Cantera::fp2str(), ThermoPhase::setPressure(), ThermoPhase::setState_TP(), and Phase::temperature().
void setState_SV (doublereal s, doublereal v, doublereal tol = 1.e-8) virtual
Set the specific entropy (J/kg/K) and specific volume (m^3/kg).
This function fixes the internal state of the phase so that the specific entropy and specific volume have the value of the input parameters.
Parameters
s specific entropy (J/kg/K)
v specific volume (m^3/kg).
tol Optional parameter setting the tolerance of the calculation.
Reimplemented from ThermoPhase.
Definition at line 372 of file SingleSpeciesTP.cpp.
References ThermoPhase::cv_mass(), ThermoPhase::entropy_mass(), Cantera::fp2str(), Phase::setDensity(), Phase::setTemperature(), and Phase::temperature().
virtual void setParameters (int n, doublereal *const c) inline virtual
Set equation of state parameters. The number and meaning of these depends on the subclass.
Parameters
n number of parameters
c array of n coefficients
Deprecated:
Unimplemented
Reimplemented from ThermoPhase.
Reimplemented in FixedChemPotSSTP, electrodeElectron, MetalSHEelectrons, StoichSubstanceSSTP, and MineralEQ3.
Definition at line 572 of file SingleSpeciesTP.h.
References Cantera::warn_deprecated().
virtual void getParameters (int & n, doublereal *const c) const inline virtual
Deprecated:
Unimplemented
Reimplemented from ThermoPhase.
Reimplemented in FixedChemPotSSTP, MetalSHEelectrons, StoichSubstanceSSTP, and MineralEQ3.
Definition at line 577 of file SingleSpeciesTP.h.
References Cantera::warn_deprecated().
virtual void setParametersFromXML (const XML_Node & eosdata) inline virtual
Set equation of state parameter values from XML entries.
This method is called by function importPhase in file importCTML.cpp when processing a phase definition in an input file. It should be overloaded in subclasses to set any parameters that are specific to that particular phase model.
Parameters
eosdata An XML_Node object corresponding to the "thermo" entry for this phase in the input file.
Reimplemented from ThermoPhase.
Reimplemented in FixedChemPotSSTP, electrodeElectron, MetalSHEelectrons, StoichSubstanceSSTP, WaterSSTP, and MineralEQ3.
Definition at line 592 of file SingleSpeciesTP.h.
virtual doublereal satTemperature (doublereal p) const inline virtual
Return the saturation temperature given the pressure.
Parameters
p Pressure (Pa)
Reimplemented from ThermoPhase.
Definition at line 599 of file SingleSpeciesTP.h.
References SingleSpeciesTP::err().
virtual doublereal satPressure (doublereal t) inline virtual
Return the saturation pressure given the temperature.
Parameters
t Temperature (Kelvin)
Reimplemented from ThermoPhase.
Reimplemented in WaterSSTP.
Definition at line 604 of file SingleSpeciesTP.h.
References SingleSpeciesTP::err().
virtual doublereal vaporFraction () const inline virtual
Return the fraction of vapor at the current conditions.
Reimplemented from ThermoPhase.
Reimplemented in WaterSSTP.
Definition at line 609 of file SingleSpeciesTP.h.
References SingleSpeciesTP::err().
virtual void setState_Tsat (doublereal t, doublereal x) inline virtual
Set the state to a saturated system at a particular temperature.
Parameters
t Temperature (kelvin)
x Fraction of vapor
Reimplemented from ThermoPhase.
Definition at line 614 of file SingleSpeciesTP.h.
References SingleSpeciesTP::err().
virtual void setState_Psat (doublereal p, doublereal x) inline virtual
Set the state to a saturated system at a particular pressure.
Parameters
p Pressure (Pa)
x Fraction of vapor
Reimplemented from ThermoPhase.
Definition at line 618 of file SingleSpeciesTP.h.
References SingleSpeciesTP::err().
void initThermo () virtual
Initialize.
This method is provided to allow subclasses to perform any initialization required after all species have been added. For example, it might be used to resize internal work arrays that must have an entry for each species. When importing a CTML phase description, this method is called just prior to returning from function importPhase().
Inheriting objects should call this function
This version sets the mole fraction vector to x[0] = 1.0, and then calls the ThermoPhase::initThermo() function.
See Also
importCTML.cpp
Reimplemented from ThermoPhase.
Reimplemented in FixedChemPotSSTP, MetalSHEelectrons, StoichSubstanceSSTP, WaterSSTP, and MineralEQ3.
Definition at line 404 of file SingleSpeciesTP.cpp.
References ThermoPhase::initThermo(), SingleSpeciesTP::m_cp0_R, SingleSpeciesTP::m_h0_RT, SingleSpeciesTP::m_s0_R, Phase::nSpecies(), and Phase::setMoleFractions().
Referenced by WaterSSTP::initThermo(), StoichSubstanceSSTP::initThermo(), MetalSHEelectrons::initThermo(), and FixedChemPotSSTP::initThermo().
void _updateThermo () const protected
This crucial internal routine calls the species thermo update program to calculate new species Cp0, H0, and S0 whenever the temperature has changed.
Definition at line 433 of file SingleSpeciesTP.cpp.
References DATA_PTR, SingleSpeciesTP::m_cp0_R, SingleSpeciesTP::m_h0_RT, SingleSpeciesTP::m_s0_R, ThermoPhase::m_spthermo, SingleSpeciesTP::m_tlast, Phase::temperature(), and SpeciesThermo::update().
Referenced by FixedChemPotSSTP::FixedChemPotSSTP(), MineralEQ3::getCp_R(), StoichSubstanceSSTP::getCp_R(), MetalSHEelectrons::getCp_R(), SingleSpeciesTP::getCp_R_ref(), SingleSpeciesTP::getEnthalpy_RT_ref(), SingleSpeciesTP::getEntropy_R_ref(), SingleSpeciesTP::getGibbs_RT_ref(), MineralEQ3::getIntEnergy_RT(), StoichSubstanceSSTP::getIntEnergy_RT(), MineralEQ3::getIntEnergy_RT_ref(), StoichSubstanceSSTP::getIntEnergy_RT_ref(), and MetalSHEelectrons::getIntEnergy_RT_ref().
doublereal err (const std::string & msg) const private
Error return for unhandled cases.
It's used when this class doesn't have an answer for the question given to it, because the derived class isn't overriding a function.
Parameters
msg String message
Definition at line 396 of file SingleSpeciesTP.cpp.
References SingleSpeciesTP::eosType(), and Cantera::int2str().
Referenced by SingleSpeciesTP::eosType(), SingleSpeciesTP::getActivityCoefficients(), SingleSpeciesTP::satPressure(), SingleSpeciesTP::satTemperature(), SingleSpeciesTP::setState_Psat(), SingleSpeciesTP::setState_PX(), SingleSpeciesTP::setState_PY(), SingleSpeciesTP::setState_Tsat(), and SingleSpeciesTP::vaporFraction().
Member Data Documentation
doublereal m_press protected
The current pressure of the solution (Pa)
It gets initialized to 1 atm.
Definition at line 649 of file SingleSpeciesTP.h.
Referenced by MineralEQ3::getEnthalpy_RT(), StoichSubstanceSSTP::getEnthalpy_RT(), SingleSpeciesTP::operator=(), MineralEQ3::pressure(), StoichSubstanceSSTP::pressure(), FixedChemPotSSTP::pressure(), MetalSHEelectrons::pressure(), MineralEQ3::setPressure(), StoichSubstanceSSTP::setPressure(), FixedChemPotSSTP::setPressure(), and MetalSHEelectrons::setPressure().
doublereal m_p0 protected
Reference pressure (Pa) must be the same for all species
defaults to 1 atm.
Definition at line 655 of file SingleSpeciesTP.h.
Referenced by FixedChemPotSSTP::FixedChemPotSSTP(), MineralEQ3::getEnthalpy_RT(), StoichSubstanceSSTP::getEnthalpy_RT(), MetalSHEelectrons::getEntropy_R(), MetalSHEelectrons::getGibbs_RT(), MineralEQ3::getIntEnergy_RT(), StoichSubstanceSSTP::getIntEnergy_RT(), MineralEQ3::getIntEnergy_RT_ref(), StoichSubstanceSSTP::getIntEnergy_RT_ref(), MetalSHEelectrons::getIntEnergy_RT_ref(), StoichSubstanceSSTP::initThermo(), and SingleSpeciesTP::operator=().
doublereal m_tlast mutable protected
Last temperature used to evaluate the thermodynamic polynomial.
Definition at line 658 of file SingleSpeciesTP.h.
Referenced by SingleSpeciesTP::_updateThermo(), FixedChemPotSSTP::FixedChemPotSSTP(), and SingleSpeciesTP::operator=().
vector_fp m_h0_RT mutable protected
Dimensionless enthalpy at the (mtlast, m_p0)
Definition at line 661 of file SingleSpeciesTP.h.
Referenced by SingleSpeciesTP::_updateThermo(), FixedChemPotSSTP::FixedChemPotSSTP(), SingleSpeciesTP::getEnthalpy_RT_ref(), SingleSpeciesTP::getGibbs_RT_ref(), MineralEQ3::getIntEnergy_RT(), StoichSubstanceSSTP::getIntEnergy_RT(), MineralEQ3::getIntEnergy_RT_ref(), StoichSubstanceSSTP::getIntEnergy_RT_ref(), MetalSHEelectrons::getIntEnergy_RT_ref(), StoichSubstanceSSTP::initThermo(), SingleSpeciesTP::initThermo(), and SingleSpeciesTP::operator=().
vector_fp m_cp0_R mutable protected
Dimensionless heat capacity at the (mtlast, m_p0)
Definition at line 663 of file SingleSpeciesTP.h.
Referenced by SingleSpeciesTP::_updateThermo(), MineralEQ3::getCp_R(), StoichSubstanceSSTP::getCp_R(), MetalSHEelectrons::getCp_R(), SingleSpeciesTP::getCp_R_ref(), StoichSubstanceSSTP::initThermo(), SingleSpeciesTP::initThermo(), and SingleSpeciesTP::operator=().
vector_fp m_s0_R mutable protected
Dimensionless entropy at the (mtlast, m_p0)
Definition at line 665 of file SingleSpeciesTP.h.
Referenced by SingleSpeciesTP::_updateThermo(), FixedChemPotSSTP::FixedChemPotSSTP(), SingleSpeciesTP::getEntropy_R_ref(), MineralEQ3::getGibbs_RT(), StoichSubstanceSSTP::getGibbs_RT(), SingleSpeciesTP::getGibbs_RT_ref(), StoichSubstanceSSTP::initThermo(), SingleSpeciesTP::initThermo(), and SingleSpeciesTP::operator=().
The documentation for this class was generated from the following files:
SingleSpeciesTP.h
SingleSpeciesTP.cpp