Cantera: PDSS_SSVol Class Reference
PDSS_SSVol Class Reference
Species Standard-State Thermodynamic Properties
Class for pressure dependent standard states that uses a standard state volume model of some sort.
#include <PDSS_SSVol.h>
Public Member Functions
Constructors
PDSS_SSVol (VPStandardStateTP *tp, size_t spindex)
Constructor.
PDSS_SSVol (VPStandardStateTP *tp, size_t spindex, const std::string &inputFile, const std::string &id="")
Constructor that initializes the object by examining the input file of the ThermoPhase object.
PDSS_SSVol (VPStandardStateTP *vptp_ptr, size_t spindex, const XML_Node &speciesNode, const XML_Node &phaseRef, bool spInstalled)
Constructor that initializes the object by examining the input file of the ThermoPhase object.
PDSS_SSVol (const PDSS_SSVol &b)
Copy Constructur.
PDSS_SSVol & operator= (const PDSS_SSVol &b)
Assignment operator.
virtual PDSS * duplMyselfAsPDSS () const
Duplication routine for objects which inherit from PDSS.
Molar Thermodynamic Properties of the Species Standard State in the Solution
virtual doublereal enthalpy_mole () const
Return the molar enthalpy in units of J kmol-1.
virtual doublereal enthalpy_RT () const
Return the standard state molar enthalpy divided by RT.
virtual doublereal intEnergy_mole () const
Return the molar internal Energy in units of J kmol-1.
virtual doublereal entropy_mole () const
Return the molar entropy in units of J kmol-1 K-1.
virtual doublereal entropy_R () const
Return the standard state entropy divided by RT.
virtual doublereal gibbs_mole () const
Return the molar Gibbs free energy in units of J kmol-1.
virtual doublereal gibbs_RT () const
Return the molar Gibbs free energy divided by RT.
virtual doublereal cp_mole () const
Return the molar const pressure heat capacity in units of J kmol-1 K-1.
virtual doublereal cp_R () const
Return the molar const pressure heat capacity divided by RT.
virtual doublereal cv_mole () const
Return the molar const volume heat capacity in units of J kmol-1 K-1.
virtual doublereal molarVolume () const
Return the molar volume at standard state.
virtual doublereal density () const
Return the standard state density at standard state.
Public Member Functions inherited from PDSS
PDSS ()
Empty Constructor.
PDSS (VPStandardStateTP *tp, size_t spindex)
Constructor that initializes the object by examining the XML entries from the ThermoPhase object.
PDSS (const PDSS &b)
Copy Constructor.
PDSS & operator= (const PDSS &b)
Assignment operator.
virtual ~PDSS ()
Destructor for the phase.
virtual doublereal enthalpyDelp_mole () const
Get the difference in the standard state enthalpy between the current pressure and the reference pressure, p0.
virtual doublereal entropyDelp_mole () const
Get the difference in the standard state entropy between the current pressure and the reference pressure, p0.
virtual doublereal gibbsDelp_mole () const
Get the difference in the standard state gibbs free energy between the current pressure and the reference pressure, p0.
virtual doublereal cpDelp_mole () const
Get the difference in standard state heat capacity between the current pressure and the reference pressure, p0.
doublereal refPressure () const
Return the reference pressure for this phase.
doublereal minTemp () const
return the minimum temperature
doublereal maxTemp () const
return the minimum temperature
virtual doublereal pressure () const
Returns the pressure (Pa)
virtual doublereal thermalExpansionCoeff () const
Return the volumetric thermal expansion coefficient. Units: 1/K.
doublereal temperature () const
Return the current stored temperature.
doublereal molecularWeight () const
Return the molecular weight of the species in units of kg kmol-1.
void setMolecularWeight (doublereal mw)
Set the molecular weight of the species.
PDSS_enumType reportPDSSType () const
Returns the type of the standard state parameterization.
virtual void reportParams (size_t &kindex, int &type, doublereal *const c, doublereal &minTemp, doublereal &maxTemp, doublereal &refPressure) const
This utility function reports back the type of parameterization and all of the parameters for the species, index.
virtual void initAllPtrs (VPStandardStateTP *vptp_ptr, VPSSMgr *vpssmgr_ptr, SpeciesThermo *spthermo_ptr)
Initialize or Reinitialize all shallow pointers in the object.
Private Member Functions
Mechanical Equation of State Properties
virtual void setPressure (doublereal pres)
Sets the pressure in the object.
virtual void setTemperature (doublereal temp)
Set the internal temperature.
virtual void setState_TP (doublereal temp, doublereal pres)
Set the internal temperature and pressure.
virtual void setState_TR (doublereal temp, doublereal rho)
Set the internal temperature and density.
Miscellaneous properties of the standard state
virtual doublereal critTemperature () const
critical temperature
virtual doublereal critPressure () const
critical pressure
virtual doublereal critDensity () const
critical density
virtual doublereal satPressure (doublereal t)
saturation pressure
Initialization of the Object
virtual void initThermo ()
Initialization routine for all of the shallow pointers.
void constructPDSSFile (VPStandardStateTP *vptp_ptr, size_t spindex, const std::string &inputFile, const std::string &id)
Initialization of a PDSS object using an input XML file.
void constructPDSSXML (VPStandardStateTP *vptp_ptr, size_t spindex, const XML_Node &speciesNode, const XML_Node &phaseNode, bool spInstalled)
Initialization of a PDSS object using an xml tree.
virtual void initThermoXML (const XML_Node &phaseNode, const std::string &id)
Initialization routine for the PDSS object based on the phaseNode.
Private Attributes
SSVolume_Model_enumType volumeModel_
Enumerated data type describing the type of volume model used to calculate the standard state volume of the species.
doublereal m_constMolarVolume
Value of the constant molar volume for the species.
vector_fp TCoeff_
coefficients for the temperature representation
doublereal dVdT_
Derivative of the volume wrt temperature.
doublereal d2VdT2_
2nd derivative of the volume wrt temperature
Properties of the Reference State of the Species in the Solution
virtual doublereal gibbs_RT_ref () const
Return the molar gibbs free energy divided by RT at reference pressure.
virtual doublereal enthalpy_RT_ref () const
Return the molar enthalpy divided by RT at reference pressure.
virtual doublereal entropy_R_ref () const
Return the molar entropy divided by R at reference pressure.
virtual doublereal cp_R_ref () const
Return the molar heat capacity divided by R at reference pressure.
virtual doublereal molarVolume_ref () const
Return the molar volume at reference pressure.
void calcMolarVolume () const
Does the internal calculation of the volume.
Additional Inherited Members
Protected Attributes inherited from PDSS
PDSS_enumType m_pdssType
Enumerated type describing the type of the PDSS object.
doublereal m_temp
Current temperature used by the PDSS object.
doublereal m_pres
State of the system - pressure.
doublereal m_p0
Reference state pressure of the species.
doublereal m_minTemp
Minimum temperature.
doublereal m_maxTemp
Maximum temperature.
VPStandardStateTP * m_tp
ThermoPhase which this species belongs to.
VPSSMgr * m_vpssmgr_ptr
Pointer to the VPSS manager for this object.
doublereal m_mw
Molecular Weight of the species.
size_t m_spindex
Species index in the ThermoPhase corresponding to this species.
SpeciesThermo * m_spthermo
Pointer to the species thermodynamic property manager.
doublereal * m_h0_RT_ptr
Reference state enthalpy divided by RT.
doublereal * m_cp0_R_ptr
Reference state heat capacity divided by R.
doublereal * m_s0_R_ptr
Reference state entropy divided by R.
doublereal * m_g0_RT_ptr
Reference state Gibbs free energy divided by RT.
doublereal * m_V0_ptr
Reference state molar volume (m3 kg-1)
doublereal * m_hss_RT_ptr
Standard state enthalpy divided by RT.
doublereal * m_cpss_R_ptr
Standard state heat capacity divided by R.
doublereal * m_sss_R_ptr
Standard state entropy divided by R.
doublereal * m_gss_RT_ptr
Standard state Gibbs free energy divided by RT.
doublereal * m_Vss_ptr
Standard State molar volume (m3 kg-1)
Detailed Description
Class for pressure dependent standard states that uses a standard state volume model of some sort.
Class PDSS_SSVol is an implementation class that compute the properties of a single species in a phase at its standard states, for a range of temperatures and pressures. This particular class assumes that the calculation of the thermodynamics functions can be separated into a temperature polynomial representation for thermo functions that can be handled bey a SimpleThermo object and a separate calculation for the standard state volume. The Models include a cubic polynomial in temperature for either the standard state volume or the standard state density. The manager uses a SimpleThermo object to handle the calculation of the reference state. This object then adds the pressure dependencies and the volume terms to these thermo functions to complete the representation.
The class includes the following models for the representation of the standard state volume:
Constant Volume
This standard state model is invoked with the keyword "constant_incompressible" or "constant". The standard state volume is considered constant.
\[ V^o_k(T,P) = a_0 \]
Temperature polynomial for the standard state volume
This standard state model is invoked with the keyword "temperature_polynomial". The standard state volume is considered a function of temperature only.
\[ V^o_k(T,P) = a_0 + a_1 T + a_2 T^2 + a_3 T^3 + a_4 T^4 \]
Temperature polynomial for the standard state density
This standard state model is invoked with the keyword "density_temperature_polynomial". The standard state density, which is the inverse of the volume, is considered a function of temperature only.
\[ {\rho}^o_k(T,P) = \frac{M_k}{V^o_k(T,P)} = a_0 + a_1 T + a_2 T^2 + a_3 T^3 + a_4 T^4 \]
Specification of Species Standard State Properties
The standard molar Gibbs free energy for species k is determined from the enthalpy and entropy expressions
\[ G^o_k(T,P) = H^o_k(T,P) - S^o_k(T,P) \]
The enthalpy is calculated mostly from the SpeciesThermo object's enthalpy evalulator. The dependence on pressure originates from the Maxwell relation
\[ {\left(\frac{dH^o_k}{dP}\right)}_T = T {\left(\frac{dS^o_k}{dP}\right)}_T + V^o_k \]
which is equal to
\[ {\left(\frac{dH^o_k}{dP}\right)}_T = V^o_k - T {\left(\frac{dV^o_k}{dT}\right)}_P \]
The entropy is calculated mostly from the SpeciesThermo objects entropy evalulator. The dependence on pressure originates from the Maxwell relation:
\[ {\left(\frac{dS^o_k}{dP}\right)}_T = - {\left(\frac{dV^o_k}{dT}\right)}_P \]
The standard state constant-pressure heat capacity expression is obtained from taking the temperature derivative of the Maxwell relation involving the enthalpy given above to yield an expression for the pressure dependence of the heat capacity.
\[ {\left(\frac{d{C}^o_{p,k}}{dP}\right)}_T = - T {\left(\frac{{d}^2{V}^o_k}{{dT}^2}\right)}_T \]
The standard molar Internal Energy for species k is determined from the following relation.
\[ U^o_k(T,P) = H^o_k(T,P) - p V^o_k \]
XML Example
An example of the specification of a standard state for the LiCl molten salt which employs a constant molar volume expression.
<speciesData id="species_MoltenSalt">
<species name="LiCl(L)">
  <atomArray> Li:1 Cl:1 </atomArray>
  <standardState  model="constant_incompressible">
     <molarVolume> 0.02048004 </molarVolume>
  </standardState>
  <thermo>
    <Shomate Pref="1 bar" Tmax="2000.0" Tmin="700.0">
      <floatArray size="7">
       73.18025, -9.047232, -0.316390,
       0.079587, 0.013594, -417.1314,
       157.6711
      </floatArray>
    </Shomate>
  </thermo>
</species>
</speciesData>
An example of the specification of a standard state for the LiCl molten salt which has a temperature dependent standard state volume.
<speciesData id="species_MoltenSalt">
<species name="LiCl(L)">
   <atomArray> Li:1 Cl:1 </atomArray>
   <standardState  model="density_temperature_polynomial">
      <densityTemperaturePolynomial units="gm/cm3" >
         1.98715, -5.890906E-4, 0.0, 0.0
      </densityTemperaturePolynomial>
   </standardState>
   <thermo>
     <Shomate Pref="1 bar" Tmax="2000.0" Tmin="700.0">
       <floatArray size="7">
         73.18025, -9.047232, -0.316390,
         0.079587, 0.013594, -417.1314,
         157.6711
       </floatArray>
     </Shomate>
   </thermo>
 </species>
 </speciesData>
Definition at line 159 of file PDSS_SSVol.h.
Constructor & Destructor Documentation
PDSS_SSVol (VPStandardStateTP * tp, size_t spindex)
Constructor.
Parameters
tp Pointer to the ThermoPhase object pertaining to the phase
spindex Species index of the species in the phase
Definition at line 25 of file PDSS_SSVol.cpp.
References PDSS::m_pdssType, and PDSS_SSVol::TCoeff_.
Referenced by PDSS_SSVol::duplMyselfAsPDSS().
PDSS_SSVol (VPStandardStateTP * tp, size_t spindex, const std::string & inputFile, const std::string & id = "")
Constructor that initializes the object by examining the input file of the ThermoPhase object.
This function calls the constructPDSSFile member function.
Parameters
tp Pointer to the ThermoPhase object pertaining to the phase
spindex Species index of the species in the phase
inputFile String name of the input file
id String name of the phase in the input file. The default is the empty string, in which case the first phase in the file is used.
Definition at line 36 of file PDSS_SSVol.cpp.
References PDSS_SSVol::constructPDSSFile(), and PDSS::m_pdssType.
PDSS_SSVol (VPStandardStateTP * vptp_ptr, size_t spindex, const XML_Node & speciesNode, const XML_Node & phaseRef, bool spInstalled)
Constructor that initializes the object by examining the input file of the ThermoPhase object.
This function calls the constructPDSSXML member function.
Parameters
vptp_ptr Pointer to the ThermoPhase object pertaining to the phase
spindex Species index of the species in the phase
speciesNode Reference to the species XML tree.
phaseRef Reference to the XML tree containing the phase information.
spInstalled Boolean indicating whether the species is installed yet or not.
Definition at line 47 of file PDSS_SSVol.cpp.
References PDSS_SSVol::constructPDSSXML(), and PDSS::m_pdssType.
PDSS_SSVol (const PDSS_SSVol & b)
Copy Constructur.
Parameters
b Object to be copied
Definition at line 59 of file PDSS_SSVol.cpp.
Member Function Documentation
PDSS_SSVol & operator= (const PDSS_SSVol & b)
Assignment operator.
Parameters
b Object to be copeid
Definition at line 71 of file PDSS_SSVol.cpp.
References PDSS_SSVol::m_constMolarVolume, PDSS::operator=(), PDSS_SSVol::TCoeff_, and PDSS_SSVol::volumeModel_.
PDSS * duplMyselfAsPDSS () const virtual
Duplication routine for objects which inherit from PDSS.
This function can be used to duplicate objects derived from PDSS even if the application only has a pointer to PDSS to work with.
Returns
A pointer to the base PDSS object type
Reimplemented from PDSS.
Definition at line 83 of file PDSS_SSVol.cpp.
References PDSS_SSVol::PDSS_SSVol().
doublereal enthalpy_mole () const virtual
Return the molar enthalpy in units of J kmol-1.
Returns
the species standard state enthalpy in J kmol-1 at the current temperature and pressure.
Reimplemented from PDSS.
Definition at line 186 of file PDSS_SSVol.cpp.
References PDSS_SSVol::enthalpy_RT(), Cantera::GasConstant, and PDSS::m_temp.
doublereal enthalpy_RT () const virtual
Return the standard state molar enthalpy divided by RT.
Returns
The dimensionless species standard state enthalpy divided at the current temperature and pressure.
Reimplemented from PDSS.
Definition at line 194 of file PDSS_SSVol.cpp.
References PDSS::m_hss_RT_ptr, and PDSS::m_spindex.
Referenced by PDSS_SSVol::enthalpy_mole().
doublereal intEnergy_mole () const virtual
Return the molar internal Energy in units of J kmol-1.
Returns
The species standard state internal Energy in J kmol-1 at the current temperature and pressure.
Reimplemented from PDSS.
Definition at line 200 of file PDSS_SSVol.cpp.
References Cantera::GasConstant, PDSS::m_h0_RT_ptr, PDSS::m_pres, PDSS::m_spindex, PDSS::m_temp, and PDSS::m_Vss_ptr.
doublereal entropy_mole () const virtual
Return the molar entropy in units of J kmol-1 K-1.
Returns
The species standard state entropy in J kmol-1 K-1 at the current temperature and pressure.
Reimplemented from PDSS.
Definition at line 209 of file PDSS_SSVol.cpp.
References PDSS_SSVol::entropy_R(), and Cantera::GasConstant.
doublereal entropy_R () const virtual
Return the standard state entropy divided by RT.
Returns
The species standard state entropy divided by RT at the current temperature and pressure.
Reimplemented from PDSS.
Definition at line 216 of file PDSS_SSVol.cpp.
References PDSS::m_spindex, and PDSS::m_sss_R_ptr.
Referenced by PDSS_SSVol::entropy_mole().
doublereal gibbs_mole () const virtual
Return the molar Gibbs free energy in units of J kmol-1.
Returns
The species standard state Gibbs free energy in J kmol-1 at the current temperature and pressure.
Reimplemented from PDSS.
Definition at line 222 of file PDSS_SSVol.cpp.
References Cantera::GasConstant, PDSS_SSVol::gibbs_RT(), and PDSS::m_temp.
doublereal gibbs_RT () const virtual
Return the molar Gibbs free energy divided by RT.
Returns
The species standard state Gibbs free energy divided by RT at the current temperature and pressure.
Reimplemented from PDSS.
Definition at line 230 of file PDSS_SSVol.cpp.
References PDSS::m_gss_RT_ptr, and PDSS::m_spindex.
Referenced by PDSS_SSVol::gibbs_mole().
doublereal cp_mole () const virtual
Return the molar const pressure heat capacity in units of J kmol-1 K-1.
Returns
The species standard state Cp in J kmol-1 K-1 at the current temperature and pressure.
Reimplemented from PDSS.
Definition at line 236 of file PDSS_SSVol.cpp.
References Cantera::GasConstant, PDSS::m_cpss_R_ptr, and PDSS::m_spindex.
Referenced by PDSS_SSVol::cv_mole().
doublereal cp_R () const virtual
Return the molar const pressure heat capacity divided by RT.
Returns
The species standard state Cp divided by RT at the current temperature and pressure.
Reimplemented from PDSS.
Definition at line 243 of file PDSS_SSVol.cpp.
References PDSS::m_cpss_R_ptr, and PDSS::m_spindex.
doublereal cv_mole () const virtual
Return the molar const volume heat capacity in units of J kmol-1 K-1.
Returns
The species standard state Cv in J kmol-1 K-1 at the current temperature and pressure.
Reimplemented from PDSS.
Definition at line 249 of file PDSS_SSVol.cpp.
References PDSS_SSVol::cp_mole(), PDSS::m_spindex, and PDSS::m_V0_ptr.
doublereal molarVolume () const virtual
Return the molar volume at standard state.
Returns
The standard state molar volume at the current temperature and pressure. Units are m**3 kmol-1.
Reimplemented from PDSS.
Definition at line 255 of file PDSS_SSVol.cpp.
References PDSS::m_spindex, and PDSS::m_Vss_ptr.
doublereal density () const virtual
Return the standard state density at standard state.
Returns
The standard state density at the current temperature and pressure. units are kg m-3
Reimplemented from PDSS.
Definition at line 261 of file PDSS_SSVol.cpp.
References PDSS::m_mw, PDSS::m_spindex, and PDSS::m_Vss_ptr.
doublereal gibbs_RT_ref () const virtual
Return the molar gibbs free energy divided by RT at reference pressure.
Returns
The reference state gibbs free energy at the current temperature, divided by RT.
Reimplemented from PDSS.
Definition at line 268 of file PDSS_SSVol.cpp.
References PDSS::m_g0_RT_ptr, and PDSS::m_spindex.
doublereal enthalpy_RT_ref () const virtual
Return the molar enthalpy divided by RT at reference pressure.
Returns
The species reference state enthalpy at the current temperature, divided by RT.
Reimplemented from PDSS.
Definition at line 273 of file PDSS_SSVol.cpp.
References PDSS::m_h0_RT_ptr, and PDSS::m_spindex.
doublereal entropy_R_ref () const virtual
Return the molar entropy divided by R at reference pressure.
Returns
The species reference state entropy at the current temperature, divided by R.
Reimplemented from PDSS.
Definition at line 278 of file PDSS_SSVol.cpp.
References PDSS::m_s0_R_ptr, and PDSS::m_spindex.
doublereal cp_R_ref () const virtual
Return the molar heat capacity divided by R at reference pressure.
Returns
The species reference state heat capacity divided by R at the current temperature.
Reimplemented from PDSS.
Definition at line 283 of file PDSS_SSVol.cpp.
References PDSS::m_cp0_R_ptr, and PDSS::m_spindex.
doublereal molarVolume_ref () const virtual
Return the molar volume at reference pressure.
Returns
The reference state molar volume. units are m**3 kmol-1.
Reimplemented from PDSS.
Definition at line 288 of file PDSS_SSVol.cpp.
References PDSS::m_spindex, and PDSS::m_V0_ptr.
void calcMolarVolume () const private
Does the internal calculation of the volume.
Definition at line 293 of file PDSS_SSVol.cpp.
References Cantera::cSSVOLUME_CONSTANT, Cantera::cSSVOLUME_DENSITY_TPOLY, Cantera::cSSVOLUME_TPOLY, PDSS_SSVol::d2VdT2_, PDSS_SSVol::dVdT_, PDSS_SSVol::m_constMolarVolume, PDSS::m_mw, PDSS::m_spindex, PDSS::m_temp, PDSS::m_Vss_ptr, PDSS_SSVol::TCoeff_, and PDSS_SSVol::volumeModel_.
Referenced by PDSS_SSVol::setTemperature().
void setPressure (doublereal pres) private virtual
Sets the pressure in the object.
Currently, this sets the pressure in the PDSS object. It is indeterminant what happens to the owning VPStandardStateTP object and to the VPSSMgr object.
Parameters
pres Pressure to be set (Pascal)
Reimplemented from PDSS.
Definition at line 332 of file PDSS_SSVol.cpp.
References PDSS_SSVol::d2VdT2_, PDSS_SSVol::dVdT_, Cantera::GasConstant, PDSS::m_cp0_R_ptr, PDSS::m_cpss_R_ptr, PDSS::m_gss_RT_ptr, PDSS::m_h0_RT_ptr, PDSS::m_hss_RT_ptr, PDSS::m_p0, PDSS::m_pres, PDSS::m_s0_R_ptr, PDSS::m_spindex, PDSS::m_sss_R_ptr, PDSS::m_temp, and PDSS::m_Vss_ptr.
void setTemperature (doublereal temp) private virtual
Set the internal temperature.
Parameters
temp Temperature (Kelvin)
Reimplemented from PDSS.
Definition at line 351 of file PDSS_SSVol.cpp.
References PDSS_SSVol::calcMolarVolume(), PDSS_SSVol::d2VdT2_, PDSS_SSVol::dVdT_, Cantera::GasConstant, PDSS::m_cp0_R_ptr, PDSS::m_cpss_R_ptr, PDSS::m_g0_RT_ptr, PDSS::m_gss_RT_ptr, PDSS::m_h0_RT_ptr, PDSS::m_hss_RT_ptr, PDSS::m_p0, PDSS::m_pres, PDSS::m_s0_R_ptr, PDSS::m_spindex, PDSS::m_spthermo, PDSS::m_sss_R_ptr, PDSS::m_temp, PDSS::m_Vss_ptr, and SpeciesThermo::update_one().
Referenced by PDSS_SSVol::setState_TP(), and PDSS_SSVol::setState_TR().
void setState_TP (doublereal temp, doublereal pres) private virtual
Set the internal temperature and pressure.
Parameters
temp Temperature (Kelvin)
pres pressure (Pascals)
Reimplemented from PDSS.
Definition at line 373 of file PDSS_SSVol.cpp.
References PDSS::m_pres, and PDSS_SSVol::setTemperature().
void setState_TR (doublereal temp, doublereal rho) private virtual
Set the internal temperature and density.
Parameters
temp Temperature (Kelvin)
rho Density (kg m-3)
Reimplemented from PDSS.
Definition at line 379 of file PDSS_SSVol.cpp.
References PDSS_SSVol::m_constMolarVolume, PDSS::m_mw, and PDSS_SSVol::setTemperature().
doublereal critTemperature () const private virtual
critical temperature
Reimplemented from PDSS.
Definition at line 314 of file PDSS_SSVol.cpp.
doublereal critPressure () const private virtual
critical pressure
Reimplemented from PDSS.
Definition at line 320 of file PDSS_SSVol.cpp.
doublereal critDensity () const private virtual
critical density
Reimplemented from PDSS.
Definition at line 326 of file PDSS_SSVol.cpp.
doublereal satPressure (doublereal T) private virtual
saturation pressure
Parameters
T Temperature (Kelvin)
Reimplemented from PDSS.
Definition at line 389 of file PDSS_SSVol.cpp.
void initThermo () private virtual
Initialization routine for all of the shallow pointers.
This is a cascading call, where each level should call the the parent level.
The initThermo() routines get called before the initThermoXML() routines from the constructPDSSXML() routine.
Calls initPtrs();
Reimplemented from PDSS.
Definition at line 176 of file PDSS_SSVol.cpp.
References PDSS::initThermo(), PDSS_SSVol::m_constMolarVolume, PDSS::m_p0, PDSS::m_spindex, PDSS::m_tp, PDSS::m_V0_ptr, PDSS::m_Vss_ptr, SpeciesThermo::refPressure(), and ThermoPhase::speciesThermo().
void constructPDSSFile (VPStandardStateTP * vptp_ptr, size_t spindex, const std::string & inputFile, const std::string & id) private
Initialization of a PDSS object using an input XML file.
This routine is a precursor to constructPDSSXML(XML_Node*) routine, which does most of the work.
Parameters
vptp_ptr Pointer to the Variable pressure ThermoPhase object This object must have already been malloced.
spindex Species index within the phase
inputFile XML file containing the description of the phase
id Optional parameter identifying the name of the phase. If none is given, the first XML phase element will be used.
Definition at line 130 of file PDSS_SSVol.cpp.
References XML_Node::build(), XML_Node::child(), PDSS_SSVol::constructPDSSXML(), XML_Node::findByAttr(), Cantera::findInputFile(), Cantera::findXMLPhase(), Cantera::get_XML_NameID(), XML_Node::root(), and Phase::speciesNames().
Referenced by PDSS_SSVol::PDSS_SSVol().
void constructPDSSXML (VPStandardStateTP * vptp_ptr, size_t spindex, const XML_Node & speciesNode, const XML_Node & phaseNode, bool spInstalled) private
Initialization of a PDSS object using an xml tree.
This routine is a driver for the initialization of the object.
basic logic:
initThermo() (cascade)
getStuff from species Part of XML file
initThermoXML(phaseNode) (cascade)
Parameters
vptp_ptr Pointer to the Variable pressure ThermoPhase object This object must have already been malloced.
spindex Species index within the phase
speciesNode XML Node containing the species information
phaseNode Reference to the phase Information for the phase that owns this species.
spInstalled Boolean indicating whether the species is already installed.
Definition at line 88 of file PDSS_SSVol.cpp.
References Cantera::cSSVOLUME_CONSTANT, Cantera::cSSVOLUME_DENSITY_TPOLY, Cantera::cSSVOLUME_TPOLY, XML_Node::findByName(), ctml::getFloat(), ctml::getFloatArray(), PDSS::initThermo(), PDSS_SSVol::m_constMolarVolume, PDSS::m_p0, PDSS::m_spindex, PDSS::m_tp, XML_Node::name(), SpeciesThermo::refPressure(), ThermoPhase::speciesThermo(), PDSS_SSVol::TCoeff_, and PDSS_SSVol::volumeModel_.
Referenced by PDSS_SSVol::constructPDSSFile(), and PDSS_SSVol::PDSS_SSVol().
void initThermoXML (const XML_Node & phaseNode, const std::string & id) private virtual
Initialization routine for the PDSS object based on the phaseNode.
This is a cascading call, where each level should call the the parent level.
Parameters
phaseNode Reference to the phase Information for the phase that owns this species.
id Optional parameter identifying the name of the phase. If none is given, the first XML phase element will be used.
Reimplemented from PDSS.
Definition at line 167 of file PDSS_SSVol.cpp.
References PDSS::initThermoXML(), PDSS::m_maxTemp, PDSS::m_minTemp, PDSS::m_mw, PDSS::m_p0, PDSS::m_spindex, PDSS::m_spthermo, PDSS::m_tp, SpeciesThermo::maxTemp(), SpeciesThermo::minTemp(), Phase::molecularWeight(), and SpeciesThermo::refPressure().
Member Data Documentation
SSVolume_Model_enumType volumeModel_ private
Enumerated data type describing the type of volume model used to calculate the standard state volume of the species.
Definition at line 324 of file PDSS_SSVol.h.
Referenced by PDSS_SSVol::calcMolarVolume(), PDSS_SSVol::constructPDSSXML(), and PDSS_SSVol::operator=().
doublereal m_constMolarVolume private
Value of the constant molar volume for the species.
m3 / kmol
Definition at line 330 of file PDSS_SSVol.h.
Referenced by PDSS_SSVol::calcMolarVolume(), PDSS_SSVol::constructPDSSXML(), PDSS_SSVol::initThermo(), PDSS_SSVol::operator=(), and PDSS_SSVol::setState_TR().
vector_fp TCoeff_ private
coefficients for the temperature representation
Definition at line 333 of file PDSS_SSVol.h.
Referenced by PDSS_SSVol::calcMolarVolume(), PDSS_SSVol::constructPDSSXML(), PDSS_SSVol::operator=(), and PDSS_SSVol::PDSS_SSVol().
doublereal dVdT_ mutable private
Derivative of the volume wrt temperature.
Definition at line 336 of file PDSS_SSVol.h.
Referenced by PDSS_SSVol::calcMolarVolume(), PDSS_SSVol::setPressure(), and PDSS_SSVol::setTemperature().
doublereal d2VdT2_ mutable private
2nd derivative of the volume wrt temperature
Definition at line 339 of file PDSS_SSVol.h.
Referenced by PDSS_SSVol::calcMolarVolume(), PDSS_SSVol::setPressure(), and PDSS_SSVol::setTemperature().
The documentation for this class was generated from the following files:
PDSS_SSVol.h
PDSS_SSVol.cpp