Cantera: Species Reference-State Thermodynamic Properties
Species Reference-State Thermodynamic Properties
Thermodynamic Properties
The ThermoPhase object relies on classes to calculate the thermodynamic properties of the reference state for all of the species in the phase.
Classes
class ConstCpPoly
A constant-heat capacity species thermodynamic property manager class.
class Nasa9PolyMultiTempRegion
The NASA 9 polynomial parameterization for a single species encompassing multiple temperature regions.
class NasaPoly2
The NASA polynomial parameterization for two temperature ranges.
class ShomatePoly
The Shomate polynomial parameterization for one temperature range for one species.
class ShomatePoly2
The Shomate polynomial parameterization for two temperature ranges for one species.
class Adsorbate
An adsorbed surface species.
class Mu0Poly
The Mu0Poly class implements an interpolation of the Gibbs free energy based on a piecewise constant heat capacity approximation.
class Nasa9Poly1
The NASA 9 polynomial parameterization for one temperature range.
class NasaPoly1
The NASA polynomial parameterization for one temperature range.
class SpeciesThermoInterpType
Pure Virtual Base class for the thermodynamic manager for an individual species' reference state.
class STITbyPDSS
Class for the thermodynamic manager for an individual species' reference state which uses the PDSS base class to satisfy the requests.
class StatMech
Statistical mechanics.
Functions
void installMu0ThermoFromXML (const std::string &speciesName, SpeciesThermo &sp, size_t k, const XML_Node *Mu0Node_ptr)
Install a Mu0 polynomial thermodynamic reference state.
Detailed Description
The ThermoPhase object relies on classes to calculate the thermodynamic properties of the reference state for all of the species in the phase.
This group describes the types and functionality of the classes that calculate the reference state thermodynamic functions within Cantera.
To compute the thermodynamic properties of multicomponent solutions, it is necessary to know something about the thermodynamic properties of the individual species present in the solution. Exactly what sort of species properties are required depends on the thermodynamic model for the solution. For a gaseous solution (i.e., a gas mixture), the species properties required are usually ideal gas properties at the mixture temperature and at a reference pressure (almost always at 1 bar). For other types of solutions, however, it may not be possible to isolate the species in a "pure" state. For example, the thermodynamic properties of, say, Na+ and Cl- in saltwater are not easily determined from data on the properties of solid NaCl, or solid Na metal, or chlorine gas. In this case, the solvation in water is fundamental to the identity of the species, and some other reference state must be used. One common convention for liquid solutions is to use thermodynamic data for the solutes in the limit of infinite dilution within the pure solvent; another convention is to reference all properties to unit molality.
In defining these standard states for species in a phase, we make the following definition. A reference state is a standard state of a species in a phase limited to one particular pressure, the reference pressure. The reference state specifies the dependence of all thermodynamic functions as a function of the temperature, in between a minimum temperature and a maximum temperature. The reference state also specifies the molar volume of the species as a function of temperature. The molar volume is a thermodynamic function. A full standard state does the same thing as a reference state, but specifies the thermodynamics functions at all pressures.
Whatever the conventions used by a particular solution model, means need to be provided to compute the species properties in the reference state. Class SpeciesThermo is the base class for a family of classes that compute properties of all species in a phase in their reference states, for a range of temperatures. Note, the pressure dependence of the species thermodynamic functions is not handled by this particular species thermodynamic model. SpeciesThermo calculates the reference-state thermodynamic values of all species in a single phase during each call.
The class SpeciesThermoInterpType is a pure virtual base class for calculation of thermodynamic functions for a single species in its reference state. The following classes inherit from SpeciesThermoInterpType.
NasaPoly1 in file NasaPoly1.h
This is a one zone model, consisting of a 7 coefficient Nasa Polynomial format.
NasaPoly2 in file NasaPoly2.h
This is a two zone model, with each zone consisting of a 7 coefficient Nasa Polynomial format.
ShomatePoly in file ShomatePoly.h
This is a one zone model, consisting of a 7 coefficient Shomate Polynomial format.
ShomatePoly2 in file ShomatePoly.h
This is a two zone model, with each zone consisting of a 7 coefficient Shomate Polynomial format.
ConstCpPoly in file ConstCpPoly.h
This is a one-zone constant heat capacity model.
Mu0Poly in file Mu0Poly.h
This is a multizoned model. The chemical potential is given at a set number of temperatures. Between each temperature the heat capacity is treated as a constant.
Nasa9Poly1 in file Nasa9Poly1.h
This is a one zone model, consisting of the 9 coefficient Nasa Polynomial format.
Nasa9PolyMultiTempRegion in file Nasa9PolyMultiTempRegion.h
This is a multiple zone model, consisting of the 9 coefficient Nasa Polynomial format in each zone.
STITbyPDSS in file SpeciesThermoInterpType.h
This is an object that calculates reference state thermodynamic functions by relying on a pressure dependent standard state object (i.e., a PDSS object) to calculate the thermodynamic functions.
The most important member function for the SpeciesThermoInterpType class is the member function updatePropertiesTemp(). The function calculates the values of Cp, H, and S for the specific species pertaining to this class. It takes as its arguments the base pointer for the vector of Cp, H, and S values for all species in the phase. The offset for the species is known within the object.
A key concept for reference states is that there is a maximum and a minimum temperature beyond which the thermodynamic formulation isn't valid. Calls for temperatures outside this range will cause the object to throw a CanteraError.
Function Documentation
void installMu0ThermoFromXML (const std::string & speciesName, SpeciesThermo & sp, size_t k, const XML_Node * Mu0Node_ptr)
Install a Mu0 polynomial thermodynamic reference state.
Install a Mu0 polynomial thermodynamic reference state property parameterization for species k into a SpeciesThermo instance, getting the information from an XML database.
Parameters
speciesName Name of the species
sp Owning SpeciesThermo object
k Species index
Mu0Node_ptr Pointer to the XML element containing the Mu0 information.
Definition at line 126 of file Mu0Poly.cpp.
References Cantera::fpValue(), ctml::getByTitle(), ctml::getFloat(), ctml::getFloatArray(), ctml::getInteger(), XML_Node::hasChild(), SpeciesThermo::install(), and MU0_INTERP.
Referenced by SpeciesThermoFactory::installThermoForSpecies().