Cantera: IdealSolnGasVPSS Class Reference
IdealSolnGasVPSS Class Reference
Models of Phases of Matter » Thermodynamic Properties
An ideal solution or an ideal gas approximation of a phase.
#include <IdealSolnGasVPSS.h>
Public Member Functions
virtual Units standardConcentrationUnits () const
Returns the units of the "standard concentration" for this phase.
virtual void getActivityConcentrations (doublereal *c) const
This method returns an array of generalized concentrations.
virtual doublereal standardConcentration (size_t k=0) const
Returns the standard concentration \(C^0_k \), which is used to normalize the generalized concentration.
virtual void getActivityCoefficients (doublereal *ac) const
Get the array of non-dimensional activity coefficients at the current solution temperature, pressure, and solution concentration.
Constructors and Duplicators for IdealSolnGasVPSS
IdealSolnGasVPSS ()
IdealSolnGasVPSS (const std::string &infile, std::string id="")
Create an object from an input file.
Utilities (IdealSolnGasVPSS)
virtual std::string type () const
String indicating the thermodynamic model implemented.
virtual std::string phaseOfMatter () const
String indicating the mechanical phase of the matter in this Phase.
void setGasMode ()
Set this phase to represent an ideal gas.
void setSolnMode ()
Set this phase to represent an ideal liquid or solid solution.
void setStandardConcentrationModel (const std::string &model)
Set the standard concentration model.
Molar Thermodynamic Properties
virtual doublereal enthalpy_mole () const
Molar enthalpy. Units: J/kmol.
virtual doublereal entropy_mole () const
Molar entropy. Units: J/kmol/K.
virtual doublereal cp_mole () const
Molar heat capacity at constant pressure. Units: J/kmol/K.
virtual doublereal cv_mole () const
Molar heat capacity at constant volume. Units: J/kmol/K.
Partial Molar Properties of the Solution
virtual void getChemPotentials (doublereal *mu) const
Get the species chemical potentials. Units: J/kmol.
virtual void getPartialMolarEnthalpies (doublereal *hbar) const
Returns an array of partial molar enthalpies for the species in the mixture.
virtual void getPartialMolarEntropies (doublereal *sbar) const
Returns an array of partial molar entropies of the species in the solution.
virtual void getPartialMolarIntEnergies (doublereal *ubar) const
Return an array of partial molar internal energies for the species in the mixture.
virtual void getPartialMolarCp (doublereal *cpbar) const
Return an array of partial molar heat capacities for the species in the mixture.
virtual void getPartialMolarVolumes (doublereal *vbar) const
Return an array of partial molar volumes for the species in the mixture.
Public Member Functions inherited from VPStandardStateTP
VPStandardStateTP ()
Constructor.
virtual bool isCompressible () const
Return whether phase represents a compressible substance.
virtual int standardStateConvention () const
This method returns the convention used in specification of the standard state, of which there are currently two, temperature based, and variable pressure based.
virtual void getdlnActCoeffdlnN_diag (doublereal *dlnActCoeffdlnN_diag) const
Get the array of log species mole number derivatives of the log activity coefficients.
virtual void getChemPotentials_RT (doublereal *mu) const
Get the array of non-dimensional species chemical potentials.
void installPDSS (size_t k, std::unique_ptr< PDSS > &&pdss)
Install a PDSS object for species k
PDSS * providePDSS (size_t k)
const PDSS * providePDSS (size_t k) const
virtual bool addSpecies (shared_ptr< Species > spec)
Add a Species to this Phase.
virtual void getStandardChemPotentials (doublereal *mu) const
Get the array of chemical potentials at unit activity for the species at their standard states at the current T and P of the solution.
virtual void getEnthalpy_RT (doublereal *hrt) const
Get the nondimensional Enthalpy functions for the species at their standard states at the current T and P of the solution.
virtual void getEntropy_R (doublereal *sr) const
Get the array of nondimensional Entropy functions for the standard state species at the current T and P of the solution.
virtual void getGibbs_RT (doublereal *grt) const
Get the nondimensional Gibbs functions for the species in their standard states at the current T and P of the solution.
virtual void getPureGibbs (doublereal *gpure) const
Get the Gibbs functions for the standard state of the species at the current T and P of the solution.
virtual void getIntEnergy_RT (doublereal *urt) const
Returns the vector of nondimensional Internal Energies of the standard state species at the current T and P of the solution.
virtual void getCp_R (doublereal *cpr) const
Get the nondimensional Heat Capacities at constant pressure for the species standard states at the current T and P of the solution.
virtual void getStandardVolumes (doublereal *vol) const
Get the molar volumes of the species standard states at the current T and P of the solution.
virtual const vector_fp & getStandardVolumes () const
virtual void setTemperature (const doublereal temp)
Set the temperature of the phase.
virtual void setState_TP (doublereal T, doublereal pres)
Set the temperature and pressure at the same time.
virtual doublereal pressure () const
Returns the current pressure of the phase.
virtual void updateStandardStateThermo () const
Updates the standard state thermodynamic functions at the current T and P of the solution.
virtual double minTemp (size_t k=npos) const
Minimum temperature for which the thermodynamic data for the species or phase are valid.
virtual double maxTemp (size_t k=npos) const
Maximum temperature for which the thermodynamic data for the species are valid.
virtual void getEnthalpy_RT_ref (doublereal *hrt) const
virtual void getGibbs_RT_ref (doublereal *grt) const
Returns the vector of nondimensional Gibbs Free Energies of the reference state at the current temperature of the solution and the reference pressure for the species.
virtual void getGibbs_ref (doublereal *g) const
Returns the vector of the Gibbs function of the reference state at the current temperature of the solution and the reference pressure for the species.
virtual void getEntropy_R_ref (doublereal *er) const
Returns the vector of nondimensional entropies of the reference state at the current temperature of the solution and the reference pressure for each species.
virtual void getCp_R_ref (doublereal *cprt) const
Returns the vector of nondimensional constant pressure heat capacities of the reference state at the current temperature of the solution and reference pressure for each species.
virtual void getStandardVolumes_ref (doublereal *vol) const
Get the molar volumes of the species reference states at the current T and P_ref of the solution.
Public Member Functions inherited from ThermoPhase
ThermoPhase ()
Constructor.
virtual doublereal refPressure () const
Returns the reference pressure in Pa.
doublereal Hf298SS (const size_t k) const
Report the 298 K Heat of Formation of the standard state of one species (J kmol-1)
virtual void modifyOneHf298SS (const size_t k, const doublereal Hf298New)
Modify the value of the 298 K Heat of Formation of one species in the phase (J kmol-1)
virtual void resetHf298 (const size_t k=npos)
Restore the original heat of formation of one or more species.
bool chargeNeutralityNecessary () const
Returns the chargeNeutralityNecessity boolean.
virtual doublereal intEnergy_mole () const
Molar internal energy. Units: J/kmol.
virtual doublereal gibbs_mole () const
Molar Gibbs function. Units: J/kmol.
virtual doublereal thermalExpansionCoeff () const
Return the volumetric thermal expansion coefficient. Units: 1/K.
void setElectricPotential (doublereal v)
Set the electric potential of this phase (V).
doublereal electricPotential () const
Returns the electric potential of this phase (V).
virtual int activityConvention () const
This method returns the convention used in specification of the activities, of which there are currently two, molar- and molality-based conventions.
virtual doublereal logStandardConc (size_t k=0) const
Natural logarithm of the standard concentration of the kth species.
virtual void getActivities (doublereal *a) const
Get the array of non-dimensional activities at the current solution temperature, pressure, and solution concentration.
virtual void getLnActivityCoefficients (doublereal *lnac) const
Get the array of non-dimensional molar-based ln activity coefficients at the current solution temperature, pressure, and solution concentration.
void getElectrochemPotentials (doublereal *mu) const
Get the species electrochemical potentials.
virtual void getIntEnergy_RT_ref (doublereal *urt) const
Returns the vector of nondimensional internal Energies of the reference state at the current temperature of the solution and the reference pressure for each species.
doublereal enthalpy_mass () const
Specific enthalpy. Units: J/kg.
doublereal intEnergy_mass () const
Specific internal energy. Units: J/kg.
doublereal entropy_mass () const
Specific entropy. Units: J/kg/K.
doublereal gibbs_mass () const
Specific Gibbs function. Units: J/kg.
doublereal cp_mass () const
Specific heat at constant pressure. Units: J/kg/K.
doublereal cv_mass () const
Specific heat at constant volume. Units: J/kg/K.
doublereal RT () const
Return the Gas Constant multiplied by the current temperature.
virtual void setState_TPX (doublereal t, doublereal p, const doublereal *x)
Set the temperature (K), pressure (Pa), and mole fractions.
virtual void setState_TPX (doublereal t, doublereal p, const compositionMap &x)
Set the temperature (K), pressure (Pa), and mole fractions.
virtual void setState_TPX (doublereal t, doublereal p, const std::string &x)
Set the temperature (K), pressure (Pa), and mole fractions.
virtual void setState_TPY (doublereal t, doublereal p, const doublereal *y)
Set the internally stored temperature (K), pressure (Pa), and mass fractions of the phase.
virtual void setState_TPY (doublereal t, doublereal p, const compositionMap &y)
Set the internally stored temperature (K), pressure (Pa), and mass fractions of the phase.
virtual void setState_TPY (doublereal t, doublereal p, const std::string &y)
Set the internally stored temperature (K), pressure (Pa), and mass fractions of the phase.
virtual void setState_PX (doublereal p, doublereal *x)
Set the pressure (Pa) and mole fractions.
virtual void setState_PY (doublereal p, doublereal *y)
Set the internally stored pressure (Pa) and mass fractions.
virtual void setState_HP (double h, double p, double tol=1e-9)
Set the internally stored specific enthalpy (J/kg) and pressure (Pa) of the phase.
virtual void setState_UV (double u, double v, double tol=1e-9)
Set the specific internal energy (J/kg) and specific volume (m^3/kg).
virtual void setState_SP (double s, double p, double tol=1e-9)
Set the specific entropy (J/kg/K) and pressure (Pa).
virtual void setState_SV (double s, double v, double tol=1e-9)
Set the specific entropy (J/kg/K) and specific volume (m^3/kg).
virtual void setState_ST (double s, double t, double tol=1e-9)
Set the specific entropy (J/kg/K) and temperature (K).
virtual void setState_TV (double t, double v, double tol=1e-9)
Set the temperature (K) and specific volume (m^3/kg).
virtual void setState_PV (double p, double v, double tol=1e-9)
Set the pressure (Pa) and specific volume (m^3/kg).
virtual void setState_UP (double u, double p, double tol=1e-9)
Set the specific internal energy (J/kg) and pressure (Pa).
virtual void setState_VH (double v, double h, double tol=1e-9)
Set the specific volume (m^3/kg) and the specific enthalpy (J/kg)
virtual void setState_TH (double t, double h, double tol=1e-9)
Set the temperature (K) and the specific enthalpy (J/kg)
virtual void setState_SH (double s, double h, double tol=1e-9)
Set the specific entropy (J/kg/K) and the specific enthalpy (J/kg)
virtual void setState_RP (doublereal rho, doublereal p)
Set the density (kg/m**3) and pressure (Pa) at constant composition.
virtual void setState_RPX (doublereal rho, doublereal p, const doublereal *x)
Set the density (kg/m**3), pressure (Pa) and mole fractions.
virtual void setState_RPX (doublereal rho, doublereal p, const compositionMap &x)
Set the density (kg/m**3), pressure (Pa) and mole fractions.
virtual void setState_RPX (doublereal rho, doublereal p, const std::string &x)
Set the density (kg/m**3), pressure (Pa) and mole fractions.
virtual void setState_RPY (doublereal rho, doublereal p, const doublereal *y)
Set the density (kg/m**3), pressure (Pa) and mass fractions.
virtual void setState_RPY (doublereal rho, doublereal p, const compositionMap &y)
Set the density (kg/m**3), pressure (Pa) and mass fractions.
virtual void setState_RPY (doublereal rho, doublereal p, const std::string &y)
Set the density (kg/m**3), pressure (Pa) and mass fractions.
virtual void setState (const AnyMap &state)
Set the state using an AnyMap containing any combination of properties supported by the thermodynamic model.
void setMixtureFraction (double mixFrac, const double *fuelComp, const double *oxComp, ThermoBasis basis=ThermoBasis::molar)
Set the mixture composition according to the mixture fraction = kg fuel / (kg oxidizer + kg fuel)
void setMixtureFraction (double mixFrac, const std::string &fuelComp, const std::string &oxComp, ThermoBasis basis=ThermoBasis::molar)
Set the mixture composition according to the mixture fraction = kg fuel / (kg oxidizer + kg fuel)
void setMixtureFraction (double mixFrac, const compositionMap &fuelComp, const compositionMap &oxComp, ThermoBasis basis=ThermoBasis::molar)
Set the mixture composition according to the mixture fraction = kg fuel / (kg oxidizer + kg fuel)
double mixtureFraction (const double *fuelComp, const double *oxComp, ThermoBasis basis=ThermoBasis::molar, const std::string &element="Bilger") const
Compute the mixture fraction = kg fuel / (kg oxidizer + kg fuel) for the current mixture given fuel and oxidizer compositions.
double mixtureFraction (const std::string &fuelComp, const std::string &oxComp, ThermoBasis basis=ThermoBasis::molar, const std::string &element="Bilger") const
Compute the mixture fraction = kg fuel / (kg oxidizer + kg fuel) for the current mixture given fuel and oxidizer compositions.
double mixtureFraction (const compositionMap &fuelComp, const compositionMap &oxComp, ThermoBasis basis=ThermoBasis::molar, const std::string &element="Bilger") const
Compute the mixture fraction = kg fuel / (kg oxidizer + kg fuel) for the current mixture given fuel and oxidizer compositions.
void setEquivalenceRatio (double phi, const double *fuelComp, const double *oxComp, ThermoBasis basis=ThermoBasis::molar)
Set the mixture composition according to the equivalence ratio.
void setEquivalenceRatio (double phi, const std::string &fuelComp, const std::string &oxComp, ThermoBasis basis=ThermoBasis::molar)
Set the mixture composition according to the equivalence ratio.
void setEquivalenceRatio (double phi, const compositionMap &fuelComp, const compositionMap &oxComp, ThermoBasis basis=ThermoBasis::molar)
Set the mixture composition according to the equivalence ratio.
double equivalenceRatio (const double *fuelComp, const double *oxComp, ThermoBasis basis=ThermoBasis::molar) const
Compute the equivalence ratio for the current mixture given the compositions of fuel and oxidizer.
double equivalenceRatio (const std::string &fuelComp, const std::string &oxComp, ThermoBasis basis=ThermoBasis::molar) const
Compute the equivalence ratio for the current mixture given the compositions of fuel and oxidizer.
double equivalenceRatio (const compositionMap &fuelComp, const compositionMap &oxComp, ThermoBasis basis=ThermoBasis::molar) const
Compute the equivalence ratio for the current mixture given the compositions of fuel and oxidizer.
double equivalenceRatio () const
Compute the equivalence ratio for the current mixture from available oxygen and required oxygen.
void equilibrate (const std::string &XY, const std::string &solver="auto", double rtol=1e-9, int max_steps=50000, int max_iter=100, int estimate_equil=0, int log_level=0)
Equilibrate a ThermoPhase object.
virtual bool compatibleWithMultiPhase () const
Indicates whether this phase type can be used with class MultiPhase for equilibrium calculations.
virtual doublereal critTemperature () const
Critical temperature (K).
virtual doublereal critPressure () const
Critical pressure (Pa).
virtual doublereal critVolume () const
Critical volume (m3/kmol).
virtual doublereal critCompressibility () const
Critical compressibility (unitless).
virtual doublereal critDensity () const
Critical density (kg/m3).
virtual doublereal satTemperature (doublereal p) const
Return the saturation temperature given the pressure.
virtual doublereal satPressure (doublereal t)
Return the saturation pressure given the temperature.
virtual doublereal vaporFraction () const
Return the fraction of vapor at the current conditions.
virtual void setState_Tsat (doublereal t, doublereal x)
Set the state to a saturated system at a particular temperature.
virtual void setState_Psat (doublereal p, doublereal x)
Set the state to a saturated system at a particular pressure.
void setState_TPQ (double T, double P, double Q)
Set the temperature, pressure, and vapor fraction (quality).
virtual void modifySpecies (size_t k, shared_ptr< Species > spec)
Modify the thermodynamic data associated with a species.
void saveSpeciesData (const size_t k, const XML_Node *const data)
Store a reference pointer to the XML tree containing the species data for this phase.
const std::vector< const XML_Node * > & speciesData () const
Return a pointer to the vector of XML nodes containing the species data for this phase.
virtual MultiSpeciesThermo & speciesThermo (int k=-1)
Return a changeable reference to the calculation manager for species reference-state thermodynamic properties.
virtual const MultiSpeciesThermo & speciesThermo (int k=-1) const
virtual void initThermoFile (const std::string &inputFile, const std::string &id)
virtual void setParameters (int n, doublereal *const c)
Set the equation of state parameters.
virtual void getParameters (int &n, doublereal *const c) const
Get the equation of state parameters in a vector.
virtual void setParameters (const AnyMap &phaseNode, const AnyMap &rootNode=AnyMap())
Set equation of state parameters from an AnyMap phase description.
const AnyMap & input () const
Access input data associated with the phase description.
AnyMap & input ()
virtual void setStateFromXML (const XML_Node &state)
Set the initial state of the phase to the conditions specified in the state XML element.
virtual void getdlnActCoeffds (const doublereal dTds, const doublereal *const dXds, doublereal *dlnActCoeffds) const
Get the change in activity coefficients wrt changes in state (temp, mole fraction, etc) along a line in parameter space or along a line in physical space.
virtual void getdlnActCoeffdlnX_diag (doublereal *dlnActCoeffdlnX_diag) const
Get the array of ln mole fraction derivatives of the log activity coefficients - diagonal component only.
virtual void getdlnActCoeffdlnN (const size_t ld, doublereal *const dlnActCoeffdlnN)
Get the array of derivatives of the log activity coefficients with respect to the log of the species mole numbers.
virtual void getdlnActCoeffdlnN_numderiv (const size_t ld, doublereal *const dlnActCoeffdlnN)
virtual std::string report (bool show_thermo=true, doublereal threshold=-1e-14) const
returns a summary of the state of the phase as a string
virtual void reportCSV (std::ofstream &csvFile) const
returns a summary of the state of the phase to a comma separated file.
double stoichAirFuelRatio (const double *fuelComp, const double *oxComp, ThermoBasis basis=ThermoBasis::molar) const
Compute the stoichiometric air to fuel ratio (kg oxidizer / kg fuel) given fuel and oxidizer compositions.
double stoichAirFuelRatio (const std::string &fuelComp, const std::string &oxComp, ThermoBasis basis=ThermoBasis::molar) const
Compute the stoichiometric air to fuel ratio (kg oxidizer / kg fuel) given fuel and oxidizer compositions.
double stoichAirFuelRatio (const compositionMap &fuelComp, const compositionMap &oxComp, ThermoBasis basis=ThermoBasis::molar) const
Compute the stoichiometric air to fuel ratio (kg oxidizer / kg fuel) given fuel and oxidizer compositions.
Public Member Functions inherited from Phase
Phase ()
Default constructor.
Phase (const Phase &)=delete
Phase & operator= (const Phase &)=delete
XML_Node & xml () const
Returns a const reference to the XML_Node that describes the phase.
void setXMLdata (XML_Node &xmlPhase)
Stores the XML tree information for the current phase.
virtual bool isPure () const
Return whether phase represents a pure (single species) substance.
virtual bool hasPhaseTransition () const
Return whether phase represents a substance with phase transitions.
virtual std::map< std::string, size_t > nativeState () const
Return a map of properties defining the native state of a substance.
virtual std::vector< std::string > fullStates () const
Return a vector containing full states defining a phase.
virtual std::vector< std::string > partialStates () const
Return a vector of settable partial property sets within a phase.
virtual size_t stateSize () const
Return size of vector defining internal state of the phase.
void saveState (vector_fp &state) const
Save the current internal state of the phase.
virtual void saveState (size_t lenstate, doublereal *state) const
Write to array 'state' the current internal state.
void restoreState (const vector_fp &state)
Restore a state saved on a previous call to saveState.
virtual void restoreState (size_t lenstate, const doublereal *state)
Restore the state of the phase from a previously saved state vector.
doublereal molecularWeight (size_t k) const
Molecular weight of species k.
void getMolecularWeights (vector_fp &weights) const
Copy the vector of molecular weights into vector weights.
void getMolecularWeights (doublereal *weights) const
Copy the vector of molecular weights into array weights.
const vector_fp & molecularWeights () const
Return a const reference to the internal vector of molecular weights.
void getCharges (double *charges) const
Copy the vector of species charges into array charges.
virtual bool ready () const
Returns a bool indicating whether the object is ready for use.
int stateMFNumber () const
Return the State Mole Fraction Number.
bool caseSensitiveSpecies () const
Returns true if case sensitive species names are enforced.
void setCaseSensitiveSpecies (bool cflag=true)
Set flag that determines whether case sensitive species are enforced in look-up operations, e.g.
virtual void setRoot (std::shared_ptr< Solution > root)
Set root Solution holding all phase information.
vector_fp getCompositionFromMap (const compositionMap &comp) const
Converts a compositionMap to a vector with entries for each species Species that are not specified are set to zero in the vector.
void massFractionsToMoleFractions (const double *Y, double *X) const
Converts a mixture composition from mole fractions to mass fractions.
void moleFractionsToMassFractions (const double *X, double *Y) const
Converts a mixture composition from mass fractions to mole fractions.
std::string id () const
Return the string id for the phase.
void setID (const std::string &id)
Set the string id for the phase.
std::string name () const
Return the name of the phase.
void setName (const std::string &nm)
Sets the string name for the phase.
std::string elementName (size_t m) const
Name of the element with index m.
size_t elementIndex (const std::string &name) const
Return the index of element named 'name'.
const std::vector< std::string > & elementNames () const
Return a read-only reference to the vector of element names.
doublereal atomicWeight (size_t m) const
Atomic weight of element m.
doublereal entropyElement298 (size_t m) const
Entropy of the element in its standard state at 298 K and 1 bar.
int atomicNumber (size_t m) const
Atomic number of element m.
int elementType (size_t m) const
Return the element constraint type Possible types include:
int changeElementType (int m, int elem_type)
Change the element type of the mth constraint Reassigns an element type.
const vector_fp & atomicWeights () const
Return a read-only reference to the vector of atomic weights.
size_t nElements () const
Number of elements.
void checkElementIndex (size_t m) const
Check that the specified element index is in range.
void checkElementArraySize (size_t mm) const
Check that an array size is at least nElements().
doublereal nAtoms (size_t k, size_t m) const
Number of atoms of element m in species k.
void getAtoms (size_t k, double *atomArray) const
Get a vector containing the atomic composition of species k.
size_t speciesIndex (const std::string &name) const
Returns the index of a species named 'name' within the Phase object.
std::string speciesName (size_t k) const
Name of the species with index k.
std::string speciesSPName (int k) const
Returns the expanded species name of a species, including the phase name This is guaranteed to be unique within a Cantera problem.
const std::vector< std::string > & speciesNames () const
Return a const reference to the vector of species names.
size_t nSpecies () const
Returns the number of species in the phase.
void checkSpeciesIndex (size_t k) const
Check that the specified species index is in range.
void checkSpeciesArraySize (size_t kk) const
Check that an array size is at least nSpecies().
void setMoleFractionsByName (const compositionMap &xMap)
Set the species mole fractions by name.
void setMoleFractionsByName (const std::string &x)
Set the mole fractions of a group of species by name.
void setMassFractionsByName (const compositionMap &yMap)
Set the species mass fractions by name.
void setMassFractionsByName (const std::string &x)
Set the species mass fractions by name.
void setState_TRX (doublereal t, doublereal dens, const doublereal *x)
Set the internally stored temperature (K), density, and mole fractions.
void setState_TRX (doublereal t, doublereal dens, const compositionMap &x)
Set the internally stored temperature (K), density, and mole fractions.
void setState_TRY (doublereal t, doublereal dens, const doublereal *y)
Set the internally stored temperature (K), density, and mass fractions.
void setState_TRY (doublereal t, doublereal dens, const compositionMap &y)
Set the internally stored temperature (K), density, and mass fractions.
void setState_TNX (doublereal t, doublereal n, const doublereal *x)
Set the internally stored temperature (K), molar density (kmol/m^3), and mole fractions.
void setState_TR (doublereal t, doublereal rho)
Set the internally stored temperature (K) and density (kg/m^3)
void setState_TX (doublereal t, doublereal *x)
Set the internally stored temperature (K) and mole fractions.
void setState_TY (doublereal t, doublereal *y)
Set the internally stored temperature (K) and mass fractions.
void setState_RX (doublereal rho, doublereal *x)
Set the density (kg/m^3) and mole fractions.
void setState_RY (doublereal rho, doublereal *y)
Set the density (kg/m^3) and mass fractions.
compositionMap getMoleFractionsByName (double threshold=0.0) const
Get the mole fractions by name.
double moleFraction (size_t k) const
Return the mole fraction of a single species.
double moleFraction (const std::string &name) const
Return the mole fraction of a single species.
compositionMap getMassFractionsByName (double threshold=0.0) const
Get the mass fractions by name.
double massFraction (size_t k) const
Return the mass fraction of a single species.
double massFraction (const std::string &name) const
Return the mass fraction of a single species.
void getMoleFractions (double *const x) const
Get the species mole fraction vector.
virtual void setMoleFractions (const double *const x)
Set the mole fractions to the specified values.
virtual void setMoleFractions_NoNorm (const double *const x)
Set the mole fractions to the specified values without normalizing.
void getMassFractions (double *const y) const
Get the species mass fractions.
const double * massFractions () const
Return a const pointer to the mass fraction array.
virtual void setMassFractions (const double *const y)
Set the mass fractions to the specified values and normalize them.
virtual void setMassFractions_NoNorm (const double *const y)
Set the mass fractions to the specified values without normalizing.
void getConcentrations (double *const c) const
Get the species concentrations (kmol/m^3).
double concentration (const size_t k) const
Concentration of species k.
virtual void setConcentrations (const double *const conc)
Set the concentrations to the specified values within the phase.
virtual void setConcentrationsNoNorm (const double *const conc)
Set the concentrations without ignoring negative concentrations.
doublereal elementalMassFraction (const size_t m) const
Elemental mass fraction of element m.
doublereal elementalMoleFraction (const size_t m) const
Elemental mole fraction of element m.
const double * moleFractdivMMW () const
Returns a const pointer to the start of the moleFraction/MW array.
doublereal charge (size_t k) const
Dimensionless electrical charge of a single molecule of species k The charge is normalized by the the magnitude of the electron charge.
doublereal chargeDensity () const
Charge density [C/m^3].
size_t nDim () const
Returns the number of spatial dimensions (1, 2, or 3)
void setNDim (size_t ndim)
Set the number of spatial dimensions (1, 2, or 3).
doublereal temperature () const
Temperature (K).
virtual double density () const
Density (kg/m^3).
double molarDensity () const
Molar density (kmol/m^3).
double molarVolume () const
Molar volume (m^3/kmol).
virtual void setDensity (const double density_)
Set the internally stored density (kg/m^3) of the phase.
virtual void setMolarDensity (const double molarDensity)
Set the internally stored molar density (kmol/m^3) of the phase.
doublereal mean_X (const doublereal *const Q) const
Evaluate the mole-fraction-weighted mean of an array Q.
doublereal mean_X (const vector_fp &Q) const
Evaluate the mole-fraction-weighted mean of an array Q.
doublereal meanMolecularWeight () const
The mean molecular weight. Units: (kg/kmol)
doublereal sum_xlogx () const
Evaluate \(\sum_k X_k \log X_k \).
size_t addElement (const std::string &symbol, doublereal weight=-12345.0, int atomicNumber=0, doublereal entropy298=ENTROPY298_UNKNOWN, int elem_type=CT_ELEM_TYPE_ABSPOS)
Add an element.
void addSpeciesAlias (const std::string &name, const std::string &alias)
Add a species alias (i.e.
virtual std::vector< std::string > findIsomers (const compositionMap &compMap) const
Return a vector with isomers names matching a given composition map.
virtual std::vector< std::string > findIsomers (const std::string &comp) const
Return a vector with isomers names matching a given composition string.
shared_ptr< Species > species (const std::string &name) const
Return the Species object for the named species.
shared_ptr< Species > species (size_t k) const
Return the Species object for species whose index is k.
void ignoreUndefinedElements ()
Set behavior when adding a species containing undefined elements to just skip the species.
void addUndefinedElements ()
Set behavior when adding a species containing undefined elements to add those elements to the phase.
void throwUndefinedElements ()
Set the behavior when adding a species containing undefined elements to throw an exception.
Initialization Methods - For Internal use
int m_idealGas
boolean indicating what ideal solution this is
int m_formGC
form of the generalized concentrations
vector_fp m_pp
Temporary storage - length = m_kk.
virtual bool addSpecies (shared_ptr< Species > spec)
virtual void setParametersFromXML (const XML_Node &thermoNode)
Set equation of state parameter values from XML entries.
virtual void initThermo ()
virtual void setToEquilState (const doublereal *lambda_RT)
This method is used by the ChemEquil equilibrium solver.
virtual void initThermoXML (XML_Node &phaseNode, const std::string &id)
Import and initialize a ThermoPhase object using an XML tree.
Mechanical Properties
void setPressure (doublereal p)
Set the internally stored pressure (Pa) at constant temperature and composition.
virtual doublereal isothermalCompressibility () const
Returns the isothermal compressibility. Units: 1/Pa.
virtual void calcDensity ()
Calculate the density of the mixture using the partial molar volumes and mole fractions as input.
Additional Inherited Members
Protected Member Functions inherited from VPStandardStateTP
virtual void invalidateCache ()
Invalidate any cached values which are normally updated only when a change in state is detected.
virtual void _updateStandardStateThermo () const
Updates the standard state thermodynamic functions at the current T and P of the solution.
const vector_fp & Gibbs_RT_ref () const
Protected Member Functions inherited from ThermoPhase
virtual void getCsvReportData (std::vector< std::string > &names, std::vector< vector_fp > &data) const
Fills names and data with the column names and species thermo properties to be included in the output of the reportCSV method.
Protected Member Functions inherited from Phase
void assertCompressible (const std::string &setter) const
Ensure that phase is compressible.
void assignDensity (const double density_)
Set the internally stored constant density (kg/m^3) of the phase.
void setMolecularWeight (const int k, const double mw)
Set the molecular weight of a single species to a given value.
virtual void compositionChanged ()
Apply changes to the state which are needed after the composition changes.
Protected Attributes inherited from VPStandardStateTP
doublereal m_Pcurrent
Current value of the pressure - state variable.
double m_minTemp
The minimum temperature at which data for all species is valid.
double m_maxTemp
The maximum temperature at which data for all species is valid.
doublereal m_Tlast_ss
The last temperature at which the standard state thermodynamic properties were calculated at.
doublereal m_Plast_ss
The last pressure at which the Standard State thermodynamic properties were calculated at.
std::vector< std::unique_ptr< PDSS > > m_PDSS_storage
Storage for the PDSS objects for the species.
vector_fp m_h0_RT
Vector containing the species reference enthalpies at T = m_tlast and P = p_ref.
vector_fp m_cp0_R
Vector containing the species reference constant pressure heat capacities at T = m_tlast and P = p_ref.
vector_fp m_g0_RT
Vector containing the species reference Gibbs functions at T = m_tlast and P = p_ref.
vector_fp m_s0_R
Vector containing the species reference entropies at T = m_tlast and P = p_ref.
vector_fp m_V0
Vector containing the species reference molar volumes.
vector_fp m_hss_RT
Vector containing the species Standard State enthalpies at T = m_tlast and P = m_plast.
vector_fp m_cpss_R
Vector containing the species Standard State constant pressure heat capacities at T = m_tlast and P = m_plast.
vector_fp m_gss_RT
Vector containing the species Standard State Gibbs functions at T = m_tlast and P = m_plast.
vector_fp m_sss_R
Vector containing the species Standard State entropies at T = m_tlast and P = m_plast.
vector_fp m_Vss
Vector containing the species standard state volumes at T = m_tlast and P = m_plast.
Protected Attributes inherited from ThermoPhase
MultiSpeciesThermo m_spthermo
Pointer to the calculation manager for species reference-state thermodynamic properties.
AnyMap m_input
Data supplied via setParameters.
std::vector< const XML_Node * > m_speciesData
Vector of pointers to the species databases.
doublereal m_phi
Stored value of the electric potential for this phase. Units are Volts.
bool m_chargeNeutralityNecessary
Boolean indicating whether a charge neutrality condition is a necessity.
int m_ssConvention
Contains the standard state convention.
doublereal m_tlast
last value of the temperature processed by reference state
Protected Attributes inherited from Phase
ValueCache m_cache
Cached for saved calculations within each ThermoPhase.
size_t m_kk
Number of species in the phase.
size_t m_ndim
Dimensionality of the phase.
vector_fp m_speciesComp
Atomic composition of the species.
vector_fp m_speciesCharge
Vector of species charges. length m_kk.
std::map< std::string, shared_ptr< Species > > m_species
UndefElement::behavior m_undefinedElementBehavior
Flag determining behavior when adding species with an undefined element.
bool m_caseSensitiveSpecies
Flag determining whether case sensitive species names are enforced.
Detailed Description
An ideal solution or an ideal gas approximation of a phase.
Uses variable pressure standard state methods for calculating thermodynamic properties.
Deprecated:
"Gas" mode to be removed after Cantera 2.5. Use IdealGasPhase for ideal gas phases instead.
Definition at line 30 of file IdealSolnGasVPSS.h.
Constructor & Destructor Documentation
IdealSolnGasVPSS()
IdealSolnGasVPSS (const std::string & infile, std::string id = "")
Create an object from an input file.
Definition at line 30 of file IdealSolnGasVPSS.cpp.
References Cantera::get_XML_File(), Cantera::get_XML_NameID(), and Cantera::importPhase().
Member Function Documentation
type()
virtual std::string type () const inline virtual
String indicating the thermodynamic model implemented.
Usually corresponds to the name of the derived class, less any suffixes such as "Phase", TP", "VPSS", etc.
Reimplemented from ThermoPhase.
Definition at line 47 of file IdealSolnGasVPSS.h.
phaseOfMatter()
virtual std::string phaseOfMatter () const inline virtual
String indicating the mechanical phase of the matter in this Phase.
Options for the string are:
gas
undefined
If m_idealGas is true, returns gas. Otherwise, returns undefined.
Reimplemented from ThermoPhase.
Definition at line 59 of file IdealSolnGasVPSS.h.
References IdealSolnGasVPSS::m_idealGas.
setGasMode()
void setGasMode () inline
Set this phase to represent an ideal gas.
Definition at line 68 of file IdealSolnGasVPSS.h.
References IdealSolnGasVPSS::m_idealGas, and Cantera::warn_deprecated().
Referenced by IdealSolnGasVPSS::initThermo(), IdealSolnGasVPSS::initThermoXML(), and IdealSolnGasVPSS::setParametersFromXML().
setSolnMode()
void setSolnMode () inline
Set this phase to represent an ideal liquid or solid solution.
Definition at line 75 of file IdealSolnGasVPSS.h.
References IdealSolnGasVPSS::m_idealGas.
Referenced by IdealSolnGasVPSS::initThermo(), IdealSolnGasVPSS::initThermoXML(), and IdealSolnGasVPSS::setParametersFromXML().
setStandardConcentrationModel()
void setStandardConcentrationModel (const std::string & model)
Set the standard concentration model.
Definition at line 47 of file IdealSolnGasVPSS.cpp.
References Cantera::caseInsensitiveEquals(), IdealSolnGasVPSS::m_formGC, and IdealSolnGasVPSS::m_idealGas.
Referenced by IdealSolnGasVPSS::initThermo(), and IdealSolnGasVPSS::initThermoXML().
enthalpy_mole()
doublereal enthalpy_mole () const virtual
Molar enthalpy. Units: J/kmol.
Reimplemented from ThermoPhase.
Definition at line 70 of file IdealSolnGasVPSS.cpp.
References VPStandardStateTP::m_hss_RT, Phase::mean_X(), ThermoPhase::RT(), and VPStandardStateTP::updateStandardStateThermo().
entropy_mole()
doublereal entropy_mole () const virtual
Molar entropy. Units: J/kmol/K.
Reimplemented from ThermoPhase.
Definition at line 76 of file IdealSolnGasVPSS.cpp.
References Cantera::GasConstant, VPStandardStateTP::m_sss_R, Phase::mean_X(), Phase::sum_xlogx(), and VPStandardStateTP::updateStandardStateThermo().
cp_mole()
doublereal cp_mole () const virtual
Molar heat capacity at constant pressure. Units: J/kmol/K.
Reimplemented from ThermoPhase.
Definition at line 82 of file IdealSolnGasVPSS.cpp.
References Cantera::GasConstant, VPStandardStateTP::m_cpss_R, Phase::mean_X(), and VPStandardStateTP::updateStandardStateThermo().
Referenced by IdealSolnGasVPSS::cv_mole().
cv_mole()
doublereal cv_mole () const virtual
Molar heat capacity at constant volume. Units: J/kmol/K.
Reimplemented from ThermoPhase.
Definition at line 88 of file IdealSolnGasVPSS.cpp.
References IdealSolnGasVPSS::cp_mole(), and Cantera::GasConstant.
setPressure()
void setPressure (doublereal p) virtual
Set the internally stored pressure (Pa) at constant temperature and composition.
Currently this passes down to setState_TP(). It does not make sense to calculate the standard state without first setting T and P.
Parameters
p input Pressure (Pa)
Reimplemented from VPStandardStateTP.
Definition at line 93 of file IdealSolnGasVPSS.cpp.
References IdealSolnGasVPSS::calcDensity(), VPStandardStateTP::m_Pcurrent, and VPStandardStateTP::updateStandardStateThermo().
isothermalCompressibility()
doublereal isothermalCompressibility () const virtual
Returns the isothermal compressibility. Units: 1/Pa.
The isothermal compressibility is defined as
\[ \kappa_T = -\frac{1}{v}\left(\frac{\partial v}{\partial P}\right)_T \]
or
\[ \kappa_T = \frac{1}{\rho}\left(\frac{\partial \rho}{\partial P}\right)_T \]
Reimplemented from ThermoPhase.
Definition at line 116 of file IdealSolnGasVPSS.cpp.
References IdealSolnGasVPSS::m_idealGas, and VPStandardStateTP::m_Pcurrent.
calcDensity()
void calcDensity () protected virtual
Calculate the density of the mixture using the partial molar volumes and mole fractions as input.
The formula for this is
\[ \rho = \frac{\sum_k{X_k W_k}}{\sum_k{X_k V_k}} \]
where \(X_k\) are the mole fractions, \(W_k\) are the molecular weights, and \(V_k\) are the pure species molar volumes.
Note, the basis behind this formula is that in an ideal solution the partial molar volumes are equal to the species standard state molar volumes. The species molar volumes may be functions of temperature and pressure.
Reimplemented from VPStandardStateTP.
Definition at line 100 of file IdealSolnGasVPSS.cpp.
References Phase::assignDensity(), Cantera::dot(), VPStandardStateTP::getStandardVolumes(), IdealSolnGasVPSS::m_idealGas, VPStandardStateTP::m_Pcurrent, Phase::meanMolecularWeight(), Phase::moleFractdivMMW(), and ThermoPhase::RT().
Referenced by IdealSolnGasVPSS::setPressure().
standardConcentrationUnits()
Units standardConcentrationUnits () const virtual
Returns the units of the "standard concentration" for this phase.
These are the units of the values returned by the functions getActivityConcentrations() and standardConcentration(), which can vary between different ThermoPhase-derived classes, or change within a single class depending on input options. See the documentation for standardConcentration() for the derived class for specific details.
Reimplemented from ThermoPhase.
Definition at line 125 of file IdealSolnGasVPSS.cpp.
References IdealSolnGasVPSS::m_formGC, and IdealSolnGasVPSS::m_idealGas.
getActivityConcentrations()
void getActivityConcentrations (doublereal * c) const virtual
This method returns an array of generalized concentrations.
\(C^a_k\) are defined such that \(a_k = C^a_k / C^0_k, \) where \(C^0_k \) is a standard concentration defined below and \(a_k \) are activities used in the thermodynamic functions. These activity (or generalized) concentrations are used by kinetics manager classes to compute the forward and reverse rates of elementary reactions. Note that they may or may not have units of concentration — they might be partial pressures, mole fractions, or surface coverages, for example.
Parameters
c Output array of generalized concentrations. The units depend upon the implementation of the reaction rate expressions within the phase.
Reimplemented from ThermoPhase.
Definition at line 134 of file IdealSolnGasVPSS.cpp.
References Phase::getConcentrations(), VPStandardStateTP::getStandardVolumes(), IdealSolnGasVPSS::m_formGC, IdealSolnGasVPSS::m_idealGas, Phase::m_kk, and Phase::moleFraction().
standardConcentration()
doublereal standardConcentration (size_t k = 0) const virtual
Returns the standard concentration \(C^0_k \), which is used to normalize the generalized concentration.
This is defined as the concentration by which the generalized concentration is normalized to produce the activity. In many cases, this quantity will be the same for all species in a phase. Since the activity for an ideal gas mixture is simply the mole fraction, for an ideal gas \(C^0_k = P/\hat R T \).
Parameters
k Optional parameter indicating the species. The default is to assume this refers to species 0.
Returns
Returns the standard Concentration in units of m3 kmol-1.
Reimplemented from ThermoPhase.
Definition at line 160 of file IdealSolnGasVPSS.cpp.
References VPStandardStateTP::getStandardVolumes(), IdealSolnGasVPSS::m_formGC, IdealSolnGasVPSS::m_idealGas, VPStandardStateTP::pressure(), and ThermoPhase::RT().
getActivityCoefficients()
void getActivityCoefficients (doublereal * ac) const virtual
Get the array of non-dimensional activity coefficients at the current solution temperature, pressure, and solution concentration.
For ideal gases, the activity coefficients are all equal to one.
Parameters
ac Output vector of activity coefficients. Length: m_kk.
Reimplemented from ThermoPhase.
Definition at line 178 of file IdealSolnGasVPSS.cpp.
References Phase::m_kk.
getChemPotentials()
void getChemPotentials (doublereal * mu) const virtual
Get the species chemical potentials. Units: J/kmol.
This function returns a vector of chemical potentials of the species in solution at the current temperature, pressure and mole fraction of the solution.
Parameters
mu Output vector of species chemical potentials. Length: m_kk. Units: J/kmol
Reimplemented from ThermoPhase.
Definition at line 187 of file IdealSolnGasVPSS.cpp.
References VPStandardStateTP::getStandardChemPotentials(), Phase::m_kk, Phase::moleFraction(), ThermoPhase::RT(), and Cantera::SmallNumber.
getPartialMolarEnthalpies()
void getPartialMolarEnthalpies (doublereal * hbar) const virtual
Returns an array of partial molar enthalpies for the species in the mixture.
Units (J/kmol)
Parameters
hbar Output vector of species partial molar enthalpies. Length: m_kk. units are J/kmol.
Reimplemented from ThermoPhase.
Definition at line 196 of file IdealSolnGasVPSS.cpp.
References VPStandardStateTP::getEnthalpy_RT(), Phase::m_kk, ThermoPhase::RT(), and Cantera::scale().
getPartialMolarEntropies()
void getPartialMolarEntropies (doublereal * sbar) const virtual
Returns an array of partial molar entropies of the species in the solution.
Units: J/kmol/K.
Parameters
sbar Output vector of species partial molar entropies. Length = m_kk. units are J/kmol/K.
Reimplemented from ThermoPhase.
Definition at line 202 of file IdealSolnGasVPSS.cpp.
References Cantera::GasConstant, VPStandardStateTP::getEntropy_R(), Phase::m_kk, Phase::moleFraction(), Cantera::scale(), and Cantera::SmallNumber.
getPartialMolarIntEnergies()
void getPartialMolarIntEnergies (doublereal * ubar) const virtual
Return an array of partial molar internal energies for the species in the mixture.
Units: J/kmol.
Parameters
ubar Output vector of species partial molar internal energies. Length = m_kk. units are J/kmol.
Reimplemented from ThermoPhase.
Definition at line 212 of file IdealSolnGasVPSS.cpp.
References VPStandardStateTP::getIntEnergy_RT(), Phase::m_kk, ThermoPhase::RT(), and Cantera::scale().
getPartialMolarCp()
void getPartialMolarCp (doublereal * cpbar) const virtual
Return an array of partial molar heat capacities for the species in the mixture.
Units: J/kmol/K
Parameters
cpbar Output vector of species partial molar heat capacities at constant pressure. Length = m_kk. units are J/kmol/K.
Reimplemented from ThermoPhase.
Definition at line 218 of file IdealSolnGasVPSS.cpp.
References Cantera::GasConstant, VPStandardStateTP::getCp_R(), Phase::m_kk, and Cantera::scale().
getPartialMolarVolumes()
void getPartialMolarVolumes (doublereal * vbar) const virtual
Return an array of partial molar volumes for the species in the mixture.
Units: m^3/kmol.
Parameters
vbar Output vector of species partial molar volumes. Length = m_kk. units are m^3/kmol.
Reimplemented from ThermoPhase.
Definition at line 224 of file IdealSolnGasVPSS.cpp.
References VPStandardStateTP::getStandardVolumes().
addSpecies()
bool addSpecies (shared_ptr< Species > spec) virtual
The following methods are used in the process of constructing the phase and setting its parameters from a specification in an input file. They are not normally used in application programs. To see how they are used, see importPhase().
Reimplemented from VPStandardStateTP.
Definition at line 257 of file IdealSolnGasVPSS.cpp.
References VPStandardStateTP::addSpecies(), and IdealSolnGasVPSS::m_pp.
setParametersFromXML()
void setParametersFromXML (const XML_Node & eosdata) virtual
Set equation of state parameter values from XML entries.
This method is called by function importPhase() when processing a phase definition in an input file. It should be overloaded in subclasses to set any parameters that are specific to that particular phase model. Note, this method is called before the phase is initialized with elements and/or species.
Parameters
eosdata An XML_Node object corresponding to the "thermo" entry for this phase in the input file.
Deprecated:
The XML input format is deprecated and will be removed in Cantera 3.0.
Reimplemented from ThermoPhase.
Definition at line 318 of file IdealSolnGasVPSS.cpp.
References IdealSolnGasVPSS::setGasMode(), ThermoPhase::setParametersFromXML(), and IdealSolnGasVPSS::setSolnMode().
initThermo()
void initThermo () virtual
The following methods are used in the process of constructing the phase and setting its parameters from a specification in an input file. They are not normally used in application programs. To see how they are used, see importPhase().
Reimplemented from VPStandardStateTP.
Definition at line 266 of file IdealSolnGasVPSS.cpp.
References AnyMap::hasKey(), VPStandardStateTP::initThermo(), IdealSolnGasVPSS::m_idealGas, ThermoPhase::m_input, IdealSolnGasVPSS::setGasMode(), IdealSolnGasVPSS::setSolnMode(), and IdealSolnGasVPSS::setStandardConcentrationModel().
setToEquilState()
void setToEquilState (const doublereal * mu_RT) virtual
This method is used by the ChemEquil equilibrium solver.
It sets the state such that the chemical potentials satisfy
\[ \frac{\mu_k}{\hat R T} = \sum_m A_{k,m} \left(\frac{\lambda_m} {\hat R T}\right) \]
where \(\lambda_m \) is the element potential of element m. The temperature is unchanged. Any phase (ideal or not) that implements this method can be equilibrated by ChemEquil.
Parameters
mu_RT Input vector of dimensionless chemical potentials The length is equal to nSpecies().
Reimplemented from ThermoPhase.
Definition at line 229 of file IdealSolnGasVPSS.cpp.
References VPStandardStateTP::m_g0_RT, Phase::m_kk, IdealSolnGasVPSS::m_pp, ThermoPhase::refPressure(), ThermoPhase::setState_PX(), and VPStandardStateTP::updateStandardStateThermo().
initThermoXML()
void initThermoXML (XML_Node & phaseNode, const std::string & id) virtual
Import and initialize a ThermoPhase object using an XML tree.
Here we read extra information about the XML description of a phase. Regular information about elements and species and their reference state thermodynamic information have already been read at this point. For example, we do not need to call this function for ideal gas equations of state. This function is called from importPhase() after the elements and the species are initialized with default ideal solution level data.
The default implementation in ThermoPhase calls the virtual function initThermo() and then sets the "state" of the phase by looking for an XML element named "state", and then interpreting its contents by calling the virtual function setStateFromXML().
Parameters
phaseNode This object must be the phase node of a complete XML tree description of the phase, including all of the species data. In other words while "phase" must point to an XML phase object, it must have sibling nodes "speciesData" that describe the species in the phase.
id ID of the phase. If nonnull, a check is done to see if phaseNode is pointing to the phase with the correct id.
Deprecated:
The XML input format is deprecated and will be removed in Cantera 3.0.
Reimplemented from ThermoPhase.
Definition at line 287 of file IdealSolnGasVPSS.cpp.
References XML_Node::attrib(), XML_Node::child(), XML_Node::hasChild(), ThermoPhase::initThermoXML(), IdealSolnGasVPSS::m_idealGas, IdealSolnGasVPSS::setGasMode(), IdealSolnGasVPSS::setSolnMode(), and IdealSolnGasVPSS::setStandardConcentrationModel().
Member Data Documentation
m_idealGas
int m_idealGas protected
boolean indicating what ideal solution this is
1 = ideal gas
0 = ideal soln
Definition at line 186 of file IdealSolnGasVPSS.h.
Referenced by IdealSolnGasVPSS::calcDensity(), IdealSolnGasVPSS::getActivityConcentrations(), IdealSolnGasVPSS::initThermo(), IdealSolnGasVPSS::initThermoXML(), IdealSolnGasVPSS::isothermalCompressibility(), IdealSolnGasVPSS::phaseOfMatter(), IdealSolnGasVPSS::setGasMode(), IdealSolnGasVPSS::setSolnMode(), IdealSolnGasVPSS::setStandardConcentrationModel(), IdealSolnGasVPSS::standardConcentration(), and IdealSolnGasVPSS::standardConcentrationUnits().
m_formGC
int m_formGC protected
form of the generalized concentrations
0 unity (default)
1 1/V_k
2 1/V_0
Definition at line 194 of file IdealSolnGasVPSS.h.
Referenced by IdealSolnGasVPSS::getActivityConcentrations(), IdealSolnGasVPSS::setStandardConcentrationModel(), IdealSolnGasVPSS::standardConcentration(), and IdealSolnGasVPSS::standardConcentrationUnits().
m_pp
vector_fp m_pp protected
Temporary storage - length = m_kk.
Definition at line 197 of file IdealSolnGasVPSS.h.
Referenced by IdealSolnGasVPSS::addSpecies(), and IdealSolnGasVPSS::setToEquilState().
The documentation for this class was generated from the following files:
IdealSolnGasVPSS.h
IdealSolnGasVPSS.cpp