Cantera: SpeciesThermoInterpType Class Reference
SpeciesThermoInterpType Class Reference
Models of Phases of Matter » Thermodynamic Properties » Species Reference-State Thermodynamic Properties
Abstract Base class for the thermodynamic manager for an individual species' reference state.
#include <SpeciesThermoInterpType.h>
Public Member Functions
SpeciesThermoInterpType (double tlow, double thigh, double pref)
SpeciesThermoInterpType (const SpeciesThermoInterpType &b)=delete
SpeciesThermoInterpType & operator= (const SpeciesThermoInterpType &b)=delete
virtual doublereal minTemp () const
Returns the minimum temperature that the thermo parameterization is valid.
virtual void setMinTemp (double Tmin)
Set the minimum temperature at which the thermo parameterization is valid.
virtual doublereal maxTemp () const
Returns the maximum temperature that the thermo parameterization is valid.
virtual void setMaxTemp (double Tmax)
Set the maximum temperature at which the thermo parameterization is valid.
virtual doublereal refPressure () const
Returns the reference pressure (Pa)
virtual void setRefPressure (double Pref)
Set the reference pressure [Pa].
virtual void validate (const std::string &name)
Check for problems with the parameterization, and generate warnings or throw and exception if any are found.
virtual int reportType () const
Returns an integer representing the type of parameterization.
virtual size_t temperaturePolySize () const
Number of terms in the temperature polynomial for this parameterization.
virtual void updateTemperaturePoly (double T, double *T_poly) const
Given the temperature T, compute the terms of the temperature polynomial T_poly.
virtual void updateProperties (const doublereal *tt, doublereal *cp_R, doublereal *h_RT, doublereal *s_R) const
Update the properties for this species, given a temperature polynomial.
virtual void updatePropertiesTemp (const doublereal temp, doublereal *cp_R, doublereal *h_RT, doublereal *s_R) const
Compute the reference-state property of one species.
virtual size_t nCoeffs () const
This utility function returns the number of coefficients for a given type of species parameterization.
virtual void reportParameters (size_t &index, int &type, doublereal &minTemp, doublereal &maxTemp, doublereal &refPressure, doublereal *const coeffs) const
This utility function returns the type of parameterization and all of the parameters for the species.
virtual doublereal reportHf298 (doublereal *const h298=0) const
Report the 298 K Heat of Formation of the standard state of one species (J kmol-1)
virtual void modifyOneHf298 (const size_t k, const doublereal Hf298New)
Modify the value of the 298 K Heat of Formation of one species in the phase (J kmol-1)
virtual void resetHf298 ()
Restore the original heat of formation for this species.
Protected Attributes
doublereal m_lowT
lowest valid temperature
doublereal m_highT
Highest valid temperature.
doublereal m_Pref
Reference state pressure.
Detailed Description
Abstract Base class for the thermodynamic manager for an individual species' reference state.
One key feature is that the update routines use the same form as the update routines in the MultiSpeciesThermo class. They update values of cp_R, s_R, and H_R.
Definition at line 113 of file SpeciesThermoInterpType.h.
Member Function Documentation
minTemp()
virtual doublereal minTemp () const inline virtual
Returns the minimum temperature that the thermo parameterization is valid.
Definition at line 128 of file SpeciesThermoInterpType.h.
References SpeciesThermoInterpType::m_lowT.
Referenced by MultiSpeciesThermo::minTemp().
setMinTemp()
virtual void setMinTemp (double Tmin) inline virtual
Set the minimum temperature at which the thermo parameterization is valid.
Reimplemented in ShomatePoly2, and NasaPoly2.
Definition at line 133 of file SpeciesThermoInterpType.h.
References SpeciesThermoInterpType::m_lowT.
Referenced by NasaPoly2::setMinTemp(), ShomatePoly2::setMinTemp(), Nasa9PolyMultiTempRegion::setParameters(), and ShomatePoly2::setParameters().
maxTemp()
virtual doublereal maxTemp () const inline virtual
Returns the maximum temperature that the thermo parameterization is valid.
Definition at line 139 of file SpeciesThermoInterpType.h.
References SpeciesThermoInterpType::m_highT.
Referenced by MultiSpeciesThermo::maxTemp(), Nasa9PolyMultiTempRegion::Nasa9PolyMultiTempRegion(), and Nasa9PolyMultiTempRegion::setParameters().
setMaxTemp()
virtual void setMaxTemp (double Tmax) inline virtual
Set the maximum temperature at which the thermo parameterization is valid.
Reimplemented in ShomatePoly2, and NasaPoly2.
Definition at line 144 of file SpeciesThermoInterpType.h.
References SpeciesThermoInterpType::m_highT.
Referenced by NasaPoly2::setMaxTemp(), ShomatePoly2::setMaxTemp(), and ShomatePoly2::setParameters().
refPressure()
virtual doublereal refPressure () const inline virtual
Returns the reference pressure (Pa)
Definition at line 149 of file SpeciesThermoInterpType.h.
References SpeciesThermoInterpType::m_Pref.
Referenced by Nasa9PolyMultiTempRegion::Nasa9PolyMultiTempRegion(), MultiSpeciesThermo::refPressure(), and Nasa9PolyMultiTempRegion::setParameters().
setRefPressure()
virtual void setRefPressure (double Pref) inline virtual
Set the reference pressure [Pa].
Reimplemented in ShomatePoly2, and NasaPoly2.
Definition at line 154 of file SpeciesThermoInterpType.h.
References SpeciesThermoInterpType::m_Pref.
Referenced by Nasa9PolyMultiTempRegion::setParameters(), NasaPoly2::setRefPressure(), and ShomatePoly2::setRefPressure().
validate()
virtual void validate (const std::string & name) inline virtual
Check for problems with the parameterization, and generate warnings or throw and exception if any are found.
Reimplemented in NasaPoly2.
Definition at line 160 of file SpeciesThermoInterpType.h.
reportType()
virtual int reportType () const inline virtual
Returns an integer representing the type of parameterization.
Reimplemented in ShomatePoly2, ShomatePoly, NasaPoly2, NasaPoly1, Nasa9PolyMultiTempRegion, Nasa9Poly1, Mu0Poly, and ConstCpPoly.
Definition at line 163 of file SpeciesThermoInterpType.h.
Referenced by MultiSpeciesThermo::reportType().
temperaturePolySize()
virtual size_t temperaturePolySize () const inline virtual
Number of terms in the temperature polynomial for this parameterization.
Reimplemented in ShomatePoly2, ShomatePoly, NasaPoly2, NasaPoly1, Nasa9PolyMultiTempRegion, and Nasa9Poly1.
Definition at line 166 of file SpeciesThermoInterpType.h.
updateTemperaturePoly()
virtual void updateTemperaturePoly (double T, double * T_poly) const inline virtual
Given the temperature T, compute the terms of the temperature polynomial T_poly.
Reimplemented in ShomatePoly2, ShomatePoly, NasaPoly2, NasaPoly1, Nasa9PolyMultiTempRegion, and Nasa9Poly1.
Definition at line 170 of file SpeciesThermoInterpType.h.
updateProperties()
void updateProperties (const doublereal * tt, doublereal * cp_R, doublereal * h_RT, doublereal * s_R) const virtual
Update the properties for this species, given a temperature polynomial.
This method is called with a pointer to an array containing the functions of temperature needed by this parameterization, and three pointers to arrays where the computed property values should be written. This method updates only one value in each array.
The form and length of the Temperature Polynomial may vary depending on the parameterization.
Parameters
tt vector of evaluated temperature functions
cp_R Vector of Dimensionless heat capacities. (length m_kk).
h_RT Vector of Dimensionless enthalpies. (length m_kk).
s_R Vector of Dimensionless entropies. (length m_kk).
Reimplemented in ShomatePoly2, ShomatePoly, NasaPoly2, NasaPoly1, Nasa9PolyMultiTempRegion, Nasa9Poly1, Mu0Poly, and ConstCpPoly.
Definition at line 30 of file SpeciesThermoInterpType.cpp.
updatePropertiesTemp()
void updatePropertiesTemp (const doublereal temp, doublereal * cp_R, doublereal * h_RT, doublereal * s_R) const virtual
Compute the reference-state property of one species.
Given temperature T in K, this method updates the values of the non- dimensional heat capacity at constant pressure, enthalpy, and entropy, at the reference pressure, of the species.
Parameters
temp Temperature (Kelvin)
cp_R Vector of Dimensionless heat capacities. (length m_kk).
h_RT Vector of Dimensionless enthalpies. (length m_kk).
s_R Vector of Dimensionless entropies. (length m_kk).
Reimplemented in ShomatePoly2, ShomatePoly, NasaPoly2, NasaPoly1, Nasa9PolyMultiTempRegion, Nasa9Poly1, Mu0Poly, and ConstCpPoly.
Definition at line 37 of file SpeciesThermoInterpType.cpp.
Referenced by MultiSpeciesThermo::update_single().
nCoeffs()
size_t nCoeffs () const virtual
This utility function returns the number of coefficients for a given type of species parameterization.
Reimplemented in ShomatePoly2, NasaPoly2, Nasa9PolyMultiTempRegion, Mu0Poly, and ConstCpPoly.
Definition at line 43 of file SpeciesThermoInterpType.cpp.
reportParameters()
void reportParameters (size_t & index, int & type, doublereal & minTemp, doublereal & maxTemp, doublereal & refPressure, doublereal *const coeffs) const virtual
This utility function returns the type of parameterization and all of the parameters for the species.
All parameters are output variables
Parameters
index Species index
type Integer type of the standard type
minTemp output - Minimum temperature
maxTemp output - Maximum temperature
refPressure output - reference pressure (Pa).
coeffs Vector of coefficients used to set the parameters for the standard state.
Reimplemented in ShomatePoly2, ShomatePoly, NasaPoly2, NasaPoly1, Nasa9PolyMultiTempRegion, Nasa9Poly1, Mu0Poly, and ConstCpPoly.
Definition at line 48 of file SpeciesThermoInterpType.cpp.
reportHf298()
doublereal reportHf298 (doublereal *const h298 = 0) const virtual
Report the 298 K Heat of Formation of the standard state of one species (J kmol-1)
The 298K Heat of Formation is defined as the enthalpy change to create the standard state of the species from its constituent elements in their standard states at 298 K and 1 bar.
Parameters
h298 If this is nonnull, the current value of the Heat of Formation at 298K and 1 bar for species m_speciesIndex is returned in h298[m_speciesIndex].
Returns
the current value of the Heat of Formation at 298K and 1 bar for species m_speciesIndex.
Reimplemented in ShomatePoly2, ShomatePoly, NasaPoly2, NasaPoly1, and ConstCpPoly.
Definition at line 55 of file SpeciesThermoInterpType.cpp.
Referenced by MultiSpeciesThermo::reportOneHf298().
modifyOneHf298()
void modifyOneHf298 (const size_t k, const doublereal Hf298New) virtual
Modify the value of the 298 K Heat of Formation of one species in the phase (J kmol-1)
The 298K heat of formation is defined as the enthalpy change to create the standard state of the species from its constituent elements in their standard states at 298 K and 1 bar.
Parameters
k Species k
Hf298New Specify the new value of the Heat of Formation at 298K and 1 bar
Reimplemented in ShomatePoly2, ShomatePoly, NasaPoly2, NasaPoly1, and ConstCpPoly.
Definition at line 60 of file SpeciesThermoInterpType.cpp.
Referenced by MultiSpeciesThermo::modifyOneHf298().
resetHf298()
virtual void resetHf298 () inline virtual
Restore the original heat of formation for this species.
Resets changes made by modifyOneHf298().
Reimplemented in ShomatePoly2, ShomatePoly, NasaPoly2, NasaPoly1, and ConstCpPoly.
Definition at line 263 of file SpeciesThermoInterpType.h.
Referenced by MultiSpeciesThermo::resetHf298().
Member Data Documentation
m_lowT
doublereal m_lowT protected
lowest valid temperature
Definition at line 269 of file SpeciesThermoInterpType.h.
Referenced by SpeciesThermoInterpType::minTemp(), Nasa9PolyMultiTempRegion::Nasa9PolyMultiTempRegion(), and SpeciesThermoInterpType::setMinTemp().
m_highT
doublereal m_highT protected
Highest valid temperature.
Definition at line 271 of file SpeciesThermoInterpType.h.
Referenced by SpeciesThermoInterpType::maxTemp(), Nasa9PolyMultiTempRegion::Nasa9PolyMultiTempRegion(), and SpeciesThermoInterpType::setMaxTemp().
m_Pref
doublereal m_Pref protected
Reference state pressure.
Definition at line 273 of file SpeciesThermoInterpType.h.
Referenced by Nasa9PolyMultiTempRegion::Nasa9PolyMultiTempRegion(), SpeciesThermoInterpType::refPressure(), and SpeciesThermoInterpType::setRefPressure().
The documentation for this class was generated from the following files:
SpeciesThermoInterpType.h
SpeciesThermoInterpType.cpp