Cantera: Solution Class Reference
Solution Class Reference
A container class holding managers for all pieces defining a phase.
#include <Solution.h>
Inherits enable_shared_from_this< Solution >.
Public Member Functions
Solution (const Solution &)=delete
Solution & operator= (const Solution &)=delete
std::string name () const
Return the name of this Solution object.
void setName (const std::string &name)
Set the name of this Solution object.
void setThermo (shared_ptr< ThermoPhase > thermo)
Set the ThermoPhase object.
void setKinetics (shared_ptr< Kinetics > kinetics)
Set the Kinetics object.
void setTransport (shared_ptr< Transport > transport)
Set the Transport object.
shared_ptr< ThermoPhase > thermo ()
Accessor for the ThermoPhase pointer.
shared_ptr< Kinetics > kinetics ()
Accessor for the Kinetics pointer.
shared_ptr< Transport > transport ()
Accessor for the Transport pointer.
Static Public Member Functions
static shared_ptr< Solution > create ()
Create an empty Solution object.
Protected Attributes
shared_ptr< ThermoPhase > m_thermo
ThermoPhase manager.
shared_ptr< Kinetics > m_kinetics
Kinetics manager.
shared_ptr< Transport > m_transport
Transport manager.
Detailed Description
A container class holding managers for all pieces defining a phase.
Definition at line 19 of file Solution.h.
Member Function Documentation
create()
static shared_ptr<Solution> create () inline static
Create an empty Solution object.
Definition at line 30 of file Solution.h.
Referenced by Cantera::newSolution().
name()
std::string name () const
Return the name of this Solution object.
Definition at line 22 of file Solution.cpp.
References Solution::m_thermo.
Referenced by Solution::setName().
setName()
void setName (const std::string & name)
Set the name of this Solution object.
Definition at line 31 of file Solution.cpp.
References Solution::m_thermo, and Solution::name().
setThermo()
void setThermo (shared_ptr< ThermoPhase > thermo)
Set the ThermoPhase object.
Definition at line 40 of file Solution.cpp.
References Solution::m_thermo, and Solution::thermo().
setKinetics()
void setKinetics (shared_ptr< Kinetics > kinetics)
Set the Kinetics object.
Definition at line 47 of file Solution.cpp.
References Solution::kinetics(), and Solution::m_kinetics.
setTransport()
void setTransport (shared_ptr< Transport > transport)
Set the Transport object.
Definition at line 54 of file Solution.cpp.
References Solution::m_transport, and Solution::transport().
thermo()
shared_ptr<ThermoPhase> thermo () inline
Accessor for the ThermoPhase pointer.
Definition at line 50 of file Solution.h.
References Solution::m_thermo.
Referenced by Solution::setThermo().
kinetics()
shared_ptr<Kinetics> kinetics () inline
Accessor for the Kinetics pointer.
Definition at line 55 of file Solution.h.
References Solution::m_kinetics.
Referenced by Solution::setKinetics().
transport()
shared_ptr<Transport> transport () inline
Accessor for the Transport pointer.
Definition at line 60 of file Solution.h.
References Solution::m_transport.
Referenced by Solution::setTransport().
Member Data Documentation
m_thermo
shared_ptr<ThermoPhase> m_thermo protected
ThermoPhase manager.
Definition at line 65 of file Solution.h.
Referenced by Solution::name(), Solution::setName(), Solution::setThermo(), and Solution::thermo().
m_kinetics
shared_ptr<Kinetics> m_kinetics protected
Kinetics manager.
Definition at line 66 of file Solution.h.
Referenced by Solution::kinetics(), and Solution::setKinetics().
m_transport
shared_ptr<Transport> m_transport protected
Transport manager.
Definition at line 67 of file Solution.h.
Referenced by Solution::setTransport(), and Solution::transport().
The documentation for this class was generated from the following files:
Solution.h
Solution.cpp