Cantera: ThermoPhase Class Reference
ThermoPhase Class Reference
Models of Phases of Matter » Thermodynamic Properties | Models of Phases of Matter
Base class for a phase with thermodynamic properties.
#include <ThermoPhase.h>
Public Member Functions
ThermoPhase ()
Constructor.
Information Methods
virtual std::string type () const
String indicating the thermodynamic model implemented.
virtual std::string phaseOfMatter () const
String indicating the mechanical phase of the matter in this Phase.
virtual doublereal refPressure () const
Returns the reference pressure in Pa.
virtual doublereal minTemp (size_t k=npos) const
Minimum temperature for which the thermodynamic data for the species or phase are valid.
doublereal Hf298SS (const size_t k) const
Report the 298 K Heat of Formation of the standard state of one species (J kmol-1)
virtual void modifyOneHf298SS (const size_t k, const doublereal Hf298New)
Modify the value of the 298 K Heat of Formation of one species in the phase (J kmol-1)
virtual void resetHf298 (const size_t k=npos)
Restore the original heat of formation of one or more species.
virtual doublereal maxTemp (size_t k=npos) const
Maximum temperature for which the thermodynamic data for the species are valid.
bool chargeNeutralityNecessary () const
Returns the chargeNeutralityNecessity boolean.
Molar Thermodynamic Properties of the Solution
virtual doublereal enthalpy_mole () const
Molar enthalpy. Units: J/kmol.
virtual doublereal intEnergy_mole () const
Molar internal energy. Units: J/kmol.
virtual doublereal entropy_mole () const
Molar entropy. Units: J/kmol/K.
virtual doublereal gibbs_mole () const
Molar Gibbs function. Units: J/kmol.
virtual doublereal cp_mole () const
Molar heat capacity at constant pressure. Units: J/kmol/K.
virtual doublereal cv_mole () const
Molar heat capacity at constant volume. Units: J/kmol/K.
Mechanical Properties
virtual doublereal isothermalCompressibility () const
Returns the isothermal compressibility. Units: 1/Pa.
virtual doublereal thermalExpansionCoeff () const
Return the volumetric thermal expansion coefficient. Units: 1/K.
Electric Potential
The phase may be at some non-zero electrical potential.
These methods set or get the value of the electric potential.
void setElectricPotential (doublereal v)
Set the electric potential of this phase (V).
doublereal electricPotential () const
Returns the electric potential of this phase (V).
Activities, Standard States, and Activity Concentrations
The activity \(a_k\) of a species in solution is related to the chemical potential by
\[ \mu_k = \mu_k^0(T,P) + \hat R T \log a_k. \]
The quantity \(\mu_k^0(T,P)\) is the standard chemical potential at unit activity, which depends on temperature and pressure, but not on composition. The activity is dimensionless.
virtual int activityConvention () const
This method returns the convention used in specification of the activities, of which there are currently two, molar- and molality-based conventions.
virtual int standardStateConvention () const
This method returns the convention used in specification of the standard state, of which there are currently two, temperature based, and variable pressure based.
virtual Units standardConcentrationUnits () const
Returns the units of the "standard concentration" for this phase.
virtual void getActivityConcentrations (doublereal *c) const
This method returns an array of generalized concentrations.
virtual doublereal standardConcentration (size_t k=0) const
Return the standard concentration for the kth species.
virtual doublereal logStandardConc (size_t k=0) const
Natural logarithm of the standard concentration of the kth species.
virtual void getActivities (doublereal *a) const
Get the array of non-dimensional activities at the current solution temperature, pressure, and solution concentration.
virtual void getActivityCoefficients (doublereal *ac) const
Get the array of non-dimensional molar-based activity coefficients at the current solution temperature, pressure, and solution concentration.
virtual void getLnActivityCoefficients (doublereal *lnac) const
Get the array of non-dimensional molar-based ln activity coefficients at the current solution temperature, pressure, and solution concentration.
Partial Molar Properties of the Solution
virtual void getChemPotentials_RT (doublereal *mu) const
Get the array of non-dimensional species chemical potentials These are partial molar Gibbs free energies.
virtual void getChemPotentials (doublereal *mu) const
Get the species chemical potentials. Units: J/kmol.
void getElectrochemPotentials (doublereal *mu) const
Get the species electrochemical potentials.
virtual void getPartialMolarEnthalpies (doublereal *hbar) const
Returns an array of partial molar enthalpies for the species in the mixture.
virtual void getPartialMolarEntropies (doublereal *sbar) const
Returns an array of partial molar entropies of the species in the solution.
virtual void getPartialMolarIntEnergies (doublereal *ubar) const
Return an array of partial molar internal energies for the species in the mixture.
virtual void getPartialMolarCp (doublereal *cpbar) const
Return an array of partial molar heat capacities for the species in the mixture.
virtual void getPartialMolarVolumes (doublereal *vbar) const
Return an array of partial molar volumes for the species in the mixture.
Properties of the Standard State of the Species in the Solution
virtual void getStandardChemPotentials (doublereal *mu) const
Get the array of chemical potentials at unit activity for the species at their standard states at the current T and P of the solution.
virtual void getEnthalpy_RT (doublereal *hrt) const
Get the nondimensional Enthalpy functions for the species at their standard states at the current T and P of the solution.
virtual void getEntropy_R (doublereal *sr) const
Get the array of nondimensional Entropy functions for the standard state species at the current T and P of the solution.
virtual void getGibbs_RT (doublereal *grt) const
Get the nondimensional Gibbs functions for the species in their standard states at the current T and P of the solution.
virtual void getPureGibbs (doublereal *gpure) const
Get the Gibbs functions for the standard state of the species at the current T and P of the solution.
virtual void getIntEnergy_RT (doublereal *urt) const
Returns the vector of nondimensional Internal Energies of the standard state species at the current T and P of the solution.
virtual void getCp_R (doublereal *cpr) const
Get the nondimensional Heat Capacities at constant pressure for the species standard states at the current T and P of the solution.
virtual void getStandardVolumes (doublereal *vol) const
Get the molar volumes of the species standard states at the current T and P of the solution.
Thermodynamic Values for the Species Reference States
virtual void getEnthalpy_RT_ref (doublereal *hrt) const
Returns the vector of nondimensional enthalpies of the reference state at the current temperature of the solution and the reference pressure for the species.
virtual void getGibbs_RT_ref (doublereal *grt) const
Returns the vector of nondimensional Gibbs Free Energies of the reference state at the current temperature of the solution and the reference pressure for the species.
virtual void getGibbs_ref (doublereal *g) const
Returns the vector of the Gibbs function of the reference state at the current temperature of the solution and the reference pressure for the species.
virtual void getEntropy_R_ref (doublereal *er) const
Returns the vector of nondimensional entropies of the reference state at the current temperature of the solution and the reference pressure for each species.
virtual void getIntEnergy_RT_ref (doublereal *urt) const
Returns the vector of nondimensional internal Energies of the reference state at the current temperature of the solution and the reference pressure for each species.
virtual void getCp_R_ref (doublereal *cprt) const
Returns the vector of nondimensional constant pressure heat capacities of the reference state at the current temperature of the solution and reference pressure for each species.
virtual void getStandardVolumes_ref (doublereal *vol) const
Get the molar volumes of the species reference states at the current T and P_ref of the solution.
Specific Properties
doublereal enthalpy_mass () const
Specific enthalpy. Units: J/kg.
doublereal intEnergy_mass () const
Specific internal energy. Units: J/kg.
doublereal entropy_mass () const
Specific entropy. Units: J/kg/K.
doublereal gibbs_mass () const
Specific Gibbs function. Units: J/kg.
doublereal cp_mass () const
Specific heat at constant pressure. Units: J/kg/K.
doublereal cv_mass () const
Specific heat at constant volume. Units: J/kg/K.
doublereal RT () const
Return the Gas Constant multiplied by the current temperature.
Setting the State
These methods set all or part of the thermodynamic state.
virtual void setState_TPX (doublereal t, doublereal p, const doublereal *x)
Set the temperature (K), pressure (Pa), and mole fractions.
virtual void setState_TPX (doublereal t, doublereal p, const compositionMap &x)
Set the temperature (K), pressure (Pa), and mole fractions.
virtual void setState_TPX (doublereal t, doublereal p, const std::string &x)
Set the temperature (K), pressure (Pa), and mole fractions.
virtual void setState_TPY (doublereal t, doublereal p, const doublereal *y)
Set the internally stored temperature (K), pressure (Pa), and mass fractions of the phase.
virtual void setState_TPY (doublereal t, doublereal p, const compositionMap &y)
Set the internally stored temperature (K), pressure (Pa), and mass fractions of the phase.
virtual void setState_TPY (doublereal t, doublereal p, const std::string &y)
Set the internally stored temperature (K), pressure (Pa), and mass fractions of the phase.
virtual void setState_TP (doublereal t, doublereal p)
Set the temperature (K) and pressure (Pa)
virtual void setState_PX (doublereal p, doublereal *x)
Set the pressure (Pa) and mole fractions.
virtual void setState_PY (doublereal p, doublereal *y)
Set the internally stored pressure (Pa) and mass fractions.
virtual void setState_HP (double h, double p, double tol=1e-9)
Set the internally stored specific enthalpy (J/kg) and pressure (Pa) of the phase.
virtual void setState_UV (double u, double v, double tol=1e-9)
Set the specific internal energy (J/kg) and specific volume (m^3/kg).
virtual void setState_SP (double s, double p, double tol=1e-9)
Set the specific entropy (J/kg/K) and pressure (Pa).
virtual void setState_SV (double s, double v, double tol=1e-9)
Set the specific entropy (J/kg/K) and specific volume (m^3/kg).
virtual void setState_ST (double s, double t, double tol=1e-9)
Set the specific entropy (J/kg/K) and temperature (K).
virtual void setState_TV (double t, double v, double tol=1e-9)
Set the temperature (K) and specific volume (m^3/kg).
virtual void setState_PV (double p, double v, double tol=1e-9)
Set the pressure (Pa) and specific volume (m^3/kg).
virtual void setState_UP (double u, double p, double tol=1e-9)
Set the specific internal energy (J/kg) and pressure (Pa).
virtual void setState_VH (double v, double h, double tol=1e-9)
Set the specific volume (m^3/kg) and the specific enthalpy (J/kg)
virtual void setState_TH (double t, double h, double tol=1e-9)
Set the temperature (K) and the specific enthalpy (J/kg)
virtual void setState_SH (double s, double h, double tol=1e-9)
Set the specific entropy (J/kg/K) and the specific enthalpy (J/kg)
virtual void setState_RP (doublereal rho, doublereal p)
Set the density (kg/m**3) and pressure (Pa) at constant composition.
virtual void setState_RPX (doublereal rho, doublereal p, const doublereal *x)
Set the density (kg/m**3), pressure (Pa) and mole fractions.
virtual void setState_RPX (doublereal rho, doublereal p, const compositionMap &x)
Set the density (kg/m**3), pressure (Pa) and mole fractions.
virtual void setState_RPX (doublereal rho, doublereal p, const std::string &x)
Set the density (kg/m**3), pressure (Pa) and mole fractions.
virtual void setState_RPY (doublereal rho, doublereal p, const doublereal *y)
Set the density (kg/m**3), pressure (Pa) and mass fractions.
virtual void setState_RPY (doublereal rho, doublereal p, const compositionMap &y)
Set the density (kg/m**3), pressure (Pa) and mass fractions.
virtual void setState_RPY (doublereal rho, doublereal p, const std::string &y)
Set the density (kg/m**3), pressure (Pa) and mass fractions.
virtual void setState (const AnyMap &state)
Set the state using an AnyMap containing any combination of properties supported by the thermodynamic model.
Set Mixture Composition by Mixture Fraction
void setMixtureFraction (double mixFrac, const double *fuelComp, const double *oxComp, ThermoBasis basis=ThermoBasis::molar)
Set the mixture composition according to the mixture fraction = kg fuel / (kg oxidizer + kg fuel)
void setMixtureFraction (double mixFrac, const std::string &fuelComp, const std::string &oxComp, ThermoBasis basis=ThermoBasis::molar)
Set the mixture composition according to the mixture fraction = kg fuel / (kg oxidizer + kg fuel)
void setMixtureFraction (double mixFrac, const compositionMap &fuelComp, const compositionMap &oxComp, ThermoBasis basis=ThermoBasis::molar)
Set the mixture composition according to the mixture fraction = kg fuel / (kg oxidizer + kg fuel)
Compute Mixture Fraction
double mixtureFraction (const double *fuelComp, const double *oxComp, ThermoBasis basis=ThermoBasis::molar, const std::string &element="Bilger") const
Compute the mixture fraction = kg fuel / (kg oxidizer + kg fuel) for the current mixture given fuel and oxidizer compositions.
double mixtureFraction (const std::string &fuelComp, const std::string &oxComp, ThermoBasis basis=ThermoBasis::molar, const std::string &element="Bilger") const
Compute the mixture fraction = kg fuel / (kg oxidizer + kg fuel) for the current mixture given fuel and oxidizer compositions.
double mixtureFraction (const compositionMap &fuelComp, const compositionMap &oxComp, ThermoBasis basis=ThermoBasis::molar, const std::string &element="Bilger") const
Compute the mixture fraction = kg fuel / (kg oxidizer + kg fuel) for the current mixture given fuel and oxidizer compositions.
Set Mixture Composition by Equivalence Ratio
void setEquivalenceRatio (double phi, const double *fuelComp, const double *oxComp, ThermoBasis basis=ThermoBasis::molar)
Set the mixture composition according to the equivalence ratio.
void setEquivalenceRatio (double phi, const std::string &fuelComp, const std::string &oxComp, ThermoBasis basis=ThermoBasis::molar)
Set the mixture composition according to the equivalence ratio.
void setEquivalenceRatio (double phi, const compositionMap &fuelComp, const compositionMap &oxComp, ThermoBasis basis=ThermoBasis::molar)
Set the mixture composition according to the equivalence ratio.
Compute Equivalence Ratio
double equivalenceRatio (const double *fuelComp, const double *oxComp, ThermoBasis basis=ThermoBasis::molar) const
Compute the equivalence ratio for the current mixture given the compositions of fuel and oxidizer.
double equivalenceRatio (const std::string &fuelComp, const std::string &oxComp, ThermoBasis basis=ThermoBasis::molar) const
Compute the equivalence ratio for the current mixture given the compositions of fuel and oxidizer.
double equivalenceRatio (const compositionMap &fuelComp, const compositionMap &oxComp, ThermoBasis basis=ThermoBasis::molar) const
Compute the equivalence ratio for the current mixture given the compositions of fuel and oxidizer.
double equivalenceRatio () const
Compute the equivalence ratio for the current mixture from available oxygen and required oxygen.
Chemical Equilibrium
Chemical equilibrium.
void equilibrate (const std::string &XY, const std::string &solver="auto", double rtol=1e-9, int max_steps=50000, int max_iter=100, int estimate_equil=0, int log_level=0)
Equilibrate a ThermoPhase object.
virtual void setToEquilState (const doublereal *mu_RT)
This method is used by the ChemEquil equilibrium solver.
virtual bool compatibleWithMultiPhase () const
Indicates whether this phase type can be used with class MultiPhase for equilibrium calculations.
Critical State Properties.
These methods are only implemented by subclasses that implement liquid-vapor equations of state.
virtual doublereal critTemperature () const
Critical temperature (K).
virtual doublereal critPressure () const
Critical pressure (Pa).
virtual doublereal critVolume () const
Critical volume (m3/kmol).
virtual doublereal critCompressibility () const
Critical compressibility (unitless).
virtual doublereal critDensity () const
Critical density (kg/m3).
Saturation Properties.
These methods are only implemented by subclasses that implement full liquid-vapor equations of state.
virtual doublereal satTemperature (doublereal p) const
Return the saturation temperature given the pressure.
virtual doublereal satPressure (doublereal t)
Return the saturation pressure given the temperature.
virtual doublereal vaporFraction () const
Return the fraction of vapor at the current conditions.
virtual void setState_Tsat (doublereal t, doublereal x)
Set the state to a saturated system at a particular temperature.
virtual void setState_Psat (doublereal p, doublereal x)
Set the state to a saturated system at a particular pressure.
void setState_TPQ (double T, double P, double Q)
Set the temperature, pressure, and vapor fraction (quality).
Initialization Methods - For Internal Use (ThermoPhase)
virtual bool addSpecies (shared_ptr< Species > spec)
virtual void modifySpecies (size_t k, shared_ptr< Species > spec)
Modify the thermodynamic data associated with a species.
void saveSpeciesData (const size_t k, const XML_Node *const data)
Store a reference pointer to the XML tree containing the species data for this phase.
const std::vector< const XML_Node * > & speciesData () const
Return a pointer to the vector of XML nodes containing the species data for this phase.
virtual MultiSpeciesThermo & speciesThermo (int k=-1)
Return a changeable reference to the calculation manager for species reference-state thermodynamic properties.
virtual const MultiSpeciesThermo & speciesThermo (int k=-1) const
virtual void initThermoFile (const std::string &inputFile, const std::string &id)
virtual void initThermoXML (XML_Node &phaseNode, const std::string &id)
Import and initialize a ThermoPhase object using an XML tree.
virtual void initThermo ()
Initialize the ThermoPhase object after all species have been set up.
virtual void setParameters (int n, doublereal *const c)
Set the equation of state parameters.
virtual void getParameters (int &n, doublereal *const c) const
Get the equation of state parameters in a vector.
virtual void setParameters (const AnyMap &phaseNode, const AnyMap &rootNode=AnyMap())
Set equation of state parameters from an AnyMap phase description.
const AnyMap & input () const
Access input data associated with the phase description.
AnyMap & input ()
virtual void setParametersFromXML (const XML_Node &eosdata)
Set equation of state parameter values from XML entries.
virtual void setStateFromXML (const XML_Node &state)
Set the initial state of the phase to the conditions specified in the state XML element.
virtual void invalidateCache ()
Invalidate any cached values which are normally updated only when a change in state is detected.
Derivatives of Thermodynamic Variables needed for Applications
virtual void getdlnActCoeffds (const doublereal dTds, const doublereal *const dXds, doublereal *dlnActCoeffds) const
Get the change in activity coefficients wrt changes in state (temp, mole fraction, etc) along a line in parameter space or along a line in physical space.
virtual void getdlnActCoeffdlnX_diag (doublereal *dlnActCoeffdlnX_diag) const
Get the array of ln mole fraction derivatives of the log activity coefficients - diagonal component only.
virtual void getdlnActCoeffdlnN_diag (doublereal *dlnActCoeffdlnN_diag) const
Get the array of log species mole number derivatives of the log activity coefficients.
virtual void getdlnActCoeffdlnN (const size_t ld, doublereal *const dlnActCoeffdlnN)
Get the array of derivatives of the log activity coefficients with respect to the log of the species mole numbers.
virtual void getdlnActCoeffdlnN_numderiv (const size_t ld, doublereal *const dlnActCoeffdlnN)
Public Member Functions inherited from Phase
Phase ()
Default constructor.
Phase (const Phase &)=delete
Phase & operator= (const Phase &)=delete
XML_Node & xml () const
Returns a const reference to the XML_Node that describes the phase.
void setXMLdata (XML_Node &xmlPhase)
Stores the XML tree information for the current phase.
virtual bool isPure () const
Return whether phase represents a pure (single species) substance.
virtual bool hasPhaseTransition () const
Return whether phase represents a substance with phase transitions.
virtual bool isCompressible () const
Return whether phase represents a compressible substance.
virtual std::map< std::string, size_t > nativeState () const
Return a map of properties defining the native state of a substance.
virtual std::vector< std::string > fullStates () const
Return a vector containing full states defining a phase.
virtual std::vector< std::string > partialStates () const
Return a vector of settable partial property sets within a phase.
virtual size_t stateSize () const
Return size of vector defining internal state of the phase.
void saveState (vector_fp &state) const
Save the current internal state of the phase.
virtual void saveState (size_t lenstate, doublereal *state) const
Write to array 'state' the current internal state.
void restoreState (const vector_fp &state)
Restore a state saved on a previous call to saveState.
virtual void restoreState (size_t lenstate, const doublereal *state)
Restore the state of the phase from a previously saved state vector.
doublereal molecularWeight (size_t k) const
Molecular weight of species k.
void getMolecularWeights (vector_fp &weights) const
Copy the vector of molecular weights into vector weights.
void getMolecularWeights (doublereal *weights) const
Copy the vector of molecular weights into array weights.
const vector_fp & molecularWeights () const
Return a const reference to the internal vector of molecular weights.
void getCharges (double *charges) const
Copy the vector of species charges into array charges.
virtual bool ready () const
Returns a bool indicating whether the object is ready for use.
int stateMFNumber () const
Return the State Mole Fraction Number.
bool caseSensitiveSpecies () const
Returns true if case sensitive species names are enforced.
void setCaseSensitiveSpecies (bool cflag=true)
Set flag that determines whether case sensitive species are enforced in look-up operations, e.g.
virtual void setRoot (std::shared_ptr< Solution > root)
Set root Solution holding all phase information.
vector_fp getCompositionFromMap (const compositionMap &comp) const
Converts a compositionMap to a vector with entries for each species Species that are not specified are set to zero in the vector.
void massFractionsToMoleFractions (const double *Y, double *X) const
Converts a mixture composition from mole fractions to mass fractions.
void moleFractionsToMassFractions (const double *X, double *Y) const
Converts a mixture composition from mass fractions to mole fractions.
std::string id () const
Return the string id for the phase.
void setID (const std::string &id)
Set the string id for the phase.
std::string name () const
Return the name of the phase.
void setName (const std::string &nm)
Sets the string name for the phase.
std::string elementName (size_t m) const
Name of the element with index m.
size_t elementIndex (const std::string &name) const
Return the index of element named 'name'.
const std::vector< std::string > & elementNames () const
Return a read-only reference to the vector of element names.
doublereal atomicWeight (size_t m) const
Atomic weight of element m.
doublereal entropyElement298 (size_t m) const
Entropy of the element in its standard state at 298 K and 1 bar.
int atomicNumber (size_t m) const
Atomic number of element m.
int elementType (size_t m) const
Return the element constraint type Possible types include:
int changeElementType (int m, int elem_type)
Change the element type of the mth constraint Reassigns an element type.
const vector_fp & atomicWeights () const
Return a read-only reference to the vector of atomic weights.
size_t nElements () const
Number of elements.
void checkElementIndex (size_t m) const
Check that the specified element index is in range.
void checkElementArraySize (size_t mm) const
Check that an array size is at least nElements().
doublereal nAtoms (size_t k, size_t m) const
Number of atoms of element m in species k.
void getAtoms (size_t k, double *atomArray) const
Get a vector containing the atomic composition of species k.
size_t speciesIndex (const std::string &name) const
Returns the index of a species named 'name' within the Phase object.
std::string speciesName (size_t k) const
Name of the species with index k.
std::string speciesSPName (int k) const
Returns the expanded species name of a species, including the phase name This is guaranteed to be unique within a Cantera problem.
const std::vector< std::string > & speciesNames () const
Return a const reference to the vector of species names.
size_t nSpecies () const
Returns the number of species in the phase.
void checkSpeciesIndex (size_t k) const
Check that the specified species index is in range.
void checkSpeciesArraySize (size_t kk) const
Check that an array size is at least nSpecies().
void setMoleFractionsByName (const compositionMap &xMap)
Set the species mole fractions by name.
void setMoleFractionsByName (const std::string &x)
Set the mole fractions of a group of species by name.
void setMassFractionsByName (const compositionMap &yMap)
Set the species mass fractions by name.
void setMassFractionsByName (const std::string &x)
Set the species mass fractions by name.
void setState_TRX (doublereal t, doublereal dens, const doublereal *x)
Set the internally stored temperature (K), density, and mole fractions.
void setState_TRX (doublereal t, doublereal dens, const compositionMap &x)
Set the internally stored temperature (K), density, and mole fractions.
void setState_TRY (doublereal t, doublereal dens, const doublereal *y)
Set the internally stored temperature (K), density, and mass fractions.
void setState_TRY (doublereal t, doublereal dens, const compositionMap &y)
Set the internally stored temperature (K), density, and mass fractions.
void setState_TNX (doublereal t, doublereal n, const doublereal *x)
Set the internally stored temperature (K), molar density (kmol/m^3), and mole fractions.
void setState_TR (doublereal t, doublereal rho)
Set the internally stored temperature (K) and density (kg/m^3)
void setState_TX (doublereal t, doublereal *x)
Set the internally stored temperature (K) and mole fractions.
void setState_TY (doublereal t, doublereal *y)
Set the internally stored temperature (K) and mass fractions.
void setState_RX (doublereal rho, doublereal *x)
Set the density (kg/m^3) and mole fractions.
void setState_RY (doublereal rho, doublereal *y)
Set the density (kg/m^3) and mass fractions.
compositionMap getMoleFractionsByName (double threshold=0.0) const
Get the mole fractions by name.
double moleFraction (size_t k) const
Return the mole fraction of a single species.
double moleFraction (const std::string &name) const
Return the mole fraction of a single species.
compositionMap getMassFractionsByName (double threshold=0.0) const
Get the mass fractions by name.
double massFraction (size_t k) const
Return the mass fraction of a single species.
double massFraction (const std::string &name) const
Return the mass fraction of a single species.
void getMoleFractions (double *const x) const
Get the species mole fraction vector.
virtual void setMoleFractions (const double *const x)
Set the mole fractions to the specified values.
virtual void setMoleFractions_NoNorm (const double *const x)
Set the mole fractions to the specified values without normalizing.
void getMassFractions (double *const y) const
Get the species mass fractions.
const double * massFractions () const
Return a const pointer to the mass fraction array.
virtual void setMassFractions (const double *const y)
Set the mass fractions to the specified values and normalize them.
virtual void setMassFractions_NoNorm (const double *const y)
Set the mass fractions to the specified values without normalizing.
void getConcentrations (double *const c) const
Get the species concentrations (kmol/m^3).
double concentration (const size_t k) const
Concentration of species k.
virtual void setConcentrations (const double *const conc)
Set the concentrations to the specified values within the phase.
virtual void setConcentrationsNoNorm (const double *const conc)
Set the concentrations without ignoring negative concentrations.
doublereal elementalMassFraction (const size_t m) const
Elemental mass fraction of element m.
doublereal elementalMoleFraction (const size_t m) const
Elemental mole fraction of element m.
const double * moleFractdivMMW () const
Returns a const pointer to the start of the moleFraction/MW array.
doublereal charge (size_t k) const
Dimensionless electrical charge of a single molecule of species k The charge is normalized by the the magnitude of the electron charge.
doublereal chargeDensity () const
Charge density [C/m^3].
size_t nDim () const
Returns the number of spatial dimensions (1, 2, or 3)
void setNDim (size_t ndim)
Set the number of spatial dimensions (1, 2, or 3).
doublereal temperature () const
Temperature (K).
virtual double pressure () const
Return the thermodynamic pressure (Pa).
virtual double density () const
Density (kg/m^3).
double molarDensity () const
Molar density (kmol/m^3).
double molarVolume () const
Molar volume (m^3/kmol).
virtual void setDensity (const double density_)
Set the internally stored density (kg/m^3) of the phase.
virtual void setMolarDensity (const double molarDensity)
Set the internally stored molar density (kmol/m^3) of the phase.
virtual void setPressure (double p)
Set the internally stored pressure (Pa) at constant temperature and composition.
virtual void setTemperature (const doublereal temp)
Set the internally stored temperature of the phase (K).
doublereal mean_X (const doublereal *const Q) const
Evaluate the mole-fraction-weighted mean of an array Q.
doublereal mean_X (const vector_fp &Q) const
Evaluate the mole-fraction-weighted mean of an array Q.
doublereal meanMolecularWeight () const
The mean molecular weight. Units: (kg/kmol)
doublereal sum_xlogx () const
Evaluate \(\sum_k X_k \log X_k \).
size_t addElement (const std::string &symbol, doublereal weight=-12345.0, int atomicNumber=0, doublereal entropy298=ENTROPY298_UNKNOWN, int elem_type=CT_ELEM_TYPE_ABSPOS)
Add an element.
void addSpeciesAlias (const std::string &name, const std::string &alias)
Add a species alias (i.e.
virtual std::vector< std::string > findIsomers (const compositionMap &compMap) const
Return a vector with isomers names matching a given composition map.
virtual std::vector< std::string > findIsomers (const std::string &comp) const
Return a vector with isomers names matching a given composition string.
shared_ptr< Species > species (const std::string &name) const
Return the Species object for the named species.
shared_ptr< Species > species (size_t k) const
Return the Species object for species whose index is k.
void ignoreUndefinedElements ()
Set behavior when adding a species containing undefined elements to just skip the species.
void addUndefinedElements ()
Set behavior when adding a species containing undefined elements to add those elements to the phase.
void throwUndefinedElements ()
Set the behavior when adding a species containing undefined elements to throw an exception.
Printing
MultiSpeciesThermo m_spthermo
Pointer to the calculation manager for species reference-state thermodynamic properties.
AnyMap m_input
Data supplied via setParameters.
std::vector< const XML_Node * > m_speciesData
Vector of pointers to the species databases.
doublereal m_phi
Stored value of the electric potential for this phase. Units are Volts.
bool m_chargeNeutralityNecessary
Boolean indicating whether a charge neutrality condition is a necessity.
int m_ssConvention
Contains the standard state convention.
doublereal m_tlast
last value of the temperature processed by reference state
virtual std::string report (bool show_thermo=true, doublereal threshold=-1e-14) const
returns a summary of the state of the phase as a string
virtual void reportCSV (std::ofstream &csvFile) const
returns a summary of the state of the phase to a comma separated file.
virtual void getCsvReportData (std::vector< std::string > &names, std::vector< vector_fp > &data) const
Fills names and data with the column names and species thermo properties to be included in the output of the reportCSV method.
Compute Stoichiometric Air to Fuel Ratio
double stoichAirFuelRatio (const double *fuelComp, const double *oxComp, ThermoBasis basis=ThermoBasis::molar) const
Compute the stoichiometric air to fuel ratio (kg oxidizer / kg fuel) given fuel and oxidizer compositions.
double stoichAirFuelRatio (const std::string &fuelComp, const std::string &oxComp, ThermoBasis basis=ThermoBasis::molar) const
Compute the stoichiometric air to fuel ratio (kg oxidizer / kg fuel) given fuel and oxidizer compositions.
double stoichAirFuelRatio (const compositionMap &fuelComp, const compositionMap &oxComp, ThermoBasis basis=ThermoBasis::molar) const
Compute the stoichiometric air to fuel ratio (kg oxidizer / kg fuel) given fuel and oxidizer compositions.
void setState_HPorUV (doublereal h, doublereal p, doublereal tol=1e-9, bool doUV=false)
Carry out work in HP and UV calculations.
void setState_SPorSV (double s, double p, double tol=1e-9, bool doSV=false)
Carry out work in SP and SV calculations.
void setState_conditional_TP (doublereal t, doublereal p, bool set_p)
Helper function used by setState_HPorUV and setState_SPorSV.
double o2Required (const double *y) const
Helper function for computing the amount of oxygen required for complete oxidation.
double o2Present (const double *y) const
Helper function for computing the amount of oxygen available in the current mixture.
Additional Inherited Members
Protected Member Functions inherited from Phase
void assertCompressible (const std::string &setter) const
Ensure that phase is compressible.
void assignDensity (const double density_)
Set the internally stored constant density (kg/m^3) of the phase.
void setMolecularWeight (const int k, const double mw)
Set the molecular weight of a single species to a given value.
virtual void compositionChanged ()
Apply changes to the state which are needed after the composition changes.
Protected Attributes inherited from Phase
ValueCache m_cache
Cached for saved calculations within each ThermoPhase.
size_t m_kk
Number of species in the phase.
size_t m_ndim
Dimensionality of the phase.
vector_fp m_speciesComp
Atomic composition of the species.
vector_fp m_speciesCharge
Vector of species charges. length m_kk.
std::map< std::string, shared_ptr< Species > > m_species
UndefElement::behavior m_undefinedElementBehavior
Flag determining behavior when adding species with an undefined element.
bool m_caseSensitiveSpecies
Flag determining whether case sensitive species names are enforced.
Detailed Description
Base class for a phase with thermodynamic properties.
Class ThermoPhase is the base class for the family of classes that represent phases of matter of any type. It defines a common public interface, and implements a few methods. Most of the methods, however, are declared virtual and are meant to be overloaded in derived classes. The standard way used throughout Cantera to compute properties of phases of matter is through pointers of type ThermoPhase* that point to objects of subclasses of ThermoPhase.
Class ThermoPhase extends class Phase by adding methods to compute thermodynamic properties in addition to the ones that are used to define the state of a substance (temperature, density/pressure and composition). The distinction is that the methods declared in ThermoPhase require knowing the particular equation of state of the phase of interest, while those of class Phase do not, since they only involve data values stored within the object.
Instances of subclasses of ThermoPhase should be created using the factory class ThermoFactory, not by calling the constructor directly. This allows new classes to be used with the various Cantera language interfaces.
To implement a new equation of state, derive a class from ThermoPhase and overload the virtual methods in ThermoPhase. Methods that are not needed can be left unimplemented, which will cause an exception to be thrown if it is called.
Relationship with the kinetics operator:
Describe activity coefficients.
Describe K_a, K_p, and K_c, These are three different equilibrium constants.
K_a is the calculation of the equilibrium constant from the standard state Gibbs free energy values. It is by definition dimensionless.
K_p is the calculation of the equilibrium constant from the reference state Gibbs free energy values. It is by definition dimensionless. The pressure dependence is handled entirely on the RHS of the equilibrium expression.
K_c is the equilibrium constant calculated from the activity concentrations. The dimensions depend on the number of products and reactants.
The kinetics manager requires the calculation of K_c for the calculation of the reverse rate constant
Definition at line 101 of file ThermoPhase.h.
Constructor & Destructor Documentation
ThermoPhase()
ThermoPhase ()
Constructor.
Note that ThermoPhase is meant to be used as a base class, so this constructor should not be called explicitly.
Definition at line 27 of file ThermoPhase.cpp.
Member Function Documentation
type()
virtual std::string type () const inline virtual
String indicating the thermodynamic model implemented.
Usually corresponds to the name of the derived class, less any suffixes such as "Phase", TP", "VPSS", etc.
Reimplemented from Phase.
Reimplemented in WaterSSTP, SurfPhase, StoichSubstance, SingleSpeciesTP, RedlichKwongMFTP, RedlichKisterVPSSTP, PureFluidPhase, MixtureFugacityTP, MetalPhase, MaskellSolidSolnPhase, MargulesVPSSTP, LatticeSolidPhase, LatticePhase, IonsFromNeutralVPSSTP, IdealSolnGasVPSS, IdealSolidSolnPhase, IdealMolalSoln, IdealGasPhase, HMWSoln, FixedChemPotSSTP, EdgePhase, DebyeHuckel, ConstDensityThermo, and BinarySolutionTabulatedThermo.
Definition at line 113 of file ThermoPhase.h.
Referenced by Kinetics::addPhase(), IdealGasConstPressureReactor::setThermoMgr(), IdealGasReactor::setThermoMgr(), and VCS_SOLVE::VCS_SOLVE().
phaseOfMatter()
virtual std::string phaseOfMatter () const inline virtual
String indicating the mechanical phase of the matter in this Phase.
Options for the string are:
unspecified
supercritical
gas
liquid
solid
solid-liquid-mix
solid-gas-mix
liquid-gas-mix
solid-liquid-gas-mix
unspecified is the default and should be used when the Phase does not distinguish between mechanical phases or does not have enough information to determine which mechanical phase(s) are present.
Todo:
Needs to be implemented for all phase types. Currently only implemented for PureFluidPhase.
Reimplemented in WaterSSTP, PureFluidPhase, MolalityVPSSTP, LatticeSolidPhase, IdealSolnGasVPSS, and IdealGasPhase.
Definition at line 137 of file ThermoPhase.h.
refPressure()
virtual doublereal refPressure () const inline virtual
Returns the reference pressure in Pa.
This function is a wrapper that calls the species thermo refPressure function.
Reimplemented in LatticeSolidPhase.
Definition at line 145 of file ThermoPhase.h.
References ThermoPhase::m_spthermo, and MultiSpeciesThermo::refPressure().
Referenced by MixtureFugacityTP::_updateReferenceStateThermo(), IdealGasPhase::addSpecies(), IdealSolidSolnPhase::addSpecies(), LatticePhase::addSpecies(), ConstDensityThermo::enthalpy_mole(), IdealGasPhase::entropy_mole(), RedlichKwongMFTP::entropy_mole(), ConstDensityThermo::getChemPotentials(), RedlichKwongMFTP::getChemPotentials(), IdealGasPhase::getEntropy_R(), MixtureFugacityTP::getEntropy_R(), PureFluidPhase::getEntropy_R_ref(), IdealGasPhase::getGibbs_RT(), MixtureFugacityTP::getGibbs_RT(), PureFluidPhase::getGibbs_RT_ref(), IdealGasPhase::getPartialMolarEntropies(), RedlichKwongMFTP::getPartialMolarEntropies(), IdealGasPhase::getPureGibbs(), MixtureFugacityTP::getPureGibbs(), IdealGasPhase::getStandardChemPotentials(), MixtureFugacityTP::getStandardChemPotentials(), MixtureFugacityTP::getStandardVolumes_ref(), ChemEquil::initialize(), StoichSubstance::initThermo(), IdealSolnGasVPSS::setToEquilState(), and IdealSolidSolnPhase::setToEquilState().
minTemp()
virtual doublereal minTemp (size_t k = npos) const inline virtual
Minimum temperature for which the thermodynamic data for the species or phase are valid.
If no argument is supplied, the value returned will be the lowest temperature at which the data for all species are valid. Otherwise, the value will be only for species k. This function is a wrapper that calls the species thermo minTemp function.
Parameters
k index of the species. Default is -1, which will return the max of the min value over all species.
Reimplemented in VPStandardStateTP, PureFluidPhase, and LatticeSolidPhase.
Definition at line 160 of file ThermoPhase.h.
References ThermoPhase::m_spthermo, and MultiSpeciesThermo::minTemp().
Referenced by MultiPhase::addPhase(), ChemEquil::equilibrate(), ThermoPhase::setState_HPorUV(), and ThermoPhase::setState_SPorSV().
Hf298SS()
doublereal Hf298SS (const size_t k) const inline
Report the 298 K Heat of Formation of the standard state of one species (J kmol-1)
The 298K Heat of Formation is defined as the enthalpy change to create the standard state of the species from its constituent elements in their standard states at 298 K and 1 bar.
Parameters
k species index
Returns
the current value of the Heat of Formation at 298K and 1 bar
Definition at line 175 of file ThermoPhase.h.
References ThermoPhase::m_spthermo, and MultiSpeciesThermo::reportOneHf298().
modifyOneHf298SS()
virtual void modifyOneHf298SS (const size_t k, const doublereal Hf298New) inline virtual
Modify the value of the 298 K Heat of Formation of one species in the phase (J kmol-1)
The 298K heat of formation is defined as the enthalpy change to create the standard state of the species from its constituent elements in their standard states at 298 K and 1 bar.
Parameters
k Species k
Hf298New Specify the new value of the Heat of Formation at 298K and 1 bar
Reimplemented in LatticeSolidPhase.
Definition at line 190 of file ThermoPhase.h.
References ThermoPhase::invalidateCache(), ThermoPhase::m_spthermo, and MultiSpeciesThermo::modifyOneHf298().
resetHf298()
void resetHf298 (const size_t k = npos) virtual
Restore the original heat of formation of one or more species.
Resets changes made by modifyOneHf298SS(). If the species index is not specified, the heats of formation for all species are restored.
Reimplemented in LatticeSolidPhase.
Definition at line 43 of file ThermoPhase.cpp.
References ThermoPhase::invalidateCache(), ThermoPhase::m_spthermo, Cantera::npos, Phase::nSpecies(), and MultiSpeciesThermo::resetHf298().
maxTemp()
virtual doublereal maxTemp (size_t k = npos) const inline virtual
Maximum temperature for which the thermodynamic data for the species are valid.
If no argument is supplied, the value returned will be the highest temperature at which the data for all species are valid. Otherwise, the value will be only for species k. This function is a wrapper that calls the species thermo maxTemp function.
Parameters
k index of the species. Default is -1, which will return the min of the max value over all species.
Reimplemented in VPStandardStateTP, PureFluidPhase, and LatticeSolidPhase.
Definition at line 213 of file ThermoPhase.h.
References ThermoPhase::m_spthermo, and MultiSpeciesThermo::maxTemp().
Referenced by MultiPhase::addPhase(), ChemEquil::equilibrate(), ThermoPhase::setState_HPorUV(), and ThermoPhase::setState_SPorSV().
chargeNeutralityNecessary()
bool chargeNeutralityNecessary () const inline
Returns the chargeNeutralityNecessity boolean.
Some phases must have zero net charge in order for their thermodynamics functions to be valid. If this is so, then the value returned from this function is true. If this is not the case, then this is false. Now, ideal gases have this parameter set to false, while solution with molality- based activity coefficients have this parameter set to true.
Definition at line 225 of file ThermoPhase.h.
References ThermoPhase::m_chargeNeutralityNecessary.
Referenced by Cantera::chargeNeutralityElement().
enthalpy_mole()
virtual doublereal enthalpy_mole () const inline virtual
Molar enthalpy. Units: J/kmol.
Reimplemented in SurfPhase, SingleSpeciesTP, RedlichKwongMFTP, RedlichKisterVPSSTP, PureFluidPhase, MetalPhase, MaskellSolidSolnPhase, MargulesVPSSTP, LatticeSolidPhase, LatticePhase, IonsFromNeutralVPSSTP, IdealSolnGasVPSS, IdealSolidSolnPhase, IdealMolalSoln, IdealGasPhase, HMWSoln, DebyeHuckel, and ConstDensityThermo.
Definition at line 234 of file ThermoPhase.h.
Referenced by ThermoPhase::enthalpy_mass(), ThermoPhase::gibbs_mole(), and ThermoPhase::intEnergy_mole().
intEnergy_mole()
virtual doublereal intEnergy_mole () const inline virtual
Molar internal energy. Units: J/kmol.
Reimplemented in SurfPhase, SingleSpeciesTP, PureFluidPhase, MetalPhase, LatticeSolidPhase, and IdealMolalSoln.
Definition at line 239 of file ThermoPhase.h.
References ThermoPhase::enthalpy_mole(), Phase::molarVolume(), and Phase::pressure().
Referenced by ThermoPhase::intEnergy_mass().
entropy_mole()
virtual doublereal entropy_mole () const inline virtual
Molar entropy. Units: J/kmol/K.
Reimplemented in SurfPhase, SingleSpeciesTP, RedlichKwongMFTP, RedlichKisterVPSSTP, PureFluidPhase, MetalPhase, MaskellSolidSolnPhase, MargulesVPSSTP, LatticeSolidPhase, LatticePhase, IonsFromNeutralVPSSTP, IdealSolnGasVPSS, IdealSolidSolnPhase, IdealMolalSoln, IdealGasPhase, HMWSoln, DebyeHuckel, and ConstDensityThermo.
Definition at line 244 of file ThermoPhase.h.
Referenced by ThermoPhase::entropy_mass(), and ThermoPhase::gibbs_mole().
gibbs_mole()
virtual doublereal gibbs_mole () const inline virtual
Molar Gibbs function. Units: J/kmol.
Reimplemented in SingleSpeciesTP, PureFluidPhase, MetalPhase, LatticeSolidPhase, IonsFromNeutralVPSSTP, IdealSolidSolnPhase, IdealMolalSoln, HMWSoln, and DebyeHuckel.
Definition at line 249 of file ThermoPhase.h.
References ThermoPhase::enthalpy_mole(), ThermoPhase::entropy_mole(), and Phase::temperature().
Referenced by ThermoPhase::gibbs_mass().
cp_mole()
virtual doublereal cp_mole () const inline virtual
Molar heat capacity at constant pressure. Units: J/kmol/K.
Reimplemented in SurfPhase, SingleSpeciesTP, RedlichKwongMFTP, RedlichKisterVPSSTP, PureFluidPhase, MetalPhase, MargulesVPSSTP, LatticeSolidPhase, LatticePhase, IonsFromNeutralVPSSTP, IdealSolnGasVPSS, IdealSolidSolnPhase, IdealMolalSoln, IdealGasPhase, HMWSoln, DebyeHuckel, and ConstDensityThermo.
Definition at line 254 of file ThermoPhase.h.
Referenced by ThermoPhase::cp_mass().
cv_mole()
virtual doublereal cv_mole () const inline virtual
Molar heat capacity at constant volume. Units: J/kmol/K.
Reimplemented in WaterSSTP, SurfPhase, SingleSpeciesTP, RedlichKwongMFTP, RedlichKisterVPSSTP, PureFluidPhase, MetalPhase, MargulesVPSSTP, LatticeSolidPhase, LatticePhase, IonsFromNeutralVPSSTP, IdealSolnGasVPSS, IdealSolidSolnPhase, IdealGasPhase, HMWSoln, and ConstDensityThermo.
Definition at line 259 of file ThermoPhase.h.
Referenced by ThermoPhase::cv_mass().
isothermalCompressibility()
virtual doublereal isothermalCompressibility () const inline virtual
Returns the isothermal compressibility. Units: 1/Pa.
The isothermal compressibility is defined as
\[ \kappa_T = -\frac{1}{v}\left(\frac{\partial v}{\partial P}\right)_T \]
or
\[ \kappa_T = \frac{1}{\rho}\left(\frac{\partial \rho}{\partial P}\right)_T \]
Reimplemented in WaterSSTP, StoichSubstance, PureFluidPhase, IdealSolnGasVPSS, IdealMolalSoln, IdealGasPhase, and FixedChemPotSSTP.
Definition at line 278 of file ThermoPhase.h.
Referenced by HMWSoln::cv_mole().
thermalExpansionCoeff()
virtual doublereal thermalExpansionCoeff () const inline virtual
Return the volumetric thermal expansion coefficient. Units: 1/K.
The thermal expansion coefficient is defined as
\[ \beta = \frac{1}{v}\left(\frac{\partial v}{\partial T}\right)_P \]
Reimplemented in WaterSSTP, StoichSubstance, PureFluidPhase, IdealMolalSoln, IdealGasPhase, and FixedChemPotSSTP.
Definition at line 289 of file ThermoPhase.h.
setElectricPotential()
void setElectricPotential (doublereal v) inline
Set the electric potential of this phase (V).
This is used by classes InterfaceKinetics and EdgeKinetics to compute the rates of charge-transfer reactions, and in computing the electrochemical potentials of the species.
Each phase may have its own electric potential.
Parameters
v Input value of the electric potential in Volts
Definition at line 312 of file ThermoPhase.h.
References ThermoPhase::m_phi.
electricPotential()
doublereal electricPotential () const inline
Returns the electric potential of this phase (V).
Units are Volts (which are Joules/coulomb)
Definition at line 320 of file ThermoPhase.h.
References ThermoPhase::m_phi.
Referenced by InterfaceKinetics::_update_rates_phi(), ThermoPhase::getElectrochemPotentials(), and VCS_SOLVE::VCS_SOLVE().
activityConvention()
int activityConvention () const virtual
This method returns the convention used in specification of the activities, of which there are currently two, molar- and molality-based conventions.
Currently, there are two activity conventions:
Molar-based activities Unit activity of species at either a hypothetical pure solution of the species or at a hypothetical pure ideal solution at infinite dilution cAC_CONVENTION_MOLAR 0
default
Molality-based activities (unit activity of solutes at a hypothetical 1 molal solution referenced to infinite dilution at all pressures and temperatures). cAC_CONVENTION_MOLALITY 1
Reimplemented in MolalityVPSSTP.
Definition at line 54 of file ThermoPhase.cpp.
References Cantera::cAC_CONVENTION_MOLAR.
Referenced by vcs_MultiPhaseEquil::reportCSV(), and VCS_SOLVE::VCS_SOLVE().
standardStateConvention()
int standardStateConvention () const virtual
This method returns the convention used in specification of the standard state, of which there are currently two, temperature based, and variable pressure based.
Currently, there are two standard state conventions:
Temperature-based activities cSS_CONVENTION_TEMPERATURE 0
default
Variable Pressure and Temperature -based activities cSS_CONVENTION_VPSS 1
Thermodynamics is set via slave ThermoPhase objects with nothing being carried out at this ThermoPhase object level cSS_CONVENTION_SLAVE 2
Reimplemented in VPStandardStateTP, MixtureFugacityTP, and LatticeSolidPhase.
Definition at line 59 of file ThermoPhase.cpp.
References ThermoPhase::m_ssConvention.
Referenced by Cantera::importPhase().
standardConcentrationUnits()
Units standardConcentrationUnits () const virtual
Returns the units of the "standard concentration" for this phase.
These are the units of the values returned by the functions getActivityConcentrations() and standardConcentration(), which can vary between different ThermoPhase-derived classes, or change within a single class depending on input options. See the documentation for standardConcentration() for the derived class for specific details.
Reimplemented in StoichSubstance, PureFluidPhase, MetalPhase, MaskellSolidSolnPhase, LatticeSolidPhase, LatticePhase, IdealSolnGasVPSS, IdealSolidSolnPhase, IdealMolalSoln, GibbsExcessVPSSTP, and FixedChemPotSSTP.
Definition at line 64 of file ThermoPhase.cpp.
References Phase::nDim().
getActivityConcentrations()
virtual void getActivityConcentrations (doublereal * c) const inline virtual
This method returns an array of generalized concentrations.
\(C^a_k\) are defined such that \(a_k = C^a_k / C^0_k, \) where \(C^0_k \) is a standard concentration defined below and \(a_k \) are activities used in the thermodynamic functions. These activity (or generalized) concentrations are used by kinetics manager classes to compute the forward and reverse rates of elementary reactions. Note that they may or may not have units of concentration — they might be partial pressures, mole fractions, or surface coverages, for example.
Parameters
c Output array of generalized concentrations. The units depend upon the implementation of the reaction rate expressions within the phase.
Reimplemented in SurfPhase, StoichSubstance, RedlichKwongMFTP, PureFluidPhase, MolalityVPSSTP, MetalPhase, MaskellSolidSolnPhase, LatticeSolidPhase, LatticePhase, IdealSolnGasVPSS, IdealSolidSolnPhase, IdealMolalSoln, IdealGasPhase, HMWSoln, GibbsExcessVPSSTP, FixedChemPotSSTP, DebyeHuckel, and ConstDensityThermo.
Definition at line 398 of file ThermoPhase.h.
Referenced by InterfaceKinetics::_update_rates_C(), ThermoPhase::getActivities(), and GasKinetics::update_rates_C().
standardConcentration()
virtual doublereal standardConcentration (size_t k = 0) const inline virtual
Return the standard concentration for the kth species.
The standard concentration \(C^0_k \) used to normalize the activity (i.e., generalized) concentration. In many cases, this quantity will be the same for all species in a phase - for example, for an ideal gas \(C^0_k = P/\hat R T \). For this reason, this method returns a single value, instead of an array. However, for phases in which the standard concentration is species-specific (e.g. surface species of different sizes), this method may be called with an optional parameter indicating the species.
Parameters
k Optional parameter indicating the species. The default is to assume this refers to species 0.
Returns
Returns the standard concentration. The units are by definition dependent on the ThermoPhase and kinetics manager representation.
Reimplemented in SurfPhase, StoichSubstance, RedlichKwongMFTP, PureFluidPhase, MolalityVPSSTP, MetalPhase, MaskellSolidSolnPhase, LatticeSolidPhase, LatticePhase, IdealSolnGasVPSS, IdealMolalSoln, IdealGasPhase, HMWSoln, GibbsExcessVPSSTP, FixedChemPotSSTP, DebyeHuckel, ConstDensityThermo, and IdealSolidSolnPhase.
Definition at line 419 of file ThermoPhase.h.
Referenced by InterfaceKinetics::buildSurfaceArrhenius(), ThermoPhase::getActivities(), ThermoPhase::logStandardConc(), and InterfaceKinetics::updateExchangeCurrentQuantities().
logStandardConc()
doublereal logStandardConc (size_t k = 0) const virtual
Natural logarithm of the standard concentration of the kth species.
Parameters
k index of the species (defaults to zero)
Reimplemented in SurfPhase, StoichSubstance, MetalPhase, MaskellSolidSolnPhase, LatticeSolidPhase, LatticePhase, GibbsExcessVPSSTP, and FixedChemPotSSTP.
Definition at line 70 of file ThermoPhase.cpp.
References ThermoPhase::standardConcentration().
Referenced by InterfaceKinetics::updateMu0().
getActivities()
void getActivities (doublereal * a) const virtual
Get the array of non-dimensional activities at the current solution temperature, pressure, and solution concentration.
Note, for molality based formulations, this returns the molality based activities.
We resolve this function at this level by calling on the activityConcentration function. However, derived classes may want to override this default implementation.
Parameters
a Output vector of activities. Length: m_kk.
Reimplemented in MolalityVPSSTP, IdealMolalSoln, HMWSoln, GibbsExcessVPSSTP, DebyeHuckel, SingleSpeciesTP, and PureFluidPhase.
Definition at line 75 of file ThermoPhase.cpp.
References ThermoPhase::getActivityConcentrations(), Phase::nSpecies(), and ThermoPhase::standardConcentration().
Referenced by ThermoPhase::getCsvReportData(), and vcs_MultiPhaseEquil::reportCSV().
getActivityCoefficients()
virtual void getActivityCoefficients (doublereal * ac) const inline virtual
Get the array of non-dimensional molar-based activity coefficients at the current solution temperature, pressure, and solution concentration.
Parameters
ac Output vector of activity coefficients. Length: m_kk.
Reimplemented in SingleSpeciesTP, RedlichKwongMFTP, MolalityVPSSTP, MaskellSolidSolnPhase, LatticeSolidPhase, LatticePhase, IonsFromNeutralVPSSTP, IdealSolnGasVPSS, IdealSolidSolnPhase, IdealGasPhase, GibbsExcessVPSSTP, and ConstDensityThermo.
Definition at line 448 of file ThermoPhase.h.
References Phase::m_kk.
Referenced by ChemEquil::calcEmoles(), ThermoPhase::getCsvReportData(), ThermoPhase::getLnActivityCoefficients(), and vcs_MultiPhaseEquil::reportCSV().
getLnActivityCoefficients()
void getLnActivityCoefficients (doublereal * lnac) const virtual
Get the array of non-dimensional molar-based ln activity coefficients at the current solution temperature, pressure, and solution concentration.
Parameters
lnac Output vector of ln activity coefficients. Length: m_kk.
Reimplemented in RedlichKisterVPSSTP, and MargulesVPSSTP.
Definition at line 83 of file ThermoPhase.cpp.
References ThermoPhase::getActivityCoefficients(), and Phase::m_kk.
getChemPotentials_RT()
virtual void getChemPotentials_RT (doublereal * mu) const inline virtual
Get the array of non-dimensional species chemical potentials These are partial molar Gibbs free energies.
\(\mu_k / \hat R T \). Units: unitless
Parameters
mu Output vector of dimensionless chemical potentials. Length: m_kk.
Reimplemented in SingleSpeciesTP, VPStandardStateTP, RedlichKwongMFTP, MixtureFugacityTP, MaskellSolidSolnPhase, and IdealSolidSolnPhase.
Definition at line 476 of file ThermoPhase.h.
getChemPotentials()
virtual void getChemPotentials (doublereal * mu) const inline virtual
Get the species chemical potentials. Units: J/kmol.
This function returns a vector of chemical potentials of the species in solution at the current temperature, pressure and mole fraction of the solution.
Parameters
mu Output vector of species chemical potentials. Length: m_kk. Units: J/kmol
Reimplemented in SurfPhase, SingleSpeciesTP, RedlichKwongMFTP, RedlichKisterVPSSTP, PureFluidPhase, MetalPhase, MaskellSolidSolnPhase, MargulesVPSSTP, LatticeSolidPhase, LatticePhase, IonsFromNeutralVPSSTP, IdealSolnGasVPSS, IdealSolidSolnPhase, IdealMolalSoln, IdealGasPhase, HMWSoln, DebyeHuckel, and ConstDensityThermo.
Definition at line 489 of file ThermoPhase.h.
Referenced by ChemEquil::estimateElementPotentials(), MixtureFugacityTP::getChemPotentials_RT(), VPStandardStateTP::getChemPotentials_RT(), MolalityVPSSTP::getCsvReportData(), ThermoPhase::getCsvReportData(), ThermoPhase::getElectrochemPotentials(), and vcs_MultiPhaseEquil::reportCSV().
getElectrochemPotentials()
void getElectrochemPotentials (doublereal * mu) const
Get the species electrochemical potentials.
These are partial molar quantities. This method adds a term \(F z_k \phi_p \) to each chemical potential. The electrochemical potential of species k in a phase p, \(\zeta_k \), is related to the chemical potential via the following equation,
 \f[
      \zeta_{k}(T,P) = \mu_{k}(T,P) + F z_k \phi_p
 \f]
Parameters
mu Output vector of species electrochemical potentials. Length: m_kk. Units: J/kmol
Definition at line 91 of file ThermoPhase.cpp.
References Phase::charge(), ThermoPhase::electricPotential(), Cantera::Faraday, ThermoPhase::getChemPotentials(), and Phase::m_kk.
Referenced by InterfaceKinetics::getDeltaElectrochemPotentials().
getPartialMolarEnthalpies()
virtual void getPartialMolarEnthalpies (doublereal * hbar) const inline virtual
Returns an array of partial molar enthalpies for the species in the mixture.
Units (J/kmol)
Parameters
hbar Output vector of species partial molar enthalpies. Length: m_kk. units are J/kmol.
Reimplemented in SurfPhase, SingleSpeciesTP, RedlichKwongMFTP, RedlichKisterVPSSTP, PureFluidPhase, MaskellSolidSolnPhase, MargulesVPSSTP, LatticeSolidPhase, LatticePhase, IonsFromNeutralVPSSTP, IdealSolnGasVPSS, IdealSolidSolnPhase, IdealMolalSoln, IdealGasPhase, HMWSoln, DebyeHuckel, and MetalPhase.
Definition at line 515 of file ThermoPhase.h.
Referenced by MolalityVPSSTP::getCsvReportData(), ThermoPhase::getCsvReportData(), and InterfaceKinetics::getDeltaEnthalpy().
getPartialMolarEntropies()
virtual void getPartialMolarEntropies (doublereal * sbar) const inline virtual
Returns an array of partial molar entropies of the species in the solution.
Units: J/kmol/K.
Parameters
sbar Output vector of species partial molar entropies. Length = m_kk. units are J/kmol/K.
Reimplemented in SurfPhase, SingleSpeciesTP, RedlichKwongMFTP, RedlichKisterVPSSTP, PureFluidPhase, MaskellSolidSolnPhase, MargulesVPSSTP, LatticeSolidPhase, LatticePhase, IonsFromNeutralVPSSTP, IdealSolnGasVPSS, IdealSolidSolnPhase, IdealMolalSoln, IdealGasPhase, HMWSoln, and DebyeHuckel.
Definition at line 525 of file ThermoPhase.h.
Referenced by MolalityVPSSTP::getCsvReportData(), ThermoPhase::getCsvReportData(), and InterfaceKinetics::getDeltaEntropy().
getPartialMolarIntEnergies()
virtual void getPartialMolarIntEnergies (doublereal * ubar) const inline virtual
Return an array of partial molar internal energies for the species in the mixture.
Units: J/kmol.
Parameters
ubar Output vector of species partial molar internal energies. Length = m_kk. units are J/kmol.
Reimplemented in SingleSpeciesTP, RedlichKwongMFTP, PureFluidPhase, IdealSolnGasVPSS, and IdealGasPhase.
Definition at line 535 of file ThermoPhase.h.
Referenced by MolalityVPSSTP::getCsvReportData(), and ThermoPhase::getCsvReportData().
getPartialMolarCp()
virtual void getPartialMolarCp (doublereal * cpbar) const inline virtual
Return an array of partial molar heat capacities for the species in the mixture.
Units: J/kmol/K
Parameters
cpbar Output vector of species partial molar heat capacities at constant pressure. Length = m_kk. units are J/kmol/K.
Reimplemented in SurfPhase, SingleSpeciesTP, RedlichKwongMFTP, RedlichKisterVPSSTP, PureFluidPhase, MaskellSolidSolnPhase, MargulesVPSSTP, LatticeSolidPhase, LatticePhase, IdealSolnGasVPSS, IdealSolidSolnPhase, IdealMolalSoln, IdealGasPhase, HMWSoln, and DebyeHuckel.
Definition at line 546 of file ThermoPhase.h.
Referenced by IonsFromNeutralVPSSTP::cp_mole(), IonsFromNeutralVPSSTP::cv_mole(), MolalityVPSSTP::getCsvReportData(), and ThermoPhase::getCsvReportData().
getPartialMolarVolumes()
virtual void getPartialMolarVolumes (doublereal * vbar) const inline virtual
Return an array of partial molar volumes for the species in the mixture.
Units: m^3/kmol.
Parameters
vbar Output vector of species partial molar volumes. Length = m_kk. units are m^3/kmol.
Reimplemented in SurfPhase, SingleSpeciesTP, RedlichKwongMFTP, RedlichKisterVPSSTP, PureFluidPhase, MaskellSolidSolnPhase, MargulesVPSSTP, LatticeSolidPhase, LatticePhase, IdealSolnGasVPSS, IdealSolidSolnPhase, IdealMolalSoln, IdealGasPhase, HMWSoln, GibbsExcessVPSSTP, FixedChemPotSSTP, and DebyeHuckel.
Definition at line 556 of file ThermoPhase.h.
Referenced by MolalityVPSSTP::getCsvReportData(), ThermoPhase::getCsvReportData(), and vcs_MultiPhaseEquil::reportCSV().
getStandardChemPotentials()
virtual void getStandardChemPotentials (doublereal * mu) const inline virtual
Get the array of chemical potentials at unit activity for the species at their standard states at the current T and P of the solution.
These are the standard state chemical potentials \(\mu^0_k(T,P) \). The values are evaluated at the current temperature and pressure of the solution
Parameters
mu Output vector of chemical potentials. Length: m_kk.
Reimplemented in SurfPhase, StoichSubstance, MetalPhase, LatticeSolidPhase, IdealSolidSolnPhase, FixedChemPotSSTP, ConstDensityThermo, VPStandardStateTP, PureFluidPhase, MixtureFugacityTP, MaskellSolidSolnPhase, LatticePhase, IdealGasPhase, and WaterSSTP.
Definition at line 574 of file ThermoPhase.h.
Referenced by SingleSpeciesTP::getChemPotentials(), SingleSpeciesTP::getChemPotentials_RT(), InterfaceKinetics::getDeltaSSGibbs(), GasKinetics::getEquilibriumConstants(), vcs_MultiPhaseEquil::reportCSV(), InterfaceKinetics::updateExchangeCurrentQuantities(), GasKinetics::updateKc(), and InterfaceKinetics::updateMu0().
getEnthalpy_RT()
virtual void getEnthalpy_RT (doublereal * hrt) const inline virtual
Get the nondimensional Enthalpy functions for the species at their standard states at the current T and P of the solution.
Parameters
hrt Output vector of nondimensional standard state enthalpies. Length: m_kk.
Reimplemented in WaterSSTP, VPStandardStateTP, SurfPhase, StoichSubstance, PureFluidPhase, MixtureFugacityTP, MetalPhase, LatticePhase, IdealSolidSolnPhase, IdealGasPhase, FixedChemPotSSTP, and ConstDensityThermo.
Definition at line 584 of file ThermoPhase.h.
Referenced by InterfaceKinetics::getDeltaSSEnthalpy(), and SingleSpeciesTP::getPartialMolarEnthalpies().
getEntropy_R()
virtual void getEntropy_R (doublereal * sr) const inline virtual
Get the array of nondimensional Entropy functions for the standard state species at the current T and P of the solution.
Parameters
sr Output vector of nondimensional standard state entropies. Length: m_kk.
Reimplemented in WaterSSTP, VPStandardStateTP, SurfPhase, StoichSubstance, PureFluidPhase, MixtureFugacityTP, MetalPhase, LatticePhase, IdealSolidSolnPhase, IdealGasPhase, FixedChemPotSSTP, and ConstDensityThermo.
Definition at line 594 of file ThermoPhase.h.
Referenced by InterfaceKinetics::getDeltaSSEntropy(), and SingleSpeciesTP::getPartialMolarEntropies().
getGibbs_RT()
virtual void getGibbs_RT (doublereal * grt) const inline virtual
Get the nondimensional Gibbs functions for the species in their standard states at the current T and P of the solution.
Parameters
grt Output vector of nondimensional standard state Gibbs free energies. Length: m_kk.
Reimplemented in WaterSSTP, VPStandardStateTP, SurfPhase, StoichSubstance, PureFluidPhase, MixtureFugacityTP, LatticePhase, IdealSolidSolnPhase, IdealGasPhase, FixedChemPotSSTP, and ConstDensityThermo.
Definition at line 604 of file ThermoPhase.h.
Referenced by SingleSpeciesTP::getPureGibbs().
getPureGibbs()
virtual void getPureGibbs (doublereal * gpure) const inline virtual
Get the Gibbs functions for the standard state of the species at the current T and P of the solution.
Units are Joules/kmol
Parameters
gpure Output vector of standard state Gibbs free energies. Length: m_kk.
Reimplemented in VPStandardStateTP, SingleSpeciesTP, MixtureFugacityTP, MaskellSolidSolnPhase, LatticePhase, IdealSolidSolnPhase, IdealGasPhase, ConstDensityThermo, and SurfPhase.
Definition at line 615 of file ThermoPhase.h.
getIntEnergy_RT()
virtual void getIntEnergy_RT (doublereal * urt) const inline virtual
Returns the vector of nondimensional Internal Energies of the standard state species at the current T and P of the solution.
Parameters
urt output vector of nondimensional standard state internal energies of the species. Length: m_kk.
Reimplemented in WaterSSTP, VPStandardStateTP, StoichSubstance, MixtureFugacityTP, IdealSolidSolnPhase, IdealGasPhase, and FixedChemPotSSTP.
Definition at line 625 of file ThermoPhase.h.
Referenced by SingleSpeciesTP::getPartialMolarIntEnergies().
getCp_R()
virtual void getCp_R (doublereal * cpr) const inline virtual
Get the nondimensional Heat Capacities at constant pressure for the species standard states at the current T and P of the solution.
Parameters
cpr Output vector of nondimensional standard state heat capacities. Length: m_kk.
Reimplemented in WaterSSTP, VPStandardStateTP, SurfPhase, StoichSubstance, MixtureFugacityTP, LatticePhase, IdealSolidSolnPhase, IdealGasPhase, FixedChemPotSSTP, and ConstDensityThermo.
Definition at line 636 of file ThermoPhase.h.
Referenced by SingleSpeciesTP::cp_mole(), and SingleSpeciesTP::getPartialMolarCp().
getStandardVolumes()
virtual void getStandardVolumes (doublereal * vol) const inline virtual
Get the molar volumes of the species standard states at the current T and P of the solution.
units = m^3 / kmol
Parameters
vol Output vector containing the standard state volumes. Length: m_kk.
Reimplemented in VPStandardStateTP, SurfPhase, MixtureFugacityTP, LatticePhase, IdealSolidSolnPhase, IdealGasPhase, SingleSpeciesTP, and FixedChemPotSSTP.
Definition at line 648 of file ThermoPhase.h.
getEnthalpy_RT_ref()
virtual void getEnthalpy_RT_ref (doublereal * hrt) const inline virtual
Returns the vector of nondimensional enthalpies of the reference state at the current temperature of the solution and the reference pressure for the species.
Parameters
hrt Output vector containing the nondimensional reference state enthalpies. Length: m_kk.
Reimplemented in WaterSSTP, VPStandardStateTP, SurfPhase, SingleSpeciesTP, PureFluidPhase, MixtureFugacityTP, IdealSolidSolnPhase, IdealGasPhase, and FixedChemPotSSTP.
Definition at line 663 of file ThermoPhase.h.
getGibbs_RT_ref()
virtual void getGibbs_RT_ref (doublereal * grt) const inline virtual
Returns the vector of nondimensional Gibbs Free Energies of the reference state at the current temperature of the solution and the reference pressure for the species.
Parameters
grt Output vector containing the nondimensional reference state Gibbs Free energies. Length: m_kk.
Reimplemented in WaterSSTP, VPStandardStateTP, SurfPhase, SingleSpeciesTP, PureFluidPhase, MixtureFugacityTP, LatticeSolidPhase, LatticePhase, IdealSolidSolnPhase, IdealGasPhase, and FixedChemPotSSTP.
Definition at line 674 of file ThermoPhase.h.
getGibbs_ref()
virtual void getGibbs_ref (doublereal * g) const inline virtual
Returns the vector of the Gibbs function of the reference state at the current temperature of the solution and the reference pressure for the species.
Parameters
g Output vector containing the reference state Gibbs Free energies. Length: m_kk. Units: J/kmol.
Reimplemented in WaterSSTP, VPStandardStateTP, SingleSpeciesTP, PureFluidPhase, MixtureFugacityTP, LatticeSolidPhase, LatticePhase, IdealSolidSolnPhase, IdealGasPhase, and FixedChemPotSSTP.
Definition at line 685 of file ThermoPhase.h.
getEntropy_R_ref()
virtual void getEntropy_R_ref (doublereal * er) const inline virtual
Returns the vector of nondimensional entropies of the reference state at the current temperature of the solution and the reference pressure for each species.
Parameters
er Output vector containing the nondimensional reference state entropies. Length: m_kk.
Reimplemented in WaterSSTP, VPStandardStateTP, SurfPhase, SingleSpeciesTP, PureFluidPhase, MixtureFugacityTP, IdealSolidSolnPhase, IdealGasPhase, and FixedChemPotSSTP.
Definition at line 696 of file ThermoPhase.h.
getIntEnergy_RT_ref()
virtual void getIntEnergy_RT_ref (doublereal * urt) const inline virtual
Returns the vector of nondimensional internal Energies of the reference state at the current temperature of the solution and the reference pressure for each species.
Parameters
urt Output vector of nondimensional reference state internal energies of the species. Length: m_kk
Reimplemented in StoichSubstance, IdealSolidSolnPhase, IdealGasPhase, and FixedChemPotSSTP.
Definition at line 707 of file ThermoPhase.h.
getCp_R_ref()
virtual void getCp_R_ref (doublereal * cprt) const inline virtual
Returns the vector of nondimensional constant pressure heat capacities of the reference state at the current temperature of the solution and reference pressure for each species.
Parameters
cprt Output vector of nondimensional reference state heat capacities at constant pressure for the species. Length: m_kk
Reimplemented in WaterSSTP, VPStandardStateTP, SurfPhase, SingleSpeciesTP, MixtureFugacityTP, IdealSolidSolnPhase, IdealGasPhase, and FixedChemPotSSTP.
Definition at line 719 of file ThermoPhase.h.
Referenced by HighPressureGasTransport::thermalConductivity(), and MultiTransport::updateThermal_T().
getStandardVolumes_ref()
virtual void getStandardVolumes_ref (doublereal * vol) const inline virtual
Get the molar volumes of the species reference states at the current T and P_ref of the solution.
units = m^3 / kmol
Parameters
vol Output vector containing the standard state volumes. Length: m_kk.
Reimplemented in WaterSSTP, VPStandardStateTP, MixtureFugacityTP, and IdealGasPhase.
Definition at line 731 of file ThermoPhase.h.
enthalpy_mass()
doublereal enthalpy_mass () const inline
Specific enthalpy. Units: J/kg.
Definition at line 742 of file ThermoPhase.h.
References ThermoPhase::enthalpy_mole(), and Phase::meanMolecularWeight().
Referenced by ChemEquil::equilibrate(), SingleSpeciesTP::setState_HP(), and ThermoPhase::setState_HPorUV().
intEnergy_mass()
doublereal intEnergy_mass () const inline
Specific internal energy. Units: J/kg.
Definition at line 747 of file ThermoPhase.h.
References ThermoPhase::intEnergy_mole(), and Phase::meanMolecularWeight().
Referenced by ChemEquil::equilibrate(), ThermoPhase::setState_HPorUV(), and SingleSpeciesTP::setState_UV().
entropy_mass()
doublereal entropy_mass () const inline
Specific entropy. Units: J/kg/K.
Definition at line 752 of file ThermoPhase.h.
References ThermoPhase::entropy_mole(), and Phase::meanMolecularWeight().
Referenced by ChemEquil::equilibrate(), SingleSpeciesTP::setState_SP(), ThermoPhase::setState_SPorSV(), and SingleSpeciesTP::setState_SV().
gibbs_mass()
doublereal gibbs_mass () const inline
Specific Gibbs function. Units: J/kg.
Definition at line 757 of file ThermoPhase.h.
References ThermoPhase::gibbs_mole(), and Phase::meanMolecularWeight().
cp_mass()
doublereal cp_mass () const inline
Specific heat at constant pressure. Units: J/kg/K.
Definition at line 762 of file ThermoPhase.h.
References ThermoPhase::cp_mole(), and Phase::meanMolecularWeight().
Referenced by UnityLewisTransport::getMixDiffCoeffs(), UnityLewisTransport::getMixDiffCoeffsMass(), SingleSpeciesTP::setState_HP(), ThermoPhase::setState_HPorUV(), SingleSpeciesTP::setState_SP(), ThermoPhase::setState_SPorSV(), and StFlow::updateThermo().
cv_mass()
doublereal cv_mass () const inline
Specific heat at constant volume. Units: J/kg/K.
Definition at line 767 of file ThermoPhase.h.
References ThermoPhase::cv_mole(), and Phase::meanMolecularWeight().
Referenced by ThermoPhase::setState_HPorUV(), ThermoPhase::setState_SPorSV(), SingleSpeciesTP::setState_SV(), and SingleSpeciesTP::setState_UV().
RT()
doublereal RT () const inline
Return the Gas Constant multiplied by the current temperature.
The units are Joules kmol-1
Definition at line 776 of file ThermoPhase.h.
References Cantera::GasConstant, and Phase::temperature().
Referenced by BinarySolutionTabulatedThermo::_updateThermo(), IdealSolidSolnPhase::_updateThermo(), IdealSolnGasVPSS::calcDensity(), ConstDensityThermo::enthalpy_mole(), IdealGasPhase::enthalpy_mole(), IdealSolidSolnPhase::enthalpy_mole(), IdealSolnGasVPSS::enthalpy_mole(), LatticePhase::enthalpy_mole(), RedlichKwongMFTP::enthalpy_mole(), RedlichKwongMFTP::getActivityCoefficients(), RedlichKwongMFTP::getActivityConcentrations(), ConstDensityThermo::getChemPotentials(), DebyeHuckel::getChemPotentials(), HMWSoln::getChemPotentials(), IdealGasPhase::getChemPotentials(), IdealMolalSoln::getChemPotentials(), IdealSolidSolnPhase::getChemPotentials(), IdealSolnGasVPSS::getChemPotentials(), IonsFromNeutralVPSSTP::getChemPotentials(), LatticePhase::getChemPotentials(), MargulesVPSSTP::getChemPotentials(), RedlichKisterVPSSTP::getChemPotentials(), RedlichKwongMFTP::getChemPotentials(), SurfPhase::getChemPotentials(), MixtureFugacityTP::getChemPotentials_RT(), RedlichKwongMFTP::getChemPotentials_RT(), VPStandardStateTP::getChemPotentials_RT(), SingleSpeciesTP::getChemPotentials_RT(), InterfaceKinetics::getDeltaSSEnthalpy(), FixedChemPotSSTP::getEnthalpy_RT(), IdealSolidSolnPhase::getEnthalpy_RT(), LatticePhase::getEnthalpy_RT(), PureFluidPhase::getEnthalpy_RT(), StoichSubstance::getEnthalpy_RT(), SurfPhase::getEnthalpy_RT(), WaterSSTP::getEnthalpy_RT(), FixedChemPotSSTP::getEnthalpy_RT_ref(), GasKinetics::getEquilibriumConstants(), InterfaceKinetics::getEquilibriumConstants(), IdealGasPhase::getGibbs_ref(), IdealSolidSolnPhase::getGibbs_ref(), LatticePhase::getGibbs_ref(), LatticeSolidPhase::getGibbs_ref(), MixtureFugacityTP::getGibbs_ref(), PureFluidPhase::getGibbs_ref(), SingleSpeciesTP::getGibbs_ref(), VPStandardStateTP::getGibbs_ref(), WaterSSTP::getGibbs_ref(), FixedChemPotSSTP::getGibbs_RT(), IdealSolidSolnPhase::getGibbs_RT(), LatticePhase::getGibbs_RT(), PureFluidPhase::getGibbs_RT(), SurfPhase::getGibbs_RT(), WaterSSTP::getGibbs_RT(), FixedChemPotSSTP::getGibbs_RT_ref(), IdealSolidSolnPhase::getIntEnergy_RT(), StoichSubstance::getIntEnergy_RT(), VPStandardStateTP::getIntEnergy_RT(), IdealSolidSolnPhase::getIntEnergy_RT_ref(), StoichSubstance::getIntEnergy_RT_ref(), DebyeHuckel::getPartialMolarCp(), HMWSoln::getPartialMolarCp(), DebyeHuckel::getPartialMolarEnthalpies(), HMWSoln::getPartialMolarEnthalpies(), IdealGasPhase::getPartialMolarEnthalpies(), IdealMolalSoln::getPartialMolarEnthalpies(), IdealSolidSolnPhase::getPartialMolarEnthalpies(), IdealSolnGasVPSS::getPartialMolarEnthalpies(), IonsFromNeutralVPSSTP::getPartialMolarEnthalpies(), LatticePhase::getPartialMolarEnthalpies(), MargulesVPSSTP::getPartialMolarEnthalpies(), RedlichKwongMFTP::getPartialMolarEnthalpies(), SingleSpeciesTP::getPartialMolarEnthalpies(), SurfPhase::getPartialMolarEnthalpies(), DebyeHuckel::getPartialMolarEntropies(), HMWSoln::getPartialMolarEntropies(), IdealGasPhase::getPartialMolarIntEnergies(), IdealSolnGasVPSS::getPartialMolarIntEnergies(), RedlichKwongMFTP::getPartialMolarIntEnergies(), SingleSpeciesTP::getPartialMolarIntEnergies(), DebyeHuckel::getPartialMolarVolumes(), HMWSoln::getPartialMolarVolumes(), RedlichKwongMFTP::getPartialMolarVolumes(), ConstDensityThermo::getPureGibbs(), IdealGasPhase::getPureGibbs(), IdealSolidSolnPhase::getPureGibbs(), LatticePhase::getPureGibbs(), MixtureFugacityTP::getPureGibbs(), SingleSpeciesTP::getPureGibbs(), VPStandardStateTP::getPureGibbs(), IdealGasPhase::getStandardChemPotentials(), LatticePhase::getStandardChemPotentials(), MixtureFugacityTP::getStandardChemPotentials(), VPStandardStateTP::getStandardChemPotentials(), StoichSubstance::getStandardChemPotentials(), MixtureFugacityTP::getStandardVolumes(), IdealGasPhase::getStandardVolumes_ref(), MixtureFugacityTP::getStandardVolumes_ref(), IdealSolidSolnPhase::gibbs_mole(), FixedChemPotSSTP::initThermoXML(), HMWSoln::relative_enthalpy(), IdealGasPhase::setPressure(), IdealGasPhase::standardConcentration(), IdealSolnGasVPSS::standardConcentration(), GasKinetics::updateKc(), InterfaceKinetics::updateKc(), InterfaceKinetics::updateMu0(), and MixtureFugacityTP::z().
setState_TPX() [1/3]
void setState_TPX (doublereal t, doublereal p, const doublereal * x) virtual
Set the temperature (K), pressure (Pa), and mole fractions.
Note, the mole fractions are set first before the pressure is set. Setting the pressure may involve the solution of a nonlinear equation.
Parameters
t Temperature (K)
p Pressure (Pa)
x Vector of mole fractions. Length is equal to m_kk.
Reimplemented in MixtureFugacityTP.
Definition at line 100 of file ThermoPhase.cpp.
References Phase::setMoleFractions(), and ThermoPhase::setState_TP().
Referenced by MultiTransport::getMassFluxes(), DustyGasTransport::getMolarFluxes(), MultiPhase::setMoles(), and MultiPhase::setPhaseMoleFractions().
setState_TPX() [2/3]
void setState_TPX (doublereal t, doublereal p, const compositionMap & x) virtual
Set the temperature (K), pressure (Pa), and mole fractions.
Note, the mole fractions are set first before the pressure is set. Setting the pressure may involve the solution of a nonlinear equation.
Parameters
t Temperature (K)
p Pressure (Pa)
x Composition map of mole fractions. Species not in the composition map are assumed to have zero mole fraction
Definition at line 106 of file ThermoPhase.cpp.
References Phase::setMoleFractionsByName(), and ThermoPhase::setState_TP().
setState_TPX() [3/3]
void setState_TPX (doublereal t, doublereal p, const std::string & x) virtual
Set the temperature (K), pressure (Pa), and mole fractions.
Note, the mole fractions are set first before the pressure is set. Setting the pressure may involve the solution of a nonlinear equation.
Parameters
t Temperature (K)
p Pressure (Pa)
x String containing a composition map of the mole fractions. Species not in the composition map are assumed to have zero mole fraction
Definition at line 112 of file ThermoPhase.cpp.
References Phase::setMoleFractionsByName(), and ThermoPhase::setState_TP().
setState_TPY() [1/3]
void setState_TPY (doublereal t, doublereal p, const doublereal * y) virtual
Set the internally stored temperature (K), pressure (Pa), and mass fractions of the phase.
Note, the mass fractions are set first before the pressure is set. Setting the pressure may involve the solution of a nonlinear equation.
Parameters
t Temperature (K)
p Pressure (Pa)
y Vector of mass fractions. Length is equal to m_kk.
Definition at line 118 of file ThermoPhase.cpp.
References Phase::setMassFractions(), and ThermoPhase::setState_TP().
setState_TPY() [2/3]
void setState_TPY (doublereal t, doublereal p, const compositionMap & y) virtual
Set the internally stored temperature (K), pressure (Pa), and mass fractions of the phase.
Note, the mass fractions are set first before the pressure is set. Setting the pressure may involve the solution of a nonlinear equation.
Parameters
t Temperature (K)
p Pressure (Pa)
y Composition map of mass fractions. Species not in the composition map are assumed to have zero mass fraction
Definition at line 124 of file ThermoPhase.cpp.
References Phase::setMassFractionsByName(), and ThermoPhase::setState_TP().
setState_TPY() [3/3]
void setState_TPY (doublereal t, doublereal p, const std::string & y) virtual
Set the internally stored temperature (K), pressure (Pa), and mass fractions of the phase.
Note, the mass fractions are set first before the pressure is set. Setting the pressure may involve the solution of a nonlinear equation.
Parameters
t Temperature (K)
p Pressure (Pa)
y String containing a composition map of the mass fractions. Species not in the composition map are assumed to have zero mass fraction
Definition at line 130 of file ThermoPhase.cpp.
References Phase::setMassFractionsByName(), and ThermoPhase::setState_TP().
setState_TP()
void setState_TP (doublereal t, doublereal p) virtual
Set the temperature (K) and pressure (Pa)
Setting the pressure may involve the solution of a nonlinear equation.
Parameters
t Temperature (K)
p Pressure (Pa)
Reimplemented in VPStandardStateTP, and MixtureFugacityTP.
Definition at line 136 of file ThermoPhase.cpp.
References Phase::density(), Phase::setPressure(), Phase::setState_TR(), Phase::setTemperature(), and Phase::temperature().
Referenced by ImplicitSurfChem::setCommonState_TP(), ThermoPhase::setState(), SingleSpeciesTP::setState_HP(), SingleSpeciesTP::setState_SP(), ThermoPhase::setState_TPX(), and ThermoPhase::setState_TPY().
setState_PX()
void setState_PX (doublereal p, doublereal * x) virtual
Set the pressure (Pa) and mole fractions.
Note, the mole fractions are set first before the pressure is set. Setting the pressure may involve the solution of a nonlinear equation.
Parameters
p Pressure (Pa)
x Vector of mole fractions. Length is equal to m_kk.
Definition at line 185 of file ThermoPhase.cpp.
References Phase::setMoleFractions(), and Phase::setPressure().
Referenced by IdealSolnGasVPSS::setToEquilState(), IdealGasPhase::setToEquilState(), and IdealSolidSolnPhase::setToEquilState().
setState_PY()
void setState_PY (doublereal p, doublereal * y) virtual
Set the internally stored pressure (Pa) and mass fractions.
Note, the temperature is held constant during this operation. Note, the mass fractions are set first before the pressure is set. Setting the pressure may involve the solution of a nonlinear equation.
Parameters
p Pressure (Pa)
y Vector of mass fractions. Length is equal to m_kk.
Definition at line 191 of file ThermoPhase.cpp.
References Phase::setMassFractions(), and Phase::setPressure().
setState_HP()
void setState_HP (double h, double p, double tol = 1e-9) virtual
Set the internally stored specific enthalpy (J/kg) and pressure (Pa) of the phase.
Parameters
h Specific enthalpy (J/kg)
p Pressure (Pa)
tol Optional parameter setting the tolerance of the calculation. Important for some applications where numerical Jacobians are being calculated.
Reimplemented in SingleSpeciesTP, and PureFluidPhase.
Definition at line 197 of file ThermoPhase.cpp.
References ThermoPhase::setState_HPorUV().
setState_UV()
void setState_UV (double u, double v, double tol = 1e-9) virtual
Set the specific internal energy (J/kg) and specific volume (m^3/kg).
This function fixes the internal state of the phase so that the specific internal energy and specific volume have the value of the input parameters.
Parameters
u specific internal energy (J/kg)
v specific volume (m^3/kg).
tol Optional parameter setting the tolerance of the calculation. Important for some applications where numerical Jacobians are being calculated.
Reimplemented in SingleSpeciesTP, and PureFluidPhase.
Definition at line 202 of file ThermoPhase.cpp.
References Phase::assertCompressible(), and ThermoPhase::setState_HPorUV().
setState_SP()
void setState_SP (double s, double p, double tol = 1e-9) virtual
Set the specific entropy (J/kg/K) and pressure (Pa).
This function fixes the internal state of the phase so that the specific entropy and the pressure have the value of the input parameters.
Parameters
s specific entropy (J/kg/K)
p specific pressure (Pa).
tol Optional parameter setting the tolerance of the calculation. Important for some applications where numerical Jacobians are being calculated.
Reimplemented in SingleSpeciesTP, and PureFluidPhase.
Definition at line 516 of file ThermoPhase.cpp.
References ThermoPhase::setState_SPorSV().
setState_SV()
void setState_SV (double s, double v, double tol = 1e-9) virtual
Set the specific entropy (J/kg/K) and specific volume (m^3/kg).
This function fixes the internal state of the phase so that the specific entropy and specific volume have the value of the input parameters.
Parameters
s specific entropy (J/kg/K)
v specific volume (m^3/kg).
tol Optional parameter setting the tolerance of the calculation. Important for some applications where numerical Jacobians are being calculated.
Reimplemented in SingleSpeciesTP, and PureFluidPhase.
Definition at line 521 of file ThermoPhase.cpp.
References Phase::assertCompressible(), and ThermoPhase::setState_SPorSV().
setState_ST()
virtual void setState_ST (double s, double t, double tol = 1e-9) inline virtual
Set the specific entropy (J/kg/K) and temperature (K).
This function fixes the internal state of the phase so that the specific entropy and temperature have the value of the input parameters. This base class function will throw an exception if not overridden.
Parameters
s specific entropy (J/kg/K)
t temperature (K)
tol Optional parameter setting the tolerance of the calculation. Important for some applications where numerical Jacobians are being calculated.
Reimplemented in PureFluidPhase.
Definition at line 959 of file ThermoPhase.h.
setState_TV()
virtual void setState_TV (double t, double v, double tol = 1e-9) inline virtual
Set the temperature (K) and specific volume (m^3/kg).
This function fixes the internal state of the phase so that the temperature and specific volume have the value of the input parameters. This base class function will throw an exception if not overridden.
Parameters
t temperature (K)
v specific volume (m^3/kg)
tol Optional parameter setting the tolerance of the calculation. Important for some applications where numerical Jacobians are being calculated.
Reimplemented in PureFluidPhase.
Definition at line 975 of file ThermoPhase.h.
setState_PV()
virtual void setState_PV (double p, double v, double tol = 1e-9) inline virtual
Set the pressure (Pa) and specific volume (m^3/kg).
This function fixes the internal state of the phase so that the pressure and specific volume have the value of the input parameters. This base class function will throw an exception if not overridden.
Parameters
p pressure (Pa)
v specific volume (m^3/kg)
tol Optional parameter setting the tolerance of the calculation. Important for some applications where numerical Jacobians are being calculated.
Reimplemented in PureFluidPhase.
Definition at line 991 of file ThermoPhase.h.
setState_UP()
virtual void setState_UP (double u, double p, double tol = 1e-9) inline virtual
Set the specific internal energy (J/kg) and pressure (Pa).
This function fixes the internal state of the phase so that the specific internal energy and pressure have the value of the input parameters. This base class function will throw an exception if not overridden.
Parameters
u specific internal energy (J/kg)
p pressure (Pa)
tol Optional parameter setting the tolerance of the calculation. Important for some applications where numerical Jacobians are being calculated.
Reimplemented in PureFluidPhase.
Definition at line 1007 of file ThermoPhase.h.
setState_VH()
virtual void setState_VH (double v, double h, double tol = 1e-9) inline virtual
Set the specific volume (m^3/kg) and the specific enthalpy (J/kg)
This function fixes the internal state of the phase so that the specific volume and the specific enthalpy have the value of the input parameters. This base class function will throw an exception if not overridden.
Parameters
v specific volume (m^3/kg)
h specific enthalpy (J/kg)
tol Optional parameter setting the tolerance of the calculation. Important for some applications where numerical Jacobians are being calculated.
Reimplemented in PureFluidPhase.
Definition at line 1023 of file ThermoPhase.h.
setState_TH()
virtual void setState_TH (double t, double h, double tol = 1e-9) inline virtual
Set the temperature (K) and the specific enthalpy (J/kg)
This function fixes the internal state of the phase so that the temperature and specific enthalpy have the value of the input parameters. This base class function will throw an exception if not overridden.
Parameters
t temperature (K)
h specific enthalpy (J/kg)
tol Optional parameter setting the tolerance of the calculation. Important for some applications where numerical Jacobians are being calculated.
Reimplemented in PureFluidPhase.
Definition at line 1039 of file ThermoPhase.h.
setState_SH()
virtual void setState_SH (double s, double h, double tol = 1e-9) inline virtual
Set the specific entropy (J/kg/K) and the specific enthalpy (J/kg)
This function fixes the internal state of the phase so that the temperature and pressure have the value of the input parameters. This base class function will throw an exception if not overridden.
Parameters
s specific entropy (J/kg/K)
h specific enthalpy (J/kg)
tol Optional parameter setting the tolerance of the calculation. Important for some applications where numerical Jacobians are being calculated.
Reimplemented in PureFluidPhase.
Definition at line 1055 of file ThermoPhase.h.
setState_RP()
virtual void setState_RP (doublereal rho, doublereal p) inline virtual
Set the density (kg/m**3) and pressure (Pa) at constant composition.
This method must be reimplemented in derived classes, where it may involve the solution of a nonlinear equation. Within Cantera, the independent variable is the density. Therefore, this function solves for the temperature that will yield the desired input pressure and density. The composition is held constant during this process.
This base class function will print an error, if not overridden.
Parameters
rho Density (kg/m^3)
p Pressure (Pa)
Reimplemented in IdealGasPhase.
Definition at line 1072 of file ThermoPhase.h.
Referenced by ThermoPhase::setState_RPX(), and ThermoPhase::setState_RPY().
setState_RPX() [1/3]
void setState_RPX (doublereal rho, doublereal p, const doublereal * x) virtual
Set the density (kg/m**3), pressure (Pa) and mole fractions.
Note, the mole fractions are set first before the density and pressure are set. Setting the pressure may involve the solution of a nonlinear equation.
Parameters
rho Density (kg/m^3)
p Pressure (Pa)
x Vector of mole fractions. Length is equal to m_kk.
Definition at line 149 of file ThermoPhase.cpp.
References Phase::setMoleFractions(), and ThermoPhase::setState_RP().
setState_RPX() [2/3]
void setState_RPX (doublereal rho, doublereal p, const compositionMap & x) virtual
Set the density (kg/m**3), pressure (Pa) and mole fractions.
Note, the mole fractions are set first before the density and pressure are set. Setting the pressure may involve the solution of a nonlinear equation.
Parameters
rho Density (kg/m^3)
p Pressure (Pa)
x Composition map of mole fractions. Species not in the composition map are assumed to have zero mole fraction
Definition at line 155 of file ThermoPhase.cpp.
References Phase::setMoleFractionsByName(), and ThermoPhase::setState_RP().
setState_RPX() [3/3]
void setState_RPX (doublereal rho, doublereal p, const std::string & x) virtual
Set the density (kg/m**3), pressure (Pa) and mole fractions.
Note, the mole fractions are set first before the density and pressure are set. Setting the pressure may involve the solution of a nonlinear equation.
Parameters
rho Density (kg/m^3)
p Pressure (Pa)
x String containing a composition map of the mole fractions. Species not in the composition map are assumed to have zero mole fraction
Definition at line 161 of file ThermoPhase.cpp.
References Phase::setMoleFractionsByName(), and ThermoPhase::setState_RP().
setState_RPY() [1/3]
void setState_RPY (doublereal rho, doublereal p, const doublereal * y) virtual
Set the density (kg/m**3), pressure (Pa) and mass fractions.
Note, the mass fractions are set first before the density and pressure are set. Setting the pressure may involve the solution of a nonlinear equation.
Parameters
rho Density (kg/m^3)
p Pressure (Pa)
y Vector of mole fractions. Length is equal to m_kk.
Definition at line 167 of file ThermoPhase.cpp.
References Phase::setMassFractions(), and ThermoPhase::setState_RP().
setState_RPY() [2/3]
void setState_RPY (doublereal rho, doublereal p, const compositionMap & y) virtual
Set the density (kg/m**3), pressure (Pa) and mass fractions.
Note, the mass fractions are set first before the density and pressure are set. Setting the pressure may involve the solution of a nonlinear equation.
Parameters
rho Density (kg/m^3)
p Pressure (Pa)
y Composition map of mole fractions. Species not in the composition map are assumed to have zero mole fraction
Definition at line 173 of file ThermoPhase.cpp.
References Phase::setMassFractionsByName(), and ThermoPhase::setState_RP().
setState_RPY() [3/3]
void setState_RPY (doublereal rho, doublereal p, const std::string & y) virtual
Set the density (kg/m**3), pressure (Pa) and mass fractions.
Note, the mass fractions are set first before the density and pressure are set. Setting the pressure may involve the solution of a nonlinear equation.
Parameters
rho Density (kg/m^3)
p Pressure (Pa)
y String containing a composition map of the mole fractions. Species not in the composition map are assumed to have zero mole fraction
Definition at line 179 of file ThermoPhase.cpp.
References Phase::setMassFractionsByName(), and ThermoPhase::setState_RP().
setState()
void setState (const AnyMap & state) virtual
Set the state using an AnyMap containing any combination of properties supported by the thermodynamic model.
Accepted keys are:
X (mole fractions)
Y (mass fractions)
T or temperature
P or pressure [Pa]
H or enthalpy [J/kg]
U or internal-energy [J/kg]
S or entropy [J/kg/K]
V or specific-volume [m^3/kg]
D or density [kg/m^3]
Composition can be specified as either an AnyMap of species names to values or as a composition string. All other values can be given as floating point values in Cantera's default units, or as strings with the units specified, which will be converted using the Units class.
If no thermodynamic property pair is given, or only one of temperature or pressure is given, then 298.15 K and 101325 Pa will be used as necessary to fully set the state.
Reimplemented in SurfPhase, and MolalityVPSSTP.
Definition at line 208 of file ThermoPhase.cpp.
References AnyMap::erase(), AnyMap::hasKey(), Cantera::OneAtm, Phase::setMassFractionsByName(), Phase::setMoleFractionsByName(), ThermoPhase::setState_TP(), and AnyMap::size().
Referenced by MolalityVPSSTP::setState(), and SurfPhase::setState().
setMixtureFraction() [1/3]
void setMixtureFraction (double mixFrac, const double * fuelComp, const double * oxComp, ThermoBasis basis = ThermoBasis::molar)
Set the mixture composition according to the mixture fraction = kg fuel / (kg oxidizer + kg fuel)
Fuel and oxidizer compositions are given either as mole fractions or mass fractions (specified by basis) and do not need to be normalized. Pressure and temperature are kept constant. Elements C, S, H and O are considered for the oxidation.
Parameters
mixFrac mixture fraction (between 0 and 1)
fuelComp composition of the fuel
oxComp composition of the oxidizer
basis either ThermoPhase::molar or ThermoPhase::mass. Fuel and oxidizer composition are interpreted as mole or mass fractions (default: molar)
Definition at line 923 of file ThermoPhase.cpp.
Referenced by ThermoPhase::setMixtureFraction().
setMixtureFraction() [2/3]
void setMixtureFraction (double mixFrac, const std::string & fuelComp, const std::string & oxComp, ThermoBasis basis = ThermoBasis::molar)
Set the mixture composition according to the mixture fraction = kg fuel / (kg oxidizer + kg fuel)
Fuel and oxidizer compositions are given either as mole fractions or mass fractions (specified by basis) and do not need to be normalized. Pressure and temperature are kept constant. Elements C, S, H and O are considered for the oxidation.
Parameters
mixFrac mixture fraction (between 0 and 1)
fuelComp composition of the fuel
oxComp composition of the oxidizer
basis either ThermoPhase::molar or ThermoPhase::mass. Fuel and oxidizer composition are interpreted as mole or mass fractions (default: molar)
Definition at line 914 of file ThermoPhase.cpp.
References Cantera::npos, Cantera::parseCompString(), and ThermoPhase::setMixtureFraction().
setMixtureFraction() [3/3]
void setMixtureFraction (double mixFrac, const compositionMap & fuelComp, const compositionMap & oxComp, ThermoBasis basis = ThermoBasis::molar)
Set the mixture composition according to the mixture fraction = kg fuel / (kg oxidizer + kg fuel)
Fuel and oxidizer compositions are given either as mole fractions or mass fractions (specified by basis) and do not need to be normalized. Pressure and temperature are kept constant. Elements C, S, H and O are considered for the oxidation.
Parameters
mixFrac mixture fraction (between 0 and 1)
fuelComp composition of the fuel
oxComp composition of the oxidizer
basis either ThermoPhase::molar or ThermoPhase::mass. Fuel and oxidizer composition are interpreted as mole or mass fractions (default: molar)
Definition at line 906 of file ThermoPhase.cpp.
References Phase::getCompositionFromMap(), and ThermoPhase::setMixtureFraction().
mixtureFraction() [1/3]
double mixtureFraction (const double * fuelComp, const double * oxComp, ThermoBasis basis = ThermoBasis::molar, const std::string & element = "Bilger") const
Compute the mixture fraction = kg fuel / (kg oxidizer + kg fuel) for the current mixture given fuel and oxidizer compositions.
Fuel and oxidizer compositions are given either as mole fractions or mass fractions (specified by basis) and do not need to be normalized. The mixture fraction \(Z \) can be computed from a single element
\[ Z_m = \frac{Z_{\mathrm{mass},m}-Z_{\mathrm{mass},m,\mathrm{ox}}} {Z_{\mathrm{mass},\mathrm{fuel}}-Z_{\mathrm{mass},m,\mathrm{ox}}} \]
where \(Z_{\mathrm{mass},m} \) is the elemental mass fraction of element m in the mixture, and \(Z_{\mathrm{mass},m,\mathrm{ox}} \) and \(Z_{\mathrm{mass},m,\mathrm{fuel}} \) are the elemental mass fractions of the oxidizer and fuel, or from the Bilger mixture fraction, which considers the elements C, S, H and O (R. W. Bilger, "Turbulent jet diffusion flames," Prog. Energy Combust. Sci., 109-131 (1979))
\[ Z_{\mathrm{Bilger}} = \frac{\beta-\beta_{\mathrm{ox}}} {\beta_{\mathrm{fuel}}-\beta_{\mathrm{ox}}} \]
with \(\beta = 2\frac{Z_C}{M_C}+2\frac{Z_S}{M_S}+\frac{1}{2}\frac{Z_H}{M_H} -\frac{Z_O}{M_O} \) and \(M_m \) the atomic weight of element \(m \).
Parameters
fuelComp composition of the fuel
oxComp composition of the oxidizer
basis either ThermoPhase::mole or ThermoPhase::mass. Fuel and oxidizer composition are interpreted as mole or mass fractions (default: molar)
element either "Bilger" to compute the mixture fraction in terms of the Bilger mixture fraction, or an element name, to compute the mixture fraction bsaed on a single element (default: "Bilger")
Returns
mixture fraction (kg fuel / kg mixture)
Definition at line 982 of file ThermoPhase.cpp.
Referenced by ThermoPhase::equivalenceRatio(), and ThermoPhase::mixtureFraction().
mixtureFraction() [2/3]
double mixtureFraction (const std::string & fuelComp, const std::string & oxComp, ThermoBasis basis = ThermoBasis::molar, const std::string & element = "Bilger") const
Compute the mixture fraction = kg fuel / (kg oxidizer + kg fuel) for the current mixture given fuel and oxidizer compositions.
Fuel and oxidizer compositions are given either as mole fractions or mass fractions (specified by basis) and do not need to be normalized. The mixture fraction \(Z \) can be computed from a single element
\[ Z_m = \frac{Z_{\mathrm{mass},m}-Z_{\mathrm{mass},m,\mathrm{ox}}} {Z_{\mathrm{mass},\mathrm{fuel}}-Z_{\mathrm{mass},m,\mathrm{ox}}} \]
where \(Z_{\mathrm{mass},m} \) is the elemental mass fraction of element m in the mixture, and \(Z_{\mathrm{mass},m,\mathrm{ox}} \) and \(Z_{\mathrm{mass},m,\mathrm{fuel}} \) are the elemental mass fractions of the oxidizer and fuel, or from the Bilger mixture fraction, which considers the elements C, S, H and O (R. W. Bilger, "Turbulent jet diffusion flames," Prog. Energy Combust. Sci., 109-131 (1979))
\[ Z_{\mathrm{Bilger}} = \frac{\beta-\beta_{\mathrm{ox}}} {\beta_{\mathrm{fuel}}-\beta_{\mathrm{ox}}} \]
with \(\beta = 2\frac{Z_C}{M_C}+2\frac{Z_S}{M_S}+\frac{1}{2}\frac{Z_H}{M_H} -\frac{Z_O}{M_O} \) and \(M_m \) the atomic weight of element \(m \).
Parameters
fuelComp composition of the fuel
oxComp composition of the oxidizer
basis either ThermoPhase::mole or ThermoPhase::mass. Fuel and oxidizer composition are interpreted as mole or mass fractions (default: molar)
element either "Bilger" to compute the mixture fraction in terms of the Bilger mixture fraction, or an element name, to compute the mixture fraction bsaed on a single element (default: "Bilger")
Returns
mixture fraction (kg fuel / kg mixture)
Definition at line 971 of file ThermoPhase.cpp.
References ThermoPhase::mixtureFraction(), Cantera::npos, and Cantera::parseCompString().
mixtureFraction() [3/3]
double mixtureFraction (const compositionMap & fuelComp, const compositionMap & oxComp, ThermoBasis basis = ThermoBasis::molar, const std::string & element = "Bilger") const
Compute the mixture fraction = kg fuel / (kg oxidizer + kg fuel) for the current mixture given fuel and oxidizer compositions.
Fuel and oxidizer compositions are given either as mole fractions or mass fractions (specified by basis) and do not need to be normalized. The mixture fraction \(Z \) can be computed from a single element
\[ Z_m = \frac{Z_{\mathrm{mass},m}-Z_{\mathrm{mass},m,\mathrm{ox}}} {Z_{\mathrm{mass},\mathrm{fuel}}-Z_{\mathrm{mass},m,\mathrm{ox}}} \]
where \(Z_{\mathrm{mass},m} \) is the elemental mass fraction of element m in the mixture, and \(Z_{\mathrm{mass},m,\mathrm{ox}} \) and \(Z_{\mathrm{mass},m,\mathrm{fuel}} \) are the elemental mass fractions of the oxidizer and fuel, or from the Bilger mixture fraction, which considers the elements C, S, H and O (R. W. Bilger, "Turbulent jet diffusion flames," Prog. Energy Combust. Sci., 109-131 (1979))
\[ Z_{\mathrm{Bilger}} = \frac{\beta-\beta_{\mathrm{ox}}} {\beta_{\mathrm{fuel}}-\beta_{\mathrm{ox}}} \]
with \(\beta = 2\frac{Z_C}{M_C}+2\frac{Z_S}{M_S}+\frac{1}{2}\frac{Z_H}{M_H} -\frac{Z_O}{M_O} \) and \(M_m \) the atomic weight of element \(m \).
Parameters
fuelComp composition of the fuel
oxComp composition of the oxidizer
basis either ThermoPhase::mole or ThermoPhase::mass. Fuel and oxidizer composition are interpreted as mole or mass fractions (default: molar)
element either "Bilger" to compute the mixture fraction in terms of the Bilger mixture fraction, or an element name, to compute the mixture fraction bsaed on a single element (default: "Bilger")
Returns
mixture fraction (kg fuel / kg mixture)
Definition at line 961 of file ThermoPhase.cpp.
References Phase::getCompositionFromMap(), and ThermoPhase::mixtureFraction().
setEquivalenceRatio() [1/3]
void setEquivalenceRatio (double phi, const double * fuelComp, const double * oxComp, ThermoBasis basis = ThermoBasis::molar)
Set the mixture composition according to the equivalence ratio.
Fuel and oxidizer compositions are given either as mole fractions or mass fractions (specified by basis) and do not need to be normalized. Pressure and temperature are kept constant. Elements C, S, H and O are considered for the oxidation.
Parameters
phi equivalence ratio
fuelComp composition of the fuel
oxComp composition of the oxidizer
basis either ThermoPhase::mole or ThermoPhase::mass. Fuel and oxidizer composition are interpreted as mole or mass fractions (default: molar)
Definition at line 795 of file ThermoPhase.cpp.
References Phase::pressure().
Referenced by ThermoPhase::setEquivalenceRatio().
setEquivalenceRatio() [2/3]
void setEquivalenceRatio (double phi, const std::string & fuelComp, const std::string & oxComp, ThermoBasis basis = ThermoBasis::molar)
Set the mixture composition according to the equivalence ratio.
Fuel and oxidizer compositions are given either as mole fractions or mass fractions (specified by basis) and do not need to be normalized. Pressure and temperature are kept constant. Elements C, S, H and O are considered for the oxidation.
Parameters
phi equivalence ratio
fuelComp composition of the fuel
oxComp composition of the oxidizer
basis either ThermoPhase::mole or ThermoPhase::mass. Fuel and oxidizer composition are interpreted as mole or mass fractions (default: molar)
Definition at line 829 of file ThermoPhase.cpp.
References Cantera::npos, Cantera::parseCompString(), and ThermoPhase::setEquivalenceRatio().
setEquivalenceRatio() [3/3]
void setEquivalenceRatio (double phi, const compositionMap & fuelComp, const compositionMap & oxComp, ThermoBasis basis = ThermoBasis::molar)
Set the mixture composition according to the equivalence ratio.
Fuel and oxidizer compositions are given either as mole fractions or mass fractions (specified by basis) and do not need to be normalized. Pressure and temperature are kept constant. Elements C, S, H and O are considered for the oxidation.
Parameters
phi equivalence ratio
fuelComp composition of the fuel
oxComp composition of the oxidizer
basis either ThermoPhase::mole or ThermoPhase::mass. Fuel and oxidizer composition are interpreted as mole or mass fractions (default: molar)
Definition at line 838 of file ThermoPhase.cpp.
References Phase::getCompositionFromMap(), and ThermoPhase::setEquivalenceRatio().
equivalenceRatio() [1/4]
double equivalenceRatio (const double * fuelComp, const double * oxComp, ThermoBasis basis = ThermoBasis::molar) const
Compute the equivalence ratio for the current mixture given the compositions of fuel and oxidizer.
The equivalence ratio \(\phi \) is computed from
\[ \phi = \frac{Z}{1-Z}\frac{1-Z_{\mathrm{st}}}{Z_{\mathrm{st}}} \]
where \(Z \) is the Bilger mixture fraction of the mixture given the specified fuel and oxidizer compositions \(Z_{\mathrm{st}} \) is the mixture fraction at stoichiometric conditions. Fuel and oxidizer compositions are given either as mole fractions or mass fractions (specified by basis) and do not need to be normalized. Elements C, S, H and O are considered for the oxidation. If fuel and oxidizer composition are unknown or not specified, use the version that takes no arguments.
Parameters
fuelComp composition of the fuel
oxComp composition of the oxidizer
basis either ThermoPhase::mole or ThermoPhase::mass. Fuel and oxidizer composition are interpreted as mole or mass fractions (default: molar)
Returns
equivalence ratio
See also
mixtureFraction for the definition of the Bilger mixture fraction
equivalenceRatio() for the computation of \(\phi \) without arguments
Definition at line 877 of file ThermoPhase.cpp.
References ThermoPhase::mixtureFraction().
equivalenceRatio() [2/4]
double equivalenceRatio (const std::string & fuelComp, const std::string & oxComp, ThermoBasis basis = ThermoBasis::molar) const
Compute the equivalence ratio for the current mixture given the compositions of fuel and oxidizer.
The equivalence ratio \(\phi \) is computed from
\[ \phi = \frac{Z}{1-Z}\frac{1-Z_{\mathrm{st}}}{Z_{\mathrm{st}}} \]
where \(Z \) is the Bilger mixture fraction of the mixture given the specified fuel and oxidizer compositions \(Z_{\mathrm{st}} \) is the mixture fraction at stoichiometric conditions. Fuel and oxidizer compositions are given either as mole fractions or mass fractions (specified by basis) and do not need to be normalized. Elements C, S, H and O are considered for the oxidation. If fuel and oxidizer composition are unknown or not specified, use the version that takes no arguments.
Parameters
fuelComp composition of the fuel
oxComp composition of the oxidizer
basis either ThermoPhase::mole or ThermoPhase::mass. Fuel and oxidizer composition are interpreted as mole or mass fractions (default: molar)
Returns
equivalence ratio
See also
mixtureFraction for the definition of the Bilger mixture fraction
equivalenceRatio() for the computation of \(\phi \) without arguments
Definition at line 867 of file ThermoPhase.cpp.
References ThermoPhase::equivalenceRatio(), Cantera::npos, and Cantera::parseCompString().
equivalenceRatio() [3/4]
double equivalenceRatio (const compositionMap & fuelComp, const compositionMap & oxComp, ThermoBasis basis = ThermoBasis::molar) const
Compute the equivalence ratio for the current mixture given the compositions of fuel and oxidizer.
The equivalence ratio \(\phi \) is computed from
\[ \phi = \frac{Z}{1-Z}\frac{1-Z_{\mathrm{st}}}{Z_{\mathrm{st}}} \]
where \(Z \) is the Bilger mixture fraction of the mixture given the specified fuel and oxidizer compositions \(Z_{\mathrm{st}} \) is the mixture fraction at stoichiometric conditions. Fuel and oxidizer compositions are given either as mole fractions or mass fractions (specified by basis) and do not need to be normalized. Elements C, S, H and O are considered for the oxidation. If fuel and oxidizer composition are unknown or not specified, use the version that takes no arguments.
Parameters
fuelComp composition of the fuel
oxComp composition of the oxidizer
basis either ThermoPhase::mole or ThermoPhase::mass. Fuel and oxidizer composition are interpreted as mole or mass fractions (default: molar)
Returns
equivalence ratio
See also
mixtureFraction for the definition of the Bilger mixture fraction
equivalenceRatio() for the computation of \(\phi \) without arguments
Definition at line 858 of file ThermoPhase.cpp.
References ThermoPhase::equivalenceRatio(), and Phase::getCompositionFromMap().
equivalenceRatio() [4/4]
double equivalenceRatio () const
Compute the equivalence ratio for the current mixture from available oxygen and required oxygen.
Computes the equivalence ratio \(\phi \) from
\[ \phi = \frac{Z_{\mathrm{mole},C} + Z_{\mathrm{mole},S} + \frac{1}{4}Z_{\mathrm{mole},H}} {\frac{1}{2}Z_{\mathrm{mole},O}} \]
where \(Z_{\mathrm{mole},m} \) is the elemental mole fraction of element \(m \). In this special case, the equivalence ratio is independent of a fuel or oxidizer composition because it only considers the locally available oxygen compared to the required oxygen for complete oxidation. It is the same as assuming that the oxidizer only contains O (and inert elements) and the fuel contains only H, C and S (and inert elements). If either of these conditions is not met, use the version of this functions which takes the fuel and oxidizer compositions as input
Returns
equivalence ratio
See also
equivalenceRatio compute the equivalence ratio from specific fuel and oxidizer compositions
Definition at line 846 of file ThermoPhase.cpp.
References Phase::massFractions(), ThermoPhase::o2Present(), and ThermoPhase::o2Required().
Referenced by ThermoPhase::equivalenceRatio().
stoichAirFuelRatio() [1/3]
double stoichAirFuelRatio (const double * fuelComp, const double * oxComp, ThermoBasis basis = ThermoBasis::molar) const
Compute the stoichiometric air to fuel ratio (kg oxidizer / kg fuel) given fuel and oxidizer compositions.
Fuel and oxidizer compositions are given either as mole fractions or mass fractions (specified by basis) and do not need to be normalized. Elements C, S, H and O are considered for the oxidation. Note that the stoichiometric air to fuel ratio \(\mathit{AFR}_{\mathrm{st}} \) does not depend on the current mixture composition. The current air to fuel ratio can be computed from \(\mathit{AFR} = \mathit{AFR}_{\mathrm{st}}/\phi \) where \(\phi \) is the equivalence ratio of the current mixture
Parameters
fuelComp composition of the fuel
oxComp composition of the oxidizer
basis either ThermoPhase::mole or ThermoPhase::mass. Fuel and oxidizer composition are interpreted as mole or mass fractions (default: molar)
Returns
Stoichiometric Air to Fuel Ratio (kg oxidizer / kg fuel)
Definition at line 764 of file ThermoPhase.cpp.
Referenced by ThermoPhase::stoichAirFuelRatio().
stoichAirFuelRatio() [2/3]
double stoichAirFuelRatio (const std::string & fuelComp, const std::string & oxComp, ThermoBasis basis = ThermoBasis::molar) const
Compute the stoichiometric air to fuel ratio (kg oxidizer / kg fuel) given fuel and oxidizer compositions.
Fuel and oxidizer compositions are given either as mole fractions or mass fractions (specified by basis) and do not need to be normalized. Elements C, S, H and O are considered for the oxidation. Note that the stoichiometric air to fuel ratio \(\mathit{AFR}_{\mathrm{st}} \) does not depend on the current mixture composition. The current air to fuel ratio can be computed from \(\mathit{AFR} = \mathit{AFR}_{\mathrm{st}}/\phi \) where \(\phi \) is the equivalence ratio of the current mixture
Parameters
fuelComp composition of the fuel
oxComp composition of the oxidizer
basis either ThermoPhase::mole or ThermoPhase::mass. Fuel and oxidizer composition are interpreted as mole or mass fractions (default: molar)
Returns
Stoichiometric Air to Fuel Ratio (kg oxidizer / kg fuel)
Definition at line 754 of file ThermoPhase.cpp.
References Cantera::npos, Cantera::parseCompString(), and ThermoPhase::stoichAirFuelRatio().
stoichAirFuelRatio() [3/3]
double stoichAirFuelRatio (const compositionMap & fuelComp, const compositionMap & oxComp, ThermoBasis basis = ThermoBasis::molar) const
Compute the stoichiometric air to fuel ratio (kg oxidizer / kg fuel) given fuel and oxidizer compositions.
Fuel and oxidizer compositions are given either as mole fractions or mass fractions (specified by basis) and do not need to be normalized. Elements C, S, H and O are considered for the oxidation. Note that the stoichiometric air to fuel ratio \(\mathit{AFR}_{\mathrm{st}} \) does not depend on the current mixture composition. The current air to fuel ratio can be computed from \(\mathit{AFR} = \mathit{AFR}_{\mathrm{st}}/\phi \) where \(\phi \) is the equivalence ratio of the current mixture
Parameters
fuelComp composition of the fuel
oxComp composition of the oxidizer
basis either ThermoPhase::mole or ThermoPhase::mass. Fuel and oxidizer composition are interpreted as mole or mass fractions (default: molar)
Returns
Stoichiometric Air to Fuel Ratio (kg oxidizer / kg fuel)
Definition at line 745 of file ThermoPhase.cpp.
References Phase::getCompositionFromMap(), and ThermoPhase::stoichAirFuelRatio().
setState_HPorUV()
void setState_HPorUV (doublereal h, doublereal p, doublereal tol = 1e-9, bool doUV = false) private
Carry out work in HP and UV calculations.
Parameters
h Specific enthalpy or internal energy (J/kg)
p Pressure (Pa) or specific volume (m^3/kg)
tol Optional parameter setting the tolerance of the calculation. Important for some applications where numerical Jacobians are being calculated.
doUV True if solving for UV, false for HP.
Definition at line 325 of file ThermoPhase.cpp.
References Cantera::clip(), ThermoPhase::cp_mass(), ThermoPhase::cv_mass(), ThermoPhase::enthalpy_mass(), ThermoPhase::intEnergy_mass(), ThermoPhase::maxTemp(), ThermoPhase::minTemp(), Phase::setDensity(), Phase::setPressure(), ThermoPhase::setState_conditional_TP(), and Phase::temperature().
Referenced by ThermoPhase::setState_HP(), and ThermoPhase::setState_UV().
setState_SPorSV()
void setState_SPorSV (double s, double p, double tol = 1e-9, bool doSV = false) private
Carry out work in SP and SV calculations.
Parameters
s Specific entropy (J/kg)
p Pressure (Pa) or specific volume (m^3/kg)
tol Optional parameter setting the tolerance of the calculation. Important for some applications where numerical Jacobians are being calculated.
doSV True if solving for SV, false for SP.
Definition at line 527 of file ThermoPhase.cpp.
References Cantera::clip(), ThermoPhase::cp_mass(), ThermoPhase::cv_mass(), ThermoPhase::entropy_mass(), ThermoPhase::maxTemp(), ThermoPhase::minTemp(), Phase::setDensity(), Phase::setPressure(), ThermoPhase::setState_conditional_TP(), and Phase::temperature().
Referenced by ThermoPhase::setState_SP(), and ThermoPhase::setState_SV().
setState_conditional_TP()
void setState_conditional_TP (doublereal t, doublereal p, bool set_p) private
Helper function used by setState_HPorUV and setState_SPorSV.
Sets the temperature and (if set_p is true) the pressure.
Definition at line 317 of file ThermoPhase.cpp.
References Phase::setPressure(), and Phase::setTemperature().
Referenced by ThermoPhase::setState_HPorUV(), and ThermoPhase::setState_SPorSV().
o2Required()
double o2Required (const double * y) const private
Helper function for computing the amount of oxygen required for complete oxidation.
Parameters
y array of (possibly non-normalized) mass fractions (length m_kk)
Returns
amount of required oxygen in kmol O / kg mixture
Definition at line 700 of file ThermoPhase.cpp.
References Phase::elementIndex(), Phase::m_kk, Phase::molecularWeights(), Phase::nAtoms(), and Cantera::npos.
Referenced by ThermoPhase::equivalenceRatio().
o2Present()
double o2Present (const double * y) const private
Helper function for computing the amount of oxygen available in the current mixture.
Parameters
y array of (possibly non-normalized) mass fractions (length m_kk)
Returns
amount of O in kmol O / kg mixture
Definition at line 729 of file ThermoPhase.cpp.
References Phase::elementIndex(), Phase::m_kk, Phase::molecularWeights(), and Phase::nAtoms().
Referenced by ThermoPhase::equivalenceRatio().
critTemperature()
virtual doublereal critTemperature () const inline virtual
Critical temperature (K).
Reimplemented in WaterSSTP, RedlichKwongMFTP, and PureFluidPhase.
Definition at line 1481 of file ThermoPhase.h.
Referenced by MixtureFugacityTP::calculatePsat(), MixtureFugacityTP::densityCalc(), MixtureFugacityTP::phaseState(), and MixtureFugacityTP::psatEst().
critPressure()
virtual doublereal critPressure () const inline virtual
Critical pressure (Pa).
Reimplemented in WaterSSTP, RedlichKwongMFTP, and PureFluidPhase.
Definition at line 1486 of file ThermoPhase.h.
Referenced by MixtureFugacityTP::psatEst().
critVolume()
virtual doublereal critVolume () const inline virtual
Critical volume (m3/kmol).
Reimplemented in RedlichKwongMFTP.
Definition at line 1491 of file ThermoPhase.h.
critCompressibility()
virtual doublereal critCompressibility () const inline virtual
Critical compressibility (unitless).
Reimplemented in RedlichKwongMFTP.
Definition at line 1496 of file ThermoPhase.h.
critDensity()
virtual doublereal critDensity () const inline virtual
Critical density (kg/m3).
Reimplemented in WaterSSTP, RedlichKwongMFTP, and PureFluidPhase.
Definition at line 1501 of file ThermoPhase.h.
Referenced by MixtureFugacityTP::phaseState().
satTemperature()
virtual doublereal satTemperature (doublereal p) const inline virtual
Return the saturation temperature given the pressure.
Parameters
p Pressure (Pa)
Reimplemented in PureFluidPhase.
Definition at line 1518 of file ThermoPhase.h.
satPressure()
virtual doublereal satPressure (doublereal t) inline virtual
Return the saturation pressure given the temperature.
Parameters
t Temperature (Kelvin)
Reimplemented in MixtureFugacityTP, WaterSSTP, PureFluidPhase, and HMWSoln.
Definition at line 1526 of file ThermoPhase.h.
Referenced by HighPressureGasTransport::viscosity().
vaporFraction()
virtual doublereal vaporFraction () const inline virtual
Return the fraction of vapor at the current conditions.
Reimplemented in WaterSSTP, and PureFluidPhase.
Definition at line 1531 of file ThermoPhase.h.
setState_Tsat()
virtual void setState_Tsat (doublereal t, doublereal x) inline virtual
Set the state to a saturated system at a particular temperature.
Parameters
t Temperature (kelvin)
x Fraction of vapor
Reimplemented in PureFluidPhase.
Definition at line 1540 of file ThermoPhase.h.
setState_Psat()
virtual void setState_Psat (doublereal p, doublereal x) inline virtual
Set the state to a saturated system at a particular pressure.
Parameters
p Pressure (Pa)
x Fraction of vapor
Reimplemented in PureFluidPhase.
Definition at line 1549 of file ThermoPhase.h.
setState_TPQ()
void setState_TPQ (double T, double P, double Q)
Set the temperature, pressure, and vapor fraction (quality).
An exception is thrown if the thermodynamic state is not consistent.
For temperatures below the critical temperature, if the vapor fraction is not 0 or 1, the pressure and temperature must fall on the saturation line.
Above the critical temperature, the vapor fraction must be 1 if the pressure is less than the critical pressure. Above the critical pressure, the vapor fraction is not defined, and its value is ignored.
Parameters
T Temperature (K)
P Pressure (Pa)
Q vapor fraction
Definition at line 1105 of file ThermoPhase.cpp.
addSpecies()
bool addSpecies (shared_ptr< Species > spec) virtual
The following methods are used in the process of constructing the phase and setting its parameters from a specification in an input file. They are not normally used in application programs. To see how they are used, see importPhase().
Reimplemented from Phase.
Reimplemented in VPStandardStateTP, SurfPhase, SingleSpeciesTP, RedlichKwongMFTP, MolalityVPSSTP, MixtureFugacityTP, LatticeSolidPhase, LatticePhase, IonsFromNeutralVPSSTP, IdealSolnGasVPSS, IdealSolidSolnPhase, IdealMolalSoln, IdealGasPhase, GibbsExcessVPSSTP, DebyeHuckel, and ConstDensityThermo.
Definition at line 1134 of file ThermoPhase.cpp.
References Phase::addSpecies(), MultiSpeciesThermo::install_STIT(), Phase::m_kk, and ThermoPhase::m_spthermo.
Referenced by LatticeSolidPhase::addLattice(), ConstDensityThermo::addSpecies(), IdealGasPhase::addSpecies(), IdealSolidSolnPhase::addSpecies(), LatticePhase::addSpecies(), MixtureFugacityTP::addSpecies(), SingleSpeciesTP::addSpecies(), SurfPhase::addSpecies(), and Cantera::importPhase().
modifySpecies()
void modifySpecies (size_t k, shared_ptr< Species > spec) virtual
Modify the thermodynamic data associated with a species.
The species name, elemental composition, and type of thermo parameterization must be unchanged. If there are Kinetics objects that depend on this phase, Kinetics::invalidateCache() should be called on those objects after calling this function.
Reimplemented from Phase.
Definition at line 1148 of file ThermoPhase.cpp.
References ThermoPhase::m_spthermo, MultiSpeciesThermo::modifySpecies(), Phase::modifySpecies(), and Phase::speciesName().
saveSpeciesData()
void saveSpeciesData (const size_t k, const XML_Node *const data)
Store a reference pointer to the XML tree containing the species data for this phase.
This is used to access data needed to construct transport manager later.
Parameters
k Species index
data Pointer to the XML_Node data containing information about the species in the phase.
Deprecated:
The XML input format is deprecated and will be removed in Cantera 3.0.
Definition at line 1164 of file ThermoPhase.cpp.
References ThermoPhase::m_speciesData.
Referenced by FixedChemPotSSTP::FixedChemPotSSTP().
speciesData()
const std::vector< const XML_Node * > & speciesData () const
Return a pointer to the vector of XML nodes containing the species data for this phase.
Deprecated:
The XML input format is deprecated and will be removed in Cantera 3.0.
Definition at line 1172 of file ThermoPhase.cpp.
References Phase::m_kk, and ThermoPhase::m_speciesData.
speciesThermo()
MultiSpeciesThermo & speciesThermo (int k = -1) virtual
Return a changeable reference to the calculation manager for species reference-state thermodynamic properties.
Parameters
k Species id. The default is -1, meaning return the default
Definition at line 1053 of file ThermoPhase.cpp.
References ThermoPhase::m_spthermo.
initThermoFile()
void initThermoFile (const std::string & inputFile, const std::string & id) virtual
Initialize a ThermoPhase object using an input file.
Used to implement constructors for derived classes which take a file name and phase name as arguments.
Parameters
inputFile Input file containing the description of the phase
id Optional parameter identifying the name of the phase. If blank, the first phase definition encountered will be used.
Definition at line 1064 of file ThermoPhase.cpp.
References Cantera::dot(), Cantera::findXMLPhase(), AnyMap::fromYamlFile(), Cantera::get_XML_File(), Cantera::importPhase(), Cantera::npos, and Cantera::setupPhase().
Referenced by BinarySolutionTabulatedThermo::BinarySolutionTabulatedThermo(), FixedChemPotSSTP::FixedChemPotSSTP(), IdealGasPhase::IdealGasPhase(), IdealMolalSoln::IdealMolalSoln(), IdealSolidSolnPhase::IdealSolidSolnPhase(), IonsFromNeutralVPSSTP::IonsFromNeutralVPSSTP(), LatticePhase::LatticePhase(), MargulesVPSSTP::MargulesVPSSTP(), RedlichKisterVPSSTP::RedlichKisterVPSSTP(), RedlichKwongMFTP::RedlichKwongMFTP(), StoichSubstance::StoichSubstance(), SurfPhase::SurfPhase(), and WaterSSTP::WaterSSTP().
initThermoXML()
void initThermoXML (XML_Node & phaseNode, const std::string & id) virtual
Import and initialize a ThermoPhase object using an XML tree.
Here we read extra information about the XML description of a phase. Regular information about elements and species and their reference state thermodynamic information have already been read at this point. For example, we do not need to call this function for ideal gas equations of state. This function is called from importPhase() after the elements and the species are initialized with default ideal solution level data.
The default implementation in ThermoPhase calls the virtual function initThermo() and then sets the "state" of the phase by looking for an XML element named "state", and then interpreting its contents by calling the virtual function setStateFromXML().
Parameters
phaseNode This object must be the phase node of a complete XML tree description of the phase, including all of the species data. In other words while "phase" must point to an XML phase object, it must have sibling nodes "speciesData" that describe the species in the phase.
id ID of the phase. If nonnull, a check is done to see if phaseNode is pointing to the phase with the correct id.
Deprecated:
The XML input format is deprecated and will be removed in Cantera 3.0.
Reimplemented in BinarySolutionTabulatedThermo, IdealMolalSoln, StoichSubstance, RedlichKwongMFTP, RedlichKisterVPSSTP, MaskellSolidSolnPhase, MargulesVPSSTP, IdealSolnGasVPSS, IdealSolidSolnPhase, HMWSoln, FixedChemPotSSTP, and DebyeHuckel.
Definition at line 1089 of file ThermoPhase.cpp.
References XML_Node::child(), XML_Node::hasChild(), and ThermoPhase::setStateFromXML().
Referenced by FixedChemPotSSTP::initThermoXML(), HMWSoln::initThermoXML(), IdealSolidSolnPhase::initThermoXML(), IdealSolnGasVPSS::initThermoXML(), MargulesVPSSTP::initThermoXML(), RedlichKisterVPSSTP::initThermoXML(), RedlichKwongMFTP::initThermoXML(), StoichSubstance::initThermoXML(), IdealMolalSoln::initThermoXML(), and BinarySolutionTabulatedThermo::initThermoXML().
initThermo()
void initThermo () virtual
Initialize the ThermoPhase object after all species have been set up.
Initialize.
This method is provided to allow subclasses to perform any initialization required after all species have been added. For example, it might be used to resize internal work arrays that must have an entry for each species. The base class implementation does nothing, and subclasses that do not require initialization do not need to overload this method. Derived classes which do override this function should call their parent class's implementation of this function as their last action.
When importing a CTML phase description, this method is called from initThermoXML(), which is called from importPhase(), just prior to returning from function importPhase().
When importing from an AnyMap phase description (or from a YAML file), this method is responsible for setting model parameters from the data stored in m_input.
Reimplemented in WaterSSTP, VPStandardStateTP, SurfPhase, StoichSubstance, RedlichKwongMFTP, RedlichKisterVPSSTP, PureFluidPhase, MolalityVPSSTP, MetalPhase, MaskellSolidSolnPhase, MargulesVPSSTP, LatticeSolidPhase, LatticePhase, IonsFromNeutralVPSSTP, IdealSolnGasVPSS, IdealSolidSolnPhase, IdealMolalSoln, HMWSoln, FixedChemPotSSTP, DebyeHuckel, ConstDensityThermo, and BinarySolutionTabulatedThermo.
Definition at line 1096 of file ThermoPhase.cpp.
References Phase::m_kk, ThermoPhase::m_spthermo, and MultiSpeciesThermo::ready().
Referenced by ConstDensityThermo::initThermo(), FixedChemPotSSTP::initThermo(), IdealSolidSolnPhase::initThermo(), LatticeSolidPhase::initThermo(), StoichSubstance::initThermo(), VPStandardStateTP::initThermo(), and WaterSSTP::initThermo().
setParameters() [1/2]
virtual void setParameters (int n, doublereal *const c) inline virtual
Set the equation of state parameters.
The number and meaning of these depends on the subclass.
Parameters
n number of parameters
c array of n coefficients
Reimplemented in SurfPhase, StoichSubstance, FixedChemPotSSTP, and ConstDensityThermo.
Definition at line 1691 of file ThermoPhase.h.
Referenced by IonsFromNeutralVPSSTP::setParameters(), and LatticeSolidPhase::setParameters().
getParameters()
virtual void getParameters (int & n, doublereal *const c) const inline virtual
Get the equation of state parameters in a vector.
The number and meaning of these depends on the subclass.
Parameters
n number of parameters
c array of n coefficients
Reimplemented in StoichSubstance, FixedChemPotSSTP, and ConstDensityThermo.
Definition at line 1701 of file ThermoPhase.h.
setParameters() [2/2]
void setParameters (const AnyMap & phaseNode, const AnyMap & rootNode = AnyMap()) virtual
Set equation of state parameters from an AnyMap phase description.
Phases that need additional parameters from the root node should override this method.
Reimplemented in LatticeSolidPhase, and IonsFromNeutralVPSSTP.
Definition at line 1181 of file ThermoPhase.cpp.
References ThermoPhase::m_input.
input()
const AnyMap & input () const
Access input data associated with the phase description.
Definition at line 1186 of file ThermoPhase.cpp.
References ThermoPhase::m_input.
Referenced by StoichSubstance::initThermo(), TransportFactory::newTransport(), and LatticePhase::setSiteDensity().
setParametersFromXML()
virtual void setParametersFromXML (const XML_Node & eosdata) inline virtual
Set equation of state parameter values from XML entries.
This method is called by function importPhase() when processing a phase definition in an input file. It should be overloaded in subclasses to set any parameters that are specific to that particular phase model. Note, this method is called before the phase is initialized with elements and/or species.
Parameters
eosdata An XML_Node object corresponding to the "thermo" entry for this phase in the input file.
Deprecated:
The XML input format is deprecated and will be removed in Cantera 3.0.
Reimplemented in RedlichKwongMFTP, IonsFromNeutralVPSSTP, IdealSolnGasVPSS, SurfPhase, EdgePhase, WaterSSTP, StoichSubstance, PureFluidPhase, MetalPhase, LatticeSolidPhase, LatticePhase, FixedChemPotSSTP, and ConstDensityThermo.
Definition at line 1728 of file ThermoPhase.h.
Referenced by Cantera::importPhase(), IdealSolnGasVPSS::setParametersFromXML(), IonsFromNeutralVPSSTP::setParametersFromXML(), and RedlichKwongMFTP::setParametersFromXML().
setStateFromXML()
void setStateFromXML (const XML_Node & state) virtual
Set the initial state of the phase to the conditions specified in the state XML element.
This method sets the temperature, pressure, and mole fraction vector to a set default value.
Parameters
state AN XML_Node object corresponding to the "state" entry for this phase in the input file.
Deprecated:
The XML input format is deprecated and will be removed in Cantera 3.0.
Reimplemented in SurfPhase, MolalityVPSSTP, and MixtureFugacityTP.
Definition at line 1196 of file ThermoPhase.cpp.
References Cantera::getChildValue(), Cantera::getFloat(), XML_Node::hasChild(), Phase::setDensity(), Phase::setMassFractionsByName(), Phase::setMoleFractionsByName(), Phase::setPressure(), and Phase::setTemperature().
Referenced by ThermoPhase::initThermoXML(), and MolalityVPSSTP::setStateFromXML().
invalidateCache()
void invalidateCache () virtual
Invalidate any cached values which are normally updated only when a change in state is detected.
Reimplemented from Phase.
Reimplemented in VPStandardStateTP, and MixtureFugacityTP.
Definition at line 1221 of file ThermoPhase.cpp.
References Phase::invalidateCache(), and ThermoPhase::m_tlast.
Referenced by MixtureFugacityTP::invalidateCache(), VPStandardStateTP::invalidateCache(), LatticeSolidPhase::modifyOneHf298SS(), ThermoPhase::modifyOneHf298SS(), LatticeSolidPhase::resetHf298(), and ThermoPhase::resetHf298().
getdlnActCoeffds()
virtual void getdlnActCoeffds (const doublereal dTds, const doublereal *const dXds, doublereal * dlnActCoeffds) const inline virtual
Get the change in activity coefficients wrt changes in state (temp, mole fraction, etc) along a line in parameter space or along a line in physical space.
Parameters
dTds Input of temperature change along the path
dXds Input vector of changes in mole fraction along the path. length = m_kk Along the path length it must be the case that the mole fractions sum to one.
dlnActCoeffds Output vector of the directional derivatives of the log Activity Coefficients along the path. length = m_kk units are 1/units(s). if s is a physical coordinate then the units are 1/m.
Reimplemented in RedlichKisterVPSSTP, MargulesVPSSTP, and IonsFromNeutralVPSSTP.
Definition at line 1763 of file ThermoPhase.h.
Referenced by IonsFromNeutralVPSSTP::getdlnActCoeffds().
getdlnActCoeffdlnX_diag()
virtual void getdlnActCoeffdlnX_diag (doublereal * dlnActCoeffdlnX_diag) const inline virtual
Get the array of ln mole fraction derivatives of the log activity coefficients - diagonal component only.
For ideal mixtures (unity activity coefficients), this can return zero. Implementations should take the derivative of the logarithm of the activity coefficient with respect to the logarithm of the mole fraction variable that represents the standard state. This quantity is to be used in conjunction with derivatives of that mole fraction variable when the derivative of the chemical potential is taken.
units = dimensionless
Parameters
dlnActCoeffdlnX_diag Output vector of derivatives of the log Activity Coefficients wrt the mole fractions. length = m_kk
Reimplemented in RedlichKisterVPSSTP, MargulesVPSSTP, and IonsFromNeutralVPSSTP.
Definition at line 1783 of file ThermoPhase.h.
Referenced by IonsFromNeutralVPSSTP::s_update_dlnActCoeff_dlnX_diag().
getdlnActCoeffdlnN_diag()
virtual void getdlnActCoeffdlnN_diag (doublereal * dlnActCoeffdlnN_diag) const inline virtual
Get the array of log species mole number derivatives of the log activity coefficients.
For ideal mixtures (unity activity coefficients), this can return zero. Implementations should take the derivative of the logarithm of the activity coefficient with respect to the logarithm of the concentration- like variable (i.e. moles) that represents the standard state. This quantity is to be used in conjunction with derivatives of that species mole number variable when the derivative of the chemical potential is taken.
units = dimensionless
Parameters
dlnActCoeffdlnN_diag Output vector of derivatives of the log Activity Coefficients. length = m_kk
Reimplemented in VPStandardStateTP, RedlichKisterVPSSTP, MixtureFugacityTP, MargulesVPSSTP, and IonsFromNeutralVPSSTP.
Definition at line 1803 of file ThermoPhase.h.
getdlnActCoeffdlnN()
void getdlnActCoeffdlnN (const size_t ld, doublereal *const dlnActCoeffdlnN) virtual
Get the array of derivatives of the log activity coefficients with respect to the log of the species mole numbers.
Implementations should take the derivative of the logarithm of the activity coefficient with respect to a species log mole number (with all other species mole numbers held constant). The default treatment in the ThermoPhase object is to set this vector to zero.
units = 1 / kmol
dlnActCoeffdlnN[ ld * k + m] will contain the derivative of log act_coeff for the m-th species with respect to the number of moles of the k-th species.
\[ \frac{d \ln(\gamma_m) }{d \ln(n_k) }\Bigg|_{n_i} \]
Parameters
ld Number of rows in the matrix
dlnActCoeffdlnN Output vector of derivatives of the log Activity Coefficients. length = m_kk * m_kk
Reimplemented in RedlichKisterVPSSTP, MolalityVPSSTP, MargulesVPSSTP, IonsFromNeutralVPSSTP, and GibbsExcessVPSSTP.
Definition at line 1271 of file ThermoPhase.cpp.
References Phase::m_kk.
report()
std::string report (bool show_thermo = true, doublereal threshold = -1e-14) const virtual
returns a summary of the state of the phase as a string
Parameters
show_thermo If true, extra information is printed out about the thermodynamic state of the system.
threshold Show information about species with mole fractions greater than threshold.
Reimplemented in PureFluidPhase, and MolalityVPSSTP.
Definition at line 1335 of file ThermoPhase.cpp.
References Phase::name().
Referenced by Cantera::operator<<().
reportCSV()
void reportCSV (std::ofstream & csvFile) const virtual
returns a summary of the state of the phase to a comma separated file.
To customize the data included in the report, derived classes should override the getCsvReportData method.
Parameters
csvFile ofstream file to print comma separated data for the phase
Definition at line 1448 of file ThermoPhase.cpp.
References ThermoPhase::getCsvReportData(), Phase::getMoleFractions(), Phase::nSpecies(), Cantera::SmallNumber, and Phase::speciesName().
getCsvReportData()
void getCsvReportData (std::vector< std::string > & names, std::vector< vector_fp > & data) const protected virtual
Fills names and data with the column names and species thermo properties to be included in the output of the reportCSV method.
Reimplemented in MolalityVPSSTP.
Definition at line 1480 of file ThermoPhase.cpp.
References ThermoPhase::getActivities(), ThermoPhase::getActivityCoefficients(), ThermoPhase::getChemPotentials(), Phase::getMassFractions(), Phase::getMoleFractions(), ThermoPhase::getPartialMolarCp(), ThermoPhase::getPartialMolarEnthalpies(), ThermoPhase::getPartialMolarEntropies(), ThermoPhase::getPartialMolarIntEnergies(), ThermoPhase::getPartialMolarVolumes(), and Phase::nSpecies().
Referenced by ThermoPhase::reportCSV().
Member Data Documentation
m_spthermo
MultiSpeciesThermo m_spthermo protected
Pointer to the calculation manager for species reference-state thermodynamic properties.
This class is called when the reference-state thermodynamic properties of all the species in the phase needs to be evaluated.
Definition at line 1870 of file ThermoPhase.h.
Referenced by MixtureFugacityTP::_updateReferenceStateThermo(), BinarySolutionTabulatedThermo::_updateThermo(), ConstDensityThermo::_updateThermo(), IdealGasPhase::_updateThermo(), IdealSolidSolnPhase::_updateThermo(), LatticePhase::_updateThermo(), SingleSpeciesTP::_updateThermo(), SurfPhase::_updateThermo(), ThermoPhase::addSpecies(), VPStandardStateTP::addSpecies(), ThermoPhase::Hf298SS(), ThermoPhase::initThermo(), ThermoPhase::maxTemp(), ThermoPhase::minTemp(), ThermoPhase::modifyOneHf298SS(), ThermoPhase::modifySpecies(), ThermoPhase::refPressure(), ThermoPhase::resetHf298(), and ThermoPhase::speciesThermo().
m_input
AnyMap m_input protected
Data supplied via setParameters.
When first set, this may include parameters used by different phase models when initThermo() is called.
Definition at line 1874 of file ThermoPhase.h.
Referenced by BinarySolutionTabulatedThermo::initThermo(), ConstDensityThermo::initThermo(), DebyeHuckel::initThermo(), FixedChemPotSSTP::initThermo(), HMWSoln::initThermo(), IdealMolalSoln::initThermo(), IdealSolidSolnPhase::initThermo(), IdealSolnGasVPSS::initThermo(), IonsFromNeutralVPSSTP::initThermo(), LatticePhase::initThermo(), LatticeSolidPhase::initThermo(), MargulesVPSSTP::initThermo(), MetalPhase::initThermo(), PureFluidPhase::initThermo(), RedlichKisterVPSSTP::initThermo(), StoichSubstance::initThermo(), SurfPhase::initThermo(), ThermoPhase::input(), and ThermoPhase::setParameters().
m_speciesData
std::vector<const XML_Node*> m_speciesData protected
Vector of pointers to the species databases.
This is used to access data needed to construct the transport manager and other properties later in the initialization process. We create a copy of the XML_Node data read in here. Therefore, we own this data.
Deprecated:
The XML input format is deprecated and will be removed in Cantera 3.0.
Definition at line 1885 of file ThermoPhase.h.
Referenced by ThermoPhase::saveSpeciesData(), and ThermoPhase::speciesData().
m_phi
doublereal m_phi protected
Stored value of the electric potential for this phase. Units are Volts.
Definition at line 1888 of file ThermoPhase.h.
Referenced by ThermoPhase::electricPotential(), and ThermoPhase::setElectricPotential().
m_chargeNeutralityNecessary
bool m_chargeNeutralityNecessary protected
Boolean indicating whether a charge neutrality condition is a necessity.
Note, the charge neutrality condition is not a necessity for ideal gas phases. There may be a net charge in those phases, because the NASA polynomials for ionized species in Ideal gases take this condition into account. However, liquid phases usually require charge neutrality in order for their derived thermodynamics to be valid.
Definition at line 1898 of file ThermoPhase.h.
Referenced by ThermoPhase::chargeNeutralityNecessary(), and MolalityVPSSTP::MolalityVPSSTP().
m_ssConvention
int m_ssConvention protected
Contains the standard state convention.
Definition at line 1901 of file ThermoPhase.h.
Referenced by ThermoPhase::standardStateConvention().
m_tlast
doublereal m_tlast mutable protected
last value of the temperature processed by reference state
Definition at line 1904 of file ThermoPhase.h.
Referenced by VPStandardStateTP::_updateStandardStateThermo(), BinarySolutionTabulatedThermo::_updateThermo(), ConstDensityThermo::_updateThermo(), IdealSolidSolnPhase::_updateThermo(), LatticePhase::_updateThermo(), LatticeSolidPhase::_updateThermo(), SingleSpeciesTP::_updateThermo(), SurfPhase::_updateThermo(), FixedChemPotSSTP::FixedChemPotSSTP(), ThermoPhase::invalidateCache(), and VPStandardStateTP::updateStandardStateThermo().
The documentation for this class was generated from the following files:
ThermoPhase.h
ThermoPhase.cpp