Cantera: MultiTransport Class Reference
MultiTransport Class Reference
Models of Phases of Matter » Transport Properties for Species in Phases
Class MultiTransport implements multicomponent transport properties for ideal gas mixtures.
#include <MultiTransport.h>
Public Member Functions
MultiTransport (thermo_t *thermo=0)
default constructor
virtual std::string transportType () const
Identifies the Transport object type.
virtual void getThermalDiffCoeffs (doublereal *const dt)
Return the thermal diffusion coefficients (kg/m/s)
virtual doublereal thermalConductivity ()
Returns the mixture thermal conductivity in W/m/K.
virtual void getMultiDiffCoeffs (const size_t ld, doublereal *const d)
Return the Multicomponent diffusion coefficients. Units: [m^2/s].
virtual void getSpeciesFluxes (size_t ndim, const doublereal *const grad_T, size_t ldx, const doublereal *const grad_X, size_t ldf, doublereal *const fluxes)
Get the species diffusive mass fluxes wrt to the mass averaged velocity, given the gradients in mole fraction and temperature.
virtual void getMolarFluxes (const doublereal *const state1, const doublereal *const state2, const doublereal delta, doublereal *const fluxes)
Get the molar diffusional fluxes [kmol/m^2/s] of the species, given the thermodynamic state at two nearby points.
virtual void getMassFluxes (const doublereal *state1, const doublereal *state2, doublereal delta, doublereal *fluxes)
Get the mass diffusional fluxes [kg/m^2/s] of the species, given the thermodynamic state at two nearby points.
virtual void init (ThermoPhase *thermo, int mode=0, int log_level=0)
Initialize a transport manager.
Public Member Functions inherited from GasTransport
virtual doublereal viscosity ()
Viscosity of the mixture (kg /m /s)
virtual void getSpeciesViscosities (doublereal *const visc)
Get the pure-species viscosities.
virtual void getBinaryDiffCoeffs (const size_t ld, doublereal *const d)
Returns the matrix of binary diffusion coefficients.
virtual void getMixDiffCoeffs (doublereal *const d)
Returns the Mixture-averaged diffusion coefficients [m^2/s].
virtual void getMixDiffCoeffsMole (doublereal *const d)
Returns the mixture-averaged diffusion coefficients [m^2/s].
virtual void getMixDiffCoeffsMass (doublereal *const d)
Returns the mixture-averaged diffusion coefficients [m^2/s].
Public Member Functions inherited from Transport
Transport (thermo_t *thermo=0, size_t ndim=1)
Constructor.
Transport (const Transport &)=delete
Transport & operator= (const Transport &)=delete
thermo_t & thermo ()
bool ready ()
void setNDim (const int ndim)
Set the number of dimensions to be expected in flux expressions.
size_t nDim () const
Return the number of dimensions in flux expressions.
void checkSpeciesIndex (size_t k) const
Check that the specified species index is in range.
void checkSpeciesArraySize (size_t kk) const
Check that an array size is at least nSpecies().
virtual doublereal getElectricConduct ()
Compute the mixture electrical conductivity (S m-1) at the current conditions of the phase (Siemens m-1)
virtual void getElectricCurrent (int ndim, const doublereal *grad_T, int ldx, const doublereal *grad_X, int ldf, const doublereal *grad_V, doublereal *current)
Compute the electric current density in A/m^2.
virtual void getSpeciesFluxesES (size_t ndim, const doublereal *grad_T, size_t ldx, const doublereal *grad_X, size_t ldf, const doublereal *grad_Phi, doublereal *fluxes)
Get the species diffusive mass fluxes wrt to the mass averaged velocity, given the gradients in mole fraction, temperature and electrostatic potential.
virtual void getSpeciesVdiff (size_t ndim, const doublereal *grad_T, int ldx, const doublereal *grad_X, int ldf, doublereal *Vdiff)
Get the species diffusive velocities wrt to the mass averaged velocity, given the gradients in mole fraction and temperature.
virtual void getSpeciesVdiffES (size_t ndim, const doublereal *grad_T, int ldx, const doublereal *grad_X, int ldf, const doublereal *grad_Phi, doublereal *Vdiff)
Get the species diffusive velocities wrt to the mass averaged velocity, given the gradients in mole fraction, temperature, and electrostatic potential.
virtual void setParameters (const int type, const int k, const doublereal *const p)
Set model parameters for derived classes.
void setVelocityBasis (VelocityBasis ivb)
Sets the velocity basis.
VelocityBasis getVelocityBasis () const
Gets the velocity basis.
virtual doublereal bulkViscosity ()
The bulk viscosity in Pa-s.
virtual doublereal ionConductivity ()
The ionic conductivity in 1/ohm/m.
virtual void getSpeciesIonConductivity (doublereal *const ionCond)
Returns the pure species ionic conductivity.
virtual void mobilityRatio (double *mobRat)
Returns the pointer to the mobility ratios of the species in the phase.
virtual void getSpeciesMobilityRatio (double **mobRat)
Returns the pure species limit of the mobility ratios.
virtual void selfDiffusion (doublereal *const selfDiff)
Returns the self diffusion coefficients of the species in the phase.
virtual void getSpeciesSelfDiffusion (double **selfDiff)
Returns the pure species self diffusion in solution of each species.
virtual doublereal electricalConductivity ()
The electrical conductivity (Siemens/m).
virtual void getMobilities (doublereal *const mobil_e)
Get the Electrical mobilities (m^2/V/s).
virtual void getFluidMobilities (doublereal *const mobil_f)
Get the fluid mobilities (s kmol/kg).
virtual bool initLiquid (LiquidTransportParams &tr)
Called by TransportFactory to set parameters.
virtual bool initSolid (SolidTransportData &tr)
Called by TransportFactory to set parameters.
virtual void setThermo (thermo_t &thermo)
Specifies the ThermoPhase object.
Protected Member Functions
void update_T ()
Update basic temperature-dependent quantities if the temperature has changed.
void update_C ()
Update basic concentration-dependent quantities if the concentrations have changed.
void updateThermal_T ()
Update the temperature-dependent terms needed to compute the thermal conductivity and thermal diffusion coefficients.
void correctBinDiffCoeffs ()
void eval_L0000 (const doublereal *const x)
Evaluate the L0000 matrices.
void eval_L0010 (const doublereal *const x)
Evaluate the L0010 matrices.
void eval_L1000 ()
Evaluate the L1000 matrices.
void eval_L0100 ()
void eval_L0001 ()
void eval_L1010 (const doublereal *x)
void eval_L1001 (const doublereal *x)
void eval_L0110 ()
void eval_L0101 (const doublereal *x)
bool hasInternalModes (size_t j)
doublereal pressure_ig ()
virtual void solveLMatrixEquation ()
Protected Member Functions inherited from GasTransport
GasTransport (ThermoPhase *thermo=0)
virtual void updateViscosity_T ()
Update the temperature-dependent viscosity terms.
virtual void updateSpeciesViscosities ()
Update the pure-species viscosities.
virtual void updateDiff_T ()
Update the binary diffusion coefficients.
virtual void setupCollisionParameters ()
Setup parameters for a new kinetic-theory-based transport manager for low-density gases.
void setupCollisionIntegral ()
Setup range for polynomial fits to collision integrals of Monchick & Mason.
void getTransportData ()
Read the transport database.
void makePolarCorrections (size_t i, size_t j, doublereal &f_eps, doublereal &f_sigma)
Corrections for polar-nonpolar binary diffusion coefficients.
void fitCollisionIntegrals (MMCollisionInt &integrals)
Generate polynomial fits to collision integrals.
virtual void fitProperties (MMCollisionInt &integrals)
Generate polynomial fits to the viscosity and conductivity.
virtual void fitDiffCoeffs (MMCollisionInt &integrals)
Generate polynomial fits to the binary diffusion coefficients.
void getBinDiffCorrection (doublereal t, MMCollisionInt &integrals, size_t k, size_t j, doublereal xk, doublereal xj, doublereal &fkj, doublereal &fjk)
Second-order correction to the binary diffusion coefficients.
Protected Member Functions inherited from Transport
void finalize ()
Enable the transport object for use.
Protected Attributes
doublereal m_thermal_tlast
DenseMatrix m_astar
Dense matrix for astar.
DenseMatrix m_bstar
Dense matrix for bstar.
DenseMatrix m_cstar
Dense matrix for cstar.
DenseMatrix m_om22
Dense matrix for omega22.
vector_fp m_cinternal
vector_fp m_sqrt_eps_k
DenseMatrix m_log_eps_k
vector_fp m_frot_298
vector_fp m_rotrelax
doublereal m_lambda
DenseMatrix m_Lmatrix
DenseMatrix m_aa
vector_fp m_a
vector_fp m_b
vector_fp m_spwork1
vector_fp m_spwork2
vector_fp m_spwork3
vector_fp m_molefracs_last
Mole fraction vector from last L-matrix evaluation.
bool m_abc_ok
Boolean indicating viscosity is up to date.
bool m_l0000_ok
bool m_lmatrix_soln_ok
DenseMatrix incl
bool m_debug
Protected Attributes inherited from GasTransport
vector_fp m_molefracs
Vector of species mole fractions.
doublereal m_viscmix
Internal storage for the viscosity of the mixture (kg /m /s)
bool m_visc_ok
Update boolean for mixture rule for the mixture viscosity.
bool m_viscwt_ok
Update boolean for the weighting factors for the mixture viscosity.
bool m_spvisc_ok
Update boolean for the species viscosities.
bool m_bindiff_ok
Update boolean for the binary diffusivities at unit pressure.
int m_mode
Type of the polynomial fits to temperature.
DenseMatrix m_phi
m_phi is a Viscosity Weighting Function. size = m_nsp * n_nsp
vector_fp m_spwork
work space length = m_kk
vector_fp m_visc
vector of species viscosities (kg /m /s).
std::vector< vector_fp > m_visccoeffs
Polynomial fits to the viscosity of each species.
vector_fp m_mw
Local copy of the species molecular weights.
DenseMatrix m_wratjk
Holds square roots of molecular weight ratios.
DenseMatrix m_wratkj1
Holds square roots of molecular weight ratios.
vector_fp m_sqvisc
vector of square root of species viscosities sqrt(kg /m /s).
vector_fp m_polytempvec
Powers of the ln temperature, up to fourth order.
doublereal m_temp
Current value of the temperature at which the properties in this object are calculated (Kelvin).
doublereal m_kbt
Current value of Boltzmann constant times the temperature (Joules)
doublereal m_sqrt_kbt
current value of Boltzmann constant times the temperature.
doublereal m_sqrt_t
current value of temperature to 1/2 power
doublereal m_logt
Current value of the log of the temperature.
doublereal m_t14
Current value of temperature to 1/4 power.
doublereal m_t32
Current value of temperature to the 3/2 power.
std::vector< vector_fp > m_diffcoeffs
Polynomial fits to the binary diffusivity of each species.
DenseMatrix m_bdiff
Matrix of binary diffusion coefficients at the reference pressure and the current temperature Size is nsp x nsp.
std::vector< vector_fp > m_condcoeffs
temperature fits of the heat conduction
std::vector< vector_int > m_poly
Indices for the (i,j) interaction in collision integral fits.
std::vector< vector_fp > m_omega22_poly
Fit for omega22 collision integral.
std::vector< vector_fp > m_astar_poly
Fit for astar collision integral.
std::vector< vector_fp > m_bstar_poly
Fit for bstar collision integral.
std::vector< vector_fp > m_cstar_poly
Fit for cstar collision integral.
vector_fp m_zrot
Rotational relaxation number for each species.
vector_fp m_crot
Dimensionless rotational heat capacity of each species.
std::vector< bool > m_polar
Vector of booleans indicating whether a species is a polar molecule.
vector_fp m_alpha
Polarizability of each species in the phase.
vector_fp m_eps
Lennard-Jones well-depth of the species in the current phase.
vector_fp m_sigma
Lennard-Jones diameter of the species in the current phase.
DenseMatrix m_reducedMass
This is the reduced mass of the interaction between species i and j.
DenseMatrix m_diam
hard-sphere diameter for (i,j) collision
DenseMatrix m_epsilon
The effective well depth for (i,j) collisions.
DenseMatrix m_dipole
The effective dipole moment for (i,j) collisions.
DenseMatrix m_delta
Reduced dipole moment of the interaction between two species.
vector_fp m_w_ac
Pitzer acentric factor.
vector_fp m_disp
Dispersion coefficient.
vector_fp m_quad_polar
Quadrupole polarizability.
int m_log_level
Level of verbose printing during initialization.
Protected Attributes inherited from Transport
thermo_t * m_thermo
pointer to the object representing the phase
bool m_ready
true if finalize has been called
size_t m_nsp
Number of species.
size_t m_nDim
Number of dimensions used in flux expressions.
int m_velocityBasis
Velocity basis from which diffusion velocities are computed.
Detailed Description
Class MultiTransport implements multicomponent transport properties for ideal gas mixtures.
The implementation generally follows the procedure outlined in: R. J. Kee, M. J. Coltrin, and P. Glarborg, "Chemically Reacting Flow: Theory & Practice", John Wiley & Sons, 2003.
Definition at line 26 of file MultiTransport.h.
Constructor & Destructor Documentation
MultiTransport()
MultiTransport (thermo_t * thermo = 0)
default constructor
Parameters
thermo Optional parameter for the pointer to the ThermoPhase object
Definition at line 36 of file MultiTransport.cpp.
Member Function Documentation
transportType()
virtual std::string transportType () const inline virtual
Identifies the Transport object type.
Each derived class should override this method to return a meaningful identifier.
Reimplemented from Transport.
Reimplemented in HighPressureGasTransport.
Definition at line 35 of file MultiTransport.h.
References GasTransport::m_mode.
getThermalDiffCoeffs()
void getThermalDiffCoeffs (doublereal *const dt) virtual
Return the thermal diffusion coefficients (kg/m/s)
Eqn. (12.126) displays how they are calculated. The reference work is from Dixon-Lewis.
Eqns. (12.168) shows how they are used in an expression for the species flux.
Parameters
dt Vector of thermal diffusion coefficients. Units = kg/m/s
Reimplemented from Transport.
Reimplemented in HighPressureGasTransport.
Definition at line 100 of file MultiTransport.cpp.
References Cantera::GasConstant, GasTransport::m_molefracs, GasTransport::m_mw, and Transport::m_nsp.
Referenced by MultiTransport::getMassFluxes(), and MultiTransport::getSpeciesFluxes().
thermalConductivity()
doublereal thermalConductivity () virtual
Returns the mixture thermal conductivity in W/m/K.
Units are in W / m K or equivalently kg m / s3 K
Returns
thermal conductivity in W/m/K.
Reimplemented from Transport.
Reimplemented in HighPressureGasTransport.
Definition at line 90 of file MultiTransport.cpp.
References Transport::m_nsp.
getMultiDiffCoeffs()
void getMultiDiffCoeffs (const size_t ld, doublereal *const d) virtual
Return the Multicomponent diffusion coefficients. Units: [m^2/s].
If the transport manager implements a multicomponent diffusion model, then this method returns the array of multicomponent diffusion coefficients. Otherwise it throws an exception.
Parameters
[in] ld The dimension of the inner loop of d (usually equal to m_nsp)
[out] d flat vector of diffusion coefficients, fortran ordering. d[ld*j+i] is the D_ij diffusion coefficient (the diffusion coefficient for species i due to species j).
Reimplemented from Transport.
Reimplemented in HighPressureGasTransport.
Definition at line 351 of file MultiTransport.cpp.
References MultiTransport::eval_L0000(), Cantera::invert(), GasTransport::m_molefracs, GasTransport::m_mw, Transport::m_nsp, GasTransport::m_temp, Transport::m_thermo, Phase::meanMolecularWeight(), MultiTransport::update_C(), MultiTransport::update_T(), and MultiTransport::updateThermal_T().
getSpeciesFluxes()
void getSpeciesFluxes (size_t ndim, const doublereal *const grad_T, size_t ldx, const doublereal *const grad_X, size_t ldf, doublereal *const fluxes) virtual
Get the species diffusive mass fluxes wrt to the mass averaged velocity, given the gradients in mole fraction and temperature.
Units for the returned fluxes are kg m-2 s-1.
Parameters
ndim Number of dimensions in the flux expressions
grad_T Gradient of the temperature (length = ndim)
ldx Leading dimension of the grad_X array. (usually equal to m_nsp but not always)
grad_X Gradients of the mole fraction. Flat vector with the m_nsp in the inner loop. length = ldx * ndim
ldf Leading dimension of the fluxes array. (usually equal to m_nsp but not always)
fluxes Output of the diffusive mass fluxes. Flat vector with the m_nsp in the inner loop. length = ldx * ndim
Reimplemented from Transport.
Definition at line 166 of file MultiTransport.cpp.
References Phase::density(), MultiTransport::getThermalDiffCoeffs(), GasTransport::m_bdiff, GasTransport::m_molefracs, Transport::m_nsp, GasTransport::m_spwork, GasTransport::m_temp, Transport::m_thermo, Phase::massFractions(), Cantera::solve(), MultiTransport::update_T(), and GasTransport::updateDiff_T().
getMolarFluxes()
void getMolarFluxes (const doublereal *const state1, const doublereal *const state2, const doublereal delta, doublereal *const fluxes) virtual
Get the molar diffusional fluxes [kmol/m^2/s] of the species, given the thermodynamic state at two nearby points.
The molar diffusional fluxes are calculated with reference to the mass averaged velocity. This is a one-dimensional vector
Parameters
state1 Array of temperature, density, and mass fractions for state 1.
state2 Array of temperature, density, and mass fractions for state 2.
delta Distance from state 1 to state 2 (m).
fluxes Output molar fluxes of the species. (length = m_nsp)
Reimplemented from Transport.
Definition at line 340 of file MultiTransport.cpp.
References MultiTransport::getMassFluxes(), GasTransport::m_mw, Transport::m_thermo, and Phase::nSpecies().
getMassFluxes()
void getMassFluxes (const doublereal * state1, const doublereal * state2, doublereal delta, doublereal * fluxes) virtual
Get the mass diffusional fluxes [kg/m^2/s] of the species, given the thermodynamic state at two nearby points.
The specific diffusional fluxes are calculated with reference to the mass averaged velocity. This is a one-dimensional vector
Parameters
state1 Array of temperature, density, and mass fractions for state 1.
state2 Array of temperature, density, and mass fractions for state 2.
delta Distance from state 1 to state 2 (m).
fluxes Output mass fluxes of the species. (length = m_nsp)
Reimplemented from Transport.
Definition at line 252 of file MultiTransport.cpp.
References Phase::density(), Phase::getMoleFractions(), MultiTransport::getThermalDiffCoeffs(), GasTransport::m_bdiff, GasTransport::m_molefracs, Transport::m_nsp, GasTransport::m_spwork, GasTransport::m_temp, Transport::m_thermo, Phase::massFractions(), Phase::nSpecies(), ThermoPhase::pressure(), Phase::restoreState(), ThermoPhase::setState_TPX(), Cantera::solve(), MultiTransport::update_T(), and GasTransport::updateDiff_T().
Referenced by MultiTransport::getMolarFluxes().
init()
void init (ThermoPhase * thermo, int mode = 0, int log_level = 0) virtual
Initialize a transport manager.
This routine sets up a transport manager. It calculates the collision integrals and populates species-dependent data structures.
Parameters
thermo Pointer to the ThermoPhase object
mode Chemkin compatible mode or not. This alters the specification of the collision integrals. defaults to no.
log_level Defaults to zero, no logging
Reimplemented from GasTransport.
Definition at line 41 of file MultiTransport.cpp.
References Cantera::Boltzmann, Cantera::Frot(), GasTransport::init(), MultiTransport::m_abc_ok, MultiTransport::m_astar, MultiTransport::m_bstar, MultiTransport::m_cstar, GasTransport::m_eps, GasTransport::m_epsilon, MultiTransport::m_molefracs_last, Transport::m_nsp, MultiTransport::m_om22, DenseMatrix::resize(), and Transport::thermo().
update_T()
void update_T () protected virtual
Update basic temperature-dependent quantities if the temperature has changed.
Reimplemented from GasTransport.
Definition at line 388 of file MultiTransport.cpp.
References MultiTransport::m_abc_ok, Transport::m_nsp, GasTransport::m_temp, Transport::m_thermo, Phase::nSpecies(), and Phase::temperature().
Referenced by HighPressureGasTransport::getBinaryDiffCoeffs(), MultiTransport::getMassFluxes(), MultiTransport::getMultiDiffCoeffs(), HighPressureGasTransport::getMultiDiffCoeffs(), MultiTransport::getSpeciesFluxes(), and HighPressureGasTransport::thermalConductivity().
update_C()
void update_C () protected virtual
Update basic concentration-dependent quantities if the concentrations have changed.
Implements GasTransport.
Definition at line 401 of file MultiTransport.cpp.
References Phase::getMoleFractions(), GasTransport::m_molefracs, MultiTransport::m_molefracs_last, Transport::m_nsp, Transport::m_thermo, and Cantera::Tiny.
Referenced by MultiTransport::getMultiDiffCoeffs(), and HighPressureGasTransport::getMultiDiffCoeffs().
updateThermal_T()
void updateThermal_T () protected
Update the temperature-dependent terms needed to compute the thermal conductivity and thermal diffusion coefficients.
Definition at line 418 of file MultiTransport.cpp.
References Cantera::Frot(), Cantera::GasConstant, ThermoPhase::getCp_R_ref(), MultiTransport::m_abc_ok, MultiTransport::m_astar, GasTransport::m_astar_poly, GasTransport::m_bdiff, MultiTransport::m_bstar, GasTransport::m_bstar_poly, MultiTransport::m_cstar, GasTransport::m_cstar_poly, GasTransport::m_eps, GasTransport::m_kbt, GasTransport::m_logt, GasTransport::m_mode, GasTransport::m_mw, Transport::m_nsp, MultiTransport::m_om22, GasTransport::m_omega22_poly, GasTransport::m_poly, GasTransport::m_sqrt_t, GasTransport::m_temp, Transport::m_thermo, GasTransport::m_visc, GasTransport::m_zrot, Phase::nSpecies(), Cantera::poly6(), Cantera::poly8(), Phase::temperature(), GasTransport::updateDiff_T(), and GasTransport::updateSpeciesViscosities().
Referenced by MultiTransport::getMultiDiffCoeffs(), and HighPressureGasTransport::getMultiDiffCoeffs().
eval_L0000()
void eval_L0000 (const doublereal *const x) protected
Evaluate the L0000 matrices.
Evaluate the upper-left block of the L matrix.
Parameters
x vector of species mole fractions
Definition at line 488 of file MultiTransport.cpp.
References GasTransport::m_bdiff, GasTransport::m_mw, Transport::m_nsp, and GasTransport::m_temp.
Referenced by MultiTransport::getMultiDiffCoeffs(), and HighPressureGasTransport::getMultiDiffCoeffs().
eval_L0010()
void eval_L0010 (const doublereal *const x) protected
Evaluate the L0010 matrices.
Parameters
x vector of species mole fractions
Definition at line 510 of file MultiTransport.cpp.
References GasTransport::m_bdiff, MultiTransport::m_cstar, GasTransport::m_mw, Transport::m_nsp, and GasTransport::m_temp.
eval_L1000()
void eval_L1000 () protected
Evaluate the L1000 matrices.
Definition at line 530 of file MultiTransport.cpp.
References Transport::m_nsp.
Member Data Documentation
m_astar
DenseMatrix m_astar protected
Dense matrix for astar.
Definition at line 128 of file MultiTransport.h.
Referenced by MultiTransport::init(), and MultiTransport::updateThermal_T().
m_bstar
DenseMatrix m_bstar protected
Dense matrix for bstar.
Definition at line 131 of file MultiTransport.h.
Referenced by MultiTransport::init(), and MultiTransport::updateThermal_T().
m_cstar
DenseMatrix m_cstar protected
Dense matrix for cstar.
Definition at line 134 of file MultiTransport.h.
Referenced by MultiTransport::eval_L0010(), MultiTransport::init(), and MultiTransport::updateThermal_T().
m_om22
DenseMatrix m_om22 protected
Dense matrix for omega22.
Definition at line 137 of file MultiTransport.h.
Referenced by MultiTransport::init(), and MultiTransport::updateThermal_T().
m_molefracs_last
vector_fp m_molefracs_last protected
Mole fraction vector from last L-matrix evaluation.
Definition at line 158 of file MultiTransport.h.
Referenced by MultiTransport::init(), and MultiTransport::update_C().
m_abc_ok
bool m_abc_ok protected
Boolean indicating viscosity is up to date.
Definition at line 163 of file MultiTransport.h.
Referenced by MultiTransport::init(), MultiTransport::update_T(), and MultiTransport::updateThermal_T().
The documentation for this class was generated from the following files:
MultiTransport.h
MultiTransport.cpp